### ISSUE TITLE
Support Google Maps API for geocoding

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#10]
**As a User, I want to have the option to use Google Maps instead of OpenStreetMap, so I have the best experience.**

Right now, only OpenStreetMap is supported / used (just the reverse lookup API, not the UI).

Acceptance Criteria:
- [ ] Add helpful information to our [Developer Guide](https://github.com/photoprism/photoprism/wiki/Geocoding), Geocoding is just a stub right now
- [ ] Change DB structure: We use the Place IDs of OpenStreetMap as location ID right now
- [ ] Caching should also be improved to reduce load on API and improve indexing performance
- [ ] Implement config option / parameters to configure OpenStreetMap and Google Maps (API key?)
- [ ] Check license issues, maybe we can get a special license from Google as we are Open Source?

**Comment by devzsolt** [comment]
From the perspective of privacy and freedom we should stick to openstreetmap. Google has several limitations that can even change... and a self-hosted app imho shouldn't call a closed source for-profit SaaS.

**Comment by lastzero** [comment]
Privacy, freedom and quality 😉 Google simply has the best maps implementation right now...

**Comment by lastzero** [comment]
Apparently OpenStreetMap has much greater location / object detail than Google Maps.

**Comment by lastzero** [comment]
We use https://github.com/photoprism/photoprism-places now, can be closed.
