### ISSUE TITLE
Docker: Disable chown in entrypoint script

### ISSUE THREAD

**Issue by alex-phillips** [photoprism/photoprism#1000]
After indexing my entire library, the docker container takes an enormous amount of time to startup related to the chown command that is part of the startup process. Because my library is large, this is taking forever due to all of the cache and sidecar files. These files, however, I doubt ever change ownership. Can this be disabled? Or can we incorporate a flag to manually disable this step?

**Comment by lastzero** [comment]
Sure, this should only happen if you set / change the UID and/or GUI using environment variables:

https://github.com/photoprism/photoprism/blob/develop/docker/entrypoint.sh

You may set the user and group directly via Docker without using the environment variables. In addition, we may add yet another environment flag to disable chown.

**Comment by alex-phillips** [comment]
@lastzero I am setting the UID / GID via environment variables since other containers / applications touch these file as well. It is read-only though, so is that necessary as long as global has read access on the files? If that's the case, I can remove the env variables and no longer have this issue.

**Comment by lastzero** [comment]
You may set a user in docker-compose.yml as well, so you don't even need global read permissions:

https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by lastzero** [comment]
We might be able to limit chmod to the storage path if that helps? My fear is that people set a new user and don't know how to change permissions accordingly.

**Comment by lastzero** [comment]
@alex-phillips Let us know if this works for you :+1:
