### ISSUE TITLE
Docs: German Translation

### ISSUE THREAD

**Issue by step21** [photoprism/photoprism#1001]
I showed photoprism to my dad, he liked it but asked if there was a German translation of the documentation.
As far as I can see, there is not. I would help with it, if possible.

**Comment by graciousgrey** [comment]
We are already working on it. It just does not have the highest priority at the moment.
https://github.com/photoprism/photoprism-docs-de

**Comment by step21** [comment]
cool thanks. no worries.

**Comment by mirisbowring** [comment]
@lastzero How can one help you with the translation? I saw that you added the tag `help wanted`.

**Comment by graciousgrey** [comment]
@mirisbowring We already started with the translation, but could not constantly work on it due to other priorities. 
What would help a lot is comparing what we already have (https://github.com/photoprism/photoprism-docs-de) with the english version to find out what's missing or what was updated + proof reading.

**Comment by mirisbowring** [comment]
How are you expecting feedback?
Should I write it down here? Make an Issue in de docs repo?

Are you accepting Pull Requests for newly translated pages / chapters?

**Comment by graciousgrey** [comment]
Feel free to create pull requests for changes or new pages :) 
In case you have any questions or additional feedback, you can write an email to hello@photoprism.app.

At the moment we only want to translate the user guide part, not the developer guide or getting started.

**Comment by graciousgrey** [comment]
Proofreading can be done here: https://docs.photoprism.de/ :)
