### ISSUE TITLE
Feature: External database

### ISSUE THREAD

**Issue by hcsaustrup** [photoprism/photoprism#1003]
The ability to use an external database (PostgreSQL, CockroachDB etc.) would be awesome, and speed things up considerably, especially when importing and during heavy use by multiple users.

Please consider this :-)

**Comment by alexislefebvre** [comment]
It looks like PostgreSQL is already supported: https://github.com/photoprism/photoprism/blob/develop/docker-compose.postgres.yml

**Comment by lastzero** [comment]
MySQL compatible databases are supported, we recommend MariaDB.

PostgreSQL is not supported yet, for more info on this see: https://github.com/photoprism/photoprism/issues/47
