### ISSUE TITLE
Feature: Background processing of new photos

### ISSUE THREAD

**Issue by hcsaustrup** [photoprism/photoprism#1007]
While PhotoPrism looks and feels awesome, it completely locks down while importing images. I'm running it on a Ryzen 5 1600 processor with 6 cores, and it becomes completely unresponsive and refuses login until the import is finished. While this could perhaps be due to locking issues with the SQLite database, I suspect the reason is that it's running a lot of very cool image processing stuff during the import.

While that's awesome, I see no reason why this couldn't be applied to the photos later, at low priority. Smack on a "Queued for post processing" label, and people know why the meta data isn't 100% yet.

**Comment by lastzero** [comment]
You may reduce the number of workers to reduce system load. Also, SQLite is really much slower and needs much more CPU than MariaDB.

**Comment by lastzero** [comment]
Will this work for you so that we can close this issue?

**Comment by hcsaustrup** [comment]
I'll give MySQL a go and see if I can tweak the settings - thanks! Awesome! :-)

**Comment by lastzero** [comment]
Use MariaDB instead if you can help it, MySQL has issues with certain types of queries and they're not going to fix them.
