### ISSUE TITLE
Photoprism as standalone app

### ISSUE THREAD

**Issue by giacombum** [photoprism/photoprism#101]
Is it possible to obtain Photoprism as a standalone app to be installed on any linux or freebsd system (I'm thinking about FreeNAS)?

**Comment by lastzero** [comment]
Yes, we're working on this although progress is slow at the moment. See Wiki for more information: https://github.com/photoprism/photoprism/wiki/Distribution

**Comment by lastzero** [comment]
I'll close this since there are no more questions.
