### ISSUE TITLE
Index: Rescan doesn't remove deleted folders

### ISSUE THREAD

**Issue by maltokyo** [photoprism/photoprism#1010]
I have about 1000 folders (400k photos) in my originals directory, and I deleted (actually moved) about 200 of those to another drive which I don't want to be displayed in Photoprism.

The folders have been removed, but still show up in the gallery, including the ability to view them.

How can I remove these from Photoprism altogether?  I realize a complete rescan may work, but the first scan took about two weeks!  So I don't want to do that again..

Any advice?

**Comment by lastzero** [comment]
Regular rescan doesn't work?

**Comment by maltokyo** [comment]
Unfortunately not, I have tried it a few times, the old photos still there..

**Comment by lastzero** [comment]
Also when you manually run photoprism purge in a terminal?

**Comment by maltokyo** [comment]
oh let me see how to do this, I am only using web GUI.

**Comment by maltokyo** [comment]
I am in the docs advanced section, but cannot find CLI guide, could you please help as to where that is?
https://docs.photoprism.org/user-guide/settings/advanced/

**Comment by lastzero** [comment]
Getting Started as well as in our Docker example config file. Look for command reference.

**Comment by maltokyo** [comment]
ah, you just mean simply there is a command `photoprism purge` - sorry, I will try this.
Thank you for your help.

**Comment by maltokyo** [comment]
thank you, that finished as below, and says it deleted a bunch of things, but I can still see them in the gallery.

```
WARN[2021-02-06T19:55:07Z] photo: photo pqnd7992yynrln6m has no jpegs (set new primary) 
INFO[2021-02-06T19:55:07Z] purge: searching index for hidden media files 
INFO[2021-02-06T19:55:20Z] purge: removed 22913 files and 33500 photos in 8m12.047469537s 
INFO[2021-02-06T19:55:20Z] closed database connection  
```

That said, the machine still has a huge process running `darktable-cli` as below, so maybe it still needs time.  Ill leave it running overnight and see.

```
top - 21:22:28 up  2:48,  0 users,  load average: 18.02, 13.15, 7.19
Tasks:   5 total,   2 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s): 57.8 us, 18.5 sy,  0.0 ni, 15.5 id,  8.1 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :   7925.8 total,   5259.1 free,   2371.6 used,    295.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   5293.1 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                         
 4573 root      20   0  144016  53856  33484 R  12.6   0.7   0:00.38 darktable-cli 
```

**Comment by lastzero** [comment]
Let us know if this is a major bug we need to fix... otherwise we'll tag a new release tomorrow.

**Comment by maltokyo** [comment]
Yes, unfortunately, the photos (at least generated previews of photos) are still available, even though the folder containing them is no longer mounted in the docker at all (after docker restart).

I am mounting the originals folder on the host machine (debian10) as read-only, I am not sure if it makes a difference?  But I thought a regular rescan would detect removed photos.

How can I give you the proper logs etc, to have a look at?

**Comment by lastzero** [comment]
Do you see any errors in the log? You may also send your logs to hello@photoprism.app

@graciousgrey is going to test this again with our current preview build. It's going to be the next stable version (unless we have to fix this issue), so trying it should be safe.

**Comment by lastzero** [comment]
Might be related to readonly mode, maybe because generated JPEGs don't get removed and stay in the index...

**Comment by lastzero** [comment]
There was a similar issue recently: [Purge: Can't remove deleted TIFF files #917](https://github.com/photoprism/photoprism/issues/917)

**Comment by maltokyo** [comment]
Where are the logs stored.   I had a look in the storage mount, and cannot see.  In the database maybe?  Please let me know, and I will email to you.

In the meantime, in the storage docker volume, I can see as attached, in the sidecar folder, the folders with the red box are all completely removed in the originals directory.  But still in the sidecar files..  

![image](https://user-images.githubusercontent.com/1388507/107158633-cae04c80-698b-11eb-9a07-c8d63575ef94.png)

**Comment by maltokyo** [comment]
sorry, i thought i put a red box around the folders.  Basically, from `_queenie folder ` down to and including the  `_WIP_q` folder, these are all not existing in the originals folder.

**Comment by lastzero** [comment]
Warnings & errors are here: https://demo.photoprism.org/library/errors

All logs, incl debug and info messages, are sent to Docker... up to you where / if to store them.

**Comment by maltokyo** [comment]
There are thousands of this error in library/errors

![image](https://user-images.githubusercontent.com/1388507/107159304-645d2d80-698f-11eb-9a2a-0b5a935e89b3.png)

**Comment by maltokyo** [comment]
I have also sent the logs, as a zip file to your email above.  Please keep those private, clearly.  Thank you again for all of your help, and the great project!

**Comment by lastzero** [comment]
Maybe also try the cleanup command...

**Comment by maltokyo** [comment]
trying cleanup now, its running

**Comment by maltokyo** [comment]
Still going, will let it run overnight, have a good evening, from Switzerland ;)

**Comment by lastzero** [comment]
Just added a folder and removed it - works perfectly:

![delete](https://user-images.githubusercontent.com/301686/107181829-e6734380-69db-11eb-9a7e-faf404c1f5fe.png)

Based on this, I've decided to reduced the log level for missing primary files to info as that's what you would expect if you delete them:

![again](https://user-images.githubusercontent.com/301686/107183035-381ccd80-69de-11eb-95f6-a4c746bd9fba.png)

What database are you using? Maybe there's an issue with the query... didn't have time to look at your full logs yet.

**Comment by graciousgrey** [comment]
Works for me with sqlite and mysql. I tested in read-only mode and with webdav disabled.

**Comment by maltokyo** [comment]
Cleanup finished as follows:

```
root@790399c401d0:/photoprism# photoprism cleanup
INFO[2021-02-07T21:21:56Z] cleanup: read-only mode enabled              
INFO[2021-02-07T23:31:08Z] cleanup: removed 1895854 orphaned thumbnails and 147266 photos in 2h9m14.191996408s 
INFO[2021-02-07T23:31:08Z] closed database connection  
```

Seems to have removed a lot of entries and thumbnails, but some still do remain in the gallery.  There are however noticeably fewer photos that should not be there, but some do remain.

I start to think that my photo album just is too large?

**Comment by maltokyo** [comment]
This may also help, another screenshot of the errors section from the web GUI, you can see it is still searching for those folders starting with an underscore "_" which simply do not exist in the originals folder anymore:

![image](https://user-images.githubusercontent.com/1388507/107196314-c8650d80-69f2-11eb-8f97-fe183b597570.png)

**Comment by lastzero** [comment]
Certainly should not happen. Try our update, just released:

https://docs.photoprism.org/release-notes/

**Comment by maltokyo** [comment]
And, running again photoprism cleanup (without making ANY changes in the orginals directory or any other settings..  it keeps removing more still.  So, it is somehow missing to remove things on first pass.

```
root@790399c401d0:/photoprism# photoprism cleanup
INFO[2021-02-08T08:44:34Z] cleanup: read-only mode enabled              
INFO[2021-02-08T08:47:50Z] cleanup: removed 99 orphaned thumbnails and 0 photos in 3m16.769966147s 
INFO[2021-02-08T08:47:50Z] closed database connection
```

**Comment by lastzero** [comment]
Yes, maybe the list was too long so that some files have been skipped!?

**Comment by maltokyo** [comment]
ok, let me try to update and try again.  I still use photoprism/photoprism:latest right, no need for photoprism/photoprism:preview ?

**Comment by lastzero** [comment]
Yes, stable release - not the preview. Both are identical right now.

**Comment by maltokyo** [comment]
Ran cleanup again with latest version, no files removed, but the images (some, a noticeable amount) are still in my gallery ;(

```
root@db4ab5483db2:/photoprism# photoprism cleanup
INFO[2021-02-08T08:56:05Z] cleanup: read-only mode enabled              
INFO[2021-02-08T08:56:17Z] cleanup: removed 0 index entries and 0 orphan thumbnails in 13.214358801s 
INFO[2021-02-08T08:56:17Z] closed database connection  
```

**Comment by maltokyo** [comment]
Meanwhile, I confirmed the offending photos are not in here https://gallery.mydomain.com/library/files 

![image](https://user-images.githubusercontent.com/1388507/107197771-9f457c80-69f4-11eb-8c7d-02ccb386d082.png)

They are only available in the `folders` and `search` views etc, not in the originals section at all.

**Comment by lastzero** [comment]
You still didn't tell us if you're using sqlite, mariadb or mysql?

**Comment by maltokyo** [comment]
Apologies here is the entire docker-compose file, I missed that question.

```
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Linux / AMD64)
#
# Documentation : https://docs.photoprism.org/getting-started/docker-compose/
# Docker Hub URL: https://hub.docker.com/r/photoprism/photoprism/
#
# Please run behind a reverse proxy like Caddy, Traefik or Nginx if you need HTTPS / SSL support
# e.g. when running PhotoPrism on a public server outside your home network.
#
# ------------------------------------------------------------------
# DOCKER COMPOSE COMMAND REFERENCE
# ------------------------------------------------------------------
# Start    | docker-compose up -d
# Stop     | docker-compose stop
# Update   | docker-compose pull
# Logs     | docker-compose logs --tail=25 -f
# Terminal | docker-compose exec photoprism bash
# Help     | docker-compose exec photoprism photoprism help
# Config   | docker-compose exec photoprism photoprism config
# Reset    | docker-compose exec photoprism photoprism reset
# Backup   | docker-compose exec photoprism photoprism backup -a -i
# Restore  | docker-compose exec photoprism photoprism restore -a -i
# Index    | docker-compose exec photoprism photoprism index
# Reindex  | docker-compose exec photoprism photoprism index -a
# Import   | docker-compose exec photoprism photoprism import
# -------------------------------------------------------------------
# Note: All commands may have to be prefixed with "sudo" when not running as root.
#       This will change the home directory "~" to "/root" in your configuration.

services:
  photoprism_app:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:latest
    container_name: photoprism_app
    restart: unless-stopped
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "REMOVED"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_HTTP_PORT: 2342                     # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "true"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "true"             # Disable built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Users can not view or change settings
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism_mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "REMOVED"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/mnt/rWes10000/00_PhotosMaster/Lightroom_Library:/photoprism/originals:ro"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "/mnt/rWes10000/z_photoprism/storage:/photoprism/storage"

  photoprism_mariadb:
    image: mariadb:10.5
    container_name: photoprism_db
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: REMOVED
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: REMOVED

# Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
#
#  watchtower:
#    image: containrrr/watchtower
#    restart: unless-stopped
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by lastzero** [comment]
MariaDB is good... maybe we hit a result limit when building the purge lookup tables... certainly works for us, but haven't tested with 400k files yet.

**Comment by maltokyo** [comment]
Ok. Please let me know if there is anything I can help with, to test etc.

**Comment by lastzero** [comment]
Are you sure there were no duplicates of the deleted files in any of your other folders?

You can easily see the actual file names in the list view when sorting by name (full list in the edit dialog's files tab):

https://demo.photoprism.org/browse?view=list&order=name&public=true&quality=3

**Comment by maltokyo** [comment]
![image](https://user-images.githubusercontent.com/1388507/107200634-3c55e480-69f8-11eb-8be5-f9b67c814dce.png)

I am sure, in the folders directory, I can search by folder name.

This `_queenie` folder doesnt exist anymore, but is still in the folder search results.

**Comment by maltokyo** [comment]
and it is not in the originals area of PhotoPrism at all

**Comment by lastzero** [comment]
We'll get back to you when we know more... going to take look at your logs as soon as I have some time :)

**Comment by maltokyo** [comment]
I keep running cleanup and purge, multiple times successively.  They keep removing entires / thumbnails etc each run..  different numbers each time.

**Comment by maltokyo** [comment]
Final update - yes it seems there is a bug:

Running this (as below, you get the picture...) finally cleaned everything up.  Each one kept purging and cleaning files, decreasing in number each time.  Seems it could be a good old binary search issue, that the search just skips items when there are too many.

`photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup && photoprism purge && photoprism cleanup`

After 15-20 cycles of the above, above command eventually gave this outcome consistently:

```
INFO[2021-02-08T12:06:54Z] purge: searching index for hidden media files 
INFO[2021-02-08T12:07:02Z] purge: removed 0 files and 0 photos in 1m5.9222824s 
INFO[2021-02-08T12:07:02Z] closed database connection                   
INFO[2021-02-08T12:07:05Z] cleanup: read-only mode enabled              
INFO[2021-02-08T12:07:10Z] cleanup: removed 0 index entries and 0 orphan thumbnails in 6.149076047s 
INFO[2021-02-08T12:07:10Z] closed database connection  
```

**Comment by lastzero** [comment]
Purge already fetches files and photos in batches: https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/purge.go

This query might be wrong though (looks like a duplicate WHERE):

https://github.com/photoprism/photoprism/blob/9e10ba69001edcec57982c684776052bdb216f92/internal/query/photo.go#L87

**Comment by lastzero** [comment]
Started a new preview build so that you may test this if you like - although the issue seems already ~~fixed~~ solved?

https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
Tested on my own (large) photo library: Found 3 additional photos to delete 👍

**Comment by lastzero** [comment]
Folders with hidden or missing photos only should be hidden now as well.

**Comment by maltokyo** [comment]
Tested now, same result.  But I already had zero results, so I cannot confirm if it is fixed, but indeed things are solved for now for me.  Let me "delete" another folder, and try it out.  Will come back with more results soon.

**Comment by maltokyo** [comment]
Yes, it did find more, and after one purge and one cleanup they were all gone after one run of each command.  Seems this has fixed it!  Thank you!

**Comment by lastzero** [comment]
Excellent, thanks for testing!

**Comment by kevinmkr** [comment]
I just had this same issue while running the latest version of PhotoPrism through Docker on an UnRAID server, I'm sorry to say.  

MariaDB.

I had removed 66 folders consisting of 46,000 photos from my physical location.

Executing the "purge/cleanup/purge/cleanup/etc..." routine a few times eventually cleared it all out.

I'm not sure if there's anything that I can offer in terms of logs, now that it's cleaned up.  But, I can definitely suggest that, based on my experience, running purge/cleanup a single time was insufficient under these conditions.

**Comment by lastzero** [comment]
How long did you wait? Could be a caching issue that eventually resolves itself after indexing & waiting a little.

Also possible that related sidecar files were left. In that case the solution is to delete them as well, which is what happens if you use the UI to delete. Might have to implement a delete sidecar command for manually deleted originals.

**Comment by kevinmkr** [comment]
I'm a bit untrustsworthy on my memory of the timeline, to be honest, so I'm not sure if it's even of any value to speculate as to how long I waited.  It could very well have simply been the issue as you've described it with the caching.

Although, I can say that every time I executed the purge/cleanup, it DID find items (for the first few dozen iterations of those commands).  So, would that still point towards the cache?  Seems like it wouldn't.

**Comment by kevinmkr** [comment]
I can offer further information (Sorry -- missed that part in my initial read of your response):

The removal of the files occurred outsite of the UI.  I physically removed them from the file system instead of "Deleting" them from the UI.
The purge/cleanup cycles occurred in the terminal.
I DID run the re-index command from the UI a couple of times, including with the "Complete Rescan" checked.  But, again, the order of when I did what and the time in between the operations has been "purged" from my brains, unfortunately.

**Comment by lastzero** [comment]
Rather indicates a problem with orphaned sidecar files... Folders that no longer exist should be hidden / deleted. However, if sidecar entries still exist in the index, this is exactly what can prevent this from functioning.

**Comment by kevinmkr** [comment]
Was there an additional command that I should have executed to axe the sidecar orphans?

**Comment by lastzero** [comment]
We have to focus on completing multi-user features at the moment and work overtime to provide support to as many users as possible. Can't tell you more without digging deeper into details.

The code is public, so in theory others could take a look as well... 😉

**Comment by lastzero** [comment]
- Needless to say, we tested it all before releasing it, so it should generally work. It could be an edge case, 46,000 photos is a lot and no folder structure is the same.
- Note that there was a bug in a previous version that prevented certain index entries from being permanently removed when you delete a photo.
- So the behaviour depends not only on the version you are currently using, but also on when you started deleting photos.

**Comment by kevinmkr** [comment]
No worries.  I wasn't clear on how to locate the version -- UnRAID simply says "up to date" and I didn't see anything within the UI.  Running "photoprism version" from the terminal gave: "211018-e200f322-Linux-x86_64".  Looking at the release notes, this looks like October 18, 2021.  So, this could be the problem.

Still cutting my teeth on the UnRaid experience and even moreso on Docker.

Sorry for what was likely a false alarm based on an outdated build.

**Comment by lastzero** [comment]
In this case, your issue may already be solved 💎

**Comment by kevinmkr** [comment]
:)

**Comment by ChenSun-Phys** [comment]
Running purge multiple times solved it. Although a bit tangential to the original issue -- would there be a way to help with the [documentation](https://docs.photoprism.app/user-guide/advanced/commands/#purge) where the explanations of purge and cleanup are currently missing?

**Comment by mlapaglia** [comment]
anyone else seeing this, `photoprism purge` is limited to [10k files](https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/purge.go#L81) for each run, so that might be why you have to run it multiple times to  get rid of them all.
