### ISSUE TITLE
Library: Show folder covers in Originals

### ISSUE THREAD

**Issue by friesoft** [photoprism/photoprism#1011]
Having a fully structured/organized private photo collection ranging over 30 years (1,8TB, 270.000 photos, many of them scanned, thefore lacking useful time information) our primary way at looking at our photos will be from "Library => Originals". The problem is that there are no previews in the folder icons.

We are coming from Synology Photostation which nails it pretty much with the basic folder management (previews, permissions, ..) but fails at pretty much everything else.
(Yes I've seen the faq that you won't provide a tree view for private use - which is sad for us but a decision I can understand if it isn't within the scope of photoprism)

Having folder previews for the Originals would really help our workflow as you can see in this photo
![Screenshot 2021-02-06 at 22 03 40](https://user-images.githubusercontent.com/124109/107129672-4f1ccc00-68c7-11eb-995e-a65de6aeecfb.png)

**Comment by alexislefebvre** [comment]
The commits above mention icon but no image. Will we see images on the “Originals” view? That was the request in that issue.

**Comment by lastzero** [comment]
![Screenshot_20210208_124513](https://user-images.githubusercontent.com/301686/107215389-885e5480-6a0b-11eb-8c66-20e959d58890.jpg)

**Comment by alexislefebvre** [comment]
Yes I found that commit too: https://github.com/photoprism/photoprism/commit/c7753b87ffb13c56485351056311b954dd6f50af

For some reason it's not linked here.

Thanks for the improvement.

**Comment by lastzero** [comment]
You're welcome ⭐

**Comment by friesoft** [comment]
Working great :) thanks!
