### ISSUE TITLE
Add more camera makes / models to lookup table

### ISSUE THREAD

**Issue by kn100** [photoprism/photoprism#1015]
Hi,

I'm looking for opportunities to get into and contribute to Photoprism, and I noticed a fairly low hanging fruit easy thing I could contribute to. See this file:

https://github.com/photoprism/photoprism/blob/2d0ba9c60e73c69861e658e1a71af1e2b15b19e5/internal/entity/camera.go

I notice all the 'Models' listed are Huawei phones, but many are missing. For example, My P30 has the model number ELE-L29 - which is not listed, since Huawei have a lot of variants of each model.

This is common across many phone manufacturers. I am considering refactoring camera.go so that it instead can hold many keys which point to one 'friendly' name, so for example for the Huawei P30 has 4 variants, which are the ELE-L09, ELE-L29, VOG-L09 and VOG-L29. These would all be keys for the value which would be P30. 

Is there interest in me doing this? Any considerations/requests for the approach I take? I believe this file could grow extremely large as it grows to encompass more camera/phone models, so maybe this is a consideration?

**Comment by lastzero** [comment]
There it is:

```
"ELE-L29":    "P30",
```

**Comment by lastzero** [comment]
https://github.com/photoprism/photoprism/blob/2d0ba9c60e73c69861e658e1a71af1e2b15b19e5/internal/entity/camera.go#L66

**Comment by kn100** [comment]
I guess I am blind as a bat! Either way, point still stands, is this a PR you'd like somebody (namely me!) to make?

**Comment by lastzero** [comment]
You're welcome to add additional aliases if they don't exist yet. Might have missed some models, especially newer ones and from other vendors. Huawei is extreme when it comes to cryptic model strings.

**Comment by lastzero** [comment]
I'll close this. You're welcome to submit a PR if something is missing.
