### ISSUE TITLE
Sharing: Map view for shared album

### ISSUE THREAD

**Issue by Coltage** [photoprism/photoprism#1016]
Enable the Maps & Places view for shared Albums.

Would be nice to share albums with the family, and allow them to view where it was taken on the map.

**Comment by graciousgrey** [comment]
Just added this to the acceptance criteria of: https://github.com/photoprism/photoprism/issues/557.
Feel free to leave a :+1: there :)

**Comment by DennyWeinberg** [comment]
I've developed a service which displays your shared album on a map. Check it out here: 
https://levionsoftware.com/online-photo-map/
