### ISSUE TITLE
Metadata: Remove estimate when setting a new country

### ISSUE THREAD

**Issue by krair** [photoprism/photoprism#1018]
Some of my photos are incorrectly tagged (date, location, timezone). 

When I edit the photo, input the correct data, everything is saved correctly except for the country. Some photos it works, but a handful always default back to Germany as soon as I click "Approve".

Note: 

This is from a docker-installed ubuntu 20.04.
Browser: Firefox 85
App version: 210208-9e10ba69-Linux-x86_64

**Comment by lastzero** [comment]
Do they have GPS coordinates? In that case, changing the country is not possible (at the moment) as it is set automatically based on latitude and longitude.

**Comment by lastzero** [comment]
Or did you try to set the country to Unknown?

**Comment by krair** [comment]
No GPS coordinates, listed as 0,0 in the metadata. Tried deleting even the 0's and applying the change, no luck.

Setting to Unknown also reverts back to Germany.

**Comment by lastzero** [comment]
Any other differences between the photos that work and those that don't? It is possible the country is "estimated" from the title or keywords (like "Berlin")?

**Comment by lastzero** [comment]
Would be good to see screenshots or a recording (with private information removed) for debugging.

**Comment by krair** [comment]
Name of photo definitely not indicative of location, although the app is unable to pull out the date and time. For example:

IMG_20170529_123119_903.jpg

I'll see about a small recording or a few screenshots, some life admin getting in the way today, but I'll attempt

**Comment by lastzero** [comment]
Date / time extraction from this file name pattern can implemented 👍

**Comment by krair** [comment]
![Peek 2021-02-11 11-18](https://user-images.githubusercontent.com/75268581/107624439-25fb9300-6c5b-11eb-99c4-cd8672f5c836.gif)

**Comment by lastzero** [comment]
Probably happens when editing an image with estimated place as the cell id doesn't get removed when changing the country. Going to fix it with the next update.

**Comment by lastzero** [comment]
Does the fix work for you?

**Comment by lastzero** [comment]
Going to release this tomorrow if we hear no complaints :+1:

**Comment by krair** [comment]
I haven't tested it, I am using the docker image to host.

**Comment by lastzero** [comment]
You may use the demo or our preview image for testing, see https://docs.photoprism.org/release-notes/

**Comment by graciousgrey** [comment]
I tried editing lat/lng & country of photos with an estimated location. The changes stay as expected.
