### ISSUE TITLE
question: why does it need to move files ?

### ISSUE THREAD

**Issue by TwanoO67** [photoprism/photoprism#102]
Hello guys,

The project seems very promising :) but I wonder why the import process have to move files ?

As I have my photos folders already organized, this force me to have a duplication of them (which will cost a lot of space (talking about hundreds of gygabite... ).

I think that NAS users or people having their own server; already have their sorting methods for their photo files etc..

Is it not possible to have this system being read-only with the already existing assets file, and then organize only the meta data of those on it's own database ?

Regards,
Antoine

**Comment by lastzero** [comment]
As discussed in other tickets and probably our Wiki, you technically don't need to move them if there are no duplicates - but then the library must be read only for PhotoPrism, so you have less functionality.

**Comment by TwanoO67** [comment]
Thanks for the quick answer :)

Sorry but I didn't found info on that in the wiki.

What kind of functionnality loss are we talking about ?

So is it possible to use the docker version, with read-only volumes over my all photos dir ?
and so the import process will not copy them ? but only read them for metadata, and refer to them for raw data ?
That would be amazing :) I was looking for those type of functionnality for a while ^^

**Comment by lastzero** [comment]
Yes, this is what our example does, see https://docs.photoprism.org/en/latest/setup/

Uploading and deleting (not implemented yet) wouldn't work for example.

**Comment by TwanoO67** [comment]
Thanks for you answers :)
