### ISSUE TITLE
Adding an ignore file does not hide already indexed files

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#1032]
After indexing my library I added a `.ppignore` file to hide/remove some folders, but even after reindexing and purging, the folders are still shown in the app.

**Comment by lastzero** [comment]
Already indexed files won't be removed after the fact. Should be mentioned in our docs. Purge checks if files still exist, not of they are listed in a ppignore file.

**Comment by alexislefebvre** [comment]
A workaround that may work: rename the folders to a different name, put that name in the ignore list, reindex your files and then restore the original names.

**Comment by kvalev** [comment]
I see. Just to make sure - this is feature and not a bug, right?

**Comment by lastzero** [comment]
Yes, intended like this as ppignore is not a batch delete feature and gitignore also doesn't delete existing files. Typo may otherwise do lots of damage.
