### ISSUE TITLE
WebDAV: Uploading: ERROR “webdav: locked”

### ISSUE THREAD

**Issue by aocana** [photoprism/photoprism#1033]
I am trying to upload photos to my original drive where I have my photos located using webdav and I am getting the following error:

```
2021-02-14 19:36:42 ERRO webdav: "webdav: locked" in PUT /originals/msn/3000-4000-max.jpg

2021-02-14 19:36:42 DEBU http: PROPFIND /originals/msn/3000-4000-max.jpg (404) [113.444µs]

2021-02-14 19:36:42 DEBU http: PUT /originals/msn/3000-4000-max.jpg (423) [37.779µs]

```

Im using windows to open the remote drive wwebdav. 
I use docker for photoprism

Any ideas?

on the other hand congratulations for the great work. I hope it can continue free and free for a long time to come.

**Comment by lastzero** [comment]
Thanks! Not sure what might cause this... never happened to me. Maybe trying to upload the same file twice?

**Comment by aocana** [comment]
> Thanks! Not sure what might cause this... never happened to me. Maybe trying to upload the same file twice?

thanks you so much to support me.
I have tried to upload new files or photos..
I have tried logging into docker, making files, deleting files and I can do it without any problem.
is there any other log that i can try to check it?

**Comment by aocana** [comment]
we can close the case, I found the issue in the directory rights.

thanks team for your support!
