### ISSUE TITLE
Question: Recommended settings to speed up scroll performance?

### ISSUE THREAD

**Issue by inthreedee** [photoprism/photoprism#1035]
Are there any recommended settings to help speed up scrolling through a large library?

I'm currently seeing a 2-3 second wait time to load the next group of photos after reaching the bottom of the page on an 8GB Raspberry Pi 4.  It doesn't appear to be taxing the CPU much at all, and it's running off a decent SSD so I don't think that would be the bottleneck.  The thumbnails it's loading are only around 25kb each.  Could there be another bottleneck I'm not thinking of?  Or is there a setting to be more aggressive about loading more photos before reaching the bottom of the page?

Just looking for any advice on what I could tweak to make scrolling a bit more smooth.  Thanks!

**Comment by lastzero** [comment]
There may be various reasons, see #1014: The database, the browser, the number of http connections can be blocking as well. Of course you can make preloading even more aggressive, but then you might experience more of a lag while scrolling as JS is single threaded - so scrolling & loading at the same time is not ideal. You can also preload more files at once, but then your browser may be blocking as too many HTTP connections are being used. Cloud apps are using multiple domains for their CDN, which we can't. Using a CPU with more cores might help as well (even though the load may be low as you mentioned).

Note that the Mosaic view wasn't really built for scrolling through very fast like the timeline view that is on our roadmap. If you slow down a little bit, it should work just fine.
