### ISSUE TITLE
link generation photo sharing

### ISSUE THREAD

**Issue by aocana** [photoprism/photoprism#1037]
sorry for my question, but it''s not clear to me. 
To be able to share photos with third parties, friends, family, is it only possible to share with them if you have previously enabled nextcloud webdav?
I mean, if I don't have a nextcloud server, wouldn't it be possible to generate a "temporary" link to share the photos/albums within mydomain.com?

thank you very much for the help and very good work.

**Comment by alexislefebvre** [comment]
No, you don't need WebDav to share photos. Try on the demo: https://demo.photoprism.org/albums/aqokbmd3cuzeeohu/flowers

**Comment by aocana** [comment]
I have noticed that, but in my installed version, which is the latest version of docker, I only have the option to share via webdav, I do not know if I am missing something.

**Comment by lastzero** [comment]
See docs: https://docs.photoprism.org/user-guide/share/share/
