### ISSUE TITLE
Failing Tensorflow test TestTensorFlow_GetImageTags

### ISSUE THREAD

**Issue by skunert** [photoprism/photoprism#104]
When I execute `go test -tags slow -v ./internal/photoprism/...`, test `TestTensorFlow_GetImageTags` fails with the following message:

```
=== RUN   TestTensorFlow_GetImageTags
--- FAIL: TestTensorFlow_GetImageTags (2.59s)
    config.go:77: Initializing test data
    tensorflow_slow_test.go:33:
        	Error Trace:	tensorflow_slow_test.go:33
        	Error:      	Not equal:
        	            	expected: 0.1648176
        	            	actual  : 0.16481775
        	Test:       	TestTensorFlow_GetImageTags
```

I assume this is due to the recent tensorflow update. Project seems to be running fine on travis.

**Comment by lastzero** [comment]
Oops, should have tested with `-slow`... Yes, probably the new TensorFlow... also need to update Travis config in that case.
