### ISSUE TITLE
ImageDescription from exif results in binary comment

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1046]
**Steps to reproduce:**
1. Index a .CR2 file with  `"ImageDescription": "Shop with glasses"` in its exif data. 
2. After indexing check the edit dialogue

**Current behaviour**:
The UI shows me "binary comment" as description.
For jpg files with ImageDescription set there is no problem.

This is probably related to the exiftool update.

**Comment by lastzero** [comment]
Included in our next preview build: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by graciousgrey** [comment]
Looks good now
