### ISSUE TITLE
Flaky TestMediaFile_GetColors_Slow test

### ISSUE THREAD

**Issue by skunert** [photoprism/photoprism#105]
Sadly, TestMediaFile_GetColors_Slow is now flaky because of PR #103. The output of the prominentcolors library depends on some random parameters in the algorithm.
I think we should move the discussion here instead of the PR.

**Comment by skunert** [comment]
I have ideas how to fix the issue, but do not have time until monday.

**Comment by lastzero** [comment]
I've just pushed an implementation that doesn't use random numbers. It also enables us to search specific parts of an image (3x3 pixels = up to 9 colors). Seems to work well for now! A friend of mine did that long ago for an art project, not sure if it's an official algorithm 😉 

Of course you can have the bounty for #7 if you like, see https://issuehunt.io/r/photoprism/photoprism/issues/7

![Screenshot 2019-04-26 at 02 30 23](https://user-images.githubusercontent.com/301686/56776208-467b0480-67cb-11e9-9d3f-99e0ec4175ab.png)

**Comment by skunert** [comment]
Okay, I was too slow :D. But nice that you fixed it so quickly, sorry for the hassle.

**Comment by lastzero** [comment]
It was really helpful that you pushed this forward 👍
