### ISSUE TITLE
Navigate stacks while browsing an album

### ISSUE THREAD

**Issue by JamesSwift** [photoprism/photoprism#1050]
At the moment while browsing an album, if you swipe/move to an image that is stacked there is no indication that it's part of a stack, and no way to navigate the stack. 

It would be nice to detect when an image is part of a stack and allow navigating through the stack. As an example implementation, if left/right arrows move through an album, then up/down could navigate a stack. 

On Mobile devices, you could have swipe up/down but that is already assigned to exiting the view. So perhaps for mobile you could have a button to switch to stack navigate mode?

**Comment by lastzero** [comment]
We'll build a custom viewer eventually... probably not worth implementing this on top of PhotoSwipe, which we use right now.

**Comment by slowbiz** [comment]
If it's not possible or reasonable right now to change the viewer, can an overlay button be added to notify the user the photo is a member of a stack?  Potentially, you could then have the button take the user to the stacked photos viewer.

For my use case, this is important for scanned photos wherein the back of the photo has handwritten notes.  I have these stacked so the user can view the notes without cluttering the main gallery view.

**Comment by graciousgrey** [comment]
I close this as duplicate. 

The option to browse through stacks from within the photo viewer (fullscreen mode) will be part of https://github.com/photoprism/photoprism/issues/1307. It's already part of the acceptance criteria.

@slowbiz In the normal photos view we already have the stacking symbol (see https://docs.photoprism.org/user-guide/organize/stacks/#browse-through-related-files). Before we find time to add a new symbol + functionality to the current photoviewer we prefer to invest the time in building the new viewer :)
