### ISSUE TITLE
Google Photos *-edited.JPG files not always being stacked automatically

### ISSUE THREAD

**Issue by JamesSwift** [photoprism/photoprism#1051]
I began importing my library from google takeout yesterday and was pleased to see the "edited" versions it creates were being automatically stacked. My import finished, but then I realised it was because watchtower had pulled the latest version and restarted the container. So I restarted the import.

However, the "edited" version are no longer being stacked automatically. I reset my container (deleted the db and storage) and began the import again just to be sure, and sure enough the photos aren't being stacked. Is this a regression?

Here's some example filenames: 

```
UID | FQOMHA727JV8BWOY
Hash | 9e3dbdb38ff39217727ed15c1a3e704b9e1f4e59
Name | 2014/07/20140724_213339_617B0438.jpg
Original Name | Takeout/Google Photos/Andrea and Jamie Invite Shoot/IMG_1087.JPG


UID | FQOMHA1VSZDCG9N7
Hash | 645b6dcf0d5edc445b80d330535933b097b165a9
Name | 2014/07/20140724_213339_204BF995.jpg
Original Name | Takeout/Google Photos/Andrea and Jamie Invite Shoot/IMG_1087-edited.JPG

```

**Comment by lastzero** [comment]
May be yet another issue after updating our Exif library. Are you sure the settings are the same? Why should the files be stacked, by what attribute / based on what setting?

**Comment by lastzero** [comment]
There may also be a new exiftool version since we've upgraded Ubuntu for video transcoding. It may return other metadata thus influencing stacks.

**Comment by JamesSwift** [comment]
So, both containers had default settings apart from enabling experimental feature and changing the password. I'm reverting to the previous release with a clean container to test if it really has changed. I'll report back shortly.

> Why should the files be stacked, by what attribute / based on what setting?
I don't know I'm afraid. It seemed to work fine before, but now it doesn't. I know that's of no help. If you can tell me what to look for I'll happily report back :-)

**Comment by JamesSwift** [comment]
So, I'm now running the previous release `210211-b9595dd4-Linux-x86_64`. Most files are stacking but some are being missed. I'm honestly not sure if there is a better ratio between releases, sorry if this was a false alarm.

Here are some log entries for two files which should have been stacked, but weren't:
```
2021-02-16 13:21:24 INFO import: moving related json file “Takeout/Google Photos/2006 - Friends, Family and Bute/200612281317_00046.jpg.json” to 2007/05/20070520_142944_ABC03079.json
2021-02-16 13:21:24 INFO import: moving main jpg file “Takeout/Google Photos/2006 - Friends, Family and Bute/200612281317_00046.jpg” to 2007/05/20070520_142944_ABC03079.jpg
2021-02-16 13:21:24 INFO media: 200612281317_00046.jpg was taken at 2007-05-20 14:29:44 +0000 UTC (meta)
2021-02-16 13:21:24 INFO import: moving main jpg file “Takeout/Google Photos/2006 - Friends, Family and Bute/200612281317_00046-edited.jpg” to 2007/05/20070520_142944_01E765DC.jpg
2021-02-16 13:21:24 INFO media: 200612281317_00046-edited.jpg was taken at 2007-05-20 14:29:44 +0000 UTC (meta)
```

And their corresponding log entries:

```
UID | FQOMIFP2QP64EBTV
Hash | ff314afb3a1217a8f208668b9cf1125b76db7bac
Name | 2007/05/20070520_142944_ABC03079.jpg
Original Name | Takeout/Google Photos/2006 - Friends, Family and Bute/200612281317_00046.jpg
Size | 1280 × 960, 0.2 MB

UID | FQOMIFP3LKW1RCTP
-- | --
Instance ID | FAF5BDD5-BA3D-11DA-AD31-D33D75182F1B
Hash | 599060827c49d180f068df5cce2444a650f9c532
Name | 2007/05/20070520_142944_01E765DC.jpg
Original Name | Takeout/Google Photos/2006 - Friends, Family and Bute/200612281317_00046-edited.jpg
Size | 1280 × 960, 0.2 MB
```

**Comment by lastzero** [comment]
Yes, that may affect the matching... again, depending on your settings... you may want to enable "stack by sequential name"

Stackin in general works as you can see in our demo: https://demo.photoprism.org/photos?q=stack%3Atrue

**Comment by JamesSwift** [comment]
Thanks. Does "stack by sequential name" work globally or is it restricted to the directory the files are in?

So, why are some files auto stacking, and some not? They appear to have identical relevant meta available.

**Comment by JamesSwift** [comment]
I can confirm after a short test that enabling "stack by sequential name" doesn't help with the issue. As both photos have the same exact "time taken" and an identical filename (apart from appending -edited), I'm curious why the stacker doesn't match them?

**Comment by lastzero** [comment]
Works globally. Very much depends on how your files are named. Maybe reindexing helps if time and place are the same - won't work without GPS coordinates though. Same files also seem to have an Instance ID (unique image id).

Time zone estimates may influence stacking based on time and place in theory, not sure if that is the case here.

**Comment by lastzero** [comment]
Note: "stack by sequential name" won't change stacking after indexing, only when indexing or importing a file for the first time.

**Comment by JamesSwift** [comment]
> Note: "stack by sequential name" won't change stacking after indexing, only when indexing or importing a file for the first time.
Thanks, I assumed so and ran another import to be sure.

> Time zone estimates may influence stacking based on time and place in theory, not sure if that is the case here.
Doesn't seem to be. Can't see any differences apart from `Main Color` and `Chroma`, but I assume they aren't taken into account.

**Comment by lastzero** [comment]
You're welcome to send affected images to hello@photoprism.app for debugging! Won't publish them :)

**Comment by JamesSwift** [comment]
Thanks, I've sent you them now.
