### ISSUE TITLE
[Bug] Long file_name not supported

### ISSUE THREAD

**Issue by RichiH** [photoprism/photoprism#106]
I maintain an extensive photo collection via git-annex; think of it as a distributed git-LFS without lock-in to a single file source. It checks symlinks into Git and maintains the content outside of main Git; by default it refers to said files via a content hash.

Trying your latest docker image, I get the following error:

````
[2019-04-24 03:23:20]  
Added main jpg file ".git/annex/objects/00/v8/SHA512E-s129561--70c0b10e5f36e64acfdfeda1ec35e6ddedb903a1240cbfe2bc145ef971129e709e460b7026d5fe2332b5ec0f8bb58a7a47347ccbac19e5ef70634355d956329e.JPG/SHA512E-s129561--70c0b10e5f36e64acfdfeda1ec35e6ddedb903a1240cbfe2bc145ef971129e709e460b7026d5fe2332b5ec0f8bb58a7a47347ccbac19e5ef70634355d956329e.JPG"
No location: lat and long are missing in metadata

(Error 1406: Data too long for column 'file_name' at row 1) 
````

**Comment by lastzero** [comment]
Thanks for reporting this. How many chars should we allow for file names? 65,535 is the max for MySQL.

**Comment by lastzero** [comment]
4096 chars should work, that's the max for most Linux file systems. OS X seems limited to 1024 chars.

**Comment by lastzero** [comment]
Error on CI:
```
(Error 1071: Specified key was too long; max key length is 3072 bytes)
```

**Comment by lastzero** [comment]
@RichiH Please test. Seems like MySQL doesn't work with (much) more than 512 chars if you use 4 byte UTF-8 (required for emojis). TiDB is more powerful. PhotoPrism should work with both.

**Comment by lastzero** [comment]
Ok, no feedback. Seems to work 👍

**Comment by RichiH** [comment]
Sorry, very much under the water...

Will the current docker work to test this?

Sent by mobile; please excuse my brevity.

**Comment by lastzero** [comment]
I just merged to master. Our Docker images get updated automatically, if all tests are green. They are tagged with the build date, so you can see how old they are.
