### ISSUE TITLE
Too many packets buffered for output stream 0:1 Conversion failed!

### ISSUE THREAD

**Issue by JamesSwift** [photoprism/photoprism#1060]
When playing an mkv file, it fails to start and I get the following issue in the logs:
```
photoprism_1  | time="2021-02-17T12:31:18Z" level=info msg="converting 2020/04/20200429_173515_0AF3A078.mkv to avc (libx264)"
photoprism_1  | time="2021-02-17T12:31:19Z" level=warning msg="ffmpeg: ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)\n  configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared\n  WARNING: library configuration mismatch\n  avcodec     configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc\n  libavutil      56. 51.100 / 56. 51.100\n  libavcodec     58. 91.100 / 58. 91.100\n  libavformat    58. 45.100 / 58. 45.100\n  libavdevice    58. 10.100 / 58. 10.100\n  libavfilter     7. 85.100 /  7. 85.100\n  libavresample   4.  0.  0 /  4.  0.  0\n  libswscale      5.  7.100 /  5.  7.100\n  libswresample   3.  7.100 /  3.  7.100\n  libpostproc    55.  7.100 / 55.  7.100\n[matroska,webm @ 0x55e0b2dd1280] Could not find codec parameters for stream 0 (Video: h264, none(progressive), 1280x720): unspecified pixel format\nConsider increasing the value for the 'analyzeduration' and 'probesize' options\nInput #0, matroska,webm, from '/photoprism/originals/2020/04/20200429_173515_0AF3A078.mkv':\n  Metadata:\n    ENCODER         : Lavf58.36.100\n  Duration: 00:00:30.72, start: 0.018000, bitrate: 1037 kb/s\n    Stream #0:0: Video: h264, none(progressive), 1280x720, 25 fps, 25 tbr, 1k tbn, 2k tbc (default)\n    Metadata:\n      DURATION        : 00:00:30.720000000\n    Stream #0:1: Audio: aac (LC), 44100 Hz, mono, fltp (default)\n    Metadata:\n      title           : Track1\n      DURATION        : 00:00:30.506000000\nStream mapping:\n  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))\n  Stream #0:1 -> #0:1 (copy)\nPress [q] to stop, [?] for help\nToo many packets buffered for output stream 0:1.\nConversion failed!\n"
photoprism_1  | time="2021-02-17T12:31:19Z" level=error msg="video: transcoding 2020/04/20200429_173515_0AF3A078.mkv failed"
```
Any hints on how to debug? What I have learned so far:

- When I open the file in VLC, the audio plays and the video is black until about 6s seconds in.
- My file is obviously non-standard (it was captured through OBS), so this isn't your fault, but with a tweak we might be able to get it and other files to play
- The log mentions `unspecified pixel format\nConsider increasing the value for the 'analyzeduration' and 'probesize' options`
- Perhaps that is the issue. I am happy to test if you can tell me how to do what it asks 😊

**Comment by lastzero** [comment]
Is this the only file that causes problems or is this a general issue? Note that we don't run a ffmpeg consultancy :)

You may reduce the number of buffers using the ffmpeg buffers config option. Run photoprism help to see all options and a description.

**Comment by JamesSwift** [comment]
> Note that we don't run a ffmpeg consultancy :)

But you'd be so good at it 😁 But seriously, I debated whether to post this issue or not as I don't want to abuse your knowledge and time. I thought if it is a case of simply tweaking a default to make PP more compatible for everyone it would be worth it.

Reducing the number of buffers as you suggested didn't seem to help, but according to [this](https://stackoverflow.com/questions/49686244/ffmpeg-too-many-packets-buffered-for-output-stream-01)  adding a flag to ffmpeg `-max_muxing_queue_size 9999` might cure the problem, but it's not possible to add custom flags via PP at present to test.

I have noticed quite a few videos failing to play, but as I was importing at the time it was impossible to keep up with the log and note the specific issues. I'll do some tests now and report back if there is any patterns of failures.

Thank you again for your dedication to this project and your time interacting with me.

**Comment by lastzero** [comment]
Maybe you can do a bit of research and figure out if setting `-max_muxing_queue_size` to `9999` has any negative side effect, like excessive memory consumption or bad performance :)

**Comment by lastzero** [comment]
Note: There may be empty *.avc files left over from earlier attempts. We now delete them after errors, but that wasn't always the case. Try to remove them manually, that might fix some videos as they get transcoded again.

**Comment by JamesSwift** [comment]
Yes, having it at 9999 could create problems. I wondered if we could have it as a configurable option, or maybe just set it to a reasonable value like 1024 or something.

**Comment by lastzero** [comment]
The [original post](https://discussion.mcebuddy2x.com/t/ffmpeg-bug-too-many-packets-buffered-for-output-stream/1148) says "This error has been detected and handled in today’s 2.4.9 BETA build. You can try it out."

**Comment by JamesSwift** [comment]
So, I downloaded the [latest ffmpeg build](https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz) and told PP to use it, and yes it solves the issue. The PP container is using the latest stable release of ffmpeg, but the regression fix hasn't been applied or backported to it.

So we can either:

1.  - leave it as is and at some future date the fix will make it's way downstream
2.  - Add the temporary work around flag
3.  - Embed the latest ffmpeg

I'd suggest either 1 or 2 😊

**Comment by lastzero** [comment]
Hope we can leave it at that for now: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by inthreedee** [comment]
FYI, this warning appears for me when testing the new options:

`Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (out.avc) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.`

**Comment by lastzero** [comment]
Always or just for a specific file? I have no such issues.

**Comment by lastzero** [comment]
Oh, it might be that your hardware transcoder doesn't support it! Will this break transcoding videos or do you see this warning when manually running ffmpeg? Need more details to debug this.

**Comment by inthreedee** [comment]
I’ve been manually running ffmpeg in debug mode with the same options you’ve been adding. As far as I can tell, the above is just a warning that shows up in yellow before the actual transcoding process starts. It doesn’t seem to cause a halt in the process.

**Comment by lastzero** [comment]
Yes, so it's not an issue and just a debug message telling you that your encoder doesn't support a dynamic bitrate based on the quality. Expect larger files compared to software encoding. Guess that's a tradeoff outside our responsibility :)

**Comment by lastzero** [comment]
Our logs show what encoder is actually used, so you can see if the software encoder is used as fallback e.g. when ffmpeg returned an error.

**Comment by JamesSwift** [comment]
Thanks so much for your quick work on this. I'd like to test it, but my sample files have already been transcoded and cached by the new ffmpg I tried earlier. How can I delete the cache for these files so as to test?

**Comment by lastzero** [comment]
Manually delete them from the sidecar folder (*.avc)

**Comment by JamesSwift** [comment]
Excellent, works perfectly now. Thank you @lastzero. Just for future reference should I close this issue or leave it for you?
