### ISSUE TITLE
idea create album from folder indexed in original

### ISSUE THREAD

**Issue by spupuz** [photoprism/photoprism#1077]
I already have a folder organization for my existing pictures, why don't create an album based on folder names that are not standard name like (year name) but if a folder exist with name wedding i create an album with wedding name containing all pictures in that folder?

**Comment by lastzero** [comment]
We already create albums from folders?

**Comment by spupuz** [comment]
do you?

**Comment by lastzero** [comment]
![Screenshot_20210219_235554](https://user-images.githubusercontent.com/301686/108570389-0d037980-730e-11eb-94a6-82f184649bb3.jpg)
