### ISSUE TITLE
When clicking "add to album" from search view there is no focus on album name

### ISSUE THREAD

**Issue by Zaijo** [photoprism/photoprism#1078]
As there's no focus I need to click into the field and then start searching for the name. I'd like the focus to be automatic.

**Comment by lastzero** [comment]
Let us know if this works for you :+1:

**Comment by Zaijo** [comment]
Works as expected. Thanks.

**Comment by lastzero** [comment]
Excellent! Had to tweak it a bit with my second commit to fix layout / timing issues...
