### ISSUE TITLE
Try to download docker-compose.yml

### ISSUE THREAD

**Issue by soshnikov** [photoprism/photoprism#108]
https://raw.githubusercontent.com/photoprism/photoprism/master/configs/docker-compose.yml

thanks

**Comment by lastzero** [comment]
Moved to a different directory. Where is this link?

**Comment by lastzero** [comment]
I couldn't find the broken link. Maybe you can send a pull request, if you find it?

URL: https://raw.githubusercontent.com/photoprism/photoprism/develop/docker/photoprism/docker-compose.yml
