### ISSUE TITLE
Update container at Synology NAS

### ISSUE THREAD

**Issue by juxeii** [photoprism/photoprism#1086]
Hello,

I have installed Portainer on my Synology NAS and Photoprism is running fine.
Now, how would I get the latest container update?
Is it enough to run the instructions as described here: https://docs.photoprism.org/getting-started/updates/
Or are there special steps needed when working with Synology or NAS?
What about the maria db container? Does it get updated too?

It is also not clear to me if an update might index everything from scratch again?
Let's say, Photoprism deploys a new AI/ML network for recognizing stuff on the pictures. How does it do that when a new installation has been done?
In the background, or just on manual starting it? How would I start it manually and how do I know if this is needed anyway?

Oh, and how do we update Portainer itself on Synology?

Thx for help.
Juergen

**Comment by TimWinkler** [comment]
https://docs.photoprism.org/getting-started/updates/

Watchtower¶

Adding Watchtower as a service to your docker-compose.yml will automatically keep images up-to-date:

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by lastzero** [comment]
Is the question answered with that? :)

**Comment by juxeii** [comment]
That answered just how to keep it updated.
These were the other questions:

**What about the maria db container? Does it get updated too?

It is also not clear to me if an update might index everything from scratch again?
Let's say, Photoprism deploys a new AI/ML network for recognizing stuff on the pictures. How does it do that when a new installation has been done?
In the background, or just on manual starting it? How would I start it manually and how do I know if this is needed anyway?

Oh, and how do we update Portainer itself on Synology?**

**Comment by lastzero** [comment]
Yes, Watchtower may update all images.

No, it will not delete existing data.

**Comment by juxeii** [comment]
So, this means that after a new AI/ML model is deployed, only **new** imported images get categorized with that, and the older images are still categorized with the previous model?
Can I manually start a new categorization for the older images?

**Comment by lastzero** [comment]
In that case, you need to do a full rescan as described in our docs. We won't release new models very often though.

**Comment by juxeii** [comment]
Ok, thx.
One last question: since a NAS has not the highest computational power, is it possible to do a rescan on a different(more powerful) machine and then move the data back to the NAS? Are there any platform specific files?

**Comment by lastzero** [comment]
Yes, but it's a manual task and I'd rather wait a bit longer than investing time in doing this. Our own files are not platform specific, but binary database files (MariaDB, SQLite) may be.

**Comment by alexislefebvre** [comment]
> Ok, thx.
> One last question: since a NAS has not the highest computational power, is it possible to do a rescan on a different(more powerful) machine and then move the data back to the NAS? Are there any platform specific files?

See #1100
