### ISSUE TITLE
Docker container support for Raspberry Pi

### ISSUE THREAD

**Issue by tjaadvd** [photoprism/photoprism#109]
Hi guys,

I love where this project is going and I'm eager to try it on my Raspberry Pi 3b+. Are you planning on making the docker container suitable for ARM devices?

Greetings,
Thomas

**Comment by lastzero** [comment]
You might have to reduce quality settings and of course you need to compile it for ARM. Since we don't own a Raspberry, some help would be appreciated.

**Comment by Redwid** [comment]
Your docker base architecture is x86. So it's not possible right now to run it on ARM.

**Comment by lastzero** [comment]
>Your docker base architecture is x86. So it's not possible right now to run it on ARM.

@Redwid This is where pull requests come into play 💎

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by guysoft** [comment]
Hey guys, 
Developer of [CustomPiOS](https://github.com/guysoft/CustomPiOS) and maintainer from [ownphotos](https://github.com/hooram/ownphotos). 
It is possible to have armv builds on dockerhub. 
I have recently implemented this for CustomPiOS, and would love to see this also in photoprism.
It requires some dark magic involving qemu and dockerhub hooks. Example [here](https://hub.docker.com/r/ckulka/multi-arch-example). CustomPiOS [implementation here](https://github.com/guysoft/CustomPiOS/tree/devel/src/hooks).
I would love to help write this, but I need some help understanding what is amd64 bit, and I can see your docker build is split to several images. We will need to make them arm-compatible one by one.

**Comment by lastzero** [comment]
@guysoft There are two main challenges regarding ARM:

1. We need the TensorFlow C library which we previously had to compile from source, especially for specific ARM-based devices like the Nvidia Jetson. Not sure if / how you would be able to compile (and test) it with qemu or any other emulation, see #83 and https://dl.photoprism.org/tensorflow/nvidia-jetson/

2. We need a RAW to JPEG converter, currently this is Darktable on Linux (alternatively Sips on OS X), see #145 and https://github.com/photoprism/photoprism/wiki/Converting-RAW-to-JPEG - Darktable however can not be compiled for arm32v7, only 64 bit on ARM (x86 also 32 bit). So we can either find a good alternative or disable RAW to JPEG conversion.

When this is solved, we can start to think about build automation.

**Comment by lastzero** [comment]
Ubuntu 18.04 and other build dependencies are available for ARM 32/64, so that's the easy part... had that already but didn't seem to push it.

**Comment by guysoft** [comment]
@lastzero 
1. Looks well documented:
 *  Raspberrypi Tensorflow C 
           There is an official doc:
https://www.tensorflow.org/install/source_rpi
And there is a script especially in their repo (latest version 2.1.0):
https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
* Jetson nano Tensorflow C:
https://github.com/jens-totemic/tensorflow/releases/tag/v1.13.1

2. Looks like it could build. I can give that a try (actually started).
Repo I am looking at is at: 
https://github.com/darktable-org/darktable

Assuming I have managed to build both of these - will you lend me a hand with the Dockerfiles?

**Comment by guysoft** [comment]
Update: the great news is that it works on ARM, the bad is only ARMv8, which is a little more tricky to setup.

```
/darktable/src/is_supported_platform.h:64:2: error: #error "Unfortunately we only work on the 64-bit architectures amd64, ARMv8-A and PPC64."
 #error "Unfortunately we only work on the 64-bit architectures amd64, ARMv8-A and PPC64."
```

So I guess I can try build an env for that but wont be. Still this possible. I can try setting up a 64bit docker in a 32bit env.

**Comment by lastzero** [comment]
You can run 64bit Docker on a 32bit Kernel? Didn't find a way to do that. We use TensorFlow 1.4 not 2.x... These scripts didn't work for me, ended up using Bazel... But you can try. Also it was tricky to find the right compiler with the rich version settings for C and C++... In fact I contributed a patch to TensorFlow because it didn't compile on ARM. Should be part of the latest releases.

**Comment by lastzero** [comment]
Check out the Nvidia Jetson forums regarding TensorFlow... Took me one week to compile it... And I had fans afterwards:

> Hi,
> 
> Thank you for your response. I am successful in building the pip package and .SO for TF v1.13.1 on Jetson TX2 after around 3 weeks!!
> 
> Thank you
>

**Comment by guysoft** [comment]
@lastzero Recent Rasbian ships a 64bit kernel in a 32bit userland. Using a chroot you can run 64bit applications. I am trying to build your darktable docker container in such a chroot. 

I can build you a raspberrypi distro that has arm64 docker running on it. I think from there it just a matter of updating the Dockerfiles.

**Comment by lastzero** [comment]
There is a pre-built darktable package for Ubuntu 18.04... No need to build it from source

**Comment by guysoft** [comment]
@lastzero prebuilt for aarch64?
If so ill divert my efforts to making an arm64 bit distro with docker, is that all that is needed?

**Comment by lastzero** [comment]
Yes, Ubuntu has one for arm64

**Comment by guysoft** [comment]
Hey, not image yet, but updating you I have a repo that builds something. Hopefully this week if life is not too much in the way:
https://github.com/guysoft/rasbian64

**Comment by guysoft** [comment]
Aaand I am stuck:
https://forums.docker.com/t/running-docker-from-within-a-chroot/86883
Help would be great.

I have docker running, but it will not chroot. Not sure how to solve this yet.

**Comment by lastzero** [comment]
Is there anything we can change within our environment or software that would help?

**Comment by guysoft** [comment]
@lastzero Well it would have been easier if it was possble to run it on 32bit arm. aka arm32v7. But AFAIK Darktable wont let us do that.
I am pretty close to getting this to work, so let see if we get an answer on that. Also posted here:
https://serverfault.com/questions/998150/running-docker-from-within-a-chroot

**Comment by lastzero** [comment]
You could search for an alternative, any command that does the same will do...

**Comment by guysoft** [comment]
I am looking at ubuntu server as an alternative now

**Comment by guysoft** [comment]
Ubuntu server distro looks promising, I am adding CustomPiOS support for it.
Its kinda ridiculous they ship the distro without dhcpcd, ifconfig and iwconfig installed. Fixing that.
Should have an image can flash and build docker aarch64bit images from.

@lastzero As the next part of this - what is the Dockerfile that i need to build to have a aarch64 container?
Start with the final one, and then list if there are smaller ones that it depends on.

**Comment by lastzero** [comment]
Our development base image for x86:

https://github.com/photoprism/photoprism/blob/develop/docker/development/Dockerfile

For deployment, we use a two stage build (copy the binary files from our development image to a new image without dev tools):

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile

**Comment by guysoft** [comment]
ok - how are you building 
https://dl.photoprism.org/tensorflow/linux/libtensorflow-linux-cpu-1.14.0.tar.gz ?
Looks like that is the biggest bit missing now.
Darktable repo has arm64 builds

**Comment by lastzero** [comment]
LOL, that's what took me 7 days to figure out last time 😄 

Put the secret sauce in 

https://github.com/photoprism/photoprism/tree/develop/docker/tensorflow

and the binaries in

https://dl.photoprism.org/tensorflow/

Note that I built the ARM64 binary on the Jetson without Docker (also because I needed the Nvidia libraries for the GPU), so the Docker image is only tested / used on x86 so far.

**Comment by guysoft** [comment]
Ok, that adds dependency to build bazel for arm64, unless you can find it (only binary needed).

**Comment by lastzero** [comment]
You might be lucky and find one, I had to build it from source last time. Note that you can't just any version of Bazel. 0.24.1 should be right for TF 1.14.0, tooks me several hours alone to test various versions. You would think that's documented.

**Comment by guysoft** [comment]
New CustomPiOS build, got 64bit docker running, just need to release as a nightly image.

Once we have a working docker image, we could ship an entire SD card with photoprism pre-installed.
For now the image should let us build arm64 bit containers (later can be moved to dockerhub, but development has to happen locally for timeframe to make sense):
https://github.com/guysoft/UbuntuDockerPi

**Comment by guysoft** [comment]
> You might be lucky and find one, I had to build it from source last time. Note that you can't just use any version of Bazel: 0.24.1 should be right for TF 1.14.0, took me several hours to figure out. You would think that's documented.

Looks like we will need to build it from source:
https://github.com/bazelbuild/bazel/issues/8833
I am not sire 0.24.1 would build. Will try.

**Comment by guysoft** [comment]
Ok, I have built a Raspberrypi Ubuntu image preinstalled with docker on ``aarch64``. So you can use it to build and push Docker images.
I also got it set up so you can connect with wifi. So its a good base image for photoprism to come.

Usage instructions:
https://github.com/guysoft/UbuntuDockerPi

Image:
http://unofficialpi.org/Distros/UbuntuDockerPi/nightly/2020-01-14_ubuntudocker-19.10.1-preinstalled-server-arm64+raspi3-0.1.0.zip

Md5: [`aa7f391a7d7f5da1b4893bb67402a59f`](http://unofficialpi.org/Distros/UbuntuDockerPi/nightly/2020-01-14_ubuntudocker-19.10.1-preinstalled-server-arm64+raspi3-0.1.0.zip.md5).

Using it to build Bazel too.

**Comment by guysoft** [comment]
Ok, got another strange insight.
You can run aarch63bit docker containers on raspbian, with docker installed. But only if they are ``--privileged``. Not sure why.

You need to pull a non-multiarch image for this. Which I created at:

https://hub.docker.com/repository/docker/guysoft/ubuntuarm64


So we could even ship a container that could run on raspbian too!

**Comment by guysoft** [comment]
Current state: Stuck building tensorflow. Getting:
```
b/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/notification.o
gcc: error: missing argument to '-march='
gcc: error: missing argument to '-march='
tensorflow/contrib/makefile/Makefile:858: recipe for target 'tensorflow/contrib/makefile/gen/obj/tensorflow/contrib/makefile/downloads/fft2d/fftsg.o' failed
make: *** [tensorflow/contrib/makefile/gen/obj/tensorflow/contrib/makefile/downloads/fft2d/fftsg.o] Error 1
make: *** Waiting for unfinished jobs....
tensorflow/contrib/makefile/Makefile:896: recipe for target 'tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/blocking_counter.o' failed
make: *** [tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/blocking_counter.o] Error 1
gcc: error: missing argument to '-march='
tensorflow/contrib/makefile/Makefile:896: recipe for target 'tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/mutex.o' failed
make: *** [tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/mutex.o] Error 1
gcc: error: missing argument to '-march='
tensorflow/contrib/makefile/Makefile:896: recipe for target 'tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/notification.o' failed
make: *** [tensorflow/contrib/makefile/gen/host_obj/tensorflow/contrib/makefile/downloads/absl/absl/synchronization/notification.o] Error 1
```

@lastzero Any tips?

**Comment by lastzero** [comment]
Looks like you're using Make and not Bazel?

**Comment by guysoft** [comment]
No, my bad, using the build script, but I had to manually update the ARCH flag in the script. Looks like its building now for ``armv8-a``. Hope thats the right one

**Comment by lastzero** [comment]
Not 100% sure, your console output looks like you're using the contributed Makefile for building TF without Bazel:

```
tensorflow/contrib/makefile/Makefile
```

My goal was to build a static version for bundling the library with our app binary, see #83. But I gave up and used Bazel instead. Don't use the static target:

```make
libtensorflow:
	bazel build --jobs 2 --config=opt //tensorflow:libtensorflow.so
static:
	env JOB_COUNT=2 ARCH=armv8-a ./build_static.sh
```

**Comment by guysoft** [comment]
Ok, now its not my bad. Internal compiler error?!

```
nsorflow/core/kernels/bcast_ops.cc -o tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/bcast_ops.o
gcc --std=c++11 -DIS_SLIM_BUILD -fno-exceptions -DNDEBUG -O3 -march=armv8-a -fPIC -MT tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/bias_op.o -MMD -MP -MF tensorflow/contrib/makefile/gen/dep//tensorflow/core/kernels/bias_op.Td -I. -Itensorflow/contrib/makefile/downloads/ -Itensorflow/contrib/makefile/downloads/eigen -Itensorflow/contrib/makefile/downloads/gemmlowp -Itensorflow/contrib/makefile/downloads/nsync/public -Itensorflow/contrib/makefile/downloads/fft2d -Itensorflow/contrib/makefile/downloads/double_conversion -Itensorflow/contrib/makefile/downloads/absl -Itensorflow/contrib/makefile/gen/proto/ -Itensorflow/contrib/makefile/gen/proto_text/ -Itensorflow/contrib/makefile/gen/protobuf-host/include -I/usr/local/include -c tensorflow/core/kernels/bias_op.cc -o tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/bias_op.o
gcc --std=c++11 -DIS_SLIM_BUILD -fno-exceptions -DNDEBUG -O3 -march=armv8-a -fPIC -MT tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/boosted_trees/prediction_ops.o -MMD -MP -MF tensorflow/contrib/makefile/gen/dep//tensorflow/core/kernels/boosted_trees/prediction_ops.Td -I. -Itensorflow/contrib/makefile/downloads/ -Itensorflow/contrib/makefile/downloads/eigen -Itensorflow/contrib/makefile/downloads/gemmlowp -Itensorflow/contrib/makefile/downloads/nsync/public -Itensorflow/contrib/makefile/downloads/fft2d -Itensorflow/contrib/makefile/downloads/double_conversion -Itensorflow/contrib/makefile/downloads/absl -Itensorflow/contrib/makefile/gen/proto/ -Itensorflow/contrib/makefile/gen/proto_text/ -Itensorflow/contrib/makefile/gen/protobuf-host/include -I/usr/local/include -c tensorflow/core/kernels/boosted_trees/prediction_ops.cc -o tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/boosted_trees/prediction_ops.o
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
tensorflow/contrib/makefile/Makefile:851: recipe for target 'tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/argmax_op.o' failed
```

**Comment by lastzero** [comment]
Running out of memory? Do you compile this on the Pi? You can reduce jobs to one if two is still too much :/

**Comment by guysoft** [comment]
Yes, added swap space, trying again.

**Comment by lastzero** [comment]
Oh yes, you need swap 🐳

**Comment by guysoft** [comment]
Ok, so its been compiling for 7 hours. I ran ``build_static.sh``
I can see protobuf bas been built. But no tensorflow:

```
root@6368e127a5fd:/home/tensorflow/tensorflow-1.14.0# find . -name '*.so'
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf-lite.so
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf.so
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotoc.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotobuf-lite.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotobuf.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotoc.so
``

I think it built it statically:

```
root@6368e127a5fd:/home/tensorflow/tensorflow-1.14.0# find . -name '*.so'
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf-lite.so
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotobuf.so
./tensorflow/contrib/makefile/gen/protobuf/lib/libprotoc.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotobuf-lite.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotobuf.so
./tensorflow/contrib/makefile/downloads/protobuf/src/.libs/libprotoc.s
```

So I guess at least I know it builds now. But will have to do it again. It might be a good idea to add a ``build_dynamic.sh`` script there.

**Comment by guysoft** [comment]
Ok, its failing now on ``time bazel build --jobs 2 --config=opt //tensorflow:libtensorflow.so``:

```
INFO: From Compiling external/nsync/internal/counter.c [for host]:
cc1plus: warning: command line option '-std=c11' is valid for C/ObjC but not for C++ [enabled by default]
ERROR: /root/.cache/bazel/_bazel_root/972e44db2b139cc1f421a35ac89a32ec/external/boringssl/BUILD:130:1: C++ compilation of rule
 '@boringssl//:crypto' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/972e44db2b139cc1f421a35ac89a32ec/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/host/bin/external/boringssl/_objs/crypto/a_bitstr.pic.d '-frandom-seed=bazel-out/host/bin/external/boringssl/_objs/crypto/a_bitstr.pic.o' -fPIC -iquote external/boringssl -iquote bazel-out/host/genfiles/external/boringssl -iquote bazel-out/host/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/host/genfiles/external/boringssl/src/include -isystem bazel-out/host/bin/external/boringssl/src/include -g0 -Wno-sign-compare '-std=c11' -DOPENSSL_NO_ASM -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/boringssl/src/crypto/asn1/a_bitstr.c -o bazel-out/host/bin/external/boringssl/_objs/crypto/a_bitstr.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
In file included from external/boringssl/src/crypto/asn1/a_bitstr.c:65:0:
external/boringssl/src/crypto/asn1/../internal.h:438:3: error: unknown type name 'pthread_rwlock_t'
   pthread_rwlock_t lock;
   ^
Target //tensorflow:libtensorflow.so failed to build  
INFO: Elapsed time: 868.758s, Critical Path: 44.95s   
INFO: 284 processes: 284 local.
FAILED: Build did NOT complete successfully
```

**Comment by lastzero** [comment]
Congratulations, looks like the end battle...

Probably has to do with compiler settings and POSIX levels / standards, see for example https://github.com/libuv/libuv/issues/306

For the settings that worked for me, see `build:opt`:

https://dl.photoprism.org/tensorflow/nvidia-jetson/config/tf_configure.bazelrc

Hope you didn't remove those.

Did you apply the patch before building?

```
patch:
	git apply tensorflow-$(TF_VERSION).diff
```

In the worst case, you have to add missing symbols to the third_party config files, if it's something my patch doesn't fix yet. You can then submit it as PR to TensorFlow and become a contributor.

**Comment by lastzero** [comment]
> So I guess at least I know it builds now. But will have to do it again. It might be a good idea to add a `build_dynamic.sh` script there.

Well, that's why I added the `Makefile`, you're not supposed to run `*.sh` manually. Sure, I could have removed the half-done static part. I started my journey with this one single script until I figured it's all nonsense and there is not one single script that just works and I have to fight my way through to the top like back in the days...

**Comment by guysoft** [comment]
Ok, had to update ``build --action_env TF_NEED_TENSORRT="0"`` building now.

**Comment by lastzero** [comment]
TF_NEED_TENSORRT is for GPUs AFAIK

**Comment by lastzero** [comment]
Seeing this, I think it would be cool to document the build process on a Wiki page (and maybe a blog post if somebody has the time to do it).

**Comment by guysoft** [comment]
Failed now on:
```
INFO: From Compiling external/nsync/internal/wait.c [for host]:
cc1plus: warning: command line option '-std=c11' is valid for C/ObjC but not for C++ [enabled by default]
ERROR: /root/.cache/bazel/_bazel_root/972e44db2b139cc1f421a35ac89a32ec/external/gif_archive/BUILD.bazel:8:1: C++ compilation o
f rule '@gif_archive//:gif' failed (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/972e44db2b139cc1f421a35ac89a32ec/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-p
ointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/host/bin/external/gif_arch
ive/_objs/gif/egif_lib.pic.d '-frandom-seed=bazel-out/host/bin/external/gif_archive/_objs/gif/egif_lib.pic.o' -fPIC -iquote ex
ternal/gif_archive -iquote bazel-out/host/genfiles/external/gif_archive -iquote bazel-out/host/bin/external/gif_archive -isyst
em external/gif_archive/lib -isystem bazel-out/host/genfiles/external/gif_archive/lib -isystem bazel-out/host/bin/external/gif
_archive/lib -g0 '-march=armv8-a' -Wno-sign-compare '-std=c11' '-D_XOPEN_SOURCE=600' -fno-canonical-system-headers -Wno-builti
n-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/gif_archive/lib/egi
f_lib.c -o bazel-out/host/bin/external/gif_archive/_objs/gif/egif_lib.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
external/gif_archive/lib/egif_lib.c: In function 'EGifOpenFileName':
external/gif_archive/lib/egif_lib.c:62:6: error: 'S_IREAD' undeclared (first use in this function)
      S_IREAD | S_IWRITE);
      ^
external/gif_archive/lib/egif_lib.c:62:6: note: each undeclared identifier is reported only once for each function it appears in
external/gif_archive/lib/egif_lib.c:62:16: error: 'S_IWRITE' undeclared (first use in this function)
      S_IREAD | S_IWRITE);
                ^
Target //tensorflow:libtensorflow.so failed to build
```

**Comment by lastzero** [comment]
Can you check if the patch was really applied? Looks like it is missing, that's exactly what the patch is for.

**Comment by guysoft** [comment]
@lastzero Dang, missed that I comment the patching. Fixed, building.

**Comment by lastzero** [comment]
@guysoft Mentioned your efforts on the [Project-Status ](https://github.com/photoprism/photoprism/wiki/Project-Status) page

**Comment by guysoft** [comment]
Success!
```
                                       ^
tensorflow/core/grappler/optimizers/data/map_vectorization.cc:313:66: warning: 'new_map_node' may be used uninitialized in this function [-Wmaybe-uninitialized]
     graph_utils::CopyAttribute(key, new_map_node, &prefetch_node);
                                                                  ^
tensorflow/core/grappler/optimizers/data/map_vectorization.cc:541:14: note: 'new_map_node' was declared here
     NodeDef* new_map_node;
              ^
Target //tensorflow:libtensorflow.so up-to-date:
  bazel-bin/tensorflow/libtensorflow.so
INFO: Elapsed time: 21082.844s, Critical Path: 1028.63s
INFO: 5011 processes: 5011 local.
INFO: Build completed successfully, 5158 total actions

real    351m24.113s
user    0m5.710s
sys     0m6.036s
```

Uploading to (there in 10 mintues):
http://unofficialpi.org/libtensorflow-aarch64-1.14.0.tar.gz

**Comment by lastzero** [comment]
Congratulations 🎊💐🎉

**Comment by negbie** [comment]
This is awesome! Thank you all who were involved!

**Comment by guysoft** [comment]
I have now all the binaries to build the image. Should have time to start next week.

**Comment by guysoft** [comment]
Built, haven't tested yet:
https://hub.docker.com/repository/docker/guysoft/photoprisim

Need to set docker-compose

**Comment by guysoft** [comment]
Ok, tested and it works and adds images.

You need to:
1. Use a Raspberrypi 3/4 where you have set in ``/boot/config.txt`` the parameter ``arm_64bit=1``
2. Update ``docker-compose.yml`` to use the image: ``guysoft/photoprisimpi``
3. Make sure your docker compose has the setting for the image:
```
  photoprism:
    security_opt:
      - seccomp:unconfined
```

You can use UbuntuDockerPi as well to run the image, or Raspbian once its on 64bit kernel.

@lastzero I guess we should talk how to set up a PR from https://github.com/guysoft/photoprism/tree/rpi
Which has all the Dockerfiles to build this.

**Comment by lastzero** [comment]
@guysoft Epic! Love it. Works (almost) out of the box.

This is merged although GitHub shows a strange merge error/conflict status...

Maybe we can automatically build images for aarch64 on Travis CI: https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

Two questions:

1) Is it normal that I have to run docker-compose as root (sudo)? Can't connect to the Docker service otherwise. Storage directories are created in /root/Pictures because of this. I'm using your Ubuntu Server image: https://github.com/guysoft/UbuntuDockerPi

2) Do you think it makes sense to move ARM64 related files to a separate directory or even repository? Or is it better to use our existing directories and image names with aarch64 suffixes / tags?

**Comment by guysoft** [comment]
0. You should be able to get it to build on docker hub, using hooks for multiatch. Check out what I did for CustomPiOS:
https://github.com/guysoft/CustomPiOS/tree/devel/src/hooks
1. Yes. docker-compose should either run as root, or you need to put the user in the docker group. I could add that to the disto.
2. I'd put them where they are. Because you want it infront of your eyes when you are editing the amd64 Dockerfiles too. Definitely the same repo, because you want a new version tag to include those filea, they are part of the release no less than your other files. Its also easy to seach for them all, they all end with aarch64.

**Comment by lastzero** [comment]
Any reason to favor aarch64 instead of arm64? Docker Hub seems to use arm64. Refactoring the directory structure at the moment.

What Dockerfile did you use to build the actual image? Can only find the development image (production Dockerfile probably looks very similar to the one for x86)

**Comment by lastzero** [comment]
Put the [docker-compose.yml](https://dl.photoprism.org/docker/arm64/docker-compose.yml) on our download server to shorten the download url:

```
wget https://dl.photoprism.org/docker/arm64/docker-compose.yml
sudo docker-compose up
```

Using `arm64` instead of `aarch64` now, simply because it's shorter. Seems like aarch64 is common in GNU land whereas Apple prefers arm64.

Should probably create a manifest for our architectures with https://github.com/estesp/manifest-tool. Shall we add a ticket for this and do it later? Wouldn't consider that a high priority task. Any experience with this?

**Comment by guysoft** [comment]
> Any reason to favour aarch64 instead of arm64? Docker Hub seems to use arm64. Refactoring the directory structure at the moment.

Its the same thing:



> AArch64 is the 64-bit state introduced in the Armv8-A architecture. The 32-bit state which is backwards compatible with Armv7-A and previous 32-bit Arm architectures is referred to as AArch32. Therefore the GNU triplet for the 64-bit ISA is aarch64. The Linux kernel community chose to call their port of the kernel to this architecture arm64 rather than aarch64, so that's where some of the arm64 usage comes from.

>   As far as I know the Apple backend for aarch64 was called arm64 whereas the LLVM community-developed backend was called aarch64 (as it is the canonical name for the 64-bit ISA) and later the two were merged and the backend now is called aarch64.

> **So aarch64 and arm64 refer to the same thing.**

[source](https://unix.stackexchange.com/questions/461179/what-is-the-difference-between-different-implemetation-of-arm64-aarch64-for-linu)

I went with aarch because that seems to be the name in most debian repos and when you download binaries.

**Comment by guysoft** [comment]
> Should probably create a manifest for our architectures with https://github.com/estesp/manifest-tool. Shall we add a ticket for this and do it later? Wouldn't consider that a high priority task. Any experience with this?

Yes I recommend a septate ticket. This one is really long as it is. and you want people to look back and have it easier to follow.

**Comment by lastzero** [comment]
Perfect, I'll close this then if that's OK for you? Thank you very much for the effort you put into this!

Maybe you or someone else can quickly test this:

```
wget https://dl.photoprism.org/docker/arm64/docker-compose.yml
sudo docker-compose up
```

**Comment by guysoft** [comment]
Close, open new issues. Including documentation on README :)

**Comment by guysoft** [comment]
Hey guys,
We need to talk more and figure out how to make this even simpler, but know that in the works there is also a RaspeberryPi image, that you just flash and comes with PhotoPrisim https://github.com/guysoft/PhotoPrismPi

The end goal is you have a drive, you flash this image and boot the Pi, and bam, you have a self-hosted photo album.

**Comment by lastzero** [comment]
Excellent! We've just ordered another Pi 4 for testing this on a TV. Comes
with a 400 GB SD card, so room for lots of images.

**Comment by negbie** [comment]
@guysoft Thank you! I've already ordered an ssd for this but now I think a biiiig SD card with your image is even better ;)

**Comment by guysoft** [comment]
Image should work fine on a 8-16GB device, not including images.

Just make sure its a fast class 10 or faster (I use A1 sandisk).

**Comment by guysoft** [comment]
Ok,  we now have a whole image you can flash that comes with everything pre-instlaled
It will even automatic-mount USB drives you attach to the Pi and lets you index them:
https://github.com/guysoft/PhotoPrismPi/releases/tag/0.1.0

**Comment by HydrelioxGitHub** [comment]
I'm a noob with docker. Can I install photoprism with docker on an rpi4 with a 32bit version (armv71) ?

**Comment by guysoft** [comment]
No you can't because photoprism requires libraries that a 64bit machine. So you must have photoprism with a 64bit kernel enabled.
You can use a rpi4 with a 32bit userspace. But the kernel must be 64bit.
I will note that if you are using a clean RaspsberryPi 4 you can also use the dedicated distribution [PhotoPrismPi](https://github.com/guysoft/PhotoPrismPi)

**Comment by levivk** [comment]
What's the recommended approach for getting docker-compose on aarch64/arm64? I see they don't build releases for it and the ones in apt and snap are outdated... Is installing through pip the best way?

**Comment by guysoft** [comment]
I personally built images that come with it pre-installed
1. 
https://github.com/guysoft/UbuntuDockerPi
2. 
https://github.com/guysoft/PhotoPrismPi

**Comment by levivk** [comment]
I saw those, however I've got a pi 4 4gb with ubuntu 20.04 server 64 bit that has Nextcloud on it already. I installed docker-compose with pip and virtualenv, and then symlinked docker-compose to my path. It seems to be working. I might make a PR for a hint in Raspberry Pi setup docs if this is the preferred method.

Thanks so much for your work on getting PhotoPrism on to the Pi!!

**Comment by guysoft** [comment]
You can take a look at the docker module in CustomPiOS and see how its done

**Comment by larsxschneider** [comment]
I have a 32-bit only ARM CPU (Annapurna Labs Alpine AL314 Quad-core ARM Cortex-A15).

Is there a fundamental problem to compile TensorFlow for 32-bit? This thread seems to indicate that. However, the "official" guide indicates that 32-bit builds are possible: https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel

**Comment by lastzero** [comment]
Our armv7 Docker image should include it already?
