### ISSUE TITLE
Prevent hashed docker volume names

### ISSUE THREAD

**Issue by maltokyo** [photoprism/photoprism#1093]
Currently, because the docker image exposes this directory from inside the container: `/var/lib/photoprism`,  in the host's docker volume directory a hashed volume gets created.  Is this directory needed?  It appears empty.  It is created each time on startup, which is confusing.  If it is needed, shall we just bind-mount it like the other directories?  If not needed, I would not expose it outside of the container.  Details below, from my installation:

```
  "Type": "volume",
  "Name": "5cbb7f750549e07a7397deb78d84815aa04beef12ce75e9ccf868aeba7f6ab61",
  "Source": "/var/lib/docker/volumes/5cbb7f750549e07a7397deb78d84815aa04beef12ce75e9ccf868aeba7f6ab61/_data",
  "Destination": "/var/lib/photoprism",
  "Driver": "local",
  "Mode": "",
  "RW": true,
  "Propagation": ""
```

**Comment by lastzero** [comment]
We use it to store backups and a token as mounted directories are sometimes misconfigured (e.g. not writable), which leads to continuous restarts. If PhotoPrism is not allowed to have any kind of storage, there is no (easy) way to detect this and know this is still the same instance / container. Of course you may bind-mount it manually, if the anonymous volume bothers you!
