### ISSUE TITLE
Docker ARM64 version - crash when try to index

### ISSUE THREAD

**Issue by darrepac** [photoprism/photoprism#1094]
Hello

I just put the docker arm64 version into my Pi3B+
I select one folder (nfs mounted) and press sync.
It says quickly that I am offline and I have the following in the log:
_

photoprism_1  | time="2021-02-24T14:15:04Z" level=info msg="Indexing files in 2020"
photoprism_1  | time="2021-02-24T14:15:04Z" level=info msg="classify: loading nasnet"
photoprism_1  | /entrypoint.sh: line 43:     8 Killed                  "$@"
mariadb_1     | 2021-02-24 14:15:20 13 [Warning] Aborted connection 13 to db: 'photoprism' user: 'photoprism' host: '172.20.0.3' (Got an error reading communication packets)
photoprism_photoprism_1 exited with code 0

_

To avoid issue, I put 1 worked into the yml...
free -m
              total        used        free      shared  buff/cache   available
Mem:            860         443         243           7         173         357
Swap:            99          99

**Comment by darrepac** [comment]
I increased the swap to 1GB and it doesn't crash anymore.... but it is very slow indexing:
photoprism_1  | time="2021-02-24T15:55:17Z" level=info msg="media: IMG-2522.JPG was taken at 2020-02-23 12:19:21 +0000 UTC (meta)"
photoprism_1  | time="2021-02-24T15:56:15Z" level=info msg="location: added place s2:478af482983c [1.829614392s]"
photoprism_1  | time="2021-02-24T15:56:25Z" level=info msg="media: 7 thumbnails created for IMG-2522 [8.942873758s]"

More than 1min per photo...

**Comment by darrepac** [comment]
It eventually crashes... seems too heavy for a Pi

**Comment by kvalev** [comment]
I managed to index almost my entire collection on Pi 2. I had to increase the swap, allow docker to use it, decrease the number of workers to one and exclude larger files (`PHOTOPRISM_ORIGINALS_LIMIT`). It still crashed from time to time, but with a little bit of patience its doable.

**Comment by darrepac** [comment]
Good to know thx

**Comment by lastzero** [comment]
Looks like there is no enough memory / swap and the process gets killed by the system:

> If you're running out of memory - or other system resources - while indexing, please limit the number of workers by setting PHOTOPRISM_WORKERS to a value less than the number of logical CPU cores in docker-compose.yml. Also make sure your server has swap configured so that indexing doesn't cause restarts when there are memory usage spikes. As a measure of last resort, you may additionally disable image classification using TensorFlow.

**Comment by darrepac** [comment]
yep, by letting it run alone (=without trying to do something else in the same time)
I successfully made it run 3 days to scan all my database (1 worker and 1GB of swap).
Now just waiting for the timeline/infinite view like in iOS app ;)

**Comment by lastzero** [comment]
You should configure swap anyway :)
