### ISSUE TITLE
Write Metadata in the Photo

### ISSUE THREAD

**Issue by bnounours** [photoprism/photoprism#1095]
Hello,

Do you plan to be able to write the metadata into the file ?
The tool I use (shotwell) allow this and to me it is interesting because as it uses XMP, Exif, IPTC, it is directly compatible with existing tools. Also reimporting my photos recreate the list of tags on lot of tools.
For example on linux the metadata of jpeg files are indexed so when searching a picture I can use the metadata. As far as I know Windows do the same

Thx

**Comment by alexislefebvre** [comment]
See #1092

**Comment by bnounours** [comment]
Thx Alexis
