### ISSUE TITLE
German translation: categories

### ISSUE THREAD

**Issue by fratzzz** [photoprism/photoprism#1096]
"Labels" and "Categories" are both translated as "Kategorien", this is somewhat confusing. How would that translate properly?
"Etikett", "Rubrik", "Beschriftung", "Kennzeichnung" or just stick to "Label"?

In the documentation I have not found  what categories are and how they are used.

**Comment by lastzero** [comment]
Labels may be long to other labels, like cat -> animal. So it's in fact the same type of entity.
