### ISSUE TITLE
Folders: first letter of every word is capitalised 

### ISSUE THREAD

**Issue by fratzzz** [photoprism/photoprism#1097]
In my opinion, it would be better if folders were imported as they are. An example:
"Urlaub in der Provence und im Parc naturel régional du Verdon" becomes "Urlaub In Der Provence Und Im Parc Naturel Régional Du Verdon"

**Comment by lastzero** [comment]
We don't have capitalization implemented for all languages, it's a specifically English thing. So once we have language detections, we can disable it e.g. for German.

**Comment by graciousgrey** [comment]
I will close this for now, we can open a new ticket for language detection if you like :)
