### ISSUE TITLE
how to select photo as album cover?

### ISSUE THREAD

**Issue by Hurray0** [photoprism/photoprism#1098]
How can I select a specific photo in an album as the album cover?
BTW, It seems the cover of the album is changing as time passed, what is the reason?

**Comment by kvalev** [comment]
See #383

**Comment by graciousgrey** [comment]
At the moment the cover album is set automatically. It may change as PhotoPrism selects the one it assume most suitable e.g. a photo in good quality marked as favorite.

Setting the cover image manually is in progress :)

**Comment by adhatcher** [comment]
I have removed the photo that is being used for the album cover from the album, yet the photo that was removed from the album is still showing up as the album cover.

**Comment by graciousgrey** [comment]
It may still be saved in your browser cache
