### ISSUE TITLE
Duplicates in Album Download

### ISSUE THREAD

**Issue by derwaro** [photoprism/photoprism#1099]
I created an album, which I would like to download in order to get printed photos of my selection.
However, when i download the album photoprism seems to duplicate some, but not all photos.
The album in photoprism contains 308 photos. After the download I have a .zip with 499 files.
It's not possible for me to find out why or which photos get duplicated (the file names are changed).

Is this a wanted behaviour? Did I miss some setting? Or am I unvoluntarily selected photos two times?

If you need logs, please tell where to find them and I will happily post them!

Thanks in advance!

**Comment by lastzero** [comment]
Maybe some of these files are in other formats or have sidecar files? PhotoPrism will automatically create JPEGs and may also add them downloads

**Comment by derwaro** [comment]
How would I find put if there are sidecar files (what are those anyways?)
I didn't do any editing on the files, juat marked them as favourite, marked them for download or created an album from the selection and downloaded that.Both ways yielded the same 499 instead of 308 as signaled in photoprism.

**Comment by lastzero** [comment]
There's a difference between files and photos in PhotoPrism. Multiple files may belong to one photo and there many be multiple reasons for this, e.g. stacking, sidecar files (*.xmp, *.json,...), a combination of RAWs / videos and a JPEG preview.

**Comment by graciousgrey** [comment]
@derwaro could you check the count for each file type of the files you downloaded? 
Another possibility is, that some of the photos in your album are stacked (https://docs.photoprism.org/user-guide/organize/stacks/).

**Comment by derwaro** [comment]
Thanks to both of you @lastzero and @graciousgrey !
The problem really was photo stacking I was totally unaware of! I earlier modified the DateTimeOriginal with exiftool. This created a copy of my jpg appedning "_original" to the file name of the copy. Those copies however were still indexed, as stacks, by photoprism. Now i removed the "_original" files from my drive and reindexed the folder in photoprism.
This gives me more or less (one less to be exact) my expected download. I get 307 files/photos in my zip, but photoprism states that there are 308 items in my album. Any idea how to track/compare?
And another problem arises: In the stack:true view, all photos which had stacks (i.e. the "_original" files) are still there. They are missing the "stack" icon in the upper left, but when i click one and check in the file tab, I see the .jpg and the .jpg_original. On trying to unstack the "_original", I get "File not found, deleted?" It's not a big deal right now, but I think you should know about it.
Anyways: Thanks for the great work you do with photoprism!!

**Comment by graciousgrey** [comment]
@derwaro could you run the `purge` and `cleanup` command and check if the files are still listed under stack:true?

**Comment by graciousgrey** [comment]
We close this as there was no further feedback
