### ISSUE TITLE
Collaboration with ownphotos

### ISSUE THREAD

**Issue by coxtor** [photoprism/photoprism#110]
Hi there, this is a excellent project and is definitely needed in the open source community. However, a very similar project called own-photos has been around for a short while now. 
Support is needed on both projects. As both projects ultimately share the same goal and are open source it may be worth while to think about a collaboration.

Especially as both projects have already reached various differing milestones in terms of design, documentation and functionality.

I am not affiliated with own-photos, but I believe fusing man power or a sort of collaboration could definitely speed up development, traction and the success of such a large project.

Here the links to the front and back end repositories.

https://github.com/hooram/ownphotos
https://github.com/hooram/ownphotos-frontend

**Comment by lastzero** [comment]
Thanks for the hint! We didn't know https://github.com/hooram/ownphotos. 

Obviously there are a couple of similar projects including ownCloud. Figuring out how to collaborate will take time and we try to focus 100% on development right now. Any overhead will delay our first release.

We will come back to this later and are open to specific suggestions in the meantime. Sharing TensorFlow models might be a good start.

**Comment by pascalwhoop** [comment]
Judging by the commit history of ownphotos, their team has sort of lost interest in the project. 
Also by just looking at both projects briefly, it feels that photoprism has taken some good architectural decisions that ownphotos lacks. That said, I think it may be worth reaching out to the core developers of ownphotos to see if they want to migrate/merge some of their progress into photoprism. They built the frontend with react while you use vue but both rely on TF and there are many things that make sense for both (such as a redis DB, frontend proxies etc) @hooram @guysoft , am I wrong in assuming that life required your attention and so you are slowing down development in ownphotos?

**Comment by guysoft** [comment]
Yes, also I don't know on which way to develop. I am not much of a web
developer so any addition really needs @hooram .
I am still willing to work on it.

**Comment by lastzero** [comment]
I still have this on my todo list - won't be able to check how we can collaboration before September :/

**Comment by anthosz** [comment]
https://github.com/hooram/ownphotos/issues/137

**Comment by lastzero** [comment]
Sad, but we're still working on this - even full-time. Any support is welcome but in the worst cast we pay everything ourselves and release a commercial version to cover the expenses.

**Comment by guysoft** [comment]
@lastzero It might be worth merging enthusiasts.

**Comment by lastzero** [comment]
Sure, we answer questions via hello@photoprism.org and we accept pull requests. Maybe you can reach out to them and bring some attention to our project?

**Comment by guysoft** [comment]
@lastzero from a quick look it seems like the facial recognition is the biggest missing feature.
I am considering doing this. But I am giving more time to @hooram to respond, I really want his input on this, he might still be slow to respond.

**Comment by lastzero** [comment]
@guysoft That'd be great! Keep in mind facial recognition should use Go only (Python only to create models upfront etc) and develop from the bottom up, meaning start with code / components / data first, do unit tests and care about the UI last. The UI is something we typically experiment with and change a lot and we don't want contributors to be disappointed if we can't use their concept / design for it.

**Comment by lastzero** [comment]
Think I can close this now. Thank you very much for contributing! :)
