### ISSUE TITLE
Login with Admin password results in `invalid credentials`

### ISSUE THREAD

**Issue by harrowasu** [photoprism/photoprism#1103]
Hello, I am not able to login with the Admin password after installing the Docker version of PhotoPrism. 
When I set the argument:  `PHOTOPRISM_PUBLIC: "true"` the application works as expected. 

**What did I do?**
`wget https://dl.photoprism.org/docker/docker-compose.yml`
`nano docker-compose.yml`
I changed the following arguments
- `PHOTOPRISM_ADMIN_PASSWORD: "test1234"`
- `PHOTOPRISM_SITE_URL: "http://127.0.0.1:2342/"`   # for reverse proxy

`docker-compose up -d`

**Then I try to login on the web userinterface:** 

payload: `{"username":"admin","password":"test1234"}`

![image](https://user-images.githubusercontent.com/50948620/109390445-c374e900-7922-11eb-82cf-ecfdfcf0c174.png)

It takes 2.3 minutes before the response returns: 
![image](https://user-images.githubusercontent.com/50948620/109390519-2797ad00-7923-11eb-9f75-2957677ca37f.png)

From the error log I only get this error when I start the service: 
`docker-compose logs --tail=100 -f`
![image](https://user-images.githubusercontent.com/50948620/109390491-f9b26880-7922-11eb-982e-be90f0ce7ea7.png)

So I am not able to login into the web application. But as said previously it works when I make the application Public. 
What did I do wrong that this doesn't work? Because I could not find anything on the Github website or on Google...

Thanks for your help.

**Comment by lastzero** [comment]
Looks like the session can't be stored in the filesystem. Please make sure the complete storage path is writable for PhotoPrism.

**Comment by harrowasu** [comment]
Ok thank you for your help. 
- Can you tell me how to do this? 
- Is this within the docker container or outside it?
- which commands should I execute?
- what is the path that should be writable?

Thank you for your time.

**Comment by lastzero** [comment]
The local storage path is outside your docker container but also inside as it is mounted from outside, see https://dl.photoprism.org/docker/docker-compose.yml

```
volumes:
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "./storage:/photoprism/storage"
```

**Comment by lastzero** [comment]
`chown` and `chmod` are the right commands, but there are also graphical tools for this in all operating systems (file details / permissions dialog).

**Comment by graciousgrey** [comment]
@harrowasu did this solve your issue?

**Comment by harrowasu** [comment]
No, not yet. I have installed the Docker and PhotoPrism as user `root`  and so root has the rights to the storage folder.

```
-- content of local photoprism folder
drwxr-xr-x  5 root             root 4096 Mar 10 10:39 .
drwxr-xr-x 18 root             root 4096 Dec 10 10:26 ..
drwxr-xr-x  2 root             root 4096 Feb 27 17:20 backup
drwxr-xr-x  5 systemd-coredump root 4096 Feb 27 17:28 database
-rw-r--r--  1 root             root 6089 Feb 28 14:26 docker-compose.yml
-rw-r--r--  1 root             root 6108 Feb 27 17:22 docker-compose.ymlbackup
drwxr-xr-x  6 root             root 4096 Mar 10 10:28 storage
```
-- content of storage folder
drwxr-xr-x 6 root root   4096 Mar 10 10:28 .
drwxr-xr-x 5 root root   4096 Mar 10 10:39 ..
drwxr-xr-x 2 root root   4096 Feb 24 11:17 albums
drwxr-xr-x 4 root root   4096 Feb 27 16:30 cache
drwxr-xr-x 2 root root   4096 Feb 24 11:17 config
-rw-r--r-- 1 root root 425984 Feb 27 12:17 index.db
-rwxr-xr-x 1 root root     16 Feb 24 11:17 serial
drwxr-xr-x 3 root root   4096 Feb 27 15:19 sidecar
```
What I do not understand is why does it work when I make the application to `Public`? Then it also has the rights to store data in the `storage` folder.
If it helps, I am working on a Ubuntu 20.04.2 server without a graphical interface.

**Comment by harrowasu** [comment]
Hello, I have changed rights for the ./storage folder to 777, but no result. Any body any other idea's?

**Comment by lastzero** [comment]
Did you recursively change the permissions to 777 or just he main storage folder? It has subfolders.

**Comment by MFYDev** [comment]
I met this problem too, all settings are right because when I enable public, PhotoPrism can run normally.

But when I set public as false, this error occured.

I have recursively changed the storage folder permissions to 777 already, this issue still happens.

The error log displays that `session: open /photoprism/storage/cache/sessions.json: no such file or directory`.

I tried to create a file named sessions.json in that folder, but this error still exists.

**Comment by harrowasu** [comment]
Hi, my issue is also not solved yet. I have also recursivly set the rights to 777 without any results.

**Comment by lastzero** [comment]
- Do you use any network storage for this?
- Do you run PhotoPrism as root or a different user?
- In this case: How do you set the user id?

**Comment by MFYDev** [comment]
> * Do you use any network storage for this?

No, just local storage with 777 permission

> * Do you run PhotoPrism as root or a different user?

I run PhotoPrism as root

> * In this case: How do you set the user id?

I did not set any user id because according to the docker-compose file we download from the official website, it does not have that option.

**Comment by lastzero** [comment]
There are two ways to run PhotoPrism as a specific user - they are documented in our our example [docker-compose.yml](https://dl.photoprism.org/docker/docker-compose.yml):

```yaml
services:
  photoprism:
    environment:
      # You may optionally set a user / group id using environment 
      # variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"
````

Root should have enough permissions, so I would not expect any issues here.

I assume you mounted storage as shown in this example?

```yaml
volumes:
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "./storage:/photoprism/storage"
```

**Comment by MFYDev** [comment]
Yes, I can confirm that.

And just like I said, when I disable password proctection, eveything can run smoothly.

So I think I mounted the storage correctly.

**Comment by lastzero** [comment]
Can you open a terminal and run `ls -alh` in the `./storage/cache` folder? I'd like to see the output for further debugging this.

**Comment by MFYDev** [comment]
Sure, here is the output:

```bash
 root@LVPS-AMD5950X  ls -alh                                                     total 28K
drwxr-xr-x 6 www  www  4.0K Apr 30 01:16 .
drwxr-xr-x 6 www  www  4.0K Apr 27 00:39 ..
drwxr-xr-x 2 root root 4.0K Apr 30 01:16 albums
drwxr-xr-x 3 root root 4.0K Apr 30 01:16 cache
drwxr-xr-x 2 root root 4.0K Apr 30 01:16 config
-rwxr-xr-x 1 root root   16 Apr 30 01:16 serial
drwxr-xr-x 2 root root 4.0K Apr 30 01:16 sideca
```

And just like the output error log I pasted before, this is no sessions.json in cache folder.

All other things can becreated by PhotoPrism correctly.

**Comment by lastzero** [comment]
I'm wondering because you said you have recursively changed the storage folder permissions to 777, but the permissions are 755?

**Comment by MFYDev** [comment]
Yes, Honestly I just deleted photoprism before because changing it to 777 does not help and I cannot figure it out why.

What I pasted in the last message is a new photoprism container I just created. 

I would not mind changing permission to 777 first and recreate it again. Please allow me a sec.

**Comment by MFYDev** [comment]
Just change it to 777 and recreate containers again. Here is the output:

```bash
 root@LVPS-AMD5950X  ls -alh                                                     total 12K
drwxrwxrwx 3 root root 4.0K Apr 30 01:16 .
drwxrwxrwx 6 root root 4.0K Apr 30 01:30 ..
drwxrwxrwx 2 root root 4.0K Apr 30 01:16 thumbnails
```

Still got the same error

**Comment by lastzero** [comment]
Thanks! I'll take a look at this... we can ignore write / read errors... sessions are stored in memory while PhotoPrism is running... in the worst case, you have to sign in again after a restart. Better than not being able to sign in at all.

**Comment by MFYDev** [comment]
Thanks in advance!

BTW, would you please add bug label and remove question and waiting label to this issue?

**Comment by lastzero** [comment]
Looks like this was already the case, can you try signing in with the default password `insecure`?

I've reduced the log level for "no such file or directory" to debug as it isn't an issue at all - just means that it's a fresh installation without existing sessions.

**Comment by MFYDev** [comment]
@lastzero Hi there, sorry for the delay, I have to attend my brother's wedding before.

I just used docker image with `preview` tag, and did not change the password which default is  `insecure`.

This time it still shows `invalid credentials` but without any error logs.

It is really weird.

Am I the only one who can't log in with password? This should logically be the case for every installed user, since I've hardly changed any Docker parameters

**Comment by MFYDev** [comment]
Here is the docker compose file I use if it is useful:

<details>

```bash
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Linux / AMD64)
#
# Documentation : https://docs.photoprism.org/getting-started/docker-compose/
# Docker Hub URL: https://hub.docker.com/r/photoprism/photoprism/
#
# Please run behind a reverse proxy like Caddy, Traefik or Nginx if you need HTTPS / SSL support
# e.g. when running PhotoPrism on a public server outside your home network.
#
# ------------------------------------------------------------------
# DOCKER COMPOSE COMMAND REFERENCE
# ------------------------------------------------------------------
# Start    | docker-compose up -d
# Stop     | docker-compose stop
# Update   | docker-compose pull
# Logs     | docker-compose logs --tail=25 -f
# Terminal | docker-compose exec photoprism bash
# Help     | docker-compose exec photoprism photoprism help
# Config   | docker-compose exec photoprism photoprism config
# Reset    | docker-compose exec photoprism photoprism reset
# Backup   | docker-compose exec photoprism photoprism backup -a -i
# Restore  | docker-compose exec photoprism photoprism restore -a -i
# Index    | docker-compose exec photoprism photoprism index
# Reindex  | docker-compose exec photoprism photoprism index -a
# Import   | docker-compose exec photoprism photoprism import
# -------------------------------------------------------------------
# Note: All commands may have to be prefixed with "sudo" when not running as root.
#       This will change the home directory "~" to "/root" in your configuration.

services:
  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:preview
    container_name: photoprism
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_ORIGINALS_LIMIT: 100000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "https://mfy.photos/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "MFY's Photos"
      PHOTOPRISM_SITE_CAPTION: "Browse MFY's Life"
      PHOTOPRISM_SITE_DESCRIPTION: "MFY's personal photo album"
      PHOTOPRISM_SITE_AUTHOR: "MFY"
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/hdd/websites/mfy.photos/Pictures:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      - "/hdd/websites/mfy.photos/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "/hdd/websites/mfy.photos/storage:/photoprism/storage"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/hdd/websites/mfy.photos/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

# Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
#
#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    restart: unless-stopped
#    environment:
#      WATCHTOWER_CLEANUP: "true"
#      WATCHTOWER_POLL_INTERVAL: 7200 # Checks for updates every two hours
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "~/.docker/config.json:/config.json" # Optional, for authentication if you have a Docker Hub account
```bash

</details>

**Comment by wasuint** [comment]
@MFYDev could you give me a more detailed description of how you solved this? Which files did you delete? And which nginx file did you use? Thanks in advance.

**Comment by MFYDev** [comment]
Hi @wasuint , here is my personal docker compose file:

<details>

```bash
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Linux / AMD64)
#
# Documentation : https://docs.photoprism.org/getting-started/docker-compose/
# Docker Hub URL: https://hub.docker.com/r/photoprism/photoprism/
#
# Please run behind a reverse proxy like Caddy, Traefik or Nginx if you need HTTPS / SSL support
# e.g. when running PhotoPrism on a public server outside your home network.
#
# ------------------------------------------------------------------
# DOCKER COMPOSE COMMAND REFERENCE
# ------------------------------------------------------------------
# Start    | docker-compose up -d
# Stop     | docker-compose stop
# Update   | docker-compose pull
# Logs     | docker-compose logs --tail=25 -f
# Terminal | docker-compose exec photoprism bash
# Help     | docker-compose exec photoprism photoprism help
# Config   | docker-compose exec photoprism photoprism config
# Reset    | docker-compose exec photoprism photoprism reset
# Backup   | docker-compose exec photoprism photoprism backup -a -i
# Restore  | docker-compose exec photoprism photoprism restore -a -i
# Index    | docker-compose exec photoprism photoprism index
# Reindex  | docker-compose exec photoprism photoprism index -a
# Import   | docker-compose exec photoprism photoprism import
# -------------------------------------------------------------------
# Note: All commands may have to be prefixed with "sudo" when not running as root.
#       This will change the home directory "~" to "/root" in your configuration.

services:
  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:preview
    container_name: photoprism
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "REDACTED"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_ORIGINALS_LIMIT: 100000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "REDACTED"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "REDACTED"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "REDACTED"
      PHOTOPRISM_SITE_CAPTION: "REDACTED"
      PHOTOPRISM_SITE_DESCRIPTION: "REDACTED"
      PHOTOPRISM_SITE_AUTHOR: "REDACTED"
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "REDACTED/Pictures:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      - "REDACTED/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "REDACTED/storage:/photoprism/storage"

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "REDACTED/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: REDACTED

# Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
#
#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    restart: unless-stopped
#    environment:
#      WATCHTOWER_CLEANUP: "true"
#      WATCHTOWER_POLL_INTERVAL: 7200 # Checks for updates every two hours
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "~/.docker/config.json:/config.json" # Optional, for authentication if you have a Docker Hub account

```

</details>

Please note: Currently we should use preview tag docker image.

Please remove all files in /storage and /database

**Comment by oozry12** [comment]
same issue after switch to preview version.
Maybe is about Reverse Proxy.Datebase check the original URI.

**Comment by vanderneut** [comment]
I suddenly have this exact same issue as well. I have logged in several times before with admin successfully, and now it finally completed the scan of all my photos, it no longer lets me log in. No idea what to do :-/

I'm running PhotoPrism in Docker on a Synology NAS.

**Comment by lastzero** [comment]
Can you try again with our latest preview? I recommend checking the logs and making sure your intance can connect to the database, that's the usual cause for failed logins.

**Comment by Eirikr70** [comment]
Same issue here. Found no way out. Photoprism in Docker on a Raspberry Pi.

**Comment by lastzero** [comment]
Please open a GitHub Discussion for this and share all details like the version, database, and any additional tools you use such as Portainer. We cannot help you otherwise. Thank you!

**Comment by MiltonFriedman33** [comment]
I have a similar issu on Synology 7.1 and docker images `latest` or `preview`
- I tried installing Photoprism from this tutorial https://www.wundertech.net/how-to-setup-photoprism-on-a-synology-nas.
- I have database admin password setup via `PHOTOPRISM_ADMIN_PASSWORD` env var to `123`. 
- The local db/storage seems like its working, Photoprims was able to create some directories
![image](https://user-images.githubusercontent.com/112814189/188318202-a3acfc5a-b5a1-4579-8092-65724e498d97.png
- When I log in as admin/123 I get a message `Invalid credentials
- The logs shows
  - `DEBU[2022-09-04T14:40:31Z] session: open /photoprism/storage/cache/sessions.json: no such file or directory 
  - and a `400 error on session creation 
`DEBU[2022-09-04T14:42:33Z] server: POST /api/v1/session (400) [1m1.42992191s]` - the request is quite long, 1m1s

Not sure how to debug this further

**Comment by MiltonFriedman33** [comment]
My discussion on this issue https://github.com/photoprism/photoprism/discussions/2681

and the answer was

1. ssh into Synology
2. `sudo docker ps` to get the container name
3. `sudo docker exec -ti photoprism-photoprism1 photoprism passwd` to change the password, set it to at least 6 characters

After this, I was able to log in with the new password

**Comment by epheterson** [comment]
> My discussion on this issue #2681
> 
> and the answer was
> 
> 1. ssh into Synology
> 2. `sudo docker ps` to get the container name
> 3. `sudo docker exec -ti photoprism-photoprism1 photoprism passwd` to change the password, set it to at least 6 characters
> 
> After this, I was able to log in with the new password

Thanks for sharing this, made a new instance today with the docker compose and had to do this step before I could login for the first time. Very odd, it's like it didn't pick up the Docker Environment Variable. When I made a container using sqlite it worked fine, but wanted to change to marianadb (via new instance) and that's where it required this step.

**Comment by Sn3akyP3t3** [comment]
> My discussion on this issue #2681
> 
> and the answer was
> 
>     1. ssh into Synology
> 
>     2. `sudo docker ps` to get the container name
> 
>     3. `sudo docker exec -ti photoprism-photoprism1 photoprism passwd` to change the password, set it to at least 6 characters
> 
> 
> After this, I was able to log in with the new password

I just setup a vanilla docker container from photoprism/photoprism.  I restarted it after realizing I didn't change the password and ended up having to use this solution to correct whatever password had actually been saved to the default database.

**Comment by epheterson** [comment]
> > My discussion on this issue #2681
> > and the answer was
> > ```
> > 1. ssh into Synology
> > 
> > 2. `sudo docker ps` to get the container name
> > 
> > 3. `sudo docker exec -ti photoprism-photoprism1 photoprism passwd` to change the password, set it to at least 6 characters
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After this, I was able to log in with the new password
> 
> I just setup a vanilla docker container from photoprism/photoprism. I restarted it after realizing I didn't change the password and ended up having to use this solution to correct whatever password had actually been saved to the default database.

Your scenario is expected (not a bug) if the insecure password was present on the first time the container launched. The password environment variable is only ready initially, on first launch. In our scenario (the issue this bug is tracking) the password *was* updated prior to the first launch.

Another workaround for your scenario would've been to empty your config directory and restart the container.

**Comment by danjeffree** [comment]
had this issue, heres how I fixed it incase anyone in the future reads this.

stop photoprism if running.

chmod both storage and database 777

start photoprism.

login with "insecure" as password

go to settings>account>change password.

Im guessing that when it initially runs with sudo, there can sometimes be permission issues.

**Comment by Chrisbr68** [comment]
I had this issue today as I'm getting up and running on my pi. The issue was the filesystem was full. Swapped to a bigger sd card and then I was able to log in nothing else needed changing once the root partition was resized. I didn't see this point mentioned in the official documentation. I dont know if anyone here is an official.

**Comment by lastzero** [comment]
Anyone else who has login problems may also have run into this issue (dollar signs must be escaped with `$$`, e.g. in passwords):
- https://github.com/photoprism/photoprism/issues/3913

We've updated our documentation to provide more guidance on how to use Docker Compose:
- https://docs.photoprism.app/known-issues/#docker-compose
- https://docs.photoprism.app/developer-guide/technologies/yaml/#docker-compose

@Chrisbr68 Full server disks as a cause for connection problems and server errors are listed in several of our checklists (not explicitly though in the *Cannot Log In* checklist, which can be found below, so you are welcome to send a pull request with improvements):

- https://docs.photoprism.app/getting-started/troubleshooting/#connection-fails
- https://docs.photoprism.app/getting-started/troubleshooting/#cannot-log-in

**Comment by Chrisbr68** [comment]
I went back and looked at it and you're right. It should specifically be in
that section to make it easier. The photo prism documentation overall needs
a total overhaul it's not very user friendly. I dont know how to do the
pull request, its a good learning opportunity for me but I'm also
chronically unwell so I won't be tackling it at the moment.

**Comment by lastzero** [comment]
@Chrisbr68 Total overhaul? Please don't hesitate to help if you know how to write better docs:

(1) Clicking on the "Edit" button in the upper right corner of a page will take you to the related Markdown file on GitHub:

![edit](https://github.com/photoprism/photoprism/assets/301686/9b1d2950-96f9-450c-a239-f12701071800)

(2) On GitHub, you again click on the "Edit" button in the upper right corner to edit the page and then submit the changes as a pull request:

- https://github.com/photoprism/photoprism-docs/blob/master/docs/getting-started/troubleshooting/index.md

(3) That's it! 🎉

**Comment by Chrisbr68** [comment]
Yeah man i stand by that statement as drastic as it sounds. When I am
recovered I can definitely help!

**Comment by gianlucaf81** [comment]
I often get the invalid password error too.
I use a container in a synology nas. I usually solve it by restarting the container but after a bit of processing of new photos I get the error again.

**Comment by lastzero** [comment]
Maybe the database is down for some reason? Did you check the service logs yet and go through the troubleshooting checklist we provide for this in our documentation?

**Comment by AlfredoCode** [comment]
Same thing happens to me. I have to change the docker compose's auth mode to public, then restart the container, change the auth mode back to password and then restart the container again and then it works. 

But after restarting the server I have to do the steps above again.

**Comment by cruzerkk** [comment]
For anyone facing this issue after installing from the official repo on unraid, here is how I fixed it:

1. Open unraid terminal
2. Run `docker ps` and note down CONTAINERID
3. Run `docker exec -it CONTAINERID photoprism users reset —yes`
4. Restart container and try logging in using username : admin and password : <yourInitialAdminPassowrd>

**Comment by JoshuaFramptonUnofficial** [comment]
FYI if your server is full, then no more data can be written, so ssh into your server and free up some space then try again 👍

**Comment by ZhiyeTang** [comment]
> For anyone facing this issue after installing from the official repo on unraid, here is how I fixed it:
> 
> 1. Open unraid terminal
> 2. Run `docker ps` and note down CONTAINERID
> 3. Run `docker exec -it CONTAINERID photoprism users reset —yes`
> 4. Restart container and try logging in using username : admin and password :

@cruzerkk This works for me!!! Thanks for your sharing.

**Comment by Smicky007** [comment]
It also worked for me!!

**Comment by aswiderek-rtbh** [comment]
I have the same problem.
After configuring OpenID, logging in with a Google account works. However, after logging out and then logging in to the local admin account, logging in via Google stops working and I receive the message "invalid credentials".

**Comment by lastzero** [comment]
@aswiderek-rtbh Please open a GitHub Discussion and describe the exact steps, user accounts, and your OIDC/authentication settings so it's possible to reproduce the issue. Thank you!
