### ISSUE TITLE
"/var/lib/photoprism" is not mentioned in the Docker compose file.

### ISSUE THREAD

**Issue by kwm1800** [photoprism/photoprism#1107]
When I created Photoprism via docker compose, it seems it automatically created a volume for mounting "/var/lib/photoprism".

It should be mentioned at the docker compose file as required volume/binding.

**Comment by lastzero** [comment]
It's a backup volume in case you didn't mount writable storage. If you know what you're doing you may mount it externally as well, otherwise please ignore it.
