### ISSUE TITLE
Maps fail to render when using a reverse proxy with http auth

### ISSUE THREAD

**Issue by callahan22** [photoprism/photoprism#1109]
When setting up the nginx reverse proxy using the config supplied here as a rough template: https://docs.photoprism.org/getting-started/proxies/nginx and adding the http auth as well as some other bits to take it from an "F" on securityheaders.com to an "A", I'm seeing errors in the dev tools console relating to not being able to render the map as I have passed my http auth creds in the URL. Here's my reverse proxy config:

```
server {
  listen 80;
  server_name photos.mywebsite.net;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl http2;
  server_name photos.mywebsite.net;
  client_max_body_size 500M;
  auth_basic "$site_authentication";
  auth_basic_user_file /etc/nginx/.htpasswd;

  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://10.0.4.3:2342;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(self 'https://photos.mywebsite.net'), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
  }

# access_log /var/log/nginx/access.log combined_ssl;
    access_log /var/log/nginx/photos.mywebsite.net.access.log;
    error_log /var/log/nginx/photos.mywebsite.net.error.log;

    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_certificate /etc/letsencrypt/live/photos.mywebsite.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/photos.mywebsite.net/privkey.pem; # managed by Certbot
}
```

There is additional config that allows me to bypass authentication if connecting from my internal LAN but I've not included that for the sake of keeping it relevant. When I access the site internally via:

`https://photos.mywebsite.com`

and log in at the PhotoPrisim login page, the map renders. Now if I hit the site with: 

`https://my_http_auth_username:my_http_auth_password@photos.mywebsite.net`

the map fails to render. The first error (which appears regardless of how I access the site but seems to have no effect) but suggests that I have formatted the Permissions-Policy header incorrectly (I can't see where), is:

`Error with Permissions-Policy header: Parse of permission policy failed because of errors reported by structured header parser.`

The 2nd error that only appears on the site where I use the username and password in the URL and is causing the map section to not render the map is:

```
Uncaught TypeError: Failed to construct 'Request': Request cannot be constructed from a URL that includes credentials: https://my_http_auth_username:my_super_secret_password@photos.mywebsite.net/static/geo/world.json
    at f4dc83bb-7442-4a2c-94a9-2c0824815851:1
    at be (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at Object.e.getJSON (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at n.loadGeoJSON (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at n._loadData (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at n.loadData (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at Rc.processTask (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at Rc.process (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
    at MessagePort.Mc.MessageChannel._channel.port2.onmessage (f4dc83bb-7442-4a2c-94a9-2c0824815851:1)
```

Ordinarily, I would ignore this and assume the site just doesn't work with passing the username and password in the URL except for the fact that the app you guys make (https://github.com/photoprism/photoprism-mobile), supports both the http authentication and standard PhotoPrism authentication. From that, I assumed the site worked with the http authentication.

If anyone can spot something I've missed or setup incorrectly, please let me know. I've not included my docker-compose file as it didn't seem relevant to this issue but I can should you require it.

Thanks.

**Comment by lastzero** [comment]
First of all: The photoprism-mobile app is a community project, not maintained by us.

I wouldn't be surprised if the additional security headers and auth you added may cause problems with websockets or the JS maps library, for example because the map tiles are loaded from the Internet and not your local server. The config as shown in our docs should work. If not, let us know. We can't help with individual configurations.
