### ISSUE TITLE
Photos are not showing after restarting docker

### ISSUE THREAD

**Issue by windlok1010** [photoprism/photoprism#111]
I am running photoprism on unraid using docker and linked the photos to /srv/photoprism/photos/originals. After running `photoprism index`, all the photos are showing on the website under photo. However, once I restart the docker, I have to run `photoprism index` again or there is no photos.

Please let me know what I should provide so that you can look into it.

(Thank you very much for developing photoprism. I have been looking for a gallery that allow me to keep my existing file structure for some time and I really think photoprism is the one. Thanks!)

**Comment by lastzero** [comment]
It's probably because you don't use an external database and the internal database files are not on a persistent volume (`/srv/photoprism/server/database`). Note that we don't have a final release yet and the current code is only for testing.

**Comment by lastzero** [comment]
You're welcome to send a pull request for our docs: https://github.com/photoprism/photoprism-docs/blob/master/docs/setup.md

**Comment by windlok1010** [comment]
Just changed the volume mapping and all is good now. I cannot wait for the final release!
