### ISSUE TITLE
Histogram Date Range Selection

### ISSUE THREAD

**Issue by jkgeyti** [photoprism/photoprism#1113]
This is a feature request for adding histogram-enabled range sliders to aid date selection. Pictures are often taken in bursts (like on holidays), and histograms are a powerful way of estimating start/end dates of events at a glance.

A vue-based starting point exists at:

![image](https://user-images.githubusercontent.com/617033/109793193-3ffe1500-7c0c-11eb-9f40-92a4e03c8e60.png)
https://vuejsexamples.com/range-slider-with-histogram-for-vue-js/

For a live example to play around with, see for example Kibana at https://demo.elastic.co/app/discover

This would be particularly useful on the search page, but could be useful on most pages I think.

**Comment by graciousgrey** [comment]
That's already on the roadmap :) https://github.com/photoprism/photoprism/issues/214
