### ISSUE TITLE
Ability to change hostname in share album

### ISSUE THREAD

**Issue by kris-nova** [photoprism/photoprism#1114]
I run photoprism in a container and it binds to `0.0.0.0` and runs as `localhost`. 

Anyway when I share an album it will pre-populate the URI with `localhost` instead of the domain it's actually running on.

Can we add a flag or environmental variable to push a custom hostname through? 

Unsure what the "correct" approach is at doing this but if somebody tells me what the success criteria would be here im happy to open a PR

![Screenshot from 2021-03-03 22-54-42](https://user-images.githubusercontent.com/13757818/109923332-7b7ffa00-7c73-11eb-9d17-c23e533478dc.png)

**Comment by lastzero** [comment]
You may configure the base url using `PHOTOPRISM_SITE_URL` 👍 

See https://docs.photoprism.org/getting-started/config-options/
