### ISSUE TITLE
Google Photos "-edited" missing date/not reading exif

### ISSUE THREAD

**Issue by shasycouk** [photoprism/photoprism#1118]
Hi Michael, Theresa, and everyone else,

Thanks so much for this great app. I'm running this using docker on my unRAID server and I love how snappy the UI feels. Great work.

PhotoPrism is currently indexing my Google Takeout. Most of it works fine, but I sadly have an ever-growing number of photos that don't have their "date taken" set right. These are all -edited.jpg photos. As we know, Google Photos only provides one .json file per original and edited combo. The original received the right metadata but the edited version has as creation date the day of the unzipping and no "date taken" set. 

I'm wondering whether this is expected behaviour. I didn't run exiftool manually as I thought PhotoPrism would take care of the exif (as per the docs.)

**This is the (relevant part of) the exif:** 
`  "title": "FB_IMG_1424441459711.jpg",
  "description": "",
  "imageViews": "0",
  "creationTime": {
    "timestamp": "1424454441",
    "formatted": "20 Feb 2015, 17:47:21 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1424441459",
    "formatted": "20 Feb 2015, 14:10:59 UTC"
  }`

**Example files:**
FB_IMG_1424441459711-edited.jpg | No "date taken" and "creation date" is date of unzipping
FB_IMG_1424441459711.jpg | Date correctly read from exif
FB_IMG_1424441459711.jpg.json 

Is there a way to fix this after the initial indexing has finished? There's still (ten) thousands of photos left and I don't want to risk stop indexing it now. I have experimental features set to on.

Thanks so much for your work. I just became a patron and while it's only little that I contribute, I hope it's helping you out somewhere.

All the best,
Benedikt

**Comment by shasycouk** [comment]
This might have to do this #1051 also? I guess if it was stacked it wouldn't be a big issue. Not sure whether it's the same problem.

**Comment by lastzero** [comment]
Thanks for reporting this!

The taken date may depend on which file is marked as primary... reindexing should help once you've deleted the *-edited files (you may run the purge / cleanup commands in a terminal first).

Can you provide us with example files for debugging, either attached to this issue or via email to hello@photoprism.app?

Maybe there's an issue with date parsing as well.

**Comment by lastzero** [comment]
Only way to "fix" this is by improving our Google Photos import as this is pretty "non standard". I've change the issue type from `bug` to `todo`.

**Comment by graciousgrey** [comment]
I will close this issue as duplicate it will be done in the scope of this https://github.com/photoprism/photoprism/issues/1122
