### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by thielepaul** [photoprism/photoprism#1119]
The docker build for [`docker/photoprism/Dockerfile`](https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile#L114) fails with the following error:
```
"Dockerfile parse error line 114: Unknown flag: chmod"
```

As far as I can see, there is no `--chmod` flag for the `COPY` command:
https://docs.docker.com/engine/reference/builder/#copy

This bug was observed on the dockerhub build infrastructure.

**Comment by lastzero** [comment]
It's because we use a newer Docker version. Is it possible for you to upgrade?

**Comment by lastzero** [comment]
See https://github.com/moby/moby/issues/34819

**Comment by thielepaul** [comment]
thanks for the fast reply! As mentioned this error happens on the hub.docker.com infrastructure, so I can not upgrade, but I suppose it will be upgraded at some point
