### ISSUE TITLE
Graceful shutdown of servers and other goroutines

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#112]
**As a user, I want all goroutines to shut down gracefully so that I don't lose data when I quit PhotoPrism.**

See:
* https://github.com/photoprism/photoprism/blob/develop/internal/server/server.go#L40
* https://github.com/photoprism/photoprism/blob/develop/internal/tidb/server.go#L109

So far we have the web service and tidb running... in the future there might be goroutines for indexing / syncing as well... so we need a general approach that enables us to shut down all processes without losing data.

When this is done, we can start working on background processes for indexing / importing.

**Comment by vedhavyas** [comment]
@lastzero i'll this one up

**Comment by lastzero** [comment]
Related: Users should be able to start photoprism in the background (detached mode) and stop it again with a "stop" command.

**Comment by lastzero** [comment]
This is what currently MAY happen, since the database doesn't wait for the rest of the app to close connections and shutdown gracefully:

```
INFO[2019-05-30T00:25:49Z] received interrupt signal - shutting down    
INFO[2019-05-30T00:25:49Z] closed database connection                   
INFO[2019-05-30T00:25:49Z] web server closed                            
INFO[2019-05-30T00:25:49Z] please come back another time                
INFO[2019-05-30T00:25:49Z] database server closed                       
ERRO[2019-05-30T00:25:49Z] close tcp 127.0.0.1:4000->127.0.0.1:48812: use of closed network connection
github.com/pingcap/errors.AddStack
	/go/pkg/mod/github.com/pingcap/errors@v0.11.1/errors.go:174
github.com/pingcap/errors.Trace
	/go/pkg/mod/github.com/pingcap/errors@v0.11.1/juju_adaptor.go:15
github.com/pingcap/tidb/server.closeConn
	/go/pkg/mod/github.com/pingcap/tidb@v2.1.8+incompatible/server/conn.go:168
github.com/pingcap/tidb/server.(*clientConn).Close
	/go/pkg/mod/github.com/pingcap/tidb@v2.1.8+incompatible/server/conn.go:162
github.com/pingcap/tidb/server.(*clientConn).Run.func1
	/go/pkg/mod/github.com/pingcap/tidb@v2.1.8+incompatible/server/conn.go:468
github.com/pingcap/tidb/server.(*clientConn).Run
	/go/pkg/mod/github.com/pingcap/tidb@v2.1.8+incompatible/server/conn.go:495
github.com/pingcap/tidb/server.(*Server).onConn
	/go/pkg/mod/github.com/pingcap/tidb@v2.1.8+incompatible/server/server.go:384
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337 
```
