### ISSUE TITLE
thumbnail storage

### ISSUE THREAD

**Issue by dovy6** [photoprism/photoprism#1124]
Did something change with thumbnail storage? I woke up today, went to check my Unraid server, and found all my Docker containers were off. Wondering what was going on, I started researching, and found that my "Backup appdata" script had stopped all of my containers (at 2 am) and hadn't restarted them yet (at 9 am.) Doing some further research, I come to find that the reason is is because it's still backing up my appdata for /photoprism/cache/thumbnails, which has grown to over 200 gigabytes in size, with over 3 million small files. I will add this folder to be excluded from the backup script so this doesn't happen in the future, but I was wondering if it would be possible to map out the thumbnails to a separate share, or into my /Pictures folder? I'd prefer to keep the database, config files, etc, on my cache drive (/mnt/cache/appdata/photoprism) and the photos and thumbnails in /mnt/user/Pictures. 

I appreciate all the hard work you guys are doing on this amazing project. Thanks!

**Comment by lastzero** [comment]
You can of course store thumbs in a different folder via `PHOTOPRISM_CACHE_PATH`:

https://docs.photoprism.org/getting-started/config-options/

You may also increase compression and/or reduce pre-rendered sizes to save storage if you're ok with less quality and/or performance.

**Comment by dovy6** [comment]
I'd prefer to keep the config path the same except for the thumbnails folder. Would that be possible?

**Comment by lastzero** [comment]
Sure, `PHOTOPRISM_CACHE_PATH` and `PHOTOPRISM_CONFIG_PATH` are independent.

**Comment by dovy6** [comment]
OK, thanks, so I added 'PHOTOPRISM_CACHE_PATH'='/mnt/user/Pictures/cache'. That look right to you? Will that move folders automatically, will it regenerate, or should I move the folders over manually?

**Comment by dovy6** [comment]
time="2021-03-08T10:49:32-05:00" level=fatal msg="can't create /mnt/user/Pictures/cache: please check configuration and permissions"
is the PHOTOPRISM_CACHE_PATH relative to the container side or the server side? Should that be /photoprism/originals/cache?

**Comment by lastzero** [comment]
Note that you need to mount that folder separately in `docker-compose.yml` (volumes section) if you change it.

**Comment by dovy6** [comment]
copying >200 gigabytes in over 3 million tiny files - RIP
Going to take over 6 hours. 3207644 files.
Hope I did it correctly...

**Comment by dovy6** [comment]
Restarted the container, getting this running through my log, don't know what it means hopefully nothing bad - 
time="2021-03-08T17:30:03-05:00" level=info msg="photo: won't update title, pqmsqne13bmcfqi3 was modified"

**Comment by lastzero** [comment]
No, it's not bad. Seems you edited it manually.

**Comment by dovy6** [comment]
OK, so here's where I appear to stand right now. In my main picture storage folder, I have "Number of files: 555,834 (reg: 555,679, dir: 155)" for a file size of "Total file size: 311,176,880,176 bytes"

In my thumbnails folder, I have "Number of files: 4,850,512 (reg: 4,846,143, dir: 4,369)" for a file size of "Total file size: 253,380,584,757 bytes"

Is it typical that ~550k pictures generate ~4.8 Million thumbnails? Or that ~312 GB of pictures generate ~253 Gb of thumbs?

Is this the typical for everyone? What settings can I select to limit thumbnail generation to say 1 or 2 per photo, instead of 10 or 11?

**Comment by graciousgrey** [comment]
By default 11 thumbnails are created per photo.
You can configure the jpg quality to get smaller thumbs or you can configure the static size limit to get fewer thumbs created per photo. See https://docs.photoprism.org/user-guide/settings/advanced/#jpeg-quality

**Comment by dovy6** [comment]
static thumb size seems to limit the *max* size of the thumbnails. Any way
to limit the minimum size? I see no reason to create so many tiny thumbs
unless I'm missing something.

Thanks so very much

**Comment by graciousgrey** [comment]
We do not have this option, as we need the small thumbnails for image and color detection and for the places view.

**Comment by dovy6** [comment]
Hmm, ok.
While changing things arounds, I appear to have accidently fed PP the /cache/thumbnails folder, so started recursively reading each of the thumbnails, and creating thumbs for those thumbs, etc. I'd like to nuke and start over. I will delete the thumbnails, and re-index. I'd like to start the database from scratch. What else should I delete to get a fresh start? 

Thanks for your help.

**Comment by StephenBrown2** [comment]
Be sure to nuke your storage directory, I had attempted to reorganize and restart but left that there and PP recreated a bunch of albums with no-longer-existent photos.

**Comment by lastzero** [comment]
To start with a fresh index and free up storage, simply delete that database (there is a reset command for this too) as well as storage, sidecar and cache folders.
