### ISSUE TITLE
Metadata: Index physical "focal length" as well, not just the 35mm equivalent

### ISSUE THREAD

**Issue by ThomasCRichmond** [photoprism/photoprism#1126]
PhotoPrism seems to multiply focal length times a focal length multiplier for a camera's format and show that in the details pane as "Focal Length". And that product is not what "focal length" represents.

For example, for pictures taken with a 25mm focal length on a 4:3 sensor (having a focal length multiplier of 2x), PhotoPrism shows the focal length as "50mm". Which is incorrect. The focal length is 25mm.

Please provide the actual focal length in a field name"focal length". Another field for "equivalent focal length" wouldn't bother me, but that's a separate issue.

**Comment by lastzero** [comment]
Might be the 35mm equivalent. We don't actively calculate this but read it from Exif metadata.

**Comment by ThomasCRichmond** [comment]
OK, I used exiftool directly on a sample file and got the following related fields:
Focal Length                    : 38.0 mm
Focal Plane Diagonal            : 21.6 mm
Focal Length In 35mm Format     : 76 mm
Focal Length                    : 38.0 mm (35 mm equivalent: 76.0 mm)

"Focal Length" is stated correctly here at 38mm. Focal Length In 35mm Format is also stated correctly at 76mm. And another line combines both. But it doesn't say that "focal length" is 76mm because it isn't 76.

So the bug here is either the name of the field or the value of the field. The field should either say "Focal Length In 35mm Format" or the value should be whatever corresponds to that first "Focal Length", which would be 38 in this example.

**Comment by lastzero** [comment]
You're right, we're using the equivalent so that pictures can be classified as tele, wide-angle, and standard. If this is important to you and others, we can add an additional field for the physical focal length in a later release. What exactly do you need it for?

**Comment by ThomasCRichmond** [comment]
I don't need it, except that when I see a field that says "focal length", but it shows something that isn't focal length, then I file a bug.

**Comment by lastzero** [comment]
It's not a bug but a feature as we use it to compare images. That wouldn't work otherwise. Would you like to add a note to our docs? It's also possible to edit the field labels via gettext, although users with no background in physics or photography might be more confused than before...
