### ISSUE TITLE
Indexing hangs on the same spot regardless of restart. Renaming folders helped.

### ISSUE THREAD

**Issue by Zaijo** [photoprism/photoprism#1127]
Hello.

In my setup I use Photoprism with Nextcloud synced folder as original photos mount. 

I have a problem indexing my photos. It hangs for an hour (probably indefinetly) on the same spot ( Library page shows indexing on a directory path (not a folder path)). Restarting the container doesn't help.

This problem is happening since I started using Photoprism, I'm currently using docker image `f81f7b1e47a4`.

The one thing that actually helps is renaming some folder along the path to the "problematic" directory. But that's a pretty annoying workaround.

**Comment by lastzero** [comment]
Try adding the "spot" to a `.ppignore` file as described in our docs.

**Comment by Zaijo** [comment]
Thanks for quick reply @lastzero . I'll try. I'm only afraid that it hangs on a specific file even before the debug log would print the name. Is that possible? Any .DS_Store or any other macos specific issues so far?

**Comment by lastzero** [comment]
Hidden files and folders starting with a . should be ignored automatically
