### ISSUE TITLE
UX: Autocomplete in "add to album" dialog is not responsive

### ISSUE THREAD

**Issue by Zaijo** [photoprism/photoprism#1130]
Steps to reproduce this bug (introduced some time in february in `latest`):

1. Open search
2. Mark some photos
3. Click icon "add to album"
4. Start typing
5. No suggestions come in place, the dropdown stays the same

![Screenshot 2021-03-10 at 10 03 16](https://user-images.githubusercontent.com/1964908/110605172-223f2b80-8189-11eb-8361-f9e9425519ed.png)

Image version: `f81f7b1e47a4`

**Comment by graciousgrey** [comment]
Thanks for reporting!

**Comment by lastzero** [comment]
Started a new preview build, available for testing on [demo.photoprism.app](https://demo.photoprism.app/browse) soon:

https://docs.photoprism.app/getting-started/updates/#development-preview
