### ISSUE TITLE
All photos taken in portrait mode are being imported as landscape

### ISSUE THREAD

**Issue by justinosdotnet** [photoprism/photoprism#1134]
All photos are being displayed in landscape view, even those which were taken in portrait mode.  However, much older pictures that have been indexed initially have been properly imported as either landscape or portrait.  Running on ubuntu server in docker.

**Comment by graciousgrey** [comment]
It might be that your photos metadata have an invalid value for orientation. In this case we use landscape as default see (https://github.com/photoprism/photoprism/issues/1052).

Could you check your files metadata using 

```exiftool -j example.jpg```
or 
```exif-read-tool -f example.jpg``` ?

**Comment by justinosdotnet** [comment]
Thanks for the tip!

Should I be looking at the Orientation variable in the output?  Because I took 2 identical pictures as a test, in both orientations.

The landscape picture taken gives the following:

"Orientation": "Horizontal (normal)"

Which comes out as expected, but the portrait photo gives the following:

"Orientation": "Rotate 90 CW"

And as discussed, this photo is appearing in Photoprism as a landscape photo. 

So yes, judging from this data the picture is being rotated, thus making all portraits cone out as landscape.

I'm not too familiar with iphone metadata, but are you saying that my problem lies with my source (iphone) and not Photoprism?

Thanks!

**Comment by graciousgrey** [comment]
Yes, it sounds like something is wrong with the metadata of your photos. If you open one of the portraits in another image viewer - how is it displayed? Could you send us one photo for testing to hello@photoprism.app ?

**Comment by lastzero** [comment]
@graciousgrey @justinosdotnet Should there be images for testing in our inbox?

Sometimes metadata contains duplicate / conflicting information. We can't debug issues like this remotely.

**Comment by justinosdotnet** [comment]
> @graciousgrey @justinosdotnet Should there be images for testing in our inbox?
> 
> 
> 
> Sometimes metadata contains duplicate / conflicting information. We can't debug issues like this remotely.

Sorry about that, I was hoping to fix the issue myself with the info regarding the metadata mentioned earlier.  No luck so far so I will be sharing some affected photos tomorrow and maybe you can help.  Thanks for the follow up.

**Comment by graciousgrey** [comment]
Those photos have orientation 6 = Rotate 90 CW set. 
You can either set the correct orientation with exiftool like `exiftool -Orientation="Horizontal (normal)" filename.jpg` and then reindex your files. Or you wait for https://github.com/photoprism/photoprism/issues/464 to be implemented.
