### ISSUE TITLE
Indexing crashes after 9k pics

### ISSUE THREAD

**Issue by edoardoo** [photoprism/photoprism#1135]
Hello and thanks for this amazing project!

**System**: Raspberry PI 4
**RAM**: 4GB
**Swap**: 100MB
**Version**:  210222-ac5a9d5e-Linux-aarch64 
**Deployment**: Docker 

### TL;DR
Indexing after 9k pics crashes and freezes Raspberry PI.  
`PHOTOPRISM_WORKERS` is ignored.

### Description: 
It's a fresh install.
The first time it indexed almost 9k pictures without problems, then the indexing stopped.
So I tried to start it again from the web interface.   
A huge amount (>8) of threads with the command `photoprism start` is spawned.
This causes all the CPUs to be at 100% all the time, but most importantly it saturates the RAM and finally eat out all the SWAP.
In the end, the container restarts and everything goes back to normal.
If I try to index again (without rebooting) the raspberry will freeze after a picture and only a reboot fixes it.  
After reboot, the process is the same as from `So I tried to start it again from the web interface. `

### Additional details: 
I already set `PHOTOPRISM_WORKERS: 1` (it was set to 2) into the `docker-compose.yml`, but the behaviour hasn't changed.
I've pulled the latest version using `docker-compose pull`.

**Comment by edoardoo** [comment]
I opened a bash into the container and checked on the number of workers, it was still 2 even tho I rebooted the raspberry multiple times. 
`docker-compose down && docker-compose up -d` updated the number of workers. 
While this made things better, indexing still crashes after ~1000 pics. 
What I noticed is that RAM get progressively filled up until there isn't anything left of it.
I also noticed in `htop` that more than 8 processes with `photoprism start` are spawned (it hasn't changed). 
If it can help, the first 9k pictures were taken using older phones (so they're probably smaller), while the latest 2k are taken with a newer model (and also bigger in size).

**Comment by kvalev** [comment]
You can always try and exclude larger files from being indexed using `PHOTOPRISM_ORIGINALS_LIMIT`

**Comment by lastzero** [comment]
You may run `photoprism config` in a terminal to see the actual config, including the number of workers. So no guessing needed here. A command reference is part of our Getting Started docs as well as our docker-compose.yml example files.

The number of threads doesn't matter as long as they are idle. They are needed if you open a page in a browser so that more than one preview can be downloaded / shown at a time. Otherwise, the app would feel really slow.

**Comment by graciousgrey** [comment]
@edoardoo any update on this?

**Comment by edoardoo** [comment]
@lastzero Indeed `photoprism config` is how I was able to determine the current number of workers was not updating until the container was restarted manually.

@graciousgrey The only solution was to reduce at a minimum the number of workers, but even at 1 I had to manually restart the indexing a couple of times. I'm not currently dedicating much time to this setup since I still haven't found a stable solution for mobile syncing.

**Comment by lastzero** [comment]
Did you try PhotoSync yet? Uploads via WebDAV incl auto index / import. Very stable.

**Comment by edoardoo** [comment]
Hey there, sorry for late reply.
I wanted to avoid closed source softwares with internet access to sync my pictures.
At the moment I'd be happy with a mono directional rsync for Android.
I'm gonna keep looking for a solution and in case I find something satisfying I'll be happy to share it with the Prism community 😊

**Comment by dror3go** [comment]
@edoardoo How about Nextcloud to sync your photos? You can use it together with phockup to place your photos in the "originals" with directories by year/month/day or alike.

**Comment by lastzero** [comment]
Closing this since we received no more feedback. Note that 100 MB swap as mentioned in the description above won't be enough. 

You need at least 1 GB of swap, ideally the **same amount as physical, so 4 GB** in this case.
