### ISSUE TITLE
Logs are empty

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#1137]
1. I checked the “Debug Logs” option in the Settings
2. I start a scan and browse in the photos
3. Logs only show “Nothing to see here yet. Be patient.”

The Docker image `photoprism/photoprism:preview` is up-to-date.

It works on the demo: https://demo.photoprism.org/library/logs We can see “2021-03-19 18:44:32 INFO Indexing originals...” once the scan is started or logs like “2021-03-19 18:46:24 INFO photos: found 60 results for public:true dist:20 count:60 order:added merged:true [9.659479ms]” when viewing photos.

**Comment by lastzero** [comment]
You might need to restart for this to take effect as the logger needs to be reinitialized. Let us know if this works!

**Comment by alexislefebvre** [comment]
Thanks. I restarted the container, then deleted the container and restarted it. I still only see “Nothing to see here yet. Be patient.”.

**Comment by alexislefebvre** [comment]
I totally missed the message about the offline mode the last times I checked.

Once I setup Apache correctly, ran `a2enmod proxy_wstunnel` and restarted Apache, it worked.
