### ISSUE TITLE
Index with an external instance

### ISSUE THREAD

**Issue by nmocruz** [photoprism/photoprism#1145]
Since the index work is heavy and demands resouces, there's any way make indexing work done by a service on a more powerful machine.
A have small pc 3gb arm that I want to use to server to sync/backup photos from phones, but I'm afraid that it not enough to handle indexation service.

**Comment by kvalev** [comment]
3GB should be more than enough tbh. I managed to index my modest photo collection on 1GB with few tradeoffs.

**Comment by lastzero** [comment]
TensorFlow needs a lot of memory, transcoding RAWs and videos as well. If you disable TensorFlow and don't have files to transcode (just JPEGs), you'll need less memory. We've released 3 months ago, so there's a "few" other feature requests on our roadmap before we can start thinking about thinking about implementing  a service architecture with distributed indexing.

**Comment by alexislefebvre** [comment]
See also #1100
