### ISSUE TITLE
Metadata: Add support for XMP sidecar CreateDate and Keywords

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1151]
As user, I want PhotoPrism to extract information from xmp fields that are written by Apple Photos, so that I can switch from Apple Photos to PhotoPrism without loosing data.

**Acceptance Criteria:**
* Read the following xmp field:  
```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">     
      <rdf:Description rdf:about=""
            xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
         <photoshop:DateCreated>2018-01-30T20:30:48-05:00</photoshop:DateCreated>
      </rdf:Description>
```

**Comment by benmccann** [comment]
PR for this is here: https://github.com/photoprism/photoprism/pull/1161
