### ISSUE TITLE
Is it possible to use ML models without photoprism?

### ISSUE THREAD

**Issue by ligurio** [photoprism/photoprism#1157]
Hello,

I want to classify my photos, but don't need features that photoprism provides. For example  service with web ui. Is it possible to download files with trained ML models that photoprism uses?

**Comment by kyeb** [comment]
I'm not an expert, but as far as I can tell the models that PhotoPrism uses are hosted at the following URLs, and are available for anyone to download and use in their code.

https://dl.photoprism.org/tensorflow/nasnet.zip
https://dl.photoprism.org/tensorflow/nsfw.zip

**Comment by ligurio** [comment]
@kyeb it's exactly what I wanted to hear. Thanks.
