### ISSUE TITLE
Allow to label multiple images in batch

### ISSUE THREAD

**Issue by jsBlackBelt** [photoprism/photoprism#1165]
Hello,

Currently, to manually tag people in photos, the process includes:
1. Click edit picture
2. Click labels tab
3. Add labels
4. Click details tab (to see picture preview)
5. Click arrow on screen top left to see next photo
6. go to step 2

This is very manual and tedious.
There is already the option to select multiple pictures in the search screen for batch operations,  but selecting multiple photos and clicking on batch edit only allows to edit one at a time, so not a batch operation, really.

It would be a lot easier to select a few photos and add one or more labels to all of them, so that I could choose 10 pictures and add 'Person A' label to all 10, deselect and select 5 different ones and add 'Person B' to all 5, then select 7 different ones and add 'Person A' & 'Person B' to all 7.

Also - it would be a lot easier to do this with keyboard shortcuts, but this is a different issue I'll open separately.

**Comment by alexislefebvre** [comment]
See #271

**Comment by graciousgrey** [comment]
Add labels to multiple photos will be part of batch edit (#271)
