### ISSUE TITLE
Missing photos on library scan, mismatched thumbnails

### ISSUE THREAD

**Issue by mikebantz** [photoprism/photoprism#1167]
I have a small folder of smaller images - between 400k -> 500k or so, 7 images in the folder. I have NSFW filter off and Quality Filter turned off. On import, and on browsing to the folder in photoprism, it seems the correct num of photos is "seen" by photoprism:

`photoprism_1  | time="2021-04-02T13:53:51Z" level=info msg="photos: found 7 results for filter:\"path:Mike's By Year/1989 public:true\" path:\"Mike's By Year/1989\" public:true dist:20 album:aqqwogz1ea0osmll count:60 order:added merged:true [3.085398ms]"`

In originals view, I'll see all 7 images' thumbnails, but clicking on one of those thumbs will take me to the wrong image (clicking on the red marked one):

![image](https://user-images.githubusercontent.com/63611729/113421942-237b0700-9389-11eb-8fbb-6f1b41c5e218.png)

![image](https://user-images.githubusercontent.com/63611729/113421991-3988c780-9389-11eb-96d6-ac8ddefc72ed.png)

Folders view (not originals) will only show three of the images:

![image](https://user-images.githubusercontent.com/63611729/113423360-91283280-938b-11eb-8c0d-437232c58341.png)

Dir listing of those files with the three that are only shown marked with ***:
```
-rw-r--r-- 1 root       root  1.6M Apr  1 14:21 '1989.05.05 mike and jen prom.jpg' ***
-rw-r--r-- 1 root       root  539K Apr  1 14:21 '1989.05.05 prom_hope_jen.jpg' ***
-rw-r--r-- 1 root       root  912K Apr  1 14:21 '1989.05.05 prom_jen_mike.jpg'
-rw-r--r-- 1 root       root  330K Apr  1 14:21 '1989.05.05 prom_jen_mike_tongue.jpg'
-rw-r--r-- 1 root       root  580K Apr  1 14:21 '1989.05.05 prom_paul_mike.jpg' ***
-rw-r--r-- 1 root       root  502K Apr  1 14:21 '1989.05.05 prom_three_couples_1.jpg'
-rw-r--r-- 1 root       root  451K Apr  1 14:21 '1989.05.05 prom_three_couples.jpg'
```
These results are repeatable - I can completely destroy the docker containers and appdata, start completely fresh, re-index, and the same photos will be missed / mis-linked, etc.

Also, enjoy how amazing Prom was in 1989 :-)

**Comment by alexislefebvre** [comment]
These photos may be stacked. To check: see if there is only one file in the “Files” tab of a photo.

**Comment by mikebantz** [comment]
They _are_ stacked. How should this checkbox work?

![image](https://user-images.githubusercontent.com/63611729/113435968-136f2180-93a1-11eb-86f3-d098768d85d4.png)

**Comment by alexislefebvre** [comment]
Sorry I don't know, but you can unstack the files from the “Files” tab of a photo.

**Comment by mikebantz** [comment]
OK - more info. With that checkbox unchecked, clicking "Unstack" throws "Feature disabled"

So I checked that box, tried again - "Feature disabled"

Then tried `docker-compose down` and `docker-compose up -d`

"Unique Feature" is still checked, but still unable to un-stack any of the photos.

**Comment by mikebantz** [comment]
OK - another point of reference. Redeployed both docker images (docker-compose down, deleted appdata, started afresh).

Unchecked "Unique ID" and then did a docker-compose down, then docker-compose up.

Re-indexed, files are still getting stacked but was able to unstack them just fine.

"Sequential Name" in settings is also off, always has been off during this testing.

Seems like that checkbox being un-checked should disable stacking of images on import/scan, but that's not what seems to be happening.

**Comment by graciousgrey** [comment]
@mikebantz stacking for unique id and sequential name should be turned off in the settings before the initial indexing to prevent images from stacking. Once the images are stacked a re-index with changed settings won't unstack them.

**Comment by mikebantz** [comment]
Yeah - I kind of figured this part:

> stacking for unique id and sequential name should be turned off in the settings before the initial indexing to prevent images from stacking. Once the images are stacked a re-index with changed settings won't unstack them.

Let me redeploy _everything_ just to make sure I'm not holding on to some setting _somewhere_. Like, delete all the docker images, appdata, etc. and then I'll be sure to try and import making sure that unique id and sequential name are turned off.

If it still happens how would you like an archive of that directory?

**Comment by graciousgrey** [comment]
> If it still happens how would you like an archive of that directory?

2-3 of the photos that are stacked together would be sufficient. You can send them to hello@photoprism.app. We will delete them once we are done with testing.

**Comment by mikebantz** [comment]
Confirmed still stacking after total redeploy, with the following settings in place _after_ a full docker-compose down / up

![image](https://user-images.githubusercontent.com/63611729/113443817-ec6c1c00-93af-11eb-963d-04a5b92bfc18.png)

 Archive of the dir on its way to you!

**Comment by graciousgrey** [comment]
@mikebantz Thank you, we will have a look as soon as possible -  it might take some days.

**Comment by mikebantz** [comment]
Thank you so much for looking into this - please let me know how I can help, test, etc.

**Comment by graciousgrey** [comment]
Photos have been stacked by place and time in this case. 
They can either be unstacked manually (see https://docs.photoprism.org/user-guide/organize/stacks/#ungroup-files) or removed from the library and added again by indexing with the place & time setting disabled.
