### ISSUE TITLE
Managing categories

### ISSUE THREAD

**Issue by costesbas** [photoprism/photoprism#1168]
Hello,

I'm actually testing Photoprism and i really enjoy all of the functionalities. 
When I started using it I created and added some categories (not labels) to several albums. Is there anyway to manage those categories? Some of them remain in the searchbar on the album page and in the modify album menu.
How to manage those Categories?

Have a nice day and thank you for this great project.

**Comment by graciousgrey** [comment]
Hey,  good to hear that you like PhotoPrism :)

At the moment the only thing you can do with those categories is add them to albums and filter your albums by these categories.

What further functionalities would you like to have?
