### ISSUE TITLE
UX: PWA UI is not displayed correctly in Firefox

### ISSUE THREAD

**Issue by JulianEggers** [photoprism/photoprism#1169]
The UI of Photoprism breaks when installing it as pwa using Firefox on Android. 

![Screenshot_20210402-180117.jpg](https://user-images.githubusercontent.com/7057809/113432344-84ccc580-93dd-11eb-9455-52e4b34c23e5.jpg)

There seems to be a fixed spacing for the Firefox search bar that is not being displayed in PWAs.

**Comment by graciousgrey** [comment]
Thanks for reporting!

**Comment by lastzero** [comment]
Is this only happening with this app? Didn't even know browsers other than Chrome are supported for PWAs on Android. On iOS, only Safari is supported as well. Wouldn't be surprised if PWA support on Firefox is at least incomplete and may have issues. In that case, we shouldn't spend much time on a workaround but wait for an official fix.

**Comment by JulianEggers** [comment]
I think Firefox supports PWAs as well since it has the install button for some apps in the options as well. However, you are right: I tested other pwa websites on Firefox as well and found this top spacing there as well.
Waiting for updates for Firefox seems to be the best option for now.

**Comment by lastzero** [comment]
Any news on this?

**Comment by isaac84** [comment]
It seems to work correctly in Firefox 93.2.0. The search bar hides when scrolling down and reappears when scrolling back up. (Unless I'm doing something wrong) Tested on a Motorola G30 launching PhotoPrism from the home screen.


![Screenshot_20211029-214407-516](https://user-images.githubusercontent.com/385842/139422115-7365b1da-1acd-4e9d-8c08-1c576d297de3.png)

![Screenshot_20211029-214223](https://user-images.githubusercontent.com/385842/139422120-d9089fad-efec-4bd8-b1b2-1df5a97d2761.png)

**Comment by JulianEggers** [comment]
Did you use the install functionality in the Firefox options?

For me it still shows the black bar at the top.

**Comment by isaac84** [comment]
When you say install do you mean 'Add to Home Screen' or am I missing something?

**Comment by JulianEggers** [comment]
I am referring to this option that is called install. Not sure if this is the same as what you were referring to. 

![Screenshot_20211030-005039.jpg](https://user-images.githubusercontent.com/7057809/139509420-306e7bdd-4dcc-43ef-acc1-c6d72dd0f758.jpg)

**Comment by isaac84** [comment]
Ok so same icon but a different name it seems. I'm running Android 11 and the latest Firefox in the play store.

![Screenshot_20211030-151735-793](https://user-images.githubusercontent.com/385842/139519916-ea6b4934-2aaf-48ac-a433-8a69945165ea.png)

![Screenshot_20211030-151750](https://user-images.githubusercontent.com/385842/139519918-1011a6be-7704-4ea0-a4f7-32f8e1cc446a.png)

It seems pretty responsive maybe even a little smoother scrolling then Chrome (Bromite) but loading a larger image when tapping on a thumbnail feels slower (not timed just going by feel)

**Comment by JulianEggers** [comment]
I was using the Firefox nightly version and there this black bar was displayed. Retested it with the normal Firefox edition and can't reproduce this behavior there. Seems like an issue with the nightly build?

I think this issue can therefore be closed.

**Comment by graciousgrey** [comment]
Thank you all for investigating :)
