### ISSUE TITLE
UX: Navigation is not displayed correctly on small screens

### ISSUE THREAD

**Issue by JulianEggers** [photoprism/photoprism#1175]
The offline mode button at the bottom of the navigation overlaps with the other items when opening a parent item that overflow the screen. 

![Screenshot_20210406-133926.jpg](https://user-images.githubusercontent.com/7057809/113705787-243fd000-96de-11eb-9051-487ed5cfd202.jpg)

**Comment by graciousgrey** [comment]
Thanks for reporting. Which device/browser are you using?

**Comment by JulianEggers** [comment]
Android with Firefox and Chrome. Issue appears in both browsers.
It is also a problem on desktop browsers when the height of the window is relatively small.

**Comment by lastzero** [comment]
Yes, indeed may only happen when the browser window is very small AND your server is offline or has a bad configuration. So it's a minor issue most users shouldn't notice.

**Comment by moximoti** [comment]
layout is fixed now in develop. @graciousgrey please check acceptance tests as selectors have changed.
