### ISSUE TITLE
Syncing database with EXIF and XMP - both ways

### ISSUE THREAD

**Issue by bernsel** [photoprism/photoprism#1180]
Many people spend a lot of time organising and favoriting their images in some photo organizing software. However, there is a risk that this information gets lost at some future point in time. The reason might be that the database needs re-indexing from scratch, that they forget to transfer their photo-software database to a new computer when changing computers, or that the software they like simply go out of market (stops being developed).

For that reason, it is important that classification information, such as Image Rating and Tags / Categories, can be "synced" back and forth between the photo software's database, and the image files themselves. JPG files can store EXIF and XMP information in the image itself. One software that does this type of sync really well is digiKam, where a user can for example give Ratings to a number of images (from 1-5) with quick short-commands, and then have this information written down to the image files themselves, for everlasting storage. (The informaiton is then both in digiKam's database, as well as in the images). Writing information to the files can be done in "batch" in digiKam, i.e. the user can first spend some time classifying, and then it can all get written to the image files on disk.

EXIF has a tag named "Windows Rating" and XMP has a tag named just "Rating". XMP also allows for schemas to store Tags, so that for example PhotoPrism (or any software) can have its own XMP schema, and store information that the user creates in the Photoprism database, into the images files themselves.

I think it would be fantastic if Photoprism could read and write EXIF and XMP data, especially classification data (Ratings and Tags), which is the kind of data where the user spends a lot of manual time creating (all other metadata is kind of automatic, like creation date or camera model). This function would in practice mean that Photoprism should be able to do things such as:
- When indexing files, reading EXIF and XMP Ratings become a part of indexing process, and these becomes searchable / can be used as filters in PhotoPrism.
- The same for Tags.
- Phtoprism's "favourite" function can be written back to the images files, so that if a user spends time favoriting images, that can be converted into perhaps a 5-star rating for those images that have been favorited, and written to the image files. 
- Any labels / keywords that have been manually entered by the user in Photorism (not auto generated by the AI models), can be written back as XML data to the images files. 

This needs to be specified further - but it would be very valuable to have this in Photoprism.

**Comment by graciousgrey** [comment]
Writing metadata back to original files is something we plan to do later, but it needs to be well thought through. See https://github.com/photoprism/photoprism/discussions/1092.

What we already do is creating yml backup files with all the metadata.

PhotoPrism reads many exif and xmp fields like tags, keywords, descriptions. It is an ongoing task to support more fields as every tool uses different fields...

Reading rating related data will be be something we deal with once we come to https://github.com/photoprism/photoprism/issues/713

**Comment by bernsel** [comment]
Great!, looking forward to that. I would be happy to sponsor this development too. I have emailed you separately about this, to find the best way to sponsor as effectively as possible.

**Comment by graciousgrey** [comment]
I close this, as we already read exif and xmp and we have a separate ticket for writing back to xmp/exif (https://github.com/photoprism/photoprism/issues/402)
