### ISSUE TITLE
Glitches in the UI

### ISSUE THREAD

**Issue by SinTan1729** [photoprism/photoprism#1185]
When trying to view a particular folder with around 850 images, I see glitches like in the following screenshot.
![dsds](https://user-images.githubusercontent.com/35728385/114299936-841de880-9adb-11eb-8683-5f110d5e8ae4.png)
If it is relevant, indexing is still going on.
I'm using a docker install in Manjaro KDE.

**Comment by alexislefebvre** [comment]
See  #1104

**Comment by SinTan1729** [comment]
It should be noted that I'm also using Firefox. So it might be a Firefox related issue. I'll try again using some Chromium based browser to see if the problem persists.

**Comment by graciousgrey** [comment]
Thanks for reporting! I will close this ticket as a duplicate, feel free to add a comment in the existing one (#1104) Are you using Firefox on Linux?
