### ISSUE TITLE
It seems can not auto scan for new files

### ISSUE THREAD

**Issue by terry778778** [photoprism/photoprism#1188]
Photoprism can not scan for new files, I have to go to library and start a scan manually, is this how the way it works or i miss something.

**Comment by ubersteiny** [comment]
If you want PhotoPrism to scan in new images you need to add them into the imports folder and not originals folder.

**Comment by terry778778** [comment]
> If you want PhotoPrism to scan in new images you need to add them into the imports folder and not originals folder
Can i set the imports folder same as originals folder, do you think this will work? Or delete the originals folder, just keep
the imports folder only.

**Comment by terry778778** [comment]
> If you want PhotoPrism to scan in new images you need to add them into the imports folder and not originals folder.

Can i set the imports folder same as originals folder, do you think this will work? Or delete the originals folder, just keep
the imports folder only.

**Comment by ubersteiny** [comment]
> > If you want PhotoPrism to scan in new images you need to add them into the imports folder and not originals folder.
> 
> Can i set the imports folder same as originals folder, do you think this will work? Or delete the originals folder, just keep
> the imports folder only.

You need both. The imports folder is just a temporary watch folder. Images will be moved from the imports folder and then auto organized in folders by date into your originals folder.

**Comment by terry778778** [comment]
> > > If you want PhotoPrism to scan in new images you need to add them into the imports folder and not originals folder.
> > 
> > 
> > Can i set the imports folder same as originals folder, do you think this will work? Or delete the originals folder, just keep
> > the imports folder only.
> 
> You need both. The imports folder is just a temporary watch folder. Images will be moved from the imports folder and then auto organized in folders by date into your originals folder.

Is it ok to set same path for both?

**Comment by alexislefebvre** [comment]
You can configure cron to automatically index the new files, see https://github.com/photoprism/photoprism/issues/281#issuecomment-703461268

**Comment by terry778778** [comment]
> You can configure cron to automatically index the new files, see [#281 (comment)](https://github.com/photoprism/photoprism/issues/281#issuecomment-703461268)

Got it, i think that will work, thank you!

**Comment by graciousgrey** [comment]
@terry778778 automatic indexing is only triggered when files are added via WebDav to the originals or the import folder. 

In addition you can configure a cron job as @alexislefebvre said.

You can read more about the difference between indexing and importing here: https://docs.photoprism.org/user-guide/library/import-vs-index/

**Comment by terry778778** [comment]
> @terry778778 automatic indexing is only triggered when files are added via WebDav to the originals or the import folder.
> 
> In addition you can configure a cron job as @alexislefebvre said.
> 
> You can read more about the difference between indexing and importing here: https://docs.photoprism.org/user-guide/library/import-vs-index/

Thx very much

**Comment by graciousgrey** [comment]
Now you can find example docker-compose.yml + job.ini files here: https://dl.photoprism.org/docker/scheduler/.
Within the jobs.ini you can configure when and how often commands (e.g. index or import) should run. This is independent from WebDav :)
