### ISSUE TITLE
confusion about the user in the container

### ISSUE THREAD

**Issue by kylrth** [photoprism/photoprism#1189]
I see [in the development Dockerfile](https://github.com/photoprism/photoprism/blob/cc8998f9a9b841553e1c9f4129cb64dfe8fcd738/docker/development/Dockerfile#L137) that the `photoprism` user is added, but there's no `USER photoprism` line. I've been using docker-compose for my instance and noticed that my backups were being written by the root user, so I think the default docker-compose setup is running as root.

If I'm not mistaken here, I think we either need a `USER photoprism` line in the Dockerfile or a `user: photoprism` line in the sample docker-compose.yml. Is that the case?

**Comment by lastzero** [comment]
You are right, without running the container as a different user, the default user is `root`. See our inline comments in the example `docker-compose.yml` files: https://dl.photoprism.org/docker/

You can either set a user natively via Docker (`user` in Docker Compose) or use the `UID` / `GID` environment variables, which will then create a user `photoprism` with those IDs in the container.

**Comment by kylrth** [comment]
Ok, thank you for the clarification.
