### ISSUE TITLE
back up to the same file location every time

### ISSUE THREAD

**Issue by kylrth** [photoprism/photoprism#1190]
I have a cron job configured to run `docker-compose exec -T photoprism photoprism backup -a -i -f` every so often, but I'm noticing that the backups are stored in the `PHOTOPRISM_BACKUP_PATH` in a file named with the date. I use [restic](https://github.com/restic/restic) for remote backups on my system, and restic does periodic snapshots of files. It would make sense for `photoprism backup -f` to write to the same file every time, so that restic only stores the latest Photoprism backup in each snapshot and I don't have to periodically delete old Photoprism backups.

**Comment by kylrth** [comment]
Oh, I just saw in the [code](https://github.com/photoprism/photoprism/blob/cc8998f9a9b841553e1c9f4129cb64dfe8fcd738/internal/commands/backup.go#L70) where (if present) you use the first argument to `backup` as the file name.

This isn't clear in the documentation for the command:

```
kyle@spaceship:~/photoprism$ docker-compose exec -T photoprism photoprism backup --help
NAME:
   photoprism backup - Creates album and index backups

USAGE:
   photoprism backup [command options] [arguments...]

OPTIONS:
   --force, -f   overwrite existing backup files
   --albums, -a  create album yaml file backups
   --index, -i   create index database backup
```

**Comment by lastzero** [comment]
You're right that this needs to be more clear & welcome to send a pull request if you figure out how to document the argument.

**Comment by lastzero** [comment]
We've added two more flags to specify custom backup paths. The SQL index backup may be written to stdout by passing `-` as argument:

```
NAME:
   photoprism backup - Creates album and index backups

USAGE:
   A specific index sql backup filename may be passed as first argument. Use - for stdout.

OPTIONS:
   --force, -f         overwrite existing backup files
   --albums, -a        create album yaml file backups
   --albums-path PATH  custom album yaml file backup PATH
   --index, -i         create index sql database backup
   --index-path PATH   custom index sql database backup PATH
```

**Comment by kylrth** [comment]
The usage string should explain that by default it gets the backup path from `PHOTOPRISM_BACKUP_PATH` plus the date.

Also, why do we suddenly have two separate paths for albums and SQL, and what happens when I don't specify separate paths? Do they get placed in the same file? I also think it's redundant to have `--albums` and `--albums-path`. If `--albums-path` is specified, it should imply `--albums`.

**Comment by lastzero** [comment]
> The usage string should explain that by default it gets the backup path from `PHOTOPRISM_BACKUP_PATH` plus the date.

I'll think about it... note there's multiple ways to change the backup path, not only the environment variable. It shouldn't look like this is the only way to change it, especially since you can easily provide a custom path now.

> Also, why do we suddenly have two separate paths for albums and SQL, and what happens when I don't specify separate paths? Do they get placed in the same file? I also think it's redundant to have `--albums` and `--albums-path`. If `--albums-path` is specified, it should imply `--albums`.

Albums were always backed up to the default location so far, which is the folder `albums` in the storage path; is contains subfolders for each album type. If `--albums-path` is specified, it implies `--albums`. But you don't need to provide a custom path and can as well just use `-a` so it's backwards compatible.

**Comment by lastzero** [comment]
Note that backing up albums to a different path doesn't make much sense for many users as they can easily backup their storage folder and albums won't be restored from custom folders (unless you copy the files back to the albums storage folder).
