### ISSUE TITLE
Possibility to import from digikam?

### ISSUE THREAD

**Issue by zierbeek** [photoprism/photoprism#1194]
I indexed all my images with digikam. Is it possible to import this all into photoprism?

**Comment by lastzero** [comment]
Depends on what fields and metadata formats you're using. Obviously different apps may use / display / support metadata in different ways. Indexing the same files is not a problem in general.

**Comment by zierbeek** [comment]
hmm I'm not going this way. I have a lit trouble configuring photoprism.

So I'm running a Truenas server with an ssd which runs a ubuntu server vm. Then I have a raid 1 pool with 12tb storage with a photos folder which has several folders  in it named with the event and year. So I will need to go the import way.

I'm having trouble configuring the paths in the docker compose file... I mounted the photos folder using cifs in the etc/fstab. That is a succes. in the vm is see a photos folder with all the images. 
I do not understand how I need to get them into photoprism.

**Comment by zierbeek** [comment]
<img width="470" alt="Schermafbeelding 2021-04-15 om 12 47 53" src="https://user-images.githubusercontent.com/58994651/114857643-cc454f80-9de8-11eb-9766-063352ccfa9b.png">
 
The images folder is just located there. So I thought just to put it like this:
`/photos:/photoprism/Originals`

**Comment by lastzero** [comment]
You need to mount it to `/photoprism/originals` with a small `o` - the file system is case sensitive.

**Comment by zierbeek** [comment]
in my stab?

**Comment by lastzero** [comment]
docker-compose.yml unless you run photoprism without docker?

**Comment by zierbeek** [comment]
No, it is using docker :) 
this is in my fstab of the vm
`//ip/tank1/Photos /photos cifs  credentials=/home/matthias/.smb,uid=1000,gid=1000 0 0>
`
and in my docker-compose
`      # Your photo and video files ([local path]:[container path]):
      - "./photos:/photoprism/originals"`

**Comment by lastzero** [comment]
Should probably be `"/photos:/photoprism/originals"` then?

**Comment by zierbeek** [comment]
weird thing is, that when I go to my root folder, there is a folder photos with photos in it. So I just need to get them indexed in photoprism

**Comment by lastzero** [comment]
Right, but you mounted the folder to `/photos` but the Docker volume uses `./photos`, which is RELATIVE to the current directory and probably points to `/root/photos`

**Comment by zierbeek** [comment]
aha, it's indexing :) but for my case, it would be better to import it and order it in different folders, no?

**Comment by zierbeek** [comment]
how would I need to do that?

**Comment by alexislefebvre** [comment]
> aha, it's indexing :) but for my case, it would be better to import it and order it in different folders, no?

See the documentation about that question: https://docs.photoprism.org/user-guide/library/import-vs-index/

**Comment by zierbeek** [comment]
That I know! Importing would be the best, but how could I do this efficiently with the current structure.

Should I, in the docker-compose change the import to my photos folder, let it import, and afterwards change it back to import?
