### ISSUE TITLE
Metadata: Allow single quotes in keywords

### ISSUE THREAD

**Issue by dror3go** [photoprism/photoprism#1196]
In some languages, acronyms are written with a quotation mark.
When PhotoPrism is getting a photo's location details to set its title and keywords, it currently splits a phrase into two separate keywords when it finds a quotation mark. This leaves some of my photos with a 1 letter keyword and other useless keywords.

I'm not sure if this should be language-based, but it seems to me that we need some sort of logic change when setting keywords.

**Comment by graciousgrey** [comment]
@dror3go could you name us some examples? 

Language based improvements for titles, keywords etc are a bit more complex. We know there is room for improvement and will probably implement it at one point but at the moment we have some more important tasks to work on.

**Comment by lastzero** [comment]
You can now use `McDonald's` as keyword. Trailing single quotes are getting trimmed and you can't use double quotes.

**Comment by dror3go** [comment]
@lastzero Single quote works :+1: 
However, double quote is also valid in some cases/languages. For example, `נתב"ג` should be a valid keyword. That's how acronyms are written in some languages. Any chance to add such an exception?

**Comment by lastzero** [comment]
Wow, didn't know that. Thanks for testing!

More characters we need to keep in mind, other than `"`? Might not work with our search since you also use `"` for strings containing a space like "mouse trap".

**Comment by dror3go** [comment]
What do you think about allowing `"` and `'` when saving/displaying a keyword, but remove these characters when running a database query? So for example (never mind the syntax):
```
select * from keywords where replace(keyword, '"', '') = replace($searchTerm, '"', '')
```
Can such a thing work?

As for other characters - yes, checkout Unicode `U+0201C` and `U+0201D`, these are used in Apple products by default AFAIK (am not an Apple user myself).

**Comment by lastzero** [comment]
@graciousgrey We should create a new issue for "search term normalization".
