### ISSUE TITLE
EXIF keyword extraction is confused by Umlaut

### ISSUE THREAD

**Issue by dominikholler** [photoprism/photoprism#1197]
If the EXIF keyword contains an umlaut, the umlaut is not imported correctly, e.g. the keyword 'dänemark' is reconized as the two keywords 'dã, nemark'.

**Comment by lastzero** [comment]
What operating system are you using?

Macs store unicode characters decomposed: https://en.wikipedia.org/wiki/Precomposed_character

**Comment by dominikholler** [comment]
I run the offical container via podman as a usual user on RHEL 8 like this:
DATA=/srv/photoprism
podman run -it --rm \
--user=1000 \
--gidmap=0:10000:2000 --uidmap=0:10000:2000 \
-p 2342:2342 \
-v $DATA/originals:/photoprism/originals:rw,z \
-v $DATA/storage:/photoprism/storage:rw,Z \
-v /cache:/cache:rw,Z \
-e PHOTOPRISM_BACKUP_PATH=/photoprism/storage/backup \
-e PHOTOPRISM_CACHE_PATH=/cache \
-e PHOTOPRISM_ADMIN_PASSWORD=xxxx \
-e PHOTOPRISM_READONLY=false \
-e PHOTOPRISM_SITE_URL=https://xxx.xxxx.org/ \
-e PHOTOPRISM_DETECT_NSFW=true \
  photoprism/photoprism

**Comment by lastzero** [comment]
Keywords get separated by non-word characters. If you've written those Exif tags on a Mac (doesn't matter which server software you use), they might be stored decomposed. This means `ä` may be stored as `a` and `:` like `a:`. Since `:` is not a word character in itself, it might be split. Received your example, please give us a few days to look into it!

**Comment by graciousgrey** [comment]
The Umlaut is already wrong in the exif data of your file, so it might be a problem of the tool you used to set the keywords.

See:
` "Subject": ["bornholm","dänemark","urlaub"],
  "Keywords": ["bornholm","dÃ¤nemark","urlaub"] `

For the subject everything is fine. For the keyword the problem exists in the files metadata itself.

When using exiftool to set keywords e.g. `exiftool -keywords+=dänemark 123.jpg` PhotoPrism has no problem interpreting the Umlaut

**Comment by lastzero** [comment]
Thanks for testing! Closing this as there's probably nothing we can do...
