### ISSUE TITLE
How to change location of storage folder?

### ISSUE THREAD

**Issue by zierbeek** [photoprism/photoprism#1198]
Hi all, 

I have truenas setup with a vm and 50gib of disk size. I mounted my photos Raid1 pool of 2 tb which is only filled for 200gib.

I now got a message that disk space is full..

**Comment by lastzero** [comment]
Where did you mount the storage folder? See our example docker-compose.yml file: https://dl.photoprism.org/docker/docker-compose.yml

You need to mount two folders:

1. Your original pictures
2. Storage for settings, index & sidecar files

See inline comments and our [Getting Started](https://docs.photoprism.org/getting-started/docker-compose/) docs:

```yaml
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "~/Pictures:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "./storage:/photoprism/storage"
```

**Comment by zierbeek** [comment]
the first one was /photos:/photoprism/originals
the last one I left untouched

**Comment by lastzero** [comment]
Then it is where the docker-compose.yml file is, on the same disk. Seems like this disk is too small - you have to change it in this case.

**Comment by lastzero** [comment]
You may also reduce the quality of thumbnail images so that they need less space on your current disk.

**Comment by zierbeek** [comment]
the vm is running on the ssd. 
Would it help if I mount the /storage to to my raid 1 pool?

**Comment by lastzero** [comment]
Yes, for example. Or reduce the size / quality of the thumbs if you want to store them on the smaller SSD. You may also just mount the cache folder `/photoprism/storage/cache` on the RAID.

**Comment by zierbeek** [comment]
so, I leave the current things in docker-compose as it is , and I mount the /storage to a storage folder on the RAID?

**Comment by lastzero** [comment]
Same as for photos: Use "/storage:/photoprism/storage" to mount /storage, not ./storage or //storage please :)

**Comment by zierbeek** [comment]
yes so as I said: 
in docker compose : 
`/photos:/photoprism/originals`
`/storage:/photoprism/storage`
`/import:/photoprism/import`

and in my fstab:
`##photo mount
//ip/tank1/Photos /photos cifs  credentials=/home/matthias/.smb,uid=1000,gid=1000 0 0
//ip/tank1/storage /storage cifs  credentials=/home/matthias/.smb,uid=1000,gid=1000 0 0
//ip/tank1/import /import cifs  credentials=/home/matthias/.smb,uid=1000,gid=1000 0 0`

**Comment by zierbeek** [comment]
and if I wanna do it better, I can move all the contents of my photos folder into my import folder and let photoprism organise everything

**Comment by zierbeek** [comment]
just to double check before I restart the whole thing .)

**Comment by lastzero** [comment]
Should work. Performance might be an issue since now everything is stored remotely.

**Comment by zierbeek** [comment]
got it all working now, work's like a charm mate! even got it working with SWAG. added a pull request in linuxserver/swag to get it as a preconfigured file! No hassle with Traefik or Nginx

**Comment by zierbeek** [comment]
the only thing missing is the bulk edit exif tool and face recognition. But I saw it's all in dev phase :)
