### ISSUE TITLE
Cannot disable Debug Logging

### ISSUE THREAD

**Issue by shawnbarton** [photoprism/photoprism#1199]
Version: 210222-ac5a9d5e-Linux-x86_64
Deployment: Docker

I enabled "Debug Logs" in Settings -> Advanced to do some troubleshooting for another issue. Once I was done I unchecked the "Debug Logs" setting yet debug messages are still being output to docker logs. "Settings saved" is correctly shown after ticking or unticking the box.

Turned on "Debug Logs" in Settings then clicked "Albums" on the sidebar:
```
time="2021-04-16T14:11:34Z" level=debug msg="http: GET /api/v1/config/options (200) [493.625µs]"
time="2021-04-16T14:11:50Z" level=info msg="Settings saved"
time="2021-04-16T14:11:50Z" level=debug msg="http: POST /api/v1/config/options (200) [199.743742ms]"
time="2021-04-16T14:11:59Z" level=debug msg="albums: search type:album count:24 [42.015µs]"
time="2021-04-16T14:11:59Z" level=debug msg="http: GET /api/v1/albums?count=24&offset=0&q=&category=&type=album (200) [8.606486ms]"
time="2021-04-16T14:11:59Z" level=debug msg="cached album-cover:aqqjd5y13vyf5j2i:tile_500 [2.76566ms]"
time="2021-04-16T14:11:59Z" level=debug msg="http: GET /api/v1/albums/aqqjd5y13vyf5j2i/t/a5165e28/tile_500 (304) [2.882693ms]"
time="2021-04-16T14:11:59Z" level=debug msg="cached album-cover:aqrkkse9ek9j4eee:tile_500 [3.630451ms]"
time="2021-04-16T14:11:59Z" level=debug msg="http: GET /api/v1/albums/aqrkkse9ek9j4eee/t/a5165e28/tile_500 (304) [3.768799ms]"
```
Above, the debug messages are expected and correct.

Navigated to Settings, turned off "Debug Logs", and once more clicked "Albums" on the sidebar:
```
time="2021-04-16T14:12:07Z" level=debug msg="http: GET /api/v1/config/options (200) [642.632µs]"
time="2021-04-16T14:12:09Z" level=info msg="Settings saved"
time="2021-04-16T14:12:09Z" level=debug msg="http: POST /api/v1/config/options (200) [198.397627ms]"
time="2021-04-16T14:12:20Z" level=debug msg="albums: search type:album count:24 [48.4µs]"
time="2021-04-16T14:12:20Z" level=debug msg="http: GET /api/v1/albums?count=24&offset=0&q=&category=&type=album (200) [8.500556ms]"
time="2021-04-16T14:13:43Z" level=debug msg="http: GET /api/v1/config/options (200) [1.648086ms]"
```
Above, the debug messages are unexpected as the log level was changed in the settings before the navigation action.

Command with which I am viewing PhotoPrism logs:
```
sudo docker logs -f --since "10m" docker-compose_photoprism_1
```

**Comment by alexislefebvre** [comment]
Try to reset the container, see https://github.com/photoprism/photoprism/issues/1137#issuecomment-808911984

**Comment by alexislefebvre** [comment]
Try to restart the container, see https://github.com/photoprism/photoprism/issues/1137#issuecomment-808911984

**Comment by shawnbarton** [comment]
Sorry, I missed that in my search for an existing issue. Thank you. Closing this issue.
