### ISSUE TITLE
UX: Image Cards of Differing Dimensions for Asthetics

### ISSUE THREAD

**Issue by gouldadam** [photoprism/photoprism#1205]
Photoprism has amazing features but I find the layout of the image cards to not be as visually engaging as it could be. Having all images displayed in a small square to my eye makes them all blend together. Suggest a layout like this: https://github.com/gregordr/ImageStore

When I browse photos of differing dimensions I find it to me more visually engaging, interesting and playful

**Comment by lastzero** [comment]
We'll work on the UI design once high-priority feature requests on the roadmap have been implemented:

https://github.com/photoprism/photoprism/projects/5

**Comment by graciousgrey** [comment]
Just realized we already have a ticket for this: https://github.com/photoprism/photoprism/issues/85
