### ISSUE TITLE
Incorrect order of Folder view

### ISSUE THREAD

**Issue by layanto** [photoprism/photoprism#1208]
Folder view I think is supposed to be ordered monthly from latest to oldest. This mostly the case but a couple of folders appear in the wrong order. In the screenshot below you can see August 2016 is in the wrong spot.

![Screenshot_2021-04-08-20-01-47-160_org mozilla firefox_beta](https://user-images.githubusercontent.com/245078/115323303-36843880-a1cb-11eb-8d90-61284fe49a08.jpg)

Is this a bug? How do I fix this?

**Comment by layanto** [comment]
![image](https://user-images.githubusercontent.com/245078/115323751-00938400-a1cc-11eb-87cc-20a04a130135.png)

Another example - January 2014 is in the wrong spot.

**Comment by lastzero** [comment]
Are there newer files in there? Order might be by actual metadata, not what the folder name indicates.

**Comment by layanto** [comment]
I didn't create any folder myself. I used the Import feature and let Photoprism create the folders, rename files and move them out of the import folder.
I checked the August 2016 folder and noticed that while most photos were from August 2016, a few where of unknown date.

![image](https://user-images.githubusercontent.com/245078/115347561-e621d080-a1f4-11eb-8cfd-bdbfeeef5d81.png)

I think this is why the folder were displayed out of order. How do I fix this?

**Comment by lastzero** [comment]
If it's just two files, you can use the edit dialog to set the right date. In addition, we're going to look into this - "unknown" dates should be ignored for sorting.

**Comment by layanto** [comment]
Quitena few more than 2 photos unfortunately. I will try to manually fix one folder to see if the folder then becomes correctly ordered.

**Comment by lastzero** [comment]
Are you using MariaDB or SQLite? The query for getting the latest date looks good to me, only pictures with dates from actual metadata should be considered. However, this query isn't compatible with SQLite.

**Comment by layanto** [comment]
MariaDB in a Docker container.

**Comment by lastzero** [comment]
So that should not be an issue :+1:

**Comment by layanto** [comment]
Found a handful of August 2016 photos correctly under August 2016 folder but has March 2021 date in the edit screen. Not sure how that happened. After manually fixing them, August 2016 folder now appears in the correct order.

**Comment by layanto** [comment]
Strangely after fixing January 2014 folder, it is still incorrectly displayed next to January 2018 folder.

**Comment by layanto** [comment]
January 2014 folder is displayed in the correct order now. Maybe needed to wait for some time for Photoprism to reindex or something.

**Comment by layanto** [comment]
Maybe related to this issue. I found many photos which were placed in the correct folder and photoprism renamed the file name to the correct yyyymmdd_xxxx, but why is the day month year fields empty (is unknown)?

**Comment by lastzero** [comment]
It's "unknown" because a date was not found in the metadata, thus it's just an estimate that may change when you modify or move the file.

**Comment by layanto** [comment]
I also found many photos that PhotoPrism renamed to the same yyyymmdd_hash but with added suffix of .0001, .0002, etc. What do these suffixes mean? Initially I thought this meant the photos are stacked (ie group of photos taken at same place and around same time). But I don't think this is the case here where many different photos are incorrectly grouped this way.

**Comment by layanto** [comment]
Actually 00001, etc do relate to stacks. Just not sure why many photos were incorrectly grouped together.

**Comment by layanto** [comment]
I think the issue is when I tried to fix photos with missing Date Taken metadata, they ended up with the same time (as Windows Explorer only allowed editing date with the time automatically set to present time).

**Comment by graciousgrey** [comment]
@layanto photoprism might stack photos for the following reasons: 1) They have the same unique id 2) They have the same place AND time information 3) They have sequential names. See: https://docs.photoprism.org/user-guide/settings/library/#stacks.

**Comment by layanto** [comment]
I saw that in the document. Not sure why they were stacked. Date Taken metadata are completely different. File names are different too. Not sure what unique ID is.

**Comment by graciousgrey** [comment]
@layanto Could you send us example files that are stacked for unknown reason?

**Comment by layanto** [comment]
Unfortunately I have already fixed them by manually unstack them all. Also I have tried so many things that I am not clear on the sequence of events anymore. Not sure if the photos were stacked even though they have different Date Taken metadata or if I manually added the Date Taken metadata afterwards. I found that once the photos are stacked by Photoprism, even after removing the photos from original folder, trigger index, renaming the photos, moving the photos to the correct original/year/month folder, trigger index, Photoprism ended up stacking them again. This was when I ended up manually unstacking them - all the while wishing there was a way to bulk unstack all photos within a stack.

**Comment by lastzero** [comment]
If you removed / re-added the photos, then the "unstacked" flag - which PhotoPrism remembers to avoid the frustration you experienced - gets lost. If you don't like stacks in general, please disable them in Settings. The result of an unstack operation depends on the order as there is metadata attached to each file and there may be different file types in a stack, like RAW, JPEG, AVC,... thus unstacking all is generally impossible unless we can read the minds of our users.
