### ISSUE TITLE
WebDAV: Keep favorite flag when uploading via PhotoSync

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1210]
As a user, that uses PhotoSync in combination with PhotoPrism, I want photos that have been marked as favorite on my phone to be marked in PhotoPrism as well, so that I do not need to mark photos as favorite twice.

**Acceptance Criteria:**
* Mark a photo as favorite when it comes with the header
* Read  Recordtime header in case the photo/video has no exif data
* Add unit tests
* Update documentation

**Comment by dror3go** [comment]
@graciousgrey is there a different way to get this favorite boolean other than a `X-` header prefix? This "custom header" prefix has been [deprecated back in 2012](https://tools.ietf.org/html/rfc6648).

**Comment by lastzero** [comment]
This has been released. Note that PhotoSync for Android might not send the required header yet, so it may only work on iOS so far.
