### ISSUE TITLE
Indexing or search bug

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1211]
Hi there!

I thought all was well with my PhotoPrism collection, until a friend shared a photo from a few years back, that SHOULD be in my collection. But it isn't. Well it sort of is...but isn't findable!

Here is the photo ``IMG-20190422-WA0004.jpg`` metadata as seen in Amazon Photos:

![image](https://user-images.githubusercontent.com/8156439/115530666-e28d5880-a28b-11eb-86f9-b5df5aafdd02.png)

(unfortunately, it looks like Amazon uses the file creation date to show "taken date", which is great when you upload to Amazon, but not great when you then download it - I lose the time but not the date thankfully. That is another unsolvable issue however!)

I have indexed this file into PhotoPrism - my logs rotate so I've lost the original import log, but it seems I had a couple copies of this photo, and we can see the indexer doing it's magic:

```
time="2021-04-19T01:04:52Z" level=info msg="media: IMG-20190422-WA0004.jpg was taken at 2019-04-22 00:00:00 +0000 UTC (name)"
time="2021-04-19T01:04:52Z" level=info msg="import: IMG-20190422-WA0004.jpg is identical to 2019/04/20190422_000000_22BA599A.jpg (sha1 dc28eb9f0d90df0b214c303aec95fb1292897441)"
time="2021-04-19T01:04:52Z" level=info msg="import: deleted DCIM/Camera/2019-04-22/IMG-20190422-WA0004.jpg (already exists)"

time="2021-04-19T11:48:34Z" level=info msg="media: IMG-20190422-WA0004.jpg was taken at 2019-04-22 00:00:00 +0000 UTC (name)"
time="2021-04-19T11:48:34Z" level=info msg="import: IMG-20190422-WA0004.jpg is identical to 2019/04/20190422_000000_22BA599A.jpg (sha1 dc28eb9f0d90df0b214c303aec95fb1292897441)"
time="2021-04-19T11:48:34Z" level=info msg="import: deleted “amazon/Amazon Photos Downloads/Photos_and_Videos/Pictures/SM-G960F/2019-04-22/IMG-20190422-WA0004.jpg” (already exists)"

```

Great! 

So the photo exists in PhotoPrism, and I can confirm it exists, with it's new name, at ``\originals\2019\04\20190422_000000_22BA599A.jpg ``. **Clearly PhotoPrism knows it was taken on 2019\04\22 too**, due to the folder and naming of the file.

So where is it? :(

- Doesn't show when selecting 2019 and April in the search filter dropdowns
- Searching ``name:20190422_000000_22BA599A.jpg``, ``name:20190422_000000_22BA599A*``, ``name:"20190422_000000_22BA599A*"`` etc. yields no results:

```
time="2021-04-21T10:36:59Z" level=info msg="photos: found 0 results for name:20190422_000000_22BA599A.jpg public:true dist:20 year:2019 month:4 quality:3 count:60 order:name merged:true [164.132607ms]"
time="2021-04-21T10:37:09Z" level=info msg="photos: found 0 results for name:20190422_000000_22BA599A* public:true dist:20 year:2019 month:4 quality:3 count:60 order:name merged:true [166.388843ms]"

```

- Similarly, searching ``original: "IMG-20190422-WA0004.jpg"``, ``original: "IMG-20190422-WA0004*"``, etc yields no results:

```
time="2021-04-21T10:40:16Z" level=info msg="photos: found 0 results for q:\"img-20190422-wa0004*\" public:true dist:20 year:2019 month:4 quality:3 count:60 order:name merged:true [22.02994ms]"
time="2021-04-21T10:40:43Z" level=info msg="search: label img-20190422-wa0004.jpg not found, using fuzzy search"
time="2021-04-21T10:40:43Z" level=info msg="photos: found 0 results for q:\"img-20190422-wa0004.jpg\" public:true dist:20 year:2019 month:4 quality:3 count:60 order:name merged:true [6.031334ms]"
time="2021-04-21T10:40:58Z" level=info msg="search: label img-20190422-wa0004* not found, using fuzzy search"
time="2021-04-21T10:40:58Z" level=info msg="photos: found 0 results for q:\"img-20190422-wa0004*\" public:true dist:20 year:2019 month:4 quality:3 count:60 order:name merged:true [5.546736ms]"
```

- Searching ``year:2019 month:4 day:22`` does not return it
- Searching ``folder:"/2019/04*"`` does not return it

At this point, I supposed I'd need to log into mariadb to debug whats going on? Thanks for reading - sorry it's long, tried to include as much info to debug as possible!

Edit: I noticed that my name/original searches also include the year/month filters (which are hidden in the UI and persist between page reloads..naughty!) - but I've tried without these filters too with no results. And also confirmed they are not hidden.

**Comment by timdonovanuk** [comment]
I think this issue is true of all my photos that have an hour/min/second = 000000. 

I've tried finding other photos where they've been named in Photoprism as YYMMDD_000000_<random> and none of them show anywhere. E.g.

- ``name:20190428_202536_411C0D50`` - yep, 1 hit!
- ``name:20190429_000000_1C76D81F`` - nothing.

**Comment by graciousgrey** [comment]
Searching for e.g. name:"20190422_000000_22BA599A*" with no other filters set should show the image unless it is private, archived or in review. It might be that the images you do not find are in one of those sections.

**Comment by graciousgrey** [comment]
It's also possible that the files you do not find are stacked.

**Comment by timdonovanuk** [comment]
🤦 

I've clicked on just about everything in the UI, read (I thought) all the documentation and have even started consuming the REST API based on the godoc.org documentation published (BTW NodeRED + photoprism api makes for an awesome workflow tool to bulk edit photos - it would be amazing to have some official NR photoprism nodes to support reading/writing metadata! I'm currently using it to perform facial recognition on photos and write it back as keywords).

@graciousgrey I'm so sorry. I'm an idiot. Somehow I totally missed this review feature! Thank you for an awesome app :)

**Comment by graciousgrey** [comment]
Thank you for your feedback :)
