### ISSUE TITLE
Nextcloud vs Photoprism sync

### ISSUE THREAD

**Issue by pittbull** [photoprism/photoprism#1217]
Hi, and kudos on a great piece of software that I found just recently after moving towards a privat cloud setup. So far everything works as expected, but I have a question to the sync functionality towards Nextcloud.

My setup:
- Nextcloud and Photoprism installed via docker
- Mounted my photolibrary disk to Photoprism and succesfully indexed 20k photos
- Configured Nextcloud sync (disabed uploads, and chosen Nextcloud folder to sync)
- Successfully synced the one photo I have in this folder

My question: Photos synced from Nextcloud are download into the originals folder under a subfolder named as the Nextcloud folder. I wonder if it is possible to get these photos moved into my existing structure (YYYY-MM-DD) either with Photoprism or maybe other tools?

**Comment by lastzero** [comment]
WebDAV sync copies the files, so it's good to share files with others or if you only have a few photos on Nextcloud. It's not very fast & efficient if you want to index a huge file library you're managing with Nextcloud as it will consume twice the storage. When syncing, you can chose not to preserve remote names so that they are imported into PhotoPrism as if you import for other folders. Note that Nextcloud is based on PHP, so the WebDAV implementation is quite slow and not 100% standards compliant, depending on the Web server. Uploading from your phone to PhotoPrism, e.g. using PhotoSync, will be much faster. You can also chose a folder stricture with PhotoSync or upload them to your import folder, so that PhotoPrism can move and rename new files.

**Comment by pittbull** [comment]
Aha - those are good pointers indeed.

My end goal is to have some sort of auto sync from my phone to my private cloud, and as of new I have settled on Nextcloud. Using the NC client I can sync photos automatically to NC and then Photoprism can sync them (backend) and put them into my library. (And perhaps in turn delete them from NC?)

As of now I would like to avoid several sync points (Photosync -> Photoprism, Nextcloud client -> Nextcloud) as it complicates the rig.

**Comment by lastzero** [comment]
You may also (manually) mount your Nextcloud files via davfs2 within the Docker container or on your host: 

- https://wiki.archlinux.org/index.php/Davfs2
- http://manpages.ubuntu.com/manpages/xenial/man8/mount.davfs.8.html

Or mount the Nextcloud files volume to `/photoprism/originals` via Docker, and enable read-only mode, if on the same server. I know, a bit too much freedom :)

**Comment by lastzero** [comment]
From our experience, PhotoSync is much faster & reliable than the Nextcloud app for frequently syncing / uploading many photos.

**Comment by pittbull** [comment]
> Or mount the Nextcloud files volume to `/photoprism/originals` via Docker, and enable read-only mode, if on the same server. I know, a bit too much freedom :)

Actually leaning towards this solution now as it would solve the issues backend and transparent to me as a user. How about this: Rather than mounting the NC folder to the originals, I mount it to the Import folder and have PP import it into originals?

**Comment by lastzero** [comment]
> Actually leaning towards this solution now as it would solve the issues backend and transparent to me as a user. How about this: Rather than mounting the NC folder to the originals, I mount it to the Import folder and have PP import it into originals?

This would consume twice the storage as well unless you delete all photos & videos from Nextcloud. In that case, why not upload to PhotoPrism directly?

**Comment by pittbull** [comment]
Fair point 😁

**Comment by pittbull** [comment]
Testing out PS now but it does not support pre authentication from my reverse proxy - hence I have to bypass that for PS and I don't want to do that.

**Comment by lastzero** [comment]
VPN?

**Comment by pittbull** [comment]
Sure, got that - but another complexity. 

Another question on the import approach: Can PP delete source after import?

**Comment by lastzero** [comment]
From the import folder: Yes if you select move instead of copy, and the volume is writable. If you upload, it obviously can not delete files from your phone or other clients - PhotoSync can do that though.

**Comment by pittbull** [comment]
Cool. Yeah, good point about the phone, but I'm thinking like this:

NC on phone auto-syncing to NC replacing all media on the phone with downscaled versions (I seem to recall the app can do that). Then PP initiates import from the folder _moving_ the files to the originals folder. This takes care of the redundancy part, but I have to test what will happen to the downscaled versions on the phone. Logically they would be deleted as the item on NC have been deleted (or moved).

**Comment by pittbull** [comment]
or ... I could leave PP and NC unconnected and crontab [phockup](https://github.com/ivandokov/phockup) and move files from the NC folder directly into my library (which is mounted as the originals i PP) and the reindex.

**Comment by pittbull** [comment]
> or ... I could leave PP and NC unconnected and crontab [phockup](https://github.com/ivandokov/phockup) and move files from the NC folder directly into my library (which is mounted as the originals i PP) and then reindex.

Answering my own suggestion: Worked like a charm. NC keeps a local cache on the phone (that can be cleared) of media synced to NC so that takes care of all ends.

**Comment by x86dev** [comment]
Thanks for sharing this -- I'm in the same boat to get a setup up & running like this.
