### ISSUE TITLE
UX: Make login form autocomplete work with older password managers

### ISSUE THREAD

**Issue by Marenz** [photoprism/photoprism#1218]
When I log in, I use a password manager to auto-fill the password field. However, the "sign in" button doesn't notice that and stays gray.

If you then click in the password field, it deletes the already filled password.

I have to copy & paste my password to make things work..

**Comment by lastzero** [comment]
We don't have these problem with Chrome and the built-in password manager. You can provide us with more details on your issue?

**Comment by Marenz** [comment]
Sure: The version I used is PhotoPrism® 210222-ac5a9d5e-Linux-x86_64

The password manager in this case was https://github.com/passwordmaker/chrome-passwordmaker

The browser is vivaldi, which is chrome based.

**Comment by Marenz** [comment]
Basically I click the "fill fields" button here
![image](https://user-images.githubusercontent.com/424752/115712116-aa157980-a374-11eb-87e6-0b3e992f7c89.png)

**Comment by lastzero** [comment]
Is this photoprism specific or does it also happen with some other sites? In that case, it better to file an issue with them instead of making us develop a workaround.

**Comment by Marenz** [comment]
I am aware of only one other website that has that behavior

**Comment by lastzero** [comment]
Doing our best to take a look, but need to take care of a few other issues first (see roadmap). Contributors are welcome to send a pull requests for fixing this in the meantime.

**Comment by graciousgrey** [comment]
I am not able to test it. The links to the extension don't work and the latest commit in the repo was 2018.

**Comment by ArtNow198** [comment]
> When I log in, I use a password manager to auto-fill the password field. However, the "sign in" button doesn't notice that and stays gray.
> 
> If you then click in the password field, it deletes the already filled password.
> 
> I have to copy & paste my password to make things work..

**Comment by StephenBrown2** [comment]
I have not experienced this with BitWarden, my pw manager of choice.

**Comment by lastzero** [comment]
Seems this needs to be fixed in "chrome-passwordmaker", which is not actively maintained anymore: Last commit was three years ago. Sorry, but in this case we have to remove this from our Roadmap for now. We welcome pull requests if there is an easy workaround. @graciousgrey tried to do it and couldn't download / install the browser extension.

**Comment by lastzero** [comment]
I'll close this since we didn't receive feedback and also don't have to resources to work on patch for old password managers, who might not properly send JS events. Modern password managers seems to work well. You're welcome to submit a pull request with a fix if needed.
