### ISSUE TITLE
Find another solution (than changing the BasicAuthLevel) for connecting via WebDAV 

### ISSUE THREAD

**Issue by JulianEggers** [photoprism/photoprism#1219]
The guide for ['Connecting to a WebDAV server on Windows'](https://docs.photoprism.org/user-guide/sync/webdav/) states:

`If you still have trouble connecting via WebDAV, you may have to update the Basic Authentication Level in the registry.`

Settings BasicAuthLevel to 2 solves the issue but I think lowering this settings should not be the recommended fix?

As far as I understand, Windows doesn't let you connect to WebDAV when using self signed certificates. That is why lowering this setting solves this issue. 
The guide should be updated, in case someone knows a better fix for this problem.

**Comment by lastzero** [comment]
You could use a valid SSL certificate?

**Comment by JulianEggers** [comment]
Sure. But I'd like to use my own certificates.
But this for sure ist the better option if there is no other fix for this.

**Comment by lastzero** [comment]
Let's encrypt?
