### ISSUE TITLE
I used it very well before, then I want to use the latest

### ISSUE THREAD

**Issue by RUANHAOANDROID** [photoprism/photoprism#122]
![屏幕快照 2019-07-03 19 27 07](https://user-images.githubusercontent.com/10151414/60588097-a348fb80-9dc8-11e9-8db9-08931ca693ff.png)

**Comment by RUANHAOANDROID** [comment]
**I deleted all the previous containers.**
Last login: Wed Jul  3 19:21:31 on ttys002
macbook-pro:Photos rh$ docker-compose up -d
Creating network "photos_default" with the default driver
Creating volume "photos_photoprism-cache" with local driver
Creating volume "photos_photoprism-database" with local driver
Pulling photoprism (photoprism/photoprism:latest)...
latest: Pulling from photoprism/photoprism
5b7339215d1d: Pull complete
14ca88e9f672: Pull complete
a31c3b1caad4: Pull complete
b054a26005b7: Pull complete
8e415d3ac5ca: Pull complete
4573a9acfd0d: Pull complete
c3ac726d7255: Pull complete
fe99cf6021e5: Pull complete
dcf0e1c065f0: Pull complete
2fc20d3c9108: Pull complete
474bea89a82d: Pull complete
36ef2c40d772: Pull complete
1caa6ad98591: Pull complete
ea0ea5ed1512: Pull complete
690093a860b0: Pull complete
63f0d52b031a: Pull complete
4d8a44cfceab: Pull complete
Creating photos_photoprism_1 ... done
macbook-pro:Photos rh$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
photoprism/photoprism   latest              d979f0592a18        3 hours ago         660MB
macbook-pro:Photos rh$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                      NAMES
a0e3feda530f        photoprism/photoprism:latest   "/bin/sh -c 'photopr…"   6 minutes ago       Up 6 minutes        2342/tcp, 4000/tcp, 0.0.0.0:2342->80/tcp   photos_photoprism_1
macbook-pro:Photos rh$

**Comment by lastzero** [comment]
Container port now is **2342** (not 80 anymore) like on the host. It's easier test and deploy.

See https://raw.githubusercontent.com/photoprism/photoprism/master/docker/photoprism/docker-compose.yml

**Comment by RUANHAOANDROID** [comment]
Thank you, I can play happily again.
