### ISSUE TITLE
The document of REST api can not be found, Is there any other way I can find it ?

### ISSUE THREAD

**Issue by fineTu** [photoprism/photoprism#1223]
I want to write a plugin in my own project which need login and query data via REST api. But I found that REST api document with link[https://github.com/photoprism/photoprism/wiki/REST-API]( https://github.com/photoprism/photoprism/wiki/REST-API ) has been redirected to the main page of the project. Is there any other way I can find it ? Or there is some problem?

**Comment by StephenBrown2** [comment]
Unfortunately the REST api isn't documented as of yet, but you can look at the files in https://github.com/photoprism/photoprism/tree/develop/internal/api and see the endpoints.

**Comment by fineTu** [comment]
OK, and if there are any key word for searching LOGIN or AUTH api ? I Only found an auth function without REST api.

**Comment by fineTu** [comment]
I finally extract api with fiddler.thanks for help!I finally extract api with fiddler.thanks for help!
