### ISSUE TITLE
Album sharing with API access

### ISSUE THREAD

**Issue by skrat** [photoprism/photoprism#1225]
My use case is similar to the share feature, where some kind of token is generated that can be used to access the album under "guest" user. Is this also available from API? Say I want to use those tokens to download the album as JSON from the current API (eg. https://example.com/api/v1/photos?count=60&offset=0&album=aqrhl743auwse1mf) and then of course without authentication access the photo file as well as the generated tiles. This would be immensely useful for embedding albums in a (static site generator) blog and such.

Is this already possible and I'm missing something or would I need to implement this in my fork?

**Comment by skrat** [comment]
On a related note, do the thumbnails really need to be protected by authentication? IMO this is where security through obscurity shines, the only way to access them would be knowing the original file hash. By removing token from the URL photoprism can serve the files, and all the embedder needs to get is that photos API result. So a rather small change to the photos API would allow easy embedding.

**Comment by lastzero** [comment]
Thumbnails are not protected by authentication.

**Comment by lastzero** [comment]
You may use the API to create share tokens (see JS code for examples). A post request to the session endpoint will create a session with which you can authenticate against the API:

https://github.com/photoprism/photoprism/blob/develop/frontend/src/common/session.js#L208

**Comment by skrat** [comment]
@lastzero thanks, I figured it out, here's a minimal viable example using nothing but web components and fetch API

https://gist.github.com/skrat/6cc9ede841a353df96c4fa4debc8ee7d
