### ISSUE TITLE
Index: Add native support for the WebP image file format

### ISSUE THREAD

**Issue by zaywalker** [photoprism/photoprism#1226]
I wonder there is any plan to support webp format. This could be very helpful who collect pictures from web. :)

**Comment by graciousgrey** [comment]
See https://github.com/photoprism/photoprism/issues/668 :)

**Comment by zaywalker** [comment]
Oh I see. I thought that one is to use webp thumbnail instead of jpg. I mean to parse webp images. Thanks anyway. :)

**Comment by lastzero** [comment]
Good question... it's a web optimized image format not used for photography in general. If not done yet, we can support it by converting it to JPEG.

**Comment by NewbieAI** [comment]
Hi! I am new to open source and looking to make my first contribution. I do have some experience with image processing. Still learning the basics of the Photoprism codebase, but given some time, I might be able to write function that automatically detects webp files and convert them to jpeg.
What's the best way for me to help with this issue? I would really appreciate it if someone can point me at the right direction!!

**Comment by lastzero** [comment]
@NewbieAI This is now implemented in a first version, help with testing is very welcome! I'll start a new development preview build later today.
