### ISSUE TITLE
Photosync on Android cant connect using webdav

### ISSUE THREAD

**Issue by comprido** [photoprism/photoprism#1228]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/1228)

I am a user of photosync for a while and always used Samba to backup my phone (android) pictures to my server.
I have just installed Photoprism (using docker) and everything seems to work great, I read in the forums that the recommended way to trigger automatic sync is by using the internal webdav server that comes with Photoprism.

So I go to photosync and configure the webdav, type the server IP (my_local_ip) PORT (2342), Login (admin), Password (I_leave_empty), CLIENT_CERTIFICATE (I_leave_empty), DIRECTORY (/originals/), and I do not check the checkbox USE SSL.

Always gives me error: "Login Error:  OK"
Do not matter what Login/Password I place, I tried everything, always the same error.

I look at the logs, they don't track anything about that error, Am I doing something wrong, or is this really a bug?

This is my docker compose that I used for Photoprism. 

version: "2.1"
services:
  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    hostname: photoprism
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_EXPERIMENTAL=true
      - PHOTOPRISM_PUBLIC=true
      - PHOTOPRISM_READONLY=true
      - PHOTOPRISM_ADMIN_PASSWORD={removed}
      - PHOTOPRISM_LOG_LEVEL=debug
      - PHOTOPRISM_DEBUG=true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined           
    volumes:
      - /mnt/NAS/Photos:/photoprism/originals 
      - /mnt/NAS/Photoprism/storage:/photoprism/storage 
      - /mnt/NAS/Photoprism/import:/photoprism/import
    ports:
      - 2342:2342
    restart: unless-stopped

Note: I also tried to connect to webdav using windows, followed your tutorial  (https://docs.photoprism.org/user-guide/sync/webdav/), and when I reach the last step, I have windows always giving the error  "the folder you entered does not appear to be valid. Please choose another)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/19432439?v=4' alt='bitbacchus' width=24 height=24> bitbacchus](https://issuehunt.io/u/bitbacchus) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by StephenBrown2** [comment]
I believe you need to use the import folder, as PhotoPrism will import the pictures automatically as they are uploaded. Otherwise you would need to reindex your collection every time you synced from your phone.

**Comment by graciousgrey** [comment]
@StephenBrown2 Automatic syncing works with both import or originals folder. PhotoSync uses WebDAV to move files into import or originals. After a short timeout PhotoPrism will then automatically import or index.

@comprido  I see you are using PhotoPrism in public mode, it might be that WebDav is disabled in your settings (https://docs.photoprism.org/user-guide/settings/advanced/#disable-webdav). Could you check that?

**Comment by comprido** [comment]
Thanks for your quick replies
@StephenBrown2 I don't want to break the folder directory of my originals, so using import unfortunately is not a good solution or me.

@graciousgrey Yes, it is active, that was the first thing I made sure :). Also this morning I installed another webdav client on my windows machine called Bitkinex. And with that software works fine... So I am even more confused now.
It does not work with the buildin windows 10 webdav client (the one that's mentioned in the tutorial) and it does not work with the webdav client that is provided with Photosync.
This is really strange, is there a place where I can see more logs. As you can in my config I have enabled all possible logs and debugs (I think)
And yes, I am now using public mode, actually I set to public mode in the hope that webdav would work :). So with or without public mode I had the same problem.

**Comment by comprido** [comment]
I guess it's a bug then

**Comment by ayvazjet** [comment]
Windows 10 için Posta ile gönderildi Kimden: compridoGönderilme: 27 Nisan 2021 Salı 21:57Kime: photoprism/photoprismBilgi: SubscribedKonu: Re: [photoprism/photoprism] Photosync on Android cant connect using webdav (#1228) I guess it's a bug then—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lastzero** [comment]
You may enable debug mode to see more logs (requires a restart).

You said you left the password field empty ("Password (I_leave_empty)")? In that case, authentication fails.

Directory `/originals`/ is OK, I use the same. You may need to set a destination folder (or `/` for main) in FOLDER SETTINGS as well.

**Comment by comprido** [comment]
Hello @lastzero 
Thanks for your input. 
For the password, I do actually have a password, I just didn't paste it here.
Regarding debugging, I believe I have already enable it. I have also done several reboots after enabling it.
I am is not exactly sure where to get the logs of the debug.
For the destination folder, I can't even reach that step, because I am stuck in the first step (configure webDAV account), only after the account is configured "thats where I get the error described", I can configure the FOLDER SETTINGS.

**Comment by comprido** [comment]
I do not use directly docker-compose, I am using portainer.
As you suggested, I went to the logs of portainer and the following messages popup when when I try to confirm the webdav in Photosync and gives me the error "Login Error: OK"

time="2021-04-30T11:54:57+02:00" level=debug msg="http: PROPFIND /originals/ (200) [25.619083ms]"
time="2021-04-30T11:55:01+02:00" level=debug msg="http: PROPFIND /originals/ (200) [23.54423ms]"
time="2021-04-30T11:55:03+02:00" level=debug msg="http: PROPFIND /originals/ (200) [27.205883ms]"
time="2021-04-30T11:56:21+02:00" level=debug msg="http: PROPFIND /originals/ (200) [51.771871ms]"

But, I can't conclude anything with those messages.

**Comment by lastzero** [comment]
Do the logs say anything about webdav enabled/disabled (right when it starts)?

**Comment by comprido** [comment]
@lastzero I think you just hit the nail.
Indeed, when I look at the logs I see the following msgs
time="2021-04-30T12:30:47+02:00" level=info msg="webdav: server disabled"
time="2021-04-30T12:30:47+02:00" level=info msg="http: starting web server at 0.0.0.0:2342"

Strange, because I thought it was enabled by default, and when I connect using bitkitnex webdav client it seems to works.
So, I am very puzzled with this.
I do not have any option in my config to disable it, this flag is not even present in my config PHOTOPRISM_DISABLE_WEBDAV

**Comment by lastzero** [comment]
Please check your Settings for "read-only mode" and "disable webdav" (both should not be selected):

![Screenshot 2021-04-30 at 12 49 49](https://user-images.githubusercontent.com/301686/116685476-b1f79e00-a9b2-11eb-8257-b5c38a8e0e39.png)

**Comment by comprido** [comment]
Ummm, no advance options

![image](https://user-images.githubusercontent.com/13604825/116691629-5bdb2880-a9bb-11eb-8847-27a60b964d02.png)

**Comment by lastzero** [comment]
Then you're probably still in public mode.

**Comment by comprido** [comment]
yep, you are right.
It is OK now
Many thanks for your assistance, and keep up the good work on this great software.

If I can give a suggestion, I think it's a good idea to mention those restrictions somewhere in your documentation.

**Comment by cybrengineer** [comment]
I was having similar issues with getting "Login Error: OK" using photo sync. The solution ended up being to change the storage location to /photoprism/originals/ since this is where the webdav server is enabled. I found this going through the log files with: 
`docker-compose logs -f | grep "webdav"`

**Comment by asakusuma** [comment]
I'm having the same issue and symptoms in the photosync app (Login error: OK), but my logs look a bit different. I don't see anything about webdav being disabled. Sharing is enabled in the settings. Logs seem to indicate things should be working:
```
time="2022-01-12T16:36:31-08:00" level=info msg="webdav: /originals/ enabled, waiting for requests"
time="2022-01-12T16:36:31-08:00" level=info msg="webdav: /import/ enabled, waiting for requests"
time="2022-01-12T16:36:31-08:00" level=debug msg="http: successfully initialized [112.112659ms]"
time="2022-01-12T16:36:31-08:00" level=info msg="http: starting web server at 0.0.0.0:2342"
```
![photosync-prism](https://user-images.githubusercontent.com/597574/149245713-71c5f805-7cba-465d-b445-e28bcc08296a.png)

FWIW, I'm using Unraid. I tried the `/`, `/photoprism/originals/`, `/originals`, and my import directory configured at "Photo Import Folder" in the docker app settings.

**Comment by asakusuma** [comment]
Ah I am using public mode right now, I did not realize public mode and webdav were incompatible. Is there another way to use photosync on my LAN with public mode turned on?

**Comment by graciousgrey** [comment]
@asakusuma yes, webdav is disabled in public mode for security reasons. 
PhotoSync offers multiple target options, "Computer" or "SMB" might work for you.

**Comment by lastzero** [comment]
We spent a good amount of time this week improving our docs to make this clearer, for example here:

- https://docs.photoprism.app/getting-started/config-options/#basic-settings
- https://docs.photoprism.app/user-guide/library/webdav/
- https://docs.photoprism.app/user-guide/sync/webdav/
