### ISSUE TITLE
where is the file: github.com/pingcap/tidb/x-server?

### ISSUE THREAD

**Issue by jessezwd** [photoprism/photoprism#123]
the "internal/tidb/server.go" imports "github.com/pingcap/tidb/x-server", it  seems no x-server file in tidb.

**Comment by lastzero** [comment]
Should be in your go path / go modules cache directory after you run "make dep-go" (included in "make dep" or "make all") in the project main directory. I recommend using an IDE like GoLand and find and view dependencies:

![Screenshot 2019-07-07 at 11 38 48](https://user-images.githubusercontent.com/301686/60766577-d252bc00-a0ab-11e9-8c60-f691e6aaba5c.png)

**Comment by jessezwd** [comment]
@lastzero Thanks a lot!
