### ISSUE TITLE
UX: Enable long-touch menu in photo viewer on iOS

### ISSUE THREAD

**Issue by jkgeyti** [photoprism/photoprism#1233]
With the recent release, and the improved touch support, photoprism is finally usable on iOS! Loving all the good work and fantastic additions 🎉 There's still a handful of issues wrt downloading and sharing, but in the interim, it'd be good to be able to copy the JPEG shown in the photo viewer, so images can be quickly shared with other apps.

In desktop browsers, you can right click images to get a context menu that includes a "Copy image" context menu, but on iOS, `-webkit-touch-callout: none` is set on images shown in the popup full-screen image viewer, which disables the long-press context menu.

As a quick hack, adding the following css and long-clicking images produces the context menu shown in the screenshot below. I'm not sure if there's any good justification for disabling the context menu on mobile devices, but if not, it'd be really convenient if it could be enabled 🙏 .

```
.pswp__img {
    -webkit-touch-callout: default !important;
}
```

<img src="https://user-images.githubusercontent.com/617033/116137732-d100e200-a6cb-11eb-89be-b1b6a094ae41.png" width="250" />

**Comment by vader355** [comment]
Jk

**Comment by graciousgrey** [comment]
We use photoswipe for the fullscreen viewer, so we did not implement it on our own. There might be a reason why it is implemented this way. Changing this would require testing on all kinds of devices and browsers which we cannot afford at the moment. Opening images in other apps is planned see: https://github.com/photoprism/photoprism/issues/25 or https://github.com/photoprism/photoprism/issues/658

**Comment by jkgeyti** [comment]
Makes sense. I've raised it as a request on the photoswipe repo.

**Comment by jkgeyti** [comment]
This is targeted to be solved in photoswipe v5 (unreleased) 

https://github.com/dimsemenov/PhotoSwipe/issues/1748#issuecomment-829131012

**Comment by Soulplayer** [comment]
I see that version 5 is released yet it does not work on photoprism. This would be a great addition 😇?

**Comment by lastzero** [comment]
After testing it locally, I added this bit of CSS as a workaround until we have a new viewer. It's available for testing in our development preview and demo in about one hour.

**Comment by lastzero** [comment]
Note that this COULD confuse some users, since the menu refers to the image displayed in the viewer. However, this is only a thumbnail without metadata, not the original file.

**Comment by Soulplayer** [comment]
Okay it’s better then nothing. Thanks! I will subscribe today to support the project

**Comment by Soulplayer** [comment]
Just want to let you know it works in safari on iOS but in the PWA version not.

**Comment by lastzero** [comment]
I remember that we discovered problems with the menu, eg after updating to a new iOS version. That was a while ago and I'm not using iOS very often (just on the iPad), so unfortunately, I don't remember any details.

**Comment by graciousgrey** [comment]
I created a follow up issue for this:

- https://github.com/photoprism/photoprism/issues/3362
