### ISSUE TITLE
The download button on iOS produces tiny svg files for download

### ISSUE THREAD

**Issue by jkgeyti** [photoprism/photoprism#1234]
On iOS safari, the download button, including the one for downloading a single image in the Edit > Files Dialog, produces an SVG file that is 420 bytes long. Occasionally, a JPEG is produced, but I've not been able to determine what causes one or the other to happen.

<img src="https://user-images.githubusercontent.com/617033/116139927-82087c00-a6ce-11eb-9d95-db05193fcdb3.png" width="250" />

**Comment by friendyou1** [comment]
I posted a picture of myself

**Comment by lastzero** [comment]
Tested it on macOS Safari... works as expected. My assumption is that the original file can not be found, so the backend API returns a "broken file" SVG icon. This should not happen unless the file can not be found / read. Can you check filesystem permissions and if all originals are still there? You may also try reindexing.

**Comment by lastzero** [comment]
@graciousgrey Can verify download is working on iOS?

**Comment by jkgeyti** [comment]
Desktop browsers, including MacOS Safari works fine. It’s only an issue on iOS. If you can’t replicate it, I’m happy to provide a minimal example. For reference, my library consists of a RAW and JPEG copy of all images. I’m sharing that because I think there’s something funky going on with multi-downloads on iOS, and if the individual downloads button uses the same code path, it could be relevant that there’s two images available under the Files dialogue

**Comment by graciousgrey** [comment]
For me it works as expected.  I can download jpegs or raws without problems. What iOS version are you using?

**Comment by jkgeyti** [comment]
14.4 and photoprism:latest. Happens on two different iPhones I’ve tested on. 

Sounds like it’s not consistently happening, so it’s probably related to my setup or the images themselves. I’ll try and expand this ticket with a (hopefully) reproducible example soon.

**Comment by jkgeyti** [comment]
I've not looked into it in detail, but I can confirm that it only happens behind an nginx proxy. Accessing photoprism directly on the hosted port works fine. I'm not running a particularly esotoric setup, so I'll come back to this and do some more investigation later, as it may (at least) potentially affect [the documentation](https://docs.photoprism.org/getting-started/advanced/nginx-proxy-setup/) .

**Comment by lastzero** [comment]
Nginx configuration is known to be complex and error prone, would you mind trying traefik or caddy?

**Comment by lastzero** [comment]
Might be fixed with our latest update. Might have been an nginx issue anyway, so I'll close this for now.

**Comment by calebnp** [comment]
I am still having this issue with Nginx and the current version of PhotoPrism (220121). Is there a solution or something I should change in Nginx to make it download correctly? At the moment, I'm just working around it by having the web app use the IP address and port number to access PhotoPrism.

**Comment by lastzero** [comment]
If it works without nginx, then you might have to change the config.

**Comment by calebnp** [comment]
I’ll report back if it breaks again, but it seems the solution in Nginx Proxy Manager is to check the box to enable Websockets support.
