### ISSUE TITLE
Videos: Improve preview image generation depending on duration

### ISSUE THREAD

**Issue by electricpollution** [photoprism/photoprism#1241]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/1241)

Video thumbnails are currently created from the first frame hardcoded with the code `-ss 00:00:00.001 -vframes 1.` Any video that has a black first frame or anything not meaningful is not useful for previews. 

Suggest defaulting to the first frame or having a parameter to customize how many seconds  into the video a preview is created.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars.githubusercontent.com/u/62509689?v=4' alt='electricisfun' width=24 height=24> electricisfun](https://issuehunt.io/u/electricisfun) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by graciousgrey** [comment]
Related discussion: https://github.com/photoprism/photoprism/discussions/1235

**Comment by G2G2G2G** [comment]
Get video full length:
`
ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 videofile.mkv
`

Get video black bars and remove them. Useful if someone has.. black bars encoded into the video. (python running a bash script 10 times and averaging it, so in Go you'd just do the same thing):
```Python
croplist = []
for x in range(10):
    times = str(random.randint(3,59))
    cropcheckcmd = "ffmpeg -ss 00:" + times + ":00 -i \"" + filename + "\" -t 1 -vf cropdetect=17:4:3000 -f null - 2>&1 | awk '/crop/ { print $NF }' | tail -1"
    cropcheck = subprocess.run([cropcheckcmd], stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8').rstrip()
    print (cropcheck)
    croplist.append(cropcheck)
print (croplist)
cropmode = mode(croplist)
```
This "croplist" should work directly into ffmpeg as `-vf "CROPLISTVARIABLEHERE"` (including the quotes)


Last all that is needed is to pick a random time from 0 to the end of the original "duration" of the video. 

Looks like what @graciousgrey guy linked they were already looking at a thumbnailer program though. That is a good project it's used in almost all of the linux file managers. I know he said he was trying to not use C++ stuff though so my above implementations you can cut out black bars + get full duration + pick a random timestamp to make a thumbnail out of while only calling FFMPEG. you can replace AWK with something in Go to parse the output instead.

**Comment by G2G2G2G** [comment]
Actually ignore that crap above you can extract frames purely in ffmpeg
https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect
>value between 0 and 1 to indicate a new scene; a low value reflects a low probability for the current frame to introduce a new scene, while a higher value means the current frame is more likely to be one (see the example below)

This is all you need for every video:
`ffmpeg -i VIDEOFILE.mkv -vf "select=gt(scene\,0.2)" -frames:v 1 -vsync vfr thumbnail.jpg`

the magic is here: `scene\,0.2` this is generous here, a video file that does not have a lot of pixel shifts is going to get a thumbnail here. However the thumbnail may be in the beginning of the video and not a very good thumbnail. 
If you want a great thumbnail, maybe make this a setting so people can say "yes I want better thumbnails" or whatever. 
But you check less generously and if it fails, have a fallback to a more generous check, like this:

```
//great action shot
ffmpeg -i VIDEOFILE.mkv -vf "select=gt(scene\,0.8)" -frames:v 1 -vsync vfr thumbnail.jpg
//if it succeeded you are DONE!
ELSE IF IT FAILED:
//medium action shot
ffmpeg -i VIDEOFILE.mkv -vf "select=gt(scene\,0.5)" -frames:v 1 -vsync vfr thumbnail.jpg
//if it succeeded you are DONE!
ELSE IF IT FAILED:
//low action shot
ffmpeg -i VIDEOFILE.mkv -vf "select=gt(scene\,0.1)" -frames:v 1 -vsync vfr thumbnail.jpg
DONE

```
or something like that, this is what I'd personally do. However that is the only command you need.

**Comment by lastzero** [comment]
@G2G2G2G Any idea what the performance impact might be, if any?

**Comment by G2G2G2G** [comment]
@lastzero how fast is it now? I tested on a "hollywood movie" the 0.1 and 0.2 are almost instant 
All of my videos are h264 as well so it's very fast decode. and it is ryzen 3700X processor. 

From my test I think yours (for me) would be around "902.35 millis" and vs the 0.2 which is "1.02 secs" I think that's well worth it. 
(assuming millis in the linux time command is milliseconds so 902 is almost 1 second, so they basically take the same time)

```
THIS IS TAKING THE FIRST FRAME OF VIDEO, NO PROCESSING AT ALL BASICALLY, AND NO FILTER FLAGS! 
IT IS A "CONTROL" 
Executed in  902.35 millis    fish           external
   usr time   75.65 millis  344.00 micros   75.31 millis
   sys time   35.99 millis  147.00 micros   35.84 millis



0.2

Executed in    1.02 secs      fish           external
   usr time  361.55 millis  391.00 micros  361.16 millis
   sys time   41.46 millis  118.00 micros   41.34 millis


0.4

Executed in    1.43 secs    fish           external
   usr time    4.60 secs  379.00 micros    4.59 secs
   sys time    0.10 secs  112.00 micros    0.10 secs


0.6

Executed in    1.64 secs    fish           external
   usr time    8.74 secs  361.00 micros    8.73 secs
   sys time    0.21 secs  115.00 micros    0.21 secs


0.8

Executed in    3.88 secs    fish           external
   usr time   28.50 secs  365.00 micros   28.50 secs
   sys time    0.57 secs  129.00 micros    0.57 secs
```

For me, personally, 0.8 is worth it taking 4 seconds to process the frame it finds is only like 20 seconds into the video.. So if you have like a long video and it never finds one with a lot of pixels changing then it's gonna take a LONG time since it'd go through the whole video and fail.. and then try a lower number.

**Comment by G2G2G2G** [comment]
Technically there's no guarantee that even a 0.1 threshold would work if your video is extremely dark / black almost the entire thing. Somewhere I have videos of us exploring a cave that are terrible videos, if I can find them I'll test it but I guess we need a fallback to just grab the first frame as you do now, in the very worst case?

**Comment by lastzero** [comment]
Bottom line is that a fallback must be implemented and tested, so it's a bit more complicated than just replacing the current ffmpeg command?

**Comment by G2G2G2G** [comment]
Since someone can upload a video that is just all 1 color and never changes, yes. If we guaranteed people would upload actual videos then we can guarantee 0.1 would get a thumbnail. But we can't guarantee what people upload.

**Comment by G2G2G2G** [comment]
What needs to be done to add this? I feel bad for @StianOby and @axllent https://github.com/photoprism/photoprism/issues/648 lol

I can write this in like 15 minutes. Where is a video thumb created which function? https://github.com/photoprism/photoprism/tree/develop/internal/thumb I cannot find it

I've tested scene\,0.8 on thousands of random videos on imgur.com and none failed. My fear is a lightning video like: https://www.youtube.com/watch?v=Q8j5T3Qn5G0 will only work on 0.6: 
![thumbnail](https://user-images.githubusercontent.com/50514477/128618132-d74042d9-18c2-48ac-9d0f-877e9f9c9dcc.jpg)
`ffmpeg -hide_banner -y -loglevel error -i A\ Lightning\ Strike\ at\ Night-Q8j5T3Qn5G0.mp4 -vf "select=gt(scene\,0.6)" -frames:v 1 -vsync vfr thumbnail.jpg`


However terrible videos (like the one I uploaded that is entirely white the entire duration) won't find any movement.. obviously

https://user-images.githubusercontent.com/50514477/128617998-38069e40-902a-45b8-a3aa-360e0714126f.mp4

**Comment by Jarvid** [comment]
Hello,

my 2c as I just stumbled accross the black thumbnail (black screen in 1st second) problem:

**Customization** of the thumbnail **generation** is hardly worth the effort.
Every setting will work one some, but fail on other videos.

Either the thumbnail is custom, where the user can select a specific frame of the video in the GUI or upload a specific picture,
or
simple create a collage thumbnail. 

Did it with a 2x2 layout to have big enough pictures even on a mobile.
Took the duration(video playback time) from the Mediafile metadata to get 4 frames evenly distributed on the source videos. 
Only 4 lines in covert.go.
But Indexing is slower now and scales with the playback time of the video. Took 25 seconds for a 60 minutes video with 2giga bytes file size while the original approach was only 1 second. 

I'm happy with the result though. Unless you happen to have a lot of collage pictures in your library, this change makes videos also more distinguishable from pictures aside from the little arrow icon.

**Comment by lastzero** [comment]
We need the full, first frame so it can be used as still image for [Live Photos](https://docs.photoprism.app/user-guide/organize/video/#live-photos). Otherwise, the UI would have to load the entire video just to display the first frame. Note that Live Photos will only play when you hover over them with the mouse, for example in search results.

**Comment by Jarvid** [comment]
I see, is this still limited to videos up to 3 seconds or intended to be used for all kind of videos in the Future?

The former case could be easily solved as I check the duration anyways. ofc using the same function to decide if it is a live video if already there would be the best way.
If it is the other case things would require more thought.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jarvid** [comment]
Excuse my way to write the same content in a new reply again, but I as orignally answered via E-Mail github does not allow to use markdown in reply.

I see, is this still limited to videos up to 3 seconds or intended to be used for all kind of videos in the Future?

<del>I additionally now check for isLive(). If true it takes the first picture as before. A collage for a ~3 sec video is unlikely to produce any benefit anyways.
If false it creates the 2x2 tile thumbnail.
Not sure if this logic is to everyones liking or if this few lines even justify a pull request.</del>

-edit-
Ok, isLive() is always false im my 2 seconds hvc test example, even tough it is correctly typed as live by photoprism.
Is this data populated later?
But aside from this thing:
I don't see any network traffic difference indicating it is loading the entire video for the first frame.
It behaves just as in an unmodified photoprism instance. Well with the current difference, the thumbnail is a collage and once you mouseover the clip starts just normal.
I've attached a video to show the current way it looks.



https://user-images.githubusercontent.com/13620071/152652839-71cece92-c9f4-4ccf-9316-98bb0e11887d.mp4

**Comment by lastzero** [comment]
> Is this still limited to videos up to 3 seconds or intended to be used for all kind of videos in the Future?

The type is determined automatically based on the duration (and possibly other properties like the codec, see public source code), but it is possible to change it manually. So to avoid unnecessary complexity, it would be best to always have the same behavior - at least until we can pay an armada of developers to implement bells and whistles.

**Comment by lastzero** [comment]
With this commit, still images from live photos remain unchanged, while other videos may get better thumbnails, especially if the first few frames are just black or white. It's still not perfect, but hopefully an improvement.

**Comment by spyfly** [comment]
Commit https://github.com/photoprism/photoprism/commit/78151a78ee477299dffdb433e9870849888e9729 is a great improvement overall, but for videos with longer intros this can be problematic. 

Could you make this value configurable within the convert command?

**Comment by lastzero** [comment]
Generally yes, but I don't have time to add a config for it. What delay would be good instead of the 9 seconds? Note that this is dynamic and depends on the length of the video.

**Comment by spyfly** [comment]
I think going for something like 30 seconds to a few minutes would be a good idea

**Comment by lastzero** [comment]
How about this?

**Comment by spyfly** [comment]
> How about this?

Thanks, looks good, will test when it is in the preview branch 👍
