### ISSUE TITLE
Filter photos without an album

### ISSUE THREAD

**Issue by pmalek** [photoprism/photoprism#1242]
I'd like to have a possibility to filter photos without an album so that I can select them and assign to an album of my choice.

If this ends up being wanted by the community I'm willing to help with the implementation.

**Comment by graciousgrey** [comment]
You can find photos that are not part of any album in the section unsorted: https://demo.photoprism.org/unsorted :)

**Comment by pmalek** [comment]
🤦 Right, I didn't see it. Thanks!
