### ISSUE TITLE
RAW: Add config options to disable specific converters

### ISSUE THREAD

**Issue by rizmot** [photoprism/photoprism#1245]
As a user with a lot of RAW files edited in RawTherapee I would like to be able to have the option to switch to RawTherapee for RAW-conversion. Either by having an option to choose between different RAW-processors or by photoprism automatically using RawTherapee when it detects *.pp3 sidecar-files alongside the original RAW-file.

**Comment by lastzero** [comment]
We've added advanced options to disable specific image / video converters:

![options](https://user-images.githubusercontent.com/301686/116694719-e887e580-a9bf-11eb-8bf8-97357d183c8c.jpg)

**Comment by rizmot** [comment]
I tested the following scenarios: 

A - enable only RawTherapee: Images will be converted with RawTherapee but existing profiles/sidecars will not be used by RT.

B - enable only Darktable: Images will be converted with Darktable and existing profiles will be used. But changes to the profiles will not be picked up upon re-indexing.

**Comment by lastzero** [comment]
Thanks for testing!

- True, I didn't add / change any RawTherapee parameters. From what I remember, the standard profile is used by default. Probably need to modify the command to use other profiles / sidecars. Is that a generic way to do this or do we need to add yet another config parameter to set a profile name / type?
- What do you mean with "changes to the profiles" being picked up? Do you expect all existing JPEGs to be deleted and re-created when indexing?

**Comment by lastzero** [comment]
Tweaked Settings and their descriptions a bit, DarktablePresets has been renamed to RawPresets to be more generic:

![settings](https://user-images.githubusercontent.com/301686/116776374-5c7dc880-aa68-11eb-87e1-2d777c0b8fcd.png)

RawTherapee uses the profile in `/photoprism/assets/profiles/raw.pp3`. You should be able to create a custom profile and mount it into the container via Docker, so that no extra config parameters are needed. Of course this is only for advanced users.

**Comment by rizmot** [comment]
>     * Is there a generic way to do this or do we need to add yet another config parameter to set a profile name / type?

I am not familiar with the details of rawtherapee cli parameters and short on spare time but maybe i can investigate this later. But it looks like the "-s" parameter could achieve this: https://rawpedia.rawtherapee.com/Command-Line_Options

>     * What do you mean with "changes to the profiles" being picked up? Do you expect all existing JPEGs to be deleted and re-created when indexing?

Yes, every RAW has its own specific sidecar-profile change with every edit and it would be nice to see the JPEGs recreated. In my specific case this translates to a collection of RAW photos of negative film strips. As it is now, untouched RAWs would then be shown as a negative in photoprism and stay that way even after inverting them in RawTherapee or Darktable.

**Comment by lastzero** [comment]
> Yes, every RAW has its own specific sidecar-profile change with every edit and it would be nice to see the JPEGs recreated. In my specific case this translates to a collection of RAW photos of negative film strips. As it is now, untouched RAWs would then be shown as a negative in photoprism and stay that way even after inverting them in RawTherapee or Darktable.

That's somewhat advanced in that sidecar files have to be monitored for relevant changes. Keep in mind recreating RAWs may require significant time / CPU resources, so it's not something we should do "just in case". Can you add a new feature request for this please, so that we can put it on our roadmap?

When you edit RAWs in RawTherapee, why don't you export / update JPEGs at the same time? That seems way less complex than just editing profiles and let PhotoPrism create new JPEGs...

**Comment by rizmot** [comment]
> True, I didn't add / change any RawTherapee parameters. From what I remember, the standard profile is used by default. Probably need to modify the command to use other profiles / sidecars. Is there a generic way to do this or do we need to add yet another config parameter to set a profile name / type?

So i tested the following command: `rawtherapee-cli -d -p raw.pp3 -s -o output.jpg -c input.RAW`
This will use the default ( `-d` ) profile, then if another profile is specified ( `-p raw.pp3` ) it will be stacked on top of the default profile. Then, if the `-s` command is set, a sidecar-profile, if one is found, will be stacked on top of whatever was specified before. The `-d -p -s` parameters have to be set in the right order since the last one will overwrite the ones before. As I understand it, `-d` and `-p raw.pp3` might be optional in this case. So `rawtherapee-cli -s -o output.jpg -c input.RAW` should do the trick.

**Comment by rizmot** [comment]
> That's somewhat advanced in that sidecar files have to be monitored for relevant changes. Keep in mind recreating JPEGs from RAWs may require significant time / CPU resources, so it's not something we should do "just in case". Can you add a new feature request for this please, so that we can put it on our roadmap?

I will add a feature request for this :-)

> When you edit RAWs in RawTherapee, why don't you export / update JPEGs at the same time? That seems way less complex than just editing profiles and let PhotoPrism create new JPEGs...

Well that is what i am doing right now and of course this works well. But then I don't need RAW conversion in photoprism at all. My goal is to display my photos in photoprism and the work has to be done either way. So if photoprism does it for me I won't have to maintain extra JPEGs while having a convenient gallery to see the state of my photo collection.

**Comment by lastzero** [comment]
We've just release the new config options. Changing the command parameters takes a bit more time. Can you also create a new issue for this, based on the information in your comment above?
