### ISSUE TITLE
/usr/bin/ld: can't find -ltensorflow

### ISSUE THREAD

**Issue by jessezwd** [photoprism/photoprism#125]
I got an error "/usr/bin/ld: can't find -ltensorflow" under command "make dep-go", it seems I need install some lib file. right?

**Comment by lastzero** [comment]
Obviously, you don't have the tensorflow library installed. I've compiled it for various operating systems and processors:

https://dl.photoprism.org/tensorflow/

Also you can compile PhotoPrism using our ready-to-use docker images, as described in the Developer Guide (GitHub Wiki).

**Comment by lastzero** [comment]
Extract the [downloaded](https://dl.photoprism.org/tensorflow/) tar archive for your operating system / architecture and configure the linker with ldconfig:

    sudo tar -C /usr -xzf (downloaded file)  
    sudo ldconfig

The archive contains the header files to include in your C / Go program and the shared libraries to link against.

We also provide pre-compiled Bazel binaries for the NVIDIA Jetson as well as our configuration for those who want to compile TensorFlow on their own.

Official builds: https://www.tensorflow.org/install/lang_c

**Comment by lastzero** [comment]
See also https://github.com/photoprism/photoprism/wiki/Setup

**Comment by jessezwd** [comment]
@lastzero Thanks a lot! Problem has been solved.
