### ISSUE TITLE
Converting .mov to avc (libx264) during scroll through = 180% CPU usage

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1254]
I recently uploaded a bunch of photos from an iPhone and now scrolling performance is horrible. I've even shifted my 0.5TB photo collection off my rust-drive NAS to a screaming fast nvme drive and if anything, scrolling is actually worse!

I noticed while scrolling lots of this in my logs:

```
time="2021-05-02T09:36:03Z" level=info msg="converting 2019/09/20190927_112935_67F0678B.mov to avc (libx264)"
time="2021-05-02T09:36:06Z" level=info msg="converting 2019/09/20190925_171029_3CD916B2.mov to avc (libx264)"
time="2021-05-02T09:36:09Z" level=info msg="converting 2019/09/20190927_112751_D17DC9A6.mov to avc (libx264)"
time="2021-05-02T09:36:12Z" level=info msg="converting 2019/09/20190927_112829_C11359A4.mov to avc (libx264)"
```

Is photoprism doing transcoding on the fly here? I'm running on a VM and in docker, on a` CPU(s) 4 x 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz` and the photoprism process sometimes hits 180% CPU usage even while scrolling. I can understand this while importing (it's doing a lot..tensor flow and transcoding stuff!) but it's worrying to see this much usage even while browsing!

**Comment by lastzero** [comment]
Run photoprism convert in a terminal for upfront transcoding.

**Comment by lastzero** [comment]
Might be short videos, which are shown as live photos - so they start playing when you hover. Thus, they need transcoding. Only thing we can do is disabling this feature if it bothers you and you don't want to transcode upfront.

**Comment by timdonovanuk** [comment]
Thanks @lastzero I'll try this! Is there any reason this doesn't happen as part of the import process?

**Comment by lastzero** [comment]
Yes, we still didn't reach our funding goal and have limited resources to implement this.

**Comment by timdonovanuk** [comment]
Ah that is a very good reason, thought it might be a technical thing :) I've just subbed up. Hope you reach your target some day!

**Comment by lastzero** [comment]
Thanks! I'll close this then - enjoy :)

**Comment by timdonovanuk** [comment]
Sorry to trouble you, is there any documenation for this "photoprism convert" command? I guess my two questions are:

a) what is actually doing? Is it taking .mov (i.e. videos) recorded on an iPhone and the .mov file that iPhone live photos produce, and convert to avc? Does it simply replace/overwrite the .mov file with a new one? What about the thumbnails video clip of live photos?

b) It is slooooow. I've seen a few threads about using hw acceleration but it's not entirely clear how to configure this (or indeed on systems that are not a Pi 4).

**Comment by lastzero** [comment]
It's creating AVC sidecar files in the sidecar path if needed. PhotoPrism never replaces originals and especially not with other formats or a different quality.

**Comment by lastzero** [comment]
You can enable hardware transcoding on the Raspberry Pi. See our example docker-compose.yml config, it's commented out. You just have to remove # and restart.

**Comment by timdonovanuk** [comment]
Thanks @lastzero! But when this tool says:

`level=info msg="converting 2020/12/20201219_163308_0761D8D3.mov to avc (libx264)"`

If I look at this file properties in Photoprism, it shows:

- 2020/12/20201219_163308_0761D8D3.mov.jpg sidecar file (which I guess represents the thumbnail of the movie)
- 2020/12/20201219_163308_0761D8D3.mov (which I presume is the original file)

So I concluded from this it was re-encoding the .mov original file :)

I see this is not the case: 

```
docker:$ ls /mnt/photos/photoprism/sidecar/2020/12/20201219_163308_0761D8D3*

2020/12/20201219_163308_0761D8D3.mov.avc  2020/12/20201219_163308_0761D8D3.mov.jpg  2020/12/20201219_163308_0761D8D3.yml
```

Should the .mov.avc not appear as a sidecar file listing in file properties?

**Comment by lastzero** [comment]
We're not actively indexing it since it's in the sidecar path, JPEGs are an exception to this since they contain important information our indexer needs (doesn't natively index all supported file formats). It would be possible to add the AVC files to the index if needed.
