### ISSUE TITLE
Docker Setup on Raspberry Pi, Photoprism exits with error 0

### ISSUE THREAD

**Issue by AMoonRabbit** [photoprism/photoprism#1259]
Trying to install the docker version on my Pi 4. I have created a user photoprism and added it to my docker group. 
As the user ID is 990, and the group is 998, I have used this in my docker config: https://pastebin.com/HMJAfY6k

I seem to have an issue that despite the user and group setup, it's creating the storage and database folder as root and systemd-coredump respectively so I run into issues such as the container not being able to create the sidecar folder within Storage.
![image](https://user-images.githubusercontent.com/3766988/116912381-08c5d780-ac40-11eb-8e60-7d3161f9ca57.png)

I used sudo chown -R 990:998 <directory> so that the specific user had permissions to run commands within the directory.

**Comment by lastzero** [comment]
You're setting the user natively and via env variable at the same time. This is not possible as the container needs to start as root in order to change the user based on the UID variable. 
![Screenshot_20210503_195319](https://user-images.githubusercontent.com/301686/116913172-6f9bbe80-ac49-11eb-91d3-1f23afb6412d.jpg)

**Comment by AMoonRabbit** [comment]
Sorry, I left that in but should have taken it out, docker-compose rejects the config when it's like that so I commented the UID and GID lines out again

**Comment by AMoonRabbit** [comment]
Seems like it is something to do with the user and group I setup. For context I used `sudo useradd -r -s /usr/sbin/nologin -m -d path -U -G docker photoprism` to create the user. I commented out the user string in the config, re-ran it and it's up but I don't want it running as root

**Comment by lastzero** [comment]
You can and should use the user prootery in docker-compose.yml if you want it to run as a specific user. Isn't this working? What's the specific error message in this case? We need to see the log messages to debug it. Thanks! :)

**Comment by AMoonRabbit** [comment]
So, this is the output of docker-compose up https://pastebin.com/6jFDQKqH

It's creating folders as root and as such cannot create subfolders inside as far as I can tell.

**Comment by lastzero** [comment]
Oh, it might be docker itself that is creating the folders as they are the main mount points and don't exist yet. Don't think there is a way to change this behaviour (if yes, please tell us how). Changing the owner via `chown -R 990:998 storage` and restarting the container should work.

**Comment by AMoonRabbit** [comment]
Okay, yes, that has got the instance up, thank you. I believe there may be a way but I honestly don't know how it would be done. But looking at my other docker containers, all the subs folders created by the server are in the configured user/group assigned so it's possible.
