### ISSUE TITLE
Feature/Request Album thumbnail customization 

### ISSUE THREAD

**Issue by Observe-1** [photoprism/photoprism#1260]
Hello enjoying photoprism a lot thanks for a great app!

Small feature request here, it would be great if we could customize the preview/thumbnail image of an album by picking a particular photo in that album to be 'featured'.

Linked to other customization features like #1241 and #1235

**Comment by graciousgrey** [comment]
Setting a custom cover image for albums is already on our roadmap :) https://github.com/photoprism/photoprism/issues/383
