### ISSUE TITLE
More prominent play button for videos in single item view?

### ISSUE THREAD

**Issue by tanuva** [photoprism/photoprism#1261]
G'day,

my fork() loves looking at photos with me in the Photoprism PWA on my phone. Videos are particularly interesting, however they are hard to discover when viewing photos in fullscreen with the controls hidden. At some point I discovered the tiny play button in the bottom bar - which is only visible with the controls non-hidden though.

How about always showing videos with a big fat '▶️' button overlay in the 'single item' view mode?

**Comment by lastzero** [comment]
Developing an improved, combined photo & video viewer is on our todo. Simply using a colored button might interfere with image contents, so not sure if everyone would be happy...

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: #1307
