### ISSUE TITLE
lost all albums.

### ISSUE THREAD

**Issue by eddyizm** [photoprism/photoprism#1262]
I made a change to the docker-compose,yml file, changing the site title, attempting to add a backup path when I realized from reading the docs that I needed to stop the container and then run the up command again. 

When the container came back up, all my images and albums, basically everything was gone. So I hit re-index, images were back and imported. 

Now looking at the yml file, I'm guessing it pulled in the latest 
`image: photoprism/photoprism:latest`

so I'm guessing the version changed but my albums are all gone. Question is, what did I do wrong? How could have I avoided this sad situation :-( and is there any way to recover the sorted images to albums?

**Comment by lastzero** [comment]
There are yaml album backups, but it seems your complete storage is gone and you have no backups. Without any storage and no backup, there is no way for PhotoPrism to restore your albums. Your database seems lost as well?

**Comment by eddyizm** [comment]
I don't know, I didn't change anything other that stopping and starting the container. I've restarted the host linux machine several times without issue. I didn't not think stopping and starting the container via the docker-compose command would wipe out all the settings or clean out the location of the db? All the file volumes (originals) and other settings were not touched. Is that normal behavior? eg. 

I didn't change any storage except adding a line in the yml file for:
`PHOTOPRISM_BACKUP_PATH`

All the other storage paths have not been touched (i only back up my originals which was why I was trying to add a path to backup the db).

**Comment by lastzero** [comment]
Starting and stopping doesn't wipe out anything, except if you didn't mount permanent storage to the paths described in our docs and example docker-compose.yml files. There is no need to change the backup path.

**Comment by eddyizm** [comment]
I'm still looking at the commands in my terminal. 
previously this did not exist in the docker-compose.yml 
`PHOTOPRISM_BACKUP_PATH` 
so I went to add it. 

Looking at my yml, the storage was setup default: 
```    volumes:
      # Storage folder for settings, index & sidecar files (DON'T REMOVE):
      - "~/.photoprism:/photoprism/storage"
       # Your personal photo and video collection ([local path]:[container path]):
      - "<localstorage>:/photoprism/originals"
 ```
Before the update, I went ahead tried to grab that data and get this result
```
ls ~/.photoprism

ls: cannot access '/home/<myusername>/.photoprism': No such file or directory
```

So I was a little confused. After the update, the directory and files were there. So I'm not sure where the hell it was before?
after: 
```
 ls -ahl ~/.photoprism
total 6.0M
drwxr-xr-x   5 root    root    4.0K May  3 13:52 .
drwxr-xr-x+ 46 username username 16K May  3 12:33 ..
drwxr-xr-x   3 root    root    4.0K May  3 12:33 cache
-rw-r--r--   1 root    root    5.9M May  3 13:52 index.db
drwxr-xr-x   2 root    root    4.0K May  3 13:33 settings
drwxr-xr-x  97 root    root     20K May  3 13:29 sidecar
```
had this up and running for months so I'd really like to figure out what I did wrong?

**Comment by lastzero** [comment]
Maybe you've been using sudo or su to change the user or run it as root? ~ may point to /root in this case. Also check file and folder permissions please.

**Comment by eddyizm** [comment]
Ok, I was able to recover, it looks like I was using root. Don't recall that happening but glad you were able to point me in the right direction. Now I'm still stuck as to how to back that up lol. 

I have nightly cron job to index new images but I can't seem to fire the backup command no matter what I'm try.  I've been reading through the github backup thread. but keep getting `No help topic for 'backup'` in all iterations. 
I was able to enter the container file system and see the sqlite db is at 20mb but not able to find where it is being mapped, possibly not mapped to any local storage it seems after this conversation, is that possible? 

Thanks for your patience!

**Comment by lastzero** [comment]
Run this in a terminal to create a database backup:

```
docker-compose exec photoprism photoprism backup -i - > backup.sql
```

No backup path or shared volume needed.

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
@lastzero 

Hello, I ran "photoprism reset" and I told it to keep album.yml files but all my albums are gone. I look in /storage/backup and i can see that i have .yml files in the albums folder so the album.yml exist in backup, following the instructions to restore (photoprism restore -i) does not work it complains that there is no mysql backup to rebuild index, but I omit -f as I do not want to force a restore of the old index, i just want my albums back. How do I restore just my albums?

**Comment by lastzero** [comment]
The command to restore albums from YAML files is `photoprism restore -a` (a for albums). Run `photoprism restore --help` for a complete command flag overview.

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
> The command to restore albums from YAML files is `photoprism restore -a` (a for albums). Run `photoprism restore --help` for a complete command flag overview.

Hello, I did this and my albums restored but there are no photos inside them. is that normal?

**Comment by lastzero** [comment]
The photos are assigned to albums based on the unique ID (UID) stored in the index (which you seem to have deleted) and in the YAML sidecar files (which you may also have deleted?).

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
> The photos are assigned to albums based on the unique ID (UID) stored in the index (which you seem to have deleted) and in the YAML sidecar files (which you may also have deleted?).

Ok I suspected maybe it was this. yes I deleted everything except for album .yml well actually I didn't delete the index from backup but i do not want to restore the old index so i will just reassign pictures to the albums at leas I can see the albums and no pictures are deleted so i can do this thanks

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
> The photos are assigned to albums based on the unique ID (UID) stored in the index (which you seem to have deleted) and in the YAML sidecar files (which you may also have deleted?).

Hmmm my "People" tab shows broken symbol, when I click on the broken icon it indeed shows me people. It's like a broken thumbnail cache or something.
![image](https://github.com/user-attachments/assets/f3c57508-60dd-402e-aa39-c9febd86d92c)

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
@lastzero it seems like anything I do breaks it and makes it worse. I found this link https://github.com/photoprism/photoprism/issues/1594 which said run purge, convert and thumbs, so I did that but now my videos folder has reduced from over 200 video files to only 14 videos, yet the extra videos are actually in the videos section but now they are missing thumbnails. It was converting .mov to .mov.jpg? And then it lost the thumbnails. Why would it convert a .mov to a .mov.jpg?

It also did not fix the people having no thumbnails issue.

It seems that the "convert" option converted the videos into pictures, now when I view the videos folder it says "279 Pictures found" none of them have thumbnails, only the 12 videos that it actually detects as videos. Not having a good run with this software I'm afraid.

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
So I started completely from scratch and now it is putting totally wrong thumbnails on some videos. For instance a video of a cat jumping around inside has a thumbnail of a picture from a bushwalk lol. this is from a totally brand new fresh install, deleted all data, moved the files out of original and reimported them by moving them to the import folder and clicking index.
