### ISSUE TITLE
cache storage is substantially high

### ISSUE THREAD

**Issue by rickysarraf** [photoprism/photoprism#1263]
I have only been a PhotoPrism user for around 7-10 days. So, in the initial days, much time was spent understanding the workflow and mechanics of PhotoPrism.

Now that I've kinda settled down on the setup, I was surprised by the storage consumption.

PhotoPrism itself uses:
```
rrs@lenovo:~/photoprism/.photo-prism-storage$ for x in *; do du -sh $x; done
3.2M    albums
25G     cache
16K     config
4.0K    serial
937M    sidecar
```

Whereas, my total Photo/Video folder itself is around `37 GiB`.

While setting up PhotoPrism, I did refine a few of my setup steps.
* Re-encoded many of the HEVC video files because no browser would want to decode them. And transcoding is expensive and slow
* Put some automated steps in place to reorganize backed up pictures from my mobile devices into certain locations.

Now, as I understand, PhotoPrism is smart enough to detect duplicates and stack them.

What I'm still wondering is is why is the `cache` that huge. Does PhotoPrism not do cache expiry/rotation ?

**Comment by lastzero** [comment]
The cache folder holds your thumbnails. When most of your originals are JPEGs already, the downscaled versions are not much smaller combined. You may reduce quality or render them on-demand if you have a powerful CPU and enough memory:

https://docs.photoprism.org/user-guide/settings/advanced/#images
