### ISSUE TITLE
TensorFlow: Panic when indexing new files

### ISSUE THREAD

**Issue by hrv231** [photoprism/photoprism#1270]
Setting up the docker for the first time to try Photoprism out as a replacement of google photos.
I set it up with a separate mariadb database, it seems that everything is fine because I'm able to login to the docker, and start the index, but as soon as a few seconds past, I get the error in the picture below.
![image](https://user-images.githubusercontent.com/41212308/117244200-795e2700-aded-11eb-9e3d-c808198f8fb4.png)

**Comment by lastzero** [comment]
So you're using our latest Docker image? Anything special about your configuration or hardware? From what I see, this happens in TensorFlow which is unusual.

**Comment by lastzero** [comment]
If this only happens with a particular pictures, please help us debugging this by sending a sample to hello@photoprism.app

**Comment by hrv231** [comment]
Hello,

I find out the problem, I'm running the docker over a linux system (unraid to be specific), my CPU is an AMD 3950X, it is a powerful CPU.
So far I have my dockers and VMs using all the CPU threads, no CPU pinning.

I noticed that when I start running the photoprism docker, the docker uses all the CPU power, and at exactly the point where the docker breaks and stops indexing, is the time when the docker uses all the threads from the CPU, putting everything at 100% cpu utilization.

I decided to configure CPU pinning for your docker, and now the docker is running perfectly, it is still running because I have to index about 500GB of photos and videos.

Below are screenshots showing the cpu pinning I gave to the docker and the docker utilization:
![image](https://user-images.githubusercontent.com/41212308/117247440-153e6180-adf3-11eb-8b0e-2a084565c05c.png)

And this one is the docker working now and its utilization:
![image](https://user-images.githubusercontent.com/41212308/117247516-3bfc9800-adf3-11eb-8196-0f8e1b5d4078.png)

Please let me know what else do you need from me to help you debug this, so that others don't encounter the same problem.

Thank you for your time and for share with us photoprism.

**Comment by lastzero** [comment]
High CPU utilization while indexing is intentional. You may reduce the number of workers as described in our docs. This will reduce overall system load.

**Comment by hrv231** [comment]
Hello,

It is fine with me that the high cpu is intentional, but it is wrong that the system will break when using all the threads of the CPU, it shouldn't happen.
My point is, if there is another person with 2 CPUs, let say Xeon with 32 threads each, I'm sure that photoprism will break with the same problem.

I don't mind running the docker with all the cpu threads, but I wanted to report this issue to all to see if you can fix the bug.

Thanks.

**Comment by lastzero** [comment]
We don't want to break your server and kept that in mind:

https://github.com/photoprism/photoprism/blob/develop/internal/config/config.go#L349

Now it's possible our CPU library can't detect HT in your specific CPU or the amount of RAM available isn't enough for the number of cores / workers, so that TensorFlow runs out of memory.

**Comment by lastzero** [comment]
I've added panic handlers to our classification library so that indexing shouldn't stop anymore when this happens, unless the process was killed because of a memory usage spike. Make sure to have enough memory and/or swap.

**Comment by lastzero** [comment]
This change will be available for testing in our [Development Preview](https://docs.photoprism.org/getting-started/updates/) soon:

https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
Release Notes: https://docs.photoprism.org/release-notes/

**Comment by lastzero** [comment]
@hrv231 Is this working for you?

**Comment by hrv231** [comment]
Very good work, the server didn't crashed.
![image](https://user-images.githubusercontent.com/41212308/117477962-74939300-af13-11eb-92c4-f76320d0301d.png)


But for some reason the index stopped after a while, maybe this time is because of something else?
![image](https://user-images.githubusercontent.com/41212308/117477851-575ec480-af13-11eb-81cc-86f09d435091.png)

I tested running this command:
`photoprism index --all`

FYI, I have plenty of ram, and the ram didn't get full.

**Comment by lastzero** [comment]
Interesting, maybe another memory issue... No other users reported similar issues. Might be certain files that are causing this, maybe with corrupt / invalid data?

**Comment by hrv231** [comment]
I don't think so, I was able to run the entire folder when I was using only 4 cores.

I feel there is something else happening here, no corrupt or invalid data on my files.
I use a different system to check all the files against their md5 checksum, so I don't think it is corrupt data.

Only think I could think of is that I'm using mysql (mariadb), the docker connects to the other docker via network.
But again..., it worked perfectly when I restrict the CPU cores..

**Comment by lastzero** [comment]
Let us know when you figure something out we can work with. Thank you for testing! 👑
