### ISSUE TITLE
UX: Build photo viewer with video support

### ISSUE THREAD

**Issue by gittyup444** [photoprism/photoprism#1278]
I really like the photoprism project but being unable to scroll in either direction if you start viewing your library or album by tapping or clicking on a video is a little frustrating in my opinion. My comparison/benchmark here is Google Photos where browsing videos and photos works in the same way, regardless of how you start viewing your content. 

Perhaps the experience could be improved by always forcing videos to initially open as a thumbnail/still and then playing manually once it's open - i.e. making this the default behaviour whether or not you play it directly or arrive there via scrolling? For example, this behaviour already seems to be the case if you start by viewing a photo and scroll left or right to arrive at a video - in this situation the video is initially just a still and you then click play to start it. 

From what I can tell this impacts the browser experience (chrome, linux) and android (chrome) in the same way. 

version: 210505-d3e53a89-Linux-x86_64

**Comment by graciousgrey** [comment]
@gittyup444 I am not sure if I understand your issue. 
You open Photoprism, then you click on a video and then when you close the video you are not able to scroll anymore?

**Comment by lastzero** [comment]
@graciousgrey Guess this is about a combined photo / video lightbox so that you can always click "next" to see the next search result / album entry.

**Comment by graciousgrey** [comment]
@gittyup444 Thank you, now I got it :). 

The lightbox we use is from Photoswipe (and build for photos, not videos) so we are limited in what we can change there.
We plan to develop our own lightbox that works well with photos and videos. 
But a lot of other tasks need to be done first and we are still far away from our funding goal https://github.com/sponsors/photoprism ;)

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: https://github.com/photoprism/photoprism/issues/1307
