### ISSUE TITLE
Photoprism container keeps stopping

### ISSUE THREAD

**Issue by pluja** [photoprism/photoprism#1285]
The photoprism container keeps stopping, I don't really know what is happening and why. I just followed the docs step-by-step, all went perfectly and smooth.

```
photoprism    | umask 0
photoprism    | running as uid 997
photoprism    | photoprism start
photoprism    | time="2021-05-11T11:26:44Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"
watchtower    | time="2021-05-11T10:21:05Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-05-11 12:21:05 +0000 UTC\nNote that the first check will be performed in 1 hour, 59 minutes, 59 seconds"
watchtower    | time="2021-05-11T10:59:50Z" level=info msg="Waiting for running update to be finished..."
watchtower    | time="2021-05-11T11:00:28Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-05-11 13:00:28 +0000 UTC\nNote that the first check will be performed in 1 hour, 59 minutes, 59 seconds"
watchtower    | time="2021-05-11T11:07:45Z" level=info msg="Waiting for running update to be finished..."
watchtower    | time="2021-05-11T11:13:38Z" level=info msg="Watchtower 1.3.0\nUsing no notifications\nChecking all containers (except explicitly disabled with label)\nScheduling first run: 2021-05-11 13:13:38 +0000 UTC\nNote that the first check will be performed in 1 hour, 59 minutes, 59 seconds"
photoprism exited with code 0
```

These are the docker-compose logs, it says `photoprism exited with code 0`... UUID 997 corresponds to user `photoprism`:
`uid=997(photoprism) gid=996(photoprism) groups=996(photoprism),998(docker)`

**Comment by lastzero** [comment]
Maybe restarting MariaDB fixes this issue...

**Comment by pluja** [comment]
I configured the password for the database on the `docker-compose.yml` file, where should it be wrong?

**Comment by dalwar23** [comment]
This might help. https://github.com/MariaDB/mariadb-docker/issues/264

**Comment by pluja** [comment]
After checking everything out several times, it seems that I was using (by error) the same password for the MySQL user and the MySQL root user and this was causing a strange conflict.

Thank you for the help!

**Comment by ant0nwax** [comment]
@pluja how did you fix this exactly, do you remember?

I have the same issue
i changed the last charachter on the sql root password in the docker-compose.yml and then docker-compose down and up -d but still crashing... 

i have 80000 files around 90G and indexing is at around 60000+

**Comment by ant0nwax** [comment]
I guess i found the issue for crashing:

i recently migrated the VM and the memory ballooning device had minimum 2 GB and maximum 8 GB.
somehow it got stuck at 2 GB
after setting minimum and maximum to 8 GB i also added the swap with 2 GB

swapon -a #check swap files, there was nothing
free -h #show how much memory is used
sudo fallocate -l 2G /swapfile #create 2Gigs of swap as a file
sudo chmod 600 /swapfile #only root access
sudo mkswap /swapfile #allocate swap
sudo swapon /swapfile #enable swap

#add to fstab on startup
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

#edit swapiness, lower values means use swap less. at 60 swap is used with ram is 40% used.
sudo nano /etc/sysctl.conf

#at end of file add
vm.swappiness=10
vm.vfs_cache_pressure=50

reboot

root@MACHINE:/# free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       1.6Gi       3.3Gi       1.0Mi       2.8Gi       5.8Gi
Swap:         2.0Gi          0B       2.0Gi
