### ISSUE TITLE
How Does Auto Import Work?

### ISSUE THREAD

**Issue by royaltongue** [photoprism/photoprism#1288]
I have Resilio-Sync running to upload photos from my phone to `/mnt/storage/photos/photos`.
I also have `/mnt/storage/photos/photos:/photoprism/import` in my `docker-compose.yml` for PhotoPrism.

From what I had read, it seemed that auto-import ran every 15 minutes by default, but it doesn't seem like it's doing anything on my end.

Is there something I'm missing?

**Comment by graciousgrey** [comment]
Auto Sync is only triggered when files have been added to the import or original folders using WebDav. Is it possible that Resilio Sync does not use WebDav?

**Comment by royaltongue** [comment]
Ah yep, didn't know it only triggered via WebDAV. Switched over to a WebDAV client and all is good now, thanks!

**Comment by graciousgrey** [comment]
Now you can find example docker-compose.yml + job.ini files here: https://dl.photoprism.org/docker/scheduler/.
Within the jobs.ini you can configure when and how often commands (e.g. index or import) should run. This is independent from WebDav :)
