### ISSUE TITLE
webdav: read dir timeout reached

### ISSUE THREAD

**Issue by that1guy** [photoprism/photoprism#1291]
My Nextcloud has a long, deeply nested, folder hierarchy due to the "Auto-Upload Camera Roll" feature.  I believe this causes the Photoprism to timeout when hooking up the webdav sync.  This causes many of my photos not to import into PhotoPrism.

![image](https://user-images.githubusercontent.com/1218940/118378245-45ba9400-b587-11eb-83c4-dc107591cda7.png)

I went digging around in my docker container to see if I could hack a quick solution in place, but couldn't find the source file I needed to modify.

Thanks for help!

https://github.com/photoprism/photoprism/blob/ab40583c9a692730c57d4e9f5f1cd581daeed4c1/internal/remote/webdav/webdav.go#L59

**Comment by lastzero** [comment]
Think I already replied in the chat?

WebDAV sync isn't made for super huge libraries as it will also duplicate the data, which requires twice the storage.

You may alternatively mount the Nextcloud storage path into PhotoPrism via Docker or mount the WebDAV share via `davfs2`:

https://wiki.archlinux.org/title/Davfs2

Note that PhotoPrism doesn't change or rename originals on its own. Delete is optional and must be triggered by the user pressing a button. So there is little risk conflicting with Nextcloud. In addition you may enable read-only mode to disable uploads & the delete button completely.

**Comment by that1guy** [comment]
Thanks for this suggestion and workaround.

What if I have two Nextcloud users and each user has a photo directory?  Doesn't seem that I can have PhotoPrism import/index two folders, can I?

**Comment by lastzero** [comment]
Sure, just mount them in separate sub folders as shown in our docs / example config.

**Comment by that1guy** [comment]
Nextcloud photo directories for each users are not within a single subfolder.  Each Nextcloud user has it's own heiarchy.  I don't want to import the parent Nextcloud Directory because that will import photos related to the Nextcloud application and a bunch of other random images.

Perhaps I can create a single Photoprism_photos parent directory, then symlink both of my Nextcloud user's photo directory into that parent folder?

The more I'm thinking about this, the more I think it may just be better to allow the user to set the webdav timeout limit.

**Comment by lastzero** [comment]
You can mount multiple folders with Docker as sub folders of originals.

**Comment by that1guy** [comment]
Ah, gotcha.  Setup multiple volumes w/ Docker container.  Problem solved.
