### ISSUE TITLE
feature req: index new images in parallel

### ISSUE THREAD

**Issue by nergdron** [photoprism/photoprism#1293]
I'd love it if photoprism could index / generate thumbnails for / otherwise process new images in parallel, either on adding to the photo dir, or when triggering a full scan.

_background:_
I'm testing using cloud storage mounts as a photo backend for photoprism. it works well enough, but those options are high-latency compared to local disk, and I find photoprism just spends a lot of time idle waiting for connection overhead in the file ops. It'd be great if we could set an amount of parallelism (default to # of cpus?) to process new images, so that speeds would be a lot more comparable to local disk, and cloud storage would be a more viable option.

**Comment by ayvazjet** [comment]
14 May 2021 Cum, saat 20:04 tarihinde Tessa Nordgren <
***@***.***> şunu yazdı:

**Comment by lastzero** [comment]
You may set the number of indexing workers via `PHOTOPRISM_WORKERS`. Here's a list of all config options:

https://docs.photoprism.org/getting-started/config-options/

**Comment by nergdron** [comment]
well then! I swear I looked through those, but I must've missed it! thanks!
