### ISSUE TITLE
Photos can be accessed by anyone if they have the image address

### ISSUE THREAD

**Issue by pluja** [photoprism/photoprism#1297]
I couldn't find any related issue by searching for it, but I think this should not be like this. To replicate this:

1. Go to any photo/video in the gallery, right click and select "Copy image address":
![https://i.imgur.com/MbTpeZ3.png](https://i.imgur.com/MbTpeZ3.png)

2. Once you have the image address, go to a private window (or another browser where you are not signed in), and navigate to the recently copied link:
![https://i.imgur.com/fDvoCnI.png](https://i.imgur.com/fDvoCnI.png)

3. See the photo even without having signed in:
![https://i.imgur.com/o4hdl9X.png](https://i.imgur.com/o4hdl9X.png)

I know that this is very difficult for an attacker to get a link to a photo and be able to see your gallery by generating links as the hash is long enough, but it still is a vulnerability. Also, if a link gets somehow leaked I won't be able to revoke access to it (maybe I would need to delete and reupload the image idk).

**Comment by localjo** [comment]
One way that this could be an issue is if you share an album, and someone copies the image addresses from that album, even if you revoke access to the album, the image addresses that they've copied still work.

**Comment by pluja** [comment]
I don't really know how this should be addressed. I feel like making a much larger URL hash should guarantee a better security. I know that this is designed to share between friends and family but you never know how your shared links will be used (or shared without knowing), even someone may naivelly share it on a social network (because of lack of knowledge) and get on the hands of some malicious actor. Or as @localjo said in his scenario.

Maybe an advanced option to rotate URLs (so it is a manual action and not an automated action) for when you shared a considerable ammount of albums/photos and you no longer feel secure...

I just checked and this is an example link for a Google Photos image (i changed some characters for security reasons so this link should be broken):

`https://lh3.googleusercontent.com/IXXX_vp7dHF3mg_zM1hZgUg8S7Zh2-zDXXXghbxXXX51GmXg4r8qSv4x5Bu5Q2bK1bKD9Lud7e4V1rkBliSzFOjX3l5BDpxXS7V1mbpF0vrQSbO2OLu70W6W41iaTkctmSO6r5pvWvriCnuIW0XXXXXaYiKQ6slHUpvonVauE8SXXXxemhXUduj1Jn1n0YRuw12OsAws2leeufv15eGYJql7zHMqV1V501jS6F8ZQZC4I3YrB2vKoW3qI4XXXVZpT3kM9CTXXXXaWRiQicXXXXdAoyDJIXXX5bQuLmOci4yfoctubH4oQ5_pdc4e3n2xquRH70NaAnWdjcIpnhOaSXXXXbnye7o6oZRjlWhwHgb-Ya37XXXeBnY9oau-YgloBagwVppkDIbvaw2vBuL9XsbWiiye4nQ2blXT02FlUS-b8rmow2HHbe5hkEncsG5vI1TNF11Egi9o15_amI3YZi8LFnMa9aHUiQvJBTT_XXXXn2eaZXXaXXK-3IhvFE8HkH-XXXX1nNzGZ4iqB4WT7XXXXmPTHJWXnlMVpiF3xdyVslqLp4O8tjk851VLiC_Q7PN916vPoCcBfgA45ZmhXLiUPhLzn1fIXXXXXfXXXPFGlcc6fXXXkBrCAh6OtYZkk-sNQgNEQzlrMmucmGAGzhZJ8jSg2CjLacNxNHhCTXXXXXXqbzeRst6kPAblgJiKhMCxFSIXXFMwXXm6ciXXg=e987-XXXX-uo`

Also, I don't know if they ever rotate URLs. I will check this same URL more often for a certain period of time and check if it has changed...

**Comment by localjo** [comment]
> making a much larger URL hash should guarantee a better security

The entropy of the existing links is quite high. I don't think that's an issue.

Regarding the privacy of photos with known/leaked URLs, a few ideas that come to mind:

1) Hot link detection: if an image file is requested and the request doesn't come from a page with the same domain, then the server should return a 403 and not return the image. All that is required for this is checking the request headers before serving the image. This could be optional, if there are some users who prefer to allow hot-linking of images.

2) A privacy toggle: images could have a binary public/private toggle. Hot linking could be enabled just for images that are marked as "public" and not for images that are marked as "private".

3) URL rotation: rather than having random/scheduled URL rotation, which might be undesirable, URLs could change when all of an album's share links have been removed, or when share links change, or there could be a button to change an image or album of images' URLs, etc.

**Comment by StephenBrown2** [comment]
I think 1. and 2. are reasonable options. Not sure if 3 is worth the effort, but I guess it could work.

**Comment by lastzero** [comment]
You can set URL tokens in the config, should be listed in our docs. Obviously this only makes sense if you feel something has leaked as it Invalides the browser cache. URL length is more than enough. If you don't set a token, a random token is used. The download tokens for originals including metadata changes after each restart, eg when updating.

**Comment by lastzero** [comment]
Rest assured Flickr and many other high profile sites are less secure. It's just that you trust big companies more and you don't have access to their souce, so you can't look it up.

**Comment by localjo** [comment]
> You can set URL tokens in the config

Are you referring to `PHOTOPRISM_DOWNLOAD_TOKEN`?

> The download tokens for originals including metadata changes after each restart

Can you clarify what you mean? I haven't set a `PHOTOPRISM_DOWNLOAD_TOKEN`, and after a restart, the image URLs haven't changed. I can still access images with the same URL I could before restarting.

**Comment by lastzero** [comment]
The value for the previews (thumbnails) is `PHOTOPRISM_PREVIEW_TOKEN`. As mentioned, a random value is used for `PHOTOPRISM_PREVIEW_TOKEN` and `PHOTOPRISM_DOWNLOAD_TOKEN` by default - so you don't have to set anything unless you forcefully want to change the URL because you think something might have leaked or because you have special security requirements.

From what I see, Google Photos also uses image URLs that can be used by anyone with the link. This is not a security issue unless you share the URLs with people who should not have access or your browser gets hacked, so that an attacker can see the URLs e.g. in the cache. If you don't use HTTPS, an attacker can see all traffic incl images anyways.

**Comment by lastzero** [comment]
If you share images, you should assume they are getting downloaded. At least by browsers into their cache. You've already lost control at this point.

**Comment by lastzero** [comment]
If you're running a public instance (like our demo) the values might be 

```
"downloadToken":"1c5aldm0","previewToken":"public"
```

The download token is random (and may change) while the preview token stays the same and is "public" in this special case. Right clicking an image will not download the original, you have to use our download button for this. Otherwise you're just saving the preview / thumbnail image. This is a downscaled version without metadata to protect your privacy.

**Comment by lastzero** [comment]
see https://github.com/photoprism/photoprism/issues/817

When I have some time, I'll add this to our FAQ and also add a page to our developer guide, explaining the implementation details and tradeoffs.

**Comment by lastzero** [comment]
> Hot link detection: if an image file is requested and the request doesn't come from a page with the same domain, then the server should return a 403 and not return the image.

This might break some things and we already have enough work providing support.

Note that our users run all kinds of custom configs and there's also native apps using these URLs, so not all requests come from a Web app on the same domain.

**Comment by localjo** [comment]
@lastzero Thanks for your help in figuring out how this works.

For those who want to invalidate old/leaked photo URLs, it seems that the solution is to set the following variables in your [config options](https://docs.photoprism.org/getting-started/config-options/) and manually rotate the values when necessary:

```
PHOTOPRISM_DOWNLOAD_TOKEN: "r4nd0mt0k3n"
PHOTOPRISM_PREVIEW_TOKEN: "pr3v13wt0k3n"
```

Also, if these values are not set, they will be randomly generated and the download token, *but not the preview token*, will be regenerated every time you restart PhotoPrism.

It seems that this solution is the only one that will be prioritized at the moment, which is fine for my use case. However, I'm adding some additional comments in case that changes in the future:

> Google Photos also uses image URLs that can be used by anyone with the link.

It seems that Google's URLs do have some sort of privacy protection and/or expiration...

![Screen Shot 2021-05-19 at 1 35 35 PM](https://user-images.githubusercontent.com/516388/118806271-26817680-b8a7-11eb-973c-f8c1a2fd089f.png)

> Note that our users run all kinds of custom configs and there's also native apps using these URLs, so not all requests come from a Web app on the same domain.

This is why it would make sense for it to be a toggleable option and/or adding an editable "allow list" of domains that are approved to access PhotoPrism resources, following [the CORS model](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by localjo** [comment]
> The origin domain can be faked by using `curl` for example, this is a weak protection.

It's weak protection, but it adds another layer of protection, which always helps, and it prevents people from hot linking photos on my server from their own web pages, which could lead to unexpected/unwanted traffic hitting my servers.

**Comment by alexislefebvre** [comment]
> It's weak protection, but it adds another layer of protection, which always helps, and it prevents people from hot linking photos on my server from their own web pages, which could lead to unexpected/unwanted traffic hitting my servers.

Fair enough. Can it be configured on the proxy level?

**Comment by lastzero** [comment]
> It seems that Google's URLs do have some sort of privacy protection and/or expiration...

Yes, rotating URLs is possible, but it's really a full-time job to fine tune this and make sure all current use cases are supported and nothing breaks. Keep in mind Google doesn't operate with our budget, they can have 10 people optimizing this and writing scientific papers about it. Then at the end people still get their Google accounts hacked and credit card data stolen. I know some.

The Google Photos image URL I posted above is still valid, so at least they don't seem to change them very often. Also they don't check the host / domain header as you suggested to do, I can open it from everywhere.

This very old Flickr URL is also still the same and even much shorter, so it's way easier to guess than our URLs (although that's also highly unlikely):

https://live.staticflickr.com/1932/45424204711_389d0e639e_b.jpg

> it prevents people from hot linking photos on my server from their own web pages, which could lead to unexpected/unwanted traffic hitting my servers.

They can still download all shared pictures, publish them on Reddit, and share (other) URLs pointing to your server. Users might assume a safety that just isn't there.

In a future release, we may implement a way to share sensitive content with strangers, but we're not there yet.
