### ISSUE TITLE
Is there a full list of which metadata `keywords` will import as `labels`?

### ISSUE THREAD

**Issue by coolmule0** [photoprism/photoprism#1298]
I am interested in adding appropriate  keywords to images using other software, then importing them into Photoprism so they show up as labels.

I notice that certain keywords like `Building` `Flower` `Cat` come up. Is there a full reference to these? 
Does renaming and custom-added labels affect this list?

**Comment by graciousgrey** [comment]
IYou can find more information here https://github.com/photoprism/photoprism/discussions/998

**Comment by graciousgrey** [comment]
> You can set keywords to your files using exiftool:
exiftool -keywords+=banana 123.jpg
If you like your keywords to be added as labels you need to do the following:
For each label add it once manually to a photo
Then trigger a complete rescan --> this will add all photos with the keyword matching the label to the label

**Comment by coolmule0** [comment]
Thank you. In addition to your answer, [this file in the repo](https://github.com/photoprism/photoprism/blob/develop/internal/classify/rules.go) looks to have the full amount of automatically generated labels when using tensorflow

**Comment by graciousgrey** [comment]
@coolmule0 yes, this file lists all labels that tensorflow recognizes. 

`"accordion": {		Label:      "instrument",		Threshold:  1.000000,		Priority:   -2,		Categories: []string{},	},`

E.g. if tensorflow recognizes `accordion` the label in photoprism will be `instrument`
