### ISSUE TITLE
Docker: Permission issues in new Ubuntu 21.04 base image

### ISSUE THREAD

**Issue by royaltongue** [photoprism/photoprism#1301]
Photoprism container was working perfectly fine this afternoon, and I noticed a few minutes ago that a WebDAV upload failed.

Checked the container logs and saw error:
`/entrypoint.sh: line 37: photoprism: command not found`

I've tried pulling the latest image and recreating through Portainer, but no luck

**Comment by lastzero** [comment]
You think it's a problem with our update? Does it update automatically? Can you try an older version? Intel or ARM CPU?

**Comment by royaltongue** [comment]
I don't have Watchtower running on this stack, so I'm not sure what caused it actually

What image tag should I use to get an older version?

Intel CPU

**Comment by lastzero** [comment]
Here's a list of all available images (tagged by date, which is the version):

https://hub.docker.com/repository/docker/photoprism/photoprism

Previous version is `photoprism/photoprism:20210505`

**Comment by royaltongue** [comment]
`20210505` spins up without any errors

**Comment by lastzero** [comment]
Then it might be the new Ubuntu version which has other permission defaults :/ We're going to look into this! In the meantime, you might have to change permissions inside the Docker image manually in a terminal. Thee docs / docker-compose.yml file for how to open one.

**Comment by satcom886** [comment]
I just ran into this too. Also x86 Linux.

**Comment by lastzero** [comment]
Seems `/photoprism` wasn't world executable after upgrading Ubuntu. What user are you running the container as?

**Comment by lastzero** [comment]
Started a preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by satcom886** [comment]
> Seems `/photoprism` wasn't world executable after upgrading Ubuntu. What user are you running the container as?

I created a user for running multimedia services (Transmission, Jellyfin, Photoprism, etc.) to avoid media permission issues. `user: 1002:1002`

**Comment by lastzero** [comment]
So, is it working now?

**Comment by royaltongue** [comment]
Yep, preview image is good

**Comment by satcom886** [comment]
> So, is it working now?

Just had a chance to test, yes it works fine with the preview image.

**Comment by lastzero** [comment]
Thanks for testing! :heart:
