### ISSUE TITLE
No import folder created during Portainer installation on Synology

### ISSUE THREAD

**Issue by bradydjohnson** [photoprism/photoprism#1311]
I cannot find the import folder which is referenced in the rest of the [User Guide documentation](https://docs.photoprism.org/user-guide/library/import/). 

I installed Photoprism using Portainer based on Photoprism's default docker-compose yml file but downgraded to compose version 2 per [Setup Using Synology NAS and Portainer](https://docs.photoprism.org/getting-started/portainer/synology/)
https://docs.photoprism.org/getting-started/portainer/synology/. I noticed that there's no reference to the import folder in the stack code (see below).

```
 volumes:
      - /volume1/docker/photoprism/originals:/photoprism/originals
      - /volume1/docker/photoprism/storage:/photoprism/storage  
```

How should I fix this?

**Comment by graciousgrey** [comment]
You need to configure the import folder the same way you do with originals. There is an example in our docker-compose example (https://dl.photoprism.org/docker/docker-compose.yml)

**Comment by lastzero** [comment]
I'll close this as it's a question and not something we can implement or fix in our code.
