### ISSUE TITLE
JVC .mov .moi files

### ISSUE THREAD

**Issue by ameralzarouni** [photoprism/photoprism#1318]
Hi, 
PhotoPrism does not detect video files (.MOV) and their information (same file name .MOI) taken by JVC cameras.

**Comment by lastzero** [comment]
Can you send us some samples to hello@photoprism.app for testing this please? What messages do you see in the logs?

**Comment by ameralzarouni** [comment]
I'll send some samples now.
Uhhh, is there a feature to filter the log? I wasn't checking it when it scanned that directory.

**Comment by lastzero** [comment]
Then scan it again or filter the logs from Docker via grep.

**Comment by lastzero** [comment]
Or check the error logs in Library if it was an error or warning.

**Comment by ameralzarouni** [comment]
Alright

**Comment by ameralzarouni** [comment]
Is there a command to scan a certain directory?

**Comment by ameralzarouni** [comment]
Sorry for all the trouble, I'm new to this and not very experienced with docker.

**Comment by ameralzarouni** [comment]
I ran this command from within the docker container `photoprism index hdd2/PRG001` (PRG001 is the directory containing the .MOVs) and it detect the files now, but it is detecting them as pictures not videos.

**Comment by lastzero** [comment]
Short movies up to 3s are shown as live photos. Is that what you mean?

**Comment by lastzero** [comment]
You can also select a directory in the dropdown on Library > Index in the UI

**Comment by ameralzarouni** [comment]
The problem was that I was accessing it from Library > Originals instead of folders. My bad.
But now, there is another problem when I try to play one of the videos (transcoding):
`2021-05-23 01:15:08 WARN ffmpeg: ffmpeg version 4.3.2-0+deb11u1ubuntu1 Copyright (c) 2000-2021 the FFmpeg developers built with gcc 10 (Ubuntu 10.2.1-20ubuntu1) configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared WARNING: library configuration mismatch avcodec configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc libavutil 56. 51.100 / 56. 51.100 libavcodec 58. 91.100 / 58. 91.100 libavformat 58. 45.100 / 58. 45.100 libavdevice 58. 10.100 / 58. 10.100 libavfilter 7. 85.100 / 7. 85.100 libavresample 4. 0. 0 / 4. 0. 0 libswscale 5. 7.100 / 5. 7.100 libswresample 3. 7.100 / 3. 7.100 libpostproc 55. 7.100 / 55. 7.100 Input #0, mpeg, from '/photoprism/originals/hdd2/PRG001/PRG001_1/MOV066.MPG': Duration: 00:00:36.96, start: 0.251978, bitrate: 9161 kb/s Stream #0:0[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 16:15 DAR 4:3], 8500 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc Side data: cpb: bitrate max/min/avg: 8500000/0/0 buffer size: 1835008 vbv_delay: N/A Stream #0:1[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 384 kb/s Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (/photoprism/storage/sidecar/hdd2/PRG001/PRG001_1/MOV066.MPG.avc) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream. Stream mapping: Stream #0:0 -> #0:0 (mpeg2video (native) -> h264 (h264_v4l2m2m)) Stream #0:1 -> #0:1 (ac3 (native) -> aac (native)) Press [q] to stop, [?] for help [h264_v4l2m2m @ 0x560b84559240] Could not find a valid device [h264_v4l2m2m @ 0x560b84559240] can't configure encoder Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height Conversion failed!`

**Comment by lastzero** [comment]
Seems you've enabled the hardware encoder "h264_v4l2m2m" for the Raspberry Pi without mounting the device into the Docker container as also shown in our ARM64 example:

```
    # For hardware AVC transcoding using the h264_v4l2m2m encoder:
    # devices:
    #  - "/dev/video11:/dev/video11"
```

**Comment by lastzero** [comment]
I'll close this as it also seems to be a question, not something we need to implement or fix in our code.
