### ISSUE TITLE
Import: Never remove ignored folders such as for Syncthing

### ISSUE THREAD

**Issue by AudunVN** [photoprism/photoprism#1319]
I'm like #280 using Syncthing to put files in my import directory from various devices. Syncthing creates and requires an empty folder named `.stfolder` to mark its folders, which is currently deleted by Photoprism (which subsequently breaks Syncthing) after an import even if `.stfolder` is specified in the `.ppignore` file in the import folder.

https://github.com/photoprism/photoprism/blob/ed3287d8ef5e0238e496bb15c2631399205d01dd/internal/api/import.go#L82-L88

Putting a file such as `ppkeep` in `.stfolder` does prevent deletion after import without affecting Syncthing, so it's not a large issue for my use case at least.

I'm not sure if this is a bug or feature request since the documentation I've found doesn't specify that Photoprism won't delete folders specified in `.ppignore`, but I at least initially expected `.ppignore` would protect the folder from being deleted from previous `.ignore`-type files I've used.

**Comment by lastzero** [comment]
When you chose not to move files from import but to copy them only - this way, nothing gets deleted. If you selected "move" in Library > Import, then a .ppignore file still won't preserve empty folders in import from getting deleted.

**Comment by lastzero** [comment]
Maybe we can add a list of special folders like for Syncthing that never get touched. Would that help?

**Comment by AudunVN** [comment]
That should help a lot!

I specifically use move instead of copy since I want Syncthing to automatically remove the imported files from my local Photoprism import folders once the import is done. For example, I have Syncthing set up to sync the DCIM folder on my phone with a folder in Photoprism's import directory on my server, so by using move on import I can free up space on my phone.

**Comment by lastzero** [comment]
How does Syncthing know the import is done?

**Comment by AudunVN** [comment]
Ah, sorry, I worded that a bit unclearly; Syncthing doesn't wait for the import to finish, so it doesn't need to know when the import is done. All it does is keep folders on different devices synchronized, so if Photoprism removes a file from a folder watched by Syncthing during an import these will also be removed from any synchronized devices.

My current setup is more or less

- `/photoprism/originals` synchronized with a folder on my backup drives
- Phone DCIM folder synchronized with `/photoprism/import/phone`
- Laptop import folder synchronized with `/photoprism/import/laptop`
- Desktop import folder synchronized with `/photoprism/import/desktop`

where I usually regularly copy the DCIM folders from my cameras to the laptop/desktop import folders. Photoprism is running on a hosted remote VPS.

This lets me back up and import images independently of the SD card or camera the images came from as soon as they've been copied to my laptop or desktop import folder. Works quite well when offline or on a slow network connection where uploading directly from the SD card or camera to Photoprism through WebDAV or similar would have issues.

**Comment by lastzero** [comment]
Started a preview build for testing my changes: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by AudunVN** [comment]
Nice, thank you very much! 😃 The changes in 65c3967 seem like they should good solution for this indeed, will see if I can test it soon.

**Comment by lastzero** [comment]
We decided to remove such folders as some operating systems always create hidden files and folders for keeping extended attributes, so practically empty directories would never get deleted. Some less experienced users might now wonder why their empty folders are still around - that's the tradeoff.

**Comment by lastzero** [comment]
Updated Docker images are available now.

**Comment by lastzero** [comment]
We've released it already as it works for us, just tested it again. Let us know if you still have issues.

**Comment by AudunVN** [comment]
Thank you very much again - will do!

**Comment by AudunVN** [comment]
> Ah, sorry, I worded that a bit unclearly; Syncthing doesn't wait for the import to finish, so it doesn't need to know when the import is done. All it does is keep folders on different devices synchronized, so if Photoprism removes a file from a folder watched by Syncthing during an import these will also be removed from any synchronized devices.
> 
> My current setup is more or less
> 
> * `/photoprism/originals` synchronized with a folder on my backup drives
> * Phone DCIM folder synchronized with `/photoprism/import/phone`
> * Laptop import folder synchronized with `/photoprism/import/laptop`
> * Desktop import folder synchronized with `/photoprism/import/desktop`
> 
> where I usually regularly copy the DCIM folders from my cameras to the laptop/desktop import folders. Photoprism is running on a hosted remote VPS.
> 
> This lets me back up and import images independently of the SD card or camera the images came from as soon as they've been copied to my laptop or desktop import folder. Works quite well when offline or on a slow network connection where uploading directly from the SD card or camera to Photoprism through WebDAV or similar would have issues.

Just wanted to leave a quick note to verify that updating Photoprism to build `210523-b1856b9d` and doing an import works perfectly with this setup! 😄

**Comment by HaroldDLeon** [comment]
> Maybe we can add a list of protected folders like for Syncthing and Git that never get touched. Would that help?
> 
> ```
> .stfolder
> .git
> ```

Would it be possible to also include ```.stignore``` on this allow-list?
I'm using a setup pretty similar to the above, but .stignore gets deleted on import.

**Comment by lastzero** [comment]
Are you using our latest version? .folders should all be ignored now

**Comment by HaroldDLeon** [comment]
I am using the latest version. ```.stignore``` is a file (not sure if it'd be treated different than a .folder).

**Comment by lastzero** [comment]
Add it to a ".ppignore" file then

**Comment by HaroldDLeon** [comment]
Following the discussion on #1348
