### ISSUE TITLE
Upgrade vuetify to version 2

### ISSUE THREAD

**Issue by dominikstraessle** [photoprism/photoprism#132]
As you are using [vuetify](https://vuetifyjs.com/en/) as vue component framework, you should consider upgrading from version 1.5 to version 2 because this is the most recent major release of the framework and I think it's easier to migrate at an early state of this project rather than when it's already grown to a mature one. And in addition to that, new components has been added and several ones has been improved, for instance the [calendar component](https://vuetifyjs.com/en/components/calendars) which you already use for the Events page.

There is still long-term support for 1.5 until July 2020. Read more: [Long-term support](https://vuetifyjs.com/en/getting-started/long-term-support).

The upgrade guide is included in the release information. [Release and upgrade guide](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0)

Since 2.0.0, several versions with bugfixes has been released, so look for the latest version.

**Comment by lastzero** [comment]
Good idea! I won't be able to do it before next month. If somebody has time and wants to do it, please raise your hand...

**Comment by lastzero** [comment]
Tried to upgrade it quickly, but seems like a bigger task as components are loaded / included in Vuetify 2 on demand. So `webpack.config.js` needs some tweaking and additional packages / plugins, e.g.:

- sass 
- sass-loader 
- fibers 
- deepmerge 
- vuetify-loader

See https://vuetifyjs.com/en/getting-started/quick-start

**Comment by dominikstraessle** [comment]
A migration guide has just been released: [Releases and migrations](https://vuetifyjs.com/en/getting-started/releases-and-migrations)

**Comment by lastzero** [comment]
@dominikstraessle Thank you! Besides bootstrapping, many components and their layout changed too... I'm on it...

![Screenshot 2019-11-17 at 07 08 46](https://user-images.githubusercontent.com/301686/69003885-d1f3e880-0909-11ea-9d47-65eeffbcdcd5.png)

**Comment by lastzero** [comment]
It's kind of working now, but IMHO Vuetify 1.5 looks much nicer and also feels faster...

![Screenshot 2019-11-17 at 07 57 46](https://user-images.githubusercontent.com/301686/69004229-0cf91a80-0910-11ea-9f73-8ef27bca8b8e.png)

![Screenshot 2019-11-17 at 07 59 05](https://user-images.githubusercontent.com/301686/69004234-27cb8f00-0910-11ea-8166-1033a75c1a15.png)

**Comment by lastzero** [comment]
@dominikstraessle Descoping this since Vuetify 2 is based on Material Design 2, so our app would look different and we don't have time to redo our design and UI at the moment.
