### ISSUE TITLE
photosync

### ISSUE THREAD

**Issue by ameralzarouni** [photoprism/photoprism#1320]
Hi, 
If I use photosync to autosync photos, which directory do they get saved in?
Do they get mixed up with the old originals? Or do they get their own folder?
Thanks

**Comment by acranox** [comment]
You can do it either way.  
https://docs.photoprism.org/user-guide/library/import/

You can either sync them to the import directory via webdav, and then a few minutes later PhotoPrism will import the files and move the files to the originals directory (using a naming convention like `originals/2021/05/20210501_<checksum>.jpeg`.  If you sync them to the originals directory, the naming/directory structure will be determined by the setting you use in photosync, and then you'll need to run a reindex afterwards for them to get added to PhotoPrism.

So you can decide if you want  PhotoPrism to manage the file naming and directory structure of your library, or if you want to manage that yourself.

**Comment by ameralzarouni** [comment]
So if I add them to the import directory, photoprism will mix them in with the originals?

**Comment by lastzero** [comment]
Importing will copy or move (depending on your config) files from the import folder to the originals folder as described in our docs. You may as well upload directly to originals and let PhotoSync do the naming. You can configure a folder structure there when syncing.
