### ISSUE TITLE
Cannot understand counters

### ISSUE THREAD

**Issue by dml33** [photoprism/photoprism#1322]
Hi.
I am a newbie with photoprism. It looks awesome, so I am doing some tests before putting my collections in it.

I imported some photos and videos. In Originals folder there are 489 files as follows:

```
root@photoprism:/var/db/photoprism/storage/originals/2021/05 # ls *jpg | wc -l
     471
root@photoprism:/var/db/photoprism/storage/originals/2021/05 # ls *mp4 | wc -l
      18
```

In the app, I have the following:
![image](https://user-images.githubusercontent.com/25033130/119253264-b75e9780-bbb0-11eb-97a4-810bc666645b.png)
- Search -> 463
- Inside Search, only Stacks have contents -> no number is displayed, but there are 26. All of them of just 2 photos. Then, there should be 13 primary photos + 13 _no-primary_.
- Videos -> 18
- Places -> 3, but in the map there are two big bubbles: 449 and 14 -> 463. The bubbles contain the videos. No file is without location information (latitude, longitude).
![image](https://user-images.githubusercontent.com/25033130/119253373-45d31900-bbb1-11eb-891b-2447c21c2b6d.png)
- Library -> Originals -> 507. But, inside, it says "Folder contains 489 files". There is nothing under Hidden or Errors sections
![image](https://user-images.githubusercontent.com/25033130/119253494-c4c85180-bbb1-11eb-9a8a-01526c6ad9d7.png)

My question is why there is such incoherences:
- The original folder contains 489 files, not 507, as shown in the app in the Library section
- The Places do not show information about those 489 files, but just 463
- What "Search" shows? Because 463 (primaries) + 13 (no-primary) = 473, which is not 489

Thanks for the clarification!

**Comment by lastzero** [comment]
Files are actual files, photos are distinct photos / stacks. They may contain multiple files such as other formats, edited versions or XMP sidecar files. Thus the difference. Places counts distinct location labels like city names, not photos.

**Comment by dml33** [comment]
> Files are actual files,

In Library section it says 507, but when you go downwards and all the files are loaded, it says that there are 489 files, which is what the operating system says, too. So, the number _507_ must be wrong somehow.

> photos are distinct photos / stacks. They may contain multiple files such as other formats, edited versions or XMP sidecar files. Thus the difference. 

I have only edited some videos metadata, adding latitude and longitude, since it seems that the mobile does not record them in case of videos. 
Only Stack section shows some content: "26 results". Again, 463 + 13 (half of the stacked ones, since the primary photo is already counted) is 476, but not 489.

> Places counts distinct location labels like city names, not photos.

Do you mean a state or country name as a keyword or just a valid location, given by longitude and latitude coordinates? 

Thanks!

**Comment by lastzero** [comment]
> In Library section it says 507, but when you go downwards and all the files are loaded, it says that there are 489 files, which is what the operating system says, too. So, the number _507_ must be wrong somehow.

Did you count files in the *storage/sidecar/* folder as well?

> Do you mean a state or country name as a keyword or just a valid location, given by longitude and latitude coordinates?

Not numeric coordinates, actual location labels as you can see them e.g. in the cards view on https://demo.photoprism.org/browse

Example: *Chicago, Illinois, USA*
