### ISSUE TITLE
UI: Mosaic view

### ISSUE THREAD

**Issue by pixelsbyweb** [photoprism/photoprism#1329]
Hi.

Is there an option to have mosaic view as default view?

**Comment by lastzero** [comment]
Default depends on your screen size. In addition, browsers should remember the current view type unless you start browsing on a new device or clear the cache.

**Comment by lastzero** [comment]
If this doesn't work, you're welcome to file a bug report with a description how to reproduce the issue.

**Comment by pixelsbyweb** [comment]
Yes, browsers do remember the last view type. 
But if album is shared with someone for the first time it would be great if we could set default view as mosaic as most people don't need the info displayed under the pictures.

**Comment by lastzero** [comment]
Many users have image titles and descriptions, so I guess it depends. Card view should only be default on large screens anyway, so I don't see a major issue here for now. Going to incrementally improve UX and add more settings once high priority feature requests are implemented. You can increase the priority by becoming a sponsor if you haven't signed up yet.

**Comment by pixelsbyweb** [comment]
I am not saying that there is an issue. 
All I meant is that it would be great if there is an option (some day ;-) ) to select default view. 

I just started using Photoprism not so long ago so just looking around for now before I commit with sponsoring.

**Comment by lastzero** [comment]
Hope you enjoy what we have in store right now 🤗
