### ISSUE TITLE
Videos not synced from Nextcloud, but photos are

### ISSUE THREAD

**Issue by Linkandzelda** [photoprism/photoprism#1335]
I have Nextcloud WebDAV configured in the Backup section with sync enabled. It successfully syncs the photos and adds them to the library. But no videos? They are in .mp4.

**Comment by lastzero** [comment]
Did you enable RAW sync?

**Comment by Linkandzelda** [comment]
Yes I did, it's been enabled since I first setup PhotoPrism around 8 months ago. I just upgraded the Docker image, to see if anything is fixed with that.

**Comment by lastzero** [comment]
Might also be a file size limitation. How large are your videos?

**Comment by lastzero** [comment]
See [WebDAV: Support syncing videos #504](https://github.com/photoprism/photoprism/issues/504)

**Comment by Linkandzelda** [comment]
I can confirm that upgrading the container has synced all the past videos which didn't make it in. However I can find no mention of configuration of this implemented size limit except for "originals size limit" of 1000MB. It wasn't clear if this is related to import, storage, or something else.

**Comment by lastzero** [comment]
All of them.
