### ISSUE TITLE
Incorrect Video Thumbnail (Stacking Problem)

### ISSUE THREAD

**Issue by shawnbarton** [photoprism/photoprism#1336]
Deployment Type: Docker
Current Version: 210523-b1856b9d-Linux-x86_64 (Library was created some versions ago)

I seem to have not-too-infrequent occurrences in which the tile for a video shows an image which does not match the video that is played once the tile is clicked. This seems to be an issue with stacking. I found an example which I wanted to post to try and diagnose the issue.

Tile:
<img width="144" alt="tile" src="https://user-images.githubusercontent.com/17271259/120065178-4d426880-c070-11eb-8aed-1b722fd75ba9.png">

Video:
<img width="293" alt="video" src="https://user-images.githubusercontent.com/17271259/120065253-9f838980-c070-11eb-85eb-842bdf40044c.png">

In Edit > Files, I can see that three files are stacked:
<img width="304" alt="stack" src="https://user-images.githubusercontent.com/17271259/120065289-c8a41a00-c070-11eb-8c36-315c6b2669ff.png">

Here are the properties of each file in the stack:

<img width="827" alt="file_1" src="https://user-images.githubusercontent.com/17271259/120065314-fab57c00-c070-11eb-87dc-2338e0473e98.png">

<img width="830" alt="file_2" src="https://user-images.githubusercontent.com/17271259/120065316-fee19980-c070-11eb-9d6b-586724dbdad6.png">

<img width="810" alt="file_3" src="https://user-images.githubusercontent.com/17271259/120065319-02752080-c071-11eb-990a-63a0a6d92d03.png">

Why does this occur? How can I remedy this issue across my entire library?

Thanks in advance.

**Comment by lastzero** [comment]
My first guess is that JPEGs and video files share the same name (prefix), so they're getting stacked (merged into one picture). If there is no JPEG preview for a video, PhotoPrism will automatically create one. If there already is a JPEG, PhotoPrism will use it as preview. Looking at your file names, this probably happened during import, so the original names before import may have been different but still sharing the same prefix.

**Comment by shawnbarton** [comment]
These files were part of a "big" iCloud export so it took me some time to try and locate the original files. All files from this iCloud store were imported into PhotoPrism over at least four batches (with the hope of allowing PhotoPrism to provide deduplication).

There are a number of files named IMG_0535, IMG_05351, IMG_05352, IMG_05353, sometimes with various extensions. I verified my findings with the SHA1 hash.

The jpg in the stack has an original name of "IMG_05352.JPG". 
The MOV is present twice and is named "IMG_0535.MOV" and "IMG_05352.MOV". 
The HEIC is "IMG_0535.HEIC".

The HEIC, JPG, and MOV all have different content unrelated to the other.

Unless I've misunderstood, this indicates to me that this method of file association may not be particularly good for large libraries (or large diverse import jobs), especially because the naming space is commonly only four to six integers which will frequently be re-used across different devices.

![image](https://user-images.githubusercontent.com/17271259/120205453-43646500-c22a-11eb-9f04-48dfed514bc3.png)
The lone file with a (2) was also just named "IMG_05351" but was renamed with (2) to display it alongside the other files

What options do I have to remedy this issue across the existing library?

**Comment by lastzero** [comment]
> Unless I've misunderstood, this indicates to me that this method of file association may not be particularly good for large libraries (or large diverse import jobs), especially because the naming space is commonly only four to six integers which will frequently be re-used across different devices.

This method of file naming is not well suited for unrelated files, in particular when exporting or importing.

Sidecar files are a common concept in photography and not something we invented for PhotoPrism:

https://en.wikipedia.org/wiki/Sidecar_file

The point here is that Apple and Google don't care much, especially when it comes to provide a clean export for other photo apps. You have the option of renaming unrelated file prior to indexing / importing, to manually unstack unrelated files, or wait for us to find a way to clean up the mess - which will require renaming unrelated files as well, so that they don't look like related sidecar files.

**Comment by shawnbarton** [comment]
Thanks for the quick reply 👍
I'm glad to read that this is already on your radar. Hope this input helps a little.
