### ISSUE TITLE
Question: Changing directory names

### ISSUE THREAD

**Issue by ameralzarouni** [photoprism/photoprism#1341]
Hi, 
Is it possible to change a folder name in the originals folder without having to go through reindexing, regeneration of thumbnails, and resorting of photos in the review section?
I currently have a folder mounted on originals/hdd2, but I want to change it to originals/Digitals, and mount additional locations to originals/Scans and originals/Negatives.
Thanks

**Comment by lastzero** [comment]
PhotoPrism can detect moved files if you didn't change them otherwise.

**Comment by ameralzarouni** [comment]
Thanks
