### ISSUE TITLE
Searching then browsing not behaving as expected

### ISSUE THREAD

**Issue by darkenbula** [photoprism/photoprism#1343]
If i perform a search across my library for something like 'cat' for example, the search will return expected results of cat pictures.  If i click on the first picture to view it and then use the right arrow i would expect it to cycle through the search results. Instead it will browser by date, so if the first returned search result is from march 6, using the right arrow to move to the next photo will cycle in reverse order through pictures from that date.

**Comment by lastzero** [comment]
Interesting, maybe this goes somehow back in your browser history?

**Comment by darkenbula** [comment]
I get the same results in a new private browser window.  Results seem inconsistent. For example i sort my search results from oldest to newest it behaves as expected, if i then display search results from newest to oldest, doesnt work correctly

**Comment by darkenbula** [comment]
You will notice in the video below, the images that are browsed, don't match the search results

https://youtu.be/IClAsEZFccc

**Comment by guim31** [comment]
I face the exact same issue (docker install on my Unraid server)

**Comment by darkenbula** [comment]
docker install on unraid here as well

**Comment by lastzero** [comment]
@graciousgrey can test it tomorrow

**Comment by graciousgrey** [comment]
I can reproduce it. It happens only for some photos of my search result and it does not happen if I click reload before browsing photos in fullscreen mode

@darkenbula @guim31 could you test the following:
1) If you have the search result, starting browsing from different photos and see if you have the same behaviour for all photos
2) Once you have the search result and the filter set to newest first, click the reload button and see if you observe the same behaviour

Thank you!

**Comment by darkenbula** [comment]
Best i can tell, if i close my browser and start over from scratch,. i get the unintended behaviour no matter where i start viewing the pictures from

If i refresh the page F5, it behaves correctly
