### ISSUE TITLE
Google Photos Takeout Re-Import

### ISSUE THREAD

**Issue by the3dsandwich** [photoprism/photoprism#1344]
Hi,

Before reading the whole docs I deleted all the json files from my Google Photos Takeout before starting the import process, thinking that PhotoPrism won't deal with it (but it will). I want the data from the json files so I moved them back. So I wonder if I need to re-import all the photos and delete the original library (basically redo everything), or will PhotoPrism compare the files and edit the photos instead and I can save (quite some) time re-importing?

Thanks!

**Comment by graciousgrey** [comment]
During import or index PhotoPrism matches photos and related sidecar files like json files by name. If you used import your photos have been renamed in originals. So the filenames of JSON and photo do not match anymore. In this case you need to re-import.

**Comment by the3dsandwich** [comment]
I see. I guess I'll have to redo everything then... should have read the whole document before doing stuff like this.
