### ISSUE TITLE
Single word for labels/keyword/category

### ISSUE THREAD

**Issue by G2G2G2G** [photoprism/photoprism#1346]
In the search, the labels are called "Category"
In the left tabs, they're called "Labels"
In the image data, they're called "Keywords"

**Comment by lastzero** [comment]
See FAQ: https://docs.photoprism.org/user-guide/faq/#whats-the-difference-between-keywords-and-labels

**Comment by G2G2G2G** [comment]
But there's a 3rd one there called "All Categories" on the search dropdown?  Should be "All Labels?"

**Comment by lastzero** [comment]
No it's categories, not all labels are categories. Animals are a category, cat is not.
