### ISSUE TITLE
multiple label search?

### ISSUE THREAD

**Issue by G2G2G2G** [photoprism/photoprism#1347]
When you select labels via the labels tab on the left, you can select multiple of them.. Is there a way to search that? All images with BOTH of those labels in them?
If you need an example let me know

**Comment by lastzero** [comment]
PhotoPrism doesn't support AND for the same search filter yet, just OR via `|`. You can however combine different filters to perform an AND search:

https://docs.photoprism.org/user-guide/organize/search/#or-search

**Comment by G2G2G2G** [comment]
Ok thanks, I was too dumb to find the search info I guess. You use the Pipe for OR do you plan on like & for AND?
