### ISSUE TITLE
Sharing a single album is exposing almost every single photo

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1350]
Hi,

I just tried sharing my first album, it generated the link:

http://server.home:2342/s/28evhyt9o9/<my-album-name>

When visited, this redirects to:

http://server.home:2342/s/28evhyt9o9/aqu6oey36gvrh2qn

If I go to that link, I can see all the photos in that album. Perfect!

If I click "Photoprism" in the top left hand corner it navigiates "up" a level to: 

http://server.home:2342/s/28evhyt9o9/

Which appears to be a listing of a whole bunch of other photos, in mostly calendar style folders "June 2021, May 2021" etc. but also some other numerically named folders. 

It says "465 albums found" - I only have 2 albums in my collection so...? They all say "Shared with you".

I assume this is something to do with the fact I have authentication turned off, but surely the point of generating an album link is to provide a gated area for people to view? Why allow people to navigate up a level?

Thanks.

**Comment by lastzero** [comment]
Yes, in public mode all albums are visible to everyone as there is no auth check. You need to enable authentication otherwise.

**Comment by lastzero** [comment]
It's for photographers who for example want to showcase their complete portfolio this way.

**Comment by timdonovanuk** [comment]
Ah I see. I might look at url rewriting and restrictions in the reverse proxy to handle this. If the ahref on the Photoprism logo was removed (the proxy will stop it working anyway) its not all that far from being a workable solution!
