### ISSUE TITLE
UX: Configure default page for PWA

### ISSUE THREAD

**Issue by AliMickey** [photoprism/photoprism#1354]
Would be great to have an option to load a specific side bar menu. Example: load the album page when the app is launched.

**Comment by AliMickey** [comment]
Clarification - this is for the mobile layout.

**Comment by graciousgrey** [comment]
Do you mean the mobile app or photoprism as PWA?

**Comment by AliMickey** [comment]
Photoprism as a PWA. Is there a mobile app? I thought PWA was the only and recommended way. 

Outside of mounting the WebDAV URL.

**Comment by graciousgrey** [comment]
Yes, we recommend using PhotoPrism as PWA and PhotoSync for automatic sync. There is a community maintained app as well, but it is still in beta (https://github.com/photoprism/photoprism-mobile).

**Comment by AliMickey** [comment]
Ah, that looks nice. I only need interfaces for my family to access the photo library. 

Any idea when the required API changes will be done? Or after the face recognition update?

Also I don't have experience in this framework, however i will be trying to implement this issue into the app. 
- Is there a way to sort folders? It seems to be random now, i would like it to be alphabetical if possible? Or needs implementing?

**Comment by AliMickey** [comment]
Is there a set of instructions on how to build this from source? I tried running 'go run .' from cmd/photoprism but running into issues.

**Comment by AliMickey** [comment]
Submitted a PR: https://github.com/photoprism/photoprism/pull/1361
