### ISSUE TITLE
Photo may need to be removed from demo sever

### ISSUE THREAD

**Issue by LexiconCode** [photoprism/photoprism#1356]
There's a photo that may need moderation on the demo sever: See 'Portrait / 那須塩原市 / 2021'

**Comment by lastzero** [comment]
Thanks! Delete works on our demo, so you may simply delete it next time:

- select and move to archive first via context menu (bottom right)
- then select it and click delete (again red button in the menu)

**Comment by lastzero** [comment]
Delete may have to be enabled in Settings first if disabled.

**Comment by lastzero** [comment]
Restarted. Thanks for letting us know!
