### ISSUE TITLE
Cyclic disk activity wakes up harddisk

### ISSUE THREAD

**Issue by scotch666** [photoprism/photoprism#1359]
Hello,
recently I discovered photoprism and I want to thank you for this piece of code. It's very nice for browsing through all of my photos (currently there are about 13000 photos indexed).
I bought an Raspberry PI 4b for hosting photoprism together with an external USB harddisk, where the data is saved.

I noticed, that the harddisk is waking up frequently and think that photoprism is the reason, because without running photoprism the harddisk stays in sleep mode for a much longer time.

My setup currently is like this:
Raspberry PI 4b:
- 32 GB SD with photoprism database in opt/photoprism
- 1 TB USB harddisk with directory "storage" and "Originals"

The command docker stats show cyclic net I/O and block I/O although photoprism is not opened in any browser. This probably leads to spinning up the USB harddisk.

Is there any way to prevent this or debug this in more detail?

Thanks!

BR
Xaver

**Comment by lastzero** [comment]
Increase the wakeup interval via config option.

**Comment by scotch666** [comment]
Thanks for your quick response! I just increased it to 12 hours and will check, if it is better now.
Is there any description, what these background workers do?

**Comment by lastzero** [comment]
They update certain counters, perform WebDAV sync (if enabled) and auto-import/index.

**Comment by Sithuk** [comment]
Photoprism keeps waking my hard drive. I've been able to identify photoprism as the culprit by de-activating and activating the docker container.

I've set the "PHOTOPRISM_WAKEUP_INTERVAL" property in docker-compose.yml to 86400 seconds (once per day) but the drive wakes up every two hours or so. Are there any other settings that need to be configured to stop photoprism from waking the drive?

**Comment by lastzero** [comment]
If it's not the background worker and you (or any of your devices) are not accessing your instance or using WebDAV sync / auto-index in any way, then I need to resort to remote guessing and wild assumptions at this point...

**Comment by lastzero** [comment]
You might just stop your instance when you don't want it to use any resources for an extended amount of time. In theory, a disk access could also be caused by Docker and MariaDB performing maintenance tasks.

**Comment by lastzero** [comment]
Do you see anything in the logs at the time the disk access is happening? :eyes:
