### ISSUE TITLE
New photos found on index without additions

### ISSUE THREAD

**Issue by jackbrown1993** [photoprism/photoprism#1368]
I started running PhotoPrism about a week ago and imported my whole photo collection, it took about a week but finally finished with about 80,000 photos and about 15,000 in review.

I then run an index on 'All Originals' and my photos count is increasing, which I find odd as I have added any additional photos, my assumption is that my import may have missed some? Or it imported and moved them but did add that to Photoprism which worries me slightly, could there be other photos 'hidden away' that I don't know about?

**Comment by lastzero** [comment]
Concurrently indexing on multiple CPU cores is not 100% deterministic, maybe some files were skipped the first time or are now stacked with other files, that were not known initially.

**Comment by jackbrown1993** [comment]
For my understanding, is it anticipated that a 2nd re-index would pick all these up? Or is there a chance that some could still be missed after indexing multiple times?

**Comment by lastzero** [comment]
There might be rare edge cases, depending on the metadata and number of CPU cores. Indexing once or max twice should be enough generally.

**Comment by lastzero** [comment]
I'll close this issue as there were no more questions.
