### ISSUE TITLE
Force mysql/mariadb database collation

### ISSUE THREAD

**Issue by citadella** [photoprism/photoprism#1371]
Not sure if this is possible or desired, but I was running an unraid mariaDB container and it seems it had a default database collation of latin1_swedish_ci which caused errors on any photos with special characters (location data/labels/etc). Manually changing the collation type to utf8_unicode_ci fixed this on the next re-index. I'm not sure if this is the correct collation type but it does work so would it be possible to either:

1. Force mysql database collation type to whatever unicode option is best
2. Document the proper mysql database collation to make sure when we create a new database table manually we create it in the correct format, regardless of whatever defaults our mariadb/mysql instance runs on.

![image](https://user-images.githubusercontent.com/31351568/121503347-49540600-c9e1-11eb-9dd0-68af908fe183.png)

**Comment by lastzero** [comment]
The correct collation should be set when using our example docker-compose.yml file. When users run and configure their own database, we have limited influence. Of course there are ways to force collations for each table and index. It's much easier to run the database with proper unicode defaults though.

**Comment by citadella** [comment]
Perhaps just a note in the documentation about desired unicode settings, then? At least to cover the unraid users and save a lot of troubleshooting down the line..
