### ISSUE TITLE
Wrong dates being updated to existing files.

### ISSUE THREAD

**Issue by jackbrown1993** [photoprism/photoprism#1373]
After the initial import of my library, I noticed some files missing, based on feedback I decided to reindex my library, I am now seeing files being updated with the wrong dates as seen below. If you look at the file names they have already been moved and renamed by PhotoPrism with the correct dates, such as the first one '20210224' however it then proceeds to take file mode date of 06-06-2021 which is incorrect.

I am also seeing unknown JSON errors which is a separate issue. I have recently changed from 'preview' to 'latest' if that could be having an impact. Any advice?

`time="2021-06-11T15:12:27Z" level=warning msg="metadata: unknown json in d53c44bd2f45117836f738cfae01aaeefe237a62_exiftool.json"

time="2021-06-11T15:12:27Z" level=info msg="media: 20210224_155402_8093D3C1.mov was taken at 2021-06-06 16:15:29.316436413 +0000 UTC (file mod time)"

**Comment by lastzero** [comment]
It's probably due to the renaming when importing. Does it happen when you index existing originals?

**Comment by jackbrown1993** [comment]
These were existing originals I believe, as you can see by the file name is in PhotoPrism format I believe?

**Comment by lastzero** [comment]
The file name in the JSON doesn't match the actual file name. Not sure why if you didn't use import.

**Comment by jackbrown1993** [comment]
They were imported, as you can see the file name is in the photo prism format and shows the correct date in the file name '20210224' as well as being in the correct folder within originals '2021/02'. It was when I run an 'Index all originals' it seemed to start updating the photo date to the 'file mod time'.

**Comment by lastzero** [comment]
So it's a bug due to the JSON files containing the wrong (import) file name instead of the new file name after importing.

**Comment by lastzero** [comment]
We're on vacation currently and back next week to fix this.

**Comment by jackbrown1993** [comment]
OK, thanks @lastzero, after a fix should a reindex fix these issues or will they somehow have to be manually resolved?

**Comment by lastzero** [comment]
We'll find a solution 👍

**Comment by jackbrown1993** [comment]
Thanks, @lastzero I am going to sponsor $8 p/m hope this helps the team.

**Comment by jackbrown1993** [comment]
@lastzero is it normal to see the below for an image? I found this image and it says the storage folder is Sidecar, it's a thumbnail created for a video I believe so wonder if it's pulling date from date thumbnail was created.

Storage Folder | Sidecar

<img width="758" alt="Screenshot 2021-06-11 at 21 00 08" src="https://user-images.githubusercontent.com/6218551/121742703-1badb080-caf8-11eb-8036-f94901965ed6.png">
<img width="869" alt="Screenshot 2021-06-11 at 20 59 50" src="https://user-images.githubusercontent.com/6218551/121742712-1ea8a100-caf8-11eb-9149-815395e21671.png">

**Comment by lastzero** [comment]
Yes, storage folder sidecar is normal for automatically created preview images.

**Comment by graciousgrey** [comment]
@jackbrown1993 do you still observe the issue of filenames being updated when re-indexing? If yes, is it happening to many files or just some? Did you edit those somehow or opened them in other tools? I am asking as the reindex normally only indexes existing files again in case their modify date changed.

**Comment by graciousgrey** [comment]
I will close this due to inactivity.
