### ISSUE TITLE
Sharing: WebDAV upload of albums fails with "0 files uploaded"

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1376]
Hi - I can share individual or multiple photos this way, but selecting an album to share appears to upload no files.

Steps:

1. Select album
2. Click share
3. Click WEBDAV UPLOAD
4. Account: Nextcloud. Folder: / (have tried different folders)
5. Click Upload
6. "0 Files uploaded"

**Comment by graciousgrey** [comment]
Thanks for reporting :)

**Comment by lastzero** [comment]
Using NGINX? Did you see this?
- https://github.com/photoprism/photoprism/issues/443

**Comment by rabotond** [comment]
HI,

I have the same issue. I have 2 Photoprism instances running on my server as there is not yet multi user support. We would like to share albums but not able to share just as described in this bug. 
I dont use Nginx everything is only on my local LAN. I add Webdav to both instances to point to each other (http://192.168.x.x:2342/import/, and http://192.168.x.x:2343/import/) at the sync tabs. Then when I share the album even though it can list the folders under webdav, when I click share "0 files uploaded". 

Can anyone help how to solve it? 

@lastzero

**Comment by graciousgrey** [comment]
I can confirm there's a bug. 

As a workaround for now you can go into the album, select all photos and click the cloud symbol (https://docs.photoprism.app/user-guide/settings/sync/#manually-upload-files-to-a-webdav-server)

**Comment by lastzero** [comment]
Note that videos are now also uploaded if the upload size *Originals* is selected in the "Manual Upload" account settings (default):

![upload-settings](https://user-images.githubusercontent.com/301686/155893817-a39ea43f-12b8-4225-893f-6fc1f302a99c.png)

**Comment by rabotond** [comment]
I pulled the preview docker image to try out changes done on this bug, and I can confirm this is now working. 

Thanks for the fix!

**Comment by inakrin** [comment]
Hello guys
I use the docker image photoprism/photoprism:latest and the issue is still present. 
The same situation with the photoprism/photoprism:preview
Need to note that I'm trying to upload a folder selected from the folders menu

**Comment by graciousgrey** [comment]
@inakrin Do you observe this for albums with videos only (the other bug) or also for albums containing JPGs?

**Comment by inakrin** [comment]
@graciousgrey  I've tried to upload a folder which contains both JPGs and videos.  Now tried with the folder which contains videos only - the same outcome.

**Comment by graciousgrey** [comment]
@inakrin Thanks for reporting, we will have another look at this as well.

**Comment by inakrin** [comment]
@graciousgrey  Sorry, this probably should be reported as another bug. Albums uploading works, meanwhile folder uploading doesn't. 
I've confused them I guess while looking through the issues.
Meanwhile the bug where previews are uploaded instead of the videos is present in both albums and folders
