### ISSUE TITLE
Sharing a HEIC photo over webdav sends the sidecar jpg which lacks metadata

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1377]
Hi,

Been trying to figure out why all my nextcloud shares lack EXIF metadata. Please consider making this configurable or transparent to the user, as when a photo is selected to share it is probably assumed the original is being shared (unless warned otherwise).

An alternative I guess is to ensure the sidecard jpg also has the original EXIF metadata.

Thanks!

**Comment by jackbrown1993** [comment]
Is this when you are importing photos into Photprism via webdav?

**Comment by timdonovanuk** [comment]
Sorry I wasn't clear here! This is using the "Share -> WebDAV Upload" from Photoprism to a WebDAV target (like NextCloud).

**Comment by graciousgrey** [comment]
You are right, the manual upload cannot yet handle raws, heic or video files (see: https://docs.photoprism.org/user-guide/settings/sync/#manually-upload-files-to-a-webdav-server).

We plan to add this as an option: https://github.com/photoprism/photoprism/issues/829
