### ISSUE TITLE
Deleting an album?

### ISSUE THREAD

**Issue by jucor** [photoprism/photoprism#1380]
Dear team
Is there a way to delete an (empty) Album please?
Created one by mistake, want to delete it but finding no way to.
Am I missing something completely obvious?
Thanks for any help :-)

**Comment by graciousgrey** [comment]
You can select the album --> open the context menu --> click delete :)

**Comment by jucor** [comment]
Oh gosh, I hadn't realised that the "1" circled at the bottom was not just a counter, but a whole menu!! So *that*'s the "context menu" mentioned many times in the doc. I guess I'm too old-school in my UI patterns :)Thanks Theresa, that's exactly what I needed! And thanks a lot for your reactivity. Closing this issue!

**Comment by lastzero** [comment]
Welcome to the world of mobile first where there is no right mouse button to open a traditional context menu :)

**Comment by jucor** [comment]
- Give me my keyboard shortcuts back, you ungrateful millennials!
- OK boomer.

(Photoprism mode in Emacs, anyone? ;) )

**Comment by lastzero** [comment]
Keyboard shortcuts are on our todo :+1:

**Comment by jucor** [comment]
Oh? Awesome! Thanks!

**Comment by graciousgrey** [comment]
Yep, https://github.com/photoprism/photoprism/issues/1131 :)
