### ISSUE TITLE
Previously Organized Originals: index: no supported files found for ***.jpg (unknown type)

### ISSUE THREAD

**Issue by kennyparsons** [photoprism/photoprism#1383]
Hey all. I've been able to successfully run import jobs and the albums show up just as expected. However, I have some photos already organized into folder "albums." For example, I moved our wedding photos into the original photos directory with the folder title: Wedding Photos. 
At this point, I need to re-index so this folder will show up in Folders and Albums. When I index, I can see the folder in originals:
![Screen Shot 2021-06-17 at 12 13 10 PM](https://user-images.githubusercontent.com/5930491/122443653-69497380-cf65-11eb-8a8f-de0da80746b1.png)

But, after indexing, I get these errors for all photos in that folder:
```
time="2021-06-17T17:05:31Z" level=warning msg="index: no supported files found for EI2A7853.jpg (unknown type)"
*truncated*
time="2021-06-17T17:05:31Z" level=warning msg="index: no supported files found for EI2A7929.jpg (unknown type)"
time="2021-06-17T17:05:31Z" level=info msg="index: no new or modified files"
time="2021-06-17T17:05:31Z" level=info msg="purge: searching index for unassigned primary files" 
time="2021-06-17T17:05:31Z" level=info msg="purge: searching index for hidden media files"
time="2021-06-17T17:05:31Z" level=info msg="Indexing completed in 4 s"
```
Neither the folder nor the album show up in the UI. Am I missing something obvious?

**Comment by lastzero** [comment]
Can you check if EI2A7853.jpg is a JPEG file? Does it work with all other apps?

**Comment by lastzero** [comment]
Please also make sure it's readable (has the right file and folder permissions).

**Comment by kennyparsons** [comment]
> Can you check if EI2A7853.jpg is a JPEG file? Does it work with all other apps?

Yes.

**Comment by kennyparsons** [comment]
> Please also make sure it's readable (has the right file and folder permissions).

It has R/W. 

I re-ran this again and it worked on the fourth or fifth try. No changes were made.

**Comment by lastzero** [comment]
Sounds like an unstable file system, but really can only guess what the reason is. Certainly not normal. A user recently reported problems with the Unraid caching function, so that files randomly disappear.

**Comment by graciousgrey** [comment]
@kennyparsons did you observe this behaviour again or does it work now?

**Comment by kennyparsons** [comment]
Appears to work now. It took several hours to resolve, but it did so on its own.
