### ISSUE TITLE
Can't change password for mariadb in docker compose.

### ISSUE THREAD

**Issue by iTris666** [photoprism/photoprism#1387]
Anything but "insecure" for PHOTOPRISM_DATABASE_PASSWORD lead to connection errors

**Comment by graciousgrey** [comment]
Within docker-compose.yml only the initial password can be set. If you started photoprism once before changing the password in the docker-compose.yml you need to use a mysql command to update the password (see: https://websiteforstudents.com/how-to-change-mysql-mariadb-user-passwords-on-ubuntu-16-04-18-04/).
If your database is still empty you may delete the database files, and then change the password in your docker-compose before you start the service.

**Comment by graciousgrey** [comment]
@iTris666 did the above solve your issue?

**Comment by lastzero** [comment]
@iTris666 You'll may stop all Docker containers, delete the contents of the `./database` folder, and then start everything again to start with a fresh database that uses the currently set INITIAL password. Changing the initial password AFTER the database was initialized for the first time won't change the password. Same goes for the initial PhotoPrism password.

If you know a little SQL, you may set a new password using this command: https://mariadb.com/kb/en/set-password/

```
SET PASSWORD FOR 'photoprism'@'%' = PASSWORD('newpass');
```

The statement must be executed as user root in the MariaDB database. To get to the database console, you may open a terminal, go to the directory where your `docker-compose.yml` is and run:

```
docker-compose exec mariadb mysql -u root -p [root password] photoprism
```

You'll find the root password in your `docker-compose.yml`.

**Comment by iTris666** [comment]
Here's what I try today : 

What I did, from my Mac :
- Create an Ubuntu Server VM 20.04.2
- install docker
- wget https://dl.photoprism.org/docker/docker-compose.yml
- mkdir photoprism
- mv docker-compose.yml photoprism/
- cd photoprism/
- pico docker-compose.yml
- changed PHOTOPRISM_ADMIN_PASSWORD: "toto"
- changed PHOTOPRISM_DATABASE_PASSWORD: "titi"
- save and quit
- docker-compose up -d
- sudo docker-compose logs --tail=25 -f
Attaching to mariadb, photoprism
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: 128 rollback segments are active.
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: 10.5.11 started; log sequence number 45130; transaction id 20
mariadb       | 2021-07-05 16:47:11 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb       | 2021-07-05 16:47:11 0 [Note] InnoDB: Buffer pool(s) load completed at 210705 16:47:11
mariadb       | 2021-07-05 16:47:11 0 [Note] Server socket created on IP: '::'.
mariadb       | 2021-07-05 16:47:11 0 [Warning] 'proxies_priv' entry '@% root@9745adb719d1' ignored in --skip-name-resolve mode.
mariadb       | 2021-07-05 16:47:11 0 [Note] Reading of all Master_info entries succeeded
mariadb       | 2021-07-05 16:47:11 0 [Note] Added new Master_info '' to hash table
mariadb       | 2021-07-05 16:47:11 0 [Note] mysqld: ready for connections.
mariadb       | Version: '10.5.11-MariaDB-1:10.5.11+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb       | 2021-07-05 16:47:12 3 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:17 4 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:22 5 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:27 6 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:32 7 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:37 8 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:42 9 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:47 10 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:52 11 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:47:57 12 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
mariadb       | 2021-07-05 16:48:02 13 [Warning] Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)
photoprism    | running as uid 0
photoprism    | photoprism start
photoprism    | time="2021-07-05T16:48:07Z" level=fatal msg="Error 1045: Access denied for user 'photoprism'@'172.18.0.2' (using password: YES)"
photoprism exited with code 0

**Comment by iTris666** [comment]
maybe we are not supposed to change PHOTOPRISM_DATABASE_PASSWORD but if we do, even on a fresh database.

**Comment by lastzero** [comment]
You may change `PHOTOPRISM_DATABASE_PASSWORD` but then also need to change `MYSQL_PASSWORD` so that the passwords match.

If MariaDB is not publicly exposed and only running in an internal Docker network (which is inside a VM as well), it's not strictly required to change the database password as only PhotoPrism can connect to it.

**Comment by iTris666** [comment]
ok, thank you.
