### ISSUE TITLE
Unable to download photos via public URL

### ISSUE THREAD

**Issue by gomme600** [photoprism/photoprism#1392]
Hi,

I am unable to download anything via the public URL, I get access denied. There is a difference in the download link.

Connected via local ip (192.168.1.18): http://192.168.1.18/api/v1/dl/27f04496bd444b68b2706c324a6626d4d62764a8?t=<token>

Connected via public ip: https://photos.XXXXXX.ga/api/v1/dl/27f04496bd444b68b2706c324a6626d4d62764a8?t=public

If I replace "public" with the <token> then the download works via the public ip so this is not a nginx problem.

Any ideas?

Thanks

**Comment by lastzero** [comment]
You have to use the exact same URL incl. all get parameters that PhotoPrism uses. To protect your originals, PhotoPrism uses special URLs that can not be easily guessed. In addition, it requires a random download token, which may change from time to time. 

This is slightly different for smaller, downsampled thumbnail images, as they should stay cached in the browser for a good user experience. Also there is no metadata in thumbnails to protect your privacy in case something "leaks" e.g. when you copy the URL using the browser manu and post it in a public forum e.g. on Facebook.

**Comment by gomme600** [comment]
Yes, but I'm not the one typing the URLs. PhotoPrism generates the download URL without the unique token when using the public URL to acces and login to the site. If I use the internal URL then the token is correctly appended to the download URL.

**Comment by lastzero** [comment]
Do you have the same issues with our public demo? Obviously, it seems to work for others so I suspect this is a local config or networking issue.

**Comment by gomme600** [comment]
No, the public demo works fine. But that doesn't have a log in page so maybe that is why? The network is fine because if I use the generated token and append it to the download link via the public URL then it works. PhotoPrism just doesn't append the token automatically, it uses the keyword "public" instead.

**Comment by lastzero** [comment]
Public is fine if you're running a public instance without password. Is that the case? Do you run any firewall or reverse proxy in front of PhotoPrism (as strictly recommended when using it outside a private home network)? Are you sure the request hits the right server and instance / container?

**Comment by gomme600** [comment]
No, I have a password. I run nginx reverse proxy. Everything is running in docker and yes the request is connecting to photoprism ok because everything else works fine.

I have tried setting this :  PHOTOPRISM_DOWNLOAD_TOKEN: "TESTTEST"

It still doesn't work, now I get these links when clicking download:

From home network: http://192.168.1.18:2342/api/v1/dl/419b52d6cab49ef49e9aa6c9e3ac0af33478e8b0?t=TESTTEST
From public url: https://photos.XXXXXX.xx/api/v1/dl/419b52d6cab49ef49e9aa6c9e3ac0af33478e8b0?t=public

Again, if I replace "public" with "TESTTEST" then the download works fine, otherwise I get access denied.

So this works manually, but photoprism will not supply this url automatically for some reason: https://photos.XXXXXX.xx/api/v1/dl/419b52d6cab49ef49e9aa6c9e3ac0af33478e8b0?t=TESTTEST

**Comment by lastzero** [comment]
Are websockets working properly, or do you see a yellow warning icon in the left lower corner of the app navigation?

**Comment by gomme600** [comment]
I haven't seen anything like that no.

**Comment by lastzero** [comment]
Do you see any errors or warnings in the JavaScript console of you browser (open developer tools for this)?

**Comment by lastzero** [comment]
Or maybe your nginx reverse proxy is doing other strange things as it seems to work without, right?

**Comment by gomme600** [comment]
I set up a new instance and sometimes it works, othertimes not. I am rather confused!

**Comment by lastzero** [comment]
Yep, this is strange - if you can provide us with a more specific report and find the issue, we're happy to fix it if it turns out to be a bug in PhotoPrism...
