### ISSUE TITLE
Wrong location for most of the images which doesnt have any location

### ISSUE THREAD

**Issue by marcosvrs** [photoprism/photoprism#1395]
After importing my images from Google Photos, I have 40k photos imported and 10k photos to review. Most of the photos to review has the wrong location. Even for photos that doesn't have any location metadata at all and now it's located to a wrong place.
Example:
![image](https://user-images.githubusercontent.com/10147574/123845305-5430f500-d914-11eb-9533-279e3ede439b.png)
Those documents I'm sure that doesn't contain any location metadata and still they are assigned to "Belinho e Mar, Norte, Portugal".

What kind of data/log do you need from me to be able to debug it correctly?

[The original image file](https://1drv.ms/u/s!AgCPO4p2gZqbhqZrqGj_9D79GLRMEg?e=cUAOxq)
![image](https://user-images.githubusercontent.com/10147574/123846031-2a2c0280-d915-11eb-8015-f9046518d38e.png)

**Comment by graciousgrey** [comment]
PhotoPrism estimates the location of images without coordinates based on images with coordinates that have been taken at the same time (https://docs.photoprism.org/user-guide/settings/library/#estimates). Do you have images in your library that have coordinates matching with this location and do those images have date/time information ?

**Comment by lastzero** [comment]
Note that you can disable estimates in Settings (won't remove existing estimates though):

![estimates](https://user-images.githubusercontent.com/301686/123989002-c6631180-d9c8-11eb-9895-09b659d9e741.png)

**Comment by zaharcelac** [comment]
What is the right way to remove existing assets with wrong estimates (so I can disable "Estimates" and re-import them)?

**Comment by lastzero** [comment]
You should be able to remove the files and use the `photoprism purge` command in a terminal. It's a bit tedious though.

If you know a little SQL, you may set `place_id` to `'zz'` where  `place_src = 'estimate'` in the `photos` table to remove all estimates:

```
UPDATE photos SET place_id = 'zz', place_src = '' WHERE place_src = 'estimate';
```

This statement must be executed in the MariaDB database. To get to the database console, you may open a terminal, go to the directory where your `docker-compose.yml` is and run:

```
docker-compose exec mariadb mysql -u root -p [root password] photoprism
```

You'll find the root password in your `docker-compose.yml`.

**Comment by lastzero** [comment]
Note that it may also be possible that Google named the JSON sidecar files in way that associates them with the wrong image files, like when there are (name) duplicates. Googles export can get a little confusing and inconsistent in that case.

**Comment by marcosvrs** [comment]
> 
> 
> You should be able to remove the files and use the `photoprism purge` command in a terminal. It's a bit tedious though.
> 
> If you know a little SQL, you may set `place_id` to `'zz'` where `place_src = 'estimate'` in the `photos` table to remove all estimates:
> 
> ```
> UPDATE photos SET place_id = 'zz', place_src = '' WHERE place_src = 'estimate';
> ```
> 
> This statement must be executed in the MariaDB database. To get to the database console, you may open a terminal, go to the directory where your `docker-compose.yml` is and run:
> 
> ```
> docker-compose exec mariadb mysql -u root -p [root password] photoprism
> ```
> 
> You'll find the root password in your `docker-compose.yml`.

Thanks! That helped a lot.
For my use case, I also wanted to remove the country info from my photos. So I used:
```
UPDATE photos SET photo_country = 'zz', place_id = 'zz', place_src = '' WHERE place_src = 'estimate';
```

**Comment by lastzero** [comment]
Excellent, looks good to me!

**Comment by oijkn** [comment]
For my part, I've started from a fresh installation and the `Estimates` option is indeed disabled. However, during the import of photos from my smartphone, some images have incorrect location.

How can I resolve this issue?

**Comment by graciousgrey** [comment]
Are you sure that photos that are imported after the Estimates option has been disabled still receive location estimates? 

Please note that deactivating the feature does not remove the existing estimates of photos that were previously imported. 

It is also theoretically possible that your photos have incorrect coordinates in their metadata. You can check the metadata of your originals files by running "exiftool -j filename.jpg" in a terminal.
