### ISSUE TITLE
Missing tag 20210602

### ISSUE THREAD

**Issue by psa** [photoprism/photoprism#1399]
The latest update Dockerfile pulls `photoprism/development:20210602` but this tag does not exist.

**Comment by lastzero** [comment]
Where do you see that? Should be:

```
photoprism/development:20210628
```

**Comment by psa** [comment]
I must have been looking at an old checkout. Having said that I also don't see a 20210628 tag.

**Comment by psa** [comment]
For what it's worth, I'm particularly focused on the tags, not because I use Docker but because we use them for the FreeBSD port.

**Comment by lastzero** [comment]
https://hub.docker.com/r/photoprism/development/tags?page=1&ordering=last_updated

Old Docker version? We've moved to multi arch builds with development.

**Comment by psa** [comment]
Can you please tag the repo with git tags matching what you've got with docker?

For the FreeBSD port, we rely on git tags as markers of releases and we build from them. The last tag on the repo is `210523-b1856b9d`

**Comment by lastzero** [comment]
`b1856b9d` is the Git commit hash. The full version string like `210523-b1856b9d-Linux-x86_64` is generated while compiling inside the container - depending on the settings, git commit, date and architecture. So we technically don't know it upfront when starting the build, unless we duplicate the code / logic. However, we could add a tag alias later - e.g. when also tagging the version in Git. We don't tag stable releases before the build is complete because it may fail. So we had to undo everything and tell users not to upgrade because there was an error.

**Comment by psa** [comment]
It seems we are focusing on different things. Please ignore the Dockerfile comment, I was originally surprised it didn't match git tags but practically we don't actually care (others might).

We only care about _the tag in git_ as that's what we use to build from (and, correctly or not, we're using tags as an indicator of build stability).

> ... e.g. when also tagging the version in Git. We don't tag stable releases before the build is complete because it may fail. 

[Drone](https://drone.photoprism.app/photoprism/photoprism) shows successful builds since 2021-05-23. I don't see anything in the developer documentation about how tagging is done and when it's done. 

The current latest tags are:

```
git tag | sort -r | head -2
210523-b1856b9d
210520-4b32bac7
```

Succinctly:
* Please add tags to the git repo for the latest stable builds
* Please update the developer documentation describing how tagging of the git repo is done and when it is done

**Comment by lastzero** [comment]
These tags are for the released builds in the release branch. We tag them manually as we also manually write the realase notes for them. What's the advantage of drone doing this? Master is our preview build, not stable.

**Comment by psa** [comment]
I made an assumption, possibly incorrectly, that the updates to Dockerfile were an indication of a release and raised this ticket because I believed that a release had been done (based on the Dockerfile updates) and someone just missed adding the git tag. Sorry, I didn't realise that releases were manual and not related to the Dockerfile.

**Comment by lastzero** [comment]
Yeah, it's just the base image of a multi stage build. The backend binary and frontend packages are getting built inside the dev container based on the code in the GitHub repo. Final app then gets installed in a clean image without dev dependencies. You can also build without Docker if you have all dependencies installed.

**Comment by psa** [comment]
In my case, I'm helping maintain the FreeBSD port, so what's important to us is keeping track of the releases so we can update the port in a timely manner for the users of that. We're not using Docker at all, it's all a native build.

Thanks for the clarification on how releases are managed. I think this ticket can be closed now. The only improvement I can think of would to be to update the development documentation describing how releases are managed.
