### ISSUE TITLE
Source-code documentation (go doc)

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#14]
Add a `doc.go` file to describe the individual packages in `internal/`. Make sure go docs are properly rendered / displayed. Add a doc target to `Makefile`.

When docs are working, add badge to README.md.

See:
- https://godoc.org/golang.org/x/tools/cmd/godoc
- https://blog.golang.org/godoc-documenting-go-code
- https://godoc.org/

**Comment by ScreamingTaco** [comment]
How detailed do the docs have to be? I can probably help add a general overview of the packages.

**Comment by lastzero** [comment]
Excellent. Keep it simple, depending on your time. For the package description, you can use content from the homepage / user guide.

**Comment by ScreamingTaco** [comment]
Sounds good. Once I’ve got it written I’ll submit a PR; your choice to merge or not :)
