### ISSUE TITLE
Great project. I have two feature requests

### ISSUE THREAD

**Issue by diba78** [photoprism/photoprism#140]
Hi guys,

your project looks realy nice. I have two feature requests.

1. User management

2. Viewer for 360° photos (like photos from the Insta360 one X). Their is an an web plugin called Photospher Viewer. Eventually you can implement it :-)

I am no developer. So i can't help you with code.

But have send you an donation and i can help you with my feedback.

So stay tuned on the project. Wish you the best.

Best regards

Dirk

**Comment by lastzero** [comment]
Thank you for the donation! We're going to continue development soon, had to do a commercial project to fund this. This mainly is a single user up. We want to implement peer-to-peer sharing later. But a login certainly makes sense. 360° photos probably won't happen soon, but maybe later...
