### ISSUE TITLE
Exiftool: Large File Support

### ISSUE THREAD

**Issue by BetaAthe** [photoprism/photoprism#1401]
Hi. Doing some testing, I am unable to play large videos on my Photoprism instance. With large videos, I mean close to 3GB .mp4 avc1 encoded videos.

I have a folder with more than 10 videos, all encoded the same way. All the videos with size < 2.2 GB are playable, and all of them with size > 2.9GB are not. I don't have any video in the 2.2-2.9 range.

When I try to play that videos, ffmpeg kicks in consuming all the cpu of my server. Disabling ffmpeg transcoding makes the video unplayable.

Also, I saw that those video's metadata was wrong, so digging in a little found out that it was a problem with exiftools, solved by writting
```
%Image::ExifTool::UserDefined::Options = (
    LargeFileSupport => 1,
);
```
into the .ExifTool_config file in the /root directory.

**Comment by rickysarraf** [comment]
Speaking for myself, I have preferred to re-encode my video files, carefully choosing a setting, which keeps the video file's size substantially low. The reason for doing so is simply because those files are rarely to be viewed on a large display. My expected clients of PhotoPrism, in all probability, will mostly be PC, Tablet and Mobile. For these device form factors, I don't really need video files with very high bit rate. But this is purely my personal choice.

File sizes greater than 2 GiB are ignored by PP. I think it logs that information in its system logs.

**Comment by BetaAthe** [comment]
Thanks for the response! This videos are more than 3 hours long, as they are VHS digitalizations, and I think they are already compressed to an acceptable threshold. I understand that one possibility is to split them into two or more files, but I would prefer to not resort to that.

To be able to upload them to PhotoPrism, I had to add the PHOTOPRISM_ORIGINALS_LIMIT: 5000 variable.

As I saw that 2.2 GiB videos are working flawlessly, I thought it was a matter of changing one setting or removing one hard limit from the app.

**Comment by lastzero** [comment]
As the name suggests, we've designed PhotoPrism for still pictures and short clips like live photos. It MAY not be the best tool for managing full-length movies, especially if you have a lot of them. 

Increasing `PHOTOPRISM_ORIGINALS_LIMIT` to the max file size in MB and then restarting your instance should work though. If your videos are not encoded with MP4 / AVC1, we recommend you transcode them upfront by running `photoprism convert` in a terminal to avoid high server load and long delays when playing them in the UI.

**Comment by lastzero** [comment]
Please close this issue if your question is answered with that :)

**Comment by BetaAthe** [comment]
Hi! I've added that variable and restarted the instance to be able to index them in the library. All the videos are encoded using the same preset, so they are basically the same. Also, I checked them using exiftools and all of them reported the same codec, AVC1. In the PhotoPrism GUI, large playable videos report "AVC1" and the very large unplayable ones report "MP4", for some reason.

I know that PhotoPrism was not made for large videos in mind, and can understand that this issue could be marked as wontfix because of that, but as I saw that this software is able to reproduce some large videos without trouble, I considered this case a bug as, I think, nothing prevents these very large videos for playing properly.

**Comment by lastzero** [comment]
PhotoPrism uses exiftool to detect the codec, so it should show AVC1 if exiftool does. Did you try a full rescan of the affected folders (don't need to rescan your complete library)?

**Comment by BetaAthe** [comment]
Exiftools wasn't able to open this video files at first. I had to follow [this forum post](https://exiftool.org/forum/index.php?topic=3916.0) to being able to read them [[1]](https://github.com/photoprism/photoprism/issues/1401#issue-935760983). Once done, exiftools read the codec correctly. I've done the same inside the PhotoPrism Docker container but the reported codec is still MP4 in the PhotoPrism web interface after the rescan. Thumbnails are created though.

**Comment by lastzero** [comment]
Then it's probably because we didn't enable large file support in exiftool. Imagine this could lead to memory issues or DOS attacks.

**Comment by BetaAthe** [comment]
Ok, got it. I understand your concerns about memory or DOS but, is there a way to tell PhotoPrism to use exiftool with large files support?

**Comment by lastzero** [comment]
Need to change this in our code as the parameters can not be configured, there are already a ton of config options nobody understands.

**Comment by lastzero** [comment]
Added the Exiftool flag as requested, and started a new preview build:

https://docs.photoprism.app/getting-started/updates/#development-preview

Let us know if this works for you!

**Comment by BetaAthe** [comment]
I checked the photoprism/demo:latest container (don't know if that's the right container) and the issue persists. I want to test more things to try to understand why it doesn't work. I'll comment if I find something.

**Comment by lastzero** [comment]
Use the preview tag as shown in our docs / release notes / example config.

**Comment by lastzero** [comment]
Also start with a fresh installation or delete the existing JSON sidecar files so that they get recreated.

**Comment by BetaAthe** [comment]
Ok, I tested removing everything and starting again with the preview tag, but it's not working. I've done some testing:

First, I rendered 6 mp4 test files using AVC1 codec with 1:30, 2:30 and 3:30 hours in length and different sizes. (Size is under "Tamaño" and length under "Duración").
![testfiles](https://user-images.githubusercontent.com/18726230/125063757-2b48f680-e0b0-11eb-868f-dc5769096a82.jpg)

This is the import log:
```
2021-07-09 12:06:06 INFO index: added related jpg file test6.mp4.jpg

2021-07-09 12:06:05 INFO media: test6.mp4.jpg was taken at 2021-07-09 10:06:16.045067349 +0000 UTC (file mod time)

2021-07-09 12:06:05 INFO index: added main mp4 file tests/test6.mp4

2021-07-09 12:06:05 INFO media: test6.mp4 was taken at 2021-07-09 09:58:53.032380405 +0000 UTC (file mod time)

2021-07-09 12:06:05 INFO media: 11 thumbnails created for test6 [203.897678ms]

2021-07-09 12:06:04 INFO converting tests/test6.mp4 to jpg

2021-07-09 12:06:01 INFO index: added related jpg file test4.mp4.jpg

2021-07-09 12:06:00 INFO media: test4.mp4.jpg was taken at 2021-07-09 10:06:00.272474298 +0000 UTC (file mod time)

2021-07-09 12:06:00 INFO index: added main mp4 file tests/test4.mp4

2021-07-09 12:06:00 INFO media: test4.mp4 was taken at 2021-07-09 09:57:55.12619302 +0000 UTC (file mod time)

2021-07-09 12:06:00 INFO media: 11 thumbnails created for test4 [203.03006ms]

2021-07-09 12:05:59 INFO converting tests/test4.mp4 to jpg

2021-07-09 12:05:49 INFO index: added related jpg file test5.mp4.jpg

2021-07-09 12:05:48 INFO index: added main mp4 file tests/test5.mp4

2021-07-09 12:05:48 INFO media: 11 thumbnails created for test5 [200.048314ms]

2021-07-09 12:05:47 INFO converting tests/test5.mp4 to jpg

2021-07-09 12:05:46 INFO folder: added album Vhs (path:vhs public:true)

2021-07-09 12:05:46 INFO index: added related jpg file test2.mp4.jpg

2021-07-09 12:05:45 INFO index: added related jpg file test1.mp4.jpg

2021-07-09 12:05:45 INFO index: added related jpg file test3.mp4.jpg

2021-07-09 12:05:32 INFO index: added main mp4 file tests/test2.mp4

2021-07-09 12:05:32 INFO media: 11 thumbnails created for test2 [273.312459ms]

2021-07-09 12:05:32 INFO converting tests/test2.mp4 to jpg

2021-07-09 12:05:30 INFO index: added main mp4 file tests/test3.mp4

2021-07-09 12:05:30 INFO index: added main mp4 file tests/test1.mp4

2021-07-09 12:05:30 INFO media: 11 thumbnails created for test3 [301.142623ms]

2021-07-09 12:05:30 INFO media: 11 thumbnails created for test1 [281.767971ms]

2021-07-09 12:05:27 INFO converting tests/test3.mp4 to jpg

2021-07-09 12:05:27 INFO converting tests/test1.mp4 to jpg

2021-07-09 12:05:25 INFO index: added folder /tests
```

Doing this, files test1, test2, test3 and test5 work, but test4 and test6 don't. I tested with Firefox 89 and Microsoft Edge.
![works](https://user-images.githubusercontent.com/18726230/125064794-508a3480-e0b1-11eb-9ecc-06e1905c69f5.jpg)
![dont work](https://user-images.githubusercontent.com/18726230/125064795-508a3480-e0b1-11eb-81b0-7c757fe6ac5d.jpg)

This is the data of one working file and one that doesn't:
![stats yes](https://user-images.githubusercontent.com/18726230/125065021-97782a00-e0b1-11eb-857b-e504509a9eea.jpg)
![stats no](https://user-images.githubusercontent.com/18726230/125065019-96df9380-e0b1-11eb-9bdd-e528c292eeff.jpg)

**Comment by lastzero** [comment]
Currently downloading a 10h video from YouTube so that we can figure out how to properly provide multiple values to `exiftool -api`. Haven't found useful examples in their docs. Going to build a new preview image after having tested it locally.

**Comment by lastzero** [comment]
Added `-m` in addition to `-api LargeFileSupport`, seems to work with this. Preview build has been started and should be available within 1 or 2 hours (might have to restart if it fails): 

https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by BetaAthe** [comment]
Looks like it's solved now! Thanks!

**Comment by lastzero** [comment]
Excellent, thanks for testing! 🥳

**Comment by lastzero** [comment]
Development preview and https://demo.photoprism.org/ have been updated again. Had to remove `-api QuickTimeUTC`  from Exiftool parameters as it turned out not to really fix MP4 / Quicktime video time zones. Now implemented differently.
