### ISSUE TITLE
docker: document where scan results are stored

### ISSUE THREAD

**Issue by andig** [photoprism/photoprism#141]
Using the default docker setup, I want to avoid re-scanning after upgrading the docker container. I would also like to avoid re-scanning the same image if it has not changed.

Currently the docs do not make clear how scanning is done or scan results are persisted.

**Comment by lastzero** [comment]
Yes, the image is mainly there for testing and the demo. You need a persistent file system to keep the database. If you check our docker-compose.yml file, you see the various environment variables you can (you can also do this with a config file which should be documented in our wiki):

https://github.com/photoprism/photoprism/blob/develop/docker-compose.yml
