### ISSUE TITLE
In the mosaic view, is an SQL query containing 4 joins (for me, 700ms+) required? A simple query on photos/files table is orders of magnitude faster. 

### ISSUE THREAD

**Issue by timdonovanuk** [photoprism/photoprism#1413]
My photoprism database is really starting to crawl along - I've been able to temporarily slap a plaster on it by enabling the recommended settings documented here, which to some degree simply just caches some of the first queries run when viewing the page, but doesn't help with subsequent queries (e.g. when offset moves by 60).

```
2021-07-05 21:48:55 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:900 order:newest merged:true [574.937699ms]

2021-07-05 21:48:53 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:840 order:newest merged:true [587.681189ms]

2021-07-05 21:48:52 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:780 order:newest merged:true [589.981057ms]

2021-07-05 21:48:50 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:720 order:newest merged:true [577.10143ms]

2021-07-05 21:48:49 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:660 order:newest merged:true [574.567917ms]

2021-07-05 21:48:48 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:600 order:newest merged:true [556.469868ms]

2021-07-05 21:48:46 INFO photos: found 60 results for public:true dist:20 quality:3 count:60 offset:540 order:newest merged:true [559.527299ms]
```

This is actually better than it was, before making the recommended changes I was seeing queries take 800ms+.

I noticed when scrolling through in mosaic view that a colossal amount of data is being queried for:  

`SELECT photos.*, photos.id AS composite_id, files.id AS file_id, files.file_uid, files.instance_id, files.file_primary, files.file_sidecar, files.file_portrait,files.file_video, files.file_missing, files.file_name, files.file_root, files.file_hash, files.file_codec, files.file_type, files.file_mime, files.file_width, files.file_height, files.file_aspect_ratio, files.file_orientation, files.file_main_color, files.file_colors, files.file_luminance, files.file_chroma, files.file_projection, files.file_diff, files.file_duration, files.file_size, cameras.camera_make, cameras.camera_model, lenses.lens_make, lenses.lens_model, places.place_label, places.place_city, places.place_state, places.place_country FROM `photos` JOIN files ON photos.id = files.photo_id AND files.file_missing = 0 AND files.deleted_at IS NULL LEFT JOIN cameras ON photos.camera_id = cameras.id LEFT JOIN lenses ON photos.lens_id = lenses.id LEFT JOIN places ON photos.place_id = places.id WHERE (files.file_type = 'jpg' OR files.file_video = 1) AND (files.file_error = '') AND (photos.deleted_at IS NULL) AND (photos.photo_private = 0) AND (photos.photo_quality >= ?) ORDER BY taken_at DESC, photos.photo_uid, files.file_primary DESC LIMIT 60 OFFSET 120`

ooof!

![image](https://user-images.githubusercontent.com/8156439/124517165-3a435680-dddb-11eb-8fa5-1dcf894f0777.png)

I am not a database expert by any means, but as soon as I start removing JOINS, query times goes from 800ms to about 5ms. I don't see in mosaic view that camera, lense info or location is needed, which seems cause most of the slow execution time. 

It could of course be a hardware issue io issue, but my mariadb sits on an nvme drive. FWIW I have around 73k photos indexed, although a lot are trash/hidden I guess, as there are 110,593 rows in the files table.

Thanks for reading! :)

**Comment by lastzero** [comment]
You're right in that this can be optimized. The REST API as it is right now doesn't care how the result view looks like, so it always returns the same data. Joins may also be optimized. If you scroll a lot to find pictures instead of using the search, there is a high chance you're actually waiting for the timeline view. It's on our roadmap already.

**Comment by graciousgrey** [comment]
I will close this ticket in favor of this: https://github.com/photoprism/photoprism/issues/1438
