### ISSUE TITLE
Nextcloud sync freezes raspberry pi 4 8GB

### ISSUE THREAD

**Issue by gomme600** [photoprism/photoprism#1414]
Hi,

I have been experimenting with syncing with nextcloud as the photoprism mobile app is not auto uploading correctly for me. Unfortunatly whenever photoprism syncs this freezes my raspberry pi for a good 10 minutes each time. This means that all of my services go down regularly. I currently don't have any way to automatically upload my photos to photoprism reliably.

Is this a know issue on the raspberry pi ? Can it be fixed or do I need better hardware ?

Thanks

**Comment by lastzero** [comment]
It's probably causing a lot of I/O and CPU load to copy and index your files, especially since Nextcloud uses PHP.  What about mounting the Nextcloud storage folder directly without using sync? This will also reduce storage size as you don't have two copies.

**Comment by gomme600** [comment]
If I do that then won't I have to reindex originals each time ? Or should I mount the nextcloud folder as the import directory ?

**Comment by gomme600** [comment]
Also, if I mount nextcloud without using sync then won't I have to run indexing manually ? Or will the new files be detected ?

**Comment by lastzero** [comment]
You have to trigger indexing manually when mounting Nextcloud files directly as PhotoPrism won't get a notification from Nextcloud about new or changed files.

However, you can add and configure a scheduler to "automatically" index as frequently as you like, based on your personal needs (see `jobs.ini`):

https://dl.photoprism.org/docker/scheduler/

**Comment by graciousgrey** [comment]
@gomme600 can we close this?

**Comment by gomme600** [comment]
> @gomme600 can we close this?

If you want to yes. Although the problem still persists but it looks like the raspberry pi just isn't powerful enough.

**Comment by graciousgrey** [comment]
Out of interest does it persist when you use sync or do you observe the same when mounting the Nextcloud storage folder directly? I guess we can't do much about it right now.

**Comment by gomme600** [comment]
Mounting the folder directly works fine.

**Comment by lastzero** [comment]
We assume the freezing was because Nextcloud is implemented in PHP. Not ideal for syncing lots of data / files via WebDAV. Closing this issue since there's probably not much we can do at this point.
