### ISSUE TITLE
Could not find SavedModel .pb or .pbtxt at supplied export directory path: /root/.local/share/photoprism/resources/nasnet

### ISSUE THREAD

**Issue by ripnetuk** [photoprism/photoprism#142]
Hi,
Running on docker on ubuntu, and the web site now works (after the update to prevent the segfault), but when I index, i get a bunch of
Could not find SavedModel .pb or .pbtxt at supplied export directory path: /root/.local/share/photoprism/resources/nasnet
This directory exists, but is empty.

**Comment by lastzero** [comment]
I assume you're not using our Docker image?

In that case, you need to download the models manually... we do this using a script in the Dockerfile, see `scripts/download-nasnet.sh`. Maybe we should download them when photoprism starts in the future...

**Comment by ripnetuk** [comment]
Hi.
I am using your docker image. Actually a docker file with a single line from your image, and docker-compose.

**Comment by lastzero** [comment]
Maybe the development image? Then you need to follow the dev guide and run `make all build` first.

**Comment by ripnetuk** [comment]
Hi,
Thanks for replying :)
My dockerfile is pulling from photoprism/photoprism

FROM photoprism/photoprism

MAINTAINER George Styles



and im using docker-compose (that shouldnt affect the image)

version: '2'
services:
  s-photoprism:
    container_name: s-photoprism
    build:
      context: .
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 192.168.13.20
    hostname: s-photoprism
    volumes:
#      - /mnt/autofs/GFiles/cloudbackup/myphotosandvideos:/root/Pictures/Originals:ro
      - /mnt/autofs/GFiles/cloudbackup/testphotos:/root/Pictures/Originals:ro
networks:
  macvlan_net:
    external: true

**Comment by ripnetuk** [comment]
Woohoo! its working now - my test photos show up nicely on the map, which is the feature im after... now to let it loose on my entire collection
thanks

**Comment by lastzero** [comment]
@ripnetuk Note that our DB is not optimized for large collections... it's working, but slow as TiDB doesn't support FULLTEXT yet, so all text needs to be compared string by string (full table scan)

See https://twitter.com/browseyourlife/status/1175119742899650560

Also we need to implement clustering on the map, for example using https://github.com/Leaflet/Leaflet.markercluster

**Comment by lastzero** [comment]
Thank you! 👍
