### ISSUE TITLE
Using the sharing link with secret from a browser which is logged in shows all albums

### ISSUE THREAD

**Issue by rahul003** [photoprism/photoprism#1421]
The link with myphotoprism.com/s/secret showed me all albums not just the one shared with that secret. All the albums were shown with a sign saying 'shared with you'. That scared me. But it seems to be because I was already logged in. Other browsers only showed one album. It would be good to fix that secret webpage and show only the albums shared with that secret.

**Comment by lastzero** [comment]
Are you running photoprism in public mode?

**Comment by rahul003** [comment]
No I have set that to false

**Comment by lastzero** [comment]
OK, but you're authenticated as admin - so it makes sense you see everything.

**Comment by lastzero** [comment]
We're reworking authentication anyway and it's not a security issue, so we'll have to leave it like that for now - not running out of tasks anytime soon :)

**Comment by lastzero** [comment]
Thanks for reporting this anyway, should find a more user friendly solution in the future! @graciousgrey

**Comment by tootbrute** [comment]
> OK, but you're authenticated as admin - so it makes sense you see everything.

I think I bumped into this behaviour today. 

- in Incognito browser window I tested a share link from my server, so I wasn't logged in
- clicking the top left Photoprism logo seems to move it up a directory level and let somebody see all my photos.

I can't imagine anybody using the share button in it's current form unless sharing with their wife or husband. Exposing all my photos to a person is not what I expect would happen when sharing an 'album'. I'm glad I tested it before sending to family. That was a close call!

I think this should be mentioned on the documentation page, https://docs.photoprism.org/user-guide/share/share/

It could lead to an embarrassing, or dangerous situation for some people who are unaware of this.

**Comment by graciousgrey** [comment]
@tootbrute how can we reproduce this?  

When I open a sharing link in an incognito window I have only access to this album, even if I click on the site title in the upper left corner. If I open another sharing link for another album in the same incognito window I see both shared albums when clicking on the site title (as expected).

 What version/browser are you using? 
Do you run PhotoPrism in public mode? 
How does your setup look like?

**Comment by tootbrute** [comment]
system:
debian 10, with Yunohost

docker-compose.yml
PHOTOPRISM_PUBLIC: "false"

Now I try to reproduce it and I can't either. 

The only way I can reproduce it is to paste the sharing link into a NON-incognito window, when I'm already logged in. I must've used that same incognito window yesterday to test the authentication was working before testing a link.

Apologies. Sharing works as expected. I even added more characters to the 'secret' to break it, but still works. *phew*

**Comment by lastzero** [comment]
It's because albums are unlocked when you open a link for the first time so that you can share multiple albums without requiring others to kill the session and click the share links over and over again. This wouldn't be very user friendly and likely frustrating. You can also see all pictures if you're signed in as admin anyway in case you prefer the reduced share view. We can disable that if it causes confusion.

**Comment by tootbrute** [comment]
I understand.

Your example is:
- I have Photoprism installed.
- I'm logged into Photoprism
- I click a share link that someone sends me from another Photoprism installation.

I think people expect these sort of 'share' links to be dead ends. When I clicked the top corner (while logged in) and went back to my library, it wasn't a regular library view. It said "shared with me" under every photo. This was the part that really scared me. It appeared that all my files were 'shared' through that link.

I think if you change the appearance of what it looks like when you go back to your own photos through a shared link, or pop up some information so people know they are leaving the shared link and going back to their own Photoprism.

**Comment by graciousgrey** [comment]
@tootbrute once we are done with multi-user support we will improve sharing anyways. If someones shares albums with you and you have your own instance you will have a section with all content that is shared with you.
