### ISSUE TITLE
Non-Complete Rescan / Re-index does not skip unchanged files

### ISSUE THREAD

**Issue by dominikholler** [photoprism/photoprism#1424]
After adding new photos to originals via WebDAV, a long running Rescan / Re-index is triggered.
Even folders which was not modified via the WebDAV, are scanned again, which might take a several hours on big libraries.

**Comment by lastzero** [comment]
Already known files should be skipped when updating the index without performing a complete rescan. This may take a few seconds, so not an issue usually. Are you using a slow disk or network storage? Are the any other tools updating file mod times, so that they look changed?

**Comment by dominikholler** [comment]
My storage is an external USB HDD, not amazing fast, but should be okay. I will run a benchmark to ensure the storage performance, if required. I also have 250k photos in the affected instance of photoprism.

get a lot of messages, maybe for every photo, like:
```
time="2021-07-09T16:16:02Z" level=info msg="index: updated main jpg file 2004/08August/XXXburg/p1010718.jpg"
time="2021-07-09T16:16:02Z" level=info msg="media: p1010720.jpg was taken at 2004-08-01 00:00:00 +0000 UTC (name)"
```
Are those messages expected for unmodified photos on a non-complete re-scan?

**Comment by lastzero** [comment]
No, there should be no info message for unchanged files.

**Comment by dominikholler** [comment]
> No, there should be no info message for unchanged files.

I see, so the issue is about not skipping unchanged files.
I can confirm that another photoprism instance skips unchanged files as intended.

**Comment by dominikholler** [comment]
Currently I cannot reproduce. Closing this issue, I will re-open if I find the trigger to reproduce.
