### ISSUE TITLE
Bad Gateway on PUT with Photosync iOS App

### ISSUE THREAD

**Issue by Daywalker01** [photoprism/photoprism#1427]
As I have notices the iOS app PhotoSync now supports Photoprim, so I tried it out, and failed miserably with a 502 Bad Gateway...

Relevant docker-compose logs:
```
photoprism    | time="2021-07-10T17:45:27Z" level=debug msg="http: OPTIONS / (200) [4.136171ms]"
photoprism    | time="2021-07-10T17:45:27Z" level=debug msg="http: MKCOL /______ (200) [4.377806ms]"
photoprism    | time="2021-07-10T17:45:27Z" level=debug msg="http: MKCOL /______/Zuletzt (200) [3.777106ms]"
photoprism    | time="2021-07-10T17:45:27Z" level=debug msg="http: PUT /______/Zuletzt/IMG_4442.MOV (200) [3.880059ms]"
```

Relevant Apache Logs

```
==> /var/log/apache2/photoprism_access.log <==
2a01:100:2000:xyz:4615 - - [10/Jul/2021:19:47:12 +0200] "OPTIONS / HTTP/1.1" 200 8468 "-" "PhotoSync/372 CFNetwork/1240.0.4 Darwin/20.5.0"
2a01:100:2000:xyz:4615 - - [10/Jul/2021:19:47:13 +0200] "MKCOL /______ HTTP/1.1" 200 3275 "-" "PhotoSync/372 CFNetwork/1240.0.4 Darwin/20.5.0"
2a01:100:2000:xyz:4615 - - [10/Jul/2021:19:47:13 +0200] "MKCOL /______/Zuletzt HTTP/1.1" 200 3275 "-" "PhotoSync/372 CFNetwork/1240.0.4 Darwin/20.5.0"

==> /var/log/apache2/photoprism_error.log <==
[Sat Jul 10 19:47:13.594598 2021] [proxy:error] [pid 576268:tid 139683792533248] (32)Broken pipe: [client 2a01:100:2000:xyz:54064] AH01084: pass request body failed to 127.0.0.1:2342 (localhost)
[Sat Jul 10 19:47:13.594648 2021] [proxy_http:error] [pid 576268:tid 139683792533248] [client 2a01:100:2000:xyz:54064] AH01097: pass request body failed to 127.0.0.1:2342 (localhost) from 2a01:100:2000:xyz ()

==> /var/log/apache2/photoprism_access.log <==
2a01:100:2000xyz- - [10/Jul/2021:19:47:13 +0200] "PUT /______/Zuletzt/IMG_4442.MOV HTTP/2.0" 502 1627 "-" "PhotoSync/372 CFNetwork/1240.0.4 Darwin/20.5.0"

```
My apache config
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerAlias photo.my.tld

	LogLevel warn
	CustomLog ${APACHE_LOG_DIR}/photoprism_access.log combined
	ErrorLog ${APACHE_LOG_DIR}/photoprism_error.log

	SSLProxyEngine On
	SSLProxyVerify none
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off
#	ProxyPreserveHost on
	
	DocumentRoot /var/www/html
	ProxyPass /.well-known !

	RewriteEngine on
#	RewriteCond %{HTTP:Upgrade} websocket [NC]
#	RewriteCond %{HTTP:Connection} upgrade [NC]
#	RewriteRule ^/?(.*) "ws://localhost:2342/$1" [P,L]
	

	ProxyPass /api/v1/ws ws://localhost:2342/api/v1/ws
	ProxyPassReverse /api/v1/ws ws://localhost:2342/api/v1/ws
	ProxyPass / http://localhost:2342/
	ProxyPassReverse / http://localhost:2342/
	ProxyRequests off

	SSLCertificateFile /etc/letsencrypt/live/photo.my.tld/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/photo.my.tld/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Everything else is straight forward.
sqlite Databse, and nothing more...
Who is behaving wrong here?

PS.: The explanation for websokets sits different in the local documentation from the community one (as seen in my commented apache config

Best regards

**Comment by graciousgrey** [comment]
Do you observe the same when using WebDAV as target instead of PhotoPrism in PhotoSync?

Just tested with my setup and it's working fine. So it's not a general issue with PhotoSync.

@lastzero will have a look at your apache config as soon as possible

**Comment by Daywalker01** [comment]
Hi
WebDAV works just fine
Eiter /originals/ or /import/ both work without any issues
For now I have nothing changed on the server side in case you might need any more information.

Maybe it is helpful to tell you that I use IPv6. If that makes any difference.
For now I'll stick to WebDAV, as it does not seem to have any negative implications 😊
Also: the communication is completely local, in my home network. The complete Traffic from and to this network is therefore allowed. (checked again)

**Comment by lastzero** [comment]
Seems Apache related - maybe a request timeout and problems with multi-part form data? Googling for [AH01084 apache put](https://www.google.com/search?q=AH01084+apache+put) finds these pages which may contain a solution:

- https://stackoverflow.com/questions/13003282/apache-multipart-post-pass-request-body-failed 
- https://blog.ionelmc.ro/2018/03/25/proxy-issues-with-apache/
- https://www.jfrog.com/jira/si/jira.issueviews:issue-html/RTFACT-22904/RTFACT-22904.html

**Comment by Daywalker01** [comment]
I‘m on vacation for the next few days. Will check asap when I’m back

**Comment by graciousgrey** [comment]
@Daywalker01 Any update on this?

**Comment by Daywalker01** [comment]
Sry for the late reply...
Unfortunately none of the suggested links helped me out.
At least I'm still working with the WebDAV Workaround, without any issue.

Anything else that you want me to try?

**Comment by lastzero** [comment]
Unless you absolutely want to stick with Apache, we recommend using Traefik or Caddy as reverse proxy. Those are easier to configure for modern web applications as you don't need special settings for full WebDAV & Websockets support.
