### ISSUE TITLE
Videos: Skip related images when downloading

### ISSUE THREAD

**Issue by tanuva** [photoprism/photoprism#1436]
G'day,

I recently tried to download a video from PhotoPrism (PWA on iOS). What I'm offered looks like the video thumbnail image though, with a file name pattern like `video_name.mp4.jpg`. I suspect this is not intentional? :)

Observed on my local installation as well as the PP demo setup.

**Comment by lastzero** [comment]
Downloads both for me, at least on a desktop browser?

![downloads](https://user-images.githubusercontent.com/301686/125933238-62aec191-d5a2-48b2-be55-16f74731867c.png)
![download-1](https://user-images.githubusercontent.com/301686/125933239-59d2a3da-6152-4614-9d9f-caf1c82c253e.png)

**Comment by graciousgrey** [comment]
Thanks for reporting! I can reproduce it with the PWA on iOS.

@tanuva As a workaround for now you can open the edit dialogue of the video and click the download button for the mp4 file within the files section (https://docs.photoprism.org/user-guide/organize/edit/#edit-files)

**Comment by tanuva** [comment]
Thanks, the workaround... works. :)

I must admit though I find that "multiple files downloaded at once" behaviour quite unexpected. For stacked photos it probably makes sense. With video preview images it feels more like I get internal helper files thrown at me that I don't care about. 🤔

**Comment by lastzero** [comment]
Yes, for videos it probably doesn't make much sense for most users - unless your OS shows no native preview or you need a still picture as preview e.g. when sharing on social media. For RAWs, it often makes sense as browsing through those directly is typically super slow and they're not good for sharing as well.

**Comment by graciousgrey** [comment]
Maybe we should change the default behaviour vor videos until we come to this ticket: https://github.com/photoprism/photoprism/issues/449.

**Comment by lastzero** [comment]
Should also never download a transcoded MP4 / AVC version, always just the original even when stacked with other files?

**Comment by tanuva** [comment]
That one left me thinking for a bit. When downloading videos to a, say, restricted device such as a phone or tablet I would obviously prefer a transcoded video zhat plays over an original that doesn‘t.

Then again, on a proper computer I‘d of course want the original. Maybe have options on large screens and offer compatible video by default on smaller ones? Then there‘s edge cases again. Phew.

**Comment by lastzero** [comment]
Started a new preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview

Unsure how to handle live photos as some people may want to download the still picture along with the video file. Sometimes it's all in one file and the still picture was extracted, or it was automatically created by PhotoPrism. Probably need to handle those cases differently.

**Comment by tanuva** [comment]
Works fine in the preview build, thanks for the quick fix! \o/

**Comment by lastzero** [comment]
Thanks for reporting & testing! Had it in the back of my mind for a while... ultimately need to add settings for this.

**Comment by lastzero** [comment]
Downloading multiple files via iOS PWA still is broken? You're welcome to create a new issue for this... maybe a contributor can figure out how to fix it as it seems to work on all other devices and operating systems... wonder why Apple is so special.
