### ISSUE TITLE
A few questions regarding auto importer.

### ISSUE THREAD

**Issue by blmhemu** [photoprism/photoprism#1440]
As the title suggests,
* Docs suggest that importer is triggered 15 mins after activity on import folder. If a file is still in upload, what happens in such a case. Does the timer get reset-ed if a file is still in upload because there is still some activity?
* If I use syncthing to sync to the imports folder, will it be imported 15 mins after sync?

---
Thanks a lot for the amazing project.

**Comment by graciousgrey** [comment]
- The upload itself is not detected as activity. The timer is set to 15 mins when the upload starts. If the upload is taking less than 15 mins and the next file starts to upload the timer is reset to 15 mins. If the upload of one file takes longer than 15 mins and no other process is running the import will be triggered. You might change the duration of the delay (PHOTOPRISM_AUTO_IMPORT)
- If syncthing uses WebDAV to sync files to the import folder, the import will be triggered automatically

**Comment by blmhemu** [comment]
Thanks for the quick reply !
* If a large file with > 15 min is being uploaded, then will the partially uploaded file be imported to originals or will it imported in the next try? 
* No AFAIK Syncthing does not do WebDAV, lets just say it acts like another program which just creates some files in the same folder (photoprism import). Basically import is like a shared folder where syncthing can produce content (files) and photoprism can consume content (files).

**Comment by lastzero** [comment]
> * If a large file with > 15 mins upload time is being uploaded, then will the partially uploaded file be imported to originals or will it imported in the next try. I do not care about the time of import, but more about file integrity.

That's a tricky question as it may depend on your WebDAV client. From what I know, it's possible to upload in chunks with multiple HTTP requests. In this case, the timer is reset, so it should be safe.

Otherwise, 15 min might not be enough to avoid this scenario when uploading large (video) files, or when using a very slow connection as the import delay currently starts when a request is received, not when it ends.

**Comment by blmhemu** [comment]
Thanks! That answers the first question. Is it possible to implement a hash based polling ? We store the last hash and if hash changes, we postpone the import. If hash does not change, we then import.

**Comment by lastzero** [comment]
That's not very efficient as all files would need to be hashed... we may later try to poll the current status from the http server, so that the import can be blocked if needed.

**Comment by blmhemu** [comment]
Does (fsnotify)[https://github.com/fsnotify/fsnotify] fit this use case?

**Comment by lastzero** [comment]
@blmhemu In theory yes, but there can be many edge cases like 

- when there are too many files to watch 
- or the OS / FS doesn't support file watching

Also the problem of importing / indexing at the right time is a bit more complex in that you not only want to wait for completely transmitted files but also for all related files to be transferred. Importing a sidecar XMP for example doesn't make sense when the main media file(s) aren't there yet. Need to think this through in a quiet moment, ideally when we're working on related issues anyway.

**Comment by blmhemu** [comment]
Got it! Feel free to close this issue or keep it open according to your needs. Thank you.
