### ISSUE TITLE
Silly question on match logic in func bestLabels

### ISSUE THREAD

**Issue by guanlisheng** [photoprism/photoprism#1441]
hi there,
I am a little confused by the following statements and not sure how we connect the index of **probabilities** and the size of **t.labels**

```
// bestLabels returns the best 5 labels (if enough high probability labels) from the prediction of the model
func (t *TensorFlow) bestLabels(probabilities []float32) Labels {
	var result Labels

	for i, p := range probabilities {
		if i >= len(t.labels) {
			// break if probabilities and labels does not match
			break
		}
```

Thanks.

**Comment by lastzero** [comment]
The TensorFlow model was trained with a fixed list of 1000 labels as "result vector". The vector itself doesn't contain string labels, it's just floating point numbers representing probabilities. Thus we loop over the result and extract those labels that have a high probability. Hope that answers your question?

**Comment by lastzero** [comment]
Closing this since there were no follow-up questions.
