### ISSUE TITLE
Wrong creation date+time when indexing files with similar name

### ISSUE THREAD

**Issue by cabe1214** [photoprism/photoprism#1448]
Photoprism version: 210523-b1856b9d-Linux-x86_64

```
photoprism@photoprism:~$ uname -a
Linux photoprism 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

This week I copied some photos and videos from an iPhone to the originals folder of photoprism and I realized that some of the fotos were not shown on the correct order because the creation was wrong.
After digging into it I found out that some of the files are named the same but with different extensions (AFAIK this is something you cannot exclude on iPhones, as they do not use timestamps on the filenames).
```
-rwxr-xr-x 1 root root 1149510 Mar 23 17:50 IMG_8445.HEIC
-rwxr-xr-x 1 root root 2385408 Jul 14  2020 IMG_8445.JPG
```
As you can see above, the pictures were taken at different times, but during the indexing of Photoprism, it seems like they are handled as they were the same foto. Therefore, the one indexed later gets the creation time from the one indexed first  and both are stacked together.

Additionally I see some Warnings/Errors during the indexing that might be caused because of this:
```
ERRO[2021-07-26T14:03:35Z] file: Error 1062: Duplicate entry 'Fotos/P/IMG_8445.HEIC-/' for key 'idx_files_name_root' (create) 
ERRO[2021-07-26T14:03:35Z] index: Error 1062: Duplicate entry 'Fotos/P/IMG_8445.HEIC-/' for key 'idx_files_name_root' in Fotos/P/IMG_8445.HEIC (add new file) 
INFO[2021-07-26T14:03:35Z] index: failed main heif file Fotos/P/IMG_8445.HEIC 
WARN[2021-07-26T14:03:35Z] Error 1062: Duplicate entry 'Fotos/P/IMG_8445.HEIC-/' for key 'idx_files_name_root' 
```
Indexing timestamps:
```
IMG_8445.HEIC
Added 	Jul 26, 2021, 4:03 PM in 724 ms 
IMG_8445.JPG
Added 	Jul 26, 2021, 4:47 PM in 2,997 ms 
```

I would expect two files to be stacked (handled as different versions of the same picture) if the creation time is the same. As soon as two "similar" files have different creation times they shall be identified as two different pictures. 

Note: I think the problem here is Apple-specific, and it is caused by a filename-reuse policy on iPhones as on other Android phones I have the filenames always have a timestamp.

**Comment by lastzero** [comment]
It's the concept of sidecar files in photography. I don't think it's the iPhone but the export tool that's causing this. Please search for related issues as it has been discussed. We're on vacation right now.

**Comment by cabe1214** [comment]
Hi @lastzero, will do. Thank you for the answer and enjoy your vacation!

**Comment by cabe1214** [comment]
Hi again, I did the following test on a new clean installation.
I put two **different** images on the originals folder (TestIMG_0806.HEIC and TestIMG_0806.JPG) and ran a first indexing.
```
photoprism    | time="2021-07-26T21:16:25Z" level=info msg="Indexing originals..."
photoprism    | time="2021-07-26T21:16:25Z" level=info msg="classify: loading nasnet"
photoprism    | time="2021-07-26T21:16:36Z" level=info msg="classify: loading labels from labels.txt"
photoprism    | time="2021-07-26T21:16:36Z" level=info msg="index: no .ppignore file found"
photoprism    | time="2021-07-26T21:16:36Z" level=info msg="index: added folder /"
photoprism    | time="2021-07-26T21:16:37Z" level=info msg="index: added main heif file TestIMG_0806.HEIC"
photoprism    | time="2021-07-26T21:16:59Z" level=info msg="media: 7 thumbnails created for TestIMG_0806 [4.115041377s]"
photoprism    | time="2021-07-26T21:16:59Z" level=info msg="index: added related jpg file TestIMG_0806.JPG"
photoprism    | time="2021-07-26T21:16:59Z" level=info msg="purge: searching index for unassigned primary files"
photoprism    | time="2021-07-26T21:16:59Z" level=info msg="purge: searching index for hidden media files"
photoprism    | time="2021-07-26T21:16:59Z" level=info msg="Indexing completed in 34 s"
photoprism    | time="2021-07-26T21:17:02Z" level=info msg="photos: found 1 results for public:true dist:20 quality:3 count:60 order:newest merged:true [9.683209ms]"
```
After the indexing finished I can only see one image on the gallery, but when I edit the picture I see that there are two files stacked.

```
TestIMG_0806.JPG
UID 	FQWVF4779XFSB298
Hash 	2a9d1341ae9deb6071b1be6eb129de2876de590c
Name 	TestIMG_0806.JPG
Size 	1200 × 1600, 0.1 MB
Type 	JPG
Codec 	JPEG
Primary 	Yes
Portrait 	Yes
Aspect Ratio 	0.75
Main Color 	Brown
Chroma 	18 / 100
Added 	Jul 26, 2021, 11:16 PM in 17,498 ms 
```
and
```
TestIMG_0806.HEIC
UID 	FQWVF3P1TPH4U9KY
Hash 	fc024536fcc8a4acab1342f91d55ff3cc84dbd7e
Name 	TestIMG_0806.HEIC
Size 	3024 × 4032, 2.2 MB
Type 	HEIF
Codec 	HEIC
Portrait 	Yes
Aspect Ratio 	0.75
Added 	Jul 26, 2021, 11:16 PM in 192 ms 

```
The foto shown in the gallery is the last one indexed. 

If I perform the action UNSTACK, I can see both fotos in the gallery, but the metadata of both pictures is the same. 
@lastzero I hope you can follow my use case. Both files (HEIC and JPG) are different fotos, it is not the same foto in two different formats. It just happens that the filenames are the same (except the extensions).

**Comment by cabe1214** [comment]
Maybe some words about the export tool. I am not sure that the problem is introduced by the tool. I'm using [Photosync](https://www.photosync-app.com/de/index.html), to send the pictures of one album from the iPhone to the **originals** folder, so I think the pictures are copied directly from the local storage of the iPhone to the Photoprism **originals** path.

I did the test directly copying two fotos downloaded from google (one in JPEG and a different one in HEIC) and naming them Foto1.jpg and Foto1.heic. Same result as above.

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/faq/#what-are-sidecar-files-and-where-do-i-find-them

Can you configure PhotoSync to use different file names instead?

**Comment by cabe1214** [comment]
I will try to confiugre PhotoSync to add the creation timestamp at the beginning of each file and report back. I'll also read about sidecar files, the term is new to me. Thanks for the link!
