### ISSUE TITLE
Find alternative to Darktable that runs on ARM64

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#145]
**As a Raspberry Pi owner, I want to run PhotoPrism on my device without any limitations.**

PhotoPrism requires Darktable to covert RAW to JPEG. However, Darktable requires a processor that supports SSE2 (Streaming SIMD Extensions). That excludes ARM64 as used in Raspberry Pi computers.

Acceptance Criteria:
- [ ] Find one or more RAW to JPEG converters that run on the Raspberry Pi 4
- [ ] Ideally the converter should be available as pre-compiled package for Ubuntu
- [ ] If multiple converters are available, figure out which converter is best in terms of quality and performance

**Comment by graciousgrey** [comment]
The following raw converters have ubuntu packages (bionic 18.04):
* [Darktable] --> https://packages.ubuntu.com/bionic/darktable
* RawTherapee --> https://packages.ubuntu.com/bionic/rawtherapee
* UFraw --> https://packages.ubuntu.com/bionic/ufraw
* ImageMagick --> https://packages.ubuntu.com/bionic/imagemagick

Therefore we would need this ubuntu image https://hub.docker.com/layers/ubuntu/library/ubuntu/latest/images/sha256-a547e88f518355c22df160dd879cf7452b078ad445eb2c307a0787e0945b18d4

Interesting for 64bit on raspberry:
https://www.heise.de/newsticker/meldung/Raspberry-Pi-Erste-Fassung-des-64-Bit-Kernels-verfuegbar-4524121.html
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=232684

**Comment by lastzero** [comment]
So the issue is 32 vs 64 bit... the latest version of Darktable can be compiled on ARM64 but Raspbian is still 32 bit.

**Comment by bobobo1618** [comment]
Just ran across this. You might also consider dcraw. It's very basic but also relatively lightweight and has quite varied support.

I'd also suggest recommending that users use a 64-bit OS. There are 64-bit versions of BalenaOS, Manjaro and a few custom builds of Ubuntu flying around.

**Comment by Extarys** [comment]
Ah damn, I should have checked before trying to install on a Pi 4 :sob: 
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by lastzero** [comment]
This sadly has to wait until after we have a stable release or we receive more donations.

**Comment by lastzero** [comment]
Closing this since Darktable actually runs on ARM64, just not ARM32 - so it can not run directly on Raspbian (but via Docker with ARM64 kernel and ARM32 userland).
