### ISSUE TITLE
[BUG] Sound issue when playing video in Firefox

### ISSUE THREAD

**Issue by Mike-Sundays** [photoprism/photoprism#1460]
Hello! First of all, thanks for the awesome application.

I was indexing my library today for the first time, and when I tried to play one of my videos through the app, it did not play any sound. The mute / unmute button was also unclickable and even right clicking with the mouse and selecting "Unmute" did not solve the problem. This was with Firefox 90.0.2 on Mac OS 11.5.1 . I tried to reproduce videos in other websites and they work fine.

I also tried reproducing the videos in photoprism with Chrome and Safari, and I did not find any issue. Am I the only one having this problem?

Thanks, and if you need further details, let me know.

**Comment by lastzero** [comment]
Maybe it's using an audio codec Firefox doesn't support? We only transcode if the video codec isn't AVC.

**Comment by Mike-Sundays** [comment]
Yes, I investigated further and it seems it does not support it: https://support.mozilla.org/en-US/questions/1291035.
So it is not a Photoprism issue, it seems, but a Firefox one. You can close the issue. Thanks!
