### ISSUE TITLE
problematic jpeg

### ISSUE THREAD

**Issue by lakemike** [photoprism/photoprism#1463]
Hi, I have a jpeg in my library which is able to crash photoprism. Symptom is that memory consumption grows up to the point when a system daemon (running on a QNAP NAS) is noticing it and killing the process. Is there any interest in isolating this further to make photoprism more robust?
At least on my end, it was necessary to remove the file to be able to complete indexing.

**Comment by graciousgrey** [comment]
Is this only happening with this special jpeg and with no other files? What did the logs say?

**Comment by graciousgrey** [comment]
Might be related to https://github.com/photoprism/photoprism/issues/1326

**Comment by lakemike** [comment]
It's only happening with this particular jpeg, just one file from 2007, out of 20000 overall. I'll come back with logs asap.

**Comment by lakemike** [comment]
Ok, I've done another test run. It's one of the files in the directory "20070314-Lisa". Haven't confirmed it's the one mentioned last in the log file. But it probably is.

Log file:
`INFO[2021-08-11T21:42:10+02:00] media: 20070324-2037-IMG_3909-nre.jpg was taken at 2007-03-24 20:37:26 +0000 UTC (meta) 
DEBU[2021-08-11T21:42:13+02:00] index: image classification took 3.225761365s 
DEBU[2021-08-11T21:42:13+02:00] camera: cache hit for canon-digital-ixus-430 
DEBU[2021-08-11T21:42:13+02:00] lens: cache hit for 7-4-22-2-mm              
DEBU[2021-08-11T21:42:13+02:00] photo: changed title of pqxoxed3vml6ugxq to “Img Nre / 2007” 
DEBU[2021-08-11T21:42:13+02:00] index: updated yaml file 20070324-2037-IMG_3909-nre.yml 
INFO[2021-08-11T21:42:16+02:00] media: 7 thumbnails created for 20070324-2037-IMG_3909-nre [2.373282887s] 
INFO[2021-08-11T21:42:16+02:00] index: added main jpg file 20070314-Lisa/Druck/20070324-2037-IMG_3909-nre.jpg 
INFO[2021-08-11T21:42:16+02:00] index: skipped duplicate main jpg file 20070314-Lisa/Druck/20070326-1422-IMG_3919.jpg 
DEBU[2021-08-11T21:42:16+02:00] exiftool: extracting metadata from 20070314-Lisa/Druck/20070326-1422-IMG_3919_mod-nre.jpg 
DEBU[2021-08-11T21:42:16+02:00] index: 87df785857ab25810a4d55b25f69420fe98f2cac_exiftool.json created 
`

Looking at processes while the memory consumption is approaching 5 gigs:
1) with ps
`I have no name!@00086d4bc74e:/photoprism$ ps -eaf
UID        PID  PPID  C STIME TTY          TIME CMD
1000000      1     0  0 21:35 ?        00:00:00 bash /entrypoint.sh photoprism start
1000000     10     1  1 21:35 ?        00:00:06 photoprism start
1000000     18     0 99 21:35 pts/0    00:11:30 photoprism index
1000000    110     0  0 21:41 pts/1    00:00:00 /bin/bash
1000000    161   110  0 21:42 pts/1    00:00:00 ps -eaf
`
2) with top
`I have no name!@00086d4bc74e:/photoprism$ top

top - 21:43:18 up 34 days, 33 min,  0 users,  load average: 5.48, 5.48, 3.44
Tasks:   5 total,   2 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s): 38.7 us,  8.2 sy,  0.8 ni, 52.0 id,  0.2 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  15856.8 total,   1323.2 free,  11708.5 used,   2825.2 buff/cache
MiB Swap:  24473.6 total,  19061.0 free,   5412.6 used.   3331.3 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                              
   18 1000000   20   0 7231920   5.0g  35300 R  97.7  32.4  12:05.17 photoprism                                           
    1 1000000   20   0    4208   2988   2700 S   0.0   0.0   0:00.04 bash                                                 
   10 1000000   20   0 1532556  90024  27392 S   0.0   0.6   0:06.70 photoprism                                           
  110 1000000   20   0    4472   3744   3140 S   0.0   0.0   0:00.03 bash                                                 
  162 1000000   20   0    7092   3376   2840 R   0.0   0.0   0:00.00 top                                                  
`
This seems to indicate that it's "photoprism index", which consumes all the memory. Not exiftool etc.

**Comment by lakemike** [comment]
This is what exiftool says:
> ======== 20070326-1422-IMG_3919_mod-nre.jpg
ExifTool Version Number         : 12.16
File Name                       : 20070326-1422-IMG_3919_mod-nre.jpg
Directory                       : .
File Size                       : 403 KiB
File Modification Date/Time     : 2007:04:01 20:14:47+02:00
File Access Date/Time           : 2021:08:11 21:24:44+02:00
File Inode Change Date/Time     : 2021:08:09 18:01:09+02:00
File Permissions                : rwxrwxrwx
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Warning                         : IFD1 pointer references previous IFD0 directory
Current IPTC Digest             : ff5978eb5c164fa308177d41e817e08f
By-line                         : Picasa 2.0
Contact                         : <picasastamp/>.
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Image Width                     : 1278
Image Height                    : 1704
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 1278x1704
Megapixels                      : 2.2

Apparently, it's been written by Picasa at the time. And based on other files in the directory, I used Picasa for red-eye removal with this particular picutre.

**Comment by lastzero** [comment]
Can you send us a file for testing to hello@photoprism.app? Might be related to the go-exif issue mentioned above... It's a native go library, not Exiftool... What do you think @dsoprea? I have time for debugging this in detail when done with facial recognition.

**Comment by lakemike** [comment]
Excellent. I've sent it to you.

**Comment by lastzero** [comment]
Reading Exiftool's warning message, it becomes clear why `go-exif` may get stuck in a loop extracting all data:

```
$ exiftool -g yourfile.jpg 
---- ExifTool ----
ExifTool Version Number    : 12.16
Warning                    : IFD1 pointer references previous IFD0 directory
```

See https://exiftool.org/forum/index.php?topic=3524.0

Money quote:

> **Question 1:  What does this mean?  (Sorry I could not find it anywhere.)**
>
> It means that the EXIF information is corrupted, and some may have been lost.

Looks very much like the same issue as in #1326, same warning there.

**Comment by lastzero** [comment]
I'll close this as duplicate. Please use the existing issue #1326 to comment and stay updated.
