### ISSUE TITLE
Darktable 3.6.0

### ISSUE THREAD

**Issue by Mikayex** [photoprism/photoprism#1464]
Darktable 3.6.0 was released on the 3rd July.

I updated my desktop Darktable to 3.6.0 so edited images' XMP uses new modules and options.
As the Darktable shipped with Photoprism is older (3.4.1 on preview container), it doesn't use my XMP file with my edits when generating the thumbnail, it shows me the image as if no edits were made.

As a workaround I'll try to use the host Darktable (3.6.0 on Archlinux) with `PHOTOPRISM_DARKTABLE_BIN` and mounting the right volumes at the right place...

**Comment by lastzero** [comment]
Where do we get maintained packages for Ubuntu 21.04 from, also for ARM64?

**Comment by Mikayex** [comment]
Hum... Yes didn't thought about ARM64... Otherwise https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable would provide AMD64 packages.

I'll try to use host's darktable and if I can't get it works, I'll downgrade my Darktable until it's supported in Ubuntu repos.

**Comment by Mikayex** [comment]
For anyone interested I could upgrade Darktable by making a Dockerfile next to the docker-compose.yml with this content:
```Dockerfile
FROM photoprism/photoprism:latest

RUN echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_21.04/ /' > /etc/apt/sources.list.d/graphics:darktable.list && \
    curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/xUbuntu_21.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/graphics_darkta>
    apt update && apt-get -qq install darktable
```

And replacing `image: photoprism/photoprism:latest` with `build: .` in the docker-compose.yml.
