### ISSUE TITLE
Cant upload from photosync

### ISSUE THREAD

**Issue by darkwolfgar** [photoprism/photoprism#1472]
I'm getting an error on photosync that says "operation couldn't be completed. (kCFErrorDomainCFNetwork error 303)."

In the Logs in PhotoPrism it sees the connection
OPTIONS /photoprism/originals (200) [1.321917ms]"
"http: MKCOL /photoprism/originals/Iphone (200) [1.402597ms]"
"http: MKCOL /photoprism/originals/Iphone/Recents (200) [1.653328ms]"
"http: PUT /photoprism/originals/Iphone/Recents/IMG_5681.MOV (200) [1.479953ms]"

Nothing ever shows up in photoprism, not sure what I am doing wrong. I tried multiple directories including /originals/ and /import/

**Comment by lastzero** [comment]
HTTP path probably should be `/originals/`, not `/photoprism/originals/`. You may also want to check file system properties and permissions. Are you using PhotoPrism in public mode?

**Comment by graciousgrey** [comment]
@darkwolfgar any update on this?

**Comment by graciousgrey** [comment]
Closed due to inactivity.
