### ISSUE TITLE
Invalid destination on WebDAV import

### ISSUE THREAD

**Issue by justmytwospence** [photoprism/photoprism#1473]
When I upload a photo to the import directory via WebDAV, it does not import into the originals directory. The debug logs look like this:

```
photoprism    | [GIN-debug] redirecting request 307: /import/ --> /import/
photoprism    | time="2021-08-13T03:39:35Z" level=debug msg="http: PROPFIND /import/ (401) [107.079µs]"
photoprism    | time="2021-08-13T03:39:35Z" level=debug msg="http: PROPFIND /import/ (207) [309.695µs]"
photoprism    | time="2021-08-13T03:39:35Z" level=debug msg="http: PROPFIND /import/ (207) [650.9µs]"
photoprism    | time="2021-08-13T03:39:35Z" level=info msg="webdav: PUT /import/IMG_20210812_213930.jpg.tacitpart"
photoprism    | time="2021-08-13T03:39:35Z" level=debug msg="http: PUT /import/IMG_20210812_213930.jpg.tacitpart (201) [585.452663ms]"
photoprism    | time="2021-08-13T03:39:35Z" level=debug msg="http: PROPFIND /import/IMG_20210812_213930.jpg.tacitpart (207) [333.691µs]"
photoprism    | time="2021-08-13T03:39:36Z" level=error msg="webdav: “webdav: invalid destination” in MOVE /import/IMG_20210812_213930.jpg.tacitpart"
photoprism    | time="2021-08-13T03:39:36Z" level=debug msg="http: MOVE /import/IMG_20210812_213930.jpg.tacitpart (400) [170.46µs]"
photoprism    | time="2021-08-13T03:39:36Z" level=info msg="webdav: MOVE /import/IMG_20210812_213930.jpg.tacitpart"
photoprism    | time="2021-08-13T03:39:36Z" level=debug msg="http: MOVE /import/IMG_20210812_213930.jpg.tacitpart (201) [424.61µs]"
photoprism    | time="2021-08-13T03:39:36Z" level=debug msg="http: PROPFIND /import/IMG_20210812_213930.jpg (207) [175.992µs]"
```

If I force an import manually with `docker exec -it photoprism photoprism import`, it works.

I tried increasing `PHOTOPRISM_AUTO_IMPORT` to 10, but that did not affect anything.

Any ideas what's going on?

**Comment by justmytwospence** [comment]
I realize now that 10 is actually an extremely low value for auto import, but I've tried others including the default 15 minutes and still the same thing. I've tried blowing away the import and originals directories and starting over completely from scratch and the same thing happens.

**Comment by lastzero** [comment]
Maybe try PhotoSync? It's already past midnight over here, but a quick Google search shows other users may have similar issues with FolderSync:

- https://github.com/haiwen/seafdav/issues/15
-  https://forum.seafile.com/t/webdav-not-syncing-with-foldersync-anymore-with-6-0-3/593
- https://github.com/owncloud/core/issues/21486
- https://groups.google.com/g/tacitdynamics/c/aoxsUG8L_sY

**Comment by justmytwospence** [comment]
Thank you, switching to PhotoSync fixed the issue. I also had to create the directories manually before running `docker-compose up`, otherwise I had permissions issues on the directories created automatically.

**Comment by rodrigolopezguerra** [comment]
I think this error is due to selected by default option in folderSync "use temporary file", that adds .tacitpart extention to the file.
If you uncheck that option , everything will work just fine.
