### ISSUE TITLE
Certain jpgs indexed into originals not appearing anywhere in photoprism

### ISSUE THREAD

**Issue by lukeski14** [photoprism/photoprism#1476]
Hi,

I have recently uploaded and reindexed a batch export of my Google Photos to Photoprism. I'm running on the unofficial FreeBSD port of Photoprism.

There are a batch of recently taken jpgs from my phone that don't seem to appear anywhere in the UI. I've looked in the Calendar, Folder, and Library > Originals. These photos are in the originals/2021/08 directory, so I'm not sure why they aren't appearing anywhere. I've turned off the low quality filter, though they're HD photos taken from my phone. I've had a little difficulty figuring out how to best turn off the nsfw options on FreeBSD, but these are just regular portraits so I don't think they'd be flagged NSFW. Any new photos from my phone appear just fine.

If anyone knows how to permanently turn off the nsfw flags for FreeBSD (running Photoprism as a service), that would be helpful in completely eliminating possible issues.

Any help would be appreciated, I'm not sure of any other ways to debug this.

**Comment by lukeski14** [comment]
I was able to set the proper variables persistently for the NSFW filters. I reindexed my 2021/08 originals folder and those images still don't appear. Not sure what else to troubleshoot.

**Comment by graciousgrey** [comment]
If your photos show up in Library > originals they have been indexed. Your photos might be stacked with other photos (see https://docs.photoprism.org/user-guide/organize/stacks/). Do you find them within Stacks?

**Comment by lukeski14** [comment]
Thanks so much for this. They were not in stacks, but they were in Archives for some reason. Took them out of there and everything is functioning again.
