### ISSUE TITLE
failed to create shim: OCI runtime 

### ISSUE THREAD

**Issue by shaun-ba** [photoprism/photoprism#1479]
ERROR: for photoprism  Cannot start service photoprism: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container iniCreating mariadb    ... error

So I'm trying to install on an LXC container, will this not working with Docker?

**Comment by lastzero** [comment]
That has something to do with the host OS. Other users reported this before, and then they got it working. There are quite a lot of hits when googling the error, e.g. https://dev.to/aheissenberger/docker-fails-with-oci-runtime-create-failed-4e3l.

**Comment by lastzero** [comment]
Happy to add the answer to our FAQs if you figure it out!

**Comment by lastzero** [comment]
Since it may only affect MariaDB, you may also try an alternative Docker image for it or MySQL 8+

**Comment by graciousgrey** [comment]
@shaun-ba any update on this?

**Comment by graciousgrey** [comment]
Closed due to inactivity.
