### ISSUE TITLE
GET /api/v1/photos takes multiple seconds

### ISSUE THREAD

**Issue by dominikholler** [photoprism/photoprism#1481]
On an instance with slightly more than 240k photos, the  GET /api/v1/photos slows down sometimes.
This make the web UI annoying to use.

210523-b1856b9d-Linux-x86_64
```
time="2021-08-16T18:18:13Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [37.177796ms]"
time="2021-08-16T18:18:14Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=60&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [39.263778ms]"
time="2021-08-16T18:18:14Z" level=debug msg="http: GET /api/v1/photos?count=3333&offset=0&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [146.929651ms]"
time="2021-08-16T18:18:15Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=120&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [36.623387ms]"
time="2021-08-16T18:18:17Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=180&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [31.084409ms]"
time="2021-08-16T18:18:18Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=240&album=aqsqcgp93n6yhnfr&filter=&merged=true&country=&camera=0&order=oldest&q= (200) [27.972575ms]"
time="2021-08-18T07:24:15Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (401) [14.468024ms]"
time="2021-08-18T07:24:54Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [20.929442098s]"
time="2021-08-18T07:25:00Z" level=debug msg="http: GET /api/v1/photos?count=360&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [5.058197025s]"
time="2021-08-18T07:25:21Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [5.236193485s]"
time="2021-08-18T07:25:28Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=60&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [6.588991117s]"
time="2021-08-18T07:25:28Z" level=debug msg="http: GET /api/v1/photos?count=360&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [6.728362934s]"
time="2021-08-18T07:25:45Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=120&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [4.774521694s]"
```

longer extract from the log: https://datadrop.org/f/4c8b233a87ae4037a35b/?dl=1

**Comment by lastzero** [comment]
Does it improve when you use `order=added` instead of `newest`?

Taking a look at database query optimization after completing the tasks we are working on right now, see roadmap. From my experience, MySQL often does stupid things when queries get more complex. Doesn't mean our implementation can't be improved, there should be an issue for this already.

It's hard to optimize a database for a large number of different use cases. Sorting in particular can make a major difference. It may help to increase database caches for now, or use an SSD (if not the case yet).

**Comment by graciousgrey** [comment]
I added this to the scope of https://github.com/photoprism/photoprism/issues/1438

**Comment by dominikholler** [comment]
> I added this to the scope of #1438

#1438 sounds great. It reflects my intention.

**Comment by dominikholler** [comment]
> Does it improve when you use `order=added` instead of `newest`?
> 

Yes, in a small check [1] the request improved from an average of 2.7784 seconds to 0.57389 seconds.

[1]  https://github.com/dominikholler/photoprism-python-sdk/blob/main/examples/list_photos.py

> Taking a look at database query optimization after completing the tasks we are working on right now, see roadmap. From my experience, MySQL often does stupid things when queries get more complex. Doesn't mean our implementation can't be improved, there should be an issue for this already.
> 
> It's hard to optimize a database for a large number of different use cases. Sorting in particular can make a major difference. It may help to increase database caches for now, or use an SSD (if not the case yet).
I use HDD for the db. (I just have SSD for the photoprism thumbnail cache.)
I added `-innodb-buffer-pool-size=1024M` without noticing an improvement. Also the performance seems to be limited by cpu, because mysql process is eating a lot cpu and nearlt no waiting on io.
