### ISSUE TITLE
It would be nice to have a select all button in the viewer.

### ISSUE THREAD

**Issue by ddyykk** [photoprism/photoprism#1482]
When I try to organize the pictures, one frequent action is to label some of them. When I need to select all files in one album/folder, it is nice to have a "select all" button. Thanks.

**Comment by graciousgrey** [comment]
With infinite scrolling, selection length is not defined. Has been discussed in previous GitHub issues before. Selecting all could possibly mean millions of pictures. See https://github.com/photoprism/photoprism/issues/272

You can use a shift-click to select multiple photos, does that help?

**Comment by ddyykk** [comment]
Yes, using shift is helpful, thanks.

**Comment by hartraft** [comment]
The shift click method works well on desktop but is there a way to do this on mobile?

**Comment by lastzero** [comment]
Long touch.
