### ISSUE TITLE
UX: Keep selection so that it can be added to multiple albums

### ISSUE THREAD

**Issue by ddyykk** [photoprism/photoprism#1483]
My situation is I need to label some photos on multiple albums/folders, but after I put them in one album they will be de-selected, is it possible to keep them selected? Thanks.

**Comment by graciousgrey** [comment]
Currently photos are de-selected after the following operations:
- Archive
- Add to album
- Private

Photos are stay selected after:
- Download
- Edit
- Share

If you  want to label photos from different albums and then put them into one album, you can do the following:
- Select all photos from different folders/albums you want to label (If you select photos in one album/folder and then navigate to another album/folder your selection stays)
- Click edit on the context menu and label all selected photos
- After editing click "add to album" to add all those photos to a new album

**Comment by lastzero** [comment]
Looks like a potential batch edit use case: #271

**Comment by ddyykk** [comment]
Thanks, I didn't go through all the issuses.

**Comment by graciousgrey** [comment]
I will close this issue as it is going to be solved by batch edit.
