### ISSUE TITLE
API: Improve Upload Error Logging

### ISSUE THREAD

**Issue by titivermeesch** [photoprism/photoprism#1486]
When trying to upload images in RAW format (ARW) I'm get 400 "Invalid request" back:

<img width="893" alt="Screenshot 2021-08-19 at 10 36 13" src="https://user-images.githubusercontent.com/12189066/130036685-807d0ade-f96e-49ca-9a07-9abdc80a4a35.png">
<img width="335" alt="Screenshot 2021-08-19 at 10 36 23" src="https://user-images.githubusercontent.com/12189066/130036704-36f8c6c5-74a1-4580-a29c-1032f0e9d09c.png">

This did not happen a few days back.

My setup is as following:

- I have a raspberry PI connected to my local network
- Photoprism volumes redirect to an external hard drive

docker-compose:
```
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/mnt/backup/fotos:/photoprism/originals/hdd"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "/mnt/photoprism-storage/storage:/photoprism/storage"
```

The DB driver is SQLite, the rest is all default setup

**Comment by lastzero** [comment]
I've just implemented better logging for that. If an upload fails with error 400, it's either invalid encoding (e.g. incomplete request data) or a file system issue, like when the folder could not be created (e.g. bad permissions) or the file not saved (e.g. no storage left on device).

**Comment by titivermeesch** [comment]
This indeed solves the issue. My case was no storage left due to some docker images.

Thanks!
