### ISSUE TITLE
UX: Link to photo on map from fullscreen/edit view

### ISSUE THREAD

**Issue by leepfrog-ger** [photoprism/photoprism#1495]
Thanks for this great project! 

I am currently playing around with test data in a test instance and wondered if there is any way to jump to the location (on the world map) of a photo from the "photo view" (the view that has the photo in full screen), or at least from the details of that photo.

In the "Catalog View" this is already possible via the location tag below each image and a click on this takes you to the world map centered view around the particular shot.

It would be great to have that option also in the "photo detail" view (e.g. as link in the footer or in the edit view where the lat/long is displayed).

The use case would be going through a larger album in the fullscreen/slide show view and being able to quickly view the location where the image was taken without going back to the catalog view, searching for the image that was last viewed and go from there.

**Comment by graciousgrey** [comment]
Just found the ticket we already have for this request: https://github.com/photoprism/photoprism/issues/797
