### ISSUE TITLE
Password seem not support special char

### ISSUE THREAD

**Issue by banshee1971** [photoprism/photoprism#1499]
I try (as an example.. this is not my password) this : Swewe123$
but can't loggin the Photoprism. They i shutdown the Docker, change the value for : Swewe123
and after restart... it work... i can login using : admin  .... Swewe123

Special Char seems not working at all... Anyway, not realy a problem for me, as i don't expose Photoprism to outside my network..

Having also the ability to create multiple user will be great.. so we use the Admin account to set everything, then use another account for browsing, import,...

**Comment by lastzero** [comment]
Using the environment variable? You may need to escape it.

**Comment by banshee1971** [comment]
I change it from the Web Interface.. it's working (i can add symbol now).
Do you suggest i remove the Environment variable after i change it ? (what happen when i reboot the docker if the Environement variable still there ?)

**Comment by lastzero** [comment]
No, you can keep the environment variable. Just keep in mind $ is a special character there, symboling e.g. another variable. You need to use quotes " and escape it:

https://stackoverflow.com/questions/40619582/how-can-i-escape-a-dollar-sign-in-a-docker-compose-file
