### ISSUE TITLE
Videos: Add .mp to known file extensions

### ISSUE THREAD

**Issue by domharrington** [photoprism/photoprism#1501]
After a recent index of another batch of photos, I've started getting this warning in the Library page:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/848223/131232241-ff6e295b-9e2b-43d8-93d5-d2fbdbfa1ae6.png">

Going to Library -> Hidden I see lots of files without thumbnails:

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/848223/131232246-ef1cf7ab-bf23-47ad-9ce3-ee6705945537.png">

When I click on the top left one, it does actually play a video (which I think is a motion picture). The same static picture is also present in my library, but it's not marked as a motion picture. If I go and find that picture in the library, it has a filename of "Photos from 2021/PXL_20210715_220515448.MP.jpg". 

Navigating to the filesystem and doing a search for this, I find the following files:

```sh
$ ls Photos\ from\ 2021/PXL_20210715_220515448*
Photos from 2021/PXL_20210715_220515448.MP          Photos from 2021/PXL_20210715_220515448.MP.jpg      Photos from 2021/PXL_20210715_220515448.MP.jpg.json
```

Opening the .MP file in VLC confirms that it is indeed the file that's hidden. It seems as though it somehow got unlinked or detached from the photo that's searchable. Is there anything I can do here to reattach these hidden images? Any idea how it may have gotten into this state?

Side note: I've never heard of an .MP file before - this was taken using a Google Pixel 2 XL and exported from Google Photos using Takeout. VLC confirms that it is an MP4 file though! Any help would be greatly appreciated.

**Comment by lastzero** [comment]
Might be because MP is not a standard extension for videos (from what I know)? Does it work when using mp4 as extension?

**Comment by domharrington** [comment]
Should I try and rename one of them, then trigger a an index of the album folder? Will that cause it to get picked up, or is there something else i should do?

**Comment by domharrington** [comment]
Seems like it was maybe introduced as a file extension in Google Camera v7.5 with Android v11

> Motion Photos drop “MVIMG” for a simpler “MP”

https://9to5google.com/2020/08/20/google-camera-7-5-pxl/

But it's definitely a bit strange that this is the actual file extension, and not something like `PXL_20200820_142352990.MP.mp4`

**Comment by domharrington** [comment]
Adding an .mp4 extension onto the end of the .MP file `mv "Photos from 2021/PXL_20210715_220515448.MP" "Photos from 2021/PXL_20210715_220515448.MP.mp4"` and triggering a reindex seems to have done the trick! My hidden count has gone down by 1, i'm now going to try and do it for the rest of them.

I'm surprised no one else has encountered this... would it be possible to add support for this to happen automatically?

**Comment by domharrington** [comment]
If anyone else has this issue, you can rename all of the files with the following command to add .mp4 to the end:

```sh
find . -name "*.MP" | xargs -I {} mv {} {}.mp4
```

This appears to be reindexing properly and resolving the hidden files!

**Comment by lastzero** [comment]
We'll add it to the next release.

**Comment by domharrington** [comment]
Lots of them still appear to be stuck in the hidden view, and now it shows this when I open it:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/848223/131239086-2512eb68-817a-4acf-9330-44695f726505.png">

The ajax request still shows the .MP file:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/848223/131239093-d9afe397-ce8e-429b-bc92-4f3edf9309fa.png">

How can I clear out these photos from the db that no longer have files on disk any more?

**Comment by lastzero** [comment]
Try the photoprism purge command in a terminal.

**Comment by domharrington** [comment]
@lastzero 🙏 thank you! That did the trick for ~500 of them (out of 900). I'll try and figure out what's going on with the remaining 400 tomorrow. I'm going to sign up to Patreon tomorrow to donate to your project as well. Thanks again.

**Comment by domharrington** [comment]
Running purge again cleared out another 400, leaving only 5 remaining. Hopefully I can figure these out separately.

**Comment by CComparon** [comment]
> We'll add it to the next release.

I also have .MP files produced by my Google Pixel 6a phone. Photoprism still seems to consider this extension as hidden files.

The first video track is a short video taken by the phone, and there's a second track with the best still image IIUC.
Ffmpeg natively supports this format so might as well add it to the non-hidden list of formats?

**Comment by graciousgrey** [comment]
I just tested this and for me .MP files could be indexed as videos and .MP.jpg files could be indexed as live photo without issues. 

Can you reproduce the problem with your file on our public demo or [send us a sample file](https://www.photoprism.app/contact#file-samples)?
