### ISSUE TITLE
Question new development: Display all photos with the same person/face

### ISSUE THREAD

**Issue by dml33** [photoprism/photoprism#1502]
Hi,
I am using the [demo](https://demo.photoprism.org/) from time to time to see new developments, and the people recognition function is going on very well! 👍 

I notice that there is People section for each photo with the faces which have been detected. This face could belong to that actual photo or to another with the "same" face. Awesome! And, you can set the name to that person.

But, I do not see (or find) a way to just click on a person/face and all the photos where that person appears are listed. Just as Google Photos style.
Is this planned or just I cannot find it?

Thanks again for this great app!

**Comment by graciousgrey** [comment]
Facial recognition is currently in development. Once we are done with the recognition and clustering part we will work on the UI. This will include a people section where you can view all photos of a person :)
