### ISSUE TITLE
List of photoprism exit error codes

### ISSUE THREAD

**Issue by mihha** [photoprism/photoprism#1505]
Hi,

I am using Cronicle task scheduler and runner (https://github.com/jhuckaby/Cronicle) to execute cron job in PhotoPrism

Basically, I am using it to execute the following every hour

```
#!/bin/sh

cd /root/photoprism
docker-compose exec -T photoprism photoprism index
```

Sometimes, this script returns back some error codes as a result

For example, the last error code was

` Error 137: Script exited with code: 137: time="2021-09-01T19:00:05Z" level=info msg="indexing originals in /photoprism/originals"`

I believe that this error 137 is coming from PhotoPrism

Do you have a list of script error codes with the explanation for each of them?

**Comment by lastzero** [comment]
Nope, it's coming from Docker... Out of memory.

https://www.google.com/search?q=error+137+docker&oq=error+137

**Comment by mihha** [comment]
Thank you for your prompt reply and correct information

I know what to do now 😀
