### ISSUE TITLE
Support images with ProjectionType: transverse-cylindrical 

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1508]
Acceptance Criteria:

- [x] Add transverse-cylindrical as possible projection type
- [x] Adapt db to allow projection types with more than 16 character
- [x] Add Unit Test

**Comment by lastzero** [comment]
Increased the limit to 32 characters based on https://en.wikipedia.org/wiki/List_of_map_projections

Longer strings (and those containing non-ascii characters) will now also be trimmed, just in case. Should implement this for other type strings as well.
