### ISSUE TITLE
Labels: Disable client-side capitalization

### ISSUE THREAD

**Issue by sehv** [photoprism/photoprism#1509]
The auto-capitalization system handles labels like "NYC, NY" or "London, UK" in a less than ideal way, turning them into "Nyc, Ny" and "London, Uk". An option to always preserve case would be great, or failing that maybe just a check to see: does this text look like a state or country code? If so, preserve the original case.

**Comment by lastzero** [comment]
Thanks! Makes sense. We have that already for other captions, not sure why it's not used here (yet).

**Comment by lastzero** [comment]
Note sure why we he the client-client capitalization in place, disabling it should fix the issue. It wasn't very sophisticated for sure. You can test it when the next Development Preview build is available e.g. using our public demo.
