### ISSUE TITLE
Preserve explicitly set photo titles

### ISSUE THREAD

**Issue by sehv** [photoprism/photoprism#1510]
Adding a label to a photo often changes the title of the photo. This works fine for photos where the title is generated dynamically from the date and labels. If the user explicitly sets their own custom title, however, ideally the app would preserve that title when a new label is added.

**Comment by lastzero** [comment]
The app should never change a user edited title. How, when and where did that happen?

**Comment by sehv** [comment]
It seems to be somewhat inconsistent, still trying to wrap my head around how exactly the title setting works. Even in the case of the dynamically generated titles, sometimes adding a label sets the title to the new label, other times it changes it to a different label that was already in the list, sometimes it doesn't change the title at all. User-edited ones don't change very often, but I ran into that situation about half a dozen times while doing some uploading and organizing on around 500 photos this week.

I need to upload a bunch of dummy photos this weekend that I can experiment on without messing up my real albums and try to nail down exactly what circumstances cause a manual title to change.

**Comment by lastzero** [comment]
Let us know how to reproduce it, and we'll fix it 👍

**Comment by lastzero** [comment]
I'll close this due to inactivity.
