### ISSUE TITLE
Idea: Select and Sort by Favorites

### ISSUE THREAD

**Issue by ludditus-RPI** [photoprism/photoprism#1514]
As a user, I would like to select a group of photos from an album (or folder, or month) based on whether the favorite (heart) has been clicked.  Currently the UI requires me to click on favorited photos, one-by-one.

Solution 1: Add a "Select by ❤" function to the top menu in Album, Folder, and Calendar views, which will select all favorited photos from the currently visible set.

Solution 2: Add a "Sort by ❤" function to facilitate easier batch selection of favorited photos from an album/folder/month.

Desired workflow: I add a group of pictures to an album for my spouse to review. She clicks on Favorite for the photos she wants to include in a picture book. I select those photos to download or upload to WebDAV.

Keep up the great work! PhotoPrism has quickly replaced my aging Picasa library for family photo management.

**Comment by lastzero** [comment]
You can sort by relevance, which will show favorites first.

**Comment by ludditus-RPI** [comment]
Thanks, that helps. Is there a way to add/remove the favorite status for a
selected group of pictures?

**Comment by lastzero** [comment]
Batch edit is on our roadmap. We could also add a toggle favorite button to the context menu (bottom right), just pretty full already. What's the point in selecting photos and then like them instead of instantly changing their status by pressing the heart button on the preview or in the full screen viewer?

**Comment by ludditus-RPI** [comment]
The specific reason I had in mind would be to use the favorite status as a
temporary filtering mechanism for a subset of photos. Somebody else will be
assigning the favorite status in a different browser session.  I start with
a large group of photos, have somebody else review and assign the favorite
status, then I select the favorited photos and download those to send to a
different service (Snapfish).  After I'm done with that I'd like to be able
to quickly deselect the favorite status from that group of photos so that I
can repeat the process again, later.

Being able to do it as part of the batch edit function would be helpful.
Another option with the same outcome would be to add a custom label (e.g.
"8Sep21Upload") to a selected batch of photos, and then select photos with
that label in a different browser session.

**Comment by graciousgrey** [comment]
@ludditus-RPI thanks for the explanation :) I guess your workflow will be covered, once we have batch edit https://github.com/photoprism/photoprism/issues/271 implemented? In this case we can close this ticket.

**Comment by ludditus-RPI** [comment]
Agreed ... a one-click method to select favorited pictures from a group would still be nice, but the method you suggested of sorting by relevance and then selecting the consecutive range of favorited photos is sufficient for now.
