### ISSUE TITLE
Edit multiple photos at once

### ISSUE THREAD

**Issue by dav3516** [photoprism/photoprism#1515]
Hello ; 
I'm actually looking for a way to to add location to a lot of picture ; i mean select a hundred of pictures and add the location to all of them in once ; i actually found the way to do it by select picture one by one and add GPS coord. at each picture but this will took me a lot lot of time ^^
Or the way to add location to a folder ?  and then see it on the map
Thx for answer !

**Comment by lastzero** [comment]
Batch edit is on our roadmap. Right now, you could use external (Exif) tools to update GPS coordinates in many files at once.
