### ISSUE TITLE
Does “PHOTOPRISM_DISABLE_FFMPEG” disable the thumbnail generation?

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#1516]
If I remember correctly, FFMPEG is used to generate thumbnails of videos.

Can I set `PHOTOPRISM_DISABLE_FFMPEG: "true"` in my config and still have thumbnails generated?

**Comment by lastzero** [comment]
It will also disable video thumbs unless you manually create JPEG sidecar files for your videos.

**Comment by alexislefebvre** [comment]
Thanks for your answer, I suggest to explain it in the documentation: https://github.com/photoprism/photoprism-docs/pull/85

**Comment by lastzero** [comment]
On vacation until next week. You're welcome to send a pull request that improves our docs. 👍
