### ISSUE TITLE
Backup: albums/folder/*.yml created no matter they are changed or not 

### ISSUE THREAD

**Issue by lacrimal** [photoprism/photoprism#1521]
Hi,
I'm using periodically cron command for photoprism backup:
`10 1,13 * * * /usr/bin/podman exec photoprism_photoprism_1 photoprism index && /usr/bin/podman exec photoprism_photoprism_1 photoprism backup -i -a -f /photoprism/storage/data.sql`
Now yml backup files in albums/folder/ are refreshed (modify date changed) no matter they are exactly same files or not.

Since I'm using brorg backup and it base on modify date change - I'm creating backup of exactly same files ever day.
I'm wondering is there a chance to change this behavior by not updating same files or maybe creating single backup file for that files ?

**Comment by lastzero** [comment]
They are automatically updated when needed if you don't run the backup command with `-a`. The command will always create files for all albums. Otherwise it would have to open the old file and compare it, which is extra work and probably slower.

**Comment by lacrimal** [comment]
Hi,
did not seen this kind of explanation in docker compose description or https://docs.photoprism.org/user-guide/advanced/backups/ 
I will try without -a
Thanks

**Comment by lastzero** [comment]
You're welcome to help improving our docs.

**Comment by lacrimal** [comment]
Hi, 
Tried with removed ```-a``` option but files were refreshed every 15 minutes, found and disabled backup option from GUI so now they are steady.
Can I ask one more thing:
Is yml backup just another convenient option to backup photoprism, and I not need it if I'm crating sql database backup?

**Comment by lastzero** [comment]
Exactly, if you have the database and know how to restore it, you don't need YAML files.

**Comment by lacrimal** [comment]
Thanks, now it is clear - I will try to put it in doc shortly - it is great advantage to have two complete backup options and I think - it should be nicely mentioned.
Not said before - Great Work !
