### ISSUE TITLE
Thumbnails: Support color spaces such as P3 for more accurate colors

### ISSUE THREAD

**Issue by samhinshaw** [photoprism/photoprism#1522]
_Disclaimer: This is unfamiliar territory for me, so please bear with me if any of my terminology or assumptions are incorrect._ 

## Issue
Currently, the thumbnails for many of my photos look washed-out. When I download the originals, the file does not appear washed-out.

## Expected (Original)
![flower-resized](https://user-images.githubusercontent.com/14186005/133008950-f373c8c2-98c9-4b13-9a70-d235c875fbe3.jpg)

## Actual (Thumbnail)
![flower-photoprism-thumbnail](https://user-images.githubusercontent.com/14186005/133008958-2f07ab5b-fd94-4d9a-bef1-06dc0415a540.jpeg)

## Steps to Reproduce
1. Take a photo on an iPhone 7 or older (I used an iPhone 12 Pro). Take a photo of something very colorful for more a more obvious effect.
2. Import the photo into Photoprism.
3. View the photo in the photoprism gallery. (Tested with an M1 MacBook Air with Chrome v93 and an iPhone 12 Pro using Safari).

## Notes

After some digging, I have traced this back to the fact that iPhone photos are saved with a [Display P3 color profile](https://en.wikipedia.org/wiki/DCI-P3#System_colorimetry), but thumbnail generation strips the color profile. When these thumbnails are viewed, the default sRGB color profile is assumed, making the image appear washed-out. 

I tracked this down via this issue in the image processing library photoprism uses: https://github.com/disintegration/imaging/issues/67. This appears to be an underlying issue with Go's image/jpeg library, which strips the color profile when encoding images: https://github.com/golang/go/issues/23936

Importantly, the HEIC -> JPEG conversion that photoprism does on originals is not affected, so the .jpg downloaded alongside the .heic original is unaffected. (Based on my cursory searching, this is because it uses the `heif-convert` tool rather than the `imaging` library).

Now, I bring this up here, rather than adding on to the golang/go repository issue because I do not know Go, and do not think I would be able to help there at all! However, perhaps some of the talented Go developers here can help contribute to that issue and resolve this one. Or perhaps there is a simpler workaround that could be implemented at a higher-level here.

Please let me know if there is anything else I can do to assist.

## Helpful Reading

* https://stackoverflow.com/questions/47550838/unexpected-inaccurate-image-color-conversions-in-go
* https://stackoverflow.com/questions/27958452/read-write-icc-profile-in-images-with-go-and-opencv

**Comment by lastzero** [comment]
Thanks for the detailed analysis! You're right in that PhotoPrism relies on libraries that don't support custom color spaces as [used by Apple](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/). So it's not working as implicitly expected by users, but it's not an advertised feature either. Therefore, I wouldn't call it a bug but a limitation. While we can manually convert the colors, it probably has a performance impact not all users might accept. Happy to take a more detailed look when we have time. Right now, we are focusing on multi user support.

**Comment by lastzero** [comment]
Found the original issue: #1474

Should merge and close one of them...

**Comment by lastzero** [comment]
Seems fixed with our latest changes!?

![DisplayP3](https://user-images.githubusercontent.com/301686/145341747-4a0e7bd1-56c1-4d0c-a234-1a847afd6be8.png)
