### ISSUE TITLE
Mark a label as private

### ISSUE THREAD

**Issue by khenderick** [photoprism/photoprism#1528]
Currently photos can be added to albums for easy navigation. Folders can also be used, representing the physical structure. Since labels can be added to photos as well, these labels can also be considered some kind of "virtual album"; you select a label, and you can browse all photos having that label.

It would be a nice feature to mark a label as private. 

Application behaviour:
* A label marked as private is not shown. A user who cannot see private photos/labels would not even know that label exists.
* When a user is allowed to see private photos/labels, the label is visible and can be selected/browsed.
* Any photo with one or more private labels is also considered private, and behaves as if the photo itself was marked private

User benefits:
* Currently a user has to both add labels (what's on the photo), and consider who can see the photo (mark as private or not). With this feature, a user can just focus on what is on the photo.
* If situations change, a user can just mark a label as not private, or vice versa. For example, by default, no need to set any label as private, but when grandma is about to visit and the user wants to show her the album "holiday 2021", the user can mark the label "party" as private and without any fear show grandma the holiday photos.
* An extended implementation of this feature could even mark labels private for a given user.

**Comment by graciousgrey** [comment]
Related to: #480

**Comment by graciousgrey** [comment]
I added this to the acceptance criteria of https://github.com/photoprism/photoprism/issues/480
