### ISSUE TITLE
Discover: Display a random set of pictures

### ISSUE THREAD

**Issue by tonydub** [photoprism/photoprism#153]
Hi,

We could rediscover and enjoy memories you haven't seen in years by displaying a random "sample" of images with a new "Random" option among the possible choices in "Sort By" list.

**Comment by lastzero** [comment]
Great idea! Since we still change the database and index a lot, we don't test with many pictures - but for large collections, a random view makes sense.

**Comment by tonydub** [comment]
Glad to see how this project will evolve.

**Comment by lastzero** [comment]
Our idea is to add a "Discover" area where you can find photos by similarity, by color, by season or just random. This is a very first draft:

![Screenshot 2019-12-29 at 15 00 27](https://user-images.githubusercontent.com/301686/71557845-2aabba80-2a4c-11ea-9371-a740cfc28051.png)

Adding a random option to the regular search might turn out to be tricky as it needs to work together with the other filters and with all database backends. When doing a database search, you want to make the result set as small as possible to fit everything in memory. So first selecting as much as possible just to randomly change position (basically removing results from the top) is not a good strategy. In fact you expect a different result every time you click the search button plus when you scroll down to load additional results, photos must not repeat. Maybe easier done in Go and then just tell the db to return the randomly selected IDs, although I didn't spend much time investigating other solutions just yet (given the amount of other work we have to do).

**Comment by lastzero** [comment]
Added more tabs to get a better impression:

![Screenshot 2019-12-29 at 15 52 05](https://user-images.githubusercontent.com/301686/71558402-2e8f0b00-2a53-11ea-9a1c-5f961acd383e.png)

**Comment by lastzero** [comment]
FYI: Discover area probably won't be part of the release as we received very little feedback and no pull requests so far.

**Comment by JamesSwift** [comment]
Would it be possible to implement just the "random sort" option in search view as the discover feature is not going ahead? Even if it is "truly random" and not the "pseudo random" where we expect to always see different images. The idea of continually scrolling and seeing more and more random images would be great.

While assessing different solutions for self hosting photos I tried PhotoStructure. PhotoPrism is better and has a better roadmap IMO, but one thing I loved was that the home view of PhotoStructure defaulted to random. I found so many nice memories while trying it out.

**Comment by graciousgrey** [comment]
@bernsel feel free to reach out via hello@photoprism.app

**Comment by bernsel** [comment]
I have emailed you today.

**Comment by lastzero** [comment]
Thanks! Sorry for the wait, replied today :)

**Comment by daniele-athome** [comment]
An API for getting a random photo (or set of photos) would be nice too :-)

**Comment by banoslo** [comment]
Hi guys, love this project! Is this feature meant to be similar to Apple Photos "for you" tab or Google Photos "Highlights"? I am asking because that would be more sophisticated than just pure randomness. Best regards!

**Comment by graciousgrey** [comment]
@banoslo This feature is about showing a random sample of photos, which would be a nice feature for a landing page. 
In addition we already have some autogenerated albums "highlights" for users:

https://docs.photoprism.app/user-guide/organize/moments/

Other related issues:

https://github.com/photoprism/photoprism/issues/720

**Comment by lastzero** [comment]
In the last commit, we added support for a "random" sort order to our API. However, please note:

- This doesn't work well for infinite scrolling (or loading additional results), as results can repeat while others aren't displayed at all. So it's best to fetch everything you need with a single query.
- Files that belong to a batch are also not guaranteed to be returned together, as they otherwise would be (unless you sort by similarity and the files are not similar).

**Comment by yhslln** [comment]
Wow, happy to see this wonderfull feature go live.

**Comment by YuriShap** [comment]
Wow, thanks! So cool to watch photo library slide show using library/browse?order=random

**Comment by alexislefebvre** [comment]
> Wow, thanks! So cool to watch photo library slide show using library/browse?order=random

Thanks for the information, it can be tested on the demo: https://demo.photoprism.app/library/browse?order=random

**Comment by Geekados** [comment]
Is it possible to start the random slideshow automatically in fullscreen mode by loading an "extended" URL? 
(like ....browse?order=random#&play=true&display=fullscreen)

We want to use the (very) old tablet in the living room as an digital image frame. 
Currently it's running the "fully kiosk browser" and shows the visualisation of our smarthome and varios infos. 
(with the kiosk browser the smarthome server gets the possibility, to turn on the display and load any website)

at the moment I'm loading the URL, and I still need to tap on an image, press "play" and "fullscreen mode". 

It would be great if this would be possible.

Thanks! :)
