### ISSUE TITLE
Allow shared collections links to be seen on the map

### ISSUE THREAD

**Issue by lrq3000** [photoprism/photoprism#1533]
When sharing a collection with a link, there is no way to use the map feature. I would like to suggest to allow accessing the map for shared links.

But this should come after #1187 as the former is more important for usability, and maybe #98 can allow a workaround solution by creating a user account with limited rights, with an access to the map.

**Comment by graciousgrey** [comment]
Related to https://github.com/photoprism/photoprism/issues/557

**Comment by graciousgrey** [comment]
Found the duplicate ticket: https://github.com/photoprism/photoprism/issues/1016
