### ISSUE TITLE
Customize card view

### ISSUE THREAD

**Issue by KatyPurry** [photoprism/photoprism#1537]
Hey,

I just discovered Photoprism, sounds exciting ! I configured via Docker and tested to import few hundred photos / videos. Works flawless ! 

I have just a question that I can't resolve myself, is it possible to "hide" information on card view ? For example, I don't want to show Camera information and display less information from GPS (Just city, not region)

![image](https://user-images.githubusercontent.com/89610869/133935589-fa9388b9-886e-4ec0-ad0c-8155c8f0416d.png)

Thank you

**Comment by lastzero** [comment]
While it's technically possible, it would reduce rendering performance, increase code complexity and require additional settings incl documentation.

**Comment by KatyPurry** [comment]
Hi @lastzero 

Thank you for your answer, I understand your position. I'll switch to thumbnail view, it's almost perfect for me. I also sax that a "Google Photos" view was founded, I hope it will be developed in a future :)

**Comment by lastzero** [comment]
We do our best to deliver it as soon as possible. Still, there are 263 open issues and users want support, bugfixes as well as performance improvements along the way. For now, we're extremely happy Facial Recognition is done! 🥳
