### ISSUE TITLE
Will there be future releases?

### ISSUE THREAD

**Issue by rungitringit** [photoprism/photoprism#1538]
Hello,
I've been considering using photoprism in a Container for my family - it looks fantastic!  However I am concerned that a regular series of releases stopped back in May.

I'm not keen to run preview builds for my family.  Will there be releases with container builds on a regular basis again?

Thank you!

**Comment by lastzero** [comment]
No worries, the next release is just around the corner! We've added facial recognition as well as other major improvements: https://docs.photoprism.org/release-notes/

**Comment by rungitringit** [comment]
Thank you!

How often do you expect to have releases in the future?

**Comment by lastzero** [comment]
As in the past, multiple times per month unless we need time for testing major changes.

**Comment by isaacolsen94** [comment]
Thank you guys for your hard work!!
