### ISSUE TITLE
Browsing by year/month

### ISSUE THREAD

**Issue by tonydub** [photoprism/photoprism#154]
Hi,

It would be efficient and pleasant to be able to discover these photos by browsing by year/month.

**Comment by lastzero** [comment]
Once we have a first release, we will add events / moments and face recognition. Also thought about some kind of punch card view like on GitHub profiles...

**Comment by tonydub** [comment]
Events and moments are a good answer for time navigation.
Thanks.

**Comment by anthosz** [comment]
Hi, 

Events/moments generated dynamically?

**Comment by lastzero** [comment]
Well, based on your data / photos

**Comment by lastzero** [comment]
Our latest demo contains a compound database index that covers country/year/month and camera/lens. To test this, I added additional fields to our search form:

![Screenshot 2019-12-29 at 13 17 20](https://user-images.githubusercontent.com/301686/71556850-9e929680-2a3d-11ea-8535-f835acf1d8a4.png)

Note that it doesn't make sense to add an index for just year/month as we already index "taken_at" (would be a range scan in this case). You can still search ranges with "before:[date]" and "after:[date]", but I had to remove the date picker as we were running our of space in our search form and there is a year dropdown now as well.

Will be easy to automatically create dynamic filters or albums from this like "Canada / 2016" or "December 2015 in Canada". When we have a stable database structure, we will test with more photos and further improve indexing for best performance.

**Comment by lastzero** [comment]
Changed the label to `sponsor` assuming this is backed by @dennorske

Besides, we also want a year / month view for ourselves and already started working on it. See last comment.

**Comment by tonydub** [comment]
Good news! Thank you very much for your efforts.

**Comment by lastzero** [comment]
Looks like you get this feature in our [mobile app](https://github.com/photoprism/photoprism-mobile) first!

**Comment by guysoft** [comment]
> Looks like you get this feature in our [mobile app](https://github.com/photoprism/photoprism-mobile) first!

Didn't see there an option to browse by date at all ATM

**Comment by lastzero** [comment]
@guysoft This was my assumption based on https://github.com/photoprism/photoprism/pull/218

**Comment by dennorske** [comment]
Please give me a heads up if you need help testing this when it's added :+1:

**Comment by lastzero** [comment]
@dennorske @tonydub The initial implementation can now be tested with our latest x86 Docker image. Updated ARM64 / Pi build might be available later today or tomorrow.

**Comment by guysoft** [comment]
@lastzero Any reason the ARM64 build does not build at the same time with the x86? Need help with that?

**Comment by lastzero** [comment]
Building it manually at the moment, trying to push less and more stable images for the Pi.

**Comment by guysoft** [comment]
Suggestion:
1. Have an automated build on every commit using Jenkins or something like that.
2. Push all the images to photoprisim:devel
Then when you are happy with an image you just manually tag it as photoprisim:latest, or have a Jenkins job that tags it for you.

It would make your CI/CD simpler and you will have more time to enjoy life.
If you want help doing that I can help set it up.

**Comment by lastzero** [comment]
@guysoft We're working on it. Building it directly on the Pi seems much faster than an emulation, also given the fact that TravisCI has stability and performance issues. Probably migrating to [Drone](https://drone.io/). Not a top priority, we focus on a stable release right now. 

Starting an ARM64 build is just a tiny overhead, everything else is automated. It's just bad for our users, since I can't do it when we're traveling like at the moment.

**Comment by lastzero** [comment]
Closing this since nobody complained :)

This is the current implementation, see [demo.photoprism.org/calendar](https://demo.photoprism.org/calendar):

<img width="1080" alt="Screenshot 2020-06-12 at 22 51 21" src="https://user-images.githubusercontent.com/301686/84545299-43104880-acff-11ea-8c21-ae87987143cc.png">

**Comment by guysoft** [comment]
Will try test once I fix corruption issues on my drive here.
