### ISSUE TITLE
Docker: Improve entrypoint script

### ISSUE THREAD

**Issue by ToXinE** [photoprism/photoprism#1545]
As i've saw in issue https://github.com/photoprism/photoprism/issues/263 I think there is a bug in setting the correct GID of photoprism with docker compose.

here is my [docker-compose.yml](https://pastebin.com/wpLpxyim)

I've set UID to 1000 (mediacenter) and gid to 1000 (mediacenter) in docker compose but it creates the directory `photoprism` with 1000:0 and the other with another user.

here is the problem : 
![image](https://user-images.githubusercontent.com/6205053/134489476-bec5efca-3265-454a-8a8c-0a0af207f603.png)

Latest photoprism docker image running on Ubuntu 20.04 LTS

How can i make the docker image to use my user "mediacenter" and the group "mediacenter" ?

**Comment by lastzero** [comment]
Did you try starting PhotoPrism with `user: "1000:1000"` in your `docker-compose.yml`?

The env variables are for NAS devices who don't support setting a user / group natively. Of course we're also welcome improvements for the related `entrypoint.sh` script. 👍

**Comment by ToXinE** [comment]
Yes I tried but it seems no to do anything. 
I don't care running as `photoprism:photoprism` inside the container, I only need to map the user used inside the container to `mediacenter:mediacenter` outside of the container. I thought the parameters UID, GID and UMASK was made for that purpose. Am I right or did I miss something ?

**Comment by lastzero** [comment]
It's made for this, but i can't confirm any issues just like I don't have issues with the native user parameter. Might be something else if both don't work for you?

**Comment by stumpylog** [comment]
I belive I'm running into this as well.  When starting the docker container, I see the following in the logs:

```
groupadd: '971' is not a valid group name
usermod: group '971' does not exist
```

As with the above example, I am setting a `UID` and `GID` through environment variables.  It appears the group isn't being created?

**Comment by lastzero** [comment]
Can you check our entrypoint script and suggest how we can improve this for you so that it works?

**Comment by ToXinE** [comment]
I'd like to but I'm not expert enough in docker / containers to know what's wrong with GID not being applied.
I've set GID to my mediacenter group Id but it doesn't care and run photoprim with root group (0) instead of mediacenter group (1000) as specified in the GID environnement variable.

```
      # Set a non-root user, group, or custom umask if your Docker environment doesn't support this natively:
      UID: 1000
      GID: 1000
      UMASK: 002
```

**Comment by lastzero** [comment]
Might have to simply create that group in the container...

**Comment by lastzero** [comment]
Our use the native Docker way to set user and group

**Comment by lastzero** [comment]
Started a new Development Preview build with the improved entrypoint script (available when the build is green): 

https://docs.photoprism.app/getting-started/updates/#development-preview

Note that we've added PHOTOPRISM_ prefixes to the environment variable names:
- Instead of `UID`, please now use `PHOTOPRISM_UID`
- Instead of `GID`, please now use `PHOTOPRISM_GID`
- Instead of `UMASK`, please now use `PHOTOPRISM_UMASK`

Let us know if this works for you!

**Comment by lastzero** [comment]
@ToXinE Did you already try a simple
```
chown -R mediacenter:mediacenter ~/photoprism_storage
```
or does Docker automatically change the group back to root?

**Comment by ToXinE** [comment]
I'll try asap thank you !

**Comment by lastzero** [comment]
Released! 🥂

Make sure to prefix existing environment variables with `PHOTOPRISM_` as described above.
