### ISSUE TITLE
People: Improve naming, renaming, and merging

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#1557]
I had several images with faces, say person A and B. I wanted to change the tagged person A on one photo, so I changed the name to B. Now all the images with person A belong to person B, it looks like it merged the 2 persons. I think we should add a warning when changing one photo will affect several faces.

Workaround: press the eject button before changing a name: ![image](https://user-images.githubusercontent.com/2071331/134811217-f39933cf-161b-41e8-88e3-0aaed77ba3aa.png)

Side note: congrats that this new feature, this is great!

**Comment by jackbrown1993** [comment]
Agree, that some sort of confirmation or warning is required. Done this by mistake a couple of times now.

**Comment by graciousgrey** [comment]
Changing the name without pressing the reject button will rename the person see: https://docs.photoprism.org/user-guide/organize/people/#rename-person. But obviously it is not that clear

**Comment by lastzero** [comment]
That's exactly why we had the preview for testing. It works as designed. If you rename a person, it's renamed everywhere. Otherwise you need to press the button, so that PhotoPrism knows it's a DIFFERENT person. We'll improve our UI and docs to make this even more clear.

**Comment by alexislefebvre** [comment]
@graciousgrey Thanks, my bad, I didn't read the doc before trying this new feature.

Here is the context:

> ![image](https://user-images.githubusercontent.com/2071331/134811697-550a8bdc-5a21-49e5-a29d-b47e18f71043.png)

The other tabs allow to edit data for only that photo, but changing the person here will affect all the related photos, this is surprising.

**Comment by lastzero** [comment]
Probably best to disable editing names in the photo edit dialog at all to avoid mistakes.

**Comment by graciousgrey** [comment]
@alexislefebvre no worries, it's good to have that feedback! Most people don't read the docs at all, so it should be as intuitive as possible :)

**Comment by lastzero** [comment]
Started a new [Development Preview](https://docs.photoprism.org/release-notes/) build including the following changes:
- You now have to confirm merging people on the *People* overview page when you name a person like an existing person. 
- Editing existing names in the photo edit dialog is disabled to avoid mistakes.
- Orphan people and faces are removed automatically in the background, so that the count in the navigation always matches the actual search results.

**Comment by alexislefebvre** [comment]
Thank you.

I tried on the demo. I have set the name for a cluster, then I opened that show media with this person's face. When I pressed the eject button on one photo, it disconnected several photos from the same person.

And we can't mistakenly merge 2 people anymore. :clap:

**Comment by lastzero** [comment]
> When I pressed the eject button on one photo, it disconnected several photos from the same person.

That actually depends on the face similarity as the software sees it. When similar faces belong to different people, it will separate them and create individual clusters. If needed also multiple clusters per person until the user stops reporting issues by pressing the eject button.

**Comment by lastzero** [comment]
Released! 🥂
