### ISSUE TITLE
Feature disabled when trying to name a face

### ISSUE THREAD

**Issue by AliMickey** [photoprism/photoprism#1558]
Congrats on the release!

When i try and name a new face, it gives me this.
![image](https://user-images.githubusercontent.com/60691199/134836242-ce23e4a4-6672-4171-94ed-3b552e076b7e.png)

These are my settings:
![image](https://user-images.githubusercontent.com/60691199/134836260-092ab68b-5a31-491b-96c2-1a2b83c8edc3.png)
![image](https://user-images.githubusercontent.com/60691199/134836271-fbc950fb-4b51-4d95-ada1-db8aa0e5263f.png)
![image](https://user-images.githubusercontent.com/60691199/134836285-c994b5e9-4ff5-46ef-b99b-edfd6e9ab127.png)

**Comment by lastzero** [comment]
It's because you've disabled edit and adding a name would change the photo title (unless it's also edited or imported from Exif / XMP)

**Comment by AliMickey** [comment]
so theres no way to take advantage of face naming without touching the original file?

Really disappointed if thats the case.

**Comment by AliMickey** [comment]
To clarify, does that edit the in db name or actual original file name?

**Comment by lastzero** [comment]
No, editing metadata in PhotoPrism never changes the file name. All changes are stored in the database. Not just in this case.

**Comment by lastzero** [comment]
A future release may have an option to write metadata to originals, but it's not implemented yet. You'll have to enable it separately.

**Comment by AliMickey** [comment]
Ok thats perfect, i dont want photoprism to edit any original files. 

Thanks again.
