### ISSUE TITLE
Search: Query full-text index with title as fallback

### ISSUE THREAD

**Issue by bm55** [photoprism/photoprism#1560]
After installing the latest version the search without any filter only returns the pictures with people label. PhotoPrism doesn’t detect people in all images so the search result displays limited photos. Seems like the previous default search showed any photo that matches the search word in any metadata type. Can the default search behavior restored to previous version? We can always use the filter if we want to

**Comment by lastzero** [comment]
Only if there is a person with that name, not in general. You don't want to find that person but only pictures with the name as keyword?

**Comment by lastzero** [comment]
Note you can use the new labels and keywords search filters for this, which will ignore existing people.

**Comment by lastzero** [comment]
Can you confirm this was the issue? Does the alternative work for you?

**Comment by bm55** [comment]
yes, so if I type keywords:max, I get 7 pictures result. but if I just type max, I only get 1 result which is same result as person:max. It appears the default search without any filter is configured to use person filter now? can that be changed and instead use the keywords filter by default?

**Comment by lastzero** [comment]
Could be changed, but wouldn't you expect an actual, known person to have a higher priority than a random keyword?

**Comment by bm55** [comment]
Since the face detection doesn't detect all faces, I really think the default search should be the keywords that way all photos with certain keyword (title, keyword, subject, description) can be searched easily. I know how to use "keyword:max" but not all family members will remember to do that. 

Also, the people search is already on the left navigation.

I have been spending a lot of time adding related keywords on all my photos (before adding it to PhotoPrism via Lightroom, and some within the PhotoPrism) so I can easily search and list all photos of family members, pets, friends, lakes, parks, and other objects. So I really hope you will consider changing the default search back to way it used to work in  previous version. 

Or even better, make is a user configured option via settings? default search options: 1. People 2. keywords or 3. People + keyworkds
What do you think?

**Comment by lastzero** [comment]
That makes sense. Currently working on an update. Stay tuned.

**Comment by lastzero** [comment]
Started a new [Development Preview](https://docs.photoprism.org/release-notes/) build including the following changes:
- People's names will be added to the full text index in the background and when editing photos.
- Keep in mind index updates may take a while, they don't happen in real time.
- Using the full text index means names matching a stopword like "img" won't be found.
- If the query is too short for the full text index or matches a stopword, a photo name wildcard search will be performed instead.

**Comment by lastzero** [comment]
Can be tested on our demo when the build is green: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
Makes sense to use the photo title instead of file name in case the query is too short for the full-text index.

**Comment by lastzero** [comment]
Released! 🥂
