### ISSUE TITLE
Be able to select Default thumbnail

### ISSUE THREAD

**Issue by ToXinE** [photoprism/photoprism#1562]
As user, I want to be able to select default thumbnails of albums, moments, people, calendar, labels, folders.

Acceptance Criteria:

    The user MUST be able to select a picture in each categories(albums, moments, people, calendar, labels, folders) using the context menu.
    The user MUST be able to undo selection so that last thunmbnail is selected back as it was previously.

**Comment by graciousgrey** [comment]
This is planned: https://github.com/photoprism/photoprism/issues/383 :)

**Comment by lastzero** [comment]
Friendly reminder if you are not a sponsor yet: The more people sponsor our work, the faster everyone gets more features 👍
