### ISSUE TITLE
Auto-fill for people's names?

### ISSUE THREAD

**Issue by dm7500** [photoprism/photoprism#1563]
When I fill out a name for a person, it is only giving me a drop down list with `null` as shown below. I've had small instances where it will populate a list of all known names, which makes it much easier, faster, and less error prone.

Is the list of names something that should be expected? Not sure what the standard should be.

![image](https://user-images.githubusercontent.com/5718250/135113396-e1fcbae3-f268-4da6-ad19-9b287bfedbc7.png)

**Comment by graciousgrey** [comment]
Autocomplete is working on the demo and our private instances. Did you do any changes to the database?

**Comment by dm7500** [comment]
None. Basic docker-compose deployment on x86-64 hardware. I had the auto-complete working for about an hour after I posted this issue, but now it's again back to `null`. Trying to find some rhyme or reason for it, and can't seem to find any.

Just tested with Chrome, and auto-complete is working, but this was a quick test. Firefox is my daily driver though, so interesting that it's only working sporadically there.

**Comment by graciousgrey** [comment]
Just tested again on firefox. For me it's working.  Do you use special ad blockers or similar?

**Comment by dm7500** [comment]
I've tested again with my ad-blockers disabled, no change. Also confirmed it happening on Chrome now as well.

**Comment by lastzero** [comment]
Any reason websockets might not work? Do you see a warning in the lower left corner? Does it work when you reload the page?

**Comment by dm7500** [comment]
Reloading the page doesn't fix the issue.

I'm seeing an offline icon in the bottom left. 

![image](https://user-images.githubusercontent.com/5718250/135156524-d0d5e3c4-3906-4557-9fd5-c824496e3425.png)

It brings me to a websockets help page, with proxy configs for Apache, Nginx, etc. I'm not sure what exactly this is needed for. I'm running this on an internal server, but it's served out to the web via NGINX Proxy Manager.

**Comment by dm7500** [comment]
Reading up on this, I'm noticing that the offline icon only shows when I access the page form the external address I've setup (photos.domain.com). Accessing it on my LAN (server:2342) doesn't give me this issue, and I have no offline icon.

**Comment by lastzero** [comment]
Does autocomplete work when the warning does not appear?

**Comment by dm7500** [comment]
It does, without issue. The problem has to be the websockets connection right? If so, I need to find out how to do custom NGINX configs for NPM.

**Comment by lastzero** [comment]
Nginx in general works, but many users have issues configuring it properly 🤔 you might find answers in our GitHub issues or the chat

**Comment by dm7500** [comment]
Figured it out! For any future users seeing this issue, make sure you enable Websocket support on your proxy setup in NPM

![image](https://user-images.githubusercontent.com/5718250/135159232-acb11afa-3f96-49a0-98e6-3c46addec165.png)
