### ISSUE TITLE
Incorrect Image When clicking in from UI

### ISSUE THREAD

**Issue by Dulanic** [photoprism/photoprism#1572]
I am seeing the wrong images when clicking into the images. It seems to start if I click forward/backward within a photo, then all images show the same, even if I refresh the page.

https://streamable.com/560mcj

**Comment by lastzero** [comment]
Is this always happening or just a glitch? How can we reproduce this behavior?

**Comment by Dulanic** [comment]
I tried reproducing on another device and can't I'll close this as it might have just been a glitch. If I run into it again Ill follow up.
