### ISSUE TITLE
Simpler view of images on homepage as an option

### ISSUE THREAD

**Issue by aravindhsampath** [photoprism/photoprism#1573]
Currently the home page lists all images with additional details such as title, timestamp, size etc.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1080908/135411105-d1dc1d19-e457-4326-afe1-5c0078c4bacd.png">

I would like a more minimal view as an option - that looks similar to the "Photos" app on Apple ecosystem.
Example:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/1080908/135411449-7e8d9d50-6e20-4e79-98bc-f2a9b9105cf5.png">
This style could allow for more image thumbnails to appear in the view, and give a nicer browsing experience to me as a user. 

Not sure if this request belongs to the [issue for new photo viewer](https://github.com/photoprism/photoprism/issues/1307) as my request pertains only to the home page and not the viewer of images itself.

**Comment by graciousgrey** [comment]
You can switch to the mosaic view for this, see https://docs.photoprism.org/user-guide/organize/views/.

We have a open feature request for a view without squares as well: https://github.com/photoprism/photoprism/issues/1205
