### ISSUE TITLE
import upload folder not removed after import

### ISSUE THREAD

**Issue by oziee** [photoprism/photoprism#158]
once an upload is complete, the temp folder in ~/Pictures/Import/upload/xxxxxxxx remains

can this be automatically deleted on upload import complete?

**Comment by lastzero** [comment]
Is it possible that there are remaining files that can not be imported?

**Comment by oziee** [comment]
no.. the folders are empty. Being its a mac there could be hidden .ds_store files

**Comment by lastzero** [comment]
I've just fixed this bug. Uploads are also enabled again on demo.photoprism.org!
