### ISSUE TITLE
Remove people without any registered faces

### ISSUE THREAD

**Issue by coolmule0** [photoprism/photoprism#1580]
Sometimes I accidentally mistype a name while adding a face. This mistype then keeps showing up in the list of possible faces when choosing a name for a face. It would be nice to be able to remove these misspelt names.

The requirements for removing them would be if they have no faces. It would be nice if this happened automatically, but if that is not possible, then having a UI button to "clean faces" somewhere would be appreciated

**Comment by lastzero** [comment]
Should automatically be removed by the background worker. How long did you wait?

**Comment by coolmule0** [comment]
Its been on the order of ~1 week

**Comment by lastzero** [comment]
Oh, might in fact be an improvement that's coming with the next update. Current development preview is our release candidate. Found no more issues today.

**Comment by coolmule0** [comment]
Issue is sorted in the preview build, using docker
