### ISSUE TITLE
Lightbox mode does not "infinite scroll"

### ISSUE THREAD

**Issue by robbymilo** [photoprism/photoprism#1581]
Possible bug in the lightbox view mode. Running version `210925-96168e4b-Linux-x86_64` with MariaDB v10.5 with ~5000 photos.

To replicate:
1. Open default view (`/browse`), sorted by "Newest first".
2. Open first photo via lightbox.
3. Click previous button.

What happens:
The 360th photo is loaded.

What I expect:
The first/oldest photo to be loaded.

This can also be replicated by:
1. Open default view (`/browse`), sorted by "Newest first".
2. Open first photo via lightbox.
3. Click next 360 times.
4. On the 361st click the first photo is loaded.

I think this is a regression of https://github.com/photoprism/photoprism/issues/309.

Note: I cannot replicate this on https://demo.photoprism.org/ as there are fewer than 360 photos.

On initial load of `/browse`, it looks like there is an XHR request with `count=360`. I assume this request is where that comes from? Happy to help if you can point me in the right direction :)

**Comment by lastzero** [comment]
Need more sponsors to finance the development of a custom lightbox 😂

**Comment by robbymilo** [comment]
In the mean time I'm happy to help fix this if you point me in the right direction.

**Comment by lastzero** [comment]
We've stopped adding workarounds to this. There's an issue for a new lightbox already.

**Comment by graciousgrey** [comment]
There are already so many limitations on the lightbox we use that it just does not make sense to add workarounds. See https://github.com/photoprism/photoprism/issues/1307

**Comment by lastzero** [comment]
Going to attack this when multi user support is released to avoid context switching.
