### ISSUE TITLE
UX: Show hint/notice when infinite scroll is loading

### ISSUE THREAD

**Issue by robbymilo** [photoprism/photoprism#1582]
When infinite scrolling:
- There is no visual indication that more results may be loaded in the near future.
- There is no visual indication that all results have loaded.

Potential suggestions:

Show `Loading...` (maybe a spinning icon?) when the XHR request has been initiated:
![loading](https://user-images.githubusercontent.com/8106669/135686685-f3f144a6-1e61-405d-b5cc-a135aa182617.png)

Show how many results have been loaded, as well as total results:
![total](https://user-images.githubusercontent.com/8106669/135686765-5c8bf840-e837-40a7-b6a0-e4f8d2c9e049.png)

Show that you've reached the end of scrolling:
![the-end](https://user-images.githubusercontent.com/8106669/135687070-7665392a-6267-4a7b-88cb-9286e9a1c7c7.png)

**Comment by lastzero** [comment]
There should be a top loading bar as well as notifications at the bottom.

**Comment by robbymilo** [comment]
I see the top loading bar, but it only appears after the xhr request has finished loading, and after the images have already started downloading, so it doesn't give the user a hint that more images could be loaded soon.

I also see the "More than 50 results" notice, but that is only on initial load.

**Comment by lastzero** [comment]
That's common as a response time of 100ms is perceived as instantaneous. Google it. Most loading bars work like this.

**Comment by tribut** [comment]
I quite often miss the loading bar at the top and I've recently observed my significant other having the same problem. I'm staring at the bottom of a list. Looking at the top of my browser is just not very natural in that moment. I would appreciate a loading indicator at the bottom, where the new images are supposed to appear.

**Comment by lastzero** [comment]
On top of the notifications that are also displayed at the bottom? If all rows are filled, there is no space otherwise. Showing a loading bar at the top is common, kind of a best practice. We can of course show it earlier if it helps.

**Comment by tribut** [comment]
Are we talking about the same thing? I'm talking about what happens when I'm scrolling down a long list and then hit the "bottom" (which then triggers some sort of "load more" event). I don't think there is any notification at the bottom.

**Comment by lastzero** [comment]
There can be notifications as it's the general notification area, for example when other users trigger actions such as creating albums or changing settings. Try for yourself, for example using our demo. It's also possible to initial result notification ("more than 50 pictures") is still visible when you scroll very fast.

**Comment by tribut** [comment]
Oh, sure. I've absolutely seen notifications at the bottom. Just not in the specific circumstance this issue is about. There is no notification when I hit the bottom of the list while its loading more elements (just verified with the demo).

**Comment by lastzero** [comment]
Try changing settings in another window at the same moment. It's not guaranteed that there are no notifications. There may be additional notifications in future releases, like when somebody comments or likes your photo.

**Comment by tribut** [comment]
Sure. But the usual way and location for a "there will be more stuff" indicator is something like in the mockups by @robbymilo. You brought up the notification or we misunderstood each other. 
I'm not advocating for a notification, I'd much prefer something like a spinner right where more items are about to appear (see images above).

**Comment by lastzero** [comment]
That's an edge case because there is space left. What if rows are full. Add an extra row for a spinner? What if it causes flickering or reduced rendering performance for everyone? Happy to experiment with this when our roadmap isn't as crowded as it is right now. UX is super important.

**Comment by lastzero** [comment]
Also we don't know yet if something will appear until after the fact. Thus the loading bar at the top, which is indicating a backend request - not that it will include new items as we just don't know in the frontent. Often changes, in particular while indexing or when there are other users moving / editing pictures.

**Comment by tribut** [comment]
Yes, I'd rather have a row with just a loading-thing. Because right now I'm relying on the absence of an indicator and I'm never quite sure if I've waited long enough  (granted, my pc is quite slow).

**Comment by lastzero** [comment]
The frontend isn't sure either, as it depends. Sometimes files have been added to the library, so that more results can be found. Sometimes not, so that no more results pop up. Developing distributed systems is hard. To be honest, it sounds a bit like a general performance issue in your case (I generally don't need to wait very long to see something happening). Could it be that a timeline view is what you imagine? So that you just can continue scrolling down / up infinitely? It's on our roadmap already, see GitHub issue.

**Comment by tribut** [comment]
I imagine a possible implementation to have the loading indicator by default and hide it when there are no more results. A lot of modern self-hosted webapps seem to suffer from this problem and it irritates me every time, even when it's just half a second. The "big players" like Twitter, Instagram, etc all have something like this.
I've seen the timeline view issue and I'm very much looking forward to it 🙂

**Comment by lastzero** [comment]
We'll consider it, although we have a small team and already work 7 days a week from morning to evening. So we only can focus on the most important tasks and need to be very careful not to get lost in details. I'd say it's good enough until we reach our funding goal and can grow our team. Quid pro quo.

**Comment by lastzero** [comment]
PS: Thank you very much for supporting us! <3

**Comment by tribut** [comment]
Sure, it's a feature request. I understand it's not high priority. Keep up the good work 😊

**Comment by graciousgrey** [comment]
Released since no problems were reported!
