### ISSUE TITLE
People: allow manual person assignment

### ISSUE THREAD

**Issue by kavemang** [photoprism/photoprism#1583]
I have a few photos that don't seem to have a face being recognized after trying to reindex, would be nice to be able to manually assign a person to the photo and/or manually assign the face location/detection on the photo . Or maybe allow rescanning of specific photos instead of the entire library at once

**Comment by graciousgrey** [comment]
Manual tagging is already on our todo https://github.com/photoprism/photoprism/issues/1548 :)
