### ISSUE TITLE
Remove single images from person

### ISSUE THREAD

**Issue by ScuttleSE** [photoprism/photoprism#1586]
I create a "person" from a cluster of 10 faces
One of those faces is incorrect, the other nine are correct.

How do I remove that single incorrect face from the person, while keeping the photo, and using it when matching against other people.

**Comment by lastzero** [comment]
Click on the eject button.

**Comment by ScuttleSE** [comment]
Uhm...what eject button?

If I click a person I see the heart-button, the checkbox-button and the raw-button on the pictures. No eject button.

**Comment by lastzero** [comment]
In the edit dialog, people tab.

**Comment by lastzero** [comment]
https://docs.photoprism.org/user-guide/organize/people/
