### ISSUE TITLE
UX: Add ability to flow through editing photos /w keyboard.

### ISSUE THREAD

**Issue by Dulanic** [photoprism/photoprism#1593]
As a user I'd love to have the same ability to switch between photo's in edit mode as I do in viewing mode.  This would allow me to change photos much more easily when trying to add names to new faces much more easily. 

Currently I can use my left and right keys to change pictures in normal viewing mode, but this does not function in editing mode. 

I reviewed other open tickets, but those seem to be around adding/changing keyboard shortcuts. This request is just to extend current functionality to another page it does not work on.

For reference, this is the view I am discussing:

![image](https://user-images.githubusercontent.com/2948206/135846097-dfb0c405-cbc6-493d-9f01-b3259449e4a5.png)

**Comment by graciousgrey** [comment]
This will be further evaluated in the scope of: https://github.com/photoprism/photoprism/issues/1131
