### ISSUE TITLE
People: Broken thumbnails in 'New' faces.

### ISSUE THREAD

**Issue by jackbrown1993** [photoprism/photoprism#1594]
Hello,

I am seeing broken thumbnails in the 'New' faces section. I have started a full index but my library is over 100k photos. Should a re-index fix this? Is there a quicker way?

Thanks,

Jack.

<img width="1680" alt="Screenshot 2021-10-04 at 13 47 09" src="https://user-images.githubusercontent.com/6218551/135853992-4fa3389b-cbdf-4381-a09a-d9e34655c66e.png">

**Comment by lastzero** [comment]
Are you using our latest release? Seems there are issues creating cropped face thumbnails. Many reasons this could happen, starting at filesystem permission issues. Did you check the logs?

**Comment by jackbrown1993** [comment]
Yes, currently on the latest release. It could be an issue on my end as my originals are accessed via a NAS and the NAS did have a power outage recently. Anything in particular I can grep for within the logs?

**Comment by lastzero** [comment]
I'd check if thumbs are missing. Can you run the photoprism purge, convert avd thumb commands in a terminal to make sure everything is as it should?

**Comment by jackbrown1993** [comment]
What does the purge command do? Is it purging the database or sidecar and YAML files?

**Comment by lastzero** [comment]
It's removing orphan index entries, updates counts and cover images.

**Comment by jackbrown1993** [comment]
Purge complete, still haven't done convert or thumb command yet. I have a library of 111k photos. However, here are the logs when loading the 'New' faces page where broken thumbs are.

```
time="2021-10-04T20:45:36Z" level=debug msg="http: GET /api/v1/faces?count=264&offset=0&q=&all=&order=relevance&markers=true&unknown=true (200) [251.696128ms]"
time="2021-10-04T20:45:37Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:37Z" level=debug msg="http: GET /api/v1/t/f49826c32dd2fa80660bfb70d39506eb79a1284e-10d0ea0a50f8/c2c535d2/tile_320 (200) [268.244µs]"
time="2021-10-04T20:45:37Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:37Z" level=debug msg="http: GET /api/v1/t/e4f0e8ba1a823640e84857a74c3403c42a28fb06-17c09b05c08b/c2c535d2/tile_320 (200) [519.949µs]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/4e889a1b4cb288ca0355dd9d42cb09920d3c53e0-2bc08a05e08d/c2c535d2/tile_320 (200) [285.44µs]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/56b6949814b6f60ad0ac4498a3e2bc59bdc012fc-2690bd060091/c2c535d2/tile_320 (200) [1.207163ms]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/674881e754781ab60f8ec9bd5b47134d9a230d9b-1450a20860b3/c2c535d2/tile_320 (200) [253.771µs]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/284c86bbcd3f5490022fc0593801674df70a1f6e-0801a4055071/c2c535d2/tile_320 (200) [326.222µs]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/8e3e134eb6b52519b4725b75c1c4e3b54701a777-2af0ef07905a/c2c535d2/tile_320 (200) [252.781µs]"
time="2021-10-04T20:45:38Z" level=warning msg="thumb: image: unknown format"
time="2021-10-04T20:45:38Z" level=debug msg="http: GET /api/v1/t/31b5618146b3ea7ee31c1709be30a31b43cbb85c-2242d5085064/c2c535d2/tile_320 (200) [607.974µs]"
```

**Comment by lastzero** [comment]
Interesting, thumbs should always be JPEGs. Not sure what's causing this (yet).

**Comment by lastzero** [comment]
Related to #1576. Should be fixed with today's changes.

**Comment by lastzero** [comment]
Started a new Development Preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by jackbrown1993** [comment]
Still seeing 5 broken thumbnails on the latest release. Were fixed in release or still in development build only?

**Comment by lastzero** [comment]
Did you run index or purge? May also be a file system permission issue, check logs.

**Comment by jackbrown1993** [comment]
While running the convert command seeing lots of these messages.

```
INFO[2021-10-11T10:19:44Z] libx264: created 20210224_155442_6B410C0A.mov.avc [1.978190029s]
INFO[2021-10-11T10:19:44Z] libx264: transcoding 2021/02/20210224_142024_4ED9E6C9.mov to avc
WARN[2021-10-11T10:19:44Z] metadata: unknown json in 3c1f34c61c73b1b0fa42b40572e93c1c31f8c888_exiftool.json
DEBU[2021-10-11T10:19:44Z] unknown json in 3c1f34c61c73b1b0fa42b40572e93c1c31f8c888_exiftool.json
DEBU[2021-10-11T10:19:44Z] metadata: exif not supported in 20210223_203720_99644609.mov
DEBU[2021-10-11T10:19:44Z] media: exif not supported
DEBU[2021-10-11T10:19:44Z] media: exif not supported
INFO[2021-10-11T10:19:47Z] libx264: created 20210224_142024_4ED9E6C9.mov.avc [2.802911492s]
INFO[2021-10-11T10:19:47Z] libx264: transcoding 2021/02/20210223_203140_53852DF3.mov to avc
WARN[2021-10-11T10:19:47Z] metadata: unknown json in 85a669f37d1b264796c38b39790041776cca3e7f_exiftool.json
DEBU[2021-10-11T10:19:47Z] unknown json in 85a669f37d1b264796c38b39790041776cca3e7f_exiftool.json
DEBU[2021-10-11T10:19:47Z] metadata: exif not supported in 20210224_141926_6A91CEC0.mov
DEBU[2021-10-11T10:19:47Z] media: exif not supported
DEBU[2021-10-11T10:19:47Z] media: exif not supported
INFO[2021-10-11T10:19:50Z] libx264: created 20210223_203140_53852DF3.mov.avc [3.035480948s]
INFO[2021-10-11T10:19:50Z] libx264: transcoding 2021/02/20210224_155230_6FB68F92.mov to avc
WARN[2021-10-11T10:19:50Z] metadata: unknown json in bd8d0848f0edd822bb21e0df5bec538e85506a75_exiftool.json
DEBU[2021-10-11T10:19:50Z] unknown json in bd8d0848f0edd822bb21e0df5bec538e85506a75_exiftool.json
DEBU[2021-10-11T10:19:50Z] metadata: exif not supported in 20210224_160136_5C8AD724.mov
DEBU[2021-10-11T10:19:50Z] media: exif not supported
DEBU[2021-10-11T10:19:50Z] media: exif not supported
INFO[2021-10-11T10:19:53Z] libx264: created 20210224_155230_6FB68F92.mov.avc [2.782817089s]
INFO[2021-10-11T10:19:53Z] libx264: transcoding 2021/02/20210223_203720_99644609.mov to avc
WARN[2021-10-11T10:19:53Z] metadata: unknown json in f79a590b9127dd38f4b55356468e3c2dbd437b57_exiftool.json
DEBU[2021-10-11T10:19:53Z] unknown json in f79a590b9127dd38f4b55356468e3c2dbd437b57_exiftool.json
DEBU[2021-10-11T10:19:53Z] metadata: exif not supported in 20210220_095018_FB5062A8.mov
DEBU[2021-10-11T10:19:53Z] media: exif not supported
DEBU[2021-10-11T10:19:53Z] media: exif not supported
INFO[2021-10-11T10:19:55Z] libx264: created 20210223_203720_99644609.mov.avc [2.497855641s]
INFO[2021-10-11T10:19:55Z] libx264: transcoding 2021/02/20210224_141926_6A91CEC0.mov to avc
WARN[2021-10-11T10:19:55Z] metadata: unknown json in 52c567472f4cc3797c49020672d94f561c237c17_exiftool.json
DEBU[2021-10-11T10:19:55Z] unknown json in 52c567472f4cc3797c49020672d94f561c237c17_exiftool.json
DEBU[2021-10-11T10:19:55Z] metadata: exif not supported in 20210224_154858_65486E74.mov
DEBU[2021-10-11T10:19:55Z] media: exif not supported
DEBU[2021-10-11T10:19:55Z] media: exif not supported
INFO[2021-10-11T10:19:58Z] libx264: created 20210224_141926_6A91CEC0.mov.avc [2.326701778s]
INFO[2021-10-11T10:19:58Z] libx264: transcoding 2021/02/20210224_160136_5C8AD724.mov to avc
WARN[2021-10-11T10:19:58Z] metadata: unknown json in 29b02743859442fde6a0455d8ab5db33936574d5_exiftool.json
DEBU[2021-10-11T10:19:58Z] unknown json in 29b02743859442fde6a0455d8ab5db33936574d5_exiftool.json
DEBU[2021-10-11T10:19:58Z] metadata: exif not supported in 20210224_154826_8EF87186.mov
DEBU[2021-10-11T10:19:58Z] media: exif not supported
DEBU[2021-10-11T10:19:58Z] media: exif not supported
INFO[2021-10-11T10:19:59Z] libx264: created 20210224_160136_5C8AD724.mov.avc [1.210423745s]
INFO[2021-10-11T10:19:59Z] libx264: transcoding 2021/02/20210220_095018_FB5062A8.mov to avc
WARN[2021-10-11T10:19:59Z] metadata: unknown json in 7a9f9250afbea2ba9ca8437c46c9f627c1fd20f7_exiftool.json
DEBU[2021-10-11T10:19:59Z] unknown json in 7a9f9250afbea2ba9ca8437c46c9f627c1fd20f7_exiftool.json
DEBU[2021-10-11T10:19:59Z] metadata: exif not supported in 20210220_095033_317A0D27.mov
DEBU[2021-10-11T10:19:59Z] media: exif not supported
DEBU[2021-10-11T10:19:59Z] media: exif not supported
INFO[2021-10-11T10:20:03Z] libx264: created 20210220_095018_FB5062A8.mov.avc [4.556404957s]
INFO[2021-10-11T10:20:03Z] libx264: transcoding 2021/02/20210224_154858_65486E74.mov to avc
WARN[2021-10-11T10:20:03Z] metadata: unknown json in b9271ba5675e2370679f58017c10d665b71f1402_exiftool.json
DEBU[2021-10-11T10:20:03Z] unknown json in b9271ba5675e2370679f58017c10d665b71f1402_exiftool.json
DEBU[2021-10-11T10:20:03Z] metadata: exif not supported in 20210224_155200_B0AB4C3C.mov
DEBU[2021-10-11T10:20:04Z] media: exif not supported
DEBU[2021-10-11T10:20:04Z] media: exif not supported
INFO[2021-10-11T10:20:06Z] libx264: created 20210224_154858_65486E74.mov.avc [2.729383708s]
INFO[2021-10-11T10:20:06Z] libx264: transcoding 2021/02/20210224_154826_8EF87186.mov to avc
WARN[2021-10-11T10:20:07Z] metadata: unknown json in 290ba7bb840f928dcb63531270ea3ae926e2efda_exiftool.json
DEBU[2021-10-11T10:20:07Z] unknown json in 290ba7bb840f928dcb63531270ea3ae926e2efda_exiftool.json
DEBU[2021-10-11T10:20:07Z] metadata: exif not supported in 20210220_095117_4B70491E.mov
DEBU[2021-10-11T10:20:07Z] media: exif not supported
DEBU[2021-10-11T10:20:07Z] media: exif not supported
INFO[2021-10-11T10:20:09Z] libx264: created 20210224_154826_8EF87186.mov.avc [2.620887639s]
INFO[2021-10-11T10:20:09Z] libx264: transcoding 2021/02/20210220_095033_317A0D27.mov to avc
WARN[2021-10-11T10:20:09Z] metadata: unknown json in 55428eb0f96c2bb16560301fe786df7b9b95347c_exiftool.json
DEBU[2021-10-11T10:20:09Z] unknown json in 55428eb0f96c2bb16560301fe786df7b9b95347c_exiftool.json
DEBU[2021-10-11T10:20:09Z] metadata: exif not supported in 20210224_160224_92CFEE6A.mov
DEBU[2021-10-11T10:20:09Z] media: exif not supported
DEBU[2021-10-11T10:20:09Z] media: exif not supported
INFO[2021-10-11T10:20:13Z] libx264: created 20210220_095033_317A0D27.mov.avc [4.26063048s]
INFO[2021-10-11T10:20:13Z] libx264: transcoding 2021/02/20210224_155200_B0AB4C3C.mov to avc
WARN[2021-10-11T10:20:13Z] metadata: unknown json in 7071ca793ac95afb47f997cea7cecc7fe47a8e46_exiftool.json
DEBU[2021-10-11T10:20:13Z] unknown json in 7071ca793ac95afb47f997cea7cecc7fe47a8e46_exiftool.json
DEBU[2021-10-11T10:20:13Z] metadata: exif not supported in 20210224_155558_DF90CC08.mp4
DEBU[2021-10-11T10:20:13Z] media: exif not supported
DEBU[2021-10-11T10:20:13Z] media: exif not supported
INFO[2021-10-11T10:20:14Z] libx264: created 20210224_155200_B0AB4C3C.mov.avc [1.537915531s]
INFO[2021-10-11T10:20:14Z] libx264: transcoding 2021/02/20210220_095117_4B70491E.mov to avc
INFO[2021-10-11T10:22:25Z] libx264: created 20210220_095117_4B70491E.mov.avc [2m10.550613442s]
INFO[2021-10-11T10:22:25Z] libx264: transcoding 2021/02/20210224_160224_92CFEE6A.mov to avc
WARN[2021-10-11T10:22:25Z] metadata: unknown json in a811d2bb5d43e5c110c06cc7fc9a4efec6ff15b6_exiftool.json
DEBU[2021-10-11T10:22:25Z] unknown json in a811d2bb5d43e5c110c06cc7fc9a4efec6ff15b6_exiftool.json
DEBU[2021-10-11T10:22:25Z] metadata: exif not supported in 20210224_142102_4BF9F05C.mov
DEBU[2021-10-11T10:22:25Z] media: exif not supported
DEBU[2021-10-11T10:22:25Z] media: exif not supported
INFO[2021-10-11T10:22:28Z] libx264: created 20210224_160224_92CFEE6A.mov.avc [2.726393211s]
INFO[2021-10-11T10:22:28Z] libx264: transcoding 2021/02/20210224_155558_DF90CC08.mp4 to avc
WARN[2021-10-11T10:22:28Z] metadata: unknown json in 4eb8280bc27bd3a21b7b67d02a7d2616ffdd2fda_exiftool.json
DEBU[2021-10-11T10:22:28Z] unknown json in 4eb8280bc27bd3a21b7b67d02a7d2616ffdd2fda_exiftool.json
DEBU[2021-10-11T10:22:28Z] metadata: exif not supported in 20210224_155432_606CE654.mov
DEBU[2021-10-11T10:22:28Z] media: exif not supported
```

**Comment by lastzero** [comment]
None of them say thumbnails could not be created. Nothing to worry about on first sight.

**Comment by lastzero** [comment]
I'm closing this for now. Let us know when you need any further help!

**Comment by jackbrown1993** [comment]
I am still seeing this issue on the latest preview build, I now have some more time to test. I am going to run the following commands again as I have a 110k+ library and want to make sure they are fully completed.

photoprism purge
photoprism convert
photoprism thumb

**Comment by lastzero** [comment]
This could also be related to faces in non primary files!?

**Comment by jackbrown1993** [comment]
Yes could be related to #1710 I am running the preview build which fixes #1710 and still see the broken thumbnails.

I have successfully run the purge command which has been completed:

```
INFO[2021-11-10T11:21:41Z] purged 1 file and 3 photos in 4m33.104825918s 
INFO[2021-11-10T11:21:41Z] closed database connection  
```

Currently running convert and seeing quite a few of these, have you seen this before?

```
WARN[2021-11-10T11:42:58Z] metadata: unknown json in be8ea7a49734d0a91caba06de0f44ad8817c9b77_exiftool.json 
DEBU[2021-11-10T11:42:58Z] unknown json in be8ea7a49734d0a91caba06de0f44ad8817c9b77_exiftool.json 
DEBU[2021-11-10T11:42:58Z] metadata: exif not supported in 20210401_164053_F261C738.mov 
```

**Comment by lastzero** [comment]
> Yes could be related to #1710 I am running the preview build which fixes #1710 and still see the broken thumbnails.

Alright, I'll take a look. Might be possible as you otherwise may open the related photo (= primary file) and don't see the expected face because it's a different crop.

> Currently running convert and seeing quite a few of these, have you seen this before?
> 
> ```
> WARN[2021-11-10T11:42:58Z] metadata: unknown json in be8ea7a49734d0a91caba06de0f44ad8817c9b77_exiftool.json 
> DEBU[2021-11-10T11:42:58Z] unknown json in be8ea7a49734d0a91caba06de0f44ad8817c9b77_exiftool.json 
> DEBU[2021-11-10T11:42:58Z] metadata: exif not supported in 20210401_164053_F261C738.mov 
> ```

exiftool should be able to create a json file with metadata from mov files, not sure why it's not working (you could try manually and see if there is an error). "exif not supported" is normal for a mov file and just a debug message.

**Comment by jackbrown1993** [comment]
Convert is now complete

`INFO[2021-11-11T11:37:21Z] converting completed in 1h23m44.60790024s `

Will run thumbs command and see where we are from there.

**Comment by lastzero** [comment]
Thanks! I'll wait for your feedback then.

**Comment by jackbrown1993** [comment]
Thumbs command complete:

`INFO[2021-11-11T12:58:35Z] thumbnails created in 1h0m17.314762177s `

During the command there were some errors for certain files, here is an example for some. Maybe the broken thumbnails are seeing errors. Lots of log output so would need to grep down, unless we can run thumbs command for individual images?

```
DEBU[2021-11-11T12:55:55Z] media: invalid JPEG format: short Huffman data in 20130308_185622_B7C180FA.jpg 
DEBU[2021-11-11T12:55:55Z] media: created no new thumbnails for 20130308_185622_B7C180FA [45.174736ms] 
ERRO[2021-11-11T12:55:55Z] resample: invalid JPEG format: short Huffman data
```

```
DEBU[2021-11-11T12:46:29Z] media: unexpected EOF in 20200801_000000_62EE01B9.jpg 
DEBU[2021-11-11T12:46:29Z] media: created no new thumbnails for 20200801_000000_62EE01B9 [43.989946ms] 
ERRO[2021-11-11T12:46:29Z] resample: unexpected EOF  
```

I believe the EOF error is related to Samsung Galaxy photo issue as described in #1407 however, I am yet to find a way to fix these files reliably, I can see there are issues with SOS data in the images but that's something I need to fix outside of Photoprism.

When opening the 'New' 'People' page, I can see the following in the server logs.

```
time="2021-11-11T13:26:31Z" level=debug msg="http: GET /people/new (200) [6.544103ms]"
time="2021-11-11T13:26:31Z" level=debug msg="http: GET /api/v1/ws (200) [4m26.220280603s]"
time="2021-11-11T13:26:31Z" level=debug msg="http: GET /api/v1/faces?count=999&offset=0&q=&hidden=&order=samples&markers=true&unknown=true (200) [24.408159ms]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/64b3da3f820e521e9359f90308afb6042e21e0f8-15e1770760b2/c2c535d2/tile_320 (200) [320.938µs]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/e4f0e8ba1a823640e84857a74c3403c42a28fb06-2b7089060090/c2c535d2/tile_320 (200) [242.772µs]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/8766d0e575be85f099ddf7ff94f9cec3f5873d18-24221b0870cb/c2c535d2/tile_320 (200) [297.992µs]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/6a010291f84fbd05dafe0620bd5c2a621e67be7e-0801a4055071/c2c535d2/tile_320 (200) [395.213µs]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/f3bd66acdc2fa3fbc738034244f92ffa7f91573e-0f308809306e/c2c535d2/tile_320 (200) [200.845µs]"
time="2021-11-11T13:26:32Z" level=warning msg="thumb: image: unknown format"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /api/v1/t/c329258289ad3995ed814e7e8fb5ff0709c4eab6-0ad1d8058076/c2c535d2/tile_320 (200) [313.512µs]"
time="2021-11-11T13:26:32Z" level=debug msg="http: GET /manifest.json?3c637fa8 (200) [4.297527ms]"
time="2021-11-11T13:26:34Z" level=debug msg="http: GET /sw.js (200) [872.266µs]"
```
The number of 'unknown format' errors (6) matches the number of broken thumbnails I see on that page. Clicking on one of the broken thumbnails, I see the photos as part of that identified face:

<img width="1401" alt="Screenshot 2021-11-11 at 13 28 11" src="https://user-images.githubusercontent.com/6218551/141306441-899bca6e-6591-4605-b158-688cd32afe1f.png">

Clicking the first photo from above I see "The image could not be loaded".

<img width="1681" alt="Screenshot 2021-11-11 at 13 29 03" src="https://user-images.githubusercontent.com/6218551/141306438-28382711-eb73-4838-8576-f21d4a1aa2e3.png">

Clicking on the link for 'The Image' shows a blank page.

<img width="1681" alt="Screenshot 2021-11-11 at 13 29 11" src="https://user-images.githubusercontent.com/6218551/141306431-fd708157-c39b-4a26-a066-8a5fdbdadec7.png">

**Comment by graciousgrey** [comment]
`resample: invalid JPEG format: short Huffman data `

This is normally a hint that the file itself is broken. 
Could you try to open  a file with this error using another tool to see if that works. 
I had files with this error in my collection and all of those have been broken due to incomplete transmission (The upper or lower part of the image was missing)

**Comment by lapo-luchini** [comment]
I have disabled thumbnails (I prefer to use CPU than HDD), could it be the reason I see no "face" thumbnail?
All `/api/v1/t/*/*/tile_320` links are HTTP 200 but 0 bytes in size.

**Comment by Molier** [comment]
> `resample: invalid JPEG format: short Huffman data `
> 
> This is normally a hint that the file itself is broken. Could you try to open a file with this error using another tool to see if that works. I had files with this error in my collection and all of those have been broken due to incomplete transmission (The upper or lower part of the image was missing)

Is there any best practice to deal with some images being 'broken' eg. being half grey and not complete, I am pushing photos on a schedule using photosync but dont want to repush my entire library to fix some images that have been broken. Also when testing it doesnt seem as if repushing them even works, since Photoprism already has those images and doesnt really 'update' them? any push in the right direction to fix that using some sort of workflow would be appreciated.

**Comment by graciousgrey** [comment]
@Molier Are you using our latest version? Some broken files that could not be displayed in previous versions of PhotoPrism are now displayed in PhotoPrism. If you want to replace a broken file, you must remove it from the original folder, for example, by [deleting](https://docs.photoprism.app/user-guide/organize/delete/). Otherwise, when you try to add the same file again, it will be skipped because it already exists.

**Comment by jean-louis67** [comment]
I know this topic is closed, but it just helped me today.
I have a collection of about 300 faces, and for several months at least, two thirds of the thumbnails had disappeared.
I came across this topic this morning and I ran purge (7 s), convert (7 mn) and thumbs (3h).
And I got all my thumbnails back!

For info, convert just transcoded two mov files to avc. There are 12000 photos.

Jean-Louis

**Comment by lastzero** [comment]
Sounds like thumbnail images in the /photoprism/storage/cache folder got lost, which may be due to a storage volume configuration  or permission error, or because a cleanup operation deleted the thumbnail files e.g. assuming the related originals don't exist anymore.
