### ISSUE TITLE
Simple password authentication

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#16]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/16)

PhotoPrism is for personal use but some form of auth would be great to protect it from guests using the same network etc.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($20.00)

### Submitted pull Requests
- [#150 feature/simple-password-authentication #16 Add acceptance test](https://issuehunt.io/r/photoprism/photoprism/pull/150)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by adeel41** [comment]
wondering if it would be a good idea to use OpenId here, so anyone who is hosting themselves can use their preferred or their existing OpenId Connect Server.

So instead of doing password authentication, may be we should just add support for OpenId Connect Client, and then using configuration, you can set which openId server you will use

**Comment by lastzero** [comment]
How shall I explain that to Laura? She knows a little bit Open Office, uses Facebook and has a dog.

**Comment by adeel41** [comment]
Tell her, not to worry much and do the best what she can do. I believe someone from community would create a PR if they would need this feature. Basically I was thinking on the same lines and thought it would be a good idea to share here.

**Comment by lastzero** [comment]
When users see a multi-user login, they will think it's super secure. Either a good solution or no solution. In the worst case you run multiple instances and share. You would also need to configure multiple paths etc... every time you import e.g. from a SD card, you need to decide into which collection... makes the whole thing much more complex and complicated.

**Comment by 0x46616c6b** [comment]
I like this idea to authenticate users. Maybe this library will solve the problem: https://github.com/markbates/goth

**Comment by m0t0k1ch1** [comment]
I found this issue on IssueHunt. Can I try to implement this?

**Comment by m0t0k1ch1** [comment]
If we use HTTP basic auth with gin, I think the following code is a good example.

https://github.com/gin-gonic/gin#using-basicauth-middleware

**Comment by lastzero** [comment]
Using a middleware is a good start. We can also chat if you like: @lastzero on Telegram or join #photoprism in the gophers Slack (see Wiki).

**Comment by lastzero** [comment]
To document what I've just written in the chat:

Not sure if basic auth works because of our API as we are using JS to access it... must be tested. Maybe it's better to work with a token that can be stored in `localStorage`. I've implemented something like that already (you can reuse the JS code, backend is written in PHP):

- https://github.com/symlex/symlex/blob/master/frontend/src/common/session.js
- https://github.com/symlex/symlex/blob/master/src/Service/Session.php

You'd have to implement a session endpoint like `/api/v1/session` for login and logout in Go that works in a similar way, see https://github.com/photoprism/photoprism/tree/develop/internal/api

Maybe https://github.com/gin-contrib/sessions is helpful for that (never used it before).

Ideally we find a mechanism that also works for other clients like smartphone apps that use our API 
in the future. Our Config must be extended with a password field:

- https://github.com/photoprism/photoprism/blob/develop/internal/context/config.go
- https://github.com/photoprism/photoprism/blob/develop/internal/commands/flags.go
- https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/config.go

We should use `http-password` (for the flag) / `HttpPassword()` (for the function) as we're also running a SQL server that can use a different password (that password would be `sql-password` then).

**Comment by forbesmyester** [comment]
Just came across this project.

I see we're primarily leveraging docker/docker-compose for installation. Therefore may I suggest an alternative of using [NGINX auth_request](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html) along with another tiny service to do the actual authentication (with whatever web service/services we desire).

For this project it may only exist as documentation / a sample `docker-compose.yml`, because the actual authentication service and NGINX configuration would be very loosely coupled to this project.

We do this at work to authenticate against Office365 auth services, the actual docker services themselves are completely unaware of the authentication.

**Comment by lastzero** [comment]
Many potential users want to run the final software as a single binary without Docker, so we can't just use a proxy. Also some sort of auth is required when we add sharing functionality later.

**Comment by forbesmyester** [comment]
Fair point about single binary, but you're already requiring MySQL, so it's not really just a single binary already...

I think you can do basic auth with only NGINX. It's certainly really easy to pass extra headers through to identify users.

Still presuming you still allow disabling auth, anybody can put what I describe in front of photoprism as a way to customize / harden / whatever. They'd just loose the identity for sharing.

**Comment by lastzero** [comment]
We use TiDB. Pure Go. MySQL ist just for testing. See https://blog.liquidbytes.net/2018/12/personal-photo-management/

**Comment by forbesmyester** [comment]
In which case I understand your preference and TiDB looks pretty interesting, even though I'm way more into Docker/Microservices than Go.

**Comment by alexkutsan** [comment]
Would be great to have the ability to provide read-only access to photos collection ( with no authentification) and provide the ability to delete\upload data if the user authenticated.

**Comment by lastzero** [comment]
@alexkutsan We will certainly build something like that, but want to finish albums and settings first.

**Comment by alexkutsan** [comment]
@lastzero  should it be a separate issue? Or you will implement it in the scope of this one?

**Comment by lastzero** [comment]
We'll add a new issue... But need to implement this first.
