### ISSUE TITLE
Videos: Hardware transcoding doesn't work with Intel GPUs

### ISSUE THREAD

**Issue by masterwishx** [photoprism/photoprism#1602]
Im using Photoprism Last ver Docker in Unraid (Linux x64)

Intel i5 4440 CPU (Haswell) and iGPU (intel GPU TOP installed + GPU Statistics Dockers)

after enabling " intel-graphics tensorflow-amd64-avx2 "
" enc -h264_qsv,buffer -64,bitrate -32 "
![image](https://user-images.githubusercontent.com/28630321/136194527-b90b69e0-0fe1-42ed-a852-79f465b8282d.png)

i can see on docker build - trying to install driver but then go previoce driver , so i see Quick Sync is not installed ?!?
also i see some warning and same libraries i tnk thta was befor enabling intel GPU.

![image](https://user-images.githubusercontent.com/28630321/136194472-3ac77a45-921f-4c03-ab56-29696e797d50.png)

is my config right or should i use vaapi instead ?

![image](https://user-images.githubusercontent.com/28630321/136195128-bc5b2dec-0585-4d52-995e-c50598f4a442.png)

**Comment by masterwishx** [comment]
Hmm with what GPUs is working ?

**Comment by lastzero** [comment]
From the reports on our most recent release, it is generally working now. I'll move ahead and close this. If you still have issue and are a sponsor, we can help via email (technical support).
