### ISSUE TITLE
Feature RQ: Increase local folder browsing to more than 999

### ISSUE THREAD

**Issue by casperse** [photoprism/photoprism#1603]
Hi

Hardware is progression fast and loading of thumbnails on a NVME drive is very fast
I have my photos arranged in
Photos/Year/Month/
And some like weddings would have more than 999 pictures
Is it possible to increase this value today? (Running a docker with MariaDB)

This is my 4th Photo docker solution and so far this is the absolute best - except some pictures are hidden when browsing through folders....

**Comment by lastzero** [comment]
Your browser can't handle that many images, we'll eventually build a timeline view. There's already an issue for that. In general, you may want to store less files in your folders as humans and other tools alike will have it easier to find something. It will also help performance.
