### ISSUE TITLE
There is no Face picture in some new Faces

### ISSUE THREAD

**Issue by masterwishx** [photoprism/photoprism#1604]
Using Last version of docker in Unraid (linux x64)

There is no face pictures in some of New Faces
People->New->Show all Faces.

![image](https://user-images.githubusercontent.com/28630321/136232988-96f0bf13-9f42-43f4-a17e-6078f002bc0f.png)

**Comment by lastzero** [comment]
~Happens when all matches for a face cluster have been removed / marked invalid. Update fixes this. Development Preview is currently building: https://docs.photoprism.app/getting-started/updates/#development-preview~

Just saw this is the Edit Dialog. Do you see any error? Seems the thumbs can't be rendered. Can you test our Development Preview?

**Comment by lastzero** [comment]
Do you see any error in the logs or JS console? We don't have any issues, so I don't know what to fix. You may want to try our next updated which will be released today!

**Comment by masterwishx** [comment]
i checked the new version and did reindex, but having same error on 18 pictures ...

from docker log : 
![image](https://user-images.githubusercontent.com/28630321/136462286-977e5b05-fe52-475e-b6ce-e96f960475f9.png)
![image](https://user-images.githubusercontent.com/28630321/136462353-e1067b47-09bd-48ce-9d2f-156f5eb458f6.png)

from console of chrome dev tools next error: 

all:1 Unchecked runtime.lastError: The message port closed before a response was received.
all:1 Unchecked runtime.lastError: The message port closed before a response was received.
app.js?1d943bb9:2 websocket: connected
app.js?1d943bb9:2 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
bind @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ce @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ce @ app.js?1d943bb9:2
f @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
app.js?1d943bb9:2 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
bind @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ce @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ce @ app.js?1d943bb9:2
f @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took <N>ms
[Violation] 'setInterval' handler took <N>ms
SymWaxCS.js:323 [Violation] 'setTimeout' handler took 117ms
tile_320:1 GET https://photo.......com/api/v1/t/*****/****/tile_320 404
Image (async)
loadImage @ app.js?1d943bb9:2
init @ app.js?1d943bb9:2
mounted @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
Xt @ app.js?1d943bb9:2
insert @ app.js?1d943bb9:2
C @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
e._update @ app.js?1d943bb9:2
i @ app.js?1d943bb9:2
dn.get @ app.js?1d943bb9:2
dn.run @ app.js?1d943bb9:2
un @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
dn.update @ app.js?1d943bb9:2
ue.notify @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
hn.set @ app.js?1d943bb9:2
updateItem @ app.js?1d943bb9:2
updateItemsState @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
e.$nextTick @ app.js?1d943bb9:2
internalValue @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
dn.run @ app.js?1d943bb9:2
un @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
dn.update @ app.js?1d943bb9:2
ue.notify @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
hn.set @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
updateSingle @ app.js?1d943bb9:2
updateInternalValue @ app.js?1d943bb9:2
onClick @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
e.$emit @ app.js?1d943bb9:2
toggle @ app.js?1d943bb9:2
click @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
n @ app.js?1d943bb9:2
Hi.o._wrapper @ app.js?1d943bb9:2
app.js?1d943bb9:2 [Vuetify] Image load failed

src: /api/v1/t/******/******/tile_320

found in

---> <VImg>
       <VCard>
         <PTabPhotoPeople>
           <VTabItem>
             <VTabsItems>
               <ThemeProvider>
                 <VTabs>
                   <VCard>
                     <ThemeProvider>
                       <VDialog>
                         <PPhotoEditDialog>
                           <PNavigation>
                             <VApp>
                               <Photoprism>
                                 <Root>
a @ app.js?1d943bb9:2
onError @ app.js?1d943bb9:2
error (async)
loadImage @ app.js?1d943bb9:2
init @ app.js?1d943bb9:2
mounted @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
Xt @ app.js?1d943bb9:2
insert @ app.js?1d943bb9:2
C @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
e._update @ app.js?1d943bb9:2
i @ app.js?1d943bb9:2
dn.get @ app.js?1d943bb9:2
dn.run @ app.js?1d943bb9:2
un @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
dn.update @ app.js?1d943bb9:2
ue.notify @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
hn.set @ app.js?1d943bb9:2
updateItem @ app.js?1d943bb9:2
updateItemsState @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
e.$nextTick @ app.js?1d943bb9:2
internalValue @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
dn.run @ app.js?1d943bb9:2
un @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ye @ app.js?1d943bb9:2
Promise.then (async)
Ge @ app.js?1d943bb9:2
et @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
dn.update @ app.js?1d943bb9:2
ue.notify @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
hn.set @ app.js?1d943bb9:2
set @ app.js?1d943bb9:2
updateSingle @ app.js?1d943bb9:2
updateInternalValue @ app.js?1d943bb9:2
onClick @ app.js?1d943bb9:2
(anonymous) @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
e.$emit @ app.js?1d943bb9:2
toggle @ app.js?1d943bb9:2
click @ app.js?1d943bb9:2
Ue @ app.js?1d943bb9:2
n @ app.js?1d943bb9:2
Hi.o._wrapper @ app.js?1d943bb9:2

**Comment by masterwishx** [comment]
also today i see in log when viewing new faces without picture in people next error:

![image](https://user-images.githubusercontent.com/28630321/136508352-8c85b8da-da47-4ac7-b99f-b40974a59b55.png)

**Comment by lastzero** [comment]
Did these files change, so that the sha1 hash is not the same anymore? Is your disk full? Permission issues?

**Comment by lastzero** [comment]
This error is shown when a generated face thumbnail image could not be written to the cache folder:

https://github.com/photoprism/photoprism/blob/6c2245d2ffc7b6088044786122d17eaa139473d7/internal/crop/request.go#L59

**Comment by masterwishx** [comment]
> Is your disk full? Permission issues?
Disk is not full

> could not be written to the cache folder
So how to fix it ?

i didnt make any changes to cache folder, its by default in config directory ...

i only changed database in mariaDB to utf8mb4 from utf (like in documetation) some time ago,
and added " intel-graphics tensorflow-amd64-avx2 " , "h264_qsv"

do i need to enable experemental futures also for tensorflow and intel grafics?
is it right setting ?
![image](https://user-images.githubusercontent.com/28630321/136659246-7ce7edeb-b991-4aa3-a93b-77bafbc26cbe.png)

**Comment by lastzero** [comment]
Would you mind running chmod / chown to make sure PhotoPrism has read & write permissions for the cache folder and all sub-folders? Just in case, before we spend more time debugging further. Also make sure the disk is not full. That's the typical reason for these errors.

**Comment by masterwishx** [comment]
OK, Pleae wait ...

**Comment by lastzero** [comment]
Also make sure you didn't run out of filesystem [inodes](https://en.wikipedia.org/wiki/Inode).

**Comment by masterwishx** [comment]
the disk with photoprism docker 578GB Free ,For Photo 1.27GB Free.


![image](https://user-images.githubusercontent.com/28630321/136659651-88e97b7c-adf9-4d1d-a1ff-571f0a5d56e6.png)

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/136659688-b3090587-76e9-4566-9805-700550d58d33.png)

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/136659776-ab364f41-de17-4552-b664-0ede7eebc284.png)

**Comment by lastzero** [comment]
What does `df` say?

**Comment by masterwishx** [comment]
I think i founded problem but need to check it more ... 
photoprism was somehow mounted to /mnt/disk1/appdata/photoprism instead of /mnt/user/appdata/photoprism/
but it worked OK on 2 versions ago i think.
when changed to /mnt/user/appdata/photoprism/ the error of caching is gone , i will check it again ....
still have maybe 2 photos blank but with user name, but no new faces and no error of caching,only error in dev tools that i posted.
so it was permissions issue i think.

**Comment by masterwishx** [comment]
![image](https://user-images.githubusercontent.com/28630321/136671000-35c611ed-fb69-4765-b085-0ce09a6b26c8.png)

can you please check my intel grafics setting i think its not working on h265_qsv ?!?

![image](https://user-images.githubusercontent.com/28630321/136671042-1f27e1b5-fd2b-4103-ad86-6fc9a2a46a94.png)

![image](https://user-images.githubusercontent.com/28630321/136671028-f8e3cafd-37df-4e32-99fc-ada157ae6516.png)
