### ISSUE TITLE
URI

### ISSUE THREAD

**Issue by nef78** [photoprism/photoprism#1607]
Hello.

After update, i have this error.
My address is repeated in requests
1. console log:
app.js?13622590:2 WebSocket connection to 'wss://**photo.mydomen.ru**photo.mydomen.ru/api/v1/ws' failed: 
o.open @ app.js?13622590:2
(anonymous) @ app.js?13622590:2
app.js?13622590:2 websocket: disconnected
onclose @ app.js?13622590:2
n.onclose @ app.js?13622590:2
app.js?13622590:2 websocket: reconnecting
app.js?13622590:2 WebSocket connection to 'wss://photo.mydomen.ruphoto.mydomen.ru/api/v1/ws' failed: 
o.open @ app.js?13622590:2
(anonymous) @ app.js?13622590:2
app.js?13622590:2 websocket: disconnected
onclose @ app.js?13622590:2
n.onclose @ app.js?13622590:2
app.js?13622590:2 websocket: reconnecting
...

2. route:
https://photo.mydomen.ru/photo.mydomen.ru/albums

**Comment by lastzero** [comment]
That's normal while your instance is restarting, e.g. after an update. Means the frontend can't connect to the backend. If the problem persists and you're using a proxy in front of PhotoPrism, please check your settings so that Websocket connections won't be blocked.

**Comment by nef78** [comment]
My address is duplicated in the address bar, this is normal?
Expected result: 
https://photo.mydomen.ru/albums
Actual result: 
https://photo.mydomen.ru/photo.mydomen.ru/albums

I comment this and now it works correctly:
PHOTOPRISM_SITE_URL: "photo.mydomen.ru"        # Canonical / public site URL

**Comment by lastzero** [comment]
The URL must start with `https://` or `http://`

**Comment by nef78** [comment]
Thanks!
It works!!!
