### ISSUE TITLE
Albums: Group States by Country

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#1608]
Right now states are named `state / country`, which makes the sorting a bit messy. I would suggest to change the default naming to `country / state`, so that the states are nicely grouped by country.

**Comment by lastzero** [comment]
Started another Development Preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview

Note you need to index once or run the moments command in a terminal to refresh album metadata.

**Comment by kvalev** [comment]
Perfect, looks very good!

I noticed one minor UI inconsistency with the location pin icon. When clicking on the pin icon underneath a photo it links to the places UI with all nearby photos nicely visualized. However the pin icon on the states UI opens the edit album dialogue. Not a big deal tho.
