### ISSUE TITLE
Folders: Names listed in .ppignore should be ignored

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#1609]
When you click on the dropdown on the library index page, PhotoPrism will recursively crawl through all folders in originals and will create `folder` albums for every single one, even for paths which should be ignored by ppignore.

**Comment by graciousgrey** [comment]
Thanks for reporting!

**Comment by lastzero** [comment]
Ignore list wasn't properly initialized. Note that this fix won't remove existing folders from the index, just like files that are ignored after they were indexed already. This is to avoid terrible mistakes with wildcards (users - or their kids - might mistakenly add an `.ppignore` file with `*` to the originals folder, thus removing everything).

**Comment by kvalev** [comment]
Thx for the quick fix!

**Comment by lastzero** [comment]
You're welcome!
