### ISSUE TITLE
Default admin password

### ISSUE THREAD

**Issue by wtrdk** [photoprism/photoprism#161]
Hi,

I've successfully spun up the docker image, and it works great! But what is the default admin password?
Can't seem to find it anywhere (or did I overlook it?)

Thanks!

**Comment by lastzero** [comment]
I've added the parameter to our example config, you can also type `photoprism config` to see all config values. Maybe we should add this to the docs on docs.photoprism.org too?

**Comment by wtrdk** [comment]
That was fast! ;-)
Thanks!

**Comment by lastzero** [comment]
You're welcome! If you like this project and can afford it, please consider a [donation](https://github.com/photoprism/photoprism/blob/develop/SPONSORS.md) so that we can continue doing this in January and don't need to take a break again :)
