### ISSUE TITLE
TIFF: Support all features

### ISSUE THREAD

**Issue by iwinstar** [photoprism/photoprism#1612]
version: 211007-8f55d6f8-Linux-x86_64 (latest)

detail logs:

```
INFO[2021-10-09T07:51:37Z] tiff: converting photo-1415886541506-6efc5e4b1786.tiff to jpg
ERRO[2021-10-09T07:51:38Z] resample: can't open photo-1415886541506-6efc5e4b1786.tiff
WARN[2021-10-09T07:51:38Z] index: failed converting photo-1415886541506-6efc5e4b1786.tiff to jpeg (tiff: invalid format: not enough pixel data)
INFO[2021-10-09T07:52:33Z] tiff: converting photo-1584886781099-0664a292d9b0.tiff to jpg
ERRO[2021-10-09T07:52:33Z] resample: can't open photo-1584886781099-0664a292d9b0.tiff
WARN[2021-10-09T07:52:33Z] index: failed converting photo-1584886781099-0664a292d9b0.tiff to jpeg (tiff: unsupported feature: color model)
```

"tiff: unsupported feature: color model" seems easy to fix:
https://github.com/photoview/photoview/issues/242

"tiff: invalid format: not enough pixel data" no idea how to fix it.

I also provide those two photos for you guys to test. Thanks.

**Comment by iwinstar** [comment]
~~each photo is 40MB+, seems too large to directly upload under this issue, any other way?~~

[Photos.zip](https://github.com/photoprism/photoprism/files/7315239/Photos.zip)
[Photos.z01.zip](https://github.com/photoprism/photoprism/files/7315246/Photos.z01.zip)
[Photos.z02.zip](https://github.com/photoprism/photoprism/files/7315247/Photos.z02.zip)
[Photos.z03.zip](https://github.com/photoprism/photoprism/files/7315248/Photos.z03.zip)

After download those files,

rename Photos.z01.zip to Photos.z01
rename Photos.z02.zip to Photos.z02
rename Photos.z03.zip to Photos.z03

Then decompress Photos.zip

**Comment by lastzero** [comment]
I trust that some TIFF files can't be decoded... that's the full TIFF spec: https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf

The Go authors didn't implement all of it. We don't have the financial resources either if Google doesn't.

**Comment by maxammann** [comment]
We actually could use Darktable for conversion from TIFF to JPEG.

**Comment by iwinstar** [comment]
```
root@nas:/photoprism# darktable-cli originals/photo-1415886541506-6efc5e4b1786.tiff a.jpg
[rawspeed] (photo-1415886541506-6efc5e4b1786.tiff) rawspeed::RawImage rawspeed::RawDecoder::decodeRaw(), line 273: const rawspeed::TiffIFD* rawspeed::TiffIFD::getIFDWithTag(rawspeed::TiffTag, uint32_t) const, line 219: failed to find 1 ifs with tag 0x828e
[export_job] exported to `a.jpg'

root@nas:/photoprism# darktable-cli originals/photo-1584886781099-0664a292d9b0.tiff b.jpg
[export_job] exported to `b.jpg'
```
photo-1415886541506-6efc5e4b1786.tiff  45MB(tiff) -> 12MB(jpg)
photo-1584886781099-0664a292d9b0.tiff 42MB(tiff) -> 4.3MB(jpg)

It seems fine for me.

**Comment by maxammann** [comment]
[raw0037.tif.xmp.zip](https://github.com/photoprism/photoprism/files/7635407/raw0037.tif.xmp.zip)

Nice, here is another example which works and has a corresponding xmp file.

**Comment by CDeLeon94** [comment]
What's the solution for now, manually convert via darktable-cli?
Does that just leave the originals un-index and un-imported, with only the conversions being present within photoprism?

**Comment by lastzero** [comment]
The solution would be to have time to build one, which we don't have at the moment. This issue has not received much attention from users, so it has not been a top priority for us, given the number of other requests. A few lines of code should resolve it if you use an external converter instead of the built-in TIFF library (don't ask me why Google didn't implement all the TIFF features, maybe they ran out of money).

**Comment by lastzero** [comment]
It would be very helpful to have file samples available for testing, see our contact page for details:

<https://photoprism.app/contact>

Edit: Sorry, just saw you already added a ZIP with samples! Thank you :)

**Comment by lastzero** [comment]
@iwinstar @CDeLeon94 @maxammann Since we added support for the ImageMagick "convert" command to support vector formats (see issue #2207), it is possible that previously unsupported TIFF files will work now.

The [upcoming preview](https://docs.photoprism.app/release-notes/#development-preview) build `230213-32483cc88` can be used for testing. Your help is much appreciated!

**Comment by jult** [comment]
Wow. You may want to add that TIFF are not supported. Went through the non-docker install, only to find none of my images get shown. I realize this is free open source software, but come on. At least warn users beforehand. Piwigo to the rescue then. Geez.

**Comment by lastzero** [comment]
If you don't use our Docker image, please make sure to install the recommended dependencies including ImageMagick to ensure full file format support. See the "Dependencies" section of our package installation docs for more details:

https://dl.photoprism.app/pkg/linux/README.html

Thank you very much! :heart:
