### ISSUE TITLE
Enhancement: Index in background?

### ISSUE THREAD

**Issue by nautatva** [photoprism/photoprism#1613]
When uploading a photo, upload is quick, but time is taken for indexing. We should perhaps have indexing in background so that particular tab can be closed without worrying about losing any upload.

![image](https://user-images.githubusercontent.com/28155271/136672901-fa2333e3-2753-489f-919f-780044874e20.png)

**Comment by lastzero** [comment]
How may files did you upload!? Import (not just indexing but a move operation from the uploads to the originals folder) in fact happens in the background. However, users may want to get feedback in case the NSFW filter is active or there are other issues. Asking them to always check the logs asynchronously is not really user friendly. If you want to upload lots of files and you don't care about getting instant feedback, you may want to use WebDAV with auto index instead?

**Comment by lastzero** [comment]
Also, you can of course open a second or third browser tab to do other things... it's not like PhotoPrism is single threaded like early Windows versions 👯

**Comment by nautatva** [comment]
Understand, I uploaded just 1 file to test and observed this. Will use webDav then :D
