### ISSUE TITLE
Error while indexing photos with date before 1970

### ISSUE THREAD

**Issue by baembel08** [photoprism/photoprism#162]
Hi,
first of all I want to express big thanks to the work that was done during the last days. Good work!

I get error messages while indexing pictures 

[35m(/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:33)[0m 
[33m[2019-12-17 16:14:38][0m [31;1m Error 1364: Field 'photo_id' doesn't have a default value [0m

[35m(/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:33)[0m 
[33m[2019-12-17 16:14:38][0m [31;1m Error 1364: Field 'photo_id' doesn't have a default value [0m

[35m(/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:33)[0m 
[33m[2019-12-17 16:14:38][0m [31;1m Error 1364: Field 'photo_id' doesn't have a default value [0m

[35m(/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:33)[0m 
[33m[2019-12-17 16:14:38][0m [31;1m Error 1364: Field 'photo_id' doesn't have a default value [0m

[35m(/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:33)[0m 
[33m[2019-12-17 16:14:38][0m [31;1m Error 1364: Field 'photo_id' doesn't have a default value [0m

Only 4 out of 12 photos were indexed, so the local path should be correctly mapped.

I'm using  the latest docker image. If you need further information, please ask.

**Comment by lastzero** [comment]
Did you create a new database?

See https://twitter.com/browseyourlife/status/1206833437514043393

**Comment by baembel08** [comment]
I've started from scratch: latest docker image from yesterday, new container and new import and indexing of photos, but error messages still remain.  When updating the image for existing containers: Can I recreate the database with photoprism migrate command ?

Is indexing also depending on succcesfull reverse geocoding ?

**Comment by lastzero** [comment]
You can simply delete the files in the resources/database directory if you use the built-in server. Server should not run while doing this, not sure what happens if it keeps running. Probably panic or will create new files again.

![Screenshot 2019-12-18 at 14 19 25](https://user-images.githubusercontent.com/301686/71089583-7d11ef00-21a1-11ea-885c-205398b9a89d.png)

Maybe an issue with our optimized indexer, but need some more time / information to figure this out.

Certainly `photo_id` should not be empty if you want to add labels to a photo. Makes sense.

**Comment by lastzero** [comment]
If you think this is an issue specifically with your files, we would appreciate a sample (ideally upload it and send the download URL, either here or private via email to hello@photoprism.org).

**Comment by baembel08** [comment]
I guess, I've found a hint: Some of my (scanned  from original) photos are older than the date 01.01.1970., so for example: 25.08.1967 12:00:00. As I know the unix timestamp so far, it starts at the described date.

One error message is:
(/go/src/github.com/photoprism/photoprism/internal/photoprism/indexer_mediafile.go:174)
[2019-12-18 15:54:38]  Error 1292: invalid time format: '{1967 8 25 11 0 0 0}'

**Comment by lastzero** [comment]
@baembel08 Would you be able to provide us with an example file? Otherwise it will be a ping-pong with many test releases until we fixed it. Or you send a pull request with a fix :)

**Comment by baembel08** [comment]
yep, I'll prepare.

**Comment by lastzero** [comment]
@baembel08 Thank you very much! I'll take a look tomorrow :)

**Comment by baembel08** [comment]
Everything is OK now, work is done!
