### ISSUE TITLE
Option to submit corrections to auto tagging to improve detection / confidence ratings.

### ISSUE THREAD

**Issue by SiJiL82** [photoprism/photoprism#1621]
Not sure if this is possible with the automatic labelling tech you're using, but it would be great if we could optionally submit info that can be used to help improve the detection and confidence ratings.
For example:
1. If I have a picture of my dog, and it labelled it as "Cat" (or in one instance "Fish"!!) and I manually remove the Cat label and add Dog, a way to submit that information - either the picture itself, or whatever meta data it needs, and the label I've added.
2. If I have a picture of my dog, and it is labelled as "Dog" but with only a 25% confidence rating, the option to submit the data and say "Yes, this is 100% a dog"

**Comment by lastzero** [comment]
In theory yes, in practice the model is static for now as we can't afford a data scientist doing that. When we are done with multi user support, there are already the next items waiting for us on the roapmap, like batch edit. So no time to train models based on user feedback unless somebody contributes that. It's more than I would ask for as maintainer. Maybe next year or the year after when our funding improves.

**Comment by graciousgrey** [comment]
Here is the ticket for training the model: https://github.com/photoprism/photoprism/issues/448
