### ISSUE TITLE
UX: Memory consumption warning in Safari

### ISSUE THREAD

**Issue by skavans** [photoprism/photoprism#1623]
Hey folks,

Safari shows "This Webpage is using Significant Memory in Safari" message every time I use the PhotoPrism. And forcibly reloads the page after time.

It just a little bit depends on how far I'm scrolling the feed. Sometimes I can just simply navigate the sidebar items several times and the message appears.

I don't know if it's possible to beat this somehow though.

<img width="1016" alt="Снимок экрана 2021-10-13 в 22 57 13" src="https://user-images.githubusercontent.com/6472406/137204600-e1eb11aa-0f49-4e6a-ba12-2da07572041a.png">

**Comment by lastzero** [comment]
Safari is right in that images and videos consume a lot of memory, in the browser and in the backend as well. We'll optimize this in future releases. It's also Apple's responsibility to reduce memory usage. HTML is a descriptive language, we don't tell Apple how to manage the memory. Won't come up with a solution by tomorrow. Is it possible to disable the warning or to use a different browser?

**Comment by skavans** [comment]
> Is it possible to disable the warning or to use a different browser?

Sure, not a huge problem for me. Just wanted to let you know.

**Comment by lastzero** [comment]
Thanks! 🌈

**Comment by graciousgrey** [comment]
Released since no problems were reported!
