### ISSUE TITLE
Incorrect Apple live photo processing 

### ISSUE THREAD

**Issue by skavans** [photoprism/photoprism#1624]
When a live photo (HEIC image + HVC1 MOV video) is uploaded into PhotoPrism, the main photo in the PhotoPrism gallery isn't the original HEIC converted into JPEG but the MOV thumbnail for some reason.

So it looks like the following:
![20200508_113043_5F6FC86E mov](https://user-images.githubusercontent.com/6472406/137288112-dba5e54e-70be-44fe-a871-d4ff471a104b.jpg)

Whereas the original image looks like below:
![20200508_113050_C0150F25](https://user-images.githubusercontent.com/6472406/137288623-b2e48cec-78a8-416a-b9da-74e081d2f842.jpg)
(it's the HEIC I manually converted into JPEG to be able to attach it here)

If I download such photo from the PhotoPrism, I get the following files:
- photo.heic (original photo)
- photo.mov (original live video)
- photo.mov.jpg (the one I see in the gallery).

I believe the last file should be `photo.heic.jpg`.

**Comment by lastzero** [comment]
Aware of that, see #926 and #1028. Given how often this was reported, I'll move it to development now! :stuck_out_tongue_winking_eye:
