### ISSUE TITLE
People: choose which face appears as thumbnail for that person

### ISSUE THREAD

**Issue by janwillemb** [photoprism/photoprism#1625]
As a user I want to select which face appears as the thumbnail picture for a person.

Sometimes a face is recognized multiple times in a picture, so this could be an option next to the "eject" button on the faces on the "People" tab.

**Comment by graciousgrey** [comment]
This will be part of https://github.com/photoprism/photoprism/issues/383 :)

**Comment by graciousgrey** [comment]
Or do you want to change the face thumbnails on the edit dialog?

**Comment by janwillemb** [comment]
I think I agree this is a duplicate of #383
