### ISSUE TITLE
Uploading Images to Demo

### ISSUE THREAD

**Issue by shortgame11** [photoprism/photoprism#1629]
Not sure if its correct to post this here specifically. It appears uploading images to the demo is possible and there are some interesting things there. Nothing too bad as it stands but maybe its a bit risky going forward? I'm not sure. Regardless, the demo getting cluttered with junk wouldn't be great. Does it reset every x hours? Potentially a non issue just thought I'd mention it.

**Comment by lastzero** [comment]
Thanks! Happens from time to time. Restarted.
