### ISSUE TITLE
Slideshow on selected images/folder

### ISSUE THREAD

**Issue by H4dr1en** [photoprism/photoprism#1630]
Hi, 

First, thanks a lot for this wonderful tool!

I have a library of photos on my local computer organized by years/months using folders/subfolders. I would like to use PhotoPrism to select some of the folders/subfolders in the `/folders` or `/library/files` views and start a slideshow of the selection (all the images inside the selected folders/subfolders). 

My use-case is: I want to view some photos from 2020 and 2019 only in a slideshow. I also tried to used search filters in the Search view: `year:2019|2020` but some images don't have the date attributes so they are not included in the search results.

Currently, I can achieve what I want by:
- going into the `/folders` view
- select the folders I want to visualize
- create a temporary album out of the selection
- go to the album
- start the slideshow

I was wondering if there was an easier way already existing for this use case, or if it would be possible to extend PhotoPrism to allow to start a slideshow from any manual selection of multiple folders/images

**Comment by graciousgrey** [comment]
There is no option yet to select multiple folders/albums and start a slideshow for them. 

You can use the path search filter for this:

`path:"2020/06|2021/july|2019/05"` it works with wildcards as well: `path:"2020/*|2021/*"`

(https://docs.photoprism.org/user-guide/organize/search/#search-filter-overview)

I hope this helps!

**Comment by H4dr1en** [comment]
Thank you, yes this helps a lot!

I have a follow-up question: I would like to import my photos library in PhotoPrism, and create one album per subfolder (eg. 2020/Christmas). I have many subfolders and doing it manually would take me hours. Is there an easier way to do it?

**Comment by graciousgrey** [comment]
If you index your originals (https://docs.photoprism.org/user-guide/library/) and you have folders like 2020/christmas and 2021/christmas those appear as folder-albums in the folder section (like here: https://demo.photoprism.org/folders). Folder-Albums behave just like user generated albums.

**Comment by H4dr1en** [comment]
Super, thanks a lot @graciousgrey !

**Comment by graciousgrey** [comment]
You're welcome :)
