### ISSUE TITLE
RAW: Upgrade Darktable to 3.6.x

### ISSUE THREAD

**Issue by Belphemur** [photoprism/photoprism#1632]
Hello,

I've got a couple of RAW files that didn't get converted properly to JPG because the version of darktable is too old.

I'm using the docker image ('photoprism/photoprism:latest') with the docker-compose setup on Digital Ocean.

I couldn't find a place where darktable is installed in the docker image. I would love to make a quick PR to update the version of darktable.

I found this information on the documentation
> We've recently upgraded Darktable from 2.6.2 to 3.0.0. Since the old PPA is not maintained anymore, we switched to this repository that is hosted by SuSE

But I can't find any mention of the repository in the dockerfile.
Also, that repo comes with 3.7~preview.

# Mingled image
![fit_2048](https://user-images.githubusercontent.com/197810/137637521-00aadcef-3b16-4bf8-a154-18978c1dd47c.jpg)

## How it looks in darktable 3.6.1
![image](https://user-images.githubusercontent.com/197810/137637538-e7ba509f-346e-4a9b-bf83-c2ca95b1e84c.png)

**Comment by lastzero** [comment]
We will upgrade to Ubuntu 21.10 next, which includes Darktable 3.6.0:

  https://packages.ubuntu.com/impish/darktable

Please give us one or two weeks for this as working on multi-user support has priority right now. Of course you can manually install an updated package in the Docker container. Many unofficial repositories don't have packages for ARM (Raspberry Pi), so it's easier for us to use the official Ubuntu packages. Also this avoids dependency version conflicts and may reduce the Docker image size.

**Comment by lastzero** [comment]
Is it critical to have 3.6.1 instead of 3.6.0?

**Comment by Belphemur** [comment]
@lastzero I don't think there are many changes between 3.6.0 and 3.6.1.

Btw, I think you shouldn't rely on the distrib to keep the package up to date.

It seems darktable provide its own packaging for stable version:
https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

I can update the dockerfile to use this if you want, I know you already have so much to do.

Edit: I see what you mean by not having ARM packages, that quite an issue.

**Comment by Belphemur** [comment]
I've opened an issue with darktable to see if they could provide ARM package in their repo.

This would solve everything :)

**Comment by lastzero** [comment]
Right... it's Sunday evening and I'm still working, no end in sight! 😜 

Official packages provided by the Darktable team would be great.

We had versions from external repositories, but ended up using the distribution packages as it's not acceptable that our build randomly breaks when the repository maintainer thinks it's now a good time to remove or break packages. Also we need ARM packages. Once we have the resources to make a full time job out of selecting & testing alternative packages, we are happy to do it.

**Comment by SimplyCorbett** [comment]
It'd be great if this also fixed proraw files not showing up correctly but based on their issue trackers that's not fixed yet.

![firefox_REFgXfIO3y](https://user-images.githubusercontent.com/7935624/137726884-19726b12-5e38-4a8e-934d-c85e933e3ab5.jpg)

**Comment by Belphemur** [comment]
So basically, darktable team isn't the one managing the OpenSuse repository.

Even if they say it's a supported way to install it.
I'll need to find who's in charge of the repository because it's impossible to find from the OpenSuse repo page.

**Comment by duichwer** [comment]
@Belphemur are you looking for this overview page?
https://build.opensuse.org/project/users/graphics:darktable
I only do not know how to get in contact with the maintainers

**Comment by Belphemur** [comment]
@duichwer Thanks I've missed that page, I've googled a little bit and found the email of one of the maintainer, I've contacted him.

**Comment by lastzero** [comment]
Our Development Preview has been upgraded so that you can at least use 3.6.0 for now:

https://docs.photoprism.org/getting-started/updates/

**Comment by Belphemur** [comment]
Worked for me :)
Also @cryptomilk do you think it would be possible to have ARM in the OpenSuse repositories ?

**Comment by lastzero** [comment]
Removed CR3 and DNG from the Darktable file extension blacklist. Keeping Fujifilm RAF as I wasn't able to figure out if it is supported now (help welcome).

**Comment by lastzero** [comment]
There's a new preview build based on Debian Bullseye available: It includes Darktable 3.8 instead of 3.6. Might fix problems with new formats like Apple ProRAW.

**Comment by sumsumsums** [comment]
The Debian Bullseye build doesn't work for me with CR3 files. Seems exiv2 needs to be version 0.27.4 for support of CR3 in darktable. But in Debian Bullseye it is just version 0.27.3

**Comment by lastzero** [comment]
Just noticed this myself. Thanks for looking it up! From what I see, exiv2 has a vulnerability and should be updated anyway. Maybe there is a backport available?

**Comment by sumsumsums** [comment]
I think darktable must be compiled with the right version. However, i now installed the debian 11 version of darktable from the opensuse repository -> https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable

Update script:

```
#!/bin/bash

apt-get update
apt-get install sudo gpg

echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/graphics:darktable.list
curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null

apt-get update
apt-get install darktable
```

Docker command: docker exec -i photoprism bash < update_darktable.sh

**Comment by lastzero** [comment]
@sumsumsums Does the SuSE version work for you, i.e. are CR3 files supported?

**Comment by sumsumsums** [comment]
Yes, works perfect

**Comment by lastzero** [comment]
New images are currently being built. Please note that SuSE does not offer an ARM64 version, so CR3 only works on Intel/AMD CPUs at the moment.

**Comment by giacy86** [comment]
> I think darktable must be compiled with the right version. However, i now installed the debian 11 version of darktable from the opensuse repository -> https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable
> 
> 
> 
> Update script:
> 
> 
> 
> ```
> 
> #!/bin/bash
> 
> 
> 
> apt-get update
> 
> apt-get install sudo gpg
> 
> 
> 
> echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/graphics:darktable.list
> 
> curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null
> 
> 
> 
> apt-get update
> 
> apt-get install darktable
> 
> ```
> 
> 
> 
> Docker command: docker exec -i photoprism bash < update_darktable.sh
> 
> 

Hi all. I have followed these steps but I still have wrong thumbnails for Apple ProRAW. How can I check the darktable version inside photoprism docker? I use photoprism with docker-compose.

Thanks for support

**Comment by lastzero** [comment]
As far as I know, ProRAW support is still in development (feel free to talk to the developers and maybe support them):
- https://github.com/darktable-org/darktable/issues/7578
