### ISSUE TITLE
Correct way to backup heic portrait shots from iphone?

### ISSUE THREAD

**Issue by SimplyCorbett** [photoprism/photoprism#1634]
Any image with E in the filename (portrait shots with background blur) transfer from my iphone to windows corrupted.

There are two such images on the phone. One is without background blur and one is with background blur (E in filename).

I'd like to preserve these images. Google photos is able to somehow do this correctly when using the photos app, but not once these images are transferred over to my pc.

When trying to import into photoprism the following error is thrown:

`metadata: scan-data is unbounded; EOI not encountered before EOF in IMG_E0380.HEIC (parse jpeg) `

What is the current method of backing these files up using photoprism?

**Backing up via iphone on safari works. But the exif data is not present.**

![firefox_Z7uQsrWS47](https://user-images.githubusercontent.com/7935624/137640836-3f018819-a61a-4e09-982f-2084ddf7098e.png)

**Comment by SimplyCorbett** [comment]
Here is an example image which I don't mind providing.

[IMG_E0259.zip](https://github.com/photoprism/photoprism/files/7360771/IMG_E0259.zip)

**Comment by lastzero** [comment]
That's strange, looks like the file extension is wrong... HEICs shouldn't get parsed as JPEG!?

**Comment by SimplyCorbett** [comment]
> 
> 
> That's strange, looks like the file extension is wrong... HEICs shouldn't get parsed as JPEG!?

Yeah I don't really understand either. Here is the only other error:

`import: invalid JPEG format: short Huffman data in 20211017_183125_77FA6B37.heic (resample) `

**Comment by lastzero** [comment]
Does it work when you change the extensions? Use exiftool to check the file type and metadata.

**Comment by SimplyCorbett** [comment]
No, changing the extension to .jpg results in the same error. Exiftool shows it as a jpeg.

Apple is doing some weird shenanigans.

**Comment by lastzero** [comment]
Maybe there's a JPEG embedded in the HEIC file or the other way? Apple sometimes converts or modifies files "on the fly" when importing / exporting, so the actual image file on your phone may be different from what ends up on your computer. We recommend PhotoSync for backing up iOS and Android devices.

**Comment by graciousgrey** [comment]
> Backing up via iphone on safari works. But the exif data is not present.

Changing your phone settings might help here: https://stackoverflow.com/questions/57942150/file-upload-and-exif-in-mobile-safari

> invalid JPEG format: short Huffman data in 20211017_183125_77FA6B37.heic 

This error is shown because the image is "corrupted", if you open it in another tool, you see that the lower part is missing. That's why it does not show up in PhotoPrism. For how many files do you get this error? How did you import those to PhotoPrism? It looks like this photo has not been fully transmitted.

**Comment by SimplyCorbett** [comment]
> This error is shown because the image is "corrupted", if you open it in another tool, you see that the lower part is missing. That's why it does not show up in PhotoPrism. For how many files do you get this error? How did you import those to PhotoPrism? It looks like this photo has not been fully transmitted.

All of the portrait shots are like this. It's only the portrait shots or images with blur. I plugin my iphone to windows and just transfer them over file explorer.

All other heic files are fine. EXIF data transfers correctly, too. Seems to only be a problem with safari. I'm assuming apple is stripping the exif data on purpose for privacy reasons.

While on the subject of photos proraw also doesn't work correctly in photoprism, but that's due to an issue with darktable and rawtherapee.

I'll have to give photosync a shot.

**Comment by SimplyCorbett** [comment]
Photosync does solve this. I'll go ahead and close the issue.
