### ISSUE TITLE
Only `preview` tag works on Raspberry Pi 4 (64bit), `latest` fails

### ISSUE THREAD

**Issue by domharrington** [photoprism/photoprism#1635]
Hey!

I've been using the `preview` image whilst building out a self-hosted photoprism instance (to get early access to newer features!) but now I'm up and running I decided to switch to using the `latest` release to have a bit more stability. 

I tried to deploy the `latest` tag and I get this error in my docker compose logs:

```sh
photoprism     | standard_init_linux.go:228: exec user process caused: exec format error
photoprism exited with code 1
```

This is exactly the same problem as these issues:
- https://github.com/photoprism/photoprism/issues/1420
- https://github.com/photoprism/photoprism/issues/1430

I do not get this issue at all when using the `preview` tag, it runs perfectly fine. I'm running Rasperry Pi OS 64bit, and `arm_64bit` is set in /boot/config.txt:

```sh
$ grep arm_64bit /boot/config.txt
arm_64bit=1
```

I also switched to using `arm64v8/mariadb:10.5` as recommended [here](https://docs.photoprism.org/getting-started/raspberry-pi/) - this also didn't use to be necessary either.

Thanks in advance!

**Comment by lastzero** [comment]
Sorry to hear it doesn't work for you. Did you follow the instructions in our docs for updating? Older images won't work, you need to explicitly pull the latest image, the `:latest` tag doesn't mean you're automatically using the latest update.

https://docs.photoprism.org/getting-started/updates/

Docker Hub shows the current  `photoprism/photoprism:latest` tag points to a multi arch image for AMD64, ARM64 & ARMv7:

https://hub.docker.com/r/photoprism/photoprism/tags

**Comment by domharrington** [comment]
Doh! That's my bad... looks like I had an old `:latest` image hanging around:

```sh
$ docker images | grep photoprism
photoprism/photoprism                preview    54ccc68aed25   5 hours ago    1.38GB
photoprism/photoprism                latest     0607578fcce1   4 months ago   1.29GB
```

Running the follow fetched the new latest from the remote (which has multi-arch support!):

```sh
$ docker-compose pull  && docker-compose up -d
```

I (wrongly?) assumed that because I had watchtower installed as well, I shouldn't need to follow the [update instructions](https://docs.photoprism.org/getting-started/updates/). Maybe this would've resolved itself when watchtower next ran? I wouldn't be surprised if watchtower only ran on "working" (running and not error-ing) containers though.

Anyway, this issue is now resolved! Thanks for your help.
