### ISSUE TITLE
New faces shown but no option to name new people

### ISSUE THREAD

**Issue by BackedUpBooty** [photoprism/photoprism#1638]
I've gone through the other issues raised but wasn't able to find my actual issue.  #22 came closest and I played around with the settings a bit but no joy. 

From about 700 photos added to the database, photoprism found 3 faces out of approximately 15 - 2 of which were the same person. The faces it found were from group photos where there was little to no overlap of faces, and it recognises one of the faces it found in other photos where there's considerable overlap. 

Going to `People > New > Show All New Faces` shows more photos with other faces on them, but there's no 'new' faces showing up to be named in `People > New`.

**Comment by srett** [comment]
Under `People > New` you only see face clusters, i.e. if enough faces were found of what PP considers the same person. `All New Faces` really shows all new faces that were found.
For your group photo, you can open the edit dialog, go to the `People` tab and see all faces that were detected in the photo. You can also assign a name there more easily, as it shows a thumbnail of just the detected face. The automatic clustering might then improve over time, when PP runs the background face recognition job.

For more info see https://docs.photoprism.org/user-guide/organize/people/

**Comment by graciousgrey** [comment]
A view with only faces (like in people > NEW) is planned for "Show all faces" as well : https://github.com/photoprism/photoprism/issues/1601

**Comment by BackedUpBooty** [comment]
The 2 faces that were detected are in the same amount of photos as 2 other faces which is why I was a bit surprised/confused. `All New Faces` does show more faces, but definitely not all. 

> For your group photo, you can open the edit dialog, go to the `People` tab and see all faces that were detected in the photo. You can also assign a name there more easily, as it shows a thumbnail of just the detected face

Thanks for the info, I'll give this a try

> A view with only faces (like in people > NEW) is planned for "Show all faces" as well : #1601 

Sounds good, looking forward to it
