### ISSUE TITLE
Add test images with date before 1970

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#164]
**As a developer, I need (small) JPEGs with exif dates before 1970 to test the indexer.**

See #162

**Comment by graciousgrey** [comment]
- I edited exif data using: https://exiftool.org/ 
- Sample file is added to assets/resources/examples
- Wiki is updated: https://github.com/photoprism/photoprism/wiki/Edit-EXIF-metadata-for-testing

**Comment by lastzero** [comment]
@graciousgrey I've added a simple test for the file, see https://github.com/photoprism/photoprism/commit/582113fed4ed356f7e8f1ee9a0cbd1d02a85ce80#diff-9436ac4f2f028c3711818d5395e357de
