### ISSUE TITLE
Enable Mutli-Edit for pictures

### ISSUE THREAD

**Issue by spiezmaestro** [photoprism/photoprism#1643]
I would like to be able to select multiple pictures and change their shared details all at once. For example:
- change their day, month, year, country, subject, description, etc
- assign labels to them
- select them as favorite, as being scans, etc. (select them all as private is already possible).

**Comment by graciousgrey** [comment]
That's already on our roadmap: https://github.com/photoprism/photoprism/issues/271 :)
