### ISSUE TITLE
Sharing: Add overview page for shared items

### ISSUE THREAD

**Issue by spiezmaestro** [photoprism/photoprism#1644]
I would like to be able to generate an overview of all shared items (because it is hard to keep track of them one by one). Ideally as admin an overview of all items shared by all users. 

I know that it is possible to limit the sharing for a specific amount of days, but the default is "never expires", so it could well be there are shares that are hidden somewhere.

**Comment by graciousgrey** [comment]
That's something we plan to do. Users should be able to share content with other users or with non-users using links. There will be sections like "shared with me" and "shared with others" then.

**Comment by graciousgrey** [comment]
I close this as we already have a ticket here: https://github.com/photoprism/photoprism/issues/1330
