### ISSUE TITLE
Converted JPEGs from CR2 RAW files have wrong gps location

### ISSUE THREAD

**Issue by presario222** [photoprism/photoprism#1645]
I put some cr2 raw files into library and did a rescan, then I found the gps locations of the jpg thumbnails are wrong, the latitude and longitude number became identical. Example: latitude 38.8888 longitude 38.8888, but the original cr2 raw files location are  latitude 38.8888 longitude 156.6666.

**Comment by graciousgrey** [comment]
Could you send us an example file for testing to hello@photoprism.app?

**Comment by graciousgrey** [comment]
Do you have any special settings? It's working for me. For the image you sent I see lat 39.... and long 116 in PhotoPrism

**Comment by presario222** [comment]
I don’t think I have any special settings, the settings screenshots are all here, in my server the original cr2 raw file’s location is right(added by photos exif editor after shot),but the generated jpeg thumbnail picture’s location isn’t(see the screenshot attached).

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Theresa Gresch ***@***.***>
发送时间: Friday, October 22, 2021 3:20:41 PM
收件人: photoprism/photoprism ***@***.***>
抄送: presario222 ***@***.***>; Author ***@***.***>
主题: Re: [photoprism/photoprism] Converted JPEGs from CR2 RAW files have wrong gps location (Issue #1645)


Do you have any special settings? It's working for me. For the image you sent I see lat 39.... and long 116 in PhotoPrism

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotoprism%2Fphotoprism%2Fissues%2F1645%23issuecomment-949357707&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437940416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WDz8fEb5byLqprkrhw3P6ZdCpHZ5us8f3U3AZMyW20w%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAME4XY6F5ZK4L6IUIMLC6LTUIEGETANCNFSM5GOPD4ZQ&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437950371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uem05YyysQ9iezpYO44SvKHypcNHVy5Ys9jZhsk9rJE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437950371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jx8eCTDYgnlLKtcfEyxYXT%2B2wtUKEttozvHNj0SGgs8%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437960326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u2bkcZWnOpURQ15p2r9GV4ZpKf06JPH4TkP6qcSVuIE%3D&reserved=0>.

**Comment by presario222** [comment]
I use the command cleanup the thumbnails and rescan the library, now the gps location got right.
________________________________
发件人: Theresa Gresch ***@***.***>
发送时间: 2021年10月22日 15:20
收件人: photoprism/photoprism ***@***.***>
抄送: presario222 ***@***.***>; Author ***@***.***>
主题: Re: [photoprism/photoprism] Converted JPEGs from CR2 RAW files have wrong gps location (Issue #1645)


Do you have any special settings? It's working for me. For the image you sent I see lat 39.... and long 116 in PhotoPrism

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotoprism%2Fphotoprism%2Fissues%2F1645%23issuecomment-949357707&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437940416%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WDz8fEb5byLqprkrhw3P6ZdCpHZ5us8f3U3AZMyW20w%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAME4XY6F5ZK4L6IUIMLC6LTUIEGETANCNFSM5GOPD4ZQ&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437950371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uem05YyysQ9iezpYO44SvKHypcNHVy5Ys9jZhsk9rJE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437950371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jx8eCTDYgnlLKtcfEyxYXT%2B2wtUKEttozvHNj0SGgs8%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C229f6d4b645a4ded9d6508d9952c74be%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637704840437960326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u2bkcZWnOpURQ15p2r9GV4ZpKf06JPH4TkP6qcSVuIE%3D&reserved=0>.

**Comment by graciousgrey** [comment]
Good to hear that it is  working now!

**Comment by lastzero** [comment]
Can we close this issue or is there still something we need to take a look at?
