### ISSUE TITLE
Demo: Live Photos & Videos not playing with Safari

### ISSUE THREAD

**Issue by mumbledenoise** [photoprism/photoprism#1648]
Live Photos are working in the browser on desktop, but on iPhone they do not play. I see the preview thumbnail, but when the video attempts to play the video portion goes transparent. Sometimes the counter and timeline start counting up as if the video is actually playing, but usually it just stays at 00:00.

![image](https://user-images.githubusercontent.com/8943219/138356859-cc26c173-3e67-4035-9e96-baa866974a6a.png)

![image](https://user-images.githubusercontent.com/8943219/138356454-321e1775-3803-41fe-84c2-1ef2b4e52dfb.png)

**Comment by lastzero** [comment]
@graciousgrey can test it tomorrow, not aware of any issues. This looks strange!

**Comment by graciousgrey** [comment]
Might be a problem with the CDN? I observe the same on the demo, but on my private instance it's working fine

**Comment by lastzero** [comment]
Yes, most likely an issue with the CDN. Maybe somebody experienced can take a look?

**Comment by ark-** [comment]
I get the same on an iPhone 12, iOS 14.8 on demo.photoprism.org.

Has been like this for months for me on the demo website. 

Additional info: I get the same behaviour on my own instance which runs `:preview` build in a docker container which I access via local LAN. So not sure it's CDN related.

**Comment by ark-** [comment]
More additional info: The same happens on my Macbook in Safari. So perhaps it's a Safari related issue.

**Comment by graciousgrey** [comment]
Interesting, thanks for letting us know! For my personal instance safari works on mobile and on my mac. For the demo it does not.

**Comment by lastzero** [comment]
Maybe Safari doesn't like the HTTP headers we use or there is a header missing? Note our API supports streaming, it's not a simple download. Could well be that a detail is wrong. From what I remember, we use a JS lib to enable streaming. Apparently only Safari has native support (which can behave differently):

https://github.com/videojs/http-streaming#compatibility

I can confirm issues with Safari on our demo, works perfectly with my personal instance though. May point to an issue with the HTTPS proxy.

**Comment by lastzero** [comment]
Other users seem to have issues with Safari & range requests too:
https://stackoverflow.com/questions/68010780/video-not-playing-in-safari-despite-range-request-support

**Comment by lastzero** [comment]
It looks like the CDN must be bypassed for videos to avoid streaming issues on Safari. Could be related to this:
- #1937

**Comment by rwps** [comment]
Same issue for me, no content apart from an inactive logo appears on the page when I go to :
https://demo.photoprism.app/labels
And that’s on two separate iOS devices, iPhone 12 on iOS 15.4 and IPad Pro 11 gen3 on ios 15.5

**Comment by lastzero** [comment]
Can you provide a screenshot and sample file to reproduce this please? Do you have JSON sidecar files enabled?

**Comment by rwps** [comment]
![C910193B-6E88-4CFF-91E2-9CC2260E917D](https://user-images.githubusercontent.com/63499075/177023470-ce4da62f-c83b-4dd4-a1d8-8249a390c311.png)
A page I can’t do anything on
And I don’t understand the json question I have a standard iPhone setup, and the result is the same in safari and Firefox 
Thanks

**Comment by lastzero** [comment]
Might be an issue with the CDN. Do thee browsers work? Do you see any errors on the JS console?

**Comment by lastzero** [comment]
This should be fixed now. We recently implemented security enhancements and this blocked the Web Socket connection in Safari.

**Comment by rwps** [comment]
Thanks - yes it is working now
