### ISSUE TITLE
It is recommended to optimize face recognition

### ISSUE THREAD

**Issue by winddriver** [photoprism/photoprism#1649]
The current face recognition is less accurate, many of the photos of the same person are not classified to the same face, and there is a obvious person in the photo, but system can't recognize it.

**Comment by lastzero** [comment]
That's what we have in store right now. Our app is under active development and improved continuously.

There can be several reasons why a face was not detected:

- Only the primary file in stacks will be searched for faces
- Faces can be smaller than the minimum size configured
- Our face detection did not scan the image thoroughly enough
- Reducing the resolution or quality of generated [thumbnails](https://docs.photoprism.org/user-guide/settings/advanced/) negatively impacts face detection and recognition results
- In very rare cases an actual face may match a blacklist of false positives, like background noise and food that looks like a face

Docs: https://docs.photoprism.org/user-guide/organize/people/

Please don't use GitHub Issues for general comments or questions.
