### ISSUE TITLE
CPU and Memory usage high

### ISSUE THREAD

**Issue by kelvinhammond** [photoprism/photoprism#165]
Photoprism 20191219 is using 100% cpu on all cores and all of the RAM on docker image startup.

**Comment by lastzero** [comment]
Simply when you start it, without any images? No page open in the browser?

**Comment by kelvinhammond** [comment]
Its actually when I go to the page now that I've tested it.

I have a lot of photos that I've taken.

**Comment by lastzero** [comment]
If you don't want to test the limits of your computer, you should pre-render thumbnails because it simply requires a lot of CPU to do that in on demand. Facebook and Google also pre render thumbnails, that's how you do it unless you have a 12 core CPU. You can also use our import feature (put files in the import directory and press import), but most testers prefer to keep their files where they are... import will move and rename them.

![Screenshot 2019-12-20 at 22 44 03](https://user-images.githubusercontent.com/301686/71294919-51962c80-237a-11ea-8f11-be11630e7520.png)

**Comment by kelvinhammond** [comment]
I have that option turned on, is there a way to have it rescan originals and create thumbnails for them?
And is there a way to limit the number of cores used for thumbnail generation. I believe its mostly a memory issue.

**Comment by lastzero** [comment]
Yes, simply index again with the checkbox selected or run the command "photoprism thumbnails" in a terminal.

**Comment by kelvinhammond** [comment]
Thank you, this is working.

**Comment by lastzero** [comment]
You're welcome :) Please consider a [donation](https://github.com/photoprism/photoprism/blob/develop/SPONSORS.md) if you like PhotoPrism. We're working on this full-time at the moment.

**Comment by lastzero** [comment]
If you're running out of memory, limit the number of workers and make sure the server has swap configured, so that indexing doesn't stop when there are memory usage spikes. As a measure of last resort, you may additionally disable image classification using TensorFlow.

**Comment by spupuz** [comment]
> If you're running out of memory, limit the number of workers and make sure the server has swap configured, so that indexing doesn't stop when there are memory usage spikes. As a measure of last resort, you may additionally disable image classification using TensorFlow.

i have 32GB ram don't think it's a ram problem. anyway is there a way to disable anything via gui?

**Comment by lastzero** [comment]
Memory doesn't seem to be the issue here, but I don't know what else is running on your computer. Try to reduce the number of workers and see how that goes. Also make sure you use fast, local storage for your pictures, and not remote storage or a USB stick.

**Comment by spupuz** [comment]
using a mirrored local disk on my debian nas

**Comment by spupuz** [comment]
> Memory doesn't seem to be the issue here, but I don't know what else is running on your computer. Try to reduce the number of workers and see how that goes. Also make sure you use fast, local storage for your pictures, and not remote storage or a USB stick.

how do i reduce the workers?

**Comment by lastzero** [comment]
So it's network storage or PhotoPrism is running on the NAS?

Config options see https://docs.photoprism.org/getting-started/config-options/

**Comment by spupuz** [comment]
> So it's network storage or PhotoPrism is running on the NAS?
> 
> Config options see https://docs.photoprism.org/getting-started/config-options/

It's running in the docker container on a OpenMediaVault (debian) nas, i run also other stuff with no remarkable impact on cpu that is always lesse than 15/20% usage

**Comment by lastzero** [comment]
Didn't expect you use a Core i7 for your NAS - it's more like a big home server then ;)

If CPU usage is high while indexing, then PhotoPrism works as designed. This is a CPU and I/O intensive job. Reduce the number of workers if you want some cores to be idle. Also try MariaDB instead of SQLite as it will probably be faster (see inline docs in our `docker-compose.yml` example config).

**Comment by lastzero** [comment]
Using SSDs instead of traditional hard disks will also give performance a boost.

**Comment by spupuz** [comment]
> Didn't expect you use a Core i7 for your NAS - it's more like a big home server then ;)
> 
> If CPU usage is high while indexing, then PhotoPrism works as designed. This is a CPU and I/O intensive job. Reduce the number of workers if you want some cores to be idle. Also try MariaDB instead of SQLite as it will probably be faster (see inline docs in our `docker-compose.yml` example config).

yeah a little big home server, i'll take a look in the future days if i can make it work more flawless in the future days

**Comment by spupuz** [comment]
> Using SSDs instead of traditional hard disks will also give performance a boost.

i use NAS disk mirrored and a raid 6 with 6 disks + 1 disk of cache, can you suggest me a proper value for the workers?

**Comment by lastzero** [comment]
RAID 6 is known to cause a high CPU load and extremely bad write performance. This makes it unsuitable for high performance applications. You may set the number of workers to 5 or 3 and see how that goes in terms of CPU load.

**Comment by spupuz** [comment]
default worker is 0 and correspond to what?

**Comment by spupuz** [comment]
![image](https://user-images.githubusercontent.com/1721792/99516820-ee988580-298e-11eb-8694-b9d24c2c86e0.png)

**Comment by spupuz** [comment]
this is with 4 thread

**Comment by alexislefebvre** [comment]
Your [CPU](https://ark.intel.com/content/www/us/en/ark/products/88040/intel-core-i7-5775c-processor-6m-cache-up-to-3-70-ghz.html) has 4 cores and 8 threads. Maybe Photoprism used 8 threads to index the database and it overloaded the CPU.

**Comment by spupuz** [comment]
i have set 4 as CPU thread

**Comment by spupuz** [comment]
i hope once the scan has finished the usage decrease, for mobile application on android where do i get the apk?

**Comment by alexislefebvre** [comment]
> Your [CPU](https://ark.intel.com/content/www/us/en/ark/products/88040/intel-core-i7-5775c-processor-6m-cache-up-to-3-70-ghz.html) has 4 cores and 8 threads. Maybe Photoprism used 8 threads to index the database and it overloaded the CPU.

It looks like that if the number of workers is not configured, calls to [NumCPU](https://github.com/photoprism/photoprism/search?q=NumCPU) are issued. If this returns the number of threads, it will probably cause issues when CPU has hyperthreading. Like @spupuz had.

**Comment by lastzero** [comment]
As mentioned, I suspect RAID 6 to be main issue here. Unless it's a hardware RAID? It may slow down write operations about 10x (according to my research) and probably causes high CPU load by itself in combination with applications like PhotoPrism, which need to read and write a lot on the disk for indexing. This is not a good combination and the only ways to improve the situation is either reduce the number of workers (by default 2x the number of cores - 1 with hyper threading), or use an additional SSD at least for the database and thumbnail files.

**Comment by spupuz** [comment]
I'm on raid 1 with pictures data set.

Il Mer 18 Nov 2020, 13:24 Michael Mayer <notifications@github.com> ha
scritto:

**Comment by lastzero** [comment]
That should work better for I/O intensive applications. Performance also depends on the file system, and of course disk technology.

**Comment by spupuz** [comment]
emh di work as Solution Architect in Storage (for a multinational company) in my opinio i/o performance and iowait is not the problem here, i think that main problematics is given by tensorflow cpu utilization

**Comment by lastzero** [comment]
We run PhotoPrism on an older Core i3 with software raid on magnetic hard disks. No issues whatsoever. Again, CPU load must be for fast indexing. Can be reduced a bit with GPU optimized TensorFlow libs.

**Comment by spupuz** [comment]
how do user this libs? i can pass the driver video card to the docker

**Comment by lastzero** [comment]
You'd have to replace them inside the Docker image. CPU libs included by default so that it works everywhere. Might release other, pre-built images in the future.

**Comment by spupuz** [comment]
is there a procedure in order to replace these libs in the image?

**Comment by spupuz** [comment]
do i have to pass
  --device /dev/dri/renderD128:/dev/dri/renderD128 \
  --device /dev/dri/card0:/dev/dri/card0 \
to the docker container in order to use the GPU hw?

**Comment by alexislefebvre** [comment]
This sentence:

> If you're running out of memory,

Could be rewritten as something like:

> If you're running out of memory or the CPU is overloaded,

On this page: https://docs.photoprism.org/getting-started/

**Comment by spupuz** [comment]
> This sentence:
> 
> > If you're running out of memory,
> 
> Could be rewritten as something like:
> 
> > If you're running out of memory or the CPU is overloaded,
> 
> On this page: https://docs.photoprism.org/getting-started/

yes should be

**Comment by alexislefebvre** [comment]
@spupuz when indexing will be finished, please remove the runners configuration, restart the image, run `docker-compose exec photoprism photoprism config | grep workers` and share the output. It will tell how many workers PhotoPrism used with automatic detection of workers.

**Comment by spupuz** [comment]
ok i'll do i'm 9800 photo scanned over 12k

**Comment by spupuz** [comment]
root@openmediavault:~# docker exec photoprism photoprism config | grep workers
workers                   7
root@openmediavault:~#

**Comment by spupuz** [comment]
after restart and when the scan has finished high cpu utilization has gone.

**Comment by spupuz** [comment]
umh not convicend anyway about performances got many errors about stuff not foud after scan and it's so slow.
Not working very well at all.

**Comment by alexislefebvre** [comment]
> root@openmediavault:~# docker exec photoprism photoprism config | grep workers workers 7 root@openmediavault:~#

Thanks, so it detected more threads than the CPU could handle. this is why it was overloaded.

> after restart and when the scan has finished high cpu utilization has gone.

This is the expected behaviour, once your photos have been analyzed and the thumbnails have been generated, there is no heavy task to do.

**Comment by spupuz** [comment]
i use original folder since my library is quite organized, i use it for upload with autoupload with the app, does any new manual or uploaded foto get scanned automatically? i have already relalized that

**Comment by spupuz** [comment]
sometimes i get database is locked message
