### ISSUE TITLE
Does PhotoPrism support resuming indexing?

### ISSUE THREAD

**Issue by H4dr1en** [photoprism/photoprism#1653]
Hi there,

I started indexing for the first time my library of photos on a i3 with windows & docker. I've set docker resources cpu limit to 4 out of 8 available.

I now realize that the first indexing is slow (it would take me several days to finish at the current speed) and I am wondering whether I can interrupt it with docker-compose down, increase the docker cpu limit from 4 to 8, start photoprism and resume indexing.

Will it be supported? Will it skip already indexed files?

**Comment by lastzero** [comment]
Just press stop or Ctrl-C to stop indexing. You can start again at any time.

✨ **Please use [GitHub Issues](https://github.com/photoprism/photoprism/issues) only to report clearly identified bugs and impediments to us.** If you are not sure, first use [GitHub Discussions](https://github.com/photoprism/photoprism/discussions) or ask in our [Community Chat](https://gitter.im/browseyourlife/community). [Sponsors](https://docs.photoprism.org/funding/) receive direct [technical support](https://photoprism.app/contact) via email. ✨

**Comment by nsimonkaz** [comment]
Lastzero, you are a fucking idiot who ignored all of the original poster's questions.  First of all, there is no fucking "stop" button, there is only "cancel".  Secondly, of course you can "start again" stupid, that was never the question.  DO YOU READ PINHEAD?  You piss me off so much.  You are useless.  Fucking useless.  The question was about resuming.  Do you know what that means you half wit?
