### ISSUE TITLE
OSM: Extracting location information from GPS coordinates ignores `village` property

### ISSUE THREAD

**Issue by janost** [photoprism/photoprism#166]
First of all, thank you for this awesome project!

While testing it on my photo collection I noticed that some location labels look a bit weird, so I started investigating and realized that Photoprism seems to ignore the `village` property of the `address` object while parsing OSM's response, falling back to `county`. This causes photos taken in a village to have incomplete location labels. ([Code][1]) [Nominatim's documentation][2] fails to mention the `village` property, but you can see it in their examples.

[1]: https://github.com/photoprism/photoprism/blob/1e7c0c243550e6b2b251455efcc06779efcce2e0/internal/maps/osm/location.go#L75
[2]: https://nominatim.org/release-docs/develop/api/Reverse/

**Comment by lastzero** [comment]
Amazing, thank you for this hint!

**Comment by lastzero** [comment]
Merged to `master`. Updated Docker image should soon be available. Let us know if it works for you.

**Comment by lastzero** [comment]
@janost Note that you shouldn't index too many photos as OSM does not allow batch processing, see https://twitter.com/liotier/status/1207989846159036416

We're currently working on our own geolocation service.

**Comment by janost** [comment]
@lastzero noted, thank you.
Also I tested the new container, works very well, thank you!
Closing the ticket as the issue has been fixed.

**Comment by lastzero** [comment]
You're welcome :) Please consider a [donation](https://github.com/photoprism/photoprism/blob/develop/SPONSORS.md) if you like PhotoPrism. We're working on this full-time at the moment.
