### ISSUE TITLE
WebDAV: Can't connect with Windows 10 

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1665]
**What does not work as expected?**

WebDAV connection cannot be established on Windows 10.

**How can we reproduce it?**

1. Follow the steps described here on Windows 10: https://docs.photoprism.org/user-guide/sync/webdav/

**What behavior do you expect?**

A connection being established

**Can you provide us with example files for testing or screenshots?**
See:
https://docs.photoprism.org/user-guide/sync/webdav/

**What version you are using?**

Latest preview.

**Comment by 1oh1** [comment]
The same steps mentioned in the documentation but with a small change top the WebDAV URL worked for me.
I used this URL at the map network drive prompt: `\\photoprism.example.com@SSL\originals\`

Windows prompted for credentials and I entered `admin` and `photoprism` and it worked.

**Comment by lastzero** [comment]
Interesting! Thank you very much 💐

**Comment by graciousgrey** [comment]
Works for me as well. Docs are updated accordingly: https://docs.photoprism.org/user-guide/sync/webdav/

**Comment by Akruidenberg** [comment]
Address like @SSL looks strange, but it working well!
