### ISSUE TITLE
Metadata: Incorrect Handling of UTC Time Zone

### ISSUE THREAD

**Issue by dror3go** [photoprism/photoprism#1668]
Using 211010 release, I've noticed wrong time shown for some older photos I have.

For example, the following is info about a photo taken at `2015-05-17 23:02:46`:
```
exiftool -n -j 20150517_230246.jpg | grep Create
  "CreateDate": "2015:05:17 23:02:46",
```
PhotoPrism shows as if the photo was taken at `2015-05-18 02:02:46`, with UTC time shown as `2015-05-17 23:02:46`.

An example of a newer photo with correct time in PhotoPrism `2021-08-01 09:38:43`:
```
exiftool -n -j IMG_20210801_093842.jpg | grep Create
  "CreateDate": "2021:08:01 09:38:43",
```

I'm not sure what other information might be relevant here.
If needed, I can send you private links to the photos.

**Comment by lastzero** [comment]
Is the time zone UTC or is the UTC time wrong? Could be an estimate based on photos taken at a similar time. You can turn this off in Settings.

**Comment by dror3go** [comment]
Both UTC & local time are wrong in the UI. The timezone itself is correct.
The correct local timestamp of this specific example should be `2015-05-17 23:02:46` and the correct UTC time should be `2015-05-17 20:02:46`.
I have no photos taken around 2:00 AM that day, so I don't think that this is the case. What is the time window for estimating time using other photos around that time? FYI it seems that all the photos from around that time are with wrong local & UTC time.

I do have a video taken with the same device (Samsung Galaxy S3) a couple of hours before the photos: the video is shown with correct date & time - I guess thanks on the fix in #1388.

**Comment by lastzero** [comment]
About +/- a day. Does the image have a location (GPS)? If not and it has now a time zone out of nowhere, it's an estimate.

**Comment by lastzero** [comment]
AVC, MP4 & MOV videos are in UTC by default as that's what the standard says.

**Comment by dror3go** [comment]
The image has a location which I manually set in PhotoPrism, so the Country, Latitude & Longitude are all marked with a V in the photo editing section.

**Comment by lastzero** [comment]
@graciousgrey Is the information provided enough for you to reproduce / test this?

**Comment by graciousgrey** [comment]
@dror3go It would be great if you could send us an example photo with the correct time and the one that is not working. We will delete them after testing :)

**Comment by dror3go** [comment]
@graciousgrey I've sent an email to you guys :pray:

**Comment by graciousgrey** [comment]
Thank you! I will have a look today :)

**Comment by graciousgrey** [comment]
Ok this is probably a bug on our side. 

There is a video without GPS information with 
`"CreateDate": "2015:05:17 17:48:22"`
and  jpg without GPS information with 
`"DateTimeOriginal": "2015:05:17 23:02:46",
  "CreateDate": "2015:05:17 23:02:46",`

**The current behaviour is the following:**

After initial indexing we see:
* video --> Local Time: 17:48, UTC Time: 17:48, Time Zone: UTC
* jpg --> Local Time: 23:02, UTC Time: 23:02, Time Zone: Local Time

After I manually set coordinates :
* video --> Local Time: 17:48, UTC Time: 14:48, Time Zone: Asia/Jerusalem --> This is needs to be optimized
* jpg --> Local Time: 23:02, UTC Time: 20:02, Time Zone: Asia/Jerusalem --> This is correct

After optimization (in the background or complete re-index):
* video --> Local Time: 20:48, UTC Time: 17:48, Time Zone: Asia/Jerusalem --> This is correct
* jpg --> Local Time: 02:02, UTC Time: 23:02, Time Zone: Asia/Jerusalem --> This is wrong

**Comment by graciousgrey** [comment]
When only setting the country and not the coordinates:

After initial indexing we see:
* video --> Local Time: 17:48, UTC Time: 17:48, Time Zone: UTC
* jpg --> Local Time: 23:02, UTC Time: 23:02, Time Zone: Local Time

After I manually set the country :
* video --> Local Time: 17:48, UTC Time: 17:48, Time Zone: UTC --> This is needs to be optimized
* jpg --> Local Time: 23:02, UTC Time: 23:02, Time Zone: Local Time --> This needs to be optimized

After optimization:
* video --> Local Time: 20:48, UTC Time: 17:48, Time Zone: Asia/Jerusalem --> This is correct
* jpg --> Local Time: 23:02, UTC Time: 20:02, Time Zone: Asia/Jerusalem --> This correct

**Comment by graciousgrey** [comment]
When setting country + coordinates manually:

After initial indexing we see:
* video --> Local Time: 17:48, UTC Time: 17:48, Time Zone: UTC
* jpg --> Local Time: 23:02, UTC Time: 23:02, Time Zone: Local Time

After I manually set country + coordinates :
* video --> Local Time: 17:48, UTC Time: 14:48, Time Zone: Asia/Jerusalem --> This is needs to be optimized
* jpg --> Local Time: 23:02, UTC Time: 20:02, Time Zone: Asia/Jerusalem --> This is correct

After optimization:
* video --> Local Time: 17:48, UTC Time: 14:48, Time Zone: Asia/Jerusalem --> This is wrong
* jpg --> Local Time: 23:02, UTC Time: 20:02, Time Zone: Asia/Jerusalem --> This correct

**Comment by Fylax** [comment]
Since I found the same problem in my system, I did some extra researches.
Here what I did:
 1. Extracted data with exiftool
```
$ exiftool -time:all -g1 -a -s DSC_4046.JPG 

---- ExifIFD ----
DateTimeOriginal                : 2021:11:05 16:07:59
CreateDate                      : 2021:11:05 16:07:59
---- Nikon ----
TimeZone                        : +01:00
DaylightSavings                 : No
```
2. Added photo to originals folder and started index via WebUI
```
2021-11-05 16:50:10 INFO media: DSC_4046.JPG was taken at 2021-11-05 16:07:59 +0000 UTC (meta)
2021-11-05 16:50:02 INFO metadata: failed parsing GPS coordinates in DSC_4046.JPG (exif)
```
3. Both _Local Time_ and _Time UTC_ are *16:07:59* as expected
4. After setting GPS coordinates via WebUI (_Time Zone_ and _Country_ detected accordingly) _UTC Time_ is updated correctly
5. I run, through cli, photoprism optimize, purge and cleanup. Times were still correct.
6. After some time doing nothing, some background process changed the dates, resulting in:
    - _Local Time_: 17:07:59
    - _Time UTC_: 16:07:59

**Comment by Fylax** [comment]
Extra info: I had some pictures that I didn't manually geotag yet. Still, they presented the same problem.
Might it be related to face recognition task?

**Comment by lastzero** [comment]
Estimates should now be effectively prevented if the location was manually changed, even if it was just the country.
Can't reproduce it with these changes. Please test again! 👍

**Comment by dror3go** [comment]
Thanks so much for fixing this! I didn't get the chance to deploy a preview build and make some tests myself. Guess I'llsI'll see the results once I'll update my production build.
Thanks again!
