### ISSUE TITLE
UX: Scrolling not smooth on Apple devices with 120Hz display

### ISSUE THREAD

**Issue by huahuasousou** [photoprism/photoprism#1669]
**What does not work as expected?**
In my ipad pro 12.9 3rd 2018, I found if I use my finger to sliding the pictures, the frame rate of the animation is very low and not smooth (even lower than 60hz, only 20hz I guess), but if I push the "start/stop slideshow" button, it can achieve 120hz frame rate of the animation.  And in my Iphone13 pro 256G, the bug was not found.

1. use a iPad pro 12.9 3rd 2018( It must have the ProMotion display), and use safari and chrome bowser, open the photoprism
2. select a picture and use your finger to sliding the picture, you can see the animation not smooth.
3. use an iphone13 (it still have the ProMotion display), repeat the test, it not happend.

I think maybe the token of the browser makes photoprism think it is a desktop computer, which makes it not activate the high refresh rate and due to ProMotion, the display refresh rate keep a very low level(it can adjust from 10hz to 120hz). But in iphone the browser will report the device it's a mobie phone, so it's normal.

**Comment by lastzero** [comment]
We seem to be close to perfection when new bug reports look like this! ✌️

**Comment by lastzero** [comment]
Probably can't reproduce this as we currently don't own any test devices with 120Hz display:

- iPad Air
- MacBook Air
- iMac
- iPhone SE

**Comment by spattinson** [comment]
May be a browser issue? It is buttery smooth on mi Mi 10 at 120hz using Chrome.

**Comment by lastzero** [comment]
This was a bug in the Apple software which got fixed from what I know: https://discussions.apple.com/thread/253290455
