### ISSUE TITLE
Image might contain offensive content

### ISSUE THREAD

**Issue by christianwgd** [photoprism/photoprism#168]
The upload of photos stops with a message that classifies photo as "offensive content", which is far beyond offensive, even for sensible people (A fully clothed person on a chair on a camp ground). 

To me, it seems a strange idea to implement algorithms to check peoples moral ideas, it will never lead to a sufficient blocking. Since i don't know the ideas behind, i would appreciate a discussion on that.

**Comment by lastzero** [comment]
The photo may contain such content, meaning we don't know for sure. That's the only way for us to allow uploads because people uploaded lots of pr0n in the past...

**Comment by christianwgd** [comment]
So this is only meant for the public demo instance? Is there a possibility to disable that for a local installation?

**Comment by lastzero** [comment]
Yes, should be PHOTOPRISM_NSFW_UPLOAD = true

**Comment by lastzero** [comment]
We have help and config commands: `photoprism help`

**Comment by lastzero** [comment]
Could you disable it for your instance? Please close the ticket in this case.

**Comment by christianwgd** [comment]
Thanks, didn't try because of Christmas activities, but implementing that is not the point here, so close this issue
