### ISSUE TITLE
Sidecar file for raw and existing jpeg

### ISSUE THREAD

**Issue by b10102016** [photoprism/photoprism#1681]
Hi

May I know how the photoprism to handle existing jpeg for a raw?
Will photoprism try to generate sidecar jpeg for the raw without using the existing one?
If using the existing one, what is the rule of name?

ex:
XXX/xxx.raw
YYY/20211029-xxx.jpg

Will raw conversion still happen and generate the sidecar jpeg for xxx.raw?
Or the photoprism use the existing `20211029-xxx.jpg`?

Sincerely,
Ian

**Comment by lastzero** [comment]
If there's an existing JPEG, PhotoPrism won't create a new one.
