### ISSUE TITLE
Panoramas: Use PhotoSphere Viewer

### ISSUE THREAD

**Issue by Fylax** [photoprism/photoprism#1687]
A lot of devices allow creating PhotoSpheres.
Being able to visualize them properly would be very nice.

As of my knowledge, on backend side, exiftool should extract just one tag: `UsePanoramaViewer`
When this flag is set to true, the "view mode" of the photo should switch from normal to PhotoSpere.

One possible way to implement it is by using [Photo Sphere Viewer](https://photo-sphere-viewer.js.org/) Library which seems to extract all the info from the image and show it properly accordingly.

**Comment by lastzero** [comment]
https://photo-sphere-viewer.js.org/ looks great!

Our indexer already extracts the image projection type. Happy to implement this when our funding situation improves. We currently don't have enough resources to keep up with feature requests.

**Comment by Fylax** [comment]
If the backend already extract and exposes the information somehow, I can work on a PR on my free time.
Sadly I know nothing about GO, so I cannot do a thing when the task involves backend.

**Comment by lastzero** [comment]
It's not just developing a UI. We also need to test it with different browsers and files (incl automated and UX tests) as well as document it properly. Another issue is that our JS app bundle is already pretty large, so we shouldn't add more to it before we have a solution (like splitting).

**Comment by Fylax** [comment]
I see. Then I'll just wait until you get any resource to put this on your roadmap :smiley:

**Comment by lastzero** [comment]
Could be part of the new photo viewer: #1307

**Comment by lastzero** [comment]
Found the original issue: #352

Closing this as duplicate. You are welcome to add helpful comments / ideas to the original issue.
