### ISSUE TITLE
Fatal Error on Login: Size out of Range: 16

### ISSUE THREAD

**Issue by kgw4it** [photoprism/photoprism#169]
Hello,
on login the docker container crashes with the error `time="2019-12-27T22:17:49Z" level=fatal msg="size out of range: 16"`. I quickly looked through the code and it looks llike that the error originates from here: https://github.com/photoprism/photoprism/blob/dac272468eba6441ecec397cdc0f364b057b4fc9/internal/api/session.go#L28

`util.RandomToken` is limited to tokens of a max length of 10

Thank you.

**Comment by lastzero** [comment]
Cool, thank you very much! Need to add tests for this....

**Comment by lastzero** [comment]
Updated Docker image will soon be available for testing.

**Comment by lastzero** [comment]
I'll close this since it seems to be fixed.
