### ISSUE TITLE
Simple video support

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#17]
Shall we support files other than JPEG and RAW? Maybe move all videos to a separate video directory?

We focus on photos because when you remember something, your brain also uses images, not videos with sound, or not?

**Comment by husayt** [comment]
Yes, basic even rudimentary support for videos will be really useful.

**Comment by helmut72** [comment]
No video support? I also suggest video support at the same priority as photos. Where should users upload videos they've taken with their Smartphones? "Oh, the cool video from last event isn't there, can't show it to you."

**Comment by txgruppi** [comment]
In my opinion it should move the video files just like it does for images but it should not have any code to change the video. Move it to `YYYY/MM/DD` folder only.

For the UI, allow the video to be watched, that's all.

Having this feature would make it my main media management software.

**Comment by devzsolt** [comment]
Videos are ambivalent for me. On one hand I would love to handle them as first class citizens in a memory-management app like this, on the other hand I realized that 99% of my video footage are crappy before editing (most even after editing), however I wouldn't expect an app like this to provide any video-editing capabilities, it feels like out of scope. So maybe I would go with the way suggested by @txgruppi: just copy and provide a player (there are several libs, eg. videojs for playback). This way I either just have the videos in place or if I fancy I can edit them with another software and import here the edited file.

**Comment by helmut72** [comment]
@devzsolt Of course. Light users just want to have one place for all their "vacation 2018" files. They will never edit them, but want to have some light organization and to view it.
Every time I show friends photo management tools they ask for videos if not supported. If they do any video editing at all, they do it right on their Smartphones before uploading and for 99% it's only cropping start and end time.

**Comment by viperdream26** [comment]
Another idea would be a way to add links and/or embed YouTube videos. A lot of people would appreciate the decent quality and space savings this would provide. 

I would see this as replacing an image(s) within a gallery, as some people will want to have their videos spread out (with associated photos) rather than all lumped at the end. It could be as simple as a YouTube logo, or have a thumbnail, or be an embedded video.

Thx for listening to all of us future users! Keep up the great work! =)

**Comment by txgruppi** [comment]
I don't think adding YouTube videos is a good idea. In my opinion, PhotoPrism is useful for those who don't want to use a existing service or host their files in a 3rd party server.

I have about 800GB of footage at the moment and I don't see myself uploading it to any service, I rather have it on my HDs and use PhotoPrims to manage the files.

**Comment by viperdream26** [comment]
@txgruppi 

While I would tend to agree, the devs have stated the complexity of implementation is very high. For example, would your computer pre-convert and/or compress the files to make them more easily viewable by a wide audience accessing your site? Would your computer or other server do on-the-fly transcoding of the files to allow for a variety of stream resolutions or do codec conversions? (Various combinations of these techniques happen with all the services, YouTube, Google Photos, Zenfolio, Plex).

I'm just thinking the YouTube solution is a good compromise, where as having some video capability is better than none at all. Then perhaps later in the future, true video support can be added...and one that will support a wide swath of containers, codecs, resolutions, frame rates, etc.

**Comment by txgruppi** [comment]
@viperdream26, maybe I did not understood the goal of PhotoPrims correctly but I believe it is a photo management solution, not a publishing platform.

**Comment by viperdream26** [comment]
@txgruppi Perhaps you're right and private organization is the primary objective, but the feature list mentions: "Clearly structured Web interface for browsing, organizing and **sharing your personal photo collection**."

I'm trying to find an alternative to Zenfolio that I've been paying for over 10 years, which I use as a personal family photo album & to share with family/friends. It would save money & the upload time/process/bandwidth. The video feature they added many years ago was a great addition which I use for many albums. Zenfolio doesn't support linking to YouTube videos that I've aware of, and if you didn't want to use it...you wouldn't have to. Plus YouTube supports higher resolution (ex. 4K) than Zenfolio anyway.

**Comment by lastzero** [comment]
@txgruppi Users should be able to share selected photos, typically resampled and converted to jpeg. @viperdream26 is right in that proper handling of video is much more complex even for viewing them locally (depending on size and format, some browsers might play videos from specific cameras or smartphones without modification). When sharing, videos require more storage and bandwidth.

We could certainly implement that and more, but even my generosity has limits. So far, this project received zero donations, this is all my private money and I don't even have any videos. So either somebody sends a pull request, we should think about crowdfunding or we find a sponsor that pays for additional full-time developers.

**Comment by txgruppi** [comment]
@viperdream26 and @lastzero, the way I understand is that "_sharing your personal photo collection._" means a _share button_ or _export selected to folder_ and you go from there and share it in another platform.

Adding support for Platform X will open requests for platform Y, Z, etc... it will introduce complexity to PhotoPrism.

Is it worth it? Or would it be better to keep it simple and doing one thing really well, private media management.

**Comment by lastzero** [comment]
@txgruppi Some form of sharing/exporting must be possible and it's actually not an issue for me to implement it for like 2 or 3 popular services that I use myself, like Flickr and Twitter. Photos are easy, you resize them down to like 2000px and call some external API.

Videos have lots of different formats, they usually have sound (sometimes more than one track/language), they can have subtitles (with different languages and options) and so on. Also HDR, 3D, DRM,... Uploading can take very long, sometimes you even need to send a physical hard disk because that is faster. A video streaming startup is one of my clients, I know what I'm talking about.

**Comment by txgruppi** [comment]
This video complexity is why I defend the idea of just adding support for accepting videos and allowing you to view it in a web player.

In the future services may be added, but I would to the simplest solution to start with.

**Comment by lastzero** [comment]
If you work a lot with videos, check out https://trimmer.io/ - took 4 years to develop. Backend is also implemented in Go. Uploader uses WebAssembly for improved performance. Works with different storage backends, either local or in the cloud.

**Comment by txgruppi** [comment]
Thanks @lastzero, but what I expect from PhotoPrism (as a user) is to manage my local hard drives with some kind of interface/preview not just a folder structure (how I organize it today).

**Comment by lastzero** [comment]
@txgruppi Automatic tagging/categorization is also different for videos. You probably shouldn't add tags for every single object that is detected in every single frame. The idea for PhotoPrism is that it does most things automatic and you only have to change titles/tags you don't like.

**Comment by txgruppi** [comment]
Don't add support for automatic tagging, not for videos.

The ideia is to keep it simple, just allow people to manage the pictures with full power and videos in a manual way. So we don't have to use PhotoPrism for picture and something else for videos.

**Comment by jazmit** [comment]
I'm evaluating self-hosted media solutions and have to eliminate photoprism because of the lack of video support, even though it looks fantastic.  I understand that implementation is non-trivial, but unless you are a professional still photographer, your video collection will contain both images and videos, and you will usually want to deal with them uniformly with the same tool.

If it is possible to support managing videos with auto-tagging, I think it's fine to skip editing and use an external or embedded player and still greatly expand the number of use cases for photoprism.

**Comment by lastzero** [comment]
We might be able to support videos soon, but sharing with Nextcloud and grouping by place & time have higher priority. Working on that right now.

**Comment by maltokyo** [comment]
I am new to photoprism, looking for a place for me and friends to share images / videos from phone.

Do I understand that there is no way to share videos / movie files?  Not even just "upload and view"?  

Thank you for clarification.

**Comment by lastzero** [comment]
Not yet. It's on our todo list though. We already import them if they belong to a photo ("live photos"), but don't share or display them yet.

**Comment by ylluminate** [comment]
Been looking for a Photos.app replacement. This was recommended as a solid DAM replacement, but unfortunately since I have 40 years of family photos and video to manage, this is a non-starter until video thumbnail + preview / basic view is available.

**Comment by abunavas** [comment]
Thank you for great project. My vote for video support. Nothing fancy - just video thumb and view (in external soft).

**Comment by v-marinkov** [comment]
My vote also goes to a simple thumbnail and video playback. Just like https://github.com/bpatrik/pigallery2

**Comment by lastzero** [comment]
The easiest strategy for adding video support is treating video files as RAW, so that we can automatically create thumbs to show a static video preview in search results. Adding a video player to actually play the video file will be the second step.

**Comment by lastzero** [comment]
Still need to add a player and index metadata. Work in progress. Any preferences how you would like to play videos? Specific player / technology?

**Comment by lastzero** [comment]
Probably going to use https://videojs.com/, unless somebody can recommend a good alternative. Should be lightweight and not add much overhead to our frontend code. Adding a play button is easy, will be in the upper left corner (same as burst mode / related photos).

**Comment by lastzero** [comment]
MP4 files should work now, everything else needs to be tested and implemented. Help welcome.

**Comment by ImranR98** [comment]
Just wanted to say thank you to all the developers for this application! Finally becoming a viable Google Photos alternative. Will be testing the hell out of the video support 🙂.

**Comment by alxjsn** [comment]
Thank you for adding video support! I personally take almost all my photos with live photo enabled in iOS, so once issue I have right now is that all my photos appear as videos. 

Ideally they should be "live" only when I hover over them and then still bring me to the photo when I click on them. How live photo interaction should work should probably just be discussed further in #177 

As a temporary workaround, would it be possible to to detect live photos and still treat those as photos? At least until the live photo functionality is completed.

**Comment by ImranR98** [comment]
Noticed that the videos show up in the wrong order when sorting by Newest/Oldest first. Could it be that it's checking the create date of the newly generated thumbnail instead of the actual video file?

**Comment by lastzero** [comment]
@ImranR98 Metadata support was not implemented. Just pushed, new Docker images available soon (check Travis CI for status).

Make sure to run PhotoPrism with `-j` or `PHOTOPRISM_SIDECAR_JSON: "true"` in docker-compose.yml, so that exiftool is used to create json sidecar files. If you don't want them to be created or read-only mode is enabled, you have to wait until we support creating additional files outside the originals directory.

**Comment by lastzero** [comment]
> Edit: I just realized that if I don't click on the play button and click anywhere else in the thumbnail it brings me to the photo. For me this wasn't intuitive, although I'm glad I get to see both versions.

Right. I guess if we put the play button in a corner like when we detect related pictures (burst mode), users will complain they don't know how to play the video.

Live photos are photos with a video, we could simply say short videos are live photos where the photo is more important than the video. Or if it was taken with an iPhone.

In addition you want us to play live photos inside the thumbnails? So basically we should run video player instances for all photos on the same page? I imagine, that this may bring your browser to its knees. Note that there is no such thing as "mouse over" for mobile users.

**Comment by lastzero** [comment]
Pushed another change that swaps width and height if video is rotated 90.

Still not sure how to improve UX for live photos. In PhotoPrism, all photos are technically "live photos" as we use full-resolution thumbnails and you can also open / download them as photo. Metadata handling is also the same.

**Comment by lastzero** [comment]
It's working on our demo, all basic features implemented. There is a separate issue for live photos. Please create a new issue if you find a bug! :)

![Screenshot 2020-05-14 at 21 25 38](https://user-images.githubusercontent.com/301686/81976891-7b9e0300-9629-11ea-8ff2-e29f23ae5551.png)

**Comment by v-marinkov** [comment]
I just played around with the demo. It's great to have video support implemented so fast! I will definitely start moving my gallery to Photoprism now!

I have to agree, however, that the video playback is not the most intuitive. If I understand correctly, the first frame of a video is part of the usual gallery and the video playback is an alternative lightbox effect of that gallery element. As such, there is no way to play the video while viewing the gallery zoomed in. Could we the video playback button show up also on the zoomed in view? Then clicking in will open the same lightbox player. I know this means two lightboxes (gallery and video player) open at the same time but at least the UX will be much more intuitive.

**Comment by aurora** [comment]
I am really satisfied with the new video support and will now switch to photoprism, too. The only thing that would be nice to have in addition would be the ability to play the video from the details-view, too.

**Comment by tborychowski** [comment]
Yes, clicking on a video should play the video.
When sharing I have to explain to my granny that she needs to "click on a small white triangle inside the thumbnail". Every time :-)
That should be simple to fix (and it doesn't make sense to preview the video thumbnail anyways), no?

**Comment by lastzero** [comment]
Good idea! Need to take care of bug reports first before having time for improving video UX though.
