### ISSUE TITLE
hide/upload nsfw usage info incorrect

### ISSUE THREAD

**Issue by jhmartin** [photoprism/photoprism#170]
https://github.com/photoprism/photoprism/blob/a4b475cbd69af7a665c65e4e808e795ee627e614/internal/config/flags.go#L203-L209 shows that hide-nsfw and upload-nsfw's usage info was copied from the read-only entry instead of describing the actual behavior.

**Comment by lastzero** [comment]
Thank you for reporting this! 🥳

**Comment by lastzero** [comment]
Updated Docker image will soon be available for testing.

**Comment by lastzero** [comment]
I'll close this since it seems to be fixed.
