### ISSUE TITLE
stop command not working because pid file does not exist

### ISSUE THREAD

**Issue by humboldtux** [photoprism/photoprism#171]
I wan to stop PhotoPrism server via the photoprism command line, but it can't because pid file does not exist:

```
$ docker exec -ti photoprism photoprism stop
INFO[2019-12-29T09:55:37Z] looking for pid in "/home/photoprism/.local/share/photoprism/photoprism.pid" 
FATA[2019-12-29T09:55:37Z] open /home/photoprism/.local/share/photoprism/photoprism.pid: no such file or directory 
```

I have to stop and restart my Docker container instead which is not the best option.

I am using docker container version 191228-1d76f74-Linux-x86_64 on Debian Linux.

**Comment by lastzero** [comment]
You only have to stop it if you started it in the background:

```
photoprism start -d
```

If you use Docker Compose, you can simply run it normally and use it's `-d` flag to run it in the background:

```
docker-compose up -d
```

**Comment by lastzero** [comment]
If you use Docker, the stop command obviously needs to be executed in the same container where the detached process is running - otherwise you have two independent instances that can't see each other. But in general when using Docker, you can just run Docker in the background and there is no need for running PhotoPrism as daemon.

**Comment by humboldtux** [comment]
Ok, thank you i got it, i am using the Docker container, and from the Dockerfile it is not starting as a daemon, so i can't use the stop command:

```
CMD photoprism start
```

So my use case is i modified the configuration file, and i want to restart as easily and quickly as possible the photoprism process. My only option is to "brutally" restart the whole container?

```
$ docker restart photoprism
```

Thank you

**Comment by lastzero** [comment]
Basically yes, that's how you would do it with Docker after changing the configuration. You don't keep a container running, it's not a complete virtual machine and can be restarted quickly. 
.

**Comment by lastzero** [comment]
I'll close this issue, but you're welcome to ask if you have more questions!

**Comment by tilusnet** [comment]
Hi,

I would also like to be able to stop the service (aka. 'photoprism stop') if the container's healthcheck starts failing.
I haven't figured out how to start photoprism in daemon mode via docker compose.
Any tips welcome!
