### ISSUE TITLE
People: Faces in non-primary files cannot be named

### ISSUE THREAD

**Issue by jackbrown1993** [photoprism/photoprism#1710]
**What does not work as expected?**

An error is seen in server logs and web GUI when trying to assign a Person to a cluster.

**How can we reproduce it?**

Steps to reproduce the behavior (on my instance):

1. Go to 'People'
2. Click on 'New'
3. Choose the name from the dropdown.
4. See error as per screenshot.

**What behavior do you expect?**

'New' face cluster to be assigned to known existing 'Person'.

**Can you provide us with example files for testing or screenshots?**

I don't think this bug is related to specific images. But the screenshot of the error is

<img width="301" alt="Screenshot 2021-11-09 at 11 43 08" src="https://user-images.githubusercontent.com/6218551/140918312-e7a2d868-a1ae-4405-925b-1526eae83d45.png">

**What version you are using?**

PhotoPrism®211018-e200f322-Linux-x86_64

**Any other helpful information?**

Error log shows:

```
time="2021-11-09T11:39:25Z" level=debug msg="api: abort /api/v1/markers/:marker_uid with code 400 (Invalid request)"
time="2021-11-09T11:39:25Z" level=debug msg="marker: can't update markers for non-primary files (find)"
time="2021-11-09T11:39:25Z" level=debug msg="http: PUT /api/v1/markers/mr1ympb1e7lj4q7k (400) [4.921164ms]"
```

Out of the three faces I tried to add to existing 'People' two failed in the same way, one worked as expected.

If you are reporting a UI or performance issue, please always provide details about your...

- Chrome on Mac

**Comment by lastzero** [comment]
That's interesting because non-primary files shouldn't have markers indeed. Did you manually change primary files or run index purge / cleanup commands?

Thanks for reporting! The first section should actually contain your bug description and not our placeholder text :wink:

**Comment by jackbrown1993** [comment]
Yes, I ran some of those commands as part of #1594 , I actually still see some broken thumbnails. Was just away on holiday so never got a chance to follow up.

**Comment by lastzero** [comment]
I have started a preview build so you can test these changes:
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
It would be great if you could try our development preview to test if the problem is fixed:

https://docs.photoprism.org/release-notes/#development-preview

**Comment by jackbrown1993** [comment]
Once on the build do I need to re-index or anything before testing?

**Comment by jackbrown1993** [comment]
I am now using the preview build and can confirm I no longer see the error and faces can be named as expected. Thank you!

**Comment by lastzero** [comment]
Excellent, thanks for testing!
