### ISSUE TITLE
Bug: Crash after fasenet loading on pi with docker

### ISSUE THREAD

**Issue by P-Verbrugge** [photoprism/photoprism#1713]
**What does not work as expected?**

When importing "originals", facenet is loaded. It seems that facenet is not loading properly or doing something and then crashes:

> time="2021-11-09T18:45:53+01:00" level=info msg="faces: loading facenet"
> /entrypoint.sh: line 94:     9 Killed                  "$@"

After the crash it restarts

**How can we reproduce it?**

1. Install PhotoPrism on Raspberry Pi OS (on a pi 4) with docker. Use container: photoprism/photoprism:latest
2. Upload folders to your drive
3. Login into PhotoPrism. 
4. Go to library -> Orignals
5. Start the import and watch the logs. Crash happens after facenet loading.

**What behavior do you expect?**

I expected the originals to be imported

**What version you are using?**

PhotoPrism 211018-e200f322-Linux-armv7

**Comment by lastzero** [comment]
Not enough RAM? Not 4 GB of Swap configured?

**Comment by P-Verbrugge** [comment]
My Pi has 4GB ram. I have not set the swap file. Not sure how to do that.

**Comment by lastzero** [comment]
Happy to help if you are a sponsor or become one 💎
