### ISSUE TITLE
All Photos were indexed - But several are missing (400+)

### ISSUE THREAD

**Issue by saber-rider1** [photoprism/photoprism#1715]
Hi there,

i have indexed all my photos on my server.
But some are missing.

For example one folder on the server contains 500+ photos.
But photoprism can find only 56.

I deactivate the quality filter and run the indexing of that folder again. But nothing changed.

I´m sure, there is a mistake from my side.
But what?

Do you have a hint for me?

Greets
saber

**Comment by lastzero** [comment]
Please don't use GitHub Issues for support requests and general questions. I'll move this to Discussions for you! 👍
