### ISSUE TITLE
Sort photos in ascending order in folders

### ISSUE THREAD

**Issue by xhabih** [photoprism/photoprism#1719]
I see that photos in "folders" are sort in descending order and in "albums" in ascending order.
As I have my collection organized externally as folders=albums I don't use albums at photoprism so I would like to see and share my folders in ascending order (oldest first).
I suggest an option to sort the photos in ascending order in folders or alternatively a way to automaticaly create albums from folders.

Thanks.

**Comment by graciousgrey** [comment]
In the folder edit dialog you can change the sort order.

See also: https://github.com/photoprism/photoprism/issues/405 and https://github.com/photoprism/photoprism/issues/353

**Comment by xhabih** [comment]
Sorry, I didn't notice the option since I have to scroll down on my mobile to see it.

**Comment by etsiot** [comment]
Can the folder sorting option become a global setting, since for large libraries with hundreds of folders, having to manually edit that is really tedious?
Or alternatively, why not have as default the oldest first sorting?

**Comment by graciousgrey** [comment]
@etsiot Feel free to leave a 👍 in the related issue:

- https://github.com/photoprism/photoprism/issues/405

**Comment by etsiot** [comment]
@graciousgrey , just did...
hope it gets implemented because it is such a tedious task to do it manually for large libraries

**Comment by xhabih** [comment]
> @graciousgrey , just did... hope it gets implemented because it is such a tedious task to do it manually for large libraries

Same boat here ;-)

**Comment by lastzero** [comment]
I've moved the related issue to "Upcoming", but can't promise an exact release date, as we need a short break before we release the next version.

**Comment by etsiot** [comment]
That's great news!!!!
