### ISSUE TITLE
UX: Images marked private still accessible in main view

### ISSUE THREAD

**Issue by rickysarraf** [photoprism/photoprism#1720]
**What does not work as expected?**

Images marked private are still accessible, albeit not obviously.

**How can we reproduce it?**

Here are the steps to reproduce the bug.

1. In the main PP view, select the images to mark as `Private`.
2. Mark them as `Private`. A `lock` icon will now appear on the marked images
3. From PP's top right corner, click on the refresh button.
4. Private images are not listed any more
5. Click on any of the listed images from PP's view
6. Cycle through the images using `arrow key`

I've validated the bug on https://demo.photoprism.org

**What behavior do you expect?**

Images, once marked private, should not be accessible in the main view.

**What version you are using?**

211109

**Any other helpful information?**

This is just the image still being in the browser/js cache. If you do a proper browser refresh, then the private images are not listed in the subsequent view.

**Comment by lastzero** [comment]
Seems similar to #1343, but this is fixed. Since it's just a cache issue and you can reload as a workaround, we might not fix this immediately - especially since we're working on a new photo viewer anyway.

**Comment by lastzero** [comment]
Have you tested if this is still the case? As long as you're viewing the same result set, I wouldn't consider a (now) private image in the viewer a bug that needs to be fixed, especially if it means increased code complexity (and thus maintenance effort) and/or performance degradation.

**Instead, we could add a note to the [Known Issues](https://docs.photoprism.app/known-issues/) in our docs to inform those who care?**

**Comment by rickysarraf** [comment]
I tried the steps to reproduce, in the current demo site. I cannot
reproduce it no more. So the issue seems to be fixed. Thank you 🎉

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by graciousgrey** [comment]
Thanks for testing :)
