### ISSUE TITLE
Bug: Symbolic links to media files are recognized as folders instead of being indexed

### ISSUE THREAD

**Issue by michitux** [photoprism/photoprism#1723]
**What does not work as expected?**

I manage my photo collection using [git-annex](https://git-annex.branchable.com/). Thus every and thus every image or video file is a symbolic link to some file in `.git/annex/objects/`. Unfortunately, PhotoPrism doesn't index any file that is managed by git-annex, they just appear to be skipped. Some other files that are not symbolic links are indexed, though and the symbolic links seem valid inside the Docker container (they are relative and work fine in other containers I use) so I'm hoping that this is not setup error. In the "Library -> Originals" section, those symbolic links are displayed but they are displayed as folders and when I click on one, the folder just reloads and a new error log entry ` folder: readdirent: not a directory` appears in the log.

**How can we reproduce it?**

1. Create a symbolic link to an image file using, e.g., `ln -s existing_image.jpg foo-bar.jpg` on Linux
2. Run `photoprism index` (optional)
3. Go to `Library -> Originals`
4. Go to the folder containing the symbolic link
5. The symbolic link is displayed as folder
6. Click on the symbolic link
7. Go to `Library -> Errors`
8. An entry ` folder: readdirent: not a directory` exists

**What behavior do you expect?**

Symbolic links to image or video files are followed and displayed as if they were regular files instead of being displayed as directories. Note that symbolic links to files should even be followed if the target is in a hidden (starting with `.`) folder. It might be tricky to determine permissions as while the target file might be read-only and in a read-only folder (this is the case with git-annex), it might still be possible to rename or delete the symbolic link. For the moment at least, I would totally be happy with read-only support for symbolic links, though.

**Can you provide us with example files for testing or screenshots?**

This shows how symbolic links to images are displayed:

![Screenshot](https://user-images.githubusercontent.com/198317/141374113-887f937c-2964-477e-8565-cd06a0ecfeb2.png)

**What version you are using?**

PhotoPrism® 211018-e200f322-Linux-x86_64
     
**Any other helpful information?**

This is with the official docker container, host system is Arch Linux, all files are on local file systems (ext4/btrfs) but I don't think this should matter.

**Comment by lastzero** [comment]
👉  &nbsp; [Support indexing of symlinked files #1049](https://github.com/photoprism/photoprism/issues/1049)
