### ISSUE TITLE
SQLite: "database is locked" error

### ISSUE THREAD

**Issue by tuosce** [photoprism/photoprism#1734]
***System***
TrueNAS-SCALE-22.02-RC.1-1 - via **Docker** (truecharts.org)

***PhotoprismApp Version***
20211018_5.0.8

***Application Events***
none - not relevant

***Application Logs***
ERROR: database is locked

**Describe the bug**
While importing, partial media processing seems to take place at the same time. Too many concurrent database operations?

**To Reproduce**
1. Import media (30k+)
2. Observe logs

**Actual behavior**
Media processing/importing seems to be taking a long time as the database gets 'locked'.

**Expected behavior**
Media processing does not slow down (database doesn't get locked)

**Additional context**
Might be relevant - https://github.com/photoprism/photoprism/issues/392

**Comment by lastzero** [comment]
Which database do you use?

**Comment by tuosce** [comment]
SQLite

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql:

> The way MariaDB and MySQL handle multiple queries is completely different and optimized for high concurrency. SQLite, for example, locks the index on updates so that other operations have to wait. In the worst case, this can lead to timeout errors.

We could solve the problem by implementing a high concurrency layer on top of SQLite, but that would mean reinventing the wheel (MariaDB). Out of scope, considering how many high value feature requirements are waiting to be implemented.
