### ISSUE TITLE
Live Photos: Add support for Google Camera Motion Photos

### ISSUE THREAD

**Issue by Fylax** [photoprism/photoprism#1739]
Similar to how you implemented the Apple Live Photo (#177) and to the currently developing #439.

Google Camera has its way of creating Motion Photos: it makes a JPEG and then the MP4 inside the same file.

The "Motion Photo" is identified by:

    XMP:MicroVideo: 1 <- Before Android 11
    XMP:MotionPhoto: 1 <- After Android 11

Extracting the video is straightforward and doable in a few bash commands:

    srcfile=image
    offset=$(grep -F --byte-offset --only-matching --text ftyp "$srcfile")
    offset=${offset%:*}
    dd if=$srcfile of=$srcfile.mp4 bs=$((offset-4)) skip=1

*Note:* I tested it only with Android 12 Motion Pictures. Moreover,  versions <11 had the offset defined in an XMP.

**Comment by hmueller01** [comment]
A quick note. 
> offset=$(grep -F --byte-offset --only-matching --text ftyp "$srcfile")

This works only with GNU grep. BSD grep (macOS default) returns no match!
Took me some time to figure out ... hope this helps others.

More infos about Android 12 Motion Photos from [Alan Orth's blog](https://mjanja.ch/2021/10/stripping-embedded-mp4s-out-of-android-12-motion-photos/).

**Comment by wechsler42** [comment]
According to [Alan Orth's blog](https://mjanja.ch/2021/10/stripping-embedded-mp4s-out-of-android-12-motion-photos/) it seems that ..."As of Android 12 it appears that the MP4 header in Motion Photos has changed from ftypmp4 to ftypisom".. the header has changed which indicates the embedded video. See also the probably similar [issue and the solution](https://github.com/cliveontoast/GoMoPho/issues/23) for GoMoPho.

**Comment by tribut** [comment]
When "HEIF pictures" is enabled, Samsung Camera appears to use this format also ("XMP:MotionPhoto: 1"), as opposed to their custom format described in #439.

**Comment by tribut** [comment]
Here is a sample `.heic` with embedded motion photo from a Samsung phone that uses this method, in case you need something to test:

[samsung-motion-heic.zip](https://github.com/photoprism/photoprism/files/9349873/samsung-motion-heic.zip)

**Comment by alex-phillips** [comment]
Just to add some information I found here, while older images had the offset in XMP under MicroVideoOffset, it seems newer versions have defined this offset in a separate `Directory Length` value. See this comment on Nextcloud photos here: https://github.com/nextcloud/photos/issues/365#issuecomment-982014436

Do note: there are 2 entries of that metadata key and the second one needs to be used.

Also, some good info here on the "old" vs "new" formats and the hex values you can match against in the file: https://linuxreviews.org/Google_Pixel_%22Motion_Photo%22

**Comment by sethgillett** [comment]
Just a note for anyone having issues with the ```grep``` command not returning a byte offset on macos, prefixing the command with ```LC_CTYPE=C``` seems to fix the issue.

**Comment by grahamjpark** [comment]
I'm new to PhotoPrism. I had just read this thread last week and then saw a new blog from ente on the topic come out today. Dropping here for future reference.

https://ente.io/blog/tech/android-motion-photos-flutter/

**Comment by mholt** [comment]
^ That's basically what I do in Timelinize. Works pretty well, and the information in that article looks accurate by my recollection.

**Comment by lastzero** [comment]
My latest commit adds support for direct streaming of videos embedded in JPEG images. To make this possible, we've added native support for the ISO base media file format on which MP4, QuickTime (MOV), and HEIC are based.

### HEIC Files

In order to play videos embedded in HEIC image files, some more changes had to be implemented, as these are based on the same standard as the videos and therefore the HEIC at the beginning has to be ignored to find the MP4 video at the end of the file. This should also be working now.

### Related Information

- https://github.com/photoprism/photoprism/blob/develop/pkg/live/README.md
- https://github.com/photoprism/photoprism/blob/develop/pkg/video/README.md
