### ISSUE TITLE
Albums: States should be grouped by country name, not code

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#1740]
Sorting the states by country is a move in the right direction, however right now the countries are sorted by their ISO code and not their name. This leads to a weird order, for example in the demo instance Switzerland is before Germany and South Africa is after USA.

**Comment by lastzero** [comment]
It's because they now have a different slug and and additional state field while existing albums don't have this. Developed it yesterday and just started to test ourselves...
