### ISSUE TITLE
Keywords: Support Leetspeak 1337

### ISSUE THREAD

**Issue by c0de-fox** [photoprism/photoprism#1741]
**What does not work as expected?**

When creating keywords for images, you cannot have numbers as part of the keyword. 

**How can we reproduce it?**

1. Open the "[Pencil Icon] Details panel" for an image
2. In the keywords section, try to add a keyword. For example: c0de
3. Click Apply
4. Notice that the number, and the text in front of the number are removed, leaving the keyword "de".

**What behavior do you expect?**

The keyword field to support numbers between letters.

**Comment by lastzero** [comment]
It's because numbers are no words, with the exception of leetspeak which we currently don't support (you need to release at some point...).

**Comment by alopexc0de** [comment]
It's a bit of an anti-feature to not support numbers. From what it seems, this was an intentional decision but it's not documented.

I'll vote on that idea, but it's pretty critical for gallery software to support my name as a keyword, so I'll be trying other alternatives. Unfortunately I'm not skilled enough in Golang to add this myself

**Comment by lastzero** [comment]
Are you serious? :D We didn't implement it this way to punish you. PhotoPrism merges data from many different sources, often of poor quality, so it's a good idea to filter out noise.

Edit: Removed from our roadmap until you've had time to try alternatives. Let us know if you still need it then! :+1:

**Comment by alopexc0de** [comment]
I saw the original comment before the edit, and I wasn't making a jab at your funding or the development resources.

To me, a keyword is just a string so I assumed that it could handle the characters that a string can. Filtering out the noise should be a user choice, not a design decision. 

Yes nobody complained about it in 4 years, but my name is "c0de". It is not "code" and it's incorrect to tag things as such.

**Comment by lastzero** [comment]
Plonk.

**Comment by lastzero** [comment]
Even tweeted about the issue, but all we get are snarky comments... Does that usually work for you?

**Comment by lastzero** [comment]
It's typically not a good idea to put random hashes and stopwords in a text index as it increases storage requirements and reduces performance. Check out how hex numbers, commonly used for hashes and checksums, look like. They are everywhere in metadata and filenames. I was busy when I wrote earlier, so couldn't go into technical details.

**Comment by lastzero** [comment]
And no, this doesn't mean we can't find a solution now that it was reported. Feel free to reopen and say something that makes us want to fix this.

**Comment by lastzero** [comment]
Also feel free to help improving our docs. Source is public and you don't even need to learn Go first.

**Comment by c0de-fox** [comment]
I've cleaned things up and deleted the tweets. I don't care if you decide to fix this, but I will say that I'm sorry for being aggressive.

**Comment by lastzero** [comment]
Our idea was to add tags for manual categorization incl numbers + emojis. Ideally, we can keep labels and keywords "normalized", so they can easily be translated (e.g. with DeepL) and matched with each other.

You can find more information on the difference between keywords and labels in our FAQs: https://docs.photoprism.org/user-guide/faq/
