### ISSUE TITLE
TIFF: Use Darktable for conversion to JPEG

### ISSUE THREAD

**Issue by maxammann** [photoprism/photoprism#1747]
**Is your feature request related to a problem? Please describe.**

I scan negatives and invert them later in darktable. That means I have `.tif` files with `.xmp` sidecar files next to them. PhotoPrism does not asses tif files as raw files like defined [here in code](https://github.com/photoprism/photoprism/blob/b081f27e17215b34b9865f652bffb988b3be5031/internal/photoprism/convert.go#L193).

**Describe the solution you'd like**

I would like PhotoPrism to use DarkTable whenever it sees a tif file with a corresponding xmp file.

**Describe alternatives you've considered**

Currently I manually run darktable to generate jpg. This has the disadvantage that the exported files can get out of date. 

**Additional context**

None

**Comment by graciousgrey** [comment]
Might be related to https://github.com/photoprism/photoprism/issues/1747

**Comment by lastzero** [comment]
See:
- #1612

If Darktable works for TIFF, we can use it straight away. Does it support all features?

**Comment by maxammann** [comment]
Darktable works just fine for the conversion of TIFS for me. I could provide samples.

**Comment by lastzero** [comment]
You could test the files attached to the other issue for us and report if Darktable can convert them properly 👍

**Comment by maxammann** [comment]
We can close one of the issues then. Thanks!

**Comment by graciousgrey** [comment]
Thanks for testing :)
