### ISSUE TITLE
Transcode videos on-the-fly

### ISSUE THREAD

**Issue by maxammann** [photoprism/photoprism#1748]
**Is your feature request related to a problem? Please describe.**

Currently ffmpeg is used to start the transcoding of a video as soon as it is played in PhotoPrism. This has the disadvantage that you have to wait up to several minutes when playing a video.
My video collection consists of >50GB of h265 and h264 encoded videos. The h265 video files definitely need to be transcoded before playback in a browser. For h264 encoded files in a MP4 container I would expect that no transcoding is needed.

**Describe the solution you'd like**

I would be awesome if the playback would start immediately and ffmpeg would continue to run in the background.

**Describe alternatives you've considered**

Currently I have disabled ffmpeg and exclude MP4 files from indexing.

**Additional context**

None

**Comment by graciousgrey** [comment]
Why don't you transcode videos upfront using the convert command (https://docs.photoprism.org/getting-started/docker-compose/#command-line-interface)?
You could use the scheduler to run the command regularly in the background.

**Comment by lastzero** [comment]
Streaming of transcoded videos in real time is out of scope for now for a number of reasons:

- complexity
- server performance, especially on a Raspberry Pi
- the capability may depend on specific file types and bitrates
- it needs a lot of work and testing which our current roadmap doesn't allow
- watching movie-length videos isn't a core use case of PhotoPrism

For watching large videos and transcoding them while streaming, we recommend https://jellyfin.org/.

All hosted photo apps I'm aware of transcode upfront and put the transcoded files on a CDN. You can use the `photoprism convert` command for that as Theresa recommended. This will avoid waiting and works on all hardware, not just the fastest servers or with a low bitrate.

**Comment by maxammann** [comment]
Alright I understand :+1: 

In my case the issue is that the upload and download to my storage is  limited <100Mbit because my files are stored on a NAS at home and photoprism runs in the cloud.

In the cloud I do not have a lot of storage <20GB because it is quite expensive there.
