### ISSUE TITLE
Metadata: Set altitude even if coordinates are missing

### ISSUE THREAD

**Issue by hjed** [photoprism/photoprism#1749]
**What does not work as expected?**

 GPS Location parsing fails  with the message ` metadata: failed parsing GPS coordinates in IMG_20170611_183659.jpg (exif)` for images that only have the "GPS Altitude Reference" set in the GPS data and no actual co-ordinates. Apparently my old OnePlus 3t did this on quite a lot of photos.

Note this isn't a massive issue as it doesn't appear to break anything that I can work out. 

**How can we reproduce it?**

Try and index the attached image:
![IMG_20170611_183659](https://user-images.githubusercontent.com/6956262/142856266-33a0a5de-96b2-47a4-9096-17e64f32961b.jpg)

**What behavior do you expect?**

It shouldn't try and index GPS data from this image and doesn't need to log an error. 

**Can you provide us with example files for testing or screenshots?**

![IMG_20170611_183659](https://user-images.githubusercontent.com/6956262/142856266-33a0a5de-96b2-47a4-9096-17e64f32961b.jpg)

I can provide other examples if needed but they all look pretty similar

**What version you are using?**

211018-e200f322-Linux-armv7l

**Comment by hjed** [comment]
Hey I'm still seeing similar errors - not exactly the same thing so happy to open a new bug but I think the cause is likely the same error (GPS data present but not lat/long) - Here's an example image
![DSCN7980](https://user-images.githubusercontent.com/6956262/145784010-f6bb6648-3c29-4238-9a15-1c873812baae.JPG)

**Comment by graciousgrey** [comment]
@hjed I tested with this file. It does not contain GPS information in it's exif data

`exiftool -j yourfile.jpeg | grep GPS` shows

` "GPSVersionID": "2.3.0.0",
  "GPSImgDirectionRef": "Magnetic North",
  "GPSImgDirection": "undef",
`

that's why there is no lat/lng set. 
I also do not get an error when indexing this file.
