### ISSUE TITLE
Video Being Categorized as Live Photo

### ISSUE THREAD

**Issue by simoncoul** [photoprism/photoprism#1760]
I was browsing the Videos tab trying to locate a video I had taken on my mobile, but it was not present. I confirmed the date on my mobile and then looked in the Search tab I was able to locate it however it was categorized as a Live Photo. I am unsure of why this is happening and could also account for several other videos I was not able to locate. The video was shot on a Samsung S9+ and I have uploaded it to Google Drive as it is around 20MB.

https://drive.google.com/file/d/1AFO_KzyI4Na364Io6ZF_8iARyf3tGfQP/view?usp=sharing

EDIT: It also does not show up under the Stacks tab.

Simon

**Comment by lastzero** [comment]
Videos up to 3s are shown as live photos. This was a feature request we implemented for our users.

**Comment by simoncoul** [comment]
Sorry, I don't understand the use case that was user requested (could you provide the # so I could read up on the context). If I take a video I would expect it to be in the video tab, regardless of its duration.

Is there a way to use the container type to also categorize it as a video? IE, an HEIC files to displayed as a live photo thumbnail and categorized as a photo; whereas a <=3 second MP4/mov/etc is displayed as live photo thumbnail but still categorized as a video.

**Comment by lastzero** [comment]
Yes, if you formulate this as another feature request and wait a little :)

**Comment by lastzero** [comment]
I'm sure you find the original issue if you search. Writing from a mobile phone, not working anymore.

**Comment by simoncoul** [comment]
I've reviewed the previous threads and will submit a feature request.
