### ISSUE TITLE
Settings: Custom themes 

### ISSUE THREAD

**Issue by jakiisheep** [photoprism/photoprism#1763]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
I would like to be able to make custom themes for PhotoPrism (Custom CSS)

**Describe alternatives you've considered**

For now nothing

**Additional context**

**Comment by lastzero** [comment]
We will make custom themes available to teams and organizations in the [upcoming Pro Edition](https://photoprism.app/teams#compare) and also look for ways to make it available to [PhotoPrism+ Members](https://photoprism.app/membership).

Why not for everyone? We've been asked many times by commercial users how they can change the branding of the Community Edition to monetize it and sell it as their own solution.
