### ISSUE TITLE
Places: Improve Location Details in Border Regions

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#1767]
Follow up issue for:
- #1664

Places on the German / Austrian border where the state is Bayern and the country is Austria:

```
s2:479cf539b754
s2:479cf539c424
s2:479cf539c6b4
s2:479cf539da1c

s2:479c8df0b68c
s2:479c9209e37c
s2:479c920b7314
s2:479c920b731c

s2:479c8acaae24
s2:479c8acaae74
s2:479c8acab2cc
s2:479cf5350b64
s2:479cf5350b7c
```

Places on the Bulgarian/Greek border, where the name is in Bulgarian, the street is in Greek, label and country are Bulgaria, but the state and keywords are in Greek:

```
s2:14a988c8c95c
s2:14a988ce6e44
s2:14a988ce6fa4
s2:14a988d41bdc
s2:14a988d50efc
```

And as a good example, here is a place on the Austrian / Swiss border, where everything is correct:

```
s2:479b4b5ebf44
```

**Comment by kvalev** [comment]
All of the border issues that I had are now resolved. Thanks a bunch for the quick fix!
