### ISSUE TITLE
Bug: No change after I changed docker-compose.yml

### ISSUE THREAD

**Issue by jakobroehrl** [photoprism/photoprism#1775]
If I change the docker-compose.yml and do a 
```
docker-compose stop photoprism
docker-compose up -d photoprism
```
as described here: https://docs.photoprism.org/getting-started/docker-compose/#step-2-start-the-server
the changes are not applied. Tried it e.g. with changing the admin password.

**Comment by graciousgrey** [comment]
The admin password can only be changed in the docker-compose.yml before the first start of the instance.
The other variables can be changed any time.
To change your password after the initial start, you can use the web ui (https://docs.photoprism.org/user-guide/settings/account/).

**Comment by jakobroehrl** [comment]
Sorry, it's not working. 
Changed for test purposes this into tue:
 PHOTOPRISM_DISABLE_FACES: "true" 

After saving the file and 
docker-compose stop photoprism && docker-compose up -d photoprism

in the UI I can still see the faces and in the settings faces is still enabled:
![image](https://user-images.githubusercontent.com/24530680/143859511-bcff8f81-0e43-45b7-8664-696894895e19.png)

**Comment by graciousgrey** [comment]
That's expected, the option from your screenshot is just for the UI. 
PHOTOPRISM_DISABLE_FACES hinders PhotoPrism from indexing faces, but it does not delete already existing faces.

**Comment by filipiff** [comment]
> If I change the docker-compose.yml and do a
> 
> ```
> docker-compose stop photoprism
> docker-compose up -d photoprism
> ```
> 
> as described here: https://docs.photoprism.org/getting-started/docker-compose/#step-2-start-the-server the changes are not applied. Tried it e.g. with changing the admin password.

you should use the command "docker-compose down" in order to recreate the container with "docker-compose up -d"

**Comment by lastzero** [comment]
Please use GitHub Discussions for 👉 INSTALLATION PROBLEMS, SUPPORT REQUESTS, and GENERAL QUESTIONS:

  https://github.com/photoprism/photoprism/discussions

THANK YOU! 💐
