### ISSUE TITLE
Places: Incorrect state information for locations around Paris

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#1776]
I discovered a bunch of high-profile locations in and around Paris that have the wrong state information. Below are two examples.

Versailles
https://places.photoprism.app/v1/location/47e67db946ec
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=9087588&class=tourism

Louvre
https://places.photoprism.app/v1/location/47e66e2672b4
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=568455193&class=tourism

In both cases (and a bunch of others I have noticed), the places API reports the state as `France métropolitaine` (mainland France), even tho the data in Nominatim correctly shows the state being `Île-de-France` (admin level 4).

**Comment by kvalev** [comment]
Thanks a lot for the quick fix! Now the state information in places is correct 👏 

However I dont think the mapping in code is correct - `France métropolitaine` stands for mainland France (meaning the European part France without all the overseas territories). As such it cannot be mapped to a state - this would be like mapping Germany to Berlin.

**Comment by lastzero** [comment]
This isn't a state, so it must be mapped to something. Won't happen if the state is correct.  Not sure why photon does this, but Nominatim is correct. So it's double fixed.

**Comment by lastzero** [comment]
Note that other fields such as name and category have changed as well. Wasn't fixed with mapping.

**Comment by kvalev** [comment]
I still think it is wrong to have the mapping, but you are right - as long as the Places API returns the right data, the mapping wont be used.
Anyway I ran few tests and the geo-data is now perfect! Thanks a lot!

**Comment by lastzero** [comment]
Issue seems to be fixed in Photon meanwhile.
