### ISSUE TITLE
Config: Document that the log file option is for daemon mode only

### ISSUE THREAD

**Issue by duc00** [photoprism/photoprism#1778]
**What does not work as expected?**

Photoprism log file is not written when I set the `PHOTOPRISM_LOG_FILENAME` env variable. Truncated output of `photoprism config`  is:
```
NAME                      VALUE
debug                     true
log-level                 debug
log-filename              /photoprism/storage/photoprism.log
```

**How can we reproduce it?**

- Use latest image latest image (`20211128` at the time of writing)
- Set `PHOTOPRISM_LOG_FILENAME` to `/photoprism/storage/photoprism.log` and `PHOTOPRISM_DEBUG` to `1`
- Run the container and exec into it
- `ls /photoprism/storage` does not show log file

**What behavior do you expect?**

Log file is written at the specified location in `PHOTOPRISM_LOG_FILENAME` env variable.

**Comment by graciousgrey** [comment]
Did you use `photoprism start `or `photoprism start -d`?
The logfile is only expected to be  created for the -d variant.

**Comment by lastzero** [comment]
Shouldn't have removed the remark in the parameter description. This config option is used when running PhotoPrism in daemon mode only. Otherwise, it writes to stdout when Docker typically catches it. Run this command to see the logs:

```
docker-compose logs --tail=25 -f
```

**Comment by lastzero** [comment]
Flag description and docs have been updated:
- https://github.com/photoprism/photoprism-docs/commit/5a818fc991f75cf8bff483ee1049f77d495b44f8

**Comment by duc00** [comment]
That's it! I was not running daemon mode. Thank you for the quick update. 💯
