### ISSUE TITLE
Explicitly expose the thumbnail cache location via Docker script

### ISSUE THREAD

**Issue by scotws** [photoprism/photoprism#178]
**As a user who stores his photos on ZFS datasets, I would like to be able to expose and explicitly set the location of the thumbnail cache in the Docker creation script.** 

**Why:** Bulk storage and thumbnail cache could be stored on different physical media: The photos themselves on traditional HDs, the thumbnails on SSDs or NVMes. This should make all work with thumbnails faster. 

**What does this have to do with ZFS?** All file systems should be able to make use of the basic mechanism. There are secondary reasons for ZFS users **(skip this if you don't care)**: The datasets ("file systems" in legacy terms) allow tuning of record size and various other parameters.  On a zpool ("volumes") level, the bulk storage could be in raidz pools for greater storage efficiency and the thumbnail dataset on a mirrored pool for greater speed. Also, this would allow specific snapshot and backup scripts for thumbnails (can always be regenerated from original photos) and the original photos themselves (oh crap, where are my backups). 

**Example:** A default Docker script could then read:
```
docker run -d \
  --name photoprism \
  -p 2342:2342 \
  -v /tank/myRawPhotos:/home/photoprism/Pictures/Originals:ro \
  -v /dozer/thumbnails:/home/photoprism/cache/thumbnails \
  photoprism/photoprism
```
In this example, the photos themselves are exposed through the first volume (`-v`) line and read-only. "Tank" is assumed to be a ZFS raidz2 pool with slow but large HD drives. The second line is the new stuff and assumes that "dozer" is mirrored pool with fast SSD or NVMe drives.

**Alternative implemenation:** It might be a better idea to expose all cached data instead. However, I only see thumbnails in the cache folder, unless I'm looking in the wrong place.

**Implementation:** If I understand the file structure correctly (very unlikely since I have just started looking at it), you should actually be able to do this _right now_ without changing a line of actual code. This would however require freezing the thumbnail location in the directory tree, which may be too early in this stage of development. 

**Documenation requirements:** Support for this ability should be documented with the reasoning behind it and an example Docker script provided. 

**Testing requirements:** Complete test build of a system with two different file systems and splitting off the location of the thumbnail pool. Sorry, I'm not familiar enough with the Photoprism test suite to say if this could be automated.

**Priority:** Low. This is a nice-to-have optimization feature.

Thank you!

**Comment by lastzero** [comment]
Does changing the cache path work for you and do you want thumbs to be stored outside the cache directory?

```
Option: --cache-path PATH  
Description: cache PATH (default: "~/.cache/photoprism")
Environment: PHOTOPRISM_CACHE_PATH
```

You can see all options with `photoprism help` and the values with `photoprism config`

**Comment by scotws** [comment]
After installing Photoprism on a Ubuntu 18.04 LTS server based NAS in a "naive Docker download" way (not with the compose file), I have it working fine with two separate data sets and this calling script:
```
docker run -d \
  --name photoprism-test \
  -p 2342:2342 \
  -v /tank/testphotos/:/home/photoprism/Pictures/Originals:ro \
  -v /switch/testcache/:/home/photoprism/.cache/photoprism \
  photoprism/photoprism
```
"Tank" is a raidz2 pool and "switch" a single SSD ZFS drive (for tests like these only). Works absolutely fine accessing it from another machine. Can't say much about the speed without formal tests because it's probably all in the RAM cache (ARC) anyway by now. 

So the easiest thing for everybody involved at the moment would probably be to just declare this a documentation issue. We could just close it here and I'll formally open an issue over in the photoprism-docs repo, where I can add a few lines describing what this does and why somebody would want to do it?

**Comment by lastzero** [comment]
We don't have time to write lots of documentation just yet, especially since details might change and then we have to redo it and/or keep it updated. Any pull requests are welcome though!
