### ISSUE TITLE
Videos: Present multiple sources for a video to avoid transcoding when not strictly necessary

### ISSUE THREAD

**Issue by Fylax** [photoprism/photoprism#1788]
ONLY CREATE AN ISSUE AFTER YOU HAVE VERIFIED THAT NO SIMILAR IDEA EXISTS

**Is your feature request related to a problem? Please describe.**

As a user in mobility with limited bandwidth, I want to shink as much data as possible when watching videos.

**Describe the solution you'd like**

While `ffmpeg` transcoding is an excellent solution, it would be nice to let the browser use the video it prefers.

PhotoPrism already uses the `<video>` tag for displaying videos. This tag allows defining multiple inner and equivalent `<source>` tags, which in turn let the browser pick the first playable video.<sup>[1](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source)</sup>

The proposal is to add one source for each stacked original video and place the transcoded one as a last-resource fallback.
In an ideal world, `ffmpeg` would never be invoked, saving CPU time and disk space (unless manual transcoding via CLI took place).

Always in an ideal world, PhotoPrism would extract the codec of the video during indexing and decorate each `<source>`  with a `codec`<sup>[2](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/codecs_parameter)</sup> attribute.

If such a feature is deemed useful and/or interesting, I can help with studying the various `codec` attribute option and possibly (limited by my scarce go knowledge) write down a snippet to extract it properly.

**Comment by lastzero** [comment]
I see this as being implemented with this:

- #2461
- #440
- #513 
- #2379

**Comment by lastzero** [comment]
If you consider **variable bitrates chosen by the browser** to be necessary beyond the bitrate limit we have already implemented, feel free to submit a new feature request describing the use case/expectations in a way that can be realistically implemented and tested by us. 👍

Edit: Found this 👇

- #1070
