### ISSUE TITLE
Album sharing with random URL and auto expiration

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#18]
**As a user, I want to share links to albums so that friends can view my photos without giving away my admin password.**

In a later release, we might offer hosting on our servers for selected (shared) photos / albums with auto expiration, so that friends don't need direct access to a user's PhotoPrism server instance at home.

**Comment by vinz243** [comment]
I would suggest that the link could be either 
 - a JWT token that expires
 - a decryption key (might be better privacy wise)

**Comment by lastzero** [comment]
A random token is a random token, no?

**Comment by vinz243** [comment]
-  a JWT token would remove the need to keep track of generated token and the need to remove them after.
 -  a decryption key is interesting in the case where encryption would be implemented (which would be nice)

**Comment by lastzero** [comment]
Need to think about it, but nothing I would do for a first release. Adds complexity.

**Comment by vinz243** [comment]
Using JWT tokens actually makes it easier, because they are persistent across restarts without having to save them to a file/database, that's why  I suggested that

**Comment by vinz243** [comment]
URL would be a bit long like http://photoprism.org/s/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyfQ.My0Z4aAFwQeWBEcThI0V9tqCzTojhL9imCgZj1N0-HA

But that makes it quicker and more stable to implement share tokens/authentication than a database save. URL shorteners can be used if it needs to be smaller

**Comment by hooram** [comment]
The way I approached this problem in a similar project of mine is to have different user accounts, and set albums and photos sharable to particular set of users, as well as being able to make them public. This way, you can share specific albums/photos to specific people, in addition to setting them public, so that anyone can view them without having to have an account.

**Comment by dennorske** [comment]
Has this been considered as a part of the self-hosted solution as well? (I am not sure if you were discussing having it on a paid-service-website or so) - I'd love to see this coming up in photoprism and I know it is on your timeline. Sharing albums + individual photos. 

Can I somehow fund this part of the project as a sponsor as well?

**Comment by lastzero** [comment]
We'll get to this when browsing by date / timeline is done :)

**Comment by RafPe** [comment]
I like the idea of JWT in the URL which would make sure we do not ( in my opinion ) compromise security in favour of sharing album. 

In regards to the long url - we could try maybe to do the same as tinyurl ? Make it base36 ? 

And we can also make it similar to what dropbox does when u share an album/folder = ``https://www.dropbox.com/sh/uymjsmjp92aeqsns/AABVOdUO2I0aHwc5Y0s6wmd4a`` 

Where from the above we could have `https://some-domain.com/share/<base36-token>` and in token itself we could save information regarding expiration and in future expand it if needed.

**Comment by lastzero** [comment]
@RafPe What's the specific advantage of using a JWT compared to just use a random token (plus optional password) and store expiration etc in our database?

**Comment by RafPe** [comment]
I could see this as a potential step into future multi user auth. 

If we are ok with extending database entity for this purpose then I see no objections on that approach as well if it would help with MVP

**Comment by RafPe** [comment]
I noticed you created the album share functionality already. So would we consider this to be done then ?

**Comment by lastzero** [comment]
Where did you see that? :D It's not complete, started working on it though.

**Comment by RafPe** [comment]
I pulled most recent versions as I still try to set up my env to contribute :) And saw that albums now got ShareUID which led me to the remaining structs and objects 👍

**Comment by lastzero** [comment]
True, but there is no UI / UX yet. Did the file browser today, tomorrow moments. Maybe I get to sharing later this week or next week.

**Comment by RafPe** [comment]
Ok - so will not try to imterfere on this one. Will try to peak some other parts for MVP. On a sidenote - whenever you could - can you share how u set up your dev env ?

**Comment by lastzero** [comment]
Did you see our Wiki / Developer Guide? https://github.com/photoprism/photoprism/wiki/Getting-Started

**Comment by lastzero** [comment]
That was a huge one! Almost done, only expiration check is missing 🥳

**Comment by lastzero** [comment]
Looks done to me, please test :)

**Comment by lastzero** [comment]
Album title and description are now used for site metadata, e.g. when you share a link on social media. Shared albums will look like this:

![Screenshot 2020-06-27 at 09 33 42](https://user-images.githubusercontent.com/301686/85917480-b74bff80-b85a-11ea-85c3-d5500cb281ea.png)

**Comment by lastzero** [comment]
Another UX improvement: URL will now include a **slug** instead of the **album id**. When you click it, you will be redirected.

**Comment by lastzero** [comment]
Today's change improves share preview images. Make sure to **test with a fresh database** (or manually delete the table) as the `links`  table was modified once again, basically just renaming columns. We want to make sure our concept is clear to developers: One token can be valid for multiple albums (shares), so that you don't need to create multiple links for the same group of people if you want to share more than one album.

**Comment by wiwie** [comment]
is sorting/filtering in shares planned?

**Comment by dennorske** [comment]
I'm testing this tomorrow. This is clearly going to be a big game changer when working perfectly. Good job guys!

**Comment by lastzero** [comment]
Received some test reports and it seems to work for everyone. Please create a new issue for bug reports!
