### ISSUE TITLE
Mobile upload: Figure out why Exif data is missing

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#181]
**As an Android user, I want to upload photos with exif metadata so that PhotoPrism can index their location and proper time (with timezone).**

These photos were uploaded from a Huawei P30 using Chrome (Android 10), but I've seem similar results when taking photos with my iPhone:

![Screenshot 2020-01-05 at 21 51 32](https://user-images.githubusercontent.com/301686/71785936-e436fc80-3005-11ea-890d-68c60dc55b7d.png)

Acceptance Criteria:
- [ ] Find and document the reason why Exif data is missing
- [ ] Suggest a solution

**Comment by lastzero** [comment]
Might in fact be an issue with my phone... only recently switched to Android, but location tagging is on.

**Comment by thielepaul** [comment]
I cannot reproduce this issue with my phone, does this only occur with a certain combination of browser / filechooser / android version?

Phone: Oneplus 3T, OxygenOS 9.0.6 (Android 9)

Tested browsers:
* Firefox Beta (org.mozilla.firefox_beta)
* Google Chrome (com.android.chrome)

Tested filechoosers:
* Google Files (com.google.android.apps.nbu.files)
* Oneplus Camera (com.oneplus.camera)

**Comment by lastzero** [comment]
Only my edited photos have a GPS position, that's strange but must be an issue with Huawei. Not sure sure what to do about it.

**Comment by fresswolf** [comment]
It's a bug with many Huawei devices. If you switch once to the front camera and back to the back camera you'll have the exif data in the photos (just waiting doesn't help anything).
