### ISSUE TITLE
UX: Update Person Selector Menu to have better contrast and maybe a visual arrow queue

### ISSUE THREAD

**Issue by isleshocky77** [photoprism/photoprism#1824]
Currently the People Selector Pop-up has very similar background colors for the list of People as well as the Person which is currently selected (i.e. using arrow keys).

This causes an issue as it is extremely easy to select the wrong person causing major time issues having to go through all of the possible images of the two people to back it out and correct.

This is a problem on most of the themes I've looked at.

It can also be an issue if there are only two People as you're not sure which one is selected and which is the alternate color.

It might be nice to have a prefix appear next to the name to show that is the name that is currently selected. An arrow or bullet would suffice. This would also help for people who are color blind.

I've looked into doing custom css or theming, but I believe this is a major issue across the full application.

**Comment by lastzero** [comment]
@graciousgrey Is this done?

**Comment by isleshocky77** [comment]
@lastzero @graciousgrey Not sure how I missed the original notifications on this getting worked on - but awesome and thanks for the super quick turn-around. Contrast is definitely more noticeable now.
