### ISSUE TITLE
Thumbnail of empty album does not disappear

### ISSUE THREAD

**Issue by n1try** [photoprism/photoprism#183]
**How to reproduce:**
1. Create new album
2. Add a single photo
3. Remove it again

**Expected:** Album has default, empty thumbnail

**Actual:** Album has deleted picture as thumbnail

**Comment by lastzero** [comment]
Does a hard reload help? 

We can not turn client-side caching off completely because of performance reasons.

Thumbs for labels are also cached in memory because our queries are pretty expensive, we try to find the best thumb for each label.

**Comment by n1try** [comment]
Hard refresh helps :+1:
I was concerned that other users might potentially see a photo that you already deleted. But if client-side caching is the issue here this is not a problem anyway.
