### ISSUE TITLE
Albums: Exclude private pictures from download as zip

### ISSUE THREAD

**Issue by Christian-Martensson** [photoprism/photoprism#1836]
**What does not work as expected?**

Pictures marked as private that are included in an album can be accessed by anyone if the album is shared. The picture won't show up in the web UI, but it will be included when selecting "download all pictures" (as a zip file).

**How can we reproduce it?**

1. Create an album and add a few pictures
2. Mark one picture as private
3. Share the album
4. Open the album in a private browser window
5. Verify that the private picture is not visible in the web UI
6. Download all pictures
7. Verify that the private picture was included

**What behavior do you expect?**

Private pictures should in no way be accessible when not logged in. 

**Can you provide us with example files for testing or screenshots?**

**What version you are using?**

211215-93b26f19-Linux-x86_64

**Any other helpful information?**

**Comment by lastzero** [comment]
Private pictures are now always excluded from downloads, as the primary use for downloads is to share them either directly or indirectly. We may introduce a more fine-grained control with multi-user support. 

If I remember correctly, the album download button was added as a "quick improvement" to do someone a favor - we should have rejected it or taken more time to think it through.

**Comment by lastzero** [comment]
We'll build a Development Preview for testing later today.
