### ISSUE TITLE
Search: Keywords filter should not exclude stopwords

### ISSUE THREAD

**Issue by joachimtingvold** [photoprism/photoprism#1859]
**What does not work as expected?**

Adding `meme` or `memes` as description and keyword for a picture. Trying to search with `meme` or `memes` as query string has zero results. Trying to search with `keywords:meme` or `keywords:memes` returns a whole lot of images (it seems to be all images, but have not verified). Re-index has no effect.

**How can we reproduce it?**

1. Add "meme" and/or "memes" as description and keyword(s).
2. Click on "Search"
3. Search for `meme` or `memes`, and it shows zero results
4. Search for `keywords:meme` or `keywords:memes`, and it shows many results

**What behavior do you expect?**

It should show images having `meme` or `memes` as description and/or keyword when searching for `meme` or `memes` (and not zero, as it does now).

It should show *only* images having `meme` or `memes` as keyword when searching for `keywords:meme` or `keywords:memes` (and not "all" as it does now).

**More observations**

Trying to use `kkthxbye` as the description and keyword, it seems to work as expected when searching for `kkthxbye` or `keywords:kkthxbye` (i.e. only the one image shows up in both searches).

It also shows results for a substring-search, down to 4 characters. If you try to use `kkt`, it shows no images, and if you try to use `keywords:kkt`, it shows "all" images again.

There seems to be an exception to the "shorter than 4 characters" in a search, and that is if it has a label with fewer characters (for example "cat"), which then also is added as a keyword. Search for `cat` and `keywords:cat` both return only the actual pictures with those labels/keywords. Trying `kkk` as a manual keyword did not work, but `fun` works.

**Software**

Photoprism 211215-93b26f19-Linux-x86_64
Chrome version 96.0.4664.110 (Official Build) (x86_64)
MacOS 11.6.2

**Comment by joachimtingvold** [comment]
![image](https://user-images.githubusercontent.com/359918/147836828-8f453dfe-843c-472c-b565-85ecd43cc830.png)
![image](https://user-images.githubusercontent.com/359918/147836840-85c0b686-98a5-4859-82ed-472f44d0b568.png)
![image](https://user-images.githubusercontent.com/359918/147836853-b29d8bea-aa3b-486c-b26f-263c109c84e5.png)

**Comment by lastzero** [comment]
Might be on the full text stoplist in the txt package. Not sure why the word has been added, we didn't create the lists on our own. In that case, the code works as expected and you just need to remove these.

**Comment by joachimtingvold** [comment]
You seem to be correct. Both `meme` and `memes` are present in `pkg/txt/stopwords.go`.

However, that also seems to be directly related to why `keywords:<string>`-searches yields "all" images as result (if `<string>` is a word from the stoplist), even though none of the images matches that search. Is that also expected behaviour?

**Comment by lastzero** [comment]
We could add code that returns an empty result if all words are stopwords. When there are other filters, they must be ignored.

**Comment by joachimtingvold** [comment]
Yeah, that would make more sense. If you have large amounts of photos, it's hard to differentiate between "many photos that actually matches the search query" and "all images returned by default due to random stopwords".

**Comment by lastzero** [comment]
Meme and memes have been removed from the stopwords list. When keywords contain stopwords only, an empty result is returned with an error ("invalid request"). We can add a more helpful message later if needed (needs translation). 

A new Development Preview is available for testing soon.

**Comment by joachimtingvold** [comment]
Thanks. I kinda worked around it by using a different keyword.

Is there a reason why stopwords are used for specific `keywords:` searches, btw? That seems somewhat counter intuitive? I can understand stopwords for freetext-search, and maybe for specific filters, but not keywords?

**Comment by lastzero** [comment]
Correct, it seems to be possible to search for all strings when using the `keywords:` filter and not the full text search (which also indexes keywords). This would require using a different query builder, as the current one filters out stopwords. 

The `keywords:` filter might have been added more recently. Since we were mainly working on other issues, keywords field and search were changed a few times to do people a "quick" favor without having time to rethink and rework the whole implementation.

**Comment by joachimtingvold** [comment]
I see. No worries. It's just a minor "inconvenience", just have to check the stopword-list before I assign any keywords from now on (=

**Comment by lastzero** [comment]
Should be fixed with this :wink:

New Development Preview build available for testing soon.
