### ISSUE TITLE
[CLI]: Provide the option to skip unchanged files

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#187]
As shown below in the API's `StartIndex` route, an option can be passed to skip indexing photos that haven't changed and thus reduce indexing time. 
https://github.com/photoprism/photoprism/blob/ba9b3cad72e402f51ee88e77b3c8a5705e117b75/internal/api/index.go#L89-L93

In the CLI's `index` command there seems to be no such option:
https://github.com/photoprism/photoprism/blob/ba9b3cad72e402f51ee88e77b3c8a5705e117b75/internal/commands/index.go#L48-L49 

I am syncing photos from multiple devices to a single directory, so I'd like to be able to create a cronjob to periodically index photos, but currently it takes too many resources to do it hourly. If I was able to skip unchanged files, it should be feasible.

**Comment by lastzero** [comment]
You are absolutely right... should be done.

**Comment by marcoamorales** [comment]
I'd like to help with this.. fairly new to the project though @lastzero if you could provide any pointers to find which files have been indexed already, I would really appreciate that :)

**Comment by lastzero** [comment]
@marcoamorales You have to add command flags to https://github.com/photoprism/photoprism/blob/develop/internal/commands/index.go

See https://github.com/photoprism/photoprism/blob/develop/internal/commands/thumbnails.go for how to do that ("force" flag).

Main task is to think about what flags to add and how to name them. Probably "all" (short "a") makes sense. Code would look like:

```
	Flags: []cli.Flag{
		cli.BoolFlag{
			Name:  "all, a",
			Usage: "Re-index existing files",
		},
	},
```

**Comment by lastzero** [comment]
Make sure to run tests before pushing / committing code: `make test-go`

Should be described in our Developer Guide (see Wiki). If anything is unclear, let us know!

**Comment by lastzero** [comment]
Used the opportunity to improve our command help... will merge to master now.

If this solves your issue, you can close the ticket :)

**Comment by lastzero** [comment]
Build is running: https://travis-ci.org/photoprism/photoprism/builds/640370213

I'll also start a build for arm64 (using our own hardware)

**Comment by linosgian** [comment]
I've tested this one, it works perfectly! :)
