### ISSUE TITLE
Question: GPS location warning if Exif data is not standard compliant

### ISSUE THREAD

**Issue by Oni** [photoprism/photoprism#1879]
**What does not work as expected?**

When I scan the photo folders, I get a lot of "2022-01-03 19:33:42 INFO metadata: failed parsing GPS coordinates in \<filename\>.jpg (exif)" errors.

**How can we reproduce it?**

Try to scan this image:
![IMG_20200423_151334](https://user-images.githubusercontent.com/38935/147967641-e63dcc30-8a57-4a68-a042-916a11e03ad4.jpg)

**What behavior do you expect?**

On Windows 10, if I right click the image I can see the GPS coordinates just fine. So I expect PP to parse those coordinates as well.

**Can you provide us with example files for testing or screenshots?**

See above.

**What version you are using?**

Version 211215-93b26f19-Linux-x86_64 (docker image).

**Any other helpful information?**

None.

**Comment by graciousgrey** [comment]
I can confirm I get similar debug messages when indexing this file:

`2022-01-04 09:41:48 INFO metadata: failed parsing GPS coordinates in plantsgps.jpg (exif)`
`2022-01-04 09:41:48 DEBU exif: no gps tags in plantsgps.jpg (gps info)`

For me the GPS information is extracted. I see the coordinates and location information on the files edit dialog in PhotoPrism as expected.

**Comment by Oni** [comment]
Follow up.

The GPS information is, in fact, correctly displayed in PhotoPrism in the 'edit view' and the image is correctly placed on the map.

Apparently only the log is 'wrong' here.

**Comment by lastzero** [comment]
The EXIF GPS metadata in the sample image you provided is not strictly standards-compliant. It is representing the GPSLatitude and GPSLongitude fields with values of type SRATIONAL (signed rational values, type = 10) and not with values of type RATIONAL (unsigned rational values, type = 5) as specified in the Exif 2.3 specification (pages 69-70).

**Comment by lastzero** [comment]
```
IFD-PATH=[IFD/GPSInfo] ID=(0x0001) NAME=[GPSLatitudeRef] COUNT=(2) TYPE=[ASCII] VALUE=[N]
IFD-PATH=[IFD/GPSInfo] ID=(0x0002) NAME=[GPSLatitude] COUNT=(3) TYPE=[SRATIONAL] VALUE=[[43/1 31/1 2496/100]]
IFD-PATH=[IFD/GPSInfo] ID=(0x0003) NAME=[GPSLongitudeRef] COUNT=(2) TYPE=[ASCII] VALUE=[E]
IFD-PATH=[IFD/GPSInfo] ID=(0x0004) NAME=[GPSLongitude] COUNT=(3) TYPE=[SRATIONAL] VALUE=[[13/1 37/1 16/100]]
IFD-PATH=[IFD/GPSInfo] ID=(0x0006) NAME=[GPSAltitude] COUNT=(1) TYPE=[RATIONAL] VALUE=[[134/1]]
IFD-PATH=[IFD/GPSInfo] ID=(0x0007) NAME=[GPSTimeStamp] COUNT=(3) TYPE=[RATIONAL] VALUE=[[13/1 13/1 36/1]]
IFD-PATH=[IFD/GPSInfo] ID=(0x001d) NAME=[GPSDateStamp] COUNT=(11) TYPE=[ASCII] VALUE=[2020:04:23]
```
