### ISSUE TITLE
Some Folders show thumbnail but no contents

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#1888]
**What does not work as expected?**

Some but not all Folders appear empty after a complete re-scan.  
The photos from these Folders can be seen in Search or Calendar views.

**How can we reproduce it?**

Rebuild library.

**What behavior do you expect?**

The Project folder should be populated with images.

**Can you provide us with example files for testing or screenshots?**

A sample JPG file has been included.  They were all previously successfully viewable in an earlier version of Photoprism.

**What version you are using?**

I upgraded to 211215 and manually removed all the JSON files in the originals sub folders as these were turning up with "JSON" icons.

**Any other helpful information?**

I happened to discover this when I was converting some Folders into Albums.  I noticed 15/16 were populated, then this "Dining Table Restoration" Folder had no images in it.  All other Folders (so far) have images and successfully generate Albums from them.

"Project - Dining Table Restoration" is found and present in Folder view...
![screenshot977](https://user-images.githubusercontent.com/5325698/148257161-956f860d-9776-47c6-b5ed-9351b1d0bc67.png)

Entering that folder...
![screenshot978](https://user-images.githubusercontent.com/5325698/148256518-ae797e05-45b7-4d9a-a607-bdba5b4e71e5.png)

But you can find the photos from this folder via Search or Calendar...
![screenshot976](https://user-images.githubusercontent.com/5325698/148256564-3b1f333b-a8e3-4c2f-a7d1-47ad067b0a69.png)

I see no errors in the logs during a complete re-scan.  

Sample image file in the "Project - Dining Table Restoration" folder...
![IMG_9090](https://user-images.githubusercontent.com/5325698/148256775-913ca67c-e866-4549-a201-a3263559fb81.jpg)

**Comment by lastzero** [comment]
Are these stacks scattered across different folders? There's only one main folder possible, so files will be displayed there.

**Comment by elapse2039** [comment]
There is one folder which contains the original photos and I can see these files via SFTP/local command line.  
It is empty when I view it via Folders/.   (Not sure what a stack is?)

The Folder and the resulting Album I create both have nothing in them when viewed via PhotoPrism UX.  
When I do the same exact steps with other folders I can successfully create Albums and they are not empty.

**Comment by graciousgrey** [comment]
PhotoPrism stacks related files (see https://docs.photoprism.app/user-guide/organize/stacks/). But at least for the image with the white table that's not the case as I see on the screenshot that it consists of onlye one file.

Is it possible that you have duplicates of those images in another folder?

Could you check the name that is shown on the files tab (https://docs.photoprism.app/user-guide/organize/edit/#edit-files) for the images that should be in the empty folder?

**Comment by elapse2039** [comment]
If I search for one of the dining table photos, I can then look at the FILES tab and see...

![screenshot980](https://user-images.githubusercontent.com/5325698/148396199-8a02efd4-5432-48e7-ac5b-09acf1bf344a.png)

When you say duplicates, you mean filename duplicate?

I see there are two files with the same name... is this a problem?  Or is uniqueness defined by path and file name?

/mnt/PHOTOPRISM/photoprism/originals$ find . -name "IMG_9190.jpg"
./gphotos/2018/20180401/IMG_9190.jpg
./gphotos/projects/Project - Dining Table restoration /IMG_9190.jpg

**Comment by lastzero** [comment]
No, SHA-1 duplicates (same content with extremely high probability):

https://en.wikipedia.org/wiki/SHA-1

**Comment by lastzero** [comment]
I'll move this to discussions to determine the cause - like duplicates that get ignored - before we add it to our issue tracker as a confirmed bug :)
