### ISSUE TITLE
HEIC images are not imported

### ISSUE THREAD

**Issue by lzap** [photoprism/photoprism#189]
Hello,

it looks like HEIC photos captured by my iPhone 11 do not appear in my library. Are these supposed to work? Anything I can check? Thanks.

**Comment by lastzero** [comment]
Are you using our docker image? You need an external binary for this... forgot the name, you'll find in the source or when you run `photoprism help`

**Comment by lzap** [comment]
Running a docker image. One more thing I realized - my Originals folder is mounted RO, I do not want any application to change my originals.

Haven't the container image all binaries available? I do see it:

```
# docker exec -ti photoprism /usr/bin/heif-convert
USAGE: /usr/bin/heif-convert [-q quality] <filename> <output>
exit status 1
```

**Comment by lzap** [comment]
I guess that is the issue, it does store it in the originals folder :-(

https://github.com/photoprism/photoprism/blob/182b169ac00eb30541e56b9dfddfeb9ec7e16b4e/internal/photoprism/convert.go#L70-L90

**Comment by lzap** [comment]
I keep my photos from cameras in RAW and from iPhones in HEIC. I was hoping that PhotoPrism would be a good browser for my archive, however it looks like it can't do it without modifying the source folder. I guess I could do an overlay-fs as a workaround. Let's see.

**Comment by lastzero** [comment]
So where would you store JPEGs for your RAWs? In the thumbnails folder? If you do a backup, all JPEGs would be gone and some users create JPEGs manually using Photoshop, so we would have to search in different locations... your originals will never be modified.

**Comment by lastzero** [comment]
Note that creating a JPEG from a RAW file is a really expensive operating, you don't want to repeat that step and it's also difficult to match both files (know they are the same image) if they are not in the same folder with the same file name (except extension). If we can come up with a good solution, we'll do it.

**Comment by lastzero** [comment]
@lzap Updated our docs with a detailed discussion of your issue: https://github.com/photoprism/photoprism/wiki/Converting-RAW-to-JPEG#read-only-mode

**Comment by Sithuk** [comment]
I read that JPEG created from RAW is not stored in the original source folder. Is this the case now for JPEG created from HEIC? I've indexed my source folder with read only option and the HEIC photos appear to be missing. So I assume the JPEG conversion hasn't happened?

**Comment by lastzero** [comment]
Depends on your config. By default, they are stored in the sidecar folder. You may set the sidecar folder to `.` or `.photoprism` which will store them next to your originals in the very same folder.

**Comment by lastzero** [comment]
If you've enabled read only mode, setting the sidecar folder to be within the originals folder will result in an error. Check the files tab of the photo edit dialog to see the storage location and/or run photoprism config in a terminal as shown in our example docker-compose.yml files at the top.

**Comment by Sithuk** [comment]
The HEIC files are now being converted to JPEG. The conversion renames them from image123.heic to image123.HEIC.jpg. The converted files are saved in the sidecar folder. The originals folder doesn't appear to be written to during the conversion.

I've left the sidecar location as the default (- "./storage:/photoprism/storage" in the docker-compose.yml). I never changed it. My originals folder location is in the /mnt/ folder. So there is no conflict between the two.

Why does the conversion not work with the originals folder read only option enabled when I have the sidecar folder at a diferent location? If the sidecar folder location doesn't conflict with the originals folder then shouldn't the conversion work?

**Comment by lastzero** [comment]
As you've noticed, the conversion works. So there is no issue. If you configure the sidecar folder to be within the originals folder and you have read only mode enabled, conversion must not work as it would have to create the new JPEG in your write protected originals folder. Read only mode means you don't want to write there.

**Comment by Sithuk** [comment]
Yes, it's good news that the automatic heic conversion works. Photoprism is looking to be a good solution for iphone users despite no native heic read support.

There will be users like me who want to be confident that their source folders will not be modified. We will ensure our sidecar and originals folder are at separate locations. We will select the Read-Only mode. The issue is that Photoprism will not work with heic files in this configuration because the conversion will not work even though the sidecar and originals folders are in separate locations.

A solution could be to put a check for where the sidecar and originals folder conflict when the Read Only mode is selected. Then error out if the originals folder is at risk of being written to. That way users can use the Read Only mode and still have heic compatibility using the in-built conversion.

**Comment by lastzero** [comment]
> Yes, it's good news that the automatic heic conversion works. Photoprism is looking to be a good solution for iphone users despite no native heic read support.

Web browsers also have no native support, so they need to be converted anyway at some point if you want to view them in a browser. 

> The issue is that Photoprism will not work with heic files in this configuration because the conversion will not work even though the sidecar and originals folders are in separate locations.

What configuration does not work? The reason we've implemented a separate sidecar folder is that this works with mounting the originals folder in read only mode.

> A solution could be to put a check for where the sidecar and originals folder conflict when the Read Only mode is selected. 

That's what we did.

**Comment by Sithuk** [comment]
> The reason we've implemented a separate sidecar folder is that this works with mounting the originals folder in read only mode.

When I indexed my originals folder with the Read Only mode option selected my heic files were not converted. I de-selected the Read Only mode and now my heic files are being converted. I have maybe misunderstood something or did something wrong. I will try and test again and report back.

**Comment by lastzero** [comment]
It's possible it didn't work if the sidecar folder wasn't writable either and/or conversion to JPEG was disabled. Also users reported issues with old Docker versions on Unraid.

**Comment by Sithuk** [comment]
I've re-enabled the Read Only mode and everything looks to be working (heic are converted to the sidecar folder). I have always had the Conversion to JPEG enabled. It must have been something I did wrong. Everything appears to be working as it should. Thank you for your responses.
Hopefully our posts here will help iphone users to understand how photoprism handles heic files, including that the source photo folder can be left unmodified during the conversion process. Photoprism looks to work well with iphone's heic files.
