### ISSUE TITLE
Warm-up command for thumbs to improve performance?

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#19]
Not sure if thumbnails should be pre-rendered or rendered on demand. Depends on the final performance. Need to see how the user experience is.

**Comment by devzsolt** [comment]
My opinion is that it should be the responsibility of a background process. I can't imagine a situation where a subset of the thumbnails are unnecessary however it improves the performance a lot if it's pre-rendered.

**Comment by lastzero** [comment]
Already implemented: `photoprism thumbnails`
