### ISSUE TITLE
panic: html/template: pattern matches no files: `/root/.local/share/photoprism/resources/templates/*`

### ISSUE THREAD

**Issue by casidiablo** [photoprism/photoprism#190]
I'm trying to run photoprism using the docker image (right now using the `photoprism/photoprism:20191231`) and it crashes with this:

```
time="2020-01-13T04:56:28Z" level=info msg="starting web server at 0.0.0.0:2342"
panic: html/template: pattern matches no files: `/root/.local/share/photoprism/resources/templates/*`

goroutine 50 [running]:
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:372
github.com/gin-gonic/gin.(*Engine).LoadHTMLGlob(0xc000142280, 0xc000043640, 0x33)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.3.0/gin.go:174 +0x35c
github.com/photoprism/photoprism/internal/server.Start(0x25c7ee0, 0xc0005229c0, 0xc0058bf740)
	/go/src/github.com/photoprism/photoprism/internal/server/server.go:27 +0x24e
created by github.com/photoprism/photoprism/internal/commands.startAction
	/go/src/github.com/photoprism/photoprism/internal/commands/start.go:114 +0xb21
```

It fails both when running using `docker-compose` as well as when ran in my Kubernetes cluster.

Tried a couple of older images and it fails too. Any idea of how to get pass this?

**Comment by casidiablo** [comment]
Nevermind, I was running my containers as root instead of letting it run as `photoprism`, which was a bad idea anyways

**Comment by lastzero** [comment]
We could still show more helpful messages...

**Comment by casidiablo** [comment]
Yeah, in general, this and stuff that access the /assets folders have really bad error messages. e.g. I was trying to make the originals folder point to an s3 bucket that I mounted using fuse, but the mount was done in such a way that it prevented non-root users (i.e. the `photoprism` user) to access the directory.

In that case, photoprism crashes with "mkdir fail blabla: file exists", which should be more like: `Error accessing the /assets/photos/original folder: permission denied`

**Comment by lastzero** [comment]
Agree, also S3 support should be implemented natively.
