### ISSUE TITLE
Logout: Redirect to base URI instead of "/"

### ISSUE THREAD

**Issue by tpneill** [photoprism/photoprism#1901]
**What does not work as expected?**

When logging out of Photoprism both explicitly and due to session expiry I am redirected to the site root URL even when I have a non-root site URL defined.

**How can we reproduce it?**

1. Configure Photoprism to run from a non-root site URL by using `PHOTOPRISM_SITE_URL`, e.g. `PHOTOPRISM_SITE_URL=https://example.com/photoprism/`
2. Login as normal
3. Click the logout button
4. You will be redirected to the root site URL e.g. `https://example.com/`

**What behavior do you expect?**

Logout button should take you to the configured non-root site URL e.g. `https://example.com/photoprism/`

**What version you are using?**

211215

**Any other helpful information?**

This appears to be coming from a `onLogout` inside `frontend/src/common/session.js`:

```
  onLogout(noRedirect) {
    this.deleteId();
    if (noRedirect !== true) {
      window.location = "/";
    }
    return Promise.resolve();
  }
```

`window.location` should be set to the same value configured in `PHOTOPRISM_SITE_URL`

**Comment by lastzero** [comment]
Wish we had never added this feature! 😂

**Comment by lastzero** [comment]
Is it working for you now with our [Development Preview](https://docs.photoprism.app/release-notes/)?

**Comment by budokaiman** [comment]
> Wish we had never added this feature!

I, on the other hand, greatly appreciate that it exists.


> Is it working for you now with our Development Preview?

It is working for me on dev preview `220118-76c94a1f`

**Comment by graciousgrey** [comment]
Thanks for testing :)
