### ISSUE TITLE
Clicking on another section before first loads results in first being displayed

### ISSUE THREAD

**Issue by jtagcat** [photoprism/photoprism#1909]
**How can we reproduce it?**
1. Click on search (140k photos), nothing loads yet (~~server load / disk latency /~~ network)
2. Click on favourites (1 photo)
3. On load complete, 50 first photos from search are displayed

**What behavior do you expect?**
3. Favourites are displayed, or at least search is displayed, and soon after favourites replace the view.

**What version you are using?**
Make the god damn version copyable, opens about page; can't drag-select from side either. Inspecto elemento!

220107-f5b7ef83-Linux-x86_64

**Any other helpful information?**
- FF Nightly
- (both LAN and WAN pipes are bogged down by other activity)

**Comment by lastzero** [comment]
1. When you switch between Search and Favorites, the component is reused for performance reasons. So it seems possible. I've never experienced this or heard about it, could be hard to reproduce? Once we have a new full screen viewer, search requests will be reworked anyway.
2. If I hadn't spent my free weekend writing documentation, I could have changed the damn CSS for the version string. Why don't you do a quick PR while I enjoy a glass of wine? Cheers! 🍷

**Comment by lastzero** [comment]
Plonk.

**Comment by jtagcat** [comment]
Did you version the CSS?
