### ISSUE TITLE
EXIF Wiki Updates/Discussion

### ISSUE THREAD

**Issue by dsoprea** [photoprism/photoprism#193]
@lastzero 

1. Can we remove the table of all possible EXIF tags? If someone needs these, they can refer to the official link.
2. The EXIF link is a pointer to a non-authoritative library. We should update it to point to http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf (2.3). It's the same PDF as the one in go-exif (https://github.com/dsoprea/go-exif/blob/master/assets/DC-008-2012_E.pdf).
3. It might be more succinct and maintainable to point to exif.go as the source-of-truth for what tags PhotoPrism uses rather than having them in the other table, here.

Regarding the tags that the library (er, _goexif_, the previous integration) reportedly supports but PhotoPrism does not ("ExifIFDPointer", "GPSSatelites", "InteroperabilityIFDPointer"):
- "ExifIFDPointer": I'm guessing that this refers to the tag that points to child IFDs, which is a concept internal to the EXIF library and shouldn't be a concern of the integration. 
- "GPSSatelites" (a misspelling of "GPSSatellites", the official name) is supported by go-exif (as are any other standard tags); does this imply that we want it in PhotoPrism?
- "InteroperabilityIFDPointer": This refers to the collection of tags found in the Interoperability IFD. This should be already be supported as well. An example where they end-up in a JSON dump of tags during the uni-tests (the file we validate against): https://github.com/dsoprea/go-exif/blob/25524615d1246315ee12f8948d1b72acc80b00b9/assets/exif_read.json#L455 . The source-of-truth for the Interoperability tags that go-exif supports are here: https://github.com/dsoprea/go-exif/blob/9068786204c5fcf90bc65a93228da05915f7bb54/tags_data.go#L934 . Are you wanting to bring some of these tags into PP?

I also noticed that there are screenshots of people being able to see metadata, which includes the original filename. As this is not currently supported, should I assume that these screenshots are sufficiently inaccurate that they should be removed?

**Comment by lastzero** [comment]
Sure, remove it... think we don't need it anymore. Link would be good/enough. Feel free to fix other links as well.

**Comment by lastzero** [comment]
Those screenshot are of other apps and serve as inspiration, please don't remove them (until we find another place).

**Comment by dsoprea** [comment]
@lastzero Ack.

**Comment by dsoprea** [comment]
@lastzero Comments on how/whether the tags mentioned should be brought into PP?

**Comment by lastzero** [comment]
Regarding support for more fields, I think we might have to restructure our db... main table should only contain columns we actually need for our search so that it has a chance to fit in memory.

**Comment by lastzero** [comment]
Can have a look at this, but should do the Places UI first... need to replace OSM.

**Comment by dsoprea** [comment]
Makes sense to me. There are a lot of tags, but most of them are mundane. I'll assume that we already have the necessary minimum. The Iop IFD always just seemed like technical minutia to me.

We can revisit any new tags that we might want at some more prudent point in the future when the need is there. Do you just want to close this?

**Comment by lastzero** [comment]
If that's all and the documentation is updated, we can surely close this :)

**Comment by dsoprea** [comment]
+1
