### ISSUE TITLE
Settings: Add setting to change download behavior of stacks

### ISSUE THREAD

**Issue by tylerpieper** [photoprism/photoprism#1933]
Currently, when downloading a single item, it will download any items stacked (like raw files). I suggest adding a way to download just the primary file in a few different ways (whatever makes the most sense for all users)

1. Add a setting called something like "download only primary files in a stack". When enabled, clicking download while viewing a single photo will just download the primary jpg. Stacked files can still be downloaded by going into the details for a file. I would assume this would affect downloads via anonymous users via an album share link.
2. Another option would to be to prompt on each download (I don't like this idea but it is an option)
3. A more complicated option would be to add an option on a per-album basis to do the same. Something like a dropdown or checkbox to configure whether downloads include all items in stacks, only the primary, or disable downloads entirely. 

Option 1 would meet my needs, but I would love if other users replied with their needs etc.

**Comment by graciousgrey** [comment]
We know there is room for improvement when it comes to download features:  see https://github.com/photoprism/photoprism/issues?q=is%3Aissue+is%3Aopen+download+in%3Atitle

1. and 2. will be part of this  https://github.com/photoprism/photoprism/issues/449 :)
