### ISSUE TITLE
Pictures stuck in "Hidden" section of library after storage volume runs out of space

### ISSUE THREAD

**Issue by starcraft66** [photoprism/photoprism#1939]
**What does not work as expected?**

I am running Photoprism on kubernetes and underestimated the amount of space I would have to give the `/photoprism/storage` volume so that volume ran out of space during the initial import of my originals so a lot of pictures ended up in the "Hidden" folder with broken thumbnails. Following this situation, I expanded the storage volume and attempted to re-import from my originals folder but it seemed to just skip over everything and complete the import without changes. I tried to get some help in the matrix room and someone suggested I run the `thubs` command from the command-line. I did so and while that did fix the previews (I have thumbnails for all of the photos stuck in the "Hidden" section of my library), the photos were still stuck in "Hidden" and pressing on the picture, going to its details and selecting files shows an error message like `open /photoprism/storage/cache/thumbnails/6/5/d/65d52ae874b07065672eba1f6730950623a38da3_2048x2048_fit.jpg: disk quota exceeded` for every single picture.

**How can we reproduce it?**

1. Start a fresh library with a small storage volume
2. Import a ton of originals
3. Wait for the storage volume to fill up with thumbnails and run out of space
4. Expand the storage volume

I haven't changed any thumbnail settings, I currently have 170k originals in my library and 37k are stuck in "Hidden" if that matters

**What behavior do you expect?**

I expect an import to clear the error message these photos are throwing because there is now enough space to generate the thumbnail for them and import them into the library

**Can you provide us with example files for testing, error logs, or screenshots?**

I'm available to chat here or in the matrix room, my username is `@tristan:nerdsin.space`

**Which software versions do you use?**

- PhotoPrism Architecture & Build Number (AMD64, ARM64, ARMv7,...) : PhotoPrism® 220107-f5b7ef83-Linux-x86_64
- Database Type & Version (MariaDB, MySQL, SQLite,...) MySQL 8

**On what kind of device is PhotoPrism installed?**

This is especially important if you are reporting a Performance, Import, or Indexing problem. You can skip this if you are reporting a problem found on our public demo, or if it is a completely unrelated issue, such as a broken page layout.

- Device / Processor Type: Intel Xeon E5-2680
- Physical Memory & Swap Space: 32 GB ram, No swap
- Storage Type: NFS, ZFS raidz1

**Comment by lastzero** [comment]
https://letmegooglethat.com/?q=disk+quota+exceeded+kubernetes

**Comment by lastzero** [comment]
- A disk quota is a limit set by an administrator to restrict the use of the file system.
- Kubernetes does indeed have settings to limit the memory and disk usage of services, so you should check this first.
- Since PhotoPrism does not have a quota mechanism, this error does not indicate a bug in our software or a problem with your physical storage space.

Hope this helps! Feel free to reach out via email otherwise, as GitHub Issues is only for clearly identified bugs in PhotoPrism :)

**Comment by starcraft66** [comment]
I do think that this is a bug in photoprism. I clearly stated that after exceeding the quota of my storage volume, I expanded it. I currently have about 100 gigs free and photoprism refuses to import the images that failed to import when the volume used to be full when there is now clearly disk space available.

**Comment by lastzero** [comment]
So the disk quota exceeded message does NOT show up anymore? Does any other warning or message show up? Do you have logs for us to debug?

**Comment by lastzero** [comment]
Also it's not clear if you index originals or import files to originals. That's a huge difference. In the second case it would make sense no files are copied if they already exist in originals. This would be expected and not be a bug.

**Comment by starcraft66** [comment]
> Also it's not clear if you index originals or import files to originals.

I'm only indexing originals from a folder that contains all of them, I'm not uploading anything through Photoprism.

If I go to Library -> Errors, there are a few warnings but nothing that seems to have to do with this issue.

If I click just on Library and then start indexing, it just takes a couple minutes to traverse my originals folder and then finishes importing after doing nothing.

If I go to Library -> Hidden, there are 37k images from my originals folder that failed to import the very first time because the storage volume ran out of space. If I click on any of those images, press edit in the top right, then press "Files" in the top right, I get a red flash banner that says something along the lines of `open /photoprism/storage/cache/thumbnails/4/4/2/442f51a6bbabb445ca22712b09dc1758a3616ee0_2048x2048_fit.jpg: disk quota exceeded`.

**Comment by lastzero** [comment]
If they were copied but originals are in hidden because you were running out of disk space, please do a full rescan.

**Comment by starcraft66** [comment]
Okay, I was hoping to resolve this without a complete rescan because at the speed it takes to scan my originals it will probably take over a week, but I can take the hit and watch my disk space to make sure this never happens again.

**Comment by lastzero** [comment]
You can test / accelerate it by limiting the rescan to subfolders using the directory selector.

**Comment by lastzero** [comment]
If files are broken or there are other problems, it does generally not make sense to try again and again when indexing (without the full rescan option).

**Comment by lastzero** [comment]
If this doesn't work and it becomes clear there is another problem, we are happy to open a bug ticket and provide a fix. Requiring a rescan after the index operation was failing due to an external quota limit is not a bug. Also note sponsors can contact us anytime via email for technical support in cases like this.
