### ISSUE TITLE
Upgrade TiDB to v3.0

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#195]
**As a developer, I want to use the latest stable version of TiDB so that my users get the best performance and there are no security issues.**

Sadly, `go get -u -t ./...` doesn't do the trick: 

> go get: upgrading github.com/pingcap/tidb@v2.1.11+incompatible: github.com/pingcap/tidb@v2.1.11+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

Not sure what the issue is here. They have a lot of dependencies and it never was easy to figure out, which versions work together although that might have improved recently.

Once dependencies are upgraded, we might have to change some things in our bootstrap code:

https://github.com/photoprism/photoprism/tree/develop/internal/tidb

Acceptance Criteria:
- [ ] TiDB is upgraded to v3.0.x (latest stable)
- [ ] Everything works like before

**Comment by poerhiza** [comment]
Peeking at the issue - it looks like x-server went away: https://github.com/pingcap/tidb/pull/9038 - fun fun...

**Comment by cuongcb** [comment]
Is there anybody in charge of this issue? I'm new to photoprism and I got this problem too. I wanna give it a try.

**Comment by lastzero** [comment]
@cuongcb You're most welcome to help with this! We're currently working on the Web UI, so merge conflicts are unlikely :)

**Comment by skyeskie** [comment]
The specific error with `go get` is due to https://github.com/pingcap/tidb/issues/16381

**Comment by cuongcb** [comment]
> The specific error with `go get` is due to [pingcap/tidb#16381](https://github.com/pingcap/tidb/issues/16381)

Thank @skyeskie for a detailed reply.
Additionally, we can get the latest version of TiDB by issuing `go get github.com/pingcap/tidb@master` and a random-generated version number will be assigned in our `go.mod`. But as @poerhiza pointed out above, TiDB removed the `x-server` from their source. So now we have to deal with the replacement of `x-server`.

**Comment by cuongcb** [comment]
For anyone that has the same issue:
```go get: upgrading github.com/pingcap/tidb@v2.1.11+incompatible: github.com/pingcap/tidb@v2.1.11+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required```
and still want to keep the `photoprism` working with the old version of `tidb` (v2.1.11), please follow these steps:
* Remove all pingcap-related packages from `go.mod`
* Remove `client_golang` package from `go.mod`
* `go get -u -t github.com/pingcap/tidb@5ea2830cd7793b166d811d0a65a9c618296cd963`
Start~

**Comment by lastzero** [comment]
FYI: When upgrading github.com/golang/protobuf from v1.3.5 to 1.4.0, TiDB experienced a fatal error. Had to downgrade again: https://github.com/photoprism/photoprism/commit/743b2dc34802d4b4441e6b945c06d6173d00029c
