### ISSUE TITLE
Faces: Optimize faces doesn't work

### ISSUE THREAD

**Issue by agramner** [photoprism/photoprism#1957]
I noticed that one part of the background job takes 50 minutes. Concluded that it is is the ResolveFaceCollisions loop that consumes 100% of one CPU core for 50 minutes on my raspberry pi 4. With the default 15 min background jobs interval, 100% of one core is almost constantly working. I have 2093 rows in the "faces" table. I've done a lot of manually tagging of not matched faces figured that it might improve the algorithm over time.

Tried to run the `faces optimize` command but no improvement.

Looked at the code and found that the faces optimize code doesn't seem to work due to a ":" at this line.
https://github.com/photoprism/photoprism/blob/a9a374616900dbf23f41f9ddc409fdc0623dad25/internal/photoprism/faces_optimize.go#L32

**Comment by lastzero** [comment]
Interesting, thanks for reporting this! Wondering why we didn't observe any issues when testing 🤨

**Comment by lastzero** [comment]
A new Development Preview image is available for testing. Does the "faces optimize" command work for you now?

**Comment by lastzero** [comment]
see https://docs.photoprism.app/release-notes/

**Comment by agramner** [comment]
Tested with preview and unfortunately it didn't work :(. And still have 3 subjects with over 100 faces each.

**Comment by lastzero** [comment]
Did you try the CLI command? Might have a force flag. AFK right now.

**Comment by agramner** [comment]
I ran the `photoprism faces optimize` command, it says:
```
DEBU[2022-01-20T14:45:12Z] config: successfully initialized [8.779395ms] 
DEBU[2022-01-20T14:45:15Z] migrate: found 4 previous migrations         
DEBU[2022-01-20T14:45:15Z] migrate: 20211121-094727 skipped             
DEBU[2022-01-20T14:45:15Z] migrate: 20211124-120008 skipped             
DEBU[2022-01-20T14:45:15Z] migrate: 20220103-115400 skipped             
DEBU[2022-01-20T14:45:15Z] migrate: 20220118-172400 skipped             
DEBU[2022-01-20T14:45:17Z] entity: successfully initialized [4.500317575s] 
INFO[2022-01-20T14:45:18Z] merged 0 face clusters in 5.972195357s       
INFO[2022-01-20T14:45:18Z] closed database connection  
```

I guess the embeddings doesn't `Match`?

**Comment by agramner** [comment]
Shouldn't the algorithm try to match all the faces for a subject against each other and merge the ones that match?

**Comment by lastzero** [comment]
If the embeddings are similar and belong to the same person, they should be merged.

**Comment by lastzero** [comment]
In case there are further problems, it is best to create a follow-up issue, as we are planning to release an update today and the original issue has been fixed.

**Comment by agramner** [comment]
I understand. Not sure why the optimize command doesn't reduce the number of faces in my case. To me it seems like the code doesn't compare all the faces of a subject against each other and therefore misses faces that could be merge-able.  But maybe I'm missing something? I don't have the whole picture.

**Comment by lastzero** [comment]
Can't tell you out of my brain. Celebrating my birthday now. If you say it's not working, we need to find time to look at it again in detail. Help welcome!

**Comment by agramner** [comment]
Sounds good 👍 . Enjoy your birthday! 🎉

**Comment by srett** [comment]
@agramner did you tag a lot of individual faces manually, that were not part of any automatically formed cluster? If yes, that sounds like the same performance issue as in #1872

Alas, the fix from this issue seemed to at least do something in my case, unless something else about the faces engine changed; upon starting the new version, I was greeted by "faces: merged 16 clusters" in the log. Still have 1500+ rows in faces though, but it's a start. ;-)

**Comment by agramner** [comment]
@srett Yes, I've done a lot of manual tagging and noticed the same thing mentioned in #1872. That's why I started looking at the "faces optimization" code.

Great, that the fix improved something for you at least! :)

**Comment by willhoh** [comment]
Hi, I also have to tag a lot manualy and I don't know go, but didn't find a good explanation for the if statement. In most examples they would write `else if n := len(faces) - 1; n < 1` , with a ` : `. 

Here I don't understand 2 things: 
<del>1. why `n < 1` when there should be at least 2? Shouldn't it rather be `n >= 1`?</del>
2. isn't the if initialization wrong and it should be `if faces, err := query.ManuallyAddedFaces(false); err != nil`?

**Comment by lastzero** [comment]
- `foo = 123` sets a new value for an *existing* variable
- `foo := 123` defines a new variable in the current scope, in this case the if block only

Instead of `foo := 123` , you could also write:

```go
var foo int
foo = 123
```

Edit: The initialization is correct, using `:=` would limit the scope to the if block and prevent the result from being visible/usable further down, same what happened with the `n` variable :heavy_check_mark:

**Comment by agramner** [comment]
Update: Bought more powerful hardware (6 core, 3.3 GHz, NVME SSD) and the ResolveFaceCollision code now takes around 13 min, 1/4 of the time compared to the raspberry pi 4
