### ISSUE TITLE
Album Sorting: Alphanumeric Filenames are Not Sorted Naturally

### ISSUE THREAD

**Issue by xCJPECKOVERx** [photoprism/photoprism#1960]
**What does not work as described in the documentation?**

When sorting album content by filename, filenames with numbers are not sorted according to the value of the number.
For example, the files [photo1, photo5, photo10, photo11, photo100, photo110, photo111] will be sorted as: [photo1, photo10, photo100, photo11, photo110, photo111, photo5].
I believe this only happens when the photos are originals, since imported files are renamed during import.

**How can we reproduce it?**

1. Create album with files containing numeric filenames (indexed originals, since importing will rename the files)
2. Sort album by filename

**What behavior do you expect?**

For files to be sorted according to the alpha-numeric value, ie [1, 5, 10, 11, 100, 110, 111] and NOT [1, 10, 100, 11, 110, 111, 5]

**Can you provide us with example files for testing, error logs, or screenshots?**
![image](https://user-images.githubusercontent.com/9089397/150427566-efd16b52-3aeb-4f45-afd0-2ae304985365.png)
![image](https://user-images.githubusercontent.com/9089397/150427632-ddfb3632-0190-4e8f-9e75-8d2ef1504e63.png)

**Which software versions do you use?**

- PhotoPrism Architecture & Build Number: 211130-13cfcf6d-Linux-x86_64
- Database Type & Version: Mariadb 10.5.13
- Operating System Types & Versions: Unraid - Docker
- Browser Types & Versions: Chrome (desktop & Android)

**On what kind of device is PhotoPrism installed?**

- Device / Processor Type: AMD Ryzen 7 2700X
- Physical Memory & Swap Space: 32GB RAM
- Storage Type: config on NVME SSD, data on 8TB HDD

**Comment by xCJPECKOVERx** [comment]
I've taken some to look at how the sorting is done (internal/search/photos.go I think?) and it appears to actually be a MYSQL limitation.

Would it be possible to add configuration which would prevent sorting by filename with MYSQL, and instead sort the PhotoResults set programmatically?

I think the bug label could be replaced by feature request. Sorry about that.

**Comment by lastzero** [comment]
No, not feasible. Anyhow, it would be a feature request. Not a bug. 😉
