### ISSUE TITLE
Tensorflow Dockerfile is broken

### ISSUE THREAD

**Issue by guysoft** [photoprism/photoprism#197]
Building it I get:

```
Step 17/23 : RUN mv bazel-0.24.1-linux-x86_64 /usr/local/bin/bazel && chmod 755 /usr/local/bin/bazel
 ---> Running in 3b297256f0ff
Removing intermediate container 3b297256f0ff
 ---> d7167bbc338b
Step 18/23 : WORKDIR "/home/tensorflow/tensorflow-1.14.0"
 ---> Running in 54586f1a4fa7
Removing intermediate container 54586f1a4fa7
 ---> fa0883db291f
Step 19/23 : COPY /docker/tensorflow/*.sh ./
COPY failed: no source files were specified
```

This is the ``x86_64`` build from develop branch.

Need it to work to build tensorflow for aarch64 in #109

**Comment by lastzero** [comment]
I'd never let a bug slip through ;)

You need the files in https://dl.photoprism.org/tensorflow/linux/config/

**Comment by lastzero** [comment]
You can add the files to the repo, don't remember why I stored them separately... should be better documented for sure.

**Comment by lastzero** [comment]
If I had to guess, it's because you can change the files to build for different targets:

https://dl.photoprism.org/tensorflow/nvidia-jetson/config/

**Comment by lastzero** [comment]
Probably changed the files a lot and didn't want to spam our commit history with that. Could actually be moved to a separate repo. From what I remember, I didn't have time and also barely any sleep during that "let's quickly compile TensorFlow" week.

**Comment by guysoft** [comment]
Those files are in the repo:
https://github.com/photoprism/photoprism/tree/develop/docker/tensorflow

**Comment by guysoft** [comment]
Ah ok, will try download from there

**Comment by lastzero** [comment]
So the only issue is that the Dockerfile contains an absolute path?

**Comment by lastzero** [comment]
You might find https://dl.photoprism.org/tensorflow/nvidia-jetson/config/ more helpful than the regular Linux config for building, but you need to remove GPU support for the Pi.

**Comment by lastzero** [comment]
For example, JOB_COUNT=2 is important if you compile on the Pi so that you're not running out of memory and the CPU does not overheat (even though you might have 4 cores).

**Comment by lastzero** [comment]
The Jetson also has 4 GB and it was barely enough...

**Comment by lastzero** [comment]
Let me know if I shall create a new repo for building TF. No problem. Then we can add complete Docker images for all targets incl. the right config.

**Comment by guysoft** [comment]
Looks like the difference between https://github.com/photoprism/photoprism/tree/develop/docker/tensorflow and https://dl.photoprism.org/tensorflow/nvidia-jetson/config/ is the Makefile.

The difference there is:
```diff
 TF_VERSION=1.14.0
 
-# -march see https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/i386-and-x86-64-Options.html
-
-all: libtensorflow libtensorflow-avx libtensorflow-avx2
+all: libtensorflow static archive
 patch:
        git apply tensorflow-$(TF_VERSION).diff
 libtensorflow:
        bazel build --jobs 2 --config=opt //tensorflow:libtensorflow.so
-       ./create_archive.sh linux-cpu $(TF_VERSION)
-libtensorflow-avx:
-       bazel build --jobs 2 --config=opt //tensorflow:libtensorflow.so --copt=-march=core-avx-i --host_copt=-march=core-avx-i
-       ./create_archive.sh linux-avx $(TF_VERSION)
-libtensorflow-avx2:
-       bazel build --jobs 2 --config=opt //tensorflow:libtensorflow.so --copt=-march=core-avx2 --host_copt=-march=core-avx2
-       ./create_archive.sh linux-avx2 $(TF_VERSION)
-static-avx:
-       env JOB_COUNT=2 ARCH=core-avx-i ./build_static.sh
-static-avx2:
-       env JOB_COUNT=2 ARCH=core-avx2 ./build_static.sh

```


Out of that I removed the last two lines which are the only ones talking about GPU
```
        (cd tmp && tar -czf ../libtensorflow-nvidia-jetson-nano-$(TF_VERSION).tar.gz .)
        du -h libtensorflow-nvidia-jetson-nano-$(TF_VERSION).tar.gz
```


This still breaks. because you are copying stuff from:
COPY /docker/tensorflow/*.sh 

I put a PR for that.

In general I have a container and trying to build tensorflow 1.4.0 for aarch64.
