### ISSUE TITLE
People: Assign categories

### ISSUE THREAD

**Issue by flaotte** [photoprism/photoprism#1988]
I want to create people (faces) groups. One person can belong to several groups.
Family group, co-workers, etc.

use-case:
- I and my wife we are not interested in other side's co-workers.
- I want to show images to relatives, co-workers are not expected to appear. 
- If I go to kid's album and his friends, I don't want to see relatives.

Assignment/handling could be same as photos and albums.

**Comment by graciousgrey** [comment]
Just realized: We already have an issue for this: https://github.com/photoprism/photoprism/issues/1553

**Comment by lastzero** [comment]
Yep, we definitely want to build that as soon as we have time/resources.
