### ISSUE TITLE
Not showing all photos when the photos count is big.

### ISSUE THREAD

**Issue by mexusbg** [photoprism/photoprism#1989]
Not showing all the latest photos / showing in random photos first.

Last version.
About 10000 images in my folder.

Rescan doesn't fix the issue

**Comment by graciousgrey** [comment]
Please follow our issue template and only report clearly identified bugs. Make sure to read the troubleshooting guide as well: https://docs.photoprism.app/getting-started/troubleshooting/#missing-pictures
