### ISSUE TITLE
Config: Add option to display legal info in the footer, e.g. the ICP number

### ISSUE THREAD

**Issue by eallion** [photoprism/photoprism#1990]
When I hosted Photoprism in Mainland China, the web service must display `ICP number` in footer.
Can you provide this feature in the config? I deployed it with docker compose. I didn't find a better way to display it.
Thanks very much!

![111](https://user-images.githubusercontent.com/1698841/151689083-a45fe17d-405c-4bd1-9b6d-4f8fd71ac5a9.png)

**Comment by lastzero** [comment]
Should be possible... How does it look like? Could a smaller font be used for it? Only on the login page or on all pages?

**Comment by srett** [comment]
It's required by law if you host any commercial or noncommercial website in China, or even outside China if it's commercial. Most sites put it in the footer of the main site, see e.g. baidu.com or jd.com – small font should be fine.

**Comment by eallion** [comment]
@lastzero @srett Happy Lunar new year!

No specified style, the `ICP` MUST:
1. link to `https://beian.miit.gov.cn/`
2. both the computer and the eyes can see it.

- www.js.com

![屏幕截图 2022-02-04 212036](https://user-images.githubusercontent.com/1698841/152536062-ddfb692a-0abe-4c80-bf42-a3104098c035.png)

**Comment by eallion** [comment]
- A blog: https://eallion.com

![屏幕截图 2022-02-04 212306](https://user-images.githubusercontent.com/1698841/152536286-27870845-c9ce-4d15-b469-d6585fa0ae26.png)

**Comment by eallion** [comment]
It must display on the landing page, better to show on all page.

**Comment by graciousgrey** [comment]
Would it be sufficient to put it on the login page for now, as unauthenticated users are only able to see this page?

Is this a legal requirement for companies or also for individuals?

**Comment by eallion** [comment]
If you hosted a website in China, you need more than ten licenses, some industries require special licenses. ICP is basic and necessary. It's a legal requirement! Whether you are a company, individual, organization or government...

If Photoprism is unpublic, the ICP only on login page. If not, it must be displayed on every page.

MIIT officer and the ICP system will check the ICP number and link randomly.

**Comment by lastzero** [comment]
This is included in our latest [Development Preview](https://docs.photoprism.app/release-notes/#development-preview) for testing! Release Notes have not been updated yet, but will be soon.

Note that in some places we display the legal information instead of the membership/sponsorship information, so you must be a sponsor to use the new `PHOTOPRISM_IMPRINT` and optional `PHOTOPRISM_IMPRINT_URL` config options. The info is then displayed at the bottom of the browser window, also on the (redesigned) login page.

It was the fastest way to implement this. We hope that signing up as a sponsor (if you haven't already) in return for the new functionality is considered fair by all users.

**Comment by eallion** [comment]
Great! Thanks very much!
I'm still on holiday, I'll try this later.

**Comment by eallion** [comment]
It works!

**Comment by lastzero** [comment]
On the redesigned login page, the information is displayed in the lower right corner instead of the center. Started a new preview build for testing.

**Comment by lastzero** [comment]
Should we keep "imprint" and "imprint-url" or would e.g. "legal-info" and "legal-url" (or "footer-info" and "footer-url") be better? As far as I know, the use of the word "imprint" in this context is somewhat specific to Germany.

**Comment by lastzero** [comment]
Since we received no more feedback, we'll keep "imprint" for the release!

**Comment by eallion** [comment]
For me, I think "legal-info" and "legal-url" or "copyright-info" are better. 
Thanks!

**Comment by lastzero** [comment]
Damn, too late... release has been tagged already.
