### ISSUE TITLE
Search: Album names starting with a number cannot be found

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1994]
**Steps to reproduce:**

1. Create an album with a name like "2022-01-02"
2.  Add photos to it
3. Go to _Search_ and search for albums:"2022-01-02"

**Current behavior:**

All photos are displayed

**Expected behavior:**

Only photos of this album must be shown

**Comment by thehilll** [comment]
I think this is not just limited to search for album names (though maybe you didn't mean to imply it was).  It seems as if numbers never match a search request.  I have a photo that has a subject that appears like this on the Details screen:

`["20151225 Christmas",2015,"Events","John"]`

When I search for

`Subject: John`

it works as expected (returns every photo with "John" in the subject), but if I search for:

`Subject: "20151225 Christmas"`

I get everything that includes the word "Christmas" (e.g. "20141225 Christmas" as well) returned

If I search for either of:

`Subject: 2015`
`Subject: "2015"`

I get nothing, even though that number/word by itself is in the subject list.

**Comment by graciousgrey** [comment]
The subject search filter is only looking for matches in people(=subjects) see https://docs.photoprism.app/user-guide/organize/search/#search-filter-overview

I admit it's a bit confusing.

There is no dedicated search filter for the subject from the details tab for performance reasons (will be improved later). It is covered by the full-text search (which ignores number).

For now you could search year:2015 month:12 day:25 Christmas

**Comment by thehilll** [comment]
Thanks for the explanation.

**Comment by rabotond** [comment]
Tested. 
Seems to be fixed, indeed.
