### ISSUE TITLE
Search: Typing lag when entering queries in the search toolbar

### ISSUE THREAD

**Issue by agramner** [photoprism/photoprism#1995]
**What does not work as described in the documentation?**
This is not a major problem, just a bit annoying.

On the People-page, when there are many people in the list, typing in the search box is slow. It's fast when there are few people, for example after searching on a first name to narrow down the result. Tried both Firefox and Chrome on OSX, Windows and Android.

I currently have 320 people in the list and all the people are loaded when opening the People-page

**How can we reproduce it?**

1. Go to 'People' page
2. Click in the search input box
3. Start typing

**What behavior do you expect?**
I think typing should be super fast no matter how many people there are in the list because "nothing" is done until the user presses Enter key

**What could be the cause of your problem?**
I don't know Vue but can it have something to do with the how the "v-model" on the search box works? Something seems to cause a lot of computation on text input.

**Can you provide us with example files for testing, error logs, or screenshots?**
Nothing is written to the Console log of the browser

**Which software versions do you use?**
- PhotoPrism Architecture & Build Number (AMD64, ARM64, ARMv7,...): AMD64, 220121-2b4c8e1f-Linux-x86_64
- Database Type & Version (MariaDB, MySQL, SQLite,...): MySQL
- Operating System Types & Versions (Linux, Windows, Android,...): OSX
- Browser Types & Versions (Firefox, Chrome, Safari on iPhone,...): Firefox, Chrome, Safari...

**On what kind of device is PhotoPrism installed?**
- Device / Processor Type (Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...): Intel Core i5-8400T
- Physical Memory & Swap Space (in GB): 8 GB, Swap 1 GB
- Storage Type (HDD, SSD, RAID, USB, Network Storage,...): NVME SSD

**Comment by lastzero** [comment]
Yeah, so 320 people is definitely much more than this was designed for. The list of people is searched via JavaScript and updated while you type. I would assume that facial recognition is also getting slow with that many people/faces.

**Comment by agramner** [comment]
I understand. So it's suppose to update while typing? It doesn't, it only updates when pressing enter for me

**Comment by lastzero** [comment]
Yes, it's supposed to work like that - of course it could be optimized, but we don't have a lot of resources. Pull request welcome!

**Comment by agramner** [comment]
Ok, maybe I'll look into it when I have some time over

**Comment by agramner** [comment]
Investigated this and seems like the 2-way-binding (v-model) seem to cause a lot of components to be re-rendered each time you type a letter in the search box. Tried to change v-model to use only @input and that fixed to problem. Don't know Vue (I work with React), how do you avoid "everything" to be re-rendered each time some data change?

**Comment by ppprism** [comment]
Just an addition: same holds true for searching in the 'Albums' section (and probably others like 'Labels').

**Comment by lastzero** [comment]
We'll probably rework the forms and search when we upgrade to Vuetify 3, so I've only fixed the specific UX issues. Started a new [Development Preview](https://docs.photoprism.app/release-notes/) build for testing! :+1:

**Comment by agramner** [comment]
Sounds great, nice work! Will try in out later tonight

**Comment by agramner** [comment]
Sorry to say, but it didn't seem to fix the issue 😩. Just tried the preview image.

**Comment by lastzero** [comment]
What version / build specifically? See footer of Settings page.

**Comment by agramner** [comment]
It's Build 220323-45b56313-Linux-AMD64

**Comment by lastzero** [comment]
From the VueJS docs at https://v2.vuejs.org/v2/guide/forms.html?redirect=true#lazy)html?redirect=true#lazy:
> By default, v-model syncs the input with the data after each input event (with the exception of IME composition, as [stated above](https://v2.vuejs.org/v2/guide/forms.html?redirect=true#vmodel-ime-tip)). You can add the lazy modifier to instead sync after change events:
```html
<!-- synced after "change" instead of "input" -->
<input v-model.lazy="msg">
```

**Comment by lastzero** [comment]
As it turns out, "lazy" is not so lazy.... every time the filter object changes, the entire page is re-rendered. A new property has been added that is not directly referenced in the DOM, so rendering can at least be delayed until the user is done typing. Should consider developing critical UI components with vanilla JS in the future.

**Comment by lastzero** [comment]
A new [Development Preview](https://docs.photoprism.app/release-notes/) build has been pushed to Docker Hub. *Albums*, *Labels*, and the *Library > Errors* page have been reworked along with *People > Recognized*.... hope this works for you!

**Comment by agramner** [comment]
This sure fixed it, nice! :)

**Comment by agramner** [comment]
The behavior has changed a bit though. The search is "executed" when the search box loses focus. Not on submit (enter-key) as before.

**Comment by lastzero** [comment]
Yes, that seemed more intuitive when I tested it. Should we always wait until the user presses the enter key?

**Comment by agramner** [comment]
I don't have a very strong opinion but for me it feel most intuitive to either filter while typing or filter on submit (enter).

**Comment by lastzero** [comment]
While typing would be possible, but then the user interface lags, which was the original problem...

**Comment by lastzero** [comment]
@agramner It seems reasonable not to change the current behavior in order to stay consistent, so the automatic update of search results on blur/change has been disabled. A new preview build will be available soon. I'd appreciate if you could test it again!

**Comment by agramner** [comment]
Yes it works as before now 👍

**Comment by lastzero** [comment]
Fix needs to be reworked. The new implementation does not retain the query when the initial value is set by navigating to the search page and you then - for example - change the view type in the toolbar.

**Comment by lastzero** [comment]
Would be great if you (and everyone else) could test it again! 🙏

**Comment by agramner** [comment]
I can test it but I don't really understand what the problem was. Can you elaborate? 🙂

**Comment by lastzero** [comment]
In short, the problem was a workaround solution instead of passing changes to the parent component using a callback, which then updates the search field value. This is important as Vue JS reuses component instances if you navigate to a different page that is based on the same components. This got the field and the actual search query out of sync previously.

**Comment by agramner** [comment]
Ok, I understand. I can verify that the search query persists while changing between different view types on the search page.

**Comment by lastzero** [comment]
The text field wasn't working at all before I fixed it this morning. It was connected to the wrong event handler, which I hadn't noticed before. So every little bit of testing helps! 🐣

**Comment by dotfortun3** [comment]
If this is still being working on, could a potential fix could be adding a small delay before updating between only update the view if say 500/1000ms has passed since the last keystroke?

Not sure if this is a solution you would consider, but it is something I have done before to get the results to update as you type, but not lag with large datasets.

I could also look into adding this as a PR, but I don't want to do that if a solution has been completed

**Comment by lastzero** [comment]
I think searching on enter / submit is OK, so you are control and don't have to type faster just to avoid premature search requests.
