### ISSUE TITLE
Search parser similar to GitHub

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2]
Instead of providing a huge search form with different fields, PhotoPrism should perform search based on a string that can also easily be bookmarked/remembered.

Example: https://github.com/search/advanced

**Comment by devzsolt** [comment]
Great idea. IMHO tag search should belong here too.

**Comment by lastzero** [comment]
Popular Go parser library: https://github.com/alecthomas/participle

**Comment by lastzero** [comment]
Done that, can be closed.
