### ISSUE TITLE
Check if EXIF information contains unique ID and use it for duplicate detection

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#20]
Potential fields that can be used:

ImageID, ImageNumber, RawDataUniqueID, OriginalRawFileName

See http://www.exiv2.org/tags.html

**Comment by dsoprea** [comment]
I would just use a phash. This produces a hash that should withstand scaling and minor amounts of filtering. At best you eliminate duplicates. At worst, you still have them. Either way, you'll eliminate files resulting from simple copies/renaming on disk.

I wrote a Go implementation a couple of years ago that produced identical results to the other implementations at http://blockhash.io . They never updated the website, but it works all the same.

https://github.com/dsoprea/go-perceptualhash

It's not perfect, but it's as close as you're gonna get without some research guys.

**Comment by lastzero** [comment]
Was also going to look into the sha1 fingerprints we do for all files... my feeling is it adds significant overhead, maybe we can find a faster solution that is also reliable. It is used to determine, if a file needs to be indexed again and if need thumbs are needed.

**Comment by dsoprea** [comment]
That makes more sense. You're not (at this stage) concerned with associating all permutations.

**Comment by lastzero** [comment]
The light and color maps we have for all photos are some kind of perceptual hash... we want to use that later to easily find similar images.

**Comment by dsoprea** [comment]
That's interesting. Presumably, you'd have to layer them or otherwise marry them together first.

**Comment by lastzero** [comment]
See https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/colors.go

**Comment by lastzero** [comment]
We now extract Document and Instance ID via exiftool and use it for grouping related files with different names.

**Comment by dsoprea** [comment]
What if those aren't present (since they're nonstandard)?

**Comment by lastzero** [comment]
Exif may contain an ImageID, typically a hash or UUID. Not extremely common though. Document and Instance ID can be found in XMP metadata.
