### ISSUE TITLE
Edit photo details: Splitting longtitude/latitude data automatically

### ISSUE THREAD

**Issue by RasmusLauritsen** [photoprism/photoprism#2008]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more of a annoyance. Currently I have a lot of photos, where the GPS information is gone. I am adding some of it back, finding the longtitude and lattitude using Google Maps.
When I find the location on Google Maps, I right click and copy the location. This is saved in the clipboard as <longtitude, latitude>.
In PhotoPrism, I paste it in the longtitude field, and have to mark, cut and paste the latitude in the next field over.

**Describe the solution you'd like**
PhotoPrism should detect if a pasted value in either longtitude or latitude has a comma in it, and automatically split the value into the two fields.

Example:
Paste 43.64594336418684, -79.37896320305587 in Longtitude.
Then PhotoPrism should fill out:
Longitude: 43.64594336418684
Latitude: -79.37896320305587

**Comment by graciousgrey** [comment]
Could be done at one point but to be honest this has not a high priority compared to all the other open feature requests. It's also planned to set locations directly on a map.

For now there is a community maintained browser plugin that  allows you to select the location on a map: https://docs.photoprism.app/user-guide/organize/edit/#geolocation-plugin

**Comment by graciousgrey** [comment]
This has been added with https://docs.photoprism.app/release-notes/#september-23-2023
