### ISSUE TITLE
Add file browser to Web UI

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#201]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/201)

**As a User, I want to use the existing PhotoPrism Web UI to manage my image and sidecar files so that I don't need to use an extra tool like https://filebrowser.xyz/.**

Just an idea for now, waiting for feedback and maybe even a contributor who wants to do this. We might build upon https://github.com/filebrowser/filebrowser as this project needs a new maintainer anyways.

![Screenshot 2020-01-16 at 16 05 02](https://user-images.githubusercontent.com/301686/72536150-ff153680-3879-11ea-994f-144e769cfe80.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- $50.00 have been anonymously funded.
### Submitted pull Requests
- [#412 Complete file browser with symlink support and full folder / file names](https://issuehunt.io/r/photoprism/photoprism/pull/412)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by ankitskvmdam** [comment]
I would like to work on it.

**Comment by lastzero** [comment]
It's already done / started: https://demo.photoprism.org/files
