### ISSUE TITLE
"Latest" (d502a5c57ac1) docker image fails, while 20220121 works.

### ISSUE THREAD

**Issue by hal2100** [photoprism/photoprism#2013]
For some reason the "Latest" (digest: d502a5c57ac1) docker image fails with what I believe is a database connection error:

mariadb_1     | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
photoprism_1  | time="2022-02-06T11:25:48Z" level=fatal msg="dial tcp 127.0.0.1:4000: connect: connection refused"
photoprism_photoprism_1 exited with code 1

Switching to SQLite doesn't work either:
photoprism_1  | `sqlite` is not officially supported, running under compatibility mode.                                                                                                                      
photoprism_1  | `sqlite` is not officially supported, running under compatibility mode.                                                                                                                      
photoprism_1  | `sqlite` is not officially supported, running under compatibility mode.                                                                                                                      
photoprism_1  | `sqlite` is not officially supported, running under compatibility mode.                                                                                                                      
photoprism_1  | time="2022-02-06T11:04:35Z" level=fatal msg="sql: unknown driver \"sqlite\" (forgotten import?)"                                                                                             
photoprism_photoprism_1 exited with code 1 

This happened with a nearly unedited docker-compose.yml, only volumes added.

My system:
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
Docker updated to latest today.

How to reproduce:
Pull the "latest" docker and try to run it.

**Comment by lastzero** [comment]
4000 is the port in the development config, did you follow the instructions in Getting Started?

**Comment by hal2100** [comment]
`This happened with a nearly unedited docker-compose.yml, only volumes added.`

Yes, were you not able to reproduce the error?

**Comment by lastzero** [comment]
Unedited?

Compare...

```
photoprism_1 | time="2022-02-06T11:25:48Z" level=fatal msg="dial tcp 127.0.0.1:4000: connect: connection refused"
```

...with...

```
PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
```

see https://dl.photoprism.app/docker/docker-compose.yml
