### ISSUE TITLE
Use Google Maps Location History to reverse-geotag all pictures

### ISSUE THREAD

**Issue by ij0n** [photoprism/photoprism#2018]
**Is your feature request related to a problem? Please describe.**

I have a huge archive of all digital photos I took since 2009. Since 2013, I allow Google to track my Location History. None of my DSLRs have GPS, so 99% of my pictures do not have a geotag. Only a small amount of smartphone-pictures have a geotag. 

**Describe the solution you'd like**

I'd love a way to download the location-history json file from Google, store it somewhere where the original pictures are, and then have photoprism go through the json and add a geolocation which is linearly interpolated time-based between the last and the next location point in the json-file for every picture in my storage. 

**Describe alternatives you've considered**

I googled for tools that allow this and were not successfull for the scenario of a huge json (>1GB uncompressed) and more then 30.000 pictures. The available tools seem to prefer GPX-Import of much shorter tracks.

**Comment by graciousgrey** [comment]
We already have an issue for this: https://github.com/photoprism/photoprism/issues/1174
Feel fee to leave a :+1: there
