### ISSUE TITLE
Docker: Do not load libtensorflow.so.1 if TensorFlow is disabled

### ISSUE THREAD

**Issue by larsxschneider** [photoprism/photoprism#2031]
**What does not work as described in the documentation?**

`photoprism:armv7` fails do start in docker on my ARM server with the following error:
```
photoprism start
photoprism: error while loading shared libraries: libtensorflow.so.1: ELF load command alignment not page-aligned
```

I think the reason is that my ARM7 CPU (Annapurna Labs Alpine AL314 Quad-core ARM Cortex-A15 CPU @ 1.70GHz) only supports 32-bit instructions. See https://github.com/photoprism/photoprism/issues/109#issuecomment-742072348.

However, even if I set `PHOTOPRISM_DISABLE_TENSORFLOW: "true"`, then I still get the same error.

**What behavior do you expect?**

If  `PHOTOPRISM_DISABLE_TENSORFLOW: "true"`, then it would be great if PhotoPrism would not load `libtensorflow.so.1`. Would that be possible? (I am asking because I don't know the internals of the project)
 
**Which software versions do you use?**

- PhotoPrism Architecture & Build Number (AMD64, ARM64, ARMv7,...): latest `photoprism/photoprism:armv7`
- Database Type & Version (MariaDB, MySQL, SQLite,...): SQLite
- Operating System Types & Versions (Linux, Windows, Android,...): Linux

**On what kind of device is PhotoPrism installed?**

- Device / Processor Type (Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...): 
  Annapurna Labs Alpine AL314 Quad-core ARM Cortex-A15 CPU @ 1.70GHz

- Physical Memory & Swap Space (in GB): 8GB physical RAM

**Comment by lastzero** [comment]
You should use the 64 bit version on a RP4. Also you have to build a custom version if you want to run it on Alpine without TensorFlow.

**Comment by lastzero** [comment]
Just saw it's a ARMv7 device. Performance won't be great anyway so it's not worth investing days to get it working. I suggest checking Google for similar errors (spontaneously found a few related issues) and also try another OS as it could be related to Alpine. I've wasted half my day to get it running on Alpine and gave up eventually, in part due to TensorFlow.

**Comment by lastzero** [comment]
Libraries are loaded automatically, when PhotoPrism starts so there is nothing we can do. Since there was no more feedback, I'll move ahead and close this issue.

**Comment by lastzero** [comment]
We may provide a PhotoPrism Light version in the future that does not use TensorFlow and offers less features.

**Comment by rmspeers** [comment]
Suggest reopen as ARMv7 is a OS allegedly supported by the docs that point to it running on WD MyCloud devices, EX4100 is ARMv7.

Running the official docker on this results in this error, from the docker logs:

```
init as root
image: arm-prod, build 220302-armv7
home: /photoprism
umask: "0002" (u=rwx,g=rwx,o=rx)
install-path: /opt/photoprism
running as uid 0
/opt/photoprism/bin/photoprism start
/opt/photoprism/bin/photoprism: error while loading shared libraries: libtensorflow.so.1: ELF load command alignment not page-aligned
```

**Comment by rmspeers** [comment]
For clarity, the image being used is photoprism/photoprism:armv7, see https://docs.photoprism.app/getting-started/raspberry-pi/#older-armv7-based-devices for example documentation of where this should be supported.

**Comment by lastzero** [comment]
Seems to be an issue specific to WD MyCloud, which we never had a chance to test (donations accepted):

https://community.wd.com/t/please-help-elf-load-command-alignment-not-page-aligned-how-can-i-fix-it/142182
