### ISSUE TITLE
Category: Short Description

### ISSUE THREAD

**Issue by eifinger** [photoprism/photoprism#2032]
ONLY CREATE A NEW FEATURE REQUEST AFTER YOU HAVE VERIFIED THAT NO SIMILAR IDEA ALREADY EXISTS:

- Roadmap: https://link.photoprism.app/roadmap
- Open Issues: https://github.com/photoprism/photoprism/issues

Never use GitHub Issues if you have a general question, need help, or an issue has not (yet) been clearly identified. Thank you! 🙃

You are welcome to use GitHub Discussions instead:
https://github.com/photoprism/photoprism/discussions

**Is your feature request related to a problem? Please describe.**

After a great event with some friends I get send a lot of links to their Apple and Google Photo Albums where they share the photos they took. It would be great if I could offer them a private solution where we can all accumulate and share the photos of this event.

**Describe the solution you'd like**

As a logged in user I can create a (password protected) shareable upload link under which photos may be uploaded by an anonymous user. 

As a logged in user I can see what links I have created and delete them. Accessing the link will not work after I deleted it (User gets HTTP 404). This could be in the context of an album or a separate page where I can see all links.

The existing dialogue to share an album could be extended to also allow uploads to this album.

**Describe alternatives you've considered**

If multi user support is implemented in #98 I could create a "Guest" user and try to share this guest user with all my friends. I could also create a user for each friend but would need to provide everyone of them their credentials instead of a single link I can share in a group chat. The barrier of entry needs to be as low as possible to avoid questions like "Why don't we use Google instead of your complicated private setup? Google just works."

**Additional context**

I am currently using Seafile as my file sharing solution but I want to move my photos to photoprism only. The UI there lets me share a folder with separate upload and download links:
![image](https://user-images.githubusercontent.com/1481961/154038092-c33eb617-30fa-47d4-a9f0-fc2b585100df.png)

**Comment by graciousgrey** [comment]
A lot is planned for sharing with anonymous as well as other photoprism users.

See: https://github.com/photoprism/photoprism/issues?q=is%3Aissue+is%3Aopen+sharing+in%3Atitle+

Your use case should be covered by:  https://github.com/photoprism/photoprism/issues/1428, https://github.com/photoprism/photoprism/issues/1330, https://github.com/photoprism/photoprism/issues/557
