### ISSUE TITLE
DB backup and restore for MySQL database within the container

### ISSUE THREAD

**Issue by lzap** [photoprism/photoprism#204]
Hello,

it looks like the container runs MySQL on path `/home/photoprism/.local/share/photoprism/resources/database`. I wonder if it does make sense to mount this directory so when I destroy the container (e.g. for an upgrade) I don't need to reindex my huge database over and over again. It looks like reindex after container deletion is significantly faster for me (probably thumbnails pregeneration was the slowest thing I have't researched this yet) but I don't like reindexing on every destroy. What is your take on this?

I am able to report that the container works flawlessly with podman, Red Hat's docker implementation. I tested it both in root mode and in root-less mode which works fine on recently-released CentOS 8.1 (there was a bug fixed in regard to port mapping).

**Comment by lastzero** [comment]
It's TiDB and it's compiled within our binary. Since we will do some more DB changes, you should expect to re-index from time to time. But when there are no big DB changes, keeping the db files is a good idea!

**Comment by lzap** [comment]
Huh I was so confused, config files mention mysql, heck even docker-compose.yaml contains mysqld command I was almost sure it's MySQL. Yeah, nice pick that embedded TiDB. Let me try to migrate the database on a live instance hopefully it will survive so I don't need to reindex again.

It looks a bit small to me, 20 MB for my 500GB library. Is that normal?

**Comment by lastzero** [comment]
You can also run MySQL or MariaDB, might even be a bit faster... but it's an additional depdencency some users might not want.

**Comment by lzap** [comment]
Nah that is fine, thanks a bunch. Let me contribute a wiki change if you like it.

**Comment by lzap** [comment]
Here ya go: https://github.com/photoprism/photoprism-docs/pull/7
