### ISSUE TITLE
Category: Docker compose mount volume

### ISSUE THREAD

**Issue by ali2210** [photoprism/photoprism#2043]
ONLY CREATE A NEW FEATURE REQUEST AFTER YOU HAVE VERIFIED THAT NO SIMILAR IDEA ALREADY EXISTS:

- Roadmap: https://link.photoprism.app/roadmap
- Open Issues: https://github.com/photoprism/photoprism/issues

Never use GitHub Issues if you have a general question, need help, or an issue has not (yet) been clearly identified. Thank you! 🙃

You are welcome to use GitHub Discussions instead:
https://github.com/photoprism/photoprism/discussions

**Is your feature request related to a problem? Please describe.**
Feature

The problem is that docker-compose provide mount volume option which is limited in functionality. Docker-compose mounting within application 
         ```
volumes: 
        - "./:/app/app_data"
```
which means each file created with in the folder which is not good option. These files for application not for user.

**Describe the solution you'd like**

Like Docker-file volume, docker-compose provide where all the files that are generate by application should be store in docker directory.

**Describe alternatives you've considered**

reside on application data option which is not good

**Additional context**

**Comment by graciousgrey** [comment]
What functionality is missing exactly when it comes to volume mounts? 

The volume mounts are meant to define the location of your storage and originals folders : https://docs.photoprism.app/getting-started/docker-compose/#volumes

What do you want to achieve with: 

```
volumes:
- "./:/app/app_data"
```
 ?

This is not from our example docker-compose files https://dl.photoprism.org/docker/docker-compose.yml).

**Comment by ali2210** [comment]
This is very helpful
