### ISSUE TITLE
CLI: inconsistent options for backup command

### ISSUE THREAD

**Issue by bricas** [photoprism/photoprism#2048]
Note: installed via docker ("latest" tag).

For reference, this is what the usage/options say:
```
USAGE:
   photoprism backup [command options] [FILENAME | -]

   --force, -f         replace existing files
   --albums, -a        create album YAML files organized by type
   --albums-path PATH  custom album files PATH
   --index, -i         create index SQL dump
   --index-path PATH   custom index backup PATH
```

If i use `photoprism backup -f -i /photoprism/storage/backup/database.sql` I get expected results, but if i try `photoprism backup -f -a /photoprism/storage/backup/albums` there is an assumption that i actually mean the index path:
```
WARN[2022-02-20T01:50:46Z] replacing existing SQL dump                  
INFO[2022-02-20T01:50:46Z] writing SQL dump to /photoprism/storage/backup/albums 
ERRO[2022-02-20T01:50:51Z] open /photoprism/storage/backup/albums: is a directory 
```

Also, if i specify all the options i get an odd write permssion error, even though it works on its own:
```
photoprism backup --albums-path=/photoprism/storage/backup/albums --index-path=/photoprism/storage/backup/database.sql --albums --index --force

WARN[2022-02-20T01:49:44Z] custom index backup path not writable, using default 
INFO[2022-02-20T01:49:44Z] writing SQL dump to /photoprism/storage/backup/mysql/2022-02-20.sql 
INFO[2022-02-20T01:49:48Z] saving albums in /photoprism/storage/backup/albums 
INFO[2022-02-20T01:49:51Z] created 3,104 YAML album files               
INFO[2022-02-20T01:49:51Z] backup completed in 7.190282401s             
INFO[2022-02-20T01:49:51Z] closed database connection     
```

**Comment by lastzero** [comment]
The file name is for the SQL dump. Albums are multiple, you can't us that with force and only specify a single file name.

**Comment by lastzero** [comment]
Also you specified a FILENAME as backup FOLDER. We do our best to make the docs even more clear and explicit. Since this is open source you are welcome to contribute and help with this!

**Comment by bricas** [comment]
My intent was not to use it as a single file, but as an assumption that the final argument would be related to the command being run. eg:

`backup -i <file>` and `backup -a <path>`

**Comment by lastzero** [comment]
```
--albums-path PATH
```

**Comment by bricas** [comment]
It's true, that works -- it just feels like if I can use shorthand for -i, then the same could be applied against the -a option, if that's all that's being used, rather than always assuming you mean a filename for -i. This is just an observation and not a bug per se.

However, the real bug is when i specified all the options. It wouldn't write the database file, even though it's the same location as I had used with the "filename" last arg.

**Comment by lastzero** [comment]
It's not a bug. The name is generated automatically if you specify a path only. However, the path looks like the filename you want. In that case, just specify the name. Simple.

**Comment by bricas** [comment]
Oh! Are you saying that `--index-path` is only the _directory_ portion and not the full path including filename? So in theory this would be the correct invocation: 

```
photoprism backup --albums-path=/photoprism/storage/backup/albums --index-path=/photoprism/storage/backup/ --albums --index --force database.sql

```

**Comment by lastzero** [comment]
You're welcome to send a pull request to change "path" to "dir" if this helps 👍

**Comment by bricas** [comment]
Just gave it a try and didn't get what I expected
```
> docker exec -it photoprism photoprism backup --albums-path=/photoprism/storage/backup/albums --index-path=/photoprism/storage/backup/ --albums --index --force database.sql
INFO[2022-02-20T03:47:35Z] Help us make a difference and become a sponsor today! 
INFO[2022-02-20T03:47:35Z] Visit https://docs.photoprism.app/funding/ to learn more. 
INFO[2022-02-20T03:47:35Z] writing SQL dump to database.sql             
INFO[2022-02-20T03:47:42Z] saving albums in /photoprism/storage/backup/albums 
INFO[2022-02-20T03:47:46Z] created 3,104 YAML album files               
INFO[2022-02-20T03:47:46Z] backup completed in 10.97488481s             
INFO[2022-02-20T03:47:46Z] closed database connection
```
Albums went to the proper spot, but the database.sql did not:
```
> docker exec -it photoprism /bin/bash
root@3e8d6e5de1f6:/photoprism# ls -l
total 92304
drwxrwxrwx  1 photoprism photoprism     4096 Jan 21 11:50 assets
drwxrwxrwx  1 photoprism photoprism     4096 Jan 21 11:50 bin
-rwxr-xr-x  1 root       root       94497336 Feb 20 03:47 database.sql
drwxrwxrwx  2 photoprism photoprism     4096 Jan 21 11:50 import
drwxrwsrwx 23 photoprism users          4096 Feb  3 21:33 originals
drwxr-sr-x  6 photoprism users          4096 Feb 20 03:47 storage
```

Apologies if I'm not using the tool as expected. at this point I'm happy to ignore that option entirely and just use this:
```
> docker exec -it photoprism photoprism backup --albums-path /photoprism/storage/backup/albums --albums --index --force /photoprism/storage/backup/database.sql
INFO[2022-02-20T03:53:53Z] Help us make a difference and become a sponsor today! 
INFO[2022-02-20T03:53:53Z] Visit https://docs.photoprism.app/funding/ to learn more. 
WARN[2022-02-20T03:53:53Z] replacing existing SQL dump                  
INFO[2022-02-20T03:53:53Z] writing SQL dump to /photoprism/storage/backup/database.sql 
INFO[2022-02-20T03:54:00Z] saving albums in /photoprism/storage/backup/albums 
INFO[2022-02-20T03:54:03Z] created 3,104 YAML album files               
INFO[2022-02-20T03:54:03Z] backup completed in 10.265200845s            
INFO[2022-02-20T03:54:03Z] closed database connection 
```

**Comment by lastzero** [comment]
Providing the full file path is enough. Don't over complicate things :)
