### ISSUE TITLE
Attempt to archive photos lead to 401

### ISSUE THREAD

**Issue by lzap** [photoprism/photoprism#205]
Hey, I am trying to archive about 10 photos but I am getting 401. I think I may have restarted the app in the meantime, this is what I see in logs:

    [GIN] 2020/01/16 - 20:56:42 | 401 |       60.15µs |   192.168.1.128 | POST     /api/v1/batch/photos/archive

Anything else I can do in order to investigate what is causing unauthorized?

**Comment by lzap** [comment]
Hmm after I cleared my selection it worked. Weird. Not a biggie.

**Comment by lastzero** [comment]
Is this is a public installation? Otherwise the session gets lost if you restart, so any request afterwards will lead to a 401

**Comment by lzap** [comment]
Nope a home server. Ok good to know, thanks.

**Comment by lastzero** [comment]
With public I meant no password required.
