### ISSUE TITLE
Folders: Ignore case and use wildcards when searching

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#2050]
**Steps to reproduce**
1. Create a folder with a name like "Laura Geburtstag"
2. In the folder section search for "Geburtstag"

**Current behavior**
The folder "Laura Geburtstag" is not shown. 
Searching for *Geburtstag does work.

**Expected behavior**
The folder "Laura Geburtstag" must be shown.

**Comment by lastzero** [comment]
Note that searching for terms at the end of a pathname in this view requires a `*` wildcard.

**Comment by tanuva** [comment]
We/I had stumbled upon this problem a few weeks ago on Matrix. I feel like adding that this noticeably degrades usability on mobile, where starting a search term with `*` means additional typing. For folder a structure like mine (`YYYY/MM-DD <event_name>`} that affects *every* folder search, of course.

**Comment by KuenzelIT** [comment]
Hi,

I still don't exactly get how the search works. When I search for "*test*", then it only finds one of two folders with "test" in it. It's also counterintuitive to write wildcards in a search input.

**Comment by lastzero** [comment]
The most recent changes were introduced in January. Did you test our development preview? See docs for how to update.
