### ISSUE TITLE
how to disable gen thumbnail when scan originals in Library?

### ISSUE THREAD

**Issue by wpfchina** [photoprism/photoprism#2063]
how to disable gen thumbnail when scan originals in Library?

run in local pc, don't need thumbnails

**Comment by lastzero** [comment]
Read the FAQ.

**Comment by graciousgrey** [comment]
https://docs.photoprism.app/getting-started/faq/#can-i-skip-creating-thumbnails-completely
https://docs.photoprism.app/user-guide/settings/advanced/#images
