### ISSUE TITLE
Index: Out of Memory during indexing new photos

### ISSUE THREAD

**Issue by logol01** [photoprism/photoprism#2064]
When I index new images or index all images again, the indexing stops after a certain time and I see "offline" in my status window in Photoprism. 
At the same time I see an error on my Docker host in the terminal with the following text: 
"[111607.682574] Out of Memory: Killed process 8366405 (photoprism) total-vm:5763668kB, annon-rss:1448384kB2, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:3620kb oom_score_adj:0"

 Version of Photoprism on docker 220121-2b4c8e1f-Linux-x86_64

**Comment by lastzero** [comment]
https://docs.photoprism.app/getting-started/troubleshooting/

**Comment by logol01** [comment]
Thanks!
The problem was that I didn't have a swap partition. Now everything runs perfectly.
