### ISSUE TITLE
Docs: Improve "cgroups" hint in docker-compose.yml for Raspberry Pi OS on ARMv7 and ARM64

### ISSUE THREAD

**Issue by wechsler42** [photoprism/photoprism#2067]
Hi there,
I would like to suggest to adapt the notes on cgroups in docker-compose.yml for Raspberry Pi (armv7 and arm64) for Raspberry Pi OS, due to an incorrect path for this distro:
(OLD) 
 If you see Docker errors related to "cgroups", it may help to add the following to /boot/firmware/cmdline.txt:
(NEW)
 If you see Docker errors related to "cgroups", it may help to add the following to /boot/firmware/cmdline.txt or /boot/cmdline.txt (file location depends on your OS in use):

**Comment by lastzero** [comment]
Updated the `docker-compose.yml` config examples as well as the notes in our Getting Started guide:

https://docs.photoprism.app/getting-started/raspberry-pi/#raspberry-pi-os

**Comment by rabotond** [comment]
Tested. Guide indeed updated.
