### ISSUE TITLE
Metadata: Read Zulu/UTC dates from Exiftool JSON

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#2082]
**Acceptance Criteria:**
- Read zulu/utc dates from exiftool json
- Write unit test

**Comment by lastzero** [comment]
Expected date/time format changed from `2006:01:02 15:04:05-07:00` to `2006:01:02 15:04:05Z07:00`. Now successfully parses `2006:01:02 15:04:05Z` in addition to numeric time offsets.
