### ISSUE TITLE
 Help translate the UI!

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#2083]
We now use [Weblate](https://translate.photoprism.app/) for our translations, so anyone without programming skills can contribute as well :tada: 

If you are a native speaker of one of the languages already available, you can support us by:

- **Adding missing translations** 

- **Improving existing translations** 

Instructions can be found [here](https://docs.photoprism.app/developer-guide/translations-weblate/)

If you are a native speaker of a language that is not yet supported and you want to translate to that language, just leave a comment here :)

Thank you very much :heart:

**Comment by aktentasche** [comment]
[Link](https://translate.photoprism.app/projects/photoprism/#languages) to the percentage of completion for each currently supported language.
