### ISSUE TITLE
websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by vx3r** [photoprism/photoprism#209]
Hi all,

Just got the error
```level=error msg="websocket: request origin not allowed by Upgrader.CheckOrigin"```
Is there any way to specify Origin to allow? I have nginx in front of photoprism 

Thank you

**Comment by lastzero** [comment]
When using Caddy, you have to explicitly configure it as websocket proxy. There's probably a similar setting for nginx.

**Comment by lastzero** [comment]
See https://www.nginx.com/blog/websocket-nginx/

Would be great if you can share your config for other nginx users!

**Comment by vx3r** [comment]
Will check it soon and share yes, thank you

**Comment by vx3r** [comment]
Here is my nginx server block 

```
server {
        listen                  443 ssl http2;
        listen                  [::]:443 ssl http2;
        server_name             photoprism.127-0-0-1.fr;

        auth_basic              "YOU SHALL NOT PASS";
        auth_basic_user_file    /etc/nginx/htpasswd;

        location / {
            proxy_pass          http://photoprism:2342;
            include             /etc/nginx/proxy.conf;
            proxy_set_header    Origin http://photoprism:2342;
            proxy_set_header    Connection "Upgrade";
        }
}
```
The issue has been resolved by adding ``` proxy_set_header    Origin http://photoprism:2342; ```
please see [Origin Considerations WS](https://godoc.org/github.com/gorilla/websocket#hdr-Origin_Considerations) and [websocket issues](https://github.com/gorilla/websocket/issues/367).

I believe that more elegant solution would be:
- take the origin from ``` PHOTOPRISM_URL: "https://photoprism.127-0-0-1.fr/"```  env variable 
- check it in ``` Upgrader.CheckOrigin ``` function when creating ```websocket.Upgrader{}```

**Comment by lastzero** [comment]
I'll merge this into master if CI passed, you can then pull an updated Docker image and see if you still need to change the header. The origin field doesn't add much security, I've disabled the check.

**Comment by lastzero** [comment]
Build is running: https://travis-ci.org/photoprism/photoprism/builds/639634178

New image should be available in ~30 minutes.

**Comment by vx3r** [comment]
Tested, i can confirm that ```proxy_set_header Origin http://photoprism:2342;``` is not required anymore.
Thank you for this quick fix.
