### ISSUE TITLE
Places: add a layer selector box to map to switch from OpenStreetMap view to satellite view  and back

### ISSUE THREAD

**Issue by wechsler42** [photoprism/photoprism#2102]
Hi there, 
adding a satellite view would be a nice enhancement for the already implemented OpenStretMap view in "Places" . I would like to suggest a map layer selector box where one could switch to a satellite map like it is done here:
![image](https://user-images.githubusercontent.com/19371424/156539401-3291d52a-78de-4828-9cd6-586e3642e887.png)
and here
![image](https://user-images.githubusercontent.com/19371424/156538927-d564941c-fdfd-4565-8bb2-b83cafc9d4f4.png)
and here
![image](https://user-images.githubusercontent.com/19371424/156539474-f21a123f-801c-41b6-ad66-c809482a93ac.png)

For example, [MapBox](https://www.mapbox.com/) offers a free satellite view service.

**Comment by lastzero** [comment]
The Mapbox page says Get Started For Free, not that the service is generally free 😋

We have a satellite view when you select Hybrid in Settings.

**Comment by wechsler42** [comment]
> The Mapbox page says Get Started For Free, not that the service is generally free 😋
Sorry, I was not precise enough: I meant that you could generate a personal MapBox API access token which is free of charge as long as you are below a certain number of monthly requests. The monthly request number should be enough for a private use scenario.

> We have a satellite view when you select Hybrid in Settings.
Aah, I did not notice that, sorry. So, I would now just suggest a map layer selector box where I could switch dynamically the the view without going to settings every time. I would do a feature request for this if appropriate?
