### ISSUE TITLE
Places: Add map style selector and a scale for comparing distances

### ISSUE THREAD

**Issue by wechsler42** [photoprism/photoprism#2106]
Hi there,
adding a map layer selector box as an overlay would be a nice usability and functional enhancement. One could dynamically switch between the different map styles (Streets, Hybrid, Outdoor, etc) without going back and forth to the drop down menu in Settings>>Places>>Styles . An example for such a map layer selector box is illustrated here:
![image](https://user-images.githubusercontent.com/19371424/156571800-1d27257a-642b-43bc-b9fd-d17aa5f90943.png)
and
![image](https://user-images.githubusercontent.com/19371424/156572200-b5f5b517-561e-4179-a097-ac83faa13d55.png)

Thanks for considering this suggestion.

**Comment by lastzero** [comment]
With these changes, the Places view will include a map style control in the lower right corner and a map scale control in the lower left corner. An updated preview build for testing should be available within the next hour:

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by lastzero** [comment]
Here's a screenshot of the Places view with the added map controls (the scale can be seen in the lower right corner, the map style can be changed using the button below the other map controls on the right):

![places](https://github.com/photoprism/photoprism/assets/301686/8a082dc8-74f6-4726-9e26-935290daa0c2)

**Comment by lastzero** [comment]
Final screenshot with the map style selector and [places cluster view](https://github.com/photoprism/photoprism/issues/1187) open (the [distance scale](https://github.com/photoprism/photoprism/issues/2106#issuecomment-1728124244), see above, is hidden behind the overlay in this case, but I don't think that's a good enough reason to move it to the top):

![places-cluster-view](https://github.com/photoprism/photoprism/assets/301686/cd48e79f-b2a8-4fb5-bc54-52467b15b743)
