### ISSUE TITLE
Manual label editing

### ISSUE THREAD

**Issue by benwaffle** [photoprism/photoprism#212]
I want to be able to edit the labels manually, to fix mistakes that the model made.

**Comment by lastzero** [comment]
We'll implement a general edit dialog which will also contain a tab for editing labels. Just didn't have the highest priority so far, especially since the db schema was changing a lot and we didn't want our users to lose their manually entered data.

**Comment by lastzero** [comment]
This is a very first draft for our edit dialog. If you select multiple photos, you can use the prev / next buttons in the toolbar. Feedback welcome!

![Screenshot 2020-01-23 at 17 53 57](https://user-images.githubusercontent.com/301686/73005697-ab6e9400-3e09-11ea-898a-9edd4f859748.png)

**Comment by benwaffle** [comment]
Is it going to be fullscreen?

**Comment by lastzero** [comment]
Makes sense for mobile because of limited space. Not sure about desktop browsers yet. What do you think?

**Comment by benwaffle** [comment]
There should be a field to edit the date as well

**Comment by lastzero** [comment]
Of course, and many more :D This is just a first draft...

**Comment by lastzero** [comment]
Photo should also be visible somewhere, maybe top right or top left.

**Comment by lastzero** [comment]
This is how a modal dialog would look like (buttons can be moved to the bottom as well):

![Screenshot 2020-01-23 at 18 43 56](https://user-images.githubusercontent.com/301686/73009191-5b470000-3e10-11ea-9e61-30141c691e2b.png)

**Comment by benwaffle** [comment]
Might also be possible to move Labels to the General

**Comment by lastzero** [comment]
Would get very long, we also have lens, camera, time zone, time, location, altitude, various flags,...

**Comment by lastzero** [comment]
Say hello to our date and time fields 🥳

![Screenshot 2020-01-23 at 22 30 38](https://user-images.githubusercontent.com/301686/73025798-880b0f80-3e30-11ea-9dd9-3becbb628747.png)

**Comment by lastzero** [comment]
Now onwards to the labels:

![Screenshot 2020-01-23 at 23 46 05](https://user-images.githubusercontent.com/301686/73030856-cf969900-3e3a-11ea-97e3-5a22d867e300.png)

**Comment by lastzero** [comment]
Here's a read-only list with labels, hope you like it. Sun is coming out, I'll do editing later or next week, if you're not in a hurry. Docker images & demo will be updated automatically if Docker Hub doesn't have issues (had timeouts recently, probably overloaded). Metadata edit form should be complete.

![Screenshot 2020-01-24 at 11 29 08](https://user-images.githubusercontent.com/301686/73062877-b541d700-3e9d-11ea-9165-a1abedaba87a.png)

**Comment by lastzero** [comment]
@benwaffle Will this work for now? We can implement label renaming later:

![Screenshot 2020-01-29 at 23 50 52](https://user-images.githubusercontent.com/301686/73404621-365ffa80-42f2-11ea-9caf-80764702cb8d.png)

**Comment by lastzero** [comment]
Titles are not automatically updated yet after label changed. Will probably implement that for our first release. Let us know if you think it's important.

**Comment by lastzero** [comment]
You can test on https://demo.photoprism.org/

1. Select a photo
2. Open context menu
3. Press the blue button

**Comment by benwaffle** [comment]
how do i get to the context menu?

**Comment by lastzero** [comment]
Select photos, either on the list view or the tile preview (box visible on hover or long touch)

**Comment by lastzero** [comment]
You can now also edit labels names in the overview

**Comment by zhangtianai** [comment]
<img width="67" alt="Screenshot 2020-02-06 at 11 46 14 AM" src="https://user-images.githubusercontent.com/7039266/73904240-55ecb980-48d6-11ea-94c2-5b34450fbcf1.png">
no the edit button ,why?

**Comment by lastzero** [comment]
@zhangtianai Looks like an old version - you need to update

**Comment by benwaffle** [comment]
1. should the label editor autocomplete to the pre-existing labels in rules.yml, or will it just work?
2. What does it mean to click the edit button when more than one file is selected? i think this might be buggy - the files tab only shows 1 entry

**Comment by lastzero** [comment]
You have prev / next buttons (top right) to go through selected files. Autocomplete might be helpful, but it will just work if you use the same terms.
