### ISSUE TITLE
API: Provide interactive Swagger docs with examples

### ISSUE THREAD

**Issue by ppprism** [photoprism/photoprism#2132]
**What does not work as described in the documentation?**

Searching albums via REST API does not respect the album `title` filter.
This query parameter should be valid according to [form struct](https://github.com/photoprism/photoprism/blob/2a38971ba38a434ee83906c4f25d5607c0587ea4/internal/form/search_albums.go#L11).

**How can we reproduce it?**
```
curl -G -d count=3 -d title='mytitle' -d type=album -H "X-Session-ID: 1234" http://localhost:2342/api/v1/albums
```
ignores `title` constraint. Counter example:
```
curl -G -d count=3 -d favorite=1 -d type=album -H "X-Session-ID: 1234" http://localhost:2342/api/v1/albums
```
only fetches `favorite` albums, as expected.

**What behavior do you expect?**

Apply the `title` filter to the search results.

**What could be the cause of your problem?**

Presumably missing conditional check in [albums](https://github.com/photoprism/photoprism/blob/2a38971ba38a434ee83906c4f25d5607c0587ea4/internal/search/albums.go), unfortunately I have no experience with go.

**Can you provide us with example files for testing, error logs, or screenshots?**

No special data necessary, create an album 'mytitle' amongst other named albums and try to search it - and only it. 

**Which software versions do you use?**

- PhotoPrism 220121-Linux-x86_64 via docker
- MariaDB
- Linux
- Firefox

**On what kind of device is PhotoPrism installed?**

\-

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

\-

**Comment by lastzero** [comment]
Is this a documented feature? A regular query without prefix/filter will automatically search the title.

**Comment by ppprism** [comment]
The REST API itself seems a bit under-documented - I am happy to contribute with more experience.
But I guess the [form parameters](https://github.com/photoprism/photoprism/blob/2a38971ba38a434ee83906c4f25d5607c0587ea4/internal/form/search_albums.go#L11) specified in code are expected to work?

What do you mean by "regular query"? I just tried applying as regular query parameters, which should be handled the same with curl, with same effect:
```
curl -H "X-Session-ID: 1234" "http://localhost:2342/api/v1/albums?title=mytitle&count=2"
```

**Comment by lastzero** [comment]
No, not necessarily, for example when work gets interrupted by other high priority tasks. Try using q instead of title.

The search filters are documented in the User Guide, not in the developer guide though. It's not a lack of experience, just lack of time. You're welcome to contribute!

**Comment by ppprism** [comment]
You mean [these](https://docs.photoprism.app/user-guide/organize/search/#search-filter-overview)? With `title` filter, I tried following for `q`:
```
curl -H "X-Session-ID: 1234" http://localhost:2342/api/v1/albums?q='title:mytitle&count=3'
# or; equivalent to
curl -G -d count=3 -d q='title:mytitle' -H "X-Session-ID: 1234" http://localhost:2342/api/v1/albums
```
Unfortunately, effect is exactly the same: Albums/folders unrelated to title 'mytitle' are fetched, no `title` filter is applied.

Appreciate any clarification, thanks!

**Comment by lastzero** [comment]
Title is searched by default. No need to use a specific filter. Don't use title at all.

**Comment by ppprism** [comment]
Agree, it works.

Are there any intends to make the API more intuitive? I honestly wouldn't be able to explain these quirks and differences in the docs currently.

**Comment by lastzero** [comment]
We intend to make everything better, but are just 2 people at the moment. I recommend using your browser console to see the requests the existing, working, and documented UI is making.

**Comment by ppprism** [comment]
Thanks, good tipp!
I let this issue open in case there isn't already a canonical feature request for improving REST API parameters.

**Comment by lastzero** [comment]
With these changes, Swagger API docs will be generated when you run `make swag` in the project base path within your [development environment](https://docs.photoprism.app/developer-guide/setup/):


![swagger-docs](https://github.com/user-attachments/assets/876df61c-b1bc-4ef4-bd03-d445c7defcfc)

You can browse them locally by navigating to https://app.localssl.dev/api/v1/docs/index.html after rebuilding and starting `photoprism`, e.g.:

```bash
make swag
make build
./photoprism start
```

Note that the new `/api/v1/docs` API documentation endpoint is disabled in production builds.

**Any help with adding endpoint annotations, as explained at https://github.com/swaggo/swag, would be much appreciated!** :pray:

**Comment by lastzero** [comment]
We've added a section on the new Swagger API docs to our Developer Guide, so that developers know they exist and can help to add more annotations to improve the endpoint documentation:
- https://docs.photoprism.app/developer-guide/api/docs/

**Comment by lastzero** [comment]
When adding API endpoint annotations, be sure to use `@Router` and not `@Route` as I accidentally did. Swag completely ignores these without a single warning. It took me a long time to figure out what was wrong...

https://github.com/photoprism/photoprism/blob/1eaaab9aa63ac2b4db5a08220c6350a8a82090fc/internal/api/albums.go#L37-L48

**Comment by lastzero** [comment]
Our Swagger API documentation is now also publicly available at https://docs.photoprism.dev/ :gift:

**Comment by lastzero** [comment]
These changes move the generated `swagger.json` file to `/internal/api` and embed it in the executable when building in develop or debug mode:
https://github.com/photoprism/photoprism/blob/88156866f669ad297d38088048e4d2b6e4242c5c/scripts/build.sh#L28-L29

**Comment by lastzero** [comment]
Our Developer Guide has been updated to be consistent with the changed `swagger.json` file path:
- https://docs.photoprism.app/developer-guide/api/docs/

**Comment by balki** [comment]
@graciousgrey  @lastzero  In the generated swagger doc for [searchPhotos](https://docs.photoprism.dev/#/Photos/SearchPhotos), it is missing parameter `s` that is used to choose the album to get photos from.
![image](https://github.com/user-attachments/assets/33c59f57-6324-47fd-a3e5-bec344474429)

From developer [guide](https://docs.photoprism.app/developer-guide/api/search/#request-parameters)
 
![Screenshot from 2024-08-02 12-02-08](https://github.com/user-attachments/assets/4e49cc04-8b75-4580-8eae-ec51b5905dc6)

**Comment by graciousgrey** [comment]
Thank you for reporting! The parameter is included now.
