### ISSUE TITLE
[Bug]: Errors during indexing

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#215]
I've been getting a lot of errors thrown during indexing. An example is shown below:
`ERRO[2020-01-22T11:53:06Z] index: Error 1406: Data too long for column 'photo_exposure' at row 1`

I've tried all of the available docker images:
```
photoprism/photoprism      20200122                     84dd7e0b96c1        2 hours ago         882MB
photoprism/photoprism      20200121                     4660c473463b        21 hours ago        882MB
photoprism/photoprism      20200120                     702f467e2e9c        40 hours ago        882MB
``` 
What is more, I've tried to manually index the problematic photos in the development container and no errors are thrown.

**Comment by lastzero** [comment]
Would be interesting to know what the string for photo_exposure is... maybe you have an old database schema with a too short column in photos? You can check that using any MySQL client.

Anyhow, will increase size from 32 to 64 chars. Should be enough for the exposure time!?

**Comment by lastzero** [comment]
Pushed this along with other changes:

https://github.com/photoprism/photoprism/commit/f569c3adb6ac872f261411f018f158d16730071e#diff-729b547d4c454e0ea3bfce55580a51bd

**Comment by linosgian** [comment]
I was going through the code and I noticed that the size of `PhotoExposure` was bumped from 16 to 32 characters (b37d4472), I ran `photoprism migrate` in order to update the schema, but the issue persists. Once the docker image containing your commit is uploaded, i'll test it and i'll let you know.

**Comment by linosgian** [comment]
`photoprism migrate` doesn't seem to work as intended:
```
 photo_exposure      | varbinary(16)    | YES  |      | NULL    |                |
```
As stated above, its size was bumped quite a while ago.

**Comment by linosgian** [comment]
It turns out that [gorm's `AutoMigrate`](http://gorm.io/docs/migration.html) doesn't update existing columns, as per their docs:

>WARNING: AutoMigrate will ONLY create tables, missing columns and missing indexes, and WON’T change existing column’s type or delete unused columns to protect your data.

**Comment by lastzero** [comment]
Only new columns / tables will be added, existing ones won't be changed because this could lead to data loss. So you need to delete your database and let the app create a new one.

From our docs:

> Our database schema still changes a lot as we do performance optimizations and add features. Therefore we cannot provide a smooth upgrade path and you should be prepared to delete your current database and re-index. To spare you a disappointment, we kindly advise you not to index large photo collections at the moment.

**Comment by linosgian** [comment]
Alright, I've dropped all tables and re-indexed. The issue is gone, even before the 64 characters bump.

I'll shy away from organizing my photos using albums for now and wait for the first stable release.

Thanks, I'll close this one!
