### ISSUE TITLE
UI: Select all

### ISSUE THREAD

**Issue by jjbeto** [photoprism/photoprism#2153]
**Is your feature request related to a problem? Please describe.**

I've just imported my library into Photoprism (which made a GREAT job), but it contains 178k images.. Giving me 28k images for revision.

It's just impossible to click image per image to archive or approve.

**Describe the solution you'd like**

When we start to select an image, a menu shows up to allow a couple of actions: wouldn't be possible to have an option "select all"? This would just auto select all listed images (at least all in the screen or already loaded). This feature would be nice as well when we are selecting a huge number of images to add to a calendar or album, so basically every time this floating buttons shows up, it should give us the option to select all images somehow.

**Describe alternatives you've considered**

Via UI there is no alternative, aside of clicking image per image.

**Additional context**

none.

The project is awesome, congratulations ;)

**Comment by graciousgrey** [comment]
Thanks for your feedback :) 

At the moment you can use shift click (or long click on mobile) to select multiple images at once. 

"Select all" is out of scope for now for a couple of reasons, see: https://github.com/photoprism/photoprism/issues/272

**Comment by jjbeto** [comment]
Shift-click actually works pretty fine for me! I did a quick search and couldn't find that ref, maybe I've done the search with some filtering.

Thats a good way to do with the problem, for sure, so thank you!

/close

**Comment by graciousgrey** [comment]
You are welcome :)

**Comment by snakyjake1** [comment]
I have to shift-click on 527 images.
