### ISSUE TITLE
Improve authentication and websocket security

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#216]
**As a user, I want to run PhotoPrism without hiding it behind additional auth mechanisms.**

See https://github.com/photoprism/photoprism/issues/167#issuecomment-574866401:
> Make everything private by default (and behind a login) and allow me to share albums or pictures by generating. Right now I'm hiding Photoprism behind a basic HTTP auth mechanism on top of the Kubernetes ingress.

**Comment by lastzero** [comment]
First commit for this: https://github.com/photoprism/photoprism/commit/f569c3adb6ac872f261411f018f158d16730071e

**Comment by lastzero** [comment]
![Screenshot 2020-01-22 at 16 50 00](https://user-images.githubusercontent.com/301686/72909409-421e5080-3d37-11ea-848d-40558b46afc6.png)

**Comment by lastzero** [comment]
@casidiablo Since you asked for it: Maybe you want to test this? :)

![Screenshot 2020-01-23 at 07 47 45](https://user-images.githubusercontent.com/301686/72963508-cdd7c180-3db7-11ea-9320-84c1c79d93e0.png)

**Comment by casidiablo** [comment]
Works for me
