### ISSUE TITLE
Search filter `portrait:no` returns non-filtered results

### ISSUE THREAD

**Issue by PiotrKrzyzek** [photoprism/photoprism#2168]
I'm using the latest (current) version of PhotoPrism and I was trying to find all my photos that are in landscape orientation. There doesn't seem to be a UI feature for this, so I found the "portrait" filter option.

If I search for "portrait:yes" it will return photos that have the height larger than the width (portrait orientation), though if I search "portrait:no" there doesn't seem to be any filtering done as all the same photos show same if I simply clicked on the 'search' menu item.

Using the "portrait:no" filter I would assume that it would mean "show images that are NOT portrait". I didn't see a "landscape" filter option, thus if we can filter for portrait "no" should mean "not".

**Comment by lastzero** [comment]
No means the same as not set, bool filters don't have 3 possible values like yes, no, all.

**Comment by PiotrKrzyzek** [comment]
That's fair. I'll open up a new ticket (after closing this one) for a feature request for either a `landscape` filter or potentially more flexible: an `orientation` filter. :)
