### ISSUE TITLE
Search: Add `square:yes` and `landscape:yes` filters

### ISSUE THREAD

**Issue by PiotrKrzyzek** [photoprism/photoprism#2169]
Photoprism has a wonderful set of search and filter options, though we're not able to filter photos (and others) well by the items orientation. Currently, the only orientation related filter option is 'portrait` which, if set, will give us all portrait oriented (where height is bigger than width) assets.

Though there is no `landscape` filter.

As referenced in my previous bug report / question, `portrait` is a BOOLEAN filter, meaning simply true or false where the default is false meaning: simply not set.

As `false` here means `not set` and not meaning "NOT", thus I propose we have either-or of the following two filter options added:

- `orientation`
- `landscape`

The `landscape` filter would do the exact same thing as portrait (a boolean filter) except for landscape oriented (width greater than height) photos (and videos and whatnot).

Whereas `orientation` could take different options such as: 'landscape', 'portrait' and could be expanded to include more advanced filters such as 'not set', 'circle', 'upside down' and so forth.

**Comment by lastzero** [comment]
Note there is also a `panorama` filter, which limits results to photos/videos in landscape format with an aspect ratio of 2:1 and a minimum width of 1000 (or more):

https://github.com/photoprism/photoprism/blob/develop/internal/search/photos.go#L351

**Comment by lastzero** [comment]
Added `square:yes` and `landscape:yes` filters, in addition to the existing `panorama:yes` and `portrait:yes` search filters:

|  Filter   |   Type    |           Examples            |            Notes             |
|-----------|-----------|-------------------------------|------------------------------|
| fmax      | decimal   | fmax:1.245                    |                              |
| fmin      | decimal   | fmin:1.245                    |                              |
| lat       | decimal   | lat:1.245                     |                              |
| lng       | decimal   | lng:1.245                     |                              |
| chroma    | number    | chroma:-1 chroma:2            |                              |
| diff      | number    | diff:-1 diff:2                |                              |
| dist      | number    | dist:-1 dist:2                |                              |
| quality   | number    | quality:0 quality:3           |                              |
| album     | string    | album:"name"                  | single name with * wildcard  |
| albums    | string    | albums:"South Africa & Birds" | can be combined with & and | |
| camera    | string    | camera:canon                  |                              |
| category  | string    | category:"name"               |                              |
| color     | string    | color:"name"                  |                              |
| country   | string    | country:"name"                |                              |
| day       | string    | day:"name"                    |                              |
| face      | string    | face:"name"                   |                              |
| faces     | string    | faces:"name"                  |                              |
| filename  | string    | filename:"name"               |                              |
| folder    | string    | folder:"name"                 |                              |
| hash      | string    | hash:2fd4e1c67a2d             |                              |
| keywords  | string    | keywords:"name"               |                              |
| label     | string    | label:"name"                  |                              |
| lens      | string    | lens:ef24                     |                              |
| month     | string    | month:"name"                  |                              |
| name      | string    | name:"name"                   |                              |
| original  | string    | original:"name"               |                              |
| path      | string    | path:"name"                   |                              |
| people    | string    | people:"name"                 |                              |
| person    | string    | person:"name"                 |                              |
| state     | string    | state:"name"                  |                              |
| subject   | string    | subject:"name"                |                              |
| subjects  | string    | subjects:"name"               |                              |
| title     | string    | title:"name"                  |                              |
| type      | string    | type:"name"                   |                              |
| uid       | string    | uid:"name"                    |                              |
| year      | string    | year:"name"                   |                              |
| archived  | switch    | archived:yes archived:no      |                              |
| error     | switch    | error:yes error:no            |                              |
| favorite  | switch    | favorite:yes favorite:no      |                              |
| geo       | switch    | geo:yes geo:no                |                              |
| hidden    | switch    | hidden:yes hidden:no          |                              |
| landscape | switch    | landscape:yes landscape:no    |                              |
| live      | switch    | live:yes live:no              |                              |
| mono      | switch    | mono:yes mono:no              |                              |
| panorama  | switch    | panorama:yes panorama:no      |                              |
| photo     | switch    | photo:yes photo:no            |                              |
| portrait  | switch    | portrait:yes portrait:no      |                              |
| primary   | switch    | primary:yes primary:no        |                              |
| private   | switch    | private:yes private:no        |                              |
| public    | switch    | public:yes public:no          |                              |
| raw       | switch    | raw:yes raw:no                |                              |
| review    | switch    | review:yes review:no          |                              |
| scan      | switch    | scan:yes scan:no              |                              |
| square    | switch    | square:yes square:no          |                              |
| stack     | switch    | stack:yes stack:no            |                              |
| stackable | switch    | stackable:yes stackable:no    |                              |
| unsorted  | switch    | unsorted:yes unsorted:no      |                              |
| unstacked | switch    | unstacked:yes unstacked:no    |                              |
| video     | switch    | video:yes video:no            |                              |
| after     | timestamp | after:"2022-01-30 15:23:42"   | taken after this date        |
| before    | timestamp | before:"2022-01-30 15:23:42"  | taken before this date       |
