### ISSUE TITLE
No way to determine where image is from on disk

### ISSUE THREAD

**Issue by guysoft** [photoprism/photoprism#217]
I have somehow imported a folder with images I don't want. And I have no way of figuring it from the UI (or workaround) what folder they are from.
I suggest appending this to the image detail (perhaps if you want this as an admin feature you could limit it only once you have logged in).
This feature is specifically for the Originals folder

**Comment by lastzero** [comment]
We have this in our database, so you could look it up in the files table if you know the `id` or `file_hash`.

Delivering the long awaited edit (and metadata) dialog should probably be next otherwise ;)

**Comment by lastzero** [comment]
Might probably also be in the JSON data of our REST API, if you don't want to connect the database.

**Comment by lastzero** [comment]
Just pushed a new docker image with full password protection, can't work on everything at the same time :)

**Comment by guysoft** [comment]
> Just pushed a new docker image with full password protection, can't work on everything at the same time :)

Not at the same time. Also known as prioritizing.

Ill take a look at the API, then the db.

Perhaps I'll write a client so I can do more complex queries. Perhaps thats the path to extra services and plugins.

**Comment by lastzero** [comment]
That's the reason we're using SQL instead of some hipster NoSQL store. You can use almost any database tool and do a query. No advanced dev skills required, so you don't even need to write a custom client (unless you enjoy doing this).

**Comment by guysoft** [comment]
@lastzero IMHO There is a benefit of implementing an API. Which should enable you to have things like plugins or external services using OwnPhotos. An API is documented, you can have things supporting it etc. You can't expect the app developer, for example, to access your database. That goes for SQL too. You want one thing querying and adding data.

**Comment by lastzero** [comment]
We have an API too, but that requires dev skills, authentication, documentation,... it is made for our UI, not every potential other use case out there. It's different when you are Facebook or Google and the API is public and must be load balanced. There's technically nothing wrong with looking at database tables and writing a SQL query. It is as stable or unstable as the REST API if we change or add fields.

**Comment by guysoft** [comment]
I'll take a look and come back with results. 
I think we both agree and falling in to small details on how to express it. There are benefits not going with fads and having a more well known db system.

**Comment by guysoft** [comment]
Er, what kind of databse is locate at:
``/home/photoprism/.local/share/photoprism/resources/database`` ?

**Comment by lastzero** [comment]
You can use port 4000 or whatever is configured with the MySQL protocol. These files are created by our embedded TiDB, you should not open them directly. That would really be too low level ;)

**Comment by lastzero** [comment]
This is a very first draft for our edit dialog. If you select multiple photos, you can use the prev / next buttons in the toolbar. Feedback welcome!

![Screenshot 2020-01-23 at 17 53 57](https://user-images.githubusercontent.com/301686/73005559-706c6080-3e09-11ea-8d11-811cc821b0e5.png)

**Comment by lastzero** [comment]
Surely will improve the documentation of our development interfaces when we think it's stable. Wish we had more resources, but it's going forward and much cheaper than any company could realize an app like this.

In the files tab, you'll see a list / table with all files that belong to a photo incl sidecar files, RAWs etc

**Comment by lastzero** [comment]
Just pushed my first draft, many fields should already work and you can see the path and file base name (without extension):

![Screenshot 2020-01-24 at 00 53 47](https://user-images.githubusercontent.com/301686/73034033-12a93a00-3e44-11ea-8dac-7b94893f68e5.png)

**Comment by lastzero** [comment]
@guysoft You're free to close this ticket if that solves the issue for now, of course we'll also list all related files in the files tab soon.

**Comment by lastzero** [comment]
Added the Raspberry instructions to docs.photoprism.org:

https://docs.photoprism.org/en/latest/getting-started/raspberry-pi/

Taking a break now, not sure if I can finish files & labels today.

**Comment by lastzero** [comment]
Here's your file list, hope you like it. Sun is coming out, I'll do editing / downloading later or next week, if you're not in a hurry.

![Screenshot 2020-01-24 at 11 29 03](https://user-images.githubusercontent.com/301686/73062670-351b7180-3e9d-11ea-8ec0-4e426e0a776c.png)

**Comment by lastzero** [comment]
Build is running, but Docker Hub had issues recently... uploading new images sometimes fails due to timeouts. Hopefully you can pull a new image soon!

**Comment by guysoft** [comment]
Will probably get time explore Sunday, no rush.

**Comment by lastzero** [comment]
Master build is running, also for ARM64. Just fixed an additional issue with decoding Exif data, see #219.

Maybe I can make some more progress with files and labels today on the train (depending on the internet connection).

**Comment by lastzero** [comment]
This seems to be the most useful information without adding too many columns (column customization could be a feature for a later release if needed):

<img width="947" alt="Screenshot 2020-01-26 at 16 03 00" src="https://user-images.githubusercontent.com/301686/73137191-d51bfb00-4055-11ea-9dee-a6ae4df67ab2.png">

**Comment by guysoft** [comment]
Ok it works!
Took me a while also to figure I need to select the image, then click on the bottom right to enter the edit photo window

**Comment by lastzero** [comment]
Might link the dialog with the title in detail view too.
