### ISSUE TITLE
Database: Error 1205: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by RobHofmann** [photoprism/photoprism#2170]
Hi,

The past few days i've been playing around with Photoprism a bit. I'm trying to load about 75k photos into Photoview. There are two things i'm noticing;
1. After scanning (even complete rescan or doing a clean install; tried multiple times) it only shows ~58k photos & videos. I have no clue what happened to the rest. Is there any place for logs for failed imports?
2. After doing `docker exec photoprism photoprism faces index`, i'm seeing errors after 3 hours. See these logs:
```
<loads of image processings>
time="2022-03-20T02:49:51Z" level=warning msg="index: Error 1205: Lock wait timeout exceeded; try restarting transaction (update counts)"
time="2022-03-20T02:51:05Z" level=error msg="index: Error 1205: Lock wait timeout exceeded; try restarting transaction (update primary files)"
time="2022-03-20T02:51:55Z" level=error msg="Error 1205: Lock wait timeout exceeded; try restarting transaction"
time="2022-03-20T02:51:55Z" level=info msg="indexed 86,135 files in 3h0m45.766240881s"
time="2022-03-20T02:51:55Z" level=info msg="closed database connection"
```
Also note that it seems to crash after 3 hours with a timeout. Is there a way to increase the timeout?
3. I also see a lot of `index: skipped main <filetype> file `. How can I force to take all files (also in a stack).
4. Scanning & facial recognition seems to take a long time. I reckon this would go faster with a NVIDIA GPU, right? But the real question is; does the facial recognition also get better (in terms of matches & quality) with a GPU?

So in short: I'm missing a lot of photos and also a lot of faces are not detected or not matched correctly. I've looked through the options, but can't find any options (other than the facial recognition tweaks) which can help me in the right direction.

Is there anything I can do about this? Looking forward to hear from you.

PS. I am really impressed so far with what i've seen!

**Comment by lastzero** [comment]
https://docs.photoprism.app/getting-started/troubleshooting/performance/#troubleshooting

**Comment by RobHofmann** [comment]
This has a lot of nice best practises (which i've applied), but as far as I understand, it does not answer my questions, right? Sorry if  I dont understand.
