### ISSUE TITLE
Hide "Private" Photos from Thumbnails for People

### ISSUE THREAD

**Issue by mikob** [photoprism/photoprism#2174]
When I go to people, the thumbnail photos that photoprism chooses are sometimes photos I've marked as "private". Ideally I could change the photo that photoprism chooses to represent a person there, or at least photoprism wouldn't use private photos. It seems photoprism chooses the least flattering photos I have of everyone :laughing:

**Comment by lastzero** [comment]
It's a known issue, see related source in `internal/query/covers.go`:

![known-issue](https://user-images.githubusercontent.com/301686/159490263-2df8aff2-76dc-4240-99f4-8bfcb0fc4d59.png)

One of the reasons for this is performance. Right now, you shouldn't tag people in private images if you don't want them to be visible in subject covers. There should be a feature request for a cover selector so you can manually set an image.

**Comment by lastzero** [comment]
see #383

**Comment by graciousgrey** [comment]
For now you find instructions on how to change the subject cover within the database in the comments of https://github.com/photoprism/photoprism/issues/383 :)
