### ISSUE TITLE
Docker: New Debian 12 "Bookworm" base image with FFmpeg 4.4.1 and Darktable 3.8.1

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2178]

**Comment by lastzero** [comment]
Related Pull Requests:

- https://github.com/photoprism/photoprism/pull/2190
- https://github.com/photoprism/photoprism/pull/2193

All development base images in the https://hub.docker.com/r/photoprism/develop repository have been rebuilt after merging these. A new Development Preview image has been pushed to https://hub.docker.com/r/photoprism/photoprism.

**We would very much appreciate it if the community could test if everything works as expected and/or if there are any further issues that should be fixed before a stable release! Thank You :)**

**Comment by jdaviescoates** [comment]
I've no idea really, but would this update help to get photoprism on Cloudron too? https://forum.cloudron.io/post/4813

**Comment by rabotond** [comment]
Tested it on my macbook m1 with docker-compose. 
- UI seems to work fine with all pages
-  Basic functionalities like upload file, download, indexing, create album, face recognition, login, logout all seems to work fine.

I didnt find anything that breaks.
