### ISSUE TITLE
Sharing: The "Like" button must not be visible in shared album views

### ISSUE THREAD

**Issue by rounakdatta** [photoprism/photoprism#2199]
**What does not work as described in the documentation?**

When an album is shared via a sharing link, the user is expected to access the album without logging in. And hence in that case, we expect the Like button to not work. However the Like button is instead present and accidentally clicking it can be a confusing UX.

However I believe this would make sense when we have multi-user support built.

**How can we reproduce it?**

1. Create a sharing link.
2. Open the sharing link via a different browser (where you're not logged into Photoprism).
3. Click the "Like" button for any photo.
4. Get redirected to the login page.

**What behavior do you expect?**

The Like button to be absent on shared links.

**Hardware/Software**

- Raspberry Pi 4 - ARM64
- MySQL
- Linux (DietPi)
- Reproducable on any browser

PS: Huge fan of Photoprism, this is God's work!

**Comment by graciousgrey** [comment]
Good catch :) We found this during working on multi user support. It will be fixed once it is released.

**Comment by 0xmex** [comment]
I would like to challenge this. The like function is crucial for a client area use case in which the client gets sent the share link. The owner/adminthen should not only have the option (maybe a new use case/request?) to restrict downloads of images within this folder, but also to make the like function (the ❤️) working or not. This then can be used as a selection process tool with the ability to download the images as is at the same time already.
