### ISSUE TITLE
Index: SVG, PS and EPS Vector Graphics Support

### ISSUE THREAD

**Issue by djtechonline** [photoprism/photoprism#2207]
I would like to request that SVG support be added to photoprism.  Here is my use-case scenario:

One of my hobbies is crafting with vinyl cutting machines (such as Cricut, Silhouette etc.) to make signs, t-shirts, etc.  Most of the graphics files I use are vector-based because they need to scale cleanly at various sizes.  Most have been purchased from online resources (ie: creativefabrica.com, etsy.com, etc.) or designed in programs such as Adobe Illustrator.   As my image library increases in size, I find it increasingly difficult to navigate through my filesystem (I'm on a Mac) to find and preview these images.  Thankfully, the Mac allows me to preview the files natively, however there is no real way to tag and manage the thousands of images I have in my collection.   

I have searched high and low for an image gallery that would support svg images but I have not yet found anything that can do this.  This is where a program like Photoprism would come into play, as it can already manage and catalog other image types and do it very well.  Adding support for svg files would allow me to categorize, filter and search my growing library of images and make it much easier to find the images I need.  Given that Photoprism is a modern application and that all modern-day browsers have native svg support as well, I don't think it would be too difficult to add this.

I hope this request gets considered into becoming a standard feature of the app in the near future.

**Comment by koverda** [comment]
+1. Any news on .ai and .svg support?

**Comment by graciousgrey** [comment]
@koverda We've recently added support for GIFs. Support for .ai and .svg is not done yet.

Our [roadmap](https://github.com/photoprism/photoprism/projects/5) shows what features are currently being worked on and what's going to be implemented next.

We have a zero bug policy and do our best to help users when they need support or have other questions. Updating and improving the documentation takes up a large part of our time too.

This comes at a price, as we can't give exact deadlines for new features.
 
Having said that, funding really has the highest impact. So users can do their part and [become a sponsor](https://photoprism.app/membership) to get their favorite features as soon as possible :)

**Comment by koverda** [comment]
Got it - i see it in the ideas column.. I was looking for an open source Digital Asset Management solution for me to store images, videos, and vector graphics for my small business, and came across photoprism, seems perfect apart from the lack of vector support. I have no experience in the subtleties of working with vector graphics vs raster graphics as far as software is concerned, so no clue how far away an implementation of this request would be.

**Comment by lastzero** [comment]
Since the use of vector formats is not completely safe, this unfortunately cannot be tested on our demo at the moment.

**Comment by lastzero** [comment]
This is a screenshot of our demo for professional users who may also want to use PhotoPrism for general digital asset management:

![pro-vector-support](https://user-images.githubusercontent.com/301686/218477142-301e0124-f6ab-41ba-92fc-fa1c7e887f8a.jpg)

**Comment by lastzero** [comment]
Today's changes add config options to the Advanced Settings page and update the help texts for some existing options:

![advanced-settings](https://user-images.githubusercontent.com/301686/219965942-72e384e5-25ba-4776-a00a-bb1c4ef06afb.png)
