### ISSUE TITLE
Auth: Support encrypted passwords in addition to plain text 

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#221]
**As an admin, I don't want to use a plain text password in my configuration so that my password can not leak.**

Should be easy to detect if the password is encrypted since Unix passwords typically start with a specific sequence like

`$1$EqkVUoQ2$4VLpJuZ.Q2wm6TAiyYt75.`

Acceptance Criteria:
- [ ] Setting a site password via PHOTOPRISM_ADMIN_PASSWORD also works with (standard unix) encrypted passwords and not just plain text
- [ ] Please add a unit test for this!

**Comment by lastzero** [comment]
Example: https://medium.com/@jcox250/password-hash-salt-using-golang-b041dc94cb72

**Comment by guysoft** [comment]
BTW, current workaround I use is https://github.com/jwilder/nginx-proxy with basic auth.

**Comment by lastzero** [comment]
@guysoft Sure, but we want to get rid of this to simplify installation... should not require many lines of code :)

**Comment by lastzero** [comment]
Should work, maybe somebody can test this with our latest Docker image?

**Comment by guysoft** [comment]
@lastzero I have it with auto-updating (watchtower). Can you explain exactly what you need testing?

**Comment by dennorske** [comment]
I am unable to get standard unix encryption working.
I encrypted it using: `makepasswd --crypt-md5 --clearfrom file`

On latest docker image, built 32 minutes ago from the docker repo.. does that include this change?

**Comment by lastzero** [comment]
From what I see, only bcrypt is supported currently (should start with `$2`). Any specific reason you're using md5?

**Comment by lastzero** [comment]
We're merging and building several times a day, so it should never take more than one or two days for you to get the latest code (unless everyone is on vacation).

**Comment by dennorske** [comment]
My mistake, I don't know why i thought it was MD5. Could be I identified the example hash in this issue to be that. I now saw that the PR #231 has support for bcrypt.

I tested and it worked :+1:

**Comment by lastzero** [comment]
Thank you very much!

**Comment by FoxxMD** [comment]
To clarify: #231 is only for encrypting `admin-password` correct? This does not affect `sql-password` or `database-dsn`?

**Comment by lastzero** [comment]
We can not hash the db password as the app needs to be able to access the database.

**Comment by FoxxMD** [comment]
Thanks for the clarification 👍
