### ISSUE TITLE
Category: Clear and concise title (PLEASE CHANGE)

### ISSUE THREAD

**Issue by hiro5id** [photoprism/photoprism#2213]
Photos seems to be imported upside down, and some times sideways.  Even though I am certain I  did not take the photo upside down.

Here is a sample:
![image](https://user-images.githubusercontent.com/3152718/161109134-8e1cfedd-a2c1-40c5-aa12-05c32ed73676.png)

Orientation appears to be ok?
![image](https://user-images.githubusercontent.com/3152718/161108847-879be066-85f5-4a6b-9f90-2e7007b6b66d.png)

**Comment by graciousgrey** [comment]
Could you send example files to samples@photoprism.app ?
