### ISSUE TITLE
Thumbnails: Reduce default JPEG quality from 92 to 85 to optimize storage and loading

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2215]
**As a new user, I prefer a lower JPEG quality to reduce storage size and load time by default. Users with better hardware and higher quality expectations can increase the settings if needed, but most users will be happy with a lower setting.**

This issue is only for documenting the change. It has already been implemented in 7c58f87c9f2145f1f4c0aef8e0926b1e88729767.

Related Issues:
- https://github.com/photoprism/photoprism/issues/1438
- https://github.com/photoprism/photoprism/issues/860

**Comment by kvalev** [comment]
Hi, what will happen when changing the value for already indexed data? Is the old one purged and recreated or does it only apply for newly indexed data? If its the latter, is there a recommended way to purge the old data?

And one more thing - which artifacts will be affected by this change, meaning where are the jpegs used? Album, Photo, Faces covers?

**Comment by lastzero** [comment]
@kvalev see https://docs.photoprism.app/user-guide/settings/advanced/#advanced-settings

> Changing advanced settings always requires a restart to take effect. Selecting a different thumbnail quality or size won't replace existing thumbnails. You can regenerate them using the [command-line interface](https://docs.photoprism.app/getting-started/docker-compose/#command-line-interface).

All the images you see in the user interface are thumbnails, so basically everything is affected except downloading, sharing, and syncing the originals. Also, the JPEG quality of converted RAW images will be changed if the converter supports setting a quality.
