### ISSUE TITLE
Sharing an album generates localhost link, instead of configured URL

### ISSUE THREAD

**Issue by zolstarym** [photoprism/photoprism#2226]
When I click on share on albums, the link it generates has localhost in it. If I edit out the localhost to the correct external URL and then enter it into a browser, photoprism will redirect again to another localhost URL, making the shared link useless.
I have PHOTOPRISM_SITE_URL configured to what the external URL should be in docker-compose.yml

**Comment by lastzero** [comment]
❤️

**Comment by zolstarym** [comment]
> heart

I guess docker-compose restart doesn't reload the config, but "stop" and then "up -d" does.

**Comment by lastzero** [comment]
Yep, as documented 👍
