### ISSUE TITLE
Videos: Improve hardware transcoding on Synology NAS devices

### ISSUE THREAD

**Issue by sunbeam60** [photoprism/photoprism#2228]
On Synology NAS devices (and [possibly other setups](https://github.com/linuxserver/docker-plex/issues/207), /dev/dri/renderD128 has permissions 'u=rw,g=,o=' and is owned by user "videodriver".

This configuration prevents hardware transcoding using h264_qsv as the VAAPI device cannot be unless the Synology user runs the docker package as root:

> /usr/bin/ffmpeg -qsv_device /dev/dri/renderD128 -i /photoprism/originals/2022/02/27/IMG_8370.MOV -c:a aac -vf format=rgb32 -c:v h264_qsv -vsync vfr -r 30 -b:v 25M -maxrate 25M -f mp4 -y /photoprism/storage/sidecar/2022/02/27/IMG_8370.MOV.avc"
> [SNIP]
> Failed to create a VAAPI device

If the file permissions for /dev/dri/renderD128 inside the container is set to 'u=rw,g=rw,o=rw', PhotoPrism's invocation of ffmpeg with h264_qsv succeeds.

This is a common issue for docker containers using hardware transcoding and it seems the [common pattern it to iterate across the dev/dri/render devices](https://github.com/linuxserver/docker-jellyfin/pull/112/files), ensuring groups have rw rights and adding whatever group the docker's user belongs to as group owners.

**Comment by lastzero** [comment]
Do you know what ID the user videodriver has?

**Comment by lastzero** [comment]
As described in the [release notes](https://docs.photoprism.app/release-notes/), the upcoming preview build includes default user accounts for common user ID ranges (50-99, 500-549, 1000-1099) that belong to the groups `photoprism` (1000), `video` (44), and `render` (109):
- If this does not meet your requirements, we can add other users/groups if you provide us with the specific IDs
- I'd rather not change the permissions for the host device inside a guest container if we can find another solution

**Comment by sunbeam60** [comment]
> Do you know what ID the user videodriver has?

uid=937(videodriver) gid=937(videodriver)
... on my Synology. Whether that's persistent across Synology devices, I shan't say.

Apologies for late response - been away for Easter. Sounds like that's not part of the default range you've proposed.

**Comment by lastzero** [comment]
No, I'm bad at guessing IDs correctly ;)

Now also spending time with my family...

**Comment by lastzero** [comment]
If you find a way to open a terminal to execute commands in the container, you could try this manually first to save us some time / reduce feedback loops.

**Comment by lastzero** [comment]
A new development preview is available. Could you please test it again?

**Comment by sunbeam60** [comment]
Hey, yup will give it a go. On Easter break, so not been in front of keyboard much.

**Comment by sunbeam60** [comment]
Ok, finally had some time to test it and it's mixed news. First of all, I'm running the:preview image - I presume this is where the changes have manifested.

Despite running with ...
> PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"        # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
> PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2"  # Enable TensorFlow AVX2 & Intel Graphics support

... I seem to be going straight to libx264:
> photoprism_1  | time="2022-04-27T13:51:48Z" level=trace msg="/usr/bin/ffmpeg -i /photoprism/originals/2022/04/23/IMG_9926.MOV -c:v libx264 -c:a aac -vf format=yuv420p -max_muxing_queue_size 1024 -crf 23 -vsync vfr -r 30 -b:v 25M -f mp4 -y /photoprism/storage/sidecar/2022/04/23/IMG_9926.MOV.avc"

I was expecting [h264_qsv to be invoked, possibly failing with a an error message](https://github.com/photoprism/photoprism/blob/182bc09d87b86310b076e44a3b6302898cff4efc/internal/photoprism/convert_avc.go#L106), but it seems to go straight to software encoding.

Confused and maybe something I'm missing. [Attaching compose file FWIW](https://github.com/photoprism/photoprism/files/8572998/docker-compose-qsv.txt). github doesn't support yml file attachments, so attaching as text, but also viewable on https://wtools.io/paste-code/bB0u

Is there a way to check the environment set-up without attaching a debugger?

**Comment by lastzero** [comment]
Try "intel" as encoder and PHOTOPRISM_INIT="gpu"

**Comment by sunbeam60** [comment]
That's not made a difference...

> photoprism_1  | time="2022-04-28T23:42:57Z" level=trace msg="/usr/bin/ffmpeg -i /photoprism/originals/2022/04/16/IMG_9740.MOV -c:v libx264 -c:a aac -vf format=yuv420p -max_muxing_queue_size 1024 -crf 23 -vsync vfr -r 30 -b:v 25M -f mp4 -y /photoprism/storage/sidecar/2022/04/16/IMG_9740.MOV.avc"

Happens with following values in compose file:
> PHOTOPRISM_FFMPEG_ENCODER: "intel"        # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
> PHOTOPRISM_INIT: "gpu"  # Enable TensorFlow AVX2 & Intel Graphics support

Force rebuilt from preview:
> image: photoprism/photoprism:preview

... and build-spew indicates it's a very fresh container:
> `admin@NAS:/volume1/docker/photoprism$` sudo docker-compose -f docker-compose-qsv.yml up --force-recreate
> Creating photoprism_photoprism_1 ... done
> Attaching to photoprism_photoprism_1
> photoprism_1  | started 220427 as root (amd64-prod)

Does that look like the right preview?

**Comment by lastzero** [comment]
Do you have sponsor features enabled? In the latest preview, hardware transcoding may be (experimentally) disabled for non-sponsors as we look for ways to reduce our support overhead while providing more benefits to those who support our work.

**Comment by sunbeam60** [comment]
🤦 

I didn't. Now I do. And now it does indeed invoke QSV transcoding.

... but ... (and you're going to love this) ...

There's a typo here: https://github.com/photoprism/photoprism/blob/182bc09d87b86310b076e44a3b6302898cff4efc/internal/ffmpeg/convert.go#L56

Should be "-bitrate", but it's "-itrate" 😆 

So understandably this happens:
> photoprism_1  | time="2022-04-29T15:48:09Z" level=trace msg="/usr/bin/ffmpeg -qsv_device /dev/dri/renderD128 -i /photoprism/originals/2022/04/15/IMG_9661.MOV -c:a aac -vf format=rgb32 -c:v h264_qsv -vsync vfr -r 30 -b:v 25M -itrate 25M -f mp4 -y /photoprism/storage/sidecar/2022/04/15/IMG_9661.MOV.avc"
> [SNIP]
> Unrecognized option 'itrate'.
> Error splitting the argument list: Option not found"

In fact, I'm not sure the -(b)itrate is required, given the -b:v line just above.

**Comment by lastzero** [comment]
Excellent catch! Thanks 💖

**Comment by sunbeam60** [comment]
Should be added, of course, that I still can’t check if the permissions issues on dev/dri/renderD128 has been resolved. Please ping me when a new preview build is out and I’ll give it a whirl.

**Comment by lastzero** [comment]
Fixed the typo and started a new preview build for testing :+1:

**Comment by rgstori** [comment]
@sunbeam60 - did you get hardware transcoding working on intel-based synology eventually? 
I've tried setting 

  - `PHOTOPRISM_FFMPEG_ENCODER: "intel"` and `PHOTOPRISM_INIT: "gpu intel tensorflow"`
  - `devices:` and `- "/dev/dri:/dev/dri"`


but videos aren't transcoding anymore (only cached ones)

would you mind sharing your setup please?
thanks!

**Comment by sunbeam60** [comment]
hey @rgstori - that's pretty similar to what I have and mine works ... but not on a synology, though (I moved to a full Ubuntu Server PC). IIRC, I did get it to work on my NAS, but have since moved to a [full server](https://imgur.com/gallery/swmGedU).

PHOTOPRISM_INIT: "gpu tensorflow"
PHOTOPRISM_FFMPEG_ENCODER: "intel"
devices: 
- "/dev/dri:/dev/dri"

So I don't have "intel" in the _INIT section.

That said, if you enable debug logging in PHOTOPRISM_LOG_LEVEL you can see the command that photoprism invokes then open a session into the container and try to run that manually on that file and see what errors you get, if any.

If you're comfortable opening a session into your Synology, you can try to manually install intel_gpu_top and checking if your QuickSync hardware is actually engaged. Here's my output when PhotoPrism is transcoding a video:

![image](https://github.com/photoprism/photoprism/assets/17337714/10e97a7d-71c5-448f-a9ae-364247f04bfd)

**Comment by bmhj2** [comment]
> @sunbeam60 - did you get hardware transcoding working on intel-based synology eventually? I've tried setting
> 
>     * `PHOTOPRISM_FFMPEG_ENCODER: "intel"` and `PHOTOPRISM_INIT: "gpu intel tensorflow"`
> 
>     * `devices:` and `- "/dev/dri:/dev/dri"`
> 
> 
> but videos aren't transcoding anymore (only cached ones)
> 
> would you mind sharing your setup please? thanks!

I've been trying to get HEVC videos to serve up properly on my photoprism since about three years ago. Brilliant to find this, thanks for posting.

**Comment by lastzero** [comment]
We've created a new legacy image for older operating systems, e.g. running on Synology NAS devices:

- https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=legacy

It is based on Ubuntu Jammy 22.04 LTS, so you should be able to use it with older devices and operating systems. Note, however, that bundled applications and tools such as Darktable and RawThereapee may also be older, so newer file formats (especially for RAW images) may NOT be supported. If you need the latest software, please upgrade your NAS device or use PhotoPrism on a computer with a recent kernel, as we do not have the resources to work around this (also considering that our software is mostly free).

You can test the preview build by specifying the following image name (no final release yet as we are waiting for your feedback):

```
photoprism/photoprism:preview-legacy
```

Our documentation explains how to update the image you are using:

- https://docs.photoprism.app/getting-started/updates/

Related Issues:

- https://github.com/photoprism/photoprism/issues/4339

**Comment by rgstori** [comment]
Thank you! it seems like not all Synology NAS are affected, just the older models. for example, i have kernel v4 on a Synology 720+ - so i imagine i can keep using the regular `latest` image
```
myuser@nas:~$ uname -a
Linux nas 4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024 x86_64 GNU/Linux synology_geminilake_720+
```

it would be good to add the criteria on which image to choose in the docs maybe? e.g. if kernel <3.7, use `-legacy`, otherwise use `latest` ?

**Comment by lastzero** [comment]
Thanks for pointing that out! Glad we haven't named the alternative image "synology" as that might have caused confusion.
