### ISSUE TITLE
UX: Skip RAW files by default when downloading photos and albums

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2234]
**As a user with RAW files, I don't want them to be downloaded by default when I click Download All as I only use JPEGs for sharing.**

This adds a hidden `download.raw = false` setting that you can manually set to true in `settings.yml` until we implement a user interface for it.

Related Code:

- [frontend](https://github.com/photoprism/photoprism/commit/f927c68c4f63d4cb142438a23cf2f2d82c0bd01b#diff-14f844400cf465a5468a8a075414e60fb95ec801a7718c1db885598d64c05f84R545)
- [backend](https://github.com/photoprism/photoprism/commit/f927c68c4f63d4cb142438a23cf2f2d82c0bd01b#diff-90c0cdd28a37d2819e47589e7fa1e1a3e40ed071cd1709a62e6e162c9e5078b5R108)

Related Issues:
- https://github.com/photoprism/photoprism/issues/2227
- https://github.com/photoprism/photoprism/issues/848
- https://github.com/photoprism/photoprism/issues/655
- https://github.com/photoprism/photoprism/issues/449

**Comment by lastzero** [comment]
Started a new preview build for testing:

https://docs.photoprism.app/release-notes/#development-preview

**Comment by lastzero** [comment]
Last commit extends the `DownloadSettings` struct with 4 additional options (evaluated in the front- and backend when starting a download or creating a ZIP file):

- Name: File name pattern for downloaded files (was there before)
- Disabled: Disables downloads
- Originals: Only download files stored in the "originals" folder
- MediaRaw: Include RAW image files
- MediaSidecar: Include metadata sidecar files (JSON, XMP, YAML)

You can change these settings in the `config/settings.yml` file (may require a restart):

```yaml
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: false
  MediaSidecar: false
```

**A user interface will be implemented at a later time, as we currently do not have additional resources available. Thanks for your support and patience!**

**Comment by korikori** [comment]
Hi, for an iPhone user, the default options after this change lead to the following:
 - only download HEIF files;
 - won't download JPEG files. 

Settings the Originals option to `false` brought back the JPEG downlods. If you could add an option to disable HEIF downloads, or add them to the option that disables RAW downloads, that would be great.

**Comment by graciousgrey** [comment]
>  If you could add an option to disable HEIF downloads, or add them to the option that disables RAW downloads, that would be great.

I would rather not include it in disable RAW as HEIF is not a raw format. Feel free to open a new feature request for a disable HEIF download option

**Comment by korikori** [comment]
Thanks for your reply. I don't insist on this option, I only mentioned that as it changed the default behavior for me.
