### ISSUE TITLE
Faces: Option to add people manually to the pictures

### ISSUE THREAD

**Issue by Shadoweee77** [photoprism/photoprism#2242]
**Problem:**

I have a lot of old pictures so I don't blame Photoprism for not tagging people correctly, however it would be nice to have an option to do it manually. It doesn't need to be compared against a database for later automatic tags in my opinion ( since it would most likely mess with the accuraccy ), but having a simple manual tag option would be great.

**Describe alternatives you've considered:**

None, really - I don't expect the program to match faces after fifth indexing magically lol

**Solution from user's perspective:**

It would be great if on the picture's people section we would have a picture that we could manually draw a box on and name it like ususal. I think You could split tagging faces to manual and automatic so it's not a mess with the code and stuff.

Example of UI in paint:
![image](https://user-images.githubusercontent.com/20088126/162928106-7abe1c9c-c330-4d70-9c9b-604a5a980f77.png)

Thanks!

**Comment by graciousgrey** [comment]
That's planned --> https://github.com/photoprism/photoprism/issues/1548 :)
