### ISSUE TITLE
Link to setup instructions not working

### ISSUE THREAD

**Issue by tobmaster** [photoprism/photoprism#226]
In the readme.md is a link to the setup instructions. But on the website the setup page gives a 404. Seems that the build of the page didn't create /setup page while it exists in the repository.

**Comment by lastzero** [comment]
Possible, reorganized our docs yesterdays and asked everyone to report broken links and formatting issues :D

**Comment by lastzero** [comment]
Hopefully fixed now... you're free to close this ticket if you find no more issues. Everyone is also welcome to check if all links on docs.photoprism.org are working and if there are any other issues. Moved content from our wiki to the official documentation yesterday.
