### ISSUE TITLE
Search: Order of results sometimes seems to be wrong when sorting by newest first

### ISSUE THREAD

**Issue by MEGAMENE** [photoprism/photoprism#2265]
**What does not work as expected?**

When using the Newest First Order on the search tab, some pictures end up with the wrong order.
The same doesn't happen when using the Oldest First Order.
I've also noticed that the API endpoints return the wrong order with the order=newest, if the order is by TakenAt.

**How can we reproduce it?**

Here are the steps to reproduce the bug.

1. On the Search tab choose Newest First Order in the search options.
3. Look at the photos and/or the endpoint and see if every photo is ordered by TakenAt.
4. On the Search tab choose Oldest First Order in the search options.
5. Do the same thing as the 2nd step.
6. Compare the orders from Newest First and Oldest First, they should be mirrored but that's not what's happening.

The bug is visible on the demo page.
The last photo while using the Newest First Order has the date of July 6, 2002 and the one before that as the date Mar 12, 2002.
 
**What behavior do you expect?**
 
The images to be ordered by TakenAt, Newest First and Oldest First to be mirrored.

**What version you are using?**

Build 220416-73be4df8-Linux-AMD64

**On what kind of device is PhotoPrism installed?**

Photoprism is running on a Unraid server, I'm accessing the website using the latest version of Chrome.

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

Reverse Proxy (Nginx).

**Comment by lastzero** [comment]
They were previously sorted by UTC and are now sorted by local time, which is an experiment as some users have told us this is better for them. If the order is completely chaotic, you may need to re-index, as we added a new index for that.

**Comment by MEGAMENE** [comment]
My instance of Photoprism is new, I literally just ran the reset command a couple of hours ago.
The order is not completely chaotic, it's just some that are out of place.
See the image I attached for an example:
![example](https://user-images.githubusercontent.com/7219991/163870315-027c3e9e-b957-41e6-b352-f734bfc7ef9c.png)

**Comment by lastzero** [comment]
Interesting...
- which database? 
- could you give us some guidance on how to reproduce the problem, perhaps on our demo?
- did it happen only after you changed the dates, so the index wasn't updated properly?

It is necessary that we can reproduce the problem to fix it.

**Comment by MEGAMENE** [comment]
Yes, of course.
I'm using the default sqlite database.
I've made a short video of me encountering the bug in the demo website, I've attached it to this post.
I didn't change any dates, the metadata is the default one from the images files.

https://user-images.githubusercontent.com/7219991/163879397-b00c8bf8-af6b-4e52-b128-79426dffc023.mp4

**Comment by lastzero** [comment]
Because I haven't observed this with MariaDB, I assume something is wrong with this query (probably `CAST(photo_taken_at AS UNSIGNED)` doesn't do what I thought):

https://github.com/photoprism/photoprism/blob/develop/internal/entity/file.go#L152

As I am now spending time with my family, this is a great opportunity for contributors to help:
- The general idea is to sort all files by time (DESC) and importance (primary JPEGs should come first).
- A first step would be to look in the SQLite docs or just try the query and see if that explains the incorrect order.
- Then figure out how to write the query correctly.

**Comment by lastzero** [comment]
As expected, `CAST(photo_taken_at AS UNSIGNED)` casted the timestamp to a simple year only on SQLite, e.g. `2022`.

The experession 
- `strftime('%Y%m%d%H%M%S', photo_taken_at)`

now casts it to

- `YYYYMMDDhhmmss`
 
as on MariaDB, e.g. `20220131180659`

**Comment by lastzero** [comment]
A new development preview is available. Could you please test it again?

**Comment by MEGAMENE** [comment]
> A new development preview is available. Could you please test it again?

I just tested it again with the new development preview, and it's working properly now.
Good Job 👍, thanks.
