### ISSUE TITLE
Metadata: Option to not create keywords from folder names when indexing photos

### ISSUE THREAD

**Issue by gittygitnice** [photoprism/photoprism#2270]
**Is your feature request related to a problem? Please describe.**

Let's say I have several photos in a folder with the name "giraffe". In some of those a giraffe is pictured and they are correctly tagged with "giraffe" (with a different program). When I now index the pictures, PhotoPrism automatically assigns to every picture the keyword "giraffe" because they are located in the folder named "giraffe". This makes it impossible later on to search for only those photos which originaly had the tag "giraffe" assigned, since _every_ photo from the folder "giraffe" now shows up in the search results.

**Describe the solution you'd like**

It would be great to have the option in "settings" to tell PhotoPrism to not create keywords from folder names when indexing the photos.

**Describe alternatives you've considered**

An alternative would be to allow for an option to only lookup original keywords during a search. In PhotoPrism this metadata category, where the original tags are kept, seems to be labeled "subject". (While wearing the same name, this metadata category is not to be confused with the subject/person search of PhotoPrism.)

**Additional context**

Thanks!

**Comment by Dulanic** [comment]
Not a bad ask, I have run into this many times and I'm like why does this have this label only to realize it was the folder name.

**Comment by melyux** [comment]
Is this related to #745?

**Comment by graciousgrey** [comment]
Good catch! I will close this as duplicate in favor of #745
