### ISSUE TITLE
Library: Display RAW previews and the number of actual files in Originals

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2273]
**As a user who enjoys browsing his/her files in Library > Originals, I would like to see a preview (JPEG thumbnail) for RAW files and the actual number of original files in the navigation so I can compare them better.**

![originals](https://user-images.githubusercontent.com/301686/164544594-0f40d890-fb32-459f-9528-b82e64b71a6e.jpg)

**Comment by rabotond** [comment]
I tested it and seems to work fine. Samsung S21 raw footage.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/8861905/165565331-f121f763-4ca6-494a-b8b5-4d7f0dae988b.png">

**Comment by lastzero** [comment]
Thanks for testing!
