### ISSUE TITLE
PhotoPrism Unraid Docker Error: FATAL ERROR: Creation of the user's processing profile directory "/photoprism/.config/RawTherapee/profiles" failed!

### ISSUE THREAD

**Issue by PitRejection2359** [photoprism/photoprism#2278]
Hi,

I'm running the PhotoPrism docker on Unraid (as prepared by Ich777), and the error I get for all my DNGs is:

time="2022-04-22T22:31:27+01:00" level=warning msg="index: failed converting '[filename].DNG' to jpeg (\nFATAL ERROR:\nCreation of the user's processing profile directory "/photoprism/.config/RawTherapee/profiles" failed!\n\n)"

Ich777 suggested deleting the docker and adding the variable HOME (as described [here](https://forums.unraid.net/topic/83786-support-ich777-application-dockers/?do=findComment&comment=1118607)), but that didn't work, with exactly the same result.

**Comment by Tschucker** [comment]
I just tried the docker container with the preview tag since I was getting the same issue with the one in the unraid template, and this was abel to convert my Leica DNG files

**Comment by PitRejection2359** [comment]
OK - I'm not really conversant with creating my own docker containers in unraid - might be something I have to look into. I wonder if Ich777 can create an option for the preview version within his existing container.

**Comment by ich777** [comment]
@PitRejection2359 I only created the template for PhotoPrism for Unraid, simply change the Repository in your Docker template from `photoprism/photoprism` to `photoprism/photoprism:preview` if you want to use the `preview` branch.

**Comment by PitRejection2359** [comment]
ideal - thank you.

**Comment by ich777** [comment]
@lastzero I think this can be closed.

Do you have maybe some insight why this is happening? I think when the `preview` branch is merged into `latest` this will be fixed anyways...

**Comment by PitRejection2359** [comment]
Should I remove the "Home" variable as well as changing to the Preview - or will I need to keep the Home variable as well as changing to the preview?

**Comment by PitRejection2359** [comment]
I left the home variable and it works fine - will try removing it and see if it still works.

**Comment by PitRejection2359** [comment]
seems to work fine without it too.

**Comment by ich777** [comment]
@PitRejection2359 can you close this issue if everything is working?

**Comment by PitRejection2359** [comment]
Fixed in preview version. Thanks for all the help.
