### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by savegame** [photoprism/photoprism#229]
i like your project, and want help. How can i add Russian translation to your frontend? I am already fork you project and start creation of `frontend/src/resources/ru.po` file, but what i should do next?

**Comment by lastzero** [comment]
@graciousgrey can help you! She's working full-time in another project so it might take a day for her to answer. You'll also find her in our Gitter community chat.

**Comment by graciousgrey** [comment]
Hi @savegame we do the translations like this:
1) Go to /frontend run `npm run gettext-extract`
2) This will create a translations.pot file in `frontend/src/resources` --> we open this file in a translation editor (e.g. https://poedit.net/) and create a .po file in `frontend/src/resources`
3) To compile the .po file into our translations.json run `npm run gettext-compile`

In case you already created your .po file you just need to run the compile command and push the changes :)
