### ISSUE TITLE
Sharing: WebDAV Uploads should include Videos, Months, States, and Moments

### ISSUE THREAD

**Issue by inakrin** [photoprism/photoprism#2293]
Using the photoprism:preview docker image
1. Go to any folder or album which contains videos
2. Select the contents of that folder
3. Click share in the bottom right menu
4. After uploading in the destination folder on the webdav server only the JPG previews are present, not the videos as expected

**Comment by graciousgrey** [comment]
Good catch, that's already on our list and the reason why we have not released the preview yet  ;) Besides videos, raws are also not included in manual webdav uploads.
