### ISSUE TITLE
Gamification of development process

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#23]
It would be nice to give out little perks for contributing to this project like Amazon vouchers. Or at least virtual badges based on points collected. Seems like an interesting experiment.

**Comment by jkomyno** [comment]
You mean something like StackOverflow's badges or Github's (and Digitalocean) Hacktoberfest?

**Comment by lastzero** [comment]
@jkomyno Yes, or Lufthansa Miles & More ✈️

**Comment by lastzero** [comment]
We should certainly offer more issues for Hacktoberfest this year!

I'll close the ticket for now...
