### ISSUE TITLE
People: Sort people dropdown by confidence level by default

### ISSUE THREAD

**Issue by IeuanK** [photoprism/photoprism#2305]
**Is your feature request related to a problem? Please describe.**

When (re)assigning recognized faces to a person, the dropdown is sorted in a way that often does not put the best results at the top.

**Describe the solution you'd like**

I think it would be a major improvement to scan the face against known people and then sort this dropdown by confidence. Once you start typing, revert to the current behavior for search results.

**Additional context**

![CleanShot 2022-05-06 at 21 13 03](https://user-images.githubusercontent.com/1075598/167203480-10d27640-b9f2-46f9-ad37-899005b81b0e.png)

**Comment by graciousgrey** [comment]
Yes, this is something that can be improved, but we need to take care of performance:

Somehow related to: https://github.com/photoprism/photoprism/issues/1865

**Comment by IeuanK** [comment]
@graciousgrey Thanks for that, I somehow missed that issue in my search. I will close this one in favor of that one.
