### ISSUE TITLE
File types: .livp Support

### ISSUE THREAD

**Issue by cibimo** [photoprism/photoprism#2312]
https://support.apple.com/en-us/HT207310

**Comment by lastzero** [comment]
Live Photos should generally work, we have examples on our public demo.

**Comment by cibimo** [comment]
> Live Photos 通常应该可以工作，我们在公开演示中有示例。

I downloaded the live photo from alicloud disk backup and the suffix is .livp. Put it into the import folder and it cannot be imported automatically. You need to change the suffix to .HEIC.
In addition, I found that files in webp format cannot be imported.

**Comment by lastzero** [comment]
WebP is only supported in our development preview. While live photos are supported, the livp extension is currently not:

https://photoprism.app/kb/file-formats

Where can we get samples or a document describing what specific container and codecs may be contained in such a file and why Apple did not (continue) to use a standard extension?
