### ISSUE TITLE
Library: Multiple separated libraries

### ISSUE THREAD

**Issue by amigthea** [photoprism/photoprism#2317]
**Describe the solution you'd like**

I would like to be able to separate originals content in different libraries so that when I go to the Calendar or Labels section the original contents do not get merged together

**Describe alternatives you've considered**

Folder separation is not enough

**Comment by graciousgrey** [comment]
See: https://github.com/photoprism/photoprism/issues/98 :)

**Comment by amigthea** [comment]
Hi @graciousgrey, thank you for joining the discussion. It's sad to see this closed so fast, the issue you're linking me is not what I asked help for, I do not need a separate accounts but separate libraries inside tha same profile. Can this be opened again?

**Comment by graciousgrey** [comment]
@Azertooth I closed it as duplicate as the requested functionality will be part of the issue that is already on our roadmap.
The possibility to have multiple libraries with a separate index on one PhotoPrism installation will be part of multi user. 
It should then also be possible that one user has access to multiple libraries, which is what you described :)

**Comment by amigthea** [comment]
As long as having multiple users will not be mandatory to have separated library index it will be perfect! thank you for the assistance


________________________________
Da: Theresa Gresch ***@***.***>
Inviato: mercoledì 11 maggio 2022 14:17
A: photoprism/photoprism
Cc: Azertooth; Mention
Oggetto: Re: [photoprism/photoprism] Library: Multiple separated libraries (Issue #2317)

@Azertooth I closed it as duplicate as the requested functionality will be part of the issue that is already on our roadmap.
The possibility to have multiple libraries with a separate index on one PhotoPrism installation will be part of multi user.
It should then also be possible that one user has access to multiple libraries, which is what you described :)
