### ISSUE TITLE
Library: You cannot batch modify the shooting time after multiple selections

### ISSUE THREAD

**Issue by cibimo** [photoprism/photoprism#2323]
Some photos are taken at the wrong time, but it's too troublesome to modify them one by one.
Modifying after multiple selections will only modify the first selected one.

**Comment by lastzero** [comment]
Until batch editing is implemented, you will need to rely on external tools and apps:
- #271

If you sign up as a sponsor, we can provide this feature faster: https://photoprism.app/membership
