### ISSUE TITLE
Docker: opensuse repo for darktable has invalid signature

### ISSUE THREAD

**Issue by cameronetchart** [photoprism/photoprism#2327]
My system: x86 ubuntu server 22.04 LTS running latest docker and stable photoprism docker

Problem: when you initiate with the "gpu" setting, the opensuse repo for darktable/Debian_11 has an invalid signature which I believe is causing it to not install (although I don't use darktable in my installation).

Log:

> init as root
> init gpu...
> make: Entering directory '/opt/photoprism/scripts'
> ./install-gpu.sh
> Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
> Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
> Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
> Get:4 http://deb.debian.org/debian bullseye-backports InRelease [44.2 kB]
> Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [146 kB]
> Get:7 http://download.opensuse.org/repositories/graphics:/darktable/Debian_11  InRelease [1517 B]
> Get:8 http://deb.debian.org/debian bullseye/non-free amd64 Packages [93.8 kB]
> Get:9 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
> Get:10 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/debian bullseye InRelease [4637 B]
> Get:6 https://downloads.mariadb.com/Tools/debian bullseye InRelease [2164 B]
**_> Err:7 http://download.opensuse.org/repositories/graphics:/darktable/Debian_11  InRelease
>   The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>_**
> Get:11 http://deb.debian.org/debian bullseye/contrib amd64 Packages [50.5 kB]
> Get:12 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
> Get:13 http://deb.debian.org/debian bullseye-backports/non-free amd64 Packages [11.0 kB]
> Get:14 http://deb.debian.org/debian bullseye-backports/main amd64 Packages [269 kB]
> Get:15 http://deb.debian.org/debian bullseye-backports/contrib amd64 Packages [4704 B]
> Get:16 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye InRelease [6387 B]
> Get:17 https://downloads.mariadb.com/Tools/debian bullseye/main amd64 Packages [1246 B]
> Get:18 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/debian bullseye/main amd64 Packages [36.7 kB]
> Get:19 https://dlm.mariadb.com/repo/mariadb-server/10.6/repo/debian bullseye/main arm64 Packages [30.0 kB]
> Get:20 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye/main arm64 Packages [1426 B]
> Get:21 https://dlm.mariadb.com/repo/maxscale/latest/apt bullseye/main amd64 Packages [1426 B]
> Reading package lists...
> _**W: GPG error: http://download.opensuse.org/repositories/graphics:/darktable/Debian_11  InRelease: The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
> E: The repository 'http://download.opensuse.org/repositories/graphics:/darktable/Debian_11  InRelease' is not signed.
> make: *** [Makefile:20: gpu] Error 100**_
> make: Leaving directory '/opt/photoprism/scripts'
> image: amd64-prod, build 220302-bullseye
> home: /photoprism
> umask: "0002" (u=rwx,g=rwx,o=rx)
> install-path: /opt/photoprism
> running as uid 0
> /opt/photoprism/bin/photoprism start
> time="2022-05-17T01:08:42Z" level=info msg="PhotoPrism® needs your support!"
> time="2022-05-17T01:08:42Z" level=info msg="Visit https://docs.photoprism.app/funding/ to learn more."

Steps:

1. Install using docker and PHOTOPRISM_INIT: "gpu" env variable
2. resulting error log occurs

**Comment by lastzero** [comment]
Our latest release (available very soon) uses the packages provided by Debian, so this should no longer be a problem.

**Comment by cameronetchart** [comment]
Great, thanks! Just noticed this is also causing the gpu drivers to not be installed, breaking quick sync transcoding. Glad to hear it's fixed soon.

**Comment by lastzero** [comment]
Updated the package source in our install script :+1:
