### ISSUE TITLE
Exclude a folder from the Originals folder scan

### ISSUE THREAD

**Issue by guysoft** [photoprism/photoprism#233]
I have on my device a folder: ``.thumbnails``. I want to exclude it. From the import sequence.
Any ideas how to do that?
I could add a ``.photoprisimignore``  file. Or list it somewhere.

**Comment by guysoft** [comment]
I am excluding the whole folder tree as a workaround. So this is low priority for me

**Comment by lastzero** [comment]
or maybe `.ppignore` or just `.ignore` - good idea!

**Comment by lastzero** [comment]
Master build is running, new Docker images available soon. Add a `.ppignore` file to your originals directory or any sub directory. It will also work in import if needed.

File names / patterns in `.ppignore` will be ignored in all sub directories as well but should not be ignored in other directories (siblings, parent directories).

Example (regular expressions are NOT supported):
```
@eadir
beach*
*.xml
preloader.gif
```
