### ISSUE TITLE
Delete records of files deleted in the file system from the database

### ISSUE THREAD

**Issue by savegame** [photoprism/photoprism#234]
I try share (just mount to this folder my existing photos folder from local network) my photos folder to Originals/MyPhotos, and indexing it (this photo folder are shared to nextcloud and samba on my local network,  just for working with same files from different services)... 
but when i delete files/photos from this folder, photoprism still try load it and show. Is photoprism can delete not existing files from index DB?
sorry for my english )

**Comment by savegame** [comment]
now i just remove ~/.local/share/photoprism/database and indexing Originals again

**Comment by lastzero** [comment]
We'll change the code so that deleted photos stay "deleted", not that deleted means archived for us. There is no permanent delete for now. If you want to start with a fresh collection, you should delete the complete database.

**Comment by tmb80c** [comment]
> 
> 
> now i just remove `~/.local/share/photoprism/database` and indexing Originals again

I ran into the same issue, unfortunately deleting the database means that all created albums, manual title and label adjustments are getting lost right? Sure we are still in beta and there is a warning that we may need to delete the database from time to time. Nevertheless the developers may want to consider a backend maintenance function to find and eliminate orphans.

**Comment by lastzero** [comment]
This is something our planned "groom" command could do, but we didn't get to that yet. Photos should automatically be marked as missing, if you try to load them and they are not there.

When you move photos, the regular "index" command should notice it and just change the path in our database.

Note that we have to be VERY careful with permanently deleting database entries as well as files. Files might also not be there for a moment because a network connection is not available.

**Comment by tmb80c** [comment]
> Note that we have to be VERY careful with permanently deleting database entries as well as files. Files might also not be there for a moment because a network connection is not available.

Absolutely correct ! This morning I recognized that I forgot to permanently mount a shared smb folder in Originals, so a full automatic removal through a reindexing would have created new issues.  Therefore I recommended a semi automatic solution for the backend cli as a kind of maintenance command.

**Comment by lastzero** [comment]
Shall we name the command `photoprism purge`?

**Comment by tmb80c** [comment]
> 
> 
> Shall we name the command `photoprism purge`?

"purge" sounds good and consistent with the current command list

"scan" could also work in particular in case you want to implement a bit safer approach were you distinguish different maintenance tasks in the future 

Not sure if in the longrun parameters would be needed like: 
scan (without parameter just lists inconsistencies to avoid that someone purges while forgot to mount a drive)
scan --purgeorphans (removes links to deleted pictures in Originals from database)
scan --purgelabels or purgekeywords (not sure if lables or imported keywords can exist which are no longer used)
scan --purgeall
....

**Comment by lastzero** [comment]
Sorry, didn't get to this. We're on vacation next week, any contributions welcome. Basically you need to create a new command and loop through all files in the database and check if they are still there. Same for labels: Check if they are assigned to one or more photos and delete otherwise.

**Comment by BeneKenobi** [comment]
_Something_ created a second set of JPEGs for my raw files (one set with uppercase extension, one with lowercase). I deleted the uppercase ones with a script but now I have a database full of missing images. A `purge` command would be very helpful.

**Comment by lastzero** [comment]
You are right, this was a bug I also experienced myself because our development computers are Macs with case-insensitive file systems whereas Linux is case-sensitive, so tests lead to different results. Fixed it 8 days ago (f43154b).

**Comment by lastzero** [comment]
Docker build is running, new images available soon (less than one hour). You're welcome to test and provide feedback!

**Comment by BeneKenobi** [comment]
How do I trigger the `purge`? Via shell or also by reindexing (with or without `Complete Rescan` checked)?

**Comment by lastzero** [comment]
Get the latest Docker image, also pushed a fresh ARM64 image a minute ago.

You don't need the "complete rescan" option. However, when you limit indexing to a certain directory, only that directory will be scanned for added, updated and removed files. Purge will automatically run when the indexer is done with adding / updating files, so that those files don't need to be checked again. Added that optimization this morning.

**Comment by lastzero** [comment]
Note that I also updated our Docker and Docker Compose docs to reflect the latest changes and improvements: https://docs.photoprism.org/en/latest/getting-started/docker-compose/

**Comment by lastzero** [comment]
In addition, you can run `photoprism purge` and `photoprism purge --dry` (for testing) in a terminal as described in the docs. This will not add and update files, only remove missing. There's also a `--hard` option to remove all related data from the database, it's not extensively tested though (help welcome).

**Comment by lastzero** [comment]
A special situation could be when you remove primary files (JPEGs), so that a media file (e.g. RAW) has no primary file anymore. Running the indexer again should fix it though, if not we need to fix it. Testing all possible scenarios is a lot of work, the help of our community is much appreciated!

**Comment by lastzero** [comment]
Just pushed additional improvements for edge cases as mentioned above. Docker build is running, new image available within the next hour.

**Comment by lastzero** [comment]
Fixed, see #292
