### ISSUE TITLE
BUG: HEIC images are rotated while converted to JPEG

### ISSUE THREAD

**Issue by xplosionmind** [photoprism/photoprism#2343]
**What does not work as described in the documentation?**

Some HEIC images are rotated of 180° while converting to JPEG.

**How can we reproduce it?**

1. Upload a bunch of HEIC images
2. Run the indexing
3. in the gallery, the JPEG converted image appears as rotated of 180°

In my library I have ~600 pictures, that I both uploaded through the web uploader and a WebDAV connection. Some pictures are in JPEG, most in HEIC. Videos are in MOV.

**What behavior do you expect?**

Pictures to be converted without any substantial change.

**What could be the cause of your problem?**

The conversion engine having some bug.

**Can you provide us with example files for testing, error logs, or screenshots?**

- [Original HEIC image](https://cloud.tommi.space/s/5E5wgnSRzmQoCxK) (appears to be rightly oriented)
- [Converted JPG image](https://cloud.tommi.space/s/ST9Mx99kzEqmXer) (appears to be rotated)

![Screen Shot 2022-05-21 at 9 30 05 AM](https://user-images.githubusercontent.com/42862428/169641322-fb895dea-f56e-4bc7-9c0d-ee210423bfda.jpg)
![Screen Shot 2022-05-21 at 9 31 04 AM](https://user-images.githubusercontent.com/42862428/169641323-30914e88-1fc9-4631-ab5c-67e2d989e5cf.jpg)
![Screen Shot 2022-05-21 at 9 31 21 AM](https://user-images.githubusercontent.com/42862428/169641324-798ef0d5-c428-4675-86df-f264dd59296b.jpg)

**Which software versions do you use?**

- PhotoPrism Architecture & Build Number: [Build 220517-42020829-Linux-AMD64](https://docs.photoprism.app/release-notes/)
- Database Type & Version: hosted on 
- Operating System Types & Versions (Linux, Windows, Android,...)
- Browser Types & Versions: any
- Browser Plugins & Ad Blockers: N/A

**On what kind of device is PhotoPrism installed?**

- Hosted on PikaPods, 2 cores
- Physical Memory & Swap Space: 500GB
- Storage Type: ?
- RAM: 8GB

**Comment by lastzero** [comment]
Sorry this is still a problem for you, I was sure it's generally fixed and other users confirmed it. Might be something server/config specific? Need to figure this out, so sadly no easy answer/quick solution.

**Comment by xplosionmind** [comment]
I understand. Thank you!

Might this be related to the uploading way?

Since the hosting is PikaPods, I have less control on the server, therefore unfortunately I can do very little more to help you.

**Comment by graciousgrey** [comment]
> Might this be related to the uploading way?

Rather not.

We can reproduce the issue and will have a closer look at this next week. We'll keep you updated!

**Comment by graciousgrey** [comment]
This should be fixed with version 220524. 

Newly added HEICs should get the correct rotation.

For existing ones that have a JPG with the wrong rotation you can unstack the HEIC file. This way a new JPG will be generated. Then delete the JPG with the wrong rotation.
