### ISSUE TITLE
Errors during import: Error 1366: Incorrect int value: '' for column 'location_id' at row 1"

### ISSUE THREAD

**Issue by twatzl** [photoprism/photoprism#236]
Hello, 

so I am currently experimenting with import from a WebDAV directory (Nextcloud) and during indexing I get the following errors and in the UI I get the message "no images found" 

Is this a Photoprism issue or probably related to my setup/Nextcloud/WebDAV access rights?

```
photoprism_1  | time="2020-01-28T21:30:35Z" level=info msg="index: failed related jpg file \"2019-05-30_31_going_home/2019-05-31_014_thumb.JPG\""
photoprism_1  | time="2020-01-28T21:30:48Z" level=warning msg="file: no latitude and longitude in metadata"
photoprism_1  | time="2020-01-28T21:30:48Z" level=info msg="index: changed empty photo title to \"Unknown / 2019\""
photoprism_1  | time="2020-01-28T21:30:48Z" level=error msg="index: Error 1366: Incorrect int value: '' for column 'location_id' at row 1"
photoprism_1  | time="2020-01-28T21:30:48Z" level=info msg="index: failed related jpg file \"2019-05-30_31_going_home/2019-05-31_015_thumb.JPG\""
photoprism_1  | time="2020-01-28T21:30:56Z" level=warning msg="file: no latitude and longitude in metadata"
photoprism_1  | time="2020-01-28T21:30:56Z" level=info msg="index: changed empty photo title to \"Unknown / 2019\""
photoprism_1  | time="2020-01-28T21:30:56Z" level=error msg="index: Error 1366: Incorrect int value: '' for column 'location_id' at row 1"
photoprism_1  | time="2020-01-28T21:30:56Z" level=info msg="index: failed main jpg file \"2019-05-30_31_going_home/2019-05-31_016.JPG\""
photoprism_1  | time="2020-01-28T21:31:02Z" level=warning msg="file: no latitude and longitude in metadata"
photoprism_1  | time="2020-01-28T21:31:02Z" level=info msg="exif: taken at 2019-05-31 11:19:56 +0000 UTC"
photoprism_1  | time="2020-01-28T21:31:02Z" level=info msg="index: changed empty photo title to \"Runway / 2019\""
photoprism_1  | time="2020-01-28T21:31:02Z" level=error msg="index: Error 1366: Incorrect int value: '' for column 'location_id' at row 1"
```

Update: I just tried uploading an image through the UI and realized that I don't have write permissions to the Import folder. I set Photoprism to read only mode however, so I am not yet sure  if it is a directory issue or Photoprism rejects uploads in read only mode.

If the problem is a lack of permissions then there should be a more informative error message during indexing.

I will check this and update this issue.

**Comment by lastzero** [comment]
We don't have your use case covered yet, import is for moving files right now as the command help explains.

We'll implement native WebDAV support that doesn't move but copy files.

**Comment by twatzl** [comment]
I found the issue already. Seems as if I had an outdated version of the database or something. After removing the volumes and restarting using compose the import worked.

```
$ docker container rm photoprism-compose_photoprism_1 
$ docker volume rm photoprism-compose_photoprism-cache         
$ docker volume rm photoprism-compose_photoprism-database
```

**Comment by TimoJohn** [comment]
I still suffer the same error. 
Here it looks like it is related to some strange unicode cracters in the EXIF tags:

ImageDescription - Aussuchen des Kleides f�r die Hochzeit von Alex und Kristin 20.07.2007

The � character seems to cause the issue.  Sure this is not a great MetaData Quality ... 


![image](https://user-images.githubusercontent.com/23238730/120782440-49a85900-c52a-11eb-8fb4-f359922d3f95.png)

**Comment by graciousgrey** [comment]
@TimoJohn what exactly is your use case?
Are you trying to import the photo from nextcloud and it doens't show up in photoprism?
Can you send us an example file for testing (hello@photoprism.app)

**Comment by lastzero** [comment]
Looks like an issue we already solved in the chat... either the encoding in the file had issues, or the default database character set was wrong?

Please make sure to use an example config file from https://dl.photoprism.org/docker/ or run MySQL / MariaDB using the following parameters for proper unicode support:

mysqld --transaction-isolation=READ-COMMITTED --character-set-server=**utf8mb4** --collation-server=**utf8mb4_unicode_ci** --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50

**Comment by TimoJohn** [comment]
My Issue occurred during the import / scan process. 
I guess that the file has issues as well.  
I can test this again after holidays and valildate configuration file in docker compose.  I will come up with new reply.
For now I repaired all my local files containing � ...
