### ISSUE TITLE
UX: Mobile navigation toolbar menu must be accessible in public mode

### ISSUE THREAD

**Issue by spidiracer** [photoprism/photoprism#2370]
Hello,

I worked with Michael Mayer yesterday and we discovered that while in public mode the three dot navigation option is not present on mobile browsers. Would like to update the code to have that navigation available so that users can upload photos from their mobile browser while in public mode similar to how its setup on the desktop browsers.

**Comment by lastzero** [comment]
Our preview build and demo have been updated. The menu is visible in public mode now, consumes less space, and has a more colorful design. Would you be able to test this and give feedback? 🤗

![Screenshot_20220528_164314](https://user-images.githubusercontent.com/301686/170830530-f23961ee-1abb-4ae6-b279-833e7a0bebe9.jpg)

**Comment by lastzero** [comment]
Here is another screenshot with the Grayscale theme. It was just released. Hope it works for you! :+1: 

![mobile-grayscale-submenu](https://user-images.githubusercontent.com/301686/170843463-f92b15d7-723e-4a35-bbab-81513991f0a1.png)

**Comment by spidiracer** [comment]
Hi Michael,

I'm running the demo mode and it works great! Thanks again for the quick
turn around on this :)

Travis Wilson
