### ISSUE TITLE
MariaDB Change in Latest Update

### ISSUE THREAD

**Issue by simoncoul** [photoprism/photoprism#2382]
Hello,

My unraid system was showing a lot of instability due to my docker image filling up. I tracked it down to the MariaDB log file that was increasing at ~1GB a day. It keeps giving these two errors repeatedly:

2022-05-30 11:40:36 320 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').

2022-05-30 11:40:36 320 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).

I am wondering if there was a change to photoprism or if something was changed on the offical MariaDB docker image.

Thanks
Sikmon

**Comment by gyto6** [comment]
You're not alone. As an Unraid user too, my MariaDB docker display the same message.

But once I stop my NextCloud docker, the logs stops.

Check this command in MariaSQL to get rid of it.

`mysql_upgrade --user=root --password=<root_pwd>`

**Comment by lastzero** [comment]
Does your docker-compose.yml include these environment variables for the mariadb service as shown in our example on dl.photoprism.app? 

```
environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
```

**Comment by gyto6** [comment]
> Does your docker-compose.yml include these environment variables for the mariadb service as shown in our example on dl.photoprism.app?
> 
> ```
> environment:
>       MARIADB_AUTO_UPGRADE: "1"
>       MARIADB_INITDB_SKIP_TZINFO: "1"
> ```

It doesn't concerning to me...

I'm setting them by now.

**Comment by simoncoul** [comment]
The container template did not have those variables. I manually added both, restarted Maria and Photoprism however it is still throwing the same error in Maria.

**Comment by gyto6** [comment]
> The container template did not have those variables. I manually added both, restarted Maria and Photoprism however it is still throwing the same error in Maria.
> 
> I've attached the template, perhaps there is something else missing? [unraid_container_template.pdf](https://github.com/photoprism/photoprism/files/8806301/unraid_container_template.pdf)

The variables must be added to MariaDB container, not Photoprism.

**Comment by lastzero** [comment]
The MariaDB troubleshooting guide in our docs has been updated to include more detailed instructions:

- https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#version-upgrade
- https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#incompatible-schema

**Comment by simoncoul** [comment]
@gyto6 Thank you. Adding the variables to the MariaDB container fixed the issue.

@lastzero Thank you for updating the documentation.

**Comment by lastzero** [comment]
We found a few more places in our docs that needed updating... let us know if anything is still unclear or missing! :+1:
