### ISSUE TITLE
[Docker] configuration files are not created if .config directory is a volume

### ISSUE THREAD

**Issue by FoxxMD** [photoprism/photoprism#239]
When creating a fresh container if `/home/photoprism/.config` is mounted as volume PhotoPrism does not create a directory or files in `.config` (photoprism/photoprism.yml, photoprism/settings.yml).

To reproduce run a new container with 
```
-v '~/myConfigLocation/':'/home/photoprism/.config':'rw'
```
Same result if mounting `/home/photoprism/.config/photoprism`

I have volumes mounted (and working) for `.cache` and [db](https://docs.photoprism.org/en/latest/getting-started/faq/#mapping-database-directory) so I'm fairly certain I'm not doing anything wonky with volumes.

**Comment by lastzero** [comment]
You can change / use environment variables instead, did you try that? Not sure if it has to do with symlinks... We test it a path is  really a directory

**Comment by FoxxMD** [comment]
Yes I am using environmental variables for some things (sensitive info) but would prefer to use `photoprism.yml` for everything else to keep the command clean IE I don't need to be setting `description` and `twitter` via docker environmental variables.

Will try creating the directories first to see if that makes a difference.

**Comment by abrander** [comment]
What are the permissions on the `.config`? Is the photoprism user *inside* the container allowed to write to that directory?

**Comment by lastzero** [comment]
It runs with user and group ID 1000, not as root

**Comment by lastzero** [comment]
photoprism config shows you the current configuration incl paths

**Comment by lastzero** [comment]
PhotoPrism does not create new configs, you need to use our example as template!

**Comment by lastzero** [comment]
When there is time, we compile all assets in :)

**Comment by lastzero** [comment]
Closing this in favor of #66
