### ISSUE TITLE
MariaDB: Upgrade to 10.8 and increase default innodb_buffer_pool_size to 512MB

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2390]
### Our development environment and [config examples](https://dl.photoprism.app/docker/) are generally based on the [latest stable MariaDB release](https://mariadb.com/kb/en/mariadb-server-release-dates/) to take advantage of performance improvements and test compatibility.

This does not mean [older versions](https://docs.photoprism.app/getting-started/#databases) are no longer supported and you have to upgrade immediately. If MariaDB fails to start after upgrading from an earlier version the internal management schema may be outdated. See [Troubleshooting MariaDB Problems](https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#version-upgrade) for instructions on how to fix this:

- https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#version-upgrade

#### innodb_buffer_pool_size

Since the current innodb_buffer_pool_size default value of 128 MB seems very small and many users will not increase it on their own (as [recommended in our docs](https://docs.photoprism.app/getting-started/troubleshooting/performance/#mariadb)), we will increase the default value to 512 MB, which should not cause any problems on servers that meet our official system requirements. On ARM, the default value will be 256 MB. Anyone running PhotoPrism on unsupported hardware will need to reduce the size and should have enough experience to do so.

**Comment by graciousgrey** [comment]
Released since no problems were reported!
