### ISSUE TITLE
Tag or hide bad / low-quality photos

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#24]
Do we want this? What is a good technical solution?

**Comment by husayt** [comment]
Might implement via smart albums. Based on quality these photos will be tagged and then it will be able to show them or hide them.

**Comment by lastzero** [comment]
We already group several files into one photo (you can set a primary file). The UI can certainly display that as stack or at least in the detail view. Hiding "bad" shots would be more like a filter or something, not hide them completely. But I'm also not convinced. I think you should just delete them as fast and as soon as possible.

**Comment by devzsolt** [comment]
@lastzero I'm also preferring deleting the bad shots as soon as possible. They are just increasing the clutter and decreasing the disk space. I would imagine this as a post-import process which is semi-automatic, the app groups the similar shots, ranks them and gives a simple UI to choose the one(s) to keep and the rest goes to the trash (which is emptied periodically). What do you think about this approach?

**Comment by graciousgrey** [comment]
see https://github.com/photoprism/photoprism/issues/288
