### ISSUE TITLE
Getting "No files available for downloading" when selecting multiple files to download

### ISSUE THREAD

**Issue by andrewlow** [photoprism/photoprism#2412]
### Discussed in https://github.com/photoprism/photoprism/discussions/2396

<div type='discussions-op-text'>

<sup>Originally posted by **andrewlow** June  3, 2022</sup>
I went digging in the code - and got here https://github.com/photoprism/photoprism/blob/182bc09d87b86310b076e44a3b6302898cff4efc/internal/api/download_zip.go#L76

Using Firefox 100. Also tested Chrome. 

If I select only 1 item - it downloads fine. 
If I select 2 items - I get this error. Fails for 3 photos as well.

These are all .jpg photos - from a Pixel 4a and a Pixel 2

I thought I'd found the problem and fixed it.  My `settings.yml` file had only this 
```
Download:
  Name: file
  ```

changing it to 
```
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: false
  MediaSidecar: false
```

appeared to resolve my problem - as photos uploaded from the day previous - and new photos uploaded from the Pixel 4a were just fine for multi-selecting and downloading a zip.

Unfortunately when I tried to select 3 older photos from the Pixel 2 I got the same error again. Similarly if I select older Pixel 4a photos it also does not work. Even some old photos that are regular JPG files saved from the web and uploaded - don't seem to work for download. (It is difficult to exhaustively test what does not work). 

Multi-select vidoes seems to work ok - so this is limited in some way to photos?
</div>

**Comment by andrewlow** [comment]
I have enabled debug logging - but only see this in the logs when I try (and fail) to download
```
time="2022-06-10T15:14:06Z" level=debug msg="api: abort /api/v1/zip with code 404 (No files available for download)"
time="2022-06-10T15:14:06Z" level=debug msg="http: POST /api/v1/zip (404) [15.109375ms]"
```

**Comment by lastzero** [comment]
Try Originals: false or MediaRaw: true

**Comment by andrewlow** [comment]
Changing the download config section to be
```
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: true
  MediaSidecar: false
  ```
  and restarting the container - did not help.
  
  Trying
  ```
  Download:
  Name: file
  Disabled: false
  Originals: false
  MediaRaw: false
  MediaSidecar: false
```
Also did not appear to work.

**Comment by andrewlow** [comment]
Hmm.. just setting everything `true` seemed to fix it?

```
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: true
  MediaSidecar: true
  ```
  
  I'm confused as to why the defaults were not working - I don't have that weird a setup.

**Comment by andrewlow** [comment]
Details on my configuration.

I'm running it as a docker container - connected to a mariadb

I have 3 volume mounts:
- `/<host path>/storage:/photoprism/storage`
- `/<host path>/originals:/photoprism/originals`
- `/<host path>/import:/photoprism/import`

I have these environment variables
- PHOTOPRISM_UPLOAD_NSFW="true"
- PHOTOPRISM_ADMIN_PASSWORD="super secret" 
- PHOTOPRISM_DATABASE_DRIVER=mysql 
- PHOTOPRISM_DATABASE_SERVER=mariadb:3306 
- PHOTOPRISM_DATABASE_NAME=photoprism 
- PHOTOPRISM_DATABASE_USER=photoprism 
- PHOTOPRISM_DATABASE_PASSWORD="other super secret" 
- PHOTOPRISM_DISABLE_BACKUPS="true" 
- PHOTOPRISM_ORIGINALS_LIMIT=4000 

Complete settings.yml
```
UI:
  Scrollbar: true
  Zoom: false
  Theme: default
  Language: en
Templates:
  Default: index.tmpl
Maps:
  Animate: 0
  Style: streets
Features:
  Upload: true
  Download: true
  Private: true
  Review: true
  Files: true
  Videos: true
  Folders: true
  Albums: true
  Moments: true
  Estimates: true
  People: true
  Labels: true
  Places: true
  Edit: true
  Archive: true
  Delete: true
  Share: true
  Library: true
  Import: true
  Logs: true
Import:
  Path: /
  Move: true
Index:
  Path: /
  Convert: true
  Rescan: true
Stack:
  UUID: true
  Meta: true
  Name: false
Share:
  Title: ""
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: true
  MediaSidecar: true
  ```

**Comment by andrewlow** [comment]
It appears that the 1 change from `MediaSidecar:false` to `MediaSidecar:true` caused this to start working!?

From this issue https://github.com/photoprism/photoprism/issues/2234#issuecomment-1099941039  
> MediaSidecar: Include metadata sidecar files (JSON, XMP, YAML)

I really don't get why including the metadata is resulting in the download working - and removing it causes it to fail.

This is the resulting zip file that was successfully downloaded once I had set it to true
```
 % unzip -v photoprism-download-20220611-140029-3sv3194x.zip 
Archive:  photoprism-download-20220611-140029-3sv3194x.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 4662014  Defl:N  4654629   0% 06-02-2022 20:12 4eeb5c37  20220529_193105_672C3CC2.jpg
 4787743  Defl:N  4779204   0% 06-02-2022 20:12 f9794aab  20220529_193152_3F5F4738.jpg
 3806706  Defl:N  3795353   0% 06-02-2022 20:12 54cbc0da  20220529_193238_6196152B.jpg
--------          -------  ---                            -------
13256463         13229186   0%                            3 files
```

I just re-confirmed - flipping that one flag `MediaSidecar` to false (and restarting the container) - causes the 3 files to fail to download. Changing the flag to true fixes things and I can download a zip file again.

**Comment by lastzero** [comment]
Did you perform a full rescan?

**Comment by andrewlow** [comment]
No - I did not force a rescan. Let me figure out how to trigger that and see if that changes things. (but with `MediaSidecar:true` it appears to be working.. I just don't understand why.

**Comment by lastzero** [comment]
It will as the index information required to filter downloads is missing otherwise.

**Comment by andrewlow** [comment]
Ok - well - that seems to have sorted things out.

My download settings section now looks like
```
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: true
  MediaSidecar: false
  ```
  
  Prior to doing a rescan - using the above settings caused me to not be able to download certain photos from my library.
  
  Initiating a re-scan
  
![image](https://user-images.githubusercontent.com/2952475/173233971-b72d1058-9909-4208-bf73-43ac0a46dc3e.png)

and waiting for it to complete - now it seems I can download those same 3 photos I couldn't previously.

Somewhere along the upgrade path from an earlier version of Photoprism - my 'settings' didn't get updated - when I discovered the problem my Download section only had `Name`

So either - those missing settings resulted in defaults that did not work for my use OR my meta-data that is 'fixed' via a re-scan was not correct. Either way - I'm fixed now.

It has been a long time since I've done a re-scan. There hasn't been a need.

Thanks - I'll close this issue, but hopefully it's useful data for others who hit the same problem.
