### ISSUE TITLE
Unable to start - failed to create shim task: OCI runtime create failed: runc

### ISSUE THREAD

**Issue by DSew20** [photoprism/photoprism#2425]
Hello,

I had PhotoPrism working, but alas it has stopped.  Not sure what has happened, but I now get the following error:

Failure
failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown

I'm running PhotoPrism in docker, managed via Portainer.  Was working ok, then tried to open today and I get the above message.

Any ideas where to start to decode / debug this?  MariaDB seems to start ok.

**Comment by lastzero** [comment]
Check the environment variables as Portainer tends to cache those of old versions and applies them to new images as well even though they do not fit and can break things completely. Search our issues and discussions for the reports of other Portainer users.
