### ISSUE TITLE
Restore originals from thumbnails?

### ISSUE THREAD

**Issue by dessalines** [photoprism/photoprism#2431]
Somehow in an upgrade, photoprism deleted my entire originals folder :(

Luckily, I was able to save a backup of the `.photoprism` folder, which includes all the thumbnails, including high-res ones, as well as all the yml files. Unfortunately the thumbnails don't have the original exif data, so these are all completely unorganized.

After an upgrade to the newest photoprism, it now sees the thumbnails, but when I click on an album, it says "Cannot find".

Is there any way I can restore this data some way? Ideally I just want to restore dates on the exif data for the thumbnails folder, then I can remove the unecessary thumbnails, extract them to a new folder, and use it as my new "originals".

Has anyone had this problem before? How did you solve it?

**Comment by lastzero** [comment]
More likely, the folders are/were mounted incorrectly or not mounted at all, so the files were stored in the Docker container and not on the host?

We kindly ask you not to report bugs via GitHub Issues unless you are certain to have found a fully reproducible and previously unreported issue that must be fixed directly in the app. [Contact us](https://photoprism.app/contact) or [a community member](https://link.photoprism.app/discussions) if you need help, it could be a local configuration problem, or a misunderstanding in how the software works.
