### ISSUE TITLE
Videos: ffmpeg framerate (-r) option incorrect when using h264_nvenc

### ISSUE THREAD

**Issue by abgd1234** [photoprism/photoprism#2442]
When NVENC is used, the call to ffmpeg sets the framerate to 30 before `-i`. This causes ffmpeg to interpret the input video as 30fps, even when it isn't. 

https://github.com/photoprism/photoprism/blob/4909f86ca04202887a45a3914d73cc6af07f4cc3/internal/ffmpeg/convert.go#L81-L86

To fix this, `"-r", "30", ` should be placed after `"-i", fileName, ` in line with the other non-NVENC cases.

**Comment by lastzero** [comment]
This is generally intended to limit the size and bitrate of the transcoded version as 4K 60fps videos are HUGE, especially when using a less efficient encoder. We welcome a pull request to update the command so it meets that goal should this currently not be the case.

**Comment by abgd1234** [comment]
The issue is that the input file rather than the output file is specified as 30fps. For example, a 15fps input video will be treated as 30fps, and the transcoded output video will then run twice as fast. This is simply a bug - all the other encoder cases correctly place `"-r", "30", ` after the input file.

I have submitted pull request #2449 to fix this.
