### ISSUE TITLE
Photoprism cli

### ISSUE THREAD

**Issue by pniedzwiedzinski** [photoprism/photoprism#245]
I'm going to make a script for uploading images to the photoprism and I was thinking, that I could create the cli for the photoprism. I prefer using terminal for all my work, so I wanted to have also a tool for managing images.

As photoprism is written in go, I thought that I could also made it in go. I always wanted to learn go, so this sounds perfect.

**Comment by lastzero** [comment]
You mean adding a command to photoprism? There's even a copy command for importing photos. Not sure if you've seen that it already runs in a terminal, there's not only a web server :)

**Comment by pniedzwiedzinski** [comment]
> You mean adding a command to photoprism? There's even a copy command for importing photos. Not sure if you've seen that it already runs in a terminal, there's not only a web server :)

Cool, I wasn't aware of the copy command. But I'm using photoprism in docker on the other machine, so I was thinking about a standalone program, that would communicate through the api. I think it's easier because I don't need to ssh into the server and running bash in container. Standalone program sounds also more elegant.

**Comment by lastzero** [comment]
You are right, there's no tool for pushing photos yet. In theory, you could use our upload & import API for that. We'll soon implement sharing which will enable you to import photos from remote servers e.g. using WebDAV. Maybe that's the easier way?

**Comment by pniedzwiedzinski** [comment]
Hmm, I'm not familiar with WebDAV, but it sounds interesting. Although I don't really like the idea of having multiple ways of modifying the data, but that's my personal opinion.

I think that as frontend app uses http api, cli should do the same. Maybe in future we could add WebDAV support

**Comment by lastzero** [comment]
Our API is basic REST with JSON, session token is in the HTTP header (there is an API to get a token with the right password).

**Comment by pniedzwiedzinski** [comment]
@lastzero would you like to review this? Or maybe someone else https://github.com/pniedzwiedzinski/photoprism-cli/pull/1

**Comment by graciousgrey** [comment]
Sorry, we didn't get back to you earlier. Do you have more questions or can we close this issue?

**Comment by pniedzwiedzinski** [comment]
We can close it
