### ISSUE TITLE
WebDAV: Endpoints must be fully disabled in public mode

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2464]
**As a user running their instance in public mode, I expect WebDAV to be completely disabled as it is not possible to manage access in the web UI, it does not work without a password, and it is not possible to use it without a password to prevent abuse.**

Although and because it is not possible to use WebDAV in public mode (a non-empty password is required), the endpoint must be completely disabled to avoid running unused services and to clearly signal that support is neither intended nor desirable.

- the [User Guide](https://docs.photoprism.app/user-guide/sync/webdav/) clearly states that WebDAV is automatically disabled when [running in read-only or public mode](https://docs.photoprism.app/getting-started/config-options/)
- a support request indicated that endpoints were only fully disabled in read-only and/or demo mode
- these are often enabled in combination with public mode, which is probably why it was not noticed earlier

*This issue has nothing to do with the ability to explicitly disable WebDAV in the configuration, that was possible before and still is.*

**Comment by david1155** [comment]
Hello,
I'm using external two-factor auth (Authelia) for the frontend. Therefore, I set `PHOTOPRISM_PUBLIC=true`.
I also use several devices with PhotoSync to automatically upload media via WebDav (with password auth passthrough frontend auth). Please advise how is it possible to continue using WebDAV upload functionality without using built-in web auth for the whole PhotoPrism?
Maybe it's worth implementing something like this to allow such use-case:
```
PHOTOPRISM_DISABLE_WEBDAV=false
PHOTOPRISM_PUBLIC=true
```
Thank you very much in advance.

**Comment by lastzero** [comment]
You could run a custom file server. How did it work before? Were you able to use WebDAV without password?

**Comment by david1155** [comment]
I used the following nginx frontend config:
```
location /import {
  auth_basic    off;
  dav_methods                 PUT DELETE MKCOL;# COPY MOVE;
  create_full_put_path        on;
  dav_access                  user:rw  group:rw  all:r;
  dav_ext_methods             PROPFIND OPTIONS;
  proxy_pass http://127.0.0.1:2342;
```
PhotoSync has a built-in PhotoPrism plugin for authenticating via WebDAV. In fact, I used a standard admin account and password to authenticate. It was more convenient than a custom file server because PhotoPrism starts importing instantly after upload.

**Comment by david1155** [comment]
It was configured long time ago [per documentation](https://docs.photoprism.app/user-guide/sync/webdav/)
<img width="709" alt="Screenshot 2022-07-03 at 18 58 53" src="https://user-images.githubusercontent.com/64733669/177047594-e8d18641-678f-41f3-b7a8-ec754ffd81a6.png">

**Comment by bschnei** [comment]
It was also useful for me to have the front end be "public" but the WebDAV endpoint still require authorization for similar reasons as @david1155. No disagreement that that behavior feels inconsistent with the definition of "public" so I'm supportive of the change for that reason, but it would also be great if the two things were separately configurable rather than all-or-nothing.

**Comment by ChrisYx511** [comment]
How it worked was even if the server was set to PUBLIC, authentication via WEBDAV still used the admin username and password that would be the password to login to Photoprism if it was set to private/password authentication.

**Comment by legomannetje** [comment]
Sorry for responding to this old issue, but would it be possible to use the webdav in public mode. We used this feature to upload pictures to photoprism, while others could only look at them. Or is the current advice to move the pictures to an other backend?

**Comment by lastzero** [comment]
If it is public, they cannot only look at them but would have full server access. That's why authentication with a password is required.

**Comment by legomannetje** [comment]
In public mode with read-only we were able to upload pictures to the webdav. But since updating this isn't working anymore

**Comment by lastzero** [comment]
Right, that was the security issue we fixed. That should not be allowed.

**Comment by legomannetje** [comment]
Okay, then it's back into the documentation to see how to upload pictures to it while its in public mode! Thanks for your help, and all your work on this amazing app!

**Comment by lastzero** [comment]
You could use SSH / SCP or a network file system for that.

**Comment by legomannetje** [comment]
The problem is, we don't have those access to it currently, we were very happy that we could do it this way with a reverse nginx proxy. But thats something we will need to solve

**Comment by bschnei** [comment]
@legomannetje FWIW, if you're willing to build from source yourself, you can just change [this line](https://github.com/photoprism/photoprism/blob/develop/internal/config/config_features.go#L7) to restore previous behavior.
