### ISSUE TITLE
UX / Improve zooming

### ISSUE THREAD

**Issue by dennorske** [photoprism/photoprism#247]
Hello -

Been using photoprism for my January 2020+ pictures and I have one bug/feature I'd like to add in.

Today we can already zoom by using the tool, when viewing a picture- however the zoom is very limited. And when I say very limited, many times I can't even zoom in 5% on the picture from its viewed state. And then I start to wonder if the zoom is useful at all 😂 I understand it is a project in progress, so that's why I decided to pop by and add it in 😄 

Can you add a slider or another step of magnification that can improve the zoom when viewing pictures? Or are you compressing the preview as well so much that this wouldn't be of any use? 
Let me know if I am doing something wrong.

**Comment by lastzero** [comment]
We use a standard plugin for this, not sure if it can be configured. The image we deliver usually fits your screen, so for higher magnification, you would need to load a different file.

**Comment by dennorske** [comment]
Yeah I noticed, it would zoom until it hit either of my bezels on all the pictures - and in many cases that was almost no zoom for me, so a bit more would be perfect, if possible :)

**Comment by bleomycin** [comment]
Very pleased to hear you will hopefully be adding this feature in the future. I need almost limitless zoom for my application which is photographing buildings in various states of their build with extremely high resolution cameras so we can check the photo in the distant future if necessary and be able to read tiny text on wires, pipes, etc. Thank you for the wonderful project, I cant wait to ditch google photos.

**Comment by frp** [comment]
I configured photoprism to show the originals, but can't display them in 100% zoom: the only way to do that is to right-clik => open in the new tab => zoom in using the browser.

Please improve zoom feature usefulness.

**Comment by aCuria** [comment]
Its is a pity we cannot zoom to 100% resolution and beyond, this is a big deal, and the reason why I am looking for an alternative to plex in the first place.

**Comment by lastzero** [comment]
We have this on our todo but limited resources as we didn't reach our funding goal yet.

**Comment by arkadym** [comment]
While thinking on right implementation, do you think it could be good idea to add a button into preview, e.g. load full size image, then it will possible to zoom in till the full size ?

**Comment by lastzero** [comment]
Yes, adding a zoom button makes sense and/or our new viewer automatically loads a higher resolution if you zoom in with your fingers on a touch screen.

**Comment by aCuria** [comment]
Should load the small image normally, and the large one when zooming

**Comment by graciousgrey** [comment]
I close this, as it will be part of https://github.com/photoprism/photoprism/issues/1307

**Comment by meonkeys** [comment]
Was this implemented or canceled? I can't figure out an easy way to zoom (way) in when using PhotoPrism from a standard desktop/laptop web browser (Firefox in my case). I'm running the `photoprism/photoprism:latest` Docker image (says "Build 220614-dea9ff68" on the /settings page).

**Comment by graciousgrey** [comment]
Improved zooming is not cancelled it will be implemented as part of this issue: #1307.

**Comment by cybericius** [comment]
+1
