### ISSUE TITLE
UX: View type of search results and albums must be remembered

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2477]
**When you switch between card, mosaic and list view, the currently selected view type must be remembered. This feature has already been implemented. The functionality needs to be restored as it seems to have been broken during a recent refactoring.**

In addition, the viewer's history mode must be deactivated, since the result views repeatedly jumped back to the top after closing the viewer while testing.

**Comment by graciousgrey** [comment]
Released since no problems were reported!

**Comment by heikomat** [comment]
@lastzero do you happen to remember the test-setup you had while observing the issues with history mode?

**Comment by lastzero** [comment]
Regular chrome browser from what I remember. With the current release, the problem of course is not reproducible as history mode is disabled.

**Comment by heikomat** [comment]
i understand, but even with history mode enabled (in the local dev setup) i can't seem to reproduce the "jump back to top" issue

**Comment by lastzero** [comment]
When you use the back button of the browser? Not sure if only/also happens if you just close the viewer. Try esc key as well. Also it may depend on if you use back / next within the viewer.

**Comment by heikomat** [comment]
a quick test of different combinations (back button, esc, with and without using back/next in the viewer) seems to indicate, that only the back-button of the browser (or the back-button on an android device) is impacted by history mode.

Everything else seems to act the same (at least acording to the tests i did just now).

When pressing the back button while the viewer is open:
- With history mode disabled, the browser navigates away from the result view in the background by going to the previous view **without** closing the photo-viewer (this is most likely not what one would expect)
- with history mode enabled, the photo-viewer gets closed

i'd love to fix history mode (a friend of mine even told me that it is annoying, that the back-button on android doesn't close the viewer but instead navigates away).
But i can only do that if i can reproduce the bugs that history-mode causes that you observed

**Comment by lsueslack** [comment]
It would be so great if you could please fix the history mode.

**Comment by lastzero** [comment]
Still on vacation, I don't have a computer to test. Just a glass of red wine and my phone. If you can wait until later next week, I'll send you a video.

**Comment by heikomat** [comment]
Ah sorry, didn't know you were still on vacation.
I don't think trying to reproduce it myself much more would be very effective, as i don't know what the difference between your test and my test might be.

So i'll just wait until you come back from vacation and had time to reproduce it again.
That's totally fine with me. Enjoy your time off. Rome wasn't built in a day :P

**Comment by lastzero** [comment]
Of course we wouldn't mind if someone else can help! Maybe using a dev preview image if you don't have a dev environment.

**Comment by heikomat** [comment]
I could build and provide a preview-image with the only change being that history mode is enabled again, if that is what you mean

**Comment by heikomat** [comment]
You can now find a preview-image with history-mode enabled at [`ghcr.io/heikomat/photoprism:history`](https://github.com/heikomat/photoprism/pkgs/container/photoprism/37463153?tag=history)
