### ISSUE TITLE
Indexation - Error 1366: incorrect utf8 value

### ISSUE THREAD

**Issue by scilaci** [photoprism/photoprism#252]
Hello,

I'm using this version
 **PhotoPrism version 200207-5fba038-Linux-x86_64**

After indexing, I saw in the logs this type of error :
index: Error 1366: incorrect utf8 value...

`time="2020-02-16T19:40:28Z" level=warning msg="mediafile: no latitude and longitude in metadata"
time="2020-02-16T19:40:28Z" level=info msg="index: changed empty photo title to \"Unknown / 2017\""
time="2020-02-16T19:40:28Z" level=error msg="index: Error 1366: incorrect utf8 value 4844320004000000000000000300000070d833c0c0417fc0(HD2\x00\x04\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00p\xd83\xc0\xc0A\u007f\xc0) for column camera_model"
time="2020-02-16T19:40:28Z" level=info msg="index: failed main jpg file \"Photo/2017/Cambodia/DCIM/100GOPRO/GOPR7877.JPG\""
time="2020-02-16T19:40:33Z" level=error msg="camera: Error 1366: incorrect utf8 value 4844320004000000000000000300000070d833c0c0417fc0(HD2\x00\x04\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00p\xd83\xc0\xc0A\u007f\xc0) for column camera_model"
time="2020-02-16T19:40:33Z" level=warning msg="mediafile: no latitude and longitude in metadata"
time="2020-02-16T19:40:33Z" level=info msg="exif: taken at 2017-12-21 05:17:31 +0000 UTC"
time="2020-02-16T19:40:33Z" level=info msg="index: changed empty photo title to \"Building / 2017\""
time="2020-02-16T19:40:33Z" level=error msg="index: Error 1366: incorrect utf8 value 4844320004000000000000000300000070d833c0c0417fc0(HD2\x00\x04\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00p\xd83\xc0\xc0A\u007f\xc0) for column camera_model"
time="2020-02-16T19:40:33Z" level=info msg="index: failed main jpg file \"Photo/2017/Cambodia/DCIM/100GOPRO/GOPR7878.JPG\""
time="2020-02-16T19:40:37Z" level=error msg="camera: Error 1366: incorrect utf8 value 4844320004000000000000000300000070d833c0c0417fc0(HD2\x00\x04\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00p\xd83\xc0\xc0A\u007f\xc0) for column camera_model"
`

picture:
![GOPR7877](https://user-images.githubusercontent.com/11696499/74613894-398d2000-5113-11ea-82e5-4587cccf0e6c.JPG)

What is it?

How I can control if the picture is imported or not ? 
Or skipped by the error ?

**The database was erased before starting the container**

**Comment by lastzero** [comment]
Looks like UCS-2 / UTF-16, typically used by Windows and other Microsoft products. Probably happens because I added support for XP* Exif tags. To fix this, we need to convert it to UTF-8. Thank you for the bug report!

**Comment by scilaci** [comment]
I sent the original picture in the hello@ photoprism mailbox to reproduce the error

**Comment by lastzero** [comment]
Awesome! Thanks

**Comment by lastzero** [comment]
Is this fixed?
