### ISSUE TITLE
ERRO index: already running

### ISSUE THREAD

**Issue by gyto6** [photoprism/photoprism#2522]
#### 1. What is not working as documented?

Everything is working, but for each library scan with new pictures, a false positive appears.

`ERRO index: already running`

#### 2. How can we reproduce it?

-1. Go to 'Library'
-2. Click on 'Index'
-3. Scroll down to select 'Start'
-4. See error `ERRO index: already running` if pictures has been added to the library.

#### 3. What behavior do you expect?

To not meet this error as I click once only or didn't input any commands in CLI meanwhile.

#### 4. What could be the cause of your problem?

The end of the new pictures scan entry.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://user-images.githubusercontent.com/105558798/179360836-3b8e7d1f-dac2-4b99-bfb9-269ded5d7a30.png)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: Build 220629-5d7448d2 AMD64 

(b) Database Type & Version: MariaDB 10.8.3

(c) Operating System Types & Versions: Linux (Unraid)

**Comment by lastzero** [comment]
Typically happens if you start it twice or a background process (for example after uploading via WebDAV) is already running. Make sure websockets work properly as you otherwise won't see the proper status in the UI.

**Comment by gyto6** [comment]
I don't use WebDAV or any other process. Meanwhile, I might have activated new file detection but I've never succeded to make it work (or maybe I did?).

I'll close by now and check with different parameters if I can't get rid of this. Whatever, it's not dramatic.
