### ISSUE TITLE
Index Photos from Multiple Directories

### ISSUE THREAD

**Issue by garrettdowd** [photoprism/photoprism#253]
While the Originals, Import, Export directory structure may work for users that want to manage their photo collection with photoprism, I assume there are many of us that manage our photo collection and its directory structure via other methods and software. For example, I have seperate folders for my DSLR, smartphone, and drone pictures. 

There should be an ability to add multiple directories and have photoprism index each directory. This would allow users to keep existing directory structures. This would be similar to how Plex ingests media.

**Comment by tmb80c** [comment]
In my case the pictures are on smb file shares. I would just add three mount points under "Originals". Like Originals/DSLR, Originals/smartphone, Originals/drone in your case where each mount point mounts to the relevant SMB share.

**Comment by garrettdowd** [comment]
I am currently doing something similar with NFS shares. It does work, but I also need to run a bash script to ensure those shares are mounted before starting Photoprism. (I prefer that the share is only mounted when it needs to be).

I have read a few comments online from people who think that photoprism requires the user to move or rearrange their photo collections. Maybe some info can be added to the docs/FAQs to give some guidance in this area?

**Comment by lastzero** [comment]
You CAN upload, move or copy files and let photoprism name them for you to avoid duplicates. But you can also just index existing directories. Whatever you find useful. Note that you can not choose a custom directory and file name when uploading.

**Comment by garrettdowd** [comment]
Maybe I can clarify my comment further by saying that some people do NOT want to upload/move/copy their existing photo collections. It was unclear to me in the beginning that photoprism can index existing directories (assuming they are mounted/linked under the Originals folder). I had get PhotoPrism up and running to see that it could index an arbitrarily structured photo collection in the Originals folder.

**Comment by lastzero** [comment]
That's why we have a read only mode that is also mentioned in the documentation. Did you read it? Where / how can we clarify it further?

**Comment by garrettdowd** [comment]
I think the documentation is great. However, it might be useful to give use case examples in the [Getting Started ](https://docs.photoprism.org/en/latest/getting-started/) section. Giving an example of mounting a NFS/SMB volume or symlinking a directory could make it more clear that the "read only mode" can be used with existing photo collections. 

Additionally, the [Getting Started Docker Compose](https://docs.photoprism.org/en/latest/getting-started/docker-compose/) page gives Step 3 as "Import" and mentions that photos should be added to the import folder or added through the web ui. It then mentions that you can index files in the Originals folder but does not describe what indexing actually does. For example, will Photoprism create jpg previews of RAW files in the Originals folder after indexing? If I want to use PhotoPrism with my RAW photo collection do I have to "Import" the collection?

**Comment by Bjarrrne** [comment]
> does not describe what indexing actually does. For example, will Photoprism create jpg previews of RAW files in the Originals folder after indexing? If I want to use PhotoPrism with my RAW photo collection do I have to "Import" the collection?

That's what I am interested too. I'd like to use this with my existing photo collection without changing it, but with the ability to use temporary data like thumbnails, etc. Is this possible? Should I mount my photo collection as Originals and set it to read only mode?

**Comment by bobobo1618** [comment]
> But you can also just index existing directories.

I've had a quick look around the documentation, UI and command line help and I haven't found this feature, at least not the feature I expect this to mean. The command line help indicates that I can copy or "import" (move) images but I don't see any command that allows me to just add a folder to the index. All the existing actions appear to require me to put things in the originals folder.

I think the intent of this feature request, and the feature I am after, is that PhotoPrism should have some command or setting that indexes folders located outside the Originals/Import folders.

**Comment by lastzero** [comment]
You can use symbolic links to index directories outside the originals path. Or you can use Docker to mount any number of directories to originals. In addition we can transparently overlay multiple originals directories, which is how we create and store sidecar files.

**Comment by lastzero** [comment]
Updated our Getting Started & User Guide FAQs today:

https://docs.photoprism.org/getting-started/faq/

Not sure what additional tasks are required from your point of view so that we can close this issue?

- All [config options](https://docs.photoprism.org/getting-started/faq/#i-could-not-find-a-documentation-of-config-parameters) are documented now
- We provide [docker-compose.yml](https://dl.photoprism.org/docker/docker-compose.yml) files with commented out examples for mounting multiple directories
- PhotoPrism supports symlinks, see #267 & #403
- A similar issue / question has been closed already, see #456

**Comment by graciousgrey** [comment]
I will close this as indexing from multiple directories is possible and we received no more feedback.

**Comment by kubasto** [comment]
> [...] indexing from multiple directories is possible [...].

What is the current recommended method for multiple source/originals folders?

**Comment by graciousgrey** [comment]
Additional directories can be mounted as sub folders of /photoprism/originals (depending on [overlay filesystem support](https://docs.photoprism.app/getting-started/troubleshooting/docker/#overlay-volumes)):

https://docs.photoprism.app/getting-started/docker-compose/#volumes

**Comment by kubasto** [comment]
So I guess there are no plans to add feature to use real multiple locations for sources? I'd like to know is it worth waiting for.

**Comment by graciousgrey** [comment]
What do you mean by real multiple locations? What functionality exactly do you miss?

**Comment by lastzero** [comment]
@kubasto Either you use Docker, then the app can't see anything you haven't shared (mounted) with it. So you need to do that anyway. Or you run PhotoPrism without Docker, then you can use symbolic links.

**Comment by kubasto** [comment]
Yes, I use docker on TrueNAS Scale.
There is option to add _Extra Host Path Volumes_ in the app creation settings (besides the _Storage Volume for Original Media_, but I don't know if it's useful for that purpose.

**Comment by lastzero** [comment]
> Yes, I use docker on TrueNAS Scale. There is option to add _Extra Host Path Volumes_ in the app creation settings (besides the _Storage Volume for Original Media_, but I don't know if it's useful for that purpose.

Probably yes, but it is a third-party integration, so we have no experience with it and therefore rely on the help of their community and maintainers.

**Comment by kubasto** [comment]
Yes, but even if I have access to more data locations, **I still can't add more sources of Originals**, without messing with symbolic links (which would expose other locations inside the primary location, which I want to avoid).

**Comment by lastzero** [comment]
What exactly do you mean by "expose"? For example, don't you want the additional folders to be visible via WebDAV or only to certain user accounts? If symbolic links work, the instance can access those files anyway. Using them is not a "mess".

**Comment by kubasto** [comment]
I think the best solution for me would be to create a AGREGATED-PHOTOS folder and add all my datasets to it by symbolic links. I'll have to check if it's doable on TrueNAS, though.
Anyway, I don't understand why you don't consider adding multiple originals locations in the PhotoPrism app itself. Seems like a natural way to go.

**Comment by lastzero** [comment]
Maybe we'll do something like this in a future release, but right now I don't see much need for it (since there are viable alternatives) compared to other feature requests like batch editing, improved sharing, and more authentication options.
