### ISSUE TITLE
Purge: SQL error is displayed when the photo ID of a file is missing

### ISSUE THREAD

**Issue by centralhardware** [photoprism/photoprism#2540]
#### 1. What is not working as documented?

sql error in log

`ERRO[2022-07-22T14:46:13Z] files: Error 1052: Column 'photo_uid' in where clause is ambiguous (regenerate photo_taken_at)`

#### 2. How can we reproduce it?

run purge command

#### 3. What behavior do you expect?

no sql error 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

https://gist.github.com/centralhardware/db6dfd610500784a8ea3c9ed9e333a06

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: lastest docker - 220629-5d7448d2-Linux-AMD64

(b) Database Type & Version:  Version: '10.7.4-MariaDB-1:10.7.4+maria~focal'

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

If yes, please specify type and version. You can skip this if you are reporting a completely unrelated issue.

**Comment by lastzero** [comment]
In fact, this should never happen, since it means that the numeric photo ID is 0. It was implemented only as a theoretical case. Any idea how the index could have been corrupted? I don't see this when running purge. You will get a fix for this particular situation shortly.

**Comment by lastzero** [comment]
Started a new preview build, which is available shortly. Happy testing! 🤗

**Comment by lastzero** [comment]
Never mind, I found it: `func SetPhotoPrimary(photoUID, fileUID string)` in `internal/query/files.go`. Good catch!

**Comment by centralhardware** [comment]
can't reproduce, thanks
