### ISSUE TITLE
thumbnails:  create thumbnails if missing

### ISSUE THREAD

**Issue by centralhardware** [photoprism/photoprism#2547]
**Is your feature request related to a problem? Please describe.**

if thumbnails file is missing black rectangle showing.
**Describe the solution you'd like**

create thumbnails right now if the file is lost

same as [Dynamic Previews](https://docs.photoprism.app/user-guide/settings/advanced/#dynamic-previews) but cache thumbnail

**Comment by graciousgrey** [comment]
Thumbnails should not be missing unless they have been manually deleted from the cache folder. 
You can create missing ones using the thumbs command.

**Comment by lastzero** [comment]
Note dynamically create thumbnails will be cached. So the feature you are requesting is already implemented. In addition you can re-index or run the thumbs command in a terminal to generate missing thumbnails.
