### ISSUE TITLE
invalid JPEG format:  missing 0xff00 sequence while decoding

### ISSUE THREAD

**Issue by centralhardware** [photoprism/photoprism#2557]
#### 1. What is not working as documented?

error in log

`media: invalid JPEG format: missing 0xff00 sequence while decoding in <>`
`resample: invalid JPEG format: missing 0xff00 sequence while decoding`

#### 2. How can we reproduce it?

1. run `photoprism thumbs ` command 

#### 6. Which software versions do you use?

latest docker version: 220728-729ddd920-Linux-AMD64

**Comment by centralhardware** [comment]
duplicate [1673](https://github.com/photoprism/photoprism/issues/1673)

**Comment by lastzero** [comment]
https://docs.photoprism.app/known-issues/#jpeg-bad-rst-marker
