### ISSUE TITLE
UX: Show photo preview/thumbnail when editing labels

### ISSUE THREAD

**Issue by Sohalt** [photoprism/photoprism#2564]
**Is your feature request related to a problem? Please describe.**

When editing labels for pictures in the labels tab I don't see the picture, which I'm editing the labels for. This is especially annoying when editing labels for multiple pictures and moving between them using the arrows in the top right corner.

**Describe the solution you'd like**

Show a small preview/thumbnail of the picture being edited on the labels page.

This is already suggested as part of https://github.com/photoprism/photoprism/issues/317, but that issue lists a bunch of other features as well, which are not as pressing imho, so I created a separate issue to track a single feature independently.

**Describe alternatives you've considered**
Since there is already a preview of the image shown on the "details" tab and the "files" tab, it might make sense to move the preview out of the tab view alltogether and show it on the side for all tabs.

**Comment by graciousgrey** [comment]
See: https://github.com/photoprism/photoprism/issues/628 :)

**Comment by Sohalt** [comment]
Sorry, didn't see than /o\. Thank you!
