### ISSUE TITLE
Auth: Activate public mode via `PHOTOPRISM_AUTH_MODE="public"`

### ISSUE THREAD

**Issue by danackerson** [photoprism/photoprism#2565]
#### 1. What is not working as documented?

I've updated my docker-compose.yml accordingly:

    --  PHOTOPRISM_PUBLIC: "true" # No authentication required (disables password protection)
    ++ PHOTOPRISM_AUTH_MODE: "public" # authentication mode (public, password)

#### 2. How can we reproduce it?

1. Go to my photoprism website
2. Redirected to /auth/login

#### 3. What behavior do you expect?

No login screen as I chose "public" AUTH_MODE.

#### 4. What could be the cause of your problem?

Using PHOTOPRISM_AUTH_MODE: "public". Reverting to PHOTOPRISM_PUBLIC: "true" works as expected.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
PhotoPrism® CE
Build 220728-729ddd920

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
MariaDB

(c) Operating System Types & Versions: Linux, Windows, Android,...
macOS 
(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
Chrome on macOS

**Comment by graciousgrey** [comment]
Related to https://github.com/photoprism/photoprism/discussions/2559

**Comment by lastzero** [comment]
Started a new preview build build for testing. If it works, we can release it today!
