### ISSUE TITLE
Add setting "default file order in album"

### ISSUE THREAD

**Issue by dmitry-brazhenko** [photoprism/photoprism#2567]
Here is an album. All my photos are named like "2020-01-01 10:00"
I would like to sort them in all albums by filename.  Unfortunately, to be able to do that, I just need to switch it in every album. 
![image](https://user-images.githubusercontent.com/61410067/182016064-5a9d79a3-3af3-4bc9-97bb-45d5ac8c1125.png)

**Suggestion:**
Add a setting in settings "default file order in album". Where I can chose a proper order method for my collection.

Thanks :)

**Comment by graciousgrey** [comment]
Looks very similar to: https://github.com/photoprism/photoprism/issues/405 :)
