### ISSUE TITLE
index specific folder(s)

### ISSUE THREAD

**Issue by scilaci** [photoprism/photoprism#258]
I don't know if is possible, I've already indexed 60K of pictures ( more than 3 days ) from the Original folder ( where I mounted other folders from my NFS )
and I want to add and delete pictures in a spécific folder 

I need to rescan all again ?

There are a way to scan only this spécific folder ?

**Comment by lastzero** [comment]
Just pushed to master, updated Docker images should be available in less than one hour. You're welcome to test!

![Screenshot 2020-05-06 at 16 01 03](https://user-images.githubusercontent.com/301686/81186247-df358a00-8fb2-11ea-94b8-70b5c9f529bb.png)

**Comment by lastzero** [comment]
Seems to work for everyone, not bug reports for a couple of days.
