### ISSUE TITLE
Incorrect creation date from mp4 video

### ISSUE THREAD

**Issue by refactoriel** [photoprism/photoprism#2587]
#### 1. What is not working as documented?

I have a few mp4 videos that according to `exiftool` have `DateTimeOriginal` field with the video's creation date time. This is not being used by Photoprism. Here's the json output of exiftool for one sample video (file directory fields removed):
```
[{
  "ExifToolVersion": 11.16,
  "FileName": "25-03-16_1146.mp4",
  "FileSize": "21 MB",
  "FileModifyDate": "2022:03:06 18:58:25+01:00",
  "FileAccessDate": "2022:08:03 20:38:10+02:00",
  "FileInodeChangeDate": "2022:05:01 13:36:12+02:00",
  "FilePermissions": "rwxr-xr-x",
  "FileType": "MP4",
  "FileTypeExtension": "mp4",
  "MIMEType": "video/mp4",
  "MajorBrand": "MP4  Base Media v1 [IS0 14496-12:2003]",
  "MinorVersion": "0.2.0",
  "CompatibleBrands": ["isom","iso2","avc1","mp41"],
  "MovieHeaderVersion": 0,
  "CreateDate": "0000:00:00 00:00:00",
  "ModifyDate": "0000:00:00 00:00:00",
  "TimeScale": 1000,
  "Duration": "11.46 s",
  "PreferredRate": 1,
  "PreferredVolume": "100.00%",
  "PreviewTime": "0 s",
  "PreviewDuration": "0 s",
  "PosterTime": "0 s",
  "SelectionTime": "0 s",
  "SelectionDuration": "0 s",
  "CurrentTime": "0 s",
  "NextTrackID": 3,
  "TrackHeaderVersion": 0,
  "TrackCreateDate": "0000:00:00 00:00:00",
  "TrackModifyDate": "0000:00:00 00:00:00",
  "TrackID": 1,
  "TrackDuration": "11.36 s",
  "TrackLayer": 0,
  "TrackVolume": "0.00%",
  "GraphicsMode": "srcCopy",
  "OpColor": "0 0 0",
  "CompressorID": "avc1",
  "SourceImageWidth": 1920,
  "SourceImageHeight": 1080,
  "XResolution": 72,
  "YResolution": 72,
  "BitDepth": 24,
  "PixelAspectRatio": "1:1",
  "VideoFrameRate": 50,
  "MatrixStructure": "1 0 0 0 1 0 0 0 1",
  "MediaHeaderVersion": 0,
  "MediaCreateDate": "0000:00:00 00:00:00",
  "MediaModifyDate": "0000:00:00 00:00:00",
  "MediaTimeScale": 48000,
  "MediaDuration": "11.46 s",
  "MediaLanguageCode": "und",
  "HandlerDescription": "SoundHandler",
  "Balance": 0,
  "AudioChannels": 2,
  "AudioBitsPerSample": 16,
  "HandlerType": "Metadata",
  "HandlerVendorID": "Apple",
  "Encoder": "Lavf58.45.100",
  "XMPToolkit": "Image::ExifTool 11.88",
  "DateTimeOriginal": "2016:03:25 11:46+00:00",
  "GPSLatitude": "7 deg 33' 19.78\" N",
  "GPSLongitude": "80 deg 42' 49.62\" E",
  "GPSMapDatum": "WGS-84",
  "GPSVersionID": "2.0.0.0",
  "ExifImageWidth": 1920,
  "ExifImageHeight": 1080,
  "ImageHeight": 1080,
  "ImageWidth": 1920,
  "AudioChannelType": "Stereo",
  "AudioSampleRate": 48000,
  "AudioSampleType": "32-bit float",
  "VideoPixelAspectRatio": 1.77777777777778,
  "VideoPixelDepth": "8-bit integer",
  "MovieDataSize": 21907362,
  "MovieDataOffset": 15921,
  "AvgBitrate": "15.3 Mbps",
  "GPSLatitudeRef": "North",
  "GPSLongitudeRef": "East",
  "ImageSize": "1920x1080",
  "Megapixels": 2.1,
  "Rotation": 0,
  "GPSPosition": "7 deg 33' 19.78\" N, 80 deg 42' 49.62\" E"
}]
```

#### 2. How can we reproduce it?

Index the file. If needed, I can provide a 30 MB sample video file.

#### 3. What behavior do you expect?

`DateTimeOriginal` field should be used as the creation date time.

#### 4. What could be the cause of your problem?

Photoprism might ignore the `DateTimeOriginal` field.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I can share one sample video if required.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: Build 220302-0059f429-Linux-ARM64
(b) Database Type & Version: MariaDB
(c) Operating System Types & Versions: Linux
(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Rockpro64
(b) Physical Memory & Swap Space in GB
(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...
(d) Anything else that might be helpful to know?

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

**Comment by lastzero** [comment]
Please upgrade to our latest version and test again before reporting a bug. Thank you!

**Comment by refactoriel** [comment]
Apologies, it has indeed been fixed in the meantime. :heart:
