### ISSUE TITLE
some apple  HEIC file formats not suport 

### ISSUE THREAD

**Issue by TechPorter20** [photoprism/photoprism#2592]
![图片](https://user-images.githubusercontent.com/65204755/183015609-79be3cb1-c272-44ac-bfb6-d1ae8211a3c4.png)

![图片](https://user-images.githubusercontent.com/65204755/183015702-ce9f0f98-caf7-476a-96b4-d24c600e92e5.png)

![图片](https://user-images.githubusercontent.com/65204755/183015878-368aeb46-2bb7-4b63-ab3d-aa220c8598f7.png)

![图片](https://user-images.githubusercontent.com/65204755/183016345-051e854f-2469-4257-adbd-270e98aacf86.png)

version: docker Build [220730-0e1222c83]

**Comment by lastzero** [comment]
We have an issue for Apple Pro RAW already
Must be implemented in Darktable and Rawtherapee.

**Comment by TechPorter20** [comment]
![图片](https://user-images.githubusercontent.com/65204755/183018260-a9035116-ac39-415d-af3f-ba0afd78f9dc.png)

raw is open status

**Comment by lastzero** [comment]
When you disable RAW, Raw file formats won't work in general. Note we are on vacation and this is not a support forum. You may use GitHub Discussions instead or join our Reddit Community. Thank you!

**Comment by lastzero** [comment]
The heif-convert command may also require updating as there can be compatibility issues with the latest HEIF files from Apple. A user suggested compiling our own version, but we don't have the time to do so. If you can help, feel free to send a pull request.
