### ISSUE TITLE
HEIC: Some Apple formats not suported

### ISSUE THREAD

**Issue by TechPorter20** [photoprism/photoprism#2593]
![图片](https://user-images.githubusercontent.com/65204755/183019976-3308241f-68f4-41d1-8909-3c2790448f84.png)
![图片](https://user-images.githubusercontent.com/65204755/183020063-656f2b94-8d75-45ea-beee-2bd844cf8d5c.png)
![图片](https://user-images.githubusercontent.com/65204755/183020131-cc2de47a-8228-4d7b-8f77-fa9eff7d1569.png)
![图片](https://user-images.githubusercontent.com/65204755/183020222-2f5885e5-f1c1-4b8a-bc55-83b70138f694.png)

**Comment by heikomat** [comment]
Can you provide an image file that doesn't work?

**Comment by lastzero** [comment]
The heif-convert command may require updating as there can be compatibility issues with the latest HEIF files from Apple. A user suggested compiling our own version, but we don't have the time to do so. If you can help, feel free to send a pull request or help the Debian project to ship updated packages for ARM and Intel/AMD.

**Comment by TechPorter20** [comment]
[IMG_20220703_181415.zip](https://github.com/photoprism/photoprism/files/9267366/IMG_20220703_181415.zip)
please view it .

**Comment by lastzero** [comment]
Thanks! We can take a look when back in Berlin. Feel free to contribute by sending a pull request that fixes any converter problems. As mentioned above, heif-convert may require upgrading or we should use ImageMagick instead (convert command). Help with testing is much appreciated.

**Comment by estepnv** [comment]
@lastzero pls no imagemagick. What about libvips? I could help but I need some guidance on what exactly should I change.

**Comment by lastzero** [comment]
https://demo.photoprism.app/ has been updated with the latest changes! Feel free to test your HEIC and DNG files via web upload on the demo while we get the Development Preview ready for testing (it still has some migration issues so you wouldn't be able to log in).
