### ISSUE TITLE
Number of workers doesn't seem to limit the load

### ISSUE THREAD

**Issue by Eirikr70** [photoprism/photoprism#2615]
Hello, I am the happy user of Photoprism on a Raspberry Pi. It works very fine. But when I try to import new pictures, it gets mad : the load increases and the Pi loses control. The container crashes, together with the ssh connexion, and it brings other containers to crash. I have tried to reduce the number of workers to one, but it seems to have no effect.

**Comment by lastzero** [comment]
Can you please use our official bug report template and provide complete information OR use GitHub Discussions if it might be a support question? Thank you ❤️
