### ISSUE TITLE
Search: Sort results by "File Size" and "Video Duration"

### ISSUE THREAD

**Issue by maumi** [photoprism/photoprism#2620]
I miss some sorting options for Videos like sort by Duration or sort by Size. 
I would love to see that feature

**Comment by maumi** [comment]
The Code for this is really easy and I did it already. I would also create a PR, but I am to dumb to show it on the frontend.
Maybe anyone is willing to help me. What I did in short:
-Add SortOrderBiggest in entity_const.go
-Add the sort-Case in photos.go
-->I can call it pe by URL call with order=biggest and it works as expected

For the Frontend part I did:
-Add the sorting biggest to frontend/src/dialog/album/edit.vue
-and to frontend/src/component/album/toolbar.vue
-and frontend/src/component/photo/toolbar.vue
-Maybe it was too much but it should at least be visible on the DropDown
-For the localization I also run npm run gettext-extract and added a local. in de.po and then run npm run gettext-compile to build a now translations.json
-For testing purposes I also changed an existing local. in German and rebuild photoprism but even this local. wasn't changed.

I don't run photoprism in docker, I run it like in https://github.com/IndrekHaav/photoprism-debian described

I would be really glad if anyone can point me into the right direction

**Comment by maumi** [comment]
Forget my last comment. Got the frontend working. 
Issue could be closed if no one else needs that kind of sorting. 
Otherwise I could try a PR but only with german and english locale.

**Comment by iwanzarembo** [comment]
@maumi I am new to photoprism, but I love your sorting idea. It would also be great if it would be possible to filter for videos in an album as well.

**Comment by maumi** [comment]
I think there is no filtering in albums only a sorting. You could sort by length and so Videos will be at the top.

**Comment by iwanzarembo** [comment]
Well, everything is better than nothing like at the moment.

**Comment by graciousgrey** [comment]
> I think there is no filtering in albums only a sorting.

> I am new to photoprism, but I love your sorting idea. It would also be great if it would be possible to filter for videos in an album as well.

In the search section you can use 'album:Holiday type:video' to find all videos that are part of the album with the name Holiday.

https://docs.photoprism.app/user-guide/search/filters/#filter-reference

We do also have an open issue for a search bar in albums.

When it comes to sorting for size and duration, this is of great interest for others as well.
But we need to take care of edge cases e.g. stacks

**Comment by maumi** [comment]
Can you explain the edge cases a little bit more?
In my naive understanding is a sorting by size and duration always better than a Photoprism without this sorting, even when it's not perfect in the logic.

**Comment by iwanzarembo** [comment]
@graciousgrey I have people who are end users (like my wife and kids) and they are supposed to be able to find videos. 
e.g. I have an album with 250 Images and 3 Videos. Now my Kid is navigating to Album -> Select the album and trying to find the 3 Videos beneath the 250 images. But there is no filtering at all. So she has to do it manually, which is really bad. 
It is not really user-friendly to learn the search pattern.

@maumi Does the use case make sense to you?

**Comment by maumi** [comment]
Sure. Until now I don't use Albums but in the video section it is useful to sort by duration or size. 
But it could be strange to sort photos by duration. 
I could make a PR so you can pull it for now.

**Comment by iwanzarembo** [comment]
sure, I would love to give it a try.

**Comment by graciousgrey** [comment]
@iwanzarembo Search box and filter dropdowns in albums are planned. Search filters will also be integrated into the user interface at some point. It's not that we don't want it, but development takes time. Users can do their part and become sponsors :)

> In my naive understanding is a sorting by size and duration always better than a Photoprism without this sorting, even when it's not perfect in the logic.

We do not publish features that are not suitable for all use cases, as this leads to a high support effort on our side.

Videos might be stacked and those stacked videos might have different durations/sizes. 
This is even important when you want to add the size filter for views that contain photos as well. Photos are often stacked e.g. JPG+JPG, JPG+RAW ... 
We need to determine a logic what file size should be used for the sorting. 
Feel free to create a PR and label it with work in progress. This way interested people can already pull it. Once we find time for this we can review and test it with more edge cases.

**Comment by iwanzarembo** [comment]
@graciousgrey Well I understand that development needs time, but there is always the problem of over engineering if you think too long about a feature 😄.

**Comment by lastzero** [comment]
It's not that we think too long, but have too many feature request to deliver all of them instantly.

**Comment by maumi** [comment]
@iwanzarembo: PR is created as WIP
@lastzero: just to clarify: I really love photo prism and I think it is impressive what you guys are doing.

**Comment by graciousgrey** [comment]
Thank you :)

**Comment by lastzero** [comment]
You can now test this using our [Development Preview](https://docs.photoprism.app/release-notes/#development-preview) and/or [Public Demo](https://demo.photoprism.app/library/browse)!

**Comment by maumi** [comment]
I've tested in Live Demo. 
Just to clarify: you only did a descending sorting for both?
I think to be consequent you should remove "Oldest first" or give other sorting criterias also an ascending sorting.

**Comment by lastzero** [comment]
Why would you want to find the smallest files or the shortest videos? 0 bytes, 0 seconds. Can tell you that without looking it up. It also would not help usability to have a order select as long as the actual result list. But of course it makes sense to sort from oldest to newest and vice versa.

**Comment by lastzero** [comment]
The rationale is that the higher you go, the fewer results there are. Like you would generally not search for the smallest mountain, but for the highest. People with live photos will have a ton of very short videos, potentially thousands. Why even bother sorting them by shortest duration? What is the use case?

**Comment by lastzero** [comment]
If you want to find short videos, filter for live photos and sort them by something useful like oldest or newest. If you want to find very small files and delete them all at once, use terminal commands.

**Comment by lastzero** [comment]
Since there was no further feedback on my last 3 comments (and the commit is 9 days old), we will release it as is. If you feel that you really need to find the shortest videos and smallest files, please open a new feature request and describe what problem this solves and why this would be valuable to many users.

**Comment by pippo73** [comment]
Hello all, 
I've just found this post and even if it is a little bit old, I've decidet to write here. If needed I can open a new 3d.
Actually I'm running Build 230719-73fa7bbe8 on a docker env.
I would like to know if there is some way to sort the by the size or search them with a particular resolution.
I've searched the [filter page](https://docs.photoprism.app/user-guide/search/filters/) but I have not found anything like that.
Did I missed something?

thank to all

**Comment by graciousgrey** [comment]
You can define the sort order using the sort order filter.

![SortOrderFileSize](https://github.com/photoprism/photoprism/assets/15210372/4d5659a0-a1d8-4bb4-94c6-870349314c5b)

Searching for a specific resolution or size is not possible at this time.
