### ISSUE TITLE
Specify UID and GID of photoprism user in Docker image

### ISSUE THREAD

**Issue by markusressel** [photoprism/photoprism#263]
Hey there, thx for this awesome piece of software! :+1: 

I want to run photoprism using the Docker container, which has a volume mounted via NFS share. This folder has a special group that is allowed to access the data. The `photoprism` user inside of the Docker image always has UID & GID 1000 though, which makes it difficult to do a proper user/group/permission mapping.

Is there already a way to specify the UID and GID? If not, would it be trivial to add such an option f.ex. using environment variables?

Thx

**Comment by lastzero** [comment]
Not sure, maybe we can change it on startup... building a new image is not an option for most users as it takes a long time.

**Comment by markusressel** [comment]
Yes thats how most people do it (f.ex. [Plex](https://github.com/plexinc/pms-docker), altough their approach seems unnecessarily complex to me).

**Comment by lastzero** [comment]
Would using https://github.com/boxboat/fixuid be a good solution? Other suggestions?

**Comment by markusressel** [comment]
Well...
> fixuid should only be used in development Docker containers. DO NOT INCLUDE in a production container image

**Comment by pniedzwiedzinski** [comment]
I think this could work:
https://docs.docker.com/engine/reference/run/#user

**Comment by lastzero** [comment]
I've just pushed new Dockerfiles that don't explicitly set a user, so it should be possible to use them with any uid. Note that paths and some environment variable names have changed as well to simplify installation. All files are now in `/photoprism` instead of `/home/photoprism` since there is no default user `photoprism` (uid 1000) anymore.

**Comment by markusressel** [comment]
Thx, but I get this nor:

```
```

**Comment by lastzero** [comment]
@markusressel Did you update your configuration?

Note that paths have been renamed for simplicity: `/photoprism/Pictures/Import` is `/photoprism/import` now!

Example: https://dl.photoprism.org/docker/docker-compose.yml

**Comment by markusressel** [comment]
Ah without the `Pictures` too, sorry, I did miss that.
It does start now, but first I see this error in the Webinterface log:

```
2020-03-24 12:09:32 ERRO settings file not found: "/photoprism/~/.config/photoprism/settings.yml"
```
Seems like a mix of absolute and relative paths there. I have specified `PHOTOPRISM_ORIGINALS_PATH`, `PHOTOPRISM_IMPORT_PATH` and `PHOTOPRISM_EXPORT_PATH` to point to the `/photoprism/<something>` location, should I remove those?

And secondly, the group of the user inside the container can still not be changed (now it is GID 0 - `root`), which is what I would need to allow more than just one user to access the NFS share.

**Comment by lastzero** [comment]
Does this work for you? https://dev.to/acro5piano/specifying-user-and-group-in-docker-i2e

You should be able to specify a user in docker-compose.yml:

```
user: "${UID}:${GID}"
```

**Comment by lastzero** [comment]
Did you pull our latest docker image? 

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile

As you can see, `PHOTOPRISM_CONFIG_FILE` points to `/photoprism/config/photoprism.yml`

If you have everything configured using env variables, you don't need a config file and can ignore the warning.

**Comment by markusressel** [comment]
The error message related to the `PHOTOPRISM_CONFIG_FILE` option seems to have disappeared, maybe I was too quick or the cluster didn't pull the newest image (although it always should, automatically).

I am not using docker directly but a Kubernetes through Rancher, so the setup is a bit different.
According to [this](https://stackoverflow.com/a/51445080/1941623) I can use the `runAsUser` and `fsGroup` parameters to specify `UID` and `GID`. Although the output of `id` when I run it inside the container is a bit wonky:
```
groups: cannot find name for group ID 1103
I have no name!@photoprism-89fd645c9-79kfb:/photoprism$ id
uid=1103 gid=0(root) groups=0(root),1103
```
Photoprism now **does** have access to the files in the NFS share.

So it seems like it is working now, not sure if you want more input from other users using Docker directly, but imo this issue is resolved.

**Comment by lastzero** [comment]
On Linux, Docker shares the kernel with the host. So user and group ids should work, you just can't look up their names.

I'll close this. Thank you!
