### ISSUE TITLE
UI: Wrong german translation of "Panoramas"

### ISSUE THREAD

**Issue by Sanookmakmak** [photoprism/photoprism#2638]
German translation should be "Panoramen"

https://www.duden.de/rechtschreibung/Panorama

![grafik](https://user-images.githubusercontent.com/24833757/186165896-8cc4ffa0-ee22-4557-95f1-2994e691074c.png)

**Comment by lastzero** [comment]
You should be able to change this on your own at https://translate.photoprism.app/.

See: https://docs.photoprism.app/developer-guide/translations-weblate/

**Comment by gagnonraphael** [comment]
String changed in https://translate.photoprism.app/

**Comment by graciousgrey** [comment]
Thank you both :)
