### ISSUE TITLE
Add Docker Build/Image for arm32v7

### ISSUE THREAD

**Issue by brokencode64** [photoprism/photoprism#264]
Could you please add a build for arm32v7 to Dockerhub?

**Comment by pniedzwiedzinski** [comment]
I have a similar issue in my other project and I ended up creating workflow on github actions that would use buildx to build image on different architectures. It works great.

**Comment by lastzero** [comment]
We could only offer reduced functionality on 32 bit as darktable-cli is only available for 64 bit on ARM (maybe some other dependencies too).

**Comment by lastzero** [comment]
Sorry, we won't have time to deliver an arm32v7 image in the near future. Contributions welcome!

Note that creating thumbnails and indexing requires significant resources. If you can, get at least a Raspberry 4 with 4 GB of RAM and fast SD Card or an Intel/AMD-based mini PC with SSD. For testing, a regular PC or Mac with Docker will do.

**Comment by dddddddavid** [comment]
> Sorry, we won't have time to deliver an arm32v7 image in the near future. Contributions welcome!
> 
> Note that creating thumbnails and indexing requires significant resources. If you can, get at least a Raspberry 4 with 4 GB of RAM and fast SD Card or an Intel/AMD-based mini PC with SSD. For testing, a regular PC or Mac with Docker will do.

Just as an aside, a 2GB Pi4 works fine with an increased swapfile even on large (17GB) photo libraries, but maxes out memory while importing/indexing with standard swap size.

**Comment by lastzero** [comment]
@dddddddavid Excellent 👍  

I'll close this for now since we don't have resources to do it and nobody contributed.
