### ISSUE TITLE
Videos: Extract local time from DateTimeOriginal if possible

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2640]
**As a Canon PowerShot owner, I would like the local time for my videos to be extracted from the `DateTimeOriginal` Exif field if possible, as they may not have GPS coordinates to calculate the local time from the UTC `CreateDate`.**

Sample Files:

- https://dl.photoprism.app/samples/QuickTime/MVI_1724.MOV
- https://raw.githubusercontent.com/photoprism/photoprism/develop/internal/meta/testdata/MVI_1724.MOV.json

Acceptance Criteria:

- [x] The correct local time based on `DateTimeOriginal` is displayed in the UI after indexing
- [x] Unit Tests for the `meta` package have been added

**Comment by dror3go** [comment]
Should a complete rescan be performed in order to test this?

**Comment by lastzero** [comment]
> Should a complete rescan be performed in order to test this?

You may limit the rescan to folders that contain videos or other files with extended metadata, e.g. complex timestamps from different sources. It is also possible to test with our demo, as it is always based on our latest preview.

**Comment by dror3go** [comment]
@lastzero Looks good to me!
