### ISSUE TITLE
Browser Lag on places with too many photos.

### ISSUE THREAD

**Issue by bubundas17** [photoprism/photoprism#2653]
Hi, I imported all images from Google Photos Takeout a few days back.
Everything works fine. But after importing, if I open up the Locations section and Zoom enough to my home city. There are more than 15K images taken within a 0.5-mile circle. And if I zoom in at that location, The browser hangs up, making it impossible to do anything.

**Comment by heikomat** [comment]
Have a look at https://github.com/photoprism/photoprism/issues/1187
Especially [this comment](https://github.com/photoprism/photoprism/issues/1187#issuecomment-1207298386)

**Comment by lastzero** [comment]
Closing this as duplicate. We are aware that such edge cases can be a problem, so we are already working on a solution as part of this issue:
- #1187
