### ISSUE TITLE
New install hangs on requesting maps + places API key

### ISSUE THREAD

**Issue by gcushen** [photoprism/photoprism#2654]
#### 1. What is not working as documented?

New install hangs on requesting maps + places API key:

```
mariadb_1     | 2022-08-27 13:45:29 0 [Note] mysqld: ready for connections.
mariadb_1     | Version: '10.8.4-MariaDB-1:10.8.4+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
photoprism_1  | time="2022-08-27T13:45:30Z" level=debug msg="config: running on [X]"
photoprism_1  | time="2022-08-27T13:45:30Z" level=debug msg="settings: saved to /photoprism/storage/config/settings.yml "
photoprism_1  | time="2022-08-27T13:45:30Z" level=debug msg="config: requesting new api key for maps and places"
photoprism_1  | time="2022-08-27T13:47:00Z" level=debug msg="config: Post \"https://hub.photoprism.app/v1/hello\": dial tcp 5.9.32.79:443: i/o timeout (init backend api tokens)"
```

After this, there are no more logs.

#### 2. How can we reproduce it?

```
wget https://dl.photoprism.app/docker/docker-compose.yml

# set debug option to true in docker-compose.yml

docker-compose up -d
```

#### Env

Ubuntu 22.04.1 LTS

`docker-compose version`:

```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.4
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```

**Comment by lastzero** [comment]
Check your firewall & network. The services are needed for retrieving geodata while indexing, so you typically don't want it to fail silently.

**Comment by gcushen** [comment]
Thank you, it appeared that the Ubuntu UFW firewall may have been blocking the POST request to `https://hub.photoprism.app/v1/hello`. All working now 🎉

**Comment by gcushen** [comment]
@lastzero are the required firewall settings documented anywhere? If not, users might find it helpful to know which ports Photoprism requires open?

I can find references to "firewall" in the docs, but no elaboration on what's actually required.

**Comment by lastzero** [comment]
It's right here in the **System Requirements**:

https://docs.photoprism.app/getting-started/#external-services

**Comment by lastzero** [comment]
You don't need to open a port, just allow connections to those servers operated by us. See the documentation and privacy policy for details. Most users don't have such strict rules (or no firewall at all) and those who do should know what they are doing.

**Comment by lastzero** [comment]
I have further improved our documentation to explicitly mention firewalls, and also added an entry in our FAQs. Hope this helps!

Providing explicit configuration instructions for various firewall applications is beyond our capabilities. However, we are thankful for contributions.
