### ISSUE TITLE
Non monochrome images appear in monochrome tab

### ISSUE THREAD

**Issue by danielandastro** [photoprism/photoprism#2657]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?
When I open the monochrome tab in search. non monochrome images appear
Please be as specific as possible and explain what part of the software is not [working as documented](https://docs.photoprism.app/). "No photos found" would not be detailed enough. Also, never report [known issues](https://docs.photoprism.app/known-issues/) or [features not yet implemented](https://github.com/photoprism/photoprism/issues) as bugs. Thank you!

#### 2. How can we reproduce it?

1. Go to 'photoprism'
2. Click on 'monochrome'
3. Colour images appear
#### 3. What behavior do you expect?

Give us a clear and concise description of what you expect.

#### 4. What could be the cause of your problem?

Always try to determine the cause of your problem using the checklists at <https://docs.photoprism.app/getting-started/troubleshooting/> before submitting a bug report.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Yes

![PhotoPrism and 11 more pages - Personal - Microsoft​ Edge 28_08_2022 18_42_38](https://user-images.githubusercontent.com/28220506/187087744-88ae5699-cd54-4411-bca1-037cb662ef45.png)
(Screenshot edited to remove girlfriend and personal details)

Visit <https://docs.photoprism.app/getting-started/troubleshooting/browsers/> to learn how to diagnose frontend issues.

**Important: If it is an import, indexing or metadata issue, we require sample files and logs from you.** Otherwise, we will not be able to process your report. If it is an import problem specifically, please always provide us with an archive of the files before you imported them so we can reproduce the behavior.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, 220730-0e1222c83

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux (Ubuntu server), using docker-compose

(d) Browser Types & Versions: Microsoft edge

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 7. On what kind of device is PhotoPrism installed?
Docker on server
This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Intel Core i7-6700

(b) Physical Memory & Swap Space in GB: 16 GB & 8 GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage, ZFS on spinning disks

(d) Anything else that might be helpful to know?

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

NPM

*Always provide this information when you have a reliability, performance, or frontend problem, such as failed uploads, connection errors, broken thumbnails, or video playback issues.*

**Using NGINX?** Please also provide the configuration and/or consider asking the NGINX community for advice as we do not specialize in supporting their product. Docs can be found at <https://docs.photoprism.app/getting-started/proxies/nginx/>.

**Comment by lastzero** [comment]
It's low chroma to be exact, can't change this for now but you may contribute and provide this as improvement if strickly no colors is important to you. There might be related issues including a full discussion for why that is.
