### ISSUE TITLE
Feature Request: Select All Visible button

### ISSUE THREAD

**Issue by plague69** [photoprism/photoprism#2662]
I see that this has been discussed in #845 and #272 where a "Select All" is not likely due to infinite scroll, but how about a button "Select visible"?

Currently my workaround is this: (click() or dispatch event click does not work for some reason...)
`let pl = $$('.is-photo'), plist = new Array();  
for (i in pl) {  
  plist.push(pl[i].dataset['uid']);  
}  
localStorage.setItem('photo_clipboard', JSON.stringify(plist));  
location.reload();`

**Comment by graciousgrey** [comment]
How would you define visible in this case? 
All photos that have been loaded or all photos that are visible on your screen - which might be just one or two on mobile?

**Comment by plague69** [comment]
> How would you define visible in this case? All photos that have been loaded or all photos that are visible on your screen - which might be just one or two on mobile?

Everything in the viewport section/visible to the user even partially. My snippet doesn't do this of course, it was just quick and dirty

**Comment by crazyvral** [comment]
Currently you can only select up to 999 items in both desktop and mobile PWA.

In the desktop you can still use the shift key to select up to 999 items. 
You can replicate this behavior in the mobile PWA, at least for android, by selecting the first item then long press the last item you want to select. Everything in between will be selected up to 999 items.

**Comment by plague69** [comment]
That solves the problem for now. Thank you
