### ISSUE TITLE
Store converted JPEGs in a seperate directory

### ISSUE THREAD

**Issue by garrettdowd** [photoprism/photoprism#268]
# Issue
I would like to leave my RAW photo directory untouched while still being able to view the photos with photoprism. Currently, this does not seem possible. The indexing process includes the option to convert RAW to JPEG, but stores the JPEG files in the same directory as the RAW files. The Import process also copies/duplicates the RAW files, which would obliterate my remaining free HDD space.

# Solution
1) I do not know Go and I have not looked at the codebase, but I hope it would not be too difficult to store the JPEGs in a separate directory from the RAW/Original files. This would be similar to how thumbnails are currently handled.
2) I could run an external RAW->JPEG conversion process from my RAW directory to the Photos/Originals directory in Photoprism. However, I do not know of a good way to do this in an incremental fashion (without re-exporting the entire RAW library every time) and I am not entirely sure that all of the EXIF/metadata would be preserved.

### My Photo Collection
I have 2TB of RAW photos which I maintain in a specific directory structure (from exiftool) for archival purposes. The collection is stored on a slower disk array (5400rpm HDD) because I do not access them frequently. Additionally, some of these photos have been edited and exported from Lightroom/Darktable as JPEG in the same directory as the RAW photos. I see Photoprism as a great way to search through all of these photos based on location and image recognition, something that would make this massive photo library much more useful.

**Comment by lastzero** [comment]
Did you read https://github.com/photoprism/photoprism/wiki/Converting-RAW-to-JPEG?

**Comment by garrettdowd** [comment]
> Did you read https://github.com/photoprism/photoprism/wiki/Converting-RAW-to-JPEG?

I did not. Unfortunately, I was only referencing the website. Thank you for referencing this.

I mostly agree (especially with the following point)
> 20 years from now, it's probably easier to open a JPEG than render a proprietary RAW file again in good quality.

and I like the idea to..
> Idea: Put converted images in cache/converted by default with an option to automatically move / copy them to the originals directory. Feedback welcome.
At the very least this would solve my current issues/complaints

However, I do have some differing opinions.
1) **Full-size JPEG renders can take up a lot of space** as mentioned. I assume most people, most of the time do not need to view their photos at a resolution higher than 4K (8mp). If I want to really zoom in on a photo or download a full-res jpeg, I wouldn't mind if the server took a few seconds to dynamically generate a full resolution JPEG that is discarded during a daily/weekly trash dump. Having 4K JPEG renders of my RAW files would satisfy 90%+ of my use cases and it would be faster to load over slow connections. (Make this an option when indexing/importing?)
2) **Storage type makes a big difference at scale and storing RAW files on slower storage is cheaper**. I do not want/need fast access to my RAW files once I am done with initial edits. Therefore all of the RAW files are stored on slower spinning disk arrays that are often spun down. Accessing the RAW photo directory can mean waiting for all the disks to spin up. For photoprism (or any other photo viewer), I want the photos to load quickly so I would keep them stored on a faster set of disks or SSDs that have different spin-down settings.
3) If I am going to archive my RAW files in JPEG format then I would probably want to have more control over that process. It doesn't seem like photoprism should be the software to make the RAW->JPEG decision for archival purposes given the large amount of information loss.

Other thoughts
1) **Creating a separate directory for the converted JPEGs that is a mirror structure of the RAW directory would make it easier to merge the directories if needed.** Separating RAW and JPEG in the same directory is not as easy as the RAW directory might include specific JPEG edits that should not be deleted. Therefore, deleting all of the JPEG images in the RAW would not be possible and it could be difficult to tell which JPEGs to keep and which to discard.
2) What to do with existing full-size JPEGs in the RAW directory? If JPEG and RAW are stored in the same directory then the existing JPEG could be used if space or processing time is valued. If speed is valued then those existing JPEGs could also be optimized for web viewing (bit-depth, higher compression, reduced resolution, etc)

Thoughts?

**Comment by lastzero** [comment]
Did not forget about this, still busy with other issues :)

**Comment by lastzero** [comment]
In a first step, automatically converted files are now created in a `.photoprism` subdirectory so that they don't get mixed with manually created files.

**Comment by sam2kb** [comment]
I have a 3TB+ of photos, half of them is RAW and I use Photoprism in read only mode. I like the fact that I can provide a separate docker volume for thumbnails, would love to see converted RAW images handled the same way.

> Idea: Put converted images in cache/converted by default with an option to automatically move / copy them to the originals directory. Feedback welcome.
This is by far the best option because thumbnails are served from /cache directory and it's a great idea to have both directories together in one place.

**Comment by sam2kb** [comment]
It would be great if the `index` script would skip all RAW images when the `read only mode`  is on instead of reading them one by one and trying to create a sidecar directory in a read only folder.

Currently it wastes a ton of time doing that, it's being running for 2 days already :(
```
mkdir /photoprism/originals/my/path/.photoprism: read-only file system
INFO[2020-05-29T01:18:26Z] convert: my/path/DSC_7165.NEF ->  
ERRO[2020-05-29T01:18:30Z] index: creating jpeg failed ([defaults] found a 64-bit system with 24682776 kb ram and 8 cores (0 atom based)
[defaults] setting very high quality defaults
unknown extension '.PATH=/photoprism/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
)
```

**Comment by sam2kb** [comment]
Just checked the code and it seems I should NOT be getting those errors providing I set the read only mode properly. I'll need to reconfirm my ENV variables.

```go
func (c *Convert) ToJpeg(image *MediaFile, hidden bool) (*MediaFile, error) {
	if c.conf.ReadOnly() {
		return nil, errors.New("convert: disabled in read-only mode")
	}
```

**Comment by venikx** [comment]
Not sure I'm setting something wrong, or not, but this doesn't seem fixed. Or was it decided that jpg's will always live next to the original files? It's quite bothersome, especially when dealing with HEIC files, as I can't simply delete all the jpgs from the folder as in the same folder there might jpg's stored (images coming from WhatsApp for example).

**Comment by lastzero** [comment]
Generated JPEG files are stored in the sidecar folder, not the originals folder. Unless you have configured both folders to be the same, which is not our default.
