### ISSUE TITLE
The sidecar `.yml` metadata conflict for photo and video that sharing the same name like `IMG_0557.jpg` and `IMG_0557.MOV`

### ISSUE THREAD

**Issue by ziq211** [photoprism/photoprism#2695]
#### 1. What is not working as documented?

When photos and videos have the same name, although different name extension, like `IMG_0557.jpg` and `IMG_0557.MOV`. Only one sidecar .yml metadata `IMG_0557.yml` will be created and it favors the video file and hence make the jpg file not searchable.

#### 2. How can we reproduce it?

Index one photo file and one video file with same name like `IMG_0557.jpg` and `IMG_0557.MOV`

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
PhotoPrism® CE
Build 220901-f493607b0

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
MariaDB

(c) Operating System Types & Versions: Linux, Windows, Android,...
Docke in Macbook

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
No

You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
No

**Comment by lastzero** [comment]
https://docs.photoprism.app/getting-started/faq/#what-are-sidecar-files-and-where-do-i-find-them

**Comment by lastzero** [comment]
https://docs.photoprism.app/getting-started/faq/#what-are-sidecar-files-and-where-do-i-find-them

**Comment by ziq211** [comment]
Hi @lastzero , may be I was not clear in the original description. I do think this is a bug, please allow me to rephrase it a little bit.
### Issue
When you have one JPG file named like `IMG_001.JPG` and one video file named like `IMG_001.MOV`, after the indexing, in the folder you will see only one file instead of two files. The thumbnail of the file is the jpg content, but once you click into it the mov video will be displayed.
### It can be simply reproduced

- Prepare two files `IMG_001.JPG` and `IMG_001.MOV` in a folder called `photo_test`. Mount the folder to the docker as `/photoprism/originals/photo_test`

<img width="749" alt="image" src="https://user-images.githubusercontent.com/9372106/189827693-5b3dbd86-c339-4d6d-bbe7-e8afeb832506.png">
<img width="744" alt="image" src="https://user-images.githubusercontent.com/9372106/189828103-48329174-cc09-4dbb-99c6-69857c7fd326.png">

- Index the `/photo_test`

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/9372106/189828256-ec382c1d-9090-4c79-bca1-62484130d8a8.png">

- Now in `/phot_test` folder, you will only see one file which thumbnail is the image content.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/9372106/189828462-63d556ec-709d-48fd-8bb5-7cddcffd5505.png">

- But once you click into it, the video is played

<img width="1454" alt="image" src="https://user-images.githubusercontent.com/9372106/189828649-62c62183-fb06-4cbd-b8a3-c3e65bd7294b.png">

**Comment by ziq211** [comment]
Here are two sample file you can use to reproduce the issue:


https://user-images.githubusercontent.com/9372106/189829496-b0714772-98a9-44f2-99bf-5f66e2257a4d.MOV

![IMG_001](https://user-images.githubusercontent.com/9372106/189829504-56b58070-5f0f-456b-85f5-333784017635.JPG)

**Comment by lastzero** [comment]
https://docs.photoprism.app/user-guide/organize/stacks/#for-what-reasons-can-files-be-stacked

**Comment by ziq211** [comment]
Ha, got it! Thanks!
