### ISSUE TITLE
Arm64 docker image outdated

### ISSUE THREAD

**Issue by crisidev** [photoprism/photoprism#270]
Hello,
I noticed the x86 image is getting pushed regularly while the arm64 is now almost 30 days behind.. is there a possibility to update also amd64? My raspberry pi is eager to deploy the latest version :)

Thanks for the awesome job!

**Comment by lastzero** [comment]
Thanks for the reminder... Going to release a new one soon. Right now, we primarily work on sharing, but it's not ready yet.

**Comment by crisidev** [comment]
Thanks a lot!

**Comment by lastzero** [comment]
About to push a new image. Note that default paths have changed from `/home/photoprism` to `/photoprism`, see #263.

**Comment by lastzero** [comment]
Also you might need to re-index as database structure changed. Moved photo descriptions to a separate table to improve search performance.

**Comment by crisidev** [comment]
Yep, i noticed that, I am running the index now, it will take a bit.

**Comment by lastzero** [comment]
Pushed multiple times today. Make sure to use the latest image. Lots of UX improvements.

**Comment by lastzero** [comment]
FYI: Can't build new Pi images right now as we upgraded to TensorFlow 1.15. Need to build new TF libs for ARM64 first.
