### ISSUE TITLE
Videos: Fix installation of Intel Quick Sync drivers for hardware transcoding

### ISSUE THREAD

**Issue by CDeLeon94** [photoprism/photoprism#2700]
#### 1. What is not working as documented?

When attempting to playback videos, hardware accelerated transcoding is not utilized

#### 2. How can we reproduce it?

Play a video above the transcode threshold bitrate

#### 3. What behavior do you expect?

Video will playback quickly, utilizing the hardware acceleration, no massive CPU spike (and associated heat and fans)

#### 4. What could be the cause of your problem?

The lack of the `libmfxgen1` library seems to be the issue: https://github.com/blakeblackshear/frigate/issues/3170

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Trace level logging `Error initializing an internal MFX session: unsupported (-3)` brought me to the above issue. 

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 Build 220902-62aba3200

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux (Unraid Docker)

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Intel 12th Generation i3-12100

## Potential Fix

In the docker containers I ran `apt install libmfx-gen-dev` and after I got a successful 
```
time="2022-09-13T17:19:16-05:00" level=trace msg="/bin/ffmpeg -qsv_device /dev/dri/renderD128 -i /photoprism/originals/2021/07/20210727_205222_3F593A37.mp4 -c:a aac -vf format=rgb32 -c:v h264_qsv -vsync vfr -r 30 -b:v 75M -bitrate 75M -f mp4 -y /photoprism/storage/sidecar/2021/07/20210727_205222_3F593A37.mp4.avc"
time="2022-09-13T17:19:24-05:00" level=info msg="h264_qsv: created 20210727_205222_3F593A37.mp4.avc [7.982165846s]"
```

Further reading, I stumbled across other docker containers that incorporate quicksync and support for the latest intel CPUs:
https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/docker-build.sh#L230-L262

https://bugs.launchpad.net/ubuntu/+source/ffmpeg/+bug/1970637

**Comment by lastzero** [comment]
Do I understand correctly that we only need to install one additional package to make it work for you? Have you tested it with our latest release, which is now based on Ubuntu 22.04 LTS? See [Release Notes](https://docs.photoprism.app/release-notes/#november-2-2022) and [Transcoding Documentation](https://docs.photoprism.app/getting-started/advanced/transcoding/).

**Comment by CDeLeon94** [comment]
> Do I understand correctly that we only need to install one additional package to make it work for you? Have you tested it with our latest release, which is now based on Ubuntu 22.04 LTS? See [Release Notes](https://docs.photoprism.app/release-notes/#november-2-2022) and [Transcoding Documentation](https://docs.photoprism.app/getting-started/advanced/transcoding/).

I did this in the 220902-62aba3200 preview-ubuntu release

Edit: So install 1 additional package, and I had to map the `/dev/dri/` device into the docker container

**Comment by lastzero** [comment]
Is it still necessary in the latest release? I would appreciate if you can test it for us as we have limited resources and need to delay the requested changes until next year otherwise.

**Comment by CDeLeon94** [comment]
Confirmed that adding `libmfx-gen-dev` was necessary to get `h264_qsv` transcode on `221105-jammy Build 221105-7a295cab4`

**Comment by lastzero** [comment]
Thanks! I'll add it then, unless the package size is unexpectedly huge.

**Comment by lastzero** [comment]
So the installed size unfortunately is 27,346.0 kB, which is too large to ship it to everyone by default. In that case, we could install it if you set `PHOTOPRISM_INIT="gpu"`.

**Comment by lastzero** [comment]
An updated preview build will be available for testing soon:

- https://docs.photoprism.app/release-notes/#development-preview

Make sure to also read these docs, which have been updated as well:

- https://docs.photoprism.app/getting-started/advanced/transcoding/#gpu-drivers

We hope you have a few minutes to let us know if it works so we can release this in our next update!

**Comment by lastzero** [comment]
@CDeLeon94 Happy testing! :gift:

**Comment by lastzero** [comment]
We have just added a separate section about Intel Quick Sync to our documentation:

- https://docs.photoprism.app/getting-started/advanced/transcoding/#intel-quick-sync

If you are not able to test our preview, we will release the changes so you can test them in production. However, I can't tell you when we will release the next update if you need changes.

**Comment by lastzero** [comment]
Released. Please read the documentation and let us know if it works as described. Thank you!

**Comment by CDeLeon94** [comment]
Yes, using your implementation via the `intel` target for `PHOTOPRISM_INIT` works as expected. 

Thanks so much :-)
