### ISSUE TITLE
Docker: Fix Ubuntu Jammy image

### ISSUE THREAD

**Issue by baurmatt** [photoprism/photoprism#2704]
(Sorry for deleting the template, it doesn't feel appropriate for this kind of bug report)

The latest Ubuntu jammy image being available on Docker Hub is [220730-jammy](https://hub.docker.com/layers/photoprism/photoprism/220730-jammy/images/sha256-2413025db38474b2a2d8e61ea6a3010fb8c9bc713a20df371da72988d871685b?context=explore). There was no new image released for [220901](https://github.com/photoprism/photoprism/releases/tag/220901-f493607b0).

**Comment by lastzero** [comment]
We are aware of that. It is because the build process was not compatible with the Dockerfile. This has been fixed in the preview image (which is now based on Jammy by default).

**Comment by lastzero** [comment]
A new preview build will be available soon, it also includes Darktable v4.0.1:

https://docs.photoprism.app/release-notes/#development-preview

**Comment by baurmatt** [comment]
Thanks @lastzero! :) You're taking about the [preview-ubuntu](https://hub.docker.com/layers/photoprism/photoprism/preview-ubuntu/images/sha256-de832aa2b6b680dc33a85d1b678e58034bfb5c55a8f6eacac26f2a1730e7c079?context=explore) tag, right? Asking because there is a [preview-jammy](https://hub.docker.com/layers/photoprism/photoprism/preview-jammy/images/sha256-a39b17ff4b84a90f9b6ea039eef4b6ef5eed895b1b7061b4d2cd0d804ef3fed6?context=explore) tag that hasn't been updated in 2 months.

**Comment by lastzero** [comment]
There's only one preview, it's based on Jammy. The other tags could be deleted. We used them when the default was Debian, not Ubuntu.
