### ISSUE TITLE
Albums: Don't save to YAML every time the background worker runs

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2705]
**The moments background worker currently calls `BackupAlbums()` on every execution, which can result in many album YAML backup files being written every 15 minutes, causing high CPU and disk load.**

Since the album backups are updated anyway when changes are made, this is not strictly necessary. Users can also run the backup CLI command for this if they want to make sure they have a full backup.

**Comment by jayme-github** [comment]
Thanks!
FWIW: This only works after the user has created at least one album (as that triggers the creation of the `entity.AlbumDefault` directory). Not sure if that's intended.

**Comment by lastzero** [comment]
The current detection mechanism is quite simple and could be replaced e.g. by a lock file. Feel free to submit a pull request.
