### ISSUE TITLE
SQLite: Add busy timeout preset to reduce locking errors when indexing

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2707]
**Based on the advice in https://github.com/photoprism/photoprism/issues/392#issuecomment-1237120280 by @lapo-luchini, we will add `?_busy_timeout=5000` to the default SQLite DSN.**

Is there anything else that might be helpful? At https://pkg.go.dev/github.com/mattn/go-sqlite3#section-readme you will find an overview of the parameters.

I've also seen advice to set `sqlite_unlock_notify` at compile time, but I haven't figured out what it really does, whether we should use it or if it's a [Gitea-specific build tag](https://docs.gitea.io/en-us/hacking-on-gitea/#building-gitea-basic) that otherwise has no effect?

We just got back from vacation, so I'm pretty busy and don't have much time to read through the documentation. Help is much appreciated! :+1:

**Comment by jan666** [comment]
My database is almost always locked so I'd like to test it. Is there an easy way to add this to the DSN?

**Comment by lapo-luchini** [comment]
> Is there anything else that might be helpful?

Mhh, I haven't tested it on my installation yet, but this should be a nice scenario for WAL usage, I quote [from official documentation](https://sqlite.org/wal.html):

> There are advantages and disadvantages to using WAL instead of a rollback journal. Advantages include:
>
> 1. WAL is significantly faster in most scenarios.
> 2. WAL provides more concurrency as readers do not block writers and a writer does not block readers. Reading and writing can proceed concurrently.
> 3. Disk I/O operations tends to be more sequential using WAL.
> 4. WAL uses many fewer fsync() operations and is thus less vulnerable to problems on systems where the fsync() system call is broken. 
>
> But there are also disadvantages:
> …
>
> 6. WAL might be very slightly slower (perhaps 1% or 2% slower) than the traditional rollback-journal approach in applications that do mostly reads and seldom write.
> 7. There is an additional quasi-persistent "-wal" file and "-shm" shared memory file associated with each database, which can make SQLite less appealing for use as an [application file-format](https://sqlite.org/appfileformat.html).
> 8. There is the extra operation of [checkpointing](https://sqlite.org/wal.html#ckpt) which, though automatic by default, is still something that application developers need to be mindful of.

**Comment by lapo-luchini** [comment]
> My database is almost always locked so I'd like to test it. Is there an easy way to add this to the DSN?

I'm on FreeBSD so YMMV but I'm using this in my `/etc/rc.conf`:

    photoprism_enable="YES"
    photoprism_assetspath="/var/db/photoprism/assets"
    photoprism_storagepath="/var/db/photoprism/storage"
    photoprism_args="--site-url=https://(DOMAIN)/ --dsn=/var/db/photoprism/storage/index.db?_busy_timeout=5000"

This leads to a process running like this:

    /usr/local/bin/photoprism
        --defaults-yaml=
        --assets-path=/var/db/photoprism/assets
        --storage-path=/var/db/photoprism/storage
        --originals-path=/var/db/photoprism/storage/originals
        --import-path=/var/db/photoprism/storage/import
        --site-url=https://(DOMAIN)/
        --dsn=/var/db/photoprism/storage/index.db?_busy_timeout=5000 start

**Comment by lapo-luchini** [comment]
I'm currently trying `?_timeout=5000&_journal=WAL` and works fine.

Can't say I notice much difference with only using `?_timeout=5000` but it's definitely doing as instructed (`index.db-shm` and `index.db-wal` files were created) so I guess it's worth keeping the option given the above pro/cons.

**Comment by jan666** [comment]
I added it yesterday. Was great for the first hours, but now it's back:

```
$ grep -i lock /var/log/messages
Oct 17 13:30:27 photoprism photoprism[2625]: time="2022-10-17T13:30:27+02:00" level=error msg="faces: database is locked (update covers)"
Oct 17 13:31:34 photoprism photoprism[2625]: time="2022-10-17T13:31:34+02:00" level=error msg="faces: database is locked (update marker)"
Oct 17 13:41:07 photoprism photoprism[2625]: time="2022-10-17T13:41:07+02:00" level=warning msg="faces: database is locked while updating marker mrje2881dycac6pf match timestamp"
Oct 17 13:41:12 photoprism photoprism[2625]: time="2022-10-17T13:41:12+02:00" level=warning msg="faces: database is locked while updating marker mrje2891127cu2px match timestamp"
Oct 17 13:41:17 photoprism photoprism[2625]: time="2022-10-17T13:41:17+02:00" level=warning msg="faces: database is locked while updating marker mrje28glv432izri match timestamp"
Oct 17 13:41:22 photoprism photoprism[2625]: time="2022-10-17T13:41:22+02:00" level=warning msg="faces: database is locked while updating marker mrje2ax2n10qncfy match timestamp"
Oct 17 13:41:28 photoprism photoprism[2625]: time="2022-10-17T13:41:28+02:00" level=warning msg="faces: database is locked while updating marker mrje2b72c0sj0zpg match timestamp"
Oct 17 13:41:33 photoprism photoprism[2625]: time="2022-10-17T13:41:33+02:00" level=warning msg="faces: database is locked while updating marker mrje2bf273gg3cbk match timestamp"
Oct 17 13:41:38 photoprism photoprism[2625]: time="2022-10-17T13:41:38+02:00" level=warning msg="faces: database is locked while updating marker mrje2bg2gaxdhfc4 match timestamp"
Oct 17 13:41:43 photoprism photoprism[2625]: time="2022-10-17T13:41:43+02:00" level=warning msg="faces: database is locked while updating marker mrje2bo5uotthm47 match timestamp"
Oct 17 13:41:48 photoprism photoprism[2625]: time="2022-10-17T13:41:48+02:00" level=warning msg="faces: database is locked while updating marker mrjckkf1go9np917 match timestamp"
Oct 17 13:41:53 photoprism photoprism[2625]: time="2022-10-17T13:41:53+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:41:58 photoprism photoprism[2625]: time="2022-10-17T13:41:58+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:04 photoprism photoprism[2625]: time="2022-10-17T13:42:04+02:00" level=warning msg="faces: database is locked while updating marker mrje2c5f6uhj07st match timestamp"
Oct 17 13:42:09 photoprism photoprism[2625]: time="2022-10-17T13:42:09+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:14 photoprism photoprism[2625]: time="2022-10-17T13:42:14+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:19 photoprism photoprism[2625]: time="2022-10-17T13:42:19+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:24 photoprism photoprism[2625]: time="2022-10-17T13:42:24+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:29 photoprism photoprism[2625]: time="2022-10-17T13:42:29+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:35 photoprism photoprism[2625]: time="2022-10-17T13:42:35+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:40 photoprism photoprism[2625]: time="2022-10-17T13:42:40+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:45 photoprism photoprism[2625]: time="2022-10-17T13:42:45+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:50 photoprism photoprism[2625]: time="2022-10-17T13:42:50+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:42:55 photoprism photoprism[2625]: time="2022-10-17T13:42:55+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:43:00 photoprism photoprism[2625]: time="2022-10-17T13:43:00+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:43:44 photoprism photoprism[2625]: time="2022-10-17T13:43:44+02:00" level=warning msg="faces: database is locked while updating marker mrjclex3klgwnq1s match timestamp"
Oct 17 13:44:04 photoprism photoprism[2625]: time="2022-10-17T13:44:04+02:00" level=warning msg="faces: database is locked while updating marker mrjccea21s1j9mcs match timestamp"
Oct 17 13:44:14 photoprism photoprism[2625]: time="2022-10-17T13:44:14+02:00" level=warning msg="faces: database is locked (clear marker face)"
Oct 17 13:44:26 photoprism photoprism[2625]: time="2022-10-17T13:44:26+02:00" level=warning msg="faces: database is locked while updating marker mrjclex3klgwnq1s match timestamp"
Oct 17 13:44:31 photoprism photoprism[2625]: time="2022-10-17T13:44:31+02:00" level=warning msg="faces: database is locked while updating marker mrjccea21s1j9mcs match timestamp"

```

I *think* it's better than before but not super great

**Comment by lastzero** [comment]
You can reduce the number of workers if tuning Sqlite for concurrency doesn't work. What kind of storage do you use?

**Comment by jan666** [comment]
I added --workers=2 now.

I'm running Photoprism in a FreeBSD Jail on ZFS (RAIDZ on HDDs).

**Comment by lastzero** [comment]
So HDDs have high latency compared to SSDs. That may explain why the new settings don't help much.

**Comment by jan666** [comment]
> I added --workers=2 now.

Restarted, logged in, started indexing one folder (did nothing else on the UI):

```
Oct 18 07:27:31 photoprism photoprism[12815]: time="2022-10-18T07:27:31+02:00" level=info msg="classify: loading labels from labels.txt"
Oct 18 07:27:35 photoprism photoprism[12815]: time="2022-10-18T07:27:35+02:00" level=info msg="index: found no .ppignore file"
Oct 18 07:28:11 photoprism photoprism[12815]: time="2022-10-18T07:28:11+02:00" level=info msg="index: found no new or modified files"
Oct 18 07:28:21 photoprism photoprism[12815]: time="2022-10-18T07:28:21+02:00" level=info msg="index: found no jpeg for photo uid prjft023ew9g4tmt"
Oct 18 07:28:21 photoprism photoprism[12815]: time="2022-10-18T07:28:21+02:00" level=info msg="index: found no jpeg for photo uid prjfvu91l73wt2ib"
Oct 18 07:34:54 photoprism photoprism[12815]: time="2022-10-18T07:34:54+02:00" level=info msg="indexierung in 447 s abgeschlossen"
Oct 18 07:48:47 photoprism photoprism[12815]: time="2022-10-18T07:48:47+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:48:58 photoprism photoprism[12815]: time="2022-10-18T07:48:58+02:00" level=error msg="photo: database is locked"
Oct 18 07:49:03 photoprism photoprism[12815]: time="2022-10-18T07:49:03+02:00" level=error msg="metadata: database is locked (optimize photo)"
Oct 18 07:50:16 photoprism photoprism[12815]: time="2022-10-18T07:50:16+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:50:31 photoprism photoprism[12815]: time="2022-10-18T07:50:31+02:00" level=error msg="photo: database is locked"
Oct 18 07:50:36 photoprism photoprism[12815]: time="2022-10-18T07:50:36+02:00" level=error msg="metadata: database is locked (optimize photo)"
Oct 18 07:51:46 photoprism photoprism[12815]: time="2022-10-18T07:51:46+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:51:57 photoprism photoprism[12815]: time="2022-10-18T07:51:57+02:00" level=error msg="metadata: database is locked (optimize photo)"
Oct 18 07:52:08 photoprism photoprism[12815]: time="2022-10-18T07:52:08+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:52:19 photoprism photoprism[12815]: time="2022-10-18T07:52:19+02:00" level=error msg="photo: database is locked"
Oct 18 07:52:24 photoprism photoprism[12815]: time="2022-10-18T07:52:24+02:00" level=error msg="metadata: database is locked (optimize photo)"
Oct 18 07:52:29 photoprism photoprism[12815]: time="2022-10-18T07:52:29+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:57:33 photoprism photoprism[12815]: time="2022-10-18T07:57:33+02:00" level=error msg="photo: database is locked (update date fields)"
Oct 18 07:57:39 photoprism photoprism[12815]: time="2022-10-18T07:57:39+02:00" level=error msg="photo: database is locked"
Oct 18 07:57:45 photoprism photoprism[12815]: time="2022-10-18T07:57:45+02:00" level=error msg="metadata: database is locked (optimize photo)"
```

**Comment by jan666** [comment]
--workers=1

```
Oct 18 08:01:47 photoprism photoprism[17512]: time="2022-10-18T08:01:47+02:00" level=info msg="classify: loading labels from labels.txt"
Oct 18 08:02:23 photoprism photoprism[17512]: time="2022-10-18T08:02:23+02:00" level=info msg="index: found no .ppignore file"
Oct 18 08:03:05 photoprism photoprism[17512]: time="2022-10-18T08:03:05+02:00" level=info msg="index: found no new or modified files"
Oct 18 08:03:16 photoprism photoprism[17512]: time="2022-10-18T08:03:16+02:00" level=info msg="index: found no jpeg for photo uid prjft023ew9g4tmt"
Oct 18 08:03:16 photoprism photoprism[17512]: time="2022-10-18T08:03:16+02:00" level=info msg="index: found no jpeg for photo uid prjfvu91l73wt2ib"
Oct 18 08:11:32 photoprism photoprism[17512]: time="2022-10-18T08:11:32+02:00" level=error msg="moments: database is locked (update folder)"
Oct 18 08:11:37 photoprism photoprism[17512]: time="2022-10-18T08:11:37+02:00" level=error msg="moments: database is locked (update folder)"
Oct 18 08:11:42 photoprism photoprism[17512]: time="2022-10-18T08:11:42+02:00" level=error msg="moments: database is locked (update folder)"
Oct 18 08:11:48 photoprism photoprism[17512]: time="2022-10-18T08:11:48+02:00" level=error msg="moments: database is locked (update folder)"
Oct 18 08:11:53 photoprism photoprism[17512]: time="2022-10-18T08:11:53+02:00" level=error msg="moments: database is locked (update folder)"
Oct 18 08:16:56 photoprism photoprism[17512]: time="2022-10-18T08:16:56+02:00" level=info msg="indexierung in 912 s abgeschlossen"
```

**Comment by lastzero** [comment]
https://intellipaat.com/community/63246/how-do-i-unlock-a-sqlite-database

**Comment by jan666** [comment]
It unlocks "itself" after some time. It's not locked when Photoprism is stopped:

```
photoprism:/var/db/photoprism/storage # /usr/local/etc/rc.d/photoprism stop
Stopping photoprism.
Waiting for PIDS: 17513.
root@photoprism:/var/db/photoprism/storage # sql
photoprism:/var/db/photoprism/storage # sqlite3 index.db
SQLite version 3.39.3 2022-09-05 11:02:23
Enter ".help" for usage hints.
sqlite> select count(*) from photos;
44618
```

It's just the "database is locked" problem many(?) people have. And it looks like `?_busy_timeout=5000` does not solve this for my setup.

**Comment by lastzero** [comment]
Also when you do an update or delete? I imagine select works anyway.

**Comment by lastzero** [comment]
It could also be damaged or in a non-optimized/unclean state.

**Comment by lastzero** [comment]
As I said, HDD & Sqlite & fast CPU is bad combination as the CPU is forced to wait for the HDD on every single change.

**Comment by lastzero** [comment]
We'll add a warning to our docs about it...

**Comment by line72** [comment]
Enabling WAL (write-ahead logging) resolved my issues with sqlite. To enable:

```
sqlite3 index.db
sqlite> PRAGMA journal_mode=WAL;
```

You can read more about it here:
https://www.sqlite.org/wal.html

**Comment by lastzero** [comment]
Thanks! That's a great hint, although support seems to depend on the underlying operating system and filesystem. Do you know if it gracefully downgrades or would it unexpectedly throw an error some time later?

**Comment by line72** [comment]
My understanding is that it works fine on any modern filesystem. I enable for all my projects that use sqlite with multiple threads. The biggest caveat (which is typically true in journal mode too) is to not use it on a network filesystem (nfs/cifs).

**Comment by lastzero** [comment]
You're welcome to update the Sqlite Troubleshooting Guide accordingly:
- https://docs.photoprism.app/getting-started/troubleshooting/sqlite/

**Comment by anarcat** [comment]
> You're welcome to update the Sqlite Troubleshooting Guide accordingly:

i've done that in https://github.com/photoprism/photoprism-docs/pull/169, here it's night and day in terms of perforamnce, although i will also follow your advice and move this stuff to SSD. it's a little tricky because the DB is right alongside the gigantic `thumbs` folder, which is somewhat more expensive to move to SSD but whatever, storage is so cheap these days. :)
