### ISSUE TITLE
Select All / Easier selection

### ISSUE THREAD

**Issue by ptersilie** [photoprism/photoprism#272]
Great project. It's the only self-hosted photo album solution I found that comes close to Google Photos.

This issue is somewhat related to #260, as it's currently a bit difficult to create albums from pictures moved into the `Originals` folder. Ideally, photoprism would automatically create albums for each folder in `Originals` but for the time being it would also help if there was a `Select All` button. This would allow to search for the folder name, and then select all pictures and put them into a new album. Currently, each photo needs to be selected manually by clicking into the bottom right circle of the picture. It would also help if, once a photo has been selected, other selections could be added by clicking on the whole thumbnail (instead of just the small circle).

**Comment by lastzero** [comment]
You can use a shift-click to select multiple photos, does that help?

**Comment by ptersilie** [comment]
Ah, that helps indeed for the time being. Though I think a "Select all" button would still be useful, but it's not an urgent matter.

Of course, the best solution would be to add a checkbox to the "Index originals page" that says something like "Create albums from folders", which automatically creates an album for each folder it finds. Should I make this a separate issue?

**Comment by lastzero** [comment]
Select All is difficult from a UX perspective as we use infinite scrolling. So theoretically you could select several TB of images and perform operations on them. This would lead to frustration when you discover that the ZIP archive you're creating will be 500 GB in size and needs 20 h to be ready for download. You see the problem? Otherwise it would just be a fuzzy "select what I think is currently on my screen".

**Comment by lastzero** [comment]
Note that the database schema might change until our stable release. So you might lose your albums or any other data in theory, although I think the worst is over. Currently working on sharing. When that is done, we do additional performance tests that hopefully won't force us to perform big changes. But you never know.

**Comment by ptersilie** [comment]
> Select All is difficult from a UX perspective as we use infinite scrolling".

You're absolutely right. This didn't cross my mind. But now that I think about it, Google Photos, also doesn't offer a "Select all" button, I assume for the same reason.

> Note that the database schema might change until our stable release.

That's fair enough. Luckily I haven't been creating albums from my photos yet, since there's way too many and the process is currently quite tedious. What do you think about the "Create albums from folders" idea though?

**Comment by lastzero** [comment]
We store the folder name in our database, so you could use it as a filter (not 100% sure if implemented already). Also we'll automatically group photos by time and location.

Many tools only support adding a photo to a single album (e.g. Nextcloud) whereas we want to provide more diverse ways of discovering and grouping your photos.

**Comment by ptersilie** [comment]
> We store the folder name in our database, so you could use it as a filter (not 100% sure if implemented already). Also we'll automatically group photos by time and location.

Would this allow me to then generate an album from that with a single click, e.g. use filter to select all photos in a certain folder and then create an album from it? Currently, I would still have to manually select every single photo found by the filter first, right?

In any case, I'm looking forward to the stable release at which point I'm hopeful I can use this as a Google Photos replacement. Keep up that good work!

**Comment by lastzero** [comment]
We could add such a feature after we're done with sharing and other high priority tasks. For now, you can search, do two shift-clicks and then create an album from this. But you have to know what to search for, I agree.

Since users typically also have many random directories (e.g. smartphone backups), we shouldn't automatically create albums from all directories. Not sure what the best way is in terms of UX.

**Comment by ptersilie** [comment]
Agreed on all points. I'll will have another think about how this could be solved from a UX perspective and let you know in a separate issue.

**Comment by lastzero** [comment]
Thank you! :)

**Comment by spruceb** [comment]
Hi, any chance a simple select-all could be added as a stop gap? Currently it's difficult to scroll through multiple-thousands of photos to shift select them when creating an album from a search.

**Comment by lastzero** [comment]
You want to create an album with multiple thousands of photos? Sounds more like a search filter, not an album?

**Comment by ptersilie** [comment]
To chime in: after having initially suggested this change, I agree with @lastzero that this is probably not the best way to deal with albums. I had some more thoughts on this matter and the best solution is probably to do (either or both):

1) After doing a search, have a button "Create album from search", which then assigns all photos found in the search to an album.

2) When importing a folder, look for an (optional) file ".album" which contains the name of the album. When importing photos from that folder, create a new album with the given name, and assign the photos to it.

Without knowing the details of photoprism's implementation, it seems to me 2) is probably easier to implement than 1), and would, in my use case at least (of wanting to import already sorted and named albums), be completely sufficient.

**Comment by lastzero** [comment]
Shouldn't "create album from search" be dynamic, so that new results are automatically included? That's what I mean with "search filter", other apps call it "smart albums".

**Comment by lastzero** [comment]
Note that you now can do a long click to select multiple photos. This is especially useful on mobile.

**Comment by ptersilie** [comment]
> Shouldn't "create album from search" be dynamic, so that new results are automatically included? That's what I mean with "search filter", other apps call it "smart albums".

That would be even better. Is there in this case even a need for normal albums or do "search filters" do essentially the same?

**Comment by lastzero** [comment]
Sure, for me albums are selected photos of high quality that tell a story. Search filters won't do that.

**Comment by ptersilie** [comment]
You're right. I was thinking I could just have a search filter with the folder name of my album on disk, but agree that this doesn't cover all use cases.

> Note that you now can do a long click to select multiple photos. This is especially useful on mobile.

Thanks, that's useful, but for my many albums still a bit too tedious a process. But a search filter might solve this problem for me.

**Comment by lastzero** [comment]
I'll start working on albums once TensorFlow is built for all operating systems and processors :D

Also we need support for symlinks, so that you can index directories in different locations.

**Comment by ptersilie** [comment]
Of course, I totally understand this is not too high on the priority list.

**Comment by lastzero** [comment]
Albums are actually very important for us and our users, but we want to avoid people using our app before we're stable (which includes a TensorFlow version that works for everyone).

**Comment by ptersilie** [comment]
That is a very reasonable approach.

**Comment by spruceb** [comment]
Just want to chime in again, if a "select all" button is technically simple and you're at all willing to add it (perhaps behind an "advanced users" setting so it doesn't confuse people), I would absolutely find it useful. I'd like to be able to use Photoprism to sort large numbers of existing photos, and my workflow for that includes searching for certain labels/keywords, adding all results to an album, and then slowly working through that album sorting each result to a more appropriate location. Dynamic albums aren't really relevant to me, the point is to be able to queue up a subsection of photos for further sorting, and then remove them from that album as they are sorted (even though they'd still likely have the same labels/keywords as before, and show up in the original search). Importing a folder into an album would be helpful, but still not quite what I'm looking for here.

I realize Photoprism is pre-release and I don't plan on wasting tons of effort on sorting before the DB is stable etc, however I think this functionality would be very useful to me for sorting large numbers of photos manually.

**Comment by Majestic7979** [comment]
You really need to provide a select all button on at least the Archive filter, so that it becomes possible to "empty archive" at once. Why would I want to carefully go through every single thing I put in the trash... waste of time.

**Comment by jleach87** [comment]
> You really need to provide a select all button on at least the Archive filter, so that it becomes possible to "empty archive" at once. Why would I want to carefully go through every single thing I put in the trash... waste of time.

+1

**Comment by menelike** [comment]
> You really need to provide a select all button on at least the Archive filter, so that it becomes possible to "empty archive" at once. Why would I want to carefully go through every single thing I put in the trash... waste of time.

In the meantime, select the first image, scroll down to the last image, shift click the last image (all images have been selected by now) and delete all.

**Comment by lastzero** [comment]
> You really need to provide a select all button on at least the Archive filter, so that it becomes possible to "empty archive" at once. Why would I want to carefully go through every single thing I put in the trash... waste of time.

My commit adds a "Delete All" button to the Archive page toolbar.

It's true that we've been cautious about adding bulk actions in the past, as we've received feedback from users who feared that files would be deleted without their control. I have even seen posts from users claiming that our software deleted their files, which is not possible, but still looks bad and requires a response from our side.
