### ISSUE TITLE
Thumbnail on places available, but "no pictures found" when clicked

### ISSUE THREAD

**Issue by githubee** [photoprism/photoprism#2728]
#### 1. What is not working as documented?

I use Photoprism as Docker container. It used to work great, but recently I added pictures and I can see them on the map (places) correctly even with thumbnails, but when I click on the pictures, I get "No Pictures Found". The query to `http://photoprism:2342/api/v1/geo/view?near=pricmzg86y9dzhl3&count=1000` returns and empty array `[]`. It (still) works fine for the other places and pictures. I would like to dig deeper, but I do not know where to look. 

#### 2. How can we reproduce it?

1. Go to 'places'
2. Click on 'a recent picture thumb'
3. See error "no pictures found"

I have 36k images in my library. There is 50GB free space left. I have pulled the latest mariadb and photoprism via docker-compose.

#### 3. What behavior do you expect?

The picture clicked should pop up.

#### 4. What could be the cause of your problem?

I tried `docker-compose logs --tail=100` but logs show nothing since yesterday (where I pulled the new image). No indication of errors. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I doubt that this is file related, but I can check if really needed.

#### 6. Which software versions do you use?

mariadb                 10.8      86dd5a365fb2
10.8.5-MariaDB-1:10.8.5+maria~ubu2204'

photoprism/photoprism   latest    f0deb6e2fde0
Build [220901-f493607b0]

(a) PhotoPrism Architecture & Build Number: AMD64

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Brave v1.43.93

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

Yes, but disabled.

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel i5 11th gen

(b) Physical Memory & Swap Space in GB 
8GB & 4GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...
1TB HDD

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

no

**Comment by graciousgrey** [comment]
Maybe not all thumbnails exist for this photo? Can you find the photo within the search section? Is it possible to open it in full screen mode from there?

**Comment by githubee** [comment]
I have renamed the title and searched for it. It showed it (a tile) and I see a reference to `/api/v1/t/5677e87f06665355bedc2fec15ab18b6d3eccff0/337439d8/tile_500`
When I click on it I see a smaller version of it - 1280pix (`/api/v1/t/5677e87f06665355bedc2fec15ab18b6d3eccff0/337439d8/fit_1280`).
When I click on download I can download it full size.

**Comment by graciousgrey** [comment]
@githubee Could you check what latitude and longitude the affected photos have? You can find this information on the edit dialog.

**Comment by githubee** [comment]
Hey grey,
it was 42.43439,18.694036 but now they show up (thanks for reminding me about this issue). Not sure if anything recently changed (?) I didnt change anything. I will mark it resolved
KR
Alex

**Comment by cconcannon** [comment]
I'm experiencing the same issue as described. Please let me know if I should open a new issue instead of following up here.

I've attached a screenshot of what I experience immediately after clicking the one thumbnail image that is displayed in the screenshot. The request is `/api/v1/geo/view?near=prnl6533dr4i0cay&count=1000` and it returns status 200, but the UI gives the yellow "No Pictures Found" pop-up at the bottom of the screen.

<img width="1792" alt="Screenshot 2022-12-27 at 10 40 14 PM" src="https://user-images.githubusercontent.com/16453494/209769890-efb7ac46-c9ef-4078-b3f4-5d0d9ce82fa6.png">

**Comment by graciousgrey** [comment]
@cconcannon We do have a related open issue here: https://github.com/photoprism/photoprism/issues/2109
