### ISSUE TITLE
Can photoprism replace Synology Moments in future?

### ISSUE THREAD

**Issue by nguyenxndaidev** [photoprism/photoprism#273]
Hi and many thanks for an awesome open source project like photoprism.

I am searching for a replacement of [Synology Moments](https://www.synology.com/en-global/dsm/feature/moments) / [Live demo](https://demo.synology.com/dsm?utm_source=feature&utm_medium=moments) and found this very promising project.

The good parts of Synology Moments:
* The server can recognize people, subjects and places very well using AI technologies. If there is mistake or something unrecognized, user can tag manually and the machine will learn to improve result in the future.
* User can organize photos and videos with album, tags, metadata.
* User can share albums or individual photos, videos
* Performance on server side (NodeJs) and client side (web, native apps on Android and iOS) are very good.
* The native app on smartphone allows to configure to upload automatically my photos and videos from selected folders to server.
* The native app suggests me delete uploaded files to free up space on my smartphone.
* Uploaded media files are automatically organized in folders, based on metadata and source (devices)
* Web app is nice, but I personally don't use that because working on native app on smartphone is much more convenience.

Now, there are bad parts of Synology Moments and why I am searching for an alternative like photoprism:
* I cannot migrate to another solution in the future because it's closed source.
* I cannot touch its database, no way to simply backup its database files. It forces me to use its backup solution for it. The provided backup solution (Hyper Backup) does not allow me to split the backup of media files to multiple smaller pieces. So for example, if I have 10TB photos/videos, I must store all in one place.
If it's open source, I can backup anything easily, flexibly using normal file backup solution. I can even write migration scripts to migrate database if I really need to do that.
* I cannot store media files at my desired directories in my NAS server. Synology Moments forces me to store files in user home directory, which prevents me integrate with other services, such as, private and public cloud to synchronize files in flexible way.
* Don't have app for viewing on Android Smart TV

I know that this project is now in early stage and only implement for web frontend. But I would like to ask your vision about the ideas below:
* Native app on smartphone (Android/iOS) with cool features like Synology Moments?
* Native app on Smart TV (especially, Android TV)?
* Allow to specify multiple media directories (photos/videos) at desired directories on server?
* Recognize people, places and subjects using AI?
* Edit file's metadata directly with photoprism GUI (not only saving these information to database)?

Best regards

**Comment by nguyenxndaidev** [comment]
Thanks for your reply!

> Regarding uploading / synchronization, you can soon use other apps like Nextcloud or even Google Photos and let PhotoPrism automatically import from there.

The solution forces user to use public cloud. It would mean a big problem for many users. I hope that I can update directly to PhotoPrism server from photoprism-mobile app via local network?

**Comment by lastzero** [comment]
No, you can run a local Nextcloud (or any other WebDAV) server. In the future, we might provide a WebDAV client for syncing with our own app. Probably not in the next 2-3 months though.

**Comment by nguyenxndaidev** [comment]
Sorry, my bad. I didn't check what Nextcloud is.

**Comment by lastzero** [comment]
No worries, too many projects and products out there :)
We like your feedback and discuss it internally tomorrow!
