### ISSUE TITLE
Title bar contains the author

### ISSUE THREAD

**Issue by antoniomacri** [photoprism/photoprism#2735]
The "author" is shown on a space which seems reserved for the title:
![Schermata da 2022-09-27 10-27-35](https://user-images.githubusercontent.com/1660048/192475201-310819b3-d27e-4d6b-9d9b-dc734d66f97d.png)

Am I right? That page is a shared album.

I'm running photoprism:latest with docker compose on my NAS:
```
      PHOTOPRISM_SITE_CAPTION: "My Title"
      PHOTOPRISM_SITE_AUTHOR: "Antonio Macrì"
```

**Comment by graciousgrey** [comment]
This works as intended. The class v-toolbar__title is coming from the frontend component

**Comment by antoniomacri** [comment]
So that space (white text, black background, above the album title) is inteded to contain the author, not the title/caption of the photoprism instance (`PHOTOPRISM_SITE_CAPTION`)? I think it's pretty useless to put the author there.

**Comment by graciousgrey** [comment]
We set it up this way because the author's name might be more familiar to people who see the share link than the site title or caption.

We are open to other opinions, but the current implementation is definitely not a bug.

**Comment by antoniomacri** [comment]
OK, thanks for the clarification and for the quick response.

I think it should be the other way, because that's the big container of the album and the people I'm sharing the album with already know how the site is called.
