### ISSUE TITLE
Feature request: Make Datepicker optional

### ISSUE THREAD

**Issue by karakal** [photoprism/photoprism#274]
I have a feature request: As long as batch editing isn't possible, it would be very nice, if you could change the date in the meta-data editor not only with the datepicker but also by inputting a date into the input field.
Right now I have a lot of pics that photoprism tagged for the date of the upload. And if I change the metadata to the right date (e.g. 25th of June 2006) I have to to do a lot of clicking in the datepicker instead of just copying and pasting the date right into the input field...

**Comment by lastzero** [comment]
Thanks for your feedback! Validation might be an issue here, since users will use different date / time formats.

**Comment by karakal** [comment]
Yes you are absolutely right. But there are functions available that could help with sanity checks and so on: https://www.alexedwards.net/blog/validation-snippets-for-go#date

Another thing is, that this would lead to some localization options (e.g. for output of dates...)

**Comment by graciousgrey** [comment]
We do not plan to have an input field for date. We will implement batch edit soon, so setting a date for a batch of photos will be much easier.
