### ISSUE TITLE
UX: Locations - Select by piles or rectangle and return list

### ISSUE THREAD

**Issue by resmh** [photoprism/photoprism#2756]
Dear Maintainers,

first of all thank you for this well-designed application! I enjoy using it and I'm eagerly looking forward for the caching mobile app of @thielepaul to be [supported on the backend](https://github.com/photoprism/photoprism/pull/995).

In good memory of iPhoto and currently using Digikam as primary application I'm looking for a modern equivalent comprising of similarly fine-granular database query options. When it comes to geographic data, I'd kindly ask you to consider the following feature:

On the locations tab, clicking a pile of images (that are too many to display) or simply drawing a rectangle shall effectuate a query similar to the "Search" tab filtering by these exact coordinates instead of the derived (and in practice inherently unprecise) Country / State / City fields.

Current walkthrough:
1. A user lives in a city and has taken 3000 images at home and 3000 images in vicinity.
2. The user is out of town and knows that a photo depicting the elevator's license plate exists somewhere in the library.
3. First the user opens the labels tab, but no related term can be found. The user desists from opening all labels.
4. Next the user opens the locations tab and after zooming waits for the 3000 images at home to be rendered on the map.
Fail: **Unable** to get neither a clear overview nor a sortable list of images taken at home - not close to his home or in the same city - the user gives up on researching the library and drives back home to take a new photo.

Target walkthrough:
4. The user opens the locations tab and selects the pile of 3000 images taken at home without further zooming. The application switches to the search tab and filters for the (rectified) boundary of the selected pile's photos.
5. The user may choose further filters and adjust sorting as well as list rendering.
Pass: The user is **able** to look through a list 3000 instead of 6000 images, which is faster than driving back home, particularly if the library is cached locally.

While I truly admire the AI-Powered facial and object recognition, swiftly accessing information by time and location are most important not only to my personal user experience, but also to the people I know. Hopefully this feature request won't induce changes to the backend.

With kind regards and thanks in advance,

Michael

**Comment by heikomat** [comment]
You may be interested in the following issue: https://github.com/photoprism/photoprism/issues/1187

As luck will have it, yesterday i happened to finish implementing what you're looking for. It's not 100% as you describe it, but extremely close.
It also adds min/max lat/lng filters to the search-api (as this is required for the cluster-view to work)

**Comment by graciousgrey** [comment]
Our next release will come with search filters for city and state.

https://docs.photoprism.app/release-notes/
https://github.com/photoprism/photoprism/pull/2670

In a future release we might add search filters for street or postcode as well. 

The places cluster view is currently in progress and might be exaclty what you are looking for ;) https://github.com/photoprism/photoprism/issues/1187

Let us know if we can close your request as a duplicate :)
