### ISSUE TITLE
moments: Error 1093: You can't specify target table 'albums' for update in FROM clause (remove duplicates)

### ISSUE THREAD

**Issue by droopified** [photoprism/photoprism#2757]
moments: Error 1093: You can't specify target table 'albums' for update in FROM clause (remove duplicates)

what does this mean? i get this error a lot but i check the directory and it doesnt contain any duplicate filenames.

**Comment by lastzero** [comment]
We have this bug report template so we don't have to ask you at 3am what database you are using and if you have read the system requirements in our setup guide yet?

👉 https://docs.photoprism.app/getting-started/#databases
