### ISSUE TITLE
Docker "photoprism/photoprism" Exited (134)

### ISSUE THREAD

**Issue by majnerp1** [photoprism/photoprism#278]
Container stoped with exited(134):
_The TensorFlow library was compiled to use SSE3 instructions, but these aren't available on your machine_
Can you help me?

**Comment by lastzero** [comment]
Interesting, thought we ship TensorFlow without SSE support. You're using the latest Docker image?

**Comment by majnerp1** [comment]
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:36 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by majnerp1** [comment]
photoprism/photoprism:latest
from
https://hub.docker.com/r/photoprism/photoprism/tags

**Comment by lastzero** [comment]
Will check tomorrow, already late. The PhotoPrism version string should look something like `200405-1a3966e-Linux-x86_64-DEBUG`. You see it when you run `photoprism version`.

**Comment by majnerp1** [comment]
Photoprism container don't start...
_root@omv:~# photoprism version
-bash: photoprism: command not found_

**Comment by majnerp1** [comment]
root@omv:~# cat /proc/cpuinfo
_processor       : 0
vendor_id       : AuthenticAMD
...
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                             pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext lm 3dnowext 3dnow rep_good                                             nopl cpuid 3dnowprefetch vmmcall_

**Comment by lastzero** [comment]
Does it work with our latest build / docker image? See #289

**Comment by lastzero** [comment]
It looks like you need at least SSE3 for TensorFlow unless TensorFlow only shows a notice for AVX and SSE 4.1+. What exact CPU is this? Probably very old?
