### ISSUE TITLE
Auth: API change in latest preview breaks existing scripts

### ISSUE THREAD

**Issue by streiman** [photoprism/photoprism#2796]
#### 1. What is not working as documented?

Using the API in a script, the login by /api/v1/session with username "admin" and the password results in an error 401 instead of status 200 and giving back an id.

#### 2. How can we reproduce it?

Use the API on the photoprism:latest with working credentials and switch to photoprism:preview and see it break. 

#### 3. What behavior do you expect?

Using the API call which works in photoprism:latest should also work on photoprism:preview.

#### 4. What could be the cause of your problem?

You have to submit the username as "username" in photoprims:latest. On photoprism:preview this changed to "name".

Solution could be to switch back to "username", accept "username" and "name" or mark the change in the API somewhere-

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

This is the python code I use:

        def login(self,url, uname, pwd):
                if url=="":
                        url=input("URL? ")
                self.url=url
                if uname=="":
                        uname=input("Username? ")
                if pwd=="":
                        pwd=input("Password? ")
                response = requests.post(self.url+"/api/v1/session",data=simplejson.dumps({"username":uname,"password":pwd}))
                print(response)
                self.session_id=response.json()['id']
                self.headers=headers = {"X-Session-ID":self.session_id}
                return True

**Comment by lastzero** [comment]
Field name has been changed back to "username". Let us know if that was all and your script is working again!

**Comment by streiman** [comment]
Yes, it works again.
