### ISSUE TITLE
Option to not delete emptied import sub-directories after import

### ISSUE THREAD

**Issue by p-baum** [photoprism/photoprism#280]
I'm trying to get this working with Syncthing.  Deleting directories after import causes Syncthing to error.  I imagine that other software people hook up to Photoprism in this manner might also take exception to this behavior.

Can we have an option to to not delete them?

**Comment by lastzero** [comment]
Well, then you would have the data twice: in the import AND in the originals directory

Do you really want this? Think the error can be fixed, it's probably because not all files can be imported, e.g. videos at the moment (on our todo).

**Comment by p-baum** [comment]
I don't think you've understood me. My import has succeeded normally and the import subdirectories were deleted.  I would like my imports to be removed (as they currently are) while retaining the import directory structure (new feature request).

I am also looking at other methods of synchronizing with mobile devices.  If you have any suggestions I would love to hear them.

Currently I have an idea to rsync/syncthing to a seperate 'syncdir' and have a script that hardlinks files to Importdir. That way by comparing the emptied Importdir and syncdir I have a record of whats been consumed.  I really shouldn't have to be doing this though.

**Comment by lastzero** [comment]
In the sync settings dialog, you can choose to preserve file names in which case files are directly downloaded to originals and then indexed without going through import. The benefit of importing is to avoid duplicates which doesn't work with custom file names, at least we would have to provide a hell of a conflict resolution dialog and ask what files to keep and what to merge.

**Comment by p-baum** [comment]
OK. I accept then that Photoprism will become the single source of truth.  My original problem remains.  How can I prevent the removal of my (import emptied) sub-directories?

**Comment by lastzero** [comment]
Sound like you use a custom sync solution based on rsync and not our new WebDAV-based sync feature?

Then I see the problem. You can run import without deleting files and directories from the import folder, but this option might not yet be available in the terminal (there is a checkbox in our UI). Of course we can also add an option to keep the directories and not the files if that helps (might confuse some users though).

**Comment by lastzero** [comment]
Guess what, we already have a copy command that doesn't delete files and directories:

```go
// CopyCommand is used to register the copy cli command
var CopyCommand = cli.Command{
	Name:    "copy",
	Aliases: []string{"cp"},
	Usage:   "Copies files to originals path, converts and indexes them as needed",
	Action:  copyAction,
}
```

**Comment by p-baum** [comment]
I'm aware that I can copy instead of move, but like you said, then I would have 2 copies.  I want to move but just keed the directory structure.

Please tell me where I can find more information an your new WebDAV-based sync feature.

**Comment by lastzero** [comment]
WebDAV sync was developed this week, so there is not documentation yet. All you need to do is to add a WebDAV server account (e.g. Nextcloud) on this page: https://demo.photoprism.org/settings/accounts

Obviously not in our public demo but your own server ;)

Maybe we can add a flag to mv / import to keep directories. But once somebody runs it without the flag, directories are gone again. So it might not be the most stable solution.

**Comment by p-baum** [comment]
I don't have that option in my install. I'm using docker (photoprism/photoprism:latest).  I'll play with it when I get my hands on it. Thankyou.

Regarding the original issue: The option would need to be more stable. How about I just throw any old file in there that Photoprism cant import such as an empty text file '.ppnodelete' .

**Comment by lastzero** [comment]
Good idea, we were already thinking about ignore and keep files like git uses them...

**Comment by p-baum** [comment]
Ok. I'll do that then until a better solution arrives.

Thankyou.

**Comment by p-baum** [comment]
Ok. This works only if you use a normal file i.e. without a dot prefix.  dotfiles appear to be ignored.  Im now placing a file called 'ppkeepdir' everywhere i want to keep the dir. For syncthing this also means putting inside the '.stfolder' dirs.  So far syncthing has not complained about it but gitignore/keep functionality would the best solution.

**Comment by lastzero** [comment]
Yes, that's because most directories nowadays contain hidden files and directories like .DS_Store on OX or .thumbnails on Windows, so we would never be able to remove them after importing.
