### ISSUE TITLE
Security: Create new files without execution permission

### ISSUE THREAD

**Issue by nekr0z** [photoprism/photoprism#2809]
Files created by PhotoPrism, such as the imported files ending up in the "originals" directory, album YAMLs under "storage/albums/folder", YAMLs under "storage/sidecar" folder, and many other, are created with executable bit set in permissions.

#### Steps to reproduce:
1. Have a photo imported.
2. Check permissions on the file that appeared in "originals".

#### Expected behavior:
The created files don't have the executable bit set unless they are executables.

#### Likely cause of the problem:
https://github.com/photoprism/photoprism/blob/69682de32d71b8a0235e7753f4d8ff8cd6df3784/internal/photoprism/mediafile.go#L687 and https://github.com/photoprism/photoprism/blob/69682de32d71b8a0235e7753f4d8ff8cd6df3784/pkg/fs/copy.go#L30 (and maybe other places) use `os.ModePerm` that is `0o777`; need to use `0o666`, since the file created is not intended to be an executable in either case.

**Comment by lastzero** [comment]
@nekr0z Would you be able to test this for us? No CLA required 😉

**Comment by nekr0z** [comment]
> @nekr0z Would you be able to test this for us? No CLA required wink

Sure, will give the preview a try as soon as I have time (most likely, on Friday or Saturday), will report back as soon as.

**Comment by nekr0z** [comment]
Closed already, but FWIW everything looks good: imports, sidecars, config (I haven't tested album YAMLs yet, but no reason to think they'd behave differently).

**Comment by lastzero** [comment]
Thank you! Yeah, closed, since we already released it and of course tested it ourselves as well.
