### ISSUE TITLE
issue importing images with sequential naming

### ISSUE THREAD

**Issue by taibhse-designs** [photoprism/photoprism#283]
ok I found this software yesterday and it looks promising for what I need to manage photos across multiple devices, keep a backup while still maintaining easy access to make use of my photos but I have come across an issue.

Many of my photos are named as follows, "image name (1).jpg" "image name (2).jpg" "image name (3).jpg"

when I try to import / upload or have them added in, only 1 ever shows up, all images are unique, only that they are named with sequential numbering. so what is going on?

I have tested by taking random images that differ in resolution and content and named them with sequential numbering and the same issue persists, this also appears to occur in the online demo.

**Comment by lastzero** [comment]
We assume file name (1) (2) (3) or copy 1 / copy 2 / copy 3 are the same file or different versions of the same (raw) original. It's difficult to tell automatically if they are unique or really different in that the image content is not similar (like a b/w version etc).

We would need to add an option to turn this off for you, if you prefer to name your files with a scheme that operating systems typically use for copies of the same file.

**Comment by taibhse-designs** [comment]
> We assume file name (1) (2) (3) or copy 1 / copy 2 / copy 3 are the same file or different versions of the same (raw) original. It's difficult to tell automatically if they are unique or really different in that the image content is not similar (like a b/w version etc).
> 
> We would need to add an option to turn this off for you, if you prefer to name your files with a scheme that operating systems typically use for copies of the same file.

a switch to turn this off would be ideal, I'm personally not as worried about duplicates given how large dedicated drives can be and with tagging and organizing, its easy to purge them over time manually for me. 

is there any way in the mean time I could get photoprism to import besides renaming files? worst case I could run a script to add a random set of character codes to the end of picture names but this seems tedious.

**Comment by lastzero** [comment]
![Screenshot 2020-04-11 at 22 39 53](https://user-images.githubusercontent.com/301686/79054471-622e2380-7c45-11ea-8310-c2adb6852d72.png)
![Screenshot 2020-04-11 at 22 39 47](https://user-images.githubusercontent.com/301686/79054473-635f5080-7c45-11ea-83e6-bae18d256bb2.png)

**Comment by lastzero** [comment]
You can of course write this code yourself, but there is no config option yet... We'll put this on our todo list!

**Comment by taibhse-designs** [comment]
im new to go, but could give it a try, which files would it be that have the code that decides if its a duplicate or not, if it could be edited to allow duplicates with a switch set,

**Comment by lastzero** [comment]
If you need to learn go first, then give us a little bit of time :) It's Saturday evening and we need some rest now... maybe after Easter if that's ok for you!

**Comment by taibhse-designs** [comment]
that is perfectly fine and hope you have a good easter, I'm familiar with python, php and java, assuming I'm not missing anything else, I believe its the code in this file,

https://github.com/photoprism/photoprism/blob/02810ffa94420591e3e3485afc14f1f37fc34915/pkg/fs/base.go

```
if end := strings.Index(basename, " ("); end != -1 {
		// copies created by Chrome & Windows, example: IMG_1234 (2)
		basename = basename[:end]
	} else if end := strings.Index(basename, " copy"); end != -1 {
		// copies created by OS X, example: IMG_1234 copy 2
		basename = basename[:end]
	}
```

so if I add a condition around this code, to tell photoprism to skip over it, it should resolve my issue right?

**Comment by taibhse-designs** [comment]
ok so far I have tried git cloning the repository to my local drive, using docker to build the project and docker-compose up to start an instance, but when I try to visit the web front end, I get 

"This page isn’t workinglocalhost didn’t send any data.
ERR_EMPTY_RESPONSE"

any ideas whats up or anyone got any clear instructions step by step to get all this up and running on windows so I can start editing and trying to add custom stuff in?

**Comment by lastzero** [comment]
When using the development image, you need to build and start photoprism inside the container first, then connect to port 2342.

Step by step instructions can be found in our Wiki:
https://github.com/photoprism/photoprism/wiki/Setup

**Comment by lastzero** [comment]
Might be able to also use the feature flags I developed for #284. It's just a stub and not done yet. Taking a break on Easter evening.

**Comment by lastzero** [comment]
Named it "find related files", which you now can turn off (has no effect yet in the backend):

![Screenshot 2020-04-14 at 13 14 21](https://user-images.githubusercontent.com/301686/79219079-e228d900-7e51-11ea-8845-9c76d325cda5.png)

**Comment by lastzero** [comment]
No more feedback, we assume it's working.
