### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by pnbd** [photoprism/photoprism#2839]
Hi guys, first of all, thank you so much for the amazing work. 
I just started to get a problem since I made a pull for the last version and something strange started happening. So, when I put files in the import folder and press import, instead of moving the files, like normally, to the year and month folder, it puts them inside a year/month/day folder, inside the import folder itself... Then, if I press import again, it deletes everything because it says that the files were already imported.

**Comment by lastzero** [comment]
What last version? If you are not sure, you should use GitHub Discussions first.

**Comment by lastzero** [comment]
Tested it, the logs look as expected (maybe you use another tool that creates these subfolders?):

```
import: moving main jpg file 2011/10/20111002_120138_783F539B.jpg to 2011/10/20111002_120138_783F539B.jpg 
```
