### ISSUE TITLE
Public mode with disabled upload

### ISSUE THREAD

**Issue by fallais** [photoprism/photoprism#284]
Hello,

let's say I want to provide a gallery to users in order to display photos that I handle myself (moderation, tags, etc..). It needs to be public so. But I do not want people to be able to upload photos on it.
I tought it was the purpose of "read_only" but I realized I mistunderstood the feature..

It is possible please ?
Thanks a lot.

**Comment by lastzero** [comment]
We're working on an album sharing functionality, that will enable you to publicly display photos without users being able to edit or upload.

Read only should disable upload (if not, that's a bug), but it will also disable importing in general.

We don't have a flag for disabling uploads only, but it's a good idea to add one.

**Comment by fallais** [comment]
Hello @lastzero and thanks for helping. You say that if I enable `READ_ONLY` and if I set it as `PUBLIC` I could end up with a photo gallery that is available for everyone with no upload allowed, right ?

Tat being said, I could simply ask my users to send me the photos by email, and then I add them by myself directly into the `/photos` directory and they will appear ?

**Comment by lastzero** [comment]
Read only means you can still create, edit & delete albums and index your collection, but not upload or modify anything in the file system. Note that we can also not create JPEGs from RAWs in read-only mode. You have to re-index whenever you add or remove files from your photos / originals directory as we don't watch for changes (to avoid indexing while an upload is still running and only half done).

**Comment by lastzero** [comment]
Started working on feature flags you can change in settings... also added a config flag to disable / hide the settings page in the frontend, so that users can not change settings back.

**Comment by fallais** [comment]
I think there are two ways of using photoprism, as a lambda user that I am :

- **Private mode** : at home, for family purposes, on a LAN.
- **Public mode** : you want to share photo on the Internet, for example you're a graphic designer and this is your portfolio.

But that being said, in private mode, you may want your parents to see your photos (or some of them). And, in public mode, you may want some people to upload photos.

So, the idea of configuration based on flags seem to be the best solution.

But the handling of two kind of accounts could be great too, don' you think ? Administrator and guest. For the public mode I mean.

**Comment by lastzero** [comment]
Implemented common feature flags incl upload (work in progress):

![Screenshot 2020-04-13 at 18 08 56](https://user-images.githubusercontent.com/301686/79136767-dbe32000-7db1-11ea-8c38-ca926be6fff2.png)

**Comment by lastzero** [comment]
Latest Docker build should contain everything you need. Please test :)

Note that you need to start the server with `--disable-settings` or `PHOTOPRISM_DISABLE_SETTINGS` (env variable) so that users can not simply turn uploads back on or change other settings. You can still change settings in `settings.yml` if you have access to the server. You can also mount it into the image via Docker (`/photoprism/config/settings.yml`).
