### ISSUE TITLE
MariaDB: Exit with error if version is < 10.5.12

### ISSUE THREAD

**Issue by lacrimal** [photoprism/photoprism#2845]
#### 1. What is not working as documented?

```photoprism migrations ls``` error

```20221015-100000 failed with Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `accounts` TO `services`' at line 1 [631.138µs]```

Im using standalone mariadb instance:
mysql  Ver 15.1 Distrib 10.3.28-MariaDB, for Linux (x86_64) using readline 5.1

#### 2. How can we reproduce it?

Stop photopirsm docker, remove old images, start photoprism docker.
After successfully executing ```photoprism users reset``` and recreating second user account (Admin account was not created automatically - password change forced migration).

Inside docker image:

Trying to upgrade photoprism to Release 46, after checking ```photoprism migrations ls``` error is displayed:

```20221015-100000 failed with Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `accounts` TO `services`' at line 1 [631.138µs]```

Tryig to retry migration with ```photoprism migrations run -f``` but same error apears.

When reporting an import, indexing, or performance issue, please include the number and type of pictures in your library, as well as any configuration options you have changed, such as for thumbnail quality.

#### 3. What behavior do you expect?

'Ok' in migration process

#### 4. What could be the cause of your problem?

Upgrade ?

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

No idea what example is needed but will provide what needed.

#### 6. Which software versions do you use?

(a) PhotoPrism Release 46

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

(c) Centos 8 Stream

(d) Firefox

(e) relevant

#### 7. On what kind of device is PhotoPrism installed?

Skip

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by lastzero** [comment]
~~Try using today's release and watch the logs: https://docs.photoprism.app/release-notes/#november-2-2022~~

Oh wait, this is the latest release? Did you watch the logs when running `photoprism start`? What do they say?

**Comment by lacrimal** [comment]
It is today release Build [221102-905925b4d] :-)

**Comment by lastzero** [comment]
The reason I'm asking is this:
- https://github.com/photoprism/photoprism/issues/2381

Apparently that needs to be improved :)

**Comment by lacrimal** [comment]
OK looks like mariadb 10.3 is unsupported switched to 10.6 and after retry ```photoprism migrations run -f``` there are al ```OK```

**Comment by lastzero** [comment]
Didn't the command show a version warning to you? Honest question as that would help avoid related support requests...

**Comment by lacrimal** [comment]
No there was no warning for mariadb 10.3:
```INFO[2022-11-02T19:47:20Z] PhotoPrism® needs your support!
INFO[2022-11-02T19:47:20Z] Visit https://photoprism.app/membership to learn more.
INFO[2022-11-02T19:47:20Z] migrate: running previously failed migrations
INFO[2022-11-02T19:47:20Z] migrating database schema...
INFO[2022-11-02T19:47:20Z] migrate: executing pre migrations
ERRO[2022-11-02T19:47:20Z] migrate: executing 20221015-100000 failed with Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `accounts` TO `services`' at line 1 [665.214µs]
INFO[2022-11-02T19:47:21Z] migrate: executing main migrations
INFO[2022-11-02T19:47:21Z] completed in 450.228537ms
INFO[2022-11-02T19:47:21Z] closed database connection
```

**Comment by lastzero** [comment]
Thanks, I'll take a look!

**Comment by lastzero** [comment]
Now properly detects MariaDB < 10.5.12, was a mistake on my side:

```
photoprism --db-server=mariadb-10-3:4001 migrate
DEBU[2022-11-03T09:35:36Z] config: overriding config with values from /go/src/github.com/photoprism/photoprism/storage/config/options.yml 
DEBU[2022-11-03T09:35:36Z] config: running on 'Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz', 67 GB memory detected 
DEBU[2022-11-03T09:35:36Z] settings: loaded from /go/src/github.com/photoprism/photoprism/storage/config/settings.yml 
ERRO[2022-11-03T09:35:36Z] config: MariaDB 10.3.31 is not supported, see https://docs.photoprism.app/getting-started/#databases 
```

**Comment by lastzero** [comment]
Released.
