### ISSUE TITLE
Official configuration for Caddy

### ISSUE THREAD

**Issue by fallais** [photoprism/photoprism#285]
Hello,

Could you (if not already done) provide the configuration for Caddy that works with Photoprism please ? In the documentation I mean.
I am actually using it, but I face issues with websockets, I guess I need to use the `websocket` directive in the Caddyfile, but not sure.

That would be perfect, thanks !

**Comment by lastzero** [comment]
```
photos.example.com {
    tls you@example.com
    gzip
    
    proxy / photoprism:2342 {
        websocket
        transparent
    }
}
```

**Comment by fallais** [comment]
Thanks !
