### ISSUE TITLE
Set default NSFW upload to true?

### ISSUE THREAD

**Issue by ThomasEg** [photoprism/photoprism#286]
It's very frustrating for a new user, like myself, that half my pictures cannot be imported because they might be offensive? I would suggest to make the feature for NSFW-detection optional and default off... otherwise you risk loosing potential users at the very first photo import/upload :-(

**Comment by ThomasEg** [comment]
(Should say that i used the default docker image, as many other new users would most likely do to test the software)

**Comment by lastzero** [comment]
The default setting is in fact `PHOTOPRISM_UPLOAD_NSFW: "true"`

See https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/docker-compose.yml

If you don't use our docker-compose config, it is off. Why?

![Screenshot 2020-04-12 at 20 37 10](https://user-images.githubusercontent.com/301686/79076851-687fd680-7cfd-11ea-92b3-99425eaf55bf.png)

**Comment by ThomasEg** [comment]
Ah, i see... i guess the argument goes both ways then :-/ I'm not sure who your main audience for PhotoPrism is. But if the majority is people who wants to use it on their private LAN, then this NSFW should be disabled as default(in my opinion), because none of them will ever need it. I think it is obvious not to open a file/picture/video/torrent/whatever-upload service to the public and go to sleep... No offence to the guy who actually did just that, but i think he should consider it a "hands-on lesson on how NOT to do internet security" and not blame the software or it's authors ;-)

I cannot use compose on my NAS(Unraid or Synology)...only "vanilla docker", so I had to add the environment variables myself... which i did... but i made a spelling error in the variable :-/ So it works now...

**Comment by lastzero** [comment]
So providing an image that has dependencies like a MySQL server is also not possible for NAS users?

When everything is stable, we'll add more examples to our docs for each use case.

**Comment by ThomasEg** [comment]
> So providing an image that has dependencies like a MySQL server is also not possible for NAS users?

No, not via “plain docker”. But both my servers(Unraid and Synology) has appstores and it is rather simple to make apps(=scripts) and publish them for the community. Via Apps you use either compose or install the dependencies directly on the server...

**Comment by lastzero** [comment]
Sounds like something we should do / provide once there is time... then you also don't need to worry about using the "wrong" settings.

**Comment by helmut72** [comment]
> So providing an image that has dependencies like a MySQL server is also not possible for NAS users?

It's possible for Docker on Synology. Using docker-compose heavily.
