### ISSUE TITLE
PhotoPrism on Synology (ignore folders)

### ISSUE THREAD

**Issue by DenisMtfl** [photoprism/photoprism#287]
hi, i love photoprism, but i have a problem with photoprism on my synology NAS.
So when photoprism indexing my photos it also indexing the "@eadir" folders where the thumbs from the internal synology-app in it. 

Is it possible to configure photoprism to ignore the folders "@eadir" ?

**Comment by lastzero** [comment]
Thanks for your feedback! We'll keep this ticket until somebody has time to implement it.

**Comment by lastzero** [comment]
We're going to implement simple .ignore files so that you can configure what should be ignored, see #233.

**Comment by lastzero** [comment]
Master build is running, new Docker images available soon. Add a `.ppignore` file to your originals directory or any sub directory. It will also work in import if needed.

File names / patterns in `.ppignore` will be ignored in all sub directories as well but should not be ignored in other directories (siblings, parent directories).

Example (regular expressions are NOT supported):
```
@eadir
beach*
*.xml
preloader.gif
```

**Comment by DenisMtfl** [comment]
Cool! I will be waiting for the docker image.

**Comment by lastzero** [comment]
Change broke the import command, building a new image. Should be available in ~30 minutes.

**Comment by DenisMtfl** [comment]
Thanks! Docker on synology is working with ignored folders!
`INFO[2020-05-04T08:35:12Z] index: ignored "--- Australien ---/2 day trip to the Capitol (Canberra)/@eaDir" `

**Comment by lastzero** [comment]
Excellent, thank you! Of course `.ppignore` will not remove already indexed files from your library, just ignore them from now on. We're working on a purge command that will remove deleted or ignored files from search results, see #234.

New build is running that will ignore `# comments` in `.ppignore` files.

**Comment by DenisMtfl** [comment]
@lastzero a config option to  remove deleted or ignored files from search results are great

**Comment by lastzero** [comment]
That will happen automatically in the backend or when you run the purge command manually. Just give us a little bit of time to implement it :)

**Comment by DenisMtfl** [comment]
@lastzero i'm developer too, but an .NET developer. I would love to learn how developing photoprism. 
Which IDE do you use to develop photoprism?

**Comment by lastzero** [comment]
JetBrains GoLand

**Comment by DenisMtfl** [comment]
@lastzero thanks. But it is not free. What a pity

**Comment by lastzero** [comment]
Just like Windows ;) Free 30-day trial and worth every cent... even as Open Source developers, we pay for a lot of commercial tools and services

**Comment by DenisMtfl** [comment]
> Just like Windows ;) Free 30-day trial and worth every cent... even as Open Source developers, we pay for a lot of commercial tools and services

Okay for me as go-beginer too expensive. Is it possible develop with vscode ?

**Comment by lastzero** [comment]
Seems like: https://code.visualstudio.com/docs/languages/go
