### ISSUE TITLE
Provide image quality score to filter out low quality pics

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#288]
**As a user, I want to filter by quality so that my library isn't spammed with screenshots, messenger pics and other low quality image files.**

Each of those properties might give one point for the total score:

1. Exif date exists (taken at)
2. Location information exists (lat/long)
3. At least 2 MP resolution (if taken after 2012)
4. Not classified as info or screenshot
5. User likes the photo

Files with less than 2 or 3 points can optionally be sent directly to archive.

Feedback welcome!

**Comment by graciousgrey** [comment]
I guess we should have a filter in the archive to differentiate between actively added files and files automatically added due to low quality.
