### ISSUE TITLE
Make stacked images display the newest one

### ISSUE THREAD

**Issue by Tuxie** [photoprism/photoprism#2882]
My photos have the structure (excluding .xmp .arp .pp3 etc):

NAME01234.DNG <- Original RAW
NAME01234.JPG <- Original SOOC JPEG (I shoot RAW+JPEG)
NAME01234 (1).jpg <- Developed by ART or Darktable if I was not happy with the SOOC
NAME01234 (2).jpg <- Newer version

Photoprism stacks these as expected, but it always displays the SOOC instead of the newest version.

Please make it possible to make Photoprism display the one with the newest modification date instead of the original.

**Comment by graciousgrey** [comment]
Related to: https://github.com/photoprism/photoprism/issues/1028

**Comment by Tuxie** [comment]
Oh, I didn't find that one for some reason. Closing this.
