### ISSUE TITLE
Videos: Add .m2ts to known file extensions

### ISSUE THREAD

**Issue by koztya** [photoprism/photoprism#2899]
MTS is supported file format, but supported extension is only .mts.
.m2ts is valid file extension of the format. Please add this file extension to the list.
https://en.wikipedia.org/wiki/.m2ts

**Comment by lastzero** [comment]
We will provide an updated development preview shortly so you can test these changes. Thank you very much!

**Comment by lastzero** [comment]
An updated preview build will be available for testing soon:

- https://docs.photoprism.app/release-notes/#development-preview

We hope you have a few minutes to let us know if it works so we can release this in our next update!

**Comment by lastzero** [comment]
@koztya Happy testing! :gift:

**Comment by koztya** [comment]
I've tested preview - it found my *.m2ts* files normally.

@lastzero thanks, very fast, wow! :-)

**Comment by lastzero** [comment]
Thanks for testing! :+1:
