### ISSUE TITLE
Inspiration on a project

### ISSUE THREAD

**Issue by hialvaro** [photoprism/photoprism#290]
I just found a similar project which has been abandoned. Maybe you could take some ideas / pieces of code to replicate from it:
https://github.com/hooram/ownphotos

It has some nice design ideas and features that you may like. It already has face recognition implemented using this https://github.com/ageitgey/face_recognition
I know this is python and you're using Go, but maybe it can help to get inspiration somehow.

**Comment by lastzero** [comment]
Thanks, we're already in contact and one of their developers joined our team :)

We'll also work on face recognition, but it won't be part of our first release. There's a ton of features users want, so some things will come later.

**Comment by hialvaro** [comment]
> Thanks, we're already in contact and one of their developers joined our team :)
> 
> We'll also work on face recognition, but it won't be part of our first release. There's a ton of features users want, so some things will come later.

Is there a Roadmap or something like that available? Just to see what are you aiming to achieve first and what will come in a later future

**Comment by lastzero** [comment]
We have our GitHub issues and the MVP milestone, which basically is the first release. Main focus right now are albums and album sharing. Theresa is working on a long term roadmap.

Face recognition, batch editing and better XMP support are pretty high on the wish list. Some users probably also want to sync with Google Drive or social media.

**Comment by hialvaro** [comment]
@lastzero Sounds great! I will keep an eye on this awesome project! Integration/sync with Nextcloud would also be really awesome!

**Comment by lastzero** [comment]
Sync with Nextcloud is already done ✌️

![Screenshot 2020-04-27 at 13 17 33](https://user-images.githubusercontent.com/301686/80579181-e0dadd00-8a09-11ea-9fd0-88f1be7502b6.png)

**Comment by hialvaro** [comment]
Installing right now!!!!!
