### ISSUE TITLE
Memory usage spiked making photoprism unusable on RPI

### ISSUE THREAD

**Issue by crisidev** [photoprism/photoprism#291]
Hello folks,
I just updated photoprism on my RPI 4 (4gb of RAM, 2gb of SWAP). I am using the latest official docker image.

Once photoprism starts, it uses around 11% of the total memory. If I connect using the mobile application, all works fine and the memory goes a bit up, to ~ 15%.

If I connect to the web ui instead, with both Chrome or Firefox, the memory usage start growing quite fast until the system freezes and OOM kicks in.

This was not happening until I updated to the latest version. 

FYI, I also did a full reindex today since something changed in the DB and I was not able to see my pictures anymore..

**Comment by lastzero** [comment]
We'll test on the Pi again soon when we're done with other tasks. Thanks for your report. Maybe it already helps to reduce the number of workers? See `PHOTOPRISM_WORKERS` variable.

Regarding your db: Make sure to update your configuration if you use the built-in TiDB, see https://dl.photoprism.org/docker/docker-compose.yml

`PHOTOPRISM_SQL_*` was renamed to `PHOTOPRISM_TIDB_*`

**Comment by crisidev** [comment]
Regarding the db i found the issue, yep! Thanks. I'll try to reduce the workers and keep you posted!

**Comment by crisidev** [comment]
Update: I have reduced the number of workers from 3 to 1 and the issue appears to be the same, again only when I am loading the web ui. There is no problem if I use the android mobile application.

Is there anything more I can do to help you troubleshoot this?

**Comment by crisidev** [comment]
Here is some info on my system:

### Photoprism arm64 image
```
photoprism/photoprism-arm64          latest              sha256:e0eeae5e822fd6dda77433e0d1004c470b4e814b6995341e3196dcbd938f3efd   5ffe8aeac36b        42 hours ago        957MB
```
### Photoprism version
```
root@photo:/photoprism# photoprism version
200429-faa2074-Linux-aarch64
```

**Comment by lastzero** [comment]
How large is your library? We do some caching, but shouldn't be that much. My instance uses ~2.4 GB with 60.000+ photos (started 42 hours ago).

It's possible that our built-in TiDB uses the additional memory, although I didn't have memory issues so far (only performance issues). In that case, simply use MariaDB. You can create a SQL dump and import it, so that you don't need to re-index.

**Comment by crisidev** [comment]
My library is around 5k pictures.

**Comment by lastzero** [comment]
That's not a lot, strange...

**Comment by lastzero** [comment]
Did you pre-render thumbnails? On demand rendering would cause very high memory and cpu usage. Make sure to mount the following volumes in your [`docker-compose.yml`](https://dl.photoprism.org/docker/docker-compose.yml) so that the thumbnail cache doesn't get lost when you restart:

```
  volumes:
      - "~/Pictures/Originals:/photoprism/originals" # [local path]:[container path]
      - "~/Pictures/Import:/photoprism/import" # [local path]:[container path] (optional)
      - "photoprism-config:/photoprism/config" # keep settings
      - "photoprism-cache:/photoprism/cache" # keep thumbnail cache
      - "photoprism-database:/photoprism/database" # TiDB database files, remove if you use MariaDB or MySQL
```

**Comment by crisidev** [comment]
Yep, all the folders are shared from the host system. They come from an NFS share over gigabit ethernet, but it was the same also before updating to latest version.

**Comment by crisidev** [comment]
Another interesting fact is that when the memory issue starts to happen, photoprism also uses 100% of all 4 cpu cores. If I load the pictures from the mobile app, both memory and CPU stay very quiet.

**Comment by lastzero** [comment]
You can turn on debug more and see what requests are being processed in the docker logs (or specify a log file). The only thing I can think of right now are thumbnails if you're not indexing.

**Comment by lastzero** [comment]
It's possible that the mobile app had thumbs cached if you've used it before...

**Comment by lastzero** [comment]
In general, you should not use networks storage for any cache as it has high latency and overhead compared to a local SSD. NFS is not built to load many small files in a short time, unless they significantly improved it while I wasn't watching.

**Comment by crisidev** [comment]
Not it really did not improve much when you were not looking.. I cleaned up all the cache in the android app and reinstalled and I can confirm it does not load the system even without cached thumbnails..

**Comment by lastzero** [comment]
Did you try to pre-render thumbs in Library > Originals, just in case?

**Comment by crisidev** [comment]
Hum.. I thought that was done during import.. I am running `photoprism thumbs` right now!

**Comment by crisidev** [comment]
@lastzero I just rebuilt all the thumbs and memory is not going up anymore. This is great! Thanks a lot..

If you want I can close the issue, or we can keep it open if you folks want to investigate more.
