### ISSUE TITLE
Photoprism Crashing with DNG files

### ISSUE THREAD

**Issue by mzac** [photoprism/photoprism#2917]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

My install keeps crashing when trying to process some DNG files

#### 2. How can we reproduce it?

Indexing my library

#### 3. What behavior do you expect?

It should not crash

#### 4. What could be the cause of your problem?

DNG files

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

```
time="2022-11-18T08:48:24-05:00" level=info msg="convert: converting IMG_8511.dng to IMG_8511.dng.jpg (darktable-cli)"
time="2022-11-18T08:48:24-05:00" level=trace msg="/usr/bin/darktable-cli /photoprism/originals/2014/2014-12/IMG_8511.dng /photoprism/storage/sidecar/2014/2014-12/IMG_8511.dng.jpg --apply-custom-presets false --width 7680 --height 7680 --hq true --upscale false --core --library :memory:"
time="2022-11-18T08:48:24-05:00" level=debug msg="server: GET /api/v1/status (200) [105.026µs]"
time="2022-11-18T08:48:25-05:00" level=info msg="index: found 1 face in IMG_8510.dng.jpg [5.219882933s]"
time="2022-11-18T08:48:29-05:00" level=trace msg="camera: cache hit for canon-eos-40d"
time="2022-11-18T08:48:29-05:00" level=trace msg="lens: cache hit for ef-s17-85mm-f-4-5-6-is-usm"
time="2022-11-18T08:48:29-05:00" level=debug msg="media: IMG_8510.dng.jpg has color profile sRGB [756.075µs]"
time="2022-11-18T08:48:29-05:00" level=debug msg="photo: 2014/2014-12/IMG_8510 has new title 'Portrait / 2014' [1.544567ms]"
time="2022-11-18T08:48:29-05:00" level=trace msg="index: 2014/2014-12/IMG_8510.dng.jpg has keywords black, portrait"
time="2022-11-18T08:48:30-05:00" level=debug msg="markers: added face mrljqctpci9pxkxq for file frljqct3j5mhq0lq"
time="2022-11-18T08:48:30-05:00" level=debug msg="search: updated index by photo id [6.588801ms]"
time="2022-11-18T08:48:30-05:00" level=debug msg="index: updated yaml file IMG_8510.yml"
time="2022-11-18T08:48:30-05:00" level=info msg="index: stacked related jpg file 2014/2014-12/IMG_8510.dng.jpg"
time="2022-11-18T08:48:30-05:00" level=debug msg="exiftool: extracting metadata from 2014/2014-12/IMG_8512.dng"
time="2022-11-18T08:48:30-05:00" level=trace msg="/usr/bin/exiftool -n -m -api LargeFileSupport -j /photoprism/originals/2014/2014-12/IMG_8512.dng"
time="2022-11-18T08:48:32-05:00" level=debug msg="index: created 1f02fa1cccc922d56bfbab39ab866819216b8820_exiftool.json"
time="2022-11-18T08:48:32-05:00" level=trace msg="convert: /usr/bin/darktable-cli /photoprism/originals/2014/2014-12/IMG_8512.dng /photoprism/storage/sidecar/2014/2014-12/IMG_8512.dng.jpg --apply-custom-presets false --width 7680 --height 7680 --hq true --upscale false --core --library :memory:"
time="2022-11-18T08:48:32-05:00" level=trace msg="convert: /usr/bin/exiftool -q -q -b -PreviewImage /photoprism/originals/2014/2014-12/IMG_8512.dng (alternative)"
time="2022-11-18T08:48:32-05:00" level=info msg="convert: converting IMG_8512.dng to IMG_8512.dng.jpg (darktable-cli)"
time="2022-11-18T08:48:32-05:00" level=trace msg="/usr/bin/darktable-cli /photoprism/originals/2014/2014-12/IMG_8512.dng /photoprism/storage/sidecar/2014/2014-12/IMG_8512.dng.jpg --apply-custom-presets false --width 7680 --height 7680 --hq true --upscale false --core --library :memory:"
time="2022-11-18T08:48:34-05:00" level=debug msg="server: GET /api/v1/status (200) [41.274µs]"
/scripts/entrypoint.sh: line 116:    21 Killed                  "$@"
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 Build [221118-e58fee0fb](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Chome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? N/A

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Beelink U59 Celeron N5095

(b) Physical Memory & Swap Space in GB: 16gb

(c) Storage Type: SSD & NAS

(d) Anything else that might be helpful to know? Running inside K3S

**Comment by lastzero** [comment]
Does it work with Docker? Note we don't provide assistance with using Kubernetes as part of our free community support.

**Comment by mzac** [comment]
I don't have a docker environment setup.  I have been able to index about 18K photos so far in my library but it keeps getting stuck at the same point at these same DNG files so I don't think K3S is the issue.

I thought it could be a storage issue but I doubt that.  All my storage is kept on my Synology NAS and the containers are mounting it via NFS.

My storage is like follows:
```
        volumeMounts:
        - mountPath: /photoprism/originals
          name: originals
        - mountPath: /photoprism/cache
          name: photoprism
          subPath: cache
        - mountPath: /photoprism/storage
          name: photoprism
          subPath: storage
```

```
      - name: originals
        nfs:
          path: /volume1/Family Photos
          server: 192.168.0.10
      - name: photoprism
        nfs:
          path: /volume1/k3s/photoprism
          server: 192.168.0.10
```

**Comment by mzac** [comment]
@lastzero 

I see there is an option 'Disable RawTherapee' should I try this and see if it fixes it?

Edit: That didn't work, I see it is trying to use Darktable.  Will try and disable it.

Edit 2: Disabling dark table works.  No more crashes.  Is this an upstream bug then you think?

**Comment by lastzero** [comment]
Kindly note that bug reports have the highest priority, are processed at night and on weekends, and therefore should not be made unless you are sure you have found a fully reproducible and previously unreported issue that needs to be fixed directly in the app. A quick search shows this likely is a Kubernetes related problem:

- https://github.com/photoprism/photoprism/discussions/2832

In addition, you use NFS. That in combination with the Kubernetes resource management and / or the Rawtherapee / Darktable version could lead to the process being killed. So the problem might as well be related to your individual configuration, Kubernetes, Linux kernel security modules, Rawtherapee, or Darktable.

Our documentation explains how to blacklist certain file extensions for RAW converters so another converter is used:

- https://docs.photoprism.app/getting-started/config-options/#file-converters

**Comment by mzac** [comment]
Thanks I'll keep an eye on the other issue too.  Seems good now with Darktable disabled.

**Comment by lastzero** [comment]
Are these ProRAW DNG files? Darktable and Rawtherapee don't support those yet, so it is likely enough (and fastest) to blacklist DNG for both without disabling Darktable / Rawtherapee completely.

**Comment by mzac** [comment]
They are DNG files I converted a long time ago from my Canon 40D using Lightroom so not sure exactly what kind of DNG files they are.

**Comment by lastzero** [comment]
Should generally work then. It would be great if you could figure out if there is an issue with Darktable that needs to be fixed (and report it to them if necessary). Thank you very much!
