### ISSUE TITLE
Disable FFmpeg check disable video indexing

### ISSUE THREAD

**Issue by titilambert** [photoprism/photoprism#2918]
#### 1. What is not working as documented?

Disable FFmpeg check disable video indexing

![image](https://user-images.githubusercontent.com/47721/202807134-1115e27e-ef83-4aa3-bfe1-610a37fb7c3e.png)

#### 2. How can we reproduce it?

1. Go to 'Settings' -> 'Advanced'
2. Check the box named "Disable FFmpeg"
3. Add a new video to your folder
4. Run indexing
5. The new video is new added

#### 3. What behavior do you expect?

The video should be added (even if the transcoding is not enabled)

#### 4. What could be the cause of your problem?

A bad condition in the code

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 221118-e58fee0fb - AMD64

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Pihole

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Intel Core i7-3770S

(b) Physical Memory & Swap Space in GB: 32G RAM & 6G swap

(c) Storage Type: photos/videos: HDD - database SSD

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

no

**Comment by lastzero** [comment]
We can't create a thumbnail without ffmpeg and thus not index it or show a preview in the UI search results. It should be described like this in our docs. It you feel like the docs must be improved to be more clear on this, you are welcome to send a pull request. Thank you very much!

**Comment by lastzero** [comment]
@titilambert  After reviewing the current documentation, we have expanded it with more detailed information and notes:

- https://docs.photoprism.app/getting-started/troubleshooting/#videos-dont-play
- https://docs.photoprism.app/user-guide/organize/video/#transcoding
- https://docs.photoprism.app/user-guide/settings/advanced/#disable-ffmpeg

Hope this helps!

**Comment by titilambert** [comment]
@lastzero Thanks that's more clear. Also, would you accept a patch that add a new check box allow to use ffmpeg just for indexing and create thumbnail ? (to really just disable transcoding only)

**Comment by lastzero** [comment]
So you want videos not to play if they are in the wrong format?

**Comment by titilambert** [comment]
yes because the video I take are already in the good format

**Comment by lastzero** [comment]
Then they should not get transcoded. Maybe you just want to increase the bitrate limit?

**Comment by lastzero** [comment]
Check the docs for details. They explain which formats can be streamed directly without transcoding:

- MPEG-4 AVC doesn't require transcoding as it can be played natively by most modern browsers, see https://caniuse.com/mpeg4
- OGV, VP8, VP9, AV1, WebM, and HEVC videos can be streamed directly if they are supported by your browser and do not exceed the configured bitrate limit
- other formats must always be transcoded

**Comment by lastzero** [comment]
Did increasing the bitrate limit work for you?

**Comment by titilambert** [comment]
> Did increasing the bitrate limit work for you?

Where is this setting ? I don't find it

**Comment by graciousgrey** [comment]
It's this one: PHOTOPRISM_FFMPEG_BITRATE

--> https://docs.photoprism.app/getting-started/config-options/#file-converters :)

**Comment by titilambert** [comment]
> Did increasing the bitrate limit work for you?

Yeah ! Thanks ! Videos are now playing immediatly and with the original quality ! Thanks !!!!

**Comment by abugray** [comment]
> > Did increasing the bitrate limit work for you?
> 
> 
> 
> Yeah ! Thanks ! Videos are now playing immediatly and with the original quality ! Thanks !!!!

Please say how you get this. I use casa os.

**Comment by lastzero** [comment]
@abugray You will probably need to manually edit some config files or environment variables for this until we have added the additional FFmpeg options to the user interface under [Settings > Advanced](https://demo.photoprism.app/library/settings/advanced).
