### ISSUE TITLE
Pictures stacked despite disabling stacking for Unique ID and Sequential Names

### ISSUE THREAD

**Issue by mrlimacz** [photoprism/photoprism#2919]
I disabled stacking for Unique ID and Sequential Names in library settings. After indexing originals, pictures with the same name (different extension) end up being stacked even though they were taken on a different day.

![Screenshot from 2022-11-19 13-18-19](https://user-images.githubusercontent.com/29689324/202850674-9f0a9b47-348e-4ee0-ab8a-df431c01e40e.png)
![Screenshot from 2022-11-19 13-19-03](https://user-images.githubusercontent.com/29689324/202850682-bc820472-fd83-4b71-a053-d840fa46ddcc.png)
![Screenshot from 2022-11-19 13-19-41](https://user-images.githubusercontent.com/29689324/202850688-d449de3e-ec3a-4ad4-83c4-21cb738bf403.png)

Exiftool output:
```
$ exiftool -g -j -n -time:all *
[{
  "SourceFile": "IMG_8234.jpg",
  "File": {
    "FileModifyDate": "2021:09:13 21:37:25+02:00",
    "FileAccessDate": "2022:11:19 13:14:29+01:00",
    "FileInodeChangeDate": "2022:11:19 13:14:25+01:00"
  },
  "EXIF": {
    "ModifyDate": "2021:08:24 20:38:57",
    "DateTimeOriginal": "2021:08:24 20:38:57",
    "CreateDate": "2021:08:24 20:38:57",
    "OffsetTime": "+03:00",
    "OffsetTimeOriginal": "+03:00",
    "OffsetTimeDigitized": "+03:00",
    "SubSecTimeOriginal": 418,
    "SubSecTimeDigitized": 418,
    "GPSDateStamp": "2021:08:24"
  },
  "ICC_Profile": {
    "ProfileDateTime": "2017:07:07 13:22:32"
  },
  "Composite": {
    "SubSecCreateDate": "2021:08:24 20:38:57.418+03:00",
    "SubSecDateTimeOriginal": "2021:08:24 20:38:57.418+03:00",
    "SubSecModifyDate": "2021:08:24 20:38:57+03:00"
  }
},
{
  "SourceFile": "IMG_8234.JPG",
  "File": {
    "FileModifyDate": "2021:09:13 21:37:25+02:00",
    "FileAccessDate": "2022:11:19 13:14:28+01:00",
    "FileInodeChangeDate": "2022:11:19 13:14:25+01:00"
  },
  "EXIF": {
    "ModifyDate": "2021:08:21 00:20:08",
    "DateTimeOriginal": "2021:08:21 00:20:08",
    "CreateDate": "2021:08:21 00:20:08",
    "OffsetTime": "+03:00",
    "OffsetTimeOriginal": "+03:00",
    "OffsetTimeDigitized": "+03:00",
    "SubSecTimeOriginal": 117,
    "SubSecTimeDigitized": 117
  },
  "Composite": {
    "SubSecCreateDate": "2021:08:21 00:20:08.117+03:00",
    "SubSecDateTimeOriginal": "2021:08:21 00:20:08.117+03:00",
    "SubSecModifyDate": "2021:08:21 00:20:08+03:00"
  }
}]
```
I sent you these two photos over email.

**Comment by lastzero** [comment]
PLEASE USE OUR OFFICIAL BUG REPORT TEMPLATE AND PROVIDE FURTHER INFORMATION, FOR EXAMPLE IF YOU FIRST INDEXED THE FILES WITH THE SETTINGS TURNED ON AND ONLY DISABLED THEM AFTERWARDS. ALSO MAKE SURE TO READ THE USER GUIDE BEFORE OPENING A BUG REPORT:

- https://docs.photoprism.app/user-guide/organize/stacks/#for-what-reasons-can-files-be-stacked

**Comment by lastzero** [comment]
## For what reasons can files be stacked?

1. Files sharing exactly the same file and folder name will always be stacked, for example `/2018/IMG_1234.jpg` and `/2018/IMG_1234.avi`
2. Files with related, sequential names like `/2018/IMG_1234 (2).jpg` and `/2018/IMG_1234 (3).jpg` may be stacked as well (optional)
3. Pictures were taken at the same GPS position and second (optional)
4. Image metadata contains the same *Unique Image ID* or *XMP Instance ID* (optional)

You can change the behaviour for 2 - 4 in [*Settings*](https://docs.photoprism.app/user-guide/settings/library/).

**Note: Changing stacking settings won't unstack already stacked files.**
