### ISSUE TITLE
Count of photos is not updated after deleting pictures

### ISSUE THREAD

**Issue by bjarnemagnussen** [photoprism/photoprism#292]
I am not sure if this is by design, because pictures cannot/should not be deleted. 

But when I remove photos and initiate a re-scan, then the pictures are removed from the frontend but the counter of total pictures does not decrease. If i import the same pictures again then the counter is only increased.

By the way thanks for all the work! I think this is a fantastic project and very much needed!

**Comment by lastzero** [comment]
We have an issue for a purge command. It's already set to important and milestone 1.

**Comment by bjarnemagnussen** [comment]
Oh I didn't see that one! Nice!

**Comment by lastzero** [comment]
With removing photos you mean deleting them physically from the disk? The backend sends incremental updates (like when a photo is added) but also sends the total numbers from time to time (like when you reload). Importing an exact copy should not increase the counter as we detect duplicates.

**Comment by lastzero** [comment]
Just tested: When I move a photo to the archive, the counter is decreased. When I restore it, it is increased. So your report is probably related to deleting physical files from the disk.

**Comment by bjarnemagnussen** [comment]
Yes exactly. It happens when I delete the files from the time system directly. I guess the purge feature would clean this up?

For now a workaround may then be to first put the photos into the archive before deleting them?

**Comment by lastzero** [comment]
Putting them in archive would work for the counters, but it's not very user friendly.

Probably going to implement some kind of soft delete for purge too, so that no metadata gets lost in case files are restored from a backup.

**Comment by lastzero** [comment]
Just pushed our purge command. It also automatically runs when you use our Web UI for indexing, but not when you run `photoprism index` in a terminal. You're welcome to test and provide feedback!

**Comment by lastzero** [comment]
See #234 for commits and more information.

**Comment by uLUViL3gCs** [comment]
I had faced the same problem, that deleting some files physically from disk (removal out of Originals folder) led to some number "discrepancies"/left overs.
With the versions

- PhotoPrism version 200506-6c6ea0a-Linux-x86_64
- PhotoPrism version 200503-0ff34b6-Linux-x86_64

I faced the problem that both the numbers in I) Photos AND in II) Places span did not reflect the file removal, the latest status in Originals folder.

With update to

- PhotoPrism version 200508-305ec3e-Linux-x86_64

I now see that the Photos span (I) seems to reflect/adapt to file removal, but the Places span (II) keeps having left overs.
![Screenshot 2020-05-08 at 10 42 13](https://user-images.githubusercontent.com/64777347/81388813-22aa0880-9119-11ea-8c52-559c8bbb076a.png)
Note that the world map is OK, the removed file having had localization data is no longer listed/shown.

What I did:
OK:
- remove database
- remove files within Originals folder
- restart photoprism
- import files
- trigger Library -> Import -> Import
- trigger Library -> Originals -> Index (Complete Rescan: True)
- check Photos and Places span
- remove one photo from Originals folder
- trigger Library -> Originals -> Index (Complete Rescan: True)

- check navigation pane:
Photos pane number got updated, OK

NOK:
- check navigation pane:
Places pane number still having leftover, NOK

To be sure this is not a browser problem, I logged in from another browser, with same result as described.

[By the way: what a cool project!]

**Comment by lastzero** [comment]
You are right, we only count known places and don't verify if and how many photos there are for each place. Obviously this is for performance reasons, but also because you or somebody you know must have been at the place, so there is no reason to completely delete the place information just to query it again, when another photo at that place is indexed later.

We might count the number of photos for each place with a maintenance worker that runs in the background or after running the purge command. When the count is 0, it will not be counted for the number in the sidebar navigation. Would that be acceptable?

**Comment by lastzero** [comment]
Just pushed additional improvements for edge cases as mentioned in #234. Docker build is running, new image available within the next hour.

**Comment by lastzero** [comment]
Places counter should now be updated after archive, restore, import, index and purge (if triggered via our Web UI / API).

**Comment by lastzero** [comment]
Started a master build after debugging test database issues for hours... if it doesn't fail this time, you can test it in about one hour. Let us know if you find counters that are still not properly updated!

**Comment by uLUViL3gCs** [comment]
> You are right, we only count known places and don't verify if and how many photos there are for each place. Obviously this is for performance reasons, 

Thanks for letting me know; which is, of course, also totally fine.
The GUI “Places” as it is implemented today brings the user to the world map, in which bubbles of numbers are given; I believe/I expect each number represents a unique photo behind.
Having said that, my expectation is that the total number on the navigation “Photos” Pane today shows the summarized / total number of all photos which are on the world map.
The number of “known places” that you are (internally) counting might still be used in case the GUI will later show e.g. a list of all “known locations” to the system/product and maybe in addition to this the corresponding matching photos - if any.
> When the count is 0, it will not be counted for the number in the sidebar navigation. Would that be acceptable?

I think this would do - as this would result in the expectation as stated above.

**Comment by uLUViL3gCs** [comment]
> Let us know if you find counters that are still not properly updated!

I retested above steps with 
- PhotoPrism version 200508-3aad025-Linux-x86_64
and now the situation is different:

What I did: 

OK:
	•	remove database
	•	remove files within Originals folder
	•	restart photoprism ( docker system prune -a; docker-compose pull photoprism; docker-compose up -d --no-deps photoprism)
	•	import files (in total 7; all with different GPS localization)
	•	trigger Library -> Import -> Import
OK: the Photos navigation pane lists the number of all imported photos correctly (7)
NOK: the Places navigation pane lists only 6; observing the world map, it in total shows 7 photos correctly (zooming in, all photos reveal being present at different locations)
![Screenshot 2020-05-08 at 20 34 34](https://user-images.githubusercontent.com/64777347/81439842-54e65500-916f-11ea-8479-ca389611cb62.png)
	•	trigger Library -> Originals -> Index (Complete Rescan: True)
Same result as above
	•	Repeat all steps above; use different browser:
Same result as above

As said, the result is different than what was seen in file-removal test. I propose to re-test file removal only once this new observation is understood.

**Comment by lastzero** [comment]
Places are in fact distinct places, like a town or a village. Think of it as clusters, we also show clusters on the map, not indidivual photos only. Ideally we know the location of all photos at some point.

**Comment by lastzero** [comment]
Labels are likewise the number of labels, not the number of photos with labels.

**Comment by uLUViL3gCs** [comment]
> Places are in fact distinct places, like a town or a village. Think of it as clusters, we also show clusters on the map, not indidivual photos only. Ideally we know the location of all photos at some point.

Alright, I understand, which brings me to the following two questions:
- how come that with the exact same amount and same unique test files I now see 6 clustered places, but in the earlier photoprism versions the number post import was 7, closer to be "correct"/expected? Has something changed in the algorithm of places clustering here - except purge?
- with a complete different set and amount of other pictures, each of which taken in a different country, I get the same result: the number of places is one less than the number of photos
Note that for a few second(s) at the end of the import the correct (rather: the expected) number is shown, but than "it simply goes away, it will disappear like a miracle". It reduces by one.
Note that the log does not show errors; last entry: 2020-05-08 21:48:40 INFO import completed in 39 s

**Comment by lastzero** [comment]
When you have many photos, the number of places should be significantly lower, see screenshot. I've improved the counter according to your suggestion, so that places that have no visible photos are not counted (this may be  the case when it's in archive, missing or there is no JPEG). Note that this counter does not update in real time for performance reasons. 

![Screenshot_20200509_065412](https://user-images.githubusercontent.com/301686/81464446-2e9dd500-91c2-11ea-9235-096f0ea9c1a3.jpg)

**Comment by uLUViL3gCs** [comment]
> Note that this counter does not (always) update in real time for performance reasons.

[Alright, I understand - and I simply might have to get a better "feeling" and system understanding going forward.]

Photos counter (#292):
- for me, it now reflects correctly situations in which files got deleted or added from/to disk (for WebDAV connected accounts (Nextcloud) yet to be checked)

Places counter:
- it is showing "known places" rather than the total number of Photos which are having location data, and the number is not updated in real-time [info only]
- it is "wrong" by "-1"; importing a single file to a fresh database lets the number "1" show up for a second, then disappear (same behavior as described above) and not show up again. Even a photoprism system with a single gps tagged file only, should result in at least one "known place", no?

![Screenshot 2020-05-09 at 11 29 35](https://user-images.githubusercontent.com/64777347/81469965-733c6700-91e8-11ea-9099-664e24cfb75a.png)

**Comment by lastzero** [comment]
> * it is showing "known places" rather than the total number of Photos which are having location data, and the number is not updated in real-time [info only]

In fact there is an absolute number and an event that informs the frontend about added places, labels and photos. Might lead to this behaviour:

> * it is "wrong" by "-1"; importing a single file to a fresh database lets the number "1" show up for a second, then disappear (same behavior as described above) and not show up again. Even a photoprism system with a single gps tagged file only, should result in at least one "known place", no?

We'll investigate this, might be a bug. There's always one place, the "Unknown" place. It should not be counted, so we subtract 1 from the total number. If you have one more place, the counter should be 1, not 0.

**Comment by lastzero** [comment]
@uLUViL3gCs Very well observed! I was under the assumption everyone has an unknown place - that was not true. Now we only filter out the unknown place and the count shows up correctly in the navigation!

**Comment by lastzero** [comment]
Started a new build, new Docker images available soon: https://travis-ci.org/github/photoprism/photoprism/builds/685382665

We now also count photos assigned to labels, so that labels without photos are hidden in a similar way places without photos are not counted. Hopefully all bugs are fixed, so that we can continue working on albums.

**Comment by uLUViL3gCs** [comment]
> Places counter:
>     * it is "wrong" by "-1"; importing a single file to a fresh database lets the number "1" show up for a second, then disappear (same behavior as described above) and not show up again. 

> I was under the assumption everyone has an unknown place - that was not true. Now we only filter out the unknown place and the count shows up correctly in the navigation!

Great job! With 

- PhotoPrism version 200510-561323d-Linux-x86_64

the "-1" problem indeed seems to be "disappeared like a miracle". Now the Places counter seems to be correct. [FYI: I meanwhile also figured out an example of two photos being shot close by (location wise) resulting in only one "known location". 👍🏼 ]

**Comment by lastzero** [comment]
Thanks for testing!
