### ISSUE TITLE
Places Map can't be load

### ISSUE THREAD

**Issue by littleneko** [photoprism/photoprism#2921]
Settings -> Places -> Maps : Basic

Version: PhotoPrism® CE Build 221118-e58fee0fb Docker

I try the official demo https://demo.photoprism.app/library/browse, it work well.

And the version [September 1, 2022](https://github.com/photoprism/photoprism/releases/tag/220901-f493607b0) is no problem.

![image](https://user-images.githubusercontent.com/6368915/202856568-7f1700e9-6759-4be4-a234-2ac7b985d354.png)

**Comment by lastzero** [comment]
These are the basic maps. In our demo, the sponsor features are enabled so you can test the high-resolution world maps we offer:

- https://docs.photoprism.app/getting-started/#maps-places
- https://docs.photoprism.app/getting-started/faq/#are-the-keys-for-using-interactive-world-maps-provided-free-of-charge
- https://photoprism.app/membership

Thank you for supporting our work!
