### ISSUE TITLE
Can't edit PHOTOPRISM_DISABLE_CHOWN on Unraid

### ISSUE THREAD

**Issue by gyto6** [photoprism/photoprism#2927]
Hi,

I was having some trouble when sharing albums as the thumbnails stayed blank like this :

![image](https://user-images.githubusercontent.com/105558798/202911207-6fea6805-f50a-46c2-9817-367b47c5158f.png)

So I edited the variable in Unraid to set PHOTOPRISM_DISABLE_CHOWN as "false" in Unraid.

![image](https://user-images.githubusercontent.com/105558798/202911280-cc057485-4841-4826-adfc-cf3db291773d.png)

And set the docker container to "Privileged" / root

![image](https://user-images.githubusercontent.com/105558798/202911323-58a8ccb1-efdf-4c20-923b-3b4d8a439b2d.png)

Sadly, this still shows up : 

![image](https://user-images.githubusercontent.com/105558798/202911374-c173d5a9-cf71-4f83-8207-5fbc07657a9c.png)

And running photoprism thumbs -f confirms an issue with the permissions:

![image](https://user-images.githubusercontent.com/105558798/202911448-39b1ab8d-74fa-4c93-b3bf-86b8647921e9.png)

Deleting, the thumbnails folder didn't clear the permissions error. Unable to set the variable, is whatever a bug for me, or maybe I'm not documented enough about the way to make it work.

Thanks for your help.

**Comment by lastzero** [comment]
Did you set the PHOTOPRISM_UID variable?

**Comment by lastzero** [comment]
Otherwise, you have to manually fix permissions using the chmod and chown commands (or a graphical user interface).

**Comment by gyto6** [comment]
> 

My mistake, you answered before I finished to edit. I edited the GUID to 0 and that solve this error. 

![image](https://user-images.githubusercontent.com/105558798/202912893-41710640-f1e7-4d1a-8241-137b7b8d1944.png)


![image](https://user-images.githubusercontent.com/105558798/202912758-82e8f440-ad44-4e34-8de1-07c3b8161f54.png)

I'm checking the thumbnails.

Thanks again

**Comment by gyto6** [comment]
I'll create a short tutorial in the contrib as this command is quite important to deal with permissions issues.
