### ISSUE TITLE
Index: Improve the query performance when flagging hidden files

### ISSUE THREAD

**Issue by jerome-cui** [photoprism/photoprism#2928]
I noticed that there is a SQL query causes the CPU to 100% usage all the time, below is the information I found in db slow log:

```
# Time: 221120 17:13:36
# User@Host: photoprism[photoprism] @  [172.24.0.2]
# Thread_id: 392  Schema: photoprism  QC_hit: No
# Query_time: 6288.676700  Lock_time: 0.000035  Rows_sent: 0  Rows_examined: 1836237798
# Rows_affected: 0  Bytes_sent: 0
SET timestamp=1668935616;
UPDATE `photos` SET `photo_quality` = -1  WHERE (id NOT IN (SELECT photo_id FROM files WHERE file_primary = 1 AND file_missing = 0 AND file_error = '' AND deleted_at IS NULL));
```

This maybe the issue of Mariadb because it works with this query "_select count(*) from photos  WHERE (id NOT IN (SELECT photo_id FROM files WHERE file_primary = 1 AND file_missing = 0 AND file_error = '' AND deleted_at IS NULL))_", but how could I avoid this issue in Photoprism?

Database: Mariadb 10.9.3. 
Row count of table 'photos': 86789.

**Comment by lastzero** [comment]
You can suggest a different query that does the same.

**Comment by jerome-cui** [comment]
It happens after I migrated the database from DB in docker to DB in host. It has no problem for db in docker so I tried to re-import the database again and seems it works now. 
Sorry for this report and I will close it.

**Comment by lastzero** [comment]
I have already changed the queries. It would be great if you could test it when a new development preview is available later today!

**Comment by lastzero** [comment]
Any update on this?

**Comment by jerome-cui** [comment]
> Any update on this?

Sorry for the late reply. I did some test on the latest preview and there is no more slow sql query like this. 
Thanks for your work.

**Comment by lastzero** [comment]
Excellent, thank you!
