### ISSUE TITLE
Photoprism maxing out swap space, making system unresponsive.

### ISSUE THREAD

**Issue by kwm1800** [photoprism/photoprism#294]
I am actually at loss where to even start figuring out.

I am currently running photoprism in docker. Right now as a testing I have just about low quality 350 pictures, total of just 700mb in size.

It seems running photoprism long enough will creep up the swap space available at my server, eventually making the server very unresponsive and slow. Stopping photoprism container immediately solves the problem, which frees up swap space.

I have no idea what is causing this, or perhaps this can be a bug too.

**Comment by lastzero** [comment]
Same issue as #291?

If the PhotoPrism needs to render 60 thumbnails (one page) at the same time, the CPU of a Pi is not strong enough and it will run out of RAM.

**Comment by lastzero** [comment]
![Screenshot 2020-05-04 at 13 44 42](https://user-images.githubusercontent.com/301686/80962566-8d9fca80-8e0d-11ea-8d56-98bf9867929f.png)

**Comment by lastzero** [comment]
@graciousgrey Maybe we should disabled on-demand rendering completely if a server has less than 8 cores and 16 GB of memory? We'll also add a big info box to our manual.

**Comment by kwm1800** [comment]
Thank you for the response.

Well... I have to confess my server also runs about 22 containers including several databases and stuffs like Jellyfin media server, but the CPU itself is Ryzen 1600.

I do admit my server may have too little RAM, since it only has 8GB total.

But I can't help about the fact that the total memory usage goes from initial ~2GB to 6.89GB before I terminated the photoprism container seems weird. And this memory usage increased even though I really did not access web interface.

**Comment by kwm1800** [comment]
I restarted the container and I will keep track of memory usage read from both OS and docker. It seems it took about a day to nearly crash my server so I will keep an eye on it.

**Comment by lastzero** [comment]
It's in fact strange if you didn't run any process and didn't open the UI, although it's possible somebody else did that if the port is open?

Images are large files and opening 60 of them at the same time requires a lot of memory. We need to implement some sort of throttling here. If you have many cores and Docker is allowed to use them, it will also increase RAM usage. I think it's possible to limit the number of cores in docker-compose?

**Comment by kwm1800** [comment]
Well, images are large files indeed, but currently the total size of all photos maintained by photoprism is only 700mb. Def not enough to snowball into several gigabyte page files and swap space.

Currently the server is strictly local, and I am the only person who has access to the server.

So, the container has started, and it seems the memory usage is constant when I am not accessing. I will not access web UI completely for at least a day and see if any abnormal issues appear.

I am aware of thumbnail issue, but from my impression, the memory is not being given back to the system after it is used for the thumbnail generation. I shall see how it goes.

**Comment by lastzero** [comment]
700 MB compressed: When we resize them, we need to decode and resample them done using demanding algorithms, see https://github.com/photoprism/photoprism/wiki/Thumbnails

**Comment by lastzero** [comment]
It's running here with 60.000+ photos, some very large. No issues. Doesn't need more than 2.5 GB of RAM. Our demo server has 4 GB running 3 instances. If you only have 8 GB shared with 22 others, it might not be enough though.

**Comment by lastzero** [comment]
Keep us updated and let us know how we can improve user experience... certainly need to be careful with memory usage and make on-demand rendering optional.

**Comment by kwm1800** [comment]
So I did tests and stuffs, here is what I found. Once again I must remind that this is done on docker container version.

1) Fortunately no memory leak as long as I do not access web GUI. That is good. The memory stays same until I visit the web GUI.

2) The biggest issue is that it seems photoprism does not release back (or say, garbage collection?) the memory once used for rendering thumbnail or any possible workings. Once I look at the pictures of my albums, the memory usage increases, and it stays same even after I disconnected from the photoprism.

3) Keep opening and closing web GUI eventually slows down the whole server as memory depletes.


Right now I am getting another 8gb ram stick coming to my home, and see if doubling ram would help the situation, but if the process does not reduce its memory usage by itself, it will crash the system even if I have even more ram.

**Comment by lastzero** [comment]
Spent the day improving our thumbnail configuration. Hope it doesn't break anything.

On-demand rendering of regular thumbnail sizes up to 2048x2048 is now disabled by default. We can also make it dynamic based on system load, but I don't have time for this at the moment (especially testing on all operating systems is a pain).

To get the old behaviour, set `PHOTOPRISM_RESAMPLE_UNCACHED` to `"true"` in `docker-compose.yml`.

Other thumbnail config values were renamed from `PHOTOPRISM_THUMB_*` to `PHOTOPRISM_RESAMPLE_*` and `PHOTOPRISM_JPEG_QUALITY`, since "resample" is also used in our logs. Otherwise it gets confusing, at least for developers.

**Comment by lastzero** [comment]
New Docker images available later today, probably very soon. Let us know if they change anything for you. Did some profiling and it seems most memory is consumed by TensorFlow, not our own code. Added explicit garbage collections calls after import and indexing. Runtime memory information is collected and sent to the client, but not shown in the UI or evaluated yet.

**Comment by lastzero** [comment]
Edit dialog broke, building again...

**Comment by kwm1800** [comment]
Thank you so much for the new update.

I did several tests, and it seems this probably fixed the memory problem caused by thumbnail. After initial increase casued by pre-rendering thumbnail it is stable.

I will definitely report if there is any other related problems.

**Comment by lastzero** [comment]
Excellent, thanks for testing! Hope the sheer amount of config options doesn't scare potential users... thumbnail generation is getting more complex than we hoped.
