### ISSUE TITLE
Config: Do not search empty template paths for files

### ISSUE THREAD

**Issue by chrkau** [photoprism/photoprism#2946]
#### 1. What is not working as documented?

If `CustomTemplatesPath` is not set it defaults to `""`. This is expanded by `TemplateFiles` to `/[A-Za-z0-9]*.*"` which means pretty much all files at `/` are considered templates. This in turn means that if there are any files at the root of the file system (of the container) the app won't start.

#### 2. How can we reproduce it?

Create any file at the root of the file system (of the container) e.g. `dd if=/dev/zero of=/foobar.bin bs=1k count=1`.
Try to start the app and get an error about `foobar.bin` not being a valid template.

#### 3. What behavior do you expect?

The app should start no matter what files there are at `/`.

#### 4. What could be the cause of your problem?

See 1.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

See 2.

#### 6. Which software versions do you use?

Build 221125-e58fee0fb.

**Comment by lastzero** [comment]
Thanks for reporting this!

**Comment by lastzero** [comment]
Let us know if this works for you! I have also started a new preview build for testing. It will be ready within an hour.

**Comment by chrkau** [comment]
Looking good from my side. Thanks a bunch.

**Comment by graciousgrey** [comment]
Thanks for testing :)
