### ISSUE TITLE
Latitude and longitude data not imported from EXIF?

### ISSUE THREAD

**Issue by rewilson** [photoprism/photoprism#295]
Running photoprism on Ubuntu 18.04 LTS via the latest docker image (very cool project, by the way).

When importing a sample set of photos with GPS data in them, they don't appear on Places at all. The log says "no latitude and longitude in metadata". I confirmed via Exiftool that the GPS data is there. Any idea on what I might be doing wrong, or where the issue might be?

[Sample photo with relevant exif data](https://user-images.githubusercontent.com/13723217/81028017-2c3a3300-8ec3-11ea-9e19-f411ac46dc45.jpg)

**Comment by lastzero** [comment]
Strange, thanks for the bug report!

First time I notice a big-endian byte order in Exif, not sure if that means anything. Need some time to experiment. Can we add your image to our official test data files?

```json
[{
  "SourceFile": "81028017-2c3a3300-8ec3-11ea-9e19-f411ac46dc45.jpg",
  "ExifTool": {
    "ExifToolVersion": 11.85
  },
  "File": {
    "FileName": "81028017-2c3a3300-8ec3-11ea-9e19-f411ac46dc45.jpg",
    "Directory": ".",
    "FileSize": "2.9 MB",
    "FileModifyDate": "2020:05:05 18:44:26+02:00",
    "FileAccessDate": "2020:05:05 18:52:11+02:00",
    "FileInodeChangeDate": "2020:05:05 18:52:09+02:00",
    "FilePermissions": "rw-r--r--",
    "FileType": "JPEG",
    "FileTypeExtension": "jpg",
    "MIMEType": "image/jpeg",
    "ExifByteOrder": "Big-endian (Motorola, MM)",
    "ImageWidth": 4940,
    "ImageHeight": 3272,
    "EncodingProcess": "Baseline DCT, Huffman coding",
    "BitsPerSample": 8,
    "ColorComponents": 3,
    "YCbCrSubSampling": "YCbCr4:2:0 (2 2)"
  },
  "JFIF": {
    "JFIFVersion": 1.01,
    "ResolutionUnit": "inches",
    "XResolution": 96,
    "YResolution": 96
  },
  "EXIF": {
    "ImageWidth": 4940,
    "ImageHeight": 3272,
    "Orientation": "Horizontal (normal)",
    "Software": "Perfectly Clear Complete v3 3.6.3.1351",
    "GPSVersionID": "2.0.0.0",
    "GPSLatitudeRef": "South",
    "GPSLatitude": "38 deg 24' 18.70\"",
    "GPSLongitudeRef": "East",
    "GPSLongitude": "144 deg 11' 20.25\"",
    "GPSMapDatum": "WGS-84",
    "Compression": "JPEG (old-style)",
    "XResolution": 0,
    "YResolution": 0,
    "ResolutionUnit": "inches",
    "ThumbnailOffset": 372,
    "ThumbnailLength": 7556,
    "ThumbnailImage": "(Binary data 7556 bytes, use -b option to extract)"
  },
  "XMP": {
    "XMPToolkit": "XMP Core 4.4.0-Exiv2",
    "GPSVersionID": "2.0.0.0",
    "GPSMapDatum": "WGS-84",
    "GPSLatitudeRef": "S",
    "GPSLatitude": "38 deg 24' 18.70\" S",
    "GPSLongitudeRef": "E",
    "GPSLongitude": "144 deg 11' 20.25\" E"
  },
  "Composite": {
    "ImageSize": "4940x3272",
    "Megapixels": 16.2,
    "GPSLatitude": "38 deg 24' 18.70\" S",
    "GPSLongitude": "144 deg 11' 20.25\" E",
    "GPSLatitudeRef": "South",
    "GPSLongitudeRef": "East",
    "GPSPosition": "38 deg 24' 18.70\" S, 144 deg 11' 20.25\" E"
  }
}]
```

**Comment by rewilson** [comment]
> Strange, thanks for the bug report!
> 
> First time I notice a big-endian byte order in Exif, not sure if that means anything. Need some time to experiment. Can we add your image to our official test data files?

Yep, no problem. Let me know if you want me to test / try anything else.

**Comment by lastzero** [comment]
Problem is the GPS version as the parser only accepts 2.2 and 2.3, not 2.0. Unclear what the difference is, probably easy to fix. I'll add a fallback parser, we'll also need that for parsing GPS coordinates in XMP and JSON.

**Comment by lastzero** [comment]
Once CI is complete, I'll start a master build which will automatically be pushed to Docker hub. Takes about one hour.

**Comment by rewilson** [comment]
Great, I'll give it a test later tonight and confirm.

**Comment by rewilson** [comment]
Can confirm this is now working perfectly with all the files in the sample. Nice work! :)

**Comment by lastzero** [comment]
Thanks for testing! I'll close this.

**Comment by shyshov** [comment]
Hello @lastzero 

I am experiencing a similar problem with coordinates from EXIF.
The latest version of the photoprism - PhotoPrism 200514-871c5aa-Linux-x86_64 (running in docker)
Photo taken on Xiaomi Mi A1.
After indexing, longitude and latitude become empty.
In Exiftool data is:
```
GPS Altitude: 63.5 m Above Sea Level
GPS Date / Time: 2019: 05: 12 15: 13: 54Z
GPS Latitude: 53 deg 7 '24.56 "N
GPS Longitude: 18 deg 0 '5.47 "E
GPS Position: 53 deg 7 '24.56 "N, 18 deg 0' 5.47" E
```

I attach the photo. It can be used for testing.
There are no such problems with photos taken on the iPhone 11pro.

Thank you.

![photo sample](https://user-images.githubusercontent.com/9675097/82035651-792ebe00-96a8-11ea-99f0-71e7b58e48e1.jpg)

**Comment by lastzero** [comment]
@shyshov A copy of your file (created with Photoshop) seems to work just fine. Maybe @dsoprea
can help with the original, it's something with the GPS data parser.

**Comment by dsoprea** [comment]
I'll take a look at it tonight (it's 13:40 right now).

**Comment by dsoprea** [comment]
Resolved. The altitude-orientation tag (`GPSAltitudeRef`) spuriously appears more than once, and one of them with the wrong type :) . Now we discard anything that has a type other than what was expected in the registry that is established at the top of the process, which elegantly fixes this specific problem. We previously didn't actually implement this type information anywhere and relied on what was recorded in the stream. Simple enough solution.

```
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0005) TAG-TYPE=[RATIONAL] UNIT-COUNT=(1)> NAME=[GPSAltitudeRef] VALUE=[[260/100]]
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0001) TAG-TYPE=[ASCII] UNIT-COUNT=(2)> NAME=[GPSLatitudeRef] VALUE=[N]
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0002) TAG-TYPE=[RATIONAL] UNIT-COUNT=(3)> NAME=[GPSLatitude] VALUE=[[53/1 7/1 245636/10000]]
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0003) TAG-TYPE=[ASCII] UNIT-COUNT=(2)> NAME=[GPSLongitudeRef] VALUE=[E]
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0004) TAG-TYPE=[RATIONAL] UNIT-COUNT=(3)> NAME=[GPSLongitude] VALUE=[[18/1 0/1 54736/10000]]
 - TAG: IfdTagEntry<TAG-IFD-PATH=[IFD/GPSInfo] TAG-ID=(0x0005) TAG-TYPE=[BYTE] UNIT-COUNT=(1)> NAME=[GPSAltitudeRef] VALUE=[00]
```

**Comment by dsoprea** [comment]
Make sure to update _go-exif_, _go-png-image-structure_, and _go-jpeg-image-structure_ to make sure everything is in sync with the latest changes.

**Comment by lastzero** [comment]
Done that: https://github.com/photoprism/photoprism/commit/46f3f12da83a5a01a445cb729aea628359bebd0c

Errors / warnings are gone, thank you @dsoprea :)

Observations:
* Height and Width changed (which seems correct since we use smaller, resized versions of the original images, however in one case it is 0 now), see commit above.
* `CreateDate` is still not extracted for `image-2011.jpg`, wasn't `DateTimeDigitized` as I hoped (but I've seen that field in other images). Guess we need to add some extra code for this?

https://github.com/photoprism/photoprism/blob/46f3f12da83a5a01a445cb729aea628359bebd0c/internal/meta/exif_test.go#L180

**Comment by lastzero** [comment]
@rewilson Does our latest Docker build work for you?

**Comment by dsoprea** [comment]
It turns out that several tags are in the wrong IFD, including _DateTimeDigitized_ (0x9004). So, it's a malformed image. Once I add [tag-guessing](https://github.com/dsoprea/go-exif/issues/38), you will see this show up in the results.

Before the fix:

```
2020/05/17 19:06:36 exif.tags: [DEBUG]  (302) tags loaded.
2020/05/17 19:06:36 exif.utility: [WARNING]  Tag with ID (0x9004) in IFD [IFD] is not recognized and will be ignored.
2020/05/17 19:06:36 exif.utility: [WARNING]  Tag with ID (0x9286) in IFD [IFD] is not recognized and will be ignored.
2020/05/17 19:06:36 exif.utility: [WARNING]  Tag with ID (0xa403) in IFD [IFD] is not recognized and will be ignored.
2020/05/17 19:06:36 exif.tags: [WARNING]  Type [SSHORT] for tag [XClipPathUnits] is not valid and will be ignored.
```

When I added validation for the types, yesterday, I discovered that several tags are allowed to be multiple types. As a result of the validation, we began skipping some tags. So, I added support for tags supporting multiple types and added the missing types to the _PixelXDimension_ and _PixelYDimension_ tags. It looks like there were more, and this explains why you are no longer getting _ImageWidth_ and _ImageLength_. I'm guessing that your backup plan doesn't produce correct dimensions. Once I added this, it read the same dimensions as were previously asserted in your tests.

Before the fix:

```
2020/05/17 19:06:36 exif.tags: [DEBUG]  (302) tags loaded.
2020/05/17 19:06:36 exif.ifd_enumerate: [WARNING]  Skipping tag [IFD] (0x0100) [ImageWidth] with an unexpected type: SHORT ∉ [LONG]
2020/05/17 19:06:36 exif.ifd_enumerate: [WARNING]  Skipping tag [IFD] (0x0101) [ImageLength] with an unexpected type: SHORT ∉ [LONG]
2020/05/17 19:06:36 exif.ifd_enumerate: [WARNING]  Skipping tag [IFD] (0x829a) [ExposureTime] with an unexpected type: SRATIONAL ∉ [RATIONAL]
2020/05/17 19:06:36 exif.ifd_enumerate: [WARNING]  Skipping tag [IFD] (0x829d) [FNumber] with an unexpected type: SRATIONAL ∉ [RATIONAL]
2020/05/17 19:06:36 exif.ifd_enumerate: [WARNING]  Tag (0x8822) in IFD [IFD] at position (15) has invalid type (8) and will be skipped.
```


Please update the PNG- and JPEG-reader revisions. Make sure your indirect go-exif revision goes up as well.

**Comment by rewilson** [comment]
> 
> 
> @rewilson Does our latest Docker build work for you?

Yep, all still working well - I just pulled, and imported a new set of photos, and they all locate correctly.

**Comment by lastzero** [comment]
Thanks for testing! :)

**Comment by dsoprea** [comment]
We now do some configured secondary lookups when tags aren't valid in the IFDs that they were found in. Using _image-2011.jpg_, three of the four tags are resolved and one is still skipped.

```
2020/05/27 15:31:40 exif.ifd_enumerate: [WARNING]  Tag (0x8822) in IFD [IFD] at position (15) has invalid type (8) and will be skipped.
2020/05/27 15:31:40 exif.ifd_enumerate: [WARNING]  Tag (0x8827) in IFD [IFD] at position (16) has invalid type (8) and will be skipped.
2020/05/27 15:31:40 exif.utility: [DEBUG]  Tag (0x9004) is not valid for IFD [IFD]. Attempting secondary lookup.
2020/05/27 15:31:40 exif.utility: [WARNING]  Tag with ID (0x9004) is not valid for IFD [IFD], but it *is* valid as tag [DateTimeDigitized] under IFD [IFD/Exif] and has the same type [ASCII], so we will use that. This EXIF blob was probably written by a buggy implementation.
2020/05/27 15:31:40 exif.utility: [DEBUG]  Tag (0x9286) is not valid for IFD [IFD]. Attempting secondary lookup.
2020/05/27 15:31:40 exif.utility: [WARNING]  Tag with ID (0x9286) in IFD [IFD] is not recognized and will be ignored.
2020/05/27 15:31:40 exif.utility: [DEBUG]  Tag (0xa403) is not valid for IFD [IFD]. Attempting secondary lookup.
2020/05/27 15:31:40 exif.utility: [WARNING]  Tag with ID (0xa403) is not valid for IFD [IFD], but it *is* valid as tag [WhiteBalance] under IFD [IFD/Exif] and has the same type [SHORT], so we will use that. This EXIF blob was probably written by a buggy implementation.
2020/05/27 15:31:40 exif.ifd_enumerate: [DEBUG]  Next IFD at offset: (00000380)
2020/05/27 15:31:40 exif.ifd_enumerate: [DEBUG]  Parsing IFD [IFD/Exif] (0) at offset (0x01e8) (Collect).
2020/05/27 15:31:40 exif.ifd_enumerate: [DEBUG]  IFD [IFD/Exif] tag-count: (18)
2020/05/27 15:31:40 exif.utility: [DEBUG]  Tag (0x0201) is not valid for IFD [IFD/Exif]. Attempting secondary lookup.
2020/05/27 15:31:40 exif.utility: [WARNING]  Tag with ID (0x0201) is not valid for IFD [IFD/Exif], but it *is* valid as tag [JPEGInterchangeFormat] under IFD [IFD] and has the same type [LONG], so we will use that. This EXIF blob was probably written by a buggy implementation.
2020/05/27 15:31:40 exif.utility: [DEBUG]  Tag (0x0202) is not valid for IFD [IFD/Exif]. Attempting secondary lookup.
2020/05/27 15:31:40 exif.utility: [WARNING]  Tag with ID (0x0202) is not valid for IFD [IFD/Exif], but it *is* valid as tag [JPEGInterchangeFormatLength] under IFD [IFD] and has the same type [LONG], so we will use that. This EXIF blob was probably written by a buggy implementation.
```

@lastzero Update at your convenience.
