### ISSUE TITLE
UX: Add "Share" button to PWA

### ISSUE THREAD

**Issue by benplumley** [photoprism/photoprism#2957]
**Describe what problem this solves and why this would be valuable to many users**

A common pattern in image-viewing mobile apps is the Share button, to quickly send an image from the current app into a different app (eg directly to a contact in a messaging app). This button triggers a system dialog to appear with the user's other apps listed. Photoprism currently doesn't have a button for this.

![image](https://user-images.githubusercontent.com/7894368/204837893-5595d073-82b4-40fc-b08a-a53d0641bdf2.png)

**Describe the solution you'd like**

Please add a Share button which appears alongside the [Download, Favourite, Edit, etc] button toolbar in the PWA, and triggers the system Share UI.

It would work as follows:

- Open an image
- Press Share button
- The system Share UI appears.

This button could also appear in the multi-select menu when many images are selected.

**Describe alternatives you've considered**

Currently, on Android, the only way to share an image to a contact in another app is to:

- Open an image
- Press Download
- Accept the browser's Download dialog
- Open the downloaded image in a separate image viewer
- Use the separate image viewer's Share button
- The system Share UI appears.

The "Share link" option reached by long-pressing the image isn't relevant here as it requires the recipient to be able to access and log into the Photoprism instance.

**Additional context**

I believe this is possible in a PWA, see https://stackoverflow.com/questions/40858803/pwa-interoperability-with-android-apps-services

This is primarily relevant on mobile devices - the graphic above includes Windows but you never see actual software using this icon because it's just as quick to copy and paste the image. On Android, there's no quick way to copy the image and paste it into another app, hence the Share button being useful.

**Comment by benplumley** [comment]
Sorry, this is a complete duplicate of https://github.com/photoprism/photoprism/issues/658 and https://github.com/photoprism/photoprism/issues/1492 - I searched open issues but forgot to search closed ones!

**Comment by graciousgrey** [comment]
I will close this as duplicate, feel free to add additional information/ideas as a comment to #658
