### ISSUE TITLE
Emit a warning notification when not synced since a long time 

### ISSUE THREAD

**Issue by ClementNerma** [photoprism/photoprism#2961]
**Describe what problem this solves and why this would be valuable to many users**

Sometimes it can happen that the PhotoSync client crashes or the server hosting does, which makes synchronization impossible but without any warning.

**Describe the solution you'd like**

When using the synchronization feature (especially with the auto-sync feature), emit a warning no sync. happened after a customizable delay.

For instance, if the auto-sync is enabled, if no synchronization happened after two days, display a warning.

I think this warning should be enabled by default with a default delay as well(e.g. two days?).

**Describe alternatives you've considered**

I don't see any alternative.

**Comment by graciousgrey** [comment]
I think this warning should come from PhotoSync and not PhotoPrism, since PhotoSync is responsible for synchronization. PhotoPrism has no way of knowing if there is a problem with synchronization or if there are simply no new files.

**Comment by ClementNerma** [comment]
> I think this warning should come from PhotoSync and not PhotoPrism, since PhotoSync is responsible for synchronization. PhotoPrism has no way of knowing if there is a problem with synchronization or if there are simply no new files.

Sorry I wasn't very clear, I'm talking about the **PhotoSync mobile app**, NOT PhotoPrism itself.

The PhotoSync mobile app should emit a warning IMO. Of course this wouldn't make much sense for the PhotoPrism app.

**Comment by graciousgrey** [comment]
We do only develop PhotoPrism. Feel free to contact the PhotoSync  team :)

**Comment by ClementNerma** [comment]
Oh, I thought this was from the same team ^^
Sorry I was wrong.
