### ISSUE TITLE
Server: Handle HEAD requests to frontend bootstrap resources

### ISSUE THREAD

**Issue by averymd** [photoprism/photoprism#2965]
#### 1. What is not working as documented?

On build 221118-e58fee0fb, Photoprism returns 404s for HEAD requests to URLs that return 200s when GET requests are made. This began mid-October; I presumably upgraded to the Sept 1 release then. I use HEAD requests to monitor the uptime of the app.

#### 2. How can we reproduce it?

1. Set up build 221118-e58fee0fb (Photoprism Plus) in docker; it doesn't matter if webdav is enabled
2. With the container running, use curl to make a GET request to the login page and see that a 200 is returned in the headers: `curl -i -s http://127.0.0.1:2342/library/login`
3. Run a HEAD request against the same URL and get a 404: ` curl -I -s http://127.0.0.1:2342/library/login`

#### 3. What behavior do you expect?

The HEAD request should return the same status code as its matching GET request, as it did previously.

#### 4. What could be the cause of your problem?

I'm not familiar with Go, but it was updated in the [Sept 2022 release](https://docs.photoprism.app/release-notes/#september-1-2022).

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

N/A, but I can provide some docker-compose details if that would be helpful.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: ARMv7 build 221118-e58fee0fb,

(b) Database Type & Version: MariaDB 10.8

(c) Operating System Types & Versions: Raspbian GNU/Linux 10 (buster)

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Raspberry Pi 4

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

I usually run nginx as a reverse proxy, but the curl commands bypass it, so it shouldn't be relevant.

**Comment by lastzero** [comment]
Use the `GET /api/v1/status` endpoint:

https://demo.photoprism.app/api/v1/status

**Comment by lastzero** [comment]
It's fundamentally because we don't do a redirect for unhandled URLs anymore. To solve this, we can add a head handler in addition to get. Thought the framework catches this.
