### ISSUE TITLE
Issue from my Site after Reuploade it was Fixed

### ISSUE THREAD

**Issue by Einfach-Mxrc** [photoprism/photoprism#2973]
#### 1. What is not working as documented?

iPhone Screenshots Metadata and other Imported Media Metadata gets not used. Pictures from the Camera are working 100% Fine.
Metadata from Screenshots in an Example only use the Imported time Stamp, but when you check Screenshots with a Metadata Reader, it shows the Real time when the Screenshot or Downloaded Media was taken.

#### 2. How can we reproduce it?

Make Screenshots with a iPhone or Download Media from WhatsApp.
Wait a day or so
Uploaded it 
See that the time gets used when the File gets Imported to Photoprism and not the Real time when it was taken

#### 3. What behavior do you expect?

The Real Time when the Screenshot or Media was taken / downloaded.

#### 4. What could be the cause of your problem?

I would think the program that reads the Metadata in the Photoprism Software

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I will send you some Screenshots to the Mail.

#### 6. Which software versions do you use?

(a) Build 221118-e58fee0fb

(b) MySQL 

(c) Linux Ubuntu 20.10 with Docker

(d) Firefox

(e) Sophos firewall

#### 7. On what kind of device is PhotoPrism installed?

LXC container in Docker

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Sophos Firewall

If you need more information feel free to ask :)
Thanks for your awesome work!

**Comment by lastzero** [comment]
Please use Exiftool and show us what metadata is available and which field of it should be used. Also note that screenshots may require a review if this feature is enabled (see documentation).
