### ISSUE TITLE
How to add images to albums

### ISSUE THREAD

**Issue by PascalMinder** [photoprism/photoprism#298]
I am lost. I created an album and uploaded pictures. But I can't find any way to add images to an album. Is this feature missing or am I missing a button or something?

**Comment by lastzero** [comment]
Select them and open the menu in the lower right corner. Yellow button.

**Comment by PascalMinder** [comment]
@lastzero Okay thank you very much. Is there a way to add all photos from a folder in the picture folder to an album?

**Comment by lastzero** [comment]
Not yet, it's an open issue and we'll probably do this automatically as part of the indexing process. You can already search for keywords in file and directory names.

**Comment by PascalMinder** [comment]
Okay thank you.
