### ISSUE TITLE
A deleted photo does not find its way back to the system

### ISSUE THREAD

**Issue by uLUViL3gCs** [photoprism/photoprism#300]
Description:
If a known photo once got deleted from the system (physical removal from disk, followed by an Index), a new import of the EXACT SAME photo does not bring back the photo. The system seems not to trigger a “re-import” of a file that has been known from the past - irrespective of whether it  got deleted in between or not.
You can debate on the severity and also on the likelihood of this scenario; nonetheless I suppose this should be taken care of. As a user I’d like to have the chance to be able to remove a file and later change my opinion and add it again. Same is true in case user accidentally removed a file, observes her/his failure and is trying to correct it some time later again.

Steps to reproduce:
 OK:
	•	remove database 
	•	remove files within Originals folder 
	•	restart photoprism 
	•	import some random files and check that import works OK (Library -> Import -> Import)  
	•	delete ALL or a SET of files  
	•	Re-index system and check that “removal” for the selected file(s) worked correctly (Library -> Originals -> Index (Complete Rescan: True))
		
	
NOK:
	•	Import the EXACT SAME file(s) as deleted earlier and check that files are added (back) to the system
=> None of the re-added files appear in the system; neither any counter nor any list reflects the re-added files
	•	Re-index system to check it solves the problem
=> Same result; re-added files are still not visible

Tested with:
PhotoPrism version 200510-561323d-Linux-x86_64
Firefox 76.0
Chrome Version 81.0.4044.138

**Comment by lastzero** [comment]
Should be visible in archive at least? It's true that photos that have been moved to archive don't get restored when you upload / import them a second time. Since the purge command may now also (soft) delete (=archive) a photo, it's possible that it doesn't get restored too.

**Comment by uLUViL3gCs** [comment]
> Should be visible in archive at least? 

Unfortunately not. Even the archive appears to be/remain empty.

> It's true that photos that have been moved to archive don't get restored when you upload / import them a second time.

I understand. One main difference I see here is that in case A) user actively archived a photo, the file on disk remained in originals folder while in case of B) deleting/purging the photo, it is no longer available.
In case of A) by the way, a restoration is successful.

**Comment by lastzero** [comment]
Already found the issue, pushing a fix soon.

**Comment by lastzero** [comment]
With this fix, re-imported files will even get the file name they previously had.

**Comment by lastzero** [comment]
Thank you! Again, well observed :)

**Comment by lastzero** [comment]
Docker build is running: https://travis-ci.org/github/photoprism/photoprism/builds/685548527

**Comment by uLUViL3gCs** [comment]
> With this fix, re-imported files will even get the file name they previously had.

Excellent! Re-tested with

- PhotoPrism version 200511-984ffb5-Linux-x86_64

Now the pictures indeed are finding way back to the system; also, the earlier file names are applied.

**Comment by lastzero** [comment]
Next build will update photo count in places and labels after webdav sync (download). Hope we're finally done with fixes now!
