### ISSUE TITLE
I can't click the button to add labels

### ISSUE THREAD

**Issue by juanmaocxy** [photoprism/photoprism#3001]
I can't click the button to add labels
what need i to do
![image](https://user-images.githubusercontent.com/58592452/207298836-ed55f4cb-9afa-4e77-812c-2d15da3d709e.png)

**Comment by graciousgrey** [comment]
Please don't create bug reports for support requests. Use discussions instead.

--> https://docs.photoprism.app/user-guide/organize/labels/#add-labels-to-photos

**Comment by juanmaocxy** [comment]
> 
get！
sorry for this
