### ISSUE TITLE
Nextcloud: Fetching full remote directory structure does not seem to be handy for large WebDAV mounted systems

### ISSUE THREAD

**Issue by uLUViL3gCs** [photoprism/photoprism#301]
Assuming there is a WebDAV remote account connected to system. Whenever the user is making changes to “Sync” or “Upload” settings for this account, the following sequence appears to happen:
1) the system is connecting to remote end and is fetching full remote directory structure
2) the full list of remote available folders is given to user to select and update configuration

As such, this sequence seems to work and no problems of this mechanism were observed.
Nonetheless, the bigger the size of the remote structure is, the bigger the following two problems get:
- the duration of 1. is taking (long) time, 
— NC with 600+ folders on RPi3, around 125 seconds
— NC with 2 folders, a few seconds only
- the drop down menu for the remote folder selection is increasing and does not necessarily get handier for the user
![Screenshot 2020-05-11 at 14 33 23](https://user-images.githubusercontent.com/64777347/81562839-c99ad880-9395-11ea-8e0c-dbb5003f42ca.png)

The request to gather full remote directoy structure does not seem to be handled in one operation only; in fact, it seems that for every folder/subfolder there is an request made to remote server.
Of course, the duration of 1. depends on remote server’s performance, too. Still, from usability point of view you might want to consider one of the following ways of implementation:
A) gather full remote sub- & directory structure within one single access (one command) to remote server (not sure this is available with WebDAV in a first place)
B) implement "recursive requests", based on folder hierarchies:
- gather and present only one folder hierarchy X to user at a time
- user chooses a folder for which another remote folder request for underlying hierarchy X-1 is triggered; results is presented to user for selection again
- and so on…

**Comment by uLUViL3gCs** [comment]
related to #225

**Comment by lastzero** [comment]
It's not directly a WebDAV issue, it's even very slow on a regular server within my local 1 GBit/s network with like 5 directories. Agree we should improve UX here.

Prefetching / caching all remote directories seems to be the best option to me as we can not offer autocomplete when every request takes a couple of seconds otherwise. You must be a very slow typer to enjoy this.

**Comment by FrouxBY** [comment]
I have noticed the same issue and investigate a little bit,
the library gowebdav is actually spamming nextcloud with PROPFIND request (one for each file in the nextcloud directory), plus nextcloud (or SabreDAV) find the request to be deprecated. 

For exemple the nextcloud desktop synchronisation client seems to require far less PROPFIND request to get the same information (according to my nextcloud log).

There might be a possibility to improve the request to get folder information with less request to the webDAV server

**Comment by eloo** [comment]
@FrouxBY 
I see the same behaviour with the propfind and i guess also that this is the main problem.
Maybe as quick solution it could be possible to enter the path manually? or at least the first level? 
In my case for example i have an nextcloud instance with a multiple top level directories. all of them have again multiple subdirectories but i only want photoprism to check one the toplevel directories (fotos in my case).
So also for the dropdown it would be enough scan all subdirs of fotos.. 

What do you guys think? 
Thanks

**Comment by lastzero** [comment]
We'll cache it, it's not a big thing... manual entry as fallback is also possible... currently busy with like 100 other small todos for our release, so this has to wait a tiny bit.

**Comment by lastzero** [comment]
Does the caching I've added in June work for you so that we can close this in preparation for our release? If yes, you're welcome to create another issue for further WebDAV improvements if needed.

**Comment by uLUViL3gCs** [comment]
< Sorry, I somehow had missed your change... >

I re-read the thread and re-tested with PhotoPrism® 201019-1aaec319-Linux-x86_64.
As far as my original comment https://github.com/photoprism/photoprism/issues/301#issue-615859240 is concerned, I can not make out any change or system behavioral change.

Should there have been a noticable change?

**Comment by lastzero** [comment]
There is a cache now so that directories are not loaded via WebDAV every time. However, they still need to be loaded once and I don't think it makes sense not to offer autocomplete / a dropdown. Most users don't have that many directories and rather need help with entering the folder name.

**Comment by uLUViL3gCs** [comment]
> There is a cache now so that directories are not loaded via WebDAV every time. However, they still need to be loaded once and I don't think it makes sense not to offer autocomplete / a dropdown. 

Alright, I understand (though for me personally, the manual entry brings more value than an autocomplete/dropdown).

> Most users don't have that many directories and rather need help with entering the folder name.

If we look to those users who might have only one kind of single or default folder where they want to upload to and if this is not going to change often also, I think this solution is doing fine.

Just wondering are there not use cases where the folder is going to change?
How is PP's cache updated to reflect latest NC directory structure - if at all?

**Comment by lastzero** [comment]
The cache expires obviously, but I can't remember the exact time anymore.

**Comment by uLUViL3gCs** [comment]
From my point of view, we can close this issue.
Thanks for your continuous effort!

**Comment by zoenglinghou** [comment]
Thank you all for the work and improvements. Unfortunately, it seems that the aforementioned directory search method is still causing issue for a large file system. I have >100 GB in my Nextcloud, and the directory search is never completed before the connection times out. (The poor server runs on full CPU for quite a while) I am not able to choose a sync directory, and I do not think manually entering the directory works.

Should I open a new issue? Thank you!

**Comment by lastzero** [comment]
Yes, please. Might need to limit the number of directories we fetch for auto complete / dropdowns.

**Comment by zoenglinghou** [comment]
Thanks for replying! It turns out that manually entering a directory works. After a very long time from server processing, the photos are being downloaded and analyzed. I would open a new issue shortly.
