### ISSUE TITLE
failed to get exif info of spec photos 

### ISSUE THREAD

**Issue by Jinvis** [photoprism/photoprism#302]
I have installed photoprism for docker, there is an issue in my machine, some photos' exif info can't be identified correctly, but windows's photo viewer and lightroom can read them correctly, I have tried the go codes in photoprism/interal/meta, it report "{ 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC               false 0  0 0 0 0 0 0 0 0 0 map[]}".  I also tried these photos with dsoprea/go-exif and it works well. Please pay attention to this.

Thanks. 
[Camera.zip](https://github.com/photoprism/photoprism/files/4622037/Camera.zip)

**Comment by lastzero** [comment]
Does it work with our latest docker image and PHOTOPRISM_SIDECAR_JSON set to "true"? This will automatically create JSON sidecar files using exiftool. I'll also take a look at your example flies when I have time. Thank you!

**Comment by lastzero** [comment]
Maybe related to #304, #305 and #295

**Comment by lastzero** [comment]
Tested your files :) When `PHOTOPRISM_SIDECAR_JSON` is disabled, all that is missing with the latest version is GPS data (see https://github.com/dsoprea/go-exif/issues/37):

![Screenshot 2020-05-15 at 15 19 58](https://user-images.githubusercontent.com/301686/82054905-f6b1f880-96bf-11ea-8107-cd2f9c04d2d0.png)

With `PHOTOPRISM_SIDECAR_JSON` set to "true" in `docker-compose.yml`, the location can be indexed too:

![Screenshot 2020-05-15 at 15 21 14](https://user-images.githubusercontent.com/301686/82054902-f580cb80-96bf-11ea-82ef-f405e3312535.png)

**Comment by Jinvis** [comment]
Hi @lastzero,
Thanks for you reply, after I added PHOTOPRISM_SIDECAR_JSON in my docker app, photoprism still can't get the gps info, the Repository is photoprism/photoprism
![image](https://user-images.githubusercontent.com/26951454/82109353-dfc6e100-9767-11ea-9436-ea65908980b2.png)
![image](https://user-images.githubusercontent.com/26951454/82109368-f40ade00-9767-11ea-8cd0-aadf1210e504.png)

Thanks.

**Comment by lastzero** [comment]
You might put true in "quotes" and you have to reindex your originals completely (at least the directory where the file is, you can select it in the autocomplete dropdown).

**Comment by Jinvis** [comment]
This is my photoprism start command in console, is that ok?
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='photoprism' --net='bridge' --log-opt max-size='50m' --log-opt max-file='1' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e 'PHOTOPRISM_SIDECAR_JSON'='true' -p '2342:2342/tcp' -v '/mnt/user/nas/photo/xiamen/test_gps_info/':'/photoprism/originals':'rw' -v '/mnt/user/appdata/photoprism/config/':'/photoprism/config':'rw' -v '/mnt/user/appdata/photoprism/cache/':'/photoprism/cache':'rw' -v '/mnt/user/appdata/photoprism/database/':'/photoprism/database':'rw' 'photoprism/photoprism' 
5588de82dde02653d710a2d3714ad2321e4eecdb9e9e4cae4f61a8d1c4bfcdc2

**Comment by lastzero** [comment]
Can you test again with our latest Docker image?

**Comment by Jinvis** [comment]
Hi @lastzero 
After I install latest photoprism, this issue gone, please close this issue.

Thanks.

**Comment by lastzero** [comment]
Thank you for testing! :)

Remember to re-index after pulling new images and watch out for new / changed configuration options in [docker-compose.yml](https://dl.photoprism.org/docker/docker-compose.yml). Lots of optimizations happening for our release.
