### ISSUE TITLE
Feature request: Photoprism for Freenas/Truenas Jails

### ISSUE THREAD

**Issue by bestrocker221** [photoprism/photoprism#3041]
First of all, thanks for the excellent and useful project that is Photoprism.
I would think a "plugin" for freenas/truenas for deploying Photoprism would make it even better.
That way you can make full use of your nas/storage for pictures!

It would be a great feature, unfortunately I have little knowledge of freebsd to help, at the moment.

**Comment by lastzero** [comment]
AFAIK there is a TrueNAS plugin, but it is maintained externally.

**Comment by charles-997** [comment]
@bestrocker221 You may want to consider TrueNAS Scale which supports Docker, whereas TrueNAS Core only supports TrueNAS specific plugins via the FreeBSD Jails.

In regard to Photoprism supporting TrueNAS Core plugins- my 2 cents is that there are not many users interested in TrueNAS Core Plugin support as compared to users interested in Docker support and therefore this may not be worthwhile for the community / project.

In regard to your specific situation- I think the simpliest path forward would be to either 1) transition your TrueNAS system to TrueNAS Scale which supports Docker Photoprism or 2) run a VM on your TrueNAS Core system and then run Docker within your VM.

**Comment by bestrocker221** [comment]
Makes perfectly sense. Thanks for replying!
