### ISSUE TITLE
Incorrect date for a photo

### ISSUE THREAD

**Issue by machetto** [photoprism/photoprism#305]
I pulled latest docker image today and imported a few older photos. They were captured in 2003 however they are displayed as made in year 2020. Please find attached a JSON file for one of the photos.
[20200514_105139_83E2BCDB.json.txt](https://github.com/photoprism/photoprism/files/4632037/20200514_105139_83E2BCDB.json.txt)

**Comment by lastzero** [comment]
`DateTime` and `DateTimeOriginal` are missing from what I see in your JSON file. Not sure if https://github.com/dsoprea/go-exif knows `CreateDate`, @dsoprea?

Added a fallback today, in case it can be found: https://github.com/photoprism/photoprism/blob/develop/internal/meta/exif.go#L308

**Comment by dsoprea** [comment]
@lastzero CreateDate is not a standard tag.

https://github.com/dsoprea/go-exif/blob/master/v2/tags_data.go

**Comment by lastzero** [comment]
@machetto Does it work with our latest Docker image?

The only file that still didn't work for me what a resized version of your files I created with Photoshop. Not sure if this edge case is a "must have" for a first release.

**Comment by machetto** [comment]
Yes, it does work with the latest version, thanks!
I also used exiftool to create "DateTimeOriginal" attribute based on "ModifyDate":
exiftool "-DateTimeOriginal<ModifyDate" *.jpg -overwrite_original
