### ISSUE TITLE
Search: Ignore deleted albums when using the "unsorted" filter

### ISSUE THREAD

**Issue by andrewlow** [photoprism/photoprism#3051]
#### 1. What is not working as documented?

Using the "Unsorted" feature **photoprism**/library/unsorted we are moving photos into albums.

An album was accidentally created with the wrong name. Since being in an album is just a 'tag' on a photo, it felt safe to delete the album (and yes, we know that albums can be renamed).

The photos were no longer in "Unsorted". In our panic, it also felt like they were missing from "Search" (but we may have been mistaken). They were not in the archive either (but we initially suspected the photos in the album were also deleted)

After hunting around, we located the photos in the Folders **photoprism**/library/folders

This allowed us to recreate the album and all is well.

This still feels like a bug. 

#### 2. How can we reproduce it?

1. Start in the "Unsorted" album view **photoprism**/library/unsorted
2. Select some photos to add to an album.
3. Create the album with these photos.
4. Go to the "Albums" view **photoprism**/library/albums
5. Delete the newly created album.
6. Return to the "Unsorted" view - note that the photos have not re-appeared in this view

#### 3. What behavior do you expect?

When an Album is deleted, assuming those photos only were in a single album, those photos should return to the unsorted view.

#### 4. What could be the cause of your problem?

I'm guessing - but I suspect the Album delete is just removing the Album, and does no clean up of any photos in that album. Thus the photo is still in an Album - but there is no Album to be in.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

This should be simple to reproduce with the steps in (2)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

AMD64
PhotoPrism® CE Build [221118-e58fee0fb](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

MariaDB - mariadb:10.5
from: https://hub.docker.com/_/mariadb

(c) Operating System Types & Versions: Linux, Windows, Android,...

Firefox (latest) on M1 OSX (Mac Air)
Linux AMD64 hosting docker containers for photoprism

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...

Firefox (latest)

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

pi-hole network wide ad blocker

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

Intel Pentium

(b) Physical Memory & Swap Space in GB

16GB with 4GB swap
```
Tasks: 389 total,   1 running, 333 sleeping,   0 stopped,   0 zombie
%Cpu(s): 14.5 us,  9.4 sy,  0.0 ni, 75.2 id,  0.2 wa,  0.0 hi,  0.7 si,  0.0 st
KiB Mem : 16311680 total,  1640044 free,  7842576 used,  6829060 buff/cache
KiB Swap:  4194300 total,  3206140 free,   988160 used.  8336272 avail Mem 
```

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

Mix of RAID1 SSDs + snapraid on large mixed spinning disks

(d) Anything else that might be helpful to know?

No. Thank you for your work on this project.

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Yes. Fronted by nginx https://hub.docker.com/r/linuxserver/nginx setup with 'local only' http:// access. 
This is not a proxy issue

**Comment by lastzero** [comment]
A preview build is already running, but we'll start another one soon so you can test the fix.

**Comment by lastzero** [comment]
Updated *Release Notes* will be available soon as well:
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by andrewlow** [comment]
Wow.. uh.. I'll have to setup to test this real soon. I hope I can move as quickly as you are.

**Comment by andrewlow** [comment]
I just setup a test photoprism (pulling from `:latest`) and re-duplicated the problem.

1. Upload ~300 photos to a new instance
2. Visit Albums->Unsorted
3. Select 3 photos - add to a new album 'Foobar'
4. Visit Albums - delete 'Foobar' album
5. Check Albums->Unsorted - the 3 photos are missing.   **<<== Bug here**
6. Check Search - the 3 photos appear as expected

I will now figure out how to pull a development preview image.. and re-test the same scenario

**Comment by andrewlow** [comment]
Ah.. pulling `photoprism/photoprism:preview` gives me the preview image - doing that right now and re-testing my scenario.

Using the same (possibly slightly corrupted) library from the previous comment - but with the preview image

Hmm.. interesting - the 'missing' photos from (5) above - have come back into 'Unsorted' view. That is promising - but I'm also a little surprised.. but ok, I haven't looked at any of the code changes

Since I have ~300 photos .. I'll just start from
1. Visit Albums->Unsorted
2. Pick 5 different pictures than I did in the above comment (3) 
3. Create a new album 'Christmas'
4. Visit Albums - delete 'Christmas'
5. Check Albums -> Unsorted - the 5 photos are as expected visible. **(no more bug)**

I'm not sure how much more testing you'd like from me on this one - but things seem better for sure.

**Comment by graciousgrey** [comment]
Thanks for testing :)
