### ISSUE TITLE
UX: Back button does not exit full-screen photo browsing on web app

### ISSUE THREAD

**Issue by sltvtr** [photoprism/photoprism#3053]
#### 1. What is not working as documented?

I couldn't find anything on that in documentation or in issues, so I'm reporting here...

When I tap on a photo (from search page, or album, or calendar - no difference) it goes fullscreen. Duh. Then I can swipe to browse other photos. But when I tap back button on the phone I would want to take the same action as the "X" button on the photo. Actualy when I hit "back" the photo stays in fullscreen and the "back" action actualy happens underneath.
So when I was in some album and I'm browsing photos the back button takes me to album list, then to main page (eg. search), then exits the app, but the whole time is happens "behind" that photo that is displayed.

#### 2. How can we reproduce it?

1. Go to for example Albums
2. Enter some album
3. Open some photo
4. Press back button on phone

#### 3. What behavior do you expect?

The back button - I think - should exit fullscreen, back to photo list, like in any other gallery-type app.

#### 4. What could be the cause of your problem?

I don't know, but I've tried Your demo site and there it works! On every client I've tried it behaves as expected.
One thing I've noticed - the URL on demo is "full", with path, arguments, etc:
https://demo.photoprism.app/library/albums/aqoweu7vjjr0qxzz/berlin#&gid=1&pid=3
but on my version the url (when browsing photo from album) looks like this:
http://192.168.0.184:2342/albums/arhh0on3iybvig0e/testalbum

But unfortunately I couldn't find anything related in configuration (maybe I'm missing something..)

#### 6. Which software versions do you use?

a) amd64, docker image: Build220730-0e1222c83
b) mariadb (default from docker)
c) Ubuntu 22.04.1 LTS
d) android chrome 108, firefox 108, chrome, also tried PWA, different phones, tablet - everywhere the same behaviour.
e) disabled any addons for testing.

#### 7. On what kind of device is PhotoPrism installed?

Intel NUC i5, 8GB RAM, SSD disk. 
I don't think it's hardware related..

I'm using NGINX (Nginx Proxy Manager to be precise) but tried without it - the same behaviour.

**Comment by graciousgrey** [comment]
You are running an old version. This has been fixed already:

https://github.com/photoprism/photoprism/issues/2571
https://docs.photoprism.app/release-notes/#november-2-2022

You can find instructions on how to update here: https://docs.photoprism.app/getting-started/updates/

**Comment by sltvtr** [comment]
OMG, it really worked... my bad, that update didn't come to my mind...
Thank You very much :)

**Comment by shtrophic** [comment]
This seems to be broken for me, again. Can anybody confirm?
