### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by mcombalia** [photoprism/photoprism#306]
Hello, thanks for this project it is very interesting.

Is there any way I can set users with passwords required to login and see images / albums?

Thanks

**Comment by lastzero** [comment]
We currently only have a simple login with a single password you can set in `docker-compose.yml`. Multi-user support will be built later and is out of scope for our initial release.

**Comment by RafPe** [comment]
Hi @lastzero I came around this project and it tick all the boxes for me. I would <3 to contribute. Is Multi-user support something we could start working on/discussing details ?

**Comment by lastzero** [comment]
@RafPe as this might have a huge impact on performance, architecture and security, we wait until after our first release, see https://github.com/photoprism/photoprism/issues/98#issuecomment-569683052

The worst thing that can happen is that we deliver multi-user support with security issues. Imagine somebody starts selling a hosted version of PhotoPrism. Besides not getting a single cent, we would also getting blamed for compromised private photos. Right now it's clear that our solution is for single users on their own server.

**Comment by audioscavenger** [comment]
hi all
it's been a year
where is the first release and the multi user support? I tried adding password and users in the 2 database tables aforementioned but cannot login with these errors:
```
photoprism    | time="2021-12-12T18:24:55Z" level=debug msg="http: GET /login (200) [5.946109ms]"
photoprism    | time="2021-12-12T18:25:03Z" level=debug msg="session: created"
photoprism    | time="2021-12-12T18:25:03Z" level=debug msg="http: POST /api/v1/session (200) [1.393105872s]"
photoprism    | time="2021-12-12T18:25:04Z" level=debug msg="api: abort /api/v1/photos with code 401 (Please log in and try again)"
photoprism    | time="2021-12-12T18:25:04Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (401) [1.641352ms]"
photoprism    | 2021/12/12 18:25:04 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:78)
photoprism    | time="2021-12-12T18:25:04Z" level=debug msg="http: GET /api/v1/ws (200) [8.108381079s]"
photoprism    | time="2021-12-12T18:25:04Z" level=debug msg="http: GET / (200) [5.424898ms]"
```
edit: please ignore, i just found the roadmap and it's under development. good luck! and thank you

**Comment by VladoPortos** [comment]
Any news for multi user support ? :)
