### ISSUE TITLE
Update in the documentation

### ISSUE THREAD

**Issue by chris-fj** [photoprism/photoprism#3076]
**Don't use the MariaDB password directly in the migration command **

Since the migration tool to migrate from sqlite to MariaDB offers a mysql-like option to pass the password with -p, it seems sensible to update the docs to use it. Currently, the docs say:

> On the host now run sudo sqlite3mysql -f <PATH_TO_STORAGE_MOUNT>/storage/index.db -d photoprism -u root --mysql-password 'insecure'

and it can be improved to 

> On the host now run sudo sqlite3mysql -f <PATH_TO_STORAGE_MOUNT>/storage/index.db -d photoprism -u root -p

this prevents the usage of raw passwords directly into the command 

**Additional context**

I'd like to create a PR to the docs, but I didn't find the repo of the docs

**Comment by lastzero** [comment]
https://github.com/photoprism/photoprism-docs/tree/master/docs

**Comment by chris-fj** [comment]
I'm closing this issue and opening this one then https://github.com/photoprism/photoprism-docs/issues/148
