### ISSUE TITLE
UX: Custom filters based on saved search queries

### ISSUE THREAD

**Issue by dingedan** [photoprism/photoprism#3087]
**Describe what problem this solves and why this would be valuable to many users**

PhotoPrism already has a [very advanced search feature](https://docs.photoprism.app/user-guide/search/filters/) with many possible text filters but it's a bit of a hassle to always remember the terminology or to always have to type a filter that you frequently use. 

**Describe the solution you'd like**

A custom drop down selection field in the extended search menu with 'bookmarked' search queries. These bookmarks can be managed in the settings section where the list can be maintained. For each entry there are two configurable text fields: 'name' and 'query'. The name is displayed in the selection box and the query is obviously what is then (invisibly) applied when selected in the search. In the settings it should also be possible to delete entries and of course to add new ones. The ability to re-order would be nice to have. 

**Describe alternatives you've considered**

Browser bookmarks

**Additional context**

Use cases for which I'd currently use this:
- Filter for photos with certain missing meta data so I can update those.
- We are multiple users in our family and so far I've uploaded their pictures in different folders, using such a filter would make it easy to switch between photos from the different users or combined. This feature will probably be added soon as part of the multi-user development but until then a custom filter would be useful.

**Comment by kvalev** [comment]
This is very similar to #1431

**Comment by graciousgrey** [comment]
@dingedan as far as I can see  #1431 should cover your use case. I will close this issue as duplicate, feel free to leave a :+1:  in the smart albums issue :)

**Comment by dingedan** [comment]
@graciousgrey : Yes indeed it covers my uses cases, thanks for pointing that out @kvalev. I do feel that the way I had this in mind would be a lot more versatile once the filters are made available in all views as described in #651 but I also understand prioritization of features is needed.
