### ISSUE TITLE
UX: Add ability to un-approve images into the review section

### ISSUE THREAD

**Issue by davidclemens** [photoprism/photoprism#3091]
**Describe what problem this solves and why this would be valuable to many users**

If one approves (by clicking the check mark) a photo that was added to the `Search` > `Review` section automatically, there is no way to undo that action (i.e. "un-approving").

**Describe the solution you'd like**

The possibility to add photos to the `Search` > `Review` section again, after they have been approved, for example by accident.

As I gathered from other issues that, there is no more space in the context menu of a selection for additional buttons, it might be an idea to add a switch `Approved` to each photo's `Info` dialog, similar to `Stackable`, `Favorite`, `Private`, `Scan`, `Panorama`.

**Describe alternatives you've considered**

none

**Additional context**

Thanks a lot for considering and for your great work!

**Comment by lastzero** [comment]
The suggested workflow is that you archive them then, which is also what happens when you click X on the review page.

**Comment by davidclemens** [comment]
Thanks for the swift reply.

Yes, I've also thought about that.
However, at least to me, there is a difference:
Archieved photos are photos that I don't want to see in my library anymore.
Photos in the `Review` section are photos that require my attention because they are missing metadata or are of poor quality.

In my case I accidentally approved ~200 images. I don't want to archieve them all, because I want to keep many of them in my library. However they are missing metadata (coming from WhatsApp), and for some of them I'd like to manually add that metadata. So I'd like to be able to move those photos back into the `Review` section, so I can pick up processing them, when I find the time.

Does that make sense?

**Comment by lastzero** [comment]
Would adding them to a "needs metadata" album be a workable solution or using the private flag instead so they don't get mixed with the other pictures?

**Comment by graciousgrey** [comment]
> Does that make sense?

Yes, it does :). We do have a somewhat related feature request here: 
- https://github.com/photoprism/photoprism/issues/656

**Comment by davidclemens** [comment]
> Would adding them to a "needs metadata" album be a workable solution or using the private flag instead so they don't get mixed with the other pictures?

Yes, I'll use the private flag for now and be more carefull to not accidentally approve photos in the future.

> Yes, it does :). We do have a somewhat related feature request here:

I saw that feature request and I'll be using it a lot when it lands.

Thanks again for the instant replies and your great work. Hopefully, you can get closer to your monthly funding goal soon. I already spread the word to my friends and family.
