### ISSUE TITLE
Delete button not shown on Archive page

### ISSUE THREAD

**Issue by bmbouter** [photoprism/photoprism#3094]
#### 1. What is not working as documented?

Based on the [removing files permanently docs](https://docs.photoprism.app/user-guide/organize/delete/) I expect I can archive a photo and then delete that photo permanently on the archive page. I don't see the 'Delete' button on my UI on the Archive page like the photo shows in the documentation.

#### 2. How can we reproduce it?

I don't know how another user can reproduce it, but here's what the issue is for me.

1. Archive a photo
2. Go to the Archive page
3. Select the archived photo and then click the bottom right actions area (not sure what to call it)
4. Observe there is no delete there.

![image](https://user-images.githubusercontent.com/180319/212091491-b2d9e5de-f136-4324-ba0a-ddad36b63895.png)

#### 3. What behavior do you expect?

I expect to see the trash icon as shown [in the docs](https://docs.photoprism.app/user-guide/organize/delete/).

#### 4. What could be the cause of your problem?

Maybe permissions are my problem. When I did indexing my system was configured with:

* `PHOTOPRISM_READONLY = "true"`
* The photoprism docker user didn't have write permissions on the photos
* The docker-compose mount of the originals folder also specified `:ro`

Since then I've changed all of these things, now:

* `PHOTOPRISM_READONLY = "false"`
* The photoprism user has POSIX write permissions on the photos
* The docker-compose mount of the originals folder does not specify `:rw`

Note, I still have `PHOTOPRISM_DISABLE_CHOWN: "true"` set. I'm not sure if this is part of the problem or not.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I don't see anything meaningful in the logs.

#### 6. Which software versions do you use?

(a) photoprism:latest, sha256 e6f531bbf1b0e0ddd9f88e4f5c3608534368fd148c0881ba4618b0f76f42fe51  Build 221118-e58fee0fb

(b) MaraDB docker container mariadb:10.10

(c) docker-compose

(d) Firefox 108.0.1 on linux, and firefox on android

#### 7. On what kind of device is PhotoPrism installed?

docker-compose running on a QNAP system

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

I use an NGINX reverse proxy, it redirects port 80, and 443 is showing nice TLS (letsencrypt backed) on all connections.

**Comment by graciousgrey** [comment]
Just to be sure, do you have "Delete" enabled in [settings](https://docs.photoprism.app/user-guide/settings/general/#delete)?

**Comment by bmbouter** [comment]
That was it! Thanks!

Am I right in understanding this feature is disabled by default? If so, would it be helpful for me to add a note to the docs page pointing users to this setting?

**Comment by bmbouter** [comment]
Upon re-reading it, it says that as plain as day [here](https://docs.photoprism.app/user-guide/organize/delete/#removing-files-permanently). I don't see an improvement except in my reading lol. Thanks!
