### ISSUE TITLE
Question: Pluggable storage backend to enable running on top of perkeep?

### ISSUE THREAD

**Issue by owais** [photoprism/photoprism#31]
This looks really promising for personal photos. There is also a general purpose personal storage system out there called Perkeep which I think could be a great storage backend for photoprism. Perkeep could be the "database" while photoprism would be the application server and interface. Just wondering if something like this would be possible or even desired for photoprism.

**Comment by owais** [comment]
Link to perkeep: https://perkeep.org/

**Comment by lastzero** [comment]
Thank you for the link. It looks very interesting!

As a photographer, I work a lot with Photoshop and other tools that load and save photos from the filesystem. Storing them somewhere else means uploading/downloading all the time and a chaos in my downloads folder. Unless you use a virtual file system, but then you don't need a pluggable storage backend.

Also we would like to avoid unnecessary complexity. We only implement what is actually needed. So after the core features are all done and there is demand, we can certainly have a look at storage options again.

**Comment by lastzero** [comment]
We should talk again about Perkeep when our MVP is implemented. While I didn't have time to test yet, it seems to have a great developer community and very progressive ideas.
