### ISSUE TITLE
panic: photo label: label is nil #12

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#310]
@ChrisFab16 wrote (see https://github.com/photoprism/photoprism-docs/issues/12):

Version: PhotoPrism version 200505-bc69f22-Linux-x86_64
Running in docker

running "photoprism index" inside the container yields the following error:

panic: photo label: label is nil

goroutine 41 [running]:
github.com/photoprism/photoprism/internal/entity.(*PhotoLabel).ClassifyLabel(...)
/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:47
github.com/photoprism/photoprism/internal/entity.(*Photo).ClassifyLabels(0xc000daac00, 0xc000c60a20, 0x4, 0x4)
/go/src/github.com/photoprism/photoprism/internal/entity/photo.go:141 +0x34c
github.com/photoprism/photoprism/internal/photoprism.(*Index).MediaFile(0xc000e7b890, 0xc000fda000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/photoprism/photoprism/internal/photoprism/index_mediafile.go:338 +0x189e
github.com/photoprism/photoprism/internal/photoprism.IndexWorker(0xc00004aae0)
/go/src/github.com/photoprism/photoprism/internal/photoprism/index_worker.go:23 +0x5ef
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func1(0xc00004aae0, 0xc005788d30)
/go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:86 +0x2b
created by github.com/photoprism/photoprism/internal/photoprism.(*Index).Start
/go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:85 +0x1dc

**Comment by ChrisFab16** [comment]
Verified - works in the latest version. Thanks
