### ISSUE TITLE
indexing gets the date of photo wrong

### ISSUE THREAD

**Issue by agsha** [photoprism/photoprism#3105]
#### 1. What is not working as documented?
When I index my photos folder, around 10% of the photos date is indexed wrongly. They seem to all default to 08-dec-2002 although the photo was taken on another date. I have verified that the metadata contains the date taken. Other photo libraries like shotwell etc dont seem to have this issue

#### 2. How can we reproduce it?
Attaching the problematic file

1. Put the file in a folder
2. index it.
3. Observe that the date is 08-dec-2002 even though the photo was taken in 2013

#### 6. Which software versions do you use?

(a) PhotoPrism Architectur
![IMG_20130712_165427](https://user-images.githubusercontent.com/1808875/212492960-71461441-f6c7-4797-9ce4-b99f51518fe5.jpg)
e & Build Number: AMD64 Build [220901-f493607b0]

(b) Database Type & Version: MySQL, SQLite

(c) Operating System Types & Versions: Ubuntu

(d) Browser Types & Versions: Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? None

You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 7. On what kind of device is PhotoPrism installed?

regular desktop pc

(a) Device / Processor Type: AMD threadripper 3960x

(b) Physical Memory & Swap Space in GB 256GB RAM

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage, 1TB nvme

(d) Anything else that might be helpful to know?

**Comment by lastzero** [comment]
Please upgrade to our latest release and test again. Thank you!

**Comment by agsha** [comment]
can confirm that same issue exists in Build [221118-e58fee0fb]

**Comment by graciousgrey** [comment]
December 8th 2002 is the CreateDate of your photos metadata. Do you have any idea why it differs from the DateTimeOriginal ? 

```
  "DateTimeOriginal": "2013:07:12 16:54:27",
  "CreateDate": "2002:12:08 12:00:00",

```

**Comment by lastzero** [comment]
Note that `CreateDate` is an XMP field and that Shotwell does not seem to have XMP support yet (which is not a bug in PhotoPrism):
- https://gitlab.gnome.org/GNOME/shotwell/-/issues/98
