### ISSUE TITLE
UI issue when thumbnail is missing

### ISSUE THREAD

**Issue by alxjsn** [photoprism/photoprism#312]
When a thumbnail is missing for a photo/video, all the following thumbnails end up opening incorrect photos when they are clicked. I was able to reproduce the issue on the demo site.

Go to `https://demo.photoprism.org/photos?view=cards&order=similar&public=true&quality=3` and notice that the first thumbnail is missing. Clicking on any of the other photos to enlarge them opens the wrong photo.

**Comment by alxjsn** [comment]
This may also be related to #28 

I notice a lot of missing thumbnails for live photo (videos) when grouping by similar.

**Comment by lastzero** [comment]
Thanks for reporting this.

**Comment by lastzero** [comment]
How did you manage to remove the thumbnail on the demo? Did you hack the API and/or is this a second bug? I can see a thumb in the edit dialog, just not in search results...

**Comment by alxjsn** [comment]
I actually didn't have to do anything in th demo, so I guess it's another bug. I think it happens for videos/live photos in my instance.

**Comment by lastzero** [comment]
Nevermind, figured it out. Had to change a few things to make "group by similarity" work with videos, same for search by color.

**Comment by lastzero** [comment]
Updated demo and docker images :)

**Comment by alxjsn** [comment]
Thanks for fixing this! Works for me now :)
