### ISSUE TITLE
Purge corrupt files from originals directory

### ISSUE THREAD

**Issue by alxjsn** [photoprism/photoprism#313]
There are images that have been added to my originals directory that are corrupt. This results in error messages such as the following:

```
ERRO[2020-05-15T22:52:07Z]
 mediafile: can't open /photoprism/originals/2020/05/20200509_032319_D5449203.jpg (invalid JPEG format: short Huffman data)
INFO[2020-05-15T22:52:07Z] mediafile: no new thumbnails created for 20200509_032319_D5449203 [287.768005ms]
```

```
ERRO[2020-05-15T22:58:46Z] mediafile: can't open /photoprism/originals/2020/03/20200326_224837_E95AC402.jpg (invalid JPEG format: bad RST marker)
INFO[2020-05-15T22:58:46Z] mediafile: no new thumbnails created for 20200326_224837_E95AC402 [372.340283ms]
```

Would it be possible to purge my originals of all corrupt images and/or not import them in the first place? I have attached some photos that trigger these errors.

![3](https://user-images.githubusercontent.com/3642823/82103961-e1da6280-96c9-11ea-8cdc-ae1ee1af3dab.jpg)
![2](https://user-images.githubusercontent.com/3642823/82103966-e6068000-96c9-11ea-8922-3114b9260941.jpg)
![1](https://user-images.githubusercontent.com/3642823/82103968-e737ad00-96c9-11ea-9036-43de500266ac.jpg)

**Comment by lastzero** [comment]
Do you see the error message when you look in the files tab (edit dialog) or are the photos not visible in the UI at all? I guess not all errors are the same, some might be less severe. If we don't index and log them at all, you wouldn't know why the files are missing.

**Comment by alxjsn** [comment]
I see these errors when I run `photoprism thumbs`. The photos don't seem to show up in the UI at all.

**Comment by lastzero** [comment]
Note that `photoprism thumbs` doesn't use the database or index, it just creates thumbs in the file system if they don't exist. The UI will only show JPEGs, so unreadable or unconverted images should automatically be hidden. We still keep them in our index so that the indexer doesn't try reading them over and over again.

**Comment by alxjsn** [comment]
One place I do see a missing thumbnail in my instance is for a corrupted jpg + corrupted mov file which are associated with each other. I see it under the video section.

**Comment by lastzero** [comment]
Might be able to fix that when I get test files.

**Comment by lastzero** [comment]
Hopefully fixed while improving our indexer today.

New Docker images available for testing soon:
https://travis-ci.org/github/photoprism/photoprism/builds/688398842

**Comment by lastzero** [comment]
When files are broken, we now store the error message in the files table and hide them from search results (searching for "error:true" should show them for debugging).

**Comment by lastzero** [comment]
No feedback means it's probably working :)

We'll wait a little bit longer with closing this issue.

**Comment by alxjsn** [comment]
Yeah I can see the corrupted files now. Thanks!
