### ISSUE TITLE
UX: Display Map next to individual images

### ISSUE THREAD

**Issue by ravensorb** [photoprism/photoprism#3138]
When viewing individual images it would be nice if there was a way to toggle the map view zoomed into the location of the image being viewed and then from there allow the selection of other images taken at or near the same location.  

This could also work with [Issue 124](https://github.com/photoprism/photoprism/issues/124) 

This idea may be a duplicate from #1307

**Comment by graciousgrey** [comment]
When browsing images in card view you can achieve this by clicking on the location on the card:

   https://docs.photoprism.app/user-guide/organize/places/

If you are referring to the full screen mode #1307 needs to be implemented first.

**Comment by ravensorb** [comment]
I think #1307 would cover it very well!  Thanks
