### ISSUE TITLE
Feature: Change the thumbnail photo of tagged people on the people page.

### ISSUE THREAD

**Issue by dlucksinger** [photoprism/photoprism#3148]
**Describe what problem this solves and why this would be valuable to many users**

I tagged an unflattering photo of my wife and she's mad at me that this is the one that shows up in the people page.

**Describe the solution you'd like**

The ability to go into the people page and select, "Use this as thumbnail"

**Describe alternatives you've considered**

None, I am in trouble.  Please help.

**Additional context**

Please, help.

**Comment by graciousgrey** [comment]
That's planned --> https://github.com/photoprism/photoprism/issues/383 :)

In the original issue you can also find instructions on how to change the cover in the database.
