### ISSUE TITLE
UI/Navigation: Back button/breadcrums for people and tags

### ISSUE THREAD

**Issue by mendoncart** [photoprism/photoprism#3152]
**Describe what problem this solves and why this would be valuable to many users**
If we navigate to people, and select someone to see their pictures, there's no button to go to the previous page (people), so we have to click to people on the side panel again to return to the page.
The same thing happens in tags.

**Describe the solution you'd like**

Use the same style of breadcrums used in moments, calendar, and others views,
![image](https://user-images.githubusercontent.com/62950083/215533331-96b7c284-5daf-4689-a564-7c0a241eb141.png)

**Describe alternatives you've considered**

Using the back button on the browser...

**Additional context**

It'd be good to easily navigate back and fourth pages.

**Comment by lastzero** [comment]
How about using the browser back button or the corresponding touch gesture on mobile devices? Of course, we could add a button to all pages that triggers the same action, but that would take up space and the browser already has such a button...

**Comment by mendoncart** [comment]
Well, yeah. The back browser back button is a workaround, but works.
I just thought since other pages already have the same style of breadcrumbs, it could be implemented on the others without much sacrifice.

But it's just an idea and I don't really know the impacts on the rest of the system this could generate.
Anyway, thanks for the attention, and thanks for the awesome program.

**Comment by lastzero** [comment]
In the case of the People page, the link to filter for a specific person takes you to the regular photo search, so you can add additional filters as needed e.g. filter by year. While we could develop a completely different UI with a higher top toolbar that has space for more elements, most users probably would not want us to replace the existing search box with a (back) button or title with link. In fact, they want us to add a search box to albums as well.

**Comment by mendoncart** [comment]
No problem.
I'll keep comming back with other ideas.
Maybe some of them might be good.

Thanks!
