### ISSUE TITLE
Database: Add manual schema migrations

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#319]
**As a user, I want to upgrade PhotoPrism to any future version without losing data or risking bad performance.**

We're looking for a Go database migration tool or library that also works well together with GORM (similar to Doctrine Migrations for PHP), so that we don't have to use GORMs auto migration feature anymore as it's not suitable for production databases. Recommendations and pull requests welcome.

**Comment by eloo** [comment]
As you are using gorm maybe https://github.com/go-gormigrate/gormigrate would make a good match? 
Or if you want to be more generic https://github.com/golang-migrate/migrate could a good solution.

**Comment by lastzero** [comment]
Thanks for the hints. Taking a look at this tomorrow!

**Comment by lastzero** [comment]
FYI: Still didn't have time to work on this as it didn't seem to have the highest priority compared to link sharing and a couple of important UX issues. Once we are stable, there probably won't be breaking changes to our database. If we need them, we will make sure there is a convenient upgrade path using manual migrations.

**Comment by linosgian** [comment]
Hey! First off, thanks for all the work you've put into photoprism!

I believe that this issue requires more attention, now that Photoprism is about to reach its first stable version.
Up until now, I've refrained from creating albums, marking favorites and so on, because of this.
I think that providing proper schema migrations will greatly improve stability in the long run.

**Comment by lastzero** [comment]
We've added YAML backup files for albums, so they they won't get lost even if your complete database crashes - unless you've intentionally disabled this option. Also note that we've added database backup and restore commands. That's enough feature creep for this year. We won't implement incompatible changes from now on, or provide a tested update script.

**Comment by lastzero** [comment]
@linosgian Favorite flags should also be restored from photo YAML backups when the database gets lost. If that is not the case for you, please report this as bug. Only the archive flag may not be restored yet.

**Comment by linosgian** [comment]
Thanks for the quick response. 
I just found out about the YAML backups.
I guess restoring back to a new schema where a column has been renamed for example would break as well, right?
I am mostly worried about that, since I already backup my database through other means

**Comment by lastzero** [comment]
We won't randomly rename columns in our stable release. Tell me one software that works flawlessly in this case 😉

**Comment by lastzero** [comment]
Adding manual migrations was required to reliably remove an index from the `places` table. Place labels no longer need to be unique as the place id already avoids duplicates: It's based on district, city, state, and country code.
