### ISSUE TITLE
Make MariaDB check optional

### ISSUE THREAD

**Issue by dankasak** [photoprism/photoprism#3199]
**Describe what problem this solves and why this would be valuable to many users**

Photoprism refuses to start up if it encounters some "innodb_version" strings. I understand why this is. However I believe this is not an ideal way to check. It's far more common to check the version() function.

My use-case is bringing up photoprism on TiDB ( https://github.com/pingcap/tidb ). I'm not sure if it will work or not, but it's pretty difficult to even try it if there is no way to make the MariaDB check optional.

**Describe the solution you'd like**

Make the MariaDB check optional.

**Describe alternatives you've considered**

I'm also looking into faking the innodb_version variable in TiDB.

**Comment by lastzero** [comment]
![Screenshot_20230215_014651](https://user-images.githubusercontent.com/301686/218896361-ccee5b78-9b8f-478e-a34a-6cd6a10b55e1.jpg)

**Comment by lastzero** [comment]
In case this was not obvious from the screenshot: You should be able to ignore the failed version check by enabling the unsafe mode via `PHOTOPRISM_UNSAFE: "true"`. We do not document this as it is only for advanced users. Although we initially used TiDB, we have found that MariaDB is easier to use and faster for our purposes.

If you have further questions related to this, it's best to use GitHub Discussions for this.

**Comment by Jobsays** [comment]
I have added PHOTOPRISM_UNSAFE: "true" to my Docker Compose YAML environment variables because I want to use an existing external MariaDB server that is v10.5.8 but the container won't start and still gives the log error message:

`time="2023-10-18T22:49:14Z" level=error msg="config: MariaDB 10.5.8 is not supported, please upgrade to MariaDB 10.5.12 or later (https://docs.photoprism.app/getting-started/#databases)"`

Any ideas?

Thanks!

**Comment by lastzero** [comment]
@Jobsays based on this code you will see an error log message, but the app should start anyway (unless there is another problem or you are using an old version):

https://github.com/photoprism/photoprism/blob/8524fcc14905671a89b037ac9e62c78180f06c17/internal/config/config_db.go#L389-L396

Please next time use GitHub Discussion to ask :)
