### ISSUE TITLE
Search: Full text search with OCR

### ISSUE THREAD

**Issue by daniellandau** [photoprism/photoprism#3206]
It would be super nice to search for documents, signage, etc on the text that's in them. I tested EacyOCR (https://github.com/JaidedAI/EasyOCR) on some samples from my library and while it didn't necessarily provide a perfect transcription usable as a document itself for all cases, it definitely found enough words on almost all images I tried to be usable for a text-to-image search. 

I don't think there's currently any place in the data schema where this would fit and I don't yet have a clear picture in my head where if anywhere the found text should be presented to the user.

**Comment by graciousgrey** [comment]
See: https://github.com/photoprism/photoprism/issues/907 :)
