### ISSUE TITLE
Metadata: Automatically detect scans based on metadata

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3221]
**As a user I want my scanned pictures to appear in the scan section automatically**
- [x] Set scan=true for photos that have a scanner mentioned in their metadata

Examples:
- `"Model": "MS Scanner"`

**Comment by lastzero** [comment]
see https://github.com/photoprism/photoprism/commit/4451447bdd933e3d94144f979c8b1186307bc7e5
