### ISSUE TITLE
Photoprism changes color saturation of images

### ISSUE THREAD

**Issue by kausar007** [photoprism/photoprism#3223]
#### 1. What is not working as documented?
Photoprism changes the way some images look. The clear example would be this painting image on wikipedia. https://upload.wikimedia.org/wikipedia/commons/f/fb/David_Brutus.jpg 

#### 2. How can we reproduce it?
1. Download the image from the link above. 
2. Store it under originals folder and run library scan. 
3. View the file side by side to the wikipedia one. 

#### 3. What behavior do you expect?

Pictures should look the same. It feels like its less saturated.

#### 4. What could be the cause of your problem?

Maybe if there is some sort of processing done on the image. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

See the screenshot below. It shows the difference in saturation. The one on the left is Photoprism and the one on the right is wikipedia. Screenshot taken while they were both open in Chrome side by side. 

![image](https://user-images.githubusercontent.com/4196864/220447480-54378128-8670-43fe-aa9b-a85ffe58f189.png)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64 Docker Image 

(b) Database Type & Version: SQLite

(c) Operating System Types & Versions: MacOS

(d) Browser Types & Versions: Checked with both Chrome and Safari on Mac

**Comment by lastzero** [comment]
Note that we already have an issue for this:
- #1474

**Comment by lastzero** [comment]
```
exiftool -j -g -n David_Brutus.jpg
```

```json
"ICC_Profile": {
    "ProfileCMMType": "APPL",
    "ProfileVersion": 528,
    "ProfileClass": "mntr",
    "ColorSpaceData": "RGB ",
    "ProfileConnectionSpace": "XYZ ",
    "ProfileDateTime": "1999:02:12 00:55:24",
    "ProfileFileSignature": "acsp",
    "PrimaryPlatform": "APPL",
    "CMMFlags": 0,
    "DeviceManufacturer": "none",
    "DeviceModel": "",
    "DeviceAttributes": "0 0",
    "RenderingIntent": 0,
    "ConnectionSpaceIlluminant": "0.9642 1 0.82491",
    "ProfileCreator": "ADBE",
    "ProfileID": "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
    "ProfileCopyright": "(c) 1999 Adobe Systems Inc.",
    "ProfileDescription": "DonRGB4.icm",
    "MediaWhitePoint": "0.96429 1 0.8251",
    "MediaBlackPoint": "0 0 0",
    "RedTRC": "(Binary data 14 bytes, use -b option to extract)",
    "GreenTRC": "(Binary data 14 bytes, use -b option to extract)",
    "BlueTRC": "(Binary data 14 bytes, use -b option to extract)",
    "RedMatrixColumn": "0.64584 0.27838 0.00371",
    "GreenMatrixColumn": "0.19331 0.68796 0.01799",
    "BlueMatrixColumn": "0.12505 0.03366 0.80321",
    "MakeAndModel": "(Binary data 40 bytes, use -b option to extract)"
  }
```

**Comment by lastzero** [comment]
We can currently normalize colors to SRGB, but that only works with Apple Display P3 and not with less common profiles like [DonRGB4](http://www.hutchcolor.com/profiles.html). I also don't know of any camera that uses this, and our software is not designed to download images from Wikipedia either. Once we have a bit of time, we'll embed profiles in the generated thumbnails.

**Comment by kausar007** [comment]
That makes sense. Thanks for the detailed answer.
