### ISSUE TITLE
Videos: Add .dv to the list of known video file extensions

### ISSUE THREAD

**Issue by benklop** [photoprism/photoprism#3226]
As a user with old DV video files withh the extension .dv in my library, I would like photoprism to index and thumbnail these videos without having to transcode them manually beforehand.

**Comment by lastzero** [comment]
Do you have a sample file for testing?

**Comment by lastzero** [comment]
Actual support depends on FFmpeg, so needs to be tested. We'll provide a new development preview later today for you to experiment! Note there's probably not much we can do if it doesn't work.

**Comment by benklop** [comment]
I do have a sample file but github won't let me attach it. I'll try zipping it up.

**Comment by benklop** [comment]
[Wedding & reception001.dv.zip](https://github.com/photoprism/photoprism/files/10808883/Wedding.reception001.dv.zip)

VLC Plays this fine, so I'm hopeful FFmpeg is able to deal with it with no trouble

**Comment by lastzero** [comment]
Was it okay to upload your sample to https://dl.photoprism.app/samples/DV/ so we can continue to use it for testing?

**Comment by benklop** [comment]
yes, that's fine with me.

**Comment by benklop** [comment]
The current preview doesn't appear to contain the commit including DV video - should I just build my own copy with that commit?

**Comment by lastzero** [comment]
Still busy optimizing index performance. Going to build a new preview after that.

**Comment by benklop** [comment]
I've confirmed on a local build that with this change `.dv` files do in fact get recognized, thumbnailed, and play back properly, so FFmpeg does in fact work properly with these.

**Comment by lastzero** [comment]
Thanks for testing it! One more format supported 💐

**Comment by benklop** [comment]
I noticed today after testing this in my full library that the detected length for the dv video is not correct, by a large margin sometimes. This seems like it would have to be an FFmpeg issue but i'm not certain.

**Comment by benklop** [comment]
it actually seems like it might be a consistent 32 or 33 seconds extra length

**Comment by lastzero** [comment]
It could be that only the number of frames is known. In this case we assume 30 FPS, but this is not necessarily correct, so the calculated length may be wrong.

**Comment by benklop** [comment]
ok. I'll see if I can determine things more clearly. The sample i provided earlier is 6 seconds long but is detected as 36 seconds long, which seems too large of a margin to be due to framerate. VLC show the framerate as 29.97, so I don't think it's likely the difference is from assuming 30 fps.

**Comment by benklop** [comment]
it looks like it is exactly 30 extra seconds for other videos I have checked as well.
