### ISSUE TITLE
Metadata: Ignore date string defaults caused by software errors

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3229]
**As a user of a camera or phone with a software bug, I want PhotoPrism to ignore the date information that it writes to metadata so that my pictures don't have the wrong date or time.**

- #3114

The following date strings should be ignored in metadata:

- `0000-00-00`
- `0000-00-00 00:00:00`
- `0000:00:00 00:00:00`
- `0001-01-01 00:00:00`
- `0001:01:01 00:00:00`
- `0001-01-01 00:00:00 +0000 UTC`
- `1970-01-01`
- `1970-01-01 00:00:00`
- `1970:01:01 00:00:00`
- `1980-01-01`
- `1980-01-01 00:00:00`
- `1980:01:01 00:00:00`
- `2002-12-08 12:00:00`
- `2002:12:08 12:00:00`
- and similar

**Comment by lastzero** [comment]
@reidprichard You are invited to test these changes! A new development preview build will be available soon:
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by reidprichard** [comment]
This did the trick! After re-indexing my library I have zero pictures in my "December 2002" folder, whereas I previously had several hundred.

Thank you, @lastzero!

**Comment by GlassedSilver** [comment]
How are false positives avoided? What if I took a shot exactly at midnight on December 8, 2002?

**Comment by lastzero** [comment]
Unlikely.

**Comment by GlassedSilver** [comment]
Unlikely, but not impossible, maybe making this optional or only trigger when there are multiple shots for the exact same time that's sharp midnight might make sense.

If you have a million users unlikely turns into likely to affect a few thousands over time possibly.

**Comment by lastzero** [comment]
If you have such an image, please share it with us.

**Comment by GlassedSilver** [comment]
What if I don't, but people who aren't aware of this new app behavior do, and they scratch their head wondering why they can't find a given image just because they got unlucky by shooting at a too "perfect moment", e.g. at midnight at someone's birthday party?

Is my feedback only valid if it affects me or are you trying to find forensic differences between legit and false midnight shots? Doubt there's much to get, but maybe I'm wrong. (legitimately curious btw)

**Comment by lastzero** [comment]
It can happen, but much much more often it happens that the date is invalid. It's a tradeoff and only affects a single second. So not a lot of pictures as if it were a full day. Probability is on our side.
