### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by eloo** [photoprism/photoprism#324]
Hello,

im just trying out the functions of photoprism and was about to import a couple of fotos from my nextcloud instance.
It started pretty good (after a long time to wait for the directory listing using webday) and then the first images were getting indexed.. But then it started to add new photos.. 
I've checked the logs and see a lot of the following errors
``` 
2020-05-20 19:49:41 ERRO index: Error 1062: Duplicate entry 'Unknown' for key 'uix_places_loc_label'
``` 
Sounds to me like a problem with the database handling? But i'm not sure if this is related with my problem.
I've also checked the files from the webdav download, they are present in the originals folder.
When i try to reindex all, i get the same errors in the logs.

Maybe you have an idea whats going wrong?
Thanks

**Comment by lastzero** [comment]
Obviously this should not happen. Did you start with a fresh database? See  #319

**Comment by eloo** [comment]
Not directly.. i've create the image already a few month ago.. maybe thats the issue yes.. i will purge it and give it a try :+1:

**Comment by lastzero** [comment]
Great, let us know how this works! Bugs will be fixed. We're continuously optimizing our database for the release.

**Comment by eloo** [comment]
Sorry for offtopic
you have mentioned the release already earlier (another issue here).
Do you have any blog about it? What is planned for the release? 
I'm really excited, the project looks really promising!

**Comment by lastzero** [comment]
Wish we had time to write blog posts:)

Remaining issues are listed here: https://github.com/photoprism/photoprism/milestone/1

**Comment by eloo** [comment]
okay.. i have test it with a blank database. 
Looks good now :+1: 

Thanks
