### ISSUE TITLE
Make option to create a new album from gallery more discoverable

### ISSUE THREAD

**Issue by hialvaro** [photoprism/photoprism#326]
As a user I'd like to be able to create an album by selecting the photos from the PhotoPrism gallery without needing to pre-create it from the albums tab.

Right now PhotoPrism only lets me add photos to already created albums. I think it would be useful to let users create their albums by selecting the photos and using the "add to album" option of the bottom bubble menu.

**Comment by hialvaro** [comment]
Sorry, my bad. I just discovered I can already do it. I think the option is not discoverable for new users, so maybe a button would be nice.

**Comment by lastzero** [comment]
Thanks, we do our best to improve user experience! Already noticed that we have many empty albums in our demo, so some users obviously don't know how to add photos.

**Comment by lastzero** [comment]
In addition, @graciousgrey is working on a *User Guide* in this very moment :) 

We probably release a draft of this soon as work in progress, even though it won't be perfect from the start. This way, we can get feedback and basic information on how to work with albums is available.

**Comment by lastzero** [comment]
Added a hint to empty albums:

![Screenshot 2020-07-08 at 09 12 40](https://user-images.githubusercontent.com/301686/86889115-8772e680-c0fb-11ea-96b2-187dc30ab28a.png)

**Comment by lastzero** [comment]
Will it work like that or what other, specific changes must / should be made in addition to this? Right now, I don't know how we can improve further without a lot of extra effort like a/b testing and other ux research.

**Comment by hialvaro** [comment]
From the Gallery view, when selecting albums it is difficult to notice that you are able to create a new album from there. Here's an example:
![current](https://i.imgur.com/UwH02Nb.png)

Imagine being a completely new user. Here you have no clue that you are able to create a new album from here as the option is not displayed to the user. What about something like this?
![idea](https://i.imgur.com/82PKqsV.png)

Another good alternative could be a tooltip message appearing on top. Like this:
![](https://i.imgur.com/PVnI2Un.png)

**Comment by dieideeistgut** [comment]
Personally, and from a UI-X standpoint, i think it is more learned that you could create a new album by selecting something like "Create new Album" at top or bottom of the dropdown. Maybe highlight it with a "+" icon for even more clarification. I have seen this many times and its behavior may have been learned by users. Just my 2 cents.

**Comment by hialvaro** [comment]
@dieideeistgut That would be a good option too.

I just checked how Google Photos is doing that. It defaults you to create a new album (Writing the album name) and right below your albums are listed so you can choose one of them to add the selected photos instead of creating a new one.
