### ISSUE TITLE
File System: Reflect albums on the folder structure in originals

### ISSUE THREAD

**Issue by hialvaro** [photoprism/photoprism#327]
As I user I would like that the albums I create on Photoprism would be reflected the "Originals" folder on my disk. For example, if I create an album called "Day with family" I would like to be able to find it on the "Originals" folder, inside its year.

So if I create an album "Day with family" and photos are from 2020 I would find it inside the 2020 album on "Originals".

This way, the organization that I achieve by creating albums on Photoprism will not be lost If I ever have to remove Photoprism or access the disk from outside Photoprism. This is how, for example, Digikam works with the albums.

**Comment by lastzero** [comment]
At the moment, we don't want to modify (incl. move) photos in originals so that

1. We have to time to build trust in the user community before they let us touch their valuable originals.
2. We don't get in conflict with existing applications like Lightroom that *might* expect a file to be always in the same folder with the same name. Not sure how Digikam would handle this?
3. It's easy to create backups (e.g. using rsync) based on file names only. Backup strategies with continuously moving files are much more complex and may lead to data loss in the worst case.

**Comment by lastzero** [comment]
Important question to clarify: How would you handle a case where two albums contain the same photo or two images (like b/w and color) from the same RAW original, that itself is not part of any album (as it can not be displayed directly in a browser)?

**Comment by lastzero** [comment]
As an alternative, it might be possible to implement an export script that basically creates a backups with your albums as folders. We already have a light version of this: Download as ZIP, when you select an album and click download in the context menu (bottom right).

**Comment by lastzero** [comment]
In any case, backups (in general, exchanging data with other apps) will be taken care of in more detail in future releases. I don't think we should delay our release for this.

**Comment by hialvaro** [comment]
As duplicating pictures is not an option in any way, I think that maybe something like a "master album" would do. 

For example, imagine you have a photo X which you want to have it on two different albums. One is the album "Weekend with family" and the other is "Summer 2020". When you decide to add it to the second album, a prompt to the user to select the "master album" (which would be the one reflected on the filesystem) so all other albums are just symbolic (just like it is done now). This is just an idea  that came to my mind right now, I don't know if this is really possible for Photoprism / easy to implement.

Alternatively, as you say, being able to create a backup of all the gallery including an _album-like folder structure_ would also be a nice option.

**Comment by Ramblurr** [comment]
When importing a large photo collection, how are we supposed to initially create our albums if not via folder import?

I just demoed photo prism with 50GB of photos going back years. They are all now in one giant soup, without any indication as to the original event.

**Comment by lastzero** [comment]
@Ramblurr Do you use our latest Docker image?

In fact, what you are asking for is exactly what we've been working on last week, so I'm a bit shocked :D 

![Screenshot 2020-06-02 at 13 38 36](https://user-images.githubusercontent.com/301686/83515954-7ddfd880-a4d6-11ea-91f9-1ba120920c50.png)

![Screenshot 2020-06-02 at 13 40 19](https://user-images.githubusercontent.com/301686/83516045-a962c300-a4d6-11ea-8d0c-421203389d42.png)

**Comment by Ramblurr** [comment]
@lastzero  Brilliant!

I was using the latest docker image, however I didn't see the :arrow_down_small:  in the sidebar under Albums, and so I didn't see the "Folders" sub-item.

This is really great!

**Comment by graciousgrey** [comment]
The advantage of PhotoPrism's albums is that they are not tied to the filesystem and therefore do not create duplicates. Things like a master album would add complexity to the code and for the user.

> Alternatively, as you say, being able to create a backup of all the gallery including an album-like folder structure would also be a nice option.

I also think exporting/backup files structured by albums --> https://github.com/photoprism/photoprism/issues/620 is the best option here.
