### ISSUE TITLE
FFmpeg: Allow selection of specific video and audio streams for transcoding

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3284]
**As a user with videos that contain additional video or audio streams, I want to select which streams to transcode so that the others are ignored and do not cause problems during transcoding.**

### Updated FFmpeg Config Options

|           Environment            |        CLI Flag         |            Default             |                              Description                              |
|----------------------------------|-------------------------|--------------------------------|-----------------------------------------------------------------------|
| PHOTOPRISM_FFMPEG_BIN            | --ffmpeg-bin            | `ffmpeg`                         | FFmpeg `COMMAND` for video transcoding and thumbnail extraction       |
| PHOTOPRISM_FFMPEG_ENCODER        | --ffmpeg-encoder        | `libx264`                        | FFmpeg AVC encoder `NAME` *sponsors only*                             |
| PHOTOPRISM_FFMPEG_BITRATE        | --ffmpeg-bitrate        |                             `50` | maximum FFmpeg encoding `BITRATE` (Mbit/s)                            |
| PHOTOPRISM_FFMPEG_MAP_VIDEO      | --ffmpeg-map-video      | `0:v:0`                          | video `STREAMS` that should be transcoded                             |
| PHOTOPRISM_FFMPEG_MAP_AUDIO      | --ffmpeg-map-audio      | `0:a:0?`                         | audio `STREAMS` that should be transcoded                             |

### Original Feature Request

> When I upgraded my phone to the Google Pixel 7, I noticed that the videos it takes have an extra video stream in them for their compressed HVC1 implementation. This means that all software transcoding of that format would result in an unplayable video file, as it was transcoding the wrong video stream (likely a second stream of parity or difference data). This alteration fixed the issue for me, and will likely avoid video files with multiple video streams causing issues in the future. 
> — [MEDumont](https://github.com/MEDumont)

### FFmpeg Documentation

- https://trac.ffmpeg.org/wiki/Map

### Related Pull Requests

- https://github.com/photoprism/photoprism/pull/3242
- https://github.com/photoprism/photoprism/pull/3276
- https://github.com/photoprism/photoprism/pull/3283

**Comment by lastzero** [comment]
@ghostwheel We would appreciate it very much if you could help us test this change we added for you!

**Comment by ghostwheel** [comment]
I'd think that this parameter would need to be per video, or per camera, since if someone has a device that produces the important streams not as first, they still might have other videos for which the relevant stream is 0....

**Comment by lastzero** [comment]
Per video? How should that work?

**Comment by lastzero** [comment]
Is it best to remove all of this again? :D

**Comment by ghostwheel** [comment]
I'm not sure. You would have to be able to chose which stream to play when there are several... a hack could be that it would be in the notes of the video. But I wouldn't totally remove it, since it makes things totally not work for some users....
I guess a middle ground would be only use map parameter when several streams exist?

**Comment by lastzero** [comment]
That would require to extract and index that information, which we current do not. It's another day of work at a minimum and we should be stable now as everyone is waiting for the next release. Might not be the right moment to change that much, that quickly?

**Comment by ghostwheel** [comment]
So I think the way you have it would be good.

**Comment by lastzero** [comment]
Alright, I'll keep it that way for now until someone complains or has a better idea we can implement within the time available :+1:

**Comment by ghostwheel** [comment]
Another option would be to totally export all the handling to a separate part that calls ffmpeg, and then users can more easily configure it to their heart's content with being dependent on various attributes of the video. Also not something to do quickly.
