### ISSUE TITLE
restore index: broken pipe

### ISSUE THREAD

**Issue by tebra-jl** [photoprism/photoprism#3298]
Could not restore index after moving from one docker to another:

root@221118-arm64:/photoprism$ photoprism restore -i -f /photoprism/storage/backup/phtotprism-storage.tar 
INFO[2023-03-20T22:34:05Z] PhotoPrism® needs your support!              
INFO[2023-03-20T22:34:05Z] Visit https://photoprism.app/membership to learn more. 
INFO[2023-03-20T22:34:05Z] restoring index from /photoprism/storage/backup/phtotprism-storage.tar 
ERRO[2023-03-20T22:34:06Z] write |1: broken pipe                        
WARN[2023-03-20T22:34:06Z] index could not be restored completely       
INFO[2023-03-20T22:34:06Z] migrating index database schema              
INFO[2023-03-20T22:34:06Z] migrate: executing pre migrations            
INFO[2023-03-20T22:34:09Z] migrate: executing main migrations           
INFO[2023-03-20T22:34:09Z] restored in 3.971288129s                     
INFO[2023-03-20T22:34:09Z] closed database connection

**Comment by lastzero** [comment]
The tar file should be an SQL dump (uncompressed).

**Comment by tebra-jl** [comment]
It works, thank you

**Comment by lastzero** [comment]
See also:
- https://github.com/photoprism/photoprism/issues/3140#issuecomment-1492988026
