### ISSUE TITLE
Connect with nextcloud

### ISSUE THREAD

**Issue by danieldaeschle** [photoprism/photoprism#33]
Is there an option to connect it with my nextcloud and the photos where are stored there?
That would be awesome.

Nextcloud has an gallery plugin but i think this is ways better.

**Comment by lastzero** [comment]
We can remember that for later, why not? Basic functionality first.

**Comment by danieldaeschle** [comment]
What is the actually way to upload images? I think it isn't a good solution to upload the same images on two different places. In addition, nextcloud has mobile clients which photoprism doesn't have at the moment.

Then i have to wait for the release of nextcloud support :D

But nice repo!

**Comment by lastzero** [comment]
Of course, we are still working on our first release ;)

Right now, you have to put them in a directory and run a command. Later you can upload them or use plugins. Give us a little bit of time. We're doing this for free. Glad you like it!

**Comment by abhas** [comment]
Hence, if that directory where a user needs to put them in is a directory that is synced via nextcloud or syncthing, then the files would be there. The command can then be run on a regular schedule or on demand. That automates the entire workflow.

In fact, I would prefer such a workflow. That would keep the photoprism source code simple and clean and people can find a variety of solutions to copy the photos to this directory. When I take photos with my SLR camera (which doesn't have wireless, of course), I typically copy them into a separate gallery folder so nextcloud can sync and back it up.

Now to get these photos into photoprism, I just need to map that same directory to photoprism. In case I install photoprism on the same server as nextcloud, then that's not a difficult thing to do at all!

**Comment by lastzero** [comment]
Well, there are multiple directories: Import, Export and Originals.

Originals contains the unique originals. You put new files in Import and they are getting moved to Originals or deleted if exists. All other files stay in import so that they are not getting lost.

Of course you can put files in Originals directly and simply re-index. But how do you ensure they are unique and properly named? You could end up having a mess.

Export is for photos you want to send / upload / download (e.g. as a zip files), so that they don't mess up the Originals directory.

**Comment by danieldaeschle** [comment]
I'm using e2e encryption in nextcloud, so i can't sync the directory.

**Comment by lastzero** [comment]
We need the files to be unique, otherwise it make the whole thing more complicated that it needs to be. If you let photoprism manage the file names / directories and use nextcloud for syncing, that could be an option. Or you simply import new files from nextcloud. But I think you want some kind of linking / mapping / syncing.

**Comment by lastzero** [comment]
You could write some kind of plugin that maps unique files with normalized file names to randomly named files (that don't have to be unique) in a different directory so that you have total freedom. It's a nice challenge for an afternoon. Actually very similar to what git does.

**Comment by lastzero** [comment]
@graciousgrey We should evaluate how we can integrate with Nextcloud. That way, we don't need our own mobile app for the start, if I got it right.

**Comment by devzsolt** [comment]
For large collections it would be great to find a way to keep all the files directly inside Nextcloud so not just syncing the directories to Nextcloud but somehow operating on these directories that exist in Nextcloud. I'm not familiar with the possible ways so I will investigate it.
This setup would definitely help with mobile syncing without developing your own app.
Keep going man, your project is revolutionary!

**Comment by lastzero** [comment]
@devzsolt Thank you! Need to become familiar with how nextcloud stores photos... what you don't want is to manually search for duplicates and manually name every single file and directory.

**Comment by lastzero** [comment]
Still need them locally for indexing and creating thumbnails with good performance. There are enough good webdav clients our there. Don't think it makes sense to implement one for the first release.

**Comment by lastzero** [comment]
See #41 concerning the use of existing / original file names. Ideally, I would use Nextcloud for uploading to `import/nextcloud`, import the photos from there and access/browse/download them from `originals`. Again, as described in the other ticket, if Nextcloud is your **single source of truth**, you might actually not be looking for a photo management software but a simple gallery for publishing your photos on the Web (from what I know, Nextcloud already has a gallery).

**Comment by twatzl** [comment]
If I may add my 2 cents to this. I currently use nextcloud for managing/syncing my 2tb photo collection.

The nextcloud gallery app: Is in my opinion unsuitable for big photo collections. Even with thumbnails generated it takes forever to navigate around the collection and the gallery app seems pretty buggy. Also separation of concerns would call for a separate app to do this (e.g. Photoprism).

The way I would solve the access to my nextcloud files is via WebDAV. Why? Every access to nextcloud should be done via one of the built-in channels to ensure nextcloud does not get confused and can keep track of changes.

About the performance: You will have some impact by going via WebDAV, but even when running Nextcloud and Photoprism on the same server I would mount Nextcloud via WebDAV and pass that folder as a volume to Photoprism. As indexing is a one time task it would not be too bad if it takes a while.

For the end user display I think Photoprism could vastly improve the performance by showing smaller thumbnails based on the bandwidth. For example by only showing 720p or 1080p preview in the browser unless I click some button to have full resolution.

I tried that setup with WebDAV in a virtual machine using a Nextcloud instance on a server in my local network and it works reasonably well.

**Comment by lastzero** [comment]
@twatzl Since we (the dev team in Berlin) currently don't use Nextcloud, it would be great if you can continue to explore the various options of gluing our apps together in a way that makes sense and that is fast/simple enough... You're welcome to create a wiki page to collect all information and/or write a blog post 👍 

When our core features are done, we will have more time to look into this in detail.

**Comment by graciousgrey** [comment]
We've implemented this recently: Settings > Accounts > Sync
