### ISSUE TITLE
Frontend: Show helpful message if websocket connection fails

### ISSUE THREAD

**Issue by Jinvis** [photoprism/photoprism#330]
Hi,
I use my mariadb for photoprism,  as the pics show, but when I access photoprism through my domain name, the numbers at left gone, and catalogs' options also gone, but it works well when i access with local domain name, such as 192.168.0.242:2342 , it is confused.

![image](https://user-images.githubusercontent.com/26951454/82733753-acc4b480-9d48-11ea-9e2c-73477f01b354.png)

![image](https://user-images.githubusercontent.com/26951454/82733573-3ecbbd80-9d47-11ea-8847-ca45ede31ce1.png)

![image](https://user-images.githubusercontent.com/26951454/82733500-d54baf00-9d46-11ea-9097-1ad750a69891.png)
internet domain name(such as www.baidu.com)

![image](https://user-images.githubusercontent.com/26951454/82733549-1a6fe100-9d47-11ea-96cc-4993bf4b6c3b.png)
local domain name(such as 192.168.0.242:2342)

**Comment by opichals** [comment]
I have seen this earlier and it looked like the numbers were only available right after login-in. Later they disappeared. Logging out and in always brought the numbers back.

**Comment by Jinvis** [comment]
Hi @opichals,
You are right, it work well after relogin, but after I refreshed photoprism page, the issue come again.

**Comment by lastzero** [comment]
Might be a websocket issue, we frequently send updated numbers and lists to the client. You might see an error when you open the browser JavaScript console (developer tools).

**Comment by lastzero** [comment]
See also Official configuration for Caddy #285

**Comment by Jinvis** [comment]
I found a connection error in console:
![image](https://user-images.githubusercontent.com/26951454/82746196-ae7d8f00-9dbf-11ea-9963-defceebc626a.png)

**Comment by voidd** [comment]
@Jinvis if u are using nginx, you can try to add:
```proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_buffering off;
proxy_http_version 1.1;
```

**Comment by opichals** [comment]
Seems it has been indeed caused by the websocket connection failing.

From another angle it should not stop showing the numbers altogether when `numbers update channel` connection is not working IMO. I'd expect it to show stale numbers/filters till the next reload (or re-login) action.

**Comment by lastzero** [comment]
@opichals Yes, indeed we should at least show a clear error message. Since our app makes heavy use of websockets to keep everything in sync, not just the counters, we should disable all actions in the UI to avoid data loss and/or confusion until we have time to implement a fallback mode.

**Comment by Jinvis** [comment]
Hi @lastzero 
It works after add the config in nginx

Thanks

**Comment by lastzero** [comment]
Let's see if we can fix this with additional code before our release. It's mainly a documentation issue so that our users know what the requirements are and how to configure their servers.

**Comment by lastzero** [comment]
If someone from our community has a good idea, we'd be happy to accept a pull request. A warning message that explains the issue and potential solutions would already help.

**Comment by lastzero** [comment]
Message links to this issue until we have finished our docs...

![Screenshot 2020-07-01 at 18 06 45](https://user-images.githubusercontent.com/301686/86269086-886eba00-bbc9-11ea-83e2-af56f9b21ede.png)

**Comment by lastzero** [comment]
Moved the info to the sidebar navigation and added a help page which contains examples for common proxies:

![Screenshot 2020-07-03 at 17 02 55](https://user-images.githubusercontent.com/301686/86481002-6ef77a80-bd4f-11ea-9eb2-b0c1207ce2a8.png)

**Comment by lastzero** [comment]
Seems to work, received no complaints. Please create a new issue if you find a bug!
