### ISSUE TITLE
Sql Backup Doesnt Work as Documented at https://docs.photoprism.app/getting-started/advanced/backups/

### ISSUE THREAD

**Issue by amgschnappi** [photoprism/photoprism#3301]
#### 1. What is not working as documented?

Backup.

#### 2. How can we reproduce it?

Steps to reproduce the behavior:user1@Asus-Mint: $ docker compose exec -T photoprism photoprism backup -i - > photoprism-db.sql
time="2023-03-23T08:31:12Z" level=debug msg="config: running on 'Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz', 3.0 GB memory detected"
time="2023-03-23T08:31:12Z" level=info msg="config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes"
time="2023-03-23T08:31:12Z" level=debug msg="settings: loaded from /photoprism/storage/config/settings.yml"
time="2023-03-23T08:31:12Z" level=info msg="PhotoPrism® needs your support!"
time="2023-03-23T08:31:12Z" level=info msg="Visit https://photoprism.app/membership to learn more."
time="2023-03-23T08:31:12Z" level=debug msg="config: successfully initialized [25.493828ms]"
user1@Asus-Mint: $ ls -la
total 32
drwxrwxr-x 4 user1 user1 4096 Mar 23 09:29 .
drwxrwxr-x 4 user1 user1 4096 Feb  7 15:45 ..
drwxr-xr-x 6 100998 100998 4096 Mar 23 09:30 database
-rw-rw-r-- 1 user1 user1 9018 Mar 23 09:29 docker-compose.yml
-rw-rw-r-- 1 user1 user1    0 Mar 23 09:30 photoprism-db.sql
-rwxrwxr-x 1 user1 user1  143 Feb 22 10:35 Pull_Index.sh
drwxr-xr-x 8 user1 user1 4096 Mar 23 09:31 storage
user1@Asus-Mint:~/DockerApps/PhotoPrism$ 

#### 3. What behavior do you expect?

photoprism-db.sql file should have some size. 0KB size means backup didnt take place.

#### 4. What could be the cause of your problem?

No idea.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

user1@Asus-Mint: $ docker compose exec -T photoprism photoprism backup -i - > photoprism-db.sql
time="2023-03-23T08:31:12Z" level=debug msg="config: running on 'Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz', 3.0 GB memory detected"
time="2023-03-23T08:31:12Z" level=info msg="config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes"
time="2023-03-23T08:31:12Z" level=debug msg="settings: loaded from /photoprism/storage/config/settings.yml"
time="2023-03-23T08:31:12Z" level=info msg="PhotoPrism® needs your support!"
time="2023-03-23T08:31:12Z" level=info msg="Visit https://photoprism.app/membership to learn more."
time="2023-03-23T08:31:12Z" level=debug msg="config: successfully initialized [25.493828ms]"
user1@Asus-Mint: $ ls -la
total 32
drwxrwxr-x 4 user1 user1 4096 Mar 23 09:29 .
drwxrwxr-x 4 user1 user1 4096 Feb  7 15:45 ..
drwxr-xr-x 6 100998 100998 4096 Mar 23 09:30 database
-rw-rw-r-- 1 user1 user1 9018 Mar 23 09:29 docker-compose.yml
-rw-rw-r-- 1 user1 user1    0 Mar 23 09:30 photoprism-db.sql
-rwxrwxr-x 1 user1 user1  143 Feb 22 10:35 Pull_Index.sh
drwxr-xr-x 8 user1 user1 4096 Mar 23 09:31 storage
user1@Asus-Mint:~/DockerApps/PhotoPrism$ 

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
    image: photoprism/photoprism:latest
[PhotoPrism® CE](http://localhost:2342/library/about) Build [221118-e58fee0fb](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
    image: mariadb:latest

(c) Operating System Types & Versions: Linux, Windows, Android,...
$ uname -a
Linux Asus-Mint 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
NA

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
NA

#### 7. On what kind of device is PhotoPrism installed?

Laptop

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...
Intel i3

(b) Physical Memory & Swap Space in GB

free -m
               total        used        free      shared  buff/cache   available
Mem:           11855        2628         324        3271        8903        5642
Swap:           2047         447        1600

 cat /proc/meminfo
MemTotal:       12140072 kB
MemFree:          811600 kB
MemAvailable:    5745944 kB
Buffers:          311488 kB
Cached:          7845076 kB
SwapCached:        27616 kB
Active:          5387540 kB
Inactive:        4766328 kB
Active(anon):    2522820 kB
Inactive(anon):  2833580 kB
Active(file):    2864720 kB
Inactive(file):  1932748 kB
Unevictable:      163872 kB
Mlocked:              16 kB
SwapTotal:       2097148 kB
SwapFree:        1615100 kB
Dirty:             16496 kB
Writeback:             0 kB
AnonPages:       2143120 kB
Mapped:          3457236 kB
Shmem:           3359096 kB
KReclaimable:     681288 kB
Slab:             803044 kB
SReclaimable:     681288 kB
SUnreclaim:       121756 kB
KernelStack:       15856 kB
PageTables:        47036 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8167184 kB
Committed_AS:   10971008 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       39428 kB
VmallocChunk:          0 kB
Percpu:             2928 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      358492 kB
DirectMap2M:    12107776 kB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...
SSD

(d) Anything else that might be helpful to know?

No idea.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by lastzero** [comment]
This might be a buffer issue, which has also been reported elsewhere. As a workaround, you can run `mysqldump` directly.

**Comment by amgschnappi** [comment]
Could you kindly detail the steps I need to do to run the mysqldump directly for photoprism? I am not a DB guy and dont know what to do after going to cmd line.

**Comment by lastzero** [comment]
Official Documentation:
- https://mariadb.com/kb/en/mariadb-dumpmysqldump/

Beginner Tutorials:
- https://linuxize.com/post/how-to-back-up-and-restore-mysql-databases-with-mysqldump/
- https://simplebackups.com/blog/the-complete-mysqldump-guide-with-examples/

Here is our public source code where you can see what command parameters we use:
https://github.com/photoprism/photoprism/blob/1124df15675e7f4158e4da37c32b3db41a346c62/internal/commands/backup.go#L124-L132

**Comment by amgschnappi** [comment]
Bypass / workaround details -->


user1@Asus-Mint: /DockerApps/PhotoPrism$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED       STATUS          PORTS                                   NAMES
0bf850985483   photoprism/photoprism:latest   "/scripts/entrypoint…"   3 days ago    Up 2 hours      0.0.0.0:2342->2342/tcp, 2442-2443/tcp   photoprism-photoprism-1
aa908608acd7   mariadb:latest                 "docker-entrypoint.s…"   11 days ago   Up 20 seconds   3306/tcp                                photoprism-mariadb-1


user1@Asus-Mint: /DockerApps/PhotoPrism$ docker exec -it  photoprism-mariadb-1 mysql -uphotoprism -pinsecure
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.11.2-MariaDB-1:10.11.2+maria~ubu2204 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases
    -> ;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| photoprism         |
+--------------------+
2 rows in set (0.007 sec)


user1@Asus-Mint: /DockerApps/PhotoPrism$ docker exec photoprism-mariadb-1 mysqldump -uphotoprism -pinsecure photoprism > ./photoprism_db_backup.sql


user1@Asus-Mint: /DockerApps/PhotoPrism$ ls -la
total 648116
drwxrwxr-x 4 user1 user1      4096 Mar 28 14:19 .
drwxrwxr-x 3 user1 user1      4096 Mar 24 13:23 ..
drwxr-xr-x 6 100998 100998      4096 Mar 28 14:18 database
-rw-rw-r-- 1 user1 user1      9104 Mar 23 19:20 docker-compose.yml
-rw-rw-r-- 1 user1 user1 663633588 Mar 28 14:21 photoprism_db_backup.sql
-rwxrwxr-x 1 user1 user1       143 Feb 22 10:35 Pull_Index.sh
drwxr-xr-x 8 user1 user1      4096 Mar 28 12:21 storage
user1@Asus-Mint: /DockerApps/PhotoPrism$

**Comment by lastzero** [comment]
See:
- https://github.com/photoprism/photoprism/issues/3140#issuecomment-1492988026
