### ISSUE TITLE
Photo import uses EXIF tag "Date Time Digitized" instead of "Date Time Original" 

### ISSUE THREAD

**Issue by daniellandau** [photoprism/photoprism#3309]
#### 1. What is not working as documented?

I have no idea why some of my pictures from 2017 have this other field "Date Time Digitized" set to a date in 2002. Searching online it seems that it's a thing that sometimes happens to others too and Adobe tools get confused by it too: https://community.adobe.com/t5/lightroom-classic-discussions/date-time-original-vs-date-time-digitized/td-p/9464478

In PhotoPrism, the picture is shown as being from 2002, even though it is from 2017 and there are enough EXIF tags to show that it should be 2017.

#### 2. How can we reproduce it?

Import the attached picture. 

#### 3. What behavior do you expect?

The time for the picture should be taken from "Date Time Original", or "GPS Date Stamp" + "GPS Time Stamp".

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![IMG_20170531_184323](https://user-images.githubusercontent.com/1044056/228039732-6fc67457-2ab3-4ea5-8102-c01e2f9edda4.jpg)

Zip in case GitHub messed up the tags on the image:

[IMG_20170531_184323.zip](https://github.com/photoprism/photoprism/files/11082106/IMG_20170531_184323.zip)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

AMD64 latest docker release, CE Build 221118-e58fee0fb

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

MariaDB 10.10

(c) Operating System Types & Versions: Linux, Windows, Android,...

Linux

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

AMD Ryzen 7 4700G

(b) Physical Memory & Swap Space in GB

Memory: 38Gi, Swap 14Gi

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

Database and storage on NVME, pictures on BTRFS raid1 on spinning HDD

**Comment by lastzero** [comment]
This is an Android bug and we have already implemented a workaround:
- #3229
