### ISSUE TITLE
Album view shows only first 59 photos

### ISSUE THREAD

**Issue by opichals** [photoprism/photoprism#331]
Steps to reproduce
* go to https://demo.photoprism.org
* select all photos in the photos section (show 83 photos)
* add to album (create a new one e.g. 'Test')
* go to 'Test' album view and see only the first 59 images being rendered (mosaic view)
   shows `59 photos found` notification even though the album has more photos

Tested in latest stable Google Chrome.

Similarly it also appears on 3 weeks old local docker-based [photoprism/photoprism:20200429](https://hub.docker.com/layers/photoprism/photoprism/20200429/images/sha256-ecf1703af071f569169b5969889430cd8d3a9ed02b2d227813a4038012536478?context=explore)  install where it says 38 photos while there is more than a hundred items in the `photos_albums` table in the DB associated with the particular album `uuid`.

**Comment by lastzero** [comment]
Good catch! Fixed it locally, but can't push right now as I'm in the middle of a huge change for albums.

**Comment by opichals** [comment]
Seems like master doesn't have this already (just updated my git working copy).

**Comment by lastzero** [comment]
No, it's just fixed on my computer. Will be pushed to `develop` when I'm done, then `master`.

**Comment by lastzero** [comment]
Was a JS issue as we've changed how results are counted, forgot to change it in albums.

**Comment by lastzero** [comment]
It's fixed, you can test it on our demo when we release a new Docker build, hopefully tomorrow or later this week. Currently working on moments with some breaking changes.

**Comment by opichals** [comment]
@lastzero Just tried to create a new _80 Photos_ album https://demo.photoprism.org/albums/aqb05e7jcvk8qlxs?view=mosaic&order=oldest album and it still only shows 59 photos added.

**Comment by lastzero** [comment]
@opichals Still no new Docker builds, will let you know when it's merged to master.

**Comment by opichals** [comment]
@lastzero Looks good at demo.photoprism.org now.
