### ISSUE TITLE
Photoprism Backup doesnt work as Documented at https://docs.photoprism.app/user-guide/backups/restore/ 

### ISSUE THREAD

**Issue by amgschnappi** [photoprism/photoprism#3311]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

Restoring the backup

#### 2. How can we reproduce it?

user1@Asus-Mint: /DockerApps/PhotoPrism$ ls -la
total 648116
drwxrwxr-x 4 user1 user1      4096 Mar 28 14:19 .
drwxrwxr-x 3 user1 user1      4096 Mar 24 13:23 ..
drwxr-xr-x 6 100998 100998      4096 Mar 28 14:18 database
-rw-rw-r-- 1 user1 user1      9104 Mar 23 19:20 docker-compose.yml
-rw-rw-r-- 1 user1 user1 663633588 Mar 28 14:21 photoprism_db_backup.sql
-rwxrwxr-x 1 user1 user1       143 Feb 22 10:35 Pull_Index.sh
drwxr-xr-x 8 user1 user1      4096 Mar 28 15:13 storage
user1@Asus-Mint: /DockerApps/PhotoPrism$ docker compose exec photoprism photoprism restore -i ./photoprism_db_backup.sql 
INFO[2023-03-28T13:50:37Z] config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes 
INFO[2023-03-28T13:50:37Z] PhotoPrism® needs your support!              
INFO[2023-03-28T13:50:37Z] Visit https://photoprism.app/membership to learn more. 
ERRO[2023-03-28T13:50:37Z] SQL dump not found: ./photoprism_db_backup.sql 
INFO[2023-03-28T13:50:37Z] closed database connection                   
user1@Asus-Mint: /DockerApps/PhotoPrism$ 

#### 3. What behavior do you expect?

Backup should be restored

#### 4. What could be the cause of your problem?

No idea

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

user1@Asus-Mint: /DockerApps/PhotoPrism$ ls -la
total 648116
drwxrwxr-x 4 user1 user1      4096 Mar 28 14:19 .
drwxrwxr-x 3 user1 user1      4096 Mar 24 13:23 ..
drwxr-xr-x 6 100998 100998      4096 Mar 28 14:18 database
-rw-rw-r-- 1 user1 user1      9104 Mar 23 19:20 docker-compose.yml
-rw-rw-r-- 1 user1 user1 663633588 Mar 28 14:21 photoprism_db_backup.sql
-rwxrwxr-x 1 user1 user1       143 Feb 22 10:35 Pull_Index.sh
drwxr-xr-x 8 user1 user1      4096 Mar 28 15:13 storage
user1@Asus-Mint: /DockerApps/PhotoPrism$ docker compose exec photoprism photoprism restore -i ./photoprism_db_backup.sql 
INFO[2023-03-28T13:50:37Z] config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes 
INFO[2023-03-28T13:50:37Z] PhotoPrism® needs your support!              
INFO[2023-03-28T13:50:37Z] Visit https://photoprism.app/membership to learn more. 
ERRO[2023-03-28T13:50:37Z] SQL dump not found: ./photoprism_db_backup.sql 
INFO[2023-03-28T13:50:37Z] closed database connection                   
user1@Asus-Mint: /DockerApps/PhotoPrism$ 

#### 6. Which software versions do you use?

image: photoprism/photoprism:latest
    restart: unless-stopped
    depends_on:
      - mariadb
   
#### 7. On what kind of device is PhotoPrism installed?

Laptop

**Comment by lastzero** [comment]
The error message says it clearly:

```
SQL dump not found: ./photoprism_db_backup.sql
```

Note that you cannot specify a local filename, as it must be accessible from the Docker container like all other files, including originals.

**Comment by lastzero** [comment]
See:
- https://github.com/photoprism/photoprism/issues/3140#issuecomment-1492988026

**Comment by dessalines** [comment]
This should probably be reopened. The preferred way to restore a backup, would be to only start the database, then cat the backup to the docker DB, then complete your startup. See [hedgedoc for an example](https://docs.hedgedoc.org/setup/docker/#backup) . 

Also it would be good to externalize the database to a `volumes` folder, to make installations as portable as copying a folder. This is standard for postgres docker, but I'm not sure about mysql / mariadb.

The instructions as is do not work, and I'm going to have to figure out how to mount my backup file internally.

Edit: I managed to get it working by mounting my DB backup inside the docker container.

# Steps:

Add this line to your volumes section: 

`- ./photoprism-db.sql:/photoprism-db.sql`

Run:

`sudo docker compose exec photoprism photoprism restore -i -f /photoprism-db.sql`

**Comment by lastzero** [comment]
Maybe our docs need to improved so it's clear what to do, but the commands as they are work with high probability as we've tested them and nobody else has reported problems.

**Comment by lastzero** [comment]
I am currently at a wedding and therefore cannot provide a full tutorial. It is generally possible to pipe both input and output, so no extra mount or volume is needed to create or restore database dumps. However, this is a bit advanced and may not work with the Windows terminal (only with a Unix shell like Bash), so we currently don't show this with specific examples in our docs. The built-in command help mentions it though.
