### ISSUE TITLE
Quality filter doesn't filter labels

### ISSUE THREAD

**Issue by opichals** [photoprism/photoprism#332]
When the photos contain low quality images they still get into the labels list. When one wants to view the label photos it says 'No photos' after clicking on the label associated image (if there are no more images associated with the specific label).

That is quite confusing as one sees an image (low quality) as in the labels overview but that photo is nowhere to be found in the photos collection or elsewhere.

**Comment by lastzero** [comment]
Yes, it's a known issue. Should probably hide the labels. Problem is that the feature is dynamically implemented on the client side while the counters are implemented on the server side.

**Comment by lastzero** [comment]
We decided to add a new browse view that shows all photos and videos, independent of quality (private and archived content excluded).

**Comment by lastzero** [comment]
It's fixed, you can test it on our demo when we release a new Docker build, hopefully tomorrow or later this week. Currently working on moments with some breaking changes.
