### ISSUE TITLE
Docs: The "before" and "after" search filters don't support specifying a time

### ISSUE THREAD

**Issue by Radiokot** [photoprism/photoprism#3321]
#### 1. What is not working as documented?

In the [Search Filters guide](https://docs.photoprism.app/user-guide/search/filters/#filter-reference), "before" and "after" filters are described as accepting timestamps and filtering the photos by the taking date. However, it seems like the filters only take the day part of the timestamp and ignore the time. No matter what time you enter, the filters work as if the time is 00:00:00. I've tried the following timestamp formats:
- `2023-04-01 23:58:00`
- `2023-04-01T23:58:00Z`

#### 2. How can we reproduce it?

1. Go to https://demo.photoprism.app/
2. Apply the search filter: `after:"2023-03-17 00:00:00"`
3. Notice which photos are returned. There should be a photo taken on March 17th 2023
4. Apply the search filter: `after:"2023-03-17 23:59:59"`
5. Notice which photos are returned. The results are the same, and the photo taken on March 17th 2023 is still included regardless of the time set in the filter.

#### 3. What behavior do you expect?

The "before" and "after" search filters respect the time. When the `after:"2023-03-17 23:59:59"` filter is applied, the results must not contain photos taken on March 17th 2023.

#### 4. What could be the cause of your problem?

- The filter parser can't parse the time part of the timestamp
- The filters are not built to respect the time, but it is not stated in the documentation

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://user-images.githubusercontent.com/5675681/229340639-179e0935-1345-4fa1-b5d8-2826332e8720.png)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: Demo 230401-1f13b95f3, also tried on my environment ARMv7 221118-e58fee0fb

(b) Database Type & Version: on my environment it's MariaDB (https://hub.docker.com/layers/linuxserver/mariadb/latest/images/sha256-cccfe7a893661b9d3c4e4b6f3c35292b26eddeb206f74094a5bb948f376a22d1)

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Edge

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? uBlock, Windows Firewall

#### 7. On what kind of device is PhotoPrism installed?

Doesn't matter. Can be reproduced on the demo.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Doesn't matter. Can be reproduced on the demo.

**Comment by lastzero** [comment]
This is a documentation glitch that slipped in because the overview is generated automatically. The data type we use supports hours, but the underlying database filter currently does not.

The overview in our [knowledge base](https://www.photoprism.app/kb) has been updated accordingly:

- https://www.photoprism.app/kb/search-filters
