### ISSUE TITLE
Keyboard never pops up on iPhone (in PWA) - Browser navigation is OK.

### ISSUE THREAD

**Issue by galli-miranda** [photoprism/photoprism#3325]
---------------------------------------------------------------------------

#### 1. What is not working as documented?

I have used the PWA for iPhone for a while now, and all of a sudden the Keyboard stopped popping up on the PWA version of the page. Login screen, search box, Album Create.. basically no Text input is possible via keyboard. 

#### 2. How can we reproduce it?

1 - Access a Photoprism instance
2 - Add it to home screen 
3 - Click the new Shortcut
4 - Select any text input box : No keyboard pops up. 

#### 3. What behavior do you expect?

I would expect the keyboard to pop up every time there's a text input expected. 

#### 4. What could be the cause of your problem?
I have no idea what could be causing this. It is important to note that I re-installed Photoprism (via docker) after a Server Clean-up. 
So, I have the newest version setup. (No experimental, just :Lastest - Build [221118-e58fee0fb] ) 

#### 6. Which software versions do you use?

I am running it on Docker, within a Linux Server. 
Database is MariaDB. 
Browser is Safari on iPhone, however: It works fine directly in the browser, the issue only happens as PWA.  

I don't believe my HW setup is releavant, as I have no other issues overall. 

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Local network access & reverse proxy via Traefik & Cloudflare. 
Both types of access encounter the same issue. 

Thanks!

**Comment by lastzero** [comment]
I've just tested it with the latest iOS and it works for me. Please note that we need full version information, including all plugins (e.g. alternative keyboards) and the browser you are using. Also, please try reinstalling the app to see if that fixes the problem.

**Comment by galli-miranda** [comment]
Just checked my iOS and it needed an update! After that, all back to normal! Sorry about that!
