### ISSUE TITLE
Favorite counter erroneously increasing for archived files

### ISSUE THREAD

**Issue by uLUViL3gCs** [photoprism/photoprism#334]
Description:
 Whenever a user is “liking” a file that is located in Archive, the Favorite Counter is increased.
Liking a file located in archive, does not seem to be an use case as such anyways, so that the file itself is not going to be marked as “liked” anyway.
Same, however, should be true for the counter, the counter should not increase either.
Note: the counter is updated to “correct value” again as soon as any file in the system is either added or removed from archive.
Problem is rather of cosmetic character.

Steps to reproduce:
OK:
- Archive a file
- select Archive in navgation pane

NOK:
- click “like” button on any file in Archive => the favorite counter in navigation bar is increasing by each click

Tested with:
 PhotoPrism™ 200522-c88cd69-Linux-x86_64 
Chrome 81.0.4044.138 / macOS 10.15.4

**Comment by lastzero** [comment]
Great observation. I was already wondering how to handle changes in archive in general. Technically, it's possible and the biggest challenge is not to update counters etc like in this case. Adds some complexity.

**Comment by lastzero** [comment]
It's fixed, you can test it on our demo when we release a new Docker build, hopefully tomorrow or later this week. Currently working on moments with some breaking changes.

**Comment by uLUViL3gCs** [comment]
Great work!
That's how I expected private marked files should behave, thanks!

- User is still able to change like/dislike flag of an archived file and it is correctly getting visible only when file is un-archived. No counter mismatch.
- Counters correctly update when files are archived.

Checked with:
PhotoPrism™ 200604-5b1c0f2-Linux-x86_64
(Chrome 81.0.4044.138 / macOS 10.15.4)
