### ISSUE TITLE
Albums: Show "download as zip" button on mobile screens

### ISSUE THREAD

**Issue by klaus1k** [photoprism/photoprism#3340]
Hey,
as discussed on Matrix I'm missing the download all button on mobile in the shared album view. I get a lot of requests how the entire album can be downloaded. On a desktop browser, the icon is shown and working as expected. (As a side note: When I resize the window on desktop, the download button dissapears as soon as the browser window gets smaller than approx. 768px wide)

Example on desktop:
![grafik](https://user-images.githubusercontent.com/64263206/232324141-c9eb2763-ed63-443c-b5be-6fba5dde4991.png)

This is how it looks like on mobile:
![grafik](https://user-images.githubusercontent.com/64263206/232324586-63484d92-9bde-4078-a865-3eedf569b032.png)

**Describe the solution you'd like**

Show the download all button on mobile view.

**Describe alternatives you've considered**

Downloading an entire shared album on mobile would right now require one of the following actions, both way more difficult than on desktop:

- (1) Select the first picture, (2) Scroll down to the last picture, (3) Long press on the last picture, (4) click on the context menu, (5) click on download
or
- (1) click on the photoprism icon, (2) click on the folder icon, (3) select the folder with a long press, (4) click on the context menu, (5) click on download

Thanks for consideration, would make the mobile usage way easier for me :)

**Comment by lastzero** [comment]
An updated preview build will be available for testing soon:

- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by klaus1k** [comment]
Awesome, thanks Michael for the quick change!
Just tested it in preview and it works like expected now, download button is shown on mobile:
 
![preview](https://user-images.githubusercontent.com/64263206/233802349-2140d57a-19e6-4865-90c0-699ebf33a719.png)
