### ISSUE TITLE
[Feature][i18n][public demo] web gui: change languagename to something that more users can understand

### ISSUE THREAD

**Issue by k3b** [photoprism/photoprism#3341]
Feature quequest:

Can you add some icon/symbol that allows me to change the web-gui-language?

Alternative: If this is not possible: can you reset the demo to english after 1 hour?

In my android apps the language is displayed in a combination of native/english/symbol

Example

* 🇯🇵 日本人 (Japanese)
* हिंदी (Hindi)
* 🇩🇪 Deutsch (German)

---

Background:

I want to try the demo at https://demo.photoprism.app/library/browse

Currently (2023-04-17 08:30 utc) the demo gui language is set to a language i donot understand (I assume japanese or chinese symbols)

Because i do not know the translation of "change language" in japanese or chinese (or any other other non latin-chars-language) i have no chance to see the gui in a language i understand (In my case English or German)

----

![grafik](https://user-images.githubusercontent.com/1374583/232431757-60995ec9-8f37-4c47-843e-ab8cfa4455bc.png)
Where is the setting to change the gui language?

**Comment by lastzero** [comment]
It's because the Demo is shared by all users and we are currently preparing the next release, so I didn't have time yet to readd the cron job that resets the demo every hour.

**Comment by k3b** [comment]
Now the demo is in english and i can explore the app. :-)

**Comment by k3b** [comment]
![grafik](https://user-images.githubusercontent.com/1374583/232438777-3ded7608-067b-4119-aa0e-792fa4864c7b.png)

Change the language name to something that more users can understand:

* Rename "日本人" and "Japanese" to "🇯🇵 日本人 (Japanese)"
* Rename "हिंदी" and "Hindi" to "हिंदी (Hindi)"
* Rename "German" and "Deutsch" to "🇩🇪 Deutsch (German)"

**Comment by lastzero** [comment]
We previously had the opposite request to use the native names, which is why it is implemented this way. Note that English is always English and always at the top. So the language is easy to reset. The label of dropdown cannot be displayed in all languages at the same time due to a limitation in space.
