### ISSUE TITLE
Group exposure bracket photo

### ISSUE THREAD

**Issue by ravetam** [photoprism/photoprism#335]
I have a bunch of photos taken with exposure bracket mode. Rather than showing all of them as individual photos, it would be better to group all of them and only show the mid bracket photo instead. Exif has `ExposureMode` property to indicate if a photo is taken with auto bracket mode. However, the datetime taken could be seconds apart between those bracketed photos.

One way to allow Photoprism to group them automatically is to named them as such
```
20180506_091537_DSC02122.JPG
20180506_091537_DSC02122 (+3.3).JPG * overexpose
20180506_091537_DSC02122 (-2.7).JPG * underexpose
```

I would rather not put spaces in the filename itself but unfortunately is required because of the following coded naming schemes.
```
	// other common sequential naming schemes
	if end := strings.Index(basename, " ("); end != -1 {
		// copies created by Chrome & Windows, example: IMG_1234 (2)
		basename = basename[:end]
	} else if end := strings.Index(basename, " copy"); end != -1 {
		// copies created by OS X, example: IMG_1234 copy 2
		basename = basename[:end]
	}
```

**Comment by ravetam** [comment]
In Lightroom, you can automatically stack/group photo based on datetime

https://helpx.adobe.com/lightroom-classic/help/grouping-photos-stacks.html

**Comment by lastzero** [comment]
What specific solution do you suggest? It's technically possible to stack photos, also to unstack them. We just don't have an easy-to-use UI for this. In the database, it's photos and files. You can assign an unlimited number of files to each photo. If a photo has no more (visible) files, it will be purged.

**Comment by ravetam** [comment]
**For long term**, I'm thinking of a "Stack' or "Group" feature which will intelligently stack and group photos probably using tensorflow. Here's a link to an [article](https://douglasduhaime.com/posts/identifying-similar-images-with-tensorflow.html)

Stack feature could be used for
- Burst shot (very common in mobile phone and digital camera)
- Exposure bracketing
- Focus stacking

One thing in common is that these group of photos has very close "DateTime" and very similar image content. Stacking could also be done on the client side by just grouping photos with similar timestamp (which is configurable on client side)

Stack feature is different than Photo->Files, because each photo in the stack should have a thumbnail generated. Using the thumbnail, Photoprism could generate a gif for quick overview or implement a UI to slide through the photos in the stack like in the image below

![image](https://user-images.githubusercontent.com/3193896/82907029-acbaf380-9f98-11ea-8cab-593160d577f6.png)

**For short term**, I'm thinking of having a standard naming convention so these files can be identified and grouped as a single photo. It needs to be renamed outside of photoprism. Currently, I'm using my own .NET Core program to sort all photos by timestamp, filter out those with exposure bracket tag, and sort it by exposure. It will then rename the files based on the mid bracket photo and append the exposure value. Does it help to share my project code?

```
20180506_091537_DSC02122.JPG
20180506_091537_DSC02122(+3.3).JPG * overexpose
20180506_091537_DSC02122(-2.7).JPG * underexpose
```

**Comment by jan0410** [comment]
It would be an awesome feature if a ML algorithm could stack pictures that are within a short time period and are very similar - even if these are not burst shots. Then it could show the (automatically) best rated as the stack represantative picture. For example if you take multiple pictures manually for a group photo. But this is probably a (very) long term dream.

**Comment by jan0410** [comment]
PS: You could use something like [Deep Cluster PIC](https://neurohive.io/en/state-of-the-art/deep-clustering-approach/) combined and limit the search to photos close in time and potentially a very close GPS location.

**Comment by lastzero** [comment]
You typically use perceptual image hashing and not ML for this, unless you need a really sophisticated solution. If you check the files table, the diff you find there is such a hash. We use it for grouping photos by similarity: https://demo.photoprism.org/photos?view=cards&order=similar&public=true&quality=3

However, it's all about user expectations and probabilities. When images are a few seconds apart, the hash is often slightly different, so will be the probabilities of ML models. In action / sports photography, a second means a lot. For others, it's nothing.

**Comment by lastzero** [comment]
@ravetam Seems like stacking photos based on metadata will do for you? No machine learning needed since you already wrote your own little program?

We generate thumbnails for all files, not just one per photo / stack. Of course those could be converted to a MP4 movie if it helps, but that's a really advanced feature I don't see in the near future.

**Comment by ravetam** [comment]
Definitely. Grouping by metadata or filename will do for now.

**Comment by lastzero** [comment]
Removed the whitespace, does it already work like that or do you need more for now?

**Comment by lastzero** [comment]
Also added support for XMP Document and Instance ID for grouping photos, probably not helpful for your specific use case though.

**Comment by ravetam** [comment]
Thanks! I'll test it asap. Grouping by instance ID seems like another alternative. I'll have a look as well

**Comment by ravetam** [comment]
Grouping by file name without whitespace works now. Should I close the issue?

**Comment by lastzero** [comment]
Yes, otherwise this will become an epic... You're welcome to open new issues when you find bugs or have additional needs.

**Comment by ravetam** [comment]
great, will close it now. thanks a lot!
