### ISSUE TITLE
Photos with Unknown dates show up in Search by added date

### ISSUE THREAD

**Issue by arnonm-intel** [photoprism/photoprism#3356]
#### 1. What is not working as documented?
Photos with unknown dates (either missing or corrupt EXIF information show up on the search by photo added date.
Aka, if date was added to collection in May 2023, it will appear in the May 2023 filters

#### 2. How can we reproduce it?
Add a photo without a valid exif date
Go to Search, select Year (current year), 
Photo will appear

#### 3. What behavior do you expect?
I would expect there to be a "Unknown" option for years and months, and allow to select all photos that are unknown.
I would NOT expect the unknown date photos to appear in the added year
If the user wants the photo to appear in the added year, he should manually change the Date informatoin fields to the date he wants
Give us a clear and concise description of what you expect.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, Build [221118-e58fee0fb]

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux Ubuntu 22.03

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,... All

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? - NO

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel Core i7-3770

(b) Physical Memory & Swap Space in GB - 8 GB memory

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

(d) Anything else that might be helpful to know?

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN? Yes - Traefik
![arnon](https://user-images.githubusercontent.com/31270956/235493410-74f58631-d017-4d1c-a29c-1bc4d2b6904f.jpg)

**Comment by lastzero** [comment]
The ADDED date does not depend on the metadata, but on WHEN the file was indexed.

**Comment by lastzero** [comment]
The CREATED date is estimated, e.g. based on the filesystem timestamp. Sorting all these images FIRST or LAST would be just as wrong as hiding them completely.

**Comment by lastzero** [comment]
We can, however, add a search filter for pictures without (time) metadata. Please create a feature request for this. Thank you very much! ❤️

Edit: I just tested it and found that we already have a filter for Unknown year. It is unclear what else needs to be done?

**Comment by graciousgrey** [comment]
Just tested with the provided image. Works as expected. The day, month and year drop downs on the edit dialog show "Unknown". When I use the year filter "Unknown" under Search I also get the photo as search result.

**Comment by dror3go** [comment]
@lastzero, @graciousgrey Not sure if this is the same report - but when I manually set a picture's date to unknown - the auto-generated title should not be with the year when the file was indexed.
What do you think?

**Comment by lastzero** [comment]
@dror3go this might happen because the title generator function checks the taken date source to make a decision and in that particular case (when you manually changed it), it is "manual" which has the highest priority and visibility. If so, it should additionally be checked if the year was intentionally set to unknown so that it is ignored anyway.

**Comment by dror3go** [comment]
@lastzero But this is not true in the latest release. I imported a scanned photo, the photo's date is set to today, and after I manually change the date in the UI to unknown day+month+year - the title remains 2024.

**Comment by lastzero** [comment]
That's why I said **it should additionally** 😉
