### ISSUE TITLE
Mark as Private doesn't reload the view

### ISSUE THREAD

**Issue by DunklerPhoenix** [photoprism/photoprism#3359]
#### 1. What is not working as documented?

Heho
Maybe I oversaw a already posted issue for this, but the "mark as private" doesn't reload the view. e.g. I'm in the review tab and mark some images for archive they disappear instant, but if I mark them as private they stay until I press reload.

#### 2. How can we reproduce it?

1. Go to e.g. /library/review
2. Select some pictures
3. click on the action button
4. choose "mark as private"
5. pictures stay there (with a small lock icon) until reload of the page

#### 3. What behavior do you expect?

The view should reload and the private pictures should disappear. (A confirmation window for "mark as private" like "archive" would be great to prevent accidentallyclicking on that button)

#### 4. Can you provide us with example files for testing, error logs, or screenshots?

Should happen with all instances of photoprism

#### 5. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux Docker

(d) Browser Types & Versions: Chrome

Build [230502-c405f6eff](https://docs.photoprism.app/release-notes/)

#### 6. On what kind of device is PhotoPrism installed?

Powerful Intel Server

#### 7. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Traefik

**Comment by lastzero** [comment]
This is so you can undo the operation until you reload in case it happened by mistake or you selected the wrong pictures. If this isn't documented good enough, feel free to send a pull request with improvements for our docs. Thank you!

**Comment by DunklerPhoenix** [comment]
I think it should be the same like archive with this litte confirmation window. Its kinda strange to reload every time you marked something as private especialy while reviewing thousands of images ^^ But I can live with that
