### ISSUE TITLE
Index: Support broken Samsung Galaxy files

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3361]
**As a user with broken Samsung Galaxy Files I want PhotoPrism to repair the images so that they can be indexed successfully**

Related discussion: https://github.com/photoprism/photoprism/issues/1407

Acceptance Criteria:
- Repair broken files so that they can be indexed

**Comment by maxime1992** [comment]
@graciousgrey I opened a [similar issue](https://github.com/photoprism/photoprism/issues/3363) this morning with more info and provided a picture to repro.

If you consider yours as a duplicate maybe :+1: / subscribe on mine and close this one
