### ISSUE TITLE
Do we really need firefox and chrome in docker image?

### ISSUE THREAD

**Issue by sam2kb** [photoprism/photoprism#339]
Why do we need firefox, chrome and some other desktop packages in the docker image?

~Also since we only care about `darktable-cli` we don't really need to install the whole thing and a ton of GUI dependencies. Why can't we create a multistage build and then copy `darktable-cli` from it?~

**Update:** Turns out `darktable-cli` won't run without `libgtk` and other GUI stuff

**Comment by sam2kb** [comment]
And we shouldn't hardcode the tags to Docker files, this prevents locally built images from being picked up. Omit or use `latest` instead.

https://github.com/photoprism/photoprism/blob/develop/Dockerfile
https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile (edited)

**Comment by lastzero** [comment]
This is our development image, we need browsers for acceptance tests. Don't use this for production please :)

**Comment by sam2kb** [comment]
> And we shouldn't hardcode the tags to Docker files, this prevents locally built images from being picked up. Omit or use `latest` instead.
> 
> https://github.com/photoprism/photoprism/blob/develop/Dockerfile
> https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile (edited)

This is still true and should be fixed, having the image tags in the code prevents the testers from running locally built images that don't have the same tag.

**Comment by lastzero** [comment]
This is for our dev environment. It is intentional, so that all developers use the same image without pulling the latest tag every days just to check if there is something new. You don't simply change the tag name here and use another base image for testing locally, just don't commit / push it if you don't everyone else to use it.

**Comment by sam2kb** [comment]
I understand the idea behind it, but this is basically for other devs to test the images build and pushed to docker hub by somebody with release permissions.

However if I myself want to build an image from my own local source with `make docker-development` and test it before pushing the changes, I would need to remove the tags in the files above before I can run that image.

**Comment by sam2kb** [comment]
Unless of course I build my local images with the tags that match those in the files which isn't intuitive and is an unneccessary extra step

**Comment by lastzero** [comment]
I don't quite understand... When I'm testing, I simply tag the image with whatever I like and it works locally. Just can't push it to docker hub without permissions. Apart from that, I simply run the tests inside the dev image without having to create extra images or tags.

**Comment by lastzero** [comment]
There's no reason to use `make docker-development` for regular developers. It's just for maintainers.

If you don't want to push to docker hub, please use the build script to test locally:

```
scripts/docker-build.sh [image name] [tag name]
```

The right image for production is `photoprism`, not `development`. It's a two stage build.

**Comment by sam2kb** [comment]
exactly, if the tag name I provide for the build script does not match the one in the file then I won't be able to run that image

**Comment by lastzero** [comment]
But why do you need to use a custom Dockerfile? It might not be compatible with our requirements. For building / testing alone, you don't need to create custom Dockerfiles.

**Comment by lastzero** [comment]
Maybe you can give a specific example. What command does not work? Where in our Dockerfiles is a tag name defined that will prevent your image from running?

**Comment by sam2kb** [comment]
I'm not trying to use custom Dockerfile, and that's exactly why instead of my local image it's pulling down one from the docker hub. I'm sure you don't have this problem because you're the one who release the images and always have the image with the right tag on it.

Here's an example.
- Let's say I want to build a new dev image like this `scripts/docker-build.sh development my-tag` or `scripts/docker-build.sh development latest`
- And then I wan to run my local repo in that new image with the stock `docker-compose up -d` in the project root. That command builds a new image using the `Dockerfile` that has `FROM photoprism/development:20200530`. So the container that is started will pull down the image from docker hub instead of building new or reusing an existing LOCAL dev image.


I can't

**Comment by sam2kb** [comment]
Now I suppose if I build my own dev image like this `scripts/docker-build.sh development 20200530` it will use my local image instead of pulling one down from docker hub. But this isn't intuitive at all, and I'd have to open the Dockerfile and copy the tag from it

**Comment by sam2kb** [comment]
The only way to run locally built images with provided `docker-compose.yml` is to do the following. Nobody would ever guess that :(

```
scripts/docker-build.sh development 20200530
scripts/docker-build.sh photoprism develop
docker-compose up -d
```

**Comment by lastzero** [comment]
What's wrong with the development image we provide on Docker Hub? It is there, so that all developers use the same - that's the idea, not that everyone builds a custom image. You don't need to build the image before running `docker-compose up`.

**Comment by lastzero** [comment]
You can of course use a custom `Dockerfile` and and custom `docker-compose.yml`. However, you don't know if tests will fail for other developers. So we try to avoid it. The development base image is not for running code in production, its only purpose is to provide a **standardized** environment for development and testing.

**Comment by sam2kb** [comment]
I was playing with the images. Actually I moved the base images to Debian slim as best practices dictate, and cleaned up some code in the docker files.

`node:12-buster-slim` for development image
`debian:buster-slim` for production image

I'll make a PR tonight

**Comment by lastzero** [comment]
That's somewhat true, but for specific reasons and use cases like micro-services that shall be deployed quickly to many servers. PhotoPrism is a monolithic application with lots of dependencies and other assets. Therefore, even with Ubuntu, the size of any base image is relatively small compared to the payload (app binary, dependencies and assets). For typical microservices, this is not the case.
