### ISSUE TITLE
Search: "Unknown country" filter has no effect

### ISSUE THREAD

**Issue by dror3go** [photoprism/photoprism#3412]
Using the latest release 230514-0b780defb - manually setting coordinates of pictures without GPS data in their exif and filtering by unknown country still shows these pictures, even though when opening them - they have a country set in the UI.

Note that this wasn't the behavior in older releases - I'm using the "unknown country" filter a lot in order to tag (mostly) older pictures without GPS data.

**Comment by lastzero** [comment]
If this has changed, it could be that a user requested it previously. Could you check our commit/change log as well as the closed GitHub issues for this?

**Comment by dror3go** [comment]
Oh wait, it seems that all pictures are being returned when filtering by unknown country, meaning also pictures with GPS information.

I wasn't able to find a relevant note about this in the changelog.

**Comment by graciousgrey** [comment]
I will take a look at that tomorrow, thank your for reporting.

**Comment by lastzero** [comment]
Unknown country should find pictures with country code "zz" and/or place ID "zz" if I remember correctly.

Edit: Could it be a problem with retrieving the data from our geocoding API so that the coordinates cannot be resolved?

**Comment by dror3go** [comment]
I'm not familiar with the implementation - but I'd imagine that the geocoding API is being used when indexing a new picture or when tagging lat/lon, and not upon search. Right? The database and the UI shows the correct country, but the filter seems broken.

Also reproduced the issue in the demo website using the `20230517_111654_F26B14AA` file that was there.

**Comment by dror3go** [comment]
Fixed, thanks! 👏
