### ISSUE TITLE
Map not rendering in Places

### ISSUE THREAD

**Issue by MelAnubis** [photoprism/photoprism#3423]
The map in the Places view isn't working It shows markers where the photo locations are, but never loads the background. Ive reset the browser and tried both Edge and Chrome
Running Build [230506-9de9a3540] under Docker

**Comment by lastzero** [comment]
If you are not a member, it could be that this is because the level of detail isn't very good when using the built-in offline map. Unfortunately, you didn't share any specific coordinates, so it's impossible to reproduce your problem. For more detailed free maps, see the following issue:
- #2998
