### ISSUE TITLE
Documentation of configuration parameters

### ISSUE THREAD

**Issue by twatzl** [photoprism/photoprism#343]
Hi, 

I could not find a good documentation of the config parameters in the `docker-compose.yml` file and what they do.

https://github.com/photoprism/photoprism/blob/develop/docker-compose.yml

I looked in the wiki, but it only tells to call `photoprism config` which is not possible unless you have photoprism installed.

It would be cool if a description of the configuration parameters, possible values and effects could be added either to the wiki or to https://docs.photoprism.org/en/latest/getting-started/docker-compose/

Kind Regards

**Comment by lastzero** [comment]
You mean for developers?

We provide this example configuration for users, which is (hopefully) well documented: https://dl.photoprism.org/docker/docker-compose.yml

**Comment by twatzl** [comment]
Ok. Seems reasonable. I think I found the wrong docker-compose.yml at first (the developer version).
Although I think it wouldn't hurt to explain some features in a little more detail.

For example I made a separate issue about read only mode.

**Comment by lastzero** [comment]
User guide is in progress @graciousgrey 👍
