### ISSUE TITLE
Folders: Find all matching albums, even if a query contains spaces

### ISSUE THREAD

**Issue by aaronrudkin** [photoprism/photoprism#3441]
#### 1. What is not working as documented?

As per the issue title, some searches in the folder facet do not return correct results in an under-inclusive way. I am not precisely sure what the issue is, but generally very vague / single word searches return results, and exactly correct searches return results, but medium detail searches do not.

I have a folder entitled "2011 Joy of Cooking Calendar Photos" which is located at the path "Albums to Sort/2011 Joy of Cooking Calendar Photos" relative to the root.

Here are a series of search queries and whether or not the folder comes up:
"2011 joy of cooking calendar photos" :+1:
"2011 joy of cooking calendar" :+1:
"joy of cooking calendar" :x:
"joy of cooking" :x:
"cooking calendar" :x:
"joy" :+1:
"calendar" :+1:
"cooking" :+1:
"of" :+1:
"2011" :+1:

I have a second folder entitled "2008 June Emily Concert" which is located at the path "Albums to Sort/2008 June Emily Concert"

2008 june emily :+1:
2008 june :+1:
2008 emily :x:
2008 concert :x:
june emily :x:
emily concert :x:
june concert :x:
concert :+1:
emily :+1:
june :+1:
2008 :+1:

On your demo site, you have a folder called "German film awards 2012" and "film awards" will not find this as a result.

#### 2. How can we reproduce it?

It is unclear to me if this bug emerges as a result of a more sophisticated edge case in terms of the search indexing, but I imagine given that it's folder searching, that this is easy to reproduce by simply creating a folder with that name and doing the search, and as I said it's reproducible on the demo site.

#### 3. What behavior do you expect?

In general, if I am searching for a folder, and I enter search keywords that are contained in the folder name, the folder should be a result for the search query.

#### 4. What could be the cause of your problem?

My guess is it's an issue with either how folder names are indexed or how the search scores results and discards insufficiently high quality results.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Attached screenshots, though as I said you can reproduce a version of this on your demo site.

![proof no result](https://github.com/photoprism/photoprism/assets/14701267/48b7f6d0-d162-4dc9-bb0f-c4713a26169d)
![proof exists](https://github.com/photoprism/photoprism/assets/14701267/e3ec4c2d-67f2-4529-bad3-f14c092b65d7)

#### 6. Which software versions do you use?

ARM64 on Synology, MariaDB, not browser specific. Build 230514-0b780defb for my local install though it can be reproduced on your demo site.

This is a low urgency bug (since it can be worked around by simply making the search more precise or vague). I vacillated as to whether this was a bug (because these results are obviously unexpected and incorrect) or a feature request (because perhaps it is known that the folder facet doesn't have robust searching options and I'm asking for something to be built out) -- but I appreciate your time regardless and hope this report is useful.

**Comment by lastzero** [comment]
I've changed the search query, so this issue is hopefully resolved. An updated development preview will be available for testing soon! Looking forward to your feedback :)

You can also test this in our public demo, which is based on the latest preview build by default:

<https://demo.photoprism.app/library/folders?q=film%20AWARD&order=name>

**Comment by aaronrudkin** [comment]
Can confirm this works both in my own instance updated to 230601 and on the demo site, so looks like this is solved. LGTM. Feel free to close :)
