### ISSUE TITLE
Unknown column error while Uploading and Rescanning after restoring Database

### ISSUE THREAD

**Issue by Violet7026** [photoprism/photoprism#3453]
#### What is not working as documented?

After following the backup guide and restoring files + folders to the expected locations, and restoring the database using the restore command, I now get the error
`photoprism-photoprism-1  | time="2023-06-05T09:19:31Z" level=error msg="file frpshjj1c7w6qwiq: Error 1054: Unknown column 'file_orientation_src' in 'field list' while saving"`

I had tested the restore previously in February and found that it was working as expected.

####  How can we reproduce it?

1. Take a backup from an older copy of Photoprism
2. Restore backup on latest version
3. Attempt to upload or complete rescan any files

####  What behavior do you expect?
Database to be working as expected.

####  Can you provide us with example files for testing, error logs, or screenshots?

The following migrations were applied to my restored database.
`root@230603:/photoprism$ photoprism restore -i -f

INFO[2023-06-05T09:17:26Z] restoring index from /photoprism/storage/backup/mysql/2023-06-03.sql 
INFO[2023-06-05T09:17:55Z] migrating index database schema              
INFO[2023-06-05T09:17:55Z] migrate: running database migrations         
INFO[2023-06-05T09:17:55Z] migrate: 20230102-000001 successful [269.871966ms] 
INFO[2023-06-05T09:17:55Z] migrate: 20230211-000001 successful [80.36743ms] 
INFO[2023-06-05T09:17:55Z] migrate: 20230309-000001 successful [35.765584ms] 
INFO[2023-06-05T09:17:55Z] migrate: 20230313-000001 successful [15.221206ms] 
INFO[2023-06-05T09:17:55Z] restored in 29.058704432s

The following error was recieved.
`photoprism-photoprism-1  | time="2023-06-05T09:19:31Z" level=error msg="file frpshjj1c7w6qwiq: Error 1054: Unknown column 'file_orientation_src' in 'field list' while saving"`

#### Which software versions do you use?
Photoprism Build [230603-378d4746a], with MariaDB 10.11.3-MariaDB-1:10.11.3+maria~ubu2204

This is running on Docker 24.0.2 on Ubuntu Server 22.04

**Comment by lastzero** [comment]
This is probably because you have restored the old tables, but in the same database so the versions and/or migrations tables were not properly restored (or removed). To force running all migrations, run the `photoprism migrate -f` command in a terminal or manually remove the tables mentioned and then restart your instance.

**Comment by Violet7026** [comment]
I can confirm that `photoprism migrate -f` has fixed the issue, would it be worth adding this to the [Restoring Backups](https://docs.photoprism.app/user-guide/backups/restore/) page of the docs?

**Comment by lastzero** [comment]
Feel free to send a pull request for our docs, although it's kind of a rare edge case I guess. Might be worth adding the issue to the Troubleshooting Checklists we provide in Getting Started, either additionally or instead. Then add a link from the backup guide to the checklists?
