### ISSUE TITLE
Thumbnail size envs are ignored

### ISSUE THREAD

**Issue by sam2kb** [photoprism/photoprism#347]
I have these in the `docker-compose.yml` however when I browse the images I get the sizes like `3264x2448` with filenames ending in `/static/fit_2048`. Original images are 36MP.

```
PHOTOPRISM_THUMB_SIZE: 1080
PHOTOPRISM_THUMB_LIMIT: 1080
```

**Comment by sam2kb** [comment]
The thumbnails are 20Mb each by the way. Even though I have `PHOTOPRISM_JPEG_QUALITY: 90`, I don't think they should be this big.

**Comment by lastzero** [comment]
I would assume that these are originals, since we rendering thumbs is not possible with your settings.

**Comment by sam2kb** [comment]
I just saw some 4000x6000 iamges with the request URI ending on `/static/fit_2048, yes those must be originals

**Comment by sam2kb** [comment]
What do you mean not possible with my settings? Should I not set them smaller than 2048?

**Comment by lastzero** [comment]
For retina screens, we can render 2560x1600 and 3840x2400. 3264x2448 should be an original therefore.

Limit means limit, we can not render anything larger, see https://github.com/photoprism/photoprism/wiki/Thumbnails

**Comment by sam2kb** [comment]
Oh it actually means **do not create thumbs if original is bigger than** `PHOTOPRISM_THUMB_LIMIT`, that is interesting

**Comment by sam2kb** [comment]
So if I never want to skip creating the thumbs should I set `PHOTOPRISM_THUMB_LIMIT: 999999`? :)

**Comment by lastzero** [comment]
We don't render thumbs that, just updated https://github.com/photoprism/photoprism/wiki/Thumbnails based on `photoprism help`.

When you disable on-demand rendering by providing a low limit, you will simply get the original file when you request the thumbnail so that the browser can display something (fallback). 3840x2400 is our upper limit, so setting the limit to 999999 won't do much. Might lead to a validation error at best.

**Comment by sam2kb** [comment]
It it done to prevent crashes on low memory machines? It would be good to have a higher limit because I don't want my viewers to download 50Mb full size originals every time they click on an image.

**Comment by lastzero** [comment]
Sounds like all you need is `PHOTOPRISM_THUMB_SIZE`, use limit when you don't want us to render large thumbnails at all. It was a feature request by one of our users. Don't ask me why. I wouldn't do it.

**Comment by sam2kb** [comment]
I don't see a problem of defaulting to 3840x2400 as long as there's a way to set a higher number if someone wants it

**Comment by sam2kb** [comment]
Again, imagine browsing a gallery on a mobile phone where each image is 50Mb

**Comment by sam2kb** [comment]
And it's OK if the indexing will take a week, so long as we provide a better experience to the viewers

**Comment by sam2kb** [comment]
And it's a 5 seconds change, just remove this bit
```
if c.params.ThumbSize > 3840 {
    return 3840
}
```

**Comment by lastzero** [comment]
Oh that is dangerous! Enables denial of service attacks.

**Comment by sam2kb** [comment]
Well, we ought to at least increase the upper limit to allow for high MP cameras while keeping the default where it was

**Comment by lastzero** [comment]
It's the output, not input size. Out photo viewer will not request larger images.

**Comment by sam2kb** [comment]
I'm lost now. All I want is to  create thumbnails no bigger than 1080px for all images, even those that came from a 36MP camera. The viewers should not see images bigger than 1080px unless they specifically click "download"

**Comment by lastzero** [comment]
For that, you would have to modify our list of default thumbnails. 1080 is a really bad resolution, are you sure? Everyone with a HD display would only get thumbs with like 700x1080 pixels and there would be no way around.

**Comment by sam2kb** [comment]
That was just an example. What's important is creating thumbnails from all images large or small

**Comment by lastzero** [comment]
Then you can set PHOTOPRISM_THUMB_SIZE to 3840 which will work for all modern devices. As mentioned, the frontend will never request or try to request larger thumbs as this is the largest thumb in our list.

**Comment by sam2kb** [comment]
But then the problem I described still persists since the app will return original images when you click on the individual photo. And that would mean downloading huge files on every click

**Comment by lastzero** [comment]
No, it will not. Only when you disable on-demand rendering (set a PHOTOPRISM_THUMB_LIMIT lower than 3840) it will return the original. There are no values higher than 3840, this is the maximum.

**Comment by sam2kb** [comment]
Ok I removed the `PHOTOPRISM_THUMB_LIMIT` option and it's working just as you described above, which is exactly what I needed. Is it me or the docs are very confusing?

**Comment by lastzero** [comment]
As mentioned, it was a feature request. Help with improving our docs is most welcome :)
