### ISSUE TITLE
Archive photos aren't deleted in the fs with photoprism purge

### ISSUE THREAD

**Issue by grigio** [photoprism/photoprism#349]
I've some photos in `archive` but when I run `photoprism purge` those photos aren't deleted in the filesystem.

version
photoprism/photoprism          latest

```
sudo docker-compose exec photoprism photoprism purge --hard
INFO[2020-06-05T08:32:26Z] removing missing files in originals          
INFO[2020-06-05T08:32:26Z] purge: finding hidden photos                 
INFO[2020-06-05T08:32:26Z] removed 0 files and 0 photos in 323.186118ms 
INFO[2020-06-05T08:32:26Z] closed database connection
```

Is there a proper way to delete/remove photos and reflect it in the filesystem?

**Comment by lastzero** [comment]
See Implement trashcan #167

**Comment by lastzero** [comment]
Most users don't want us to modify or delete their originals, so purge is just to remove entries from the index. In a second step, after the first release, we might implement an optional feature to delete files from the filesystem.

**Comment by grigio** [comment]
Ok, thanks

**Comment by jvallery** [comment]
I'm using the archive capability to curate my library. Ideally, there would be a way to have Photoprism move all of my photos marked "Archive" to an archive folder and then optionally purge them from the index.  I don't want them all deleted but would like to remove them from my "originals" folder.

**Comment by ohjohnsen** [comment]
I agree with @jvallery.  I also want to use PhotoPrism to curate my photo library.  Letting PhotoPrism delete unwanted photos, or at least move archived photos to a separate directory in the file system would be a great.

**Comment by graciousgrey** [comment]
Delete archived photos is already on the roadmap :) https://github.com/photoprism/photoprism/issues/167
