### ISSUE TITLE
Ability to share a single file ?

### ISSUE THREAD

**Issue by francoisWeber** [photoprism/photoprism#3491]
Hi Photoprism Team !

I'm using more and more your tool every day: thanks ! :) 

It's super easy to share an album through a public link. However, sharing a single file seems impossible. I expected to get a "share" icon on the lower-right vertical menu that appears when I select one or more photos in the main gallery. The only solution seems to create an album containing only one file and then share this album.
Would it be possible to share a single picture without creating an entire album ? Technically one could maybe imagine to create a "hidden" album automatically  and share this latter ?

Thank for your efforts in Photoprism !

**Comment by graciousgrey** [comment]
Thank you very much for your kind feedback !

Creating share links for single files is planned :)

- https://github.com/photoprism/photoprism/issues/466

**Comment by francoisWeber** [comment]
My bad ! Thank you for this future features !
