### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by Foxboron** [photoprism/photoprism#35]
Currently photoprism attempts to create the directory, this fails if the folder is a symlink and thus refuses to start.

**Comment by Foxboron** [comment]
My NAS has several folders where one is `Pictures`, that is suppose to be the `Import` folder. However as i need to define `/Photos`, and `/Photos/Import` is used as a sub-directory, `/Photo` will essentially point to the root of my NAS. This isn't ideal to hand docker access into, thus I'd like to much rather symlink it to somewhere else.

**Comment by lastzero** [comment]
Anyones knows if this is still an issue and if yes, how we can fix this?

**Comment by lastzero** [comment]
According to this issue, `os.MkdirAll` should work with symlinks: https://github.com/golang/go/issues/1149
