### ISSUE TITLE
[Index] Invalid image classification timer

### ISSUE THREAD

**Issue by sam2kb** [photoprism/photoprism#351]
I see this with the latest production image. All counters are off by 20s

`index: image classification took 21.123456789s`

**Comment by sam2kb** [comment]
Unless maybe they are running in background, parallel to the thumbnail job and it really takes 20 seconds... Then it's all good.

**Comment by lastzero** [comment]
We're using multiple processes, depending on how many CPU cores you have.

**Comment by sam2kb** [comment]
Yeah it makes sense now. Thanks
