### ISSUE TITLE
Logged user can download unshared photo

### ISSUE THREAD

**Issue by CodazziS** [photoprism/photoprism#3511]
#### 1. What is not working as documented?

An user can download (or see) unshared photo

#### 2. How can we reproduce it? / Steps to reproduce the behavior:

- Create a new user (user role)
- On new browser / private navigation, login to photoprism with the newly created user
- The the user, go in album, and select one or more photos/movies
- On admin account, change newly user role to "Guest"
- Refresh the user tab (F5) -> All photo on current album is viewable 
- Go on Home page, "No photo found" displayed, but selected photos are alway selected
- Download selected photos with download button

#### 3. What behavior do you expect?

The download button should fail and display an error message

#### 4. What could be the cause of your problem?

Access is not checked if we already have photo ids ?

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://github.com/photoprism/photoprism/assets/8134250/bd0cd74e-c746-42f2-a4ec-21f8f0dc2d5f)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture: Build 230625-17242fb07 - Docker image

(b) Database Type & Version: MariaDB 11.0

(c) Operating System Types & Versions: Linux / Docker

(d) Browser Types & Versions: Brave

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Only brave

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel Xeon E5-1245v2

(b) Physical Memory & Swap Space in GB 32GB 

(c) Storage Type: SSD for container, HDD for storage

(d) Anything else that might be helpful to know?

**Comment by lastzero** [comment]
> An user can download (or see) unshared photo

Yes and no. You've had access, so you know the random file and photo UIDs we use to prevent unauthorized access. You can't guess them.

We also use many other common security measures, such as random download and thumbnail tokens that get invalidated when you update your password, log out, or the account is deleted.

Forcing an authorization recheck for every single file or thumbnail requested by testing how you might have obtained the secret identifier, e.g. though a shared album, would have huge performance implications and might honestly be too much for a consumer application. We can do that for a government agency if they pay us well.

**Comment by lastzero** [comment]
It would be an option to bind the selection to the session, but then you might accidentally lose it if you have multiple accounts and confuse them.

**Comment by lastzero** [comment]
Our Developer Guide discusses the implementation details and tradeoffs:

> Digital copies are as good as originals: Once **shared and downloaded**, such images should be considered "leaked" because they are cached and can be re-shared by the recipient at any time, with no sure way to get all copies back, even if the download URL becomes invalid or the service is shut down completely.
>
> Any form of protection we could provide would essentially be "snake oil", could be circumvented, and would have a negative impact on the user experience, such as disabling the browser cache or context menu.
> 
> For the highest level of protection, it is recommended to shield your private server from the public Internet. Always use HTTPS, a VPN and/or ideally TLS client certificates and make sure that only people you trust have access to your instance.

👉 https://docs.photoprism.app/developer-guide/media/thumbnails/#server-api

**Comment by lastzero** [comment]
If you want to share a changing list of files with untrusted users, it is best to create a static export (zip archive) and send them that.

**Comment by lastzero** [comment]
It's like Snowden. Those documents are gone. Classified or not.

**Comment by lastzero** [comment]
@CodazziS I've created an issue to reset the clipboard contents and other data stored in the browser's local storage when you log out. Note that this also resets the sort order, view types, and expanded navigation. So not all users might like it and thus it requires some UX testing.

**Comment by CodazziS** [comment]
Thank for your response @lastzero 
Ok, I'm agree, with your response, but when I refresh the site (without log out) I expect the clipboard to be empty. 

I re-tested this morning, and if I go in album and select 2 photos. When I change album, my 2 photo is still selected. Is it wanted ?

**Comment by lastzero** [comment]
Yes, the clipboard content is supposed to remain intact when you navigate to a different page or album.
