### ISSUE TITLE
Security: Clear clipboard on logout and when privileges change

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3512]
**As a user who shares his/her browser with other users or uses multiple accounts with different permissions, I want all local storage to be cleared when I log out or switch accounts so that random entity UIDs are not leaked.**

When you clear the entire local storage, the search sort order, view type, and expanded navigation state are also reset. So this might not please all users. Changes therefore require UX testing. Alternatively, it would be possible to delete only the clipboard contents and leave the rest intact.

This is related to the following report:
- #3511

**Comment by lastzero** [comment]
@CodazziS An updated development preview build will be available for testing soon.

**Comment by CodazziS** [comment]
Tested today, working fine.

Thank you for quick fix
