### ISSUE TITLE
Albums: Add extended search form with sorting options

### ISSUE THREAD

**Issue by Ramblurr** [photoprism/photoprism#353]
We've several dozen albums on our photoprism instance.  The current album list page renders albums in chronological order. Most of the time when we go to look at an album it is a recent one, which requires tons of scrolling to get it into view.

I'd like to propose a feature that allows one to sort the albums, at least by date, if not also attributes.

--------------------------------------------------------------------------------------------------------
---> Here's a separate ticket for the list view: https://github.com/photoprism/photoprism/issues/382

----------------------------------------------------------------------------------------------------------
**Acceptance Criteria:**
* Add sort filter to album overview
* Possible options: Name, Recently added, Recently edited, Newest First, Oldest First

Note: 
* Recently Added/Recently Edited probably only makes sense for albums and not for moments, states, etc as those are auto-generated and constantly updated in the background.
* Newest First/Oldest First could lead to issues. Should the earliest or the latest date be used? Especially for moments or states or folders it might not make much sense as those often cover several years

**Comment by lastzero** [comment]
Albums are sorted by name or year / month currently (latest at the top). In addition, you can filter by category. If you mark an album as favorite (click the star icon), it will be shown first as well.

**Comment by jimmcslim** [comment]
Yeah, feels like Albums, Moments, Calendar, Folders, Library/Originals could potentially support sorting by: name, "date" (although, how is this defined... earliest or latest photo in the 'collection' from EXIF data, file dates?). And being able to choose between ascending or descending sort would be great.

**Comment by Ramblurr** [comment]
> Albums are sorted by name or year / month currently (latest at the top). I

Ah, this is why I thought the default sorting was chronological, because our albums are named "YYYY-MM-DD Event"

**Comment by jeannotalpin** [comment]
> Albums are sorted by name or year / month currently (latest at the top). In addition, you can filter by category. If you mark an album as favorite (click the star icon), it will be shown first as well.

How do you choose between the 2 sort methods ? I have the felling that only by name is possible.
Thanks.

**Comment by graciousgrey** [comment]
It's not possible to change the sort order of the album overview as this issue is not implemented yet. Albums are currently sorted by name. In the calendar section the month-albums are sorted by newest first.

**Comment by jeannotalpin** [comment]
Thanks for the precision.
I will upvote the album sort by newest first :)

**Comment by el-fredo** [comment]
> Ah, this is why I thought the default sorting was chronological, because our albums are named "YYYY-MM-DD Event"

It's the same with me.

I recently switched from Google Photos to PhotoPrism and finally managed to restore all my Google Photos albums. Now I found out that my oldest albums are at the top, and my newest albums are at the bottom. I have to scroll for a very very long time to get to my latest album that I am working on because it is at the bottom.

Is there perhaps a workaround until the sort function is implemented?

**Comment by lastzero** [comment]
The last commit added an extended search form similar to the picture search, where you can change the sort order and filter by year and category:

![sort-albums](https://user-images.githubusercontent.com/301686/210242660-ec8799e7-4b4e-4124-84ae-8f6e1b7c4ed8.png)

An updated preview build will be available for testing soon!

**Comment by dror3go** [comment]
That's amazing @lastzero, thanks! May I ask what's defined as an album's "year"? If I'll create an album from last weekend of photos both from 2022-12-31 and from 2023-01-01, what will be the album's year?

**Comment by lastzero** [comment]
What the year filter finds depends on the album type:

- For manually managed albums, it finds albums that contain at least one picture from that year.
- The year of the most recent picture in a folder is automatically detected and cached in the background.
- Some moments combine month and year with a location as a dynamic search filter.
- For calendar months, it is obvious.
- States can currently not be filtered by year as it is undefined.

**Comment by lastzero** [comment]
We have updated the available sorting options and the default setting based on user feedback:

![album-sorting](https://user-images.githubusercontent.com/301686/210569923-8a0083c5-a06d-47d5-8723-72db5ff2e9c5.jpg)
