### ISSUE TITLE
Add `File Modification Date/Time` to fallback values for `takenAt`

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#355]
In the same vein as ba524d05d606ea35a98a1efcb439213e2a2add49, It would be convenient to also add exiftool's `File Modification Date/Time` as a fallback value for `takenAt`. All photos sent through [Viber](https://www.viber.com/en/), don't have any of the standard exif fields, such as `Create Date`.

This shouldn't break anything, if we put it on the bottom of the if/else statement (same as the aforementioned commit). I currently have many photos with the `unknown` takenAt field. I can send a sample for testing but it really comes down to the exif metadata, there's nothing wrong with the photo otherwise, and no errors are thrown. An example is shown below (exiftool output):

```
ExifTool Version Number         : 11.16
File Name                       : IMG-97c2b07381b62ea08d3e2e4127c9fc26-V.jpg
Directory                       : Tablet/Viber
File Size                       : 236 kB
File Modification Date/Time     : 2020:06:08 17:59:28+03:00
File Access Date/Time           : 2020:06:10 17:05:19+03:00
File Inode Change Date/Time     : 2020:06:08 17:59:46+03:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Image Width                     : 1200
Image Height                    : 1600
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 1200x1600
Megapixels                      : 1.9
```

**Comment by linosgian** [comment]
You're right a simple `stat` is sufficient to get the `mtime`. I've tracked down what's the actual issue. As shown below, when `takenAt` is the file's last modified time/date, then `takenAtSrc` is set to `SrcAuto`.
https://github.com/photoprism/photoprism/blob/f2738c1f65a34247989218a3d07ddc1503fb9731/internal/photoprism/mediafile.go#L115

Later on, while indexing a file, if `takenAtSrc` is `SrcAuto`, then the newly indexed mediafile, is going to have `Unknown` year and month.

https://github.com/photoprism/photoprism/blob/f2738c1f65a34247989218a3d07ddc1503fb9731/internal/entity/photo.go#L747-L754

This might be intended, since the date is not extracted from a "credible" source but I don't see the point of setting `takenAt` to the file's mtime, and then not setting its Year and Month to the corresponding values.

**Comment by lastzero** [comment]
It's because we use it for creating moments and in general for search. When you set up a new instance all files without metadata would show up in 2020, which is mostly wrong for the intended use case.

**Comment by linosgian** [comment]
I noticed that there's the `unknown` filter (for both year and month) on the frontend. I can see the incentive. OTOH, I'd think that since `mtime` is used as a fallback, it would make sense to put the photos to the correct year/month based on it. Even if the photos with unknown year/month appear on the bottom, we would end up with a bunch of random photos group together and one would have to explicitly browse for them when the photo they expected to find are not "there". Would you consider utilizing `mtime`'s Year and Month? This probably means dropping the `unknown` date, since files will always have an `mtime`. It could also be a toggle, opting in to fallback to `mtime` as a definitive date for all photos with `unknown` date, if you don't want to make this a default for everyone

**Comment by lastzero** [comment]
That's how it was and users didn't like it, so we changed it. What is your specific use case? Typical photos should include Exif or XMP metadata. We could add yet another confusing config option :)

**Comment by linosgian** [comment]
Right. Yes, I noticed, because I have two photoprism instances, one of which I've migrated to the latest version. The other one, indexes photos _correctly_ (by some definition of correct :smile:). As I said above, unfortunately Viber doesn't use standard Exif metadata. I dug into it a little more and it seems that: Messenger and Slack do the same. It makes sense to strip GPS metadata for privacy reasons, but the Original Date should have been there, or at least set to the current date - at the time of sending it-.

I understand that it's _yet another option_ that might confuse the user, as to what it actually does (been there with a couple of them myself), but it would **really** help me avoid, timestamping photos upon syncing them from my phone.

**Comment by lastzero** [comment]
Messengers remove metadata to protect users privacy, not because they prefer a different standard 🤗 However, we can read date and time from file names and many messengers put (received) date and time in the file name. Year and month should be indexed correctly in this case.

**Comment by lastzero** [comment]
File modification time can be especially misleading when you scan old (analog) photographs. It's easier to find those files with the unknown option rather than remembering the file mod date to use it as a filter.

**Comment by linosgian** [comment]
Right! Nextcloud (that's what I use to sync photos with) has the option of creating subfolders based on year/month. This can definitely be done. So, we can work with the full filename, e.g. /home/photoprism/Pictures/Originals/Mobile/2020/09/IMG-..jpg. This is case-specific but it can work with already existing photograph "collections". I guess people tend to organize them in similar ways (yearly/monthly).

**Comment by lastzero** [comment]
Does this work for you? Please close the issue in this case :)

**Comment by linosgian** [comment]
I was left that your 2nd edit was merely a suggestion for something that can be implemented. I just noticed (and tested) that it's already implemented. It definitely works fine. Cheers!
