### ISSUE TITLE
Places: Support sub-km distances when searching for locations

### ISSUE THREAD

**Issue by loulou91** [photoprism/photoprism#3558]
Present geographical search is a nice feature and works well but precision is today 1 km which may be sometimes too rough.
I tried to enter dist:0.1 but I got an error ("unable to do that").
I think dist unit is integer...
Could it be possible to increase precision using float in place of integer or to change unit km to meter?

Thanks in advance.

**Comment by lastzero** [comment]
It's an approximation due to how the query works (for maximum compatibility with all databases). Accepting a floating point number instead of an integer should still be possible to implement with reasonable effort.

**Comment by lastzero** [comment]
@loulou91 I've started a new preview build so you can test these changes, it should be available within the next hour:

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

Note that our public demo at https://demo.photoprism.app/ will be updated as well if you don't want to use our preview build to test with your own pictures.

**Comment by lastzero** [comment]
A screenshot of the Places view, with a distance of less than one kilometer specified in the search box (the same works for the regular search, although it's harder to test without a map):

![places](https://github.com/photoprism/photoprism/assets/301686/8a082dc8-74f6-4726-9e26-935290daa0c2)

*Note: Instead of searching for the S2 cell ID, you can also use the `lat` and `lng` filters.*

**Comment by loulou91** [comment]
Thanks a lot for the implementation !
Looks fine for me with "lat: lng: dist:" dist unit being km (and sub-km). Map size is adapted according to dist ;-) It looks working with general search field as well.
I tested your example with cell ID (s2) I was not aware of, and with city instead of lat lng but in that case dist is not operand. Maybe it's normal?

**Comment by graciousgrey** [comment]
Thank you very much for testing :)

> I tested your example with cell ID (s2) I was not aware of, and with city instead of lat lng but in that case dist is not operand. Maybe it's normal?

The city search filter cannot be used in combination with dist because we do not have the city boundary coordinates.
