### ISSUE TITLE
Live Photos: Sidecar video file dimensions are indexed incorrectly

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3559]
#### 1. What is not working as documented?

On the files tab of the edit dialog a wrong video size is displayed.

#### 2. How can we reproduce it?

1. Index a live photo, e.g. IMG_123.heic ("ImageSize": "4032x3024") + IMG_123.mov ("ImageSize": "1920x1440"). 
2. Go to the files tab of the edit dialog

For the .heic file, the correct size is displayed. For the .mov file, the size of the .heic file is displayed.

#### 3. What behavior do you expect?

Display the correct size for all files.

**Comment by lastzero** [comment]
With these changes, the correct file properties should be displayed after reindexing all affected files.
