### ISSUE TITLE
Video transcoding is not working on TrueNAS installations

### ISSUE THREAD

**Issue by immanuelsmith** [photoprism/photoprism#3573]
#### 1. What is not working as documented?

Video playback of iPhone HEVC video is not working. 

#### 2. How can we reproduce it?

Add an originals directory containing an iPhone video and index it. Try to open it from the videos folder or by manually browsing to its location. It will fail to play and instead show a 1-second video of CRT static

#### 3. What behavior do you expect?

The video should play. It plays regular MP4's

#### 4. What could be the cause of your problem?

I think it has something to do with transcoding. I have tried to turn off the FFPMEG transcoder and it has no effect.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I don't have any I can share as they are all personal videos, but any regular iPhone HEVC video will cause the issue (has to be .mov format, NOT slo-mo or any other type of video requiring a settings change).

Log with FFMPEG disabled: 
2023-07-25 07:13:31 ERRO video: transcoding '******/05404_IMG_1747.MOV' failed

Log with FFMPEG enabled: 
 2023-07-25 06:43:09 ERRO video: transcoding '****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV' failed
2023-07-25 06:43:09 WARN libx264: failed transcoding ****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV [145.628904ms]
2023-07-25 06:43:09 INFO libx264: transcoding ****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV to avc

#### 6. Which software versions do you use?

Photoprism Build [221118-e58fee0]
Current community build for truenas as of 7/25

From Truenas -
Version:
g20221118
Plugin:
photoprism
Release:
12.4-RELEASE-p3

Stock MariaDB database, no changes made to anything.
#### 7. On what kind of device is PhotoPrism installed?

NAS with a AMD Ryzen 5 3600 6-Core Processor, 16GB of ECC memory, 3x6TB drives in a ZFS pool (Raid 5). It has an Nvidia card for display output but I don't think it is supported by truenas core for any sort of video acceleration

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
I don't think so.

**Comment by graciousgrey** [comment]
If videos are to be played by a browser that does not natively support the video format, they must be transcoded. This means that ffmpeg must be enabled.

See also:
 - https://docs.photoprism.app/user-guide/organize/video/#transcoding

In your case the video transcoding does not seem to work.

We've heard similar reports of problems with videos from other TrueNAS users. Unsure what could be causing this. As playing videos is not an issue with other installation methods it's most likely a config issue or a third party integration that doesn't include all required dependencies. 

Is the third party app you are using provided by the community or by the TrueNAS team? Is there any documentation available?

**Comment by graciousgrey** [comment]
In order for us to help resolve issues with the TrueNAS installations, it would be great if you could send us links to the installation instructions / app store listings / documentation that you used to install PhotoPrism. Also, it would be helpful to know how to contact the maintainers of these third party apps. Thank you very much!
