### ISSUE TITLE
UI: Allow pasting a date on the Photo details screen

### ISSUE THREAD

**Issue by sam2kb** [photoprism/photoprism#358]
I like the date picker, but it's an inconvenience when you can't paste a date. I need to change the date on ~20 photos and doing this with a date picker is a nightmare.

I guess I'll just edit an SQL file directly :)

**Comment by lastzero** [comment]
We're working on batch edit and an improved date picker, but it's not a top priority given everyone is waiting for link sharing and a stable release in general.

**Comment by lastzero** [comment]
Using an SQL update statement is a great workaround / alternative while we work on a custom UI for this use case :)

**Comment by sam2kb** [comment]
Batch edit would be a great addition. My index.db is almost a gig, doing the edits however is pretty straightforward so I'll be doing that for now.

**Comment by sam2kb** [comment]
Here's another idea, if creation date is in the future why not use the date from the file.

**Comment by lastzero** [comment]
1 GB is pretty big for a SQLite database, maybe you should try MariaDB/MySQL instead? 

Do you have many files with a creation date in the future? Maybe we should catch that and fix it, not sure if others do it... more than I would expect from a first release.

**Comment by sam2kb** [comment]
I like the flexibility of sqlite. Is there a migration mechanism for maridb or is it gonna need to reindex and rescan everything again?

I have maybe around 100 files with a bad date.

**Comment by lastzero** [comment]
I guess there is a way to create a SQL dump for a migration, try to google it. When it comes to creating backup and having secure long-term storage, I would always go for MariaDB/MySQL. That's why we had TiDB, it was only removed because of stability issues. With TiDB it was easy to migrate and create dumps in general.

**Comment by sam2kb** [comment]
Yeah I can sure create a db dump, I was just wondering if there was an internal mechanism for it.

**Comment by lastzero** [comment]
No, SQLite support in general is pretty new so this is the first time such an idea / feature request comes up.

**Comment by sam2kb** [comment]
The actual date is somewhere in `January 2011`

**Comment by sam2kb** [comment]
I ended up reindexing, way too much work converting an sqlite dump, especially the dates.
At least existing thumbnails and sidecar files are picked up, so not too bad.

**Comment by lastzero** [comment]
That's good to hear, works as designed :) you can also set / change the dates in sidecar JSON files, e.g. with a simple search and replace.

**Comment by graciousgrey** [comment]
We do not plan to have an input field for date. We will implement batch edit soon, so setting a date for a batch of photos will be much easier.

**Comment by kbshadow1987** [comment]
Hey
