### ISSUE TITLE
Frontend: Photo viewer requests wrong image size from backend

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#362]
I uploaded several raw files to my local photoprism installation. When I try to view the full size on my larger monitor (but with less dpi, resolution 2560x1440), only a very small file (720_fit) is shown. When I view the same image on a smaller display with high dpi *resolution 3840x2160), the full image (3840_fit) is chosen.
Ideally, I would expect the largest size to open on both screens. At least, I would like an option to show a larger size.

Version: Latest from Docker.

**Comment by lastzero** [comment]
What are your thumb related settings in docker-compose.yml?

**Comment by fdw** [comment]
I had not changed anything, so they should have been `PHOTOPRISM_THUMB_SIZE=2048` and `PHOTOPRISM_THUMB_LIMIT=3840`. I have since created a new Docker container with `PHOTOPRISM_THUMB_SIZE=3840`, but the behavior persists.

**Comment by lastzero** [comment]
That's really strange. I'm using a DELL U2515H (2560 x 1440) for development and have no issues whatsoever. Might also be an issue with metadata (our indexer gets width and height from Exif and XMP), but you mentioned that it's working on a different screen... so not sure. Maybe someone from our community has time to debug this?

**Comment by lastzero** [comment]
PS: Please let us know what browsers and operating systems you are using. Could be a frontend (JavaScript) issue.

**Comment by fdw** [comment]
I'm using the latest Firefox on Linux.

If you can give me a hint where in this code this happens, I might have a look.

**Comment by fdw** [comment]
After playing with it, I have two interesting observations: On the screen with the small size (coincidentally, also a Dell, possibly the same series), there is no "zoom" button shown. On the other screen, there is.

If I make the browser smaller on the "wrong" screen, either height or width, after some threshold, a larger picture will be shown.

Could it be that this code is the culprit (`viewer.js`): 
```
for (let i = 0; i < thumbs.length; i++) {
    if (thumbs[i].Width >= viewportWidth || thumbs[i].Height >= viewportHeight) {
        return thumbs[i].Name;
    }
}

return "fit_720";
```

I suspect that my screen is too large (always larger than the possible sizes), so it defaults to `fit_720`.

**Comment by lastzero** [comment]
You have two different screens connected to the same computer? Can you also test with Chrome to see if it behaves differently?

The code is supposed to return the thumb with the best resolution. Obviously viewportWidth might be reported wrong when there are multiple screens.

**Comment by fdw** [comment]
> You have two different screens connected to the same computer?

Yes, an external display and the built-in laptop display. Additionally, they have different scaling.

>  Can you also test with Chrome to see if it behaves differently?

I just installed Chromium and tested it. The behavior is about the same (external monitor: small image and no zoom button, built-in: large picture with zoom button), but Chromium chooses `fit_2048` whereas Firefox chooses `fit_3840`.

**Comment by lastzero** [comment]
I'll try to test with two screens on OS X today, maybe it is solved there. If not, it's a more general issue that applies to all browsers and operating systems. Might be worth checking stackoverflow 🤔

**Comment by lastzero** [comment]
Using https://developer.mozilla.org/en-US/docs/Web/API/Screen/availHeight and https://developer.mozilla.org/en-US/docs/Web/API/Screen/availWidth might help. If those are virtual pixels, thumbs will be too small for retina screens though. On the other hand, window.devicePixelRatio is probably fixed in most cases, so using a second display with a different ratio leads to bad resolution. Needs to be tested.

**Comment by fdw** [comment]
I looked at `window.screen.availHeight` vs `window.innerHeight * devicePixelRatio` (same for width), and the latter one results in much larger values on both screens. Is there anything else I can try for you?

Another idea, based on the code snippet above: If I understand this right, it takes the first `thumb` that is larger than the screen in one dimension. If it can't find one that is larger, it defaults to `fit_720`. Would it make sense to use the largest `thumb` as a fallback, seeing as it tries to be as large as possible?

**Comment by lastzero** [comment]
Changed it as suggested. Let me know of this works! New Docker images available soon.

**Comment by fdw** [comment]
Yes, it works beautifully :) Thank you!
