### ISSUE TITLE
Nginx configuration not using SSL

### ISSUE THREAD

**Issue by federicociro** [photoprism/photoprism#3622]
1. What is not working as documented?
The recommended nginx reverse proxy configuration provided in the PhotoPrism documentation doesn't include certain security hardening measures, which could expose users to potential security risks.

2. How can we reproduce it?

Visit the PhotoPrism [documentation on reverse proxies](https://docs.photoprism.app/getting-started/proxies/nginx/).
Review the recommended nginx configuration.
Note the absence of certain security hardening headers and configurations.

3. What behavior do you expect?
I would expect the provided nginx configuration to have certain security headers and configurations to help users set up a more secure instance of PhotoPrism behind a reverse proxy.

4. What could be the cause of your problem?
It's possible that the documentation was created before certain nginx best practices became common, or perhaps these considerations were deemed outside the scope of the initial documentation.

5. Can you provide us with example files for testing, error logs, or screenshots?
I've attached an improved nginx configuration as provided by an expert, which includes security hardening measures.

``` # Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        listen [::]:80;
        server_name example.com;
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name example.com;
        client_max_body_size 500M;

        # SSL settings
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        # Harden SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

        # Enable HSTS (HTTP Strict Transport Security)
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Xss-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_pass http://photoprism:2342;

            # Tweaks for better security and compatibility
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_buffers 32 4k; # Adjust buffer size
            client_max_body_size 500M;
        }
    }
```

6. Which software versions do you use?
(a) Not applicable.

(b) Not applicable.

(c) Not applicable.

(d) Checked documentation on Chrome Version 115.0.5790.171 on Windows.

(e) No ad blockers or plugins relevant to this issue.

7. On what kind of device is PhotoPrism installed?
Not applicable as this is a documentation-based observation.

8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
Yes, I am using NGINX as a reverse proxy. I reviewed the configuration based on the documentation provided at [PhotoPrism nginx documentation](https://docs.photoprism.app/getting-started/proxies/nginx/).

**Comment by lastzero** [comment]
Thanks! You can simply send a pull request with your improvements to our dedicated docs repository.
