### ISSUE TITLE
Feature request: Keyboard shortcuts

### ISSUE THREAD

**Issue by tomplast** [photoprism/photoprism#3624]
**Describe what problem this solves and why this would be valuable to many users**
I believe it would be helpful if photoprism would implement keyboard shortcuts for different kinds of tasks. For example:

D: Archive ("Delete") = Archive images.
A: Add to album = Add selected images to album.
G: Download (Get)  images
S: Share images

Also, some commands (in this case for example archive) could automatically confirm operation when SHIFT+D is used.

**Comment by graciousgrey** [comment]
Keyboard shortcuts are planned. I just updated the description of the following issue to include your suggestions.

- https://github.com/photoprism/photoprism/issues/1131

Feel free to leave a :+1: there.
