### ISSUE TITLE
UI: Add "river" view which displays thumbnails in original aspect ratio

### ISSUE THREAD

**Issue by mlindgren** [photoprism/photoprism#3625]
**Describe what problem this solves and why this would be valuable to many users**

The mosaic view does not allow the user to see the relative widths, heights, or aspect ratios of photos. When browsing an album, there's no way to distinguish a panoramic photo from a photo taken in portrait mode (except based on the subject of the photo, but that's not always reliable). This ruins the composition of a lot of photos, and overall is just not as visually appealing as it could be.

**Describe the solution you'd like**

A number of competing photo apps support viewing photos in a "river" layout, where the original aspect ratio of the photos are preserved. To make the rows of photos align consistently, the scale of each row is adjusted so that a constant row width is maintained despite the photos having different individual widths. Here is an example of what it looks like:

![image](https://github.com/photoprism/photoprism/assets/945164/337e9510-775f-42f1-8ed0-c668882040ae)

**Describe alternatives you've considered**

N/A: I tried searching for other open issues related to this, but couldn't find anything. Apologies if I missed an existing issue. #645 is somewhat related, but not the same.

**Comment by loulou91** [comment]
I fully support your request but @lastzero already answered this question some days ago #3582.
Just have to wait ;-)

**Comment by mlindgren** [comment]
Thanks. I will close this since it's a duplicate of #3582 (which in turn seems to be a dupe of #85).

**Comment by mlindgren** [comment]
(Can't figure out how to properly close this as a duplicate; apologies to the maintainers...)
