### ISSUE TITLE
Search: Support Negative Filters

### ISSUE THREAD

**Issue by kevincox** [photoprism/photoprism#3628]
**Describe what problem this solves and why this would be valuable to many users**

It would be nice to filter results out of filters. For example I want to find files that don't have a particular person I could do `-person:john-smith` This is especially useful when combined with other filters to select a specific set of files.

**Describe the solution you'd like**

I would suggest that putting `-` in front of any search term negates it. This would work with bare keywords like `-dog` or for any special term such as `-original:*edited*`.

**Describe alternatives you've considered**

Some filters naturally have negatives already, such as `face:yes`, `face:no`. But I still think that it would be good for consistency to support `-face:yes`. Other options such as `person:some-name` don't have a natural negative. It would need to be something like `without-person:` or `person:-"John Smith"`.

**Comment by graciousgrey** [comment]
That's planned :) Feel free to leave a :+1: in this issue:
- https://github.com/photoprism/photoprism/issues/2073
