### ISSUE TITLE
s.style not set when loading /places directly

### ISSUE THREAD

**Issue by Toothwitch** [photoprism/photoprism#363]
Photoprism 200616-ee86bed-Linux-x86_64 (latest Docker photoprism/photoprism)

When loading the /places route directly the JS tries to access https://api.maptiler.com/maps//style.json without the map style set. When loading via link(clicking an object) it works as intended.

**Comment by lastzero** [comment]
Interesting, works for me in develop (public mode). Might only happen when authentication is turned on, so it's an initialization problem when certain config data is only available after loading the maps.

**Comment by Toothwitch** [comment]
yes. the container uses the ootb default settings so that auth is turned on

**Comment by lastzero** [comment]
Fix is merged to master, new Docker images available for testing soon (~1 hour).

**Comment by Toothwitch** [comment]
Tested with the new image. Works as expected. Great work! Thanks
