### ISSUE TITLE
Thousands of folders are created and affects tags and performance

### ISSUE THREAD

**Issue by juanpeich** [photoprism/photoprism#3633]
Hello family, 

Thank you so much for your great work. 

I have photoprism on a raspberry pi 3B+ The problem is that it creates too many thumbnails for me (right now I only have about 20 original photos). 
I have tried to delete the "sidecar" folder, the "storage/cache/thumbnails" folder. I have disabled backups and have followed the configuration indicated in the documentation. But I always get too many thumbnails and I think that is slowing down photoprism a lot. 

The problem is that even in the labels, it recognizes the thousands of thumbnails as images and catalogs them for me. If I have about 30 original photos, how can it be that I have more than 3000 folders and I don't know how many more images have been created (All images are the same? 
Can you tell me some more optimal configuration and how to restore photoprism series to start clean without thousands of folders, labels, etc? 

I am attaching some screenshots so that you can see the folders that are generated with 20 photos and also all the images that I am supposed to have in the different labels (thousands of images being the same thumbnail):

![Screenshot_2023-08-16-00-06-16-030_com android chrome](https://github.com/photoprism/photoprism/assets/108826500/634ca301-5413-4f96-9d9a-82f9f560e69b)
![Screenshot_2023-08-16-00-06-46-906_com android chrome](https://github.com/photoprism/photoprism/assets/108826500/16fdea7f-2c08-41e6-a3e8-c36464960e79)
![Screenshot_2023-08-16-00-07-05-819_com android chrome](https://github.com/photoprism/photoprism/assets/108826500/dcec3e2f-65d3-4214-a955-43cd80c55023)

The other question is that if I have to change equipment, since I want to connect a 4TB hdd to it, would a raspberry pi 4 8Gb be enough or do I need to buy a miniPc?

Thank you very much for everything beforehand. JuamPe

**Comment by graciousgrey** [comment]
Is is possible that your storage folder is configured to be within you originals folder? This would explain why that many thumbnails are generated.

See also:
- https://docs.photoprism.app/getting-started/docker-compose/#photoprismstorage

**Comment by lastzero** [comment]
👉 https://docs.photoprism.app/known-issues/#nested-storage-folder
