### ISSUE TITLE
Orientation icon is the wrong direction

### ISSUE THREAD

**Issue by kevincox** [photoprism/photoprism#3640]
#### 1. What is not working as documented?

When changing the orientation of a photo the left and right rotation options appear to be swapped.

[Screencast from 2023-08-16 10-38-56.webm](https://github.com/photoprism/photoprism/assets/494012/c031f1a9-a32e-4a88-9279-f6ab6ac23ac6)

This may be some personal preference or lack of understanding but it seems very intuitive. In the video you can see that the image original has its top facing to the right. So I select the orientation icon that has the top to the right. However the resulting image is now upside down. Instead the "correct" option to select is the icon with the top to the left.

#### 2. How can we reproduce it?

1. Have an image that is rotated 90° in either direction.
2. Click edit
3. Go to the files tab.
4. Change the orientation option.

#### 3. What behavior do you expect?

Selecting the icon that matches the rotation of my image results in the image being upright afterwards.

I see two solutions here:

1. Update the icons and behaviour to "select the current orientation of the picture" and the rotation is adjusted accordingly. This should take the current orientation into account. This is what the current iconography implies to me, but it doesn't work that way.
2. Update the icons to clearly reflect rotation instead of selecting the right orientation.

Note that both of these systems would need to take into account the current orientation when selecting which "target" orientation to apply to the image. Right now this is the responsibility of the user which is relatively complicated mental math which could be offloaded to the software.

#### 4. What could be the cause of your problem?

It seems that the icons are intended as a "rotate" icon, but that isn't reflected in the image they contain.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

No. It happens for any image.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: PhotoPrism® CE Build 230615-90a18f6e7, x86-64

(b) Database Type & Version: SQLite

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Firefox

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? N/A

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: AMD Ryzen

(b) Physical Memory & Swap Space in GB: N/A

(c) Storage Type: SSD

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Nginx

**Comment by lastzero** [comment]
It could be that in their case the image data does not match the orientation metadata? When I tested the implementation on our public demo, everything looked fine and I wouldn't change a thing - let alone consider it a bug that the dropdown (icon) looks exactly the same as the thumbnail image:

![Screenshot 2023-08-16 at 17 00 19](https://github.com/photoprism/photoprism/assets/301686/e54a7626-43e6-4728-bbf2-b8cb9750ae60)
