### ISSUE TITLE
Save search filters as favourites

### ISSUE THREAD

**Issue by dinoschachten** [photoprism/photoprism#3642]
(as always I hope this is not a duplicate - couldn't find this on the roadmap)

Being able to define (ideally using the GUI) and save complex search filters (also across users once Photoprism becomes multi-user) would be an extremely versatile tool to cover scenarios such as:

- Identify images that don't have the required metadata yet (search for: no creator name OR no location OR no title OR no labels)
- Make it easier to browse images that are ready to be shared or published (for instance search for: label "edited" AND label "greenlit")
- Narrow your search in one click to exclude older photos or photos from lower-quality cameras (search for NOT camera "XYZ" AND date later than 2016-01-01)

Of course such filters can currently be saved as browser bookmarks, but that falls apart too quickly when using multiple devices or using an instance of Photoprism with multiple users. In short: Photoprism's beauty of storing and processing everything on the server should expand to include custom searches.

I believe this makes Photoprism extremely customisable - even more so if these favourites could be presented on a customisable dashboard - but that custom dashboard is a story for another time I believe ;)

**Comment by kvalev** [comment]
I guess you are thinking something along the lines of smart albums - #1431

**Comment by dinoschachten** [comment]
> I guess you are thinking something along the lines of smart albums - #1431

That is an excellent point!! Indeed smart albums would be the best solution for this!
