### ISSUE TITLE
Upload: Pre-select current album in dialog

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3644]
**Acceptance Criteria:**
- When a user clicks the upload icon from within an album this album should be pre selected in the upload dialog so that uploaded images are automatically added to that album
- Add tests

**Comment by lastzero** [comment]
The current album (if any) should now be pre-selected in the upload dialog. I've started a new development preview build for testing!

**Comment by graciousgrey** [comment]
Looks good to me now :)

**Comment by lastzero** [comment]
@graciousgrey This doesn't seem to work yet when using the mobile navigation in the upper right corner, so a follow up issue should be created for that!

![Screenshot_20230925_125245](https://github.com/photoprism/photoprism/assets/301686/5a85d29a-9754-4cfb-a0ac-d97ced89c3ef)
