### ISSUE TITLE
Search: Add filter term for exact face count.

### ISSUE THREAD

**Issue by kevincox** [photoprism/photoprism#3647]
**Describe what problem this solves and why this would be valuable to many users**

Sometimes I want to find pictures that contain exactly a set of people. It would be useful to have a filter to match the exact number of faces. For example `person:John exact-faces:1` to find photos with just John or `person:"Jane & John" exact-faces:2` to find faces with just those two people. It could also be used to find photos with two people and someone else whose name you can't remember.

**Describe the solution you'd like**

`faces:3` is taken up by a minimum count. So maybe it could be `exact-faces:` or `faces:=3`? Or maybe this could be resolved with negative filters (https://github.com/photoprism/photoprism/issues/2073) in which case it would be `faces:3 -faces:4` to find exactly 3. Not exactly elegant but in many cases the first term may be redundant, so for example you would search `person:"Jane & John" -faces:3`

**Comment by graciousgrey** [comment]
Looks very similar to this one

- https://github.com/photoprism/photoprism/issues/3196

**Comment by kevincox** [comment]
Thanks for finding that. This is indeed a duplicate.
