### ISSUE TITLE
Ability to delete photos

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#365]
Thanks again for this cool thing :)

Unfortunately, I cannot find a way to delete one (or more) photos from my library, neither in Firefox nor Chrome (on the latest Docker image).

Is it not implemented yet, or am I too stupid to find it?

**Comment by lastzero** [comment]
See Implement trashcan #167

We don't physically delete photos yet as...
- this requires some more thought when it comes to UX
- plus we want to build more trust with our users first.

**Comment by fdw** [comment]
Oh, thank you, I hadn't seen that. That clears it up then. Thanks!
