### ISSUE TITLE
Photos Missing from "Photos" section

### ISSUE THREAD

**Issue by Aidan-OS** [photoprism/photoprism#366]
Almost 2 months ago I began working with your software and raised [this issue](https://github.com/photoprism/photoprism/issues/296). Recently I have been able to start working on this project again, and am still having a similar error.

I have restarted from scratch, and have made sure that the NSFW filters are correct (PHOTOPRISM_DETECT_NSFW is false and PHOTOPRISM_UPLOAD_NSFW is true).

When I have uploaded the files through the browser (Chrome v83.0.4103.116), the "Photos" tab reports 83 photos, however when I go to browse and add tags to these photos, only 45 appear. Some of the photos that are missing are not in any way NSFW, and they are metadataless PNG files (as mentioned in the old issue, art of a friend's).

Since my last work with the software, a new section has been added that allows me to see all the raw files under the "Library" tab. The "Originals" section of the 'Library" tab reports 101 photos, and when I go to view them, I find that all 83 of the photos I have uploaded are there, but I am unable to categorize them, as they appear to not be indexed and are not shown in the "Photos" tab.

I have tried re-indexing my entire library, with no change. Are there other things for me to try?

**Comment by lastzero** [comment]
If you see the files in originals, they have been indexed. Maybe they are under review or grouped together?

In every case, it's important to test with a fresh database.

**Comment by Aidan-OS** [comment]
This is a completely new database, and even a new installation of Linux.

There is no “For Review” section, as I have the low quality filter off, and when turning it on the new pictures do not show up. I have searched everywhere for the images, and I cannot find them.

Tomorrow I will start a new instance with different photos in an attempt to re-create the problem so that I can share my server link with you

**Comment by lastzero** [comment]
You can also try to create an album directly from the files / folders you see in originals.

**Comment by Aidan-OS** [comment]
I have created an album, then added the photos to it. This is the result:
![image](https://user-images.githubusercontent.com/1919827/85953239-ef2b7380-b93c-11ea-9636-a6d74936ae91.png)
![image](https://user-images.githubusercontent.com/1919827/85953251-ffdbe980-b93c-11ea-957f-be1174089e20.png)

If I add one of the images that I can see in the main "Photos" tab to the album, it shows up without issue.

**Comment by lastzero** [comment]
I agree, this is strange but can't confirm it with my own testing. All I can do I guess, like it might be a permission problem in the file system, photos might still be private as you didn't delete YAML sidecar files, etc...

**Comment by lastzero** [comment]
Also it might be an encoding issue. Do you see anything in Library > Hidden?

**Comment by Aidan-OS** [comment]
Nope, nothing in Library > Hidden. I don't know how YAML sidecar files could still be there, as **this is a new linux instance.** There is absolutely nothing left over from my last attempt in May.

**Comment by Aidan-OS** [comment]
Okay. I have managed to recreate the error only using SFW images. I performed uploads from both my phone using Google Chrome and my Desktop, also using Google Chrome. I included one of the SFW known problematic images in my desktop upload and it has promptly not shown up properly.

While I am not comfortable sharing the IP of the server publically, I am okay with sending it privately so that you can test.

**Comment by lastzero** [comment]
You're welcome to contact us directly via hello@photoprism.org :)

**Comment by lastzero** [comment]
Not sure how you managed to index files without converting PNGs to JPEG and creating thumbs, but a rescan completely fixed it:

![Screenshot 2020-06-29 at 07 44 17](https://user-images.githubusercontent.com/301686/85977207-6e23b900-b9dc-11ea-83c5-69a650ac4da0.png)

**Comment by Aidan-OS** [comment]
First of all, I went to check the server this morning and noticed that somehow it got some of the photos that I was using for testing on the previous server. I have no idea how that happened, and am sorry for unexpectedly possibly exposing you to that. I clearly did not know how certain aspects of the photo storing function, as things were left behind.

As for using the complete re-scan, this did not work. It is understandable to think that it had worked because of what had happened, but that is not the case. When using the index function, it does not seem to convert pngs to jpeg thumbnails. All the images that became available upon indexing were the ones from my tests that worked, and there were still plenty of missing photos.

**Comment by Aidan-OS** [comment]
I have now **properly** cleaned everything and re-indexed, and you can see that the single item in 2020/06 is not being given a thumbnail and only resides in the originals tab. This image was uploaded through chrome, and I have re-indexed since it was uploaded.

**Comment by lastzero** [comment]
Thanks, I can now see that the file type is "png" while the mime type is "image/jpeg", so it's probably a JPEG but with a wrong type extension. We should trust the mime type in this case and change the file type to "jpg", ignoring the extension.

**Comment by Aidan-OS** [comment]
I have a feeling this is due to interactions with Google Drive and Apple Devices. While I do not have access to the exact data I am meant to be storing yet, I have gone through what my friend has done with their photos: Create on Apple mobile device, upload to Google Drive. Since I will eventually be downloading all the images off Google Drive and uploading them directly to Photoprism, I decided to test that first. Apple mobile devices appear to store as jpeg files, but they become png files when uploaded to google drive.

This would also explain why I didn't appear to have problems testing the method of uploading that will be used directly after the shift, which is direct upload from Apple mobile device. They are properly stored as jpeg files in that case.

**Comment by lastzero** [comment]
Changes will be part of our next Docker build, probably tomorrow.

**Comment by Aidan-OS** [comment]
Fantastic! Notify me when that has been updated and I will test it out.

**Comment by lastzero** [comment]
Latest image contains the fix plus a password change form.

**Comment by Aidan-OS** [comment]
Wonderful! I have set everything back up, indexed my files, and everything appears!
