### ISSUE TITLE
Trying to share album: "Error 1364: Field 'link_token' doesn't have a default value"

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#367]
I'm running the latest docker version as of 3 minutes ago.

When selecting an album and clicking on the share button, the following error is shown:

" Error 1364: Field 'link_token' doesn't have a default value "

The share modal shows anyways. However, Clicking on "Share link" does nothing and only brings up the same error again.

**Comment by lastzero** [comment]
It was renamed to share token, you need to start with a fresh database when testing.

**Comment by wiwie** [comment]
oh ok. that is then what I was missing. I kept using the original database.

**Comment by wiwie** [comment]
how often do I need to reset the database? Is it documented somewhere / communicated somehow or is it best (for now) to just reset each time I pull a newer docker image?

**Comment by lastzero** [comment]
See Switch from automatic to manual SQL migrations #319

**Comment by lastzero** [comment]
The current version of PhotoPrism is for TESTING, it's not a stable version. It's communicated clearly. We don't have time and resources to provide upgrade scripts for multiple development versions each day.

**Comment by lastzero** [comment]
Alternatively, you can just drop the links table, it will be re-created automatically. However, this is too technical for most users, so I just say "start with a fresh database", even though it's just one field (or often just an index) they may need to be changed.

**Comment by lastzero** [comment]
See also https://docs.photoprism.org/getting-started/updates/

> Our database schema still changes a lot as we do performance optimizations and add features. Therefore we cannot provide a smooth upgrade path and you should be prepared to delete your current database and re-index. To spare you a disappointment, we kindly advise you not to index large photo collections at the moment.

**Comment by wiwie** [comment]
Thanks for the Infos.

Regarding the database I wasn't sure whether you were using some kind of framework that automatically creates database schemes and migrations from model changes. In that case you probably would have exposed a migration command I would have missed in that case. Good to know that this is not the case.

I know enough now. Issue is a non-issue and can be closed. Thanks!

**Comment by lastzero** [comment]
Anyhow, thanks for the feedback... In fact, I renamed the column to link_token again since we changed the concept: One token can be valid for multiple albums (shares), so that you don't need to create multiple links for the same group of people if you want to share more than one album. Needs to be tested well, would be great if you can help us!

**Comment by wiwie** [comment]
You are welcome. I am currently trying the sharing feature just by myself. I haven't gotten to trying photoprism out with friends  or family ;-) So what I can test is - unfortunately - limited.

Sharing of albums works fine so far. Also sharing two albums with the same token works. No issues so far. Will report back in #18 if anything comes up.
