### ISSUE TITLE
PDF Graphics Support

### ISSUE THREAD

**Issue by kiwiconcord** [photoprism/photoprism#3672]
I would like to request that PDF support be added to photoprism. Here is my use-case scenario:

Most of the apps and scanner software only provide either pixel based (JPG/PNG) or pdf saving options,  I use pdf as it is vector-based because they need to be scaled, cropped and cleaned at various sizes.  As my image library increases in size, I find it increasingly difficult to view and navigate through my pdf's to find and preview (no support in previewing in most os natively) of these images.

**Comment by lastzero** [comment]
Might already work if you change the pdf extension to ai. Note however that PDFs generally have multiple pages, which will be displayed as layers on top of each other. So it's not usable to read/preview most documents, unless they only have a single page.

**Comment by kiwiconcord** [comment]
Thanks for your comment, I have now tested, but no luck - Got the follow error in the logs - 2023-08-27 01:26:41 WARN index: '1980 XXXXX.ai' is unsupported (application/vnd.adobe.illustrator)

**Comment by lastzero** [comment]
It's in the vector graphics extension we currently only provide to our plus members. Alternatively, you can test it on our public demo.

**Comment by kiwiconcord** [comment]
Awesome thanks, I am now a Plus member
