### ISSUE TITLE
Implement Visual Comparison for Duplicate Image Detection

### ISSUE THREAD

**Issue by vanBassum** [photoprism/photoprism#3679]
I decided to create a separate issue for this specific feature since it differs from the comparison feature mentioned in other contexts.

**Describe what problem this solves and why this would be valuable to many users**

Currently, the available feature for identifying duplicates only relies on comparing images by their file hash. While this is a good initial step, it has limitations, especially when dealing with similar images of varying quality.

For instance, my personal use case involves syncing my phone with a NAS running Photoprism. This synchronization includes images captured by my phone's camera, WhatsApp images, and occasionally, higher-quality versions of images received from friends. This leads to a situation where duplicate images with varying resolutions and qualities accumulate in my collection.

**Describe the solution you'd like**

I propose the implementation of a visual comparison feature within Photoprism's duplicate image detection functionality. This enhancement would allow the system to analyze the visual content of images rather than solely relying on file hashes. By performing visual similarity analysis, Photoprism could intelligently identify duplicate images even if they have undergone modifications such as resizing, compression, or slight editing.

For instance, when I receive higher-quality versions of images that were initially present in my collection, Photoprism would be able to detect the duplicates and suggest the removal of the image with the lower quality. This would help in keeping the collection organized and free from redundant images of varying qualities.

**Describe alternatives you've considered**

In the past, I attempted to address the duplicate image issue using perceptual hashing. However, while perceptual hashing was effective, the process was limited to my custom application and lacked the seamless integration and broader functionalities that a dedicated tool like Photoprism offers.

**Additional context**

Info about perceptual hashing
- https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html. 

_Originally posted by @vanBassum in https://github.com/photoprism/photoprism/issues/1308#issuecomment-1686234309_

**Comment by graciousgrey** [comment]
Perceptual hashing is already implemented, we just don't have a user interface to view or merge files that are very similar.

Related to:
- https://github.com/photoprism/photoprism/issues/1182
- https://github.com/photoprism/photoprism/issues/28

**Comment by vanBassum** [comment]
Ah great, this can be closed then.
