### ISSUE TITLE
Path filter: How to escape spaces?

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#368]
I am running photoprism in readonly mode. Maybe it is therefor that the "original" search filter returns nothing. I can use the path filter though. But this is another issue.

When using the path filter with pictures that have spaces in the path, the search returns nothing. I tried quoting the search term with double quotes and escaping the spaces with backslashes. None of these worked. How can spaces be escaped?

**Comment by lastzero** [comment]
Quotes like path:"folder name" should work

**Comment by wiwie** [comment]
yes my bad, forgot the /* in the end of the path. can confirm that it works with double quotes.
