### ISSUE TITLE
Duplicate key error while importing

### ISSUE THREAD

**Issue by jdhuntington** [photoprism/photoprism#369]
While importing multiple files, I've noticed several errors referencing duplicate keys of the form:

    2020-06-28 21:11:55 ERRO photo-keyword: Error 1062: Duplicate entry '3920-351' for key 'PRIMARY'

Configuration:
- Version: `200628-7f94259-Linux-x86_64`
- Workers: default
- Backend: mariadb

**Comment by lastzero** [comment]
Thanks for reporting this! Probably not a real issue since keywords should in fact only be indexed once per photo... unique index works as expected.

**Comment by lastzero** [comment]
Closing this. Please create a new issues if you find a bug!
