### ISSUE TITLE
Album and Album Share: Clicking on any picture with pid > 100 shows fullscreen overlay for picture with pid=1

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#370]
I am using the newest docker as of 5 minutes ago.

I created an album with more than 100 pictures. I created a share for this album as well.

With either album and share, when I click on any picture with pid>100, the picture fullscreen overlay is shown for picture with pid=1 instead of the clicked picture.

I did not reset the database when updating to the newest docker. If that could be the cause of this issue, please let me know and I'll try again after resetting the database.

**Comment by lastzero** [comment]
Did you clear the browser cache? Might be related to #309, since we now load the full list of photos for large result sets.

**Comment by wiwie** [comment]
Tried clearing browser cache, tried it in a private tab, tried in Firefox and Chromium. Same result.

**Comment by lastzero** [comment]
Same happens to me, but not always... clearly a bug. That's why we didn't want to implement #309, but now we'll fix it... once the problem is clear... files are being update in the background, so the index of images changes all the time.

**Comment by lastzero** [comment]
Might only happen while the indexer is running and adding new files...

**Comment by wiwie** [comment]
All images had been indexed (at least initially) before I observed the behavior. Last indexing I initiated was yesterday.

**Comment by wiwie** [comment]
If the indexer re-encounters index files their index is probably not modified?

**Comment by lastzero** [comment]
Not sure, but thanks for reporting this. It was a long day, I'll take a look at this tomorrow. Probably a frontend (JS) issue. Everyone is most welcome to debug this in the meantime :)

**Comment by wiwie** [comment]
The issue occurs, as long as not all photos of the album have been loaded.

When opening an album with sufficiently many pictures such that not all pictures are loaded initially, all pictures with pid>100 behave faulty.

When scrolling down a bit such that some more pictures are loaded but not all, still all pictures with pid>100 behave faulty. 

As soon as one has scrolled down all the way down and all pictures have been loaded, all pictures including those with pid>100 behave correctly.

**Comment by lastzero** [comment]
That's by design. If all photos are loaded, we use the actual results for the photo viewer. If not, we request the full list (up to 3333 files).

**Comment by wiwie** [comment]
I was probably not clear enough in my explanation.

This issue that clicking on an image with pid>100 brings up the wrong fullscreen version of the first image of the album (pid=1) occurs only as long as not all images of the album have been loaded. Once all images have been loaded (by scrolling all the way down), the issue disappears and clicking on any image (also pid>100) brings up the correct fullscreen version.

**Comment by wiwie** [comment]
can confirm that it works now. However, opening a picture seems to take longer than yesterday (spinner on top shows longer)? possibly nothing related to your changes, just thought I should mention it.

**Comment by lastzero** [comment]
It does since we load the full list, however this was optimized during the day. Should be 30% faster now.

**Comment by wiwie** [comment]
Ok. I'm using the latest docker as of 5 minutes ago and it's still perceivable slower than yesterday.

**Comment by lastzero** [comment]
I have an idea how to optimize it further... We'll be the kings of complexity 🤴
