### ISSUE TITLE
Archive: Add "Delete All" button to permanently delete all files

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3701]
**As a user with many archived pictures that I want to permanently delete, I would like a "Sweep Archive" button to delete all archived pictures so I don't have to select them first.**

This enhancement is related to the following (more general) issue:

- https://github.com/photoprism/photoprism/issues/272#issuecomment-1646880786

**Comment by anst84** [comment]
How to get access to preview functions? It is not equal to ticking ""Experimental features" in settings?

**Comment by lastzero** [comment]
@anst84 If you are using Docker, you can test [upcoming features and enhancements](https://docs.photoprism.app/release-notes/#development-preview) by changing the `photoprism/photoprism` image tag from `:latest` to `:preview` :point_down: 

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by anst95** [comment]
Thanks I will try that!
