### ISSUE TITLE
All photos are disappeared

### ISSUE THREAD

**Issue by pippo73** [photoprism/photoprism#3703]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

After importing a lot of photos,  and everything was working well, this morning I've noticed that all photos as diappeared.
How can I understand were are they and why they are lost?

#### 2. How can we reproduce it?

1. import photo
2. Search for them

#### 3. What behavior do you expect?

See my photos

#### 4. What could be the cause of your problem?

in the log file I've foung a long trace that the files are indicated as missing, but not why they are lost

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Tell me what you need

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: PhotoPrism® CE Build [230719-73fa7bbe8 on 

(b) Database Type & Version: MariaDB,

(c) Operating System Types & Versions: Linux,

(d) Browser Types & Versions: Firefox, 

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

**Comment by lastzero** [comment]
It is probably a config issue, e.g. with the storage folders or the database. I'll convert this to a discussion for you! :)
