### ISSUE TITLE
Possible Memory Leak when Uploading 

### ISSUE THREAD

**Issue by Aidan-OS** [photoprism/photoprism#371]
Beginning to import the bulk of my files, and have noticed a high memory usage after uploading, persisting until the Docker container is restarted. I'm not sure how automated garbage collection works in Go, nor do I know if this is just how Docker works. I have tested with re-indexing, and it doesn't appear to increase the RAM usage.

**Just Started**
![image](https://user-images.githubusercontent.com/1919827/86062209-2fbae800-ba36-11ea-9874-5de0b729a126.png)

**9 Files Uploaded**
![image](https://user-images.githubusercontent.com/1919827/86062795-7c52f300-ba37-11ea-8f32-a12959336082.png)

For a temporary solution I am just going to run a Cron job to restart in the middle of the night, however, I have had to restart a couple times manually while bulk uploading images in batches. I have restarted before capping out my memory, so it is possible that it will only free RAM as it needs it, but I am currently being careful just in case.

**Comment by lastzero** [comment]
1 GB after indexing is not a memory leak, it's TensorFlow. Wo only load it on demand but then it stays in memory, not sure if it's even possible to "unload" it. Loading it again every time we need it would be extremely slow. Our public demo was up for weeks without running out of memory.

**Comment by lastzero** [comment]
If you don't need TensorFlow, you can disable it to save memory.

**Comment by Aidan-OS** [comment]
I should have expanded with further images. After uploading another 20 it bumps up to 4.5gb of used memory, and the memory is not freed. I don't know if that changes anything, but yes, I will probably be disabling TensorFlow

**Comment by Aidan-OS** [comment]
I do not see any information on how to disable TensorFlow on the Repo homepage, the photoprism docs, or in the docker-compose. Could you point me to where I can find how to turn it off?

**Comment by lastzero** [comment]
As written in the docs, run `photoprism help` to see all options until we had time to add all of them to docs.photoprism.org :)

**Comment by Aidan-OS** [comment]
Got it. Set in docker-compose.yml as `PHOTOPRISM_TENSORFLOW_OFF: ''`. Writing it down for any other person who stumbles on this.

**Comment by lastzero** [comment]
Better set it to "true", just to be sure. Memory consumption could also be caching, like when you request thumbs via http. So the memory may only be reserved but is not running out.

**Comment by Aidan-OS** [comment]
After I set this last night, the majority of my images actually vanished. The images were in the folder when I went to view in terminal, however Photoprism would not index them. It actually resulted in starting from scratch again, losing labels on over 200 images, most of which had 3+ labels.

This morning, I went to work on it some more, and found that I could not view the full image of anything past the first 100 on the main images screen. Clicking on the thumbnail of any image past the 100th would bring up the first image. I know this ticket is not the place for that problem.

**Comment by lastzero** [comment]
Sounds like a storage / configuration issue. The problem with the image viewer is fixed, we implemented a feature request and introduced a bug.

**Comment by Aidan-OS** [comment]
if I update the container, will that issue be fixed then?

**Comment by lastzero** [comment]
Yes, see related issues here on GitHub. Has been discussed and fixed today.
