### ISSUE TITLE
Incorrect dates when importing files having WhatsApp name extension in metadata from Google Takeout

### ISSUE THREAD

**Issue by DHBytes** [photoprism/photoprism#3716]
**Photoprism Build:** 221118-e58fee0fb
DB: MariaDB 10.11
OS: Fedora Linux 38
Installation: Docker Compose

**Steps to reproduce:**
I am importing my media from a Google Takeout dump that includes the corresponding JSON metadata sidecar files. I start with a fresh install of Photoprism and immediately place my photos and their JSONs from Takeout into my configured import directory. I unchecked "Estimates", "Place & Time", and "Unique ID" in Settings and checked "Debug Logs" in Advanced Settings.

**Observed issue:**
Media files that originated from WhatsApp and therefore have file names such as `IMG-20220528-WA0004` cause the "photoTakenTime" field (in the JSON) to be parsed incorrectly. For every such WhatsApp image, the day listed in "photoTakenTime" field is ignored, resulting in the image's date's day always being the 1st of the month.

Note: Other non-WhatsApp images' dates are parsed correctly.

Maybe it's not necessarily related to WhatsApp, but to the fact that the image filename contains additional characters after the "IMG-20XXXXXX" part?

**Example metadata JSON:**
```json
{
  "title": "IMG-20220528-WA0004.jpg",
  "description": "",
  "imageViews": "2",
  "creationTime": {
    "timestamp": "1653738315",
    "formatted": "May 28, 2022, 11:45:15 AM UTC"
  },
  "photoTakenTime": {
    "timestamp": "1653737395",
    "formatted": "May 28, 2022, 11:29:55 AM UTC"
  },
  "geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "url": "",
  "googlePhotosOrigin": {
    "mobileUpload": {
      "deviceFolder": {
        "localFolderName": "WhatsApp Images"
      },
      "deviceType": "ANDROID_PHONE"
    }
  },
  "photoLastModifiedTime": {
    "timestamp": "1674839954",
    "formatted": "Jan 27, 2023, 5:19:14 PM UTC"
  }
}
```
**Result:**
![image](https://github.com/photoprism/photoprism/assets/132843604/de887365-7e8c-4aeb-ac14-d620ca397485)

**Expected Result:**
The date on the image should be May 28, not May 1.

**Comment by graciousgrey** [comment]
You are using an older version. It is recommended to update to the [latest version](https://docs.photoprism.app/release-notes/#july-19-2023) and test the issue again, as support for reading dates from WhatsApp filenames has been added in the meantime. 

However, it is also possible that there is additional Exif information in your original file. See also:
- https://github.com/photoprism/photoprism/issues/2133

**Comment by DHBytes** [comment]
> You are using an older version.

Yes! That was indeed the problem. Thank you.
