### ISSUE TITLE
Duplicate tags when changing a label

### ISSUE THREAD

**Issue by Aidan-OS** [photoprism/photoprism#372]
When labeling different images, occasionally I have made a mistake with the spelling of a label, and immediately gone to fix it. I have fixed the spelling by clicking on the label and retyping the correct spelling. Now when I browse by label there is a selection for each of the times I have misspelled the word.

**Example from Label menu** (Censored for privacy)
![image](https://user-images.githubusercontent.com/1919827/86181150-80e0df80-bafb-11ea-8f2d-45088d9af6a1.png)

As you can see, there are three different options for the same label. Clicking on any of these shows the same set of images, however I don't believe this is intended behaviour. This issue persists through server restarts and full re-indexes.

**Comment by lastzero** [comment]
I assume none of these labels were created automatically as you turned off TensorFlow?

**Comment by lastzero** [comment]
I'll take a look. Wouldn't it be easier to use albums instead of labels? They were made for automatic tagging, not so much for user generated collections of photos. Albums also allow you to sort results in different ways plus you can add a description.

**Comment by lastzero** [comment]
Just to be sure: Did you test our latest Docker image with a fresh database?

I created a custom label, assigned multiple images and renamed it multiple times without any issues:

![Screenshot 2020-07-01 at 20 31 44](https://user-images.githubusercontent.com/301686/86279271-09ce4880-bbda-11ea-81c3-bc6ae76eeb00.png)

**Comment by Aidan-OS** [comment]
Am I able to add images to multiple albums? If so, I will start using albums instead. The instance I used was clean, but may have not been the most recent version of the docker image.

**Comment by lastzero** [comment]
PS: It is NOT possible yet to merge labels, like when you in fact added the same label multiple times and then rename it so that the different labels appear to have the same name. They are still different labels / IDs.

**Comment by lastzero** [comment]
Of course you can add one photo to as many albums as you like 👍

**Comment by lastzero** [comment]
If that works for you and my explanations make sense, please close the issue.
