### ISSUE TITLE
Photoprism empty file error and invalid cross-device link error

### ISSUE THREAD

**Issue by Bnewn** [photoprism/photoprism#3724]
**1. What is not working as documented?** 
The import and indexing of RAW/HEIC filetypes. I am having an empty file error along with a invalid cross-device link error. I tried moving the directory of originals, import, and storage to one place but that still does not work. PhotoPrism is not converting RAW/HEIC files to JPEG therefore not thumbnail is created. It will create them if I manually run an indexing call after the import is completed.

**2. How can we reproduce it?**
1. Add a picture that needs jpg conversion such as HEIC or DVG
2. Click import (move files checkbox can be checked or unchecked, it leads to same errors)
3. File gets imported but no JPEG created

**3. What behavior do you expect?**
PhotoPrism should create JPEG converted file and auto index after import is called

**4. What could be the cause of your problem?**
Root cause could be directory issue or problem
However, this is odd because it worked before with no problems, I only noticed this issue after I expanded my local VM disk space. 

**5. Can you provide us with example files for testing, error logs, or screenshots?**
```
[GIN-debug] redirecting request 307: /api/v1/import/ --> /api/v1/import/
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 folders [1.237752ms]"
time="2023-09-13T15:17:08Z" level=debug msg="removed folder:import:true:false from cache"
time="2023-09-13T15:17:08Z" level=info msg="moving files from import"
time="2023-09-13T15:17:08Z" level=info msg="import: found no .ppignore file"
time="2023-09-13T15:17:08Z" level=info msg="media: IMG_4926.heic was taken at 2023-09-06 17:21:06 +0000 UTC (meta)"
time="2023-09-13T15:17:08Z" level=info msg="import: moving main heic file IMG_4926.heic to 2023/09/20230906_172106_2170680D.heic"
time="2023-09-13T15:17:08Z" level=debug msg="failed renaming file, fallback to copy and delete: rename /photoprism/import/IMG_4926.heic /photoprism/originals/2023/09/20230906_172106_2170680D.heic: invalid cross-device link"
time="2023-09-13T15:17:08Z" level=info msg="media: 2023/09/20230906_172106_2170680D.heic is empty"
time="2023-09-13T15:17:08Z" level=error msg="import: convert: 2023/09/20230906_172106_2170680D.heic is empty in 2023/09/20230906_172106_2170680D.heic (convert to jpeg)"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no orphan markers [1.815077ms]"
time="2023-09-13T15:17:08Z" level=debug msg="markers: found no invalid references [2.277571ms]"
time="2023-09-13T15:17:08Z" level=debug msg="markers: found no missing subjects [653.475µs]"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no ambiguous subjects [527.877µs]"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no clusters to be merged [549.488µs]"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no existing clusters"
time="2023-09-13T15:17:08Z" level=debug msg="faces: skipped clustering"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no new faces [1.095374ms]"
time="2023-09-13T15:17:08Z" level=debug msg="faces: found no unmatched markers"
time="2023-09-13T15:17:08Z" level=debug msg="faces: updated 0 markers, recognized 0 faces, 0 unknown [1.492411ms]"
time="2023-09-13T15:17:08Z" level=debug msg="index: updating counts"
time="2023-09-13T15:17:08Z" level=debug msg="counts: updated 0 places [553.813µs]"
time="2023-09-13T15:17:08Z" level=debug msg="counts: updated 0 subjects [725.634µs]"
time="2023-09-13T15:17:08Z" level=debug msg="counts: updated 0 labels [727.283µs]"
time="2023-09-13T15:17:08Z" level=info msg="import: imported 2 files"
time="2023-09-13T15:17:08Z" level=debug msg="moments: analyzing 0 photos and 0 videos, with threshold 3"
time="2023-09-13T15:17:08Z" level=debug msg="moments: not enough files"
time="2023-09-13T15:17:08Z" level=info msg="import completed in 0 s"
time="2023-09-13T15:17:08Z" level=debug msg="index: updating covers"
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 albums [855.894µs]"
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 folders [1.199926ms]"
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 months [718.63µs]"
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 labels [946.785µs]"
time="2023-09-13T15:17:08Z" level=debug msg="covers: updated 0 subjects [631.912µs]"
```

**6. Which software versions do you use?**
(a) PhotoPrism Architecture & Build Number: AMD64 Build [230719-73fa7bbe8]

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Chrome,

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? N/A

**7. On what kind of device is PhotoPrism installed?**
Installed through a Debian 11 VM
(a) Device / Processor Type: Intel Xeon CPU E5-2698 v3
(b) Physical Memory & Swap Space in GB: 16GB ram, 9GB SWAP
(c) Storage Type: All files on remote SMB powered by TrueNAS Scale
(d) Anything else that might be helpful to know? N/A

Here is my docker compose
```
volumes:
      - "/mnt/SecureNAS/Storage/Pictures:/photoprism/originals"
      - "/mnt/SecureNAS/Storage/import:/photoprism/import"
      - "/mnt/SecureNAS/Storage/VM Data/PhotoPrism/storage:/photoprism/storage"
```

**Comment by aaliddell** [comment]
You need to mount your SMB volume under a single mount point in your compose at the point of the common prefix:

```yaml
volumes:
  - '/mnt/SecureNAS/Storage:/some/mount/point'
```

Then use the env vars to pick out the paths you want:

```yaml
environment:
  PHOTOPRISM_ORIGINALS_PATH: '/some/mount/point/Pictures'
  PHOTOPRISM_IMPORT_PATH: '/some/mount/point/import'
  etc
```

If `/mnt/SecureNAS/Storage` is not actually a SMB mountpoint but the parent of the mount points, then you may need to set the mount propagation flag also (not tested):

```yaml
volumes:
  - type: bind
    source: /mnt/SecureNAS/Storage
    target: /some/mount/point
    bind:
      propagation: rslave
```

**Comment by Bnewn** [comment]
Works perfectly after mounting under a single mount point in the compose! Hopefully this is useful for others, although it is very specific
Thank you so much!

**Comment by williamtrelawny** [comment]
Ran into the same issue myself. If PhotoPrism imports cannot work when import and originals folders are on separate mount points/filesystems, then this `DEBUG` level message should be returned to `ERROR` level as it was [originally](https://github.com/photoprism/photoprism/issues/136#issuecomment-552571292). 

Unless this indicates the fallback copy mechanism is broken, which seems to be the case. Either way- if import is supposed to be able to work across 2 filesystems but cannot, then this is indeed a bug. If it isn't supposed to work, then make this `invalid cross-device link` message an `ERROR` level again so users are properly alerted to it.

**Comment by lastzero** [comment]
@williamtrelawny Since the *Import* and *Originals* folders have separate mount points by default, so basically in all our test environments and most of our users' production environments, I don't think the fallback copy mechanism is broken (until e.g. confirmed by another user reporting the same issue). This is why it's currently a DEBUG message for developers and not an ERROR message for end users to take action :)

**Comment by lastzero** [comment]
From what I can tell, the original problem here was related to the use of remote storage, so the file system entries were cached or out of date, leading to issues which could be solved by using a single mount point. So it is/was not a general problem with our software that would always prevent imports if you don't use a single mount point. Using a single mount point is of course faster, but less flexible. So what is best depends on your file system layout and personal preferences.
