### ISSUE TITLE
People view: Change "profile" picture

### ISSUE THREAD

**Issue by anst84** [photoprism/photoprism#3728]
**Describe what problem this solves and why this would be valuable to many users**

The People library shows a (random?) picture of that person. This is not always the most representative photo of that person. It would be great to be able to change that "profile" picture.

**Describe the solution you'd like**

Not sure what the best UX would be for this, but here are two suggestions:

1. 
a. Select photo
b. Press action menu (bottom right)
c. Select "Pin as default for People"
d. Select Person

2. 
a. View photo
b. Select edit
c. Select People tab
d. Checkbox: Pin as default for Person in People view

**Describe alternatives you've considered**

Nothing to add

**Additional context**

Nothing to add

**Comment by graciousgrey** [comment]
We do already have an issue for this :)

- https://github.com/photoprism/photoprism/issues/383

**Comment by anst95** [comment]
Aha. I searched before I posted but not good enough apparently :)
