### ISSUE TITLE
hardware encoding must use uid=root? thats unsafe

### ISSUE THREAD

**Issue by GavinIves** [photoprism/photoprism#3739]
**Describe what problem this solves and why this would be valuable to many users**

In docker, when I enable Intel's core display for hardware encoding, my uid must be set to root, otherwise hardware decoding cannot be performed. Will this cause security issues? Or is there something wrong with my configuration?
<img width="366" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/0a802723-0f8c-43a5-b2aa-8f01774e9b8d">
<img width="691" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/f3cc7524-7608-4601-890e-a734ea2129c2">

but i use root, its ok!!! i know use hardware need high Permission, but we can use GIDLIST to solve it
image
<img width="373" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/ab127973-342d-43ba-953e-6ca11972012b">

<img width="794" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/8af67462-4150-4077-aa85-f319aae3f9fe">

**Describe the solution you'd like**

maybe like emby,use GIDLIST # A comma-separated list of additional GIDs to run emby as (default: 2) to solve it 
url: https://hub.docker.com/r/emby/embyserver
<img width="806" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/0ca0a901-6e13-4ea1-9458-247d8bee2dfd">

<img width="775" alt="image" src="https://github.com/photoprism/photoprism/assets/38970877/80961e98-46d7-4b42-a9d8-8c5a99a51905">

**Describe alternatives you've considered**

**Additional context**

**Comment by lastzero** [comment]
Granting fewer permissions is always more secure, but that doesn't mean it's instantly unsafe to grant the permissions an application (or driver) needs. I'll close this issue in favor of the discussion you opened at the same time.
