### ISSUE TITLE
Feature Request: Make frontend a progressive web app (PWA)

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#374]
As a user I want to be able to pin a photoprism instance from my mobile browser to the Homescreen of my phone and then use the shortcut as if photoprism was a native app. This functionality is called progressive web app (PWA).

As far as i know all that is needed is to embed a PWA manifest json file that defines how the PWA should behave and look like.

I know there is a mobile app in development, but I think adding this functionality to the frontend is little effort and would provide a valuable mobile experience of photoprism while photoprism-mobile is still behind the frontend's feature set. I think especially in the early stages of the project where things change more rapidly this would make sense.

**Comment by lastzero** [comment]
Already done 🌈

**Comment by wiwie** [comment]
Ok. I missed the you already include a manifest. But something seems wrong or missing, as it is not working for me on Android. Tried with chromium, Firefox and Firefox preview.

I've experienced before that browsers are quite sensitive to the contents of the manifest file. Amongst others, the dimensions of the referenced icon image files.

**Comment by wiwie** [comment]
The nextcloud manifest file works for me, so maybe you could try including the icon sizes they do?



```
{"name":"Nextcloud","start_url":"https:\/\/xxx","icons":[{"src":"\/apps\/theming\/icon?v=0","type":"image\/png","sizes":"128x128"},{"src":"\/apps\/theming\/favicon?v=0","type":"image\/svg+xml","sizes":"16x16"}],"display":"standalone"}
```

**Comment by lastzero** [comment]
Works for me on on Android and iOS, all I had to do is click "add to home screen". We're still working on updated icons and favicons that match our new logo.

**Comment by wiwie** [comment]
Yes which is also what I do. For me though it doesn't add the app to the Homescreen as a PWA, just as a regular shortcut that just opens up a browser tab when I click on it.

**Comment by lastzero** [comment]
Our demo opens without tab, full screen. It will run within Chrome in any case as it needs a browser. It's possible Google requires HTTPS to hide the tab / site info.

**Comment by lastzero** [comment]
![Screenshot_20200702_094946](https://user-images.githubusercontent.com/301686/86331618-a2e87800-bc49-11ea-8140-436be75334b7.jpg)

**Comment by wiwie** [comment]
You are right. It works with the demo installation, but not with my own.

My own instance has cert+https as well, so that can't be the problem. I'm using nginx as reverse proxy, maybe it has something to do with that. I'll look into it and report back in case I find anything.

**Comment by wiwie** [comment]
The reason it isn't working with my instance is that I have htaccess enabled. When disabling it the PWA indeed works in chromium and Firefox.
