### ISSUE TITLE
All /library/videos disappear after upload images and/or videos with PhotoSync 

### ISSUE THREAD

**Issue by pbenaim** [photoprism/photoprism#3753]
I discovered Photoprism thanks to PhotoSync, and I love Photoprism 👍 

But when I use PhotoSync with WEBDAV protocol to upload images and/or videos 
Just after upload, All /library/videos disappear and goto /library/hidden 😭 

To retrive again the only solution is to make one re-index all originals, so a very long time of work... 
( Today I have 13282 pictures and 1436 videos )

NB: Is not the case when I use Upload from Photoprism webpage, but I'm losing interest in PhotoSync 😢 

- PhotoPrism : Build 230719-73fa7bbe8
- OS : Windows 11 Pro / 10.0.22621 Build 22621 / Docker Desktop 4.21.1
- PhotoSync Android : V 4.0.7 (5731)
- Database : MariaDB ( installed by docker-compose.yml )

**Comment by graciousgrey** [comment]
To find out what the problem might be, can you tell us a little more about how you configured your [volumes](https://docs.photoprism.app/getting-started/docker-compose/#volumes) (originals, storage, import) and what folder you let PhotoSync move the new files to?

If you look at the [logs](https://docs.photoprism.app/getting-started/troubleshooting/logs/) with debug or trace mode enabled during an upload, you might get additional information.

**Comment by pbenaim** [comment]
Yes videos really in originals folder

My log say that 

2023-09-21 11:00:57 INFO webdav: PUT /originals/originals/Xiaomi%20POCO%20F2%20Pro/Camera/VID_20230921_110020.mp4

2023-09-21 11:06:08 INFO indexation terminée en 189 s

2023-09-21 11:06:05 INFO suppression de 1941 fichiers et 0 photos

2023-09-21 11:06:04 INFO index: flagged 1,933 photos as hidden [73.443153ms]

in docker-compose.yml I have:
volumes:
- "C:/Users/pbena/Pictures:/photoprism/originals"  
- "C:/PhotoPrism/import:/photoprism/import"                         # *optional* base folder from which files can be imported to originals
- "C:/PhotoPrism/storage:/photoprism/storage"                    # *writable* storage folder for cache, database, and sidecar files (never remove)

I tryed two times with 2 videos ( video one by one )
And after indexing, I have only the last video in /library/videos 😢 
other videos are in /library/hidden

**Comment by lastzero** [comment]
If it's not a file permissions problem, it may also be the characters in the folder name (Windows and Linux have a different set of reserved special characters). Could you try a folder name that contains no spaces and only alphanumeric characters otherwise?

Edit: If you are using a proxy like Nginx in between, it could also alter the file/folder names that PhotoPrism receives from PhotoSync.

**Comment by pbenaim** [comment]
All apologies, it was in the docker-compose.yml file, # before "C:/PhotoPrism/storage:/photoprism/storage" and of course not writable... And of course, too, no storage folder for cache, database, and sidecar files 😕 

So I close this false bug...

Sorry again, and long live to Photoprism
