### ISSUE TITLE
Bug: 'Connecting' box appears and will not go away

### ISSUE THREAD

**Issue by dddddddavid** [photoprism/photoprism#376]
This behaviour only started today.

Yellow box appears at the top of the main page and will not disappear. Navigation is normal & I can scroll, check out the map, look at labels and open pictures. 

When I return to the photos page - or any page which is not an individual photo, 'connecting' is still there until I refresh the page using browser controls.

Connection is obviously fine as I can move around, look at photos etc.
![Screenshot_2020-07-02_22-32-39](https://user-images.githubusercontent.com/57491766/86411227-4a01f980-bcb4-11ea-811e-79984f9614e0.png)

Server: Raspberry Pi 4 8GB Raspberry Pi OS 64 bit

PhotoPrism -  200702-5c180fd6-Linux-aarch64 

Client: Firefox 77.0.1 on Ubuntu 20.04

It's probably not incredibly important, but it's incredibly irritating.

**Comment by lastzero** [comment]
Click on the text and it will lead you to the related issue.

**Comment by dddddddavid** [comment]
OK. It leads me here: https://github.com/photoprism/photoprism/issues/330

I don't have any of the issues that person describes, but the console shows repeated Firefox can't establish a connection to the server at wss://mysite.com/api/v1/ws.

Functionally, It's fine apart from the warning.

**Comment by lastzero** [comment]
Are you using any sort of proxy (like caddy, nginx, apache,...) or special browser settings that may prevent websockets from working?

**Comment by dddddddavid** [comment]
Using Apache with a reverse proxy. I can't see anything wrong with it?

<VirtualHost *:443>
    ServerName myserver

    SSLEngine on
    SSLProxyEngine on
    ProxyPreserveHost On

    ProxyPass "/socket" "ws://192.168.1.32:2342/socket"
    ProxyPassReverse "/socket" "ws://192.168.1.32:2342/socket"

    ProxyPass "/" "http://192.168.1.32:2342/"
    ProxyPassReverse "/" "http://192.168.1.32:2342/"

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/myserver/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/myserver/privkey.pem
    Protocols h2 http/1.1

#   Enable only strong encryption ciphers and prefer versions with Forward Secrecy
    SSLCipherSuite HIGH:RC4-SHA:AES128-SHA:!aNULL:!MD5
    SSLHonorCipherOrder on

 #   Disable insecure SSL and TLS versions
    SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1

    ErrorLog /var/log/apache2/myserver-error.log
    CustomLog /var/log/apache2/myserver-access.log combined
</VirtualHost>

**Comment by lastzero** [comment]
Moved the info to the sidebar navigation and added a help page which contains examples for common proxies:

![Screenshot 2020-07-03 at 17 02 55](https://user-images.githubusercontent.com/301686/86480841-19bb6900-bd4f-11ea-9a80-f257b8c0a53b.png)

**Comment by dddddddavid** [comment]
Perfect. Thank you very much
