### ISSUE TITLE
Category: Short Description (PLEASE CHANGE)

### ISSUE THREAD

**Issue by deslea** [photoprism/photoprism#3761]
**Describe what problem this solves and why this would be valuable to many users**

I would love to be able to train Photoprism manually to recognise specific recurring non-human creatures or objects you want it to find, such as specific pets by name.

**Describe the solution you'd like**

Some sort of "Train To Recognise Object" interface at which you could upload a reasonable number of images of the object (let's say a pet) and tell it the name/label you want to associate with this object, then optionally to ask it to scan existing images for it. The idea is that you could teach it to individually recognise all your pets and associate it with the pet's name.

**Describe alternatives you've considered**

The existing recognition of dogs, cats, etc is theoretically useful, but becomes less so in households with a lot of animals, especially when your friends and family may have lots of animals in pictures as well.

**Additional context**

It's probably pretty obvious I'm hoping to manage my many many thousands of cat pictures (LOL) but I could imagine this might also be useful for some types of hobbies, etc. But if it's too complicated to pre-provision for "just any" object, certainly I think pets are the main use case.

**Comment by graciousgrey** [comment]
Thank you very much for your feedback! We do have a issue for pet detection already:

- https://github.com/photoprism/photoprism/issues/1561 

Feel free to leave a :+1: in there :)
