### ISSUE TITLE
Videos: Cache embedded media to allow streaming and transcoding

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3764]
**As a user of image files that have video embedded in them, I want the videos to be served from cache to support streaming and transcoding if needed.**

This is a follow-up issue for the following feature requests that have already shipped with our [stable release](https://docs.photoprism.app/release-notes/#september-23-2023):
- #439
- #1739

**Comment by MEGAMENE** [comment]
This change broke my Google Pixel 6 Motion Photos that have the video content in the HVC1 format.
I get a "file type of cannot be transcoded" error.
I upload a testFile to the Photoprism Demo instance to make sure it wasn't a problem on my end, and the same thing happens.

**Comment by lastzero** [comment]
Can you please send us a sample file for testing l to samples@photoprism.app?

**Comment by MEGAMENE** [comment]
> Can you please send us a sample file for testing l to [samples@photoprism.app](mailto:samples@photoprism.app)?

I've just sent a sample to the email.

**Comment by lastzero** [comment]
Thanks! Seems like the container file type extension cannot be properly detected by the library we use. The extracted video looks good otherwise. I'll fix this in the next few days.

**Comment by lastzero** [comment]
@MEGAMENE Could you please help us test this on our demo or with our preview build? See #3814. Thank you!

**Comment by MEGAMENE** [comment]
> @MEGAMENE Could you please help us test this on our demo or with our preview build? See #3814. Thank you!

I just installed the latest preview build on my server and it seems to be working without any problems.
The videos seem to take longer to start playing the first time, especially compared to the Samsung ones that I have. I'm guessing the transcoding takes longer on the Google photos.

**Comment by lastzero** [comment]
Yes, indeed. We currently transcode to AVC for maximum browser compatibility until we had time to implement dynamic codec detection. The main codec for these files is HEIC or JPEG and there is currently only one field for it, so the video codec is only known on the server side and not in the browser when you play a motion photo.
