### ISSUE TITLE
Search for everything not inside an album

### ISSUE THREAD

**Issue by eigan** [photoprism/photoprism#377]
Would make it easier to locate items I should put into albums.

**Comment by lastzero** [comment]
We had search in albums, but want to encourage users to keep them small so that no search is needed. There are plenty of other pages where you can search.

**Comment by eigan** [comment]
Hi @lastzero. Not sure if you misunderstood. I meant that I wanted to find every item which currently is not in any album. 

1. Go to photos section.
2. Search with a special keyword: "not-in-album"
3. Result shows now every photo not in any album.

**Comment by lastzero** [comment]
Oh, that would be easy to implement.

**Comment by lastzero** [comment]
Build is running, updated Docker images available for testing soon!

**Comment by eigan** [comment]
How can i test this @lastzero?

**Comment by lastzero** [comment]
![Screenshot_20200705_163109](https://user-images.githubusercontent.com/301686/86534933-f6bebf80-bedc-11ea-9052-617d928c2c17.jpg)

Albums > Unsorted

**Comment by eigan** [comment]
**"Albums" not marked as active**
same behavior as "Folders" though. Feel like these should work the same as with child items of Photos? When you refresh, the "Albums" section should be expanded, no?
![2020-07-05_16-50](https://user-images.githubusercontent.com/41789/86535313-b9a7fc80-bedf-11ea-8c90-e4b9b11f4321.png)

**List not updated after added to album**
I feel like the list should be updated after adding something to an album as it is no longer unsorted. What do you think?

**Comment by lastzero** [comment]
You mean updated without manually reloading?

Albums itself is not marked as this page is not an album, but a photo search.

**Comment by eigan** [comment]
> You mean updated without manually reloading?

Yes. But I have noticed editing a photo so the criteria no longer match _(like changing label, while filtering on label)_ doesnt update the list either. So current behavior is more consistent. 

> Albums itself is not marked as this page is not an album, but a photo search.

I see. I started using PhotoPrism yesterday so I guess it will feel natural after using it more :slightly_smiling_face:

Thanks for implementing this so quick!

**Comment by bitelxux** [comment]
Just arrived. Fantastic tool. The extra point here would be if, when filtering by unsorted, the photos add to an album were automatically removed from the view and the cursor stayed at the same point. Same way when pictures are archived they are automaticaly removed from the current view. That way it would be way easier to organize photos.
