### ISSUE TITLE
RAW-Files from Panasonic GH5 MK2 are rendered incorrectly

### ISSUE THREAD

**Issue by SmithChart** [photoprism/photoprism#3771]
_Thanks for this cool piece of software! This is exactly what I have been looking for for a long time! While testing it out with my photo library I encountered the following problem:_

#### 1. What is not working as documented?

RAW Photos taken on a Panasonic GH5 MK2 (also known as `DC-GH5M2`) only show noise in rendered JPEGs. See the following screenshot as an example:
![Screenshot from 2023-09-27 19-09-49](https://github.com/photoprism/photoprism/assets/6676035/24e229a5-e08c-4403-b311-9f4caa56dc0b)

#### 2. How can we reproduce it?

* Make a new, blank installation using the `docker compose` way documented here: https://docs.photoprism.app/getting-started/docker-compose/
* Put a few RAW files form the GH5MK2 into the `Originals`-folder.
* Put a few RAW files form the `EM10 Mark III` into the `Originals`-folder (to check if imports work in general).
* Put a few JPG (Exported by Darktable) files into the `Originals`-folder (to check if imports work in general).
* Go to the WebApp -> Library -> Index. Start a Scan
* Wait for the scan to complete.
* Go to Folders. Find that the GH5MK2 JPEGs are broken, the others are ok.

#### 3. What behavior do you expect?

I expect the JPGs of these RAWs rendered correctly.

#### 4. What could be the cause of your problem?

The GH5 MK2 uses a rather new RAW-format. Darktable learned it just a few months ago: https://github.com/darktable-org/darktable/issues/9370 . The same for LibRaw: https://github.com/LibRaw/LibRaw/commit/2a9a4de21ea7f5d15314da8ee5f27feebf239655

RAW-Files form my Olympus _EM-10 Mark III_ are rendered as expected, so I do not suspect a general issue with my installation.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

This can also be reproduced with the RAW-files currently hosted in the [raw.pixls.us](https://raw.pixls.us/#repo) -repo. Search for `GH5 M2`, download one of the images, put it into the `Originals` -folder and start a new scan.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

PhotoPrism® CE Build 230923-e59851350

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

`mariadb:10.11`

(c) Operating System Types & Versions: Linux, Windows, Android,...

Host: `Debian 11 Bullseye`

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...

Firefox 102.15.0esr on Debian 11

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

Ad Blocker and other Plugins int the Browser present,  but this should not be the issue here.

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

`AMD Ryzen 3 5300U with Radeon Graphics` as hypervisor. Photoprism running inside a `libvirt` guest.

(b) Physical Memory & Swap Space in GB

6GB physical memory, 20GB swap

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

Everything on a `qcow`-image on SSD storage.

(d) Anything else that might be helpful to know?

_nothing else_

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No, testing with direct access to the exposed port form the docker container.

**Comment by lastzero** [comment]
Seems like an upstream problem, so this is the same as:
- https://github.com/photoprism/photoprism/issues/3741

Correct? I'd prefer to have just one issue open for the task.

**Comment by SmithChart** [comment]
The camera should be supported in Darktable 4.4.

I understand correctly that photoprism internally uses Darktable for the conversion? So if my assumption is correct this issue is a duplicate.

**Comment by lastzero** [comment]
Yes, we currently use 4.2 which comes with the Ubuntu base image.

**Comment by SmithChart** [comment]
Thanks for the help!

I'll close this issue and track https://github.com/photoprism/photoprism/issues/3741 for progess.
