### ISSUE TITLE
Iphone 12 HEIC files imported as static image instead as moving picture.

### ISSUE THREAD

**Issue by TheDukeSr** [photoprism/photoprism#3788]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------
My 1st debug post, so I hope i'll do it correct ;)

#### 1. .HEIC not imported as moving picture.

several .heic iphone12 files tested on import and upload option.
Tested on the Demo page also with several files (demo page also imported as static pictures).
The heic files are converted and stacked, but indexed as static jpg images.

#### 2. How can we reproduce it?

1. Go to 'Library'
2. Click on 'Index/Start'
3. Scroll down to 'select Only a test folder with new .heic files'
4. See error: No error (see attached debug log).

When reporting an import, indexing, or performance issue, please include the number and type of pictures in your library, as well as any configuration options you have changed, such as for thumbnail quality.

#### 3. What behavior do you expect?
I expected to see a moving picture indexed in Videos/Live Photos

#### 4. What could be the cause of your problem?
No idea, the .heic files display correct in a local program.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
Debug log: https://servirex.nl/photoprism/Photoprism-debug-heic-files.txt
Testfile1: https://servirex.nl/photoprism/20220714_131428338_iOS.heic
Testfile2: https://servirex.nl/photoprism/20220714_141408534_iOS.heic

#### 6. Which software versions do you use?

(a) Build [230923-e59851350]

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
mariadb:10.11
Docker 20.10.23 on linux, amd64

(c) Operating System Types & Versions: Linux, Windows, Android,...
Intel Gemini Lake Celeron J4105 Quad core
16GB Ram
4x NVME 1TB SSD cache and Boot.

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
iPhone 12

#### 7. On what kind of device is PhotoPrism installed?
Nas: Asus Nimbustor 5400T

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...
Docker 20.10.23 on linux, amd64
Intel Gemini Lake Celeron J4105 Quad core

(b) Physical Memory & Swap Space in GB
16GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...
4x NVME 1TB SSD cache and Boot.

(d) Anything else that might be helpful to know?
DB and Photoprism Installed by the Asustor App Central app.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
Reverse Proxy

**Comment by lastzero** [comment]
Live Photos consist of a JPEG/HEIC image **and** a QuickTime AVC/HEVC video, which are both required for viewing, see https://github.com/photoprism/photoprism/blob/develop/pkg/live/README.md.

**Comment by TheDukeSr** [comment]
> Live Photos consist of a JPEG/HEIC image **and** a QuickTime AVC/HEVC video, which are both required for viewing, see https://github.com/photoprism/photoprism/blob/develop/pkg/live/README.md.

ah ok thnx, i believed they where both in the heic file.

Info Samsung: Quote 
> "Motion Photos are JPEG/HEIC image with a short MP4 video embedded after the image data"

So Samsung is just 1 file?

For Iphone:
So how to upload iPhone files? Upload (or put in originals folder) both picture and movie files at the same time?

Sorry i ask, but cant seem to find info about adding these files to photoprism anywhere on site.
A little extra info on how to add these "heic" files would be appreciated.

**Comment by lastzero** [comment]
We use the PhotoSync app for this. I don't think Live Photos work with the Web upload, especially if you can't see both files. If there's a hack then I don't know it...

**Comment by lastzero** [comment]
I've updated the docs in our Develop Guide to explicitly mention this:
- https://docs.photoprism.app/developer-guide/media/live/#apple-iphone-and-ipad

**Comment by TheDukeSr** [comment]
> We use the PhotoSync app for this. I don't think Live Photos work with the Web upload, especially if you can't see both files. If there's a hack then I don't know it...

I placed several HEIC files together with some MOV files in a Originals folder.
When pressed "Start" suddenly 2 out of 10 got imported as Live Photo. ;)

Also uploaded 1 ".jpg" file from Samsung Galaxy S10 shot at "Moving Foto" mode.
This jpg file is also correctly imported as "Live Photo" and displayes as expected.

So for Samsung Galaxy you only need 1 jpg file.
For Iphone you need 1 Mov and 1 HEIC file.

Iphone info:
I'm sure not all IPhone files where imported as Live Photo because some Mov's i imported might not had a reference to a HEIC file.
All my HEIC and MOV files are in 1 huge folder with random names I got from someone else to test out, so besides that personal challenge to find the correct HEIC linked to a MOV it did work and is not a photoprism problem. 

So both Samsung and Iphone worked on a browser using Index/Start !

Thanks for your time and explanation.
