### ISSUE TITLE
Photoprism build is broken on fedora 38

### ISSUE THREAD

**Issue by tback** [photoprism/photoprism#3789]
#### 1. What is not working as documented?

I'm trying to build photoprism locally on an amd64 machine running fedora38. 
I want to run `make ...` and get some building done.
make hangs and doesn't produce any output by default.

#### 2. How can we reproduce it?

1. Get a clean checkout of photoprism/photoprism.
2. Switch to the directory you just cloned.
3. Run `make help`
4. Make will hang.
5. Now cancel the process `^C`.
6. Run `make help --debug=verbose`
```
$ make help --debug=verbose
GNU Make 4.4.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Reading makefile '.env' (search path) (don't care) (no ~ expansion)...
Makefile:20: not recursively expanding BUILD_OS to export to shell function
Makefile:20: not recursively expanding BUILD_OS to export to shell function
Makefile:18: not recursively expanding BUILD_VERSION to export to shell function
Makefile:20: not recursively expanding BUILD_OS to export to shell function
Makefile:18: not recursively expanding BUILD_VERSION to export to shell function
Makefile:19: not recursively expanding BUILD_TAG to export to shell function
Makefile:20: not recursively expanding BUILD_OS to export to shell function
Makefile:18: not recursively expanding BUILD_VERSION to export to shell function
Makefile:19: not recursively expanding BUILD_TAG to export to shell function
Makefile:26: not recursively expanding DESTDIR to export to shell function
Makefile:17: not recursively expanding BUILD_DATE to export to shell function
Makefile:20: not recursively expanding BUILD_OS to export to shell function
Makefile:18: not recursively expanding BUILD_VERSION to export to shell function
Makefile:19: not recursively expanding BUILD_TAG to export to shell function
Makefile:26: not recursively expanding DESTDIR to export to shell function
Makefile:17: not recursively expanding BUILD_DATE to export to shell function
Makefile:21: not recursively expanding BUILD_ARCH to export to shell function
...
```

Now checkout the last version that shows the desired behavior:
1. Checkout the revision before 3b55977f881718e8fc654fab9596b764105bf806: `git checkout 6654ec7786e3181cf8daf9fe1f1d90d0920a7e5b`
2. Run `make help`
```
make help
which: no richgo in (/home/tback/.local/bin:/home/tback/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
For build instructions, visit <https://docs.photoprism.app/developer-guide/>.
```

This is the desired behavior in my case. I didn't install richgo yet.
It seems removing the `export` from [Line 9 of the Makefile](https://github.com/photoprism/photoprism/blob/fd19bc0a5c8f58a119c0572cc434d0fc5e9ed05c/Makefile#L9) fixes this, but neither do I know the consequences of this change, nor do I know the rationale for having it there.

I think all revisions from fd19bc0a5c8f58a119c0572cc434d0fc5e9ed05c to 3b55977f881718e8fc654fab9596b764105bf806 show this bevior.

**Comment by lastzero** [comment]
Note that this is not a bug, as we do not guarantee that you will be able to build the software in any environment. For questions regarding our free community edition, please use GitHub Discussions. Thank you! :heart:
