### ISSUE TITLE
[doc] PNG not supported?

### ISSUE THREAD

**Issue by PicoJr** [photoprism/photoprism#38]
It seems `PNG` pictures are not supported yet?

I tried to import `PNG` pictures (didn't work), `JPG/JPEG` OK

If PNG are not supported yet, it could be worth adding it to the setup documentation ?

<https://docs.photoprism.org/en/latest/setup/>

Great project btw :)

**Comment by ScreamingTaco** [comment]
@lastzero can correct me if I’m wrong here, but from what I saw when I was working with `/internal/commands` the only conversion option was RAW to JPEG. Tbf, I haven’t seen much of the codebase outside the internal directory.

**Comment by lastzero** [comment]
PhotoPrism is a photo software and PNGs are usually used for screenshots etc, not photos... also doesn't contain EXIF information for indexing, unlike JPEG, TIFF or RAW:

https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg/24916466

So why add support for PNGs or GIFs? What is the use case?

**Comment by PicoJr** [comment]
@lastzero Ok I understand, thanks for your answer, I feel my question is not relevant anymore, I'm closing this.

**Comment by lastzero** [comment]
It's done, enjoy.
