### ISSUE TITLE
Geocoding doesn't recognize country

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#380]
For some reason, photos with GPS coordinates in Amsterdam are recognized with the correct city, but with an `Unknown` country. Thus, they are shown in the right place on the map, but nothing in the Netherlands shows up as a "State" for me.

For other cities, it works as expected.

**Comment by lastzero** [comment]
Thanks for reporting this! Can you provide us with (non-personal) example images for debugging?

You're welcome to attach them to this ticket or send them privately via email to hello@photoprism.org

**Comment by lastzero** [comment]
Was an issue in our geolocation backend. Updating it right now. Need to clear the cache as well and then we need a way to fix incorrect information in single PhotoPrism instances. There is no easy way to do that yet.

**Comment by fdw** [comment]
Thank you :)


> There is no easy way to do that yet.

Yeah, I guess I will need to delete all images and import them again?

**Comment by lastzero** [comment]
Yes, after the server cache is cleared. Not sure when exactly I'll get to that. If you modify the database manually anyways, you can change the country column in the places table to "nl" as a workaround. For updating all location data, it should work to delete all rows from locations and places (untested).

**Comment by lastzero** [comment]
Seems to work now 🥳

<img width="376" alt="Screenshot 2020-07-12 at 05 52 27" src="https://user-images.githubusercontent.com/301686/87238554-002bb880-c404-11ea-8041-399efd072f38.png">

When pulling our latest Docker image, you should reindex - or better start with a fresh database.

**Comment by fdw** [comment]
I did start with a fresh database and imported everything from scratch. Working perfectly now, thanks :)
