### ISSUE TITLE
Delete WebDav files after import

### ISSUE THREAD

**Issue by ZoXx** [photoprism/photoprism#3804]
hello all,

I import images via webdav, but they are not deleted after importing from this folder. In the settings this is set, but all images still remain available in the webdav folder. how can this be prevented? i am on the latest stable release via docker.

**Comment by graciousgrey** [comment]
What settings exactly do you mean with:

> In the settings this is set 

?

If you want files to be removed from the import folder after importing "move files" must be selected on the [import page](https://docs.photoprism.app/user-guide/library/import/#when-should-move-files-be-selected).

I just tested this, and it works as expected. 

Also make sure that you have not mounted the import folder as read only.

**Comment by ZoXx** [comment]
Sorry for late respond.

settings - general - delete (permanently remove files to free up storage) and "move files" is selected too.

Mounts are writeable.

**Comment by graciousgrey** [comment]
If "move files" is selected and PhotoPrism has the correct permissions, it should work. Are you using our official Docker image and do you have our latest version installed? You may also find hints as to why it's not working if you look at the logs when importing files. Make sure you enable debug or trace logs first.

https://docs.photoprism.app/getting-started/troubleshooting/logs/

**Comment by ZoXx** [comment]
Iam using the latest unraid version "app". It is still latest.

Yesterday i tried again. No error, no debug logs. WebDav content is still there.

**Comment by graciousgrey** [comment]
What version string do you see on the settings page?

You have turned on debug logs, put files into the configured import folder, clicked import on the web ui - and there are no logs at all? There should at least be some INFO logs.

**Comment by ZoXx** [comment]
Build [231011-63f708417]

Only the message: Nothing to see here yet.

**Comment by graciousgrey** [comment]
Can you access the [docker logs](https://docs.photoprism.app/getting-started/troubleshooting/logs/#__tabbed_1_3) in a terminal on unraid?  Otherwise, you can try the same thing and open the logs page in a second window, so that you have one browser tab where you click Import, and a second one where you can view the logs at the same time.

**Comment by ZoXx** [comment]
time="2023-10-13T09:59:29+02:00" level=debug msg="server: GET /api/v1/albums/as2fdrw2rku1mci3/t/1mnbkycw/tile_500 (200) [40.019284ms]"
time="2023-10-13T09:59:29+02:00" level=debug msg="server: GET /api/v1/albums/as27cmi2hhgiz3v2/t/1mnbkycw/tile_500 (200) [41.032643ms]"
time="2023-10-13T09:59:29+02:00" level=debug msg="photos: found 1 result for s:as27cmij8mso8arj filter:\"public:true country:de year:2022\" public:true dist:2.000000 country:de year:2022 count:1 order:relevance [19.278918ms]"
time="2023-10-13T09:59:29+02:00" level=debug msg="cached album-cover:as27cmij8mso8arj:tile_500 [45.152455ms]"
time="2023-10-13T09:59:29+02:00" level=debug msg="server: GET /api/v1/albums/as27cmij8mso8arj/t/1mnbkycw/tile_500 (200) [45.9265ms]"
time="2023-10-13T09:59:31+02:00" level=debug msg="albums: found 3 results [1.248504ms]"
time="2023-10-13T09:59:31+02:00" level=debug msg="server: GET /api/v1/albums?count=24&offset=0&q=&category=&order=newest&year=&type=month (200) [1.373704ms]"
time="2023-10-13T09:59:31+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.253µs]"
time="2023-10-13T09:59:34+02:00" level=debug msg="albums: found 6 results [1.177318ms]"
time="2023-10-13T09:59:34+02:00" level=debug msg="server: GET /api/v1/albums?count=24&offset=0&q=&category=&order=place&year=&type=state (200) [1.296133ms]"
time="2023-10-13T09:59:35+02:00" level=debug msg="server: GET /api/v1/labels?count=24&offset=0&q=&all= (200) [1.276341ms]"
time="2023-10-13T09:59:36+02:00" level=debug msg="server: GET /api/v1/labels?count=24&offset=24&q=&all= (200) [517.989µs]"
time="2023-10-13T09:59:38+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.665µs]"
time="2023-10-13T09:59:39+02:00" level=debug msg="albums: found 3 results [877.569µs]"
time="2023-10-13T09:59:39+02:00" level=debug msg="server: GET /api/v1/albums?count=24&offset=0&q=&category=&order=name&year=&type=folder (200) [978.188µs]"
time="2023-10-13T09:59:45+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.718µs]"
time="2023-10-13T09:59:54+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.066µs]"
time="2023-10-13T10:00:00+02:00" level=debug msg="server: GET /api/v1/ws (400) [45.073µs]"
time="2023-10-13T10:00:06+02:00" level=debug msg="server: GET /api/v1/ws (400) [20.079µs]"
time="2023-10-13T10:00:12+02:00" level=debug msg="server: GET /api/v1/ws (400) [27.908µs]"
time="2023-10-13T10:00:18+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.34µs]"

**Comment by graciousgrey** [comment]
No messages (no matter at what log level) related to import when you click on import?

**Comment by ZoXx** [comment]
tried again with live log:
time="2023-10-13T10:16:01+02:00" level=debug msg="server: GET /api/v1/ws (400) [17.966µs]"
[GIN-debug] redirecting request 307: /api/v1/import/ --> /api/v1/import/
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 7 folders [3.510744ms]"
time="2023-10-13T10:16:05+02:00" level=debug msg="removed folder:import:true:false from cache"
time="2023-10-13T10:16:05+02:00" level=info msg="moving files from import"
time="2023-10-13T10:16:05+02:00" level=info msg="import: found no .ppignore file"
time="2023-10-13T10:16:05+02:00" level=info msg="import: imported 1 file"
time="2023-10-13T10:16:05+02:00" level=debug msg="moments: analyzing 417 photos and 12 videos, with threshold 9"
time="2023-10-13T10:16:05+02:00" level=debug msg="moments: 24 albums saved as yaml files"
time="2023-10-13T10:16:05+02:00" level=info msg="import completed in 0 s"
time="2023-10-13T10:16:05+02:00" level=debug msg="index: updating covers"
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 0 albums [316.115µs]"
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 7 folders [3.831751ms]"
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 4 months [4.018122ms]"
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 53 labels [25.926908ms]"
time="2023-10-13T10:16:05+02:00" level=debug msg="covers: updated 0 subjects [425.454µs]"
time="2023-10-13T10:16:05+02:00" level=debug msg="server: POST /api/v1/import/ (200) [125.724222ms]"
time="2023-10-13T10:16:11+02:00" level=debug msg="server: GET /api/v1/ws (400) [20.807µs]"
time="2023-10-13T10:16:20+02:00" level=debug msg="albums: found 0 results [1.02219ms]"
time="2023-10-13T10:16:20+02:00" level=debug msg="server: GET /api/v1/albums?count=24&offset=0&q=&category=&order=favorites&year=&type=album (200) [1.11851ms]"
time="2023-10-13T10:16:20+02:00" level=debug msg="server: GET /api/v1/ws (400) [20.057µs]"
time="2023-10-13T10:16:21+02:00" level=debug msg="server: GET /library/albums (200) [1.2295ms]"
time="2023-10-13T10:16:21+02:00" level=debug msg="server: GET /api/v1/session/32f566f188aa962bdcf25a5a262dd8b4aed385fd9a521e72 (200) [21.140072ms]"
time="2023-10-13T10:16:21+02:00" level=debug msg="server: GET /api/v1/config (200) [33.652416ms]"
time="2023-10-13T10:16:21+02:00" level=debug msg="albums: found 0 results [1.029816ms]"
time="2023-10-13T10:16:21+02:00" level=debug msg="server: GET /api/v1/albums?count=24&offset=0&q=&category=&order=favorites&year=&type=album (200) [1.129748ms]"
time="2023-10-13T10:16:21+02:00" level=debug msg="server: GET /manifest.json?1787fce2 (200) [58.985µs]"
time="2023-10-13T10:16:23+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.43µs]"
time="2023-10-13T10:16:23+02:00" level=debug msg="server: GET /sw.js (200) [180.747µs]"
time="2023-10-13T10:16:31+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.267µs]"
time="2023-10-13T10:16:39+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.832µs]"

**Comment by graciousgrey** [comment]
Mhh this looks like there have no files been imported at all. Do you see the files from the import folder in the PhotoPrism Web UI?

How did you configure the volumes import, originals and storage?

**Comment by ZoXx** [comment]
So it will be with the next release possible? :)

**Comment by ZoXx** [comment]
Yes. All files are there.

Container Path: /photoprism/storage = /mnt/user/appdata/photoprism/storage
Container Path: /photoprism/originals = /mnt/user/appdata/photoprism/originals
Container Path: /photoprism/import = /mnt/user/appdata/photoprism/import

**Comment by lastzero** [comment]
What file types (extensions) did you import? Can you provide us with some examples?

**Comment by ZoXx** [comment]
Mostly (.jpg) and some (.mp4)

**Comment by lastzero** [comment]
Your logs indeed don't show that anything got imported, neither copied or moved. Could you please send us logs where something is actually being imported and make sure you didn't accidentally upload to the originals folder instead of the import folder via WebDAV?

**Comment by ZoXx** [comment]
i only import through webdav. I dont import in originals or i dont upload via gui.

i put the images in the webdav folder, press the import button in photoprism and this is the associated log directly from the photoprism docker:
 
time="2023-10-13T20:01:54+02:00" level=debug msg="server: GET / (307) [50.682µs]"
time="2023-10-13T20:01:54+02:00" level=debug msg="server: GET /library/login (200) [2.935524ms]"
time="2023-10-13T20:01:54+02:00" level=debug msg="server: GET /api/v1/session/32f566f188aa962bdcf25a5a262dd8b4aed385fd9a521e72 (200) [36.775796ms]"
time="2023-10-13T20:01:54+02:00" level=debug msg="server: GET /api/v1/config (200) [43.598183ms]"
time="2023-10-13T20:01:55+02:00" level=debug msg="server: GET /static/build/2d8017489da689caedc1.woff2 (304) [83.263µs]"
time="2023-10-13T20:01:55+02:00" level=debug msg="photos: found 120 results for public:true dist:2.000000 year:0 month:0 quality:3 camera:0 lens:0 count:120 order:newest merged:true [19.577243ms]"
time="2023-10-13T20:01:55+02:00" level=debug msg="server: GET /api/v1/photos?count=120&offset=0&merged=true&country=&camera=0&lens=0&label=&latlng=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [109.189061ms]"
time="2023-10-13T20:01:55+02:00" level=debug msg="photos: found 120 results for public:true dist:2.000000 year:0 month:0 quality:3 camera:0 lens:0 count:120 offset:120 order:newest merged:true [19.196604ms]"
time="2023-10-13T20:01:55+02:00" level=debug msg="server: GET /api/v1/photos?count=120&offset=120&merged=true&country=&camera=0&lens=0&label=&latlng=&year=0&month=0&color=&order=newest&q=&public=true&quality=3 (200) [84.07882ms]"
time="2023-10-13T20:01:57+02:00" level=debug msg="server: GET /sw.js (200) [3.861534ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /manifest.json?1787fce2 (200) [355.946µs]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/ws (400) [35.643µs]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/ca34ac40e45c430b575409c889c994b9c93a27cb/1mnbkycw/tile_224 (200) [1.909686ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/83c0322b30af06c09ff5494ab64d044830cfda33/1mnbkycw/tile_224 (200) [3.369749ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/596f5c314b08fd48361754deb787bef7395e6364/1mnbkycw/tile_224 (200) [7.751458ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/67d6137e3d8746c6cf9b529a1a21dcdd0a5dbb29/1mnbkycw/tile_224 (200) [2.53075ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/e73c8d7a7621665cf19c536ea41119b6e6157dd5/1mnbkycw/tile_224 (200) [5.214213ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/f681c5d4993e2718ec4274d1bddfb064ecc7f02d/1mnbkycw/tile_224 (200) [5.280536ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/2b08f1cba507c9506a6fc99d5ec54bb1e828d611/1mnbkycw/tile_224 (200) [8.317115ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/ea674620db422e7e4f2b8e755b5982e335d17c9c/1mnbkycw/tile_224 (200) [8.355789ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/eb8df7f60bb0ac22189218cfc440402dbc989431/1mnbkycw/tile_224 (200) [4.013615ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/34c90601c14ab0381b999fca3cebf14727d4abbb/1mnbkycw/tile_224 (200) [5.599081ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/19744cea708141cd5b346d0e647c78db4b88a7aa/1mnbkycw/tile_224 (200) [6.992793ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/805a57a41b5e33ed157a166b66ad9ffaf675a7d8/1mnbkycw/tile_224 (200) [22.160754ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/ac824a56f90ecf438654da478acb77c89e036fdd/1mnbkycw/tile_224 (200) [14.421506ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/9f400b8f008223fe7d62b5e4670d10aaf30ec6a0/1mnbkycw/tile_224 (200) [15.569319ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/a056561d59dbf420a1ebce8fbd7ebe674d214fc0/1mnbkycw/tile_224 (200) [17.163771ms]"
time="2023-10-13T20:02:06+02:00" level=debug msg="server: GET /api/v1/t/a3ac279e5ad708dc1b91733cc61a5f435f338203/1mnbkycw/tile_224 (200) [18.778889ms]"
time="2023-10-13T20:02:11+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.006µs]"
time="2023-10-13T20:02:16+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.221µs]"
time="2023-10-13T20:02:21+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.59µs]"
[GIN-debug] redirecting request 307: /api/v1/import/ --> /api/v1/import/
time="2023-10-13T20:02:23+02:00" level=debug msg="covers: updated 8 folders [4.441329ms]"
time="2023-10-13T20:02:23+02:00" level=debug msg="removed folder:import:true:false from cache"
time="2023-10-13T20:02:23+02:00" level=info msg="moving files from import"
time="2023-10-13T20:02:23+02:00" level=info msg="classify: loading nasnet"
time="2023-10-13T20:02:26+02:00" level=debug msg="server: GET /api/v1/ws (400) [19.336µs]"
time="2023-10-13T20:02:26+02:00" level=info msg="classify: loading labels from labels.txt"
time="2023-10-13T20:02:26+02:00" level=info msg="import: found no .ppignore file"
time="2023-10-13T20:02:26+02:00" level=info msg="import: imported 1 file"
time="2023-10-13T20:02:26+02:00" level=debug msg="moments: analyzing 431 photos and 14 videos, with threshold 9"
time="2023-10-13T20:02:27+02:00" level=debug msg="moments: 28 albums saved as yaml files"
time="2023-10-13T20:02:27+02:00" level=info msg="import completed in 3 s"
time="2023-10-13T20:02:27+02:00" level=debug msg="index: updating covers"
time="2023-10-13T20:02:27+02:00" level=debug msg="covers: updated 0 albums [371.575µs]"
time="2023-10-13T20:02:27+02:00" level=debug msg="covers: updated 8 folders [4.847669ms]"
time="2023-10-13T20:02:27+02:00" level=debug msg="covers: updated 6 months [3.877013ms]"
time="2023-10-13T20:02:27+02:00" level=debug msg="covers: updated 53 labels [23.928318ms]"
time="2023-10-13T20:02:27+02:00" level=debug msg="covers: updated 0 subjects [423.089µs]"
time="2023-10-13T20:02:27+02:00" level=debug msg="server: POST /api/v1/import/ (200) [3.671853676s]"
time="2023-10-13T20:02:31+02:00" level=debug msg="server: GET /api/v1/ws (400) [18.809µs]"

**Comment by ZoXx** [comment]
after that i hit indexing and photos are there

**Comment by graciousgrey** [comment]
What url do you use for webdav? And in what folder exactly do you see the files on your server?

**Comment by ZoXx** [comment]
**What url do you use for webdav?**
https://XXX.XXX.de/remote.php/dav/files/XXX
-> then I selected the folder from which to import

**And in what folder exactly do you see the files on your server?**
/mnt/user/appdata/photoprism/originals/Photoprism-Import
here the folders (if I imported folders with images) are displayed and the files which were imported without folder

**Comment by graciousgrey** [comment]
So the import folder: /mnt/user/appdata/photoprism/import is empty?

If you want to use our [import feature](https://docs.photoprism.app/user-guide/library/#importing-files) you need to use webdav to move files to the configured import folder. Which in your case is:

Container Path: /photoprism/import = /mnt/user/appdata/photoprism/import

Can you confirm that after you move files with webdav those files are in this folder? 

Otherwise if you use webdav to move files to a folder that is located within the originals folder e.g., 

/mnt/user/appdata/photoprism/originals/Photoprism-Import

files will be [indexed instead of imported](https://docs.photoprism.app/user-guide/library/#indexing-originals).

**Comment by ZoXx** [comment]
Good morning everyone,

my mistake! i bvin assumed that through the webdav order, the data will be imported automatically.

I have rebuilt the system and only worked with the import folder, it now runs flawlessly!!!!

**Comment by ZoXx** [comment]
Good morning everyone,

my mistake! I assumed that through the webdav order, the data is imported automatically.

I have rebuilt the system and only worked with the import folder, it now runs flawlessly!!!!

**Comment by lastzero** [comment]
@ZoXx Glad you got it working now!
