### ISSUE TITLE
People: Improvement of the face:new feature

### ISSUE THREAD

**Issue by kingvuke** [photoprism/photoprism#3805]
As a user, I would like to see all new faces (face:new) on one page.
The faces should be sorted by similarity.
I can select a couple of faces, and assign to the person.

See as example https://docs.digikam.org/en/_images/mainwindow_faces_tag_assigned_iconview.webp

**Comment by graciousgrey** [comment]
I'll convert this into a discussion as it duplicates some existing feature requests. Feel free to add a :+1:  to those :)

- https://github.com/photoprism/photoprism/issues/1601
- https://github.com/photoprism/photoprism/issues/1679
- https://github.com/photoprism/photoprism/issues/1595
