### ISSUE TITLE
<!-- Thanks for reporting issues of Telegram Messenger for iOS!

### ISSUE THREAD

**Issue by Reymont30** [photoprism/photoprism#3807]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Half of the time after I tap with my finger on the send button, the on-screen keyboard is minimized instead of the message being sent. 

### Expected Behavior
The message must be sent.

### Actual Behavior
The message is not sent, only the on-screen keyboard is minimized. 

### Steps to Reproduce
1. Type a message
2. Press the send button (maybe slightly outside of it which isn't difficult taking in mind how small it is)

### Environment
**Device:** `iPhone 13 Pro Max`

**iOS version**: `17.0.3`

**App version:** `10.1.2`

_Originally posted by @ekumanov in https://github.com/TelegramMessenger/Telegram-iOS/issues/1237_

**Comment by graciousgrey** [comment]
This does not seem to be related to PhotoPrism?
