### ISSUE TITLE
ffmpeg options are possibly in wrong section in docs

### ISSUE THREAD

**Issue by tmzhuang** [photoprism/photoprism#3812]
https://docs.photoprism.app/getting-started/config-files/#database-connection
![image](https://github.com/photoprism/photoprism/assets/1159725/a3df2c50-ee81-4c01-b585-abd114437c19)

Minor docs issue but I believe the ffmpeg options should be in its own "transcoding" section of the docs perhaps.

**Comment by lastzero** [comment]
Thanks! This has been fixed in our docs.
