### ISSUE TITLE
Searching for specific keyword does not show expected results

### ISSUE THREAD

**Issue by kumarunster** [photoprism/photoprism#3815]
Just started testing photoprism on my photo library. The Library has more than 60.000 pictures and more than 3.000 videos.

Search for some keywords seems not to work properly: the results do not correspondent with expectation. I'm trying to find and delete some unneeded images, like screenshots done on mobile phones, and found following issue.

#### 1. What is not working as documented?

I have hundreds of images, correctly recognized as screenshot. Keyword section on each such picture lists screenshot as a keyword.

Searching for the word "screenshot" delivers only a small subset of apprx. 9 results and does not show any of screenshot pictures, which I can find manually, which I can find during just random navigation on photo library.

#### 2. How can we reproduce it?

not sure if you can reproduce it.

#### 3. What behavior do you expect?

keyword search should work and deliver all images, containing at least the exact keyword.

#### 4. What could be the cause of your problem?

I dont know about the realization of search here, it depends on it. Maybe the database search index is not in sync with the library. It seems for me, that the search is realized via a some complex SQL statement. 

I would like to debug the real database query, which seems is built here:
https://github.com/photoprism/photoprism/blob/63f708417dff4511da1003c81962e5955713368a/internal/search/photos.go#L725C11-L725C11

Is it possible to print the querie as debug/trace message?

Or any suggestion, what can be done here?

**Comment by lastzero** [comment]
Might be because those are stopwords or because the words exist as labels so only the pictures assigned to these labels are shown?

**Comment by lastzero** [comment]
For the list of stopwords ignored when indexing/searching text, see https://github.com/photoprism/photoprism/blob/develop/pkg/txt/resources/stopwords.txt

**Comment by kumarunster** [comment]
thanks for your quick reply. I think it is not related to stopword. The search in my case seems to be not consistent.

attached a small screencast with a demo. I've found a specific file, which is clearly a screenshot, it has all keywords and even search for id, hash does not work for that file...

https://github.com/photoprism/photoprism/assets/2104820/ff3f0e54-78fc-4ed4-b41c-2385008ac4a8

to debug the real database query would be good here I think.
used database is mariadb:10.11, as per the docker-compose file, downloaded on installation instruction.

**Comment by lastzero** [comment]
Screenshot exists as a label, but all pictures with screenshot as a keyword should be assigned to that label - meaning it shouldn't make a difference, unless maybe you combine it with other keywords in your search.

**Comment by kumarunster** [comment]
as per screencast even search for unique ids does not work here. the image in question does not have label "screenshot" assigned", it has "portrait" and "info"
any possibility to see exact query which runs against database?

**Comment by graciousgrey** [comment]
Screenshots should be displayed in the Review section because they are not photographic content.(https://docs.photoprism.app/user-guide/organize/review/). Photos that are in review will not show up in normal searches unless you approve them or disable the review feature. 
You can easily find out if this is the case for you by searching for `screenshot quality:0`, because then you will also see photos that are in review.

**Comment by kumarunster** [comment]
@graciousgrey @lastzero many thanks! that explains now the behavior for me! Great feature :)
closing then that one and sorry for opening the issue, which turned out as a feature instead of bug :)
