### ISSUE TITLE
Apply tags or set dates to selection / multiple photos at once

### ISSUE THREAD

**Issue by GitTworn** [photoprism/photoprism#3829]
**Describe what problem this solves and why this would be valuable to many users**

When indexing/importing my large amount of old photos, I noticed that a lot of photos did not have dates. I would like to apply a year to multiple photos at once. The same goes for tags.

**Describe the solution you'd like**

When selecting multiple photos and hitting the edit button, a window pops up where I can edit things like tags and dates however, it only applies it to the first image in the selection. You need to use the arrows on the top right side of the screen to navigate to the next image in the selection and re-enter the information and apply again. It would be nice to be able to apply tags and dates to the entire selection at once.

**Describe alternatives you've considered**

None

**Comment by graciousgrey** [comment]
Thank you very much for your feedback!

The functionality you describe will be part of

- https://github.com/photoprism/photoprism/issues/271

:)
