### ISSUE TITLE
Support triggering the lightbox from the Places view.

### ISSUE THREAD

**Issue by jimmcslim** [photoprism/photoprism#384]
Doesn't appear to be able to trigger the lightbox from the Places view.

At the moment, double clicking on a marker on the map, e.g. Europe with 100 photos, zooms into a lower-level, e.g. Germany with 50 photos, and France with 50 photos. This is handy, but would also be good if it were possible to launch the lightbox into a view of all the photos that are 'selected' by the region indicated by the marker, just not sure how to preserve the double-click to zoom functionality - maybe have a pop-out on hover that takes you to the lightbox if clicked?

**Comment by lastzero** [comment]
Thanks! For performance reasons, we have less data in this view. Need to make it work with fuzzy dates.

**Comment by lastzero** [comment]
You can test this as soon as new Docker images have been pushed, max 2 hours.

**Comment by jimmcslim** [comment]
I've just pulled the latest image but I don't see any additional UI elements that provide an affordance for launching the lightbox from a map marker? Clicking (or double clicking) a marker just seems to zoom further into the map, which I think is valuable behaviour, but would like to be able to open the lightbox for the one or many photos that the marker represents.

**Comment by jimmcslim** [comment]
Ah, my apologies. I thought that `docker-compose pull` would be sufficient to upgrade my stack, but I had to `down` and `up`... not just `up` on a stopped stack. Anyway, I have tested this and I see that it is working... clicking on a marker that encapsulates multiple photos zooms in, and when you are at the level of single photos, clicking on the marker takes you to that photo. Excellent!

As a post-MVP feature, I think it would be great if there was still some pop-out affordance when a map marker summarises multiple photos if you could go to a lightbox view that would load only those photos in that area.

**Comment by lastzero** [comment]
You can use the search field to limit results (also in the lightbox) to a country, city, or other keyword.
