### ISSUE TITLE
stack multiple takes of a scene

### ISSUE THREAD

**Issue by gertjanvanzwieten** [photoprism/photoprism#3841]
**Describe what problem this solves and why this would be valuable to many users**

I often take a few photos of a scene so that I can select my favorite later. I might not always get to this pruning step, though, so the many near duplicates end up forming awkward clusters in the timeline view.

**Describe the solution you'd like**

The stacking concept already in place is currently limited to exact duplicates and edits. I would love to see this optionally relaxed by making the temporal and spatial identification windows configurable. Ideally this is paired with the ability to select a favourite to represent the stack, and the ability to break up stacks that were wrongly identified by the heuristic.

**Describe alternatives you've considered**

I could not think of another way to deal with the situation of near duplicates but I imagine it to be a fairly common problem, so I would be happy to learn of a different solution if it exists.

**Comment by graciousgrey** [comment]
Thank you very much for your feedback!

> The stacking concept already in place is currently limited to exact duplicates and edits. I would love to see this optionally relaxed by making the temporal and spatial identification windows configurable.

We do have a very similar feature request:
- https://github.com/photoprism/photoprism/issues/1446

It might also make sense to add an option to stack by "time" & "camera" in addition to "time" & "place".

> Ideally this is paired with the ability to select a favourite to represent the stack

You can choose the primary file of a stack as described [here](https://docs.photoprism.app/user-guide/organize/stacks/#change-primary-files)

> the ability to break up stacks that were wrongly identified by the heuristic

[Unstacking files one by one is already possible](https://docs.photoprism.app/user-guide/organize/stacks/#unstack-files). Unstacking all files of a stack at once is planned:

- https://github.com/photoprism/photoprism/issues/667

**Comment by gertjanvanzwieten** [comment]
Thanks for the pointers and suggestions, yes "time & camera" would be excellent if time can be configurable. And indeed #1446 covers the ground already, apologies for failing to find it. I will close my issue in favour of that one.

Edit to add: thanks for photoprism! I like it quite a bit.
