### ISSUE TITLE
Geocoding: Incorrect location details for some coordinates

### ISSUE THREAD

**Issue by santiagoGPNC** [photoprism/photoprism#3849]
#### 1. What is not working as documented?

I have several photos taken by an iPhone in the city of Toulouse, France. They have the GPS coordinates in their metadata.
When processed by photoprism reverse geocoding service, photoprism tagged them as being shot in Florida US. 
Here are some coordinates and the locations they were resolved to:

- 43.59979, 1.4490111 -> Cape Coral, Florida
- 43.604378, 1.4436444 -> Medley Florida
- 43.604378, 1.44365 -> Medley Florida

Curiously, some photos very nearby well tagged correctly. eg.
43.59978, 1.4504528  (Next to the one tagged as Cape Coral) was tagged in Toulouse, 
43.604107, 1.4438833 (Next to the one tagged in Medley) was tagged Properly in Toulouse

#### 2. How can we reproduce it?

Have a picture with GPS in the provided coordinates. When scanned, they will appear as identified in Florida

#### 3. What behavior do you expect?

They should be tagged with their proper location in Toulouse.

#### 4. What could be the cause of your problem?

According to [this discussion](https://github.com/photoprism/photoprism/discussions/3848#discussioncomment-7402612) , The problem is probably in the reverse geocoding service

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

`photoprism_1  | time="2023-10-27T12:39:44Z" level=info msg="1 files uploaded in 0 s"
photoprism_1  | time="2023-10-27T12:39:44Z" level=info msg="processing upload..."
photoprism_1  | time="2023-10-27T12:39:44Z" level=info msg="classify: loading nasnet"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="classify: loading labels from labels.txt"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="import: found no .ppignore file"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="import: added folder /photoprism/storage/users/us36ttr1xacs3kwq/upload/sess90kjx4xrwoae6s"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="media: IMG_5081.HEIC was taken at 2022-08-21 08:05:09 +0000 UTC (meta)"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="folder: added album 'August 2022' (path:2022/08 public:true)"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="import: created folder /2022/08"
photoprism_1  | time="2023-10-27T12:39:48Z" level=info msg="import: moving main heic file IMG_5081.HEIC to 2022/08/20220821_080509_B2D0FEAB.heic"
photoprism_1  | time="2023-10-27T12:39:49Z" level=info msg="convert: converting 20220821_080509_B2D0FEAB.heic to 20220821_080509_B2D0FEAB.heic.jpg (heif-convert)"
photoprism_1  | time="2023-10-27T12:39:49Z" level=info msg="convert: 20220821_080509_B2D0FEAB.heic.jpg created in 581.880217ms (heif-convert)"
photoprism_1  | time="2023-10-27T12:39:51Z" level=info msg="media: created 11 thumbnails for 2022/08/20220821_080509_B2D0FEAB.heic.jpg [1.707995083s]"
photoprism_1  | time="2023-10-27T12:39:51Z" level=info msg="index: 2022/08/20220821_080509_B2D0FEAB.heic has document_id f4df759c-0c55-44c5-be4b-6c5a54cbda0d"
photoprism_1  | time="2023-10-27T12:39:51Z" level=info msg="import: added main heic file 2022/08/20220821_080509_B2D0FEAB.heic"
photoprism_1  | time="2023-10-27T12:39:54Z" level=info msg="index: matched 2 labels with 20220821_080509_B2D0FEAB.heic.jpg [3.09924483s]"
photoprism_1  | time="2023-10-27T12:39:55Z" level=info msg="cell: added place us:paVY2eg1Qv6d [368.92138ms]"
photoprism_1  | time="2023-10-27T12:39:55Z" level=info msg="import: stacked related jpg file 2022/08/20220821_080509_B2D0FEAB.heic.jpg"
photoprism_1  | time="2023-10-27T12:39:55Z" level=info msg="upload: deleted empty folder /photoprism/storage/users/us36ttr1xacs3kwq/upload/sess90kjx4xrwoae6s"
photoprism_1  | time="2023-10-27T12:39:55Z" level=info msg="upload: imported 2 files"
photoprism_1  | time="2023-10-27T12:39:55Z" level=info msg="upload has been processed"`

I have a photo that can be used to reproduce the issue, but github does not allow HEIC files being attached, so Im attaching the output of exiftool for the file
[exif.txt](https://github.com/photoprism/photoprism/files/13189050/exif.txt)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 
photoprism CE, Build [231011-63f708417], running on a Docker Container

#### 7. On what kind of device is PhotoPrism installed?

Running on a Docker container on an Intel i5 5600T

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

N/A

**Comment by lastzero** [comment]
I have updated our geodata index to confirm that the issue was caused by the data we are using and should be resolved when we start using the new data in production.


**Before the update:**

![before](https://github.com/photoprism/photoprism/assets/301686/d2bc89b4-a3b5-4555-897c-9fe10a5af928)

**After the update:**

![after](https://github.com/photoprism/photoprism/assets/301686/f13d0ce3-e3ce-48c5-9c9f-6cd6d883948f)

**Comment by lastzero** [comment]
@santiagoGPNC Our backend services have been updated, so the issue should now be resolved. Thanks for reporting it!

Please note, though, that the data cached on your instance will not be updated automatically. As a member, you can run the `photoprism places update` command [in a terminal](https://docs.photoprism.app/getting-started/docker-compose/#command-line-interface) for this. Since updating all location data puts additional load on our backend, we unfortunately cannot offer this service without [asking for support](https://www.photoprism.app/editions#compare).

**Comment by per2jensen** [comment]
I have uploaded 20 Iphone photos and checked if they are placed correctly on the map, and they are :-).

I realize it is a small number of photos and that they are taken from the same general area,within a circle of ~15 km radius.

**Comment by santiagoGPNC** [comment]
hi.sorry. I totally missed this.
I readded a couple of those images and I think they do look good now. 
thank you very much!
