### ISSUE TITLE
Documentation for Moments... how are they created?

### ISSUE THREAD

**Issue by jimmcslim** [photoprism/photoprism#385]
Would be good to know from the documentation how the Moments are created; from my recent import of 19,000 photos it looks like primarily it is from the combination of location and year (so requires geotagged photos), but I also have some Moments that seem to be created by theme: 'Bays, Capes & Beaches', 'Botanical gardens', 'Nature & Landscape', 'Pets'.

**Comment by graciousgrey** [comment]
See https://docs.photoprism.org/user-guide/organize/moments/
