### ISSUE TITLE
.mp4 files imported with correct date/time based path but timestamp is missing

### ISSUE THREAD

**Issue by Leon99** [photoprism/photoprism#3850]
I put a bunch of .mp4 files into the import folder, pressed Import. Photoprism moved/renamed them according to the correct date/time (e.g. `2022/10/20221031_085546_3502C92D.mp4`). However, their date/time is missing from the metadata, and they are not shown in the calendar view.
Any ideas much appreciated.

**Comment by graciousgrey** [comment]
This may be the case if the files have only a modification date in their metadata and not the creation date. The modification date of a photo is not necessarily the date it was taken, so we don't set it as taken at date. To verify this, you can check the metadata of your files with exiftool.

`exiftool -j -n filename.mp4`

**Comment by graciousgrey** [comment]
I'm closing this issue as we have received no further feedback and it is expected that files that only have a modification date will not appear in the calendar view.
