### ISSUE TITLE
UX: Indicate if photo is stacked in lightbox view (fullscreen mode)

### ISSUE THREAD

**Issue by jimmcslim** [photoprism/photoprism#386]
Would be great if the lightbox view gave an indication if the current photo is the primary photo of a Stack, and then support drilling into the photos of the Stack (within the lightbox view - and clearly indicating that we are browsing the photos of the Stack), and the pop back out to the previous location in the collection that the lightbox view was at.

**Comment by lastzero** [comment]
Adding an icon is simple. However, there is one one lightbox instance, so opening a photo stack would remove existing images.

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: https://github.com/photoprism/photoprism/issues/1307
