### ISSUE TITLE
Setup: Provide tar.gz, deb and rpm installation packages

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3861]
**As a user who does not want to use Docker, I would like to have `tar.gz`, `deb` and `rpm` packages so that I can more easily install PhotoPrism on Ubuntu/Debian and Red Hat compatible Linux distributions.**

----

As an alternative to our Docker images, you can now use the *tar.gz* archives available at [**dl.photoprism.app/pkg/linux/**](https://dl.photoprism.app/pkg/linux/) to install PhotoPrism on compatible Linux distributions without building it from source:

- <https://dl.photoprism.app/pkg/linux/amd64.tar.gz>
- <https://dl.photoprism.app/pkg/linux/arm64.tar.gz>

Since these packages need to be set up manually and do not include the system dependencies required to make use of all the features, we recommend that only advanced users choose this installation method.

Also note that the minimum required glibc version is 2.35, so for example Ubuntu 22.04 and Debian Bookworm will work with these binaries, but older Linux distributions may not be compatible.

## Usage

You can download and install PhotoPrism in `/opt/photoprism` by running the following commands:

```
sudo mkdir -p /opt/photoprism
cd /opt/photoprism
wget -c https://dl.photoprism.app/pkg/linux/amd64.tar.gz -O - | sudo tar -xz
sudo ln -sf /opt/photoprism/bin/photoprism /usr/local/bin/photoprism
photoprism --version
```

If your server has an ARM-based CPU, make sure to install `arm64.tar.gz` instead of `amd64.tar.gz` when using the commands above. Both are linked to the latest available build.

## Documentation

- <https://github.com/photoprism/photoprism/blob/develop/setup/pkg/linux/README.md>
- <https://dl.photoprism.app/pkg/linux/README.html>

**Comment by lastzero** [comment]
We now also have `.deb` and `.rpm` packages available for testing on our download server at https://dl.photoprism.app/pkg/linux/:

![downloads](https://github.com/photoprism/photoprism/assets/301686/32ab0358-5e89-4260-a8e9-201650712fc6)

If we receive no problem reports, then I'll assume that these are working for everyone to install PhotoPrism in `/opt/photoprism` and add a symlink for the photoprism command binary from`/usr/local/bin/photoprism` - so basically what the commands in our tar.gz installation guide do when you run them:

- https://dl.photoprism.app/pkg/linux/README.html

*Just like with our tar.gz packages, the minimum required glibc version is 2.35, so for example Ubuntu 22.04 and Debian Bookworm will work with these binaries, but older Linux distributions may not be compatible.*

**Comment by Thovi98** [comment]
Thanks for those builds!
It will be handful for Yunohost.
We will soon migrate to Bookworm. Our Bookworm CI passes with your builds https://ci-apps-bookworm-dev.yunohost.org/ci/job/205 🎉

Do you think that it would be possible to add `armhf/armv7` builds as there are also `armv7` docker builds?

Thanks!

Ping @lastzero in case you didn't see my post :)

**Comment by lastzero** [comment]
@Thovi98 My apologies for not getting back to you sooner! Our currently available installation packages are built using the multi-arch develop image for AMD64/ARM64, while the ARMv7 version uses a stripped down image that only contains the minimal Docker build dependencies. So providing ARMv7 packages should be possible, but requires a bit more work and testing on our side. We will be happy to look into this after 2FA has been released. Any help is of course much appreciated.

Edit: One particular issue is that the ARMv7 develop image is based on the latest Ubuntu version, while the binaries in the installation packages should be built on an older distribution to avoid glibc compatibility problems. We currently only maintain the older distribution images for AMD64/ARM64, and it would be somewhat time consuming (though possible) to build and maintain them for ARMv7 as well.

**Comment by lastzero** [comment]
@Thovi98 I've created a follow-up issue for building ARMv7 packages:
- https://github.com/photoprism/photoprism/issues/4082

**Comment by lastzero** [comment]
@Thovi98 An ARMv7 installation package is now available for testing:
- https://dl.photoprism.app/pkg/linux/arm.tar.gz

Any help with this is much appreciated! :pray:

**Comment by Thovi98** [comment]
Waouh I'm impressed, thank you @lastzero!
I will update my PR for Yunohost and ask for some testing (as I myself don't own an ARMv7 hardware).

Congrats! 🎉

**Comment by ktecho** [comment]
Hi!

Latest version is not available in .deb format. Is it going to be available, or is that install method discontinued? Thanks!

**Comment by lastzero** [comment]
It is available at https://dl.photoprism.app/pkg/ - please make sure to read the README.html file before you use it.

**Comment by ktecho** [comment]
> It is available at https://dl.photoprism.app/pkg/ - please make sure to read the README.html file before you use it.

Thanks!!
