### ISSUE TITLE
Dynamic Previews unchecked after restart

### ISSUE THREAD

**Issue by Aisub** [photoprism/photoprism#3863]
![Untitled](https://github.com/photoprism/photoprism/assets/48910143/d5423c1c-010e-40f8-b3dd-14cb5e6434cb)

dynamic previews is turned off after a restart. I have to manually check the check box again to make it work.

**Comment by lastzero** [comment]
It can be that your config folder / file is not writable or that your hardware is not powerful enough for this. Unfortunately, you didn't use our bug report template. Please also make sure to check the server logs for any helpful information before reporting a bug.
