### ISSUE TITLE
Share links to single images

### ISSUE THREAD

**Issue by jdanna** [photoprism/photoprism#3878]
**Describe what problem this solves and why this would be valuable to many users**

Often times In a conversation or an email or a post, i’ll want to reference a single photo. Currently I have no way of pointing someone to a single photo besides making a temporary album dedicated to just that one photo

**Describe the solution you'd like**

Just like the share functionality in an album - individual photos could have a generate share link button, or it could be in the context menu up top when a photo is selected. Then you could make a link just like you do with albums.

**Describe alternatives you've considered**

Right now the only thing I can do is make a bunch of single-photo albums that are cumbersome and hard to manage.

**Comment by graciousgrey** [comment]
Thank you very much for your feedback :) This function is planned, I am closing this issue in favor of the existing one:
- https://github.com/photoprism/photoprism/issues/466
