### ISSUE TITLE
How To: Force update database with PhotoPrism\storage\sidecar\...\yml files ?

### ISSUE THREAD

**Issue by pbenaim** [photoprism/photoprism#3882]
Context:
- I use the Build 231021-9abea5b55 version with Docker Desktop under windows on one "little" server ( Beelink Mini S12 Pro )

- I'm be able to find many descriptions with AI ( LLava [https://github.com/haotian-liu/LLaVA](url) ) this is amazing but we need GPU with minimum 12 Go of memory, so I use it on my personnal computer (  i7 i7-12700KF and NVIDIA 3080 12Go ), so can't work on my PhotoPrism server... 👍 

- After generate Descriptions and Keyswords it's easy to modify all files in PhotoPrism\storage\sidecar\...\*.yml files ( with homemade software 👍 ) on yml Details:

- It's complicated ( for me ) with Docker Desktop to access directely to the PhotoPrism database from another computer ( on same LAN of course). ( execpt ifyou have an easy solution )

My Question:

- How To: Force update database with PhotoPrism\storage\sidecar\...\yml files ? (YAML)

- Of course I would like the faster way...

Perhaps to motivate your answers, I could distribute my in-house software, if you have a graphics card that can run LLaVa...

Thank you again for your help.

**Comment by lastzero** [comment]
YAML files are always just used as export / backup as this would otherwise cause a loop:

- https://docs.photoprism.app/user-guide/backups/export/

JSON files as created by Exiftool (or Google Photos) can be used to read / inject metadata. However, those won't be written and can thus not be used as backups.

**Comment by pbenaim** [comment]
So if I undertood that you said, I can delete the data base ( with:  **docker compose exec photoprism photoprism reset -y**  , with, before, **docker compose exec photoprism photoprism backup -a -i**  , just in case... )

And so after that, **docker compose exec photoprism photoprism index --cleanup** to remake index with yml (YAML) files ?

Say me if I'm wrong...

As a reminder, if it takes “a lot” of time it’s not a big deal. The important thing is to have the right information after modifying the YML files...

Thanks for your help 👍

**Comment by lastzero** [comment]
If you want to start with a clean database, just remove the database and recreate an empty one with the same name. Both the reset and the cleanup commands MAY remove the YAML sidecar files, so if you want to keep / use them, my recommendation is to be careful with that and carefully read the command descriptions e.g. using the --help flag.
