### ISSUE TITLE
Vectors: Use RSVG instead of imagemagick to convert SVG to PNG

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3885]
Currently imagemagick is used to convert SVG to PNG, and it seems that it does not use RSVG as a delegate. The problem is that imagemagick cannot handle color gradients properly, while RSVG can.

Acceptance Criteria:
-   [x] SVGs MUST be converted with RSVG

**Comment by lastzero** [comment]
An updated development preview build is available for testing:
- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview
