### ISSUE TITLE
Update docs for "Convert to JPEG" to "Preview Images"

### ISSUE THREAD

**Issue by pgalbavy** [photoprism/photoprism#3895]
From the changes made in #3793 the documentation seems yet to be updated.

The section at [Convert to JPEG](https://docs.photoprism.app/user-guide/settings/library/#convert-to-jpeg) should be changed to refer to "Preview Images" and also perhaps document why it cannot be changed in the UI (grey tick)?

**Comment by lastzero** [comment]
You are right! It's on our todo already, but we also accept pull requests :)

**Comment by pgalbavy** [comment]
While I am comfortable to Go and MD files, I am not yet familiar enough with PP features - and work means not enough time to go deep dive quite yet. Signed up as a member at least, for now!

**Comment by graciousgrey** [comment]
Thank you very much for your support and for reporting this issue :)

The documentation has been updated accordingly:
https://docs.photoprism.app/user-guide/settings/library/#preview-images

**Comment by pgalbavy** [comment]
Great, thanks! I'll close.
