### ISSUE TITLE
Docker size

### ISSUE THREAD

**Issue by rgarrigue** [photoprism/photoprism#39]
Hi

I was wondering why downloading photoprism container took so much time...

![image](https://user-images.githubusercontent.com/1872031/47154780-8a082980-d2e3-11e8-9dde-ff9dfb370ca9.png)

May I suggest a multistage build ? Here's the doc https://docs.docker.com/develop/develop-images/multistage-build/

Basically, if you can make a standalone photoprism binary (aka no need for local third party)

```
FROM golang:1.7.3
# everything for build, until standalone photoprism bin is in say /bin/photoprism

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=0 /bin/photoprism .
ENTRYPOINT ["./photoprism"]
CMD ["start"]  
```

**Comment by lastzero** [comment]
Yes, great idea. I guess we can remove lots of stuff from the development image related to TensorFlow and Python. It's there to experiment, but most of it is not used. But of course we need the TensorFlow model, HTML templates, JS & CSS code etc, so just a single binary is not enough.

Do you think it would work without any TensorFlow libs installed? I don't think so, but never tried.

**Comment by rgarrigue** [comment]
I don't know a thing about Photoprism, I just saw the project on github explore and wanted to gave a shot via docker. And I don't know a thing about Tensorflow either.

So, on a pure docker based point of view
- Static assets can be provided like the bin, copy from build container / sources
- If tensorflow in photoprism context can be used in a client/server way, it should. Then you can write a docker-compose.yml featuring "photoprism" your container, "tensorflow" for example https://hub.docker.com/r/tensorflow/tensorflow/.

**Comment by lastzero** [comment]
I see. We use Tensorflow as a library for image classification. Doing this via rest means copying the contents (that are already in memory) to a different container via HTTP just to get some tag labels back. Can be done, but probably not very efficient. Also means maintaining another app as a server. There are (commercial) ready-to-use tensorflow based container images available for that though. Maybe worth an experiment if there is time. Not sure how small they are.

Our image certainly has to become smaller. Contains lots of dev only stuff right now.

**Comment by lastzero** [comment]
Working on this right now... There will be a development base image and one for production without any dev / build tools.

**Comment by lastzero** [comment]
Compressed size is 172 MB now. Build and push to Docker Hub performed by Travis CI whenever develop is merged into master.

**Comment by rgarrigue** [comment]
Purrrfect, thanks !
