### ISSUE TITLE
cannot use cli because of invalid originals paths error

### ISSUE THREAD

**Issue by provinzio** [photoprism/photoprism#3901]
#### 1. What is not working as documented?

I want to add users using the cli with `photoprism users add ...`, but I get following error

```
ERRO[2023-11-22T11:17:22+01:00] invalid originals path, check configuration and permissions
```

#### 2. How can we reproduce it?

1. installed photoprism on proxmox with tteck helper script (https://tteck.github.io/Proxmox/)
2. mounted an external drive
3. added environment variables in `/var/lib/photoprism/.env` defining the necessary paths
4. try to add a user with the cli

#### 3. What behavior do you expect?

I don't expect the above stated error message.

#### 4. What could be the cause of your problem?

`photoprism config` does not list the correct paths which were set in the env variable.
The website shows to correct photos.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

`/var/lib/photoprism/.env`

```
PHOTOPRISM_AUTH_MODE='...'
PHOTOPRISM_ADMIN_PASSWORD='...'
PHOTOPRISM_HTTP_HOST='...'
PHOTOPRISM_HTTP_PORT='...'
PHOTOPRISM_SITE_CAPTION='Photoprism'
PHOTOPRISM_STORAGE_PATH='/media/appdata/photoprism/storage'
PHOTOPRISM_ORIGINALS_PATH='/media/appdata/photoprism/photos/Originals'
PHOTOPRISM_IMPORT_PATH='/media/appdata/photoprism/photos/Import'

PHOTOPRISM_DETECT_NSFW='false'
PHOTOPRISM_UPLOAD_NSFW='true'

PHOTOPRISM_DATABASE_DRIVER='mysql'
PHOTOPRISM_DATABASE_SERVER='...'
PHOTOPRISM_DATABASE_NAME='...'
PHOTOPRISM_DATABASE_USER='...'
```

`photoprism config`

|          Name          |                                            Value                                            |
|------------------------|---------------------------------------------------------------------------------------------|
| auth-mode              | password                                                                                    |
| admin-user             | admin                                                                                       |
| admin-password         |                                                                                             |
| public                 | false                                                                                       |
| session-maxage         |                                                                                     1209600 |
| session-timeout        |                                                                                      604800 |
| login-uri              | /library/login                                                                              |
| register-uri           |                                                                                             |
| password-length        |                                                                                           4 |
| password-reset-uri     |                                                                                             |
| log-level              | info                                                                                        |
| debug                  | false                                                                                       |
| trace                  | false                                                                                       |
| config-path            | /root/.photoprism/storage/config                                                            |
| certificates-path      | /root/.photoprism/storage/config/certificates                                               |
| options-yaml           | /root/.photoprism/storage/config/options.yml                                                |
| defaults-yaml          | /etc/photoprism/defaults.yml                                                                |
| settings-yaml          | /etc/photoprism/settings.yml (defaults)                                                     |
| settings-yaml          | /root/.photoprism/storage/config/settings.yml                                               |
| originals-path         |                                                                                             |
| originals-limit        |                                                                                        1000 |
| resolution-limit       |                                                                                         150 |
| users-path             | users                                                                                       |
| users-originals-path   | users                                                                                       |
| storage-path           | /root/.photoprism/storage                                                                   |
| users-storage-path     | /root/.photoprism/storage/users                                                             |
| sidecar-path           | /root/.photoprism/storage/sidecar                                                           |
| albums-path            | /root/.photoprism/storage/albums                                                            |
| backup-path            | /root/.photoprism/storage/backup                                                            |
| cache-path             | /root/.photoprism/storage/cache                                                             |
| cmd-cache-path         | /root/.photoprism/storage/cache/cmd                                                         |
| media-cache-path       | /root/.photoprism/storage/cache/media                                                       |
| thumb-cache-path       | /root/.photoprism/storage/cache/thumbnails                                                  |
| import-path            |                                                                                             |
| import-dest            |                                                                                             |
| assets-path            | /opt/photoprism/assets                                                                      |
| static-path            | /opt/photoprism/assets/static                                                               |
| build-path             | /opt/photoprism/assets/static/build                                                         |
| img-path               | /opt/photoprism/assets/static/img                                                           |
| templates-path         | /opt/photoprism/assets/templates                                                            |
| temp-path              | /tmp/photoprism_00000000                                                                    |
| workers                |                                                                                           2 |
| wakeup-interval        | 15m0s                                                                                       |
| auto-index             |                                                                                         300 |
| auto-import            |                                                                                         180 |
| read-only              | false                                                                                       |
| experimental           | false                                                                                       |
| disable-webdav         | false                                                                                       |
| disable-settings       | false                                                                                       |
| disable-places         | false                                                                                       |
| disable-backups        | false                                                                                       |
| disable-tensorflow     | false                                                                                       |
| disable-faces          | false                                                                                       |
| disable-classification | false                                                                                       |
| disable-sips           | true                                                                                        |
| disable-ffmpeg         | false                                                                                       |
| disable-exiftool       | false                                                                                       |
| disable-darktable      | false                                                                                       |
| disable-rawtherapee    | true                                                                                        |
| disable-imagemagick    | true                                                                                        |
| disable-heifconvert    | true                                                                                        |
| disable-rsvgconvert    | true                                                                                        |
| disable-vectors        | true                                                                                        |
| disable-jpegxl         | true                                                                                        |
| disable-raw            | false                                                                                       |
| raw-presets            | false                                                                                       |
| exif-bruteforce        | false                                                                                       |
| detect-nsfw            | false                                                                                       |
| upload-nsfw            | false                                                                                       |
| tensorflow-version     | 1.15.2                                                                                      |
| tensorflow-model-path  | /opt/photoprism/assets/nasnet                                                               |
| default-locale         | en                                                                                          |
| default-theme          | default                                                                                     |
| app-name               | PhotoPrism                                                                                  |
| app-mode               | standalone                                                                                  |
| app-icon               | logo                                                                                        |
| app-color              | #000000                                                                                     |
| legal-info             |                                                                                             |
| legal-url              |                                                                                             |
| wallpaper-uri          |                                                                                             |
| cdn-url                | /                                                                                           |
| cdn-video              | false                                                                                       |
| site-url               | http://localhost:2342/                                                                      |
| site-https             | false                                                                                       |
| site-domain            | localhost                                                                                   |
| site-author            |                                                                                             |
| site-title             | PhotoPrism                                                                                  |
| site-caption           | AI-Powered Photos App                                                                       |
| site-description       |                                                                                             |
| site-preview           | https://i.photoprism.app/prism?cover=64&style=centered%20dark&caption=none&title=PhotoPrism |
| base-uri               | /                                                                                           |
| api-uri                | /api/v1                                                                                     |
| static-uri             | /static                                                                                     |
| content-uri            | /api/v1                                                                                     |
| video-uri              | /api/v1                                                                                     |
| https-proxy            |                                                                                             |
| https-proxy-insecure   | false                                                                                       |
| trusted-proxy          | 172.16.0.0/12                                                                               |
| proxy-proto-header     | X-Forwarded-Proto                                                                           |
| proxy-proto-https      | https                                                                                       |
| disable-tls            | true                                                                                        |
| default-tls            | false                                                                                       |
| tls-email              |                                                                                             |
| tls-cert               |                                                                                             |
| tls-key                |                                                                                             |
| http-mode              | release                                                                                     |
| http-compression       |                                                                                             |
| http-cache-maxage      |                                                                                     2592000 |
| http-cache-public      | false                                                                                       |
| http-host              | 0.0.0.0                                                                                     |
| http-port              |                                                                                        2342 |
| database-driver        | sqlite3                                                                                     |
| database-dsn           | /root/.photoprism/storage/index.db?_busy_timeout=5000                                       |
| database-server        |                                                                                             |
| database-host          |                                                                                             |
| database-port          |                                                                                             |
| database-user          |                                                                                             |
| database-password      |                                                                                             |
| database-conns         |                                                                                          24 |
| database-conns-idle    |                                                                                          12 |
| mariadb-bin            | /usr/bin/mariadb                                                                            |
| mariadb-dump-bin       | /usr/bin/mariadb-dump                                                                       |
| sips-bin               |                                                                                             |
| sips-blacklist         | avif,avifs                                                                                  |
| ffmpeg-bin             | /usr/bin/ffmpeg                                                                             |
| ffmpeg-encoder         | libx264                                                                                     |
| ffmpeg-size            |                                                                                        3840 |
| ffmpeg-bitrate         |                                                                                          50 |
| ffmpeg-map-video       | 0:v:0                                                                                       |
| ffmpeg-map-audio       | 0:a:0?                                                                                      |
| exiftool-bin           | /usr/bin/exiftool                                                                           |
| darktable-bin          | /usr/bin/darktable-cli                                                                      |
| darktable-cache-path   |                                                                                             |
| darktable-config-path  |                                                                                             |
| darktable-blacklist    |                                                                                             |
| rawtherapee-bin        |                                                                                             |
| rawtherapee-blacklist  | dng                                                                                         |
| imagemagick-bin        |                                                                                             |
| imagemagick-blacklist  | heif,heic,heics,avif,avifs,jxl                                                              |
| heifconvert-bin        |                                                                                             |
| rsvgconvert-bin        |                                                                                             |
| jpegxldecoder-bin      |                                                                                             |
| download-token         | ...|
| preview-token          | ********                                                                                    |
| thumb-color            | sRGB                                                                                        |
| thumb-filter           | lanczos                                                                                     |
| thumb-size             |                                                                                        2048 |
| thumb-size-uncached    |                                                                                        7680 |
| thumb-uncached         | false                                                                                       |
| jpeg-quality           |                                                                                          85 |
| jpeg-size              |                                                                                        7680 |
| png-size               |                                                                                        7680 |
| face-size              |                                                                                          50 |
| face-score             |                                                                                    9.000000 |
| face-overlap           |                                                                                          42 |
| face-cluster-size      |                                                                                          80 |
| face-cluster-score     |                                                                                          15 |
| face-cluster-core      |                                                                                           4 |
| face-cluster-dist      |                                                                                    0.640000 |
| face-match-dist        |                                                                                    0.460000 |
| pid-filename           | /root/.photoprism/storage/photoprism.pid                                                    |
| log-filename           | /root/.photoprism/storage/photoprism.log                                                    |

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: x86_64

(b) Database Type & Version: MySQL

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: not relevant

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? not relevant

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: 8 x 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (1 Socket)

(b) Physical Memory & Swap Space in GB: 4 GB + 4 GB

(c) Storage Type: SSD

(d) Anything else that might be helpful to know? no

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

not relevant

**Comment by lastzero** [comment]
Note that `/var/lib/photoprism/.env` is not a standard configuration file that PhotoPrism uses. It probably belongs to a third-party integration that we do not maintain or support.

Please see the following setup guide to learn more about the configuration of PhotoPrism if you are not using our official Docker image and note that we only recommend this to experienced users and/or developers:
- https://dl.photoprism.app/pkg/linux/README.html
