### ISSUE TITLE
Docs: Add note that you can use a $$ (double dollar sign) when passwords contain a literal dollar sign

### ISSUE THREAD

**Issue by gene1wood** [photoprism/photoprism#3913]
#### 1. What is not working as documented?

When using the `mysql` DB backend option, if you configure a database user password containing a dollar sign `$` character, photoprism will be unable to connect to the database and will return the error

```
Error 1045: Access denied for user 'photoprism'@'172.21.0.7' (using password: YES)
```

This prevents photoprism from launching because it can't establish a database connection.

#### 2. How can we reproduce it?

1. Setup photoprism using docker and mariadb
2. Set the `PHOTOPRISM_DATABASE_PASSWORD` to a password containing a dollar sign like `foo$foo`
3. Set the `photoprism` database user's password in mariadb to the same value (`foo$foo`). I'm using mariadb on the host as opposed to within a container, but I imagine in the mariadb container just setting the `MARIADB_PASSWORD` environment variable to `foo$foo` would trigger the bug (but I haven't tested it with the mariadb container, only with mariadb running on the host)
4. Start the photoprism docker container

#### 3. What behavior do you expect?

I would expect that the database user's password, containing any character at all (with maybe the exception of the backslash `\` which mariadb handles in a special way in string literals), would work when used in photoprism.

Instead, when there's a dollar sign `$` in the password, photoprism likely interprets that dollar sign and the resulting password that it attempts to use to authenticate isn't `foo$foo` but something else resulting in the `Access denied` error

If you remove the `$` from the password in the photoprism environment variable and in the mariadb user's password, the problem goes away.

#### 4. What could be the cause of your problem?

I suspect that photoprism isn't handling the password as a string literal and is instead interpreting the dollar sign, maybe as the indicator of a variable.

There may be other characters that get interpreted, beyond the dollar sign, and cause problems, it's just the dollar sign is the one I encountered.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Here are the log messages that docker gives

```
photoprism    | started 231021 as root (amd64-prod)
photoprism    | init: updating filesystem permissions
photoprism    | PHOTOPRISM_DISABLE_CHOWN="true" disables permission updates
photoprism    | init: https
photoprism    | Creation of a default HTTPS/TLS certificate is skipped because PHOTOPRISM_DEFAULT_TLS is "false".
photoprism    | Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
photoprism    | https://docs.photoprism.app/getting-started/troubleshooting/
photoprism    | file umask....: "0002" (u=rwx,g=rwx,o=rx)
photoprism    | home directory: /photoprism
photoprism    | assets path...: /opt/photoprism/assets
photoprism    | storage path..: /photoprism/storage
photoprism    | config path...: default
photoprism    | cache path....: default
photoprism    | backup path...: /photoprism/storage/backups
photoprism    | import path...: /photoprism/import
photoprism    | originals path: /photoprism/originals
photoprism    | switching to uid 2000:2000
photoprism    | /opt/photoprism/bin/photoprism start
photoprism    | time="2023-11-27T04:43:07Z" level=error msg="Error 1045: Access denied for user 'photoprism'@'172.21.0.7' (using password: YES)"
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 / Build 231021-9abea5b55

(b) Database Type & Version: MariaDB 10.10.7+maria~ubu2004

(c) Operating System Types & Versions: Linux Ubuntu 20.04.6 LTS

**Comment by lastzero** [comment]
You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign:
https://docs.docker.com/compose/compose-file/12-interpolation/

**Comment by gene1wood** [comment]
@lastzero I don't think that's the issue. 

If you read down in that link you posted it says

> Interpolation applies only to YAML values, not to keys. For the few places where keys are actually arbitrary user-defined strings, such as labels or environment, an alternate equal sign syntax must be used for interpolation to apply. 

If I set the `PHOTOPRISM_DATABASE_PASSWORD` variable in docker compose to a value containing a dollar sign like `foo$foo`, and I then enter the container

`docker exec -it photoprism /bin/bash`

and run `env`.

The `PHOTOPRISM_DATABASE_PASSWORD` variable correctly displays with the dollar sign present.

I don't think the issue is with docker compose interpreting the dollar sign.

**Comment by lastzero** [comment]
It is a YAML value, so it applies. Did you already try to escape it as mentioned?

**Comment by gene1wood** [comment]
@lastzero Got it.

(My testing just then got confused as I moved to using an `env_file` while I was testing instead of the `environment:` YAML key and the `$$` issue doesn't occur in an `env_file`)

Ok, so given that 

* the issue with setting a password in the docker environment variable is caused by docker interpreting the dollar sign (not by photoprism interpreting the dollar sign)
* passwords often contain dollar signs as special characters
* the error that the user gets back doesn't hint at the root cause and makes it very difficult to determine that it's a special character in the password causing the problem, and which character it is

Do you think it would be worth adding a note to the comment the succeeds the `PHOTOPRISM_DATABASE_PASSWORD` environment variable in the `docker-compose.yml` file that mentions this one character that will cause a problem? Something like

```
# MariaDB or MySQL database user password. If your password contains a dollar sign, you must enter it as $$
```

or something like that?

**Comment by lastzero** [comment]
@gene1wood While this is not specific to PhotoPrism, I agree that it should be mentioned in our docs. I was sure this was already the case e.g. in our [Introduction to YAML](https://docs.photoprism.app/developer-guide/technologies/yaml/), but apparently it isn't or it got lost along the way...

**Comment by lastzero** [comment]
@gene1wood As a first step, I have updated our Introduction to YAML since it is linked on all relevant pages (we can additionally add notes to our [config file examples](https://github.com/photoprism/photoprism/tree/develop/setup/docker)):

- https://docs.photoprism.app/developer-guide/technologies/yaml/

**Comment by lastzero** [comment]
To make sure everyone can find this information, I've also added a section on Docker Compose to the Known Issues page, which is prominently linked in the navigation:
- https://docs.photoprism.app/known-issues/#docker-compose

**Comment by lastzero** [comment]
Also added a note to the"Cannot Log In" section in the troubleshooting guide:
- https://docs.photoprism.app/getting-started/troubleshooting/#cannot-log-in

**Comment by lastzero** [comment]
Last but not least, I've added notes to our dedicated MariaDB troubleshooting guide:
- https://docs.photoprism.app/getting-started/troubleshooting/mariadb/#wrong-password

**Comment by lastzero** [comment]
Hope that's enough for now :)

**Comment by gene1wood** [comment]
Those are great documentation solutions and I think it will help others that encounter this issue. Thanks!
