### ISSUE TITLE
Cards View: Rendering breaks if a lens has no model description

### ISSUE THREAD

**Issue by Beet4** [photoprism/photoprism#3918]
#### 1. What is not working as documented?

The new "Cards View Details" from release tag `231011` seems to not render properly in some cases.

Release tag `230923`:
![oldview](https://github.com/photoprism/photoprism/assets/38279393/5e26e10a-53af-4563-9cbf-7f26872bdeb0)

Release tag `231021` (latest):
![newview](https://github.com/photoprism/photoprism/assets/38279393/80128c68-c513-404a-8d84-e68fd16e9035)
Please note that the icons in the details under the photos are not rendering as well.

Release tag `231021` (latest), miniature view:
![image](https://github.com/photoprism/photoprism/assets/38279393/56cc6f72-a65f-4385-a234-c570bba8ffec)
Works as expected.

#### 2. How can we reproduce it?

As I do not know what exactly triggers the bug it's hard to give exact reproducible steps as it seems random which images it does not render but at the same time it's the exact same range of pictures (for me at least) all the time even after completely removing them and reindexing them.

But with `latest` the issue always happens for me in this view with the same range of pictures (a couple of hundred ones).

I have around 54k pictures spanning from January 2024 to November 2023 and so far only found this issue on picture from May and June 2023.

1. Use `latest`
2. Switch to detailed cards view
3. I find it easiest is to check different months in calendar on a large library I guess to see if you can find the same bug.
4. See rendering bug
5. Check web browser error console

I have basically all settings at default.

#### 3. What behavior do you expect?

For the Cards View Details to render properly.

#### 4. What could be the cause of your problem?

- I've tried to force regenerate all thumbnails. 
- I have tried removing the files that are not renderering properly in the list completely. Let photoprism clean up, and readded the files to originals and let photoprism index. Still same results as before.

The issue started with release 231011 which seems to have introduced a new details cards view.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
See screenshots above.

Firefox logs error in the console when the bug is occuring:
[error.log](https://github.com/photoprism/photoprism/files/13472566/error.log)
I have omitted my own domain in the logs for privacy reasons.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 
AMD64, see build numbers above. Running Docker on unRAID.

(b) Database Type & Version:
MariaDB.  Server version: 10.11.5-MariaDB-log - Alpine Linux 

(c) Operating System Types & Versions: 
Server: Docker, unRAID. Client: Windows 11, 10 and Android 14.

(d) Browser Types & Versions:
Tried on Firefox 120.0 for Windows, Latest Chrome for Windows, Latest Edge for Windows and Latest Chrome for Android.

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
Tried with all disabled as well, same result.

**Comment by lastzero** [comment]
- Is this always happening or only e.g. while indexing or when you scroll for a while?
- Does changing the language to English make a difference (in case it's a problem with rendering dates/times in other languages)?
- Do you see the same issue on our public demo? If not, what could be a difference between our demo and your installation?

**Comment by lastzero** [comment]
It might be due to a JS error when generating the recently added additional lens and camera information, e.g. if an expected value is missing. Could you provide us with some of the affected files for testing?
- https://www.photoprism.app/contact#file-samples

**Comment by Beet4** [comment]
1. It is always happening - with the same set range of pictures.
2. Setting to English does not help.
3. No. And there could of course be a lot of different reasons why it's not showing on the demo:
The amount of pictures 142 vs 54k.
Different dates
Different cameras
Different locations

I mention the last three as it seems it is also having trouble rendering the details under the photo as the icons are not rendered.

The details or the gray thumbnails are not clickable either. If I click on the first thumbnail that is showing, it works fine to scroll through the pictures.

**Comment by Beet4** [comment]
I have sent some sample pictures from within this range.

You might be onto something with the camera information. I was experimenting with different Google Cameras at that time, so **some** images within this rank have different EXIF data. From outside this range it works fine with at that time the stock camera on my OnePlus 8 Pro and my wife's Galaxy S23+. But there are pictures from the stock camera and my wife's camera as well in this range. So perhaps when the rendering comes to an image where perhaps some EXIF data is missing, it stops rendering the rest as well within a set range?

In the sample set, I have tried to include pictures from the stock camera on my then OnePlus 8 Pro, and some from the Google Camera app. I did use a few different Google Cameras so they might have different EXIF data, if you find no errors with these pictures let me know if you need more sample pictures.

After changing my phone to a Galaxy S23+ as well and using the stock camera it renders correctly (mid-June which might explain why it's not occurring after June).

**Comment by lastzero** [comment]
Thanks! We'll test with your files and then provide a fix as soon as possible 👍

**Comment by lastzero** [comment]
I've started a new preview build so you can test these changes as soon as it has been [uploaded to Docker Hub](https://hub.docker.com/r/photoprism/photoprism/tags) (shouldn't take more than an hour, probably less):
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
The release notes for the preview build have been updated to include this fix:
- https://docs.photoprism.app/release-notes/#development-preview

**Comment by Beet4** [comment]
I have pulled `photoprism/photoprism:preview` and am happy to say that the fix seems to be working great!

![Untitled-2](https://github.com/photoprism/photoprism/assets/38279393/36e5d4b7-569c-4afb-8890-5e03ba2709e6)

Thank you for your support, efforts and super quick fix!

Edit: Build `231127-f48ff16ef`
