### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by bobobo1618** [photoprism/photoprism#392]
I'm running an index and various pieces of code are complaining that the database is locked:

- `index: database is locked for “<redacted>”`
- `photo: database is locked (save <id looking thing> after deadlock)`
- `index: database is locked`
- `photo: database is locked (create)`
- `file: database is locked (create)`

I'm using SQLite3 as the database.

**Comment by bobobo1618** [comment]
Oh, to be clear, this happens intermittently. It's not consistent or overly common, they seem to pop up roughly every 10 images or so.

**Comment by lastzero** [comment]
Since you have a lot of images, I'd absolutely recommend using MySQL or MariaDB. Should scale better, much easier to backup & debug and probably also needs less storage.

**Comment by bobobo1618** [comment]
I don't need a whole lot of concurrent writes so SQLite should work just fine for me. I avoid MySQL and its derivatives like the plague, the alternative for me would be PostgreSQL.

It looks like this is somewhat expected with SQlite3. There are some mitigation suggestions [here](https://github.com/mattn/go-sqlite3/issues/274#issuecomment-232942571).

I think this can be easily solved by appending `?_busy_timeout=5000` to [the SQLite default DSN](https://github.com/photoprism/photoprism/blob/0e426a547bcad7bdf333bbb2aa9665649fdbf8e7/internal/config/db.go#L46).

For myself for now, I can just manually set the DSN on the command line.

**Comment by lastzero** [comment]
Once we have solid funding, we can add support for additional SQL dialects and experiment with in memory databases. For now, MariaDB works just fine and many users are familiar with it. It's syntax seems also more compatible with Sqlite. We also had TiDB compiled in, but removed it after stability issues we couldn't fix easily.

**Comment by bobobo1618** [comment]
Adding the `?_busy_timeout=5000` to the DSN seems to have reduced incidence of the problem but not eliminated it.

**Comment by lastzero** [comment]
Locks were my main concern when adding sqlite. Maybe it helps to reduce the number of workers? If you don't like MySQL, you should hate Sqlite. Uses dynamic typing, feels like PHP 3.

**Comment by bobobo1618** [comment]
I could just reduce the number of DB connections to 1 but I'd prefer to keep some degree of concurrency.

Is it possible that a lock is being held for a relatively long time, for example while thumbnails are being generated or something like that?

SQLite has some appeal to me because it fills a niche that MySQL and PostgreSQL cannot. In particular, it's very lightweight, both to run and to administer. I'm not going through all the hassle of running a MySQL server for this application, especially when I already have a PostgreSQL server.

**Comment by lastzero** [comment]
No, not really... as you mentioned, you could experiment with GORM settings like the number of open connections (not sure if or to what degree that impacts embedded databases like Sqlite).

Reason why I am cautious with Sqlite is that we received feedback from users who had issues with creating SQL dumps / backups and reported large database files for relatively small libraries.

Clearly, MariaDB is the more conservative choice, unless you have personal reasons not to use it. With Docker, it shouldn't make a huge difference. Just another container and we even added a working config to our example `docker-compose.yml` file: https://dl.photoprism.org/docker/docker-compose.yml

**Comment by bobobo1618** [comment]
I'm not going to use MySQL/MariaDB, please stop recommending it to me. There's a bug caused by PhotoPrism's improper use of SQLite and I want to fix it. If you have pointers to the other SQLite issues, I'm happy to have a look at those too.

I bumped up the `_busy_timeout` to 50000 and I'm yet to see a locking error, so I think this is one viable solution to the problem.

This might be a problem that's exacerbated by my having 24 workers running at once.

**Comment by lastzero** [comment]
Well, complex software always has bugs. Happy to accept pull requests if you sign the CLA :) 

You can also do this via email if don't want to expose your address on GitHub.

One major challenge with this project is that we need to scale from a Raspberry Pi up to single servers with lots of memory and cpu cores. So far, our focus was on smaller servers. If the focus was on larger servers or clusters, the architecture would look somewhat different. You always need to start somewhere.

**Comment by bobobo1618** [comment]
I'm happy to sign the CLA but I discovered I need permission from my employer, so I'm waiting for that.

**Comment by lastzero** [comment]
Updated our scalability notes in getting started for future reference:

https://docs.photoprism.org/getting-started/scalability/

**Comment by lastzero** [comment]
After my recent changes, indexing errors on our test server seem gone (Intel i3, 4 cores).

Changed the default number of idle connections and their lifetime. Suspected this to cause other issues recently and reduced both. Now it looks like this might have caused bad indexing performance instead. Not sure what difference it makes when using SQLite, didn't have time to test yet.

Optimizing the overall indexing architecture (as suggested in #391) would surely also help, but it's (mostly) not a viable short term solution. We need to keep in mind that there could be more than one instance accessing the same data (base), like when the web server is running and you additionally run a terminal command for indexing. That's why we use the database as single source of truth, even if that leads to extra requests that could be optimized away.

Scalable distributed systems, transparent persistence & caching are hard, not exactly our "unique selling points". I'd rather invest my time in the UI at the moment, but am still very much interested in obvious quick wins when it comes to indexing performance and locking!

**Comment by bobobo1618** [comment]
I merged the latest changes and everything looks good for me so far.

As for the rest, there are definitely some easy optimizations I can suggest but I wonder if I should try rewriting the indexer from scratch instead...

> We need to keep in mind that there could be more than one instance accessing the same data (base), like when the web server is running and you additionally run a terminal command for indexing.

Of course, that's what databases are designed for though, I'm sure there are ways around it.

Off the top of my head, an architecture I've employed for a similar problem is to add a `processed` boolean to the database for each item that needs to be "indexed":

- The task that finds new items just needs to `INSERT <...> ON CONFLICT DO NOTHING;` and enqueue a task for the processing tasks. This way the "I found a thing that needs to be indexed" operation is idempotent and it's totally fine for multiple indexers to be running (just arguably pointless). 
- The processing tasks (in a not-Go world) fetch the row from the database to get the other information they need (usually only a key is enqueued) and if it's somehow been processed since it was enqueued, the tasks just do nothing, making the processing task idempotent as well.

The trouble here comes from the fact that we're in a yes-Go world and the queue is in each process' memory rather than in some shared server like RabbitMQ.

The only way I can think of around this without adding a new dependency is to put at least some of the queue state into the database. For example in addition to a `processed` boolean, we could add a `worker_timestamp` column that indicates that a worker took that photo from the database at that timestamp.

I think all my yammering on here makes it sound complicated but it's really quite simple.

**Comment by lastzero** [comment]
Besides reducing stat calls: Specific, repeating lookups, like for cameras and lenses, could "easily" be cached while indexing. Not when showing them in the UI though, otherwise it may look like changes were lost - at least as soon as users can view / edit camera descriptions, owners and notes (not implemented yet).

There are always a few use cases to keep in mind, it's not like optimizing a micro service that does exactly one thing like just indexing or just converting images.

**Comment by gerroon** [comment]
I am hitting this issue badly too, so I am trying to use mysql.

Do I need to enable this for mariadb?

`# PHOTOPRISM_DATABASE_DSN: "photoprism:photoprism@tcp(photoprism-db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"`

**Comment by lastzero** [comment]
@gerroon Sorry, came back from vacation and saw your question just now...

We've improved our Docker Compose example config files to simplify installation: https://dl.photoprism.org/docker/docker-compose.yml

Added `--transaction-isolation=READ-COMMITTED` today to reduce MariaDB locking.

**Comment by LMSSonos** [comment]
@lastzero I'm testing the software on synology (DS916+) using docker/mysql and scan for 5000 images takes multiple hours. I see a lot of these entries here in the error log:

![image](https://user-images.githubusercontent.com/19758451/91654311-f3dce700-eaa7-11ea-87fe-9fef6854ef93.png)

Should I change anything from the settings?

**Comment by lastzero** [comment]
@LMSSonos You're not using SQLite but MySQL? What version with what settings?

We recommend MariaDB 10.5 with the following settings:

`mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50`

**Comment by lastzero** [comment]
Currently re-indexing a huge library with no locking issues so far... SQLite might scale less well, although a DS916+ has 4 cores from which only 3 will be used for indexing. That shouldn't lead to much locking, except storage is slow. Use a local SSD if possible.

**Comment by LMSSonos** [comment]
sorry, I'm using sqlite not mysql. I test it with maria-db but without success

I get following log output
```
Attaching to photoprism_photoprism_1, photoprism_photoprism-db_1
photoprism_1     | WARNING: no logs are available with the 'db' log driver
photoprism-db_1  | WARNING: no logs are available with the 'db' log driver
photoprism_photoprism_1 exited with code 1
photoprism_1     | WARNING: no logs are available with the 'db' log driver
```

In the terminal from the sql i see following. Any ideas? tried with the original docker-compose settings (changing from sqlite to mariadb.

`2020-08-30  8:45:31 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.22.0.3' (This connection closed normally without authentication)`

I don't have an SSD right now, but will order one and see if it makes a difference. You mean for the `/photoprism/storage`

**Comment by lastzero** [comment]
> sorry, I'm using sqlite not mysql. I test it with maria-db but without success
> `2020-08-30 8:45:31 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.22.0.3' (This connection closed normally without authentication)`

Seems authentication is not configured correctly, see our https://dl.photoprism.org/docker/docker-compose.yml example (even if you're not using Docker Compose, the values are the same):

```
PHOTOPRISM_DATABASE_DRIVER: "mysql"
PHOTOPRISM_DATABASE_DSN: "user:passwd@tcp(photoprism-db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
```

> I don't have an SSD right now, but will order one and see if it makes a difference. You mean for the `/photoprism/storage`

Yes, it will certainly make a difference. If you're using MariaDB, make sure to also use the SSD for database storage - needs to be configured separately for the `photoprism-db` service as shown in our example.

**Comment by LMSSonos** [comment]
I'm using docker-compose with the settings from https://dl.photoprism.org/docker/docker-compose.yml - is there anything to enable logging on the client so that i could see what's going wrong.

Only thing in the terminal i see is `time="2020-08-30T09:32:06Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"`

my docker-compose.yaml:

```
      #PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # Change to "mysql" for external MySQL or MariaDB
      PHOTOPRISM_DATABASE_DRIVER: "mysql"          # Using MariaDB or MySQL instead of SQLite is optional
      PHOTOPRISM_DATABASE_DSN: "user:passwd@tcp(photoprism-db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
```

```
  photoprism-db:
    image: mariadb:10.5 # Alternatively mysql:8.0
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - "/volume1/docker/photoprism/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: photoprism
```

**Comment by lastzero** [comment]
Didn't know docker-compose is available on Synology? Interesting.

All logs are sent to Docker, so you should see them with `docker logs`, `docker-compose logs` or whatever UI Synology provides for this. In addition, you can turn on debug mode to see more detailed messages (`PHOTOPRISM_DEBUG: "true"`).

**Comment by LMSSonos** [comment]
Solved the issue. Reason was that on the first startup i canceled the docker too early and didn't have a photoprism database. so on the next runs it hasn't been created because it was expected to create on first run. Now it works with mariadb on synology. Scan is not faster than with mysql. It takes several hours to add 5000 images (even if I have the thumbs etc already from previous mysql run)

main reason for the slow import is that image classification takes about 3seconds per image on my synology DS918+ - don't think that SSD will improve that. So having ~45k photos with 3 scan threads will take about 13hours - I can live with that ;-)

Thanks for all your help

**Comment by lastzero** [comment]
Yes, consumer NAS typically don't have a strong processor that is good for fast indexing. But you only have to do it once, so it's not a major issue for most use cases - unless you continuously get lots of new files.

**Comment by LMSSonos** [comment]
> unless you continuously get lots of new files

Not in my case, so that's ok for me. Is there a reason Tensorflow runs again even if sidecar file exist?

**Comment by lastzero** [comment]
Sidecar files and TensorFlow have nothing to do with each other.

**Comment by LMSSonos** [comment]
but tensorflow results are stored in the sidecar yml file. At least the keywords from this example: city, plant, bucket or not?

img_xyz.yml
```
Details:
  Keywords: city, bucket, family, january, magenta, plant

```

**Comment by lastzero** [comment]
That's just keywords without probabilities etc

**Comment by LMSSonos** [comment]
@lastzero thanks for explaining.

**Comment by lapo-luchini** [comment]
> this can be easily solved by appending `?_busy_timeout=5000` to [the SQLite default DSN](https://github.com/photoprism/photoprism/blob/0e426a547bcad7bdf333bbb2aa9665649fdbf8e7/internal/config/db.go#L46)

This has improved things vastly for me. I agree SQLite is not perfect (but I still prefer it for simplicity sake), but this value would also be a quite sensible default. (myself, I added it on launch and that's fine)

**Comment by lastzero** [comment]
Based on your advice, we will add `?_busy_timeout=5000` to the default SQLite DSN. Is there anything else that might be helpful?

https://pkg.go.dev/github.com/mattn/go-sqlite3#section-readme

I've also seen advice to set `sqlite_unlock_notify` at compile time, but I haven't figured out what it really does, whether we should use it or if it's a [Gitea-specific build tag](https://docs.gitea.io/en-us/hacking-on-gitea/#building-gitea-basic) that otherwise has no effect?

We just got back from vacation, so I'm pretty busy and don't have much time to read through the documentation. Help is much appreciated! :+1:
