### ISSUE TITLE
Cant enable "people" in settings

### ISSUE THREAD

**Issue by kuduacz** [photoprism/photoprism#3920]
---------------------------------------------------------------------------

#### 1. What is not working as documented?

Cant enable "people" in settings. when click on it it marked and after moment disable by himself.

Using photoprism on docker.

in config.yaml its on "true"

Build [231021-9abea5b55](https://docs.photoprism.app/release-notes/)

AMD64 arch N1000 processor 16 gb ram

SSD

**Comment by lastzero** [comment]
I'll convert this to a discussion as it appears to be a local configuration issue or a misunderstanding of how the software works.
