### ISSUE TITLE
.ppignore does not ignore folders starting with #

### ISSUE THREAD

**Issue by martinhoess** [photoprism/photoprism#3925]
#### 1. What is not working as documented?
Regarding to [this comment](https://github.com/photoprism/photoprism/issues/287#issuecomment-623339571) a folder ignore for folders starting with # should work. However on my synology the #recycle folder (and other folders starting with #) is not ignored, even after a reset or a complete new install. 

Also the [documentation ](https://docs.photoprism.app/user-guide/library/originals/) differs from that and uses # as comment
![image](https://github.com/photoprism/photoprism/assets/47973549/664a73bc-7645-4ae0-9f4c-b228746ff4ba)

#### 2. How can we reproduce it?

![image](https://github.com/photoprism/photoprism/assets/47973549/bee56269-5b80-4c5d-9238-8c3312d75e7f)
![image](https://github.com/photoprism/photoprism/assets/47973549/10a39cce-6466-4345-bcb4-5cae46a65ce2)

![image](https://github.com/photoprism/photoprism/assets/47973549/d8d75a1c-2e99-46e1-a953-30fd46109029)

When reporting an import, indexing, or performance issue, please include the number and type of pictures in your library, as well as any configuration options you have changed, such as for thumbnail quality.

#### 3. What behavior do you expect?

ignore folders starting with #

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: [PhotoPrism® CE](http://192.168.0.10:2342/library/about) Build [231128-f48ff16ef](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: [MariaDB, MySQL, SQLite,...] mariadb:10.11

(c) Operating System Types & Versions: Synology DSM 7.2-64570 Update 1

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Synology RS1221+ 

(b) Physical Memory & Swap Space in GB: 12 GB

(c) Storage Type: 2TB SSD Raid 1

**Comment by graciousgrey** [comment]
I did some testing and for me it worked after escaping the #

Adding `[#]recycle` to the .ppignore ignored the folder "#recycle" adding `[#]*` ignored all folders starting with a hash.
We can add an example for this to our docs as well.

**Comment by martinhoess** [comment]
Thank you! 
Just tried it with escaping and it works as expected. 
Yes, an example in the documentation would be nice :)
