### ISSUE TITLE
Restrict the maximum in-memory cache size

### ISSUE THREAD

**Issue by andir** [photoprism/photoprism#393]
I just setup photoprism and imported a few hundred pictures. After browsing them on multiple devices (desktop & mobile) I noticed that the memory consumption spiked to >2GB. It didn't decrease after a few minutes of being idle and only decreased after restarting the process.

After a bit of digging I figured out that photoprism is currently using an in-memory cache that expires items after an hour (https://github.com/photoprism/photoprism/blob/f8ec76d6c9e030e5284d1bd4afc5ecc0daa06288/internal/service/cache.go#L15). The default configuration of bigcache doesn't restrict the size growth (as far as I can tell / https://github.com/allegro/bigcache/blob/bbbffd30d25b538b4c03be6649b1dffbacca9596/config.go).

While the default is probably fine for many devices and scenarios I think it should be configurable so that it fits better on memory-constrained devices. I had to increase the VM memory from 2GB to 4GB as otherwise there wouldn't be enough memory left for darktable-cli to do the RAW -> JPG conversions.

My proposal would be to add a configuration flag to set the cache size in megabytes and default that to ~512MB. Since most (all?) setups will likely have thumbnails stored on (fast) disks that shouldn't be a problem. Making the expiry configurable might also be nice. I do not know enough about bigcache to judge that.

**Comment by lastzero** [comment]
There's a difference between memory reserved and used. Do you actually run out of memory with massive swapping or is this something you expect seeing the numbers? Our cache typically shouldnt be very large as it's mostly metadata and some smaller thumbs for labels. I'll test and check again when I'm done with some other tasks.

Independent of this, I strongly recommend a minimum of 4 GB (or swap) unless TensorFlow is disabled. My feeling is that TensorFlow alone needs about 1 GB, so there's not much left if you only have 2.

**Comment by lastzero** [comment]
Added a few words on system requirements and how to reduce memory usage to our getting started docs:

https://docs.photoprism.org/getting-started/

**Comment by andir** [comment]
Thank you for taking the time!

It does indeed look like that must be from tensorflow or some other part of the application that only is triggered during import.
Since the instance was basically idle yesterday and I only did some brief browsing through the images the memory consumption looks a lot better:

![memory](https://user-images.githubusercontent.com/638836/87299402-3bb1aa00-c50c-11ea-9d2f-4938a6d315c8.png)

I am closing this as it was a wrong initial suspicion from my side.
