### ISSUE TITLE
Videos: Add Material Exchange Format (MXF) Support

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3935]
**As a professional user, I would like to have support for the Material Exchange Format (MXF) so that I can index, transcode and play files with the `.mxf` extension.**

More information about this container format can be found at https://en.wikipedia.org/wiki/Material_Exchange_Format.

**Comment by lastzero** [comment]
This can now be tested with our Development Preview build:
-  https://docs.photoprism.app/getting-started/updates/#development-preview
