### ISSUE TITLE
Raw files cannot be ungrouped from stack

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#394]
I have two raw files that, because of errors with the camera's clock, have the same timestamp, but aren't related at all. I can understand why they have been stacked, but I'd like to ungroup them.
Both files have a sidecar jpg each, but if I click "ungroup" on it, only the JPG is removed from the stack; both raw files are still in it.

![2020-07-12-211643_8960x2880_scrot](https://user-images.githubusercontent.com/5821180/87254765-41b07800-c485-11ea-969d-6465bf50323f.png)

**Comment by lastzero** [comment]
Please try again :)

**Comment by fdw** [comment]
I started the latest docker image and tried to unstack two raws with their respective sidecar files.
Now I only see the "ungroup" button on the raw files. After clicking it, the raw file is gone from the group, but the sidecar jpg is apparently still there and also cannot be ungrouped.

Am I doing something wrong?

**Comment by lastzero** [comment]
Not 100% sure, do you want to delete the JPEG completely? It should be possible to remove both RAWs, so that the JPEG remains. Worked without issues when I just tested it with a .mov file and a JPEG.

**Comment by fdw** [comment]
Sorry, I just noticed that I didn"t say that the sidecar is auto-generated.
Because of this, I assumed that the raw file and the associatad jpeg stay connected to each other instead of being treated as stand-alone. In this instance, I had expected both the raw and its jpeg to be ungrouped from the stack together. Does that make sense?

**Comment by lastzero** [comment]
You can never unstack a JPEG from a stack that has only one JPEG, otherwise the stack becomes invisible as we can not display RAW files in a browser. Instead, remove everything except the primary JPEG. New JPEGs will be automatically generated for your RAWs or videos, unless you turned this off e.g. with read only mode and a sidecar storage path within your originals.

**Comment by fdw** [comment]
Ah, okay, I hadn't expected this behavior. So thanks for the explanation :)

I could successfully ungroup both raws from the stack, and now both are shown as separate files with associated sidecar. So that works perfectly.

The only problem is that I now also have a stack of the two original sidecar jpgs, which I can neither ungroup nor delete.

**Comment by lastzero** [comment]
We'll add this (and more) to the docs soon :)

**Comment by lastzero** [comment]
> The only problem is that I now also have a stack of the two original sidecar jpgs, which I can neither ungroup nor delete.

When there are two JPEGs in a stack, you can remove one. If you don't need them, you can move them to the archive until we add a "permanent delete" option.

**Comment by fdw** [comment]
Thank you, that works for me :)
