### ISSUE TITLE
Wrong photo showed when click the thumbnail.

### ISSUE THREAD

**Issue by safrain** [photoprism/photoprism#395]
When I scroll down more than one page in one album and click the thumbnail, wrong photo showed.

The first photo in the album will be always showed nomatter which photo i click.
I observed "pid=1"  in the url when wrong picture is showing.

**Comment by lastzero** [comment]
Are you using our latest version? This is a bug we had and that was fixed.

**Comment by safrain** [comment]
Im using the lastest arm64 docker image, how can i check if the fix is included?

https://hub.docker.com/layers/photoprism/photoprism-arm64/latest/images/sha256-b285e722840fd6f7864b8422790b92a49ab422a7a1d4aff47cf8e5aee35e827c?context=explore

**Comment by lastzero** [comment]
You see the version in the Settings footer: Date plus GitHub commit hash

**Comment by safrain** [comment]
200629-2a24bf29-Linux-aarch64 this is the version Im using

**Comment by safrain** [comment]
I didn't spin down & up after using  docker-compose pull, so my container stuck at 0629.
After recreate my container, i got the 200717-63603ff7-Linux-aarch64, and confirmed the issue is gone.
Thanks for the help, closing the issue.
