### ISSUE TITLE
Date from filename (gif, png)

### ISSUE THREAD

**Issue by eigan** [photoprism/photoprism#396]
This is a followup of #304

All of my images are sorted by date and have the format `Y-m-d H:i:s`, even gifs and pngs. After importing into Photoprism, several old images was appearing first. TakenAt(?) was set to date of import (see screenshots). It would be great if these formats could fallback to read date from the filename too.

I noticed that the name of the image was using the proper month though. Let me know if you need the originals.

![2020-07-13_07-45](https://user-images.githubusercontent.com/41789/87274863-1a859500-c4dd-11ea-97c7-e46e8e914790.png)
![2020-07-13_07-46](https://user-images.githubusercontent.com/41789/87274868-1d808580-c4dd-11ea-99c6-64d3aa10876f.png)

![2020-07-13_07-51](https://user-images.githubusercontent.com/41789/87275145-d8108800-c4dd-11ea-8731-e42f1a9989d3.png)

**Comment by lastzero** [comment]
The file name as such seems to work for me, test is green. Reported date is `2018-04-12 19:24:49 +0000 UTC`.

Added the date and it's source to the photo info tab as shown here:

![Screenshot 2020-07-13 at 16 26 44](https://user-images.githubusercontent.com/301686/87316696-66106100-c526-11ea-9f67-44b88a13a327.png)

Maybe there is existing metadata like a date in a JSON / YAML sidecar file (if any)? In that case, you might want to delete them and re-index. I'm starting a new build, will be available within one hour.

**Comment by eigan** [comment]
Its showing up as "Unknown" for Taken. 

![2020-07-13_17-59](https://user-images.githubusercontent.com/41789/87326136-a1b12800-c532-11ea-9c97-4d2371ecced0.png)

Will try to find some more info later, and reindex. Here is the gif anyway: [Original gif](https://user-images.githubusercontent.com/41789/87326277-ce653f80-c532-11ea-9022-27f84c9df4b6.gif)

**Comment by lastzero** [comment]
Just added more infos to the files tab, next build is running.

To avoid any side effects while testing:
- update the Docker image
- use a fresh db
- and remove any automatically created sidecar files (typically found in the storage path)

**Comment by lastzero** [comment]
Excellent catch! There in fact was a glitch when a file was not a JPEG and also had no metadata... next build should fix it.

**Comment by eigan** [comment]
I tried with both the GIF and the PNG and it seems to work now. Thanks!

Will report back if this occur with the other gifs/pngs after full reindex.
