### ISSUE TITLE
Ability to create a query/search based on current image

### ISSUE THREAD

**Issue by khaytsus** [photoprism/photoprism#3969]
**Describe what problem this solves and why this would be valuable to many users**
When viewing an image, I often remember other images I took on this day, or other times I took pictures near this spot.  Another photo album I also use, Picapport, has a really nice Query that you can run against the current image which lets you view images within a configurable distance, on this same day, in the same folder, etc, so that you can view related images no matter what path you got to this image you can see associated (distance/folder/day) images.

**Describe the solution you'd like**
I'm not great at UI so I'm not sure exactly what to suggest on how to display this, but perhaps from the thumbnail view, which shows the thumbnail, date, image info, and location, perhaps something here which would open up a modal or another view which would expose a way to create a query based on this image.  It would let you directly search some of the example parameters mentioned above (distance/day/folder/etc)

I think this would help users rediscover their images, especially the distance search, I use this all the time.  I'll find an image via some path in the app then want to know what other images I took nearby this spot.  I could copy down the location and go to the Search, put in lat:NNN, lon:NNN (then realize lot's not lon, put in lng:NNN) for it, but some kind of dialog with a few clicks would be much easier.

**Describe alternatives you've considered**
I often currently use Picapport to look contextually at images, as searching for a date in PhotoPrism is more indirect (remember/write down date, go to search, type in day:N month:N year:N.  I often do this when looking at my older images.

**Comment by graciousgrey** [comment]
This sounds very similar to: 
- https://github.com/photoprism/photoprism/issues/797 

Note that you can already navigate from the card view to the location of a photo on the map:
https://docs.photoprism.app/user-guide/organize/places/#open-photo-from-search-in-places

**Comment by khaytsus** [comment]
@graciousgrey Yes, #797 has most of what I was asking for here, I missed that one searching or I likely would not have logged this one.

I am however confused about your "can already navigate" comment, as far as I can tell that's just from Places, not from other locations in the app?  That really doesn't cover any of the use cases I was mentioning.

**Comment by graciousgrey** [comment]
> I am however confused about your "can already navigate" comment, as far as I can tell that's just from Places, not from other locations in the app? That really doesn't cover any of the use cases I was mentioning.

If you are browsing photos somewhere in the app, e.g. in the search or in albums using the [card view](https://docs.photoprism.app/user-guide/search/views/), you can [click on the location of a photo on the card](https://docs.photoprism.app/user-guide/organize/places/#open-photo-from-search-in-places) to display it on the map. This allows you to find photos you have taken nearby. In addition you can use the ["dist" search filter on the map](https://demo.photoprism.app/library/places?q=s2%3A47a85a649dd4%20dist%3A5) to see images within a larger distance of the photo.

**Comment by khaytsus** [comment]
> If you are browsing photos somewhere in the app, e.g. in the search or in albums using the [card view](https://docs.photoprism.app/user-guide/search/views/), you can [click on the location of a photo on the card](https://docs.photoprism.app/user-guide/organize/places/#open-photo-from-search-in-places) to display it on the map. This allows you to find photos you have taken nearby. In addition you can use the ["dist" search filter on the map](https://demo.photoprism.app/library/places?q=s2%3A47a85a649dd4%20dist%3A5) to see images within a larger distance of the photo.

Seems like this doesn't show up using Library->Originals, which is often how I'm viewing images because they're already organized by directories and I am often starting there.  But where it does work, yes this works pretty good, thank you for pointing that out!
