### ISSUE TITLE
UX with the term "sidecar"

### ISSUE THREAD

**Issue by eigan** [photoprism/photoprism#397]
My first _(and only)_ experience with the term was while looking at the "Files" section. I tried to locate where in my originals the JPG was located, but could not find it. Then I found the "Root" part and figured it had to mean that it wasnt really in my originals. Could this be made more clear? I was thinking making it a part of the name (which I assume is the path).

![2020-07-13_07-58](https://user-images.githubusercontent.com/41789/87275778-24a89300-c4df-11ea-88fe-5f611bbdd7e6.png)

**Comment by lastzero** [comment]
It used to be in the originals directory, but some users didn't like it for a number of reasons (check closed GitHub issues).

So now, we kind of have something like a virtual file system with different layers (roots):

![](https://www.datalight.com/assets/blog-images/OverlayFS_Image.png)

Do I think this is too complex? Yes. Does it cause overhead when indexing? Yes.

But for a long time, nobody complained :)

**Comment by lastzero** [comment]
Maybe this helps a bit?

![Screenshot 2020-07-17 at 16 04 48](https://user-images.githubusercontent.com/301686/87795450-5788b900-c848-11ea-9d35-f6371f5506fe.png)

On Wikipedia, the term "sidecar" is defined as:

> Sidecar files, also known as buddy files or connected files, are computer files that store data (often metadata) which is not supported by the format of a source file.

See also [Store converted JPEGs in a seperate directory #268](https://github.com/photoprism/photoprism/issues/268)

**Comment by eigan** [comment]
Yes, that works, thanks :+1: _Another iteration of this would be to add a :question: and a `title` tag for more information._

Just to be clear: I do like this "sidecar" feature, as I don't want any software to touch my originals (nfs is mounted readonly from my NAS).
