### ISSUE TITLE
Map & Places: Update reverse geocoding data to include corrections from OSM

### ISSUE THREAD

**Issue by overbyrn** [photoprism/photoprism#3972]
#### 1. What is not working as documented?

There is a discrepency between the map data as shown in Places vs. same location when viewed via alternative map sources such as OpenStreetMap, Google Maps, MapTiler.  That is to say, from within PhotoPrism Places, the map is showing an incorrect spelling for a road name that has long since been corrected.

#### 2. How can we reproduce it?
Use attached image, bring into PhotoPrism, view its map data from Places.

#### 3. What behavior do you expect?
I'd expect the road name to match the spelling as viewed via many alternative mapping sources such as Google, OpenStreetMap etc.

#### 4. What could be the cause of your problem?
An issue with the reverse geocoding.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

1. example image. https://github.com/photoprism/photoprism/assets/545222/9e3800a2-8e12-4a45-9460-316f76e24cb8

2. screenshot from PhotoPrism Maps and Places showing (wrong) road name spelling. [PhotoPrism-Places-Map](https://github.com/photoprism/photoprism/assets/545222/48cb376a-7b7d-44b4-af14-375a45b2b4de)

4. screenshot from MapTiler (which according to [docs](https://docs.photoprism.app/getting-started/#maps-places) is the source for mapping data. [MapTiler-Maps](https://github.com/photoprism/photoprism/assets/545222/c44cd88e-9f5c-46aa-b2c2-4157e6240dd5)

6. screenshot from an online GPS coordinate converter, using GPS metadata from the image, the returned address, showing correct road name spelling. [GPS Coordinate Converter](https://github.com/photoprism/photoprism/assets/545222/277235be-2d42-4931-be73-8bd93f0befb4)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
Arch: x86_64
Build 231128-f48ff16ef

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
MariaDB 10.11

(c) Operating System Types & Versions: Linux, Windows, Android,...
Debian 12

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
N/A

**Comment by lastzero** [comment]
Note that we offer this service free of charge and do not have a dedicated team to update the data very frequently. If it is something that has been corrected in OSM, these corrections will eventually be included in our reverse geocoding data. So there is no need to submit bug reports for individual place or street names.
