### ISSUE TITLE
Archive: Sort pictures by "Recently Archived"

### ISSUE THREAD

**Issue by nowjon** [photoprism/photoprism#3975]
**Describe what problem this solves and why this would be valuable to many users**

Currently, when managing your pictures, it can be fairly easy to hit the wrong button. 
I recently did this when attempting to add a large amount of photos to an album, but ended up hitting the archive button. 
I'd like for the Archive tab to have a sort option for when items were added to archive. 

**Describe the solution you'd like**

On the archive page, you'll be able to sort by Archived Date

**Describe alternatives you've considered**

N/A

**Additional context**

![SCR-20240102-kcda](https://github.com/photoprism/photoprism/assets/40905072/c6c1c9a0-9bc6-4827-8ffb-c7809695ed2d)

**Comment by lastzero** [comment]
This would correspond to the `deleted_at` column in the database and seems to doable, however, this option must not be available in any other view...
