### ISSUE TITLE
Data too long for column 'file_colors' leads to "index: failed adding main jpg file"

### ISSUE THREAD

**Issue by SoPat712** [photoprism/photoprism#3976]
#### 1. What is not working as documented?

Adding and I guess exif'ing certain photos? Not sure if it's a metadata issue 

I'm getting 

1) Data too long for column 'file_colors' at row 1 while saving"
and 
2) unknown json in 2401bbe66ebd3a08f836cd0cdbeabada50322ef4_exiftool.json' in ' (29).JPG' (read json sidecar)'%!(EXTRA string=' (29).JPG')

#### 2. How can we reproduce it?

1. Run library scan
2. Wait for the scan to reach that folder.

I have around 800,000 photos I believe? A large amount,and I believe PhotoPrism skipped around half of them.

#### 3. What behavior do you expect?

For those photos to be added regardless of broken metadata. I noticed this issue when it was apparently indexing 2013, and there were only 8 photos with the metadata of 2013. I specifically checked folder by folder and made sure, and found those errors from Docker.

#### 4. What could be the cause of your problem?

I have no clue, as I haven't even messed with settings. Simply installed it and gave it my Photos folder and let it run for an entire day.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number:  ARM64

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

(c) Operating System Types & Versions: MacOS

(d) Browser Types & Versions: Firefox

#### 7. On what kind of device is PhotoPrism installed?

Macbook Pro

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

M1 Pro.

(b) Physical Memory & Swap Space in GB

13 TB remaining and The machine has 32 GB Ram.

(c) Storage Type: HDD

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

Some logs:

2024-01-02 16:49:35 photoprism-1  | time="2024-01-02T21:49:35Z" level=error msg="index: Error 1406: Data too long for column 'file_colors' at row 1 in '2012/2013/Nikon Camera/(29).JPG' (add new file)"
2024-01-02 16:49:35 photoprism-1  | time="2024-01-02T21:49:35Z" level=error msg="index: failed adding main jpg file '2012/2013/Nikon Camera/(29).JPG'"
2024-01-02 16:49:35 photoprism-1  | time="2024-01-02T21:49:35Z" level=error msg="index: Error 1406: Data too long for column 'file_colors' at row 1 in '2012/2013/Nikon Camera/(29).JPG' (add new file)"
2024-01-02 16:49:35 photoprism-1  | time="2024-01-02T21:49:35Z" level=error msg="index: failed adding main jpg file '2012/2013/Nikon Camera/(29).JPG'"

**Comment by SoPat712** [comment]
Seem to have fixed the file_colors issue by going in and updating the maria_db file_colors column to just be infinitely long.

**Comment by lastzero** [comment]
I don't see any information about the version you are using?

**Comment by SoPat712** [comment]
> I don't see any information about the version you are using?

I'm on the latest stable docker release of photoprism

**Comment by lastzero** [comment]
Could you please paste the build number for this? You will find it at the bottom of the Settings page.

**Comment by SoPat712** [comment]
Fixed by changing docker-composer to use version photoprism-latest instead of version photoprism I believe.

**Comment by lastzero** [comment]
Even when you use an image with the :latest tag, Docker does not automatically download new images for you. You can either manually upgrade as shown in our docs, or set up a service like [Watchtower](https://docs.photoprism.app/getting-started/updates/#watchtower) to get automatic updates:

https://docs.photoprism.app/getting-started/updates/

**Comment by SoPat712** [comment]
I switched from MacOS to Ubuntu as well. Maybe that fixed it?

**Comment by lastzero** [comment]
Rather not. It's something I remember to have fixed with an update released months ago.

**Comment by xmatthewx** [comment]
I am hitting this issue as well for many files. 

I am importing a large number of photos from google photos takeout.

I don't see anything special about the file or metadata json.

> 2024-01-23 17:46:22 ERRO file: Error 1406: Data too long for column 'file_colors' at row 1 while saving

6. Software
(a) Build 231128-f48ff16ef
(b) MariaDB
(c) MacOS 13.2
(d) Chrome Version 120.0.6099.234

7. Macbook Pro
(a) Apple M1 Pro
(b) 16GB memory
docker
memory limit: 7.9 GB
Swap 1 GB
virtual disk: 64 GB

(c) Storage Type: SSD

8. No Proxy, Firewall, VPN, or CDN

**Comment by graciousgrey** [comment]
@xmatthewx If you send us a sample file to samples@photoprism.app we can take a look at it.

**Comment by lastzero** [comment]
@xmatthewx I just double-checked our code and found no reason why the size of the file_colors column should be too small, since the thumbnail is 3x3 pixels, 9 pixels in total, and each color has a code from 0 to F. The maximum string size should therefore be 9 and the column size is 18.

So either:
- some thumbnails on your instance might be larger than 3x3 pixels e.g. because they were created incorrectly or changed/replaced manually
- or there might be a problem with your database schema, e.g. because you migrated from SQLite or performed manual schema updates (edit: a variation of this would be if you had restored the tables from a backup that did not contain the migrations table, so you have an old schema that is not automatically migrated)

Would that be possible?

You are welcome to test with our updated `photoprism/photoprism:test` image, which includes additional code to enforce the size limit and log a warning if exceeded.
