### ISSUE TITLE
No zip download possible for shared links

### ISSUE THREAD

**Issue by Bart1909** [photoprism/photoprism#398]
When using a shared link I'm only able to download single pictures. When selecting multiple images and clicking on the download button, a login is required.

Is there a way to enable the download of multiple files for shared links OR to disable the download button, when multiple images are selected?

**Comment by lastzero** [comment]
Good catch, should be fixed with the next build in about one hour :)

**Comment by Bart1909** [comment]
Works with the new version!

Thank you :)
