### ISSUE TITLE
Replace the terms whitelist and blacklist with alternatives

### ISSUE THREAD

**Issue by Mike-J-W** [photoprism/photoprism#3981]
#### 1. What is not working as documented?

The issue is the use of the terms "whitelist" and "blacklist", which are racially loaded and not inclusive. These terms are in the documentation and I'm guessing they might be used in the code as well.

#### 2. How can we reproduce it?

You can see an example here, in the last bullet point: https://docs.photoprism.app/user-guide/organize/people/#when-a-face-was-not-detected

#### 3. What behavior do you expect?

The terms "whitelist" and blacklist" should be changed to terms that are more direct and which lack racial connotations, such as "allowlist" and "blocklist". This is also becoming the industry standard, https://www.vice.com/en/article/v7dd3d/we-need-to-stop-saying-blacklist-and-whitelist.

#### 4. What could be the cause of your problem?

n/a

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

n/a

#### 6. Which software versions do you use?

n/a

#### 7. On what kind of device is PhotoPrism installed?

n/a

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

n/a

**Comment by lastzero** [comment]
Please do not use bug tickets for telling us this because the time we need to manage those could be used instead to improve our docs as you suggested. Thank you! ❤️

**Comment by lastzero** [comment]
@Mike-J-W @GlassedSilver Despite all the other work already on our plate and no help from the reporter or our community, I was able to go through our entire codebase today to replace the term blacklist with alternatives. Now that this is done, the documentation can also be updated (and not the other way around).

I stand by our policy to not use a bug ticket to get priority and/or more attention for demands. We're working as fast as we can, and it's not getting any faster this way. Thank you for your careful consideration! :+1:

**Comment by lastzero** [comment]
Note that the configuration reference does not need to be updated manually as it will be updated automatically with our next release.

**Comment by lastzero** [comment]
Our release notes and the development preview build have been updated so you can test the changes:

- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
The updated config options for file conversion are as follows (note that we keep `_BLACKLIST` as an alias for backwards compatibility):

|                           Environment                            |        CLI Flag         |                 Default                  |                           Description                           |
|------------------------------------------------------------------|-------------------------|------------------------------------------|-----------------------------------------------------------------|
| PHOTOPRISM_FFMPEG_BIN                                            | --ffmpeg-bin            | ffmpeg                                   | FFmpeg `COMMAND` for video transcoding and thumbnail extraction |
| PHOTOPRISM_FFMPEG_ENCODER                                        | --ffmpeg-encoder        | libx264                                  | FFmpeg AVC encoder `NAME`                                       |
| PHOTOPRISM_FFMPEG_SIZE                                           | --ffmpeg-size           |                                     4096 | maximum video size in `PIXELS` (720-7680)                       |
| PHOTOPRISM_FFMPEG_BITRATE                                        | --ffmpeg-bitrate        |                                       50 | maximum video `BITRATE` in Mbit/s                               |
| PHOTOPRISM_FFMPEG_MAP_VIDEO                                      | --ffmpeg-map-video      | `0:v:0`                                  | video `STREAMS` that should be transcoded                       |
| PHOTOPRISM_FFMPEG_MAP_AUDIO                                      | --ffmpeg-map-audio      | `0:a:0?`                                 | audio `STREAMS` that should be transcoded                       |
| PHOTOPRISM_EXIFTOOL_BIN                                          | --exiftool-bin          | exiftool                                 | ExifTool `COMMAND` for extracting metadata                      |
| PHOTOPRISM_SIPS_BIN                                              | --sips-bin              | sips                                     | Sips `COMMAND` for media file conversion *macOS only*           |
| PHOTOPRISM_SIPS_EXCLUDE, PHOTOPRISM_SIPS_BLACKLIST               | --sips-exclude          | avif, avifs, thm                         | file `EXTENSIONS` not to be used with Sips *macOS only*         |
| PHOTOPRISM_DARKTABLE_BIN                                         | --darktable-bin         | darktable-cli                            | Darktable CLI `COMMAND` for RAW to JPEG conversion              |
| PHOTOPRISM_DARKTABLE_EXCLUDE, PHOTOPRISM_DARKTABLE_BLACKLIST     | --darktable-exclude     | thm                                      | file `EXTENSIONS` not to be used with Darktable                 |
| PHOTOPRISM_DARKTABLE_CACHE_PATH                                  | --darktable-cache-path  |                                          | custom Darktable cache `PATH`                                   |
| PHOTOPRISM_DARKTABLE_CONFIG_PATH                                 | --darktable-config-path |                                          | custom Darktable config `PATH`                                  |
| PHOTOPRISM_RAWTHERAPEE_BIN                                       | --rawtherapee-bin       | rawtherapee-cli                          | RawTherapee CLI `COMMAND` for RAW to JPEG conversion            |
| PHOTOPRISM_RAWTHERAPEE_EXCLUDE, PHOTOPRISM_RAWTHERAPEE_BLACKLIST | --rawtherapee-exclude   | dng, thm                                 | file `EXTENSIONS` not to be used with RawTherapee               |
| PHOTOPRISM_IMAGEMAGICK_BIN                                       | --imagemagick-bin       | convert                                  | ImageMagick CLI `COMMAND` for image file conversion             |
| PHOTOPRISM_IMAGEMAGICK_EXCLUDE, PHOTOPRISM_IMAGEMAGICK_BLACKLIST | --imagemagick-exclude   | heif, heic, heics, avif, avifs, jxl, thm | file `EXTENSIONS` not to be used with ImageMagick               |
| PHOTOPRISM_HEIFCONVERT_BIN                                       | --heifconvert-bin       | heif-convert                             | libheif HEIC image conversion `COMMAND`                         |
| PHOTOPRISM_RSVGCONVERT_BIN                                       | --rsvgconvert-bin       | rsvg-convert                             | librsvg SVG graphics conversion `COMMAND` *plus*                |
