### ISSUE TITLE
Enable option to display image/video detailed properties in a single image/vid view

### ISSUE THREAD

**Issue by typekpb** [photoprism/photoprism#3985]
**Describe what problem this solves and why this would be valuable to many users**

None of the icons showing the image enables me to display photo details:
<img width="362" alt="image" src="https://github.com/photoprism/photoprism/assets/499820/306ceea1-7750-4b27-9f54-baf2b550aa77">

**Describe the solution you'd like**

I'd like to have additional toggle, that would display picture/video details next (or under the) shown image.

**Describe alternatives you've considered**

The only option seems to get back to overview and toggle view type using: 
<img width="48" alt="image" src="https://github.com/photoprism/photoprism/assets/499820/0bf33092-c6b4-4e7b-988d-b80b6115c3f1">

**Additional context**

**Comment by graciousgrey** [comment]
Thank you very much for your feedback!

This is planned as part of this issue:

- https://github.com/photoprism/photoprism/issues/1307

I will therefore close this as duplicate.
