### ISSUE TITLE
Wrong Auto Geotagging with Polish city names.

### ISSUE THREAD

**Issue by PiotrEsse** [photoprism/photoprism#399]
Hi, I found a bug where PP cant show location but images in fact contain valid Geolocation data. 

Way to replicate bug:
1. photos have geolocation data
2. photoprism cannot determine the country
3. PP sometimes adds valid tags
4. Such photos fall into the "unknown" location category

5. To solve the issue You just specify the country when editing the photo and all data appear correctly - street, city, etc.

It may have something to do with Polish signs for the city. Noticed with the city of Polska / GDAŃSK

**Comment by lastzero** [comment]
Can you provide us with example files for testing?

**Comment by lastzero** [comment]
Might be related to #380. I'll try with random coordinates in Poland. Still would be helpful to get more details for testing.

**Comment by lastzero** [comment]
Works for me, but I assume there are specific coordinates that are broken because of incoherent OpenStreetMap data. So in order to really debug and fix this, we need coordinates and/or a test image from you.

![Screenshot 2020-07-14 at 13 36 50](https://user-images.githubusercontent.com/301686/87421353-19389300-c5d7-11ea-8b16-24b23d382f71.png)

**Comment by PiotrEsse** [comment]
To be correct - it works for me most of the time ;-)

**Comment by PiotrEsse** [comment]
More wrongly tagged pictures
![20190309-130718-Unknown-2019-32f](https://user-images.githubusercontent.com/42764623/87506741-56029980-c66c-11ea-9a14-182462d109cc.jpg)
![20190531-130604-Unknown-2019-194](https://user-images.githubusercontent.com/42764623/87506746-59962080-c66c-11ea-9c39-0dab2c9a2bfc.jpg)
![20200323-154652-Info-2020-2k0](https://user-images.githubusercontent.com/42764623/87506757-6155c500-c66c-11ea-9f15-556c83043eb7.jpg)
![20200416-143434-Museum-2020-316](https://user-images.githubusercontent.com/42764623/87506761-63b81f00-c66c-11ea-8a71-8fce06b7a4d2.jpg)
![20200501-113047-Unknown-2020-3cp](https://user-images.githubusercontent.com/42764623/87506779-70d50e00-c66c-11ea-993b-4ba0cd2ccbfc.jpg)
![20200519-173951-Unknown-2020-1j0](https://user-images.githubusercontent.com/42764623/87506788-75012b80-c66c-11ea-92aa-11578cc9d7ec.jpg)

**Comment by PiotrEsse** [comment]
ups, closed by accident...

**Comment by lastzero** [comment]
Amazing, thank you!

Migrated your backend translation to gettext by the way, so that we have a common toolset: https://github.com/photoprism/photoprism/tree/develop/assets/locales/pl

**Comment by PiotrEsse** [comment]
> Amazing, thank you!
> 
> Migrated your backend translation to gettext by the way, so that we have a common toolset: https://github.com/photoprism/photoprism/tree/develop/assets/locales/pl

Thank You!

**Comment by lastzero** [comment]
Looks good to me, wouldn't know what to improve? Added Huawei models P20 / P20 Pro and removed automatically generated image descriptions for you though :)

![Screenshot 2020-07-15 at 09 26 06](https://user-images.githubusercontent.com/301686/87516177-42136380-c67d-11ea-9886-2d7edb3840c1.png)

**Comment by lastzero** [comment]
Can you try again using a fresh PhotoPrism instance with empty storage directory and database?

**Comment by PiotrEsse** [comment]
I should remove /originals folder or just do complete rescan?

**Comment by lastzero** [comment]
Don't delete your originals, please :) Just automatically created JSON or YAML sidecar files. They can hold a backup of the database, so just deleting the database won't remove all previously indexed data. They should be in a separate directory, depending on your configuration (see `docker-compose.yml`). When using Docker, you might have to remove the volume with `docker volume rm`, unless it'a mounted to a regular host directory where you can simply delete the sidecar files.

**Comment by lastzero** [comment]
Note that we're continuously updating our example `docker-compose.yml` files, to reflect recent changes in configuration like new or renamed parameters: https://dl.photoprism.org/docker/docker-compose.yml

**Comment by PiotrEsse** [comment]
I have defauly docker-compose.yml version 3.3 from Your link. 
I found  sidecar files in:
 _/var/lib/docker/volumes/root_photoprism-storage/_data/sidecar_

Should I delete all subfolders there? (I have subfolders with years - ie 2014..2015..2016...etc)

**Comment by lastzero** [comment]
Yes, it's safe to delete them, alternatively you can change the volume name in docker-compose.yml

**Comment by PiotrEsse** [comment]
An update. 
Yesterday Ive deleted all sidecar files and reindex files again. Theres still the same issue - some files are not properly updated with country tag. But I doscover another bug - Ill fill new issue right away.
![20200523-123536-Warsaw-Poland-2020-41n](https://user-images.githubusercontent.com/42764623/87638497-2aeb7900-c744-11ea-91e7-c491d8fb86c8.jpg)

**Comment by PiotrEsse** [comment]
Additionally I found bug in logs: 
![2020-07-16 09_22_03-Album_ PhotoPrism](https://user-images.githubusercontent.com/42764623/87639716-f4166280-c745-11ea-8b95-34356961b678.png)

**Comment by lastzero** [comment]
Can we close this? I'm sure there is some "bad" geo data every once in a while but that needs to be fixed over time for specific coordinates.

**Comment by PiotrEsse** [comment]
Yes, close this. Will take care later ;-)

**Comment by PiotrEsse** [comment]
Dear Michael,
sure Ive closed this. We ll take care about this later if any issue arrise.
-- 
-- 
Pozdrawiam serdecznie,
*Piotr Esse
*
------------------------------------------------------------------------

|Mobile: +48 506392139 | E-mail: piotr.esse@spero.click 
<mailto:piotr.esse@spero.click> |

  * /Zgłoszenia prosimy przesyłać na adres naszego systemu:
    *zgloszenia@spero.click*/
  * /**Jeśli jesteś już naszym klientem - *zaloguj się
    <https://spero.click/pm/clients/login>* na Twój panel klienta aby
    dodawać i sprawdzać Twoje zgłoszenia oraz mieć dostęp do innych
    informacji odnośnie naszej wspólnej współpracy./
  * /Jeśli nie masz dostępu do panelu klienta - zgłoś brak dostępu. /
  * /**Baza wiedzy: zanim zadasz pytanie - zajrzyj do naszej *bazy
    wiedzy <https://spero.click/pm/knowledge-base>**
    */

/Ta wiadomość może zawierać informacje, które są uprzywilejowane, poufne 
i nie podlegają ujawnieniu na mocy obowiązującego prawa. Jeśli czytelnik 
tej wiadomości nie jest zamierzonym odbiorcą lub agentem odpowiedzialnym 
za dostarczenie jej do zamierzonego odbiorcy, zostajesz powiadomiony, że 
otrzymałeś tę wiadomość elektroniczną omyłkowo oraz, że wszelkie 
przeglądy, rozpowszechnianie, rozpowszechnianie lub kopiowanie tej 
wiadomości jest surowo zabronione. Jeśli otrzymałeś tę wiadomość 
elektroniczną przez pomyłkę, powiadom nas natychmiast e-mailem i usuń 
oryginalną wiadomość ze swojego systemu. Dziękujemy za zrozumienie.
This message may contain information that is privileged, confidential 
and exempt from disclosure under applicable law. If the reader of this 
message is not the intended recipient, or an agent responsible for 
delivering it to the intended recipient, you are hereby notified that 
you have received this electronic message in error and that any review, 
dissemination, distribution or copying of this message is strictly 
prohibited. If you have received this electronic message in error, 
please notify us immediately by email, and delete the original message 
from your system. Thank you. /


Michael Mayer wrote on 03.09.2020 08:38:
