### ISSUE TITLE
Are there any mistake in this div tag? 

### ISSUE THREAD

**Issue by capraynor** [photoprism/photoprism#3991]
Reading PP code in these days, trying to create timeline feature. 

Are there any mistake in this tag? The div tag should not be self-closed. 

If you think that should not be like this please tell me, I'll modify it. 

https://github.com/photoprism/photoprism/blob/cc356abe03dd4bdfa9ac60472e0b6b04ec96e96c/frontend/src/component/photo/list.vue#L56

**Comment by capraynor** [comment]
<img width="685" alt="image" src="https://github.com/photoprism/photoprism/assets/3467515/ecc81fc0-d0b5-45ac-8cf6-45fecd97caf1">

Sorry may be this is a special usage in Vue (v-if and v-else), is that true?

**Comment by lastzero** [comment]
It's obviously not correct based on the HTML standard, but might still work since all templates and JS are transpiled before they are displayed in a browser? Feel free to change this.
