### ISSUE TITLE
Store metadata in the filesystem

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#4]
In order to be able to copy the archive or restore database contents after a problem, it would be very convenient to store a copy of the metadata in the filesystem right next to the photos they belong to.

Contents need to be time stamped and fingerprinted in order to avoid sync/merge issues.

YAML, JSON or XML? Are there existing standard formats?

This way we could also store the original filename during import (simply write it to this file).

**Comment by eliasp** [comment]
What about writing those kind of metadata in a way where they aren't detached from the actual file, e.g. [FDO CommonExtendedAttributes](https://www.freedesktop.org/wiki/CommonExtendedAttributes/) on Linux/OS X (see also: https://gist.github.com/gwpl/a00e18bc150f1e3518335d13c5e46ad7), [NTFS Alternate Data Streams](https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/) on Windows?

**Comment by eliasp** [comment]
Unfortunately yes :(

**Comment by husayt** [comment]
This is very important. I have stumbled on this issue so many times with Picasa. Had all my metadata overwritten if by mistake forgot to have a harddrive with photos connected. Metadata needs to be next to images and in some readable/editable format like json/xml.

**Comment by tendant** [comment]
This is a great idea. Text file has a lot of benefits for backup purpose. Format like YAML can be easily tracked in version control system like git, most of editing conflict can be resolved automatically.  It can be edited using text editor when needed.

**Comment by lastzero** [comment]
Darktable docs for sidecar files: https://www.darktable.org/usermanual/en/sidecar_files.html

**Comment by lastzero** [comment]
Created a wiki page for XMP sidecar files: https://github.com/photoprism/photoprism/wiki/XMP

**Comment by splitbrain** [comment]
Personally I'd prefer to have the meta data written back to the image file (as XMP/IPTC/Exif tags). That way the info is not lost when the image is moved or copied somewhere else (and reimported in a different instance).

**Comment by lastzero** [comment]
@splitbrain That way, the md5/sha fingerprint would change, which makes it much more difficult to detect duplicate imports. Also XMP files are human readable, other than binary data inside image files.

**Comment by lastzero** [comment]
Still think we should do this, maybe soon. Using XMP seems difficult and we can't write data back to XMP files yet: https://github.com/photoprism/photoprism/wiki/XMP

**Comment by jagot** [comment]
I would vote for [TOML](https://github.com/toml-lang/toml)

**Comment by lastzero** [comment]
Implemented. Please open a new issue if you find bugs!
