### ISSUE TITLE
PhotoPrism Folders tab not displaying every folder available

### ISSUE THREAD

**Issue by srahimeen** [photoprism/photoprism#4006]
#### 1. What is not working as documented?

I am running PhotoPrism on my Synology DS923+. PhotoPrism Build 231128-f48ff16ef.

I have PhotoPrism pointing to a folder called "Google Photos" on my NAS volume.

![image](https://github.com/photoprism/photoprism/assets/9031145/7ac50596-5214-4c39-b52a-6f1e8a0758fd)

Within this folder, I have many other sub-folders which contain photos and videos. However, many of these folders don't show up in the PhotoPrism Folders tab.

For example, I have this folder:
![image](https://github.com/photoprism/photoprism/assets/9031145/a0c53f7c-7824-4839-990b-42d3787ece80)

However, when I go to my PhotoPrism Folders tab, the only folder with the word "2018" in it is this:
![image](https://github.com/photoprism/photoprism/assets/9031145/cc1f60af-fa89-4c85-8a0c-d4724918ad75)

Which is also another folder in the base "Google Photos" folder. However, I want every folder in my Google Photos folder to show up here.

How can I achieve this?

#### 2. How can we reproduce it?

1. Point PhotoPrism to a folder.
2. Create a sub-folders in that folder.
3. Add various images and videos in those sub folders.
4. Go to Library -> Scan in PhotoPrism and complete the scan.
5. Notice that every single sub-folder does not show up in the PhotoPrism Folders tab.

#### 3. What behavior do you expect?

I expect every sub-folder inside the base "Google Photos" folder to show up in the PhotoPrism Folders tab.

#### 4. What could be the cause of your problem?

Not sure. Maybe there are a duplicates somewhere and PhotoPrism is excluding folders because of that? The "Photos from Year" also include the same files, but I use folders to organize so I want to be able to see them in the Folders tab.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Please include sample files or screenshots that help to reproduce your problem. You can also email files or share a download link, see <https://www.photoprism.app/contact> for details.

Visit <https://docs.photoprism.app/getting-started/troubleshooting/browsers/> to learn how to diagnose frontend issues.

**Important: If it is an import, indexing or metadata issue, we require sample files and logs from you.** Otherwise, we will not be able to process your report. If it is an import problem specifically, please always provide us with an archive of the files before you imported them so we can reproduce the behavior.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

PhotoPrism® CE
Build 231128-f48ff16ef

Running on Synology DS923

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

MariaDB 11.1.2+maria~ubu2204

(c) Operating System Types & Versions: Linux, Windows, Android,...

Synology DSM 7.2-64570 Update 1

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...

Chrome on Windows 10

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

uBlock Origin, but same issue if it is disabled.

You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

Synology DS923+

(b) Physical Memory & Swap Space in GB

4 GB DDR4 ECC SODIMM

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

4 x Seagate IronWolf 8TB NAS Hard Drive

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No.

**Comment by graciousgrey** [comment]
This is how the software currently works. If it has already indexed a file it won't index it again. 
We do already have a related feature requests to improve this:
- https://github.com/photoprism/photoprism/issues/1306

See also:
https://docs.photoprism.app/user-guide/use-cases/google/#transfer-albums

**Comment by srahimeen** [comment]
Good to know its in the works, thanks!
