### ISSUE TITLE
No logs displayed when transcoding fails due to bitrate

### ISSUE THREAD

**Issue by rgstori** [photoprism/photoprism#4012]
#### 1. What is not working as documented?

When trying to play/transcode a video whose bitrate is above the limit (default 50 Mbps), the player fails silently. I've set container logs to trace level and no logs are displayed either.

#### 2. How can we reproduce it?

1. Have a video whose bitrate is above the limit, and needs transcoding (e.g. a random 4K HEVC video taken on my Pixel phone at 64 Mbps)
2. Try to play it
3. Player fails silently, no logs in the container beyond
```
time="2024-01-17T09:46:45Z" level=debug msg="video: 2023/12/20231231_130036_F3771AB3.mp4 is HVC1 encoded and cannot be streamed directly, average bitrate 62.5 MBit/s"
time="2024-01-17T09:46:45Z" level=debug msg="server: GET /api/v1/videos/ad95a6e94a1171a7c0b3281eae882f50020903e1/3so80eqh/hevc (206) [34.082614ms]"
```
and nothing else. The player just shows the thumbnail.

When increasing the bitrate limit, the video plays fine.

#### 3. What behavior do you expect?

When transcoding fails due to the video being above the limit, an error should be displayed in the player, or at least it should be logged in the container.

#### 4. What could be the cause of your problem?

The cause might be the video bitrate check that doesn't throw errors when failing.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

sample 4k hevc video here: https://www.dropbox.com/scl/fi/odsdirr3zqopt009tqljx/PXL_20231231_130004482.mp4?rlkey=ldnvt237f8as8lrcuflm7qmx6&dl=0

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: amd64 - Build 231128-f48ff16ef

(b) Database Type & Version: MariaDB 10.11

(c) Operating System Types & Versions: Linux (synology)

(d) Browser Types & Versions: Chrome 120.0.6099.216

(e) Ad Blockers, Browser Plugins, and/or Firewall Software - none

#### 7. On what kind of device is PhotoPrism installed?

Synology NAS DS720+

(a) Device / Processor Type: Intel Celeron J4125

(b) Physical Memory & Swap Space in GB: 10 GB RAM / 7.7 GB Swap

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage : HDD

**Comment by graciousgrey** [comment]
Thank you very much for reporting.

As far as I remember videos that cannot be streamed directly are always transcoded even if they exceed the bitrate limit. 

Is it possible that transcoding just took a while, so you got the impression it was not working? 
I tested with your file and a bitrate limit of 5. After pressing play PhotoPrism started transcoding the video as expected. It just took a while for the video to play.

**Comment by lastzero** [comment]
I would think that the transcoding takes a little time, which is why the video does not play instantly. How the bitrate limit works and when not is described in your documentation:
- https://docs.photoprism.app/getting-started/advanced/transcoding/#bitrate-limit

Also see our regular User Guide:
- https://docs.photoprism.app/user-guide/organize/video/#transcoding

Should it be a problem with FFmpeg, e.g. a crash with your files, then it would be best if you let them know, as we do not maintain the software and thus may not be able to do much.
