### ISSUE TITLE
People: show favorites first when selecting name

### ISSUE THREAD

**Issue by stephanvierkant** [photoprism/photoprism#4019]
I'm tagging people and I've to type the name every time. But for the most photos it's me, my wife or my children (not recognised very well).

It would be great to have favorite people first, so it's easier to select the name.

Another idea: show names of people who are already in the current directory/album at the top as well.

**Comment by graciousgrey** [comment]
This looks very similar to this request:

- https://github.com/photoprism/photoprism/issues/1865

Feel free to leave a :+1: in there :)
