### ISSUE TITLE
File Browser: Follow symlinks

### ISSUE THREAD

**Issue by bobobo1618** [photoprism/photoprism#403]
When you symlink folders into `/originals`, the indexer will happily pick them up but `/api/v1/folders/originals` will return 0 results.

The `FoldersByPath` function, which is used to display folders, [uses](https://github.com/photoprism/photoprism/blob/0a4dc155e6c259437122790769bc6715fe3b0bd0/internal/query/folders.go#L12) `fs.Dirs`, which [only uses](https://github.com/photoprism/photoprism/blob/0a4dc155e6c259437122790769bc6715fe3b0bd0/pkg/fs/dirs.go#L96-L97) `os.FileMode` to determine whether something is a directory or not.

I think this logic should either read the folders from the `folders` table or use the same logic to traverse the filesystem that the indexer does, to avoid inconsistencies.

**Comment by lastzero** [comment]
Closing this since there was no more feedback. Seems to work.
