### ISSUE TITLE
Idea to Improve UX - unselect selected photos on list with one click

### ISSUE THREAD

**Issue by PiotrEsse** [photoprism/photoprism#404]
When I am using photos list to select photos for edit I very often want to unselect them after making changes. On the main list I dont see any option to unselect and end up with browsing through many pictures to finally find the one which is selected. 
Sometimes its quite hard and timeconsuming. 

I propose to add an Icon with option to unselect any selected picture with one click to floating menu to the right

![2020-07-15 07_33_33](https://user-images.githubusercontent.com/42764623/87507436-ad553980-c66d-11ea-951f-47ba29d5d604.jpg)

**Comment by lastzero** [comment]
The X at the top should unselect all?

**Comment by PiotrEsse** [comment]
ahh, does this works that way now? I thought X stands for picture deletion...

**Comment by lastzero** [comment]
We only use red buttons for removing contents. Good to know that's not completely clear!

It's described here at the bottom (work in progress):

https://docs.photoprism.org/user-guide/navigate/

**Comment by PiotrEsse** [comment]
Thank You!!

**Comment by eigan** [comment]
Maybe the FAB shouldn't be used for selected items? 

It might be more clear if the toolbar was used instead. 

Google Photos:
![2020-07-15_10-09](https://user-images.githubusercontent.com/41789/87520433-417dcb80-c683-11ea-857b-0c69a8d009fc.png)


Resources:
- https://material.io/components/app-bars-top (Contextual action bar)
- https://material.io/design/interaction/selection.html (see the example videos)
- https://material.io/components/buttons-floating-action-button#behavior

**Comment by lastzero** [comment]
You can always do things differently, especially when it leaves more space for the actual content on mobile. Bottom right is a convenient position for the thumb. Besides, Google Photos is not the gold standard in UX for us. Otherwise we could just copy it 1:1.

**Comment by eigan** [comment]
> it leaves more space for the actual content on mobile

Looking at the implementations, it doesnt actually remove any space? Just replaces the top bar which is already visible anyway.

I tried finding an app on my phone that didn't use the contextual action bar, but I couldnt find any. Even the PhotoPrism app uses the contextual action bar. Obviously there might exist many apps that do use the FAB for this, I don't have them all, heh :)

**Photoprism**
![2020-07-15_10-39](https://user-images.githubusercontent.com/41789/87523909-d1257900-c687-11ea-9b6f-f2b9391a9ea4.png)

**Todoist** was the only one not using the bar at top.
![photo_2020-07-15_10-39-20](https://user-images.githubusercontent.com/41789/87523915-d5ea2d00-c687-11ea-9fd4-dd55461ce55d.jpg)

**Comment by lastzero** [comment]
Basically every app has their most important action (typically add / create / compose) where the thumb is on mobile, that means bottom right. For us, the most important actions are create album, edit, delete & share. Wouldn't make sense just to offer one of those. Also can't add more elements to the top bar, it already contains the page title, sidenav & upload button.

**Comment by lastzero** [comment]
Google Photos, Huawei Gallery and Apple use a [bottom navigation](https://v15.vuetifyjs.com/en/components/bottom-navigation) for their apps. That limits the number of navigation items, we offer a lot more and need the vertical space. Note that there also is a PhotoPrism mobile app with reduced functionality in development, see https://github.com/photoprism/photoprism-mobile. It uses a bottom navigation for those who prefer it.

**Comment by eigan** [comment]
> Note that there also is a PhotoPrism mobile app

I added screenshot from that app which _do_ use the contextual action bar, see comment above.


> Offer a lot more and need the vertical space

The contextual action bar replaces the top bar, so no space should be sacrificed.


I understand that you do not want to change the current behaviour _(which is ok)_, and it seems like you have reflected more about this than me, so I will put this to rest now.

**Comment by lastzero** [comment]
We'll keep an eye on this and and are thankful for every feedback! You're welcome to create an issue whenever you have a (probably) good idea.

I think our clipboard button is different (maybe more powerful?) from how many mobile apps handle selection. As you've observed, a dedicated select mode often forces users to apply an action, like share, before they can continue doing something else. That's easier for users and developers, but limits functionality.

**Comment by dmitryivashkin** [comment]
I was so confused by it, also because selections are sticky - tried to refresh the browser page to get rid of selection. Only then did I realize that the "x" button in the popup doesn't just close the popup, but clears the selection!

**Comment by lastzero** [comment]
@dmitryivashkin Otherwise, you would not be able to select multiple pictures across search results, and you would lose your current selection if your browser unexpectedly restarted or you accidentally reloaded the current tab.

As we are currently upgrading the UI to a new major version, we will also try to improve the UX for selecting pictures:
- https://github.com/photoprism/photoprism/issues/3168
