### ISSUE TITLE
BUG: Incorrect Creation/Modification Date for Uploaded Files

### ISSUE THREAD

**Issue by jtamm-red** [photoprism/photoprism#4042]
#### 1. What is not working as documented?
The uploaded file displays an incorrect date, reflecting the date of upload rather than the original file's date. It is crucial for the file date to accurately reflect the original creation date of the file. PhotoPrism relies on extracting EXIF metadata exclusively from the file itself to determine the correct date. Therefore, it is imperative to rectify this discrepancy to ensure accurate and meaningful organization of files within the system.

#### 2. How can we reproduce it?

1. Launch PhotoSync on your Android device.
2. Tap the red sync icon.
3. Navigate to the 'Send' tab and select 'New.'
4. Choose 'PhotoPrism' as the destination.
Please note that the transfer process may take a few minutes.

To verify the uploaded date of the transferred files on the PhotoPrism server:
1. Access the PhotoPrism server terminal.
`docker exec -it photoprism bash`
2. Navigate to the directory containing the original files.
`cd /photoprism/originals/`
3. List all folders in the current directory.
`ls -la`
4. Enter the sub-folder where your files are located.
`cd Camera`
5. List all files in the Camera.
`ls -la`
5. To check the upload date of a specific file, run the following command:
`stat IMG_20230412_133303.jpg`
This will provide detailed information, including the file's upload date.
You can make a comparison between the file's birth date and its filename, specifically looking for the datetime '20230412_133303' (which corresponds to April 12, 2023, 13:33 GMT+3).

#### 3. What behavior do you expect?

The file's date should accurately reflect the original creation date. This is crucial for easy sorting by date in file explorers. For instance, during maintenance tasks such as copying files to a backup external USB HDD, it is imperative that the file dates are not incorrect. Maintaining accurate file dates ensures a smooth and efficient organization of files, facilitating hassle-free processes such as backups.

#### 4. What could be the cause of your problem?

Dealing with files that have incorrect dates can lead to confusion and hinder the ability to filter or sort them based on date. In such cases, relying on EXIF metadata becomes necessary, but reading this metadata can be time-consuming, especially when dealing with a large number of files, such as 100,000. Unfortunately, standard file explorers lack built-in EXIF reading features, requiring the use of external applications. This process can be cumbersome and complex, making it challenging to efficiently manage and organize files with accurate date information.

Sometimes the date appears as unknown on the PhotoPrism page (refer to the screenshot below). I have to manually inspect each file and update the correct date, a process that consumes a significant amount of time.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

The datetime display on the PhotoPrism page appears unusual, with the time consistently showing as '00:00:00'.
![image](https://github.com/photoprism/photoprism/assets/53046846/ed5fa957-3267-49b7-bfda-923a6575de19)

Compare the date of upload with the original creation date of the file.
![image](https://github.com/photoprism/photoprism/assets/53046846/66e0a26a-6640-43b9-ab2b-cfed4a8eda86)

The file date is accurately displayed on the Android Explorer.
![image](https://github.com/photoprism/photoprism/assets/53046846/61e2251e-f570-42f0-b1d6-68dd466bd93a)

Curiously, the fields for day, month, and year appear as 'Unknown,' while the time is displayed correctly.
![image](https://github.com/photoprism/photoprism/assets/53046846/32129b8e-dc2b-4dd8-9576-36b713fdd2d8)

Upon executing the command 'stat 20240113_192341_635.mp4,' it is observed that the Birth and Change dates are displayed incorrectly. The timestamp '2024-01-26 21:31:15' signifies the time at which the file was uploaded.
![image](https://github.com/photoprism/photoprism/assets/53046846/8a5c386e-8b6e-4793-aa2f-9dde6dfccab0)

The datetime is accurately displayed on the Android Explorer.
![image](https://github.com/photoprism/photoprism/assets/53046846/7240b507-d95f-4b22-903c-7bc234ae6bd1)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: ARM64 231128-f48ff16ef

(b) Database Type & Version: MariaDB 11.1.2+maria~ubu2204

(c) Operating System Types & Versions: Linux 5.10.160

(d) Docker 20.10.22, build 3a2c30b

(e) PhotoSync 4.0.10 (5786) for android

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: NanoPi R6C / RK3588S

(b) Physical Memory: 8GB

(c) Storage Type: 32GB eMMC, 500GB NVMe

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by graciousgrey** [comment]
Since "Unknown" is displayed in the editing dialog, I assume that your photos only have a modification date, but no real taken date.

If there is no taken at date we do use the file modification date for sorting, but we do not set it as the date taken because it is not necessarily the date the photo was taken.

You can see the metadata of your files by running `exiftool -j filename.jpg`

In case of your whats app images we extracted the date from the filename this is why day, month and year are set but the time is 00:00.

Currently, the modification date of files is updated when the files are synchronized with webdav. Improvements for this behavior are already in progress.

https://github.com/photoprism/photoprism/issues/3959
