### ISSUE TITLE
MariaDB: Show info when waiting for the database to become available

### ISSUE THREAD

**Issue by bradsk88** [photoprism/photoprism#4059]
#### 1. What is not working as documented?

I moved my server to a new network, which caused my IP subnet to change. 

After booting up photoprism, I was met with this when I tried to open the web UI.

![image](https://github.com/photoprism/photoprism/assets/2147630/1ae113eb-93bd-4dc1-8201-032b1080ebe9)

It had been a long time since I set up my docker container. And I forgot that the `PHOTOPRISM_DATABASE_DSN` environment variable included an IP address - which was using the old subnet.

The logs on the docker container do not show any indication of a problem:
```
text  error  warn  system  array  login  

started 231128 as root (amd64-prod)
init: updating filesystem permissions
PHOTOPRISM_DISABLE_CHOWN="true" disables permission updates
init: https
Creation of a default HTTPS/TLS certificate is skipped because PHOTOPRISM_DEFAULT_TLS is "false".
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
switching to uid 99:100
/opt/photoprism/bin/photoprism start
```
#### 2. How can we reproduce it?

Update a working PhotoPrism container to have an invalid IP address in `PHOTOPRISM_DATABASE_DSN`. 

#### 3. What behavior do you expect?

The logs should indicate that the IP address from the environment variable does not correspond to a real DB.

#### 4. What could be the cause of your problem?

Explained everything I know, above.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

See above

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 231128-f48ff16ef

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux (Unraid)

(d) Browser Types & Versions: Firefox

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? No

#### 7. On what kind of device is PhotoPrism installed?

Skipping

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN? 

No

**Comment by lastzero** [comment]
It's trying to connect a few times in case the database server has been started and becomes available after PhotoPrism has been started, which is a  common scenario in Docker environments. How long did you wait until you came to the conclusion that there are no logs? Did you try enabling trace or debug log mode to get additional information? Did you check the troubleshooting checklists we provide as these mention this exact issue?

**Comment by bradsk88** [comment]
@lastzero Yes. I reviewed the troubleshooting checklist. Can you point out exactly where it mentions this issue?

I let the container sit for several hours before concluding it was a bug.

**Comment by bradsk88** [comment]
Deleted my previous comment. After attempting another reproduction with debug logs enabled, I do see that it emits "no such host" a few moments after the container boots up.

This is a UX bug. The logs seem to "resolve successfully" very quickly - leading people like me not to notice the additional logs that get appended after a few minutes.

Clarifying the logs to make it easier to understand that the start-up process has not yet completed would go a long way.

**Comment by lastzero** [comment]
It could also lead to tools that watch the logs to shut down the stack while the mariadb host simply isn't up yet and still starting. How do we know that this isn't the case? We could add yet another config options for those who do not want photoprism to wait and who do not want to change the log level?

**Comment by lastzero** [comment]
Maybe some info logs like "waiting for database to become ready..." could be added if it helps?

**Comment by lastzero** [comment]
I have added an info log for you. Note, however, that the exact behavior depends on the type of host the IP is pointing to. For example, our firewall will always let the client run against a timeout (even if there is no database running on the firewall that the client could connect to). This info log MAY therefore not be displayed immediately, as your network configuration and the hosts in your network are not under our control.

**Comment by lastzero** [comment]
This can now be tested with the `photoprism/photoprism:test` image available on Docker Hub.

**Comment by bradsk88** [comment]
Definitely an improvement. Ideally, I would have liked to see something here:
![image](https://github.com/photoprism/photoprism/assets/2147630/ad21bb64-3255-45f6-9cf9-3a2fd6783f13)

because that's where it "hangs" for a few minutes before the "no such host" errors start to come in.

**Comment by lastzero** [comment]
@bradsk88 It might be worth checking why a simple name / IP lookup is taking so long?

**Comment by lastzero** [comment]
@bradsk88 Based on your feedback, these changes introduce a default timeout of 15 seconds for establishing a connection to a database server. 

You will be able to change it to a value between 1 and 60 (seconds) by using either the CLI flag `--database-timeout` or the environment variable `PHOTOPRISM_DATABASE_TIMEOUT`.

**Comment by lastzero** [comment]
An updated preview build will be available for you shortly so that you can test it again with these changes:
- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by bradsk88** [comment]
Perfect, I've updated the preview and it looks like it emits the database connection message shortly after the other initialization steps have completed. 👍🏼 

Thanks for improving this.
