### ISSUE TITLE
Albums: Fix links to albums in the settings tab of the edit dialog

### ISSUE THREAD

**Issue by gconklin** [photoprism/photoprism#4060]
#### 1. What is not working as documented?

When you edit a photo (pencil icon), click the gear, click one of the "Albums" links, goes to just /library and not the album.

#### 2. How can we reproduce it?

1. Create some albums
2. Tag/keyword a picture with something unique to find it more easily later.
3. Add said photo to the albums in step 1.
4. Go to search.
5. Search for the tag in step 2.
6. Click photo.
7. Click pencil.
8. Click gear.
9. See the list of albums you assigned in step 3.
10. None of those links take you to the specific album.

#### 3. What behavior do you expect?

I expect the album I clicked on to open and show all of the images in it.

#### 4. What could be the cause of your problem?

The link generated for the `a href` tag is incorrect. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

N/A

#### 6. Which software versions do you use?

(a) PhotoPrism® CE Build 231128-f48ff16ef

(b) MariaDB, idk, latest by docker standards

(c) Ubuntu

(d) Chrome

(e) Nothing noteworthy

**Comment by gconklin** [comment]
![image](https://github.com/photoprism/photoprism/assets/23655/28eee4d3-af40-4d69-a34a-ebe172d43352)

The links shown don't take you to the album listed.

**Comment by graciousgrey** [comment]
Thank you very much for reporting!

**Comment by lastzero** [comment]
@gconklin Note that this is a contributed feature and the behavior was an agreed upon compromise to make linking to at least one album possible. We would love to see this work with multiple albums as well. However, that requires additional work that no one has been willing to invest so far. Any help with this is much appreciated! ❤️

**Comment by gconklin** [comment]
Hi @lastzero - Thanks for the response.

> the behavior was an agreed upon compromise to make linking to at least one album possible

I would argue that links to albums on this page do not work at all. For example, in the image below, when I hover over the "Doors" album, the hot link will take me to /library/ and not to any album. I would say they should not be links at all and just regular text if the links don't work to avoid the confusion.

![image](https://github.com/photoprism/photoprism/assets/23655/8a647558-974d-44c8-913d-d86c0598bbad)

**Comment by gconklin** [comment]
![image](https://github.com/photoprism/photoprism/assets/23655/c2782a9c-5003-45b4-98e5-5e95f58187dc)

I would guess at this point, `a.url` is blank (a href="") and the browser is just using whatever the current navigation path is.

https://github.com/photoprism/photoprism/blob/9b62467741e61e0e8919687072abc68fd1605484/frontend/src/dialog/photo/edit/info.vue#L86

This is where it converts an album name into a url, and looks like it should be working, but I don't understand vue-js well enough:

https://github.com/photoprism/photoprism/blob/9b62467741e61e0e8919687072abc68fd1605484/frontend/src/dialog/photo/edit/info.vue#L389

**Comment by lastzero** [comment]
I can't remember all the details. Would you be able to check the related code and issue / pull request comments for how/if this was supposed to work?

**Comment by gconklin** [comment]
I can poke around some more, probably this evening. I am keen to generate some pull requests for things I have in mind in other areas, but I have no go and minimal js experience, so my barrier to entry is pretty high and I've been putting it off.

**Comment by gconklin** [comment]
2023-01-12 PR adding albums to info.vue without links:
https://github.com/photoprism/photoprism/pull/3095

2023-06-13 Commit that adds the 'a href' links, related to the PR, but not the PR:
https://github.com/photoprism/photoprism/commit/6a4bfa84be380c5a47f490cffa67ae663136e54f#diff-4c859fd6226af262b62a4a2133110b7605c19fa2e84cca592b182c7752b3acb4

**Comment by gconklin** [comment]
I'm sure this is the completely wrong way to fix this, but as a hack, it worked in my testing after setting up a dev env.

In `info.vue` replace:
`return this.$router.resolve({name: 'album', params: {uid: m.UID, slug: 'view'}}).href;`

with:
`return '/library/albums/' + m.UID + '/view';`

Doing that generated a link that takes you to the specific album.

I have no idea how $router.resolve is supposed to work, but what's there is not generating the correct link.

**Comment by lastzero** [comment]
@gconklin Thanks for insisting that this is broken! It looks like it was already working (I probably fixed it after the PR was merged) and the reason it stopped working is that the "uid" parameter in the album route had been changed to "album" in a previous refactoring. You can test my changes with the [next test or preview build](https://hub.docker.com/r/photoprism/photoprism/tags), e.g. on [demo.photoprism.app](https://demo.photoprism.app/).

**Comment by gconklin** [comment]
I didn't test the docker image, but I did play around on the demo site and it looks good and the links work as I expected!
Thanks for bearing with me and fixing this simple but useful feature.
