### ISSUE TITLE
File Browser: Show full file and folder names

### ISSUE THREAD

**Issue by bobobo1618** [photoprism/photoprism#408]
When I navigate my directory hierarchy, I expect to see the same thing I see on disk.

In particular, nearly all of my directory names have dates in them (e.g. 2020-07-15), have white space where white space should be and have proper capitalization. Any divergence from my chosen name is unwanted, though replacing underscores with spaces at least doesn't affect me.

So I'd like to either remove [this](https://github.com/photoprism/photoprism/blob/b314ef2a2792bfb75818d7c0c434c49de96c495b/internal/entity/folder.go#L119-L121) and everything like it or make it optional with a command-line flag.

**Comment by lastzero** [comment]
This can easily be solved / implemented in the frontent by displaying the path instead of title. 

Remember that we create flat albums from this. Using "10" as title is not helpful (even when accurate) considering the intended use case and the fact, that most users organize their library by year, month and day like "2019/10/18".

If you want to browse your files and folders in a desktop-like way, why not via WebDAV?

**Comment by bobobo1618** [comment]
> This can easily be solved / implemented in the frontent by displaying the path instead of title.

Sounds good to me. Should this be implemented as a frontend change with a setting stored in the browser's offline storage or something like that then?

> Remember that we create flat albums from this. Using "10" as title is not helpful (even when accurate) considering the intended use case and the fact, that most users organize their library by year, month and day like "2019/10/18".

That's fine and I can understand taking some liberties to handle albums but when the UI is presenting a navigation structure designed to emulate the filesystem, any deviations are confusing.

That said, I'd want this to be optional/customizable as well. For example would it make sense to use Go's templating system to allow users to come up with their own album names?

> If you want to browse your files and folders in a desktop-like way, why not via WebDAV?

I don't really want to browse my files and folders in a desktop-like way. I want to hierarchically organize and browse through my photos (which is fairly common, see all the desktop DAMs like Lightroom, Capture One and Darktable) and the filesystem is the only mechanism PhotoPrism currently offers through which to do that.
