### ISSUE TITLE
File Browser: PNGs look broken in the image viewer

### ISSUE THREAD

**Issue by bobobo1618** [photoprism/photoprism#409]
Per #38, IIUC, PNG wasn't intended to be supported but support was added in 3d990fc.

It looks like things are broken (in particular the image viewer doesn't work) in various places for a few reasons:
- The backend returns a type of "png" instead of "image" for PNG images but the frontend has a bunch of `=== 'image'` checks
- The backend doesn't seem to support width and height for PNG images unless it's expressed in EXIF (which is relatively rare)
- The backend generates sidecars and thumbnails but doesn't communicate the resulting aspect ratio metadata to the database or clients

I've been digging into this but I'm not 100% clear on how to fix it just yet. I've got bits and pieces working but the width/height from the database are particularly problematic.

I am however assuming that the missing width/height info is breaking the image viewer.

Note: I'm still mostly using the file browser.

**Comment by lastzero** [comment]
We basically treat PNGs like RAW files: Create a JPEG from it and use that to get the metadata, like width and height, we need.

The file browser in Library, so far, was not meant for starting a nice slide show on the couch, but for checking the index, and maybe downloading particular files or finding out what file was mapped to what photo. Wouldn't be totally surprised if PNGs cause issues in the photo viewer in that particular context. Maybe we should only allow viewing JPEGs, thought it would be nice to have some kind of fallback so that you can click on all files. 

Are PNGs also "broken" for you, when using the regular photo browser / search?

**Comment by bobobo1618** [comment]
Unfortunately I have over half a million files and it's impossible to navigate them without some kind of hierarchy, so I'm stuck with what I have.

It does appear to be a file browser-specific issue. When I search for a file by tags and click, everything works just fine.

**Comment by lastzero** [comment]
Think you mentioned "only" 400,000 files recently... anyhow, you seem to be the user with the most files so far :) Excellent test case!

Please be patient, doing my best to provide information and perform changes when needed. Be aware that our main focus for the rest of the month will be documentation, also taking a couple of days off after working so much.

Sounds like you could use some kind of hybrid view we have not developed yet. Grouping photos solely by folder, like many gallery apps do, is not our primary use case although of course possible using the technology and data in place.

Our primary use case is grouping personal photos (not files) dynamically by place, time and various classifications, explicitly including files from all folders and without cluttering search results with duplicates or sidecar files. We're aware that other use cases, like enterprise content management with millions of files sorted by product category, may have other requirements we can not fulfil with what we have at the moment.

**Comment by lastzero** [comment]
How did you open a PNG in the Photo Viewer? When I click on a non-JPEG file, it will be downloaded as you would expect based on what I explained above (fallback only used for preview thumbnails in the tile view):

![Screenshot 2020-07-16 at 15 32 53](https://user-images.githubusercontent.com/301686/87677193-c3e8b700-c779-11ea-97e3-e24d31b11efc.png)

**Comment by bobobo1618** [comment]
I just searched for a tag that happened to be on a PNG, it came up and I clicked it. I do have a sidecar generated for it but aside from that I don't think there's anything special.

Maybe I did something while I was trying to fix the problem that somehow did so persistently (e.g. wrote something to the database).

**Comment by lastzero** [comment]
This should not happen anymore since we now always open the edit dialog and not the photo viewer.

**Comment by lastzero** [comment]
Closing this, let us know when there are still issues :)
