### ISSUE TITLE
Cant save country data in a picture but PP say "changes successfully saved"

### ISSUE THREAD

**Issue by PiotrEsse** [photoprism/photoprism#410]
Theres an error with saving modified data to a pictures. 
PP wrongly state that is saved all modyfied data but in fact they are still untouched.
Please find this in a screencast. Its zipped webm.

[Play WebM on google drive](https://drive.google.com/file/d/1TIs3y7IduA5CqpiNG9HWApDWmtJ3byMc/preview)

**Comment by lastzero** [comment]
You mean modifying the original file? Or saving to the database doesn't work?

Note that you can't change the country where there are lat / long coordinates at the same time.

**Comment by lastzero** [comment]
As I thought, it's because there are coordinates with broken country data (which was your original issue). We need to disable the country dropdown in this case.

**Comment by PiotrEsse** [comment]
Hi, please see video - coordinates are not the same - Long and Lat are differnet on this example. The root of this bug is that PP shows "Successfull" label but didnt save data.

**Comment by lastzero** [comment]
It saves the data, then queries the country using the coordinates and changes the country to that and returning it to the frontend. Thus it looks like it was not saved.

**Comment by PiotrEsse** [comment]
Do You think I should remove completely PP and install it from the scratch? Will this help? I am updating PP very often so this should suffice but If You like I can removePP and install it from the beggining.

**Comment by lastzero** [comment]
I'll check your coordinates, you can wait for that if you like.

As mentioned, to avoid side effects when testing, it may help to completely wipe the database and storage directory (or rename the storage volume in docker-compose.yml). If you created sidecar files in your originals directory using an old release, you may also want to delete those (not default anymore).

**Comment by lastzero** [comment]
Kind of stuck here, since the coordinates in your video work locally and on our demo... I suspect an issue in our indexer when adding many files concurrently... how many CPU cores do you have? In that case, probably a small change needed to fix it, just hard to test.

![Screenshot 2020-07-16 at 13 21 18](https://user-images.githubusercontent.com/301686/87665575-6ba8b980-c767-11ea-8b8a-ca01e42165be.png)
![Screenshot 2020-07-16 at 13 21 14](https://user-images.githubusercontent.com/301686/87665579-6cd9e680-c767-11ea-89eb-6713834d0a5d.png)

**Comment by PiotrEsse** [comment]
> Kind of stuck here, since the coordinates in your video work locally and on our demo... I suspect an issue in our indexer when adding many files concurrently... how many CPU cores do you have? In that case, probably a small change needed to fix it, just hard to test.
> 
> ![Screenshot 2020-07-16 at 13 21 18](https://user-images.githubusercontent.com/301686/87665575-6ba8b980-c767-11ea-8b8a-ca01e42165be.png)
> ![Screenshot 2020-07-16 at 13 21 14](https://user-images.githubusercontent.com/301686/87665579-6cd9e680-c767-11ea-89eb-6713834d0a5d.png)

I use KVM with 8 cores of AMD opteron 4332HE cores, 4GB RAM. Node have 2xAMD Opteron 4332HE

**Comment by lastzero** [comment]
Country select should now be disabled if latitude & longitude exist, so I'll close this.

We can later improve it so that you can fix wrong geo data and ideally report it to us as well.
