### ISSUE TITLE
Account: Allow Users to Manage App Passwords from the UI

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#4114]
**As a user with two-factor authentication enabled, I would like to add and remove app passwords from the web user interface so that I can connect mobile apps and WebDAV clients with PhotoPrism.**

This is the last puzzle piece needed to release [2-Factor Authentication (2FA)](https://github.com/photoprism/photoprism/issues/808#issuecomment-2012414188). We plan to implement this with a dialog that opens when you go to **Settings > Account** and then click the "APPS AND DEVICES" button:

![account-buttons](https://github.com/photoprism/photoprism/assets/301686/650b3978-1457-40eb-bbdb-08de1b9217a5)

The dialog will allow you create, edit, and delete app-specific passwords (we may later extend it so you can also manage apps connected via OAuth2):

![apps-and-devices](https://github.com/photoprism/photoprism/assets/301686/f3c0bebb-99b5-4af4-acef-e5ebd590ea52)

![copy-app-password](https://github.com/photoprism/photoprism/assets/301686/bf9c7ccf-bd53-4cf6-9868-e1ae2741a2ca)

![apps-overview-large](https://github.com/photoprism/photoprism/assets/301686/b58ea76e-ba1b-4d2e-8ee3-1c35940c8392)

**Comment by lastzero** [comment]
Note that creating app passwords and managing OAuth2 credentials is also possible through terminal commands. For example, you can run the following to create a WebDAV app password for the *admin* account, so that compatible clients can use the WebDAV API even if 2FA is enabled for the user account:

```bash
photoprism auth add -s webdav admin
```

**Comment by Richigeht** [comment]
Thanks for the cli hint! And the idea how you want to manage this in UI looks nice :-)

**Comment by lastzero** [comment]
In order to release 2FA more quickly, we could use some help translating the user interface into other languages:
- https://translate.photoprism.app/projects/photoprism/
- https://docs.photoprism.app/developer-guide/translations-weblate/

Thank you very much! :heart:

**Comment by lastzero** [comment]
Our [preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) now also allows you to list and delete previously added app passwords in the **Apps and Devices** dialog:

![apps-confirm](https://github.com/photoprism/photoprism/assets/301686/fa225ac6-312f-4942-9957-085a8a96dbd3)

There are still some tests we need to add. We also wanted to **increase the session lifetime** when 2FA is enabled, so you don't need to re-login as often (since this takes longer with 2FA and accounts seem less likely to be abused). Should there be any other opinions, now would be a good time to let us know! :right_anger_bubble:

**Comment by lastzero** [comment]
An [updated preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) is now available [on Docker Hub](https://hub.docker.com/r/photoprism/photoprism/tags?name=preview) for you to test this:

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Any help with that is much appreciated!** :tada:

**Comment by per2jensen** [comment]
I am running "Build [240412-ada91516f]" - you mentioned [here](https://github.com/photoprism/photoprism/issues/4114#issuecomment-2046605382) it it possible to "*view* and delete" app passwords.

I can delete an app password, but not view it in the "Apps and Devices" dialog. That is consistent with the message given when generating the password. The dialog to generate the password clearly states this is the only time the password is viewable.

So, I am a little confused what you mean when stating app passwords can be viewed.

**Comment by lastzero** [comment]
@per2jensen By show, I mean list the existing passwords (names) to see when they were last used, when they expire, and to delete them. Of course, you will NOT see the passwords in plain text anymore.
