### ISSUE TITLE
Index: Skip JPEG files with a ".heic" extension

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#4118]
While our mime type detector can recognize JPEG images even with an incorrect `.heic` file extension and they could then be indexed as usual, ignoring the file extension in PhotoPrism leads to follow-up issues in other tools we commonly use (e.g. Exiftool, heif-convert,...) as they also depend on a proper file extension. 

**It is therefore best to skip files with an incorrect extension and display a log message instead, so that users can make sure that the extensions of their media files match their actual type.**

Related Issues:
- https://github.com/photoprism/photoprism/issues/3518

**Comment by pgalbavy** [comment]
Pretty sure there's a file type mime detector in the Go std packages, could be used to validate with little extra cost?

**Comment by lastzero** [comment]
@pgalbavy We have a mime detector, see my commits for details:

https://github.com/photoprism/photoprism/blob/8b6f43ad65fc0aae9a091337b4960186a51f0c60/pkg/fs/mime.go#L68-L73

However, as described above, ignoring the file extension in PhotoPrism leads to follow-up issues in other tools we commonly use (e.g. Exiftool, heif-convert,...) as they also depend on a proper file extension. We cannot change every software as a "workaround" so that incorrect file extensions can be used for all files.

**Comment by lastzero** [comment]
@pgalbavy I've updated the issue description above to (hopefully) better explain the underlying problem.

**Comment by lastzero** [comment]
My upcoming changes will display a warning about incorrect mimetypes when indexing, as shown in this example:

```
index: skipped jpeg/test.HEIC due to wrong extension '.heic' for mimetype 'image/jpeg' 
```

**Comment by lastzero** [comment]
Please note that these changes **need to be tested very well**, as mime type detection may not be 100% reliable for certain file types, especially videos and modern image types like heic(s).

An updated [photoprism/photoprism:test](https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=test) build will soon be available on Docker Hub. Any help with testing these changes is much appreciated! :pray:

**Comment by lastzero** [comment]
We removed the strict check for MP4 files, as we found that many such videos are based on MP4 but actually have a different (sub) type:

![Screenshot 2024-03-25 at 16 34 50](https://github.com/photoprism/photoprism/assets/301686/f90faa95-238f-4c15-87b5-34b982e96e6a)

**Comment by lastzero** [comment]
If you would like to test this but don't have any suitable files, our sample archive can provide you with test files for all common types and formats:
- https://dl.photoprism.app/samples/Formats/
