### ISSUE TITLE
Search: advanced search "subject" looks to use "keyword" items

### ISSUE THREAD

**Issue by loulou91** [photoprism/photoprism#4125]
#### 1. What is not working as documented?
Field "subject" of all my pictures contains "tags" I entered with Digikam 8. Field "keywords" is automatically filled by Photoprism.
As an example here is the detailed section of a picture.
![image](https://github.com/photoprism/photoprism/assets/51127123/83d62335-8de7-4242-a94c-e6427495e94b)

If I request advanced search as "subject: ville-d'automne" this picture is selected but should not be as far as ville-d'automne is not in subject field. Isn't it?

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: [PhotoPrism® CE Build [231218-c6cad4614]

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

(c) Operating System Types & Versions: Proxmox 8 & Debian 12

(d) Browser Types & Versions: Chrome

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: NUC I5

(b) Physical Memory & Swap Space in GB: 8

**Comment by graciousgrey** [comment]
There is currently no search filter for the subject field in the photo details. The subject search filter is an alias for person and searches for the people tagged in that photo. I think we should remove the alias as it is too confusing.

https://docs.photoprism.app/user-guide/search/filters/#filter-reference

If you want to use a search filter, you would have to search for `subject:"ville-d'automne"` or rather `subject:"Jane Doe"`. A search for `"subject: ville-d'automne"` or `"subject: Jane Doe" `does not use the search filter and therefore also shows photos that contain parts of the search term in their keywords.
