### ISSUE TITLE
JPEGs in ProPhoto have odd colors

### ISSUE THREAD

**Issue by odedia** [photoprism/photoprism#4130]
#### 1. What is not working as documented?
I usually process my Nikon Z9 RAW files in Lightroom, then export the output as RAW+JPEG pair to Apple Photos. The output of my JPEGs is in ProPhoto which is considered to have a preferred color gamut compared to older profiles such as AdobeRGB and sRGB.
In Apple Photos, the JPEGs look exactly as they did in Lightroom. 
After uploading this JPEG to PhotoPrism, the colors look weird and incorrect. The exif does show ProPhoto but the image looks a bit washed out and with a greenish hue.

#### 2. How can we reproduce it?

1. Process a RAW file as a ProPhoto RGB JPEG, preferably from Lightroom although I doubt the source would make much difference.
2. Import the JPEG to Apple Photos
3. Import the JPEG to PhotoPrism.
4. Compare the results. You should see very visible differences.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Will be shared via email.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: TrueNAS Scale (using TrueCharts)

(d) Browser Types & Versions: Chrome and Safari, same behaviour
[PhotoPrism® CE] Build [231128-f48ff16ef]

**Comment by lastzero** [comment]
We already have two open issues regarding support for additional color profiles (optionally also in thumbnails):

- https://github.com/photoprism/photoprism/issues/1474
- https://github.com/photoprism/photoprism/issues/3479

Any help with that would be much appreciated! 💎
