### ISSUE TITLE
Indexing aborts when encountering broken symlink that looks like an image file

### ISSUE THREAD

**Issue by flesser** [photoprism/photoprism#414]
I am trying to index my existing collection in read-only mode.

Somewhere in there I have some broken symlinks (pointing to destinations that don't exist anymore) that are named `*.JPG`.

## Actual Behavior
Once Photoprism encounters the first one of them, the indexing process stops and no further images are indexed:
```
time="2020-07-18T17:52:00Z" level=error msg="stat /photoprism/originals/2010/2010 Norwegen/zzPräsentation/01/0101.JPG: no such file or directory"
time="2020-07-18T17:52:08Z" level=info msg="purge: searching index for hidden media files"
time="2020-07-18T17:52:08Z" level=info msg="indexed 25207 files in 1m25.465540257s"
time="2020-07-18T17:52:08Z" level=info msg="closed database connection"
```
```bash
# docker exec photoprism ls -l "/photoprism/originals/2010/2010 Norwegen/zzPräsentation/01/"
total 15976
lrwxrwxrwx 1 www-data www-data      69 Jun 21  2011 0101.JPG -> /home/Bilder/Fotos/Norwegen 2010/2010-08-18/P1040281.JPG
```
Restarting the index process stops at the same place again and no photos after the '2010/' folder are indexed.

## Expected Behavior
PhotoPrism logs, but ignores those broken "files" and continues indexing.

## PhotoPrism version
Whatever was in docker `latest` yesterday at that time, but also tried again this morning with the current `200718-24cfa1a-Linux-x86_64`.

**Comment by lastzero** [comment]
Excellent catch! Turns out, godirwalk needs an error handler to skip such broken links...

**Comment by lastzero** [comment]
I'll merge this to master after testing some other potential issues that may have been introduced with recent optimizations.

**Comment by lastzero** [comment]
Fixed additional issues with wrong file type extensions, like PNGs that end with ".jpg". Lots of files imported from Google Photos seem to suffer from this. Also removed a potential deadlock in our log events.

**Comment by lastzero** [comment]
This (and much more) should be fixed now.
