### ISSUE TITLE
Metadata: Use file mod time instead of birth time as creation time fallback

### ISSUE THREAD

**Issue by kjetilho** [photoprism/photoprism#4157]
#### 1. What is not working as documented?

In mediafile.go, the import does:

```go
	if fileInfo.HasBirthTime() {
		m.takenAt = fileInfo.BirthTime().UTC()
		log.Infof("media: %s was taken at %s (file birth time)", clean.Log(filepath.Base(m.fileName)), m.takenAt.String())
	} else {
		m.takenAt = fileInfo.ModTime().UTC()
		log.Infof("media: %s was taken at %s (file mod time)", clean.Log(filepath.Base(m.fileName)), m.takenAt.String())
	}
```

However, if you have moved your files around a few times (copied them to a different server), BirthTime will be the time of the last backup (the birth time of the file on that server), not when the file was created for the first time.

Trivial example:
```
$ stat ./Pictures/sigfried-1927.jpg 
  File: ./Pictures/sigfried-1927.jpg
  Size: 10749     	Blocks: 24         IO Block: 4096   regular file
Device: 253,1	Inode: 4124311     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1232/kjetilho)   Gid: (  960/photoprism)
Access: 2024-04-07 00:33:27.189450507 +0200
Modify: 2014-10-12 02:23:06.000000000 +0200
Change: 2024-04-07 00:25:46.808088926 +0200
 Birth: 2024-03-29 20:53:55.942567413 +0100
```

Let's do a fresh copy, and see the birth time is updated to the current time.

```sh
$ cp --preserve Pictures/sigfried-1927.jpg test.jpg
$ stat test.jpg
  File: test.jpg
  Size: 10749     	Blocks: 24         IO Block: 4096   regular file
Device: 253,1	Inode: 4146744     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1232/kjetilho)   Gid: (  960/photoprism)
Access: 2024-04-07 00:33:27.189450507 +0200
Modify: 2014-10-12 02:23:06.000000000 +0200
Change: 2024-04-07 00:47:33.227091882 +0200
 Birth: 2024-04-07 00:47:33.215092029 +0200
```

#### 2. How can we reproduce it?

1. Copy an image file without metadata
2. Import it
3. See it included in the wrong calendar event.

#### 3. What behavior do you expect?

I would expect PhotoPrism to use the Modify Time.

#### 6. Which software versions do you use?

Installed using podman-compose, but code seems unchanged since that release.

(a) PhotoPrism Architecture & Build Number: photoprism version 231128-f48ff16ef-Linux-AMD64-Plus

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

**Comment by lastzero** [comment]
@kjetilho Thanks for pointing this out! I generally don't use the birth time for anything (some of my filesystems don't even support it), but added it assuming that it might help correctly determine the creation time on certain operating systems and/or filesystems.

However, I didn't realize that no vendor actually uses it for storing the media creation time and that instead it is just used internally by the filesystem to remember when a record was created in the allocation table? In this case, we can indeed just use the mtime to estimate the media creation time if no other metadata is available...

**Comment by lastzero** [comment]
An [updated preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) is now available [on Docker Hub](https://hub.docker.com/r/photoprism/photoprism/tags?name=preview) for you to [test these changes](https://github.com/photoprism/photoprism/commit/e5c5ce2348f00d573cbfeb43bf02e0bf00cff2bd):

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Any help with that is much appreciated!** :tada:

**Comment by kjetilho** [comment]
thank you very much for the quick fix!  sorry, I did not have access to my server to test the patch before release, but it looks good :+1:
