### ISSUE TITLE
Feature request: Allow to share single picture

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#417]
Right now, as far as I can see the only kind of share implemented is album shares.

Sometimes I would like to share only a single picture with friends or family, if there is a picture that I find particularly nice. Or maybe there are several, but I want to share them without the need to persist the share in form of an album.

Being able to create a share for a single picture directly from the picture details and sending it around to people would be a way faster procedure and less interruptive than first creating a new album, changing to the album, sharing it. In the former case, one could even continue browsing where one left off after a picture has been shared via the picture details.

I believe what this is fundamentally suggesting is, that shares should not be tied to albums. But instead, shares should be their own entity listed in the menu, that can either point to a single picture, or to an album, or to some other entity that can be shared (maybe a tag?).

**Comment by lastzero** [comment]
We've prepared this in the backend, but decided that album sharing is enough for a first release. Need a frontend concept for sharing photos, files or labels first.

**Comment by graciousgrey** [comment]
I close this as it duplicates https://github.com/photoprism/photoprism/issues/466
