### ISSUE TITLE
Metadata: Files with an invalid F-number fail to index

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#4170]
**As a user with files that have an invalid F-number in their Exif data, I want PhotoPrism to index the files anyway.**

It seems that some old samsung phones generate invalid Fnumbers, e.g. `"EXIF:FNumber": "2.8 1"`. Those files cannot be indexed at this time. `level=trace msg="photo: Error 1264: Out of range value for column 'photo_f_number' at row 1 in filename.jpg (create)"`

Acceptance Criteria:
- Files with an invalid FNumber MUST be indexed

**Comment by thanasisn** [comment]
Hello, thank you for addressing the issue.

Although, I created a way to edit those files, and correct the problematic tags. In case someone wants to fix the original metadata.

First, I created a generalized script to list all images with a specific tag (here the model of the phone):
[exif_list_by_tag_value.sh](https://github.com/thanasisn/IStillBreakStuff/blob/eaff0abd371eab7b846d8d9cc14802a155905bbd/data_tools/exif_list_by_tag_value.sh)

```
exif_list_by_tag.sh "exif:Model" "GT-B2710" "./path/to/folder" > ./files_with_tag.list
```

and then a script to edit all the offending FNumber tags with: [exif_edit_tag.sh](https://github.com/thanasisn/IStillBreakStuff/blob/eaff0abd371eab7b846d8d9cc14802a155905bbd/data_tools/exif_edit_tag.sh)

```
cat ./files_with_tag.list | xargs -P 4 -I % exif_edit_tag.sh % 
```

After this, my pictures were indexed by photoprism, without any problem.

**Comment by lastzero** [comment]
An [updated preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) is now available [on Docker Hub](https://hub.docker.com/r/photoprism/photoprism/tags?name=preview) for you to test these changes:

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Any help with that is much appreciated!** :tada:
