### ISSUE TITLE
Videos: Upgrade FFmpeg from 6.1.1 to 7.x for faster transcoding

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#4181]
**As a user with videos that need to be transcoded or videos in the new EVC and VVC formats, I would like to see FFmpeg shipped with and used by PhotoPrism as it supports [multi-threaded transcoding](https://ffmpeg.org/#cli_threading) and the [latest codecs](https://ffmpeg.org/#vvcdec).**

There are *static builds* provided directly by the FFmpeg project, but it's unclear if we can use them since **(a)** they only support [a subset of codecs](https://johnvansickle.com/ffmpeg/git-readme.txt) which are freely available (so our file format support could shrink rather than grow) and **(b)** hardware video transcoding must continue to work for (at least) all [currently supported GPUs and CPUs](https://docs.photoprism.app/getting-started/advanced/transcoding/), which might require *dynamic linking*:
- https://johnvansickle.com/ffmpeg/ 
- https://johnvansickle.com/ffmpeg/git-readme.txt

**[Video Formats](https://www.photoprism.app/kb/file-formats) currently supported by PhotoPrism:**
- **3G2**	Mobile Multimedia Container (CDMA2000)	Video	.3g2
- **3GP**	Mobile Multimedia Container (3G)	Video	.3gp
- **ASF**	Advanced Systems Format	Video	.asf
- **AV1**	AOMedia Video 1	Video	.av1
- **AVC**	Advanced Video Coding (H.264, MPEG-4 Part 10)	Video	.avc
- **AVI**	Microsoft Audio Video Interleave	Video	.avi
- **DV**	DV Video	Video	.dv
- **FLV**	Adobe Flash	Video	.f4v, .flv
- **HEVC**	High Efficiency Video Coding (H.265)	Video	.hevc
- **M2TS**	Blu-ray MPEG-2 Transport Stream	Video	.m2ts
- **M4V**	Apple iTunes Multimedia Container	Video	.m4v
- **MJPG**	Motion JPEG	Video	.mjpeg, .mjpg
- **MKV**	Matroska Multimedia Container	Video	.mkv
- **MOV**	Apple QuickTime	Video	.mov, .qt
- **MP2**	MPEG 2 (H.262)	Video	.mp2, .mpv
- **MP4**	Multimedia Container (MPEG-4 Part 14)	Video	.mp, .mp4
- **MPG**	Moving Picture Experts Group (MPEG)	Video	.mpeg, .mpg
- **MTS**	Advanced Video Coding High Definition (AVCHD)	Video	.mts
- **OGV**	Ogg Media (OGG)	Video	.ogg, .ogv, .ogx
- **VVC**	Versatile Video Coding (H.266)	Video	.vvc
- **WEBM**	Google WebM	Video	.webm
- **WMV**	Windows Media	Video	.wmv

**Sample Files for Testing:**

- https://dl.photoprism.app/samples/Formats/Video/

**Related Documentation:**

- https://docs.photoprism.app/getting-started/advanced/transcoding/
- https://docs.photoprism.app/user-guide/organize/video/#transcoding

**Acceptance Criteria:**

- [ ] Our [official Docker image](https://hub.docker.com/r/photoprism/photoprism) MUST include FFmpeg 7.x for all currently supported architectures: AMD64, ARM64 and ARMv7
- [ ] If there is an official Linux distribution backport (e.g. from Ubuntu), it SHOULD be used; otherwise, we can ideally install pre-compiled FFmpeg 7.x binaries from a trusted, external source or, if there is no other option, compile our own binaries from source code
- [ ] For all other architectures, there SHOULD be a way to either compile binaries or download and install pre-compiled FFmpeg 7.x binaries
- [ ] All [currently supported video formats](https://www.photoprism.app/kb/file-formats) (free and non-free) MUST continue to work, in addition to the newly supported EVC and VVC video file formats
- [ ] Hardware video transcoding MUST continue to work for (at least) all [currently supported GPUs and CPUs](https://docs.photoprism.app/getting-started/advanced/transcoding/)

*Any help figuring out the best way to upgrade to FFmpeg 7.x and then testing it would be much appreciated!*

**Comment by lastzero** [comment]
These changes install FFmpeg 7 as described at https://ubuntuhandbook.org/index.php/2024/04/ffmpeg-7-0-ppa-ubuntu/ for testing purposes. Unfortunately, this appears to be a privately maintained PPA (so no guaranteed updates) and there is no ARMv7 build.

**Comment by lastzero** [comment]
It also seems like the `h264_nvenc` codec, required to support NVIDIA hardware transcoding, is missing in this package...

**Comment by lastzero** [comment]
### AVC Decoder / Encoder Support

Running the `ffmpeg -codecs` command shows the supported H.264 (MPEG-4 AVC) codecs for the FFmpeg version currently installed:

#### FFmpeg 6.1.1 (standard Ubuntu 24.04 LTS distribution package)

```
H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
(decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid)
(encoders: libx264 libx264rgb h264_nvenc h264_qsv h264_v4l2m2m h264_vaapi)
```

#### FFmpeg 7.0 (installed from `ppa:ubuntuhandbook1/ffmpeg7`)

```
H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
(decoders: h264 h264_v4l2m2m h264_qsv libopenh264)
(encoders: libx264 libx264rgb libopenh264 h264_amf h264_omx h264_qsv h264_v4l2m2m h264_vaapi)
```

### Conclusion

While the new version (originally compiled by the Debian maintainers) additionally supports `h264_amf` for AMD CPUs and `h264_omx` for Rapberry Pi's, it **does not support NVIDIA GPUs** (which are popular among our users). This is probably because NVIDIA support needs to be added from an external repository when building FFmpeg and so it is not available by default.

### Upgrade Strategy

We will therefore wait for an official Ubuntu distribution package for FFmpeg 7, which should include NVIDIA GPU support. Everyone else can use the new `install-ffmpeg.sh` script included with our Docker image (or `PHOTOPRISM_INIT: "ffmpeg"` if you are using Docker Compose).

**Comment by lastzero** [comment]
The `install-ffmpeg.sh` script has been updated to install the static build available at [johnvansickle.com/ffmpeg/](https://johnvansickle.com/ffmpeg/).

If you use Docker Compose, you can add `PHOTOPRISM_INIT: "ffmpeg"` to the environment section of your `compose.yaml` or `docker-compose.yml` file to run this script when the PhotoPrism container starts for the first time:

```yaml
services:
  photoprism:
    environment:
      PHOTOPRISM_INIT: "ffmpeg"
```

Please note, though, that this version **does not support hardware transcoding** and is therefore only suitable if you use standard software transcoding. The static build may also not support all video formats.

**Comment by Ep0chalypse** [comment]
Installing ffmpeg v7 under docker is failing for me. I'm running fully updated raspberry pi os(64bit) on a raspberry pi 5 8gb and did a docker compose pull before adding "ffmpeg" to the photoprism_init section. When I open a shell on the container I can see /opt/ffmpeg folder is created but is empty.

photoprism  | init: ffmpeg
photoprism  | Installing FFmpeg...
photoprism  | ------------------------------------------------
photoprism  | VERSION: release
photoprism  | ARCHIVE: ffmpeg-release-arm64-static.tar.xz
photoprism  | DESTDIR: /opt/ffmpeg
photoprism  | ------------------------------------------------
photoprism  | Extracting "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz" to "/opt/ffmpeg".
photoprism  | tar (grandchild): xz: Cannot exec: No such file or directory
photoprism  | tar (grandchild): Error is not recoverable: exiting now
photoprism  | --2024-06-03 06:44:01--  https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz
photoprism  | Resolving johnvansickle.com (johnvansickle.com)... 107.180.57.212
photoprism  | Connecting to johnvansickle.com (johnvansickle.com)|107.180.57.212|:443... connected.
photoprism  | HTTP request sent, awaiting response... 200 OK
photoprism  | Length: 19339992 (18M) [application/x-xz]
photoprism  | Saving to: 'STDOUT'
photoprism  |
photoprism  |      0K .......tar: Child died with signal 13
photoprism  | tar: Error is not recoverable: exiting now
photoprism  |                                                  0%  111K=0.07s
photoprism  |
photoprism  |
photoprism  | Cannot write to '-' (Success).
photoprism  | Done.

**Comment by lastzero** [comment]
@Ep0chalypse Seems to work for me, at least with the amd64 version (I'd be surprised if xz is only installed there and not in the arm64 base image, the download URL seems to be correct too...):

```
started 240602 as uid 1000 (amd64-prod)
init: account with the user id 1000 already exists
init: ffmpeg
Installing FFmpeg...
------------------------------------------------
VERSION: release
ARCHIVE: ffmpeg-release-amd64-static.tar.xz
DESTDIR: /opt/ffmpeg
------------------------------------------------
Extracting "https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz" to "/opt/ffmpeg".
--2024-06-03 09:06:25--  https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 107.180.57.212
Connecting to johnvansickle.com (johnvansickle.com)|107.180.57.212|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41876392 (40M) [application/x-xz]
Saving to: ‘STDOUT’

0K .......... .......... .......... .......... ..........  0%  155K 4m24s
```

Can you test it again in case it was a temporary issue? Otherwise, since the error might depend on certain environment settings, e.g. the [`PHOTOPRISM_UID` variable](https://docs.photoprism.app/getting-started/config-options/#docker-image) being set, it only makes sense for us to test it again if you can provide complete information about the Docker image and all environment variables.

**Comment by lastzero** [comment]
@Ep0chalypse I've updated our Dockerfiles to make sure the `xz-utils` package is installed (in case that was the problem). Could you please test it again with our latest [development preview](https://docs.photoprism.app/release-notes/#development-preview)?

An updated `photoprism/photoprism:preview` build will be available on Docker Hub shortly:
- https://hub.docker.com/r/photoprism/photoprism/tags?name=preview

**Comment by Ep0chalypse** [comment]
@lastzero 

I tried a few times last night and again just now and it is still failing.

I created a new container using the :preview build and it worked. So it looks like you guessed right and that xz isn't installed on the aarch64 base image.

**Comment by lastzero** [comment]
Thanks for testing it again! Then ARM64 users should use our preview image until these changes become available with the next release at the end of the month when we are back in the office. It does not contain anything that would affect stability.
