### ISSUE TITLE
Only first "Person in Image" is added to People tab when import photo with exif metadata

### ISSUE THREAD

**Issue by FudiHub** [photoprism/photoprism#4183]
#### 1. What is not working as documented?

I want to import Photos with EXIF/IPTC metadata.
There are person information present in the metadata. Both person get added to the subject field in photoprism but only the first person in the list is added tp the People tab.

Exif metadata from exiftool:

```
XMP Toolkit                     : Image::ExifTool 12.82
Person In Image                 : Firstname1 Lastname1, Firstname2 Lastname2
Region Person Display Name      : Firstname1 Lastname1, Firstname2 Lastname2
Region Applied To Dimensions H  : 1536
Region Applied To Dimensions Unit: pixel
Region Applied To Dimensions W  : 2048
Region Area H                   : 0.42802414298057556, 0.33715641498565674
Region Area Unit                : normalized, normalized
Region Area W                   : 0.32101810723543167, 0.25286731123924255
Region Area X                   : 0.6419097185134888, 0.4480791538953781
Region Area Y                   : 0.524799570441246, 0.5459824204444885
Region Name                     : Firstname1 Lastname1, Firstname2 Lastname2
Region Type                     : Face, Face
``` 

This results in "Firstname1 Lastname1, Firstname2 Lastname2" added to the Subject field of the photo.
<img width="400" alt="image" src="https://github.com/photoprism/photoprism/assets/6597597/94d95be1-66b2-457b-bbd4-c887c5c82385">

But only the first of both persons is added to the People tab:
<img width="249" alt="image" src="https://github.com/photoprism/photoprism/assets/6597597/82c4de15-94ad-4c98-83a8-e6a1c86368e4">

#### 2. How can we reproduce it?

Upload a photo with multiple person in exif-data

#### 3. What behavior do you expect?

Both person should be added to the People tab

#### 4. What could be the cause of your problem?

I guess photoprism is not parsing the list of personinimage field correctly

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Please include sample files or screenshots that help to reproduce your problem. You can also email files or share a download link, see <https://www.photoprism.app/contact> for details.

Visit <https://docs.photoprism.app/getting-started/troubleshooting/browsers/> to learn how to diagnose frontend issues.

**Important: If it is an import, indexing or metadata issue, we require sample files and logs from you.** Otherwise, we will not be able to process your report. If it is an import problem specifically, please always provide us with an archive of the files before you imported them so we can reproduce the behavior.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 231128-f48ff16ef

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Chrome

Thanks.

**Comment by graciousgrey** [comment]
PhotoPrism does not yet read face region metadata from exif. This is planned for the future:

- https://github.com/photoprism/photoprism/issues/1570
- https://github.com/photoprism/photoprism/issues/747
- https://github.com/photoprism/photoprism/issues/554

You can find the full list of currently supported metadata fields here:

https://docs.photoprism.app/user-guide/library/metadata/
https://www.photoprism.app/kb/metadata

The PersonInImage field is read and used to populate the subject field from the photo details. The faces you see on the people tab are the faces recognized by PhotoPrism.
