### ISSUE TITLE
Places: Include videos in the map-based place browser (the 'Places' view)

### ISSUE THREAD

**Issue by dgtal1** [photoprism/photoprism#4184]
**Describe what problem this solves and why this would be valuable to many users**

Videos recorded by mobile phones also have GPS location tags. In fact Photoprism is able to read this information and show in file properties:
![image](https://github.com/photoprism/photoprism/assets/27864579/66a5a729-753d-4854-ad41-738675a31d6c)
![image](https://github.com/photoprism/photoprism/assets/27864579/bb1d4a6a-3b3f-47d1-b0d7-e28ede430333)

I do not understand why videos are not shown in the places view when I click on a place on the map and on the small circle with little thumbnails. The slide-up, contextual thumnails list at the bottom of the main window does not show videos, but only photos. Other views e.g. Calendar or Search show both things - photos and videos.

The fact that videos are missing in the Places view spoils the UX a bit. Adding videos in the Places view would feel Photoprism as a complete, intuitive and convenient solution.

**Describe the solution you'd like**

Videos shown in the places view as well. If not always - at least some filter/flag available to users, so one could either see them or not in this view depending on the setting in the Places view or general settings.

**Describe alternatives you've considered**

I need to find the place again using the Calendar view and this one shows everything - photos and videos, but it's incovenient and a bit cumbersome to browse the library this way if I'm explicitly interested in contents captured in a specific place. 

**Additional context**

**Comment by graciousgrey** [comment]
Videos with GPS coordinates should be shown on the map:

https://demo.photoprism.app/library/videos
https://demo.photoprism.app/library/places?q=s2%3A47a84eded274
https://demo.photoprism.app/library/places?q=video

**Comment by dgtal1** [comment]
You are right. I used this link in places to explicitly specify that I want to see videos only and it displayed some of them. Then I'm not sure why, but for some reason it doesn't show all of them in this view. I tried reindexing but it didn't help. 
That would be my next Feature Request to (re)index selected files only and fix the index this way.

Let's close this issue then
