### ISSUE TITLE
Are existing tags supposed to be imported?

### ISSUE THREAD

**Issue by relink2013** [photoprism/photoprism#419]
I have a few years worth of tags on my photos that I have used in other software for organizing, and categorizing my images. However despite all of the info Photo Prism did extract from my images, their existing tags did not seem to be included. 

Is this a bug or by design? Is there a way to have Photo Prism import my existing tags? After Indexing I expected to see them under "Labels" but not a single one of them is there.

**Comment by lastzero** [comment]
We do import keywords. Labels are used for standardized categorization using TensorFlow and geo data. When there is a matching keyword, the photo is also added to the corresponding label. But we don't add labels for every keyword we find in indexed metadata.

What software are / were you using?

What format are your existing "tags" stored in (XMP sidecar files, Excel sheets, Exif headers)? What specific XMP or Exif fields?

**Comment by relink2013** [comment]
I have been using a mix between Digikam and Synology Photostation, both of which appear to just write the tag directly into the files.

**Comment by lastzero** [comment]
You can use exiftool to check their metadata.

**Comment by relink2013** [comment]
Using exiftool my tags seem to be listed under the "keywords" section.

**Comment by lastzero** [comment]
![Screenshot_20200724_171149](https://user-images.githubusercontent.com/301686/88406322-cfb72780-cdd0-11ea-9949-eb4585fef133.jpg)

When you open the edit / details view, are all keywords gone or do you see them?

**Comment by relink2013** [comment]
My keywords are not there. The keywords that appear there are the ones that Photo Prism has added automatically.

**Comment by lastzero** [comment]
Can you provide us with a file for testing? Either privately to hello@photoprism.org or attached to this issue.

**Comment by relink2013** [comment]
![lake](https://user-images.githubusercontent.com/29458277/88409638-36bde780-cda3-11ea-9831-89791a25847b.jpeg)

I used Digikam to tag this file with the words "shot" and "ideas"

**Comment by lastzero** [comment]
Indexed this and the keywords are there as expected:

<img width="958" alt="Screenshot 2020-07-26 at 11 58 18" src="https://user-images.githubusercontent.com/301686/88476272-6d2c6b80-cf37-11ea-9882-4c6e66b2ef15.png">

Not sure why those tools are using JSON arrays for the subject field... is that a standard? But we can of course also detect and parse this (after our vacation).

**Comment by relink2013** [comment]
Huh...Well for starters maybe ill try re-indexing everything and see if it clears up.

**Comment by lastzero** [comment]
Maybe you need to enable JSON sidecar files if you disabled them. Otherwise, embedded XMP data can not be indexed.

**Comment by relink2013** [comment]
> Maybe you need to enable JSON sidecar files if you disabled them. Otherwise, embedded XMP data can not be indexed.

Where would I find the option? I do not recall disabling anything.

**Comment by lastzero** [comment]
docker-compose.yml - see our example config or run `photoprism help` for a list of all config options incl description

**Comment by uLUViL3gCs** [comment]
I have a similar question as @relink2013 , but in a different scenario:
I am having...
1) Apple Photos App used to 'tag' files using built in 'keywords' functionality
2) these files exported from Apple Photos incl. IPTC as XMP:
![Screenshot 2020-08-13 at 17 27 55](https://user-images.githubusercontent.com/64777347/90155299-73ba4000-dd8b-11ea-9a2b-8473a4ae9c8e.png)
![Screenshot 2020-08-13 at 17 39 09](https://user-images.githubusercontent.com/64777347/90155775-fe9b3a80-dd8b-11ea-915e-17defe96b344.png)
Exemplary, this xmp export lists the keyword "**done**" as prior set in Apple Photos App
![Screenshot 2020-08-13 at 17 44 06](https://user-images.githubusercontent.com/64777347/90156474-c8aa8600-dd8c-11ea-93b6-5c090a335e9f.png)
3) Having local PP instance ( 200812-f737edb-Linux-x86_64 ) with PHOTOPRISM_SIDECAR_JSON set to true running:
![Screenshot 2020-08-13 at 17 30 03](https://user-images.githubusercontent.com/64777347/90156003-44580300-dd8c-11ea-9259-53e877b4fd79.png)

4) When the above picture is being imported to PP, I now would expect to find the keyword (here "done") listed under the keyword section, but this is not the case 
![Screenshot 2020-08-13 at 17 49 51](https://user-images.githubusercontent.com/64777347/90157008-7a49b700-dd8d-11ea-8625-dc4cbe953808.png)
logs while import:  

> [GIN-debug] redirecting request 307: /api/v1/import/ --> /api/v1/import/
> time="2020-08-13T15:31:06Z" level=info msg="Copying files from 93_sidecar"
> time="2020-08-13T15:31:06Z" level=info msg="import: no .ppignore file found"
> time="2020-08-13T15:31:08Z" level=debug msg="mediafile: no json sidecar file found for P1080181.jpeg"
> time="2020-08-13T15:31:08Z" level=info msg="mediafile: P1080181.jpeg was taken at 2017-08-25 09:04:05 +0000 UTC (meta)"
> time="2020-08-13T15:31:08Z" level=info msg="import: moving related xmp file P1080181.xmp to 2017/08/20170825_090405_2F696435.xmp"
> time="2020-08-13T15:31:08Z" level=info msg="import: moving main jpg file P1080181.jpeg to 2017/08/20170825_090405_2F696435.jpeg"
> time="2020-08-13T15:31:14Z" level=info msg="mediafile: 11 thumbnails created for 20170825_090405_2F696435 [5.0770381s]"
> time="2020-08-13T15:31:14Z" level=debug msg="convert: 2017/08/20170825_090405_2F696435.jpeg -> 20170825_090405_2F696435.json"
> time="2020-08-13T15:31:15Z" level=debug msg="import: 20170825_090405_2F696435.json created"
> time="2020-08-13T15:31:17Z" level=debug msg="index: image classification took 1.5193839s"
> time="2020-08-13T15:31:17Z" level=debug msg="api: sending request to https://places.photoprism.org/v1/location/47e66c55339c (photoprism places)"
> time="2020-08-13T15:31:17Z" level=debug msg="cached 47e66c55339c [217.1013ms]"
> time="2020-08-13T15:31:17Z" level=debug msg="places: record not found (find place id s2:47e66c55339c, label “Pantin, Ile-de-France, France”)"
> time="2020-08-13T15:31:17Z" level=info msg="places: added place id s2:47e66c55339c [277.9465ms]"
> time="2020-08-13T15:31:17Z" level=debug msg="places: added cell id s2:47e66c55339c [325.3546ms]"
> time="2020-08-13T15:31:17Z" level=debug msg="photo: using label “Quai De L'Ourcq” to create title for pqf0ds52dcqyxkew"
> time="2020-08-13T15:31:17Z" level=debug msg="photo: changed title of pqf0ds52dcqyxkew to “Quai De L'Ourcq / Pantin / 2017”"
> time="2020-08-13T15:31:17Z" level=info msg="import: added main jpg file 2017/08/20170825_090405_2F696435.jpeg"
> time="2020-08-13T15:31:17Z" level=debug msg="metadata: original name 20170825_090405_2F696435.xmp does not match 20170825_090405_2F696435.jpeg (exiftool)"
> **time="2020-08-13T15:31:17Z" level=debug msg="mediafile: exif not supported: 20170825_090405_2F696435.xmp"**
> time="2020-08-13T15:31:17Z" level=info msg="import: added related xmp file 2017/08/20170825_090405_2F696435.xmp"
> time="2020-08-13T15:31:18Z" level=debug msg="moments: index contains 306 photos and 3 videos, using threshold 9"
> time="2020-08-13T15:31:18Z" level=info msg="Import completed in 11 s"
> time="2020-08-13T15:31:18Z" level=debug msg="POST /api/v1/import/ (200) [11.4783423s]"
> 

Having read all PP documentation that I could find and having described above, could you please give advice on the following:
a) is my understanding generally correct, that I could "transfer/import" given keywords from Apple Photos App to PP using XMP files - by the process as described above?
b) if yes, is it true that those keywords will be listed in PP's keywords section - or will those keywords be used for other PP configurations also?
c) if yes, do you have any idea why in above given example the keyword is not listed?
d) Is the bold marked log message above (**exif not supported**) something to worry? 

Thanks in advance!

**Comment by lastzero** [comment]
You are generally right. The difficulty with XMP is that it can contain everything and is extremely extensible - as the name suggests. I'd assume there are subject fields in various namespaces, dublin core being one of them. Then it may also conflict with the subject field in Exif, and so on.... Ideally PhotoPrism merges everything, removes duplicates and unwanted keywords.

Providing a completely tested and certified XMP solution would be very expensive, and very boring work at the same time. I'd rather not do this for free while other people enjoy the summer 😎 - probably not even in winter during total lockdown.

**Comment by uLUViL3gCs** [comment]
> You are generally right. The difficulty with XMP is that it can contain everything and is extremely extensible - as the name suggests. […] Ideally PhotoPrism merges everything, removes duplicates and unwanted keywords.

> Providing a completely tested and certified XMP solution would be very expensive, and very boring work at the same time. […]

Thanks for your explanation and of course, I'd like you to rather continue on PP's core than on a full-certified XMP solution... 👍🏼😀

Nonetheless, I continued experimenting and digging into the metadata handling with PP - I think it would be important to have a way at hand to change metadata somehow apart from using GUI. At least this would give me some flexibility in case I need to add full bunch of data for one reason or the other in future.


Although I am now able to add metadata to a file (mostly corrected or added gps + additional keywords) **DURING** the import to PP (using a yml file),…
![Screenshot 2020-08-24 at 09 36 04](https://user-images.githubusercontent.com/64777347/91017180-268d6800-e5ee-11ea-9c49-f571ca86df31.png)
```
2020-08-24 09:27:28 INFO import: moving related yml file P1120256.yml to 2019/02/20190201_023841_A341762C.yml
2020-08-24 09:27:28 INFO mediafile: P1120256.jpeg was taken at 2019-02-01 02:38:41 +0000 UTC (meta)
2020-08-24 09:27:28 DEBU mediafile: no json sidecar file found for P1120256.jpeg
2020-08-24 09:27:27 INFO import: added folder /upload/1598254046129
2020-08-24 09:27:27 INFO import: no .ppignore file found
2020-08-24 09:27:27 INFO Moving files from 1598254046129
2020-08-24 09:27:27 DEBU POST /api/v1/upload/1598254046129 (200) [14.0192ms]
2020-08-24 09:27:27 INFO 1 files uploaded in 0 s
2020-08-24 09:27:27 DEBU upload: saving file P1120256.yml
2020-08-24 09:27:27 DEBU POST /api/v1/upload/1598254046129 (200) [1.1369933s]
2020-08-24 09:27:27 INFO 1 files uploaded in 1 s
2020-08-24 09:27:27 DEBU upload: saving file P1120256.jpeg
```
I have not found a way yet to update metadata for files that **ARE ALREADY** imported/known to PP.
I tried:
- editing PP’s json sidecar file and triggering a re-index of complete library <- no change (I found this method mentioned here (although I admit the source of the change is mentioned to be exiftool and not me 😳: https://github.com/photoprism/photoprism/issues/473#issuecomment-678263354)
- modifying the original yml file that was giving along while import, and uploading the same to PP <- no change (probably PP has not clue which photo the file shall relate to in a first place...)

Could you please let me know whether there is a mechanism in place - apart from manual GUI intervention of course - to change metadata of a file (file manipulation, file import, re-indexing etc. welcome). How would that look like?

**Comment by lastzero** [comment]
YAML sidecar files are there as backups, they are not the primary metadata source when files are already indexed (otherwise, we need to implement a complex sync solution that compares values field by field every time - might do that later if needed).

Instead, use JSON files as used by Exiftool.  If they don't exist yet, PhotoPrism will automatically create them using Exiftool (if the option is enabled).

If you tried this before, maybe you put the keywords in the wrong fields? You need to use the field names as used by Exiftool, not the PhotoPrism field names.

In addition, since we use a standard SQL database, you can modify data directly in the database as a developer (given the schema stays the same - or will only be extended - which will be the case for our stable release).

**Comment by haldi4803** [comment]
Might there be some errors with the importing from Tags?

Tried to upload an Example on the Demo Page.
The "Title" field got used for "Title" and "description" and the "Subject" field is filled with "Tags" The "Subject" and "Comments" field from the file are not used. (check Screenshot)

![image](https://user-images.githubusercontent.com/17104473/197413713-af47a799-5574-4ecd-b0da-59637d28e540.png)

**Comment by lastzero** [comment]
There is no title field in Exif, it's called description. Windows Explorer is not a reference for photography metadata, please show us what Exiftool reports if you feel something is wrong 👍

**Comment by haldi4803** [comment]
my fault... i was actually expecting windows to work... sorry.

ExifTool Version Number         : 12.49
File Name                       : TestStable.jpg
Directory                       : C:/Users/Haldi/Desktop
File Size                       : 343 kB
File Modification Date/Time     : 2022:10:23 21:15:24+02:00
File Access Date/Time           : 2022:10:23 21:26:25+02:00
File Creation Date/Time         : 2022:10:23 21:14:28+02:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 96
Y Resolution                    : 96
Exif Byte Order                 : Big-endian (Motorola, MM)
Image Description               : TEST_Title
Artist                          : Haldi
Date/Time Original              : 2022:10:23 21:15:09
Create Date                     : 2022:10:23 21:15:09
Sub Sec Time Original           : 35
Sub Sec Time Digitized          : 35
XP Title                        : TEST_Title
XP Comment                      : TEST_Comments
XP Author                       : Haldi
XP Keywords                     : No_Tags
XP Subject                      : TEST_Subject
Padding                         : (Binary data 2018 bytes, use -b option to extract)
About                           : uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b
Rating                          : 4
Warning                         : [minor] Fixed incorrect URI for xmlns:MicrosoftPhoto
Rating Percent                  : 75
Last Keyword XMP                : No_Tags
Creator                         : Haldi
Subject                         : No_Tags
Title                           : TEST_Title
Description                     : TEST_Title
Image Width                     : 1664
Image Height                    : 1664
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 1664x1664
Megapixels                      : 2.8
Create Date                     : 2022:10:23 21:15:09.35
Date/Time Original              : 2022:10:23 21:15:09.35
-- press ENTER --

**Comment by lastzero** [comment]
I see special fields "invented" by Microsoft, they have an XP prefix. Feel free to share test samples with us as described on our contact page: https://photoprism.app/contact
