### ISSUE TITLE
UX: Support timeline feature

### ISSUE THREAD

**Issue by Hector1990** [photoprism/photoprism#4208]
**Describe what problem this solves and why this would be valuable to many users**

I notice now there is the **Calendar** feature, but it's not convenient for me browser all features by time.

Can we support a **Timeline** feature like other softwares?

**Describe the solution you'd like**

Add **Timeline** feature.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by graciousgrey** [comment]
A timeline view is planned :)

- https://github.com/photoprism/photoprism/issues/152

**Comment by Hector1990** [comment]
> A timeline view is planned :)
> 
> * [UX: Timeline View #152](https://github.com/photoprism/photoprism/issues/152)

Awesome, looking forward to it.
