### ISSUE TITLE
Image Import seems to ignore visually similar image with different SHA1sums. 

### ISSUE THREAD

**Issue by NKNdevs** [photoprism/photoprism#4209]
#### 1. What is not working as documented?

We are attempting to import a large number of images exported from Flickr in zip files. Our initial test import contained roughly 2200 files. I did a sanity check to see that all images were imported, by comparing the image file original names to the contents of all the sidecar .yml files. I found that around 40 of the images didn't get imported. 

When I looked into what had happened, it seems that the missing images were excluded because they were visually very similar to ones previously imported. However they were different jpg files with different SHA1 sums. Example: 3 very similar photographs taken at the same time in the same location, so their exif data is all very similar. However only 2 are imported and the third is not. The images are large at around 60Mb jpgs, so I don't know if that had some bearing on it. 

#### 3. What behavior do you expect?

As the documentation says it decides if an image is duplicate based on SHA1sum I'd expect all images to be imported. However if AI or exif data is also used then maybe that's causing the failure. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I can't post the pictures here due to copyright reasons. 

#### 6. Which software versions do you use?

Latest photoprism, mariadb in the docker compose format. 

Running on Ubuntu 22. 32Gb RAM. 1Tb disk.

**Comment by graciousgrey** [comment]
Depending on your stacking settings files with sequential names or photos that have been taken at the same place in the same second might got stacked.

https://docs.photoprism.app/user-guide/settings/library/#stacks
https://docs.photoprism.app/user-guide/organize/stacks/

Other reasons for missing files can be found here:
https://docs.photoprism.app/getting-started/troubleshooting/#missing-pictures

**Comment by NKNdevs** [comment]
Fantastic. It was stacking. The icon denoting it is pretty faint, so if you don't know that it exists, its hard to see. 
I have disabled stacking and am trying another import. Have also read the manual and discovered the process for unstacking, so I think that's case closed. Thanks for the speedy reply.
