### ISSUE TITLE
Orientation operation, returned error 500

### ISSUE THREAD

**Issue by kcrazy** [photoprism/photoprism#4213]
I want to flip an image using the orientation operation, 

calling the API: 
/api/v1/photos/psceoaw65z11gr0i/files/fsceoax5ool8vusl/orientation, 

which returns a 500 Internal Server Error. 

Version: April 20, 2024.

**Comment by lastzero** [comment]
Please enable trace log mode and provide the full logs:
- https://docs.photoprism.app/getting-started/troubleshooting/docker/#viewing-logs
- https://docs.photoprism.app/developer-guide/issues/#creating-bug-reports

**Comment by kcrazy** [comment]
```
photoprism --debug --trace start
```

log:
```
...
DEBU[2024-04-26T08:45:57+08:00] server: GET /api/v1/t/bbf499c0ae50ed4f4b0445b4b47a7c3fa7d0153d/xoql6sbt/tile_224 (200) [327.410552ms]
DEBU[2024-04-26T08:46:04+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [686.201µs]
DEBU[2024-04-26T08:46:50+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [1.428872ms]
DEBU[2024-04-26T08:47:09+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [416.362µs]
```

**Comment by lastzero** [comment]
So you don't use our Docker image? A dependency is probably missing then. We can't help with that within the scope of a bug ticket.

**Comment by kcrazy** [comment]
Yes, I'm not using Docker, 
but I'm using the [photoprism_240420-ef5f14bc4-linux-amd64.tar.gz](https://github.com/photoprism/photoprism/releases/download/240420-ef5f14bc4/photoprism_240420-ef5f14bc4-linux-amd64.tar.gz) from the [Release page](https://github.com/photoprism/photoprism/releases).
