### ISSUE TITLE
Search: Enable Title-Based Sorting

### ISSUE THREAD

**Issue by wsyxbcl** [photoprism/photoprism#4214]
A similar request to #2620 

A current similar sorting method would be Sort with filename, which becomes problematic when users upload images since filenames are automatically generated. This makes the Title a more logical metric for sorting, especially since users can edit titles to suit their sorting needs.

**Comment by lastzero** [comment]
We could do that, but titles are often also automatically generated. Wouldn't that make them "unusable" for sorting in the same way? 🤔

**Comment by wsyxbcl** [comment]
Indeed, but it provides chances for those who need "customized" sorting method. Users will have the option to edit titles during the upload process or make modifications afterward, unlike filenames for uploaded files.

**Comment by wsyxbcl** [comment]
I implemented it directly because it's not difficult, and it's essential for my current workflow. There may be some test cases to cover, and I'll follow up on that in the PR: #4218
