### ISSUE TITLE
Live Photo’s needing to be manually changed

### ISSUE THREAD

**Issue by Chadea** [photoprism/photoprism#422]
Can you provide some information on how Live Photo’s are picked up/detected. I can get them working if I go to the video file and change it’s type to Live, it removes it from videos and I get the hover functionality in the photos view but I don’t get an indicator like in the demo to show its Live. 

Additionally, are there plans to be able to modify multiple files at once? I.e manually change date and other metadata?

**Comment by lastzero** [comment]
Videos up to 3 seconds. Are they longer?

**Comment by Chadea** [comment]
No, they're 3 seconds or shorter .movs. 
When I got into the file details I can't see length anywhere, should I be able to? What would stop the length being detected?

**Comment by lastzero** [comment]
We use exiftool for this as we can't directly read video metadata yet. So you need to enable json sidecar files, which slows down indexing a bit when indexing for the first time.

**Comment by Chadea** [comment]
How do I enable json sidecar? I get a lot of .jpg sidecar files but not seen .json ones.

**Comment by lastzero** [comment]
See our example docker-compose.yml files or run `photoprism help`.

**Comment by Chadea** [comment]
Thank you, I'll give that a try, and what is the benefit of adding yaml sidecar files while I'm here?

**Comment by lastzero** [comment]
They'll contain a metadata backup (title, description, favorite, private,...), so it can be recovered when your database gets lost.

**Comment by Chadea** [comment]
Thank you!! That's solved it. Re-indexing a folder didn't seem to work after I made the changes, so I moved my settings/sidecar/cache folder and re-indexed the same folder and it's adding them as Live. Thanks again, I've really been enjoying curating lost memories in PhotoPrism, looking forward to seeing how it develops.
