### ISSUE TITLE
People: New face cannot be named due to invalid file or photo UID

### ISSUE THREAD

**Issue by Radiokot** [photoprism/photoprism#4221]
#### 1. What is not working as documented?

Under the "People", "New" tab, I have a face of mine. I want to give it my name by selecting it from the dropdown list. I get "Entity not found" error.

![image](https://github.com/photoprism/photoprism/assets/5675681/d80f5158-6a8f-4af0-8825-cff824b942a4)
![image](https://github.com/photoprism/photoprism/assets/5675681/b708d5af-8b4c-4c55-982a-129982652735)

#### 2. How can we reproduce it?

I don't know, this is the only stuck "new face" I have this problem with.

#### 3. What behavior do you expect?

I expect the face to be named successfully and disappear from the "New" tab.

#### 4. What could be the cause of your problem?

🤷🏻‍♂️

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Screenshot attached above.

#### 6. Which software versions do you use?

(a) photoprism/photoprism:240420@sha256:3dc6b93163548fcd83c2a51e33562e079afa4b52f80883dc6f942a4ec7a99b37

(b) mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd

(c) Ubuntu

(d) Edge 124.0.2478.51 (Official build) (64-bit)

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

uBlock origin

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) x86_64 laptop, Intel Core i5

(b) Physical Memory & Swap Space in GB: 8/24

(c) SSD

(d) Anything else that might be helpful to know?

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Cloudflare tunnel, but it doesn't matter for the issue.

**Comment by graciousgrey** [comment]
Thank you very much for reporting. 

If you click on the face, do you see the photos that are assigned to this face cluster? Could you turn on trace logs and watch them while you try to name the face? This could give us a hint as to where the problem might lie.

**Comment by Radiokot** [comment]
- If I click on this face, I see 8 other photos with me from this day, so it works;
- Here's the trace log output when I try to name the face:
```
web_1        | 2024-04-29T07:42:09.566468244Z time="2024-04-29T07:42:09Z" level=debug msg="api-v1: abort /api/v1/markers/:marker_uid with code 404 (entity not found)"
web_1        | 2024-04-29T07:42:09.566612417Z time="2024-04-29T07:42:09Z" level=debug msg="faces: file fscche6v4nz4g9n0 record not found (find marker to update)"
web_1        | 2024-04-29T07:42:09.566910219Z time="2024-04-29T07:42:09Z" level=debug msg="server: PUT /api/v1/markers/mscche6odyxe9a2q (404) [21.176438ms]"
```

**Comment by Radiokot** [comment]
Well, the file `fscche6v4nz4g9n0` this face marker refers to is indeed not there: search for `uid:fscche6v4nz4g9n0` gives not results

**Comment by Radiokot** [comment]
I think this may be caused by re-uploading the updated version of this exact photo and then running index cleanup.
This is what I remember doing before facing this bug:
1. Upload the photo (WebDAV to originals)
2. Get it indexed
3. Crop the original photo on the phone (keeping the file name)
4. Upload it again
5. Get it indexed again
6. Run the index with "Cleanup" checkbox

**Comment by lastzero** [comment]
It may be that cleanup currently does not remove related face markers when permanently deleting other index entries.

**Comment by lastzero** [comment]
Does a full rescan fix this?

**Comment by Radiokot** [comment]
I'll launch full rescan now

**Comment by Radiokot** [comment]
It did not help: the stray marker remained there.
However, by opening the updated photo and naming my face on the "People" tab, I was able to finally get rid of it 👌🏻

**Comment by lastzero** [comment]
The "faces audit --fix" command might have helped as well.

**Comment by lastzero** [comment]
From what I remember, markers reference the sha1 hash and the file or photo UID. So if you re-upload the same file with a (now) different UID, that might not cause the existing marker to get removed. The update method might then try to find the old file / photo, which fails since the stored UID is wrong.

**Comment by Radiokot** [comment]
Thanks for help and clarification, Michael

**Comment by lastzero** [comment]
@Radiokot There is a good chance that this problem cannot occur anymore with these changes:
- https://github.com/photoprism/photoprism/issues/4238

Would you be able to test this for us and report back (or otherwise close this issue)?

**Comment by Radiokot** [comment]
Sorry, Michael, I can't test it as my Intel server capable of face recognition is not currently running and needs repair.

**Comment by graciousgrey** [comment]
I will then try to reproduce it. Good luck with the repair!

**Comment by graciousgrey** [comment]
Unfortunately, I could not reproduce this. I replaced a file that was used as a cover for a new face with a cropped version and ran the indexing with the cleanup option enabled. I also tried complete indexing and no indexing, but in neither case did I get the "Entity not found" error message when I subsequently named the new face.

**Comment by Radiokot** [comment]
Okay, thank you for checking it, Theresa, the issue is to be closed as it can't be reproduced, and the original problem is solved anyway.
