### ISSUE TITLE
Cannot create apps and services

### ISSUE THREAD

**Issue by Alejandro18650** [photoprism/photoprism#4224]
#### 1. What does not work as documented?
I cannot create a new "Apps and Services". I always get an error message saying that the password is incorrect, but as you can see below, the server responds with a http 401

#### 2. How can we reproduce it?

1. Go to Settings/General Settings
2. Click on Applications and Services
3. Try to create an application and a service

![Captura de pantalla 2024-04-29 155551](https://github.com/photoprism/photoprism/assets/92676426/629cea0e-6c56-4b3b-bff1-788ab204d224)
![Captura de pantalla 2024-04-29 155632](https://github.com/photoprism/photoprism/assets/92676426/75e045a7-722d-40ff-9000-b96ebd02d095)
![Captura de pantalla 2024-04-29 155656](https://github.com/photoprism/photoprism/assets/92676426/142087c1-67dd-4799-a0be-635b7c6c5b3c)
![Captura de pantalla 2024-04-29 155709](https://github.com/photoprism/photoprism/assets/92676426/784b238a-6657-4889-a357-ec3d7c7ffc44)

PhotoPrism built in a Raspberry Pi ([240420-ef5f14bc4](https://docs.photoprism.app/release-notes/)). It has been tested in the Windows version of Brave.
To access the server, I have several ports open in the router and I use a url from duckdns.org

**Comment by graciousgrey** [comment]
Just to be sure, what did you enter as password? You need to enter the login password of the user that is currently signed in. Afterwards a secure app password will be generated for you.

**Comment by Alejandro18650** [comment]
Sorry, I'm silly. It works properly
