### ISSUE TITLE
Review: Automatically approve photos when adding them to an album

### ISSUE THREAD

**Issue by clearlynotstefan** [photoprism/photoprism#4229]
Torn between feature request and bug report, but I'd call it a bug because there's absolutely no scenario where a user would add a photo to an album from the Review screen and then disapprove of it. PP should automatically approve any photo that's manually placed in an album.

**Comment by lastzero** [comment]
Thank you very much for your kind words! It will be our pleasure to test this and improve it for you if needed.

**Comment by lastzero** [comment]
@clearlynotstefan An updated [Development Preview](https://hub.docker.com/r/photoprism/photoprism/tags?name=preview) build is now available for you to test these changes:
- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
@clearlynotstefan Would you be able to test this for us?

**Comment by lastzero** [comment]
@clearlynotstefan any update on this?
