### ISSUE TITLE
Auth: Running the "photoprism users reset" command should also recreate the "auth_sessions" table

### ISSUE THREAD

**Issue by lapo-luchini** [photoprism/photoprism#4242]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

After migration from 231128 to 240420 login does not work anymore, when password is actually wrong a 401 with `{error:"Invalid credentials"}` is received, but when password is right a 200 with `{error:"Invalid credentials"}` is received.

![image](https://github.com/photoprism/photoprism/assets/420454/84686f24-9f81-4936-af41-87d40145dc63)

#### 2. How can we reproduce it?

1. Upgrade (with no errors)
2. Try login (to no avail)
3. Try `photoprism user reset` + `photoprism passwd admin`
4. Try login again (to no avail)
5. Check logs: nothing at all is shown (even with `--debug` and `--trace`)

#### 3. What behavior do you expect?

Actual login.
Give us a clear and concise description of what you expect.

#### 4. What could be the cause of your problem?

With zero error logs I really don't know.
I'd like to know how to proceed with debug.
I build the software (on FreeBSD) by myself, and can easily try patches.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Would be a bit difficult.

#### 6. Which software versions do you use?

a. photoprism version 240420-240420-ef5f14b-FreeBSD-amd64-DEBUG-build-240508
b. MariaDB 10.11.7
c. FreeBSD 14.0
d. Firefox
e. uBlock Origin

#### 7. On what kind of device is PhotoPrism installed?

Home server / NAS, based on Intel i7.
FreeBSD 14.0, root on ZFS.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

```nginx
    server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        server_name  <domain>;

        ssl_certificate     /var/db/acme/certs/<domain>/fullchain.cer;
        ssl_certificate_key /var/db/acme/certs/<domain>/foto.lapo.it.key;
        add_header Strict-Transport-Security "max-age=31536000";

        location / {
            proxy_pass http://127.0.0.1:2342/;
            # Websocket
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
```

**Comment by lastzero** [comment]
Did you try **all** of this?
- https://docs.photoprism.app/getting-started/troubleshooting/#cannot-log-in

If you've been building from the develop branch (unstable) before, you should certainly run the "photoprism auth reset" command as mentioned in our docs.

Logs should also work on FreeBSD?

**Comment by lapo-luchini** [comment]
Ohhh, `auth reset` did it!
I did try `user reset` and didn't notice they weren't the same command, so I thought I already did it.
Thanks!

**Comment by lastzero** [comment]
In order to avoid any confusion, these changes will recreate the `auth_sessions` database table when you run the `photoprism users reset --yes` command in a terminal. They also add a more detailed description of the `photoprism auth reset` and `photoprism users reset` subcommands to better explain what they do.

**Comment by lastzero** [comment]
I've also added more notes on this to our documentation, for example:
- https://docs.photoprism.app/user-guide/users/cli/#managing-user-accounts

**Comment by jfbordelais** [comment]
Bonjour, j ai perdu mon mot de passe de PhotoPrism..comment le réinitialiser ? j ai installé PhotoPrism depuis les extensions de OMV .message erreur :"Les informations d'identification sont invalides" login : admin , MdP: ?
merci d avance
