### ISSUE TITLE
Docker image transcode: map /usr dir

### ISSUE THREAD

**Issue by maicss** [photoprism/photoprism#4244]
**Describe what problem this solves and why this would be valuable to many users**

Everytime recreate container, photorism will download TensorFlow lib from https://dl.photoprism.app/tensorflow/amd64/libtensorflow-amd64-avx2-1.15.2.tar.gz. For somewhere who has a bad network to connect to this assert(I am from China, we have a GFW), it will takes about 30min~60min to download this assert.
**Describe the solution you'd like**
Map this file to local, we can download this file behand VPN. 
```
Installing TensorFlow 1.15.2 for AMD64-AVX2 in "/usr"...
Downloading amd64 libs from "https://dl.photoprism.app/tensorflow/amd64/libtensorflow-amd64-avx2-1.15.2.tar.gz". Please wait.
apt-get update
Detecting driver...
/scripts/install-tensorflow.sh auto
init: tensorflow
Extracting "/tmp/amd64/libtensorflow-amd64-avx2-1.15.2.tar.gz" to "/usr".
Running "ldconfig".
Done.
```
**Describe alternatives you've considered**

**Additional context**
And for the same reason, can we change source.list for command `apt-get update`? 
```
pt-get update
Get:1 http://archive.ubuntu.com/ubuntu mantic InRelease [256 kB]
Get:2 http://security.ubuntu.com/ubuntu mantic-security InRelease [109 kB]
Get:3 http://archive.ubuntu.com/ubuntu mantic-updates InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu mantic-security/restricted amd64 Packages [427 kB]
Get:5 http://archive.ubuntu.com/ubuntu mantic-backports InRelease [90.8 kB]
Get:6 http://archive.ubuntu.com/ubuntu mantic/multiverse amd64 Packages [293 kB]
Get:7 http://archive.ubuntu.com/ubuntu mantic/universe amd64 Packages [18.8 MB]
Get:8 http://security.ubuntu.com/ubuntu mantic-security/main amd64 Packages [445 kB]
Get:9 http://security.ubuntu.com/ubuntu mantic-security/universe amd64 Packages [360 kB]
Get:10 http://security.ubuntu.com/ubuntu mantic-security/multiverse amd64 Packages [6227 B]
Get:11 http://archive.ubuntu.com/ubuntu mantic/restricted amd64 Packages [180 kB]
Get:12 http://archive.ubuntu.com/ubuntu mantic/main amd64 Packages [1808 kB]
Get:13 http://archive.ubuntu.com/ubuntu mantic-updates/restricted amd64 Packages [449 kB]
Get:14 http://archive.ubuntu.com/ubuntu mantic-updates/multiverse amd64 Packages [9605 B]
Get:15 http://archive.ubuntu.com/ubuntu mantic-updates/universe amd64 Packages [470 kB]
Get:16 http://archive.ubuntu.com/ubuntu mantic-updates/main amd64 Packages [522 kB]
Get:17 http://archive.ubuntu.com/ubuntu mantic-backports/universe amd64 Packages [4216 B]
```

Thanks for your great work!

**Comment by lastzero** [comment]
Thanks for your feedback! Note that installing TensorFlow with AVX support is optional. It likely won't save you enough indexing time to justify the download, so I recommend to remove "tensorflow" from the init actions. You also don't necessarily need to update the Ubuntu distribution packages if you use our most recent version, since we always update them before making a release.

**Comment by maicss** [comment]
1, transcoding is a good feature, I like it, why not map the folder to local, make the download optional?
2, I am using the 2024-04-20 23:46:12 build latest version

**Comment by lastzero** [comment]
You probably copied the config example from our [advanced user guide](https://docs.photoprism.app/getting-started/advanced/transcoding/#intel-quick-sync)?

```yaml
services:
  photoprism:
    environment:
      PHOTOPRISM_FFMPEG_ENCODER: "intel"
      PHOTOPRISM_INIT: "intel tensorflow"
      ...
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ...
```

As mentioned above, installing a different version of TensorFlow is completely optional and you do not need this to enable hardware video transcoding. However, you may need to install additional system packages, e.g.:

```yaml
services:
  photoprism:
    environment:
      PHOTOPRISM_FFMPEG_ENCODER: "intel"
      PHOTOPRISM_INIT: "gpu"
      ...
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ...
```
Also see the info box in our transcoding setup documentation:

> Most users can either skip PHOTOPRISM_INIT completely or just use PHOTOPRISM_INIT: "tensorflow" to install a special version of TensorFlow that improves indexing performance if the server CPU supports AVX, which is independent of video transcoding and the type of GPU.

**Comment by maicss** [comment]
I'm a little confused.
Now suppose I want to use my own hardware to accelerate video transcoding, intel i5-12450h, which comes with an intel integrated GPU, and the model may be UHD730. This CPU supports AVX instructions.

I have two questions
1. PHOTOPRISM_INIT: Is it enough to just set the value of "intel tensorflow" to intel? tensorflow is optional, right?
2. Can the AVX instruction set of the CPU be used to accelerate transcoding? Does this have anything to do with whether to add tensorflow?

Thank you for your quick reply, I really appreciate it.

**Comment by lastzero** [comment]
Yes, setting it to intel (installs qsv drivers) or gpu (auto detect) is enough to enable hardware video transcoding. Make sure you remove the existing photoprism container with "docker compose down" before you try again (or start it with  "docker compose up --force-recreate") since the init actions will only be executed when it starts for the first time.

Edit: AVX / TensorFlow are NOT required or used for hardware video transcoding.
