### ISSUE TITLE
Sharing: One-off sharing

### ISSUE THREAD

**Issue by kevincox** [photoprism/photoprism#4248]
**Describe what problem this solves and why this would be valuable to many users**

Right now you can share albums or a few other things. However all of these items are "permanent" and end up more tedious to share and end up cluttering your album list. It would be great if there was a way to share 1 or multiple photos/videos in a way that was quick, easy and avoided creating clutter.

**Describe the solution you'd like**

My current idea is something like this:

1. Select one or multiple items.
2. In the menu there is a "Share Link" option.
3. When clicked this does the following:
4. Create an album with a title such as "Link Sharing on {date}"
5. The album is flagged as a "Share Album"
6. A sharing link is created with a configured default validity.
7. The user is provided the link in some way. Ex:
    - A dialog with the link is shown. 
    - The link is copied to the clipboard.
    - A share menu is triggered.
8. These "Share Albums" are filtered out of most default views (but likely can be seen in some way ex: https://github.com/photoprism/photoprism/issues/1330)

**Describe alternatives you've considered**

a. Create a different type of collection for temporary shares.
  - Seems like extra complication.
b. Just make creating + sharing an album easier.
  - Still clutters album list.

**Additional context**

Some possible future improvements:
1. Nicer behaviour for single-item shares.
2. Ability to use this for allowing other users to upload items.

**Comment by graciousgrey** [comment]
Related to:

- https://github.com/photoprism/photoprism/issues/466

**Comment by kevincox** [comment]
The title of that issue sounds like it is only for specific items but the main issue and the discussion clearly wants to also support multi-items shares. So I think this is a complete duplicate. I'll close this.
