### ISSUE TITLE
UX: Remove archive action from the menu in Library > Hidden

### ISSUE THREAD

**Issue by qlyoung** [photoprism/photoprism#4255]
#### 1. What is not working as documented?

If I go to "Library -> Hidden", select an item, and archive it, that item does not appear in the archive, and the archive count does not increase to account for that item.

#### 2. How can we reproduce it?

1. Go to "Library -> Hidden"
2. Select an item
3. Archive it
4. Try to find it in the archive

#### 3. What behavior do you expect?

The image should appear in the archive.

#### 4. What could be the cause of your problem?

I do not know.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

These are the logs I see when I archive an item from hidden:

```
photoprism-1  | time="2024-05-14T01:41:45Z" level=info msg="photos: archiving psdfqppe3jl3pmsz"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="photo: updated sidecar file IMG_1818.yml"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="index: updating counts"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="counts: updated 0 places [36.602065ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="counts: updated 0 subjects [3.394478ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="counts: updated 0 labels [43.638191ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="index: updating covers"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="covers: updated 0 albums [17.623119ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="covers: updated 0 folders [38.993528ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="covers: updated 0 months [19.317368ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="covers: updated 0 labels [55.163349ms]"
photoprism-1  | time="2024-05-14T01:41:45Z" level=debug msg="covers: updated 0 subjects [7.012116ms]"
photoprism-1  | time="2024-05-14T01:41:46Z" level=debug msg="server: POST /api/v1/batch/photos/archive (200) [455.64922ms]"
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...

```
root@240513:/photoprism$ photoprism version
DEBU[2024-05-14T01:42:56Z] settings: loaded from /photoprism/storage/config/settings.yml
240513-f00d88dfc-Linux-AMD64-Plus
```
```
[PhotoPrism® CE] Build [240513-f00d88dfc](https://docs.photoprism.app/release-notes/)
```

(b) Database Type & Version: MariaDB, MySQL, SQLite,...

MariaDB

(c) Operating System Types & Versions: Linux, Windows, Android,...

Docker compose on Ubuntu Linux 22.04.4

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...

Firefox

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?

You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

(b) Physical Memory & Swap Space in GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

(d) Anything else that might be helpful to know?

I recognize that this is a preview build. I will attempt to reproduce on a recent stable release.

**Comment by lastzero** [comment]
Pictures listed under "Hidden" are not displayed in your library, i.e. they are already archived ("soft deleted"/removed from your library). So if you use the "Archive" action in "Hidden", this will cause the pictures to not appear at all, e.g. when you gave up on finding and fixing the problem that prevents them from being indexed.

If this is confusing, we could remove the "Archive" action in the menu under "Hidden" or replace it with a "Delete Permanently" action?

**Comment by qlyoung** [comment]
> So if you use the "Archive" action in "Hidden", this will cause the pictures to not appear at all

And this situation is unrecoverable from the web UI, right? In my case I accidentally clicked "Archive" mistaking it for the "Download" button, the picture was gone, and I had no way to find it - even on disk - since I didn't get any identifying data before archiving it (thumbnail was broken so I didn't see the picture, which is why I was trying to download it).

> e.g. when you gave up on finding and fixing the problem that prevents them from being indexed.

I don't think I said I gave up on finding and fixing the problem that prevented that image from being indexed 😕. I was making a first pass at doing that by just trying to download the image and accidentally clicked 'Archive'.

> If this is confusing, we could remove the "Archive" action in the menu under "Hidden" or replace it with a "Delete Permanently" action?

Conceptually, the `Archive` is a "place" - if I 'archive' a picture, I expect it to appear in the `Archive`, no matter what page I performed the 'archive' action on. However, in this case in order for pictures to appear in the `Archive` they need to be indexable, and they are not which is why they are in `Hidden`, so it's not possible to make the 'archive' button send pictures from `Hidden` to `Archive`, if I understand correctly?

In any case, since the 'archive' button does something to the picture that is different on the `Hidden` page than it does on any other page, I agree that it should be changed to reflect what it does. "Delete permanently" sounds very reasonable and a confirmation dialog would be even better, since this is a rare case of an unrecoverable action within Photoprism that users are unlikely to expect or fully understand.

**Comment by lastzero** [comment]
I'll try to fix / improve this when I get a chance. Since we rarely see any broken / hidden pictures anymore after having fixed most of the issues that could lead to this, the menu options in Hidden were clearly flying under our radar. The picture metadata should still be in your database, but you would need to update the photos table manually to make it visible again in the UI (it may be that a combination of search filters like hidden:true archived:true work as well).

**Comment by qlyoung** [comment]
> I'll try to fix / improve this when I get a chance.

Sounds great, thank you!

> Since we rarely see any broken / hidden pictures anymore after having fixed most of the issues that could lead to this, the menu options in Hidden were clearly flying under our radar. 

No problem, given the breadth and complexity of the software there's going to be rough edges here and there.

> The picture metadata should still be in your database, but you would need to update the photos table manually to make it visible again in the UI (it may be that a combination of search filters like hidden:true archived:true work as well).

Thanks for the tip. I completely reindexed and I think that resolved the problem.

**Comment by lastzero** [comment]
A new release that includes this enhancement will be available soon:
- https://docs.photoprism.app/release-notes/
