### ISSUE TITLE
Location batch editing: error 401 on updating

### ISSUE THREAD

**Issue by ItalianBoB** [photoprism/photoprism#4258]
#### 1. What is not working as documented?

Browser throws error 401 message when updating location for a batch of pictures

#### 2. How can we reproduce it?

1. Select multiple pictures
2. Select "location" in the bottom right corner menu
3. enter a location on the map input field
4. Select "save" in the bottom right corner menu

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
![image](https://github.com/photoprism/photoprism/assets/137296373/c513121a-47c7-4fc0-b5ae-26569042b16c)

LOG:
time="2024-05-15T08:39:19Z" level=debug msg="server: PUT /api/v1/photos/psdhkn2uecazq8qx (401) [163.849µs]"
time="2024-05-15T08:39:19Z" level=debug msg="server: PUT /api/v1/photos/psdh9j2ahnmza5cw (401) [145.368µs]"

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number:  **Docker - ARM64 - Build 240420-ef5f14bc4**
(b) Database Type & Version: **MariaDB,**
(c) Operating System Types & Versions: **Debian Bullseye**
(d) Browser Types & Versions: **Chrome**
(e) Ad Blockers, Browser Plugins, and/or Firewall Software? **Geolocation plugin  for photoprism** 

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: **Raspberry pi 4 4GB .**

(c) Storage Type: HDD for storage SSD for docker container

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Apache reverse proxy

**Comment by graciousgrey** [comment]
Thank you for your feedback! 
As far as I can see, the error comes from the plugin and not from PhotoPrism itself. So you may want to report this in the plugin's repository. 
I could imagine that changes regarding authentication are necessary there, as we have added support for 2FA and OAUTH2 client credentials in the last release.
