### ISSUE TITLE
Directory structure after import

### ISSUE THREAD

**Issue by isisyodin** [photoprism/photoprism#426]
I am testing Photoprism docker in Unraid, and so far everything is working well. I am coming from Synology's Moments which works but looking for an alternative as my NAS is getting close to its demise.
I would like to find out if the directory structure after importing can be customized. 

Photoprism as far as I can tell uses:
Year
->Month
--->photo files

How about being able to do this:
Year-Month-Date1
->photo files
Year-Month-Date2
->photo files

Great work, thanks!

**Comment by lastzero** [comment]
While that's possible, it's not implemented yet as it significantly increases the amount of testing necessary. Might offer this later.

**Comment by graciousgrey** [comment]
I close this, as it will be part of #475
