### ISSUE TITLE
Potoprism unexpectedly collapsed

### ISSUE THREAD

**Issue by ai30328348** [photoprism/photoprism#4260]
Crashes when scanning pictures larger than 100MB due to high CPU usage

photoprism-1  | time="2024-05-16T03:16:51Z" level=info msg="media: 'mz20pro.png' was taken at 2024-04-25 15:01:15.23345566 +0000 UTC (file mod time)"
photoprism-1  | /scripts/entrypoint.sh: line 103:  1323 Killed                  /usr/bin/setpriv --reuid "${PHOTOPRISM_UID}" --regid "${PHOTOPRISM_GID}" --init-groups --inh-caps -all "$@"
mariadb-1     | 2024-05-16  3:21:50 6 [Warning] Aborted connection 6 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 9 [Warning] Aborted connection 9 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 4 [Warning] Aborted connection 4 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 3 [Warning] Aborted connection 3 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 5 [Warning] Aborted connection 5 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 8 [Warning] Aborted connection 8 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
mariadb-1     | 2024-05-16  3:21:50 7 [Warning] Aborted connection 7 to db: 'photoprism' user: 'photoprism_sql' host: '172.19.0.3' (Got an error reading communication packets)
photoprism-1 exited with code 0

**Comment by graciousgrey** [comment]
Does your server fulfill our system requirements? Do you have at least 4GB Swap configured?

https://docs.photoprism.app/getting-started/#system-requirements
