### ISSUE TITLE
[Question] How-To reset password inside the db

### ISSUE THREAD

**Issue by xxlbug** [photoprism/photoprism#428]
Hi there,

little bit of a problem for me and I couldn't find an answer elsewhere online: 
I've got prism to work perfectly on my own server in the docker variant and with the sqlite db. Sadly I didn't save the password I changed the initial one to. Since I use a password generator there is no way I will get the right one after the fact.

I got access to all config files and can open the db file without a problem.

So: Is there a way I can update the password in the db or create a new account without having to reset the application?

Thank you for your time!

**Comment by lastzero** [comment]
Run `photoprism passwd` in a terminal 📺

**Comment by xxlbug** [comment]
First: Thank you for the answer, worked nicely :-)
Second: Wow, speak of reaction time
Third: A suggestion: Create a little section in the user guide on the website, I found it only hidden in the docker instructions after you showed me the way :-)

**Comment by lastzero** [comment]
We'll improve our docs after coming back from vacation 🌻
