### ISSUE TITLE
Config: Disable the use of libvips on 32-bit operating systems

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#4299]
This seems to be necessary due to compatibility issues between our Go wrapper library and `libvips` (which is implemented in C).

**Comment by Radiokot** [comment]
The `photoprism:preview-armv7` (f30a713ba3a3868e4b183ca83ee85609eb7674d937a04aa87b0de4ff4234b822) build without `PHOTOPRISM_THUMB_LIBRARY` option generates correct thumbnails on ARMv7 32-bit computer, which means `vips` has been successfully disabled automatically.
