### ISSUE TITLE
Sporadically: "Month" not properly shown in details view 

### ISSUE THREAD

**Issue by uLUViL3gCs** [photoprism/photoprism#430]
For some photos that got imported, PP does not show the proper value of the month within photo's details view.
The field remains empty, while remaining fields seem to be filled properly.
The error occurred for several photos imported in local PP instance, as well as at least for one - if not more - photos as in public PP demo. 
Trigger for the problem is unknown.

Steps to reproduce:
OK:
Import Photos to PP
NOK
Check Photos' details: Navigation bar "Photos" -> select impacted photo(s) -> select "edit" -> select "Details"
Example as from local instance:
![Screenshot 2020-07-29 at 17 04 00](https://user-images.githubusercontent.com/64777347/88818204-bd692f00-d1be-11ea-9042-593f128c6ea9.png)
Example as in public PP demo:
![Screenshot 2020-07-29 at 17 08 54](https://user-images.githubusercontent.com/64777347/88818197-bb06d500-d1be-11ea-85fb-c0ddb8776300.png)

System details:
- Demo version running on demo.photoprism.org (PhotoPrism™ 200729-65c57f5-Linux-x86_64)
- local instance: PhotoPrism™ 200724-2859549-Linux-x86_64 / Chrome 81.0.4044.138 / macOS 10.15.5

Example original picture:
![P1110451](https://user-images.githubusercontent.com/64777347/88818930-97905a00-d1bf-11ea-8782-a6c0f8f9e82e.jpeg)

**Comment by lastzero** [comment]
Thank you for reporting this! Will be fixed. Not sure when exactly, since we're on vacation for the next couple of days.

**Comment by lastzero** [comment]
Can be tested later today, when the next Docker build is ready.

**Comment by uLUViL3gCs** [comment]
There is no more file on my system running version 200812-f737edb-Linux-x86_64 which is having the problem.
Also on PP demo the problem seems to be resolved.

Thanks a lot!
