### ISSUE TITLE
Photos / Live Photos with the same name are stacked, even if they are in different subfolders in the originals folder

### ISSUE THREAD

**Issue by mrRo8o7** [photoprism/photoprism#4309]
#### 1. What is not working as documented?

When I index my originals folders, photos and videos (live photos) with the same name are stacked despite the fact that the photos are in different subfolders. As a result, I sometimes see the wrong live photo when I move the mouse pointer over a photo.

The documentation says that only files with the same name and in the same folder (i.e. with different file extensions) are stacked to enable Live Photos. When I export photos from different iPhones to separate folders, they often have the same name. I don't think this is the desired behavior of Photoprism.

#### 2. How can we reproduce it?

1. Put photos / videos (live photos) with same name in different subfolders
2. Run photoprism index

Amount of originals: 31601
Config options: I have tried disabling sequential name stacking and metadata stacking without success.

#### 3. What behavior do you expect?

Photos / videos (live photos) from different folders should not be stacked.

#### 4. What could be the cause of your problem?

I think this is an implementation problem.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![Screenshot 2024-05-30 175900](https://github.com/photoprism/photoprism/assets/7901907/eb6bf723-86e3-44fd-a500-77cf4e392272)
![Screenshot 2024-05-30 175923](https://github.com/photoprism/photoprism/assets/7901907/f8ae873c-aa45-4dc3-8179-c8e95aa8a1a1)
![Screenshot 2024-05-30 180302](https://github.com/photoprism/photoprism/assets/7901907/6d4120e7-385b-44a4-8a9a-dfeec56df1de)

File structure:
USA/iPhoneA/IMG_6199.JPG
USA/iPhoneB/IMG_6199.JPG
USA/iPhoneB/IMG_6199.MOV

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number:  Unraid CA Docker, PhotoPrism CE Build 240523-923ee0cf7

(b) Database Type & Version: MariaDB 10.11.6-MariaDB-log

(c) Operating System Types & Versions: Linux (Unraid)

(d) Browser Types & Versions: Firefox

**Comment by lastzero** [comment]
It would be interesting to see the details of the other file `IMG_6199.JPG` underneath as well. I also noticed that the actual folders seem to be different from the example file structure you provided. All in all, this is not enough information to help with troubleshooting as we do not have the resources to create our own sample files and directories based on your screenshots. Could you provide us with a zip file with 3 sample files located in the same folders as in your library so we can try to reproduce your problem?
- https://www.photoprism.app/contact#file-samples

Thank you very much!

**Comment by lastzero** [comment]
Please also note that files that were already indexed (i.e. stacked before you moved them) will not be unstacked if you change their name or folder.

**Comment by mrRo8o7** [comment]
> It would be interesting to see the details of the other file `IMG_6199.JPG` underneath as well. I also noticed that the actual folders seem to be different from the example file structure you provided. All in all, this is not enough information to help with troubleshooting as we do not have the resources to create our own sample files and directories based on your screenshots. Could you provide us with a zip file with 3 sample files located in the same folders as in your library so we can try to reproduce your problem?
> 
> * https://www.photoprism.app/contact#file-samples
> 
> Thank you very much!

Of course I will send you a sample. Yes, because the file structure was an example. 
![Screenshot 2024-05-30 185130](https://github.com/photoprism/photoprism/assets/7901907/324e84cc-9d1f-401a-9311-4cbecd0feb47)


> Please also note that files that were already indexed (i.e. stacked before you moved them) will not be unstacked if you change their name or folder.

All right. The photos were never in the same folder or were moved after indexing. Yes, unfortunately I now have the problem that I can no longer get them unstacked. I don't want to reset my database either, as we have already sorted the photos into albums.

Thank you very much.

**Comment by mrRo8o7** [comment]
Thank you @lastzero. I was able to solve the problem by not using German umlauts in my Originals path.

**Comment by mrRo8o7** [comment]
Another small update. The problem was that I forgot the character set and collation when creating the table 

`CREATE DATABASE photoprism
CHARACTER SET = 'utf8mb4'
COLLATE = 'utf8mb4_unicode_ci';)`

 as described here: https://docs.photoprism.app/getting-started/advanced/databases/
