### ISSUE TITLE
New built in indexing schedule does not index video files

### ISSUE THREAD

**Issue by Beet4** [photoprism/photoprism#4326]
#### 1. What is not working as documented?

Previously I have been using the command docker exec -t PhotoPrism photoprism index --cleanup on a schedule on the host machine and it has been working as intended. Since the new bultin indexing scheulde was released I have been using that instead as an environment variable, it has worked fine but today I noticed that no video files has been added for a couple of weeks. I manually tried photoprism index --cleanup command and it found all video files that are in originals but missing from PhotoPrism and added them.

The video files are HEVC mp4 files in 4K 60 fps.

#### 2. How can we reproduce it?

1. Enable new built in indexing schedule
2. Add video and jpg file to /originals
3. Let the schedule run
5. No video file was added but the jpg file was added to PhotoPrism

#### 3. What behavior do you expect?

Same as `docker exec -t PhotoPrism photoprism index --cleanup` with video files added as well.

#### 4. What could be the cause of your problem?

No idea.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

A couple of weeks after running the bult in scheduler this is the log from the manual command:

`󰒍 root on unRAID at 󰋜 ~ docker exec -t PhotoPrism photoprism index --cleanup
INFO[2024-06-09T17:53:12+02:00] Become a member today, support our mission and enjoy our member benefits! 💎
INFO[2024-06-09T17:53:12+02:00] Visit https://www.photoprism.app/membership to learn more.
INFO[2024-06-09T17:53:13+02:00] indexing originals in /photoprism/originals
INFO[2024-06-09T17:53:13+02:00] config: enabled read-only mode
INFO[2024-06-09T17:53:13+02:00] classify: loading nasnet
INFO[2024-06-09T17:53:14+02:00] classify: loading labels from labels.txt
INFO[2024-06-09T17:53:19+02:00] convert: converting 20240607_152337.mp4 to 20240607_152337.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:19+02:00] convert: converting 20240607_153450.mp4 to 20240607_153450.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:19+02:00] convert: converting 20240607_152130.mp4 to 20240607_152130.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:20+02:00] convert: 20240607_152337.mp4.jpg created in 1.375125529s (ffmpeg)
INFO[2024-06-09T17:53:20+02:00] convert: 20240607_153450.mp4.jpg created in 1.148611112s (ffmpeg)
INFO[2024-06-09T17:53:20+02:00] media: generated 10 thumbnails for Bilder/Mobil/2024/06/20240607_152337.mp4.jpg [348.101081ms]
INFO[2024-06-09T17:53:20+02:00] index: added main mp4 file Bilder/Mobil/2024/06/20240607_152337.mp4
INFO[2024-06-09T17:53:20+02:00] media: generated 10 thumbnails for Bilder/Mobil/2024/06/20240607_153450.mp4.jpg [368.409648ms]
INFO[2024-06-09T17:53:21+02:00] index: added main mp4 file Bilder/Mobil/2024/06/20240607_153450.mp4
INFO[2024-06-09T17:53:21+02:00] convert: 20240607_152130.mp4.jpg created in 1.993882632s (ffmpeg)
INFO[2024-06-09T17:53:21+02:00] media: generated 10 thumbnails for Bilder/Mobil/2024/06/20240607_152130.mp4.jpg [235.390471ms]
INFO[2024-06-09T17:53:21+02:00] index: added main mp4 file Bilder/Mobil/2024/06/20240607_152130.mp4
INFO[2024-06-09T17:53:24+02:00] convert: converting 20240601_211550.mp4 to 20240601_211550.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:24+02:00] convert: converting 20240601_221930.mp4 to 20240601_221930.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:24+02:00] photo: created sidecar file Bilder/Mobil/2024/06/20240607_152337.yml
INFO[2024-06-09T17:53:24+02:00] index: stacked related jpg file Bilder/Mobil/2024/06/20240607_152337.mp4.jpg
INFO[2024-06-09T17:53:24+02:00] photo: created sidecar file Bilder/Mobil/2024/06/20240607_153450.yml
INFO[2024-06-09T17:53:24+02:00] index: stacked related jpg file Bilder/Mobil/2024/06/20240607_153450.mp4.jpg
INFO[2024-06-09T17:53:24+02:00] photo: created sidecar file Bilder/Mobil/2024/06/20240607_152130.yml
INFO[2024-06-09T17:53:24+02:00] index: stacked related jpg file Bilder/Mobil/2024/06/20240607_152130.mp4.jpg
INFO[2024-06-09T17:53:24+02:00] convert: converting 20240606_182706.mp4 to 20240606_182706.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:24+02:00] convert: converting 20240606_182337.mp4 to 20240606_182337.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:25+02:00] convert: 20240606_182706.mp4.jpg created in 645.573829ms (ffmpeg)
INFO[2024-06-09T17:53:25+02:00] convert: 20240606_182337.mp4.jpg created in 710.768021ms (ffmpeg)
INFO[2024-06-09T17:53:25+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240606_182706.mp4.jpg' [366.977181ms]
INFO[2024-06-09T17:53:25+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240606_182337.mp4.jpg' [290.143922ms]
INFO[2024-06-09T17:53:25+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240606_182706.mp4'
INFO[2024-06-09T17:53:25+02:00] convert: converting 20240601_205435.mp4 to 20240601_205435.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:25+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240606_182337.mp4'
INFO[2024-06-09T17:53:25+02:00] convert: converting 20240607_120600.mp4 to 20240607_120600.mp4.jpg (ffmpeg)
INFO[2024-06-09T17:53:26+02:00] index: matched 3 labels with 20240606_182706.mp4.jpg [90.826726ms]
INFO[2024-06-09T17:53:26+02:00] convert: 20240601_211550.mp4.jpg created in 1.960308115s (ffmpeg)
INFO[2024-06-09T17:53:26+02:00] convert: 20240601_221930.mp4.jpg created in 1.836609215s (ffmpeg)
INFO[2024-06-09T17:53:26+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240601_221930.mp4.jpg' [274.598141ms]
INFO[2024-06-09T17:53:26+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240606_182337.yml'
INFO[2024-06-09T17:53:26+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240606_182337.mp4.jpg'
INFO[2024-06-09T17:53:26+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240601_221930.mp4'
INFO[2024-06-09T17:53:26+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240601_211550.mp4.jpg' [411.581195ms]
INFO[2024-06-09T17:53:26+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240606_182706.yml'
INFO[2024-06-09T17:53:26+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240606_182706.mp4.jpg'
INFO[2024-06-09T17:53:26+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240601_211550.mp4'
INFO[2024-06-09T17:53:26+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240601_221930.yml'
INFO[2024-06-09T17:53:26+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240601_221930.mp4.jpg'
INFO[2024-06-09T17:53:26+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240601_211550.yml'
INFO[2024-06-09T17:53:26+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240601_211550.mp4.jpg'
INFO[2024-06-09T17:53:27+02:00] convert: 20240601_205435.mp4.jpg created in 1.886339676s (ffmpeg)
INFO[2024-06-09T17:53:27+02:00] convert: 20240607_120600.mp4.jpg created in 1.763896821s (ffmpeg)
INFO[2024-06-09T17:53:28+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240601_205435.mp4.jpg' [267.185587ms]
INFO[2024-06-09T17:53:28+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240601_205435.mp4'
INFO[2024-06-09T17:53:28+02:00] media: generated 10 thumbnails for 'Sandras Bilder/Mobil/2024/06/20240607_120600.mp4.jpg' [302.556878ms]
INFO[2024-06-09T17:53:28+02:00] index: added main mp4 file 'Sandras Bilder/Mobil/2024/06/20240607_120600.mp4'
INFO[2024-06-09T17:53:28+02:00] index: matched 2 labels with 20240607_120600.mp4.jpg [69.063183ms]
INFO[2024-06-09T17:53:28+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240601_205435.yml'
INFO[2024-06-09T17:53:28+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240601_205435.mp4.jpg'
INFO[2024-06-09T17:53:28+02:00] photo: created sidecar file 'Sandras Bilder/Mobil/2024/06/20240607_120600.yml'
INFO[2024-06-09T17:53:28+02:00] index: stacked related jpg file 'Sandras Bilder/Mobil/2024/06/20240607_120600.mp4.jpg'
INFO[2024-06-09T17:53:46+02:00] index: updated 9 files [33.570064391s]
INFO[2024-06-09T17:53:51+02:00] files: deleted sidecar ec940da6b5d6d004b09f4512ee4d2fc5ee526aee_exiftool.json
INFO[2024-06-09T17:53:51+02:00] cleanup: removed Bilder/Mobil/2024/06/20240602_145415 from index
INFO[2024-06-09T17:53:51+02:00] files: deleted sidecar 1472131387bd96a76bc3e68aab89016b6f1e40f1_exiftool.json
INFO[2024-06-09T17:53:51+02:00] cleanup: removed Bilder/Mobil/2024/06/20240603_142501 from index
INFO[2024-06-09T17:53:51+02:00] files: deleted sidecar 7b019818cfcbfe01360e1cb47e454fe66e6ab75e_exiftool.json
INFO[2024-06-09T17:53:51+02:00] cleanup: removed Bilder/Mobil/2024/06/20240603_190904 from index
INFO[2024-06-09T17:53:51+02:00] cleanup: removed 3 index entries and deleted 3 sidecar files [96.928387ms]
INFO[2024-06-09T17:53:51+02:00] cleanup: searching for orphaned cache files
INFO[2024-06-09T17:53:53+02:00] cleanup: deleted 825 files from cache [1.361462346s]
INFO[2024-06-09T17:53:53+02:00] cleanup: deleted 828 files in total [2.148660064s]
INFO[2024-06-09T17:53:53+02:00] indexed 58,929 files in 40.677278943s`

Visit <https://docs.photoprism.app/getting-started/troubleshooting/browsers/> to learn how to diagnose frontend issues.

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: amd64, docker. Build 240531-60b3a4628

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux (Unraid, Docker)

(d) Browser Types & Versions: Firefox, Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Not applicable.

#### 7. On what kind of device is PhotoPrism installed?

Custom built server

(a) Device / Processor Type: Intel i7 14700K,

(b) Physical Memory & Swap Space in GB: 64GB

(c) Storage Type: SSD Cache, HDD array

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Reverse proxy yes, SWAG.

**Comment by graciousgrey** [comment]
Thank you for reporting. Unfortunately we cannot reproduce this.

Is it possible that you are running the command as root and that your photoprism instance is running with a different userID that does not have the right permissions to e.g. create files in the sidecar folder?

Does indexing new video files work when you trigger it using the [web UI](https://docs.photoprism.app/user-guide/library/originals/#manual-indexing) ?

**Comment by Beet4** [comment]
I've checked your suggestions and it was indeed a permissions error, the subfolders in sidecar had been created while the docker exec command was running as root while photoprism docker runs as nobody. I've fixed the permissions of all sidecar folder and files and now everything works as expected. Thank you for your support and time!
