### ISSUE TITLE
Unstacking results in error

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#435]
If I currently try to unstack photos, the interface just shows me an error "Invalid request". In the log files, I find "photo: only originals can be unstacked". But I am trying to unstack one raw file from another, so both should be originals?

Using the latest docker image.

**Comment by lastzero** [comment]
After fixing the frontend template (that was hiding the button after changing the default root path value for files), unstack seems to work just fine:

![Screenshot 2020-08-11 at 16 08 56](https://user-images.githubusercontent.com/301686/89907503-0d97b680-dbed-11ea-8c34-cbb458b055e7.png)

![Screenshot 2020-08-11 at 16 09 10](https://user-images.githubusercontent.com/301686/89907498-0cff2000-dbed-11ea-84a9-dc5624f183e7.png)

**Comment by fdw** [comment]
I updated the Docker container, but have not reloaded the database.
But with the existing stacks, I do not get a "Unstack" button anymore, neither on the raw file nor on the jpg. I do get a "Download" button, though.

**Comment by lastzero** [comment]
That's because the root column in the files table has changed from "" to "/" for files in originals so that we could improve indexing speed manyfold. So you need to completely reindex or use a fresh database.

**Comment by fdw** [comment]
Ah, okay. Then I'll do that. Thanks :)

**Comment by fdw** [comment]
Hi, I can confirm that it works now :)

However, I can't seem to get rid of the jpegs of the unstacked raws - they are still part of the original stack :/

**Comment by lastzero** [comment]
You need at least one JPEG for RAWs so that they can be displayed in a browser.

**Comment by fdw** [comment]
I know, and that makes sense :)

As an example:
Before, I had one stack consisting of:
* `A.raw`
* `A.jpg`
* `B.raw`
* `B.jpg`

After I unstacked `B.raw`, I expected this stack:
* `A.raw`
* `A.jpg`


What I have, instead, is:
* `A.raw`
* `A.jpg`
* `B.jpg`

How can I get rid of `B.jpg`?

**Comment by lastzero** [comment]
I see, maybe one of those was automatically created? It's not possible to unstack two files at once yet or manually add files to existing photos.

**Comment by fdw** [comment]
Yes, all of the jpgs were created automatically from raw files.

**Comment by lastzero** [comment]
In that case you probably only need a delete button for B.jpg?

**Comment by fdw** [comment]
That, or it should be automatically unstacked with the associated raw files.

**Comment by lastzero** [comment]
I'll add a **delete button** for **generated files** that are **not selected as primary**, so that we can hopefully close this issue...

**Comment by fdw** [comment]
Sound cool, thank you :)

**Comment by lastzero** [comment]
Finally getting to this! I'll try to implement a delete button that we can later also use to delete regular files.

**Comment by lastzero** [comment]
Will be deployed for testing with our next Docker image, hopefully later today.

**Comment by lastzero** [comment]
New Docker images available for testing! Note that the password will be reset to its initial state when upgrading. Our Docker images have been optimized for common NAS models. You can now set a specific user and group using the UID and GID environment variables. Feedback welcome.

**Comment by fdw** [comment]
Works beautifully, thank you :)
