### ISSUE TITLE
API: Authenticated requests return error code 400

### ISSUE THREAD

**Issue by thatsalltheyare90** [photoprism/photoprism#4354]
### Discussed in https://github.com/photoprism/photoprism/discussions/4262

<div type='discussions-op-text'>

<sup>Originally posted by **thatsalltheyare90** May 16, 2024</sup>
Hi,
I want to use the API to create albums and put photos in it. I'm using a laravel project for this.
I have created in access token and I'm able to fetch all originals using the photoprism's api (my access token is with full access).
But when I try to make a new album, I always get the following response:
`{"code":400,"error":"Unable to do that"}`

I'm sending this to photoprism:
```
  "headers" => [
    "Authorization" => "Bearer xxxxxx-xxxxxxx-xxxxxxx-xxxxxxx"
    "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0"
  ]
  "form_params" => [
    "Title" => "title"
    "Description" => "description"
    "Notes" => ""
    "Favorite" => false
  ]
]
```

I've tried various combinations in the form_params:
```
 'form_params' => [
                    'data' => [
                        'title'       => 'title',
                        'description' => 'description',
                        'notes'       => '',
                        'favorite'    => false,
                    ],
                ],
```

```
        'form_params' => [
                    'data' => json_encode([
                        'title'       => 'title',
                        'description' => 'description',
                        'notes'       => '',
                        'favorite'    => false,
                    ]),
                ],
```

```
'form_params' => [
                    json_encode([
                        'title'       => 'title',
                        'description' => 'description',
                        'notes'       => '',
                        'favorite'    => false,
                    ]),
                ]
```

Also I've tried with capitalizing the keys (Title instead of title), but I always get the same response.
I must be doing something wrong here but I have no idea what that is unfortunately.
I've tried to look ip up in the api documentation, but I don't have any knowledge about go so I couldn't take much from that code.</div>

**Comment by Hari-20042002** [comment]
check once the type of method you are sending with. It should be in post method for create album end point. Hope it will fix the error

**Comment by lastzero** [comment]
Error 400 indicates that either a required field is missing or the value type of a field is wrong:

https://github.com/photoprism/photoprism/blob/8c67fb1fe8cc45714a00c9881b1d93e18f145012/internal/api/albums.go#L82-L86

Please also make sure that the `Content-Type` request header is set to `application/json`. I recommend to check the requests that our JS frontend sends (via browser console) - and then use the same URI, methods, value names and types in your own application.

The `POST /api/v1/albums` request in particular should only require a `Title` (string) and optionally the `Favorite` flag (bool) to be set as JSON fields (not URL Form encoded):

https://github.com/photoprism/photoprism/blob/8c67fb1fe8cc45714a00c9881b1d93e18f145012/internal/api/albums.go#L91-L92

https://github.com/photoprism/photoprism/blob/8c67fb1fe8cc45714a00c9881b1d93e18f145012/internal/form/album.go#L10

https://github.com/photoprism/photoprism/blob/8c67fb1fe8cc45714a00c9881b1d93e18f145012/internal/form/album.go#L20

**Comment by lastzero** [comment]
Based on [some quick research](https://stackoverflow.com/questions/68610827/in-laravel-send-a-post-request-with-json-object-data) I did, something like the following should work [when using Laravel](https://laravel.com/docs/11.x/http-client):

```php
$headers = [
  "Authorization" => "Bearer [access token or app password]",
]

$data = [
  'Title' => 'foo',
  'Favorite' => false,
]

Http::withBody(json_encode($data), 'application/json')
    ->withOptions([
       'headers' => $headers
    ])
    ->post('https://your.domain/api/v1/albums');
```

**Comment by lastzero** [comment]
We welcome any contributions that help improve [our API docs](https://docs.photoprism.app/developer-guide/api/) and make them easier to use for developers, e.g.:
- https://github.com/photoprism/photoprism/issues/2132

**Comment by thatsalltheyare90** [comment]
> Based on [some quick research](https://stackoverflow.com/questions/68610827/in-laravel-send-a-post-request-with-json-object-data) I did, something like the following should work [when using Laravel](https://laravel.com/docs/11.x/http-client):
> 
> ```
> $headers = [
>   "Authorization" => "Bearer [access token or app password]",
> ]
> 
> $data = [
>   'Title' => 'foo',
>   'Favorite' => false,
> ]
> 
> Http::withBody(json_encode($data), 'application/json')
>     ->withOptions([
>        'headers' => $headers
>     ])
>     ->post('https://your.domain/api/v1/albums');
> ```

Ah yes, this was my problem, I wasn't sending the data as body and also not json encoded. Thanks!
