### ISSUE TITLE
Massive collection, CPU usage and threshold on scanning feature

### ISSUE THREAD

**Issue by Mansour-J** [photoprism/photoprism#438]
Hey,

I have a massive images and videos collection 3TB+ that I would like to use photoprism with it.

Now that I have an instance of it running on my linux box it is using the CPU as much as it can for scanning....

Is there a way to put a threshold and make it consistent.... for example I want it to use 30% of the CPU and I wouldn't mind if it takes 4 days or a week :) 

I just dont want to stress the CPU

![image](https://user-images.githubusercontent.com/12991664/89117821-0689ed80-d4f5-11ea-8201-605f23f2c4de.png)

**Comment by lastzero** [comment]
Then simply reduce the number of workers to 30% of your virtual or physical cores, whatever you prefer. Run `photoprism help` to see all config options.

**Comment by Mansour-J** [comment]
I am running it via this `docker-compose` file [link here](https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/docker-compose.yml).

Any chance that there is a ENV_VARIABLE or some config setting I can set ? or I have to ssh to container and do it manually?

**Comment by lastzero** [comment]
Should be `PHOTOPRISM_WORKERS`, you can set all config options as env variables.

**Comment by Mansour-J** [comment]
@lastzero yes you are right - I got to know `PHOTOPRISM_WORKERS` is the env_variable for it by doing `photoprism help` there are quite a lot of other settings and env variable `photoprism help` shows 👍

I set it through docker env variable and is doing what is intended to do which is AWESOME 👍 

It's been an hour playing around with Photoprism and I think I have a lot to learn.
