### ISSUE TITLE
TrueNAS - Cannot save config changes

### ISSUE THREAD

**Issue by TheGroundZero** [photoprism/photoprism#4390]
#### 1. What is not working as documented?

Editing the container/app settings fails as certain host paths are configered as required values but these settings are marked as not-editable in the config editor.

#### 2. How can we reproduce it?

1. Go to TrueNAS SCALE apps
2. Edit config for photoprism app
3. It's not necessary to try and edit anything. Do notice `Photoprism Import Storage`, `Photoprism Storage` and `Photoprism Originals Storage` cannot be changed (set to `Host Path (Path that already exists on the system)` in my case).
4. Click `Save`
5. Notice error

#### 3. What behavior do you expect?

Being able to change the config of the TrueNAS app (like adding an Environment Variable).

#### 4. What could be the cause of your problem?

For some reason, 3 fields are set to be mandatory but read-only at the same time, and the default setting is somehow not accepted.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://github.com/photoprism/photoprism/assets/2406013/383bcb44-e2bb-4f92-b6af-8d1fe3f1e338)

```
Error: [EINVAL] values.photoprismStorage.import.hostPathConfig.hostPath: attribute required [EINVAL] values.photoprismStorage.storage.hostPathConfig.hostPath: attribute required [EINVAL] values.photoprismStorage.originals.hostPathConfig.hostPath: attribute required 
```

![settings](https://github.com/photoprism/photoprism/assets/2406013/e1d5b53a-1c71-4c3f-81f0-afef4a128694)

#### 6. Which software versions do you use?

TrueNAS SCALE app 240531_2.0.8

PhotoPrism® CE Build 240531-60b3a4628

#### 7. On what kind of device is PhotoPrism installed?

TrueNAS SCALE

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

/

**Comment by graciousgrey** [comment]
Thank you for your feedback! 

The TrueNAS Scale app is a third-party integration that is not maintained by us, so unfortunately we cannot help in this case. You might get help with this in a TrueNAS help forum.

**Comment by TheGroundZero** [comment]
FYI: https://forums.truenas.com/t/photoprism-config-cannot-be-updated-einval/8472

**Comment by lastzero** [comment]
Thanks! I'll go ahead and close this issue :)
