### ISSUE TITLE
Unexpected identical hash values in Canonical Filenames 

### ISSUE THREAD

**Issue by tilusnet** [photoprism/photoprism#4393]
Hello,

I am raising this with concern that Canonical Filenames used in duplicate detection may not be generated correctly when several identically named files are imported, but with different extension. The files have unrelated binary content.

Example:
* foo/bar/baz/fileX.jpg
* foo/bar/baz/fileX.png
  

#### 1. What is not working as documented?

Since the files are different in content, they should generate different CRC32c hash values used in Canonical Filenames.

However this doesn't seem to be the case, for example:

| Imported Filenames | File Size | Canonical Filename | CRC32c Used | Correct CRC32c |
|--------|--------|--------|--------|--------|
| "2021-03-02 15.13.44-2.jpg" | 28.0 kB | 20210302_151344_618AD105.jpg :heavy_check_mark: | 618AD105 | 618AD105 |
| "2021-03-02 15.13.44-2.png" | 3.3 MB | 20210302_151344_618AD105.png :x:  | 618AD105 | A90C5854 |

Notice, the imported filenames differ only in extension.

I suspect the second .png file's canonical name hash value is incorrect. 
As result, duplicates against this second file will fail to get detected in Photoprism.

More examples below:

Consider the Canonical Filenames generated. Notice in the highlighted files the suspiciously identical hash values for files that are _different_ in binary content -- the filesize is a clear indicator of their difference too:

![Canonical_Filenames](https://github.com/user-attachments/assets/45a178bf-be6a-40a9-9946-4d132ac877c4)

These are the corresponding Imported files, with near identical filenames, which is a coincidence. The files are different, varying extensions and different contents:

![Imported_Filenames](https://github.com/user-attachments/assets/89e891cf-9584-4e3e-bda8-731b49ece748)

The severity of the problem is also highlighted by the use case of Dropbox which will generate these (near) identical filenames all the time when one is synchronising with their service.

#### 2. How can we reproduce it?

1. Take two arbitrary files, of different type, eg. a JPG and a PNG. The files should be unrelated in content.
2. Put them in your Import folder under the same directory
3. Rename them to have identical names (but preserve their extension), ie. "MyFileX.jpg" and "MyFileX.png"
4. Run Import on the directory with the two files
5. Check their generated canonical filenames under Original, the hash counterpart should differ. 

#### 3. What behavior do you expect?

 "MyFileX.jpg" and "MyFileX.png" files' hash value in the canonical filename should be different as they are different files in content.

#### 4. What could be the cause of your problem?

The screenshots reveal a suspicious pattern of matching hash values where the imported filename part is identical. (but not the extension, nor content)

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

See screenshots attached above. 

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 Build 240531-60b3a4628

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: irrelevant

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? N/A

#### 7. On what kind of device is PhotoPrism installed?

Not relevant.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No and not relevant.

**Comment by tilusnet** [comment]
Are you caching by chance these hash values somewhere in the code?

**Comment by lastzero** [comment]
This is not a bug: The CRC32 checksum in the generated canonical filename belongs to the main file of a stack (a group of files) and therefore the same canonical name will (and must) be used when importing stacks.

https://github.com/photoprism/photoprism/blob/2197af8486f1f6d1407c306910ae472ef0bfceee/internal/photoprism/mediafile.go#L282-L285

Related Documentation:

- https://docs.photoprism.app/user-guide/organize/stacks/
- https://docs.photoprism.app/user-guide/library/duplicates/#related-files

**Comment by tilusnet** [comment]
Ah so it's stacking related then. Now it all makes much more sense.
Thanks for the answer and links.

Couple of questions for advice.

Q1.
So it seems that most of my Dropbox archived files are inadvertently stacked together, as there are many unrelated .jpg and .png files with identical names. I notice in your [docs](https://docs.photoprism.app/user-guide/settings/library/#stacks) (clearly written, thumbs up!) that I have no way of unstacking these files.
I assume my only option is renaming the imported unrelated jpg/png pairs, is there any alternative you can suggest? 

Q2.
I notice the "stacking effect" for such a jpg+png pair, with Files(2), as in the screenshot. However, there's only one file listed underneath, the PNG. Shouldn't I see both the JPG and PNG? I assume the JPG was chosen as "Primary" file. 

![image](https://github.com/user-attachments/assets/bdd27c26-c117-44a9-8cf4-ef26b85927c6)

**Comment by lastzero** [comment]
The original file names are stored in the files table, so you could write a script to restore the original path and file names. It's just that we do not have the resources to do this right now.

PNG files are supported as primary files, so a full resolution JPEG version is not strictly required.

**Comment by tilusnet** [comment]
Thanks, I found the stacked entries in the database `files` table. :+1:
This will indeed help me identifying the original filenames stacked together.

And if I'm not mistaken, the full table will also help with detecting files that were marked duplicates during previous Imports and left behind: these files will be those missing from `files:original_name`.
