### ISSUE TITLE
OIDC: Improve documentation for deleting accounts and using CLI commands

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [photoprism/photoprism#4394]
To reproduce- Configure OIDC. Login.

Voila, you have created a new user account.

Log out. Delete that newly created user via CLI.

Try to log back in via OIDC.

You get an error.

Run

`delete from auth_users where user_name = 'your_oidc_username'`

You can now log back in (and create a new account) with OIDC.

### Detailed Steps.

Configure OIDC [per documentation.](https://docs.photoprism.app/getting-started/advanced/openid-connect/)

Log in using OIDC.

![image](https://github.com/user-attachments/assets/eb8e0294-296e-499e-a97d-7ff05afb057e)

Log out.

![image](https://github.com/user-attachments/assets/8214755b-35a2-4852-9daa-6f753bd7e5bf)

Delete the user per [documented CLI commands](https://docs.photoprism.app/user-guide/users/cli/#managing-user-accounts)

``` bash
root@240711:/photoprism$ photoprism users rm akadmin
Delete user 'akadmin'?: y
INFO[2024-07-12T01:19:16Z] user 'akadmin' has been deleted
DEBU[2024-07-12T01:19:16Z] closed database connection
root@240711:/photoprism$
```

Try to log back in.

![image](https://github.com/user-attachments/assets/9063029f-d536-47ce-8e90-70c2a72414bc)

You now get invalid credentials error.

![image](https://github.com/user-attachments/assets/904a3149-da76-4b7b-ba09-2c967de72bd0)

No errors in logs.

![image](https://github.com/user-attachments/assets/028e10d9-2225-4b1e-9f3e-1d8699ca5ba6)

Log into database. Delete user.

``` sql
MariaDB [photoprism]> delete from auth_users where user_name = 'akadmin';
Query OK, 1 row affected (0.003 sec)
```

You can now create an account again.

![image](https://github.com/user-attachments/assets/e4778bec-04d0-40af-a56e-4d705791f73c)

**Comment by lastzero** [comment]
Works as intended. You can also use the CLI to restore the account. It's called soft delete, which is needed to keep track of who has been using the app aka security.

**Comment by XtremeOwnageDotCom** [comment]
@lastzero Suppose- that would make sense.

Perhaps we should update the OIDC documentation to reflect this one, for the edge-case when a admin deletes a user, and the user later tries to reauthenticate using OIDC.

Or- perhaps, automatically undelete the record, as OIDC would have created a new user record if the deleted record didn't exist?

**Comment by lastzero** [comment]
@XtremeOwnageDotCom Thanks for your feedback! We have improved our documentation to clarify this and to better cover the CLI commands available for managing user accounts:

- https://docs.photoprism.app/getting-started/advanced/openid-connect/#existing-accounts
- https://docs.photoprism.app/developer-guide/api/oidc/#existing-accounts

Does this look good to you?

**Comment by XtremeOwnageDotCom** [comment]
> @XtremeOwnageDotCom Thanks for your feedback! We have improved our documentation to clarify this and to better cover the CLI commands available for managing user accounts:
> 
> * https://docs.photoprism.app/getting-started/advanced/openid-connect/#existing-accounts
> * https://docs.photoprism.app/developer-guide/api/oidc/#existing-accounts
> 
> Does this look good to you?

It's simple, and it gets the relevant details across. I would say- this one is resolved.
