### ISSUE TITLE
File Type / Support H265 videos

### ISSUE THREAD

**Issue by PiotrEsse** [photoprism/photoprism#440]
Hi, 
Id like to report that all movies recorded in my phone Huawei P20 Pro" are not played correctly. 

Theres a black box in the center of screen - video are not played at all. Sound is played correctly. 

Theres is also entry frame correctly shown.

[VID_20200625_170256.zip](https://github.com/photoprism/photoprism/files/5020439/VID_20200625_170256.zip)

Files are recorded in H265, 1920P, 60 frmaes/sec.

![2020-08-04 08_26_39-Window](https://user-images.githubusercontent.com/42764623/89260411-849ce000-d62c-11ea-91f1-54f9596cd37d.png)

I am uploading short movie (zipped) and screenshot.

Its not very important for now but it would be great to have possibility to play those formats in the future (1080P/h265)

**Comment by calucido** [comment]
While I am able to play your video on my computer, I am unable to play it when I directly request it through PhotoPrism's API, or when I host it on a plain web server (both through Firefox 79.0 on OS X 10.13.6). It seems that this is an issue with browsers, not PhotoPrism. It also seems that H.265 support is lagging not for technical reasons but because of royalties due: https://stackoverflow.com/a/36390568.
Perhaps a workaround for PhotoPrism would be to convert H.265 videos to H.264 (or whatever codec is least problematic) when they are uploaded.

**Comment by lastzero** [comment]
@calucido is right, we need to convert videos with other codecs to H.264, which is supported by Internet Explorer, Safari and Chrome, but NOT Opera and Chromium (only supports VP8, VP9 & AV1).

Complete video support for all formats on all browsers is a lot of work, we might build that as a premium feature for sponsors and contributors.

**Comment by acarrera94** [comment]
Looks like H265 is supported in Safari. Is there any way to get videos to play on safari? On my instance I'm not even seeing a play button on the videos with H265 encoding on any browser.

**Comment by lastzero** [comment]
We only show the play button for AVC videos as that's the only codec supported by all major browsers except Chromium. There is no capability detection implemented yet.

**Comment by acarrera94** [comment]
I’d be happy to submit a PR adding that feature for safari. Almost all of
my videos are this encoding so I’d love to be able to play them with
PhotoPrism.

**Comment by lastzero** [comment]
Ideally you only have to change a few lines of JS and rebuild the frontend, see https://docs.photoprism.org/developer-guide/frontend/introduction/

If it's a small change, we might be able to include a PR for this in our stable release. If it turns out to be more complex, or has side-effects in other browser, we should wait.

**Comment by lastzero** [comment]
Implemented transcoding to Avc1/Mp4 for web browsers, see 846c635f222e485b11eebdb5d899e871e9d2265f

**Comment by PiotrEsse** [comment]
YaY!
  Dear Michael! Great news, thank you!
-- 
-- 
Pozdrawiam serdecznie,
*Piotr Esse
*
------------------------------------------------------------------------

|Mobile: +48 506392139 | E-mail: piotr.esse@spero.click 
<mailto:piotr.esse@spero.click> |

  * /Zgłoszenia prosimy przesyłać na adres naszego systemu:
    *zgloszenia@spero.click*/
  * /**Jeśli jesteś już naszym klientem - *zaloguj się
    <https://spero.click/pm/clients/login>* na Twój panel klienta aby
    dodawać i sprawdzać Twoje zgłoszenia oraz mieć dostęp do innych
    informacji odnośnie naszej wspólnej współpracy./
  * /Jeśli nie masz dostępu do panelu klienta - zgłoś brak dostępu. /
  * /**Baza wiedzy: zanim zadasz pytanie - zajrzyj do naszej *bazy
    wiedzy <https://spero.click/pm/knowledge-base>**
    */

/Ta wiadomość może zawierać informacje, które są uprzywilejowane, poufne 
i nie podlegają ujawnieniu na mocy obowiązującego prawa. Jeśli czytelnik 
tej wiadomości nie jest zamierzonym odbiorcą lub agentem odpowiedzialnym 
za dostarczenie jej do zamierzonego odbiorcy, zostajesz powiadomiony, że 
otrzymałeś tę wiadomość elektroniczną omyłkowo oraz, że wszelkie 
przeglądy, rozpowszechnianie, rozpowszechnianie lub kopiowanie tej 
wiadomości jest surowo zabronione. Jeśli otrzymałeś tę wiadomość 
elektroniczną przez pomyłkę, powiadom nas natychmiast e-mailem i usuń 
oryginalną wiadomość ze swojego systemu. Dziękujemy za zrozumienie.
This message may contain information that is privileged, confidential 
and exempt from disclosure under applicable law. If the reader of this 
message is not the intended recipient, or an agent responsible for 
delivering it to the intended recipient, you are hereby notified that 
you have received this electronic message in error and that any review, 
dissemination, distribution or copying of this message is strictly 
prohibited. If you have received this electronic message in error, 
please notify us immediately by email, and delete the original message 
from your system. Thank you. /


Michael Mayer wrote on 05.12.2020 04:26:
