### ISSUE TITLE
Selection stays active after sharing selected photo batch

### ISSUE THREAD

**Issue by RAYs3T** [photoprism/photoprism#441]
If you select one or multiple photos and share them, the selection stays active.
Is this wanted behavior or a bug?

For album creation the selection is removed after creating the Album.

**Comment by graciousgrey** [comment]
This is the expected behaviour. We keep the selection after the actions: edit, download and share because one might do other actions with the same selection afterwards (like add it to an album). You can delete the selection by clicking x. 
![Screenshot 2020-08-12 at 08 01 43](https://user-images.githubusercontent.com/15210372/89980462-344c0080-dc72-11ea-9003-b0f0a9c4f22d.png)

After private, archive and add to album the selection is deleted.

**Comment by RAYs3T** [comment]
@graciousgrey That's properly something for a new config option (after the intial release of course).
For me personally there is no use in keeping the selection after sharing.

I'm happy with implementing these changes and put in in a PR.

Also tought about adding a shortcut for deselection, because otherwise you have to click twice just to deselect everything (clear the clipboard). Something like "ESC" maybe.

**Comment by lastzero** [comment]
That's something we keep an eye on when optimizing UX in the future. Maybe it's better to remove the selection as you suggest.

The problem with listening to keyboard events is that they are global while they are typically used in a specific context. ESC for example closes dialogs already. So when you close the "Add to album" dialog with ESC, you would also lose the current selection. That may lead to weird behaviour. I've mastered this before, it's possible. But first - as you mentioned - we need to focus on a stable release.

**Comment by lastzero** [comment]
Guess the idea was that you can share items with more than one remote service like Nextcloud and Google Drive or Facebook. Obviously keeping the selection doesn't make sense when you can only share to one type of service (WebDAV) so far.

**Comment by lastzero** [comment]
@RAYs3T OK like this?

**Comment by RAYs3T** [comment]
Yep, did just test it, works perfectly ❤️
