### ISSUE TITLE
Checkout on windows is not possible due to file naming

### ISSUE THREAD

**Issue by RAYs3T** [photoprism/photoprism#442]
## Problem description
If you try to checkout the repository on a windows machine, the checkout fails because there are invalid (at least invalid for windows) characters in the file name. 
**This puts the working tree in a non-usable state. So you can't commit anything without making a mess.**

```shell
$ GIT_TRACE=1 git checkout develop
09:48:25.466107 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
09:48:25.467063 git.c:442               trace: built-in: git checkout develop
error: invalid path 'internal/photoprism/testdata/2018-04-12 19:24:49.gif'
error: invalid path 'internal/photoprism/testdata/2018-04-12 19:24:49.jpg'
error: invalid path 'internal/photoprism/testdata/2018-04-12 19:24:49.json'
error: invalid path 'internal/photoprism/testdata/2018-04-12 19:24:49.mov'
```

This is kinda annoying since you can't edit anything on a windows workstations this way.

## Possible solution
Since these files are used in the media test, we could keep the name in the repository clean and change it when the test runs (so the files with the correct names will be generated at test runtime).
This will at least make the checkout possible without issues on windows.

**Comment by lastzero** [comment]
Make sense. I wouldn't use those characters in a file name, but others do and that causes issues we added tests for. Without those files, we need to test this differently or remove the tests and pray it doesn't happen again somehow (not a viable option).

Changing the names dynamically after detecting the file system type and otherwise skipping the test is way too complex (not a viable option too).

**Comment by RAYs3T** [comment]
Agree, but what if we always generate these file names at test runtime ignoring what platform this is running at? (ignoring the fact that the test WILL FAIL on windows.

But i guess it is also not an option to leave it like it is (the repo should be useable on all systems without issues). When people (new to the project) want to change something simple they will hit this error and will properly give up on it.

The alternative would be to create a guide on how to setup the dev environment using the windows subsystem for Linux.

I would prefere the dynamic renaming tho.

**So let me know what you settle on and i will do a PR for it.**
1. Set filenames for test dynamically (accepting that this specific test is broken on windows platform, tho who wants to run test on windows anyways, these are for the pipeline...)
2. Create a developer guide using the Subsystem for Windows.

**Comment by RAYs3T** [comment]
@lastzero Checkout is now working fine. Thanks!

`` `
$ git clone git@github.com:photoprism/photoprism.git
Cloning into 'photoprism'...
remote: Enumerating objects: 166, done.
remote: Counting objects: 100% (166/166), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 29576 (delta 77), reused 95 (delta 42), pack-reused 29410
Receiving objects: 100% (29576/29576), 32.03 MiB | 5.06 MiB/s, done.
Resolving deltas: 100% (21153/21153), done.
```
