### ISSUE TITLE
heic photo taked by ios18 device convert fail

### ISSUE THREAD

**Issue by 1rnmortal** [photoprism/photoprism#4425]
---------------------------------------------------------------------------

 1. What is not working as documented?

heic photo taked by ios18 device convert fail

 2. How can we reproduce it?

take photo use ios18 device and index it in photoprism

 3. What behavior do you expect?
convert normally

4. What could be the cause of your problem?

apple change heic photo encoding method casue heif-convert cannot convert it.

 5. Can you provide us with example files for testing, error logs, or screenshots?
any phohto take by ios18 device camera 

 6. Which software versions do you use?

(a)  AMD64

(b)  MariaDB, MySQL

(c)  Linux(unraid)

(d) Chrome

Build [240711-2197af848]

7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a)  Intel Core i3-8100

(b) 32GB

(c) Storage Type: HDD

**Comment by graciousgrey** [comment]
Thank you for reporting! 

Can you send us a sample file?

https://www.photoprism.app/contact#file-samples

**Comment by 1rnmortal** [comment]
> Thank you for reporting!
> 
> Can you send us a sample file?
> 
> https://www.photoprism.app/contact#file-samples


already sent an example to you email

**Comment by graciousgrey** [comment]
Thank you, I can confirm that the conversion is failing. 

This should be fixed by using the latest version of libheif. 

- https://github.com/strukturag/libheif/issues/1190

However, we have to test this version first, as the previous version caused problems with image rotation.

**Comment by 1rnmortal** [comment]
> Thank you, I can confirm that the conversion is failing.
> 
> This should be fixed by using the latest version of libheif.
> 
> * [Unable to convert heic to jpg taken by iPhone 15 pro iOS18 strukturag/libheif#1190](https://github.com/strukturag/libheif/issues/1190)
> 
> However, we have to test this version first, as the previous version caused problems with image rotation.

ok，I will try fix it by replace the lib  in docker manually

**Comment by lastzero** [comment]
Please see the following issue, which explains how you can help us with testing so that we can be sure that upgrading `libheif` will not break HEIC images taken with older versions of iOS:
- https://github.com/photoprism/photoprism/issues/4439

**Comment by lastzero** [comment]
@1rnmortal Since our team is on vacation until August 19, it would be super amazing if someone from our community could take another look at it to find out what the exact problem is, e.g. by contacting Apple and/or the libheif maintainer to get more information. Feel free to use our [sample images](https://dl.photoprism.app/samples/Brands/Apple/) for this! 🖼️

- https://github.com/photoprism/photoprism/issues/4439#issuecomment-2265616780
