### ISSUE TITLE
Delete user does not really delete it, only disabled and cannot recreated therefor via OIDC login

### ISSUE THREAD

**Issue by sseide** [photoprism/photoprism#4436]
---------------------------------------------------------------------------

#### 1. What is not working as documented?

1. Create a new user via OIDC login  - on first login this account is created (having oidc-register=true).

2. The CLI command to delete a user is not really deleting it, it is just disabled. At least for OIDC users, not tested for local users.
But the command says it is deleted and a following `users ls` does not list it anymore.
Auth sessions are also not listed for this user with `auth ls`, therefor a user _must_ think the account is deleted.

As soon as this OIDC  user tries to login again via OIDC there is only a error message "Ungültige Zugangsdaten" and no more information _why_ they are invalid or what is going wrong. There is no way to find out why login is not possible. And container logging does not help here either (as for other cases - no useful logs at all).

Manually searching the entire database i found the table "auth_users" which - to my surprise at it is not documented at all - contains an entry for this OIDC user and it is not deleted as the output from the `photoprism users rm` command suggests.

After manually deleting the user entry from the `auth_users`, `auth_users_settings` and `auth_users_details` table allowed a new login of this user via OIDC - account could be recreated.

#### 2. How can we reproduce it?

1. Enable OIDC and allow register of new users trough it.
2. Log in the first time with a new OIDC user
3. delete user via CLI `photoprism users rm -f <username>`
4. Lig in again with the deleted user via OIDC
5. Error message about invalid login data is shown, no way for this user to log in again (except manual sql delete).

#### 3. What behavior do you expect?

1. Deleting user really deletes a user and does not just disable it (or at least say user is disabled)
2. Logging in again with OIDC with a deleted user account recreates this account and allows login as it is obviously not forbidden by the OIDC provider, therefor a valid user

#### 4. What could be the cause of your problem?

Not doing what the docs/UI says (deleting) but doing something undocumented (disabling).

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, PhotoPrism® Essentials Build 240711-2197af848
(b) Database Type & Version: MariaDB 10.11
(c) Operating System Types & Versions: Debian Linux with Docker 20.10.24+dfsg1
(d) Browser Types & Versions: Firefox, Chrome
(e) Ad Blockers, Browser Plugins, and/or Firewall Software? - irrelevant here

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel Core i7, AMD64
(b) Physical Memory & Swap Space in GB 64
(c) Storage Type: SSD
(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Docker setup behind NGinx reverse proxy.

**Comment by lastzero** [comment]
Please see the documentation we have created to explain this:
- https://docs.photoprism.app/getting-started/advanced/openid-connect/#deleting-accounts
- https://docs.photoprism.app/user-guide/users/cli/#creating-a-new-account

Remember to use `docker exec -ti ...` if you want to restore a previously deleted user account, as you will be asked for interactive confirmation.

**Comment by sseide** [comment]
oh thank. But here the CLI command output and logging should be changed in various ways:

1. `users rm` should not say "account deleted" but "account disabled" at first
2. how to list disabled accounts? `users ls` does not have a option to view disabled accounts (checked right now with `users ls --help`
3. How to finally delete already disabled accounts?
4. at least docker logs should print information _why_ an login was denied - a docker log message saying "account login denied, its disabled" would help a lot to admins trying to pinpoint such problems. And thanks to your link above i discovered some log in the "audit logins" output, but why not in generic logs? And than number 2 and 3 are still valid.

And what do you do if the account is already deleted? How do you "fix" it afterwards the "official" way? These users are never listed anymore... and `users mod` has a "disable" flag but no "enable".

**Comment by lastzero** [comment]
You can also disable login, which is different from (soft) deleting the account. Since this is important for auditing in certain use cases (maybe not for you as a home user), we currently do not provide a way to completely delete user accounts. However, if this is important to you and you are experienced, you can delete them from the database using standard SQL.

**Comment by lastzero** [comment]
If you have further questions, please check our documentation and if it doesn't answer them, use GitHub Discussions to ask the community for support, as this will otherwise prevent us from fixing actual bugs and developing new features that our users are waiting for. Thank you very much!
