### ISSUE TITLE
Canon CR3 Support

### ISSUE THREAD

**Issue by SchoolGuy** [photoprism/photoprism#445]
Hi guys,

I have a Canon EOS RP and wanted to try if this works with your project. Sadly it seems it doesn't.

I went to your demo instance and uploaded a file called `_MG_3360.CR3` which now has the name `20200626_071802_AC913341`. This is a mountain landscape in the German/Austrian Alps. Exiftool supports reading metadata from this format and thus I thought you guys can support it.

The spec can be found here: https://github.com/lclevy/canon_cr3  
The format will become more and more popular in the future as the R series will probably gain more and more track.

Thanks for your awesome work chaps!

**Comment by lastzero** [comment]
We use Darktable and Exiftool. If they support CR3, it should work. If support was added very recently, it's possible we need to upgrade the versions included in our Docker image.

Make sure to enable JSON sidecar files so that they are automatically created using Exiftool while indexing.

**Comment by SchoolGuy** [comment]
Darktable has no support for CR3. Please see https://github.com/darktable-org/darktable/issues/2170 for this. Rawtherapee has but without metadata.

Exiftool does support CR3 but it is added only "recently" which means that according to my research there are a few limitations but all in all the support is there.

**Comment by lastzero** [comment]
You can also run PhotoPrism on a Mac if OS X contains CR3 support. Does Rawtherapee have a CLI command like Darktable? We can add support for that as well.

**Comment by SchoolGuy** [comment]
I don't own a MAC but yeah it will just take a while until this is working.

And yes Rawtherapee appears to have a CLI: https://rawpedia.rawtherapee.com/Command-Line_Options

**Comment by lastzero** [comment]
We have a page in our developer guide comparing various raw to JPEG converters. Darktable was chosen because it had the best quality (assuming Photoshop is what users expect).

**Comment by SchoolGuy** [comment]
As long as I can have a photo library where I can save my RAWs and have a nice browser view it is fine for me.

**Comment by RAYs3T** [comment]
But if the CLI is somewhat similar I guess it should be possible to make it a config option.

**Comment by lastzero** [comment]
Right, now that it makes sense to add additional converters. Can someone figure out if there are formats Darktable supports but Rawtherapee not?

**Comment by lastzero** [comment]
Using to the new Ubuntu 20.04 base image might be the easiest option to upgrade CLI tools like `exiftool`.

**Comment by lastzero** [comment]
Just merged to master, you're welcome to test when the new Docker image is available (~1 hour if nothing fails).

**Comment by SchoolGuy** [comment]
@lastzero Photo preview now works, metadata not as far as I see.

**Comment by SchoolGuy** [comment]
Thanks a lot

**Comment by lastzero** [comment]
Metadata generally works, I can see it in the json sidecar files. Rawtherapee probably doesn't copy Exif data to JPEGs though, Darktable and Photoshop do. Either we can fix that or we need to implement a fallback in the Indexer.

**Comment by lastzero** [comment]
Exif metadata probably can be configured indirectly using a sidecar file or render profile, see https://rawpedia.rawtherapee.com/Exif_Tab

Maybe someone can help with this, I don't have time to experiment and have no experience with Rawtherapee.

**Comment by SchoolGuy** [comment]
Sadly in this regard I am only a user so I can't step in there...

**Comment by lastzero** [comment]
Done, going to look into some other issues and then start a new Docker build!

**Comment by SchoolGuy** [comment]
Okay something is strange: When I now Upload a CR3 it starts uploading the picture and then the Upload Dialog closes itself without a message and the picture is not visible in the Gallery. When uploading a JPG it works fine so it seems you introduced a bug with yesterdays commit.

**Comment by lastzero** [comment]
Do you use a proxy like nginx in front of PhotoPrism?

**Comment by SchoolGuy** [comment]
I use your demo instance

**Comment by SchoolGuy** [comment]
And when I will set it up on the weekend I will use Traeffik

**Comment by lastzero** [comment]
You're right, the raw.pp3 file I created seems missing in the image... going to fix this, or maybe we just use the default as I see no difference. Was hoping to preserve Exif data with this.

**Comment by lastzero** [comment]
Fixed, looks good on our demo:

![Screenshot 2020-08-13 at 12 00 53](https://user-images.githubusercontent.com/301686/90121769-b153a480-dd5c-11ea-97f0-b8e422dd4c89.png)

**Comment by SchoolGuy** [comment]
I would consider this closed. The JPG generated by the Camera itself looks on my Desktop nearly identical to the one generated in the browser. I will report back here if I have my own library set up on my own server.

**Comment by SchoolGuy** [comment]
Thanks a lot for this! To my knowledge you are the first library to support this btw... :heart:

**Comment by boecko** [comment]
Hi,

i've installed this fantastic project yesterday and indexed about 80k photis with it.
But i've run in this CR3 issue, because i'm using a Canon EOS R6 since Dec 2021.

```bash
$ docker-compose exec photoprism bash
root@220730-bookworm:/photoprism$ cd originals/2021/12/11-hochzeitraw
root@220730-bookworm:/photoprism/originals/2021/12/11-hochzeitraw$ rawtherapee-cli -o AU4A8016a.jpg -c AU4A8016.CR3
root@220730-bookworm:/photoprism/originals/2021/12/11-hochzeitraw$ darktable-cli AU4A8016.CR3 AU4A8016b.jpg
```
AU4A8016a.jpg  is just plain white. rawtherapee 5.8 seems to have an issue with CR3 files - see https://github.com/Beep6581/RawTherapee/issues/5901.
AU4A8016b.jpg is fine.

https://github.com/photoprism/photoprism/commit/fdf3d2627746c7556e13f5f24bbfd04c520fbf8e seems to be wrong.

**Comment by lastzero** [comment]
You can change the config if Darktable works for you. Note it may behave differently in the Ubuntu (jammy) Docker image. Can you test this for us?

**Comment by boecko** [comment]
I've changed it in options.yml
```
DarktableBlacklist: dng
```
and it works.
Same behaviour in  **photoprism/photoprism:jammy** 

rawtherapee -> ostfriesische nationalflagge -> weißer Adler auf weißen Grund
darktable -> works

**Comment by lastzero** [comment]
OK, so it's safe to remove CR3 from the Darktable blacklist?

**Comment by boecko** [comment]
i guess so. CR3 should be blacklisted for rawtherapee when version 5.8 is used.

**Comment by lastzero** [comment]
You're welcome to send a pull request for the internal/config package, otherwise we'll do it after our vacation.
