### ISSUE TITLE
Location information for the island of Aruba incorrect

### ISSUE THREAD

**Issue by moleculezz** [photoprism/photoprism#4462]
#### 1. What is not working as documented?

In the PhotoPrism web app, the pictures have incorrect location information for Aruba.
Aruba is an independent island, but it lists the country as "The Netherlands". The country should be "Aruba"

I see in some cases, the name of a district is used, and other times city is used in the data. Not sure how this is chosen, but here is the correct list of cities and their districts:
https://en.wikipedia.org/wiki/List_of_cities_in_Aruba

#### 2. How can we reproduce it?

1. In the search list, each thumbnail has the incorrect info.
2. When you open an image and view it's metadata, you can see the same information that is incorrect.

#### 3. What behavior do you expect?

The country should be listed as "Aruba"

#### 4. What could be the cause of your problem?

Incorrect location data I would guess.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Here is a screenshot of some images with incorrect location data.
https://imgur.com/a/sfNX7ZS

I also sent samples via email.

#### 6. Which software versions do you use?

(a) PhotoPrism Plus Build 240711-2197af848, AMD64

(b) TrueNAS App.. SQLite?

(c) Linux (TrueNAS Scale)

(d) Chrome v127

(e) None

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Intel(R) Core(TM) i3-9300 CPU @ 3.70GHz

(b) 32GB (ECC)

(c) HDD (RAIDZ2)

(d) No

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

HAProxy 2.8.2

**Comment by graciousgrey** [comment]
Thank you for reporting!

It's a complicated edge case, as Aruba seems to belong to the Kingdom of the Netherlands, although it is mostly independent:
- https://www.google.com/search?q=aruba+belongs+to+what+country

We don't want to discriminate against anyone and rely on the data that OpenStreetMap provides us with. You can try filing a complaint there if you believe that this country code should not be used for the island. If it has already been changed, these changes will be shown when we update our data.

**Comment by moleculezz** [comment]
I've looked at OSM forums and I found a post regarding this exact issue. I have posted there.
https://community.openstreetmap.org/t/mis-labeled-country/85144

**Comment by lastzero** [comment]
Thanks! I'll move ahead and close this issue as there's probably nothing we can do to "fix" this on our own. OSM changes are pulled automatically from time to time.
