### ISSUE TITLE
Incorrect Thumbnails for some videos

### ISSUE THREAD

**Issue by thisIsNotTheFoxUrLookingFor** [photoprism/photoprism#4471]
I create a brand new instance, I delete the entire storage (and database) folder to ensure no artefacts remain.

I copy the pics and vids into the import folder, I then click import in the UI and it imports the pictures and videos into the originals folder.

It builds thumbnails for them, but some videos are getting thumbnails from other pictures that have absolutely nothing to do with the video.

I have rebuilt PhotoPrism several times and the exact same videos cause the same error every time.

Example:

Here is the thumbnail generated:
![Screenshot 2024-08-21 135706](https://github.com/user-attachments/assets/feffd2f5-772e-471b-9e81-3fb5c042c7b1)

Here is the actual video, it is of a fire bombing helicopter and it does not contain a map of Australia.
![image](https://github.com/user-attachments/assets/0a278b2f-13a3-474f-a498-ea2644b7dd33)

How does this occur?

**Comment by lastzero** [comment]
Most likely images with the same name as the video files, so they get stacked: https://docs.photoprism.app/user-guide/organize/stacks/#for-what-reasons-can-files-be-stacked

If you want to file an official bug report, please use the template provided and make sure that the feature is not working as documented. Thank you!
