### ISSUE TITLE
Control process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by tomasenskede** [photoprism/photoprism#4481]
During import phtotprism stopped... this is what I found in the log;

1st time today
Aug 25 10:41:55 photoprism systemd[1]: photoprism.service: Control process exited, code=exited, status=1/FAILURE
Aug 25 10:41:55 photoprism systemd[1]: photoprism.service: Failed with result 'oom-kill'.
Aug 25 10:41:55 photoprism systemd[1]: photoprism.service: Consumed 1h 24min 46.041s CPU time.

2nd time today
Aug 25 22:56:27 photoprism systemd[1]: photoprism.service: A process of this unit has been killed by the OOM killer.
Aug 25 22:56:29 photoprism systemd[1]: photoprism.service: Main process exited, code=killed, status=9/KILL
Aug 25 22:56:33 photoprism photoprism[199876]: time="2024-08-25T22:56:33+02:00" level=warning msg="config: failed loading values from /opt/photoprism/storage/co>
Aug 25 22:56:33 photoprism photoprism[199876]: time="2024-08-25T22:56:33+02:00" level=info msg="Become a member today, support our mission and enjoy our member >
Aug 25 22:56:33 photoprism photoprism[199876]: time="2024-08-25T22:56:33+02:00" level=info msg="Visit https://www.photoprism.app/membership to learn more."
Aug 25 22:56:33 photoprism photoprism[199876]: time="2024-08-25T22:56:33+02:00" level=info msg="looking for pid in /opt/photoprism/storage/photoprism.pid"
Aug 25 22:56:33 photoprism systemd[1]: photoprism.service: Control process exited, code=exited, status=1/FAILURE
Aug 25 22:56:34 photoprism systemd[1]: photoprism.service: Failed with result 'oom-kill'.
Aug 25 22:56:34 photoprism systemd[1]: photoprism.service: Consumed 1d 19h 7min 25.928s CPU time.

had to restart photoprism both times ...

**Comment by srett** [comment]
Probably not a bug, you're out of memory. Try adding more RAM or decrease the worker count.

**Comment by tomasenskede** [comment]
I have 8 GB RAM... should add more? Don't looks like the host is out of memory... but I can add more if that's the reason.

**Comment by lastzero** [comment]
Could also be a memory or CPU usage limit e.g. set via systemd. Check your logs, our FAQS, and the troubleshooting checklists we provide.

**Comment by tomasenskede** [comment]
Doesnt looks like its runs our of RAM...
![image](https://github.com/user-attachments/assets/de49bcb3-5a3a-4131-b49f-639f6c4e0aea)

But the CPU is working hard when importing 60k images
![image](https://github.com/user-attachments/assets/3da3dd59-e181-4795-b49d-ca6bae06419f)

Lots of network traffic as aspected
![image](https://github.com/user-attachments/assets/025a40ae-5b48-447b-81df-65e08279cac9)

and disk I/O
![image](https://github.com/user-attachments/assets/c2450c65-99c4-41bf-a319-eb554493235e)

**Comment by lastzero** [comment]
`oom-kill` likely means "out of memory" e.g. because you set a memory limit or there isn't enough swap configured.
