### ISSUE TITLE
Shared albums links can't be removed

### ISSUE THREAD

**Issue by gpulido** [photoprism/photoprism#450]
1) Share an album -> a share link is created. 
2) Try to remove the link or modify  the expiration info
3) An error is shown: "An error occurred - are you offline?" and the link can't be created / modified

**Comment by calucido** [comment]
I can't reproduce this on PhotoPrism version 200807-3ffe74a-Linux-x86_64. What version are you using? Also, do you get any errors in the PhotoPrism server log or in your browser console?

**Comment by gpulido** [comment]
I have just test with version 200807-3ffe74a-Linux-x86_64 and is not working for me.
I'm using mariadb as db, and the stack is running on a docker swarm.

On the console, when I try to remove a link this is what comes out:
```
app.js?6098f462:15 DELETE https://photoprism.gpulido.com/api/v1/albums/aqe4fx52gk3a7i85/links/undefined 500

(anonymous) @ app.js?6098f462:15
e.exports @ app.js?6098f462:15
e.exports @ app.js?6098f462:1736
Promise.then (async)
l.request @ app.js?6098f462:1736
r.forEach.l.<computed> @ app.js?6098f462:1736
(anonymous) @ app.js?6098f462:15
value @ app.js?6098f462:9
remove @ app.js?6098f462:1736
click @ app.js?6098f462:1736
Ve @ app.js?6098f462:9
n @ app.js?6098f462:9
Ve @ app.js?6098f462:9
e.$emit @ app.js?6098f462:9
click @ app.js?6098f462:452
Ve @ app.js?6098f462:9
n @ app.js?6098f462:9
a._wrapper @ app.js?6098f462:9
app.js?6098f462:15 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (app.js?6098f462:15)
    at e.exports (app.js?6098f462:1736)
    at XMLHttpRequest.p.onreadystatechange (app.js?6098f462:15)
```

**Comment by lastzero** [comment]
Works perfectly on our demo. The `link_expires` column seems to be a time value in your database whereas the model uses an `int`. If you don't want to use a fresh database, you can simply delete the `links` table and restart PhotoPrism. It will then be recreated using the right columns. However, it's possible that other tables are outdated as well. We had to change a number of columns & tables to implement sharing.

**Comment by gpulido** [comment]
Just a quick comment to confirm that after removing the db and recreating it this works perfectly.
Sorry for the disturbance, just didn't notice the change of db structure.
