### ISSUE TITLE
OIDC login fails with HTTP status 500 and message "Could not connect, please try again"

### ISSUE THREAD

**Issue by seiferma** [photoprism/photoprism#4528]
#### 1. What is not working as documented?
I configured the OIDC login via authentic as described in the [documentation](https://docs.photoprism.app/developer-guide/api/oidc/). After pressing the login button on the UI, only a short popup is displayed saying "Could not connect, please try again". The corresponding HTTP status code is 500. No further details about the reason are provided.

#### 2. How can we reproduce it?

1. Configure OIDC using my issuer URI (I would like to keep the URL out of this issue but will provide it on request)
2. Press the OIDC login button
3. See the error message popup

If the parsing of the discovery endpoint might already be a problem:
1. Put the [discovery JSON](https://gist.github.com/seiferma/c4bcb4d134930cf1009f90e93a799486) on a webserver into `.well-known/openid-configuration`
2. Configure OIDC using the webserser URI
3. Press the OIDC login button
4. See the error message popup

OIDC configuration of photoprism:
```
OPENID CONNECT (OIDC)

|---------------|----------------------------------------------------------------------------------------------------------------------------------|
|     Name      |                                                              Value                                                               |
|---------------|----------------------------------------------------------------------------------------------------------------------------------|
| oidc-uri      | https://auth.example.org/application/o/photoprism-public                                                                       |
| oidc-client   | XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                                         |
| oidc-secret   | ******************************************************************************************************************************** |
| oidc-scopes   | openid email profile address                                                                                                     |
| oidc-provider | Authentik                                                                                                                        |
| oidc-icon     | /static/img/oidc.svg                                                                                                             |
| oidc-redirect | false                                                                                                                            |
| oidc-register | true                                                                                                                             |
| oidc-username | email                                                                                                                            |
| oidc-role     | guest                                                                                                                            |
| oidc-webdav   | false                                                                                                                            |
| disable-oidc  | false                                                                                                                            |
|---------------|----------------------------------------------------------------------------------------------------------------------------------|
```

The JSON of the discovery endpoint is available as Gist: https://gist.github.com/seiferma/c4bcb4d134930cf1009f90e93a799486

#### 3. What behavior do you expect?
* The browser is redirected to the issuer based on the discovered endpoint
* An error message in the log provides details on what went wrong

#### 4. What could be the cause of your problem?
Most probably, the configuration of my issuer violates some not documented assumptions. However, I cannot track down the issue much more because no detailed information about the error is logged.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
I enabled trace logging in photoprism and authentic. Photoprism only logged the following information after pressing the login button:
```
photoprism-1  | time="2024-09-15T15:41:18Z" level=debug msg="server: GET /api/v1/ws (200) [15.979916724s]"
photoprism-1  | time="2024-09-15T15:41:19Z" level=trace msg="config: cache hit for wallpaper-uri"
photoprism-1  | time="2024-09-15T15:41:19Z" level=debug msg="server: GET /api/v1/oidc/login (500) [915.480615ms]"
photoprism-1  | time="2024-09-15T15:41:19Z" level=trace msg="config: cache hit for wallpaper-uri"
photoprism-1  | time="2024-09-15T15:41:19Z" level=debug msg="server: GET /library/login (200) [3.355476ms]"
photoprism-1  | time="2024-09-15T15:41:19Z" level=trace msg="config: cache hit for wallpaper-uri"
photoprism-1  | time="2024-09-15T15:41:19Z" level=debug msg="server: GET /api/v1/config (200) [1.626297ms]"
```

Authentik (hosted at `auth.example.org`) logged that photoprism accessed the discovery endpoint successfully (status code 200). After that, no further requests coming from photoprism are logged.
```
server-1      | {"auth_via": "unauthenticated", "domain_url": "auth.example.org", "event": "/application/o/photoprism-public/.well-known/openid-configuration", "host": "auth.example.org", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 167, "remote": "", "request_id": "e8b25c1fba134f248401b21f92f304db", "runtime": 702, "schema_name": "public", "scheme": "https", "status": 200, "timestamp": "2024-09-15T15:41:19.183981", "user": "", "user_agent": "Go-http-client/2.0"}
```

The UI only shows a red popup saying "Could not connect, please try again".

I executed the download of the json file via the discovery endpoint in the photoprism container using curl. The configuration looked good, so I assume that there is no connectivity issue in general.

#### 6. Which software versions do you use?

(a) PhotoPrism CE Build 240711-2197af848 ARM64
(b) MariaDB 10.11.9-MariaDB-ubu2204 source revision 0e8fb977b00983d98c4c35e39bc1f36463095938
(c) Container (photoprism/photoprism:latest) on Linux (Debian 12.6 arm64) with Docker (version 27.2.0, build 3ab4256)
(d) Firefox 130.0 (64-bit) on Windows
(e) No active plugins/addons in browser

#### 7. On what kind of device is PhotoPrism installed?

There is no performance issue, so I omit this information.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

* Reverse Proxy in front of Photoprism (Caddy v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=)
* Reverse Proxy in front of Authentik (Caddy v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=)
* Photoprism and Authentik are located on different hosts (both accessible via internet)

**Comment by lastzero** [comment]
Does your instance use HTTPS, i.e. does the URL of the site start with `https://`? Does the `issuer` field returned by `.well-known/openid-configuration` match the `oidc-uri`? From what I see in your gist, one of the URIs ends with a `/` and the other does not, which alone would be enough to get error 500. Unfortunately, the security logs for our Community Edition are not ready yet and we do not output certain security related information in the regular logs.

**Comment by seiferma** [comment]
You are right: After adding the slash in the `oidc-uri`, the authentication works as expected. Thanks for your fast response and all the work you are putting into photoprism.

I was not aware of this validation and it might be worth mentioning it in the OIDC documentation of photoprism. In fact, I though I had to enter the URI without trailing slash because in the [documentation](https://docs.photoprism.app/getting-started/advanced/openid-connect/#identity-providers) the standardized service discovery endpoint is given with leading slash, which would mean that concatenating it with the `oidc-uri` would lead to a double slash.

I get the point about separating security and regular logs. An option to temporarily put the security logs into a dedicated file or something similar would have been sufficient here but I am sure you already got a better solution in the backlog.

**Comment by lastzero** [comment]
To ensure a high level of security, the configured issuer (URI) and the issuer value returned by the Identity Provider must match exactly (this should apply to all applications that support OIDC, unless they have flaws). From what I know, the issuer may or may not have a slash at the end - we can therefore not give specific advice on this as it depends on (the configuration of) your Identity Provider.

If you use a public provider, it is best to check their documentation and otherwise check the information returned by the discovery endpoint to see if the `issuer` value matches the URI in your OIDC configuration.
