### ISSUE TITLE
Show more columns in tile view on large screens

### ISSUE THREAD

**Issue by olegelantsev** [photoprism/photoprism#453]
Hi,

I noticed that tiles are blurred on my FullHD screen. It seems that fronted scales the tile size depending on the page width and if page wider than ~1500px, tile size becomes bigger than default thumbnail size - 224px.

![photoprism-screenshot](https://user-images.githubusercontent.com/7139119/89729977-cd90d200-da3a-11ea-813e-24289d9ee781.png)

I see that thumbnails are also generated with higher resolution, so front end could use those.

**Comment by lastzero** [comment]
That's not a retina / high dpi screen, right?

As a quick solution, you can use the Cards view which uses 500px tiles instead of 224px. The Mosaic view was built for smaller mobile screens. Making the thumb size dependent on the visible window size might not be ideal given the performance overhead when resizing (you have to reload all thumbs when over 1000 search results might be shown already).

**Comment by olegelantsev** [comment]
Screen is 1920x1080. 

For now I set the default tile size in frontend to 500px in my branch. 

Is it possible to calculate max tile size in Mosaic view? Then switch between tile size wouldn't be needed.

**Comment by lastzero** [comment]
Size is dynamic based on a responsive grid. Changes when you resize the window. We should show more tiles if the size is larger than 224px, not make them larger and/or replace already loaded images.

**Comment by olegelantsev** [comment]
Why is the issue closed? The problem doesn't seem to be solved. I could help to fix it.

**Comment by lastzero** [comment]
You are right, Theresa closed it because it was marked as question. Should actually create a new issue with a specific solution like showing more tiles (or convert this into a task).

Changing the resolution dynamically is not something we want to implement at this point for the reasons mentioned.

**Comment by lastzero** [comment]
FYI: Vuetify has a 12 column grid system. How many columns do you see right now on your screen?

See https://v15.vuetifyjs.com/en/framework/grid

**Comment by olegelantsev** [comment]
I have 6 columns. Thanks for the link.

**Comment by lastzero** [comment]
In that case you probably only have to add the class `xl1` to the tile markup, see `.vue` component in `/frontend/src`

**Comment by olegelantsev** [comment]
I struggle to serve the frontend after it is built. Is it possible to do that without docker? I am new to Vue (I saw vue-cli-service tool, but apparently it doesn't quite work with the frontend setup)

**Comment by lastzero** [comment]
I can do it tomorrow. Have a great evening!
