### ISSUE TITLE
Pikapods: Cannot read assets.json Error Occurring Frequently

### ISSUE THREAD

**Issue by sayem314** [photoprism/photoprism#4548]
We are encountering repeated errors with PhotoPrism related to reading the `assets.json` file. This issue appears frequently in the logs and affects the functionality of the pod. Below is a sample of the error message:

```
level=error msg="frontend: cannot read assets.json"
```

**Steps to Reproduce**:  
1. Start the PhotoPrism pod.
2. Monitor the logs for errors related to the frontend.
3. Notice the repeated occurrence of the `cannot read assets.json` error.

**Expected Behavior**:  
The PhotoPrism frontend should be able to read the `assets.json` file without any issues.

**Actual Behavior**:  
The PhotoPrism frontend fails to read the `assets.json` file, triggering repeated error messages in the logs.

**Logs**:  
```
time="2024-09-23T03:38:22Z" level=error msg="frontend: cannot read assets.json"
time="2024-09-23T05:08:22Z" level=error msg="frontend: cannot read assets.json"
time="2024-09-23T12:39:52Z" level=error msg="frontend: cannot read assets.json"
...
```

**Environment**:  
- PhotoPrism version: 240915
- Deployment method: Docker
- Server: Pikapods

**Temporary Solution**:  
We have restarted the pod, which temporarily resolves the issue, but the error is likely to recur.

Thank you for looking into this!

**Comment by lastzero** [comment]
Do you observe the same with our public demo at demo.photoprism.app? If this is specific to your Pikapods instance, please contact their support team so they can help you and work with us if needed. Thank you very much!

**Comment by sayem314** [comment]
@lastzero To clarify, I am a sysadmin at PikaPods, but I don't handle the deployment specifics, only @m3nu has that information. I haven't tested this on your public demo yet, but this issue was reported twice by our customers using PikaPods, which is why I created this issue here. 

If there's anything specific you would need from our end or further insights you might require, please let me know, and I'll coordinate as needed.

**Comment by lastzero** [comment]
The error you mentioned is logged here if the `assets.json` file could not be found:
https://github.com/photoprism/photoprism/blob/0b391d26ecf3989becef2b8280a15b0014e709f2/internal/config/client_assets.go#L74-L84

It should be present in the Docker images we distribute, as I just confirmed with our public demo:
- https://demo.photoprism.app/static/build/assets.json

Can you please check if the affected instances return it under the path `/static/build/assets.json` and if you can find the file inside the Docker image that you have deployed? The absolute path should be `/opt/photoprism/assets/static/build/assets.json`.

Edit: Additional error details should be logged when you **enable debug mode** e.g. with `PHOTOPRISM_DEBUG: "true"`.

**Comment by sayem314** [comment]
Everything's working fine now after resetting the Docker image. The assets.json file is loading correctly. This issue popped up a few weeks ago and then again today, which is why I created this ticket. It's a bit tricky since it's not consistent, but we'll keep an eye out. If it happens again, we'll switch on debug mode to get more info. Thanks for your help on this!

**Comment by lastzero** [comment]
Did you check if the user modified the default configuration? Something like this could happen with a custom assets path or wrongly mounted volumes.

**Comment by sayem314** [comment]
I can ensure user setting **was default** and **not modified**. Now I cannot pull older logs since pod was reset already but here is a screenshot from earlier, if that helps.

<img width="1155" alt="Screenshot 2024-09-24 at 12 02 08 AM" src="https://github.com/user-attachments/assets/87d15a1e-e98d-492e-b65a-b5c242cb4d8b">

**Comment by sayem314** [comment]
Issue identified as a problem with the storage adapter reading certain asset files. Resolved by resetting the Docker image, monitoring will continue. Closing for now. Thank you!
