### ISSUE TITLE
Cleanup in UI and PURGE without effect

### ISSUE THREAD

**Issue by anthraxn8b** [photoprism/photoprism#4555]
#### 1. What is not working as documented?

Using the rescan with cleanup option in the UI does not remove the missing pictures and also not the missing directories.
Same with the CLI command "purge".

The UI (even after restart, reload, private window,...) still shows the full count of all the images that had been present and show a symbol (kind of image defect symbol) for each entry.

#### 2. How can we reproduce it?

1. add r/w mounts into the docker image originals directory
2. let it be indexed
3. stop the container
4. remove the mount
5. start the container
6. do a full rescan with cleanup and/or a CLI purge
7. entries are still there

#### 3. What behavior do you expect?

Entries are gone.

#### 4. What could be the cause of your problem?

It seems as if the database entries are not cleaned up.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
![grafik](https://github.com/user-attachments/assets/6c4d3f2f-6edd-436f-938d-2cdbdc627c2e)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: ARM64

(b) Database Type & Version: MariaDB 11

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Firefox

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? ------

Build [240915-e1280b2fb](https://docs.photoprism.app/release-notes/)

#### 7. On what kind of device is PhotoPrism installed?

RASPI 4A

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

rProxy. Irrelevant.

**Comment by graciousgrey** [comment]
Do you see something like "originals empty" in the logs?

Then this is due to a security mechanism. We implemented it so that indexing does not remove all files from the index in case for example the originals folder cannot be accessed due to network problems.

--> https://github.com/photoprism/photoprism/issues/2299

See also: https://github.com/photoprism/photoprism/discussions/3938

**Comment by graciousgrey** [comment]
I will go ahead and close this as we have not received any further feedback.
