### ISSUE TITLE
More then one Originals Folder

### ISSUE THREAD

**Issue by corgan2222** [photoprism/photoprism#456]
Hello

im a photographer and looking for an alternative to the photostation on synology. I have several different original Folders on different Servers. (2mio Images, 30tb)

In the docker image on Unraid there is only one input box for a original Folder.
Is there a possibility to add more then one?

**Comment by RAYs3T** [comment]
@corgan2222 There is no direct way of doing this right now (AFAIK), but you could create symbolic links...
So for example create a folder (which is then used as originals folder in PP). Inside that folder you create symbolic links to the locations mounted in unraid (if these are on different servers, mount them via NFS / SMB).

I would not do this directly in unraid but rather create a VM inside unraid (debian/ubuntu) and do all these changes in there.

https://wiki.debian.org/SymLink

**Comment by corgan2222** [comment]
I was thinking about that solution, but want to make shure, that there is no other way. Thanks

**Comment by lastzero** [comment]
You can to use hard or symbolic links for this or mount the directories to the originals path via Docker / docker-compose.yml
