### ISSUE TITLE
FFMPEG transcode by QSV ，the video autorotated

### ISSUE THREAD

**Issue by HuoDaxia** [photoprism/photoprism#4566]
1. What is not working as documented?

The same problem as this issue.https://github.com/photoprism/photoprism/issues/4403

I configured transcoding by QSV，it‘s so fast but the video played rotered 90 degrees.

2. How can we reproduce it?

Config  transcode by QSV as https://docs.photoprism.app/getting-started/advanced/transcoding/ ,and enable FFMPEG transcode.

Play a video form smartphone by portrait mode.

3. What behavior do you expect?

I think we need an option can chose if use -noautorotate option when FFMPEG running.

 4. What could be the cause of your problem?

First.When smartphone filming vedio by portrait mode，the video will tag totated.

Second.When FFMPEG working ，autorotate is default option，if we don‘t need it should add -noautorotate opt.
![WechatIMG51](https://github.com/user-attachments/assets/ce085e16-a189-477d-8aed-7a3329c73ad8)

Third.Transcode by FFMPEG didn‘t have -noautorotate opt, and we can't change it.
![WechatIMG52](https://github.com/user-attachments/assets/f2e414d8-404a-41ff-ba81-e3e0d01a979b)

5. Can you provide us with example files for testing, error logs, or screenshots?

https://github.com/user-attachments/assets/2dd470d2-cc33-4d35-892f-12bfa52fd2bb

 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, Build [240915-e1280b2fb]

(b) Database Type & Version: MariaDB, 11.5.2

(c) Operating System Types & Versions: Linux

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,... ALL

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Na

 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Synology NAS/Intel® Celeron® Processor 3867U

(b) Physical Memory & Swap Space in 8GB

(c) Storage Type: SSD, RAID

**Comment by lastzero** [comment]
Since we already have two issues regarding the same problem, I am closing this one as duplicate:
- https://github.com/photoprism/photoprism/issues/4403
- https://github.com/photoprism/photoprism/issues/4503

I have also already tried the noautorotate flag:

- https://github.com/photoprism/photoprism/issues/4503#issuecomment-2334427756

**You are welcome to repeat the tests and let us know if you were successful!**

**Comment by HuoDaxia** [comment]
> Since we already have two issues regarding the same problem, I am closing this one as duplicate:
> 
> * [Live Photos: Previews rotated 90 degrees after enabling Intel QSV on QNAP 453D #4403](https://github.com/photoprism/photoprism/issues/4403)
> * [Intel QSV: Portrait Live Photos transcoded in avc codec are in landscape #4503](https://github.com/photoprism/photoprism/issues/4503)
> 
> I have also already tried the noautorotate flag:
> 
> * [Intel QSV: Portrait Live Photos transcoded in avc codec are in landscape #4503 (comment)](https://github.com/photoprism/photoprism/issues/4503#issuecomment-2334427756)
> 
> **You are welcome to repeat the tests and let us know if you were successful!**

I‘ve tried encoding by software，it's optput the right result as default video

But I still not understood how to add -noautorotate opt when I'm transcoding by QSV

Software encoding use too much system resources ，It’s an important function for low power host

**Comment by lastzero** [comment]
To change the command parameters for QSV transcoding, you will have to edit them and build from source. This is how I tested the noautorotate flag, just to find that it didn't resolve the issue. However, you can also test it by manually running the ffmpeg command in a terminal.
