### ISSUE TITLE
AI: Abstraction

### ISSUE THREAD

**Issue by mhasanunal** [photoprism/photoprism#4576]
It may be a good idea to make AI handling via abstract way?
This way, we can call a microservice or current implementation?

There should be a DI, an interface where implements:
input is a image in binary, 
output is embeddings and/or labels/rectange/point.

and even we can change the strategy on-the-fly?

**Comment by graciousgrey** [comment]
We've already started working on a micro-service that will allow us to use advanced computer vision models through a REST API (it also includes support for additional AI/ML hardware, although I'm not 100% sure if Coral TPUs are supported):

https://github.com/photoprism/photoprism-vision
