### ISSUE TITLE
We need Chinese support

### ISSUE THREAD

**Issue by leebro7** [photoprism/photoprism#4594]
PLEASE ONLY PROCEED IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR A PROBLEM WITH OTHER SOFTWARE YOU ARE USING. PLEASE ALSO CHECK OUR PUBLIC ROADMAP AND TRY TO FIND EXISTING FEATURE REQUESTS FIRST:

- <https://link.photoprism.app/roadmap>
- <https://github.com/photoprism/photoprism/issues>
 
VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

===============================================================================

we need simple Chinese support alone with traditional Chinese(hk,sg,tw)

**Comment by lastzero** [comment]
When you go to Settings > General, you can choose Traditional Chinese and Simplified Chinese as the UI language e.g.:
- https://demo.photoprism.app/library/settings

If you are not satisfied with the translations, you can help us improve them as described here in our Developer Guide:
- https://docs.photoprism.app/developer-guide/translations-weblate/
