### ISSUE TITLE
Infrastructure / Database environment variable is incompatible with Kubernetes Secrets

### ISSUE THREAD

**Issue by Expro** [photoprism/photoprism#460]
Currently, if user wishes to use external database, user needs to specify connection details as environment variable PHOTOPRISM_DATABASE_DSN, in form "user:password@tcp(address:port)/database?parseTime=true)".

That form is incompatible with Kubernetes Secrets, where Secret (password in this case) can be either provided as file / volume or value for whole environment variable (but not for part), for example:

- name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretName
              key: secretItemKey

Please consider splitting single environment variable (PHOTOPRISM_DATABASE_DSN), into several environment variables, so that secrets (passwords) can be provided in safe manner. Example - Nextcloud splits database connection details into following variables:
- MYSQL_HOST
- MYSQL_DATABASE
- MYSQL_USER
- MYSQL_PASSWORD

**Comment by lastzero** [comment]
I assume you had a look at https://docs.photoprism.org/getting-started/kubernetes/?

From what I understand, you want to provide `MYSQL_PASSWORD` as dynamic env variable as you can't provide a dynamic DSN using Kubernetes (or only as static plain text)?

Our Go driver expects a DSN. The exact format depends on the database, for SQLite it's a just file name (no password needed). So we can't merge host, database, user and password into a universal DSN string for all drivers. At minimum, we need to implement separate converter functions for each supported database.

Nextcloud is based on PHP which also uses DSNs for some db drivers, but without username and password: https://www.php.net/manual/en/ref.pdo-mysql.connection.php

**Comment by Expro** [comment]
> I assume you had a look at https://docs.photoprism.org/getting-started/kubernetes/?

Yes I did.

> From what I understand, you want to provide MYSQL_PASSWORD as dynamic env variable as you can't provide a dynamic DSN using Kubernetes (or only as static plain text)?

Yes, but it would be also nice to separate username, password, database name and address into separate environment variables. In Kubernetes, this values often comes from different places (database name and database address from ConfigMap, username and password from Secret, application structure from Deployment / StatefulSet), and it is impossible to combine them into single variable (DSN).

> Our Go driver expects a DSN. The exact format depends on the database, for SQLite it's just a file name (no password needed). So we can't merge host, database, user and password into a universal DSN string for all drivers. At minimum, we need to implement separate converter functions for each supported database.

Taking Nextcloud as an example, this seems to be true - they have separate variables for different databases.

> Nextcloud is based on PHP which also uses DSNs for some db drivers, but without username and password: https://www.php.net/manual/en/ref.pdo-mysql.connection.php

Not sure what driver they use, but it does support username and password, at least for mysql / mariadb, had even "pleasure" to check it by providing erroneous values and getting access denied to database.

**Comment by tehniemer** [comment]
I'm having a similar issue with the Docker container. I'm getting the following error which I think is related to connecting to an external database. 
```
time="2020-08-15T02:10:17Z" level=fatal msg="Error 1045: Access denied for user 'photoprism_user'@'photoprism.proxy' (using password: YES)"
```
Most other Docker containers use the format @Expro listed in the first post and it seems to work well.

**Comment by bpgerber** [comment]
I think the above user isn't aiming to dynamically change databases but using an already established secure mariaDB service.

Using [Docker's secrets](https://docs.docker.com/engine/swarm/secrets/) functions are [more secure than a single environment variable](https://stackoverflow.com/questions/44615837/why-is-docker-secrets-more-secure-than-environment-variables). If you are trying to keep your database  passwords more secure.

Multiple environment variables as @Expro said or even nested environment variables replacing that one would be a decent config. You could do a string builder operation if MYSQL_PASSWORD or the MYSQL_PASSWORD_FILE for using secrets (or any of the environment variables exist in the compose/docker build).

Pardon the quick docker variable-ness pseudocode:
$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_DATABASE:3306)......

and having a _FILE instance for those for the use of secrets would create a layer of database security.

**Comment by lastzero** [comment]
Can any Kubernetes user confirm this works?
