### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by Crell** [photoprism/photoprism#4609]
#### 1. What is not working as documented?

The license on this application is unclear.  The GitHub repository has an AGPLv3 license listed.  

However, in the app, the "license" page under settings shows a license that is very much not AGPLv3, nor any Free Software license.  It explicitly forbids redistribution of modified versions.

So what is the license on this application?  Please unify the licensing statement, because right now it is horribly unclear, and I cannot use an application with unclear licensing.

**Comment by lastzero** [comment]
You can use our software under the terms of the AGPL if you build from source or use the Docker image with the "ce" tag. This is explained in our Release Notes, Membership FAQs, Open Source FAQs, and Getting Started FAQs:

- https://docs.photoprism.app/release-notes/#may-2-2023
- https://www.photoprism.app/membership/faq#why-does-your-docker-image-use-the-plus-license-instead-of-the-agpl
- https://www.photoprism.app/oss/faq#why-does-your-docker-image-use-the-plus-license-instead-of-the-agpl
- https://docs.photoprism.app/getting-started/faq/#why-does-your-docker-image-use-the-plus-license-instead-of-the-agpl

We cannot "merge" or "unify" the licenses, as that would actually make it unclear.

Please also note that our team and all issue subscribers receive an email notification from GitHub whenever a new comment is added, so these should only be used to share important information and not for [discussions, questions](https://github.com/photoprism/photoprism/discussions), or [expressing personal opinions](https://www.photoprism.app/code-of-conduct):

- https://github.com/photoprism/photoprism?tab=readme-ov-file#github-issues-%EF%B8%8F

If you have further questions or concerns, you are welcome to email us or use GitHub Discussions if you want to discuss this publicly with our community. Thank you very much!
