### ISSUE TITLE
Uploaded Video previews correctly, playback is upside down 

### ISSUE THREAD

**Issue by matteohoeren** [photoprism/photoprism#4614]
#### 1. What is not working as documented?

When i playback a video (.MOV Format, HEVC H.265, Recorded on an iPhone 13 Mini) it is flipped 180° degrees. The preview is displayed correctly. It's kinda weird because it happens on nearly all said videos, but not every single one of them. Their orientation is right on my iPhone and my Photos Library on Mac. 

#### 2. How can we reproduce it?

Upload a Video with Photosync from an iPhone, filmed in portrait orientation.

#### 3. What behavior do you expect?

Playback the video with the right orientation.

#### 4. What could be the cause of your problem?

Photoprism infers the orientation? 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Here are 2 screenshots:

https://ibb.co/25dDyqq
https://ibb.co/xscpGpk

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, Version 24.04, Build 240915-e1280b2fb (docker on linux)

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: MacOS

(d) Browser Types & Versions: Chrome-based browser

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? None

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel N100

(b) Physical Memory & Swap Space in GB: 32GB RAM

(c) Storage Type: SSD 2TB

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by graciousgrey** [comment]
Do you have hardware transcoding enabled?

If yes this might be related to: 
- https://github.com/photoprism/photoprism/issues/4403

**Comment by matteohoeren** [comment]
@graciousgrey No, i don't have that configured in my docker-compose so it defaults to software transcoding. Should i try enabling hardware transcoding?

**Comment by lastzero** [comment]
Before you try anything else, we recommend that you check the metadata of both files with Exiftool, as described here in our documentation:
- https://docs.photoprism.app/getting-started/troubleshooting/metadata/

**Comment by lastzero** [comment]
I will move this to discussions while the issue is still being investigated.
