### ISSUE TITLE
Private folders still shown in Albums, search, etc

### ISSUE THREAD

**Issue by Ayo91** [photoprism/photoprism#4624]
I set a folder as private (similar to single images) and I still see images or videos related to that folder in the rest of the sections.

For search the checkbox for exclude private elements is enabled.

**Comment by graciousgrey** [comment]
Thank you for your feedback! 

This works as designed. Marking a folder as private in the folder edit dialog (which is only possible with "experimental features" enabled) only hides the folder in the  folder view. It does not mark all photos of this folder as private. 

You can mark photos as private as described here: 
- https://docs.photoprism.app/user-guide/organize/private/

The possibility to mark all photos of an album or folder as private is planned but not yet implemented.
