### ISSUE TITLE
Google Photos like quiz feature - Is this the Same person? 

### ISSUE THREAD

**Issue by demiahmed** [photoprism/photoprism#4634]
Firstly I would like to appreciate the tremendous effort taken by the devs to make Photoprism such an awesome free tool. I've been loving every single feature and execution of it. 

While it has a few flaws on its own, the features outweigh the bugs. 

For anyone moving from Google Photos, this feature would be a lifesaver. How about a prompt or a side menu that starts a quiz (gamify) asking the user to identify, match existing faces much like Google Photos? This would potentially save tons of time in labelling, renaming and identifying faces.

Potentially the above feature can be improved by adding a text field below the image, to choose a new person (or tag existing) if the left and right faces do not match.

![6urksirnuug31](https://github.com/user-attachments/assets/0369b39e-b155-4614-b015-1739b478a60e)

Hope this can be of good value to the platform.

Cheers

**Comment by graciousgrey** [comment]
Thank you for your feedback!

We do already have a feature request for this, you are welcome to give it a :+1: 

- https://github.com/photoprism/photoprism/issues/1595
