### ISSUE TITLE
Some task is spinning up disk each 24hours

### ISSUE THREAD

**Issue by sgflt** [photoprism/photoprism#4640]
#### 1. What is not working as documented?

After some time I have noticed the disk array is again spinning up periodically.
fatrace's output reveals some task is updating or accessing /photoprism/storage/config/hub.yml

#### 2. How can we reproduce it?

1. Wait at least 24 hours.
2. Check power usage

#### 3. What behavior do you expect?
Do not spin storage disk if there is no change.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
![spin-up-by-photoprism](https://github.com/user-attachments/assets/06260292-92d9-4ff7-b9aa-442e7a161096)

fatrace:
09:32:25.163335 photoprism(6227): O /photoprism/storage/config/hub.yml
09:32:25.165197 photoprism(6227): CW /photoprism/storage/config/hub.yml
#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64

(b) Database Type & Version: MariaDB

(c) Operating System Types & Versions: Linux

Build 240915-e1280b2fb

**Comment by lastzero** [comment]
This works as designed to [retrieve the API keys for the interactive world maps](https://docs.photoprism.app/getting-started/troubleshooting/firewall/#outgoing-connections) from our backend. The source code for this is public if you want to check the details and make suggestions for improvement. I also recommend checking the backup settings, as these can also cause disk activity:
- https://docs.photoprism.app/user-guide/settings/advanced/#backups
- https://docs.photoprism.app/getting-started/config-options/#backup

**Comment by sgflt** [comment]
Could't be refresh performed just in time when API key is needed?

**Comment by sgflt** [comment]
I had configuration inspired by https://docs.photoprism.app/getting-started/advanced/caching/.

But https://docs.photoprism.app/getting-started/docker-compose/#photoprismstorage now recommends moving whole /storage folder to SSD. So cache optimization may be obsolete. 

I have moved whole /storage to SSD now.
