### ISSUE TITLE
cant delete admin user 

### ISSUE THREAD

**Issue by Xyz00777** [photoprism/photoprism#4662]
#### 1. What is not working as documented?
i cant delete the per default created admin user because its an "system user". And i find no documentation about that.

#### 2. How can we reproduce it?

all per cli on a fresh instance
1. `photorpism users reset`
2. `photoprism users ls`  now there should be 0 users
3. `photoprism users add <USERNAME> -S` specified user get created as superuser but also admin user
4. `photoprism users rm admin`  the following error is coming up "cannot delete system user"

#### 3. What behavior do you expect?

should be able to delete some default admin user when i created an own admin user for better security so i have no defualt user...

#### 4. What could be the cause of your problem?

i dont know

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
![Screenshot_20241212_163038-1](https://github.com/user-attachments/assets/d0eccb9d-7bfa-47c1-a798-ae945ca437c5)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64

(b) Database Type & Version: MySQL

(c) Operating System Types & Versions: NixOS (linux)

(d) Browser Types & Versions: CLI photoprism version 240711-2197af848

**Comment by lastzero** [comment]
This is so you don't accidentally lock yourself out. If this is a new installation, you can change the default admin username with the `PHOTOPRISM_ADMIN_USER` environment variable:
- https://docs.photoprism.app/getting-started/config-options/#authentication

**Comment by Xyz00777** [comment]
oh okay, thanks for the information
