### ISSUE TITLE
UX: Indicate real file type on top of the image with a transparent badge

### ISSUE THREAD

**Issue by RAYs3T** [photoprism/photoprism#467]
I think an option to display the real image type (which was used to create the JPG thumbnail) on top of the image / near the other control elements would be great.
Specifically something like "RAW" or "CRAW" as you can see it in the camera overlay. 

![image](https://user-images.githubusercontent.com/16596807/90254641-61034200-de43-11ea-8e2a-5c98c3a0e331.png)
![image](https://user-images.githubusercontent.com/16596807/90254768-8e4ff000-de43-11ea-8a4a-28e335e37624.png)

Some sort of transparent sitting in one of the corners.

**Comment by lastzero** [comment]
Sounds good! We'll keep that as idea for later.

**Comment by graciousgrey** [comment]
Related to #314

**Comment by graciousgrey** [comment]
I included this in: https://github.com/photoprism/photoprism/issues/314.
