### ISSUE TITLE
Synology: Simplify installation

### ISSUE THREAD

**Issue by Darkwolf1515** [photoprism/photoprism#468]
Issue 1: Despite having a storage folder configured, it still saves into the orignals folder, these are my mounts 
![image](https://user-images.githubusercontent.com/65789901/90364230-95e5e380-e053-11ea-8f4e-17bc8aeb3d8e.png)

(also tried just /storage)

Issue 2: Password does not work, tried admin and "photoprism" as the password, just tells me its invalid. 
![image](https://user-images.githubusercontent.com/65789901/90364532-dba2ac00-e053-11ea-89d2-ac7551e08fb7.png)

I assume most of these issues stem from synology's version of docker, any help would be appreciated!

**Comment by lastzero** [comment]
You probably don't have the environment variables set as shown in our Docker Compose example: https://dl.photoprism.org/docker/docker-compose.yml

Specifically, you need to set `PHOTOPRISM_STORAGE_PATH` and `PHOTOPRISM_ADMIN_PASSWORD`.

**Comment by Darkwolf1515** [comment]
Been trying to make it work with the storage path variable, but I genuinely dont know what path to put there + what volumes to mount.

**Comment by lastzero** [comment]
Mounting storage at `/photoprism/storage` is good, you just need to set `PHOTOPRISM_STORAGE_PATH` to the same value. Otherwise it will be located in the originals folders as this is the default in case there is no storage folder specified.

**Comment by Darkwolf1515** [comment]
Well, i did that, but nothing shows up in the folder, meaning that part did not work sadly.

**Comment by lastzero** [comment]
Also delete the `.photoprism` folder in originals to make sure it isn't used by accident and properly restart (down & up) the container. Can you show a screenshot of the Environment tab (without password)?

**Comment by Darkwolf1515** [comment]
path in the variable was set to /photoprism/storage, the volume used that path, and was mounted with /photoprism/storage, i swapped the variable to be docker/photoprism/storage but no dice there. And I have wiped the folder clean each time.

**Comment by Darkwolf1515** [comment]
![image](https://user-images.githubusercontent.com/65789901/90373362-558d6200-e061-11ea-9f1b-2b3700d0c961.png)

**Comment by lastzero** [comment]
`PHOTOPRISM_STORAGE_PATH` must be `/photoprism/storage`, not `docker/photoprism/storage`

**Comment by lastzero** [comment]
PhotoPrism can't see anything outside its container. All paths must be relative to what is inside the container.

**Comment by Darkwolf1515** [comment]
> 
> 
> `PHOTOPRISM_STORAGE_PATH` must be `/photoprism/storage`, not `docker/photoprism/storage`

It was at first, I changed it after it failed to save to that folder.

**Comment by lastzero** [comment]
Looks like we need to simplify Synology installations and add more debug info to the Web UI as you probably can't run `photoprism config` in a terminal? This would output the actual config values so that you know what PhotoPrism really uses.

**Comment by Darkwolf1515** [comment]
It does have a terminal, although ive yet to be able to type into it, its less Synology installations that need to be simplified and just the standard docker without compose install. Haven't used docker outside of Synology but im going to assume they built this one around being as user friendly as possible.

**Comment by lastzero** [comment]
We could set more defaults for the standard docker image, like a standard password etc. - but then some users might not change it and run into security issues. So there are tradeoffs, many MongoDB installations got hacked because of insecure defaults: https://snyk.io/blog/mongodb-hack-and-secure-defaults/

**Comment by Darkwolf1515** [comment]
> 
> 
> We could set more defaults for the standard docker image, like a standard password etc. - but then some users might not change it and run into security issues. So there are tradeoffs, many MongoDB installations got hacked because of insecure defaults: https://snyk.io/blog/mongodb-hack-and-secure-defaults/

Why not just let users create an admin account with a password on first boot? Unless that requires wayyy more effort and work than its worth.

**Comment by Darkwolf1515** [comment]
And if I had to guess whats got me screwed up is that PHOTOPRISM_STORAGE_PATH variable, im used to apps just wanting a /config or whatevers needed, had it just wanted /storage, /imports, /index, and so on, working like jellyifn and nextcloud, I think that would make things much easier.

**Comment by lastzero** [comment]
You can also use a YAML config file, in that case you need to create and update it somewhere. In case you use a `docker-compose.yml`, I think maintaining a separate config file is more complicated.

**Comment by lastzero** [comment]
Added a default for PHOTOPRISM_STORAGE_PATH: 1bd4336b7999a71fca676bac9ad84539b90c5ba6

Updated our Docker docs accordingly: https://github.com/photoprism/photoprism-docs/commit/42ba3de83a29bda7a14963a5bce3f67139656933

**Comment by Darkwolf1515** [comment]
Thanks for your time btw, to my knowledge Sinology docker cant use docker compose, and this is the first app out of the 5 or so ive used that didnt just like volume mount paths, if you want how id fix it, I would remove the PHOTOPRISM_STORAGE_PATH variable, and just allow users to use mount paths, or if you can make PHOTOPRISM_STORAGE_PATH  account for it that works too.

And im confused about the default password thing, doesn't the docker compose thing set a default password that the docs say you have to use to get in and to change after, I dont see how that's much different the giving the standard docker image a default.

But yeah, thanks for dealing with my specific problem!

**Comment by lastzero** [comment]
Yes, if you use docker-compose.yml you have a default password but not when you run Docker without a specific password. Again this could be solved by setting a default in our Dockerfiles, but that is more hidden to the user. So people might just start the image, don't know how to login, let it run and then someone else logs in using the well known default to upload pr0n.

**Comment by Darkwolf1515** [comment]
> 
> 
> Yes, if you use docker-compose.yml you have a default password but not when you run Docker without a specific password. Again this could be solved by setting a default in our Dockerfiles, but that is more hidden to the user. So people might just start the image, don't know how to login, let it run and then someone else logs in using the well known default to upload pr0n.

Ah, that makes a lot more sense when you put it that way, thanks for your time and for building something to help others.

**Comment by Darkwolf1515** [comment]
I downloaded the newest image, once I get a bit more time ill smash some more paths at it until maybe something sticks, how should it all work now, theoretically?

**Comment by lastzero** [comment]
Well, the recommended defaults can be found in our https://dl.photoprism.org/docker/docker-compose.yml example.

Guess we'll get a Synology NAS for testing and then provide pre-configured images that should just work... difficult to perform remote debugging :/

**Comment by Darkwolf1515** [comment]
> 
> 
> Well, the recommended defaults can be found in our https://dl.photoprism.org/docker/docker-compose.yml example.
> 
> Guess we'll get a Synology NAS for testing and then provide pre-configured images that should just work... difficult to perform remote debugging :/

Man i'd feel guilty if you spent $500 on something that you dont really need, the docker there should work like any other docker, its just the volumes are a tad not what im used to, this is the only app ive seen behave this way. Standard docker should work for your testing.

**Comment by Darkwolf1515** [comment]
Heres my jellyfin volumes, im used to it being this simple 
![image](https://user-images.githubusercontent.com/65789901/90378940-8d000c80-e069-11ea-915e-12a18e42534a.png)

**Comment by lastzero** [comment]
There are probably also other (more hidden) issues like how you run the image as a certain user to fix permissions...

**Comment by Darkwolf1515** [comment]
> 
> 
> There are probably also other (more hidden) issues like how you run the image as a certain user to fix permissions...

Well if youre gonna get one make sure it actually can run docker, only a select few can, I used the ds720+

**Comment by lastzero** [comment]
See comments at https://github.com/photoprism/photoprism/issues/411#issuecomment-662890791 

In short: It seems many NAS don't have proper Docker support and don't allow to set certain config values so that images need to implement workarounds instead.

**Comment by Darkwolf1515** [comment]
Hey! The update seems to have fixed it, im gonna finish it but I just mounted it as /photoprisim/storage and it made the rest of the folders!

**Comment by Darkwolf1515** [comment]
It works, you fixed it!

**Comment by LMSSonos** [comment]
Using it on synology and works as expected. just mont the original folder as readonly (ro) so nothing is changed

```
    volumes:
      - /volume1/photo/Family:/photoprism/originals/Family:ro           # [local path]:[container path]
      - /volume1/docker/photoprism/storage:/photoprism/storage   # Settings, index, sidecar files, and generated thumbnails
```

**Comment by kudalife** [comment]
Hi can I get a little clarity? I have a DS918+ and been struggling to workout where the files needs to be for originals I'm using docker on the NAS and I selected the folder under volume for where all my photos are and to manually add yet it doesn't seem to detect those photos? This script was installed from the registry within docker. and can I point out that the import function wow that really needs some work, like it doesn't even read the meta and yeah lots of issues. Thanks in advance for assistance

**Comment by lastzero** [comment]
Hope you have a great Sunday too! 👍

Would you mind sharing your configuration? Did you read Getting Started at docs.photoprism.org?

**Comment by kudalife** [comment]
reading docs.photoprism.org says go here do this do that, nothing that points the help for Synology NAS users, as I said Docker on the NAS has the ability to search for what apps we want to install, it's automatic and just works, but there is nothing telling us how to change or select what folder our photos are as originals (except assumption that we select the volume) etc if its in a folder that we cant see in file manager of the NAS we have to use Terminal which not everyone knows how to use, even though I am trying to figure that out right now.

Steps taken:

1. Open Docker and click Registry, search for PhotoPrism, double click and choose latest version
2. After it finishes downloading click on the tab called images then click Launch (This brings up the General Settings page)
3. On that page you click advance settings, in that you click Enable Auto-Restart, under Volume, you Add folder that you wish to mount with this app.
4. under network you select use same as docker host
5. Click Apply and the way we go to the web URL and start using the app

**Comment by lastzero** [comment]
If you send us a Synology NAS for testing, we can tell you the exact steps. Looks like you didn't set any environment variables for configuration? Specific paths and features will depend on this.

**Comment by kudalife** [comment]
![image](https://user-images.githubusercontent.com/71207749/93015528-94c9b700-f5fd-11ea-813a-a5d30b49ebee.png)
Looking at previous comments, we don't need to send you a Synology NAS to test, its standard DOCKER practise. It automatically fills our environment variables automatically and yes I have removed the PHOTOPRISM_STORAGE_PATH in hopes that it works for like the previous poster wrote. There has been lots of comments regarding Synology NAS yet you won't write a guide on it!

**Comment by lastzero** [comment]
Your welcome to send a pull request for that. Other users reported no remaining issues, so this ticket was closed.

**Comment by lastzero** [comment]
The environment variables Synology lists are NOT complete, see https://dl.photoprism.org/docker/docker-compose.yml for an example and https://docs.photoprism.org/getting-started/config-options/ for a complete list. There was no way for us to know that this "auto detection" exists.

We might provide a special Docker image for Synology users later when we had time to implement and test it. Latest feedback was that this is probably not needed, but now it seems like we should still do it. Donations help us to spend more time with the features you care about.

**Comment by LMSSonos** [comment]
@kudalife in the end it is much easier to to login into the synology using ssh and use the `docker-compose.yaml`

For the volumes, my configuration looks like this (i did not make any other changes to the docker-compose-yaml.
```
    volumes:
      - /volume1/photoprism/Family:/photoprism/originals/Family:ro           # [local path]:[container path]
      - /volume1/docker/photoprism/storage:/photoprism/storage   # Settings, index, sidecar files, and generated thumbnails
```
make sure the `/volume1/docker/photoprism/storage` folder exists before you start

then in ssh call `sudo docker-compose up -d` (or leave the -d if you don't want to start it in background).

**Comment by kudalife** [comment]
> @kudalife in the end it is much easier to to login into the synology using ssh and use the `docker-compose.yaml`
> 
> For the volumes, my configuration looks like this (i did not make any other changes to the docker-compose-yaml.
> 
> ```
>     volumes:
>       - /volume1/photoprism/Family:/photoprism/originals/Family:ro           # [local path]:[container path]
>       - /volume1/docker/photoprism/storage:/photoprism/storage   # Settings, index, sidecar files, and generated thumbnails
> ```
> 
> make sure the `/volume1/docker/photoprism/storage` folder exists before you start
> 
> then in ssh call `sudo docker-compose up -d` (or leave the -d if you don't want to start it in background).

Hi, I have logged into Synology via putty (ssh) docker-compose.yaml and get an error as in not found, so then I downloaded and uploaded docker-compose.yaml with volumes similar to what you have mentioned from github, and yeah I get alot of images running in docker webdav dummy, mariadb:10.5 version etc and what a mess which none will work on port 2343

You clearly have this installed on a Synology device, if you could provide specific step by step cause I have been trying very hard to get it going and although through Synology Docker I kinda got it to work by placing homes/Kuda/Drive/Photos   =  /photoprism/originals :RO but I don't know if it's setup properly as in if I add settings to photos that it will remain etc I would be greatly appreciative alot

**Comment by LMSSonos** [comment]
@kudalife the script launches only 2 containers. So the webdav musst be something else (maybe from synology itself). But after the launch it should look like this:

![image](https://user-images.githubusercontent.com/19758451/93086443-6dbfc380-f697-11ea-9d30-8f0e7b9716e7.png)

If you can't access it may be that you need to configure the Synology Firewall in > Control Panel > Security > Firewall. Mine is disabled, so I had nothing to do here, but if yours is enabled, you need to open the port 2343 to get access.

**Comment by lastzero** [comment]
Maybe it's the development config? That has a webdav service defined. Please use https://dl.photoprism.org/docker/docker-compose.yml 👈

**Comment by KITblue** [comment]
Normal under my unraid, Synology can refer to
![image](https://user-images.githubusercontent.com/68754977/93758063-573ade80-fc3a-11ea-8e4f-59a00be3e735.png)

**Comment by lastzero** [comment]
Think I've implemented a lot of this but can't test as we don't have a Synology NAS. Let us know if you still need anything! Otherwise, we would like to close this.

**Comment by toasti2000** [comment]
> Normal under my unraid, Synology can refer to
> ![image](https://user-images.githubusercontent.com/68754977/93758063-573ade80-fc3a-11ea-8e4f-59a00be3e735.png)

Is it not possible to use docker-compose in Unraid? Would be much easier.
What options are set in PhotoPrism when I just install it in Unraid?
PP has so much options now and I want to be able to control these things.

**Comment by Darkwolf1515** [comment]
> Think I've implemented a lot of this but can't test as we don't have a Synology NAS. Let us know if you still need anything! Otherwise, we would like to close this.

As the guy who opened this, you fixed all my Synology problems back on August 17, so I think it’s safe to close.

**Comment by bmscmoreira** [comment]
Just to add something: you can install portainer in synology and then use its interface to deploy a stack using a docker-compose v.2 syntax. Quick and easy!

**Comment by lastzero** [comment]
We may add a Portainer and/or Synology page to our Gettings Started docs in the Advanced section. Contributions welcome!

**Comment by bmscmoreira** [comment]
> We may add a Portainer and/or Synology page to our Getting Started docs in the Advanced section. Contributions welcome!
> 
> Repo: https://github.com/photoprism/photoprism-docs/tree/master/docs/getting-started
> 
> Example: https://docs.photoprism.org/getting-started/proxies/advanced-nginx-proxy-setup/

Great! I am really new to Photoprism (installed it yesterday) and it seems really great on my synology. I'll start a "portainer + synology" setup on the repo and share all my config. All seems to be working except I can't seem to connect yet using synology reverse proxy. I'll leave that as a "to-do". Expect some news in the next hours.

**Comment by bmscmoreira** [comment]
Done. I *think* I did a pull request correctly.

**Comment by banshee1971** [comment]
In case it could help. No need to purchase Synology NAS to test Docker.
Xpenology is based on the opensource, so they provide their code. That lead to the creation of Xpenology! 
https://xpenology.org/

So if someone wants to test the docker image there, simply find a PC, burn the image on a USB stick, plug at least one drive and we have the minimum for a NAS
