### ISSUE TITLE
You cannot log in with the default password after installing with Docker

### ISSUE THREAD

**Issue by 260250510** [photoprism/photoprism#478]
You cannot log in with the default password after installing with Docker

**Comment by macguirerintoul** [comment]
I'm seeing this as well - neither `photoprism`, the environment variable I set, nor the password I set via `photoprism passwd` seem to work. It looks like there is no default account being created? Here's a screenshot from my database: 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/18323154/91244691-d1427b00-e701-11ea-93be-7e5c47755060.png">

**Comment by lastzero** [comment]
Check the users table, admin should always exist. Make sure the encryption variable is properly set as well.

**Comment by macguirerintoul** [comment]
A `users` table wasn't created, but I do have a `people` table. The admin account exists there, but for some reason all I can get is "invalid user name or password". The `login_attempts` value in `people` isn't increasing for the account either. Sorry, what do you mean by encryption variable?

**Comment by lastzero** [comment]
Might be a really old database, what version is this?

**Comment by lastzero** [comment]
More specifically:

```
-e PHOTOPRISM_ADMIN_PASSWORD="photoprism" \
```

The initial password is photoprism. You can change it in Settings or using the `photoprism passwd` command in a terminal.

To see the current value, run `photoprism config`. It's all in our User Guide:

https://docs.photoprism.org/getting-started/docker/

For Docker Compose:

https://docs.photoprism.org/getting-started/docker-compose/

**Comment by macguirerintoul** [comment]
Here's the output from `photoprism passwd`:

```
root@87b202526f3d:/photoprism# photoprism passwd
ERRO[2020-08-27T01:26:11Z] places: Error 1062: Duplicate entry 'zz' for key 'PRIMARY' (create place id zz) 
ERRO[2020-08-27T01:26:11Z] places: Error 1062: Duplicate entry 'zz' for key 'PRIMARY' (first or create cell id zz) 
ERRO[2020-08-27T01:26:11Z] camera: Error 1062: Duplicate entry 'zz' for key 'uix_cameras_camera_slug' (first or create Unknown) 
ERRO[2020-08-27T01:26:11Z] lens: Error 1062: Duplicate entry 'zz' for key 'uix_lenses_lens_slug' (first or create Unknown) 
INFO[2020-08-27T01:26:12Z] please enter a new password for admin (at least 6 characters) 
New Password: 
Retype Password: 
INFO[2020-08-27T01:26:18Z] changed password for admin                   
INFO[2020-08-27T01:26:18Z] closed database connection                   
root@87b202526f3d:/photoprism# 
```

I get confirmation that the password was changed, but still can't log in. I've also tried setting an initial password via environment variables, but couldn't log in that way either.

**Comment by lastzero** [comment]
Maybe a client issue? Did you try a different browser?

**Comment by macguirerintoul** [comment]
Got it working, although not sure what fixed it. Here's what I did: 

- enabled debug mode, saw "user admin not found" error
- dropped/recreated the database several times, seemed to do nothing
- I wasn't using the exact `command` from the `docker-compose.yml` for `mariadb` because I had a previous command from a Nextcloud container. I tried piecing together the options 
- `sudo rm -rf` the PhotoPrism storage directory, which seemed to shake things up a bit (caused a missing `settings.yml` error)
- `sudo rm -rf` the `photoprism` directory within my MariaDB directory
- `photoprism passwd` after both of the above caused the container to crash/restart
- ran `photoprism passwd` again after everything above and then logged in and it worked

**Comment by lastzero** [comment]
Sounds like a wild story :) make sure to use the latest image, the settings "error" was actually just an info and we reduced the log level to debug so that it causes less confusion
