### ISSUE TITLE
Import seems to mess up images when source files have a certain naming standard (stacking option on or off - same issue)

### ISSUE THREAD

**Issue by purana** [photoprism/photoprism#483]
You have a directory that contains images named like so below;

IMG_0001.JPG
IMG_0001_2.JPG
IMG_0001_2_2.JPG
IMG_0001_2_2_2.JPG
IMG_0001_2_3.JPG
IMG_0001_2_4.JPG
IMG_0001_3.JPG

NOTE: These files are not all the same image either, they are 7 different images, that somehow just got the same filename prefix.

(I only came across this as I have 19 year old digital images that somehow got like this from the early period of Digital Cameras just starting to become popular).

You run the import..

`
root@13903ec12fcb:/photoprism# photoprism import

INFO[2020-08-26T08:25:57Z] moving media files from /photoprism/import to /photoprism/originals

INFO[2020-08-26T08:25:57Z] classify: loading nasnet

INFO[2020-08-26T08:26:00Z] classify: loading labels from labels.txt

INFO[2020-08-26T08:26:00Z] import: no .ppignore file found

INFO[2020-08-26T08:26:00Z] import: added folder /

INFO[2020-08-26T08:26:00Z] import: added folder /2002

INFO[2020-08-26T08:26:00Z] import: added folder /2002/Buddy

INFO[2020-08-26T08:26:00Z] mediafile: IMG_0001.JPG was taken at 2002-05-26 20:44:23 +0000 UTC (meta)

INFO[2020-08-26T08:26:00Z] import: moving main jpg file 2002/Buddy/IMG_0001.JPG to 2002/05/20020526_204423_40B5B5E9.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_2.JPG to 2002/05/20020526_204423_40B5B5E9.00001.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_3.JPG to 2002/05/20020526_204423_40B5B5E9.00002.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_2_2.JPG to 2002/05/20020526_204423_40B5B5E9.00003.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_2_3.JPG to 2002/05/20020526_204423_40B5B5E9.00004.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_2_4.JPG to 2002/05/20020526_204423_40B5B5E9.00005.jpg

INFO[2020-08-26T08:26:00Z] import: moving related jpg file 2002/Buddy/IMG_0001_2_2_2.JPG to 2002/05/20020526_204423_40B5B5E9.00006.jpg

INFO[2020-08-26T08:26:00Z] mediafile: 11 thumbnails created for 20020526_204423_40B5B5E9 [405.475519ms]

INFO[2020-08-26T08:26:04Z] import: added main jpg file 2002/05/20020526_204423_40B5B5E9.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00001.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00002.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00003.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00004.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00005.jpg

INFO[2020-08-26T08:26:04Z] import: added related jpg file 2002/05/20020526_204423_40B5B5E9.00006.jpg

INFO[2020-08-26T08:26:04Z] import: deleted empty folder 2002/Buddy

INFO[2020-08-26T08:26:04Z] import: deleted empty folder 2002

INFO[2020-08-26T08:26:04Z] import completed in 8.072551339s

INFO[2020-08-26T08:26:04Z] closed database connection

`

And when you log into the web interface all the files that got *.0000n.jpg named don't have any image thumbnail associated. They are appearing as broken in the web interface. See image below on what it looks like in the web interface.

![image](https://user-images.githubusercontent.com/5284738/91280916-cef82380-e7ca-11ea-804d-01f67aed918a.png)

I did the same test import with Stacking disabled and same condition happens.

I am a very new user only just started playing around with this and absolutely love it, but this problem is going to cause me so many problems. I'll need to go through about 90GB of images to fix up all these file names before I import anything OR wait for this condition to be fixed in a future release.

Let me know if you need any more details.

Thanks for making this wonderful software - totally impressed with it.

**Comment by lastzero** [comment]
Think the reason is how import works, it tries to find related files to import them together.

In your case, it might be better to just keep the file names and index the original directories as they are.

**Comment by purana** [comment]
@lastzero I wonder if it would be possible to implement an import switch/option to turn that feature off. I like the file naming that it creates for me, just under this circumstances I don't want it to assume what its doing for me here.

**Comment by lastzero** [comment]
It can certainly be improved but it's not possible to completely remove the concept of files that belong together:

Importing XMP (or even RAW) files without a JPEG doesn't make much sense, you need to get them together. The concept of sidecar files exists in photography if we like it or not. And there are different patterns for the naming on top of it. Personally, I might have standardized it more.

**Comment by purana** [comment]
@lastzero I understand, I've worked out what was causing these broken images in the web view and now I can do remediation steps on the data before the import to deal with it.

photoprism is very nice. It's going to be so much easier to manage out images moving forward. It's been done for so long on Macintosh using iPhoto (and then Photos app) now I can finally move away from that completely.

Thanks for the tip above that I can put the files directly into Originals path in directory structure I want and then do an index. I didn't know you could do that, but that is an option too.

Thank you
