### ISSUE TITLE
Reindex error

### ISSUE THREAD

**Issue by joy4eg** [photoprism/photoprism#486]
Hey there,

First of all, thanks for such great app!

A little bit of context what I have:
- RPI 4 with ubuntu 20
- `photoprism/photoprism-arm64:latest` image inside docker (`sha256:0038a5649d1674de3b0ac5cedd1ab2db3eb368ea9aa760e45f2f1f9815e30249`)
- NFS/syncthing share on my NAS
- [syncthing](https://syncthing.net/) app on my mobile phone (Sony xz1 compact) which is configured to sync `DCIM` folder to NAS
- photoprism is configured to use NAS (via NFS) as the source for originals

So the main goal to have a self-hosted replacement for google photos.

What I do:
- My phone produces photos in sequential order (like `DSC_9378`, `DSC_9379`, etc)
- Sometimes I can remove old/bad/last photos from my phone using file manager or album application
- All changes are synced to NAS
- Those photos removed from photoprism too, which is OK
- But their metadata still exists, which cause the issue

The issue:
- If I remove a photo which was synced to NAS and indexed in photoprism, photoprism keeps it's metadata
- I do a new photo
- My phone assigns the same filename as the deleted one (to keep sequential order)
- [Sync to NAS and reindex in photoprism]
- photoprism's logs:
```
level=info msg="index: restored from DSC_9378.yml"
```
- As the result, the new photo has tags/data from the deleted one which is completely different and wrong

Some examples:
```
$ exiftool /mnt/router/files/sync/yaroslav/camera/sdcard/100ANDRO/DSC_9378.JPG | grep GPS
GPS Version ID                  : 2.2.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
GPS Time Stamp                  : 13:48:09
GPS Status                      : Measurement Active
GPS Map Datum                   : WGS-84
GPS Processing Method           : network
GPS Date Stamp                  : 2020:08:23
GPS Altitude                    : 26.6 m Above Sea Level
GPS Date/Time                   : 2020:08:23 13:48:09Z
GPS Latitude                    : 46 deg 9' 50.73" N
GPS Longitude                   : 34 deg 48' 43.15" E
GPS Position                    : 46 deg 9' 50.73" N, 34 deg 48' 43.15" E
```
Photoprism:
![Screenshot_20200901_180742](https://user-images.githubusercontent.com/878385/91869065-1a547b00-ec7e-11ea-98e8-4c63cabe2ef7.png)

**Comment by lastzero** [comment]
Understand the problem, but not sure how to solve it as we also need to handle the case that files are edited or restored from a backup by the user.

**Comment by joy4eg** [comment]
>but not sure how to solve it 

From my point of view, we can compare some static metadata (like `TakenAt`, `GPS`, or smth else) and decide to use or not the previously generated sidecar tags. But this is true only if photo has those exif data.

**Comment by lastzero** [comment]
The user may edit files to change, add, or remove metadata intentionally... Would be much easier to use unique file names, also for backups & sync.

**Comment by joy4eg** [comment]
User also may save some photo like `my_pet_edited.jpg` and will have wrong tags.

There is no elegant solution for that issue, just a set of compromises :)

**Comment by lastzero** [comment]
There is a purge command with a hard option BTW. You may run that and turn Yaml sidecar backup files off. Then readded files should be indexed without using data from a backup.

**Comment by joy4eg** [comment]
>Why would that specific file name lead to wrong tags?

Imagine you have two (or more) pets, and you are editing their photos from time to time. I used that filename just as a placeholder, it may contain your first pet (a dog), or a second one (a little humster). But the tags will belong to whoever gets first in the index.

>There is a purge command with a hard option BTW. You may run that and turn Yaml sidecar backup files off. Then readded files should be indexed without using data from a backup.

I guess it's a good workaround, thanks!

**Comment by lastzero** [comment]
Excellent! I'll close this as we can't come up with a better solution for now...
