### ISSUE TITLE
Fixed, Success Message in German

### ISSUE THREAD

**Issue by MarJun1988** [photoprism/photoprism#487]
In the German language, when changing an album, after pressing the Save button, the message comes in English (Album saved).

<img width="774" alt="Bildschirmfoto 2020-09-01 um 21 36 48" src="https://user-images.githubusercontent.com/49251031/91898594-41ba4080-ec9c-11ea-923a-1370c6955855.png">
<img width="525" alt="Bildschirmfoto 2020-09-01 um 21 41 37" src="https://user-images.githubusercontent.com/49251031/91898610-454dc780-ec9c-11ea-9c27-696d18ebdbbf.png">

**Comment by lastzero** [comment]
Thanks for reporting this!

**Comment by graciousgrey** [comment]
Should be fixed now.
