### ISSUE TITLE
Make importing XMP metadata default or option more prominent

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#488]
Maybe you need to enable JSON sidecar files if you disabled them. Otherwise, embedded XMP data can not be indexed.

_Originally posted by @lastzero in https://github.com/photoprism/photoprism/issues/419#issuecomment-664528741_

Sorry, but why do I have to enable an option for *sidecar* files to consider *embedded* metadata?!
If I hadn't read through the closed issue the other day, I would have stopped testing around with photoprism as I would have thought I cannot combine it with my mobile app writing tags as subjects!

**Comment by lastzero** [comment]
Because we don't have a Go library for that yet, we can only extract Exif metadata for now. Just because we support Exif doesn't mean we support anything that can be embedded in JPEG. Note that the default for `PHOTOPRISM_SIDECAR_JSON` in our example config is `"true"` for this reason:

https://dl.photoprism.org/docker/docker-compose.yml

**Comment by lastzero** [comment]
You're welcome to suggest a better description for this option. Some XMP metadata can be read without JSON sidecar files / Exiftool. Just not all, and in particular not embedded data. Technically possible, just not implemented yet.

**Comment by totti4ever** [comment]
Okay, seems to be in the default docker-compose.yml since 3 weeks - but great that it was changed!

Regarding the description: I still don't understand what that switch really does. Description says *sidecar* files, which to me means not in the JPEG. From your sentence (_Some XMP metadata can be read without JSON sidecar files / Exiftool. Just not all, and in particular not embedded data._) I one could understand that some XMP metadata cannot be embedded and has to be in a separate sidecar file.

But I am talking (and I think the guy in the referenced issue as well) about metadata which is embedded, but can be read from photoprism - but only if one enables JSON *sidecar* files.

So, either that switch does also affect embedded meta data or something is weird.

**Comment by lastzero** [comment]
By default, Exiftool (an external application) is used by PhotoPrism to create those JSON sidecar files based on the data it finds embedded. **So it's both.** From our perspective, we read the sidecar file. But the information in the sidecar file typically was embedded in a photo or video file. However, you may also create / modify sidecar files manually. In that case the data comes from the user and not from Exiftool, PhotoPrism or a file.

In addition, Exiftool may include data found in other sidecar files. Plus we also support JSON files created by Google Photos, which we merge with other metadata. That's the long answer.

**Comment by lastzero** [comment]
PS: You're welcome to provide a short description for our example config files / command help if you can come up with something better :)

**Comment by totti4ever** [comment]
> PS: You're welcome to provide a short description for our example config files / command help if you can come up with something better :)

First I need to better understand, to see if I have a better suggestion :-)



> By default, Exiftool (an external application) is used by PhotoPrism to create those JSON sidecar files based on the data it finds embedded. **So it's both.** From our perspective, we read the sidecar file. But the information in the sidecar file typically was embedded in a photo or video file. However, you may also create / modify sidecar files manually. In that case the data comes from the user and not from Exiftool, PhotoPrism or a media file.
> 
> In addition, Exiftool may include data found in other sidecar files. Plus we also support JSON files created by Google Photos, which we merge with other metadata. 

So the process is that

1. all embedded metadata is extracted using exiftool into a sidecar file, which a) is created next to the image or b) only resides in some cache folder ?!? I couldn't find any sidecar files on my filesystem and I am readonly = false. Also the [FAQ](https://docs.photoprism.org/user-guide/user-faq/#what-are-sidecar-files-and-where-do-i-find-them) couldn't help

2. What if a sidecar file already exists? Is it merged or is the embedded metadata not extracted and only the existing sidecar information is considered? Would newly added information in the photoprism web UI be edited into the existing sidecar files then?

3. Nevertheless when indexing, photoprism reads the sidecar files (no matter if newly created or provided with the image)

Is that how it works?
Sorry, but I need to understand what happens before I throw all my photos into photoprism :-)

> That's the long answer.
helped a lot, thanks!

**Comment by lastzero** [comment]
> 1. all embedded metadata is extracted using exiftool into a sidecar file, which a) is created next to the image or b) only resides in some cache folder ?!? I couldn't find any sidecar files on my filesystem and I am readonly = false. Also the [FAQ](https://docs.photoprism.org/user-guide/user-faq/#what-are-sidecar-files-and-where-do-i-find-them) couldn't help

Will be stored in the sidecar path, which itself can be configured. By default, we store generated sidecar files in the storage path outside of the originals path so that originals can be indexed in read-only mode.

> 2. What if a sidecar file already exists? Is it merged or is the embedded metadata not extracted and only the existing sidecar information is considered? Would newly added information in the photoprism web UI be edited into the existing sidecar files then?

If a JSON / XMP sidecar is found, it will always be used for indexing.

The config option (see above) makes sure a JSON file will be automatically created using Exiftool if it does not exist yet.

YAML sidecar files are used as backup only - so the other direction. They will only be read in case the index was lost, but not when reindexing. PhotoPrism won't change what's inside JSON files, so they are not backups but metadata sources that will be merged with existing index values that may be written to YAML files (if enabled).

You typically enable both as they serve different purposes. 

> 3. Nevertheless when indexing, photoprism reads the sidecar files (no matter if newly created or provided with the image)

Yes.

> Sorry, but I need to understand what happens before I throw all my photos into photoprism :-)
> helped a lot, thanks!

You're welcome!

**Comment by totti4ever** [comment]
Found them, thanks!

----

That means there is no proper way back for data edited in Photoprism as the data is not stored back to the original image or sidecar file but only into the database and YAML-sidecar for backup purposes?

Any plans on enabling editing at least the original sidecar files if not the original JPGs?

**Comment by lastzero** [comment]
> That means there is no proper way back for data edited in Photoprism as the data is not stored back to the original image or sidecar file but only into the database and YAML-sidecar for backup purposes?
> Any plans on enabling editing at least the original sidecar files if not the original JPGs?

YAML files are the proper way to automatically create metadata backups, see `PHOTOPRISM_SIDECAR_YAML`. In addition, you can create SQL dumps using standard database tools.

**Comment by totti4ever** [comment]
Sorry, I didn't mean way out on a general meeting, but regarding my process. I.e. that one can use and see the edited data in other places/software without scraping then out of the yaml

**Comment by lastzero** [comment]
Depends on your other software then I guess. There is no obvious way to put merged metadata back to exactly it was. Ideally we can use XMP for syncing with Adobe later. See GitHub issues and Developer Guide for more information.

**Comment by lastzero** [comment]
Updated `photoprism help` hints for this :)

@graciousgrey We also need to update sidecar config hints in our docs!

**Comment by graciousgrey** [comment]
Updated docs as well --> https://docs.photoprism.org/getting-started/config-options/
