### ISSUE TITLE
Batch approve/archive

### ISSUE THREAD

**Issue by flamingspaz** [photoprism/photoprism#489]
I've seen #271 but I think this is slightly different in that it provides value in a much different area than that issue.

As a new user, there are a ton of photos which need to be approved or archived. It would greatly improve the FTE if I was able to select multiple images and approve or archive them all at once. The main place I'd use this is approving entire folders where all the images in that folder have been flagged for review.

**Comment by Morl99** [comment]
Am I missing something? Batch archiving is possible in the latest version. Was this just implemented, or are you talking about something else? If I open the main photo list, I can select multiple images and then use the context menu to batch archive.

**Comment by graciousgrey** [comment]
What is meant here is to improve the workflow of approving or archive photos that are in  the _Review_ section. 
In the _Review_ section it is possible to select multiple photos and archive them using the context menu. But it is not yet possible to select multiple photos (or maybe even folders) and approve all of them.

**Comment by danielo515** [comment]
What I would want is a more "brain-dead" ui for approbing. So the photo I approved disappears and the next one takes its place, so all I have to do is click again in the same place without moving the mouse, or just slightly move it to archive it.

**Comment by graciousgrey** [comment]
Except the keyboard short cuts this should work now. You can either select multiple images and approve or archive them via the context menu. Or you can click the approve/archive button in the details view.

**Comment by Rolf-Smit** [comment]
@graciousgrey is it correct that the multi-select approve is only available in the review section? Not the hidden section under library?

**Comment by lastzero** [comment]
Hidden means the files could be broken or a JPEG is missing. There's nothing to approve.

**Comment by Rolf-Smit** [comment]
> Hidden means the files could be broken or a JPEG is missing. There's nothing to approve.

I'm having an instance where after removing files from the originals, then indexing, then adding the files again, the indexing process would put all the files under "hidden".

For each of the files/photos I see an approve button in the details screen. Which seems to move them out of the "hidden" folder. However after indexing they seem to magically return to "hidden".

I'm guessing this is another approve button then? Maybe even a bug?

**Comment by lastzero** [comment]
No, indexing should not require any confirmation or approval. There should also not be any approve button for hidden files, at best you can delete single files or change the primary JPEG. If you think this is a bug, we'd need the exact steps how to reproduce this incl any custom settings you may have, screenshots, and the version number. Would be great if you can test if it happens with the latest development preview as well (or on our demo, which is based on the preview version).

PS: Try a full rescan if you deleted/modified any sidecar files. I saw your comment under a realted issue that describes problems when you change files in the sidecar path but only perform a partial scan in originals (which would explain the behavior you describe here). Next time it's best to start with GitHub Discussions as this is not a support forum here :)

**Comment by Rolf-Smit** [comment]
Thanks @lastzero, I may have encountered a bug then, I will try to see if I can reproduce it (because after removing the files again, and running `photoprism purge` and `cleanup` the files are no longer indexed into hidden).
