### ISSUE TITLE
Idea: Allow a user to manually stack photos

### ISSUE THREAD

**Issue by SchoolGuy** [photoprism/photoprism#491]
Currently the stacking works good if files are uploaded together. But if I want to upload for example a file from my camera which I edited on my computer I can't manually add this to the stack. I wouldn't consider the file as another picture since it originates from my RAW file I have stored in photoprism. Also (for testing purposes) I first uploaded the my RAW file and then afterwards (the files have the same filename) the jpg. The pictures are considered as different ones, although they are taken at the same time and the same filename. Thus I think it could be an improvement if a user is allowed to add files manually to a stack.

**Comment by graciousgrey** [comment]
I close this as it will be part of #28
