### ISSUE TITLE
Where is edited metadata stored?

### ISSUE THREAD

**Issue by m1nde** [photoprism/photoprism#493]
Hi, I am trying to find out how PhotoPrism saves metadata attributes that I edit. I indexed a few originals and edited GPS coordinates of a few photos. I clicked "Apply" and "Close" afterwards. The metadata appears to be saved, but I cannot figure out where:
1. I checked the EXIF data of the photos with `exiftool -s IMG_2000.jpg`, and the GPS attributes are not set
2. I checked the sidecar `IMG_2000.json` file, which contains all the attributes that the original had set when I indexed it, but not the ones added afterwards.

So, where is this data saved, and how can I make PhotoPrism store the metadata in the EXIF of the file?

**Comment by lastzero** [comment]
We don't modify originals to reduce the risk of file corruption, and to avoid potential conflicts with other tools that might modify files at the same time. You should find related discussions / comments here on GitHub.

The primary storage is a SQL database, you can use any standard tool for browsing, editing, and exporting. See photos, files, and details tables for metadata.

It is planned to add batch editing later and we will also work on a "sync" feature that provides other apps with updated metadata or directly connects to cloud services. Right now, our primary focus is browsing & organizing, not editing.

**Comment by ark-** [comment]
If you have sidecar JSON file enabled surely it changes the metadata there also?

**Comment by lastzero** [comment]
No, because JSON uses the Exiftool schema. There is no 1:1 relationship. Many fields are outright duplicates or have a similar purpose. What you are asking for is a universal metadata conversion tool. Not impossible that we implement such a reverse merge later. Only yaml can be updated with changes for now.

**Comment by ark-** [comment]
Interesting. What is the purpose of JSON sidecar then? Is it just for importing the Google Photos takeout (and maybe other tools I'm not aware of) data into the Photoprism database?

I thought it was a way to keep any metadata changes in plaintext alongside your photos. That was perhaps something I hoped for and excitedly assumed that's what this feature did (without checking).

**Comment by ark-** [comment]
I see this on the FAQ in the docs which I guess is where my assumption that changing metadata in the Web UI of Photoprism would be represented in the JSON files also:

![image](https://user-images.githubusercontent.com/6353339/92707598-54441200-f34d-11ea-9b1d-ccb16ed77bdf.png)

**Comment by ark-** [comment]
Ok delving a little deeper, I note there are 2 types of sidecar. YAML and JSON. 

> Only yaml can be updated with changes for now.

Based on your comment above I should switch to YAML to ensure **all** metadata is preserved on the filesystem in plaintext.

**Comment by lastzero** [comment]
They serve different purposes. JSON is created by Exiftool, YAML is created by PhotoPrism. We could as well have used JSON for backups, but having two JSON files would be even more confusing and putting different schemas in the same file doesn't seem like a good practice either.

**Comment by ark-** [comment]
Thanks for explaining. 

I've added some of the info discussed here to the FAQ about sidecar files. Please see referenced pull request.

**Comment by lastzero** [comment]
Thanks! Might take a few days, currently out of office.
