### ISSUE TITLE
Random videos are skipped

### ISSUE THREAD

**Issue by v-marinkov** [photoprism/photoprism#499]
Trying to index a folder with videos in `originals` but only some of them get added properly as videos. The rest are simply ignored - no "hidden", no errors, nowhere to be found. I tried multiple times with and without "Complete Rescan" with the same result.

The videos were shot on the same camera with the same settings - Panasonic G6 1080p@60fps, mp4. Here is the VLC codec info for one of them:
![image](https://user-images.githubusercontent.com/7135724/93522830-fe153700-f929-11ea-8861-c91f3c25b9a0.png)

What could be going wrong?

**Comment by v-marinkov** [comment]
I found some of them in "Archive" - perhaps from my tinkering earlier today. But a big random chunk is still missing. Is there any cache of archived, duplicate, skipped, etc. files that I can clear? Presumably "Complete Rescan" does this but still no sign of the not indexed videos.

**Comment by v-marinkov** [comment]
Here is what I found in the logs regarding these files after a complete rescan:
```
 2020-09-19 13:52:12 INFO index: skipped archived main mp4 file 2020/2020-08/videos/20200801-22-01-57-231.mp4

2020-09-19 13:52:12 DEBU index: 20200801-22-01-57-231.mp4 was modified (new size 91729762, old size 91729762, new timestamp 1600370394, old timestamp 1600336823)
```
Does it mean they have been archived before? The archive is empty though. I tried archiving a video and restoring it and it worked fine, so I don't know what the logs refer to. Again, **how can I clear any cache** or record of these files so photoprism treats them as completely new?

**Comment by lastzero** [comment]
Doe they share like a common file name / prefix? Another idea would be to check for a common document ID in their metadata. Hard to guess remotely. Maybe you can share examples for testing?

**Comment by v-marinkov** [comment]
I ended up just deleting the entire app storage and re-indexing from scratch. All works fine now - it must have been something I did when I was initially playing around with it. Thanks
