### ISSUE TITLE
Added timeline mode

### ISSUE THREAD

**Issue by rainsuns** [photoprism/photoprism#502]
Timeline like Synology momtens, or timeline like plex photo.

**Comment by RAYs3T** [comment]
Something like this? https://github.com/photoprism/photoprism/issues/214#issuecomment-669082579

**Comment by rainsuns** [comment]
> Something like this? [#214 (comment)](https://github.com/photoprism/photoprism/issues/214#issuecomment-669082579)

like this

![Uploading 150.png…]()

**Comment by rainsuns** [comment]
![150](https://user-images.githubusercontent.com/26184114/93750525-3076ab00-fc2e-11ea-836d-a90339796f7b.png)

**Comment by rainsuns** [comment]
https://github.com/photoprism/photoprism/issues/152

**Comment by lastzero** [comment]
While you are waiting for a visual timeline: You might want to try our `after:2006-01-02` and `before:2009-01-02` search filters to limit results by date.

In addition, you can search for `day`, `month` and `year` independently. To find birthday pics taken on January 22nd, enter `day:22 month:1` in the main search field. That's something a linear timeline can't do!

I agree, a custom timeline selector would be better for other use cases, like when you quickly want to browse your collection by time without knowing the exact date. For now, we provide the calendar for this.

A list of all filters can be found on https://docs.photoprism.org/user-guide/organize/search/

We know those docs need a little more work and better descriptions of what each filter does. Pull requests welcome!

**Comment by graciousgrey** [comment]
Will close it as it is a duplicate :)
