### ISSUE TITLE
Filter for camera does not work for videos

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#506]
**Current behaviour:** The camera filter does not work for videos
**Expected behaviour:** It must work.

Example json files are in internal/meta/testdata

**Comment by lastzero** [comment]
Fixed if Exiftool can detect camera make & model:

![video-camera](https://user-images.githubusercontent.com/301686/95013236-45e0d180-063f-11eb-9bb0-0ed7f9a80521.png)

Will be deployed for testing with our next Docker image, hopefully later today.

**Comment by lastzero** [comment]
New Docker images available for testing! Note that the password will be reset to its initial state when upgrading. Our Docker images have been optimized for common NAS models. You can now set a specific user and group using the UID and GID environment variables. Feedback welcome.
