### ISSUE TITLE
UX: Customize which actions (archive, set labels etc) can be done in fullscreen mode

### ISSUE THREAD

**Issue by Morl99** [photoprism/photoprism#508]
As a user I want to archive a photo while viewing it in the photo viewer, so that I can review a new batch of photos quickly. Let us assume I return from a trip and uploaded 200 photos to photoprism. I would like to quickly slide through them and decide:

1. Which Photos I like best (Favs)
2. Which Photos are trash, because they are blurry, have poor quality, lighting,...
3. The rest

Ideally this is achieved not only by adding the archive button to the top action bar in the viewer, but also by assigning a hotkey/keyboard shortcut. And please, no confirmation dialog for archiving a single picture, as this is easily reversible.

_While this is off-topic, I still need to note, that I really like this project, and that I just found it a few days ago looking for a replacement of the QNAP PhotoViewer software, that is really low on usability. I like the clean design, the good performance, and how easy it was to deploy it on Docker. Kudos!_

If you approve, I might be able to tackle this (at least the button in the top nav bar) as a first contribution. The API is all ready for this, and it seems to just be a frontend addition.

**Comment by savegame** [comment]
Yes, really need this feature! )

**Comment by graciousgrey** [comment]
Sounds like a good idea! We need to think about which actions in the photo viewer are most important because not all can be shown on smaller screens (mobile). Any opinions on this? Currently we are finalising our first stable release, so all improvements will be added afterwards :)

**Comment by Morl99** [comment]
Maybe it would make sense to make this customizable, and by default, only a sensitive number of actions is shown. If the instance owner could customize the available actions he could fine tune the usability targeted for his use case.

But I doubt, that this would be a good use of the time for the moment. My best bet would be to sort them according to priority, and display the ones that do not fit in a kind of hamburger menu.

**Comment by novodim** [comment]
here is the use case:

- given a huge photo/video collection
- in one pass user can tag all the photos/videos appropriately. shortcuts make the process faster. 
- get list of marked files to be able to process originals as needed

currently I mark photo/video as private and then get a list from database and process originals.

shortcuts for setting private, favorite flags for the image or video are really necessary.
the should be available in any view of the particular photo or video.
in general it would be good to be able to create any custom tag in photoprism and assign a custom shortcut for toggling the tag in the same way. and there should be some way to get a list of files with tag/flag set.

**Comment by graciousgrey** [comment]
@novodim workflow improvements will come after the stable release :) 
I guess we should open a separate ticket for keyboard shortcuts to collect all related requests there. 
In what format would prefer to have the list of files with a certain keyword or flag?

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: https://github.com/photoprism/photoprism/issues/1307
