### ISSUE TITLE
Update Russian translation

### ISSUE THREAD

**Issue by savegame** [photoprism/photoprism#512]
Just need update translation, I'll try do it later (in holidays) ) 
[Instructions](https://github.com/photoprism/photoprism/issues/229#issuecomment-578688326)

**Acceptance Criteria:**

**Update frontend translations**
 
- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/ru.po file with Poedit
- In the Poedit menu click "Catalogue" --> "Update from POT File" --> select the translations.pot file from /frontend/src/locales
- Now you can start proofreading and adding the missing translations
- Once your done save the changes in the ru.po file 
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Update backend translations**
- Run `make generate`
- Open the /assets/locales/ru/default.po file with Poedit
- In the Poedit menu click "Catalogue" --> "Update from POT File" --> select the messages.pot file from /assets/locales/
- Now you can start proofreading and adding the missing translations
- Once your done save the changes in the default.po file 

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by graciousgrey** [comment]
@savegame Yes, an update of the russian translation would be great :) We added the instructions on how to do translations to our developer guide: https://docs.photoprism.org/developer-guide/translations/
