### ISSUE TITLE
Update polish translation

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#515]
We have polish translations for our User Interface, but due to changes and added features not everything is translated yet.
The scope of this issue is to prove read the existing translations and add the missing ones.

**Acceptance Criteria:**

**Update frontend translations**
 

- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/pl.po file with Poedit
- In the Poedit menu click "Catalogue" --> "Update from POT File" --> select the translations.pot file from /frontend/src/locales
- Now you can start proofreading and adding the missing translations
- Once your done save the changes in the pl.po file 
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Update backend translations**
- Run `make generate`
- Open the /assets/locales/pl/default.po file with Poedit
- In the Poedit menu click "Catalogue" --> "Update from POT File" --> select the messages.pot file from /assets/locales/
- Now you can start proofreading and adding the missing translations
- Once your done save the changes in the default.po file 

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by wikiyu** [comment]
Work In Progress.
