### ISSUE TITLE
Add translation for a new language

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#519]
We already have translations for our User Interface in chinese, french, spanish, polish, dutch, russian and german. In case you want to add a translation for another language add a comment and we will create a ticket for this language :)

The scope of this issue is to add translations for a new language:

**Acceptance Criteria:**

**Add frontend translations**
 
- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/translations.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, save your translation as *.po file using the two-letter language locale as name
-  Add the new language in  /frontend/src/options/options.js
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Add backend translations**
- Run `make generate`
- Open the /assets/locales/messages.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, create a new directory (using the locale as name) and save your translation there as default.po

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by forgondolin** [comment]
I'll try brazilian portuguese

**Comment by MatheusMuriel** [comment]
Hello, you can create a specific issue for portuguese translation?

**Comment by graciousgrey** [comment]
For brazilian portugese we need to check whether our frontend can handle it (because it does not have a two letter code like pt but pt_BR). We will check tomorrow and keep you updated.
@forgondolin and @MatheusMuriel: do you think it makes sense to offer pt and pt_BR is there a huge difference?

**Comment by MatheusMuriel** [comment]
@graciousgrey Yeah, have a huge difference mainly in flowing text, but in isolated words the difference is small... 
But you can name the file with "br.po"

**Comment by forgondolin** [comment]
PT-BR speakers can understand the PT speakers, but in grammar, we have some big differences. The pronoums, the way we assemble words in a phrase. So yeah, I would recomend different choices for PT-BR and PT.

**Comment by MatheusMuriel** [comment]
@forgondolin Do you think these differences would be expressive in the context of this software?

**Comment by forgondolin** [comment]
@MatheusMuriel, maybe not, I mean, I think in Portugal, some words related to art like pictures, camera, art, have different main words that in Brazil, but thats not a HUUUUUGE problem.

**Comment by MatheusMuriel** [comment]
@forgondolin and @graciousgrey  What do you think of create a file "pt.po" and a "br.po"?

**Comment by forgondolin** [comment]
I think this could be a good idea. I think the most active portuguese speakers on internet are the brazilians, but there are a lot of people from Portugal, Angola, Timor East, and their portugese are slightly different

**Comment by MatheusMuriel** [comment]
@forgondolin So, for both of us we participate, what do you think of each one doing a part of the Brazilian Portuguese translation?

**Comment by forgondolin** [comment]
I think it will be a good idea

**Comment by graciousgrey** [comment]
@MatheusMuriel @forgondolin Thanks for your input!
We would rather not like to have a br.po file as br is the locale for another language. 
I currently see two options:
1) You both work on one pt.po (I could make a ticket for creating the translation and one for updating and you can share the work)
2) One of you works on pt.po and the other one on pt_br.po --> It might require a bit of time on our side to get the pt_br.po running in the frontend 

What would both of you prefer?

**Comment by graciousgrey** [comment]
@MatheusMuriel @forgondolin I added those tickets https://github.com/photoprism/photoprism/issues/530 and https://github.com/photoprism/photoprism/issues/529 just leave a comment in them if you want me to assign you :)

**Comment by forgondolin** [comment]
@graciousgrey, Hm, I'm thinking on how to make it works since br is used for another language. Like ` bz.po` ...

**Comment by graciousgrey** [comment]
@forgondolin Lets use pt_BR because this is the official locale and we will make those longer locales work :) This is the ticket for it https://github.com/photoprism/photoprism/issues/530

**Comment by forgondolin** [comment]
ok, We'll do that

**Comment by isabelirusso-dev** [comment]
@forgondolin I made the backend and the first part of frontend translation to brazilian portuguese, but there still is the rest of the frontend translation if you want to finish it 😄 

Happy Hacktoberfest 👾

**Comment by forgondolin** [comment]
Dont worry @isabelirusso-dev , go for it, you're doing a great job at this. I'm actually a little out of time too :/, unfortunately

"Drink all the booze hack all the things"

**Comment by shahzaibahmad3** [comment]
what about Hindi. I can try.

**Comment by graciousgrey** [comment]
@shahzaibahmad3 I created a ticket for Hindi: https://github.com/photoprism/photoprism/issues/54. If you leave a comment there I will assign it to you :)

**Comment by nlssn** [comment]
@graciousgrey Hi, could we adda a ticket for Swedish? :)

**Comment by graciousgrey** [comment]
@nlssn Here it is: https://github.com/photoprism/photoprism/issues/571. Just leave a comment there then I can assign you :)

**Comment by yudete** [comment]
I'd like to try Japanese.

**Comment by graciousgrey** [comment]
@yudete Great :)
 I created a ticket for you: https://github.com/photoprism/photoprism/issues/794
Just leave a comment there and I will assign you.

**Comment by Shamshala** [comment]
@graciousgrey May i ask you for a ticket for Czech? Thanks! :slightly_smiling_face:

**Comment by graciousgrey** [comment]
Sure :) @Shamshala just leave a comment here: https://github.com/photoprism/photoprism/issues/902 and I will assign you

**Comment by LucaDiba** [comment]
Hi! I can translate to Italian. 🙂

**Comment by graciousgrey** [comment]
@LucaDiba italian sounds great. Here is our documentation on how to do translations: https://docs.photoprism.org/developer-guide/translations/. Feel free to open a pull request or reach out in case you have any questions :)

**Comment by LucaDiba** [comment]
Thanks @graciousgrey! I have already translated the frontend and the backend following the documentation instructions. Should I wait the issue for Italian to be opened or I can submit a pull request without the issue?

**Comment by lastzero** [comment]
Just send the PR, that's fine. Thank you! 🤗

**Comment by Hrazhan** [comment]
I am currently working on adding Kurdish language translation. Can you please create a ticket and assign me?

**Comment by rosdyana** [comment]
Hi, I am currently working on Bahasa Indonesia translation. Could you please create a ticket and assign me?

**Comment by graciousgrey** [comment]
@rosdyana I just created the ticket, if you leave a comment there, I can assign you: https://github.com/photoprism/photoprism/issues/1689. Thanks a lot for working on this :)
