### ISSUE TITLE
UX / Improve context menu for folders, calendar and states

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#520]
In the context menu of the sections folders, calendar and states currently there is the option "remove". 
But there is no option to add photos to certain folders/calendar or state entries because those are populated automatically.  That's why we decided to replace the "remove" action with "archive" --> Archived photos do not appear in folders/calendar or states. If you restore them they will appear again in folders/calendar/states.

**Acceptance Criteria:**
* Replace the action remove with the action archive in the context menu of the following sections: Folders, Calendar, States (see screenshots)
* Make sure to also switch the icons

![calendar-1](https://user-images.githubusercontent.com/15210372/94682270-fb044880-0324-11eb-9091-53a5fc6f3531.png)
![Screenshot 2020-09-30 at 13 45 13](https://user-images.githubusercontent.com/15210372/94682282-fd66a280-0324-11eb-9c18-55209b9a7026.png)
![Screenshot 2020-09-30 at 13 46 26](https://user-images.githubusercontent.com/15210372/94682290-00fa2980-0325-11eb-86b7-1ded079d25df.png)

**Comment by HariniJeyaraman** [comment]
@graciousgrey Would love to work on this for Hacktoberfest 2020. Can you assign me this issue ?

**Comment by Morl99** [comment]
Hello @HariniJeyaraman, do you have any idea when you would like to tackle this? I would also be interested in brushing up my vue know-how, and this seems to be an easy task. If you - for some reason - no longer have any interest in fixing this, I would be willing to give it a try.

**Comment by HariniJeyaraman** [comment]
@Morl99 I'm new to the tech stack and am still learning and understanding the code. If you're already familiar with the workflow and the code, you can work on the issue.

**Comment by timschlechter** [comment]
I also started trying to get familiar with the codebase and tried if I could tackle this issue. 

Making the 'Archive' options visible can be done by removing the `!album &&` here I think: https://github.com/photoprism/photoprism/blob/develop/frontend/src/component/photo/clipboard.vue#L82

But to make the 'Remove from album' option visible/invisible, I think we're missing some sort of context to determine whether an album gets populated automatically or not. I currently see two options:
- pass this context a prop in the [routes](https://github.com/photoprism/photoprism/blob/develop/frontend/src/routes.js#L131)
- have some flag on an [Album](https://github.com/photoprism/photoprism/blob/develop/frontend/src/model/album.js) which determines if the album gets populated automatically or not

I'm really new to this project, so I have no idea what would be the best approach. Any thoughts?
