### ISSUE TITLE
Add spanish backend translation

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#528]
**Add backend translations**

* Run make generate
* Open the /assets/locales/messages.pot file with Poedit
* In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
* When done, create a new directory (using the locale as name) and save your translation there as default.po

**Comment by MatheusMuriel** [comment]
Assing this issue for @isabelirusso-dev

**Comment by isabelirusso-dev** [comment]
You can assing this to me 😄
