### ISSUE TITLE
Add brazilian portuguese transalation

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#530]
The scope of this issue is to add translations for brazilian portuguese:

**Acceptance Criteria:**

**Add frontend translations**
 
- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/translations.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, save your translation as *.po file using the two-letter language locale (pt_BR) as name
-  Add the new language in  /frontend/src/options/options.js
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Add backend translations**
- Run `make generate`
- Open the /assets/locales/messages.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, create a new directory (using the locale (pt_BR) as name) and save your translation there as default.po

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by MatheusMuriel** [comment]
Csn you assing this issue for @isabelirusso-dev she is going do it

**Comment by isabelirusso-dev** [comment]
You can assign it to me 😄 I think I can translate from the ID 1 to 213 and Kaleb Alves from the 214 to 426, is that ok? The IDs appear once you activate the option "Mostrar ID na cadeia" of Poedit on "Visualizar".

**Comment by isabelirusso-dev** [comment]
Also, may you add the tag "hacktoberfest" on the repository? After some updates now the only valid PRs will be the ones in repositories with this tag https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by graciousgrey** [comment]
@isabelirusso-dev Thanks for the hint :) I added the hacktoberfest2020 topic to the repo yesterday and I will mark the pull requests with hacktoberfest-accepted.

**Comment by graciousgrey** [comment]
Reopened because second part of frontend translation is still missing
