### ISSUE TITLE
File Type / Support for Google Pixel (HVC1: H.265/HEVC) videos

### ISSUE THREAD

**Issue by theorician** [photoprism/photoprism#533]
Currently videos shot on Google Pixel line phones don't play. The audio plays fine but the screen remains black. The format is identified as HVC1, which is H.265/HEVC. 

I can provide sample videos or further metadata dumps if needed.

Thanks for running a great project.

**Comment by theorician** [comment]
I just saw that there is this PR: https://github.com/photoprism/photoprism/pull/513 which adds playback support for Safari. I'm running Firefox, but perhaps there's a similar problem there. Happy to have you close this issue if you suspect that's the case.

**Comment by lastzero** [comment]
We want to implement transcoding for this, but after a stable release. I doubt Firefox supports H. 265.

**Comment by blmhemu** [comment]
@lastzero Here is the relevant info : https://caniuse.com/?search=hevc
Firefox does not support hevc in my exp. I tried streaming hevc video using jellyfin and it always transcoded it.

**Comment by swingstate** [comment]
Adding to this. Apple also uses HVC1/H.265 to shoot in 4K / 60FPS. From a workflow perspective, it would be nice to have a single import step. Meaning I have all my recently shoot HEIC / HVC1 Photos and videos in one folder and can upload them all at once, without having to deal with any converter tools prior. HEIC import works well so far. 

Please threat the support for HVC1 transcoding and/or conversion to H.264 as a feature request.
