### ISSUE TITLE
/photoprism directory clobbers  /photoprism/assets and /photoprism/bin on volume mount

### ISSUE THREAD

**Issue by mylinttrap** [photoprism/photoprism#542]
Original issue: mount of nfs to individual volume mount points creates stale file handle. 
switched to smb/cifs: mount of cifs to individual import and original volume mounts in /photoprism causes a move error per the following: https://github.com/photoprism/photoprism/issues/136, https://github.com/photoprism/photoprism/issues/130
(I am using the latest from docker hub. deployed three days ago).

Read that putting the mount as /photoprism for the import and original... aka mount /my/disk/path/photoprism:/photoprism
would prevent the import error when two volume mounts are trying to transfer inside the photoprism container. 

This makes it so that the /photoprism/assets and /photoprism/bin directories are clobbered by the mount of /my/disk/path/photoprism:/photoprism. 

further. to copy these assets out of container and into my local would mean that any futher updates from photoprism would be clobbered by my local mounting. 

Please fix your file system IO so that it works in a POSIX standard manner.

**Comment by mylinttrap** [comment]
INFO[2020-10-10T13:14:33Z] metadata: failed parsing gps coordinates in IMG_0086.JPG (exif)
INFO[2020-10-10T13:14:33Z] mediafile: IMG_0086.JPG was taken at 2009-11-06 03:49:39 +0000 UTC (meta)
INFO[2020-10-10T13:14:33Z] import: moving main jpg file Masters/2015/12/28/20151228-154250/IMG_0086.JPG to 2009/11/20091106_034939_C9C0EC83.jpg
ERRO[2020-10-10T13:14:33Z] open /photoprism/originals/2009/11/20091106_034939_C9C0EC83.jpg: permission denied
ERRO[2020-10-10T13:14:33Z] import: failed moving file to 2009/11/20091106_034939_C9C0EC83.jpg (open /photoprism/originals/2009/11/20091106_034939_C9C0EC83.jpg: permission denied)
ERRO[2020-10-10T13:14:33Z] import: mediafile: 20091106_034939_C9C0EC83.jpg not found in 2009/11/20091106_034939_C9C0EC83.jpg


did some more research. a little confused by this: 

root@photoprism:/photoprism# touch  import/l
touch: cannot touch 'import/l': Permission denied

**Comment by mylinttrap** [comment]
I'm a little perplexed. This app is great, but has been a puzzle to get running. It needs a goldi locks sort of zone. 
I have the mysql db on an iscsi because both db options wont work on nfs (not that it should, but other projects work). I suspect the app does something with locks to prevent two clients from editing the same data and nfs/smb mounts cause issue because of the underlying file system io over a network. So i had to research iscsi to get a disk into my VM that is running the docker container of photoprism. That took 3 months of picking up and putting down. 

Then, the iscsi mount broke. (my fault) and corrupted the heck out of the mysql database. wow. this was actually pretty cool to experience because it was just interesting. So I load the photoprism back up after giving it a new blank DB wondering how long the re-import would take. SUPRISE! it was easy and took a long time but pulled a bunch of data from the sidecar yml files. Super cool. But made me think on why the DB is so picky about read/write locks if this system can just load that up from a yml file. 

also noticed that the photoprism user is in the container, but the app is ran as root. so i dont know how photoprism user is being utilized in the container. Tried to SU as photoprism with touch and it also fails. The SMB mount points are under the same UID/GUID as photoprism. so this should not be an issue. 

I can mount things back with nfs volume... but I dont like the idea of stale file system mounts possibly showing up at random. it's a file system known for NFS though not a photoprism issue. :(

**Comment by mylinttrap** [comment]
after reading earlier to all this... I was thinking that photoprism does not support cifs... because of https://docs.photoprism.org/getting-started/faq/ noting the nfs volume mount example. 

but the other links in this thread appear to be using smb/cifs... So I dont know

**Comment by lastzero** [comment]
Not much time right now, just some quick thoughts:

1. Never run any type of database on a network mount. Always use local storage or connect to a remote db that uses local storage.
2. Experiment with UID, GID and UMASK if you experience file / folder permission issues.

**Comment by lastzero** [comment]
There might still be issues with SIGINT and SIGTERM handling, see https://github.com/photoprism/photoprism/pull/543

**Comment by lastzero** [comment]
Oh, and don't mound `/photoprism`, just `/photoprism/originals`! Assets like the TensorFlow models are part of the docker image and will be missing if you mound an external volume.

Maybe we have to make that more clean in our docs... Feedback welcome :+1:

**Comment by mylinttrap** [comment]
I know this was recently closed, but i just found it in my open tabs. 

A possible solution would be to have a /photoprism/app and /photoprism/data folders so that /photoprism/data/originals and photoprism/data/import could exist on the same mount point in container and thereby avoid the failure to transfer from one nfs/smb mount to the other. 

/photoprism/app would contain the above mentioned clobbered files that are needed to run.

**Comment by lastzero** [comment]
Makes sense! Thanks for the hint 👍

**Comment by lastzero** [comment]
Note that you can freely change all path names using environment variables (see docs). Need to be careful with changing defaults as this may break existing installations.
