### ISSUE TITLE
Handling of files indexed during network outages

### ISSUE THREAD

**Issue by vb0** [photoprism/photoprism#546]
As indexing large libraries can take days or even more there can be times when (briefly or not so briefly) there would be no internet access, so whatever magic would be done via places.photoprism.pro will fail. Would these be re-indexed next time (I presume not, as they are already in the db)? I guess they'll be included in the next rescan and all the data will be (by chance) correctly inserted for them but as it'll take again quite long maybe the network will briefly fail then as well and some other items will get just partly indexed.

**Comment by lastzero** [comment]
Is the server currently down or do you ask in general?

**Comment by vb0** [comment]
There is no problem with the server, just with the local network/internet connection. Also many DSL connections are changing the IP daily (or even if they have a longer time now still many routers are configured to force a reconnect at 3AM or similar so there is no outage for the normal use during the day). Bottom line some pictures might get incomplete metadata (I'm not sure how much) if the indexing is done during such outages (again, there can be many more network problems, especially that large libraries take a lot of time). It would be good to have some way to re-index the files (or maybe even to retry at next rescan, even if it is partial).

**Comment by lastzero** [comment]
In general you should stop indexing and wait until everything is back online as there is no point in indexing twice. We have to perform additional tests to see what happens in various failure scenarios, also eg when files and directories become unavailable.

**Comment by lastzero** [comment]
Requests will be repeated 3 times until they fail.

**Comment by vb0** [comment]
> In general you should stop indexing and wait until everything is back online as there is no point in indexing twice.

I'm not sure how you'd do that. Again, indexing takes days. Somewhere in the night the connection goes away for a short while and it's already back well before morning. Some items ended up with incomplete metadata.  

* will these items be skipped at the next partial scan? Probably yes I guess  
* is the any chance for this to happen again for other items if doing again a very long/complete scan? Again probably yes I guess.  

This might make it very tricky to scan large libraries if you don't have an absolutely flawless internet connection (even if you have absolutely no local problem with RAM, storage, the stability of the system, etc.).

**Comment by lastzero** [comment]
Fair enough. We should set a flag if a photo needs re-indexing e.g. because geodata is incomplete.

**Comment by barrystaes** [comment]
I noticed when importing (Library > Copy) a folder, that the (otherwise fully server-side?) import stops when i close the webinterface. 

I expected this to happen fully server-side. Perhaps same logic/cause?

**Comment by lastzero** [comment]
@barrystaes Importing and indexing shouldn't stop when you close the browser window. Can you confirm this with our latest release? Fixed a few indexing issues, but not related to what you describe.
