### ISSUE TITLE
WebDAV: Manually trigger Nextcloud sync

### ISSUE THREAD

**Issue by SuberSeb** [photoprism/photoprism#551]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%247%20Funded-%2300A156.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/551)

I have a question. How can I manually trigger Nextcloud sync?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $7.00)

- $7.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by lastzero** [comment]
Sync automatically runs every 15 Minutes:

https://github.com/photoprism/photoprism/blob/414a3a840ad56a821e2bdbd8cc9dd2cb72c86a1d/internal/config/config.go#L249

If you experience issues and need to debug, it's probably easiest to set `PHOTOPRISM_WAKEUP_INTERVAL` to 60 (1 Minute) or less, see https://docs.photoprism.org/getting-started/config-options/

We might add a manual sync button to the UI in a later, wasn't a top priority so far.

**Comment by vhodh** [comment]
Just wanted to add my support for this. First thing I looked for when setting up nextcloud sync was a button to trigger it. I'm fine with how it is currently, but it would likely alleviate some confusion on new setups.

**Comment by lastzero** [comment]
You can trigger syncing manually by going to *Settings* > *Sync*, opening the *Remote Sync* dialog (clickable icon in the account list), and then pressing *Save* (make sure the switch in the upper right corner is set to "Enabled"): 

![trigger-sync](https://user-images.githubusercontent.com/301686/160294670-086a11ca-051f-4bec-a8fa-78ae85e018b2.png)

Related API code:

![code](https://user-images.githubusercontent.com/301686/160292646-926831ef-e939-4cb7-ba75-2d33ea618d0a.png)

**Comment by wuast94** [comment]
Can we reopen this issue? i enabled a new sync and nothing happens, so the api code you mentioned seems not to trigger a sync.

**Comment by graciousgrey** [comment]
The sync starts after the configured PHOTOPRISM_WAKEUP_INTERVAL, which is 15 minutes by default. I just tested it with our own installations. It works as expected. You may want to check what you have configured as the wakeup interval. If you have further questions, feel free to use [Github Discussions](https://github.com/photoprism/photoprism/discussions) to get help :)
