### ISSUE TITLE
Nextcloud sync don't work

### ISSUE THREAD

**Issue by SuberSeb** [photoprism/photoprism#552]
I have set up sync with my nextcloud instance. First synchronization was fine, protoprism downloaded all photos. But after that nothing happened, new photos don't sync. In logs I have "Downloading from nextcloud", no errors.

`yesterday at 21:59 time="2020-10-16T21:59:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 22:14 time="2020-10-16T22:14:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 22:29 time="2020-10-16T22:29:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 22:44 time="2020-10-16T22:44:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 22:59 time="2020-10-16T22:59:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 23:14 time="2020-10-16T23:14:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 23:29 time="2020-10-16T23:29:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 23:44 time="2020-10-16T23:44:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"
yesterday at 23:59 time="2020-10-16T23:59:01+03:00" level=info msg="sync-worker: downloading from Nextcloud"`

**Comment by lastzero** [comment]
Probably a config issue either in PhotoPrism or Nextcloud. Wrong directory? Permissions? User? Can the host name be resolved? Firewall?

**Comment by SuberSeb** [comment]
First sync works fine. But after that, when I added new photos to Nextcloud, Photoprism don't sync them. I see in logs that sync-worker executing every 15 mins but no new photos synced.

**Comment by lastzero** [comment]
Sounds like the number of files is limited? You say there are more files, but they are not synced? How many files were synced? Is it possible to store your files in a nested folder structure instead of all files in one directory for testing?

**Comment by SuberSeb** [comment]
All my files in directories like this:
2020 - 10 - Photo.jpg, so there are about 20 files in each folder.
In first sync there are about 3000 files were synced. After that I made a couple of photos (1-3) but they won't synced.

**Comment by lastzero** [comment]
How many files in total? If you're a developer and know how to do it, you might want to check the files_sync table in the database... it should a contain the list of files to be synced and their status.

**Comment by SuberSeb** [comment]
Ok, I will check that. Now I'm using alternative way of sync - storage folder points on photos folder in Nextcloud. With cron I run indexing every 20 mins. Seems working fine for me.

**Comment by lastzero** [comment]
If files are already indexed, they won't be downloaded (based on sha1 hash).

**Comment by SuberSeb** [comment]
No new files downloaded using Nextcloud sync. I made a couple of new photos, but they don't sync in photoprism.

**Comment by lastzero** [comment]
Thought you share the storage folder with Nextcloud? The photos should be indexed already in this case?

**Comment by SuberSeb** [comment]
PhotoPrism don't grab new photos from Nextcloud.

**Comment by lastzero** [comment]
> Now I'm using alternative way of sync - storage folder points on photos folder in Nextcloud. With cron I run indexing every 20 mins. Seems working fine for me.

Do you run a separate PhotoPrism instance for testing WebDAV sync? Both at the same time won't work.

**Comment by SuberSeb** [comment]
> Do you run a separate PhotoPrism instance for testing WebDAV sync? Both at the same time won't work.

Of course not, you don't get it. Sync just not work. No issues with instances, configs, etc. New photos from nextcloud are not uploaded in PhotoPrism.

**Comment by lastzero** [comment]
Just wanted to make sure the file is not already indexed directly as PhotoPrism won't download existing files and also won't overwrite existing files, even if they are not already indexed. So if you use the same folder for PhotoPrism and Nextcloud, you should expect issues (I understand it also didn't work before).

Since I'm out of ideas, it's probably best you check the `files_sync` database table... maybe it contains helpful information.

**Comment by SuberSeb** [comment]
> Just wanted to make sure the file is not already indexed directly as PhotoPrism won't download existing files and also won't overwrite existing files, even if they are not already indexed.
No, this files are new, so they can't be already indexed.
> So if you use the same folder for PhotoPrism and Nextcloud, you should expect issues (I understand it also didn't work before).
This works fine, only sync feature doesn't work.

**Comment by nimjor** [comment]
@lastzero I seem to have a similar issue but the PhotoPrism Library > Errors tab shows the following:

> sync: ReadStream /nextcloud-dev/Photos/21-05-25 18-34-29 9553.jpg: Authorize https://(nextcloud-baseUrl)/remote.php/dav/files/admin/: 401

I say it's similar because when I set up the Nextcloud server sync settings in PhotoPrism, it always successfully syncs the first few photos, but then stops syncing any new photos and throws this error.  It makes no sense to me because 401 = unauthorized.  It's not like anything changes between the first few photos syncing successfully and the errors starting.  How would it suddenly become unauthorized?  I have tried also generating an API key for my Nextcloud user and using that instead in the sync settings, but no dice.

I'd be happy to help troubleshoot this however I can, if you can provide some guidance.

**Comment by lastzero** [comment]
Sounds like permissions issues, maybe depending on the specific files or folders you're trying to sync. Is that possible?

**Comment by jac2424** [comment]
Same issue here as well, initial sync works fine with Nextcloud WedDav but any newly added files don't show unless I delete and re-create the PhotPrism DB.

**Comment by ozls** [comment]
I have the exact same issue. It worked fine in the past, but I recently made two big changes: I have migrated my setup to full docker (Nextcloud was previously installed bare-metal) and I have changed my OS from ARM 32 bits to an ARM 64bits one.

**Comment by zakafx** [comment]
I am glad that I found this because I am having the exact same issue. One day PP decided to stop downloading new photos from my NC instance. Getting the same auth error above. PP will download new photos after I delete and recreate the service, but nothing else after.

**Comment by zakafx** [comment]
when disabling and reenabling WebDAV/nextcloud sync within PP, here is the log output.

2022-11-19 07:51:25 ERRO webdav: 'ReadStream /Photos/2022/11/20221118_122859.jpg: Authorize https://awebsite.com/remote.php/dav/files/user/: 401'

2022-11-19 07:51:25 INFO sync: downloading from Cloud

2022-11-19 07:51:20 INFO account saved

If I delete the WebDAV/nextcloud service and reconfigure, PP will connect to my Nextcloud instance, scan everything that already exists (a lot of skipping), and then sees the new files and downloads them. It does not download anything after and reverts to the above output.

**Comment by nimjor** [comment]
@zakafx I haven’t tried setting up the sync in a while, but the way I worked around this was by mounting my SMB share that Nextcloud is using for storage onto the docker host that’s running photoprism, and then in my docker-compose file I specified that location for index. Not sure if that would work for your situation but it’s worked flawlessly for me.

**Comment by zakafx** [comment]
@nimjor thanks for the reply, i will try that out later today and see what happens

**Comment by lastzero** [comment]
Strange that it works the first time. Do you have the background worker disabled or changed the default interval in your config?

Also check out the bug report for owncloud, which apparently requires special authentication handling. If Nextcloud works the first time, it's probably not related though.

**Comment by zakafx** [comment]
> Strange that it works the first time. Do you have the background worker disabled or changed the default interval in your config?
> 
> Also check out the bug report for owncloud, which apparently requires special authentication handling. If Nextcloud works the first time, it's probably not related though.

No, I have left the config default other than minor things like mapped volumes and the author name. I did see that owncloud reference as well but yeah, works once then quits after.

**Comment by zakafx** [comment]
> @zakafx I haven’t tried setting up the sync in a while, but the way I worked around this was by mounting my SMB share that Nextcloud is using for storage onto the docker host that’s running photoprism, and then in my docker-compose file I specified that location for index. Not sure if that would work for your situation but it’s worked flawlessly for me.

@nimjor This worked! Doesn't resolve the actual issue, but it's a good workaround. As well, with this workaround, i don't have to have photoprism copying over the same files over to it's originals folder from nextcloud, so I save space with this. Thank you for your suggestion.

**Comment by nimjor** [comment]
Exactly why I ended up going that route and haven’t looked back :)
