### ISSUE TITLE
[Synology NAS] photo counter in PhotoPrism - 3x more than in import - no idea what is happening here

### ISSUE THREAD

**Issue by flirtysanchez** [photoprism/photoprism#555]
Hi!

**First of all:** Thank you very much for this great product. I have been looking for a modern photo app with AI.

I have been testing PhotoPrism on my Synology NAS for a few days. I used the Docker Compose file with the customizations from the following article  (https://github.com/photoprism/photoprism/issues/468) in conjunction with MariaDB.

I have copied exactly 20 images into my import folder:

![DSM_NAS_folder_structur](https://user-images.githubusercontent.com/68855073/96564566-9acd4a80-12c3-11eb-9f58-10c33c9f6de3.png)

When I use indexing in PhotoPrism UI, PhotoPrism shows me 74 photos and I have no idea what is happening here:

![photoprism_number_of_photos](https://user-images.githubusercontent.com/68855073/96564786-df58e600-12c3-11eb-8886-f9826fec8797.png)

Here are my Docker settings:
![Docker_Settings_1](https://user-images.githubusercontent.com/68855073/96564996-17602900-12c4-11eb-82b1-c020a46c4a70.png)
![Docker_Settings_2](https://user-images.githubusercontent.com/68855073/96565004-1a5b1980-12c4-11eb-819b-fac026567f03.png)

**Comment by lastzero** [comment]
Indexing won't IMPORT from your import folder, it will INDEX originals in the originals folder.

**Comment by flirtysanchez** [comment]
Ok, but the originals folder is and was empty!

**Comment by lastzero** [comment]
How can there be photos in your index then?

**Comment by lastzero** [comment]
See #560

**Comment by flirtysanchez** [comment]
I put 20 pictures into my IMPORT folder and thats it (look at my first screenshot). I've done a fresh install of photoprism and mariadb a few times and all the folder were empty before the reinstall.

**Comment by lastzero** [comment]
OK, what pictures do you see? Do they look familiar? What files do you see in the files tab of the edit dialog?

**Comment by flirtysanchez** [comment]
Here is a screenshot. In the folder REVIEW there are the same photos in different resolutions:

![photoprism_double](https://user-images.githubusercontent.com/68855073/96767840-5d5ce000-13dd-11eb-96d5-8c563401eec4.png)

**Comment by lastzero** [comment]
74 - 61 = 13

If you approve the 61 photos in review, all 74 will be visible. It seems like you somehow indexed your thumbnail / storage folder? Maybe delete all directories and start with a fresh installation as described in our docs.

**Comment by flirtysanchez** [comment]
Ok. I'll try a fresh install. Where should I copy my test photos? IMPORT or ORIGINAL?

**Comment by lastzero** [comment]
Originals

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/faq/

**Comment by flirtysanchez** [comment]
Hi! Me again. I've done a fresh reinstall and copied 9 photos to the ORIGINALS Folder. I installed the docker container with 

`PHOTOPRISM_READONLY: "true"`

Now the 9 photos are 14:

![image](https://user-images.githubusercontent.com/68855073/96882350-82099400-147f-11eb-9c4f-16234c690d54.png)

**Comment by lastzero** [comment]
Can you check the folder and file name in the edit dialog (files tab) please?

**Comment by flirtysanchez** [comment]
Sorry for the late response! Do you mean this settings:

![photo_1](https://user-images.githubusercontent.com/68855073/97981184-2ec60880-1dd2-11eb-8c62-8afad04df5db.png)
![photo_2](https://user-images.githubusercontent.com/68855073/97981186-31286280-1dd2-11eb-900a-b390a236d7a1.png)

**Comment by endthestart** [comment]
Just chiming in here because I had a similar problem with the Synology. It ended up being that the media indexing setting of the Synology creates a hidden `@eaDir` wherever media files are stored. In there it creates high quality thumbnails that Photoprism won't detect as duplicates. I ended up having to move my photo collection off of my Synology for the import. And eventually I removed the Moments app and disabled most of the indexing on the Synology since I only want it to store files. However I believe (but I am not certain) that this creates issues for indexing when shares are mounted on macs, etc.

@flirtysanchez, you should see if you can find those hidden folders by SSHing into the NAS or if you have a share mounted somewhere else you can type `ls -la` to see them. 

It might be worthwhile to add logic to Photoprism to ignore those directories.

**Comment by lastzero** [comment]
@endthestart You can add `@eaDir` to a `.ppignore` file in your originals folder.
