### ISSUE TITLE
Automatically limit the number of workers when using SQLite

### ISSUE THREAD

**Issue by CorneliousJD** [photoprism/photoprism#558]
This seems to happen either when adding new files to the originals folder, or when adding to via import.

The database ends up locked and not all files end up being indeded.
When importing it seems all the files get MOVED to the original folder successfully, but not all are successfully indexed.

This is happening with a small subset of sample images that I have (96 images). 
I can seemingly recreate this all the time. 

If I force a full re-scan it will get some more indexed, but sometimes I have to force a re-scan a few times to get it to be fully updated where the photos count in the UI matches my amount of originals.

Not sure what's happening or causing this. I'm running the photoprism/photoprism docker container.
I am attempting to use this as a replacement for Google Photos to get away from uploading my images to their servers. 

Please let me know if I can test/contribute more to this case.

**Comment by lastzero** [comment]
We had this issue before, but it disappeared. Does this happen with SQLite or MariaDB/MySQL?

**Comment by CorneliousJD** [comment]
I actually just read this issue. 
https://github.com/photoprism/photoprism/issues/392

I was using SQLite at first when this issue happened becuase the unRAID template for this docker container didn't actually mention anything a bout MySQL as an option at all.

for what it's worth i have dual Xeon E5-2650 v2's, total of 16 cores, 32 threads @ 2.60 GHz
128GB of RAM.

Fixed my issues by just swapping my MySQL (MariaDB).
SO MUCH FASTER too. Wow! :) 

I've asked the maintainer of the unRAID template for this container to add in the option for using MySQL to the template as well.

**Comment by lastzero** [comment]
Excellent! We should automatically limit the number of workers when using SQLite as it doesn't scale well, at least not without optimizations. Thanks for reporting this.

Users who want to stick with SQLite may manually limit the number of workers via `PHOTOPRISM_WORKERS`, see https://docs.photoprism.org/getting-started/config-options/

**Comment by CorneliousJD** [comment]
> Excellent! We should automatically limit the number of workers when using SQLite as it doesn't scale well, at least not without optimizations. Thanks for reporting this.
> 
> Users who want to stick with SQLite may manually limit the number of workers via `PHOTOPRISM_WORKERS`, see https://docs.photoprism.org/getting-started/config-options/

Thanks, I'll pass the workers info along to them too to be included in the template, since it's not included it defaults to 0 which I assume is no-limit.

What would a suitable limit be for using SQLite?

**Comment by lastzero** [comment]
The hard limit is https://golang.org/pkg/runtime/#NumCPU in case there is no - or a higher - `PHOTOPRISM_WORKERS` limit.

I guess setting `PHOTOPRISM_WORKERS` to 8 should work in most cases. Needs to be tested. Our demo was built with 6 cores and I've never seen an error. May depend on storage performance and cpu architecture as well.
