### ISSUE TITLE
Count of Originals is more than actual photo count on Windows

### ISSUE THREAD

**Issue by kcbimonte** [photoprism/photoprism#564]
So I just finished indexing my 63k photo and video collection and I wanted to add more metadata to the actual photo and have it auto-appear on PhotoPrism. When I clocked the library button, I accidentally revealed the Originals tab where it said I had around 73k photos. That is a difference of 10k photos between what photoprism reports and what Windows reports. I'm thinking this must be some sort of bug. For reference, the photos tab (while currently re-indexing) reports approximately 60,800, and the videos tab report 1,900.

Since I am using MySQL, I ran a quick query to see if I could find any duplicates by looking at file_names, and I found exactly 1. Not exactly the 10k difference that I am looking for. For reference, the database also contains the 73K number in the files table.

**Comment by lastzero** [comment]
These are not photos, these are files including JPEGs that were generated for non-JPEG files and videos.

**Comment by kcbimonte** [comment]
Thanks for your prompt response, that makes more sense.
