### ISSUE TITLE
Unable to share albums or images

### ISSUE THREAD

**Issue by accountForIssues** [photoprism/photoprism#566]
First off, thanks for creating and maintaining this amazing project.

I'm running Photoprism using docker-compose on a VPS. The main web server is Caddy that reverse proxies requests to Photoprism using it's own subdomain.

The image upload, info extraction, maps, etc. seem to work fine but I'm unable to find ways to share album or images. The 'share' option is checked in settings but I there is no share option on any context menu so I don't even know how to check what's wrong.

Photoprism version: 201021-33d36611-Linux-x86_64

Maybe someone can help me or direct me ?

Thanks in advance.

**Comment by lastzero** [comment]
Does it work for you in our demo as shown here? The share dialog should open when you press the purple button in the context menu:

![demo](https://user-images.githubusercontent.com/301686/97107054-ae165680-16c5-11eb-870a-bbbe4b8dd500.png)

**Note:** Our database schema may change when new development versions are published, so it's possible you need to start with a fresh database (or manually delete the related sharing tables) when upgrading from an older version.

**Comment by accountForIssues** [comment]
Oh I feel so stupid now. I should have known to check the demo instance as well.

Turns out uBlock Origin was blocking that share button on both the demo and my instance. I've added my site onto the whitelist so it's working now. However, I wonder why it was blocked as I just use the default settings.

I think it was blocking it assuming it was one of the common social network sharing buttons. (The setting causing this was 'Parse and enforce cosmetic filters').

Can something be done in the code to avoid this ? I mean Nextcloud has a similar share button which is not blocked by uBlock Origin.

Thanks for the quick reply :+1: 

You can close the issue.

**Comment by lastzero** [comment]
Renaming it in our code might help. Not a perfect solution that may introduce bugs as well. 

Please let us know if you figure something out! I'm using AdGuard without any issues.
