### ISSUE TITLE
Metadata: Backup in YAML Files

### ISSUE THREAD

**Issue by croontje** [photoprism/photoprism#567]
I am moving my photo collection into photoprism, but I was wondering if it is possible to store YAML files next to the original?
That way my sidecar files stay together with the photo.

And second question, if I archive a photo it does not seem to be written to the YAML file like other tags. Is it possible to write an "Archive" tag/label/... to the YAML file, because it would be a pain to archive everything again if I even need to rebuild my library...

**As user, I want all metadata to be backed up in yaml format, so that I have a backup that is independent from the database.**

**Acceptance Criteria:**

- [x] Store albums in yaml file

Added a follow up issue for the archive flag, see #912

**Comment by lastzero** [comment]
You can set the sidecar path using the `PHOTOPRISM_SIDECAR_PATH` environment variable, see https://docs.photoprism.org/getting-started/config-options/

We stopped storing them next to the orginals as some users prefer to mount their library read-only. It's also easer to delete sidecar files - should this be needed - if they are in a separate directory. Note that you can't configure different directories for JSON & YAML files.

Storing the "archive" flag in YAML backup files probably requires some changes as archived photos / videos are usually skipped when indexing. So when you lost your index, re-indexing might lead to inconsistent data: Only the first file might be indexed and related files - like RAW or XMP - might be ignored.

FYI: The archive flag is implemented using the `DeletedAt` colum in the files and photos tables (it is `NULL` by default).

**Comment by croontje** [comment]
I understand why you don't save them next to the photo files anymore :)
I was checking some more a minute ago and I noticed that also the Albums are not stored in the YAML files. Wouldn't this be interesting to store in the YAML file too? 
The main reason I am checking this is because imagine for some reason something happens to the DB, it would be nice to have all the YAML files to recreate the DB.

**Comment by lastzero** [comment]
You're right: We want to use YAML backups for albums as well, but it's not implemented yet.
