### ISSUE TITLE
Translations: Add Swedish 🇸🇪

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#571]
The scope of this issue is to add translations for swedish:

**Acceptance Criteria:**

**Add frontend translations**
 
- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/translations.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, save your translation as *.po file using the two-letter language locale (sv) as name
-  Add the new language in  /frontend/src/options/options.js
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Add backend translations**
- Run `make generate`
- Open the /assets/locales/messages.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, create a new directory (using the locale (sv) as name) and save your translation there as default.po

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by nlssn** [comment]
@graciousgrey Thanks for creating this issue. You can go ahead and assign me. 

Just a note: your comment mentions
"brazilian portugese", but this issue is for swedish.

**Comment by graciousgrey** [comment]
@nlssn Now its swedish instead of brazilian portuguese --> I copy pasted the description from another ticket and forgot to change this part :)

**Comment by jean-louis67** [comment]
Hello
In the French version, a few titles are missing a space. I saw it also in Spanish version:
![image](https://user-images.githubusercontent.com/65403912/98779928-ac9e9b00-23f4-11eb-9da1-09db991c8e18.png)![image](https://user-images.githubusercontent.com/65403912/98779959-b7593000-23f4-11eb-8a10-c0603ee7389e.png)
What would happen with more than 1000 photos?
Ok, it's just an aesthetic detail.
