### ISSUE TITLE
Feature Request - Share individaul photos with share links (not WebDAV)

### ISSUE THREAD

**Issue by CorneliousJD** [photoprism/photoprism#574]
Now that you can share albums with the /s/secret/album URL, I would love to share individual photos sometimes with people. 
I really don't like the idea of needing to upload to WebDAV (partly becuase it never works right or if it ever does it's terribly slow)

I'd like to be able to select one photo, and have it generate a share link that I can share just like I can with calendar months/albums, etc.

Thank you for the consideration.

**Comment by lastzero** [comment]
You can already share image thumbnail URLs via browser context menu (right click, copy URL). They won't contain any metadata though.

**Comment by graciousgrey** [comment]
See: https://github.com/photoprism/photoprism/issues/466
