### ISSUE TITLE
Removing picture from album does not update the album cover

### ISSUE THREAD

**Issue by aureooms** [photoprism/photoprism#575]
If one removes from an album the picture used by its cover, the cover does not get updated to use a different picture from the album. Bug or feature?

**Comment by graciousgrey** [comment]
That's because it is cached. It will disappear later.

**Comment by aureooms** [comment]
Ok. At what level is it cached? If I open a shared album with deleted cover picture in an incognito/private tab with disabled cache the deleted picture still shows up as a cover. This happens even if the shared link is created after the deletion. There does not seem to be a way to manually change the cover picture. I could recreate the album but that defeats the purpose... I create the album first by selecting all pictures in some time range, then I delete the ones I do not want. If one of the is the cover picture then the cover picture stays there. This is bad if that picture is not meant to be shared for whatever reason.

**Comment by lastzero** [comment]
On the server in memory. Expires after one hour or so. Cache should be cleared if album items change, but wasn't a top priority so far.

**Comment by aureooms** [comment]
> On the server in memory. Expires after one hour or so. Cache should be cleared if album items change, but wasn't a top priority so far.

It has been more than two weeks than the cover picture was removed from the album but it still shows up in a shared link open in incognito/private tab with disabled cache. I am using NGINX as proxy with the following configuration:

```
proxy_redirect off;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $http_host;

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_set_header X-Forwarded-Proto $scheme;

client_max_body_size 30M;
proxy_buffering off;
location / {
    auth_basic 'PLEASE IDENTIFY';
    auth_basic_user_file /etc/nginx/photoprism.example.tld/.htpasswd;
    proxy_pass http://localhost:2342;
}

location ~ ^/(?:s|static|api)/.* { # Disable authentication for shares.
    auth_basic off;
    proxy_pass http://localhost:2342;
}
```

I get a `200 OK` response for the `tile_500` request:

```
Request URL: https://photoprism.example.tld/api/v1/albums/<blurb>/t/public/tile_500
Request Method: GET
Status Code: 200 OK
Remote Address: <IP ADDRESS>:443
Referrer Policy: no-referrer-when-downgrade
Accept-Ranges: bytes
Connection: keep-alive
Content-Length: 112458
Content-Type: image/jpeg
Date: Mon, 02 Nov 2020 06:07:08 GMT
Last-Modified: Mon, 12 Oct 2020 01:23:45 GMT
Server: nginx
Accept: image/avif,image/webp,image/apng,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: photoprism.example.tld
Referer: https://photoprism.example.tld/s/<blurb>
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
```

**Comment by lastzero** [comment]
Here is the code for you to review: https://github.com/photoprism/photoprism/blob/develop/internal/api/thumbs.go#L204

**Comment by lastzero** [comment]
@aureooms Could you take a look at our code? If you think this is a bug, I might be able to fix it next week. In any case, it should work to clear the cache when an album changes - just wasn't a priority so far. Last week was crazy busy again, so I didn't get to much.

**Comment by aureooms** [comment]
Also the cover picture does not update when I restart the server. I am 100% sure the picture used for the cover is not part of the album (it was included at album creation but was removed later). I will look at the code.

**Comment by lastzero** [comment]
Maybe there is an issue with the db query then: We keep the database row when a photo was removed, maybe the "hidden" flag is ignored?

**Comment by aureooms** [comment]
Here is what I think is happening:
  - Deleting a picture from an album sets `hidden` to true: https://github.com/photoprism/photoprism/blob/7131db0cfebe39815d6d02f2aa57f5a631027cf7/internal/entity/album.go#L357
  - Getting the album cover does not take the value of `hidden` into account: https://github.com/photoprism/photoprism/blob/7131db0cfebe39815d6d02f2aa57f5a631027cf7/internal/query/albums.go#L81

**Comment by aureooms** [comment]
> Maybe there is an issue with the db query then: We keep the database row when a photo was removed, maybe the "hidden" flag is ignored?

Yes!

**Comment by aureooms** [comment]
Can you point to where hidden is used in order to filter which photos to load in the UI? I was not able to find it.

**Comment by lpnueg4** [comment]
Why not add a button to set album cover ? so this problem is gone

**Comment by lastzero** [comment]
@lpnueg4 It's on our todo, just didn't have time for this yet. Showing a default cover is a must, selecting a cover is optional. See #604.

**Comment by lastzero** [comment]
Starting a new Docker build for testing soon.

**Comment by aureooms** [comment]
The changeset in 668025c looks good to me. Clearing the cache when the album cover query response changes would be sufficient. Clearing on each update is safe.
