### ISSUE TITLE
Indexer: Some photos are not stacked that should be stacked

### ISSUE THREAD

**Issue by CorneliousJD** [photoprism/photoprism#576]
I have a very new install, stacking is enabled, but it's not currently stacking portrait mode photos when I index them.

#560 was something I submitted about another stacking issue and perhaps the changes made from that messed up this type of stacking? 

Here are the portrait mode files and their sidecar files.

The portraid mode one with the blurred backgound called COVER should ideally end up being the primary photo, with the other version stacked.

![image](https://user-images.githubusercontent.com/724777/97739348-1c885980-1ab6-11eb-9b08-ae9affb2c695.png)

EDIT: Perhaps they never stacked? I thought they did with my initial testing but I had wiped/realoaded PhotoPrism so many times now I can't recall with any certainty that they ever did before, but I *thought* they did. 

If they never did, is it possible to make images with names like this stack with COVER taking the displayed photo (top) slot on the stack?

**Comment by lastzero** [comment]
Don't think PhotoPrism would stack them based on the file names, they are too different. They might be stacked based on the exact same time & location or the same unique image id / document id. Did you check their metadata if any of those match?

**Comment by CorneliousJD** [comment]
> Don't think PhotoPrism would stack them based on the file names, they are too different. They might be stacked based on the exact same time & location or the same unique image id / document id. Did you check their metadata if any of those match?

Yep the .json sidecar file with the metadata shows everything as identical except the Title (as it shows the filenames I already listed) -- Everyhting else is exactly the same. Screenshot below.

I know each cellphone probably names portrait mode photos differently, but perhaps it would be a good enhancement at some point to stack these, as the portrait mode photos are quite popular nowadays, and having the one labeled as cover being the main with the original as a stacked file I think would work very nicely and mimic what Google Photos does when it shows you a portrait mode image.

![image](https://user-images.githubusercontent.com/724777/97875099-ec280180-1ce7-11eb-9f46-3d9b73ab23b8.png)

**Comment by lastzero** [comment]
Did you enable stacking after the files were already indexed or before your started indexing for the first time?

**Comment by CorneliousJD** [comment]
> Did you enable stacking after the files were already indexed or before your started indexing for the first time?

Nope, what I had done because I was finally ready to roll forward with a "production" install for home, I wiped the Photoprism mysql database and docker containers and started fresh, only thing I disabled was quality review, meaning stacking was enabled from the start. and indexed these originals (which came from a Google Takeout export).

**Comment by lastzero** [comment]
Can you provide examples for testing so that we can debug this further?

Either attach them to this issue or email to: hello@photoprism.org

**Comment by CorneliousJD** [comment]
Enjoy some cat photos, for some reason on my brand new Pixel 5 I can't get it to actually store the original and portrait mode photo separately for some reason, weird, but my old Pixe 3 XL stored them separately like this -- they do not stack though and I believe they should, with COVER being the one displayed on top.

![PXL_20200929_154625690 PORTRAIT-02 ORIGINAL](https://user-images.githubusercontent.com/724777/98624180-43773480-22db-11eb-9dcc-160e09a45181.jpg)
![PXL_20200929_154625690 PORTRAIT-01 COVER](https://user-images.githubusercontent.com/724777/98624182-440fcb00-22db-11eb-8e60-7b37fdc9ead4.jpg)

**Comment by lastzero** [comment]
Works for me...

<img width="661" alt="Screenshot 2020-11-22 at 03 28 02" src="https://user-images.githubusercontent.com/301686/99892196-c05ac480-2c72-11eb-9c2c-ab051cd4a69c.png">

**Comment by lastzero** [comment]
Seems this was a "timing" issue when all files happen to be indexed at the same time in different go routines. Identical photos will be merged now when indexing is done (if it didn't happen before).

**Comment by lastzero** [comment]
I'll take a look at some other issues and then start a new build for testing!
