### ISSUE TITLE
Metadata date issue when the filename is the same  

### ISSUE THREAD

**Issue by mszel42** [photoprism/photoprism#579]
I managed to hit an edge case: we use a shared upload dir with my wife so sometimes she has the same filename with a different extension:
https://imgur.com/a/EibVJ91

So if you have xxxx.jpg and xxxx.heic then photoprism will process all metadata properly BUT the date, displaying a potentially older file among the newer ones. 

This can be bypassed by renaming the files, but the issue might worth to be investigated anyway. 

Thanks.

**Comment by graciousgrey** [comment]
Thank you for reporting. We will have a look at that within the next weeks.

**Comment by lastzero** [comment]
Our indexer assumes that files sharing the same *base name* belong together, like when there is a JPEG and RAW. That makes sense in most cases. Changing this, or adding exceptions, would be risky at this stage.

Wouldn't it be easier to use separate sub folders for your uploads instead?

**Comment by mszel42** [comment]
I think that perfectly makes sense! I will set up an upload/auto renaming cron or use separate upload folders as you suggested.
