### ISSUE TITLE
Feature Request: Random Photos

### ISSUE THREAD

**Issue by gerroon** [photoprism/photoprism#580]
Hi

It would be very nice if there was a section on the left menu for opening/listing random photos based on some set options like 
number of photos to show.

Basically the random photos tab lists some random photos from the database. And there could be a refresh button a the top to change the randomized listing.

thanks

**Comment by alexislefebvre** [comment]
See also #153

**Comment by graciousgrey** [comment]
I close this as showing random photos is part of #153
