### ISSUE TITLE
Commas in folder names cause autogenerated "folder albums" to come up empty.

### ISSUE THREAD

**Issue by theorician** [photoprism/photoprism#581]
To reproduce: When importing a folder with a comma in the name, the photos are imported fine. However, the auto-generated album that shows up Sidebar > Albums > Folders shows no photos.

This is running the latest photoprism docker container.

**Comment by lastzero** [comment]
Thanks for reporting this! Bug fixing session is planned for next week :+1:

**Comment by lastzero** [comment]
Just started a new Docker build for testing. Available soon.

**Comment by lastzero** [comment]
Closing this since no negative test reports came in.
