### ISSUE TITLE
Upgrade to mariaDB

### ISSUE THREAD

**Issue by danielo515** [photoprism/photoprism#582]
Hello.
I was wondering if there is an easy way to migrate from SQLite to a MariaDB instance?
I just started using photoprism to test it out, but now I have many photos indexed, so I think I will better use a MariaDB instance instead. Is there a way to migrate the data from one DB to another?

Regards

**Comment by danielo515** [comment]
I just rebuilt the entire database, it didn't took that long.
Feel free to close the issue

**Comment by danielo515** [comment]
duplicate of #495

**Comment by lastzero** [comment]
Sorry for the wait, glad you found the existing issue... apparently there is a Python script that may convert the data. Not sure how well it works for data types and indexes though. Feedback welcome!
