### ISSUE TITLE
Share all albums or view-only user?

### ISSUE THREAD

**Issue by v-marinkov** [photoprism/photoprism#586]
Hi,
I use Photoprism to build a family repository of photos and would like family members to be able to freely browse all albums without needing to bookmark individual links to shared albums.

Is there a "share all albums" option? Can it be implemented with a link like the single album sharing is?

Even better: can we have a "view-only" user(s) who can solely browse photos, videos and albums but has no access to Library, Settings or archiving?

Any of these would be amazing!
Thanks a lot

**Comment by lastzero** [comment]
Multi-user support is on our todo, there's an existing issue for this. It's be possible to run two PhotoPrism instances in the meantime. Settings and any others features may be disabled in the second instance, so that you can only browse pictures. Not idea, but should work.

**Comment by graciousgrey** [comment]
I close this, as it duplicates https://github.com/photoprism/photoprism/issues/98
