### ISSUE TITLE
Bug? I have two folders (in album's folder view) with no content

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#587]
The folder appears black and there is no content although I can see the pics of that folder in library's folder mode and they are also shown in calendar and places view.

Did I miss something or is this a bug? If so, how can I report for details?

cheers

**Comment by lastzero** [comment]
Might be a bug. Can you add a screenshot? What are the folder names (any special characters in it)?

**Comment by totti4ever** [comment]
This is how it looks like:
<img src="https://user-images.githubusercontent.com/49901208/98521637-fd3aba80-2273-11eb-827e-3f0d073abce3.png" height=150 />

Folder names are both having a comma in them - this might be the reason? I'd say that is the difference to the ones without a problem

**Comment by lastzero** [comment]
Yes. Guess it's because our API can search for multiple values by separating them with a comma like `folder:a,b`. Might need to quote the name like `folder:"a,b"`.

**Comment by totti4ever** [comment]
I'm not talking about search (although there should be the same effect). I clicked on Almbums --> Folders and the folders with commas in their path are empty.
I cannot quote anything there, I guess this has to be done somewhere in the code (when pictures are assigned to folders or so)?

**Comment by lastzero** [comment]
I know you're not talking about search, the server API is the same for all views though. Needs to be fixed in code somewhere.

**Comment by lastzero** [comment]
Just started a new Docker build for testing. Available soon.

**Comment by lastzero** [comment]
Closing this since no negative test reports came in.
