### ISSUE TITLE
Difference in count of photos

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#588]
I have a photo count of 894 stated at _Photos_ and 45 at _Review_, are the latter part of the former? Additionally a count of 57 videos is shown. Library  --> Original says  1054.

Then in the database I have 951 rows in the `photos` table

And running `find` (inside the container) against the _original_ folder, it finds 870 jpg files and 53 movies.

How do these numbers belong together or where would I get more insight why they differ?
And why is the path in the files details of every video ending on jpg, therefore showing the preview?

**Comment by lastzero** [comment]
Short videos < 4s are shown as live photos, so probably 4 videos are this short? Photos includes those in review, but not in archive. Not sure why there are additional rows in the database if you only have 923 files. Maybe there are hidden files? Also files can be stacked, but then it would be less photos than files. Impossible to know exactly from where I sit.

**Comment by lastzero** [comment]
See #564 and #560

**Comment by totti4ever** [comment]
Okay, I could dig a bit deeper. What I don't understand is that I have a couple of duplicates, ending on `.~1~` and so on (coming from `mv` operations). Some of them can be found in the `files` table, other cannot be found there. Permissions are the same. Those having own entries are shown in the library view as distinct files, linked to the same photo, which seems right.

How can I get more details on why others are not shown? Please understand I am quite picky; I just want to make sure all files are considered before using photoprism as single point of photo view! :-)
