### ISSUE TITLE
Search for subject with colon

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#589]
Hey, thanks to #490 I can now search for the content of the subject tag, that's great!

BUT I have come to no proper solution on how to use it. I want to use it to tag faces. So far I figured out two options:
1. Tag is _Name_
2. Tag is _face:Name_

Problem with `1.` is that this also leads to search results where e.g. the _Name_ is part of the folder and therefore the fallback title of many pictures.
Problem with `2.` is that I cannot search for strings with a colon, i.e. `face:Name` leads to an invalid request. I guess this is by design as this is meant to be used only for the standard tags like label and so on?  
What would be a good syntax then for my personal added tag face? `face-Name` `face.Name`? Any suggestions or other ideas how I can reach my goal to tag certain faces using the subject and search for them without having results from non-face properties?

**Comment by lastzero** [comment]
Try quotes as described in https://github.com/photoprism/photoprism/issues/587#issuecomment-723901930

**Comment by lastzero** [comment]
If you use a comma like `foo,bar`, it will search for `foo` and/or `bar`.

**Comment by totti4ever** [comment]
It is still a `400 Invalid request` response, tried it with single and double quotes

**Comment by lastzero** [comment]
Guess colons are not supported right now, would need special handling / escaping in our query parser. Can you use any other character?

**Comment by graciousgrey** [comment]
@totti4ever did you find a character that works?

**Comment by totti4ever** [comment]
Wow, indeed not that easy!

What is NOT working:
* `#`
* `()`
* `=`
* `:` (as discussed)

What actually would work:
* `->`  
so it could look like `face(Name)`


Not really sweet, but would work at least...
quite hard to tell my wife how to use it though :-D

**Comment by graciousgrey** [comment]
What about simply using faceName?
