### ISSUE TITLE
Create acceptance test suite

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#59]
**As a frontend developer, I want to write acceptance tests using JavaScript so that I don't have to learn Go and can test independently.**

Acceptance Criteria:
- [x] Compare test libraries using a decision matrix before starting to implement
- [x] Discuss the results of your comparison on the mailing list
- [x] Implement a few example tests for `/photos`
- [x] Tests must be easy to execute in a local development environment
- [x] Tests must be written in standard JavaScript (not CoffeeScript or TypeScript)
- [x] It must be possible to execute single tests
- [x] The full test suite must also be able to run on the command line (for Travis CI)
- [x] Add documentation to our wiki / developer guide

---

Potential test libraries and services (feel free to add more):
- https://devexpress.github.io/testcafe/
- https://codecept.io/
- https://funcunit.com/
- http://nightwatchjs.org/
- https://www.browserstack.com/ (free for open-source)

How to compare:
  - Easy to learn? How much time does it take to write a test?
  - How popular is it (stars on GitHub etc)? What do others say about it?
  - Is the library stable oder still beta/under development?
  - Are the tests stable? How does the lib make sure the UI is ready for testing? Timeouts?
  - What dependencies does it have?
  - How is the performance? Can you quickly run tests?
  - Browser compatibility?

See also #58 Improve test coverage.

**Comment by lastzero** [comment]
See https://www.philosophicalhacker.com/post/integration-tests-in-go/ and 
https://medium.com/@povilasve/go-advanced-tips-tricks-a872503ac859.

Probably best to do it like that:

> When you have some slowly running tests, it gets annoying to wait for all the tests to complete, especially when you want to know right away whether the build runs. The solution to this problem is to move slowly running tests to *_integration_test.go files and add build tag in the beginning of the file. For example:
>
> // +build integration
>
> This way go test won’t include tests, which have build tags.
> In order to run all the tests you have to specify build tag in go test:
> 
> go test -tags=integration

**Comment by lastzero** [comment]
We just discussed acceptance testing and figured that doing it with JS probably makes more sense, so the frontend developers are able to write tests without learning Go.

**Comment by lastzero** [comment]
Potential test libraries (feel free to add more):
- https://devexpress.github.io/testcafe/
- https://codecept.io/
- https://funcunit.com/

**We need to compare those options using a decision matrix before starting to work on a test suite.**

**Comment by or29544** [comment]
I have experience with [Jest](https://jestjs.io/) but I guess it doesn't matter much. We picked jest at work because there we use react and jest is able to make html snapshots of the rendered components based on a given state - and so you can compare the render with what you want. Kinda like a behavior test purely in code, without actually running a browser.

**Comment by lastzero** [comment]
@or29544 Seems like people also use it with VueJS
- https://vue-test-utils.vuejs.org/guides/testing-single-file-components-with-jest.html
- https://github.com/vuejs/vue-jest

Would be interesting to know what other Vuetify-based projects and Vuetify itself use. Can you do some research?

**Comment by or29544** [comment]
Sure, on it. Testing the actual render fully in code without relying on a browser is great. Also saves a lot of time since it doesn't run anything in background basically.

**Comment by lastzero** [comment]
Guess we need both in practice, so that we don't deploy a broken UI that only renders without a browser.

**Comment by lastzero** [comment]
I just had a look at [Mozilla's Coral Project](https://github.com/coralproject/talk) (interesting solution for comments). 

They use [Nightwatch.js](http://nightwatchjs.org/) (8,751 ⭐️) together with [BrowserStack](https://www.browserstack.com/) (free for open-source) to perform UI acceptance tests.

[CodeceptJS](https://github.com/Codeception/CodeceptJS) is slightly less popular in comparison (1,962 ⭐️).

**Comment by graciousgrey** [comment]
We decided to use TestCafe. Why ? --> see https://github.com/photoprism/photoprism/wiki/Tests
