### ISSUE TITLE
Allow for read-only access to source folders

### ISSUE THREAD

**Issue by binaryvisions** [photoprism/photoprism#592]
I think it's really important to provide an option for photographers to have their libraries be read-only to PhotoPrism. 

My primary use case - and one that I've talked to some fellow photographers about who agree with me - is to have a convenient and fast way to browse content on a remote device, and then to download copies if I want them. Flexibility and speed in browsing photos is paramount.

What I don't ever want, is for these photo packages to ever touch my source folders; I would expect that I could provide read-only access and have the software be fully functional. I don't want anything generated by an external software package to modify my carefully-managed and curated source folders.

For the arguments against read-only, which I've read in issues here and in your docs:
- Generating JPGs is expensive: sure, but it's my choice whether to incur that expense.
- JPGs aren't backed up: why not? They can be stored on a mounted filesystem folder outside the container and backed up.
- RAW files may not be accessible forever: that's, again, not your choice or your decision to make. It's mine. Dumping thousands of files into my original folders because of your feelings on RAW files isn't appropriate.
- It's hard to map files to each other: aren't you already doing this with thumbnails? In any event, it seems like you could hash the RAW files or use a collection of metadata to get a correlation.

Note that I am also experimenting with "PhotoStructure" which handles files in the way I was hoping - read only. PhotoPrism looks to have a lot more options for displaying and organizing files, though, so I was hoping to give it a shot. But 95% of my library is RAW and I'm not interested in creating 100k JPG files inside my original source folders.

Just some thoughts!

**Comment by lastzero** [comment]
Your original media files won't be deleted, modified, or moved. If you still want to enable the read-only mode, you can do so by setting PHOTOPRISM_READONLY to "true". It will disable all features that require write permissions, like importing files via Web upload. You may additionally want to mount the originals folder with :ro flag so that Docker blocks write operations.

See https://docs.photoprism.org/getting-started/config-options/ for a list of all config options.

**Comment by binaryvisions** [comment]
Sorry, maybe I wasn't clear with the issue.

As I said, virtually my entire library is in RAW.

https://docs.photoprism.org/user-guide/settings/library/#read-only-mode

Setting PhotoPrism to read-only mode essentially makes it useless for photographers, because the RAW conversion doesn't happen. I don't know any photographer who shoots RAW but also has a full library of JPG files, and equally so, I don't know anyone that wants photo applications like this one to be auto-generating thousands of files and storing them in their source folders.

**Comment by lastzero** [comment]
Sidecar files and thumbnails will only be stored in a sub-folder of your originals directory if no other folder was set in the configuration. Do you use our Docker Compose config template? See https://dl.photoprism.org/docker/docker-compose.yml

**Comment by lastzero** [comment]
Thanks for the documentation link! This seems outdated as JPEGs are now stored in the storage path and not next to your originals anymore.

**Comment by lastzero** [comment]
Updated our docs.

**Comment by binaryvisions** [comment]
Thanks! I will give PhotoPrism a shot now that I know I can have full functionality without modifying my source directories.

**Comment by lastzero** [comment]
Let us know when you notice any issues with read only mode! Creating full-res JPEGs and high-quality thumbs will require a significant amount of storage, make sure there is enough space left before you start indexing.
