### ISSUE TITLE
Several files pointing to the same photo_id

### ISSUE THREAD

**Issue by danielo515** [photoprism/photoprism#593]
Take a look at this screenshot:

![Screenshot 2020-11-10 at 21 05 13](https://user-images.githubusercontent.com/2270425/98727789-cad6ad80-2398-11eb-81ec-c98ae682e6cb.png)

As you can see, there are several files with different file_hash pointing to the same photo with the same photo_id and photo_uid.

If you want to check if there are duplicates on your DB run this:

```sql
SELECT photo_id, file_hash, count(photo_id) 
FROM files 
WHERE file_type IN (0x6A7067)  -- This is JPEG
GROUP BY photo_id order by 3 DESC;
```

On this video you can see how navigating the galery for those files feels:

![Screen Recording 2020-11-10 at 21 10 42](https://user-images.githubusercontent.com/2270425/98728255-87307380-2399-11eb-8a9b-bd67ab21c4ae.gif)

You may find some duplicates

**Comment by lastzero** [comment]
Did you disable "Stack Sequences" in settings? Likely due to your file names, I see lots of brackets.

**Comment by danielo515** [comment]
> Did you disable "Stack Sequences" in settings?

No I didn't. What are they for?

> Likely due to your file names, I see lots of brackets.

Yeah, those are from the old days, when I was almost a teen and I had no idea about file naming (and some of my family members made it even worse)

**Comment by danielo515** [comment]
> Stack sequences: Files with sequential names like 'IMG_1234 (2)' or 'IMG_1234 copy 2' belong to the same photo

Oh, I see. That's why some of my photos had a "sequence" icon. I just disabled it, I'll see what happens. Should I re-index or something?

By the way, in case they were, how would I see them in sequence? I didn't found a way to see the sequence. I though I should just click the sequence icon but nothing happened.

**Comment by graciousgrey** [comment]
@danielo515 If you click the sequence icon on the image, it should open in fullscreen. If you then use the arrows you can switch between the images of the sequence in fullscreen mode.
What exactly happens when you click on the sequence icon? From what view did you try?

**Comment by danielo515** [comment]
When I clicked it open the sequence like any other photo. I didn't tried to move with the arrows, but that is a bit not intuitive, there is nothing indicating that I can do that. I can't check again because I just disabled the option and rebuilt my library

**Comment by graciousgrey** [comment]
We know there is room for improvement. Any ideas how to improve the UX for that? 
We plan to provide an option to manually merge similar images to stacks (#28 ), maybe we find a better solution for browsing through sequences then. 
Can we close this issue?

**Comment by lastzero** [comment]
In there any specific bug or new feature request? If yes, the title should be changed. If no, we should close this issue.
