### ISSUE TITLE
Several different files points to the same photo_id

### ISSUE THREAD

**Issue by danielo515** [photoprism/photoprism#594]
Take a look at this screenshot:

![Screenshot 2020-11-10 at 21 05 13](https://user-images.githubusercontent.com/2270425/98727789-cad6ad80-2398-11eb-81ec-c98ae682e6cb.png)

As you can see, there are several files with different file_hash pointing to the same photo with the same photo_id and photo_uid.

If you want to check if there are duplicates on your DB run this:

```sql
SELECT photo_id, file_hash, count(photo_id) 
FROM files 
WHERE file_type IN (0x6A7067)  -- This is JPEG
GROUP BY photo_id order by 3 DESC;
```

You may find some duplicates

On this video you can see how navigating the galery for those files feels:

![Screen Recording 2020-11-10 at 21 10 42](https://user-images.githubusercontent.com/2270425/98728255-87307380-2399-11eb-8a9b-bd67ab21c4ae.gif)

**Comment by lastzero** [comment]
Duplicate of #593?

**Comment by danielo515** [comment]
Yes, sorry, github was making funny of me telling me that it failed creating it while it was actually created.
