### ISSUE TITLE
Missing spaces between the title and and the count

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#595]
In the French version, a few titles are missing a space. I saw it also in Spanish version:
![image](https://user-images.githubusercontent.com/65403912/98780536-35b5d200-23f5-11eb-96d2-8f14a3db00e0.png)  ![image](https://user-images.githubusercontent.com/65403912/98780552-3babb300-23f5-11eb-8e7b-98aeed2fdbb6.png)

What would happen with more than 1000 photos?
Ok, it's just an aesthetic detail!

**Comment by graciousgrey** [comment]
This should not happen. Which browser do you use? Did you zoom in?
I cannot reproduce this with chrome, firefox or safari.

**Comment by jean-louis67** [comment]
Damn, I feel so dumb.
You are obviously right. It's related to the zoom that I was not aware of.
