### ISSUE TITLE
Possibility to change the "Monochrome" indicator

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#596]
Among more than 7000 photos in my library, only 3 are classified Monochrome, while several dozen others should have been.
Probably during scanning there were traces of color introduced
It would be useful to have the possibility to change this indicator in the edit view of the parameters of a photo, like this for example:
![image](https://user-images.githubusercontent.com/65403912/98796924-3c9c0f00-240c-11eb-9df4-a409a2ff7a2a.png)

**Comment by lastzero** [comment]
Can you provide us with example files? We detect this automatically based on the color information in the picture... wondering why PhotoPrism finds colors when there are none :thinking:

**Comment by lastzero** [comment]
We have it almost working with your examples, except for a sepia picture which is recognized as being golden in the upper right corner:

![sepia](https://user-images.githubusercontent.com/301686/102477689-f6fee180-405c-11eb-907f-2871a46667ad.png)

In that case, the image technically has mixed colors, even if it's gold & brown, which are similar. Think I'll leave it at that for now, but we can revisit sepia pictures later. You should not have to mark those manually as monochrome!

**Comment by jean-louis67** [comment]
Thank you very much for all of your efforts and your explanations!
Are these modifications available? Is it necessary to reindex all the photos to benefit from it?

**Comment by lastzero** [comment]
Yes, you should re-index - also because we've added a new database column to improve sort by similarity. Let us know if the new chroma threshold works for you. Increased it from 0 to 1, so that sepia pictures may show up in monochrome as well. However, that also leads to search results which have few colors but are NOT monochrome. So it's a tradeoff. Not sure what is best.

**Comment by grafst** [comment]
If you really wanted to go overboard with the accuracy you might wan't to train a classifier that estimates if a picture *should* have colors. If it is sepia but should have color i.e. picture of an apple, then you would classify it as "monochrome". Contrary, if it's a picture from a desert, then it shouldn't have  different colors than brown and therefore should be classified "not monochrome".
Just an idea, probably too much work...

**Comment by graciousgrey** [comment]
I will close this as we got no more complaints :)
