### ISSUE TITLE
Allow indexed items to become imported after the albums are created.

### ISSUE THREAD

**Issue by Darkwolf1515** [photoprism/photoprism#597]
Its a bit weird, but it would be nice if you could have indexed items merge into the standard db format after the albums are made (since that seems to be the only reason to index) Would be nice to have it all go into the year folders, as opposed to those oddball named folders.

**Comment by lastzero** [comment]
What do you mean with "oddball named folders"? Moments? Albums? The file browser?

**Comment by Darkwolf1515** [comment]
Basically I just meant Id rather have all my folders be the 2020, 2019. ect as named and indexed by the program, rather than having those the extra folders that share the album names.
