### ISSUE TITLE
Error while indexing files

### ISSUE THREAD

**Issue by speedyflipper** [photoprism/photoprism#599]
I noticed that close to 6k photos were not indexing. So I ran "docker exec photoprism photoprism index" and I got the error "Error 1093: You can't specify target table 'photos' for update in FROM clause"

I am using a MySQL database

**Comment by lastzero** [comment]
What version?

**Comment by lastzero** [comment]
Might be an issue with the SQL syntax or the database tables could be not be created automatically for any reason. Some more info is needed before debugging this further.

**Comment by speedyflipper** [comment]
It is installed via Docker. The version I'm running is 201021-33d36611-Linux-x86_64

It is definitely a SQL syntax error related to MySQL. [https://bugs.mysql.com/bug.php?id=6980](https://bugs.mysql.com/bug.php?id=6980)

**Comment by lastzero** [comment]
What is the MySQL version?

**Comment by speedyflipper** [comment]
8.0.22

**Comment by lastzero** [comment]
In fact, the [MySQL manual](https://dev.mysql.com/doc/refman/8.0/en/update.html) says:

> You cannot update a table and select directly from the same table in a subquery.

Just wow.

I'll push my changes for testing, but we need to verify how this affects large photo libraries. I'm confident this ugly workaround comes with a performance impact, just not sure if significant. The (much better) [MariaDB manual](https://mariadb.com/kb/en/derived-table-merge-optimization/) warns "executing a subquery like this is very inefficient".

**Comment by lastzero** [comment]
Note: I'm going to take a look as some more issues before I start a new build for testing.

**Comment by lastzero** [comment]
Closing this since no negative test reports came in.

**Comment by lastzero** [comment]
@speedyflipper Just updated our database queries. Let us know if these cause any issues with MySQL.

**Comment by speedyflipper** [comment]
I was able to run the command to completion with no errors.

Thank you

**Comment by lastzero** [comment]
Excellent, thanks for testing!
