### ISSUE TITLE
Concurrent map read/write crash on import

### ISSUE THREAD

**Issue by williewillus** [photoprism/photoprism#600]
Set up with docker-compose and default options (besides changing uid and adding volumes), started an import, then crash. 

Log: https://gist.github.com/williewillus/07d6f5930a45cda9e6364095abc3fa63

**Comment by lastzero** [comment]
Looks like an issue in `go-exif/v3` at first sight:

```
fatal error: concurrent map read and map write

goroutine 1285 [running]:
runtime.throw(0x10c8c7f, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc02adb3e80 sp=0xc02adb3e50 pc=0x442712
runtime.mapaccess2(0xf83c80, 0xc02b12d110, 0xc02adb3ef6, 0x3, 0xc02b400bf8)
	/usr/local/go/src/runtime/map.go:469 +0x25b fp=0xc02adb3ec0 sp=0xc02adb3e80 pc=0x41b71b
github.com/dsoprea/go-exif/v3.(*TagIndex).Get(0xc0002f50f0, 0xc0198f0420, 0xc02b518769, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20200807075213-089aa48c91e6/tags.go:252 +0xe5 fp=0xc02adb3f18 sp=0xc02adb3ec0 pc=0xb08805
github.com/dsoprea/go-exif/v3.(*IfdEnumerate).parseTag(0xc02adb44f0, 0xc0198f0420, 0x7, 0xc02b518420, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20200807075213-089aa48c91e6/ifd_enumerate.go:249 +0x3a5 fp=0xc02adb4018 sp=0xc02adb3f18 pc=0xafdfe5
github.com/dsoprea/go-exif/v3.(*IfdEnumerate).parseIfd(0xc02adb44f0, 0xc0198f0420, 0xc02b518420, 0x0, 0x0, 0x0, 0x0, 0xc02b524de0, 0x3, 0x4, ...)
	/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20200807075213-089aa48c91e6/ifd_enumerate.go:434 +0x25e fp=0xc02adb41b8 sp=0xc02adb4018 pc=0xaff53e
github.com/dsoprea/go-exif/v3.(*IfdEnumerate).Collect(0xc02adb44f0, 0xc000000008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20200807075213-089aa48c91e6/ifd_enumerate.go:1342 +0xb29 fp=0xc02adb4488 sp=0xc02adb41b8 pc=0xb05e49
github.com/dsoprea/go-exif/v3.Collect(0xc000130600, 0xc0002f50f0, 0xc02adde006, 0x4ed4, 0x4ed4, 0x125ef80, 0x22271d0, 0x8, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/dsoprea/go-exif/v3@v3.0.0-20200807075213-089aa48c91e6/exif.go:230 +0x26c fp=0xc02adb4548 sp=0xc02adb4488 pc=0xafcd6c
github.com/photoprism/photoprism/internal/meta.(*Data).Exif(0xc02ae19250, 0xc01bc77920, 0x55, 0x109c434, 0x3, 0x0, 0x0)
	/go/src/github.com/photoprism/photoprism/internal/meta/exif.go:78 +0x2f3 fp=0xc02adb49b0 sp=0xc02adb4548 pc=0xb71433
```

Didn't upgrade to the latest  `go-exif` version for some reason, but can't remember why... was this already fixed, @dsoprea?

**Comment by lastzero** [comment]
@williewillus Can you provide us with an example file, so that we can debug this further? You may attach it to this issue, or send via email to hello@photoprism.org. Looks like unexpected data, maybe not standards compliant.

**Comment by dsoprea** [comment]
@lastzero I see a concurrency issue. What makes you think unexpected data?

It's worth mentioning that go-exif obviously doesn't manage concurrency. Make sure that we're serializing the requests from the PP side.

**Comment by lastzero** [comment]
Thanks, that's good to know! Using a mutex should be enough? Might slow indexing down a bit.

**Comment by dsoprea** [comment]
Correct. It would be a necessary cost. As go-exif doesn't not have nor need any parallel processes, locking is somewhat well out of scope.

That said, this is no heavy feat of engineering, so I might just add it. It looks like it's just a thing with a race on the caching. There aren't many situations where parallel processes would get tripped up, so for me to serialize it here might just completely solve it.

**Comment by lastzero** [comment]
Just pushed to master. New Docker build for testing available soon.

**Comment by dsoprea** [comment]
Fixed in go-exif, as well.

**Comment by dsoprea** [comment]
Sorry for the delay.

**Comment by lastzero** [comment]
No worries, we're super busy too... fixed all obvious issues this weekend. Hope that's it, so that we can tag a release soon!

**Comment by lastzero** [comment]
Closing this since no negative test reports came in.

**Comment by williewillus** [comment]
Hi, sorry for the lack of updates on this, but I just pulled and tried importing again and so far things are looking good. Thanks for the fix!
