### ISSUE TITLE
Several thumbnails size created for each image

### ISSUE THREAD

**Issue by alensfor** [photoprism/photoprism#601]
Hello
Not really an issue but more a question or a request for support.
I initiated indexing of folders with the parameters below.

```
PHOTOPRISM_SIDECAR_JSON | true
PHOTOPRISM_SIDECAR_YAML | true
PHOTOPRISM_THUMB_FILTER | lanczos
PHOTOPRISM_THUMB_UNCACHED | false
PHOTOPRISM_THUMB_SIZE | 800
PHOTOPRISM_THUMB_SIZE_UNCACHED | 7680
PHOTOPRISM_JPEG_SIZE | 7680
PHOTOPRISM_JPEG_QUALITY | 85
PHOTOPRISM_DARKTABLE_PRESETS | false

```
I didn't start photoprism from command line with custom parameters since the quality details attributes are in my container environment. 
I am surprised to see a big amount files by thumbnails and noticed I have multiple thumbnails files create for each single HD photo.
![image](https://user-images.githubusercontent.com/67714495/99044028-66317380-258f-11eb-9fb8-037a3a3ec2eb.png)

I tried to go through documentation but couldn't find a reference about why the indexing engine would create these multiple thumbnails.
Thanks a lot for this great product and for the help !

**Comment by lastzero** [comment]
See https://docs.photoprism.org/user-guide/settings/thumbnails/

**Comment by alensfor** [comment]
Thank you Lastzero. I've been reading this page but was understanding I should expect only 1 thumbnails file of xxx (whatever max size I configured)
If this is expected then apologies for the question, I'll close it.

**Comment by graciousgrey** [comment]
Yes, we expect multiple thumbnails for each image. Some of those are used for color and object detection others for the maps view or the lightbox. 
Setting a thumbnail size of 800 means we create only those types of thumbnails that are not bigger than 800.

**Comment by alensfor** [comment]
Excellent thank you all !
