### ISSUE TITLE
Possibility to choose the cover of an album among its photos

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#604]
Apparently the photo used for the album cover is chosen at random. There is little chance that this is the one the user would have chosen.

This request echoes the remark of @lpnueg4:

Why not add a button to set album cover ? so this problem is gone

_Originally posted by @lpnueg4 in https://github.com/photoprism/photoprism/issues/575#issuecomment-726501436_

**Comment by lastzero** [comment]
PhotoPrism automatically uses the latest picture with the highest rating right now, it's not completely random. Didn't have time to implement a dialog / button so far.

**Comment by lastzero** [comment]
There might existing feature requests already. Can check our GitHub issues for duplicates?

**Comment by graciousgrey** [comment]
Found it https://github.com/photoprism/photoprism/issues/383. So I will close this one.
