### ISSUE TITLE
How can i uninstall photoprism?

### ISSUE THREAD

**Issue by gerardit** [photoprism/photoprism#605]

**Comment by lastzero** [comment]
Just delete the Docker container and image. Google it, seriously.

**Comment by lastzero** [comment]
Added this question to our [FAQs](https://docs.photoprism.org/getting-started/faq/#how-can-i-uninstall-photoprism):

### How can I uninstall PhotoPrism? ###

This depends on how you installed it. If you're running PhotoPrism with Docker Compose, 
this command will stop and remove the Docker container:

```
docker-compose rm -s -v
```

Please refer to the official Docker [documentation](https://docs.docker.com/compose/reference/rm/) 
for further details.
