### ISSUE TITLE
Arm64 build

### ISSUE THREAD

**Issue by crisidev** [photoprism/photoprism#606]
Hello folks,
I noticed the docker container for arm64 is not being rebuild in the last 25 days. I would like to get the latest version to understand why my Android application stops after opening.

Is it possible to get it build again or can I help on fixing the automation to build the arm64 image upon push?

**Comment by lastzero** [comment]
A new version is automatically built along with the x86 image:

https://docs.photoprism.app/getting-started/updates/#development-preview

We receive a ton of requests recently, that reduces the time we can spend on development. Trying to start a new build with bug fixes as soon as possible.

**Comment by crisidev** [comment]
Thanks a million!

**Comment by crisidev** [comment]
Thanks a lot!

**Comment by lastzero** [comment]
Does it work for you? Let is know when there are issues.
