### ISSUE TITLE
Ungroup button missing

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#609]
In some cases, it is not possible to ungroup files in a group of photos. In the file view, you can only download or delete but not ungroup.
When the Ungroup button is missing for one of the files, it is also missing for all the others
I'm not sure, but this seems to happens when the grouping is done automatically when using the import function.
 
![image](https://user-images.githubusercontent.com/65403912/99142668-86c50080-2657-11eb-9681-e06dbe45be5e.png)

**Comment by lastzero** [comment]
Thanks for reporting this! Needs some more debugging / testing, no idea why this is happening.

**Comment by lastzero** [comment]
Can you provide us with example files for testing?

**Comment by jean-louis67** [comment]
Ouch, as I'm reindexing from scratch, I don't have this situation on hand for now.
I take this opportunity to point out that although I have unchecked Stack sequences, there are several dozen stacks that have been created, and that I ungroup them one by one. Maybe I did not understand the role of this parameter.

**Comment by lastzero** [comment]
PhotoPrism would still stack photos with the same XMP instance ID or Exif image ID as well as images with the exact same time and location. These are considered identical, not sequences of related files based on the file name. Sidecar files will also always be stacked as that's their purpose.

**Comment by jean-louis67** [comment]
Thank you for your reply.
Indeed, some photos produced some years ago by a digital camera have a different name (DSC00724.JPG and DSC00725.JPG for example) but do not include other differences. I hadn't noticed it yet. Ultimately, the functionality of Stack will help me to do a little cleaning!

**Comment by jean-louis67** [comment]
Hello,
After having reinitialized the base and reindexed all my originals, I then dealt with the many cases of grouping without problem (unstacking or deletion depending on the situation) 
The problem I described here did not recur, so I propose to close this incident for now.
