### ISSUE TITLE
Thumbnail API improvements

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#61]
**As a developer, I want the thumbnails API to be more flexible and reliable.**

Documentation: https://github.com/disintegration/imaging

Acceptance Criteria:
- API should accept 4 parameters: File hash, method (fit or fill), width, height
- Thumbnail file name in cache directory should contain actual file hash so that no outdated thumbnails are served
- Directory structure needs improvement
- Client-side code needs to be updated accordingly

**Comment by FrouxBY** [comment]
Hi, 
I'm getting currently into golang, and I am really involved in photography stuff, so I find this project worth a try for improving my go skills with some PR.
After reading a little bit the code, I think I can begin with this issue,

So I have a few questions, as far as I understand, the current state of the API accept only a thumbnail type as parameters with the image hash, which are predefined method/width/height. 
I understand that flexibility is the object of this issues, but I assume those predefined thumb parameters have been there first for a reason, 
So the question is, **do we want to have two endpoints, the current and a flexible one or do we want that this is the role of the front end to manage its favorites parameters and provide only a unique API with all parameters ?**

I think the intended purpose of predefined setting are that they can be pre-generate during import (or nightly, or whatever) and the API can serve them directly, and save a lot of time when requested, and it ensure that front end will ask for them and not choose random value which require computation.

Yet flexibility is a requirement for developer that may want to implement specific/smart and fast views and prototype them easily without changing backend code each time.

**Comment by lastzero** [comment]
Oh, this is actually not relevant anymore since I already refactored the API. We use pre-defined and pre-rendered sizes to keep it fast. We previously didn't pre-render thumbs but it turned out to be too CPU intensive to do it on the fly, especially for smaller devices.
