### ISSUE TITLE
Incorrect search show all results

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#610]
If we use a wrong filter like `quality:a` then hit `Enter` key, we get no error message and we see the same results as when there is no filter.

Steps to reproduce:
1. Open https://demo.photoprism.org/photos
2. Search for `quality:a`
3. We see the same results

I think that we should see a message and no result.

In logs we have:

````
2020-11-14 19:46:21 ERRO strconv.Atoi: parsing "a": invalid syntax
2020-11-14 19:46:21 ERRO error while parsing form values: strconv.Atoi: parsing "a": invalid syntax
````

But, the behaviour is correct if we reload the page or open the same URL, see in demo: https://demo.photoprism.org/photos?view=cards&order=newest&q=quality%3Aa We see "Couldn't find anything" as expected

**Comment by lastzero** [comment]
Quality must be a number, there is no quality "a". Current search result is only replaced if the request / query was successful.

**Comment by alexislefebvre** [comment]
Thanks for the answer, I understand. So maybe we could have a small notification to inform the user that the query was unsuccessful?

**Comment by lastzero** [comment]
Agree, validation should be improved. Need to take a look at other issues first though. Not sure when I'll get to it. Keep in mind that we support many languages, so we might need translations for all of those in case we perform changes.

**Comment by alexislefebvre** [comment]
I'm very sorry, I didn't see the message "Invalid request" at the bottom of the page.
