### ISSUE TITLE
Photo previews broken

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#611]
This has been mentioned on Gitter, but not really been solved, I suppose. So I'd like to provide anything need to fix this.

So what's happening?
<img src="https://user-images.githubusercontent.com/49901208/99155987-6fb8f980-26bd-11eb-8526-d65936d01c3c.png" height=100 />

Clicking on them leads also to this broken preview, downloading the original works.
I get heaps of `level=error msg="thumbs: thumbnail not cached"`
Apparently this happens after updating and thus restarting the the docker image.

So I am on docker, using a mariadb (figured out today that I parametrized mysql instead of mariadb - could that be the problem?) and having the cache in `/tmp/`

**Comment by lastzero** [comment]
Seems you lost your thumbs. Is the storage volume mounted in `docker-compose.yml`? Otherwise, data is lost after restarts. Rendering thumbs dynamically is a "workaround", but very slow. Better to storage the thumbs. They are automatically created while indexing.

**Comment by totti4ever** [comment]
volume is mounted:
`- /tmp/photoprism/cache:/photoprism/storage/cache # cache on SSD`

No problems to `ls` into that directory when execing into the container.

It is no problem that the storage folder is mounted to another directory, is it?
`- "./data/Storage:/photoprism/storage"`

From what I can see in the container, it is not.

**Comment by lastzero** [comment]
Well, they overlay each other. That's an edge case, don't know what might happen. Probably one will "overwrite" the other.

**Comment by totti4ever** [comment]
From what I can see inside the container, it is not a problem (and I am quite sure I have seen and done this somewhere else, too).

```
root@photoprism:/photoprism# ls -la /photoprism/storage/     
total 24
drwxr-xr-x 5 root       root       4096 Nov  8 19:00 .
drwxrwxrwx 1 photoprism photoprism 4096 Oct 21 06:15 ..
drwxr-xr-x 3 root       root       4096 Nov 14 20:20 cache
drwxr-xr-x 2 root       root       4096 Oct 23 18:26 settings
drwxr-xr-x 3 root       root       4096 Nov  8 20:39 sidecar
```

```
root@photoprism:/photoprism# ls -la /photoprism/storage/cache/
total 16
drwxr-xr-x  3 root root 4096 Nov 14 20:20 .
drwxr-xr-x  5 root root 4096 Nov  8 19:00 ..
-rw-------  1 root root  145 Nov 14 20:20 sessions.json
drwxr-xr-x 18 root root 4096 Nov 14 20:39 thumbnails
```

The thumbs are all there!

**Comment by lastzero** [comment]
"thumbnail not cached" means PhotoPrism can't find the thumb(s) for any reason... might also be permissions... hard to guess from where I sit... must have worked at some point in the past?

**Comment by totti4ever** [comment]
Permissions cannot be: `photoprism` runs as root and root sees all I quoted above.

A simple restart couldn't break it again. I wait for the next time the problem arises ( I guess after updates?).

**Comment by lastzero** [comment]
Yes, probably whenever the container is restarted.

**Comment by kushfest** [comment]
For what it's worth, I'm having the same problem. Everything had been working fine, but it seems something broke and   my thumbnails are gone. Same "thumbnail not cached error". I just disabled watchtower for photoprism so I can be in more control of updates and presently re-indexing all my photos...brutal. I checked permissions, everything looked right. Same with the volumes mounted in docker.

**Comment by lastzero** [comment]
Can you pull today's Docker image and reindex? There was a glitch in yesterday's build with volumes that might have caused this, replaced it shortly after we noticed.

**Comment by kushfest** [comment]
I pulled the image at 11:06am pacific today and have been reindexing since. Is that recent enough to be on the new build? I'd love to not reindex again haha.

**Comment by lastzero** [comment]
If the version in Settings at the bottom shows today's date, it's OK.

**Comment by lastzero** [comment]
But also if it's yesterday's build. You see our demo is working, it wasn't with the broken base image.

**Comment by kushfest** [comment]
Seems I just barely missed it haha. Stopped the indexing and just pulled
latest again. Definitely on the new version now. Re-starting the index.
Hoping this is the last time i’ll reindex for a while haha.


On November 16, 2020 at 3:09:49 PM, Michael Mayer (notifications@github.com)
wrote:

But also if it's yesterday's build. You see our demo is working, it wasn't
with the broken base image.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/photoprism/photoprism/issues/611#issuecomment-728384843>,
or unsubscribe

**Comment by lastzero** [comment]
Let us know how this goes. There were some major changes in how the indexer handles deleted and moved files as well as duplicates.

**Comment by kushfest** [comment]
Sounds like a minor setback for some major progress! I’ll let you know how
we’re looking when it’s done. Thanks! I’m really enjoying photoprism.


On November 16, 2020 at 3:20:04 PM, Michael Mayer (notifications@github.com)
wrote:

Let us know how this goes. There were some major changes in how the indexer
handles deleted and moved files as well as duplicates.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/photoprism/photoprism/issues/611#issuecomment-728388737>,
or unsubscribe

**Comment by kushfest** [comment]
Indexing completed and so far I appear to be good. Thumbnails are back. Still have watchtower off so I can see what happens next time I manually pull the docker image.

**Comment by totti4ever** [comment]
So, after watchtower pulled them latest version tonight (European time, i.e. 3 hours ago), it's broken again.

What can I do to provide more information?

**Comment by lastzero** [comment]
You've mounted storage to /tmp? That gets cleaned up automatically, for example after a reboot. Nothing to do with PhotoPrism.

**Comment by totti4ever** [comment]
oh jeez - thanks for pointing that out. To make it harder to discover, the directories are kept there.
It seem, I should find another path which is mounted to my SSD ;-)

thanks, that should fix it for me!
