### ISSUE TITLE
If I remove an "original" picture from the filesystem, will photoprism remove it after I re-scan?

### ISSUE THREAD

**Issue by dessalines** [photoprism/photoprism#612]
I'm deleting duplicate files after the fact, and would like them to be removed from photoprism on a 2nd scan.

**Comment by lastzero** [comment]
They should be removed from the index after re-indexing. Any issues with this?

**Comment by dessalines** [comment]
So a `Complete Rescan` isn't necessary?

**Comment by lastzero** [comment]
It shouldn't.

**Comment by dessalines** [comment]
Sounds good, thanks.
