### ISSUE TITLE
Can I hide the Private folder like how the Settings page can be hidden?

### ISSUE THREAD

**Issue by pale2hall** [photoprism/photoprism#613]
I'd like to allow my family to look through our photos, but I would like to hide any private pics.

I see that I can turn off the settings page via a docker variable, can that be done for the Private page?

Is there any way to make it so they can't see the photos marked private?  It would even be okay if I can't see them either.

**Comment by lastzero** [comment]
No, not yet. Might be better to implement true multi-user support for this?

**Comment by graciousgrey** [comment]
Can we close this? I guess this will be solved once we implement user management. This way you can give your family guest credentials and configure in the permission what they are allowed to see.
