### ISSUE TITLE
Create Unique Link For Media

### ISSUE THREAD

**Issue by royaltongue** [photoprism/photoprism#617]
As I'm sure a lot of us are, I'm here because of Google Photos removing it's free uploads.

I'm hosting Photoprism on a personal server, reverse-proxied through Caddyv2 and served via my own domain.

The one feature that PhotoPrism is missing that I can't go without is the ability to upload a video and share a link to that video, instead of sharing the video itself. Since I have an Android phone and everyone in the US still uses SMS, sending videos that way isn't really viable

Having this feature would be a lifesaver!

**Comment by graciousgrey** [comment]
Sharing single files (photos or videos) via link is planned see https://github.com/photoprism/photoprism/issues/466 :)
