### ISSUE TITLE
Albums: Broken share expiration date in form label

### ISSUE THREAD

**Issue by Engr-AllanG** [photoprism/photoprism#621]
- Installed via docker compose in proxmox container running ubuntu 18.04
- Separate container running nginx reverse proxy
- Everything seems to be working normally using my subdomain.domain.com
- When I create a share link and paste it into a private browser for testing, it takes me to my login screen instead of a public view, which is what I expected. After I log in, it then goes to mydomain.com/photos

I am guessing this is related to my reverse proxy. Any tips on where to start looking? For what its worth, I am successfully using my reverse proxy with Nextcloud, Seafile, W10 blue iris, Cryptpad and 3 or 4 other applications, so i'm not a complete novice. But I can't seem to figure this one out. I'm not certain if its a bug or a configuration issue.

**Comment by alexislefebvre** [comment]
If you reopen the link after being logged in, do you see the expected page?

**Comment by Engr-AllanG** [comment]
@alexislefebvre no after logging in, the album share link gets redirected to my main photos folder. I noticed that the share link does not have "public" in it:
e.g. `https://photo.mydomain.net/s/15ouucueev/share`
But if I right click a photo in preview and copy link address - that one _does_ have "public" in the link and it does work as intended:
e.g. `https://photo.mydomain.net/api/v1/t/14b7285bb2b7bbe2140ca8546bb8abe7f2b384f2/public/fit_1280`

this leads me to believe it is a photoprism issue. Thoughts?

**Comment by Engr-AllanG** [comment]
I discovered the issue is related to having an expiration date on the link. Above the selection it says "Invalid DateTime". I'll have to check the date/time of the OS this evening. I suspect it is set incorrect. If it is correct, then maybe a bug

**Comment by alexislefebvre** [comment]
You're right, we can see this error on https://demo.photoprism.org/albums/aqjyfk72jstm22m5/berge-2020 too:

![image](https://user-images.githubusercontent.com/2071331/99564059-3ee10900-29ca-11eb-8fe9-ab6b3a1817bb.png)

**Comment by graciousgrey** [comment]
Thanks for reporting, we will have a look at it on the weekend!

**Comment by Engr-AllanG** [comment]
Just tested on new ubuntu 20.04 container - public album share link with expiration worked as expected! I didn't expect the actual expiration (will have to wait 24 hours), but the link itself functions.

Excellent app - I'm loving it

**Comment by Mabenan** [comment]
Hi, is this already released?

For me it doesnt work. Tested with stable docker image and on demo.
![Screenshot_2021-09-20-13-54-44-614_com android chrome](https://user-images.githubusercontent.com/4959465/133998115-5a4c6cf5-63e7-42de-8ad7-d2544e1b683c.jpg)

**Comment by Mabenan** [comment]
The link is accesible

Addition the expiration is entered in the database i  checked with changing the seconds in db the link really expires.

**Comment by lastzero** [comment]
Share form label is fixed: It tried finding a date in `UpdatedAt` while the actual name is `ModifiedAt`.
