### ISSUE TITLE
File Type  / Support for 3gp videos

### ISSUE THREAD

**Issue by idolpx** [photoprism/photoprism#624]
Would be great to add support for 3gp video files.  I'm importing media files from some old phone backups and would like those included in the library too.

**Comment by alexislefebvre** [comment]
Browsers may not be able to read 3gp video format. I think you better convert the videos to MP4 H264/AAC if you want to be able to read them in the browser. Plus, it will be more future-proof than 3gp.

**Comment by lastzero** [comment]
Need to implement transcoding for this and other video formats.

**Comment by idolpx** [comment]
Yeah... it would be nice for it to do the transcoding on import.

**Comment by alexislefebvre** [comment]
Mozilla [recommend](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#Recommendations_for_everyday_videos):

> 1. A WebM container using the VP8 codec for video and the Opus codec for audio. These are all open, royalty-free formats which are generally well-supported, although only in quite recent browsers, which is why a fallback is a good idea.
> 2. An MP4 container and the AVC (H.264) video codec, ideally with AAC as your audio codec. This is because the MP4 container with AVC and AAC codecs within is a broadly-supported combination—by every major browser, in fact—and the quality is typically good for most use cases. Make sure you verify your compliance with the license requirements, however.

---

To look more in-depth, see the following links: [containers](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#Index_of_media_container_formats_file_types), [video codecs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#Codec_details) and [audio codecs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_codecs#Codec_details)
