### ISSUE TITLE
Metadata: Fault-tolerant parsing of timestamps from Exif and JSON sidecar files

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#625]
I will probably reset the database and reindex all of my photos. I expect to lose some metadata. I would like if possible not to re-enter a number of dates.
In many scanned photos, I have defined the _Date/Time Original_ field with _exiftool_. When the date is complete, it is taken into account by PhotoPrism. On the other hand, if there is only part of the date (year, or year + month for example), it is totally ignored, whereas we would like the year to be taken into account and the month and / or the day is declared _Unknown_
I tried with this one for example:

- "1993"
- "1993 12:00:00"
- "1993-00-00 12:00:00"

but without success.
Behind this subject, there is a significant time saving because with _exiftool_ I can put a date, even incomplete, in dozens of photos at a time, while with PhotoPrism, you have to manually go through each of them, and operate 3 changes (year / month / day)
Well, at least as long as there isn't a way to apply the same change to several photos.

**Comment by lastzero** [comment]
You can enter "1993-00-00 12:00:00" with Exiftool and that works in all software? 00 is not a valid month, so typical date parsers will report an error. We would also have to set it to 01 internally as the database will not store it otherwise.

**Comment by jean-louis67** [comment]
Hello
I only tried with PhotoPrism. My goal is not to test exiftool, but to find out how to get PhotoPrism to recognize an incomplete date. For example "1993" and "1993-12" seem correct, but when indexed, year, month and day are all unknown. Maybe this is an unmanageable requirement. I am looking to use exiftool mainly because I can apply to many photos at once. If I could set the year and/ or month for multiple photos at once via PhotoPrism (issue 271 for example, batch editing), that would be fine for me.

**Comment by lastzero** [comment]
Batch edit will be implemented for sure, after our release so that users don't have to wait any longer :)

**Comment by tootbrute** [comment]
> Batch edit will be implemented for sure, after our release so that users don't have to wait any longer :)

Nice! Can't wait.

**Comment by maxammann** [comment]
I like the idea of incomplete dates. Currently this function is used to check for a valid exif datetime. It is missing checks for partial datetimes: https://github.com/photoprism/photoprism/blob/bc86997ba3923498ba13a9e176dfa55ab26ed3f3/internal/meta/exif.go#L36

In fact this could be a good be a good beginner task, so I might find some time to implement this.

**Comment by lastzero** [comment]
With these improvements, PhotoPrism should be able to parse any timestamps matching the following patterns regardless of the delimiters or missing values (as long as they make sense, e.g. `2006-05-  T  :  :  :` for *May 1, 2006*):

- `2006:05:11:01:02:03`
- `2006:05:11:01:02:03Z`
- `2006:05:11:01:02:03+0130`
- `2006:05:11:01:02:03-0130`
- `2006:05:11:01:02:03+01:30`
- `2006:05:11:01:02:03-01:30`

**Help with testing would be greatly appreciated! A new [development preview build](https://docs.photoprism.app/release-notes/#development-preview) has been started...**

**Comment by jean-louis67** [comment]
Hello 
It's nice to work on this subject!
I didn't manage to pass my favourite test case, but maybe I'm doing it wrong.
Here are the detaiis:


- I updated my PhotoPrism instance with _docker pull photoprism/photoprism:preview_ to Build 220302-0059f429-Linux-AMD64 

- I put two files in originals/test
- I used exiftool according to point 5 of this FAQ: https://exiftool.org/faq.html
```
exiftool -overwrite_original -xmp:DateTimeOriginal="1906" lf1.jpg
exiftool -overwrite_original -xmp:DateTimeOriginal="1906:05" lf2.jpg
```
- I controlled  as follow the two files:
```
exiftool . | grep 'Date/Time Original'
Date/Time Original              : 1906
Date/Time Original              : 1906:05
```

- I launched an indexation
- The 2 files are added in photoprism and all date fields are _Unknown_, except for the hour

**Comment by lastzero** [comment]
Just pulling the [preview image](https://docs.photoprism.app/release-notes/#development-preview) is not enough, you also need to change the image name in your `docker-compose.yml` (or Portainer/NAS if you're using a Web UI for running Docker containers).

Stable Version (default in our [config example](https://dl.photoprism.app/docker/docker-compose.yml)):

```yaml
services:
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:latest
```

Development Preview:

```yaml
services:
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:preview
```

After you have changed the tag name, be sure to properly restart your instance as described in our docs:
https://docs.photoprism.app/getting-started/updates/#docker-compose

```bash
docker-compose pull
docker-compose stop
docker-compose up -d
```

**Comment by jean-louis67** [comment]
Oops, I feel stupid. Thank you very much for kindly correcting me.

So it's going much better now with Build 220325-e77a029f-Linux-AMD64

Here are the results for 1906-05 and 1906 respectively
![image](https://user-images.githubusercontent.com/65403912/160270815-f9d1335c-e148-4d9b-a026-82861f1f3c89.png)
So, it is exactly what I expected!

Leaving the time at zero is perfectly fine.
![image](https://user-images.githubusercontent.com/65403912/160270912-f9756992-f65b-4334-8a04-191204415622.png)

Thank you very much for covering this topic!

**Comment by lastzero** [comment]
Would it be better to assume 12:00 (lunchtime) when there is no specific time provided?

**Comment by jean-louis67** [comment]
For me personally, this is not very important. I don't know if there are more or less universal conventions.
Would it be too rich to have a parameter to choose between these 2 values,  or even any value?

**Comment by maxammann** [comment]
> Would it be better to assume 12:00 (lunchtime) when there is no specific time provided?

I would say 00:00 is fine. That way it is obvious that the image did not contain a hour.
