### ISSUE TITLE
Can't run docker-compose.yml on Raspberry Pi 4

### ISSUE THREAD

**Issue by gitowiec** [photoprism/photoprism#626]
Hi

I would like to try out this interesting software but I can't run default docker-compose.yml prepared for R PI.
I get this error when running with `docker-compose up`
```
pi@bank:~/containers/photoprism $ docker-compose up
Creating photoprism_photoprism_1 ... done
Attaching to photoprism_photoprism_1
photoprism_1  | standard_init_linux.go:211: exec user process caused "exec format error"
photoprism_photoprism_1 exited with code 1
```
I don't know what to do next, how to debug this issue?

**Comment by alexislefebvre** [comment]
It looks like the wrong image is started: https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error/648558#648558

Check that you use the `photoprism/photoprism-arm64:latest` image.

**Comment by lastzero** [comment]
Please use our docker-compose.yml example config for ARM64 / Raspberry Pi:

https://dl.photoprism.org/docker/arm64/docker-compose.yml

**Comment by lastzero** [comment]
Note that our ARM64 server is currently being upgraded to a newer Ubuntu version to solve build issues. While the upgrade is running, we can't provide updated ARM64 images.
