### ISSUE TITLE
Question - How to import directory?

### ISSUE THREAD

**Issue by Engr-AllanG** [photoprism/photoprism#635]
Hi, I searched the Issues and docs and didn't see an answer to the following question:

Am I missing an easy way to _import_ an entire library? The import dialog only lets me select files. Am I missing something? The way I am going to do it is to use FileZilla to copy my directory of pictures from my laptop into the import folder of my photoprims container, and then hit the import button from the web gui.

If that's the way to do it, I would suggest adding the ability to import/upload entire directories. Maybe i'm just not seeing it.

Thanks!

**Comment by alexislefebvre** [comment]
PhotoPrism can access to the file on the server by mounting them in the container: https://docs.photoprism.org/getting-started/docker-compose/#step-1-configure

**Comment by Engr-AllanG** [comment]
Hi, thanks for the reply. In this case the pictures are on a windows laptop and not easily accessible to the photoprism container.

The easiest workflow would be for web gui import dialog to allow selection of directories. Not sure what the implications are leading to that feature not currently existing. 

⁣

**Comment by lastzero** [comment]
The container can see nothing outside of it, that's its purpose. However, you can use WebDAV to copy files inside. It's better than using the browser file upload.

**Comment by alexislefebvre** [comment]
You could use the upload feature but it will probably be faster to transfer the files from Windows to the server with something like `rsync`.

**Comment by barrystaes** [comment]
Ok so basically if you already have a folder structure, PhotoPrism wont rename files?
And i can still find them in the groups i made using folders like "YYYY-MM Vacation XYZ"?

This would help me bulk edit to add locations to the EXIF data.

**Comment by lastzero** [comment]
No, only importing will rename files to avoid duplicates - as described in our docs and FAQs.

**Comment by Engr-AllanG** [comment]
@alexislefebvre No, I can't use the upload feature - that was the point of the question. The upload feature doesn't let you select an entire folder. It only lets you select files, so the entire library I'm uploading would have to be in one folder. I also understand I can use some other ways of copying to the server. Which I am doing

@lastzero  I guess the point of my question was if I was missing some obvious way to easily add the files to my server running photoprism. I know I can use webdav, but that requires me uploading my files to a go between (like my seafile or nextcloud instances, or creating a webdav server) which I was trying to avoid.

Thanks for your time

**Comment by lastzero** [comment]
PhotoPrism works as a webdav server AND client. You can add files with common operating systems and many mobile clients.

**Comment by Engr-AllanG** [comment]
@lastzero Ok, it sounds like I don't understand webdav enough- I'll look into that further!

Thanks for the help. Awesome application
