### ISSUE TITLE
Metadata: Implement workaround for bad image rotation in Exif headers

### ISSUE THREAD

**Issue by lpnueg4** [photoprism/photoprism#637]
as #602  said, the phtot was reversed.

root@05e4df78ebba:/photoprism/storage/cache/thumbnails/4/8/5# exiftool 48535247caa3e52f7f80f7a208298f89f760fa26_1280x1024_fit.jpg 
ExifTool Version Number         : 11.88
File Name                       : 48535247caa3e52f7f80f7a208298f89f760fa26_1280x1024_fit.jpg
Directory                       : .
File Size                       : 200 kB
File Modification Date/Time     : 2020:11:17 02:08:15+00:00
File Access Date/Time           : 2020:11:23 02:43:32+00:00
File Inode Change Date/Time     : 2020:11:17 02:08:15+00:00
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Image Width                     : 768
Image Height                    : 1024
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 768x1024
Megapixels                      : 0.786

you can see, photo looks been squeezed only in browser, origin photo is right.
I will send file from email.
![image](https://user-images.githubusercontent.com/16138783/99925542-82949380-2d79-11eb-9a1f-ea693ff5b438.png)

**Comment by lastzero** [comment]
Did you already send the files for testing via email?

**Comment by lpnueg4** [comment]
@lastzero Yes, I send the mail again use gmail, title is "**[#637] In Stacks photo size was reversed, except main file-2**"

**Comment by lastzero** [comment]
Thanks! Found it.

**Comment by lastzero** [comment]
Looks like your photos have bad metadata:

```
photoprism/internal/meta$ exif-read-tool -f testdata/notebook.jpg  | grep Or
IFD-PATH=[IFD] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[[1]]
IFD-PATH=[IFD/Exif] ID=(0x9003) NAME=[DateTimeOriginal] COUNT=(20) TYPE=[ASCII] VALUE=[2020:11:13 15:25:45]
IFD-PATH=[IFD/Exif] ID=(0x9291) NAME=[SubSecTimeOriginal] COUNT=(7) TYPE=[ASCII] VALUE=[878303]
IFD-PATH=[IFD1] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[[6]]
```

You can get the `exif-read-tool` from https://github.com/dsoprea/go-exif if you want to check on your own. If JSON sidecar files are enabled, the fist file gets some if its metadata from `exiftool` which randomly uses the other value. Browsers etc display the image in the right orientation because they don't rotate at all. So it's randomly OK too.

**Comment by lastzero** [comment]
I might be willing to spend time with implementing a workaround after our release. Is this an important issue that needs to be solved?

**Comment by lpnueg4** [comment]
@lastzero I use mspaint edit the picture, maybe mspaint change the exif info, thanks

**Comment by lastzero** [comment]
Sounds plausible.
