### ISSUE TITLE
[Suggestion] Can we add a way to change the picture for Albums? 

### ISSUE THREAD

**Issue by nowjon** [photoprism/photoprism#638]
Heyo, 

Love the program, but wanted to ask if we could change the Album pictures. Depending on how they're added appears to affect if the album gets a photo at all, and when it does, it's not one I can set. 

I wish this was in the settings for the Album. 

Let me know if there are any questions. 

Thanks! ;)

**Comment by graciousgrey** [comment]
Yes, we plan to implement this :). For more information see: https://github.com/photoprism/photoprism/issues/604.

**Comment by jetset11** [comment]
when will this be implemented?

**Comment by lastzero** [comment]
When I have a new chair. The old one is breaking down from working day and night. 😱

If you are not a sponsor yet: https://www.photoprism.app/membership
