### ISSUE TITLE
Random files/directories just missing

### ISSUE THREAD

**Issue by theorician** [photoprism/photoprism#640]
Running the official docker containers, it seems as though when importing larger folder structures, random files and folders are just never imported. I've looked into what sorts of files and can't come up with any kind of pattern. Indeed, when wiping the DB and generated metadata, and reimporting, _different_ files and folders end up being missed next go round. It's entirely inconsistent.

Is this an issue you're aware of at all?

**Comment by lastzero** [comment]
Might those be duplicates? Are you using symbolic links?

**Comment by theorician** [comment]
No, no symlinks at all. They might be duplicates but I doubt it. Is there away to check by poking around in the DB?

**Comment by theorician** [comment]
I've just checked, `select * from duplicates` - there are indeed some but those are unrelated. So that's not it either.

**Comment by theorician** [comment]
Let me go away and investigate some more - I'll close this ticket for now and reopen it if I find something. I'll dig through the DB a bit.

**Comment by lastzero** [comment]
Check the error / indexing logs for anything unusual, like skipped files. You may enable debug mode to see more detailed log messages.
