### ISSUE TITLE
Replace “~/” paths with full paths in docker-compose.yml and doc?

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#642]
The [documentation](https://docs.photoprism.org/getting-started/docker-compose/#step-1-configure) states that:

> You may mount any folder accessible from your computer, including network drives. Note that PhotoPrism won't be able to see folders that have not been mounted. Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
> 
> ```
> volumes:
>   - "~/Family:/photoprism/originals/Family"
>   - "~/Friends:/photoprism/originals/Friends"
> ```

I think that it would be better to use full path like `/data/Family` in examples because:

- it is more explicit
- on a server, files will probably not be mounted on `/home` directory (or whatever directory is the home)
- `~/Family` depend of the user who launch the command, which could give surprising results (the probability of this usage is very low though)

What do you think?

**Comment by lastzero** [comment]
Depends, on windows there is no obvious / like on Linux. Our idea was that most users will be able to find their home directory.

**Comment by kurtph1969** [comment]
Could someone please explain to me how I mount an external drive in Windows to show up as "originals"?

**Comment by lastzero** [comment]
We'll add examples for Windows to our docs soon. What Windows version and Linux subsystem are you using specifically?

**Comment by kurtph1969** [comment]
Thank you.

I am using Windows 10 and Docker Desktop 3.0.0 (50684).
https://docs.docker.com/docker-for-windows/release-notes/

I would like to be able to index an external drive called F:\

Kind regards,

Kurt

**Comment by lastzero** [comment]
![IMG_20201221_213432](https://user-images.githubusercontent.com/301686/102819947-b4c6fe80-43d4-11eb-912f-3fda2efd721f.jpg)

**Comment by lastzero** [comment]
@kurtph1969 We've updated our Getting Started guide for you, see info box at the top:

https://docs.photoprism.org/getting-started/docker-compose/

**Comment by kurtph1969** [comment]
OK, thanks Michael, I'll check it out.
