### ISSUE TITLE
[Suggestion] Connect Google Drive/Goole Photos

### ISSUE THREAD

**Issue by Pheggas** [photoprism/photoprism#646]
This feature would be useful not just for me but many others too. No need to setup Rclone for viewing content on google drive via your windows explorer. Just use their public API for access and manage photos and videos. There should be support for both, Google drive and photos. 

API Page: https://developers.google.com/drive/api/v3/about-sdk

PS: I think there's Shared Drives already in the API. I use Shared Drives with my family to share photos and videos.

**Comment by graciousgrey** [comment]
Relates to #224 #223

**Comment by Pheggas** [comment]
Already exist
