### ISSUE TITLE
Albums: Nested calendar view

### ISSUE THREAD

**Issue by anaxmedia** [photoprism/photoprism#649]
Hi there, I'm loving PhotoPrism so far. I'm a travel photographer and I'm currently indexing my library which is sync'd to my NAS using Nextcloud. My folder/file structure is as such:

- 2020
  - 01
    - Grand Canyon 
    - Zion National Park
  - 02
    - Costa Rica Hike
etc...

After indexing on the Calendar page everything is grouped by Year and Month and all of the pictures for that month show under a single album. I often have thousands if not tens of thousands of pictures (time lapses) and it makes it a bit difficult to dig through what I'm looking for. Is there a way under the Calendar page to have sub albums for the groupings like I have in my file system (Grand Canyon, Zion National Park, Costa Rica Hike, etc) under each year/month album?

I can almost get this by using the "Folders" page under albums but then those aren't sorted by year/month.

**Comment by graciousgrey** [comment]
The only place where we currently support hierarchical structures is in *Library > Originals*. There you find a representation of your folder structure.
You could also find the photos in *Photos* by using our search. Set the filters for year and month and use parts of the folder name (those are automatically set as keywords) as search term. Additionally you can set filters for location or camera model.
Given you example set Year to 2020, Month to January and use "canyon" as search term --> then the search result should contain all photos of your folder.

Some more thoughts on hierarchical albums are collected in https://github.com/photoprism/photoprism/issues/401.

**Comment by graciousgrey** [comment]
Would this be solved with https://github.com/photoprism/photoprism/issues/651?

**Comment by anaxmedia** [comment]
I still think having the hierarchical structure would be beneficial from a navigation and organizational experience. It's a natural thing that I think many people come to expect when viewing media. I understand the focus on search but sometimes I like to just be able to find what I'm looking for through old school browsing.

**Comment by lastzero** [comment]
@anaxmedia Thank you for backing our project 🌈

The FAQs at https://docs.photoprism.org/user-guide/faq/ explain why we try to avoid using trees for organizing pictures. Trees as a data structure make developing good software much more complex, slow and insecure, like when permissions are inherited and merged through multiple levels (google "windows acl inheritance").

If it's just for browsing, we might be able to provide nested views based on existing search filters.

**Comment by anaxmedia** [comment]
Thank you for all your hard work on such an awesome project. I'm happy to help back it! That sounds like it would work. I would solely use it for browsing, I'm not sure if others would have other use cases. Basically combining both the "Calendar" view and the "Folders" view so I can see the folders under year/month. 

If that's not possible due to some of the complexities you listed above then definitely having the searching by album/folder I suggested in #651 would at least allow us to get the same result just in a different way.

**Comment by graciousgrey** [comment]
@anaxmedia I will close this as we already have this ticket for hierachical albums --> https://github.com/photoprism/photoprism/issues/401. And the calendar months are albums as well.

For your use case I guess this: https://github.com/photoprism/photoprism/issues/1536 could be a solution as well ?
