### ISSUE TITLE
Random language switch

### ISSUE THREAD

**Issue by Pheggas** [photoprism/photoprism#650]
I have longterm opened Photoprism demo in Chrome and when i open it, it automatically reloads the page (it's completely normal), but after then i see the translation is in random avalible language. E.g. Spanish, German etc.

I don't know how to replicate the bug. Try to go to the settings and let the page be. After couplne hours/days open back the tab and see if the language changed. Currently i have it in French which i never set.

![image](https://user-images.githubusercontent.com/9994511/100222872-01750200-2f1b-11eb-9163-65a9da25e3ef.png)

**Comment by lastzero** [comment]
The UI is automatically updated for ALL users based on the settings.

**Comment by Pheggas** [comment]
Thank you.
