### ISSUE TITLE
UX: Disable archiving confirmation

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#659]
Since the app does not delete anything atm I find the additional confirmation to archive a photo just nagging. Can you add a switch to disable this popup so users can move selected photos directly to the archive?

**Comment by lastzero** [comment]
We can add a setting for this. Would you still skip the confirm dialog when **Use trashcan to physically delete files after confirmation #167** is implemented?

**Comment by swingstate** [comment]
Let's say, I am comparing the UX with MacOS. I click on a file / photo and hit backspace (delete), which moves the file into the bin (In photoprism I would compare this to the archive). 
Then I can go into the bin and empty it completely or select files which I want to delete permanently. Bottomline, the confirmation has it stands today isnt necessary and I think the UX can be streamlined the way i described here. 

mark a file -> move to Archive -> go to Archive -> delete permanently (or leave it there).
