### ISSUE TITLE
UX: Add full context menu to photo viewer

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#660]
While I am scrolling through large albums by using the picture viewer I want to e.g. archive / share / lock / add to album ... . However, at the moment I have to close the picture and then choose the picture again or more often scroll far down to the picture (while I am hoping to remember the correct picture; difficult in collections with a lot of very similar pictures like landscape pictures in my case) and then choose it, click the context button and so on. 

I suggest to make the features of the round context button also available while the picture viewer is displaying a photo. At the moment the options at the top right are not on par with the context button. 
To keep the interface clean I suggest to move most of the features into a submenu and / or allow to configure the menu with the features I am using most (share, archive, move to album ...).

**Comment by lastzero** [comment]
Maybe when we develop our own lightbox. Adding this to https://photoswipe.com/ would be a hack. Our regular views automatically update when the backend publishes changes, e.g. when metadata was edited or when files were moved to the archive. Our photo viewer / lightbox uses a static result list based the data PhotoSwipe requires, so completely different technology.

**Comment by swingstate** [comment]
sounds like a backlog item :)

**Comment by swingstate** [comment]
Few more thoughts on this...

After adding 2K more photos I started to create albums. Many of them are based on the actual location where they have been taken. So I went to maps and zooming in to see where photos have been taken works well.
However, If I click on a photo I cannot move it from this view into an album. This might not be an issue when one only adds a few photos every now and then through the upload button, however I think when working with large libraries through the import and in certain workflows this would be very powerful.
Like in my case when there are clusters of photos e.g. 5km away from each other it would ease the flow if I could group the photos on the map with the mouse, open the context button and create a new album "location X" and move the selected photos into the album. Without leaving the view in the app.

**Comment by graciousgrey** [comment]
Yes, there is room for improvement for the photo viewer. See #657 and #508. 
I like the idea of selecting on the map as well! But I guess some other items have higher priority right now.

**Comment by swingstate** [comment]
In this context - Can you allow to create a album from the add to album menu? That would ease sorting photos a lot. 

<img width="931" alt="Bildschirmfoto 2020-12-29 um 13 04 22" src="https://user-images.githubusercontent.com/73672554/103282784-21df2300-49d7-11eb-962b-c9319b7d5259.png">

Not sure if this has to be e separate issue.

**Comment by lastzero** [comment]
Typing the name of a new album will create it.

**Comment by swingstate** [comment]
I bet I tried that :) Anyway, thank you!

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: https://github.com/photoprism/photoprism/issues/1307
