### ISSUE TITLE
WebDAV: Improve UX of remote directory autocomplete

### ISSUE THREAD

**Issue by zoenglinghou** [photoprism/photoprism#664]
Related: #301 
As mentioned in :arrow_up: this issue, PhotoPrism uses an inefficient way to fetch remote directory structure, which could causes high resource usage on the NC server and potentially failure/timeout. However, manually entering the remote directory sync directory works, but only after the timeout (~10min).
It would be nice to see PhotoPrism improve the directory fetching function for a better UX. (and maybe with the option to directly enter the directory name before fetching?)

**Comment by lastzero** [comment]
Implemented a 45s timeout. Does this work for now?

**Comment by zoenglinghou** [comment]
The timeout works really well! And it remembers the directory I last inputted!
