### ISSUE TITLE
Updating a Folder Album

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#665]
Hello,
I created an album from a folder and find the photos from the folder in the album.
However, the subsequent addition of new photos in the folder does not affect the album.
Maybe it's not a bug, if the link between album and folder is not kept. But in this hypothesis, this automatic update feature would seem practical to me. However, it is not very important, because you can quickly update manually.

**Comment by lastzero** [comment]
PhotoPrism automatically creates and updates folder albums, see screenshot. If you create a regular album from them, entries need to be managed manually.

![Screenshot 2020-11-30 at 08 58 22](https://user-images.githubusercontent.com/301686/100582891-3b168600-32ea-11eb-8bf8-ac9aed1d071e.png)

**Comment by jean-louis67** [comment]
Thank you for your answer
I did not pay attention to the presence of this _Folders_ sub-menu under _Albums_. I think I get the idea. Folders are by nature albums.
