### ISSUE TITLE
Photoprism container constantly restarting

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#666]
The container log is full of this entry:

time="2020-11-29T21:37:41+01:00" level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"

Webinterface seems to be inaccessible.
Also I cannot get a terminal into the container. 
The folder sidecar and its content does exist.

I didnt touch the config since days. Any advise?

**Comment by lastzero** [comment]
Seems like photoprism can't write to the directory and Docker automatically restarts the instance. Did you check permissions?

**Comment by swingstate** [comment]
Is it safe to remove the container and rebuild it, without losing any data? Can I reconnect a new container to the db instance for an old container or will that cause any trouble?

**Comment by lastzero** [comment]
All user data should be stored outside the container, either in the directories you specified or an anonymous Docker volume. This depends on your specific configuration. When using our [docker-compose.yml](https://dl.photoprism.org/docker/docker-compose.yml) example, you are safe to upgrade the image or rebuild the container.

**Comment by swingstate** [comment]
I use following command: 

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='PhotoPrism' --net='br0' --ip='192.168.178.244' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PHOTOPRISM_UPLOAD_NSFW'='true' -e 'PHOTOPRISM_DETECT_NSFW'='false' -e 'PHOTOPRISM_ADMIN_PASSWORD'='############' -e 'TCP_PORT_2342'='2342' -e 'PHOTOPRISM_DATABASE_DRIVER'='mysql' -e 'PHOTOPRISM_DATABASE_DSN'='photoprism:###############@tcp(192.168.178.240:3306)/photoprism?parseTime=true' -e 'PHOTOPRISM_SETTINGS_HIDDEN'='false' -e 'PHOTOPRISM_THUMB_UNCACHED'='false' -e 'PHOTOPRISM_THUMB_SIZE'='2048' -e 'PHOTOPRISM_THUMB_SIZE_UNCACHED'='7680' -e 'PHOTOPRISM_JPEG_SIZE'='7680' -e 'PHOTOPRISM_JPEG_QUALITY'='95' -e 'PHOTOPRISM_DARKTABLE_PRESETS'='false' -e 'PHOTOPRISM_THUMB_FILTER'='blackman' -e 'PHOTOPRISM_EXPERIMENTAL'='true' -e 'UID'='99' -e 'GID'='100' -e 'PHOTOPRISM_STORAGE_PATH'='/photoprism/storage' -v '/mnt/cache/appdata/photoprism/':'/photoprism/storage':'rw' -v '/mnt/user/photolibrary/storage/':'/photoprism/originals':'rw' -v '/mnt/user/photolibrary/import/':'/photoprism/import':'rw' --restart=unless-stopped 'photoprism/photoprism'

2f78611f214198d1fd126e31dea45cea837758129aca5c1617fdf11e48f3d152

This has been running fine for a week where I imported approx. 5K images. Any issues with the above?

**Comment by valorad** [comment]
I had the same issue but I have solved it. In short, do you really have the permission to write in those mounted volumes?

In my case, I first forgot to create the folders on my host, so docker created them for me. Therefore the ownership was `root:root` and I cannot write as a normal user. After changing the folder `~/.photoprism` with `1000:1000` ownership and the container will no longer restart.

**Comment by lastzero** [comment]
I'd assume `/mnt/cache/appdata/photoprism` is not properly writable by whatever the container is running as. Using the rw option doesn't ensure filesystem permissions are correct. Also I'm not 100% sure about the format as I'm using Docker Compose mostly. Would look more like `- "/mnt/cache/appdata/photoprism:/photoprism/storage:rw"` there.

**Comment by danburd** [comment]
I am experiencing the same issue, with the program restarting repeatedly with the same error.

`level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"`

This is on a fresh Fedora install, using Docker, and using the default docker-compose.yml file. I'm trying to put the files in my home drive as specified by the default yml file. I'm running it without sudo, but Photoprism creates the .photoprism folder with root permissions and then can't seem to do anything inside of it, generating errors. When I give the .photoprism folder the proper permissions and create the sidecar folder myself, it complains that it can't create the next folder. And so on.

I'm not sure if I messed something up, or if this is some kind of obscure SELinux issue, or something else altogether. Thank you.

**Comment by danburd** [comment]
I resolved this by turning off SELinux. The program now runs as expected.

**Comment by lastzero** [comment]
Maybe is happens when you use UID instead of the Docker-native `user: "1000:1000"` to set a user id? SELinux should totally prevent user id hacks in Docker containers. We've added the UID und GID env variables for NAS users who have no other way to configure this.

**Comment by lastzero** [comment]
Added this question to our FAQs: https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop

**Comment by danburd** [comment]
Sorry for the late response -- I tried again with SELinux turned back on and with several variants of the UID settings (though I know little about how it works), including trying the UID settings as they are the default yml file. None worked. It's working fine with SELinux off.

Thanks for adding the issue to the FAQ. Other Fedora users will likely encounter this issue as well.

**Comment by lastzero** [comment]
SELinux is for enterprise environments Just turn it off unless you want to make a full-time job out of this :)

**Comment by lastzero** [comment]
Updated our FAQs to mention AppArmor and SELinux as well.

**Comment by ImranR98** [comment]
The FAQ doesn't really make it clear what needs to be done to fix this. It may be better to use the `privileged: true` option for each service in the `docker-compose.yml` instead of disabling SELinux entirely.

**Comment by lastzero** [comment]
See https://docs.photoprism.app/getting-started/troubleshooting/

The container will only restart if you have intentionally enabled this in your configuration. Feel free to ask in GitHub Discussions or sign up as a sponsor to get direct technical support if needed.
