### ISSUE TITLE
Error 1045: Access denied for user 'photoprism'@'172.23.0.2'

### ISSUE THREAD

**Issue by kerHbal** [photoprism/photoprism#67]
Hi,
(Error message in second post below)

I followed this to install it on my remote server: http://docs.photoprism.org/en/latest/setup/
And used yml file in link above (just for test).
After `docker-compose up -d`:
![putty_2018-11-12_17-29-54](https://user-images.githubusercontent.com/11629684/48378979-9abc7d00-e6a0-11e8-8def-cf1d564301f4.png)
But I cannot open web frontend:
![brave_2018-11-12_17-33-39](https://user-images.githubusercontent.com/11629684/48379298-a197bf80-e6a1-11e8-8e2d-2095a91bd7d3.png)
In case there is any problems related to iptables: (the reason showing http here may be "2342:80" writen in yml file )
![putty_2018-11-12_17-25-43](https://user-images.githubusercontent.com/11629684/48379373-f0ddf000-e6a1-11e8-8d69-86c10feac9bc.png)

So is there any reason for that?
Thank you.

**Comment by kerHbal** [comment]
And `docker ps`:
![putty_2018-11-12_22-31-17](https://user-images.githubusercontent.com/11629684/48389295-d2401f00-e6ca-11e8-8d3d-7971584d2884.png)

**Comment by lastzero** [comment]
Does it work on a local computer? Just in case there is a problem with the docker image.

Also you could try to change the port to 80 in docker-compose.yml 

Note that https is not supported yet

**Comment by lastzero** [comment]
Is it possible that you skipped "Step 1: Configure" from the setup guide and jumped to "Step 2: Run" without making sure a `photos` directory actually exists on your server?

**Comment by kerHbal** [comment]
@lastzero I'm using Windows and Hyper-v is facing problems in my Windows, so I cannot start docker on my computer.  Port is changed to 80, still not working.
I used `chmod 777` on `Photos` to make sure nothing goes wrong and I can see 3 sub-folders `Import`, `Export` and `Originals` were created properly by Photoprism.
But still not working, same error 1045.

**Comment by lastzero** [comment]
Also "access denied" can mean you can not access MySQL. Did you change any networking settings or the credentials in the config file or docker-compose.yml? Did you pull the latest docker image for photoprism/photoprism?

**Comment by kerHbal** [comment]
@lastzero Yeah at first I changed credentials without paying attention to `# keep this` in the yml file 🤣 
After that, I changed the credentials back and still not working. I'm gonna delete images and re-pull them to have a clean start.

**Comment by lastzero** [comment]
MySQL is only initialized once, changing the env variables after it was created doesn't have any effect.

**Comment by kerHbal** [comment]
@lastzero Oh, I see. However, still facing the problem.
I used `docker system prune -a` to delete photoprism and mysql images, after doing that, they were not showed using `docker images` command. And after re-pulling it, starting again, this time I didn't touch anyting in yml file. But the problem still exists.

**Comment by kerHbal** [comment]
And there are some MySQL warnings if this helps:
![putty_2018-11-13_11-41-58](https://user-images.githubusercontent.com/11629684/48428541-41ecf300-e739-11e8-8786-a3067e863b6b.png)

**Comment by lastzero** [comment]
Ok, strange. I'm pretty sure the problem is connecting to MySQL. Not sure if deleting an image also means deleting the container that uses it. Time for us to setup a public demo...

**Comment by kerHbal** [comment]
@lastzero And actually before deleting the images, I used `docker-compose down` to stop photoprism and MySQL.

**Comment by lastzero** [comment]
Mysql uses a permanent volume for data. See compose file.

**Comment by kerHbal** [comment]
@lastzero Thank you for the information. From compose file, 
```
volumes:
      - photoprism-database:/var/lib/mysql
```
However I don't see any mysql folder in /var/lib
So I searched for that, and it showed in some deeper folders, sorry that I'm not quite familiar with docker file structure, are they the permanent volume that I'm looking for?

**Comment by kerHbal** [comment]
It's solved. I tried to delete all volumes related to photoprism, and now it works. Thank you!

**Comment by rkrzr** [comment]
I ran into the same problem and this thread helped me to fix it by:

1. Stopping the running containers
2. Running `docker system prune -a`
3. Running `docker volume prune`
4. Editing `docker-compose.yml` and making sure that the values for `PHOTOPRISM_DATABASE_PASSWORD` and `MYSQL_PASSWORD` are identical
5. Running `docker-compose up`

**Comment by cwpearson** [comment]
I had a similar problem, and in addition to what @rkrzr suggested I had to delete the `storage` and `database` folder that PhotoPrism created.

it seemed sufficient to do
```
docker-compose down
docker volume prune
rm -r storage database
docker-compose up
```

i.e., I did not need to do `docker system prune -a`
