### ISSUE TITLE
Apache Reverse Proxy

### ISSUE THREAD

**Issue by eddyizm** [photoprism/photoprism#672]
There is no apache reverse proxy in the docs. Is this because is not possible (don't see why not) or just not the recommended way to server photoprism? Would it be possible to add an example to the docs?

**Comment by OliveiraHermogenes** [comment]
There is [In-App documentation](https://github.com/photoprism/photoprism/blob/develop/frontend/src/pages/help/websockets.vue). You may also wanna take a look at PR #573.

**Comment by eddyizm** [comment]
Thanks @OliveiraHermogenes I got it sorted out with some googling and apache docs.
Curious though, I am not able to find that page anywhere. Searched "apache" in the docs.photoprism.com site. 

`sleep(3600)`

 And I spent some time looking. I did not find it linked anywhere but I typed mysite.com/help and got to the help page referenced. :-) I actually did stumble against that PR when googling for solutions.
