### ISSUE TITLE
photoprism fails on make test

### ISSUE THREAD

**Issue by maisen20** [photoprism/photoprism#673]
Hi,
unfortunately I have no experience in developing with github, but I would like to deal with it now and help with the further development of this great application.

I have set everything up according to the instructions on https://docs.photoprism.org/developer-guide/setup/, but I get an error when I run "make test". 

Can I ignore that? I started the webserver and made some changes for testing in the frontend and it seems to work.

Error message in my terminal while make test command:

> FAIL | 	github.com/photoprism/photoprism/internal/photoprism	114.898s

**Comment by lastzero** [comment]
No, you should not ignore this! :wink: 

Did you run `make all`? Are you using our dev Docker image as described in the docs? It's been a while since we wrote them, so maybe some details need to be updated. Feedback welcome.
