### ISSUE TITLE
Downloads: Configure Name Schema

### ISSUE THREAD

**Issue by wechsler42** [photoprism/photoprism#675]
**Acceptance Criteria:**

- [ ] Add this option to the UI
- [ ] Update the docs

---------------------------------
Hi there,
thanks for working on this exceptional project!
I am one of that guys who has a well organized photo collection, so I work with "photoprism index". I use a naming schema fpr my photos: "Date_Time.jpg". When I download photos from Photoprism the original file names are extended by for example "Date_Time_Location.jpg".
What do I have to to do that I could download photos from Photoprism with an unchanged, original file name? Is there a way to force this in the configuration of Photoprism?
Thanks in advance for a hint!

**Comment by lastzero** [comment]
Not yet, but it might be a feature! I personally keep my file names unchanged on the server, so that it's easier to backup. Otherwise you need to do full backups, or use a super smart backup tool that keeps track of moved and renamed files. As I still like properly named files when sharing with others, we've implement download this way.

**Comment by lastzero** [comment]
Note that you might download two files from different folders that have the same name (your browser will put them in the same local directory). What should happen in this case?

**Comment by wechsler42** [comment]
Well, I see this point. I would suggest that if two  or more files have the same name, an appendix would be added to the file name like "20201208_140220_conflicting_[1..n].jpg".

**Comment by lastzero** [comment]
Just added a value in `settings.yml` for this (download.name). There is no UI for changing it yet. Default is "file", other options are "share" (as before) and "original" (if renamed by PhotoPrism).

**Comment by lastzero** [comment]
Putting this back to ideas until we have time to implement a settings UI. For now, you may change the download file name directly in `config/settings.yml` and restart. Default has been changed to use the original file name.

**Comment by wechsler42** [comment]
Hi Michael, thanks for considering and implementing this option. It is very appreciated.

**Comment by graciousgrey** [comment]
@wechsler42 Glad to here, you like it :) I reopen this as we still want to add this option to the UI

**Comment by lastzero** [comment]
Let's create a new issue for this so that it's clear it already works in the backend.
