### ISSUE TITLE
Get a better understanding of Adobe XMP sidecar files

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#68]
**As a developer, I want to understand what fields of XMP are commonly used for photography, especially in Photoshop, Lightroom and Darktable so that I know what I have to implement.**

[Extensible Metadata Platform](http://www.adobe.com/devnet/xmp.html) (XMP) is a common sidecar file format for metadata. It is defined by the Adobe XMP Specification [Part 1](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf), [Part 2](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart2.pdf) and [Part 3](http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart3.pdf).

As it is extensible (open to extensions), also used for media other than photos and many fields are just defined as text (like actions for RAW to JPEG conversion), we can certainly not support everything but must focus on our specific use case and common photography applications.

See also [Compare the quality of different RAW converters with Lightroom / Photoshop #65](https://github.com/photoprism/photoprism/issues/65).

Acceptance Criteria:
* Experiment with Darktable and Adobe Photoshop / Lightroom to see how they use sidecar files
  * What fields are commonly used? 
  * What metadata model(s)?
  * Do you need plugins / special settings?
* Create a matrix showing what fields/models are used/supported by which application/tool (Photoshop, Lightroom, Darktable and others, see [Converting RAW to JPEG](https://github.com/photoprism/photoprism/wiki/Converting-RAW-to-JPEG)
* We might use the open-source [trimmer-io/go-xmp](https://github.com/trimmer-io/go-xmp) package to work with XMP files, so it would be good to know if our use case if covered by that library. Trimmer seems to be a video app, so they might have a different focus.
* Please document your results in our wiki: https://github.com/photoprism/photoprism/wiki/XMP

---

### List of XMP metadata models supported by [go-xmp](https://github.com/trimmer-io/go-xmp)  ###

**Included metadata models**

* XMP DublinCore (dc)
* XMP Media Management (xmpMM)
* XMP Dynamic Media (xmpDM)
* XMP Rights (xmpRights)
* XMP Jobs (xmpBJ)
* XMP Paged Text (xmpTPg)
* EXIF v2.3.1 (exif, exifEX)
* Adobe Camera Raw (crs)
* Creative Commons (cc)
* DJI Drones (dji)
* ID3 v2.2, v2.3, v2.4 (id3)
* iXML audio recorder (ixml)
* iTunes/MP4 (itunes)
* ISO/MP4 (mp4)
* Quicktime (qt)
* PhotoMechanic (pm)
* Tiff (tiff)
* Riff (riff)
* Photoshop (ps)
* PDF (pdf)

**Metadata models available under commercial license**

* ACES Image Metadata
* AEScart
* ARRI Camera Metadata
* ASC CDL
* EBU Broadcast WAV
* Getty Images
* IPTC Core 1.2, IPTC Extension 1.3, IPTC Video Metadata 1.0
* Plus Licensing Metadata
* SMPTE DPX Image Metadata
* SMPTE MXF Metadata
* OpenEXR Image Header Metadata
* XMP Media Production SDK (Universal Metadata Container)

**Comment by lastzero** [comment]
I've met the author of [go-xmp](https://github.com/trimmer-io/go-xmp) in Berlin and think we can build upon this library. Next step would be to see how it can be used together with [go-exif](https://github.com/dsoprea/go-exif) and evolve our exif related code into a general metadata abstraction.

Idea: Write all Exif data into XMP files (while or before indexing) and then use XMP as our primary source of truth - this will also enable us to keep metadata in sync with Lightroom & Photoshop. Maybe @dsoprea can help with that, see https://github.com/photoprism/photoprism/issues/21#issuecomment-568534714.

**Comment by dsoprea** [comment]
@lastzero 

Please clarify "use XMP as our primary source of truth". Are you saying that XMP would be the common internal format used within Photoprism?

It looks like _go-xmp_ already decodes EXIF. You're suggesting that I just help to integrate it? Since Photoprism is already cherry-picking values of interest into Photoprism-specific structures, I imagine that it'll be about the same level of effort as it was to integrate _go-exif_.

**Comment by lastzero** [comment]
**go-xmp** supports Exif within XMP. XMP can include many types of data, not just Exif... We use **go-exif** to extract Exif from image files. So when we find the same fields with different values e.g. in a JPEG and a XMP sidecar file, we need to decide what to use and what to ignore. Since it's probably faster to read Exif from XMP, it makes sense to always write all Exif information to XMP so that re-indexing becomes faster and we have a backup in case the database crashes or the user simply does not know how to create a SQL backup.

In addition, I suspect Lightroom doesn't change Exif data in image files when you edit it but uses XMP to store new or changed information. But that needs to be tested. Ideally, our users can use Lightroom and PhotoPrism in parallel and keep data in sync with XMP.

**Comment by dsoprea** [comment]
Why use XMP as your metadata backend rather than a data-specific format, such as JSON, protobuf, etc..?

**Comment by lastzero** [comment]
Because it's the standard for image sidecar files. Why invent something new? With XMP, we're compatible with Adobe.

**Comment by dsoprea** [comment]
Got it.

**Comment by lastzero** [comment]
Updated documentation: https://github.com/photoprism/photoprism/wiki/XMP

**Comment by lastzero** [comment]
Think we have a better understanding now, we can close this. We need more code next.
