### ISSUE TITLE
Significant (~1 sec) freeze when scrolling photos in mosaic view

### ISSUE THREAD

**Issue by olegelantsev** [photoprism/photoprism#680]
Hi, 

I noticed that even on a small (<1K photos) data set, scrolling doesn't work smoothly. Frontend requests a set of photo metadata with a query, so that it can build mosaic view and request photos:
```
photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=&public=true&quality=3&photo=true
```
As the user keeps scrolling, frontend will reach out for another set of 60, and these requests take significant amount of time for a scrolling operation. On the following screenshot you can see the response times:
![photoprism_latency](https://user-images.githubusercontent.com/7139119/101265313-ab3b6680-3745-11eb-89cd-36bc07970e7c.png)

I guess something could be wrong with my configuration. I use docker-compose with SQLite DB on desktop hardware (Intel Core i7-6700 CPU @ 3.40GHz and NVME and enough RAM). But then I checked the SQL queries in that method: there are multiple JOIN's, I suspect, that take a lot of time. Just for my curiosity, I made a query without any JOIN that returns next 60 photos, and it returned result in <50ms (I took that test a while ago, don't have exact numbers at hand). And if adding even a single JOIN already makes response time >100ms even on a table with <10K records. Current query of Photoprism indeed took between 500ms and 1s (sorry, don't have precise numbers, but can try it out again if needed).

Do you know if the DB configuration can be adjusted to improve the performance or setup is somehow wrong? Did anyone see such latency when scrolling?

**Comment by lastzero** [comment]
MariaDB scales better and is much faster, as documented in our example config. Sqlite is OK for small collections like our demo.

**Comment by lastzero** [comment]
Joins are no problem for SQL databases. That's a myth.

**Comment by lastzero** [comment]
See #558 and #392

**Comment by olegelantsev** [comment]
Indeed, thanks for pointing out. Switched to Maria DB and `/photos?...` method response become <100ms.
