### ISSUE TITLE
Stack Sequence not working

### ISSUE THREAD

**Issue by Marco1097** [photoprism/photoprism#681]
After unchecking "Stack Sequence" and indexing the library (for the first time), some photos are still grouped, is there a reason?

Also I can't find a way separate them manually, what can I do?

**Comment by lastzero** [comment]
This is not an undo button. Existing photos won't be modified. Simply start with a fresh database and re-index if you're new to PhotoPrism and don't have any valuable data yet.

**Comment by Marco1097** [comment]
@lastzero I tried to delete the database and redo the index but nothing has changed

**Comment by lastzero** [comment]
I see, in that case it might be the "regular" stacking of pictures with the exact same unique id or place & time? Can you see what the files have in common?

**Comment by Marco1097** [comment]
File 1: 2020-12-05_15-42-39_5885.jpg UID:FQKXIA82II6QTFJ4
File 2: 2020-12-05_15-42-39_5886.jpg UID:FQKXIA814GNE5HIL
File 3: 2020-12-05_15-42-39_5887.jpg UID:FQKXIA8D2FOJJZF3
File 4: 2020-12-05_15-42-39_5888.jpg UID:FQKXIA817CZHP6ZI

**Comment by lastzero** [comment]
At least these JPEGs share the same timestamp and prefix, so the stacking doesn't seem to be completely wrong.

You should be able to disable stacking almost completely (except for actual sidecar files) in `settings.yml` using these values for `sequences` and `stack`:

```
index:
  sequences: false
  stack: false
```

Note that there is not UI checkbox yet and it is experimental, the name of the value may change in the final release.

**Comment by Marco1097** [comment]
> ```
> index:
>   sequences: false
>   stack: false
> ```
Thanks, it worked

> Update: We're also going to disable "stack sequences" by default in the final release.
The files have the same timestamp because they were downloaded simultaneously from Telegram, but they are completely different photos. Being that many people use PhotoPrism as an alternative to Google Photos it could be a common problem so I like the idea that in the final version it is disabled by defautl

**Comment by lastzero** [comment]
Next build comes with UI checkboxes for this 🐳
