### ISSUE TITLE
Navigation: Counts not readable on small screens or when count is too large

### ISSUE THREAD

**Issue by Marco1097** [photoprism/photoprism#682]
When the height of the windows is less than the height of the left menu, some numbers are cut and are not readable at 100%

Firefox Browser 83.0 (64 bit)
Tested on the demo website and on the latest docker release

![immagine](https://user-images.githubusercontent.com/23193188/101290022-2f522480-3800-11eb-9271-52b9c5af0935.png)
![immagine](https://user-images.githubusercontent.com/23193188/101290067-66283a80-3800-11eb-8947-913ce8f74a94.png)

**Comment by lastzero** [comment]
Thanks for reporting this! Noticed this already, but guess it's good enough for a first release anyway. Also issues when you happen to have millions of photos as space runs out. Need to shorten the counts.
