### ISSUE TITLE
Albums not matching actual folder structure

### ISSUE THREAD

**Issue by jrc1883** [photoprism/photoprism#684]
Photoprism shows I have more than 13,000 folders in the albums tab. I may have when I originally imported things but I do not anymore. I went through a photo re-organizing and condensed to folders based on year only...so like 20 folders or so. I did a complete re-index in photoprism but still see >13,000 folders. How would I reconcile this?

**Comment by lastzero** [comment]
Improved it, you'll need to index again (but not complete, so it should be fast). New Docker build available for testing soon!
