### ISSUE TITLE
two different images why came into a same stack?

### ISSUE THREAD

**Issue by incity** [photoprism/photoprism#687]
![image](https://user-images.githubusercontent.com/7846605/101497503-053a6700-39a6-11eb-998e-ec5c49b1a1c7.png)

**Comment by graciousgrey** [comment]
Images might be stacked for one of the following reasons:
- Photos have been taken at the same time & place
- Photos have the same unique id
- Related Filename 

You can change the stacking behaviour in the settings:
![stackingOptions](https://user-images.githubusercontent.com/15210372/101508837-6e0aea80-3978-11eb-8d58-f2bc04f088c6.png)

**Comment by incity** [comment]
why i can't see these configurations?

**Comment by graciousgrey** [comment]
Looks like you need to update to the latest version.

**Comment by lastzero** [comment]
This was added yesterday so that users can adapt stacking behaviour to their needs.

**Comment by incity** [comment]
ok thanks
