### ISSUE TITLE
Using existing mariadb database doesn't work, container hangs loading config, no logs

### ISSUE THREAD

**Issue by bpgerber** [photoprism/photoprism#689]
Hello, I am trying to run photoprism with mariadb through a Traefik reverse proxy with authentication.

I tried making a whole docker-compose based on your example, but that blew up and didn't work, so I thought I would take it one step at a time and use your example locally, then access my database, then try to put it behind traefik.

I got it to load up completely default not using mariadb, but then I switched using the DRIVER and DSN environments to: 

`"photoprism:Ph0topr!s@tcp(mariadb:3306)/photoprism?charset-utf8mb4.utf8&parseTime=true"`
also tried replace with photoprism.web, but I'm not sure how your code handles it. It didn't work

I tried both not having the photoprism database setup as you seem to have it auto-create (or at least don't specify to people who may not know that they should), but either way, the db I have setup currently is 10.5.8. I have the utf8mb4_unicode_ci (essentially using the same structure as nextcloud), and have the user and password specified as here (I have tried a few different ones to see if it was a parsing error).

I have debug turned on, besides this line, and connecting to my docker network with necessary network setup (working for many other containers)

```
  UID: $PUID
  GID: $PGID
...

networks:
  - web
```
The docker logs are completely emply except for 

`time="2020-12-09T02:00:22Z" level=debug msg="config: loaded settings from /photoprism/storage/settings/settings.yml "`

Which seems to hang the photoprism process trying to load the settings. When going into the container bash with docker exec -it photoprism_photoprism_1 bash, I get in, and it will kick me out after about 3 minutes despite being in use.

Anyway, I try to do a status and it says `"Could not connect to 0.0.0.0:2342"`, and I tried to do a reset and it hung on loading the config and kicked me out again.

Any ideas? I really want to get this running because it looks like a fantastic app! Thank you in advance!

**Comment by alexislefebvre** [comment]
Another user used an existing database in https://github.com/photoprism/photoprism-docs/pull/33

**Comment by bpgerber** [comment]
Thanks! I looked at his issue and the MYSQL documentation he attempted to merge. It definitely would be helpful for the database setup. I just double checked my phpmyadmin, and the collation, charset, and privileges are all set at specified values.

I'm not actually sure if it is related because it has literally 1 line in the docker logs. 

`time="2020-12-09T02:00:22Z" level=debug msg="config: loaded settings from /photoprism/storage/settings/settings.yml "`

It seems like an internal program problem that it is unable to parse the inputs. Has photoprism implemented support for all the new docker syntax like network definitions? If settings are being loaded successfully, what is the next step in the flow where it is failing?

**Comment by lastzero** [comment]
We don't parse Docker config files, `settings.yml` is our own file for storing user sessions. Hard to guess what is going wrong here why you say "blew up". I guess something with permissions...

**Comment by bpgerber** [comment]
I switched just those two lines back to sqlite and everything started loading and debugging:

```
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (7): 
        - minimal.tmpl
        - rainbow.tmpl
        - share.tmpl
        - 
        - app.tmpl
        - favicons.tmpl
        - index.tmpl

[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] GET    /favicon.ico              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (3 handlers)
[GIN-debug] HEAD   /favicon.ico              --> github.com/gin-gonic/gin.(*RouterGroup).StaticFile.func1 (3 handlers)
...
```

for some reason, when I add that line, everything hangs. I'm guessing it tries to access the database, fails, but doesn't have an output because it isn't an expected failure point?

[This CVjoint docker compose file uses SQLite](https://github.com/CVJoint/docker-compose/blob/master/ymlfiles/photoprism.yml) but it also defines the directory for the database? Is it necessary to define the full database path as a volume?

Maybe it is because my mariadb isn't running with innodb_rollback_on_timeout set because the db is already spun up and running, but all of the other variables are set correctly, including tx_isolation. At this point I'm not sure why it just hangs with no errors. It has to be database-related though.

**Comment by lastzero** [comment]
You can set a container name and use a common network, so that you don't have to use photoprism_photoprism_1 to connect.

**Comment by bpgerber** [comment]
I thought that was what I was doing (maybe I got the syntax wrong):

`"photoprism:Ph0topr!s@tcp(mariadb:3306)/photoprism"`

am accessing container named "mariadb" on port 3306 to database "photoprism" with username "photoprism" and password "Ph0topr!s"

then this container is on the common "web" network that is shared between them.

**Comment by lastzero** [comment]
You may now use individual environment variables to configure your database connection instead of trying to get the `DSN` right. Here's the output of `photoprism help` since it's not in our docs yet (description needs a little bit more work, but not today)

```
   --database-driver NAME                   database driver NAME (sqlite or mysql) (default: "sqlite") [$PHOTOPRISM_DATABASE_DRIVER]
   --database-dsn DSN                       sqlite file name, DSN is optional for mysql [$PHOTOPRISM_DATABASE_DSN]
   --database-server HOST                   database server HOST, port is optional [$PHOTOPRISM_DATABASE_SERVER]
   --database-name NAME                     database NAME (default: "photoprism") [$PHOTOPRISM_DATABASE_NAME]
   --database-user NAME                     database user NAME (default: "photoprism") [$PHOTOPRISM_DATABASE_USER]
   --database-password PASSWORD             database user PASSWORD` [$PHOTOPRISM_DATABASE_PASSWORD]
```

If no server is set, PhotoPrism still parses the `DSN`. `PHOTOPRISM_DATABASE_SERVER` may include a port, like `mariadb:3306` in your case. Since 3306 is the default port, you may also skip it. No changes for SQLite users.

**Comment by bpgerber** [comment]
I just pulled the new version, it shows in the help file now, awesome!

I put this in my compose:

#PHOTOPRISM_DATABASE_DSN: "......"
PHOTOPRISM_DATABASE_SERVER: "mariadb"
PHOTOPRISM_DATABASE_NAME: "photoprism"
PHOTOPRISM_DATABASE_USER: "photoprism"
PHOTOPRISM_DATABASE_PASSWORD: "Ph0topr!s"

I still get this output:

`time="2020-12-13T16:34:13Z" level=fatal msg="Error 1045: Access denied for user 'photoprism'@'photoprism_photoprism_1.web' (using password: YES)"`

**Comment by lastzero** [comment]
Are you 100% sure the database server name is `photoprism_photoprism_1.web` and the parameters are correct? You may verify this by opening a terminal and use the `mysql` command to manually connect to your database from within the container:

```
docker-compose exec photoprism bash
```

or directly via

```
docker-compose exec photoprism mysql -h HOST -P PORT -u USER -p DATABASE
```

**Comment by bpgerber** [comment]
I think I am misunderstanding something. My database name is "photoprism.web", that's what I thought `DATABASE_NAME: "photoprism"` was specifying like how it works in nextcloud. Is it not allowed for photoprism to have a different database name besides "photoprism_photoprism_1"? Does the database name have to be equal to the photoprism container name?

**Comment by lastzero** [comment]
You can use any schema name, but photoprism_photoprism_1 looks like an internal Docker host name and not a schema name. So I was wondering if the database schema name and database server host name got mixed up.

**Comment by alexislefebvre** [comment]
It looks like the error 1045 means that the parameters are right and the connection is working, but that the user doesn't have the rights on the database.

**Comment by bpgerber** [comment]
Alright, thanks, so while I had done some searching before creating this I had found some common 1045 reasons:

- Type error: Incorrect user-name or password.
- Accessing from the wrong host.
- User doesn’t exist on the server.
- A mix of numeric and name-based hosts.

I assumed it was "user doesn't exist on the server" because of the confusion with the names. However, a "photoprism" user does exist on my server, the credentials are correct (I deleted and remade the user with the correct password just to be sure), and it has full permissions for the "photoprism" database.

Other containers can reach the server and log in to their respective databases, but could it be a docker issue? I'm not sure what the mix of numeric and name-based hosts means.

Sorry I'm taking so much of your time.

**Comment by lastzero** [comment]
Before we continue guessing: Were you able to successfully connect from within the container using the mysql command as described above?

**Comment by bpgerber** [comment]
apologies

`docker-compose exec photoprism mysql -h mariadb -P 3306 -u photoprism -p photoprism`

returned a password prompt where I tried putting in my "photoprism" db password, my mysql root password, and even my nextcloud db password. It always returned with:

`ERROR 1045 (28000): Access denied for user 'photoprism'@'photoprism_photoprism_1.web' (using password: YES)`

**Comment by lastzero** [comment]
Yes, looks like an issue with your Docker config. When the original mysql client works, photoprism should work as well.

**Comment by bpgerber** [comment]
Yeah my mariadb config was wrong. I had to set the host as "photoprism_photoprism_1.web" with mysql in order to get it to allow. Speaking of, (kind of off topic) is their any way to change that? I was under the impression that the 

```
service:
  name:
....
```

Would set the name of the service, but I guess I don't know enough about docker because it doesn't seem to. I'll close this issue.

**Comment by alexislefebvre** [comment]
Do you use the same Docker network for PhotoPrism and the MariaDB database?

**Comment by bpgerber** [comment]
yes, same docker network (one called web), so I could get it to work with setting up the photoprism_photoprism_1 hostname in phpmyadmin for the user "photoprism"

**Comment by alexislefebvre** [comment]
Did you put photoprism and mariadb containers in the same `docker-compose.yml` file?

**Comment by bpgerber** [comment]
nope, this whole thread has been about accessing a previously made mariadb instance with photoprism.

(Multiple databases, one database server setup)

**Comment by alexislefebvre** [comment]
I recently had the same issue and I had to use the `external` option:

```yaml
networks:
    photoprism:
        external:
            name: mysql

```

So if the photoprism container is in the `photoprism` network and the mysql container is in the `mysql` network, we have to bind them like this. And photoprism should be able to use the `mysql` hostname.

**Comment by jedman14** [comment]
Quick note, I was having this same problem and this helped me fix it.  My MariaDB is not running in Docker and my photoprism was. My MariaDB was not allowing connections from anywhere except localhost.  This article helped me fix it. 
https://mariadb.com/kb/en/configuring-mariadb-for-remote-client-access/

**Comment by lastzero** [comment]
See also https://docs.photoprism.app/getting-started/troubleshooting/mariadb/
