### ISSUE TITLE
moments: near \"INNER\": syntax error (update folder dates) & (update album dates)

### ISSUE THREAD

**Issue by MwC-Trexx** [photoprism/photoprism#692]
I have created a docker container on a QNAP NAS running the latest version of their Container Station ("docker") platform.

When I am doing an import of photo's, I am seeing these errors flagged in the log.

```
time="2020-12-10T03:08:04+08:00" level=error msg="moments: near \"INNER\": syntax error (update folder dates)"                              
time="2020-12-10T03:08:04+08:00" level=error msg="moments: near \"INNER\": syntax error (update album dates)"                               
time="2020-12-10T03:08:04+08:00" level=info msg="Import completed in 34 s"                                                                  
```

Let me know what additional information you may need to troubleshoot this.

**Comment by lastzero** [comment]
What database are you using?

**Comment by lastzero** [comment]
Should be fixed with the next build. Only affected SQLite. Disabled the query there until we have a working alternative.

**Comment by MwC-Trexx** [comment]
Embedded SQLlite.

**Comment by MwC-Trexx** [comment]
> What database are you using?

Embedded SQLite
