### ISSUE TITLE
Search by filename not working

### ISSUE THREAD

**Issue by dekiesel** [photoprism/photoprism#694]
Using pp 20201209 (pulled from dockerhub) "Search by filename" isn't working.

Example: My collection contains 185 files. On disk one of those files is called `100_2550.JPG`, but when I type that into the search bar all 185 files in the collection are returned. I know the file is in the collection and when I open it->edit->Files->Name I can see the name `100_2550.JPG` in the row called "Name".

I don't know whether it worked in earlier versions.

**Comment by alexislefebvre** [comment]
What parameter did you type to search by filename?

According to the [doc](https://docs.photoprism.org/user-guide/organize/search/#search-filter), `name:"*100_2550*"` and `name:"100_2550.JPG"` should work. Or `original:"100_2550.JPG`. If you still don't see the photo, try these filters in the "review" section.

**Comment by dekiesel** [comment]
I have to shamefully admit that I overlooked that you have to type in `name:` too.... I am very sorry.

Can be closed.

**Comment by alexislefebvre** [comment]
No problem. :slightly_smiling_face: 

You should see a Close button at the bottom of this issue. If not, maybe repository settings block this.

**Comment by lastzero** [comment]
We also support `original:` and  `filename:`, depending on the use case. `name:` must not include the file path and extension, while `filename:` expects the relative path and full file name. All are case sensitive and you can use a `*` wildcard at the end.

**Comment by alexislefebvre** [comment]
[`filename:"*Peacock-Tubingen*"`](https://demo.photoprism.org/photos?view=cards&order=newest&q=filename%3A%22%2aPeacock-Tubingen%2a%22) and [`name:"*Peacock-Tubingen*"`](https://demo.photoprism.org/photos?view=cards&order=newest&q=name%3A%22%2aPeacock-Tubingen%2a%22) but [`original:"*Peacock-Tubingen*"`](https://demo.photoprism.org/photos?view=cards&order=newest&q=original%3A%22%2aPeacock-Tubingen%2a%22) doesn't. Is it the expected behaviour?

**Comment by lastzero** [comment]
Yes, `original:` is only for files that were renamed e.g. while importing.

**Comment by alexislefebvre** [comment]
Thanks, I added it in docs in https://github.com/photoprism/photoprism-docs/pull/35
