### ISSUE TITLE
Remove dependency on fonts.googleapis.com

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#695]
When I use PhotoPrism, a request is sent to https://fonts.googleapis.com/css?family=Open Sans:400italic,700italic,400,700

I think that it would be better to not rely on a service owned by Google for these fonts.

**Comment by lastzero** [comment]
Interesting... probably included by Vuetify from their CDN for performance reasons...

**Comment by alexislefebvre** [comment]
I didn't found googleapis in the code. So it must be added by a dependency.

And I don't see this request on the [demo](https://demo.photoprism.org/photos), I don't understand why I only have when using my dockerized PhotoPrism.

**Comment by lastzero** [comment]
Maybe you can do a little research to figure out where it's included and how we can change this? Maybe the maps use it?

**Comment by alexislefebvre** [comment]
I can't reproduce it, it looks like it was caused by Firefox cache and
