### ISSUE TITLE
UX: Have a dark theme

### ISSUE THREAD

**Issue by fdw** [photoprism/photoprism#700]
I could not find a truly dark theme (light on dark), but I think it would be nice to have one.

**Comment by lastzero** [comment]
Moonlight and Onyx are our darkest themes currently. Many of our UI elements invert their contrast when selected. That makes it difficult to just use dark colors. We also have to change this logic, otherwise you have a black font on black background. All in all, this wasn't easy and important enough to delay our release. Might do this later though, when there is time and funding.

**Comment by lastzero** [comment]
That's how PhotoPrism looks in a dark desktop environment. The Onyx theme is pretty much dark and grey already, nothing that burns your eyes. Most "bright" screen area is covered by pictures. Those are not under our control... We've intentionally kept the UI grey to avoid bias in terms of darkness, brightness, or colors (unless you've chosen to use the Raspberry theme).

<img width="1100" alt="Screenshot 2020-12-13 at 02 19 51" src="https://user-images.githubusercontent.com/301686/102000638-bebc7380-3ce9-11eb-91f0-945cc6c4dbf5.png">

**Comment by lastzero** [comment]
As dark as it gets for now 😎

![darkness](https://user-images.githubusercontent.com/301686/102000899-73579480-3cec-11eb-9c12-e78d49070242.jpg)

**Comment by fdw** [comment]
Thanks for your efforts!

My idea was to have a theme that is really dark around the photos, as that often makes them look better. But I agree that it's not an important topic :)

**Comment by lastzero** [comment]
In fact, I've seen screenshots of users who had it all dark... maybe they've applied a patch locally and don't use other themes to avoid contrast issues (as mentioned above).

**Comment by alexislefebvre** [comment]
It would be awesome to have a theme that rely on the user's settings to enable dark mode automatically at night, see [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). It could be added to current themes.

**Comment by inthreedee** [comment]
@lastzero Feedback on the Shadow theme:
1. The initial loading screen is white and, ideally, would match the background of the chosen theme to avoid the bright white flash.
2. Darker!  Please consider a "Night" theme with a nearly black background for a slick darkroom vibe.

**Comment by lastzero** [comment]
Did you try the Vanta theme yet?

**Comment by inthreedee** [comment]
@lastzero Whups!  I somehow completely missed the switch to a multi-arch image and my instance hasn't updated in a while now. 😳  Vanta is great, and the loading screen flash is solved.  Thanks for all the hard work!  <3

**Comment by Richigeht** [comment]
Hey,
could we maybe get a photoprism dracula color theme? 
Or would this be doable if I become a higher level sponsor? (I have read that you could then put something on the feature request list, if this would be doable and feasible I would check out that option as I am currently only a „small“ sponsor)

**Comment by inthreedee** [comment]
Info on the theme being requested above: https://draculatheme.com/
It uses the MIT license.

**Comment by graciousgrey** [comment]
Feel free to open a new feature request for this :)
