### ISSUE TITLE
Bug: Videos save as jpg?

### ISSUE THREAD

**Issue by DillFrescott** [photoprism/photoprism#701]
Both direct download and webdav saves the video as an image. That's not what I want.

**Comment by lastzero** [comment]
If you download a video file via WebDAV you get an image? A file selector for web downloads should be on our roadmap otherwise. Same for raw and other non JPEG formats.

**Comment by DillFrescott** [comment]
Yep. It gives me an image of the thumbnail and it confused me haha.

Ok that's fine.

Is there anything I might have done in the config that's causing the video to turn into a jpg? It's fine when it's still on PhotoPrism, it shows up as a video, just not when I download it or do WebDAV.

**Comment by DillFrescott** [comment]
Or is there a way to exec into the container and change something till it can be properly fixed?

**Comment by lastzero** [comment]
No problem with downloading and playing videos via WebDAV whatsoever:

**Step 1: Copy to Desktop**
<img width="822" alt="Screenshot 2020-12-13 at 01 22 15" src="https://user-images.githubusercontent.com/301686/101999911-d859bd00-3ce1-11eb-940f-967e59f1d063.png">

**Step 2: Play**
<img width="1062" alt="Screenshot 2020-12-13 at 01 22 53" src="https://user-images.githubusercontent.com/301686/101999909-d263dc00-3ce1-11eb-84d2-200c5d00cd71.png">

**Comment by lastzero** [comment]
Note that we originally didn't plan to support videos. JPEG as default download format was meant for RAWs that most users can't properly use for most of what you're typically doing with a downloaded picture e.g. sharing, or watching on TV.

**Comment by lastzero** [comment]
Maybe you don't use WebDAV but our REST API? That's not the same. Or you downloaded a mp4.jpg thumb instead of the actual video?

**Comment by DillFrescott** [comment]
Hmmm. 

What I did was select the video by tapping in the lower right corner of the thumbnail.

Then the little circle with the 1 pops up at the bottom right of the page. I click that and then the green download button that extends from that menu.

It asks if I want to save a jpeg file. 

I'll look again to notice if it's a mp4.jpeg file and report back.

My WebDAV server is just

https://github.com/hacdias/webdav

This WebDAV server. It does the same thing as clicking the download button except I click the cloud and select the WebDAV server. Then when I check the WebDAV data folder it's a jpg.

**Comment by DillFrescott** [comment]
This was tested on my Windows 10 desktop as well as my iPhone using multiple browsers

**Comment by lastzero** [comment]
You don't need an extra WebDAV server, PhotoPrism is a WebDAV server:

https://docs.photoprism.org/user-guide/backup/webdav/

**Comment by DillFrescott** [comment]
You mentioned the api thing. This is the url of the jpeg from trying to download a video...




![image](https://user-images.githubusercontent.com/56714680/102000292-1dff9100-3cb4-11eb-9346-e35f8b25b8a5.jpeg)

**Comment by lastzero** [comment]
In addition, you can download all files in the files tab:

<img width="902" alt="Screenshot 2020-12-13 at 01 56 31" src="https://user-images.githubusercontent.com/301686/102000310-8d8e7400-3ce6-11eb-850b-f695e05b7681.png">

**Comment by lastzero** [comment]
> You mentioned the api thing. This is the url of the jpeg from trying to download a video...

Looks like the REST API... you can hack it, but you can as well use the download button in the dialog or connect via WebDAV...

**Comment by DillFrescott** [comment]
Ok. So I tried the download button and this is what I got

https://i.ibb.co/b60d9Ht/capture.jpg

**Comment by DillFrescott** [comment]
I must be doing something incorrectly

**Comment by DillFrescott** [comment]
Nevermind I just noticed theres a jpg and an mp4

**Comment by DillFrescott** [comment]
Both the same file but i guess its the sidecar thing?

**Comment by lastzero** [comment]
You are right in that there is a download format and size selector missing when you click download in the context menu or full screen photo viewer. But there are other ways, as described, to download all files.

**Comment by DillFrescott** [comment]
Ok. Thank you for the help!

**Comment by DillFrescott** [comment]
By the way, I accidently clicked unstack. How do I undo that? Because now the mp4 is not listed under files anymore :(

**Comment by lastzero** [comment]
There is no way to manually merge arbitrary files in our UI yet. You can make sure the files have the same base name (without extension), remove the Unstacked flag in the edit dialog settings tab (on the right), and then wait a little or re-index.

**Comment by DillFrescott** [comment]
Ok. Thank you

**Comment by lastzero** [comment]
You're welcome.
