### ISSUE TITLE
Darktable: Build fails because of unmet dependencies

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#709]
Docker builds currently fail because the Darktable package has unmet dependencies:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:

darktable : 
Depends: libexiv2-27 (>= 0.27.3) but it is not going to be installed
Depends: libilmbase25 (>= 2.5.3) but it is not installable
Depends: libjson-glib-1.0-0 (>= 1.5.2) but 1.4.4-2ubuntu2 is to be installed
Depends: libopenexr25 (>= 2.5.3) but it is not installable

E: Unable to correct problems, you have held broken packages.
```

**Comment by sesselastronaut** [comment]
I've to pick this up again, trying to install darktable 3.6.1-1 on Debian following [these](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable) instructions, unfortunately I get the following error:
```
The following packages have unmet dependencies:
 darktable : Depends: libexiv2-14 (>= 0.25) but it is not installable
             Depends: libicu63 (>= 63.1-1~) but it is not installable
             Depends: libilmbase23 (>= 2.2.1) but it is not installable
             Depends: libopenexr23 but it is not installable
```
I've libexiv2-27 installed:
```
Package: libexiv2-27
Version: 0.27.3-3+deb11u1
```
Any hint how to solve these dependencies on the current version very welcome.

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
This is happening again in the latest PhotoPrism docker image FYI @lastzero 

<img width="836" height="222" alt="Image" src="https://github.com/user-attachments/assets/e11e6fa6-1c17-40ff-b01f-e106907b0a8e" />

**Comment by thisIsNotTheFoxUrLookingFor** [comment]
@lastzero it seems that the script is setting the os target as 23.04 for the darktable repo, while the docker container has been bumped to 25.10. When I change the source file to 25.10 in `/etc/apt/sources.list.d/graphics\:darktable.list` and force apt update and apt upgrade, it properly installs the dependencies and upgrades darktable correctly.

I guess the Makefile here: https://github.com/photoprism/photoprism/blob/develop/scripts/dist/Makefile

Needs to be changed from 23.04 to 25.10 at lines 64 and 65

<img width="863" height="397" alt="Image" src="https://github.com/user-attachments/assets/9e8dae3a-34cd-4c84-8350-018a5684f8c0" />

<img width="882" height="391" alt="Image" src="https://github.com/user-attachments/assets/25d70e33-b07f-4303-bc9e-6ff0ba9f730a" />

<img width="1118" height="380" alt="Image" src="https://github.com/user-attachments/assets/5135592e-49fb-47df-b490-a8bbf1ae3cc6" />
