### ISSUE TITLE
Language dropdown: don't translate locales

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#712]
I think that it's easier to not translate locale options and instead show each locale in its own locale.

Examples:
- English
- Français

Wikipedia implements that:

> ![image](https://user-images.githubusercontent.com/2071331/102224818-b54c2a80-3ee6-11eb-9300-fbf59c420782.png)

See https://en.wikipedia.org/wiki/Photography for example

**Comment by lastzero** [comment]
Sounds like a good idea! Still users would need to know where the language settings dropdown is if they don't understand the current UI language...

**Comment by alexislefebvre** [comment]
Thanks, it works on the [demo](https://demo.photoprism.org/settings). :clap:

**Comment by lastzero** [comment]
![Screenshot 2020-12-16 at 14 50 19](https://user-images.githubusercontent.com/301686/102356876-0ecb5c80-3fae-11eb-86c1-da1ce700dfd3.png)

**Comment by alexislefebvre** [comment]
It looks like some translations may be removed, see https://github.com/photoprism/photoprism/pull/1470#discussion_r689753561

**Comment by graciousgrey** [comment]
@alexislefebvre you mean because there are translations for the language names? This should not affect the language dropdown, it shows each language name in it's own language independent from whether the string is translated or not :)

**Comment by alexislefebvre** [comment]
@graciousgrey Yes. So contributors are translating texts that won't be shown?

**Comment by lastzero** [comment]
Just the language names as they were shown before we implemented your suggestion. Need a little bit of time to think about it, may use it again in a different context. Currently working on facial recognition.

**Comment by lastzero** [comment]
(In fact they are used in JS code, but not shown in the UI.)

**Comment by alexislefebvre** [comment]
Is it dead code then ?

**Comment by lastzero** [comment]
We will decide when done with facial recognition. Limited resources.

**Comment by alexislefebvre** [comment]
Ok, I created another issue to keep track of it: #1480
