### ISSUE TITLE
Translations: Update Traditional Chinese 漢語

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#714]
We already have a frontend translation for traditional chinese.
At the moment the backend translation contains simplified chinese.

**Acceptance Criteria:**
Update backend translations
* Run make generate
* Open the /assets/locales/zh_tw/default.po file with Poedit
* In the Poedit menu click "Catalogue" --> "Update from POT File" --> select the messages.pot file from /assets/locales/
* Now you can start adding the missing translations
* Once your done save the changes in the default.po file

**Comment by lastzero** [comment]
Added and automatically translated missing strings for all languages today. Needs human review and probably rework.
