### ISSUE TITLE
Bounded thumbnail cache

### ISSUE THREAD

**Issue by williewillus** [photoprism/photoprism#725]
I've set up an instance so far on my family's photos and things seem to be working great. However, I have quite a few photos (600G and counting at the time of writing), and pre-generating thumbnails for all of that seems to be wasteful, when not all 600G of that content is expected to be "hot".

On the other hand, not generating thumbnails can strain the server when trying to browse.

It would be nice to have a bounded thumbnail cache that is not to exceed some configurable size or amount of images, using something like LRU or ARC to evict thumbnails. I imagine a cache of several gigs would be enough for a family NAS with moderate traffic, considering the fact that it's likely a small set of photos receive the majority of traffic.

A clunky solution in the meantime is to reduce the thumbnail sizes, but you would have to keep decreasing it as the data size continues to grow. It would be better to have a fire-and-forget option.

If this already exists, let me know :)

**Comment by lastzero** [comment]
When you do image classification with TensorFlow, you need thumbnails anyway - even if you don't view them at the end. Of course you can throw them away and recreate when reindexing, but I can barely imagine a storage price that would justify this overhead? Even 30% of 600 GB are just 200 GB. Most servers have 4 TB+ disks, even notebooks often have 1 TB or more nowadays.

**Comment by lastzero** [comment]
Why don't you limit the size of static images and use dynamic previews for larger sizes > 720px?

**Comment by williewillus** [comment]
Ah okay, keeping dynamic previews while limiting the default thumbnail size makes sense. I also didn't know the classifiers needed thumbnails anyways. I'll try a 720px limit and see how it works. Thanks!
