### ISSUE TITLE
People: DeepStack go

### ISSUE THREAD

**Issue by ghost** [photoprism/photoprism#728]
I wish I knew how to use golang.. I came across DeepStackGo with is DeepStack for the golang

seems like it would make face identification simple. Can outline faces, add to the model and then build on finding the same taught ppl in other photos

**Comment by alexislefebvre** [comment]
Could you please share a link to this library? I found one with this name but it looked unmaintained.

There already is an issue about face detection: #22

**Comment by oziee** [comment]
https://golang.hotexamples.com/examples/deepstack/DeepStack/Get/golang-deepstack-get-method-examples.html

https://github.com/johnolafenwa/deepstackgo

**Comment by alexislefebvre** [comment]
Does it need to send photos to an external service to identify people?

**Comment by oziee** [comment]
No.. shouldn’t.. would use DeepStack locally

**Comment by alexislefebvre** [comment]
My bad, I misinterpreted the word “client” in the project description.

**Comment by graciousgrey** [comment]
Thanks for investigating :) We will start implementing Face recognition in January!

**Comment by francescocarzaniga** [comment]
@graciousgrey Offering DeepStack as an alternative to TensorFlow as well would be absolutely amazing. Tensorflow is a **major** pain in the butt to compile, and being able to connect Photoprism to a remote DeepStack server would be massive for me and, I believe, many others as well.

**Comment by jurgenhaas** [comment]
I have integrated DeepStack with Home-Assistant earlier this week and I'm amazed how easy that was. It is so powerful, not only for face recognition but also for object and scene recognition. And as it runs locally with zero to none configuration effort, it would be much preferred to TensorFlow, because I don't want to use any of those services at all.

Their API is super slick and it should be very simple to integrate that into PhotoPrism. I'd be interested to help with this, if that's what you're looking for.

**Comment by jurgenhaas** [comment]
Ah, here is a link to their docs: https://docs.deepstack.cc

**Comment by kn100** [comment]
It would be super ultra cool (and I am not necessarily requesting this, this would be a large undertaking!) if something like deepstack could run on my powerful desktop, which is not on all of the time, and when my desktop gets switched on Photoprism would see this and automatically send stuff over to be labelled. That way, you get past the fact Photoprism (which I want to be always available) is running on low power hardware, without having to have a high power image classification server running 24/7!

**Comment by robmarkcole** [comment]
Deepstack can be run on a [Jetson nano](https://developer.nvidia.com/embedded/jetson-nano-developer-kit), which is low cost hardware. The combo of deepstack and photoprism would make a nice low cost & always on service

**Comment by rahul003** [comment]
Is there any specific reason why Pigo was picked over Deepstack for this (https://github.com/photoprism/photoprism/issues/22)? I was wondering if I should look into this further for Photoprism

**Comment by lastzero** [comment]
To reduce the number of dependencies. We would like to provide home users with a single binary instead of an enterprise micro-service architecture. Also we love the challenge. We may later add support for external services for advanced users.

**Comment by janstadt** [comment]
Just a shout out for another service called double-take: https://github.com/jakowenko/double-take Claims to be a unified API that supports multiple detectors for face recognition/training/etc. Learned about it via frigate NVR but it might be cool to leverage the API in case things change in the future and you want to choose a different detector.

**Comment by lastzero** [comment]
I am closing this issue as DeepStack does not seem to be maintained anymore:

- https://github.com/johnolafenwa/DeepStack

Also note that we have started working on [`photoprism/photoprism-vision`](https://github.com/photoprism/photoprism-vision), which allows us to integrate additional AI/ML models through a REST API.
