### ISSUE TITLE
Search / Original file name

### ISSUE THREAD

**Issue by Sherlock1979** [photoprism/photoprism#730]
Hi,

I couldn't find a way to search for the (original) file name. My photos are already organised in folders and named in a way I like them so I just index my originals. It would be really helpful if I could find a file just by searching for its file name.

Thanks for considering.

**Comment by lastzero** [comment]
Do you type in the full file name do perform a search? Keywords in file names are indexed, you can also search for exact matches or with wildcard using the name, original, and filename search filters.

**Comment by lastzero** [comment]
In addition, you can search for folders using the path filters like `path:2002`

**Comment by Sherlock1979** [comment]
Now I tried the full file name without extension. I also tried it with the extension. And also just a part of the filename encloswd with asterisks.

Search always returns "more than 50 results". I tried random characters and still got 50+ results.

**Comment by Sherlock1979** [comment]
Does Photoprism trim numbers from the search? My filenames are mostly numbers and I guess that may be the problem. E.g. 20181229_131541_PC291027. Is there a chance that it only searches for "PC"?

**Comment by lastzero** [comment]
I'm with my family right now. Can give you more specific examples that work on our demo tomorrow.

We "trim" numbers from words in the full TEXT search for the obvious reason: The index contains words, not numbers as it is not a number search.

You can still use the filters mentioned to perform a search for the EXACT name or prefixes using a * wildcard. Note that the search is case sensitive.

**Comment by lastzero** [comment]
This will search for file names containing numbers:

https://demo.photoprism.org/photos?view=cards&order=name&q=name%3A2003%2a&public=true&quality=3

**Comment by lastzero** [comment]
Docs: https://docs.photoprism.org/user-guide/organize/search/

**Comment by Sherlock1979** [comment]
Thank you. I have read the documentation, even checked the fronend api pages. But for some reason I could not find it. Sorry I missed the above page. It's so obvious. Thanks for your help and support. Keep up the great work. 👍
