### ISSUE TITLE
Auto Capitalization after Apostrophes

### ISSUE THREAD

**Issue by anaxmedia** [photoprism/photoprism#737]
It seems like indexing is auto-capitalizing letters after apostrophes. In the screenshot below you can see the file path folder is "Boston New Year's" with a lowercase "s" however the generated folder name is changing it to "Boston New Year'S" with an uppercase "S".

![image](https://user-images.githubusercontent.com/7167565/103031910-c7ece200-452c-11eb-9364-b326221318f1.png)

**Comment by lastzero** [comment]
Thanks for reporting this!

**Comment by lastzero** [comment]
Shouldn't happen according to our tests... Might be a frontend issue...

**Comment by lastzero** [comment]
Are you sure this a regular ' apostrophe or might it actually be something similar like ` ?

**Comment by anaxmedia** [comment]
Definitely a regular apostrophe and not a `. Read-only mode pulling from a path on my nextcloud server. I SSH'd into the files directory to confirm on there as well:

"Boston New Year's" is how it appears.

**Comment by lastzero** [comment]
Going to take another look at this after Christmas 🎄

**Comment by lastzero** [comment]
Excellent catch! Found it. Note that this fix won't update titles of already indexed folders.
