### ISSUE TITLE
Folders disappeared after removing album

### ISSUE THREAD

**Issue by oscar-b** [photoprism/photoprism#738]
Here is what I think happened:

1. Create album from folder (select a folder under Folders, click Add to album)
2. Delete the album
3. The original folder album (?) is deleted as well as the album.

Wouldn't it make sense to not being able to delete folders (or are they just auto created albums?)

Possibly related to #684 ?

**Comment by lastzero** [comment]
Not related to #684. I'm going to test this.

Note: If you delete pictures within a folder, they are moved to archive. If no more pictures are left, the folder is hidden from the folder list as it is empty. Removing pictures from a manually created album is different and should not affect folders or other albums.

**Comment by lastzero** [comment]
Yes, folders are "just" auto created albums. Think of them as a search filter.

**Comment by lastzero** [comment]
Can't confirm your observation.

Step 1: Add folder contents to album

<img width="1224" alt="Screenshot 2020-12-24 at 11 59 31" src="https://user-images.githubusercontent.com/301686/103085151-1b206c80-45e1-11eb-9389-1887c3ac843c.png">

Step 2: Remove album

<img width="1224" alt="Screenshot 2020-12-24 at 11 59 46" src="https://user-images.githubusercontent.com/301686/103085113-fcba7100-45e0-11eb-8239-82689da8430b.png">

Step 3: Folder still there

<img width="1224" alt="Screenshot 2020-12-24 at 12 00 13" src="https://user-images.githubusercontent.com/301686/103085034-d1d01d00-45e0-11eb-8d37-f3b82362e135.png">

**Comment by lastzero** [comment]
Disabled the delete button so that users don't click it accidentally. Thought some users might report it as bug if they can't hide unwanted folders, momentan or months this way, but you are are in that it may cause confusion.

**Comment by lastzero** [comment]
I'll close this for now. Let us know if this happens again!

**Comment by oscar-b** [comment]
I will try to reproduce it on a clean install tonight.
