### ISSUE TITLE
Settings available even though PHOTOPRISM_SETTINGS_HIDDEN is set

### ISSUE THREAD

**Issue by oscar-b** [photoprism/photoprism#739]
Even though `PHOTOPRISM_SETTINGS_HIDDEN` is set to true, "Settings" is displayed in the menu with sections "General" / "Library" / "Sync". I also have `PHOTOPRISM_PUBLIC` and `PHOTOPRISM_READONLY` set.

Are these settings supposed to be global or per user?

Version: `PhotoPrism® 201222-b433c630-Linux-x86_64`

**Comment by lastzero** [comment]
As announced on Twitter and in the chat, this is one of the config options that was renamed: It's now PHOTOPRISM_DISABLE_SETTINGS. See also docs and example config. Options that disable something now all start with disable.

**Comment by lastzero** [comment]
Docs: https://docs.photoprism.org/getting-started/config-options/

**Comment by oscar-b** [comment]
Sorry, was using an "old" `docker-compose.yml` file :)

**Comment by lastzero** [comment]
Just went through all examples to make sure everything is clear, and also added a command reference 👍
