### ISSUE TITLE
Floating button misaligned on Firefox

### ISSUE THREAD

**Issue by lerenn** [photoprism/photoprism#74]
Hi there,

There is some misalignment on Firefox with the floating button on bottom right.
This doesn't seem to happen with Chromium (I don't really know for other web browsers, Linux here).

![done](https://user-images.githubusercontent.com/10376004/49109985-7eb5ff80-f28c-11e8-93f4-f95956575f57.png) 
After fix on the left, before fix on the right

Regarding [this issue](https://github.com/vuetifyjs/vuetify/issues/5741) on Vuetify, it's just two lines in CSS that are not in the correct order. In PhotoPrism, those lines are also not in the correct order.

Merge request on its way! :)

**Comment by lastzero** [comment]
Works on Firefox, Chrome & Safari (OS X). Thank you for fixing this!
