### ISSUE TITLE
"metadata: runtime error: slice bounds out of range" during re-indexing

### ISSUE THREAD

**Issue by Noschvie** [photoprism/photoprism#740]
```
 Warning
24. Dezember 2020, 00:30:11 MEZ
metadata: runtime error: slice bounds out of range [:13591] with capacity 13583 in _MG_0831.JPG, starting brute-force search (parse jpeg) 
```
get a lot of these messages during indexing of originals mapped from Synology NAS.
Any idea ?
Thanks

**Comment by lastzero** [comment]
Ignore them, these are coming from one of our Exif libraries when a file can not be parsed properly e.g. because of non-standard headers. It's just a warning, not a problem you need to take care of - other than using cameras that comply with standards in the future.
