### ISSUE TITLE
Mobile: Enable auto-rotate to view photos in landscape mode

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#744]
This is more of a question than an issue.
When I view PhotoPrism on a smartphone (android), portrait photos are displayed correctly, using the entire screen.
On the other hand, this is not the case for landscape type photos, even if you have switched to screen rotation mode and you turn the phone.
Is this normal? Am I doing it wrong?

**Comment by lastzero** [comment]
Might need some extra work on our side so that they are properly rotated.

**Comment by jean-louis67** [comment]
Thank you so much. Right now I will stop torturing my phone!

**Comment by lastzero** [comment]
Should be fixed with the next release / build, currently available in preview: a2155566170ab82d9ba491b9d052d567f5b886bd

**Comment by lastzero** [comment]
Successfully tested with PhotoPrism installed as app on the home screen via *Chrome > Install PhotoPrism...*

Haven't been able to rotate the Chrome browser itself on my Android phone though - not sure why.

**Comment by jean-louis67** [comment]
Sorry not to have reacted earlier. I did not immediately understand whether it was an android specific application or not. I understand that this is just adding an icon to easily access the web application in Chrome, which I was already doing.
Indeed in these conditions, there is still no rotation of the screen. May be I did not get you correctly.
However, I tried with another browser, in this case Qwant, which was already installed on my phone. And there, bingo it works! But it was not so fluid.
Then I did another successful try by installing Firefox. I went full screen, scrolled through photos, turned and flipped the phone based on the photo and it was still the expected behavior.
You can then install Firefox opening PhotoPrism on the home screen, but this is not essential for the subject.
So we can, it seems, conclude that the problem is on the client side and not on the PhotoPrism side.

**Comment by lastzero** [comment]
![Screenshot_20210113_084031_com android chrome](https://user-images.githubusercontent.com/301686/104421025-0baa9880-557b-11eb-87cf-aafc4dce6a24.jpg)

Just took this on Android from our demo. Try remove the icon from home screen and install it again using Chrome. 

Should look like this:

![Screenshot_20210113_084227](https://user-images.githubusercontent.com/301686/104421201-53c9bb00-557b-11eb-9069-f8afa3ca5b64.jpg)

**Comment by jean-louis67** [comment]
Thank you! It works.
I have no idea why just recreating the icon fixes the problem, but whatever. Ah, that's magic, that's all!
I think this ticket is now eligible for closure!
