### ISSUE TITLE
Index shorter keywords in languages like Chinese

### ISSUE THREAD

**Issue by cathaysia** [photoprism/photoprism#746]
It seem that photoprism ask search keyword's length >=3? But two word is enough is some case, Chinese especially. More, one word is enough some case. 

Such as : 桥 = bridge, 船 = boat, etc.

Can I disable the limit of search keyword?

**Comment by lastzero** [comment]
Instead of adding yet another config option and indexing a, b, c, d, e, f... we should implement exceptions for languages like Chinese. What do you think?

**Comment by cathaysia** [comment]
It must be a great idea,  I'd looking forward for this.

**Comment by lastzero** [comment]
Implementation was slightly more complex than just removing the limit 😉

**Comment by cathaysia** [comment]
HAHA, I have noticed this change! Thank you so much. 😄
If need any test, let me know please!😄(If have a testing-docker-image, that's great.)
