### ISSUE TITLE
Move image to e.g. quay.io

### ISSUE THREAD

**Issue by ibotty** [photoprism/photoprism#749]
Dockerhub recently enforces pull limits.  It would be great to publish images on quay.io as well.

**Comment by lastzero** [comment]
We can take a look at this in the next few weeks. Why would quay.io provide this service for free? Also we should be listed as community project on Docker Hub, so that limits don't apply. Do you have specific issues?

**Comment by ibotty** [comment]
I am pretty sure the rate limits are for the account pulling images.  It does not matter which image is pulled. See  <https://www.docker.com/increase-rate-limits>.

Regarding quay.io and the associated costs see <https://quay.io/plans/>.

> Can I use Quay for free?
> Yes! We offer unlimited storage and serving of public repositories. We strongly believe in the open source community and will do what we can to help!

Quay.io is run by RedHat and they advertise it as alternative to dockerhub with not having rate limiting.

**Comment by lastzero** [comment]
Docker told us otherwise:

> Welcome to the Docker Open Source Program!  We are very excited to have you as a part of our great community.  We have whitelisted your namespace "photoprism" and this should come into effect in the next couple of days. With this whitelisting, the Docker data pull rate policies that went into effect on November 2, will not apply to the users pulling images from your namespace.

**Comment by ibotty** [comment]
Oh, that's interesting.  It's not mentioned in the usual places.  Well, not much of a hurry then.  Thank you for the information.
