### ISSUE TITLE
Edit Album Title and new title fails to be displayed after save until return to top-level Albums page

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#750]
If you edit an Album's title the title isn't updated on GUI until you refresh the page or go out to top-level Album page and back.

Latest docker image 201227-91acaaa5-Linux-x86_64

**Comment by lastzero** [comment]
Works on our demo. Seems your proxy may be blocking Websocket connections: Do you see a yellow warning icon in the lower left corner? Click it to see configuration examples.

**Comment by elapse2039** [comment]
Yes, works now with websockets enabled. Thx.

**Comment by lastzero** [comment]
You're welcome! ✨
