### ISSUE TITLE
Adding albums using the "+" icon do not appear until GUI is refreshed.

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#751]
Adding albums using the "+" icon do not appear until GUI is refreshed.

Latest docker image 201227-91acaaa5-Linux-x86_64

**Comment by lastzero** [comment]
Works on our demo. Seems your proxy may be blocking Websocket connections: Do you see a yellow warning icon in the lower left corner? Click it to see configuration examples.

https://user-images.githubusercontent.com/301686/103180201-d112e180-4893-11eb-9c67-737f2dd51e92.mov

**Comment by elapse2039** [comment]
Arh, yes, the proxy websocket was not functioning.  Now albums appear.

**Comment by elapse2039** [comment]
BTW - love the warning linking to a context based solution via GUI and not have to trawl through docs!

**Comment by lastzero** [comment]
Seems PhotoPrism is not so bad after all 🥳
