### ISSUE TITLE
Use PHOTOPRISM_SITE_URL to create share links in the UI

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#752]
When creating an Album sharing link, the URL includes the local IP address, not the value in PHOTOPRISM_SITE_URL.
This was discovered when attempting to place photoprism behind a nginx proxy (for SSL) and using the internal network address (due to DNS/routing issues).

Expecting that PHOTOPRISM_SITE_URL would be used to form the sharing link.  Instead, the link includes the local network URL.

Docker image: 201227-91acaaa5-Linux-x86_64

**Comment by lastzero** [comment]
Are you using this site url to access the server? The URL is generated via JS based on the host you are currently using.

**Comment by lastzero** [comment]
We've implemented it this way (for now) as we expect many users to enter a wrong URL into PHOTOPRISM_SITE_URL or ignore this config option completely when "just" testing.

**Comment by elapse2039** [comment]
From within my local network where the photo prism server is running I do not use the public URL because of routing issues to the NGINX proxy.  From outside, it works as expected.  

However, it sounds like from your description that PHOTOPRISM_SITE_URL is not even used?
This kind of parameter is typical/expected in many other opensource web-based projects I've installed.

Anyway, I can't use photo prism to share albums etc unless I'm outside of my local network. :(

**Comment by lastzero** [comment]
We can improve this. As mentioned, there may be other users who ignore this config option and are disappointed because it doesn't use the current hostname. We do our very best to make everyone happy!

**Comment by lastzero** [comment]
Note that you can manually change the URL - the important parts are the share slug & token after the host name.

**Comment by elapse2039** [comment]
Ok, that may be a good workaround for now.  Maybe you can compromise my leaving the PHOTOPRISM_SITE_URL as empty string and using JS host and if someone like me fills the PHOTOPRISM_SITE_URL with a string then use that?

**Comment by elapse2039** [comment]
It's also not very obvious that this setting in the docker-compose file is not used... maybe it needs removing/comment in the interim?

**Comment by lastzero** [comment]
Commenting it is the same amount of work than changing it. Your simply the first user who raises this issue and we had more than enough other tasks to take care of. It's Sunday night... companies like Adobe won't even reply to your questions at this time :)

**Comment by lastzero** [comment]
Next build contains this improvement for you, so that the configured site url is used unless it happens to be empty :+1: 

![site_url](https://user-images.githubusercontent.com/301686/103404668-c20e8680-4b54-11eb-9c94-d2a52cfd4a69.jpg)

**Comment by lastzero** [comment]
Docker build has been started: https://docs.photoprism.app/getting-started/updates/#development-preview

Please use `photoprism/photoprism:preview` for testing preview builds.

**Comment by lastzero** [comment]
@elapse2039 That's what I was talking about: #941

**Comment by 7IM3rW** [comment]
Hi!
I am not a developer so I hope this is the right place to ask. Is it planned that the receipient of the link will have to **enter a password**? So I could share pictures with my family and friends, but its more secure if a password is needed in case some stranger accidentaly "finds" the link.
Thanks!

**Comment by lastzero** [comment]
Yes, it is planned 👍

**Comment by xhabih** [comment]
I've set the PHOTOPRISM_SITE_URL but I still have "localhost" when sharing, I this not yet implemented?

**Comment by lastzero** [comment]
Did you restart for changes to take effect? Is it a valid URL?

**Comment by xhabih** [comment]
Restarted and now working OK.
Thanks.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ant0nwax** [comment]
Hi

I changed the PHOTOPRISM_SITE_URL to "https://prism.example.com/"
I restarted with docker-compose stop and docker-compose start and still see localhost:2324, is there a way how to restart correctly? maybe i am not totally aware that restart could be something different too? Thank you

**Comment by lastzero** [comment]
Use up, not start: https://docs.photoprism.app/getting-started/docker-compose/#step-2-start-the-server

Please note that GitHub Issues should not be used as support forum :)

**Comment by ant0nwax** [comment]
@lastzero you are a hero for a docker pebkac

**Comment by kmanan** [comment]
I seem to be running into a variation of this issue. I am accessing photoprism my domain xyz.com but the URL generated for sharing an album is photoprism.me:2342 and this URL does not work. I have installed Photoprism in TrueNAS and I don't know which file I would need to edit to get the right domain name configured.

**Comment by Bonscha** [comment]
Hi, I have another issue altogether. I might be setting the variable in the wrong way or it might be used in a way I don't think of, but...

I connect via my own DynDNS to the server, which looks like this:

`http://dyndns.MYDOMAIN.TLD/index.php?protocol=http&port=MYPORT`

I can add a path to this URL, which does result in a shared link open correctly:
`http://dyndns.MYDOMAIN.TLD/index.php?protocol=http&port=MYPORT&pfad=/x/73nhz72t6u3htu2/GALLERY`

When I add the environment variable in docker (CasaOS) though, it doesn't even show the standard UI after restarting the container. I can't even use Photoprism at all.

What I entered is the following:
`PHOTOPRISM_SITE_URL = http://dyndns.MYDOMAIN.TLD/index.php?protocol=http&port=MYPORT&pfad=`

Can someone explain to my why the UI doesn't show up anymore, when this variable is set, and how I can use my own DynDNS path for sharing link generation?

Sebastian
