### ISSUE TITLE
Don't flag new albums as favorite by default

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#753]
When creating new albums, they appear with favourite icon illuminated.  Under Favourites, there are no albums.

Docker image: 201227-91acaaa5-Linux-x86_64

**Comment by lastzero** [comment]
Yes, favorite is the default as we want to show new albums at the top so that users can instantly see them. Otherwise, they may be "hidden" at the bottom after all favorites when you press the "new album" button.

**Comment by elapse2039** [comment]
Ok, that is just weird use of favourite.

**Comment by lastzero** [comment]
Yes, we may improve this. We value your feedback, and you can deselect it of course. The main issue with your installation seems to be that Websockets don't work though?

**Comment by elapse2039** [comment]
Yes, I have fixed that now and updated the issues. 

I am still having DNS/routing problems internally and have to use 192.168.x.x address internally to access photo prism. Maybe you can share/add to the docs if they're not already how there how you would actually but a NGINX proxy with FQDN infront of prism?  

Currently, I have this setup:

CNAME (photos.example.com) -> DDNS (myplace1234.ddns.org) -> ISP Router WAN -> ISP LAN -> Home Router WAN -> Home LAN -> MachineA (prism and nginx dockers)

I have successfully got letsencrypt setup and photos.example.com resolves to the ISP Router WAN IP address.  Ports are open and access works fine from outside.  However, within my network, my Home LAN "dig"s photos.example.com to the ISP Router WAN but browser access just times out.   It's as if the return path from ISP Router WAN back into the home network fails.  

All computers within the the Home Router LAN use PiHole with external Cloudflare DNS.  

Any clues/guides very much welcome, I'm missing something but not sure what.  

Otherwise, keep up the work on photo prism... it looks really great and with a few more sharing use-cases it will be perfect for my personal photo server needs. Thx!

**Comment by lastzero** [comment]
I personally use traefik and caddy as they are easier to set up with modern protocols like Websocket. Letsencrypt is also supported out of the box. If you're using a public IP address with NAT than it won't work from inside your local network.
