### ISSUE TITLE
Can folders, under originals, have Albums created automatically when scanned?

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#754]
I see there is a difference between Folders and Albums in the UI.  
I also see the "Add Album" icon on a folder on the context-menu.

Is there a way to automatically convert a folder to an album?
Is there a way to select multiple Folders via UI and then create an Album for each of them?

When downloading from Google Photos, I have folders with names like "December 2020" and would like to "convert" or associate those with an Album, one per Folder.  Not all folders from Google work this way, they seem to have folders with duplicates organised by year, events, etc.  So there is some need for human intervention/selection.

**Comment by elapse2039** [comment]
FWIW I have over 10yrs of Google Photos where I have a Google Photo Album per Month... so I'm not terribly enthusastic about mousing-clicking my way through creating an Album of each of them one by one... but if there was a drop-down on "Add to Album" where you could specify 'individual' albums based on Folder name or something like that would help.

**Comment by lastzero** [comment]
Folders are automatically available as albums when you click on "Folders" in the main navigation. You can also convert those automatically created albums to manually managed albums by selecting them and using the context menu in the lower right corner.

**Comment by Phlogi** [comment]
This does not solve the original question of mass converting all folders to albums. This would require to select each folder manually and click "add to album".

**Comment by lastzero** [comment]
Can we change the folder albums in a way that makes you use those instead of duplicating / mass converting everything? Doesn't sound it should be this way...

**Comment by Phlogi** [comment]
I agree. Well, if we could allow to hide the albums then and stick to folders only. This should then create new folders on uploads, etc.

**Comment by graciousgrey** [comment]
@Phlogi in the newest version you can hide albums using the settings.yml :)
