### ISSUE TITLE
Indexer: Automatically updating JSON metadata doesn't work

### ISSUE THREAD

**Issue by lecaf** [photoprism/photoprism#755]
Hi
I m trying out PP ...till now it seems neat... but ... :)

I would really appreciate having an option to correct rotation on the fly but...ok...could do that with an external tool...well no...
My issue :

- I take a random photo put it in "originals" ask PP to scan the folder, gets indexed and photo is visible in Photos
- I use the out-of-the-box-windows-10 "photos" to change rotation of the image and I verify that the time stamp was changed
- I ask PP to rescan (with or without checking complete scan) and nothing changes for this photo in PP
I would have expected the PP metadata to change and reflect the new image state.
I even pushed further by using digiKam to add tags and description and other metadata. Re-scanning will not alter the file information in PP.
I m using PhotoPrism® 201226-fd53d30c-Linux-x86_64

Am I doing something wrong ? or is it normal.

**Comment by lastzero** [comment]
I assume this happens because metadata is "cached" in the JSON sidecar files created by Exiftool. As a workaround and for testing, you may delete them before reindexing.

**Comment by lecaf** [comment]
well not conclusive
the orientation is in the sidecar jpg (deleting it recreates it updated)
the subject and description is indeed in the json (deleting it recreates it updated)
the digiKam "tags" that are translated to "subject" in PP persist even after deleting the sidecar folder associated with this library (I deleted cache, sidecar and albums)

**Comment by lastzero** [comment]
What means not conclusive? PhotoPrism won't delete already index and merged information when you delete a sidecar file. It's definitely an issue when the same type of data can be found in different sources, for example like the orientation. Unlike thumbs, JSON files are stored by file name and not by hash. A discussion on this can be found somewhere in GitHub issues if you're interested.

**Comment by lecaf** [comment]
Hi thanks for the roadmap inclusion. But JSON is one thing. There is also the sidecar thumbnail and some other metadata (in the DB?)
In a word I think the update library misses the  update part. :)

**Comment by lastzero** [comment]
We now store ExifTool JSON files in the cache folder based on the original file hash. This fixes the issue for me:

![happy_unrotated](https://user-images.githubusercontent.com/301686/103353617-91bdde00-4aa9-11eb-9c44-50c3789391d7.jpg)
![happy_rotate](https://user-images.githubusercontent.com/301686/103353616-91bdde00-4aa9-11eb-98f0-722f214616b8.jpg)
![happy_index](https://user-images.githubusercontent.com/301686/103353613-91254780-4aa9-11eb-9dab-2f8fef28dd54.jpg)
![happy_rotated](https://user-images.githubusercontent.com/301686/103353612-908cb100-4aa9-11eb-850c-1702a49825bd.jpg)

**Comment by lastzero** [comment]
Found one more issue, new builds should be available soon.

**Comment by lecaf** [comment]
Yes! it works now.
as soon as the time stamp differs the file is re-indexed.
Orientation changes. 
This works for jpg but doesn't work for png (did not test other formats)

tags: I m not sure it was working then I deleted the json and it doesn't work anymore. Json was abandoned ? they don't get created even for new images.

my version PhotoPrism® 201230-88483933-Linux-x86_64

**Comment by lastzero** [comment]
JPEGs created from PNGs are not recreated every time the original PNG changes. Our converter is designed for RAWs, which never change as they are digital negatives. For a discussion, see #156. Can't find the issue where our users decided they want JPEGs stored under their original name. We offered to store JPEGs using a hash instead, explaining the tradeoffs. Since we use the original name, full backups containing all related files are easier - especially since RAW formats are often not safe for long-term storage.

I'm sure we'll add yet another config option in a future release to fine tune this and let the user decide the storage and refresh strategy for all file types and sidecar file types in detail 👍 

What's the specific issue with tags? Can you provide us with a file for testing?

**Comment by lecaf** [comment]
Pngs are not an important issue. There was one in my test bench so I mentioned it. 

Tags : I don’t know it worked then it didn’t. I started testing on 88483933. I see there is a  newer... maybe that ? Will check tomorrow. 

Thanks.

**Comment by lastzero** [comment]
PhotoPrism offers labels and keywords (we plan to add hashtags later):

https://docs.photoprism.org/user-guide/faq/#whats-the-difference-between-keywords-and-labels

Existing tags should typically be converted to keywords if they are stored in a common field in a common format. Note that some apps choose to use non-standard data formats within standard fields to make life more difficult for all developers.

If you can't provide us with an image file for testing, we need at least the full metadata in JSON format as returned by ExifTool:

```
exiftool -j example.jpg > example.json
```

Thank you :)

**Comment by lastzero** [comment]
Note that we read ALL exif data and sidecar files in a certain order and merge the data if possible. When using multiple JSON sidecar files, it may be possible that a value is already set and thus ignored when also found in another sidecar file.

**Comment by lecaf** [comment]
good morning 
so this is a sample file 
[2.holliday added.zip](https://github.com/photoprism/photoprism/files/5757097/2.holliday.added.zip)
[1.no tags.zip](https://github.com/photoprism/photoprism/files/5757098/1.no.tags.zip)
[3.greetings added.zip](https://github.com/photoprism/photoprism/files/5757099/3.greetings.added.zip)

- I first scan it in PP with no tag 
- then add holiday (with digikam )
- scan it, subject now shows 'holiday'
- add a second tag greetings 
- scan it, subject is not modified

root@debianbuster:/home/me# ls -alt /data/storage/photoprism/sidecar/a/05*
-rwxr-xr-x 1 root root 323 Dec 31 11:58 /data/storage/photoprism/sidecar/a/050-53f203f2.yml
contents:
TakenAt: 2016-09-07T12:49:23Z
TakenSrc: meta
UID: pqm7a3t2vxnjj6o3
Type: image
Title: Unknown / 2016
Year: 2016
Month: 9
Day: 7
ISO: 25
Exposure: 1/2079
FNumber: 2.2
FocalLength: 29
Details:
  Keywords: brown
  Subject: holiday
CreatedAt: 2020-12-31T10:50:17Z
UpdatedAt: 2020-12-31T10:58:48Z
EditedAt: 2020-12-31T10:58:49Z

PS they were tasty on coal.

**Comment by lastzero** [comment]
The only solution is to also store the data source for each of those fields and compare it when indexing so that manual changes don't get lost. Please test this well!

**Comment by lecaf** [comment]
Hi Michael
yes  got PhotoPrism® 201231-8e22fbf8-Linux-x86_64 and my results:

I can multiple times add or remove tags in jpg, they always get updated into subject
Changing rotation gets updated (not for png see #156)

Should I close it, or you still need it ?

great job many thanks 
with so much work your project gets better by the .. . hour . 
Enjoy the new year

**Comment by lastzero** [comment]
Thank you, you too! 🥂
