### ISSUE TITLE
Sharing / Allow friends with URL to upload photos to an album

### ISSUE THREAD

**Issue by pluja** [photoprism/photoprism#758]
I think this is an important feature. Whenever I have an event with friends or family I want them to share the photos they took with me. I would like to be able to generate a public album link where my friends could also upload the photos and videos they took to a certain album just like you can do with Google Photos (logged in), or MEGAdrop.

I think it would be also important for this feature that the uploader enters their name wherever so it gets added to the "Author" metadata field.

This is what I imagine the option should look like:
![Example upload option](https://i.imgur.com/ZNhJRzy.jpg)

I imagine something like this for the album (with uploads allowed) page:
![Design example](https://i.imgur.com/GmpRUTh.jpg)

And this when the user wants to upload:
![Upload page for guests](https://i.imgur.com/7fhsME2.jpg)

Maybe it would be important for the link to have a expiry date by default when this option is set, so it is not open forever.

**Comment by graciousgrey** [comment]
Thanks for your input and the screenshots! I like the idea with the name :)
 We have a similar ticket already: https://github.com/photoprism/photoprism/issues/557

**Comment by pluja** [comment]
I see! I made a quick search before creating this issue so I dind't duplicate any, but I didn't find that one!! If you want I can make a comment on that issue and close this one.

**Comment by graciousgrey** [comment]
@pluja yes, let's close this one and add a comment with your screenshots to the other one. Thank you :)
