### ISSUE TITLE
Videos: Codec unknown when importing from Google Photos 

### ISSUE THREAD

**Issue by elapse2039** [photoprism/photoprism#759]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

Often, this exception in the browser is seen when trying to play a video.  

The initial impression (~2-3mins) of trying to play any of the video items in the GUI has a spinner and no playback.  Sometimes this 'just resolves itself' after a very long time (~2mins) with the video playback panel visible and spinning circle. Feels like a race-condition.

I've also noticed these iOS based videos (not edited, straight from camera) have no video metadata information.  However, timelapse videos from iOS have some video container information. See underlined green video (timelapse) and underlined blue (regular 1080 iOS video) in third screenshot.  I have noticed the timelapse videos seem to always play while the non-timelapse ones have this spinning loading/DOMException.

![screenshot858](https://user-images.githubusercontent.com/5325698/103223851-f421ad80-48f4-11eb-85f9-dd62d58a0460.png)

![screenshot859](https://user-images.githubusercontent.com/5325698/103224035-2af7c380-48f5-11eb-9f67-eed10d25ef30.png)

![screenshot860](https://user-images.githubusercontent.com/5325698/103224439-abb6bf80-48f5-11eb-8964-dfe9ef70582a.png)

Browser: Chrome, latest version on Windows10.

**Comment by elapse2039** [comment]
Oh, and if you re-click playback icon on a re-try attempt, you see this more often than not...

"Media error: Format(s) not supported or source(s) not foundDownload File: /api/v1/videos/9130a766ad9418337927219234d08b58a61d52d4/public/avc"

![screenshot861](https://user-images.githubusercontent.com/5325698/103224685-2d0e5200-48f6-11eb-897e-ced5eb4c4024.png)

**Comment by lastzero** [comment]
**The message and general frontend UX of the video player may be improved.**

However, it looks very much like the codec could not be detected in most cases, except MKV. Did you disable ExifTool? There is no way we can decode video metadata and detect video codecs otherwise, see https://github.com/photoprism/photoprism/issues/703#issuecomment-743983871. This is also documented in our [FAQs](https://docs.photoprism.org/getting-started/faq/#json).

If the codec is unknown, PhotoPrism triggers transcoding to AVC - but only one video at a time. That's not a deadlock, but to reduce system load, see #703.

In a commercial SaaS app, all your videos would be transcoded automatically before you can play them - but this is a self-hosted application and we already have more than enough users complaining about the storage requirements. There is no practical solution to support all videos formats in a way that makes everyone happy, and doesn't cost any storage or CPU time. There are limits to what even the best developer can do.

**Comment by lastzero** [comment]
When even ExifTool can't detect your codecs, there is no way for us to detect them directly right now as PhotoPrism is a photo app and not a complete video solution. Please add the JSON metadata of one affected file to this issue for testing:

```
exiftool -j example.mov > example.json
```

Thank you! :)

**Comment by elapse2039** [comment]
Understand the balancing act between user and server expectations.  I did not disable exiftool.  Here is the exiftool info for one of the videos.  The eventual playback of the video makes sense now I know it's design intent to encode on demand, one at a time.  Is it possible to kick off transcode for all videos from the command line as a one-off?  Like re-indexing but for video transcoding?  (BTW does the video playback stream from Photoprism or does it download the entire video file to the browser and then playback starts?)

[IMG_2679.MOV.json.txt](https://github.com/photoprism/photoprism/files/5748138/IMG_2679.MOV.json.txt)

I have to amend my original assumption, these are not native iOS videos, these have infact been uploaded (as native iOS) but then Google did some magic it appears, and they are the videos from Google Photos (that I exported recently).  The exif shows they have been re-encoded by Google.  It shows as MP4.  The timelapses from iOS were also from Google Photos, so curious why those have exif.  Perhaps Google leaves MKV alone.

I will experiment with native iOS video upload and see if the playback is better.

**Comment by lastzero** [comment]
Maybe there are naming conflicts with the JSON files in the Google photos export. Not sure how to resolve them... Might use a different extension

**Comment by lastzero** [comment]
Can you figure out if all Google photos videos are AVC? Then we can set that in the metadata without using Exiftool.

**Comment by elapse2039** [comment]
This is a json file from one of the MOV files I got from Google Photo (Takeout). Had to add .txt to get github to accept it.
[IMG_9785.MOV.json.txt](https://github.com/photoprism/photoprism/files/5749493/IMG_9785.MOV.json.txt)

All MOV files I've uploaded from iOS device to Google have this same file format:
IMG_7453.MOV: ISO Media, MP4 v2 [ISO 14496-14]

Movies I have created, using Blender, are MKV and Google has this type of profile for them:
[cowboy-snowmen.mkv.json.txt](https://github.com/photoprism/photoprism/files/5749498/cowboy-snowmen.mkv.json.txt)

**Comment by lastzero** [comment]
We now store ExifTool JSON files in the cache folder to avoid conflicts with Google Photos JSON files in originals. This fixes the issue for me. Feedback welcome! Just started a new build.

**Comment by lastzero** [comment]
Found one more issue, new builds should be available soon.

**Comment by lastzero** [comment]
Fun fact: Found a video metadata bug on Google Photos while performing tests for this issue! This should be displayed in portrait mode, width & height are wrong.

![google_portrait_video](https://user-images.githubusercontent.com/301686/103364515-58dc3400-4abe-11eb-8192-558e68739774.jpg)
