### ISSUE TITLE
Be able to filter on photo which are not already added to an album

### ISSUE THREAD

**Issue by SublimeSM** [photoprism/photoprism#760]
AS a user
I WANT to be able to easily know which photo are not already assign to an album
SO THAT I can focus on these photo when I want to enrich an album

**Comment by lastzero** [comment]
Go to Albums > Unsorted

**Comment by lastzero** [comment]
Unsorted is also available as a filter in the general search. Use `unsorted:true`. Should also be listed in our User Guide in the search section.

**Comment by SublimeSM** [comment]
THANKS !
