### ISSUE TITLE
[QUESTION] Images that are mounted in the Nextcloud instance, should appear instantly in Photoprism?

### ISSUE THREAD

**Issue by esturniolo** [photoprism/photoprism#764]
Hi!
I asked this (#724) and the solution mounting the Nextcloud directory in Photoprism is perfect.

The fact is that I've new photos in the Nextcloud directory, but nothing new in Photoprism (for several days). So, should I run ` photoprism index` manually in this case? Because when I ran it, the new photos appears perfectly.

I don´t have any problem to cron that command once or twice a day. But may be I'm doing something wrong.

Thanks!!!

**Comment by lastzero** [comment]
Yes, you need to reindex as photoprism doesn't want to randomly start indexing while the file system is being modified externally. We'll try to find a smart solution for this issue later, for example observe all files and wait a given amount of time until indexing seems safe.

**Comment by esturniolo** [comment]
Perfect! While you find a solution for this, I'll to cron the index.

Thanks for the fast response!
