### ISSUE TITLE
Metadata: Support additional JSON formats

### ISSUE THREAD

**Issue by narensankar0529** [photoprism/photoprism#767]
I am getting the following warning and metadata is not being read. What does PhotoPrism not like?

WARN metadata: unknown json in PHOTO_20080625_IPHONE_F1C6E6DC251E4743F3EB2A66590E2FE6_2008_JUN_25.JSON

JSON file -

[{
    "Keywords": ["bowl", "carrot", "food", "plate", "salad", "stir fry", "tableware", "utensil", "vegetable"], 
    "Subject": ["bowl", "carrot", "food", "plate", "salad", "stir fry", "tableware", "utensil", "vegetable"], 
    "TagsList": ["bowl", "carrot", "food", "plate", "salad", "stir fry", "tableware", "utensil", "vegetable"], 
    "DateTimeOriginal": "2008:06:25 14:55:38", 
    "CreateDate": "2008:06:25 14:55:38", 
    "OffsetTimeOriginal": "+08:00", 
    "DateCreated": "2008:06:25", 
    "TimeCreated": "14:55:38+08:00", 
    "ModifyDate": "2008:06:25 14:55:38"
}]

**Comment by lastzero** [comment]
Because it's an unknown json format. The Exiftool header and filename are missing.

**Comment by narensankar0529** [comment]
So photoprism will look for the follow items?

  "SourceFile": "photo_20080613_iphone_dcce19c188c6cea1a6e5bfc24e31bc15_2008_Jun_13.jpg",
  "ExifToolVersion": 12.00,
  "FileName": "photo_20080613_iphone_dcce19c188c6cea1a6e5bfc24e31bc15_2008_Jun_13.jpg",

**Comment by graciousgrey** [comment]
For this to be implemented we need example files and it would be beneficial to know what tools write json in this format.

**Comment by narensankar0529** [comment]
Hi
This JSON was created via a tool call osxphotos which exports Photos from MacOS Photos. I worked with that tool developer to fix the JSON format to match what PhotoPrism expects. So no changes needed here
