### ISSUE TITLE
UX: Show error when cache folder is in originals

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#768]
I have a small docker container with PP (photoprism) and added 9 photos and 6 videos last night. I re run the index and now the navigate shows 1149 photos and 106 folders. See screen shot from the "folder" view. 

I didnt create any folder manually and I set up a new db and a new folder structure for the container. 

Did I do something wrong with the re-index?

<img width="1142" alt="Bildschirmfoto 2020-12-29 um 11 14 14" src="https://user-images.githubusercontent.com/73672554/103276507-0bc96680-49c7-11eb-8b41-a69f70c99566.png">

**Comment by lastzero** [comment]
Seems like you put the cache folder in the originals folder so that thumbnails were indexed and then probably second and third order thumbs of thumbs.

**Comment by lastzero** [comment]
You can do this, but then in a hidden folder starting with a dot so that PhotoPrism ignores it. Or we error on startup and prevent this completely if it isn't obvious enough :)

**Comment by swingstate** [comment]
I'll vote for a clear error msg. :)  I am tech savvy, and stumbled upon this. I used the stock config from the UnRaid Repo @ich777 and only added a second PP root folder "photoprismx".

<img width="1024" alt="Bildschirmfoto 2020-12-29 um 11 36 02" src="https://user-images.githubusercontent.com/73672554/103277838-2bae5980-49ca-11eb-8489-ab0bb35fbf00.png">

**Comment by lastzero** [comment]
The unraid config is not maintained by us and should be fixed in this case. We'll add yet another error message. Looking forward to complaints that PhotoPrism is not starting 🥳

**Comment by lastzero** [comment]
You screenshot shows both folders - cache and data - are exactly the same! 

![Screenshot_20201229_114255](https://user-images.githubusercontent.com/301686/103278131-05d58480-49cb-11eb-8535-b1b954959c8c.jpg)

**Comment by lastzero** [comment]
Maybe cache and user point to the same drive? Don't know...

**Comment by ich777** [comment]
@swingstate @lastzero

I will update the description so that it says you don't should put your import folder in your pictures folder...

**Comment by lastzero** [comment]
Right, that may be an issue as well - especially when you copy and don't move the imported files it might create a loop. Screenshot looks like thumbs were indexed though. Guess it's easy to make mistakes when configuring a software that has more than one config parameter 🙄

**Comment by lastzero** [comment]
Folder name shown by PhotoPrism is cache, so should be very obvious unless you intended to index your cache folder:

![Screenshot_20201229_121417](https://user-images.githubusercontent.com/301686/103279934-636bd000-49cf-11eb-869b-b74e7f635833.jpg)

**Comment by ich777** [comment]
Updated the description so that it says to not put your import folder into your images folder:

https://github.com/ich777/docker-templates/blob/master/ich777/PhotoPrism.xml#L170

**Comment by lastzero** [comment]
Might using a double slash in a path like // be an issue that causes the container to mount / instead of the intended folder?

**Comment by ich777** [comment]
No, since the values from the Unraid 'template' are passed over to the Docker daemon and executes a default 'docker run' with the variables/ports/paths from the template.
The default path for the import folder in the container should be '/photoprism/import'
![Bildschirmfoto_2020-12-29_12-52-10](https://user-images.githubusercontent.com/28066518/103282002-b09e7080-49d4-11eb-9a00-2ca55f5ee0b5.png)

**Comment by graciousgrey** [comment]
I close this issue, as in unraid there is a warning and we have another open issue for a warning when using the docker-compose setup : https://github.com/photoprism/photoprism/issues/1642
