### ISSUE TITLE
Idea: Ease GPS tagging of photos - open Maps when clicking lat/long to allow picking of GPS location

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#771]
I mostly know where I have taken photos. However, through various conversion / editing processes sometimes exif data gets lost. Hence, I manually add it again.
Doing that for the GPS location is cumbersome and today I go to Google Maps, find the location, right click ... and so on.

Can you add a simple map view into the lat/long fields so when somebody clicks there (or on a separate button) a location can easily be picked and automatically entered into the two fields?

**Comment by lastzero** [comment]
@graciousgrey Looks like a duplicate?

**Comment by graciousgrey** [comment]
Yep, it's already on our roadmap: https://github.com/photoprism/photoprism/issues/465.
