### ISSUE TITLE
Backup strategy

### ISSUE THREAD

**Issue by thomaseizinger** [photoprism/photoprism#772]
First, thanks for building photoprism, it is really amazing and I am looking forward to use it!

I am currently running photoprism on my RPI with MariaDB as a database and I would like to set up an automated, daily backup scheme using restic.

My questions are:

1. What exactly do I need to backup?
2. How would restoring look like / work?

I know that the `originals` directory contains all the pictures so that sounds like a good starting point. What about all the edited metadata and the albums I create? Is it good enough to just backup my MariaDB? If yes, what would you advise? Dump the database into an SQL file or simply backup the whole of `/var/lib/mysql`?

Should I be shutting down photoprism for the backup or can I simply run the backup job concurrently? I know that within the `originals` directory, pictures are not modified so at least for those, it sounds like photoprism would not need to be shut down.

Looking forward to your input!

**Comment by jean-louis67** [comment]
Hello
I cannot answer for myself to know what is sufficient to do.
However, this subject is very important to me.

### Originals
Regarding originals, I regularly save it to an external drive with _rsync_.

### Metadata
Regarding metadata, I also use mariadb. I am in the process of developing a backup and restore script which I am running with **Jenkins**. I am doing tests on a PhotoPrism instance installed with docker-compose.

#### Backup
Here is for example the backup code:

```
#!/bin/bash
set -ex

dir=/root/photoprism
backupdir=${dir}/mariadb_backup

rm -rf ${backupdir}/*

docker-compose -f ${dir}/docker-compose.yml exec -T mariadb mariabackup --backup --target-dir=/backup --user=root --password=photoprism

date=$(date +"%Y%m%d-%H%M%S")
tar zcf ${dir}/mariadb_backup${date}.tar.gz ${backupdir}
```
#### Restore
The corresponding restore code is:
```
#!/bin/bash
set -exdir=/root/photoprism

backupdir=${dir}/mariadb_backup

rm -rf ${backupdir}/*

tar xvf mariadb_backup20201229-092303.tar.gz -C mariadb_backup
docker-compose -f ${dir}/docker-compose.yml exec -T mariadb service mariadb stop -user=root --password=photoprism
docker-compose -f ${dir}/docker-compose.yml exec -T mariadb mariabackup --prepare --target-dir=/backup --user=root --password=photoprism
docker-compose -f ${dir}/docker-compose.yml exec -T mariadb mariabackup --copy-back --target-dir=/backup --user=root --password=photoprism
```
/jenkins is defined as a volume of mariadb:
`- "/root/photoprism/mariadb_backup:/backup"`

I share this without pretension and no certainty that this is the best approach
Hope this can move this discussion forward

**Comment by thomaseizinger** [comment]
Thanks for contributing your ideas @jean-louis67 !

Personally, I would like to create backups of everything that is crucial to photoprism in a way that is consistent (i.e. database entries match the files that are on disk).

As such, I _think_ this can only be achieved if `photoprism` and `mariadb` are shut down for the duration of the backup.
Inspired by your use of `mariabackup`, a backup procedure could look like this:

1. shutdown photoprism
2. shutdown mariadb
3. backup mariadb
4. create `restic` backup of `originals` directory, the mariadb backup and **whatever other data needs to be backed up**. I don't know what this is yet, hopefully the maintainers can shed some light onto this :)
5. start mariadb
6. start photoprism

I also saw that photoprism is doing some kind of backup itself to `yaml` files. That sounds useful to include as well. I am not sure what is in these files but maybe we can even skip the DB backup if these files contain everything?

Ideally, we would not have to shut everything down for the backup although that is really an inconvenience rather than a blocker :)

**Comment by jean-louis67** [comment]
Hello @thomaseizinger 

I agree with your process.

In my script there is not (yet) stopping PhotoPrism, because piteously:disappointed_relieved:, I did not find the right command to stop Photopprism in the docker container (and not the container itself)

I intend to chain the backup of originals and metadata by 2 jobs in Jenkins
I did not know restic. Does restic do incremental backups?
This is important if you want to make regular backups. More generally, a process adapted to the volumetry is needed.

In my case, for the moment:
- About 8000 photos and 130 videos
- 24 GO for originals
- mariadbbackup: 124MB before compression

For originals, I find _rsync_ to be really handy.

Regarding YAML files, I'm not sure you can find everything there. As these files are sidecars, I would be surprised if there were relationships between photos and other entities, for example the organization in albums.

**Comment by lastzero** [comment]
Note that we've added backup and restore commands - run `photoprism help` so see available commands:

```
photoprism@1c5377415f57:/go/src/github.com/photoprism/photoprism$ ./photoprism help
NAME:
   PhotoPrism - Browse Your Life in Pictures

USAGE:
   photoprism [global options] command [command options] [arguments...]

VERSION:
   201230-d09c23ad-Linux-x86_64-DEBUG

COMMANDS:
   start, up         Starts web server
   stop, down        Stops web server (only in daemon mode)
   index             Indexes media files in originals folder
   import, mv        Moves files to originals folder, converts and indexes them as needed
   moments           Creates albums based on popular locations, dates and labels
   optimize          Starts metadata check and optimization
   purge             Removes missing files from search results
   copy, cp          Copies files to originals folder, converts and indexes them as needed
   convert           Converts originals in other formats to JPEG
   resample, thumbs  Pre-renders thumbnails (significantly reduces memory and cpu usage)
   migrate           Initializes the index database if needed
   backup            Creates album and index backups
   restore           Restores album and index backups
   reset             Resets the index and removes sidecar files after confirmation
   config            Displays global configuration values
   passwd            Changes the admin password
   version           Shows version information
   status            Performs a server health check
   help, h           Shows a list of commands or help for one command
```
