### ISSUE TITLE
Frontend: Enable text search for short words

### ISSUE THREAD

**Issue by cathaysia** [photoprism/photoprism#773]
At the last issue: #746 , thanks for you resolve this problem, there is a new issue now.

One Chinese word is allow, tow words are disabled, and three words are allow. 😔

**Comment by lastzero** [comment]
Removed the frontend validation check. Just started new Docker builds for testing!

**Comment by cathaysia** [comment]
I remove this image and rebuild Docker, but it seem not work? Maybe Docker not update?

**Comment by lastzero** [comment]
From now on, you need to use the `photoprism/photoprism:preview` image for testing development builds. We don't automatically trigger `latest` builds after adding features or fixing issues anymore.

A new `latest` build will be triggered later, when we don't find issues in the preview & demo builds.

**Comment by lastzero** [comment]
Started a new build for `photoprism/photoprism:latest` - available in ~30min

**Comment by cathaysia** [comment]
sorry, the pre days I'm on the train.( Happy New ars Day! Maybe it's just a late.) I had try the newest version, it works perfect! Thanks!!!

**Comment by lastzero** [comment]
Excellent, thanks for testing 🙏
