### ISSUE TITLE
No photo found

### ISSUE THREAD

**Issue by kklot** [photoprism/photoprism#777]
I followed your docker-compose guides, installed on a Xubuntu 20.04. Things went well and I added photos in `~/Pictures`. But indexing via either web UI or command line found no photos and completed within seconds. I must have missed something obvious, what could I do? I restarted the docker, tested uploading files (which showed up) nothing changes.

**Comment by lastzero** [comment]
Might be file system permission issues. Maybe a typo. Hard to guess remotely. Uploadings works, or do pictures also disappear? When exactly?

**Comment by lastzero** [comment]
Probably mounted the wrong directory? Use an absolute path to besure. Also read our FAQs on [docs.photoprism.org](https://docs.photoprism.org).

**Comment by kklot** [comment]
I used `docker-compose.yml` file, changed only the admin password. Uploading works fine (folder created in `/photoprism/originals` and photos show up in the library). 

I tested expanding the tilde in `- "~/Pictures:/photoprism/originals"` and `sudo docker-compose restart` but still not work. 

In the FAQ I see this

> Please verify file system permissions before starting to index: The originals folder must be readable, while storage must be readable and writeable.

but unsure what to do?  I run docker with sudo.

**Comment by lastzero** [comment]
In that case, it runs as **root** and will not index your home. Make sure to use down and up when changing the config, it won't be applied otherwise. Also check out our command reference im the docker-compose.yml example at the top.

**Comment by kklot** [comment]
Thanks! It's indexing now, after running `up -d`, and absolute path as well.

**Comment by lastzero** [comment]
Excellent, we're looking forward to a 5 star review 😉

Happy New Year 🥂
