### ISSUE TITLE
Search/filter for shares - question

### ISSUE THREAD

**Issue by Sherlock1979** [photoprism/photoprism#778]
Hi,

Is there any way to use the search/filter capability for shares? I don't see it on the UI but is it available through the API or by adding the relevant GET parameters to the share URL?

Thanks,
David

**Comment by lastzero** [comment]
When authenticated as a guest?

**Comment by Sherlock1979** [comment]
Yes.

As a user I would like to add search filter parameters to my share URL so that I can filter the photos a guest user who receives my share URL can (initially) see.

Use case: I add new photos to an already shared album and I would like to send a link where only the new photos are shown. (E.g. filtered by date or tag).

Thanks

**Comment by lastzero** [comment]
In theory yes, but haven't tested this 🙄

**Comment by Sherlock1979** [comment]
I am happy to try it if you give me a hint on how to add the filter parameters.

**Comment by lastzero** [comment]
Copying the GET parameters from the regular search and adding it to the share album URL should work...

**Comment by Sherlock1979** [comment]
Hi @lastzero,

Thanks for your reply.

Yes, I can confirm that the GET parameters work on the share album URL. However, only when the album ID is used in the share URL. E.g. /s/token/aqm6vng2qnd3gars?q=name%3A"IMG_%2a"

It does not work across all albums. E.g. /s/token?q=name%3A"IMG_%2a". Do you think you can make it work?

It also does not work if in the share URL I use the album name instead if the album ID. E.g. /s/token/albumname/?q=name%3A"IMG_%2a". Note, in this case PhotoPrism looks up the album ID and redirects the browser to the URL with the album id. However during this redirect the GET parameters are lost. Do you think you can fix this scenario?

Thank you for your hard work.

Cheers,
David

**Comment by lastzero** [comment]
> Yes, I can confirm that the GET parameters work on the share album URL. However, only when the album ID is used in the share URL. E.g. /s/token/aqm6vng2qnd3gars?q=name%3A"IMG_%2a"

Makes sense, the share link is just a redirect to the actual URL. It contains the (not unique) slug. Thus also the issue you discovered earlier, when there are duplicate names and tokens. The actual URL contains the UID.

> It does not work across all albums. E.g. /s/token?q=name%3A"IMG_%2a". Do you think you can make it work?

How should that work? This is an ALBUM list and you're searching for a FILE name.

There should be an existing feature request for showing all albums a photo is in. Is this what you want?

> It also does not work if in the share URL I use the album name instead if the album ID. E.g. /s/token/albumname/?q=name%3A"IMG_%2a". Note, in this case PhotoPrism looks up the album ID and redirects the browser to the URL with the album id. However during this redirect the GET parameters are lost. Do you think you can fix this scenario?

Might be able to keep the parameters in the redirect. @graciousgrey Can you put this on the roadmap?

> Thank you for your hard work.

Thank you!

**Comment by graciousgrey** [comment]
Here is the ticket for keeping the parameters https://github.com/photoprism/photoprism/issues/796

**Comment by Sherlock1979** [comment]
> > It does not work across all albums. E.g. /s/token?q=name%3A"IMG_%2a". Do you think you can make it work?
> 
> How should that work? This is an ALBUM list and you're searching for a FILE name.

Totally valid point. I guess what I miss then is a share-view that is similar to the Photos page of the full (logged in) Photoprism. That is, a page where the user with the shared token can see (and filter) all the photos that are shared with him, regardless of which albums the photos are in.

E.g. a /s/token/photos URL (that also accepts the GET parameters for filtering).

I think the code may be almost identical to the logged in users' Photos page (incl. the search feature) but logically the photos would also be filtered in a way that they can only see the ones that are shared with them (in an album).

To elaborate on this requirement, in my use case I would share tokens with guest users who are family members. So the share tokens are 'grandma', 'grandpa' etc. I create originals folders for my events such as 'New Years Eve' and then I create albums with a subset of the photos that I would like to share with the family members. As I do this with my full photo library each share token will have hundreds of albums and tens of thousands of photos in total. I would like to give the share token users the ability to search through all the photos in a similar way as the Photos page works for logged in users. I would also like to be able to do the search myself and send the family members a share URL with the GET query request.

Hope it makes sense and you support my idea. Please share your thoughts. Thanks.

**Comment by graciousgrey** [comment]
@Sherlock1979 We could do that in the future. Would you open a separate idea ticket for it, I will close this question then :)
