### ISSUE TITLE
Dynamic Previews, Skip Thumbnail Generation - Question

### ISSUE THREAD

**Issue by intdel** [photoprism/photoprism#781]
Hello,

I have a powerful CPU and plenty of RAM. I would like to skip creating thumbnails when indexing. Is that not possible? I was not able to find an option to do so.

Thanks

**Comment by lastzero** [comment]
Not completely as we need them for image classification. See docs.

**Comment by lastzero** [comment]
Added your questions to our FAQs: https://docs.photoprism.org/getting-started/faq/#can-i-skip-creating-thumbnails-completely

**Comment by intdel** [comment]
Thanks
