### ISSUE TITLE
Duplicate detection limited to file names or image content?

### ISSUE THREAD

**Issue by andmib** [photoprism/photoprism#784]
First, let me say thank you for the development on this! This is exactly what I've been looking for.

I have a quick question - does PhotoPrism take care of duplicates outside of the file name? That is, say you have two images: `a.jpg` and `b.jpg`, and they contain the same metadata as well as image content. Will PhotoPrism ignore these? If not, is there a way to implement a hashing feature - e.g. generate a hash for each image based solely on image pixel values, and ignore images with the same hash that already exist?

**Comment by lastzero** [comment]
Yes, will be skipped when indexing or importing 👍
