### ISSUE TITLE
(idea)Capability to use Coral devices to improve tensorflow performances

### ISSUE THREAD

**Issue by bnounours** [photoprism/photoprism#785]
Google sell some devices to improve performance of neural networks model using tensorflow Lite (https://coral.ai/)
The idea is to use this library so people having these devices can improve performance on slow servers (like me)
I can do some tests with the usb accelerator : https://coral.ai/products/accelerator/
As far as I read the lib is the same whatever the device is.

**Comment by lastzero** [comment]
The main issue here is compiling TensorFlow, UX and documentation. We could easily distribute highly optimized, faster versions of TensorFlow - but those wouldn't work on many devices. Inference really doesn't need that much performance, thumbnail generation is much more demanding. It's different for training a model, but we don't do that while indexing.

**Comment by lastzero** [comment]
Please check existing issue, might be a duplicate... seen a similar idea before.

**Comment by graciousgrey** [comment]
This one #536  ?
