### ISSUE TITLE
UX: Illusion of browsing whole collection at once (idea)

### ISSUE THREAD

**Issue by tomas789** [photoprism/photoprism#786]
Preload empty rectangles for all photos in the gallery. Fill them in with thumbnails on demand.

It would help in two situations:
1. Get quickly to older/newer photos without waiting many times to fetch more thumbnails.
2. Find photos faster by doing something like binary search on the whole gallery.

**Comment by lastzero** [comment]
We'll eventually work on these things - for now, we're glad PhotoPrism is stable 🥳

**Comment by uxusoft** [comment]
When collection have thousands of photos it takes too long to load all photos. I have to scroll multiple times to the bottom of page. The only option is to split it to small albums. But it is not always convenient and takes time.

It is great to have feature to preload more photos at once (for example, now it loads about 15 photos when I scroll down). For example, to load 50 at once when scroll down.

**Comment by lastzero** [comment]
You might run into http connection limit issues when loading too many previews at once.

**Comment by eblanshey** [comment]
Just want to throw some support for this. Currently it loads a pretty small amount of thumbnails at once. I reach the bottom of the page, and it seems nothing happens for a second or two, then more images load, then I wait again, etc.

I think it's unnecessary to preload all empty rectangles at once on a page. Instead, when I reach near the bottom of the page, it would be better to load blank rectangles for the "next" loaded amount. If I near the bottom of the page, it will continue loading more empty boxes (if there are more images available to load.) This will give the illusion of an instantaneous infinite scroll while the images themselves populate the empty rectangles.

FYI this is the behavior in Google Photos, and it's a very smooth experience.

**Comment by graciousgrey** [comment]
I will close this as it will be solved with: https://github.com/photoprism/photoprism/issues/152 :)
