### ISSUE TITLE
API tests show error on Travis CI but tests are green

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#79]
See https://travis-ci.org/photoprism/photoprism/jobs/466362413#L631

```
=== RUN   TestGetPhotos
--- PASS: TestGetPhotos (0.01s)
=== RUN   TestLikePhoto
(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1) 
[2018-12-11 06:35:04]  
--- PASS: TestLikePhoto (0.00s)
=== RUN   TestDislikePhoto
(Error 1292: Incorrect datetime value: '0000-00-00' for column 'taken_at' at row 1) 
[2018-12-11 06:35:04]  
--- PASS: TestDislikePhoto (0.02s)
PASS
ok  	github.com/photoprism/photoprism/internal/api	0.365s
```

Maybe models are not properly initialized? Check GORM docs and compare to other code.

**Comment by webrules** [comment]
Maybe it is GORM related? I see that following change has been made 
to      const DataURL = "https://dl.photoprism.org/fixtures/photos.zip" 
from const DataURL = "https://www.dropbox.com/s/na9p9wwt98l7m5b/import.zip?dl=1"

However, when we look at the download server, only demo.zip and test.zip are there.

**Comment by lastzero** [comment]
Test fixtures are cached in /tmp (only the file hash is compared, not the original download URL). You can pull / merge again, I changed the file name a few times. Should exist, worked for me. We have our own download server now.

I've seen the error before somewhere else, it was easy to fix... not quite sure what it was.

**Comment by lastzero** [comment]
In fact, tests failed whenever database was empty as there was not photo with ID 1. We need to create default test fixtures that are there from the start.
