### ISSUE TITLE
On initial import, all my titles are "Unknown / [year]"

### ISSUE THREAD

**Issue by zzyzx-dc** [photoprism/photoprism#790]
I don't know what I was expecting, per se, but on initial import all my photos are being labelled Unknown. Is there any other behavior I could enable? Title by location - or just the year?

I am importing a large amount of disorganized photos.

**Comment by lastzero** [comment]
You had a look at our demo, right? https://demo.photoprism.org/

So this is what you should expect. Without ANY additional information, I can't tell you what went wrong. Sorry.

**Comment by zzyzx-dc** [comment]
My apologies. Per the demo, it appears most photos are auto-titled with location, and then further titled (by TensorFlow? Or manually?) with the subject of the photo. 

I believe I recognize my problem:

PHOTOPRISM_DISABLE_TENSORFLOW: "true"         # Don't use TensorFlow for image classification

I read this commented part as "false" meaning it would not use TF. I believe what happened is I've disabled TF by setting "DISABLE" to true.

**Comment by lastzero** [comment]
That makes sense. Yes, don't disable it. You're welcome to help us improve our docs 🌈
