### ISSUE TITLE
PHOTOPRISM_THUMB_UNCACHED still creates thumbs while indexing

### ISSUE THREAD

**Issue by cthulu** [photoprism/photoprism#793]
Hi,

maybe I misunderstand the `PHOTOPRISM_THUMB_UNCACHED` from https://docs.photoprism.org/getting-started/config-options/ but I was under an impression that with that env variable (I'm running in Docker) it would prevent the thumbnails from being created while indexing the collection, and only on-demand when a collection is opened. 

I've also disabled the TensorFlow too with the hope to significantly speed up the process of indexing (only sizes, folder name and geo data to be extracted). I am running the app on my Synology NAS with really limited resources and I don't think I want all the thumbs of my 400k photo collection to be created, but rather selectively.

Maybe I just don't understand the config switch, but checking the code shows the actual flag is only checked when doing `GET` but not when reindexing (or I couldn't spot it)

Cheers

**Comment by lastzero** [comment]
See https://docs.photoprism.org/user-guide/settings/advanced/

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/faq/#can-i-skip-creating-thumbnails-completely

**Comment by cthulu** [comment]
Thanks. Maybe my question is better formed as 'do not create the thumbs
immediately when indexing, but only when browsing (and store them)'

For large collections this may spread out the load to create all the thumbs
and if you don't use TensorFlow it should be good enough.

**Comment by lastzero** [comment]
That's possible, see docs. Only thumbs up to 720px need to be created statically (while indexing) as we need them for indexing. Reduce the static size to the minimum in the Advanced settings tab.

**Comment by cthulu** [comment]
Thanks, I couldn’t find the advanced settings as I’ve had the public mode enabled. I’ll check it out!
