### ISSUE TITLE
Metadata: Location Doesn't Update After Changing GPS Coordinates in JPEG Exif Headers

### ISSUE THREAD

**Issue by gchaincl** [photoprism/photoprism#800]
I recently mass-updated a folder using the https://github.com/marcoil/gottengeography tool.
After I re-index the photos (not using the `Complete Scan` option) but the location is not updated in Photoprism.
I want to avoid running a complete scan cause it will take too long.

What would be the right way to reflect the geotag changes in Photoprism?

Thanks!

**Comment by lastzero** [comment]
Did you update the original files (Exif?), or where did you change the location? I assume you're using our latest (stable) version from Docker Hub?

**Comment by gchaincl** [comment]
I updated the original photo folder
I'm using the docker-compose file provided

**Comment by lastzero** [comment]
Alright, give us a few days to test this and provide a fix if needed. Or try a complete rescan **limited to a single folder** using the folder dropdown on the index page.

**Comment by gchaincl** [comment]
I managed to do it using `photoprism index -a ./my-folder`, not sure if this is a bug or expected

**Comment by lastzero** [comment]
Hard to guess why it didn't work in the first place. But glad it did now!

**Comment by lastzero** [comment]
You want to keep this issue open?

**Comment by gchaincl** [comment]
Thanks for your help!
I think the issue was that I had to do a complete index. Closing it.
