### ISSUE TITLE
UX: Unknown should default to end

### ISSUE THREAD

**Issue by egyptianbman** [photoprism/photoprism#803]
The default sort is `Newest first`. This works well except when there are items that have a date of `Unknown`. Currently, those images always get sorted in the front. IMHO, images/videos with no date should go to the end, allowing the newest images to always appear first.

**Comment by lastzero** [comment]
And when you sort for oldest?

**Comment by egyptianbman** [comment]
I have no preference beyond default sort putting `unknown` at the end. Whether they then come to the front when sorting by oldest first or there be a specific filter for unknown, I'll leave to the devs and/or others to decide.

**Comment by ryancc9** [comment]
Agreed.  Obviously I'm only 1 person and 1 library, but "unknown" photo for me are more likely to be old than new.

**Comment by lastzero** [comment]
@ryancc9 It's actually not new anymore if you wait a little... if there is no other date, the file system date is used - which typically is about the date of an image, unless you've just copied everything and are indexing for the very first time. Using ANY other date would be completely random, not deterministic in any way. Pure chaos. What order would you apply?

What we CAN do is simply hide all photos without metadata, unless they are so old that metadata didn't exist at that time. That's basically what our quality filter does. Did you disable it?

**Comment by rjt** [comment]
Would be nice to have a feature that suggested a few dates to the user, but allowed a human to set a date.

**Comment by lastzero** [comment]
You want to be asked for every single unknown date after importing / indexing?

**Comment by lastzero** [comment]
Date, time and time zone can be changed in the edit dialog. Batch edit is on our public roadmap.

**Comment by rjt** [comment]
Not necessarily during import, but the option at some time to set a date.  Usually, UNKNOWN dates are in batches.  So multiselecting a range of photos and setting a date for all at once might  not be too time consuming.  A date of 19890000 would mean those photos are from 1989 with unknown month and day.  Further, there have been so many different metadata places to put a date.  `strings unknown.jpeg` output might reveal something useful to give the user.

**Comment by lastzero** [comment]
Note that putting your files in a folder structure like YEAR/MONTH/DAY or just YEAR/MONTH will also automatically use that date as fallback if no metadata exists. So basically you need a library...

- without meaningful folder structure-
- without metadata
- with wrong file system dates
- and disabled quality filter 

...for images to be wrongly shown as new at the top of the photo search.

**Comment by lastzero** [comment]
> Usually, UNKNOWN dates are in batches. So multiselecting a range of photos and setting a date for all at once might not be too time consuming.

See https://github.com/photoprism/photoprism/issues/271

**Comment by lastzero** [comment]
Please let us know if using a meaningful folder structure, and enabling the quality filter, solve this issue for you ✨

**Comment by ryancc9** [comment]
> @ryancc9 It's actually not new anymore if you wait a little... if there is no other date, the file system date is used - which typically is about the date of an image, unless you've just copied everything and are indexing for the very first time. Using ANY other date would be completely random, not deterministic in any way. Pure chaos. What order would you apply?
> 
> What we CAN do is simply hide all photos without metadata, unless they are so old that metadata didn't exist at that time. That's basically what our quality filter does. Did you disable it?

This was the first indexing.  I have a lot of photos, so its hard to remember, but I think you are correct that the quality filter caught mine and I approved without knowing I needed to adjust dates.  It's not obvious from the review screen that a date of unknown is bad.  Maybe make it red, force an edit, or give some kind of notification? I just blindly hit the checkmark for photos I wanted in my library. [https://i.imgur.com/n77xtV9.png](https://i.imgur.com/n77xtV9.png)

However, the file dates were 2017, and after more than 24 hrs and a docker restart they are still showing at the top of my "newest" list as unknown.  The file dates are wrong, but that's my problem.  Unknown seems worse than using the file date.  Can you explain why these didn't pull in the date modified or created date (same in this case) and how I could fix in the future?

All of my "problem" photo are low resolution (750x1334 apple saved message pictures labeled .PNG.jpg
example folder structure: /originals/phone 2-21-2018/101APPLE/IMG_1606.PNG.jpg

**Comment by egyptianbman** [comment]
It is true that I imported gigabytes of photos but I think there's an issue, still. For example, I see one of the photos was imported with the following on the *FILES* tab:

Name | 2007/02/20070218_191238_F132DBF4.jpg
-- | --
Added | Jan 4, 2021, 4:33 PM in 1,004 ms

Unfortunately, the DETAILS tab shows *Unknown* for each of `Day`, `Month`, `Year` and `Local Time`.

**Comment by tootbrute** [comment]
Personally, I don't care where Unknown files show up (top or bottom), but it would be nice to be able to search for photos with "Unknown' dates. Then we can find our bad files, and edit the metadata manually.

**Comment by graciousgrey** [comment]
@egyptianbman the date from file names is often unreliable we only use it for sorting / importing see https://github.com/photoprism/photoprism/issues/877

**Comment by egyptianbman** [comment]
@graciousgrey thanks for clarifying. I think I saw somewhere that there's batch date updating planned for a future release so I'll patiently wait for that.

**Comment by graciousgrey** [comment]
@egyptianbman yes, batch edit is coming, I also wait for it to fix some dates and locations :)

**Comment by tanuva** [comment]
I see unexpected behavior around image files with *unknown* dates. I hope I'm not accidentally mixing in a different problem here though.

My photo library also has a folder with old desktop backgrounds. They are comparatively low resolution and have no photo metadata whatsoever, therefore the quality filter rightfully rejected them on the initial library scan. I manually approved these background images. After approval they ended up at the top of my library when sorting with 'newest first'. However, none of the files has a modification date newer than 2018. There are plenty of photos newer than that.

These backgrounds also *stay* at the top when I add new photos to the library.

May the quality review process have interfered with the sorting date?

Possibly relevant: Because I had > 500 photos in review I disabled the filter by now. (What happens to yet unreviewed files then?)

**Comment by lastzero** [comment]
@tanuva We've improved date extraction and time zones in the January 28, 2021 update, see [Metadata: Fallback to earliest file mod time in case there is no other date #930](https://github.com/photoprism/photoprism/issues/930)

The filter won't approve photos... once you enable it, unapproved files will be hidden again.

**Comment by tanuva** [comment]
Looks good, the approved wallpapers don't show up in an unexpected place anymore when ordering by date. 👍

**Comment by graciousgrey** [comment]
Is there something left to do here?
