### ISSUE TITLE
Show album membership in photo details

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#809]
When opening the details for a photo I'd like to see and be able to edit the album memberships for this specific photo. With large imports, where often EXIF data is incomplete, I come across photos that meet certain album criteria. 

Then I'd like to know whether this photo is already in a specific album and/or I want to add it to an album, another album, or to a new album from this view. The latter I think is already possible through the round context button. 

Possible? :)

**Comment by graciousgrey** [comment]
A similar one is already on the roadmap  https://github.com/photoprism/photoprism/issues/373 :)
