### ISSUE TITLE
"Error 1114: The table 'photos' is full / record not found" while indexing

### ISSUE THREAD

**Issue by tanuva** [photoprism/photoprism#814]
G'day!

I have just (very happily!) installed Photoprism and told it to index my library of ~29000 photos. At count 3563 the number in the "Photos" item in the sidebar on the left stopped increasing. In the indexing log I see this error message come up for every new photo that is being indexed:
```
2021-01-04 19:38:14 ERRO index: Error 1114: The table 'photos' is full / record not found in “<redacted>” (find or create photo)
2021-01-04 19:38:12 ERRO Error 1114: The table 'photos' is full / record not found
2021-01-04 19:38:12 INFO index: failed main jpg file “<redacted>”
```

Photoprism is running in Docker as recommended in the docs (with a docker'ed mariadb server) on an Arch Linux host (Xeon E3, 8 GB RAM).

Can you guess what the problem might be? What can I do to help?

**Comment by tanuva** [comment]
Ah well. And then I realized that the rootfs is... full. I shall put the storage folder somewhere else and report back afterwards. 😅

**Comment by lastzero** [comment]
SQLite?

**Comment by lastzero** [comment]
Yes, disk seems to be full :+1:

**Comment by tanuva** [comment]
Yup, moving the Photoprism storage onto the actual storage disks allows it to continue indexing. \o/
