### ISSUE TITLE
[QUESTION]Photos appear in browser but appear broken in apps

### ISSUE THREAD

**Issue by imjoep** [photoprism/photoprism#818]
I'm running Nextcloud where I backup all my photos.  I'm mounting Photoprism to point at my nextcloud photo directory.  When I pull up my photoprism in a web browser, all of the images load as expected.  When I log into the app (on either ios or android) I just receive a bunch of broken images with exclamation points.  I initially thought it was a permissions issue, either on the files in Nextcloud or on the indexing but that doesn't appear to be the case.  

I also attempted importing rather than indexing to see if that would resolve it but it did not.  The logs only show that it successfully loaded X # of pictures (level=info msg="photos: found 100 results for photo:true dist:20 count:100 offset:200 merged:true [52.103907ms]").  

I tried resetting the database (docker-compose exec photoprism photoprism reset), I tried stopping/pulling/starting the latest image.  

I tried deleting the app from the iphone and reinstalling.  I can't figure out why the apps won't display any images.  

![IMG_C7F39A98A3F6-1](https://user-images.githubusercontent.com/49413414/103689220-9e827c00-4f58-11eb-956f-1475d1ec22a8.jpeg)

**Comment by lastzero** [comment]
We've very recently improved the security of our API by using a random preview token by default - it previously was just `public`, so that you could theoretically find thumbs by knowing their sha1 hash.

The app must be updated accordingly and is maintained by a different team in a separate repository:

https://github.com/photoprism/photoprism-mobile/

Can you open an issue there, please? 🐳

In the meantime, downgrading your PhotoPrism version should work.

**Comment by benmccann** [comment]
Do you have any advice on how we can get the random preview token? Is it returned by another API and we then need to pass it along?

**Comment by lastzero** [comment]
You'll get the previewToken from clientConfig in the page header, via push notification; it's also available via `/api/v1/config` and might also be returned by the create session api. Note that clientConfig doesn't contain the secret token in non-public mode as it is always visible, even without authentication. Also it's not good for native apps and clients for the obvious reason.

**Comment by lastzero** [comment]
I'll take a look at this, but it's been a long day (and week), so I need a break 👍

**Comment by lastzero** [comment]
Please test this with our latest version. When using it in public mode, the token is now `public` again to be compatible with clients that don't use the proper security token yet.
