### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#819]
There is a label ":dollar: Funded on Issuehunt" and also a label "funded" where the description is "Funded on IssueHunt"

**Comment by lastzero** [comment]
We've signed up for issuehunt a long time ago but it doesn't provide sustainable funding. GitHub Sponsors was introduced after and fits our needs much more. So there are different labels. What is the todo?

**Comment by benmccann** [comment]
This ticket isn't really about sponsors vs IssueHunt but about the fact that there are two labels for funded via IssueHunt. 

There is a label ":dollar: Funded on Issuehunt" and also a label "funded" where the description is "Funded on IssueHunt". I think only one of those two should be needed. Does that make sense?

**Comment by lastzero** [comment]
It's because they automatically added those I guess. Taking care of this once we may close our IssueHunt account.
