### ISSUE TITLE
Remove use of string-strip-html

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#826]
I see a function [`addCaptionHTMLFn` in the source code](https://github.com/photoprism/photoprism/blob/9ec23813070f66412460e15d13966fa209765d10/frontend/src/common/viewer.js#L117). If I `grep` for it I find it only the declaration of it and don't see anything using it

```
$ grep -r addCaptionHTMLFn src/
src/common/viewer.js:      addCaptionHTMLFn: function (item, captionEl /*, isFake */) {
```

I think if it is unused we could remove `string-strip-html` which would get rid of 100kb. If `addCaptionHTMLFn` is used it'd still be nice to see if we can get rid of `string-strip-html` since it's rather heavy for what it does. Maybe we could just use `textContent` instead of `innerHTML`?

**Comment by lastzero** [comment]
Without having time to take a detailed look: Think it is used for generating the HTML for the image titles / descriptions at the bottom of the lightbox?

**Comment by benmccann** [comment]
Yeah, I think you're right. It looks like this is passed as an option to PhotoSwipe where it's used and that's why I didn't see it called anywhere in the code.

I do think we could probably use `textContent` instead of `innerHTML` here and get rid of `string-strip-html`. I've change the title of this issue accordingly

**Comment by lastzero** [comment]
We use HTML here so that it's possible to add an optional icon / link for playing related videos - it's an ugly solution, but the only way I found without modifying PhotoSwipe.

**Comment by benmccann** [comment]
We should be able to write our own method to sanitize the user input without using `string-strip-html` and still set the result to `innerHTML`.

Here are two options that would be lighter than having to import the `string-strip-html` library:

```
function sanitize(text) {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}
```

```
function sanitize(text) {
  var tmp = document.createElement('div');
  tmp.textContent = text;
  return tmp.innerHTML;
};
```

**Comment by lastzero** [comment]
As long as there is no risk of code / html injection, sure :+1:
