### ISSUE TITLE
Sharing: Manual WebDAV upload of video and RAW files

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#829]
As a user I want to upload videos and raw files manually from my photoprism instance to e.g. nextcloud.

**Acceptance Criteria:**

- [x] Implement manual upload of videos and raws (including heic) via webdav
- [x] Write unit tests
- [x] Update docs

**Comment by lastzero** [comment]
This has been implemented as part of...

- #1376

...when you select the manual upload size "Originals":

![manual-upload-originals](https://user-images.githubusercontent.com/301686/156323439-7b442055-70fa-4f31-ac8b-73e5facdca23.png)
