### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by uxusoft** [photoprism/photoprism#830]
Hi!

My Photoprism machine have GPU:
```
~# lspci -v -s $(lspci | grep VGA | cut -d" " -f 1)
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06) (prog-if 00 [VGA controller])
	DeviceName:  Onboard IGD
	Subsystem: Micro-Star International Co., Ltd. [MSI] Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 32
	Memory at f7800000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
```

But during indexing only CPU is utilized:
```
~# atop
```
<img width="251" alt="Screenshot 2021-01-06 at 13 47 28" src="https://user-images.githubusercontent.com/64733669/103770736-c7714280-5026-11eb-85dc-b60d5cf87c19.png">

```
~# intel_gpu_top
```
<img width="587" alt="Screenshot 2021-01-06 at 13 47 09" src="https://user-images.githubusercontent.com/64733669/103770826-ec65b580-5026-11eb-87ca-9f2dd5eedd8b.png">

Just curious, is it possible/planned to use GPU during indexing/tensorflow/ffmpeg/blackman etc?

**Comment by lastzero** [comment]
![IMG_20210106_141940](https://user-images.githubusercontent.com/301686/103772748-4c119000-502a-11eb-80df-4a920c114bf3.jpg)

Test device with Nvidia GPU just arrived... if you don't want to wait, you have to manually replace the existing, general TensorFlow libs with a GPU optimized version.

**Comment by Mr-dbo** [comment]
> ![IMG_20210106_141940](https://user-images.githubusercontent.com/301686/103772748-4c119000-502a-11eb-80df-4a920c114bf3.jpg)
> 
> Test device with Nvidia GPU just arrived... if you don't want to wait, you have to manually replace the existing, general TensorFlow libs with a GPU optimized version.

Which version of TensorFlow should I use to support Nvidia GPU?
