### ISSUE TITLE
Allow URLs to be bookmarked / shared. Don't lose page when reloading

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#831]
If I open up a photo or video the URL is something like https://demo.photoprism.org/photos#&gid=1&pid=1. It'd be nice if the photo ID were in the URL so that if I refreshed the page the same photo would load. E.g. something like https://demo.photoprism.org/photos/2305e512e3b183ec982d60a8b608a8ca501973ba

I'm not that familiar with `vue-router` and whether this would be the best way to implement it, but since the background of the lightbox is opaque you might be able to simply make a new page for the lightbox instead of having it be a modal.

**Comment by lastzero** [comment]
The viewer just displays search results, as it is implemented right now. So photo 1 doesn't refer to a specific photo, just to the first result. I would expect users to be disappointed if they save or share a link to a photo and then another photo appears (or none, if there are no results this time).

Once we have time and a budget, I'm more than willing to give our photo viewer an upgrade. We also need URLs for individual photos to implement link sharing (on our roadmap).

**Comment by benmccann** [comment]
`hls.js` and `mediaelement` are very large packages, which together are about 1MB. These packages are used by the video player. 
`p-video-dialog` is statically loaded in `app.vue`, so even when dynamically loading routes as in https://github.com/photoprism/photoprism/pull/841 these packages still end up in the main bundle

I think if the photo and video players were both routes instead of dialogs it would allow them to be lazily loaded, which would cut down on the package size a lot. This in addition to the original motivation suggested here of allowing bookmarking, page reloading, etc. Just noting this as an additional consideration to take into account if any updates are made here

**Comment by graciousgrey** [comment]
Closed in favor of: https://github.com/photoprism/photoprism/issues/1307
