### ISSUE TITLE
iOS: Multi-select using long click doesn't work

### ISSUE THREAD

**Issue by adan89lion** [photoprism/photoprism#832]
Hi,

I’ve recently switched my workflow from macOS to iPadOS, and encountered multi-selecting issues with Safari on mobile devices.

Step to reproduce:
1. Open PhotoPrism instance on iOS, with Safari or Chrome [1]
2. Open Review tab (or photo stream, or any album)
3. Select the first image
4. Long press the last image to make a selection
5. Doesn't select images, but shows out text selection frame

Expected behaviour:
Make a selection from the first selected image to the long pressed image.

What went wrong?
It calls out Safari’s text selector

Did it work before?
It works perfectly on Android’s Chromium based browsers (tested on Chrome, Brave and Samsung Internet) and Fennec. This issue does not apply to desktop based systems (since we use Shift and Control to select massively)

Other notes:
N/A

[1] Browsers on iOS / iPadOS are all using WebKit, so any browser will have the same issue.

**Comment by lastzero** [comment]
Might be handling DOM / JS events differently. Needs to be debugged and fixed in this case.

**Comment by lastzero** [comment]
Just ordered an iPad so that I can test this properly:

![ipad](https://user-images.githubusercontent.com/301686/104768328-c00c1080-576d-11eb-80af-4216bc545dc3.jpeg)

If you're not a sponsor yet, consider supporting us financially. Thank you! :heart:

**Comment by alexislefebvre** [comment]
Have you been heard about Browserstack? :smiley: https://www.browserstack.com/list-of-browsers-and-platforms/live

**Comment by lastzero** [comment]
On Fri, 15 Jan 2021, 22:28 Alexis Lefebvre <notifications@github.com> wrote:

> Have you been heard about Browserstack? 😃
> https://www.browserstack.com/list-of-browsers-and-platforms/live
>
Browserstack is not a UX testing tool, and also not completely free from
what I remember.

**Comment by lastzero** [comment]
Browserstack is $348 per year minimum:

![Screenshot 2021-01-15 at 22 51 09](https://user-images.githubusercontent.com/301686/104782243-2ef46400-5784-11eb-8ce7-7bf430986085.png)

**Comment by alexislefebvre** [comment]
(I removed my previous comment shortly after posting it, I thought it wasn't heplful, and you proved it)

**Comment by lastzero** [comment]
No worries 🌈 iPad should arrive tomorrow so that I can test all issues and hopefully fix them! No iOS device anymore since I switched to Huawei because of the excellent camera. Using a simulator is not the same by any standard.

**Comment by lastzero** [comment]
Let us know if this works for you :)

Maybe @benmccann can have a second look at event handling :eyes:

**Comment by benmccann** [comment]
I'm not on iOS either, so can't really test. BrowserStack will give free accounts for open source if it's helpful. I have one with all the bells and whistles

**Comment by lastzero** [comment]
> I'm not on iOS either, so can't really test. BrowserStack will give free accounts for open source if it's helpful. I have one with all the bells and whistles

Saw that. Probably takes a couple of days until we may get approved. Even then, it's a tool for testing - not for UX optimization. Need the real experience. Feels much better now.

Don't 100% like how click and touch events are mixed, also not sure if there are edge cases when multiple fingers are being used. Anyhow, major improvement to what we had before.
