### ISSUE TITLE
Mounted directory in docker compose file not being indexed or shown properly

### ISSUE THREAD

**Issue by muzzah** [photoprism/photoprism#834]
I have both nextcloud and photoprism installed on the same host. So I am just trying to link the directory in nextcloud with my photos into photoprism. While the folders and subfolder with images come up in library, they all show  empty.

Does Photoprism support mounting a single folder with many subfolders?

**Comment by lastzero** [comment]
Check permissions.

**Comment by muzzah** [comment]
Yeah that might have been it. Though the Nextcloud docker user doesnt exist so I had to set the user to run as to root

`user : "0:0"`

which is not great. I could create the user on the host or I could open up the permissions on the folder which is also not ideal.
I will close the issue but any tips on how to handle this would be great
