### ISSUE TITLE
Indexing more than one file at a time freezes raspberry pi

### ISSUE THREAD

**Issue by gomme600** [photoprism/photoprism#835]
If I upload pictures one by one and then index each individual folder then things work fine. If I upload more than a few photos (like 4) then the whole pi 4B freezes and hangs for a long amount of time. I have set the number of worker to 1. Also if I index the whole imports directory then the pi will hang for hours even if I have only uploaded a single fine, it is as if all of the photos are reindexed! I have a 2GB RAM pi 4B with ZRam enabled for a total of 2GB swap aswell as an extra 256MB swap on the SD card.
Thanks for any help!

**Comment by gomme600** [comment]
I am wondering if the number of workers is set correctly as in theory I would think that 1 worker would be the same as uploading individually, this is the part of my docker-compose:

 environment:
      PHOTOPRISM_AUTO_INDEX: 60
      PHOTOPRISM_AUTO_IMPORT: 120
      PHOTOPRISM_WORKERS: 1
      PHOTOPRISM_ADMIN_PASSWORD: "please-change"     # Initial admin password: PLEASE CHANGE!

**Comment by gomme600** [comment]
Unless maybe it is a memory problem? Maybe the worker doesn't give back memory until all the photos have been indexed thus increasing RAM usage for each index until it is complete.

**Comment by lastzero** [comment]
Do you have 4 GB and swap configured?

**Comment by gomme600** [comment]
No, I have a 2GB pi 4B and 2GB a ZRAM (so 2GB swap) and 256MB of swap on the sd card. Using swap on the SD card really kills performance. I know that this is under the minimum system requirements but I don't understand why indexing one photo at a time works perfecly but indexing a folder of photos with 1 worker doesn't! I have an 8GB pi on order so I will soon see if it makes a difference.

**Comment by lastzero** [comment]
Try disabling TensorFlow. Requires a restart.

**Comment by gomme600** [comment]
Ok, I will try, although automatic tagging is a feature that I would prefer to keep using. If I index the photos without tensorflow would reindexing them when I get the nex pi 8GB with tensorflow generate the tags? Or would I have to start from scratch? Thanks

**Comment by lastzero** [comment]
It should add labels later, when you re-index all.

**Comment by gomme600** [comment]
Ok, have received the raspberry pi 8GB and with the same setup and 2 workers everything seems fine! lots of RAM is definitely needed! Currently using 2.26GB (and increasing) with 2 workers. CPU overclocked to 2GHz and is almost maxed out but the other applications still seem responsif. What would the max recommended amount of workers be for this kind of setup? Thanks for this great project!

**Comment by lastzero** [comment]
2 seems fine, also because Pis typically have slow I/O (USB, SD, network storage,...). You may try 3, but it really depends on the overall system resources, CPU is just one factor.
