### ISSUE TITLE
Utilize Vite for frontend development

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#838]
https://docs.photoprism.org/developer-guide/setup/ says to run `make all`, but that takes about 1 minute to run on my machine, which really slows down development cycles. I'm guessing that there's some other workflow that you use to run in development mode? But either way, [Vite](https://vitejs.dev/) would be much faster. It was written by the Vue.js lead specifically to speed up Vue development

**Comment by lastzero** [comment]
npm run watch

**Comment by benmccann** [comment]
Do you run that inside of docker or outside? What port is the app available on when you run that?

**Comment by lastzero** [comment]
Outside in the frontent directory is fastest if you have npm etc installed.

**Comment by lastzero** [comment]
Inside the container:

```
make dep-go
. /photoprism start
```

to compile and start the backend ✨

**Comment by benmccann** [comment]
Hmm. I'm afraid I'm still a bit confused

It looks like `./photoprism start` does more than run just the backend. It seems it also runs the frontend

Also, when I run `npm run watch` it doesn't say what port the server's running on, so I'm not sure how to access it

**Comment by lastzero** [comment]
You don't need to "run" the frontend. It's a Go application with built-in web server. The frontend is built and then served as static JS / CSS. This may happen dynamically with a watcher, thus `npm run watch` in the `frontend` folder.

**Comment by lastzero** [comment]
Guess you're used to full-JS apps that use nodejs in the backend as well, thus need to be started as HTTP server?

**Comment by benmccann** [comment]
Ah, got it. Thanks! I'll close this then and send a PR to update the contributor's guide instead
