### ISSUE TITLE
UX: display video player in lightbox

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#843]
When you view a photo it shows it on a dark background. When you view a video you still see the PhotoPrism app in the background. It would be nice to make it display with the same background as a photo for consistency and to remove the distraction of seeing the app in the background

**Comment by lastzero** [comment]
Seems there are different opinions on this 🤔 

You can make it fullscreen for now... the video player doesn't have prev / next controls like the photo viewer, so it would just be an unused, black frame. Ideally, we have our own combined photo & video lightbox later so that you always get the same experience - independent of the media format.

**Comment by benmccann** [comment]
For what it's worth, Google also uses a black background with it's video player

**Comment by alexislefebvre** [comment]
Instead of clicking on the video, click on the title, then on the preview image, then on the play button, and you'll have a dark background with the video in the center.

**Comment by graciousgrey** [comment]
The new video player is much darker than the old one. Is it dark enough @benmccann ?

**Comment by alexislefebvre** [comment]
Is there a reason to have different backgrounds for photos and videos? On the demo website, I can't see the background when viewing a photo, but I can see the UI when viewing a video.

**Comment by lastzero** [comment]
We like it this way, but are willing to add yet another setting for this 😅 Telegram for example also uses a semi transparent background for videos...

**Comment by lastzero** [comment]
Also many videos are much smaller than photos, although that may change with 4k ultra HD long-term. Don't believe a big black border looks good or modern. If you have other insights, please share.

**Comment by alexislefebvre** [comment]
I'm sorry but I don't understand the "big black border" part. Like on photo viewer?

Here is the result on my screen with media with similar ratio:

Photo:

![image](https://user-images.githubusercontent.com/2071331/107426138-23485300-6b20-11eb-99c9-c7399d3b00a1.png)

Video:

![image](https://user-images.githubusercontent.com/2071331/107425888-db293080-6b1f-11eb-9365-da4ee28394b3.png)

I find the flower distracting.

**Comment by lastzero** [comment]
Try a 640x480 video, not the iPad air retina screen recording.

**Comment by alexislefebvre** [comment]
I tried and well, make up your own mind:

![image](https://user-images.githubusercontent.com/2071331/107428974-a6b77380-6b23-11eb-8a89-0525343fc7a4.png)

**Comment by benmccann** [comment]
I think it's distracting to see something behind the video regardless of video size (and in fact worse with smaller videos since you see more other stuff) and inconsistent with the photo viewer

I'm not sure how many settings we'd want to add. It seems like it'd become difficult to maintain them all. But maybe video player background color could be part of a theme?

**Comment by lastzero** [comment]
Same when you open a wide in windows or macOS. Why not make it full screen? Why full attention on a small video?

**Comment by lastzero** [comment]
Happy to make this part of a theme... Easy to change.

**Comment by benmccann** [comment]
I'm not quite sure I understood the Mac/Windows thing cause I don't have either of those OSes. But I think you're saying the video player doesn't open full screen so you see stuff outside the video player. The other side of that though is that the rest of the video player background is black I believe. So the analogy here would be that the video player background would be dark and you could make Chrome not full screen and see other apps behind Chrome.

**Comment by lastzero** [comment]
Either I want to have a quick look what the videos is, then I don't mind seeing the context. Just like when browsing a video folder on whatever operating system. When I want to enjoy a full length video without distraction, I always make it full screen like on every TV out there.

**Comment by lastzero** [comment]
Note that the photo viewer has prev, next and action buttons, so I don't need other context as it's a complete "app" by itself.

**Comment by lastzero** [comment]
These are top ranked "browse videos" example screenshots on Google image search:

![guida-windows-10-supporto-mkv-quotmatroskaquot-h 265-tutte-altre-novita-ambito-audio-video-windows-10-mkv-matroska-shell-2903 img](https://user-images.githubusercontent.com/301686/107438214-71655280-6b30-11eb-8475-c28d0100dd29.png)
![Videodateien_direkt_im_Quad-Explorer_betrachten_unter_Windows_10_2019-06-12-16-43-59](https://user-images.githubusercontent.com/301686/107438217-71fde900-6b30-11eb-8050-2ca5843768f7.png)

**Comment by benmccann** [comment]
I think that the video player should also have prev and next buttons. It's strange to me that if I click the second thumbnail on https://demo.photoprism.org/browse that I can go back to the video or forward to the next picture, but if I click the video I can't go back or forwards. It's just as desirable for me to go from one video clip to the next as it is to go from one photo to the next.

On Google Photos I can use arrow keys or prev and next buttons regardless of whether it's a photo or a video.

**Comment by lastzero** [comment]
Enjoy what we have in store now and stay tuned for more. Again, I don't enjoy Google photos and don't want to copy it 1:1 even though it may be the gold standard for you. It's clear we need our own combined viewer for photos and videos. It must also support lazy loading. Just can't deliver it by tomorrow, also given we didn't reach our funding goal yet and should focus on facial recognition plus your pull requests next...

**Comment by lastzero** [comment]
Googles Youtube is also not exactly distraction free if not in full screen mode (desktop version shows even more context):

![Screenshot_20210210_001806](https://user-images.githubusercontent.com/301686/107441503-a0ca8e00-6b35-11eb-9770-14f73dd06699.jpg)

Are videos really something you consume like photos and just keep in swiping through? Not my medium, I'm a photographer 📸

**Comment by benmccann** [comment]
> Are videos really something you consume like photos and just keep in swiping through?

Yep. Most of my pictures and videos are of my kid. Most of the videos are just 5-10s clips of her doing something cute/funny, so very easy to scroll through a bunch of these in one sitting. I'll consume them like a stream and don't really care whether they're pics or videos. Just want to see them all and swipe from one to the next

**Comment by lastzero** [comment]
@benmccann We'll keep that in mind moving forward 👍

**Comment by graciousgrey** [comment]
I will close this ticket as duplicate. It will be implemented as part of this ticket: https://github.com/photoprism/photoprism/issues/1307
