### ISSUE TITLE
Feature Request: Select All button

### ISSUE THREAD

**Issue by cympfh** [photoprism/photoprism#845]
To add photos to an album, users have to select all photos. For example, it's convenient if there is "Select All" button in the search result pages.

**Comment by lastzero** [comment]
With infinite scrolling, selection length is not defined. Has been discussed in previous GitHub issues before. Selecting all could possibly mean millions of pictures.

**Comment by graciousgrey** [comment]
More information can be found here: https://github.com/photoprism/photoprism/issues/272

**Comment by cympfh** [comment]
Okay. Thanks!
