### ISSUE TITLE
Thumbnails not loading (maybe a cache issue?)

### ISSUE THREAD

**Issue by gomme600** [photoprism/photoprism#846]
Since a few days ago thumbnails are loading intermittently, this was working fine before. I have even had this happen on the photoprism demo server once! I have tried restarting photoprism and I have also tried completly starting from scratch. If I use another browser then the photos will load fine once but then the same problem occurs again later. Maybe it is a browser cache problem? But this is happening on both chrome and firefox on different machines. The photoprism log doesn't show anything strange when this occurs.

**Comment by gomme600** [comment]
After clearing browser data the issue is gone. So it's a problem on that side of things. What is weird though is that this has been happening often and on different browsers and machines.

**Comment by lastzero** [comment]
It's be because we use a random preview Token now, so that needs uo be initialized in JS first. May only happen after reloading or first load. Browsers shouldn't cache the placeholder though.

**Comment by gomme600** [comment]
After waiting a few hours it usually works again until I reload. Clearing browser cache is an instant fix. Also, the android app is broken now, the thumbnails don't display but if I click share they do download correctly.

**Comment by lastzero** [comment]
You can manually set the token to `public` (see config options). This should fix it.

**Comment by lastzero** [comment]
Is this also happening on the Raspberry Pi with 2 GB RAM?

**Comment by gomme600** [comment]
Yes, it's the same raspberry pi. But last week I didn't have this problem, I have been running photoprism for about a month now.

**Comment by lastzero** [comment]
Timing might be important here - I assume thumbs are loading slow. I'll take a look at this in the next couple of days, maybe we wait with loading thumbs until the token was initialized.

**Comment by gomme600** [comment]
Is this the correct setting to change ? PHOTOPRISM_PREVIEW_TOKEN

**Comment by lastzero** [comment]
I've just improved this, so that the right token should be used straight away. Preview builds are running, available soon. If you still have issue, it's not because of the tokens and there are other issues.

Might be possible that thumbs are missing since the indexer crashed as it ran out of memory.

**Comment by gomme600** [comment]
Latest preview update seems to have fixed this! Thanks for the fast support!
