### ISSUE TITLE
Some videos not playing while others (with same codec do)

### ISSUE THREAD

**Issue by muzzah** [photoprism/photoprism#855]
I have some iphone videos that have been indexed. Thumbnails show without problems.

When I go to play, I see a lot of the download happening (1preloaded bar in video player moves forward) but the video either does not play or when it does, it is very choppy with frames skipping.

I have photoprism hosted on a VPS in the same city I live so the download speeds are about 2 MB/sec. I see from my nginx logs that 203 partial responses are being returned. The VPS has plenty of memory and is not CPU bound.

This is the error I get (Video size is about 190 MBs) if video fails to play
![Screen Shot 2021-01-07 at 20 49 46](https://user-images.githubusercontent.com/1034537/103940062-14d7d780-512d-11eb-895f-0112d92bd20c.png)

I have observed this in both safari and firefox. Photoprism version is photoprism/photoprism:20210104

**Comment by muzzah** [comment]
I just noticed some output in nginx logs that shows the photoprism server not responding

`nginx-proxy    | 2021-01-07T20:26:35.192307347Z nginx.1    | 2021/01/07 20:26:35 [error] 535#535: *56910 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.8.0.2, request: "GET /api/v1/videos/ac32d6d74a701daa1492368d121bb359b01019e7/fd8ccb6c/avc HTTP/2.0", upstream: "http://172.18.0.9:2342/api/v1/videos/ac32d6d74a701daa1492368d121bb359b01019e7/fd8ccb6c/avc", , referrer:[photoprims domain]`

Not sure if there are more log output i can enable to help here

**Comment by muzzah** [comment]
Ok another interesting thing I just noticed, the VPS is hitting its CPU limit when trying to view some of the videos all with photoprism workers trying to do something.  I guess its trying to do some transcoding on the fly? Should I up my CPU count for the instance? Though some videos work without problem.

![Screen Shot 2021-01-07 at 21 31 03](https://user-images.githubusercontent.com/1034537/103942076-1fe03700-5130-11eb-8aca-44c6f2498350.png)

**Comment by lastzero** [comment]
Does nginx support HTTP video streaming (with your current configuration)? Transcoding should only happen if your videos are not AVC encoded already.

**Comment by muzzah** [comment]
Well its streaming some videos fine so yes. This problem happens intermittently. I see a lot of avc files being created into the sidecar folder on demand, that is, if I request a certain file to stream (which I am assuming has not been avc encoded already) then the transcoding kicks in while I wait for the stream to begin. But because I only have 2 CPUs on the VPS instance, what I assume is happening is the transcoding is taking a long time and the browser just gives up and shows the above error.

I guess the question here is is the transcoding meant to happen at indexing time or at request time? Because all these videos have already been indexed. The transcoding which uses up the CPUs happens once I then try to view the video.

**Comment by muzzah** [comment]
Just another update on this front, I am also seeing these in the console logs for firefox

<img width="1415" alt="Screen Shot 2021-01-10 at 23 05 56" src="https://user-images.githubusercontent.com/1034537/104136807-b9118680-5398-11eb-822b-4d528df7c8e0.png">

**Comment by alexislefebvre** [comment]
Try with Chrome / Chromium. It may read videos while Firefox can't.

**Comment by muzzah** [comment]
While it may be a browser codec issue, I am not 100% convinced it is. I see this in Safari too and I avoid chrome for varioud reasons. Some videos play fine that use the same codec. In fact some that initially fail, do play eventually and I think its because of the issue mentioned above which is the on the fly transcoding that happens. It ends up using all my CPU on the VPS and the site just starts to fail as a result in general until the transcoding is done. I would have thought that doing the transcoding at indexing time would be better since you can then show the video as indexed and play it without issues.

**Comment by lastzero** [comment]
@muzzah Transcoding at indexing time will also result in UX issues as it would consume additional storage and CPU time while indexing this causing high system load. I'll eventually build a top-class transcoding pipeline free for everyone, but this is what we have in store now. If transcoding fails because your server is running out of memory or other system resources, this will also happen when transcoding earlier e.g. while indexing.

**Comment by muzzah** [comment]
Yeah I understand @lastzero 
Is there any way to configure the number of workers that the transcoding process uses in the meantime? If I could limit it to 1 CPU that could help here.

**Comment by lastzero** [comment]
One, see https://github.com/photoprism/photoprism/issues/703#issuecomment-743983871

**Comment by muzzah** [comment]
Had not come across that issue, it is pretty much the same thing as what I am experiencing, I will close this issue as a duplicate of #703 then and keep an eye on that issue.

**Comment by lastzero** [comment]
@muzzah While performing tests for the update released yesterday, we found out that videos were preloaded by browsers - so when you opened the video page, it may have caused a lot of traffic and consumed tons of memory on top of it.

We're now playing live photos using custom events, and disabled preloading. This solves all issues for me in Firefox. Videos are playing, despite the "no decoders" warning.

**Comment by muzzah** [comment]
Thanks @lastzero I will update to version 20210111 and see how it goes.
