### ISSUE TITLE
Page that shows all photos and videos

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#856]
It looks to me like there's a "Photos" page and "Videos" page, but no page that displays both together. I really appreciate being able to see everything on one page together like Google Photos offers as their homepage

**Comment by lastzero** [comment]
https://demo.photoprism.org/browse

**Comment by benmccann** [comment]
That's great! Is there anyway to get there? I can't find a link to it in the UI. I'd love if that were the homepage! :smile:

**Comment by lastzero** [comment]
From labels 😉

**Comment by lastzero** [comment]
We'd have to rename Photos to Search or Browse in the navigation. Not 100% sure about this yet.
