### ISSUE TITLE
UX: Expanded search form with labels

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#857]
I wanted to share this idea for the search form and see what you thought of it. It takes up more room, but we're not short on space. I found this helps me digest the search form and more quickly understand what the different controls do

I can send a PR if you want to play around with it locally to see what it looks like

### Before

![Screenshot from 2021-01-07 16-00-15](https://user-images.githubusercontent.com/322311/103958307-869a2c00-5101-11eb-83ef-fefe25fef8de.png)

### After

![Screenshot from 2021-01-07 15-56-57](https://user-images.githubusercontent.com/322311/103958212-4c308f00-5101-11eb-8d62-f41d542d4d66.png)

**Comment by lastzero** [comment]
Too much space lost on mobile :/

**Comment by benmccann** [comment]
Here's what it looks like on mobile

![Screenshot_20210108-070159](https://user-images.githubusercontent.com/322311/104030630-8bea8b80-5180-11eb-81e8-912b8c9b8653.png)

There is one search filter that's beyond the fold that you have to scroll to reach though I don't really notice that (Google's Photo search actually takes up more then two full screens vertically).

Let me know if you still think it takes up too much space and I can either rethink it or close this

**Comment by lastzero** [comment]
Try on an iPhone 5s / SE 2.

**Comment by benmccann** [comment]
I don't have a physical device matching those specs, but here's what the Chrome emulator shows for iPhone 5/SE.

![Screenshot from 2021-01-08 09-47-05](https://user-images.githubusercontent.com/322311/104047493-93b52a80-5196-11eb-8ce3-b13ed42f9a3c.png)

**Comment by benmccann** [comment]
I'll close this for now because I think it's something that might be fixed if we upgrade to Vuetify 2
