### ISSUE TITLE
Thumbnails: consider whether to change default jpeg quality

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#860]
I noticed today that Chrome's suggesting we could shave 20s off the load of the thumbnails on the demo site by using a more efficient jpeg encoding, which would be a big win in terms of latency, disk usage, and bandwidth though at the tradeoff of longer indexing time

![Screenshot from 2021-01-07 20-51-58](https://user-images.githubusercontent.com/322311/103976051-9aa65380-512a-11eb-9df1-d29a3e053bcc.png)

**Comment by lastzero** [comment]
Chrome suggests a lot when the day is long (German saying). Typically big tech tends to compress all images to death to save storage as they give it away for free.

I don't see any relevant options here other than `jpegQuality`, which you already can change in Advanced Settings:
```
type encodeConfig struct {
	jpegQuality         int
	gifNumColors        int
	gifQuantizer        draw.Quantizer
	gifDrawer           draw.Drawer
	pngCompressionLevel png.CompressionLevel
}
```

See:

https://github.com/photoprism/photoprism/blob/develop/internal/thumb/create.go#L176

Please share, if you have any other insights :+1:

**Comment by benmccann** [comment]
Google Lighthouse apparently benchmarks against an 85% jpeg quality level and it looks like the demo site uses 95% ([looks like it might be defined here](https://github.com/photoprism/photoprism/blob/1516f556c270feddc7e7346b5ca7aa99cfa98501/internal/thumb/types.go#L9))

The question I guess is whether the tradeoff in better latency is worth if for slower indexing. If it's 30% faster download speed it might be 30% slower compression as well

I don't think we should use next generation JPEG encoding because so few browsers support it (JPEG 2000 only supported by Safari and JPEG XR is only supported by IE)

Feel free to close this if you don't think it's worth changing

**Comment by alexislefebvre** [comment]
See https://github.com/photoprism/photoprism/issues/668, some services replaced JPEG with WEBP.

**Comment by lastzero** [comment]
If we reduce quality to 1%, images are even smaller and downloading is much faster. What is the point though?

We've developed PhotoPrism to get the best experience. That includes the image quality as well as not having to upload private pictures.

Why would we limit image quality to the "Facebook standard" when there are no obvious performance issues (with caching!) at all and storage is super cheap? I don't get it.

**Comment by benmccann** [comment]
Sure, there's always a tradeoff between quality and size. It's just a question of what the best tradeoff is for the most people and there's probably many opinions on it.

I'll go ahead and close this since it sounds like it's not of interest

**Comment by alexislefebvre** [comment]
You can still change the quality on your instance with [`PHOTOPRISM_JPEG_QUALITY`](https://docs.photoprism.org/getting-started/config-options/) or in the settings.

**Comment by lastzero** [comment]
@alexislefebvre Right, plus we've added this to our UI in Settings > Advanced. Personally, I'd never go for bad quality for my pictures - especially when hosted at home. Spent too much for my cameras and lenses.

It's different for high traffic sites, or when using slow mobile connections. When you use an image in the header of a blog post, people are not there for the photo quality but want to read the text. There's no one-size-fits-all.
