### ISSUE TITLE
Google Takeout Import Does Not Create Albums

### ISSUE THREAD

**Issue by xCJPECKOVERx** [photoprism/photoprism#869]
Importing an album folder from Google Takeout does not create an album containing the photos within the folder. The import processes each photo and its corresponding json file, but skips over the metadata.json file which contains the album info. The imported files get added to the appropriate year folders.

Running version 210104-7f9e806a-Linux-x86_64 in docker

**Comment by lastzero** [comment]
Yes, just described this here: https://github.com/photoprism/photoprism/discussions/865

Not sure why our docs say this is implemented... but it's not, since there were too many automatically created, completely useless albums when I check the album JSON files on my personal Google Photos export... we may implement this later if there is demand and it's clear, how to deal with this in a way that doesn't cause a flood of support requests.

**Comment by lastzero** [comment]
Updated our docs: https://docs.photoprism.org/user-guide/use-cases/google/

**Comment by inthreedee** [comment]
@lastzero I'm also looking for a way to automate album import.  I have a few albums in google photos with thousands of photos and it would be incredibly time-consuming to re-create these now that I'm transferring everything to photoprism.

I see that manually created albums are stored as yml files in my storage directory.  I was hoping I could write a bash script that would scrape the file names from my google album jsons and insert them into the photoprism album yml files but, upon further inspection, I noticed that photos are listed with UIDs instead of by file name.  There's also an extra CreatedAt property.

Any suggestions on how I could accomplish this?

**Comment by inthreedee** [comment]
Update:
I believe I have it figured out.  I found the UID and CreatedAt values within the sidecar yml files.  I've written a bash script that will process all json files from a downloaded google takeout album, match up the file name with the appropriate sidecar file in an existing photoprism library, pull out the UID and CreatedAt values, and append them to a specific photoprism album yml file.

As currently written, the destination album has to be manually created first and the script ran once for each album.  Once I verify that it works on my instance, I'd be happy to share the script here if it would be of any use to this project.

**Comment by lastzero** [comment]
All YAML files are backups, so the albums should not exist if you add files via YAML files. We might add a sync between index and YAML files later. It's more complicated than just overwriting the index with whatever is in the files.

**Comment by inthreedee** [comment]
@lastzero Well that’s a bummer. Thank you for the clarification. Do you have any suggestions for other ways I might be able to accomplish this?  I can easily generate a list of photo UID’s that I want in the albums and am not afraid of doing a bit of work to build a tool for this. It would be less work than manually re-creating the albums.  Any guidance would be appreciated. 

I was also hoping to use that method to automate adding descriptions to a couple thousand photos, but I guess that can’t happen either.  I know this is only tangentially related here, but:  If the indexer recognizes Google’s json format for photo metadata, can I generate my own json files with just the description field and re-index to have that added to my photos? Or will that end up destroying all existing metadata?

**Comment by lastzero** [comment]
Since we're using a standard SQL database, you may create album entries directly in our database. There are no dedicated docs for this though. Also you may use the API, but good docs are not available either. See JS code and tests for examples.

**Comment by lastzero** [comment]
Happy to answer specific questions 👍

**Comment by inthreedee** [comment]
@lastzero Thanks! I think API calls will be the easiest option to integrate into my bash script.  I found this test, which I think is my starting point:
https://github.com/photoprism/photoprism/blob/1516f556c270feddc7e7346b5ca7aa99cfa98501/internal/api/album_test.go#L192

Based on that, I have put together this curl request that I could use some help massaging into the correct format:

`curl -X POST -H “Content-Type: application/json” -d ‘{“photos”: [“uid1”, “uid2”, “uid3”,...]}’ https://server.com/api/v1/albums/ALBUM-UID/photos`

- Is `application/json` the correct Content-Type?
- How many photo uid’s can I safely stuff into one request? If I have thousands to do, is it better to do thousands of individual requests or group them together?

For authentication, I’m having a more difficult time. Is this the right example to base a curl command on?
https://github.com/photoprism/photoprism/blob/1516f556c270feddc7e7346b5ca7aa99cfa98501/internal/api/session_test.go#L15

- Would that provide me with a token to include in the header of the above curl command?
- What header token format is expected by the API?  One example I’ve found is `-H “Authorization: Bearer {token}”`

Lastly, to automated adding photo descriptions, it looks like I can format it based on this, probably replacing `Title:` with `Description:`?
https://github.com/photoprism/photoprism/blob/1516f556c270feddc7e7346b5ca7aa99cfa98501/internal/api/photo_test.go#L34

`curl -X POST -H “Content-Type: application/json” -d ‘{“Description”: “Description of photo”}’ https://server.com/api/v1/photos/PHOTO-UID`

Am I on the right track?

**Comment by lastzero** [comment]
- `application/json` is perfect
- I suggest not adding more than 999 photos at once, although there should be no specific limit. Let us know if you find one.
- For session management, see https://github.com/photoprism/photoprism/blob/develop/frontend/src/common/session.js
- PhotoPrism uses `X-Session-ID` headers containing the session ID you'll get via `POST /api/v1/session`
- For updating photo metadata, see https://github.com/photoprism/photoprism/blob/develop/frontend/src/model/photo.js#L744
- Common (groups of) metadata fields like title, description, camera, time, and location have a source so that manual changes don't get overwritten when re-indexing
- Time for example consists of `TakenAt`, `TakenSrc`, `TakenAtLocal` and `TimeZone`
- When you change the `Title`, you should set `TitleSrc` to `manual` which has the highest priority
- Same for other (groups of) values like `TakenAt`, `TakenAtLocal` and `TimeZone` (`TakenSrc`), or `Lat` and `Lng` (`PlaceSrc`)

**Comment by inthreedee** [comment]
@lastzero Thank you very much for the help!  I now have functioning API calls and just have to integrate them into the bash script I wrote earlier to perform the automated tasks.

Out of curiosity:  What's the timeout period on these sessions?  Aside from sending a DELETE API call on individual session ID's, is there a way to expire all active sessions?

**Comment by lastzero** [comment]
You may delete the session json file in the cache path.

**Comment by inthreedee** [comment]
@lastzero Thank you so much for your help with this.  My script works perfectly and I can now easily import my Google Photos albums.

If anyone else wants to do the same thing, here is the script:
https://github.com/inthreedee/photoprism-transfer-album

Some things to note:
- This is just a quick and dirty script to get the job done; I didn't bother polishing it up too much.  You'll need to edit some variables at the top of the script to match your setup.
- It can also take a while for libraries with more than a few thousands photos.  In my case, it took about a half hour for an album with around 3,000 photos.  The reason for this is it's constantly scanning the sidecar files to match up filenames with photo UID's.  I didn't see an API call that would allow me to do this more quickly.

**Comment by StephenBrown2** [comment]
>  I didn't see an API call that would allow me to do this more quickly.

I found that you can do a sha-1 of the file and get the PhotoUID from the API with https://github.com/photoprism/photoprism/blob/1516f556c270feddc7e7346b5ca7aa99cfa98501/internal/api/file.go#L11-L14
So, you can get the PhotoUID with this curl:
```shell
fileSHA=$(sha1sum '/path/to/file' | awk '{print $1}');
curl --silent -X GET -H "X-Session-ID: $sessionID" "$siteURL/api/v1/files/$fileSHA" 2>&1 | grep -Eo '"PhotoUID":.*"' | awk -F '"' '{print $4}'
```
instead of looping through all the json and yaml files.

Took me much less than 30 minutes importing several albums around 2500 photos each.

**Comment by inthreedee** [comment]
@StephenBrown2 That is definitely much more efficient!  Good find.

**Comment by 7IM3rW** [comment]
> 
> 
> Updated our docs: https://docs.photoprism.org/user-guide/use-cases/google/

Is it only possible to copy them into the originals Folder or can one also use the import folder and start an import?
Thank you!
 @lastzero

**Comment by graciousgrey** [comment]
@7IM3rW the metadata from google mentioned in our docs (Title, Description, Date etc) is added to your photos during import as well

**Comment by cincodenada** [comment]
Thanks for this thread! I recently imported by 35,000 Google Photos and wanted to bring my albums over. I ended up taking @inthreedee's base and running with @StephenBrown2's suggestion, which worked great. I ended up going a bit overboard in polishing things, and created [my own fork](https://github.com/cincodenada/photoprism-transfer-album) that does things like prompts the user for config and imports the whole Takeout in one go. I just used it on my import and it worked a charm, I'd love to hear feedback from anyone else who finds it useful!

**Comment by graciousgrey** [comment]
It would be awesome to have a step by step guide in our docs for this :)

**Comment by inthreedee** [comment]
Update: @cincodenada submitted a PR to merge the improvements mentioned in https://github.com/photoprism/photoprism/issues/869#issuecomment-903057856 back into the original project.  I've done a lot of additional work on it to make the script user friendly and versatile so it will hopefully work for most use-cases.

https://github.com/inthreedee/photoprism-transfer-album

Notable improvements:
- A speedy hash matching mode for photo libraries that were uploaded directly from a google takeout
- Name matching mode for photo libraries that were uploaded from originals or another source
- Import all takeout albums or specify individual albums to import
- Excludes auto-generated albums, ie. hangout albums, albums by date, etc. Specify with  `--album-name` to override.
- Built-in `--help`

@graciousgrey I'm happy to contribute to the documentation if you let me know where you'd like this information to go.  A new page?  Subheading somewhere?  Just tell me where to put it and I'll write something up.

**Comment by ark-** [comment]
Ran this and it worked perfectly, thank you.

**Comment by graciousgrey** [comment]
@inthreedee I would suggest adding a section on this page: https://docs.photoprism.app/user-guide/use-cases/google/ 
Thank you very much for working on this :heart:

**Comment by devGIT07** [comment]
I am running this command with my user/password with the domain and getting error as : **Creating PhotoPrism session...
Failed to get session id, bailing!**

Can someone help what am i missing.

**Comment by the-sane** [comment]
> I am running this command with my user/password with the domain and getting error as : **Creating PhotoPrism session... Failed to get session id, bailing!**
> 
> Can someone help what am i missing.

@devGIT07 Based on your error message, I'm guessing you're referring to the script I wrote and linked in the discussion above? If you're having issues with that script, opening an issue on that repo would be the better place for that conversation. But providing the correct username, password, and domain should still be working fine unless the Photoprism API has changed.

In case the API has changed, I'll provide the relevant code snippits here for the Photoprism devs to double check:
https://github.com/inthreedee/photoprism-transfer-album/blob/main/transfer-album.sh#L34
```
sessionAPI="/api/v1/session"
```
https://github.com/inthreedee/photoprism-transfer-album/blob/main/transfer-album.sh#L526-L541
```
# Call the session API
session="$(curl --silent -X POST -H "Content-Type: application/json" -d "{\"username\": \"$apiUsername\", \"password\": \"$apiPassword\"}" "$siteURL$sessionAPI")"

# Check the login credentials
if echo "$session" | grep "Invalid credentials" >/dev/null; then
    echo "Invalid login credentials, bailing!" >&2
    exit 1
fi

# Get the session ID
sessionID="$(echo "$session" | grep -Eo '"id":.*"' | awk -F '"' '{print $4}')"

if [ -z "$sessionID" ]; then
    echo "Failed to get session id, bailing!" >&2
    exit 1
fi
```

**Comment by inthreedee** [comment]
> I am running this command with my user/password with the domain and getting error as : **Creating PhotoPrism session... Failed to get session id, bailing!**
> 
> Can someone help what am i missing.

@devGIT07 Based on your error message, I'm guessing you're referring to the script I wrote and linked in the discussion above? If you're having issues with that script, opening an issue on that repo would be the better place for that conversation. But providing the correct username, password, and domain should still be working fine unless the Photoprism API has changed.

In case the API has changed, I'll provide the relevant code snippits here for the Photoprism devs to double check:
https://github.com/inthreedee/photoprism-transfer-album/blob/main/transfer-album.sh#L34
```
sessionAPI="/api/v1/session"
```
https://github.com/inthreedee/photoprism-transfer-album/blob/main/transfer-album.sh#L526-L541
```
# Call the session API
session="$(curl --silent -X POST -H "Content-Type: application/json" -d "{\"username\": \"$apiUsername\", \"password\": \"$apiPassword\"}" "$siteURL$sessionAPI")"

# Check the login credentials
if echo "$session" | grep "Invalid credentials" >/dev/null; then
    echo "Invalid login credentials, bailing!" >&2
    exit 1
fi

# Get the session ID
sessionID="$(echo "$session" | grep -Eo '"id":.*"' | awk -F '"' '{print $4}')"

if [ -z "$sessionID" ]; then
    echo "Failed to get session id, bailing!" >&2
    exit 1
fi
```

**Comment by devGIT07** [comment]
Thanks. Yes, the issue with the current script. I have opened a bug/issue as suggested: https://github.com/inthreedee/photoprism-transfer-album/issues/11

**Comment by devGIT07** [comment]
> I am running this command with my user/password with the domain and getting error as : **Creating PhotoPrism session... Failed to get session id, bailing!**
> 
> Can someone help what am i missing.

Thanks for this team to help out figuring out the solution. Solution is to replace the entire siteUrl with `localhost:<port>`. Make sure not to include the `http` or `https` in this url. Also, this means you would be running this command on the host machine where your photoPrism instance is running so that localhost is properly detected.
