### ISSUE TITLE
Use Cobra & Viper

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#87]
**As a developer, I want to use the best CLI and Config components in order to be more productive.**

See https://www.reddit.com/r/golang/comments/5sdvoh/what_is_the_essential_difference_between/

Acceptance Criteria:
- [ ] Use spf13/cobra instead of urfave/cli
- [ ] Use spf13/viper instead of the current custom solution

**Comment by lastzero** [comment]
Note: My assumption was that Micro comes with a well maintained version of urfave/cli plus config package. But https://github.com/micro/cli is a very old version of urfave/cli. Using Cobra and Viper seems to be the best option for us.

**Comment by metalmatze** [comment]
What is the reason for switching from urfave/cli? We are using it with [gopass](https://github.com/gopasspw/gopass/). Another popular option I see these days is [kingpin](https://github.com/alecthomas/kingpin) which is used by Prometheus for example.

Though I still like urfave/cli the most, as it allows for non global declaration of the CLI. Both kingpin and cobra want some sort of globals to work correctly, as far as I've seen and tried.

**Comment by lastzero** [comment]
I want to use Viper for our config instead of the custom solution we have right now. From what I see, it should (ideally) be used with Cobra. Also it seems (on first sight) Cobra is better maintained and supports sub sub commands whereas urfave/cli does not.

**Comment by lastzero** [comment]
Here is how Hugo uses Cobra: https://github.com/gohugoio/hugo/blob/master/main.go

**Comment by gedw99** [comment]
Can i suggest you use Viper but have a look at krakend uses it. Its use cobra and viper in a very elegant way.

doc:
https://github.com/devopsfaith/krakend/blob/master/docs/CONFIG.md

Example of how easy it is to add another config:
https://github.com/devopsfaith/krakend-pubsub

code of actual librar wrapping cobra / viper
https://github.com/devopsfaith/krakend-cobra

How that code lib is used in the bigger system:
https://github.com/search?q=org%3Adevopsfaith+krakend-cobra&type=Code

**Comment by lastzero** [comment]
@gedw99 Thanks for the hints! For now, I think my personal time is better invested in improving the frontend. Viper is somewhat better, but probably doesn't make any difference for us at the moment...

**Comment by gedw99** [comment]
Sounds good. No worries.
