### ISSUE TITLE
Error "index: failed converting ... Not implemented for this architecture..."

### ISSUE THREAD

**Issue by Noschvie** [photoprism/photoprism#870]
The container stops running with the message below

```
time="2021-01-09T19:34:33Z" level=error msg="index: failed converting IMG_20190731_120101.ARW to jpeg ([dt_detect_cpu_features]
Not implemented for this architecture.\n[dt_detect_cpu_features]
Please contribute a patch.\n[dt_init] SSE2 instruction set is unavailable.\n[dt_init] expect a LOT of functionality to be broken. you have been warned.\n[dt_detect_cpu_features]
Not implemented for this architecture.\n[dt_detect_cpu_features] Please contribute a patch.\n[dt_codepaths_init] will be using HIGHLY EXPERIMENTAL plain OpenMP SIMD codepath.\n[dt_codepaths_init] SSE2-optimized codepath is disabled or unavailable.\n[dt_codepaths_init] expect a LOT of functionality to be broken. you have been warned.\n)"
```
Any idea ?
Thanks!

**Comment by lastzero** [comment]
Looks like *Darktable* that is being used by the indexer in the background. Obviously using a modern CPU with SSE2 would help, or contributing a patch. Nothing I can provide tonight.

As a workaround, we may implement a fallback e.g. to *RawTherapee*.

**Comment by Noschvie** [comment]
> As a workaround, we may implement a fallback e.g. to _RawTherapee_.

that would be great! Using RPi4 running "Ubuntu 20.04.1 LTS"
Thanks!

**Comment by Noschvie** [comment]
Updated to the latest version and re-indexing terminated with:
```
time="2021-01-14T09:52:35+01:00" level=debug msg="index: updated yaml file IMG_20190731_140940.yml"
time="2021-01-14T09:52:35+01:00" level=debug msg="media: no new thumbnails created for IMG_20190731_140940 [595.71µs]"
time="2021-01-14T09:52:35+01:00" level=info msg="index: added related jpg file IMG_20190731_140940.ARW.jpg"
time="2021-01-14T09:52:35+01:00" level=debug msg="convert: Family/2019/2019_Q3/2019-07-31 Rügen/IMG_20190731_141015.ARW -> IMG_20190731_141015.ARW.jpg"
time="2021-01-14T09:52:35+01:00" level=debug msg="convert: Family/2019/2019_Q3/2019-07-31 Rügen/IMG_20190731_141132.ARW -> IMG_20190731_141132.ARW.jpg"
/entrypoint.sh: line 21:     7 Killed                  "$@"
```
Is there a detailed log of this crash?

**Comment by Dbwilliams44** [comment]
I don’t know 


Sent from Yahoo Mail for iPhone


On Saturday, January 9, 2021, 2:46 PM, Norbert <notifications@github.com> wrote:




The container stops running with the message below
time="2021-01-09T19:34:33Z" level=error msg="index: failed converting IMG_20190731_120101.ARW to jpeg ([dt_detect_cpu_features]
Not implemented for this architecture.\n[dt_detect_cpu_features]
Please contribute a patch.\n[dt_init] SSE2 instruction set is unavailable.\n[dt_init] expect a LOT of functionality to be broken. you have been warned.\n[dt_detect_cpu_features]
Not implemented for this architecture.\n[dt_detect_cpu_features] Please contribute a patch.\n[dt_codepaths_init] will be using HIGHLY EXPERIMENTAL plain OpenMP SIMD codepath.\n[dt_codepaths_init] SSE2-optimized codepath is disabled or unavailable.\n[dt_codepaths_init] expect a LOT of functionality to be broken. you have been warned.\n)"

Any idea ?
Thanks!

**Comment by lastzero** [comment]
> Is there a detailed log of this crash?

Do you have 4 GB of RAM and at least 1 GB of Swap configured?

**Comment by Noschvie** [comment]
```
ubuntu@hadersdorf:~$ sudo free -h
              total        used        free      shared  buff/cache   available
Mem:          3.7Gi       1.6Gi       1.0Gi       4.0Mi       1.1Gi       2.1Gi
Swap:         4.0Gi       0.0Ki       4.0Gi
```
Swap file added and reindexing restarted.
Thanks!

**Comment by lastzero** [comment]
Also enable `PHOTOPRISM_DARKTABLE_PRESETS` so that only one RAW gets converted at a time. Rendering RAWs typically needs lots of memory and other system resources.

**Comment by Noschvie** [comment]
`PHOTOPRISM_DARKTABLE_PRESETS: "true"`
changed and container restarted.

**Comment by Noschvie** [comment]
retested and ok, thanks!
