### ISSUE TITLE
Importing: File Date OK, Metadata Date Unknown

### ISSUE THREAD

**Issue by tootbrute** [photoprism/photoprism#877]
Anybody have this issue for some pictures?

The file name is the correct date, but the metadata for date is 'Unknown'.

See pictures below.
![Screenshot_20210111_205153](https://user-images.githubusercontent.com/47593393/104184982-48797100-544f-11eb-8e53-e33b929bc692.png)
![Screenshot_20210111_205210](https://user-images.githubusercontent.com/47593393/104184995-4b746180-544f-11eb-8b16-b17c76f3f511.png)

Previously, I had just manually changed the dates: Look at Files tab, click to Details tab, change date, Done! but that was very time consuming and all my hard work was lost when I re-indexed my whole collection.

**Comment by lastzero** [comment]
Works as designed as the date from file names is often unreliable... so it is only used for sorting / importing, but displayed is unknown otherwise.

**Comment by tootbrute** [comment]
> Works as designed as the date from file names is often unreliable... so it is only used for sorting / importing, but displayed is unknown otherwise.

Got it. Yes I see some are correct filename dates, but you are correct, it is unreliable; a lot of filenames have defaulted to the date I originally imported the photos.

I think I will wait until file delete is implemented then I will try
1. Download collection of photos from one event
2. Delete photos from Photoprism
2. Use Exiftool to batch tag them all the same date
3. Reimport photos to Photoprism

**Comment by tootbrute** [comment]
> Works as designed as the date from file names is often unreliable... so it is only used for sorting / importing, but displayed is unknown otherwise.

Got it. Yes I see some are correct filename dates, but you are correct, it is unreliable; a lot of filenames have defaulted to the date I originally imported the photos.

I think I will wait until file delete is implemented then I will try
1. Download collection of photos from one event
2. Delete photos from Photoprism
2. Use Exiftool to batch tag them all the same date
3. Reimport photos to Photoprism
