### ISSUE TITLE
Allow repeated filters

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#881]
Let's say that I want to see all the photos of buffalo **and** water (not the photos with bufallo or water only), so I search for `label:buffalo label:water`: https://demo.photoprism.org/all?view=cards&order=added&q=label%3Abuffalo%20label%3Awater&public=true

Expected output: this photo from the demo:

> ![image](https://user-images.githubusercontent.com/2071331/104237472-67303580-5458-11eb-9383-e6e782d3eb67.png)

(see the `buffalo` and `water` keywords)

Actual output: the `label:buffalo` part is ignored, I only see photos related to water:

> ![image](https://user-images.githubusercontent.com/2071331/104237580-8af37b80-5458-11eb-8a9c-191b86736abe.png)

https://demo.photoprism.org/all?view=cards&order=added&q=label%3Abuffalo%20label%3Awater&public=true

So it looks like PhotoPrism accept only the last instance of a filters when several are provided.

Could PhotoPrism accept several instances of the same filter?

**Comment by lastzero** [comment]
We may automatically merge `label:buffalo label:water` to `label:water|buffalo` and implement AND with `label:water&buffalo` (not sure about using `&` yet as this may be part of names, just like `,` which we used instead of `|` before for OR).

**Comment by alexislefebvre** [comment]
It looks like it works for the water buffalo :tada: https://demo.photoprism.org/all?view=cards&order=added&q=keywords%3A%22buffalo%20%26%20water%22&public=true
