### ISSUE TITLE
Search: Add distinct “keywords:…” filter

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#882]
Keywords and labels are different things: https://docs.photoprism.org/user-guide/faq/#whats-the-difference-between-keywords-and-labels

There is a `label` filter for searching, for example: https://docs.photoprism.org/user-guide/organize/search/#or-search

But there is no filter for keywords, could we please have one?

Combined with #881, it would allow users to search for photos which use 2 (or more) keywords, see #747.

**Comment by banshee1971** [comment]
+1 for that !

I install Photoprism because after update my Synology to DSM 7, i completly lost the ability to find 75% of my stuff. Most were identify, tag,... using Digikam and Synology.

In Photoprism, those item as been found as "keyword".. but i can't search them.

So, be able to search in the keyword will be great !

But aslo, do some inteligent search including multiple "keyword, tag, location,.." and save them as an Album will be much better !

**Comment by lastzero** [comment]
Combining search filters is already possible, just not as user friendly as it should be eg when it comes to location names. Keywords should also be found, you can't combine them with AND however.

**Comment by banshee1971** [comment]
Already try... but cant' find anything... as the result look like a OR

So... in the "Keyword" found by Photoprism, it's look like this : audrey, cake, montreal, street, st-joseph, frederik

So when i try to search all picture with "audrey" and "frederik", got anything exept both user. I try this way in the seach box : audrey frederik : got all picture who have only one of them or all of them.

Then i try "audrey" "frederik", same result....

so.. unless i try it the wrong way.. how can i did a search in all field, with "AND" ?

I also try the search : audrey longueuil ... and got all picture with longueil (but no Audrey anywhere in the data

**Comment by lastzero** [comment]
That's what I said: "you can't combine them with AND however", thus they will be combined with OR

**Comment by banshee1971** [comment]
stil +1 for that feature.

Will be nice to have it ! As i import 15 000 file, and all methadata were found as "keyword".. be able to search them with AND will be nice...

**Comment by alexislefebvre** [comment]
This issue has been labeled as [please-test](https://github.com/photoprism/photoprism/labels/please-test), how can we test it? Can we test it on the demo environment? What search parameters have to be used? Thanks in advance

**Comment by lastzero** [comment]
Yes, on our demo. Note there are additional improvements coming later today, that's also why I didn't have time to document details yet. Basically there are `keywords`, `albums` and `subjects` search filters now. They work similar to existing filters.

**Comment by banshee1971** [comment]
Can install the demo and test it?

That's sound very interesting!

**Comment by alexislefebvre** [comment]
@banshee1971 you don't need to install the demo, it's already available, see my comment here: https://github.com/photoprism/photoprism/issues/881#issuecomment-908389394
