### ISSUE TITLE
share album on nextcloud 

### ISSUE THREAD

**Issue by stef97** [photoprism/photoprism#892]
Is there a way to share an album on Nextcloud ?
Both photoprism and Nextcloud are running on the same seerver but I am only allowing external access to nextcloud 

I would like to have the ability to share albums with my friends and , I believe, using Nextcloud is the only way if I do not want to expose photoprism 

Any help/suggestions would be very appreciated

**Comment by lastzero** [comment]
You may upload files to shared Nextcloud folders using the share dialog (cloud in the context menu), but there is no auto sync in this case.

**Comment by graciousgrey** [comment]
See: https://docs.photoprism.org/user-guide/settings/sync/#manually-upload-files-to-nextcloud
