### ISSUE TITLE
iOS: Unable to get back after tapping download in PWA

### ISSUE THREAD

**Issue by tanuva** [photoprism/photoprism#895]
Hi!

I have Photoprism on the home screen as intended for PWAs so that it launches without a browser UI. When I tap the download button for an image in this setup, I get to an "open with"-style iOS system screen. I can select an app and save the photo, but from what I see it is impossible to return to PhotoPrism from that screen. The only way is to kill the app and relaunch.

![IMG_2020](https://user-images.githubusercontent.com/772963/104591771-73411080-566d-11eb-9e1c-c7ea078c2615.PNG)

**Comment by graciousgrey** [comment]
Thanks for reporting!

**Comment by lastzero** [comment]
Just ordered an iPad so that I can test this properly:

![ipad](https://user-images.githubusercontent.com/301686/104768328-c00c1080-576d-11eb-80af-4216bc545dc3.jpeg)

If you're not a sponsor yet, consider supporting us financially. Thank you! :heart:

**Comment by tanuva** [comment]
I am indeed planning to do just that. Since Photoprism is probably soon able to take over my photo viewing needs from Plex, I recently canceled my Plex Premium subscription. (The only thing I really miss atm is a hierarchical folders view though I guess you already have that on the list. Maybe I should rekindle my Go knowledge...)

**Comment by lastzero** [comment]
Even after refactoring file downloads, it still doesn't work in the PWA - only when opening PhotoPrism in Safari.

Sadly, iOS doesn't support the JS file download API yet:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download

Other developers seem to have the same issue. Going to try a few more things.

**Comment by lastzero** [comment]
`window.open()` also doesn't work, using https://github.com/eligrey/FileSaver.js/ doesn't work as well.

Seems Apple needs to fix this:

- https://github.com/eligrey/FileSaver.js/#ios
- https://bugs.webkit.org/show_bug.cgi?id=167341
- https://bugs.webkit.org/show_bug.cgi?id=216918

**Comment by graciousgrey** [comment]
If someone could do some research on how others are solving this issue it would help us a lot!

**Comment by adambeck7** [comment]
FileSaver.js actually did solve the issue for me at least. It provides a done button at the top left that isn't available with other methods. I added `this.$router.go(-1)` to go back a screen since that felt like a more natural behavior after downloading. 

https://user-images.githubusercontent.com/18033909/108643107-45b66680-7466-11eb-80d1-8656cf8b68e9.MP4

**Comment by lastzero** [comment]
@adambeck7 Would you mind sharing your code for FileSaver.js? Didn't work for me recently, but there might be more than one way to use it...

**Comment by shasycouk** [comment]
> FileSaver.js actually did solve the issue for me at least. It provides a done button at the top left that isn't available with other methods. I added `this.$router.go(-1)` to go back a screen since that felt like a more natural behavior after downloading. RPReplay_Final1613951858.MP4

Are your changes included in your fork? https://github.com/adambeck7/photoprism

**Comment by lastzero** [comment]
Looking forward to finally find a solution that works 🥳

**Comment by shasycouk** [comment]
> Looking forward to finally find a solution that works 🥳

It's been years since I've done any programming but I'll be happy to help. Could someone tell me where in the files I can find the currently used code?

**Comment by lastzero** [comment]
We're able to take a look at this again very soon, any more information on your solution @adambeck7?

**Comment by shasycouk** [comment]
> We're able to take a look at this again very soon, any more information on your solution @adambeck7?

He seems inactive. I saw that Adam is a sponsor. Is there a possibility for you to send sponsors messages? 

Thanks so much for taking a look.

**Comment by lastzero** [comment]
No, unless they've published the email on their GitHub account...

**Comment by shasycouk** [comment]
> No, unless they've published the email on their GitHub account...

I sent him a message on the UNRAID forums. (GitHub should give that option!)

**Comment by adambeck7** [comment]
Hey, sorry about that. Nice work tracking me down on the Unraid forum. I always miss the github notifications. 

Anyway. I just implemented FileSaver as shown in their docs but after the fact I realized that it wasn't downloading the actual file, it's trying to download a text file so I'm probably messing up how I'm making the Blob or something. That's all new to me. On Android and web it downloads the proper file + that extra text file but iOS only wants to grab the txt file. Anyway, here is how I implemented file-saver in the onDownload method:

` new Photo().find(this.item.uid).then(p => {
        const downloadImg = new Blob([p.downloadAll()]);
        saveAs(downloadImg, p.name)
        this.$router.go(-1)
      });`
      
      
 You just need to `npm i file-saver` then add the import in the viewer.vue file: `import { saveAs } from 'file-saver';`

**Comment by lastzero** [comment]
Looks like this code is loading the file in memory via JS first and then saving it using the File API. While that may work, it's not a feasible option for large files, especially long 4K videos. This should blow up browser memory.

**Comment by lastzero** [comment]
I have started a preview build so you can test these changes:
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
@tanuva Can you confirm this is working? We're going to release this soon if we don't hear otherwise...

**Comment by tanuva** [comment]
Indeed I can confirm. The browser controls show up when tapping the download button so going back is possible now. Quality of life improved considerably, thanks!

**Comment by lastzero** [comment]
Excellent, thanks for testing!

**Comment by lastzero** [comment]
Released.

**Comment by shasycouk** [comment]
> Released.

Works wonderfully. Danke! Happy to be a Patreon. This was literally the last thing that still bugged me. Thanks so much :)
