### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by andrewlow** [photoprism/photoprism#898]
I'm doing a large (initial) import of many many photos.. 40k+

Initially I allowed the auto-import to trigger - and it did on it's own. I was doing a `scp` from one machine into the 'import' directory that the container is mapped for photoprism imports.

There was enough data copied when the auto import triggered, but it seems that it managed to run to completion over the first batch of files it detected while additional files were still being copied over.

![image](https://user-images.githubusercontent.com/2952475/104639514-81932a80-5675-11eb-8c7d-ebce26bd9e0d.png)

This explains the dip to near zero in the CPU graph above right at the start. From there, the next auto import cycle started and it's been running hard since (days).

Since I also want all of the files that are in the import directory to get 'moved' into my collection (really deleted from the import directory) -- I later went in and clicked on the Web UI to indicate that I wanted to do an import and 'Move' the files. This seemed to go ok, but the system was still importing away.

It's been running fine - pictures are showing up etc.. but just in the last little while I'm getting this repeating error in my library logs

```
2021-01-14 14:27:36 INFO import: moving main jpg file iPhoto/Originals/2011/woolsey11/IMG_1900.JPG to 2011/03/20110327_094408_2FF7D23B.jpg
2021-01-14 14:27:36 INFO media: IMG_1900.JPG was taken at 2011-03-27 09:44:08 +0000 UTC (meta)
2021-01-14 14:27:36 ERRO import: “open /photoprism/storage/cache/json/7/0/e/70e1030d86ad7d7503b8b9899d845a724273f98c_exiftool.json: no space left on device” in IMG_1900.JPG (extract metadata)
2021-01-14 14:27:36 ERRO import: media: 20110327_094335_BDE3C3CA.jpg not found in 2011/03/20110327_094335_BDE3C3CA.jpg
2021-01-14 14:27:36 ERRO import: failed copying file to 2011/03/20110327_094335_BDE3C3CA.jpg (open /photoprism/originals/2011/03/20110327_094335_BDE3C3CA.jpg: no space left on device)
2021-01-14 14:27:36 ERRO open /photoprism/originals/2011/03/20110327_094335_BDE3C3CA.jpg: no space left on device
2021-01-14 14:27:36 INFO import: moving main jpg file iPhoto/Originals/2011/woolsey11/IMG_1899.JPG to 2011/03/20110327_094335_BDE3C3CA.jpg
2021-01-14 14:27:36 INFO media: IMG_1899.JPG was taken at 2011-03-27 09:43:35 +0000 UTC (meta)
2021-01-14 14:27:36 ERRO import: “open /photoprism/storage/cache/json/4/1/0/410062c809e401ff8facb1792d3b84007a3d5ec7_exiftool.json: no space left on device” in IMG_1899.JPG (extract metadata)
2021-01-14 14:27:36 ERRO import: media: 20110327_094332_526D5A0F.jpg not found in 2011/03/20110327_094332_526D5A0F.jpg
2021-01-14 14:27:36 ERRO import: failed copying file to 2011/03/20110327_094332_526D5A0F.jpg (open /photoprism/originals/2011/03/20110327_094332_526D5A0F.jpg: no space left on device)
2021-01-14 14:27:36 ERRO open /photoprism/originals/2011/03/20110327_094332_526D5A0F.jpg: no space left on device
```

Now I have PLENTY of drive space on all volumes - nothing is over 47%.

When I go in and look at one of the file paths that is reporting "no space left on device" - it seems this is really file not found (no such file or directory).

```
$ ls /photoprism/storage/cache/json/4/1/0/410062c809e401ff8facb1792d3b84007a3d5ec7_exiftool.json
ls: cannot access '/photoprism/storage/cache/json/4/1/0/410062c809e401ff8facb1792d3b84007a3d5ec7_exiftool.json': No such file or directory
```

I suspect this is a minor thing - but wanted report it if there is additional information I could gather to help the project. Even if we just improved the error reporting it might be better.

**Comment by alexislefebvre** [comment]
It's unrelated to your issue but note that you can index existing files instead of importing them: https://docs.photoprism.org/user-guide/library/import-vs-index/

**Comment by andrewlow** [comment]
I'm aware I can index existing files - but chose to import because I wanted to re-order things.

**Comment by gomme600** [comment]
Just a question, how do you use auto-import? I thought that that only worked via WebDAV?

**Comment by lastzero** [comment]
True, auto import is only implemented for webdav. Maybe the storage path is somehow wrong configured?

**Comment by lastzero** [comment]
We had several cases of "no space left on device" and every single time, it turned out there really was no space left - for example because a wrong drive / folder was used for storage, or it was stored inside the Docker container and the path was not mounted properly.

**Comment by andrewlow** [comment]
> Just a question, how do you use auto-import? I thought that that only worked via WebDAV?

On my OSX machine I do indeed have a WebDAV link to the import folder (import folder is hosted on a local linux box).

I populated the import folder by using `scp` on linux from one location to the location of the import folder.

I'm running protoprism in a container and have mapped the import directory to the host filesystem

```
                -v /media/archive/photoprism/storage:/photoprism/storage \
                -v /media/archive/photoprism/originals:/photoprism/originals \
                -v /media/archive/photoprism/import:/photoprism/import \
```

I'm pretty sure that I really have space.. but I'm still having the problem :( 

Host filesystem where the container lives
```
$ df -h 
Filesystem                      Size  Used Avail Use% Mounted on
udev                            7.8G     0  7.8G   0% /dev
tmpfs                           1.6G  2.4M  1.6G   1% /run
/dev/sdb2                       110G   51G   54G  49% /
tmpfs                           7.8G     0  7.8G   0% /dev/shm
tmpfs                           5.0M     0  5.0M   0% /run/lock
tmpfs                           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop0                       98M   98M     0 100% /snap/core/10577
/dev/loop1                       98M   98M     0 100% /snap/core/10583
/dev/sdc1                       2.8T  611G  2.2T  22% /media/archive
/dev/sda1                       1.8T  713G  1.1T  41% /media/external
/dev/sde1                       3.7T  984G  2.7T  27% /media/media
/dev/sdd1                       5.5T  985G  4.5T  18% /media/parity
tmpfs                           1.6G     0  1.6G   0% /run/user/1000
```

Filesystem view from inside the photoprism container
```
photoprism@bce9cb3ff068:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         110G   51G   54G  49% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sdc1       2.8T  611G  2.2T  22% /photoprism/import
/dev/sdb2       110G   51G   54G  49% /etc/hosts
tmpfs           7.8G     0  7.8G   0% /proc/asound
tmpfs           7.8G     0  7.8G   0% /proc/acpi
tmpfs           7.8G     0  7.8G   0% /proc/scsi
tmpfs           7.8G     0  7.8G   0% /sys/firmware

```

**Comment by andrewlow** [comment]
Ok - so I decided to restart the container to figure out what was wrong.. and yup, something is wrong under the container (so this is probably NOT a photoprism issue directly)

```
time="2021-01-15T14:01:58Z" level=info msg="shutting down..."
time="2021-01-15T14:01:58Z" level=info msg="shutting down workers"
time="2021-01-15T14:01:58Z" level=info msg="closed database connection"
time="2021-01-15T14:01:58Z" level=info msg="shutting down web server"
time="2021-01-15T14:01:58Z" level=info msg="web server shutdown complete"
time="2021-01-15T14:02:03Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:06Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:08Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:11Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:14Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:18Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:23Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:31Z" level=fatal msg="storage not writable"
time="2021-01-15T14:02:46Z" level=fatal msg="storage not writable"
time="2021-01-15T14:03:14Z" level=fatal msg="storage not writable"
time="2021-01-15T14:04:07Z" level=fatal msg="storage not writable"
time="2021-01-15T14:05:09Z" level=fatal msg="storage not writable"
```

How things got into this state is curious, but at least this explains what the heck was going on.

**Comment by andrewlow** [comment]
Ah.. my filesystem is sick.. 

```
machine:/media/archive/photoprism$ touch x
touch: cannot touch 'x': No space left on device
machine:/media/archive/photoprism$ df .
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/sdc1      2928828364 640345908 2288466072  22% /media/archive
```

**Comment by andrewlow** [comment]
🤦 

I ran out of inodes.. 
```
$ df -i .
Filesystem     Inodes  IUsed IFree IUse% Mounted on
/dev/sdc1      715424 715424     0  100% /media/archive
```

**Comment by lastzero** [comment]
What file system is this? Should be millions of inodes, not just 715k.

**Comment by lastzero** [comment]
```
Filesystem                           Inodes   IUsed     IFree IUse% Mounted on
/dev/sdb1                         781403328 1669176 779734152    1% /mnt/backup
/dev/md0                          586026752  716869 585309883    1% /mnt/share
```

**Comment by andrewlow** [comment]
Unfortunately - I'm in a bad spot - I have a lot of data...(but at least this volume is ONLY got photos on it)

```
$ df -h /media/archive/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc1       2.8T  611G  2.2T  22% /media/archive
```
But not enough inodes
```
$ df -i /media/archive
Filesystem     Inodes  IUsed IFree IUse% Mounted on
/dev/sdc1      715424 715424     0  100% /media/archive
```

This is probably my past self doing something dumb - I probably created this filesystem `ext4` but specified a lower than normal inodes because I was (dumbly) thinking that I was going to have large static content on it. I was probably influenced by the snapraid documentation - but I totally could have also finger fumbled and messed this up.  I suspect I used the largefile flag https://unix.stackexchange.com/questions/43102/largefile-feature-at-creating-file-system

The other volumes on my system .. are using 1% of the inodes - the worst volume is 20% (a bit concerning this is / .. but I don't expect a lot of growth)

It wouldn't be bad to have a FAQ on checking your volume(s) for sufficient inodes - if you're using linux, and have done something dumb like me.

**Comment by lastzero** [comment]
> It wouldn't be bad to have a FAQ on checking your volume(s) for sufficient inodes - if you're using linux, and have done something dumb like me.

Inodes were first thought, but then discarded it as being too easy 😅

Many users probably wouldn't understand what this is in the first place...

**Comment by andrewlow** [comment]
TBH - I should have spotted this problem myself before logging an issue. The fact that an issue exists is probably a good enough record for others who hit the same problem. No need for FAQ.

After an epic copy/format/copy data shuffle - I'm now in a much happier spot.

```
$ df -i
Filesystem                        Inodes    IUsed     IFree IUse% Mounted on
/dev/sdc1                      183148544   688085 182460459    1% /media/archive
```

**Comment by lastzero** [comment]
Good news! Happy indexing :whale:
