### ISSUE TITLE
I forgot the command to import. help me .

### ISSUE THREAD

**Issue by RUANHAOANDROID** [photoprism/photoprism#90]

**Comment by lastzero** [comment]
`photoprism help` shows all available commands and config parameters

**Comment by Arafatk** [comment]
When using as a user you can use this instruction to import the folder required while starting the docker container itself.     
![image](https://user-images.githubusercontent.com/11155207/51866200-56bb4900-236e-11e9-861a-9aaa3bb265da.png)

If you are using the developer mode instructions then the default folder ~/Pictures will be import.      

Until now the folders have to specified this way only and the addition of a separate import tool is yet to be done.  I hope that answers your questions @RUANHAOANDROID       

@lastzero  Maybe you can describe any development goal for this issue or just close the issue.

**Comment by lastzero** [comment]
@Arafatk I was waiting for feedback. Closed now.
