### ISSUE TITLE
Uploading a RAW file crashes the app

### ISSUE THREAD

**Issue by 1e100** [photoprism/photoprism#900]
I accidentally uploaded a Sony *.ARW file to the latest PhotoPrism (installed using Docker Compose, as advised), and PhotoPrism seems to reliably crash when I do it with the following log spew:
```
time="2021-01-14T22:02:39Z" level=info msg="1 files uploaded in 1 s"
time="2021-01-14T22:02:39Z" level=info msg="Moving files from 1610661758123"
time="2021-01-14T22:02:39Z" level=info msg="import: no .ppignore file found"
time="2021-01-14T22:02:39Z" level=info msg="import: added folder /upload/1610661758123"
time="2021-01-14T22:02:39Z" level=info msg="metadata: failed parsing gps coordinates in 20190622T133127-00665.ARW (exif)"
time="2021-01-14T22:02:39Z" level=info msg="media: 20190622T133127-00665.ARW was taken at 2019-06-22 13:31:27 +0000 UTC (meta)"
time="2021-01-14T22:02:39Z" level=info msg="import: moving main raw file 20190622T133127-00665.ARW to 2019/06/20190622_133127_B139E807.arw"
/entrypoint.sh: line 21:     6 Killed                  "$@"
```
Expected: if RAW is not supported, it should reject the file without crashing.

**Comment by lastzero** [comment]
Do you have 4 GB of RAM and swap configured?

**Comment by 1e100** [comment]
Looks like that's what it was. I was able to successfully upload a RAW file after increasing RAM in the VM to 4GiB.

**Comment by alexislefebvre** [comment]
@lastzero 

> Do you have 4 GB of RAM and swap configured?

I saw this issue appeared several times recently. Could PhotoPrism display a warning or stop indexing/indexing if there is not enough RAM and swap?

**Comment by lastzero** [comment]
It's already notes several times in our docs and Readme, I'll add to docker-compose.yml as well in big letters.
