### ISSUE TITLE
Photos cannot be deleted

### ISSUE THREAD

**Issue by 929126387** [photoprism/photoprism#901]
There is a problem. There is no delete option for the photo in the search. You can only move it to the album to delete it. However, you can click delete. There is still this photo in the disk and you have to delete it manually. Is this bug or normal? I want to delete this photo permanently

**Comment by alexislefebvre** [comment]
See #885

**Comment by 929126387** [comment]
> 请参见[＃885](https://github.com/photoprism/photoprism/discussions/885)

It can only be deleted through archive software for the time being. Will developers support permanent deletion in the future? I'm very optimistic about this album management program. How long will I wait?

**Comment by lastzero** [comment]
It's 4% complete, simply become a sponsor to shorten the wait: https://github.com/sponsors/photoprism

**Comment by 929126387** [comment]
> 它完成了4％，只需成为赞助商即可缩短等待时间：[https](https://github.com/sponsors/photoprism)：[//github.com/sponsors/photoprism](https://github.com/sponsors/photoprism)

Can the album cover be set? If so, where? Thank you

**Comment by lastzero** [comment]
This is another feature request waiting for funding. Covers are automatically set right now.

**Comment by alexislefebvre** [comment]
@929126387 This project is developed with the help of sponsors and is also open source, anyone can improve the project and add new features. Feel free to contribute by adding the features you want. :slightly_smiling_face:
