### ISSUE TITLE
Add Czech translations

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#902]
The scope of this issue is to add translations for a new language:

**Acceptance Criteria:**

**Add frontend translations**
 
- In /frontend run `npm run gettext-extract`
- Install a translation tool e.g. Poedit
- Open the /frontend/src/locales/translations.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, save your translation as *.po file using the two-letter language locale as name
-  Add the new language in  /frontend/src/options/options.js
- Run `npm run gettext-compile`
- To test your translations you need to build the frontend again using `npm run build` or `npm run watch`

**Add backend translations**
- Run `make generate`
- Open the /assets/locales/messages.pot file with Poedit
- In Poedit click on "Create New Translation" at the bottom --> select the language, and start translating
- When done, create a new directory (using the locale as name) and save your translation there as default.po

If you need help setting up the development environment read our setup guide --> https://docs.photoprism.org/developer-guide/setup/.
We also provide some more information on translations in our docs --> 
https://docs.photoprism.org/developer-guide/translations/

**Comment by Shamshala** [comment]
Thanks! Assign please.

**Comment by Shamshala** [comment]
Ok, now i noticed "fuzzy" flag causes that the translation won't apply those lines at all, dang it. :smile:

And one thing i want to make sure, what "Checked" in the photo editor means? I thought it has something to do with Review but after an inspection in the GUI it doesn't look like so.

**Comment by lastzero** [comment]
Automatically checked / metadata optimized if needed
