### ISSUE TITLE
Add support for `CACHEDIR.TAG`

### ISSUE THREAD

**Issue by thomaseizinger** [photoprism/photoprism#906]
I am backing up my photoprism data using restic.

Restic has support for the [cache directory tagging specification](https://bford.info/cachedir/) using `--exclude-caches` to automatically exclude caches from being backed-up.

Would it be possible for photoprism to put such a `CACHEDIR.TAG` file into all its cache/transient directories? That would nicely simplify my backup configuration setup!

**Comment by alexislefebvre** [comment]
Can you configure Restic to ignore that folder?

**Comment by thomaseizinger** [comment]
> Can you configure Restic to ignore that folder?

I can and it is what I did for now but it would be more convenient if all I need to do is pass `--exclude-caches` and everything that is not backup-worthy is excluded automatically :)

> Or put the cache and storage outside your backed up directory?

I prefer sticking to defaults with most software as close as possible.

**Comment by alexislefebvre** [comment]
In my humble opinion, PhotoPrism shouldn't add a specific feature for one backup tool. You can create the `CACHEDIR.TAG` manually where you want and it will stay forever.

**Comment by thomaseizinger** [comment]
> PhotoPrism shouldn't add a specific feature for one backup tool.

Which is why I proposed to add support for the `CACHEDIR.tag` **specification**.

However, I also realized that I should have probably phrased this issue more in terms of a problem instead of a solution which is why I am gonna open a new one.

**Comment by thomaseizinger** [comment]
Posted here https://github.com/photoprism/photoprism/issues/919.
