### ISSUE TITLE
Backup: Restore archive flag from YAML files

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#912]
Follow up issue for #567

**Comment by alexislefebvre** [comment]
Is some other data missing from YAML backups?

**Comment by lastzero** [comment]
While the archive flag should be in the YAML file, it might be reset while indexing - otherwise, the file would be skipped as archived files will be skipped. So it's an edge case I need to investigate again. Not 100% clear if the file should be put in archive, or skipped right away. Trying to avoid too much complexity here.

**Comment by lastzero** [comment]
@alexislefebvre Had to change quite a few details to make this work. We're now keeping archived files updated in the index as well. Shouldn't be too bad as you can now delete photos you don't want. That wasn't possible previously.

In addition, photo quality and time zone have been added to the YAML backups.
