### ISSUE TITLE
Metadata / Estimate timezone

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#914]
As a user I want PhotoPrism to estimate the timezone of my images so that the sorting with other photos with a similar time is correct

**Comment by benmccann** [comment]
Wouldn't the be in the same order either way?

**Comment by graciousgrey** [comment]
@benmccann The problem here was that images from one device had a time + timezone: e.g. 19:00 CET (which is 18:00 UTC). Another image had only a time but no information about the timezone e.g. 18:45 in this case 18:45 was set as local time and UTC time. 
As we sort by UTC the 19:00 image was sorted before the 18:45 image. 
Instead of adding more config options we decided to estimate the timezone.
