### ISSUE TITLE
Complete Rescan crashes frontend when settings disabled

### ISSUE THREAD

**Issue by oscar-b** [photoprism/photoprism#916]
When trying to enable "Complete Rescan" in the UI, it does a POST to `/api/v1/settings` which returns 401 and the frontend reloads.

1. Enable `PHOTOPRISM_DISABLE_SETTINGS` (I suspect this is the cause)
2. Go to /library and enable "Complete Rescan"

Error:
```
Error: Request failed with status code 401
    at e.exports (app.js?08ffc8c4:12)
    at e.exports (app.js?08ffc8c4:1467)
    at XMLHttpRequest.p.onreadystatechange (app.js?08ffc8c4:12)
```

Running version uhm latest Docker image as of now? Can't see version since settings are disabled :) Maybe print that in the console as well on start?

**Comment by lastzero** [comment]
Thanks for reporting. That's absolutely possible since the indexing page saves settings as well.
