### ISSUE TITLE
Purge: Can't remove deleted TIFF files

### ISSUE THREAD

**Issue by oscar-b** [photoprism/photoprism#917]
My originals folder contained a TIFF file named `83-1.tiff`. I later decided to batch convert these to jpeg myself instead of letting PhotoPrism do it. I ended up replacing the file with `83-1.jpg`. However, PhotoPrism refuses to give up the old tiff file that doesn't exist anymore, and now has the jpg stacked with the tiff.

Purge does nothing:

```
$ photoprism purge --hard
INFO[2021-01-18T20:40:07Z] removing missing files in originals
INFO[2021-01-18T20:40:07Z] read-only mode enabled
INFO[2021-01-18T20:40:07Z] purge: searching index for hidden media files
INFO[2021-01-18T20:40:07Z] removed 0 files and 0 photos in 1.938523516s
INFO[2021-01-18T20:40:07Z] closed database connection
```

I've done a full re-index, the tiffs are still there stacked.

I could either:

1. Wipe everything 
2. Delete sidecar files manually?

But as I don't think this is an entirely unlikely scenario, maybe it should be handled more gracefully?

Related I think: https://github.com/photoprism/photoprism/issues/568

**Comment by lastzero** [comment]
Did you delete the JPEG as well?

**Comment by oscar-b** [comment]
> Did you delete the JPEG as well?

No I went from `83-1.tiff` -> `83-1.jpg` in one go. Should I make a purge with no files, and then re-add the jpg instead?

**Comment by lastzero** [comment]
Maybe, or try a complete rescan limited to the specific directory.

**Comment by oscar-b** [comment]
> Maybe, or try a complete rescan limited to the specific directory.

`index --all` with a directory specified didn't change anything.

I'm sure I can get it purged, temporary removing the jpg files seems like a good solution. I will do that unless you want to troubleshoot it further?

**Comment by lastzero** [comment]
We'll take at loot at it, but later this week... already past 10pm over here :)

**Comment by oscar-b** [comment]
@lastzero Hey! I tried this change now, and there still seems to be an issue. I left the data intact, pulled the latest image and ran `index --all` and `purge` without any change. I still have ghost tiff images showing in the UI as images with multiple files.

As far as I can see now, it's because the initial import generated a jpg version of my tiff files, and put these in the sidecar folder. These files doesn't seem to be purged when the original file was deleted. "Storage Folder" is reported as "Sidecar" for these files.

Is this the expected behaviour for converted files?

**Comment by lastzero** [comment]
That's possible. We don't delete JPEGs yet, also in case the original file is only temporarily gone (unstable network file system etc). The TIFF in the files tab should be gone though?

**Comment by oscar-b** [comment]
Yeah it actually says it's a jpg:

![image](https://user-images.githubusercontent.com/85102/106578810-3b2c3f80-6540-11eb-8e1c-7faf79edb960.png)

**Comment by lastzero** [comment]
You may move this to archive and delete it manually for now. Need to think about a strategy for deleting related files when the "main" file is gone. May cause huge damage if done wrong.

**Comment by oscar-b** [comment]
> You may move this to archive and delete it manually for now. Need to think about a strategy for deleting related files when the "main" file is gone. May cause huge damage if done wrong.

Yup, agree. You'd want a manual confirmation step of some sort I guess.

Thanks for the help!

**Comment by lastzero** [comment]
It seems that the problem was caused by a download manager:
- #2530
