### ISSUE TITLE
Search: Can't search for wildcard strings like *(L)*

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#927]
As a user I want to find all files with (L) in their names so that I can process them.

**Current behaviour:** 

- One of the images that should be found is named  "P12345(L).jpg"
- Searching name:"P12345*" works
- Searching for name:"*12345*" works
- Searching for name:"(L)" does not work

**Expected behaviour:**
- Searching for name:"(L)" must work

**Comment by StephenBrown2** [comment]
Does escaping the parentheses work? i.e. `*\(L\)*`

**Comment by lastzero** [comment]
Maybe, test it 🤗

**Comment by StephenBrown2** [comment]
Just a guess from a passer-by with no internal knowledge or experience. Pay no attention... :-p

**Comment by lastzero** [comment]
Works for me:

![works-for-me](https://user-images.githubusercontent.com/301686/105718748-dc543e00-5f21-11eb-8819-d15923a8c6e4.png)

Searching for `name:*(L)*` can't work when "stack by sequential name" is enabled as `name` refers to the common name - the prefix that all files in the stack have in common. However, a sequence like (123) or (L) is a suffix and will be cut off to match the remaining name (prefix) with existing files. If you want to search for full file names, please use `filename` and not `name`.

**Comment by lastzero** [comment]
Sequential suffixes should not be removed from original names anymore after the changes performed for #920.

**Comment by toasti2000** [comment]
OK - that works perfectly! Thanks for the explanation! :-)
