### ISSUE TITLE
Metadata: Fallback to earliest file mod time in case there is no other date

### ISSUE THREAD

**Issue by TheLastGimbus** [photoprism/photoprism#930]
Hi!

I finally started using Photoprism after waiting, and it is **_nice_**

The problem I have so far: I had many photos/images/videos that did not have any exif embedded in them.

I've put them in the "Originals": (docker) `- "~/Pictures:/photoprism/originals"`, went into Library -> Indexing -> Start

All photos without exif were put at the top of everything (so their date was resetted), even tho I took very much care to keep their last modified value:
```bash
matiii@gimbc:~/Pictures$ stat untitled.png 
  File: untitled.png
  Size: 121499    	Blocks: 240        IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 3430159     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  matiii)   Gid: ( 1000/  matiii)
Access: 2021-01-20 06:28:30.257239910 +0100
Modify: 2019-01-25 19:56:50.000000000 +0100
Change: 2021-01-20 02:24:20.674248821 +0100
 Birth: -
```

Would it work if i just placed them in import folder, and imported from there?

**Comment by lastzero** [comment]
Importin probably wouldn't make a difference. We use the mod or birth time for setting the date from the file system when no metadata is available - so I'm surprised this didn't work. Maybe for some reason the change date is used and/or we have a bug.

**Comment by axllent** [comment]
I'm experiencing this too, any file that lacks exif data seems to get the date `Unknown`, rather than taking the file modification date. This includes videos and images.

**Comment by lastzero** [comment]
They are shown as unknown, but sorted accordingly. It's a feature, not a bug.

**Comment by axllent** [comment]
That makes sense, but sorted where accordingly? The videos all show up first in the Search (newest first) - so I always get about 150 black thumbnails (related to #648) when I land on `/browse`. The images however seem to be displayed accordingly I though.

**Comment by lastzero** [comment]
Just pushed some more improvements and fixes for time zone handling. This was needed after setting the date from the file system first and then looking for other metadata. Let us know if it works for you.

**Comment by axllent** [comment]
@lastzero Yes! I can confirm that the latest `preview` docker build fixes the date issue I was having with videos, thank you! My guess is that it was using the generated thumbnail date previously, and not the source file, am I right?

**Comment by lastzero** [comment]
Added a few improvements for dates & time zones to handle more edge cases. Feedback welcome.
