### ISSUE TITLE
Add prompt to choose which version of photo to download

### ISSUE THREAD

**Issue by miguelarios** [photoprism/photoprism#934]
I have all my photos to backup using Photosync as original (HEIC), and I noticed that PhotoPrism will create a JPG version of each file, but it doesn't seem to be save this version in my originals folder. I think its OK to create this version but it be nice to get a prompt to select which version a user wants to download.

![image](https://user-images.githubusercontent.com/24581058/105229105-0c1dd300-5b29-11eb-9596-31affe16fb42.png)

**Comment by graciousgrey** [comment]
We already have a ticket for this: https://github.com/photoprism/photoprism/issues/449.

At the moment you can choose which version to download in the edit dialogue's file tab (https://docs.photoprism.org/user-guide/organize/edit/#edit-files). Just click the download button of the file you want to download.
