### ISSUE TITLE
UX: Improve playing videos in search results and albums

### ISSUE THREAD

**Issue by Sherlock1979** [photoprism/photoprism#935]
On mobile devices videos don't have play buttons. When you click on a thumbnail the video does not start playing but only the sidecar preview image is shown.

There is a small video icon on the top left corner of the thumbnail. To play the video you either have to click that tiny icon or you have to open the sidecar image and click the same tiny icon after the title of the video.

To make it more confusing - when the sidecar image is shown there is the play button on the top of the screen. Which does not play the video but starts the slideshow of the pictures.

I think it's a bit cumbersome. It took me a couple of minutes to actually sort out how to play the videos on mobile. Maybe I am a bit too slow but maybe we can come up with a more user friendly way of playing videos on mobile devices.

Thanks.

**Comment by lastzero** [comment]
Use the cards view, it has a big play button. It tends to be to big for the mosaic view on mobile browsers, especially in select mode. We can use a play icon instead if this helps. Or playback is different in select mode, which I think is cumbersome as you say.

**Comment by Sherlock1979** [comment]
Well, I am not a UX expert and PhotoPrism is not my product so I can only share my own opinion which may not be ultimately perfect or right. :) But here are my 2 cents...

I think replacing the icon to a play button would help a lot by itself. The current video icon for me is more of an indicator only as opposed to being an icon that I can actually click. The actual play icon (circle with a triangle in it) is a more universal indicator that actually that would play the video.

So with this change I agree that we may not need a big play button in mosaic view.

And what about taping on the mosaic thumbnail? I would think that the expected behaviour is to play the video and not to open the preview sidecar image. What do you think?

**Comment by lastzero** [comment]
When you scroll on a touch screen, it sometimes happens that you play a video if that's the default action. May get expansive when you pay for mobile traffic.

**Comment by Sherlock1979** [comment]
Well, in that case can't you just close the video player after a couple of seconds?

**Comment by lastzero** [comment]
![Screenshot_20210121_085408](https://user-images.githubusercontent.com/301686/105320355-599c4d80-5bc6-11eb-8888-d3d0f828c93b.jpg)

Tested it first thing in the morning, before I even had breakfast. The mosaic view is impossible to use on a touch screen when every pixel of an item triggers an action. Maybe we give up opening the video as image then.

**Comment by lastzero** [comment]
Please test :+1:

**Comment by lastzero** [comment]
Preview build is running: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by Sherlock1979** [comment]
I have tested the preview build. As far as I can tell the implemented change is that now the videos open instead of the sidecar image. **I love it.** I think it is a much better UX as it is the actual behaviour the user would expect. Thank you for considering this change. The only other change I would propose is the video icon change to the play button - but it's more of a nice-to-have.

I have a related question. It's more for my curiosity. If I open the video player and the video starts playing an then I close the video - would it stop downloading the video or would it continue and download the entire video in the background?

And another quick observation. Happy to open a new issue for it if needed be. When I open PhotoPrism it shows me a page called Photos. This page shows only photos and not videos. On the menu I can navigate away from this page e.g. to the Browse/Search page where I can see all the photos and videos. Which is great. But then there is no way for me to go back to the Photos page as it is no longer in the menu. To be honest, I don't think people would need the initial Photos page any more. Maybe the default initial screen in PhotoPrism should be the Browse/Search page and not the Photos page. What do you think?

Cheers,
David

**Comment by lastzero** [comment]
> I have tested the preview build. As far as I can tell the implemented change is that now the videos open instead of the sidecar image. **I love it.** I think it is a much better UX as it is the actual behaviour the user would expect. Thank you for considering this change. The only other change I would propose is the video icon change to the play button - but it's more of a nice-to-have.

We'd rather use the upper left corner to indicate it's a *Video* so that it's the same concept for all media types including *RAW* and *Live Photos*.

> I have a related question. It's more for my curiosity. If I open the video player and the video starts playing an then I close the video - would it stop downloading the video or would it continue and download the entire video in the background?

The player uses streaming, which (should) stop when the video is closed. If not, it's a bug.
 
> And another quick observation. Happy to open a new issue for it if needed be. When I open PhotoPrism it shows me a page called Photos.

That may be because the manifest.json file was cached, especially if you added PhotoPrism to your home screen / desktop. Try removing and adding it again. We kept the route for the sub navigation e.g. when you search for monochrome photos - it's also easer to remember / bookmark than a list of get parameters.

**Comment by Sherlock1979** [comment]
> We'd rather use the upper left corner to indicate it's a _Video_ so that it's the same concept for all media types including _RAW_ and _Live Photos_.

My bad. I was not clear enough. I was actually ptoposing to change the top left icon to a play icon. It may be easier to recognise and associate to videos then the current icon. But it may as well just be my personal preference.

> > And another quick observation. Happy to open a new issue for it if needed be. When I open PhotoPrism it shows me a page called Photos.
> 
> That may be because the manifest.json file was cached, especially if you added PhotoPrism to your home screen / desktop. Try removing and adding it again. We kept the route for the sub navigation e.g. when you search for monochrome photos - it's also easer to remember / bookmark than a list of get parameters.

Yep. I uninstalled and installed the pwa and now it works as expected. Makes total sense. Thanks again.

**Comment by lastzero** [comment]
> My bad. I was not clear enough. I was actually ptoposing to change the top left icon to a play icon. It may be easier to recognise and associate to videos then the current icon. But it may as well just be my personal preference.

Then we should also consider changing the icon the main navigation. You think that's a good idea and users will associate the play arrow with videos?

**Comment by Sherlock1979** [comment]
Yes. That is my firm view. I would go with play_circle_filled.

But maybe you should ask others in the community as well.

**Comment by lastzero** [comment]
See #935

**Comment by Genygo** [comment]
Hi!
When you start a Video from Slideshow, an go to the next Picture with the Keyboard Arrows, the video keeps playing above the new picture.
Supposed behaviour would be closing the video an show picture?

**Comment by lastzero** [comment]
We'll eventually have to develop a custom, combined player anyway. If this doesn't bother you too much, we would invest our time in other issues instead.

**Comment by Genygo** [comment]
Sure! not a big deal for me.
Maybe file deletion next? :smirk:

**Comment by lastzero** [comment]
Does the updated navigation and video icons / playback work for you otherwise?

**Comment by Genygo** [comment]
Videos now playing directly is more intuitive i think.
Dont know if the "live photos" need the same. 
New icon for videos is better.
On mobile: scrolling accidentally opens picture instead.

**Comment by lastzero** [comment]
We detect moves. Does this always happen or always? On the picture, not on the icon.

**Comment by Genygo** [comment]
Just sometimes.
Maybe due to an older phone
