### ISSUE TITLE
Mobile UX: Albums: Search input field is hidden in portrait mode

### ISSUE THREAD

**Issue by Sherlock1979** [photoprism/photoprism#937]
When you go to Albums on the top of the screen there is a Search input field and a Categories drop down. 

On mobile in portrait mode the Search input field is hidden. When you turn the phone to landscape mode the Search becomes visible. The Categories drop down is always visible.

It would be great if users could search in portrait mode as well. I would argue that Search is more important than Categories so if for some reason you cannot show both then I would recommend to show the Search instead of the Categories. I think ideally both should be accessible in portrait mode.

Thanks.

**Comment by graciousgrey** [comment]
I had the same thought yesterday :)

**Comment by lastzero** [comment]
Available for testing in our demo soon.

**Comment by lastzero** [comment]
Released 💐
