### ISSUE TITLE
Reverse Proxy Under Subdirectory

### ISSUE THREAD

**Issue by scolby33** [photoprism/photoprism#939]
Is it possible to host Photoprism under a subdirectory, like at `http://example.com/photoprism`? An example NGINX config could look like:

```
        location /photoprism/ {
            client_max_body_size 500M;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            proxy_pass http://photoprism:2342/photoprism/;

            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

I tried setting the environment variable `PHOTOPRISM_SITE_URL=http://localhost:2342/photoprism/`, but only the loading logo page loaded, and then requests were made to `http://{ip address}/static/build/app.css?4727fa28` and similar locations that do not exist.

**Comment by lastzero** [comment]
No, it's not possible without major code changes.

**Comment by jt0in3e** [comment]
@scolby33 I've used your configs and new version of ```photoprism``` and now everything works. I've written a blog post, it is in Ukrainian lang, but configs are understandable ))
[link to blog post](https://jt0in3e.github.io/2022/05/%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B0%D1%94%D0%BC%D0%BE-photoprism-%D0%B7%D0%B0-%D1%81%D1%82%D1%96%D0%BD%D0%BE%D1%8E-nginx-%D1%96-%D0%B2-%D1%81%D1%83%D0%B1-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%96%D1%97-%D0%BF%D0%B0%D0%BF%D1%86%D1%96/)
decided to write it here, maybe it'll help someone to configure photoprism to run in sub directory behind Nginx reverse proxy

**edit**: added link

**Comment by shunsuke218** [comment]
Thanks to @scolby33 and @jt0in3e, I just wanted to share that I successfully configured PhotoPrism behind an Apache reverse proxy under a subdirectory (e.g., https://example.com/photoprism/). Since this seems to have been a pain point in the past (and I also struggled with it), I hope this helps someone else.

Apache Configuration
```
<Location /photoprism/>
    ProxyPreserveHost On
    ProxyPass http://192.168.0.42:2342/photoprism/
    ProxyPassReverse http://192.168.0.42:2342/photoprism/

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Ssl on
    RequestHeader set X-Forwarded-Prefix "/photoprism"
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*) ws://192.168.0.42:2342/photoprism/$1 [P,L]
</Location>
```

Docker Compose (docker-compose.yml)
```
environment:
  PHOTOPRISM_SITE_URL: "https://example.com/photoprism/"
  PHOTOPRISM_DISABLE_TLS: "false"
```
Make sure to set the PHOTOPRISM_SITE_URL including the subdirectory path:
Without the correct SITE_URL, PhotoPrism may generate incorrect paths for static assets like CSS and JS files.
