### ISSUE TITLE
No docker deployment?

### ISSUE THREAD

**Issue by KipourosV** [photoprism/photoprism#94]
Is there a way to deploy it using the old traditional way?
My environment is LXC...

**Comment by lastzero** [comment]
What is the old traditional way? Do you ask for a list of dependencies and the compiler command for installation?

**Comment by KipourosV** [comment]
Yes!!! (Sorry)

**Comment by lastzero** [comment]
You'll need Go >= 1.11, TensorFlow for C, Make, NPM, Yarn and MySQL. The [Dockerfile](https://github.com/photoprism/photoprism/blob/develop/docker/development/Dockerfile) contains all commands, it's easy to read (even if you haven't worked with Docker before). Of course package names are different for each Linux distribution. The [Makefile](https://github.com/photoprism/photoprism/blob/develop/Makefile) contains all build targets, try `make all install` (very much the old traditional way).

**Comment by lastzero** [comment]
Yes, `make all install` not make install all though. Also you might have to change settings in the config file e.g. for the database host and port.

**Comment by KipourosV** [comment]
Which config file?

**Comment by lastzero** [comment]
See `Makefile`:
```
install-config:
	mkdir -p /etc/photoprism
	test -e /etc/photoprism/photoprism.yml || cp -n configs/photoprism.yml /etc/photoprism/photoprism.yml
```

**Comment by KipourosV** [comment]
Thanx for all the help...
The more I dig into this the more deploying a docker vm seems a better idea...

**Comment by lastzero** [comment]
Yes, especially for testing. The final release will be a single binary download.
