### ISSUE TITLE
Albums: Not using external URL when using Share Album

### ISSUE THREAD

**Issue by ohjohnsen** [photoprism/photoprism#941]
I've used Nginx Proxy Manager to expose PhotoPrism on a subdomain on my domain: photoprism.example.com.  Nginx Proxy Manager also handles SSL certificate request from Let's Encrypt.

But when trying to share an album, the URL is generated using "localhost:2342" as host.  Manually rewriting the URL to use https://photoprism.example.com/etc works fine, but is a bit cumbersome.

Is it possible for PhotoPrism to detect if a reverse proxy server is used and to update the URL's of shared albums?

![2021-01-21 14_26_45-PhotoPrism_ January 2021](https://user-images.githubusercontent.com/16133835/105357926-c8dd6600-5bf5-11eb-8977-87013b93632c.png)

**Comment by lastzero** [comment]
See #752 😃

**Comment by ohjohnsen** [comment]
Thank you for the feedback.

**Comment by lastzero** [comment]
You're welcome 💐
