### ISSUE TITLE
Moments: Add delete button to context menu

### ISSUE THREAD

**Issue by Genygo** [photoprism/photoprism#942]
Moments are created at indexing. 
Now i added one folder to .ppignore.
The coresponding moments folder is now empty and cant be deleted from the web ui
![grafik](https://user-images.githubusercontent.com/26231125/105388484-00103f00-5c17-11eb-93f2-2ee454a056f1.png)
![grafik](https://user-images.githubusercontent.com/26231125/105388527-0e5e5b00-5c17-11eb-89c3-bc071a511ebe.png)

**Comment by lastzero** [comment]
You're right, we removed the delete option form the context menu as there is no way to recover deleted moments. In your case, it might make sense to delete it. We'll improve this in one of our next updates.

**Comment by lastzero** [comment]
Was removed because of *Folders disappeared after removing album #738*
