### ISSUE TITLE
Struggling to install on Synology Docker

### ISSUE THREAD

**Issue by amuilyas** [photoprism/photoprism#944]
Hi trawled the Internet for help and I cannot find any solutions.  I have tried using Synology Docker GUI and Portainer but they both give me issues.  I'll focus this cry for help on GUI issues.

**MARIA_DB**
Have installed  with no issues and container is running.  In setup under networking I selected HOST mode so that it uses the local host address (192.168.1.251:3306).
Log file as CSV https://gofile.io/d/KBuZcK

**PHOTOPRISM**
Installing via the Synology Docker GUI.  But it always stops and restarts after 1min.  Looking at the log file it is searching for mariadb on the wrong address (192.168.1.1:53).  Even though I have edited the host address and ports in the environmental values.
Log file as CSV https://gofile.io/d/PNnGu6
Screen capture of the environmental values https://gofile.io/d/49sl14

Many thanks for any help as I have tried this a number of times and cannot see my way out of the hole.

**Comment by gpopesc** [comment]
use the docker compose from main project. I spent few hours also trying to make it work.
it works perfectly with mariadb (just comment or delete mariadb from compose file.

 https://docs.photoprism.org/getting-started/docker-compose/

**Comment by amuilyas** [comment]
> use the docker compose from main project. I spent few hours also trying to make it work.
> it works perfectly with mariadb (just comment or delete mariadb from compose file.
> 
> https://docs.photoprism.org/getting-started/docker-compose/
> 
> or even better:
> https://docs.photoprism.org/getting-started/portainer/synology/

Thanks for the reply
I tried portainer several times and get this error.
![image](https://user-images.githubusercontent.com/77816893/105619732-6d080e00-5daa-11eb-8b13-830cd52b9e80.png)

I figured the docker container would be easier but that also gives me issues as I described above.

**Comment by gpopesc** [comment]
Portainer is very tricky from the errors point of view. You cannot understand too much from it and you can't debug, unless you know what are you doing. Even a space char could throw an error like this. I need to see all your setting from file. I recommend you to put everything in a docker-compose file and run "docker-compose config". It gives you more info than portainer.
In the meantime, I can give you mine, and you can replace with your variables. I work with MariaDb from synology and I created in phpmyadmin the database in advance (I don't know if it is necessary and photoprism create one at the connection. first time).

Just copy-paste the text from my file in your portainer.

[docker-compose.yml.txt](https://github.com/photoprism/photoprism/files/5862090/docker-compose.yml.txt)

![image](https://user-images.githubusercontent.com/11590919/105628848-12bd8a80-5e48-11eb-901e-625d9764b4e6.png)

**Comment by lastzero** [comment]
Might be related to #963?

I've seen this error before and it's somehow related to the MariaDB / MySQL image, which doesn't work well either on ARM or on your operating system. Might also depend on Linux kernel security modules. Try using an alternative MariaDB / MySQL database image. Found those with a quick google search:

- https://hub.docker.com/r/bitnami/mariadb
- https://hub.docker.com/r/linuxserver/mariadb

**Comment by graciousgrey** [comment]
We close this as there was no further feedback
