### ISSUE TITLE
UX: Allow ctrl+click to open in new tab (e.g. album, photo)

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#948]
Currently, when clicking on an album or a photo while holding down the ctrl key, the link is not opened in a new tab.

I think allowing this is pretty standard on the web and this would also be quite useful to browse through a large collection in one go and opening tabs in the background with interesting albums/photos for later inspection.

**Comment by lastzero** [comment]
That's because we had to refactor event handling for https://github.com/photoprism/photoprism/issues/832

Right click and "open in new tab" still works. Do you know if ctrl works on all computers or Mac / Windows / Linux are different?

**Comment by wiwie** [comment]
Right click and "open in new tab" works for albums, true. But at least on Linux + Firefox, right clicking on a photo card in the "Search" tab does not show anything pertinent to opening a link (e.g. "open in new tab").

I don't know whether ctrl+click works on Mac. I do know that it usually does work on Windows and Linux.

**Comment by lastzero** [comment]
It's because there is no single photo view implemented yet. Can't work on everything at the same time 😉

In any case, let's do some research before implementation.

**Comment by graciousgrey** [comment]
This be further evaluated in the scope of: https://github.com/photoprism/photoprism/issues/1131
