### ISSUE TITLE
Feature request: Mass assignment of labels

### ISSUE THREAD

**Issue by wiwie** [photoprism/photoprism#949]
It would be great, if one could assign the same label to multiple selected photos at the same time without the need to go into each photo, edit it, and add the label.

I searched for existing issues, but couldn't find a fitting one.

**Comment by graciousgrey** [comment]
This will be part of batch edit https://github.com/photoprism/photoprism/issues/271 :)

**Comment by wiwie** [comment]
Great, thanks!
