### ISSUE TITLE
Mobile: Swipe up on ❤️ in search results triggers like

### ISSUE THREAD

**Issue by benjaminknauer** [photoprism/photoprism#953]

**Comment by lastzero** [comment]
I know, right now you need to be careful when scrolling on a touch screen. Can you provide a PR to improve this?

**Comment by lastzero** [comment]
Guess that's a no :wink:

**Comment by benjaminknauer** [comment]
😆 I would love to help you out in the future! Love your product! But as alway the time is against me ⏳

**Comment by lastzero** [comment]
Started a preview build, you may test when it's done: https://docs.photoprism.app/getting-started/updates/#development-preview
