### ISSUE TITLE
Settings: Add "Estimates" feature flag to UI

### ISSUE THREAD

**Issue by ntimo** [photoprism/photoprism#954]
Hello,
I just recently started using Photoprism and noticed something odd. When a Photo like a iOS screenshots for example have no Geolocation data embedded into it the photo is shown with a semi random location in their title (most of them show Düsseldorf, a few other Köln). 

Here is a example screenshot of this:
![Screenshot 2021-01-25 at 08 48 34](https://user-images.githubusercontent.com/6145026/105676041-3cc78900-5eea-11eb-84a8-2bf726a76cb0.png)
![Screenshot 2021-01-25 at 08 48 26](https://user-images.githubusercontent.com/6145026/105676044-3df8b600-5eea-11eb-8049-3ae4f50a1deb.png)

**Comment by Happyfeet01** [comment]
Have the same Issue with photos taken by an Smartphone, in 2013 and 2018. Shooted in Fulda/Germany and near Linz/Austria.

**Comment by lastzero** [comment]
These are estimates. If you don't like them: The next update includes an "Estimates" feature checkbox in *Settings*. You may currently disable this manually in `config/settings.yml` and restart.

**Comment by ntimo** [comment]
Thank you, if you don't mind could you maybe explain to me how these estimates work? Would be kind of interesting to know :)

And also thanks for the fast response :O

**Comment by Happyfeet01** [comment]
Thx for the fast reponse

**Comment by Happyfeet01** [comment]
how can disable it?

**Comment by lastzero** [comment]
See
- Photoprism deducing location without Exif information. How? #416
- Places: Configure location estimation parameter #622

**Comment by lastzero** [comment]
Preview build has been started: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by Happyfeet01** [comment]
realy fast support thanks.

**Comment by Happyfeet01** [comment]
have updated to the Preview Version. But where are this Option?

**Comment by lastzero** [comment]
*Settings* bottom left:

![settings](https://user-images.githubusercontent.com/301686/105702985-def86880-5f0c-11eb-970e-3aff00e63770.png)

**Comment by lastzero** [comment]
Note that changing this won't instantly remote existing estimates. That would be too slow. Only new pictures will be affected for now. Removing existing estimates may be implemented later.

**Comment by Happyfeet01** [comment]
![grafik](https://user-images.githubusercontent.com/3295104/105703304-50381b80-5f0d-11eb-9534-a21fe874b43f.png)

**Comment by lastzero** [comment]
Update again, the build only just completed - that's why I added the link, so that you can check if it's done already: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by lastzero** [comment]
Update your docker-compose.yml to use photoprism/photoprism:preview instead of photoprism/photoprism:latest for testing our latest development preview. The image name for ARM64 is photoprism/photoprism-arm64:preview.

**Comment by Happyfeet01** [comment]
thx works

**Comment by ntimo** [comment]
@lastzero thank you very much, it works like a charm.
