### ISSUE TITLE
Web page not visible.help me

### ISSUE THREAD

**Issue by RUANHAOANDROID** [photoprism/photoprism#97]
The photos I poured in before can't be seen, but they do exist, such as the "2017 2016" folder.

**Comment by RUANHAOANDROID** [comment]
<img width="1458" alt="2019-02-16 14 54 22" src="https://user-images.githubusercontent.com/10151414/52895900-90f46980-31fb-11e9-9f70-e7ee1e628036.png">
<img width="854" alt="2019-02-16 14 54 35" src="https://user-images.githubusercontent.com/10151414/52895903-9d78c200-31fb-11e9-8c59-c89c12e4231d.png">

**Comment by RUANHAOANDROID** [comment]
I executed "photoprism index" to show complete,.thank you.I love this！

**Comment by lastzero** [comment]
Glad you like it! 👍
