### ISSUE TITLE
undefined reference to `TF_StringDecode'

### ISSUE THREAD

**Issue by xyproto** [photoprism/photoprism#970]
I'm trying to build Photoprism on Arch Linux. When running `make` I get the following error:

```
...
 github.com/tensorflow/tensorflow/tensorflow/go
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125801:10: warning: function may return address of local variable [-Wreturn-local-addr]
125801 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125761:10: note: declared here
125761 |   Select standin;
       |          ^~~~~~~
# github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: $WORK/b221/_x010.o: in function `_cgo_47e32ed817c5_Cfunc_TF_StringDecode':
/tmp/go-build/cgo-gcc-prolog:130: undefined reference to `TF_StringDecode'
/usr/bin/ld: $WORK/b221/_x010.o: in function `_cgo_47e32ed817c5_Cfunc_TF_StringEncode':
/tmp/go-build/cgo-gcc-prolog:152: undefined reference to `TF_StringEncode'
/usr/bin/ld: $WORK/b221/_x010.o: in function `_cgo_47e32ed817c5_Cfunc_TF_StringEncodedSize':
/tmp/go-build/cgo-gcc-prolog:170: undefined reference to `TF_StringEncodedSize'
collect2: error: ld returned 1 exit status
make: *** [Makefile:86: dep-go] Error 2
```

I'm using these tensorflow-related packages:

python-opt_einsum 3.3.0
python-tensorflow-estimator 2.3.0
python-tensorflow-opt-cuda 2.4.0
tensorflow-opt-cuda 2.4.0

gcc 10.2.0

I'm using latest master of photoprism, commit e1752517833962d4fdfaf94d7a66ee3565217f1d.

**Comment by lastzero** [comment]
We're using tensorflow 1.5, not 2.4 - also there seems to be an issue with the sqlite3 library. Maybe also the wrong version. PhotoPrism requires many dependencies, so we recommend using our Docker container for now unless you have the experience & time to solve these issues on your own. We'll provide .deb (and other) packages as soon as possible.

**Comment by xyproto** [comment]
Thanks for the response.

I was hoping to package photoprism for Arch Linux, but if it relies on older versions of libraries, it's problematic.

**Comment by lastzero** [comment]
The TensorFlow libs are versioned since 1.5, so it should be possible to install 1 and 2 at the same time.

Compiling TensorFlow is more work than many assume and the new version provides no advantage for our use case - in fact it may not be compatible with some of the platforms we support. So "good" for you, bad for others. Took me one week to get behind all the secrets and submit a PR to make it compile on ARM. AFAIK Google only just removed the AVX requirement from 2.4 - but really didn't have much time to follow in detail.

**Comment by xyproto** [comment]
The Arch Linux packages only provides the latest release versions, with the main exception of keeping `python2` around (the removal is a work in progress).

If Photoprism should support the latest versions in the future, I would be happy to look into packaging it again, since I think it looks like a very promising application.

Cheers

**Comment by lastzero** [comment]
Going to upgrade later this year. Need to focus on high priority feature requests on our roadmap first.
