### ISSUE TITLE
How does photoprsim handle album dupliactes if all stacking is off.

### ISSUE THREAD

**Issue by Darkwolf1515** [photoprism/photoprism#971]
What I mean is, all stacking is off, I have album a, and album b, I upload a batch of photos to album a, and then album b, but they happen to have some identical photos, does it simply just tag the first upload with album b, or will it create duplicates? Or will it just erase the dupes and not tag them. Thanks!

**Comment by lastzero** [comment]
That's an edge case. I assume photos will only be added if they are not skipped as duplicates - simply because that happens well before this code is running. Obviously you need a photo first before you can add it.

Should be possible to implement this, but users are waiting for many important features - don't think we should take care of this edge case first.

**Comment by lastzero** [comment]
Also I assume not everyone wants this behaviour - so we'd need to add yet another config option and documentation.

**Comment by Darkwolf1515** [comment]
Well, sadly I have to do it all over again, added a couple of "photos from year 201x" folders before the album folders, meaning when I upload my album folders, nothing will happen.

**Comment by lastzero** [comment]
Wouldn't it be much easier to just index your existing folder structure and then use the folder as album or convert the folders to manually managed albums?

**Comment by lastzero** [comment]
The upload wasn't meant as the primary way of adding photos to albums :)

**Comment by StephenBrown2** [comment]
Sounds like your adding a Google Photos Takeout to PhotoPrism. According to the [docs](https://docs.photoprism.org/user-guide/use-cases/google/#importing-photos-from-google-photos):
> Google Photos albums won't be imported yet as we're trying to find a way to deal with auto-generated albums users may not want to import.

**Comment by graciousgrey** [comment]
@StephenBrown2 If you move your Google Takeout to PhotoPrism and index it, we already read out most of the metadata, as stated in the docs. 
Generating the albums from Google Photos is planned as well.

**Comment by StephenBrown2** [comment]
> @StephenBrown2 If you move your Google Takeout to PhotoPrism and index it, we already read out most of the metadata, as stated in the docs. 
> Generating the albums from Google Photos is planned as well.

Yup, that's exactly my point. Albums aren't yet supported, which it seems the original issue is about.
