### ISSUE TITLE
Option to move all photos of a folder to archive or private

### ISSUE THREAD

**Issue by Bitwolfies** [photoprism/photoprism#972]
Want my google photos archive to go straight to this ones, doesnt seem to be an option.

**Comment by lastzero** [comment]
Why do you upload or create albums of photos you want to archive (delete)?

**Comment by Darkwolf1515** [comment]
> 
> 
> Why do you upload or create albums of photos you want to archive (delete)?

To me, I treat archive as "dont need to see in the main view, but don't wish to remove.

**Comment by graciousgrey** [comment]
I guess adding a whole folder/album etc to archive could be part of batch edit.

**Comment by lastzero** [comment]
You could use the private flag instead as the archive flag will also skip those photos when indexing and makes it possible to permanently delete them. Doesn't seem this is what you want.

**Comment by graciousgrey** [comment]
Will be part of: https://github.com/photoprism/photoprism/issues/480

Once this is implemented you could create an album "For Archive" and mark this Album as archive or private. During the web upload you can choose to upload files directly to this album.
