### ISSUE TITLE
Video player can be activated even if hidden

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#979]
If I open a video in PhotoPrism, play it then close it, I can still play it by clicking on the “Play / Pause” button of my keyboard: I don't see the video but the sound is playing.

It looks like the player is hidden but still present in the DOM.

I can also open another video and play it, so I hear 2 videos at the same time.

Version: last preview Docker image.

**Comment by lastzero** [comment]
That's not an accident and not bad by itself, but it shouldn't listen to keyboard events when hidden.

**Comment by alexislefebvre** [comment]
This may be related to #915
