### ISSUE TITLE
Go Client

### ISSUE THREAD

**Issue by kris-nova** [photoprism/photoprism#980]
Hi - I have a use case to download and consume photos from my existing photoprism installation

Anyway I am trying to figure out the best way to consume the API data with Go. I was unable to find a client package, and the majority of the method calls (function calls) are all stored in `/internal`.

---

Questions:

 1) Does a Go client (`client-go`) exist?
 2) Is there documentation/examples for this anywhere?
 3) If no such client exists, I am happy to write and maintain one if the project would be interested. 

Holler at your girl - love the project - you all are awesome.

**Comment by lastzero** [comment]
Thank you! We don't have a go client yet as we use JS in our frontend. You're welcome to contribute one 👍

**Comment by kris-nova** [comment]
Sounds good - I will start hacking on one here https://github.com/kris-nova/photoprism-client-go

---

I added the GNU 3.0 [license](https://github.com/kris-nova/photoprism-client-go/blob/main/LICENSE) so if we want to move into this org later we can

stay tuned for updates! again - love the project - well done

**Comment by kris-nova** [comment]
Hey everyone quick update:

So the code in my [client-go](https://github.com/kris-nova/client-go) repository is in a "prototype" phase if anyone wants to take a look.

Right now there is only a few methods implemented

```go

func (v1 *V1Client) GetPhoto(uuid string) (Photo, error)
func (v1 *V1Client) UpdatePhoto(object Photo) (Photo, error) 
func (v1 *V1Client) GetPhotoDownload(uuid string) ([]byte, error) 
func (v1 *V1Client) GetPhotoYaml(uuid string) ([]byte, error)
func (v1 *V1Client) ApprovePhoto(uuid string) error 
func (v1 *V1Client) LikePhoto(uuid string) error
func (v1 *V1Client) DislikePhoto(uuid string) error 

```

and the implementation code looks like

```go
	uuid := "pqnzigq351j2fqgn" // This is a known ID
	client := photoprism.New("http://localhost:8080")
	err := client.Auth(photoprism.NewClientAuthLogin("admin", "password"))
	if err != nil {
		// error
	}

	photo, err := client.V1().GetPhoto(uuid)
	if err != nil {
		// error
	}

	photo.PhotoTitle = "A really great photo!"
	photo, err = client.V1().UpdatePhoto(photo)
	if err != nil {
		// error
	}

	file, err := client.V1().GetPhotoDownload(photo.UUID)
	if err != nil {
		// error
	}

	for _, f := range photo.Files {
		fileName := fmt.Sprintf("ignore_%s", path.Base(f.FileName))
		logger.Always(fileName)
		ioutil.WriteFile(fileName, file, 0666)
	}
```

---

There is a working integration suite that will exercise the code.

I think it's at a point we could clean it up (docs, etc) and auto-gen a lot of the code from the existing `internal/api` data. 

Anyway I don't know enough about the API (or frontend code at that) to be very effective with fleshing out a lot of the methods. If anyone wants to help with the boilerplate please let me know (pull requests accepted!)

This feature set satisfies my immediate needs, so I am unsure when I will have time to build out other methods. The good news is that they should be fairly easy to implement at this point.

Hit me up at kris@nivenly.com or respond to this issue if anyone has any questions.

Enjoy :)

**Comment by kris-nova** [comment]
If anyone has any thoughts/feedback on approach/architecture let me know - I took the lazy approach and am happy to refactor or make changes if there are any security concerns I am missing (the auth bits were interesting)

**Comment by kris-nova** [comment]
I cut a release for a 1.0.0 client - it has limited functionality but I will iterate as needed. Pull requests accepted if anybody wants to contribute.

Also if you want my shitty code I am happy to donate it to the project. 

https://github.com/kris-nova/photoprism-client-go/releases/tag/v1.0.0

**Comment by lastzero** [comment]
Thank you very much! 🌈

We'll need a bit of time to figure out how to organize client libraries... should also provide better API docs.

**Comment by kris-nova** [comment]
No worries - I closed the issue because this serves the purpose of why I originally opened the issue - As I build more functionality into my photoprism client - i will be adding more methods and tests and cutting releases as needed :) 

so I think this is good for now!

**Comment by lastzero** [comment]
Added a page for this to our Developer Guide:

https://docs.photoprism.org/developer-guide/clients/go/
