### ISSUE TITLE
Using SSL

### ISSUE THREAD

**Issue by FlyingPersian** [photoprism/photoprism#981]
Hello,

I installed photoprism using docker on my Raspberry Pi. Surprisingly, I haven't found anything related to enabling SSL. Does anybody have a tip on how to do so? I already created self-signed certificates signed by my own CA and also installed that CA on all my devices (phone, laptop, PC).

I'm using a docker-compose.yml file to set it up.

Kind Regards

**Comment by lastzero** [comment]
Use a reverse proxy as explained in our docs.

**Comment by FlyingPersian** [comment]
> Use a reverse proxy as explained in our docs.

Thanks for your reply. I'm not using a reverse proxy as I'm not exposing it to the internet. I'm using a VPN to connect to my home network if I needed to access photoprism from the outside.

**Comment by lastzero** [comment]
If you're using a VPN, why do you need SSL?

**Comment by FlyingPersian** [comment]
I figured to rather have it and not need it rather than not having it and needing it :P I use SSL on all other services as well just to be sure.

**Comment by lastzero** [comment]
We may add this eventually, but there are more than enough reverse proxies so that we don't need to reinvent the wheel and instead focus on higher value feature requests.

**Comment by FlyingPersian** [comment]
Alright thank you! Feel free to re-open this thread if this feature will be added. I consider the issue resolved for now. Thanks!
