### ISSUE TITLE
Metadata: Automatically remove orphan countries

### ISSUE THREAD

**Issue by jean-louis67** [photoprism/photoprism#982]
The list of countries should be purged, if possible.
A number of countries appear in the list although no photo is attached.
![image](https://user-images.githubusercontent.com/65403912/106378225-6299d580-63a3-11eb-9c46-b4704978cec3.png)

This results, for example, from a temporary error in entering coordinates.
It also happens to me for convenience to enter corrdinates by pasting the longitude of several photos, applying to each photo, then pasting the latitude. In doing so, the coordinates are temporarily incorrect and we show countries located on the equator…
![image](https://user-images.githubusercontent.com/65403912/106378239-6d546a80-63a3-11eb-882d-a0071f0d4f13.png)

**Comment by jean-louis67** [comment]
For testing, I suppose I've to wait for the next update of the docker image? Or should I be able to test in an on line instance of PhotoPrism?
However, thank you very much for your work!

**Comment by lastzero** [comment]
You may use the preview image or demo.

**Comment by jean-louis67** [comment]
I added a photo about 2 hours ago on demo. By modifying the coordinates, it went to Algeria, then to Zambia
The photo has now disappeared, I don't really know why, but the 2 countries still appear in the list. Maybe we have to wait a bit before updating the list.
On the other hand, if you click on Places, no photo appears in these countries.

**Comment by lastzero** [comment]
Lists only get purged when indexing.

**Comment by jean-louis67** [comment]
Hello,
I just updated my docker image, and indexed. The country list is now purged.
Thank you very much.
