### ISSUE TITLE
storage directory indexed

### ISSUE THREAD

**Issue by Gaet81** [photoprism/photoprism#985]
Hello,

Thank you for this really nice app!
I've run the index for the first time, and I think I might face an infinite loop.
I've set my external drive as the original directory to index and I've set the storage directory on this drive.
Now I've launched the index a while ago and I can see that it's now indexing the storage directory that is on the originals directory....
So I'm fearing that it will infinite loop, I've waited whole day before submitting the query but still a long time before indexing of this folder will be over and as well the storage directory keep growing so I will stop it.  
environment:
- browser = firefox 85.0
- operating system = archlinux
- installed memory = 8gb
- processor type = intel.
- I'm running photoprism in a docker on my local machine

**Comment by lastzero** [comment]
The storage folder must not be in (or be the same as) the originals folder. Otherwise you're indexing your index and cache, which doesn't make any sense.

**Comment by Gaet81** [comment]
Is there any parameter where you can exclude a folder?
As far as I know there isn't and so for me the storage folder should be automatically skipped during indexing.
And if I need to add all my folders in my external drive except the storage one it will take a bit of time...

**Comment by lastzero** [comment]
Hidden files and folders (starting with a dot) will be excluded automatically. Also you may use a .ppignore file listing all files and folders you wish to exclude.

Setting `PHOTOPRISM_STORAGE_PATH` to `.photoprism` should work for your use case.

**Comment by Gaet81** [comment]
Thanks for the quick reply @lastzero !

**Comment by harshavmb** [comment]
I just want to add something here. I too got stuck with this issue as I put storage under the originals folder & accidentally got indexed. Thousands of images (thumbnails) got indexed, it was a bit overwhelming in the beginning. 

Nevertheless, I fired a DELETE query to the MySQL database & got these images removed. Identified them by `photo_quality` column on `photos` table. Also, respective entries had to be removed from the `files` table as well. 

I did come up with the below query to remove entries from the database. 
`delete photos, files from photos inner join files on files.photo_id = photos.id where photos.photo_quality < 3;`

You can filter them by several columns present in both `files` & `photos` tables. If you have setup review by default, it would be much easier with `photo_quality` as these are thumbnails and relatively much smaller in size. 

Hope this helps!
