### ISSUE TITLE
Videos: Transcode MOV in advance

### ISSUE THREAD

**Issue by uxusoft** [photoprism/photoprism#986]
Please add feature to transcode videos during import or as separate function.

For example, when I try to play imported MOV videos from iOS, photoprism starts converting:
<img width="1077" alt="Screenshot 2021-01-31 at 18 28 39" src="https://user-images.githubusercontent.com/64733669/106392624-08286580-63f3-11eb-90f6-2c87151d494d.png">

During this conversion that takes minutes, I have to wait for video:
<img width="368" alt="Screenshot 2021-01-31 at 18 29 40" src="https://user-images.githubusercontent.com/64733669/106392645-18404500-63f3-11eb-88a8-bdb2593a4f92.png">

Sometimes I get timeout.

It would be great to have feature to convert all videos to prepare them to play instantly.

Thank you.

**Comment by alexislefebvre** [comment]
See #703

**Comment by melyux** [comment]
I think #703 only applies to a one-time conversion, but is there an issue for transcoding upon import?
