### ISSUE TITLE
Make TensorFlow an optional module (Low Power Devices / Extensibility)

### ISSUE THREAD

**Issue by rkkoszewski** [photoprism/photoprism#99]
It would be great to have the TensorFlow integration in PhotoPrism as an optional module. On one side this would allow running PhotoPrism on low power devices like the Raspberry Pi to just organise and manually tag the photos, but also allow to use alternative tagging implementations as part of the import pipeline if modularized properly.

**Comment by lastzero** [comment]
It should also work on a Raspberry Pi - only problem is compilation and we need the C library for it (ideally in a statically linkable version). Without TensorFlow, we are pretty limited. Supporting multiple ML libraries is something I rather wouldn't implement for the start.

**Comment by lastzero** [comment]
Maybe we can implement this later (when there is time) with compiler flags.

**Comment by gedw99** [comment]
Hey ,

Just discovered this project. Like the use if the tidb binlog too. Really nice usage of some cutting edge stuff !
About TF - I was doing this days ago.  Its possible to to run TensorFlow on RaspberryPi by using TensorFLow Lite on RaspPi and get about a 10 to 20 times speed up. There is also a Tensor flow accelerator for RaspPI too that can get even faster. 

It used to be tough to convert the model from TensorFLow to TensorFlow Lite, but its now pretty straight foward. AKA Forward engineering.
i can dig it up and have a go at it.

**Comment by lastzero** [comment]
@gedw99 Sounds good! 👍 Does TensorFLow Lite also work on x86 or just ARM?

**Comment by gedw99** [comment]
Not sure  I think it runs on both and that's a really good question.
I need to check.
Also currently I think there is a reduced functionality set with TF Lite.

Their intention is to get to parity though.

So need to check out these aspects first in a test harness today.

This is a good high level sweep.
https://blog.hackster.io/benchmarking-tensorflow-and-tensorflow-lite-on-the-raspberry-pi-43f51b796796

**Comment by lastzero** [comment]
By the way, the issue that prevents us from using TensorFlow statically: https://github.com/bazelbuild/bazel/issues/1920

**Comment by samhodge** [comment]
You can build tensorflow statically

./tensorflow/contrib/makefile/build_all_linux.sh

**Comment by lastzero** [comment]
@samhodge Thank you! Is there also a way to build it statically for OS X? Probably by using the iOS script... won't have time to experiment this week... would be nice if somebody can test and confirm that this works... also to use it together with Go to create a single binary.

**Comment by samhodge** [comment]
the build linux works on OSX I have confirmed I will link to my issue here:

https://github.com/tensorflow/tensorflow/issues/28388

I have yet to check on iOS, but it is one of the featured use cases so that sounds good.

**Comment by samhodge** [comment]
Oh be carefull with building on OSX that the -jN with a high value for N automatically calculated can use a high amount of RAM, because forking many clang processes from XCode budgets for 100Mb per clang instance will cause your machine two swap and die if you have 24 threads and less than 24Gb of RAM. This is what caused me to think it wasn't working my machine locked up and the GUI wouldn't work but I could still ping the machine.

The resolve is to patch the final argument in the build_all_linux.sh to a more reasonable value for N in the -jN arguement to make.

Depends if you OSX box has 24 threads and less than 24Gb of RAM

Your milage may vary.

**Comment by lastzero** [comment]
Trying to build this on ARM64 incl GPU support right now... previous attempts failed because the job was killed... I'll try it again with

`env JOB_COUNT=1 ./tensorflow/contrib/makefile/build_all_linux.sh`

**Comment by lastzero** [comment]
@samhodge We can build libtensorflow.a using the old GCC 4.8 now, but still not compile a static Go binary with it, see https://github.com/tensorflow/tensorflow/issues/23649#issuecomment-504695877

Would be great to get some additional hints 👍

**Comment by graciousgrey** [comment]
@rkkoszewski does the config option solve your issue?
