### ISSUE TITLE
Metadata: Update and test go-exif

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#990]
Support for finding and seeking multiple EXIF blobs has been added, see:

[Canon EOS R5 missing metadata #53](https://github.com/dsoprea/go-exif/issues/53#issuecomment-770466986)

**Comment by dsoprea** [comment]
It's worth mentioning that this really only benefits unsupported formats. Supported formats tell you exactly where the EXIF blob is. If you're going to use this as a contingency, then just increment the counter and loop until you get an error, and maybe just mash all of the tags together when you're done.

**Comment by lastzero** [comment]
@dsoprea Just upgraded. Tests all pass, except one. GoPro camera model is gone:

![exif-error](https://user-images.githubusercontent.com/301686/107009023-c4d44b00-6794-11eb-8d51-e359dabc9af0.png)

Test file is here: https://github.com/photoprism/photoprism/blob/develop/internal/meta/testdata/gopro_hd2.jpg

Any idea why that is?

**Comment by lastzero** [comment]
Model is now missing according to exif-read-tool as well:

```
$ exif-read-tool -f gopro_hd2.jpg 
IFD-PATH=[IFD] ID=(0x0100) NAME=[ImageWidth] COUNT=(1) TYPE=[SHORT] VALUE=[[3840]]
IFD-PATH=[IFD] ID=(0x0101) NAME=[ImageLength] COUNT=(1) TYPE=[SHORT] VALUE=[[2880]]
IFD-PATH=[IFD] ID=(0x0102) NAME=[BitsPerSample] COUNT=(3) TYPE=[SHORT] VALUE=[[8 8 8]]
IFD-PATH=[IFD] ID=(0x0106) NAME=[PhotometricInterpretation] COUNT=(1) TYPE=[SHORT] VALUE=[[2]]
IFD-PATH=[IFD] ID=(0x010e) NAME=[ImageDescription] COUNT=(14) TYPE=[ASCII] VALUE=[DCIM\100GOPRO]
IFD-PATH=[IFD] ID=(0x010f) NAME=[Make] COUNT=(24) TYPE=[ASCII] VALUE=[GoPro]
IFD-PATH=[IFD] ID=(0x0112) NAME=[Orientation] COUNT=(1) TYPE=[SHORT] VALUE=[[1]]
IFD-PATH=[IFD] ID=(0x0115) NAME=[SamplesPerPixel] COUNT=(1) TYPE=[SHORT] VALUE=[[3]]
IFD-PATH=[IFD] ID=(0x011a) NAME=[XResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[[720000/10000]]
IFD-PATH=[IFD] ID=(0x011b) NAME=[YResolution] COUNT=(1) TYPE=[RATIONAL] VALUE=[[720000/10000]]
IFD-PATH=[IFD] ID=(0x0128) NAME=[ResolutionUnit] COUNT=(1) TYPE=[SHORT] VALUE=[[2]]
IFD-PATH=[IFD] ID=(0x0131) NAME=[Software] COUNT=(33) TYPE=[ASCII] VALUE=[Adobe Photoshop 21.0 (Macintosh)]
IFD-PATH=[IFD] ID=(0x0132) NAME=[DateTime] COUNT=(20) TYPE=[ASCII] VALUE=[2020:02:19 02:01:04]
IFD-PATH=[IFD] ID=(0x0213) NAME=[YCbCrPositioning] COUNT=(1) TYPE=[SHORT] VALUE=[[1]]
IFD-PATH=[IFD] ID=(0x8769) NAME=[ExifTag] COUNT=(1) TYPE=[LONG] VALUE=[[344]]
```

**Comment by dsoprea** [comment]
Closed, but did we resolve the above?
