### ISSUE TITLE
Upload: Add duplicates to selected albums as well

### ISSUE THREAD

**Issue by kardianos** [photoprism/photoprism#991]
As a user, I would like to add a photo set to an album, even if they are already in the system. Theoretically I could find them within the system and add them, but that can be tricky to find them if there is sufficient entropy.

In `internal/photoprism/import_worker.go`, we have a few loops and Ifs that import the logic. Of importance here is `imp.DestinationFilename` and `entity.AddPhotoToAlbums`. If DestinationFilename fails, no further processing is done. Which is what you normally would want. However, In this case, I would still like to add it to the photos.

Allowing this would require refactoring this function a fair amount and would probably be in two parts: (1) refactor (2) allow adding to album pre-existing photos.

I can make this change and add some unit tests probably, but I would want to get approval for the concept first.

**Comment by lastzero** [comment]
This has been released. You may test it using our latest Docker image.

**Comment by kardianos** [comment]
Works like a charm. Thanks!
