### ISSUE TITLE
places: api: request failed with status code 404

### ISSUE THREAD

**Issue by lanquarden** [photoprism/photoprism#994]
Hi,

I have just completed a google takeout import of ~180GB and have seen numerous errors like these:
```
places: api: request failed with status code 404 (photoprism places) (query cell id s2:0d6042f4deac)
api: request failed with status code 404 (photoprism places)
```
I'm running `photoprism/photoprism:20201122` in a k8s cluster.

This is an example of what happens around the errors:
![image](https://user-images.githubusercontent.com/446743/106659792-7dd13480-659f-11eb-8b1d-85e09e29d47f.png)

I have left, what remains in the import folder, intact if I need to check files/content

started import at around 9AM and finished around 9PM this is the distribution in time of the last 5000 occurrences (grepped `places: api:`):
![image](https://user-images.githubusercontent.com/446743/106660789-bb828d00-65a0-11eb-8223-e1a5cb53fa48.png)

**Comment by lastzero** [comment]
Service seems up and running:

https://places.photoprism.app/v1/location/19543538ea8c

**Comment by lastzero** [comment]
`photoprism/photoprism:20201122` is an old development version from November 2020... we've moved our places API to places.photoprism.app... is it possible for you to use our latest stable version?

**Comment by lanquarden** [comment]
updated to `photoprism/photoprism:20210128` and running import again on the remains of the import folder, sorry overlooked I was on a older version.

**Comment by lanquarden** [comment]
Imported remaining part without errors! Thanks, closing issue!
