### ISSUE TITLE
Docker Compose Get Started Page 404

### ISSUE THREAD

**Issue by the3dsandwich** [photoprism/photoprism#999]
Hi dev team,

I just discovered this app off some random YouTube recommendation and I want to try it out. If this is a duplicate question then I am very sorry.

I wanted to view the [Docker Compose Get Started Page](https://docs.photoprism.org/getting-started/docker-compose/) since it's recommended in a number of places, but it seems to be down. If it helps, here is a screenshot when accessing.

![image](https://user-images.githubusercontent.com/32169552/106913706-3f727b80-673f-11eb-930e-d6d8594a10b7.png)

Anyways please see if the page can be put back on, or let me know if it's temporary under maintenance. Thanks! Am eager to try it out on one of my spare computers!

**Comment by alexislefebvre** [comment]
Does it work now? https://dl.photoprism.org/docker/docker-compose.yml

Actually it's the same file than here: https://github.com/photoprism/photoprism/blob/develop/docker/examples/docker-compose.yml

**Comment by the3dsandwich** [comment]
Not really. I tried accessing it from a VPN, switched browsers (Chrome, Edge, even IE since I'm a horrible human being), still 404. Any other page that I visited on the site is working just fine, only docker compose is down for some reason.

I did find the source of it shortly after, maybe I should have posted this issue on the docs repo instead but if this issue gets seen here then I probably shouldn't bother moving it.

**Comment by lastzero** [comment]
Docs work for me - if anything that's an issue in the DigitalOcean CDN in your specific location:

![Screenshot 2021-02-04 at 16 44 25](https://user-images.githubusercontent.com/301686/106917126-4205ae80-6708-11eb-91e8-f4b39532c08b.png)

**Comment by the3dsandwich** [comment]
That's weird. But I'm able to get the raw .md file so it's ok for me for now. 

If there's a way that the docker page can be fixed for Taiwan (I'm here) then it'll be awesome. 

It's just weird that the docker page is the only page that's down. Other parts of the site are totally fine.
